### ISSUE TITLE
MSBooster error in LFQ-phospho workflow

### ISSUE THREAD

**Issue by Wenhhao** [Nesvilab/FragPipe#1002]
Hi FragPipe,

We tried a LFQ-phospho analysis with FragPipe but it just worked without ticking MSBooster. It seems MSBooster is incompatible with current workflow, and we don't know whether it's abnormal or has bad effects on the results.
![image](https://user-images.githubusercontent.com/67314119/218126349-08418788-97af-4f2b-9b7b-9900d9b2a8a0.png)

And here are some details,
- MS data: 16 ddaPASEF files
- Workflow: built-in LFQ-phospho workflow
- Software version: FragPipe v19.1, MSFragger v3.7, IonQuant v1.8.10 and Philosopher v4.8.1
- log file:
[log_2023-02-10_16-02-13.zip](https://github.com/Nesvilab/FragPipe/files/10708639/log_2023-02-10_16-02-13.zip)

**Comment by yangkl96** [comment]
Hello,

Could you please attach the file at `\\172.16.13.136\share\members\lilu\000_Project\007_RBM10\N20230207Hupp_TC60_phosphorylation_DDA_60min_FragPipe_rlt_20230210\msbooster_params.txt` here? 

Thanks,
Kevin

**Comment by Wenhhao** [comment]
> Hello,
> 
> Could you please attach the file at `\\172.16.13.136\share\members\lilu\000_Project\007_RBM10\N20230207Hupp_TC60_phosphorylation_DDA_60min_FragPipe_rlt_20230210\msbooster_params.txt` here?
> 
> Thanks, Kevin

Hello,

Thanks for your reply. I have uploaded the param file.
[msbooster_params.zip](https://github.com/Nesvilab/FragPipe/files/10713103/msbooster_params.zip)

**Comment by yangkl96** [comment]
Could you please delete `N20230207Hupp_RBM10_phosphorylation_DDA_60min_KTC1_PLVX_2_Slot1-23_1_18301.mzBIN` in the folder `\\172.16.13.136\share\members\lilu\000_Project\007_RBM10\N20230207Hupp_TC60_phosphorylation_DDA_60min`? And then try running the search with MSBooster again

**Comment by lbwfff** [comment]
Hi,

I was using fragpipe for LFQ analysis and had the same problem. This seems to be caused by the update of the version, because I did not encounter similar problems in the previous version of the software, the following is my log.

[log_2023-02-12_12-24-13.txt](https://github.com/Nesvilab/FragPipe/files/10715300/log_2023-02-12_12-24-13.txt)

Thanks,
LeeLee

**Comment by fcyu** [comment]
Hi LeeLee,

Yours are due to a different reason. You are using an old version of FragPipe with new version of MSFragger. Could you upgrade FragPipe and try again?

Best,

Fengchao

**Comment by lbwfff** [comment]
> Hi LeeLee,
> 
> Yours are due to a different reason. You are using an old version of FragPipe with new version of MSFragger. Could you upgrade FragPipe and try again?
> 
> Best,
> 
> Fengchao

Yes, for me it is indeed a fragpipe version problem, thank you Fengchao.
