### ISSUE TITLE
Translational fidelity analysis with FragPipe

### ISSUE THREAD

**Issue by bioyuyang** [Nesvilab/FragPipe#1006]
- Describe the issue or question:
Dear FragPipe team,

I am trying to analyze Translational fidelity in two conditions with LFQ MS data. I ran the FragPipe with default parameters and got the peptides. Then, I aligned the peptide sequences to the references and used the mismatch level between petite and reference to evaluate the fidelity. However, almost all the peptides align 100% with the references. I was wondering if there are any specific parameters that allow mismatch during peptide search or do you have any suggestions about the Translational fidelity analysis with FragPipe? 

Thank you so much for your time and help!

Best,
Yuyang

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Yuyang,

All result peptides are from the input fasta file. So, if the input is the reference proteome, only reference proteome peptides will be reported. If you want to look for other peptides, you need to include them in the fasta file or trying open/mass-offset searches which is very tricky.

Best,

Fengchao

**Comment by bioyuyang** [comment]
Thank you so much for your quick response. That explains perfectly why I got a 100% match.  It seems more doable to include those peptides with translational errors in the fasta, but it needs to include a lot of artificial mistranslated peptides. Do you have any ideas about it? Your suggestions are highly appreciated.

**Comment by fcyu** [comment]
I don't have any good suggestion.

Best,

Fengchao
