### ISSUE TITLE
FragPipe stuck at main search

### ISSUE THREAD

**Issue by pisistrato** [Nesvilab/FragPipe#1007]
Hi,

I am trying to process a simple dataset (2 files) consisting of TMT16 K-acetylome. There is no error, but the search get stuck right after the main search step starts.
I do not think I made any mistake in the settings (I successfully processed other TMT16 K-xtylomes datasets).

I am happy to share the data if needed.

[log_2023-02-15_15-57-29.txt](https://github.com/Nesvilab/FragPipe/files/10744325/log_2023-02-15_15-57-29.txt)

**Comment by fcyu** [comment]
I can't find anything wrong. Can you check if MSFragger is running? If yes, maybe give it more time?

Thanks,

Fengchao

**Comment by pisistrato** [comment]
Sorry, problem solve. There was a pepindex that was somehow hanging from a previous failed search.
It seems to be working fine after deleting this file.
