### ISSUE TITLE
Analysis of Bruker timsTOF flex data

### ISSUE THREAD

**Issue by eriktjansson** [Nesvilab/FragPipe#1012]
Hello,

I have acquired DDA data with a timsTOF flex using MALDI. However, when I try to load the data into FragPipe I get an error. I have marked the data as Regular MS in the setup of FragPipe but then I get the following error in the log:
```
Failed in checking 20230219_Hb_rapid_peptic_digest_lyophilized_CID_highmass_60V_0_N7_000001.d. Will ignore it.
Not a valid pathDir for Bruker data directory
There are corrupted files. Please remove those files and re-start the task.
```
I do not have a reason to believe these files are corrupted since they open well in the Bruker analysis software for spectra viewing.
Should I try to circumvent this file format issue by exporting the files to mzML first? I know PASEF data is supposed to work better as raw format in FragPipe, but PASEF is not yet supported for MALDI mode on the timsTOF flex, so for the time being we must acquire the data with regular DDA.

Thanks,
Erik

[log_2023-02-20_17-49-45.txt](https://github.com/Nesvilab/FragPipe/files/10786300/log_2023-02-20_17-49-45.txt)

**Comment by fcyu** [comment]
Hi Erik,

FragPipe supports the .d with PASEF. Without PASEF, you need to convert it to mzML using msconvert.

Best,

Fengchao
