### ISSUE TITLE
Fragpipe failing when opening proteinprophet

### ISSUE THREAD

**Issue by justmpm** [Nesvilab/FragPipe#1015]
Hi,
I have  a problem with LFQ-MBR, at the protein prophet step and fragpipe exits.  It is strange because, it happens even with files that I have analyzed before.  This happens with the latest
versions of fragpipe, philosopher and Ionquant.  The only thing I can think that changed, is an
update to jre, but I get the same error if I uninstall jre and then run everything from an FragPipe-jre-19.1 install.

Below is the error code from Fragpipe, and I attached the output folder which contains a full log.

Thanks!
Mike
[new191tests02.zip](https://github.com/Nesvilab/FragPipe/files/10813406/new191tests02.zip)

ProteinProphet [Work dir: C:\GTout\new191tests02]
C:\philosopher_v4.8.1_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined C:\GTout\new191tests02\filelist_proteinprophet.txt
INFO[13:06:01] Executing ProteinProphet  v4.8.1             
panic: Cannot execute program. open NUL: The system cannot find the file specified.

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc00001e690, 0x4c}, {0xf40dbc, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ExecutingBinary({0x10b9f20?, 0xc000124840?}, {0xf40dbc, 0x5})
	/workspace/philosopher/lib/msg/msg.go:209 +0x6e
philosopher/lib/ext/proteinprophet.ProteinProphet.Execute({{0xc00006e2a0, 0x59}, {0xc00006e300, 0x5a}, {0xc00006e360, 0x5a}, {0xc00006e2a0, 0x59}, {0xc00006e300, 0x5a}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:105 +0x765
philosopher/lib/ext/proteinprophet.Run({{0xc00001c7b0, 0x24}, {0xc0000249a8, 0x16}, {0xc00001e6e0, 0x47}, {0xc00001c7e0, 0x25}, {0xc0000227c0, 0x1c}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:62 +0x3b3
philosopher/cmd.glob..func14(0x2b3b740?, {0xc00006c140, 0x1, 0x5})
	/workspace/philosopher/cmd/proproph.go:26 +0xb4
github.com/spf13/cobra.(*Command).execute(0x2b3b740, {0xc00006c0f0, 0x5, 0x5})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2b3c2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[13:06:01] Cannot execute program. open NUL: The system cannot find the file specified. 
Process 'ProteinProphet' finished, exit code: 2
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by justmpm** [comment]
Hi,
Thanks for your help.  The data is generated on another computer, converted from Agilent .d files to mzML with msconvert and then the files are moved to the computer running fragpipe.  I also downloaded some thermo .Raw files and tried them as .raw or converted to mzML with msconvert and got the same errors.  I also tried reconverting the data directly on the fragpipe computer and this also resulted in the same errors.  As far as I can tell filelist_proteinprophet.txt and the files it is pointing to are in the right places.  There is currently 1.44 TB free space on this HD drive I am using.

I also deleted everything in C:\Windows\temp and everything in C:\Users\mascot\AppData\Local\Temp, restarted the computer, and still have the same errors.  I attached the outputs from a run with the  .raw data and the contents of C:\Users\mascot\AppData\Local\Temp\fragpipe


Thanks again!

Mike
[fragpipe.zip](https://github.com/Nesvilab/FragPipe/files/10822988/fragpipe.zip)
[tests02.zip](https://github.com/Nesvilab/FragPipe/files/10822994/tests02.zip)

**Comment by fcgportal** [comment]
Same issues here. Is there any solution? Thanks

**Comment by prvst** [comment]
Could you please try the [latest release candidate](https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0) version, and let me know what message do you see?

**Comment by justmpm** [comment]
Hi,
Here is the error:  
Percolator: Delete temp
java -cp C:\FragPipe-19.1\fragpipe\lib\fragpipe-19.1.jar com.github.chhh.utils.FileDelete C:\GTmsconvOUT\tests14\1_1\Sample1_percolator_decoy_psms.tsv
Process 'Percolator: Delete temp' finished, exit code: 0
ProteinProphet [Work dir: C:\GTmsconvOUT\tests14]
C:\philosopher\philosopher-v5.0.0-RC8.exe proteinprophet --maxppmdiff 2000000 --output combined C:\GTmsconvOUT\tests14\filelist_proteinprophet.txt
INFO[18:14:06] Executing ProteinProphet  v5.0.0             
ERRO[18:14:07] Cannot execute program. open NUL: The system cannot find the file specified. 
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

log is attached, let me know if you need something else.

Thanks for your help!
[log_2023-02-27_18-14-07.txt](https://github.com/Nesvilab/FragPipe/files/10842258/log_2023-02-27_18-14-07.txt)

**Comment by fcyu** [comment]
@prvst @justmpm Any update? Or should I close this one?

Thanks,

Fengchao
