### ISSUE TITLE
extracting the unidentified spectra

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#1016]
Dear FragPipe team, 
I am wondering if it is possible to extract the unidentified spectra from each of the raw files (label-free) and export them as a single file . The idea is, we would like to perform a "cascade search" where initially we identify the most probable PSMs . Subsequently, we would like to do second search for the remainder of the unassigned peaks using a complimentary algorithm (e.g. de novo). 
Thanks

**Comment by fcyu** [comment]
Thanks for your suggestion.

Currently, we don't have this feature. Maybe implement it in the future.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @fazeliniah ,

We have added this feature. Please contact yufe AT umich.edu if you want to test the pre-released version.

Best,

Fengchao
