### ISSUE TITLE
Fragpipe-PDV Failure to see spectra

### ISSUE THREAD

**Issue by jcharkow** [Nesvilab/FragPipe#1017]
- Describe the issue or question:
When trying to visualize with Fragpipe-PDV, the spectra area is blank no matter what is selected. This is using DDA timsTOF data. Fragpipe analysis seems to run fine (although ionquant does not run I don't think this should affect things). Clicking on the checkbox in the PSMs section leads to continuous loading and then nothing occurs. 

![image](https://user-images.githubusercontent.com/47336288/221264505-74439b41-cb24-45f9-8518-35bb9258fa2c.png)

- Upload your log file
[log_2023-02-24_14-08-43.txt](https://github.com/Nesvilab/FragPipe/files/10828033/log_2023-02-24_14-08-43.txt)

**Comment by fcyu** [comment]
I assign Kai to take a look.

On a separate note, it seems that there was not enough memory to finish the label-free quantification:
```shell
2023-02-24 14:05:01 [INFO] - ...20%...40%...60%...Not enough memory allocated to IonQuant.
For ddaPASEF data with 2h gradients, IonQuant normally requires at least 20 GB memory.Process 'IonQuant' finished, exit code: 1
```

Best,

Fengchao

**Comment by jcharkow** [comment]
Thanks for the fast reply! Yes I'll try rerunning with more memory

**Comment by KaiLiCn** [comment]
Can you check if there is a `.mzml` file has the same name with the `.d` file in your `/home/joshua/Data/Meier_2018/` folder? 

Best,
Kai

**Comment by jcharkow** [comment]
Almost the same name. I have a `20180819_TIMS2_12-2_AnBr_SA_200ng_HeLa_50cm_120min_100ms_11CT_1_A1_01_2767_uncalibrated.mzML` file present there. (note the uncalibrated extension)

**Comment by KaiLiCn** [comment]
Could you update your FP-PDV package using this version? https://github.com/Nesvilab/FragPipe-PDV/releases/download/V1.1.0/FP-PDV-1.1.0.jar

Please follow the README here: https://github.com/Nesvilab/FragPipe-PDV 

If it still has issues, please let me know.

**Comment by jcharkow** [comment]
Unfortunately even after updating it still seems to be an issue.  I don't know if this helps but I can select checkmarks with the protein level but I cannot select check marks at the .psm level. I've tried rerunning fragpipe but it still seems to fail. 

I don't know if it is relevant for java applications but I am running Ubuntu 22.04.2 LTS

**Comment by KaiLiCn** [comment]
Sorry about that. Could you please share your result folder and raw file (including mzml files) with me? If it's ok, you can upload them here: https://www.dropbox.com/request/Z1lTfGryzdoIqiKJyump . I will take a close test once I receive it.

Best,
Kai

**Comment by KaiLiCn** [comment]
Hi there,

I tried to open your data on multiple computers, including Ubuntu and Windows. It works well crossing different OS platforms on my side.

So now I have two recommendations:

1. You can try to visualize your data on a different computer. You can select "Output dir" in "Run" panel and click "Open FragPipe-PDV viewer" directly without re-running it. But before that, please change the spectra raw file path in "fragpipe-files.fp-manifest" file which locates in your result folder.
2. Please run FP-PDV directly by command line : `java -jar FP-PDV-1.1.0.jar _YOUR_RESULT_FOLDER_ _THREAD_NUMBERS_` , e.g. `java -jar FP-PDV-1.1.0.jar /mnt/d/FP-PDV/issues/issue_1017/output/ 6`. Here is the link to download the runnable version https://www.dropbox.com/s/25xjyleqqmzr1am/FP-PDV-1.1.0.zip?dl=0 . If there is still an issue to visualize your data, there should be some output messages on the console.

Please feel free to let me know if this cannot fix your issues.
Kai
