### ISSUE TITLE
Print decoys in validation tab

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1018]
Hi,,

I have installed FragPIpe 19.1. The FDR filter and report is greyed out. I need to select "print decoys" to import search data to Scaffold. Is there is a reason this is greyed out?

Thanks,

Matt Foster

**Comment by fcyu** [comment]
Hi Matt,

Are you using the latest Philosopher?

Best,

Fengchao

**Comment by mwfoster** [comment]
That was the issue, thanks. I didn’t see it prompt me to update. Thanks, Matt

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao
