### ISSUE TITLE
bug in multi-report

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/FragPipe#102]
When using multi-report option (Report tab), the command has extra tags from the filter line. --sequential and --mapmods and --prot 0.01 should not be there. The program crashes

C:\Users\nesvi\Desktop\FragPipe\philosopher_windows_amd64.exe abacus --reprint --sequential --razor --mapmods --prot 0.01 --tag rev_ --protein D:\MCP_2018\Results_4Exp\interact.prot.xml --peptide D:\MCP_2018\Results_4Exp\interact.pep.xml R4 R2 R1 R3

**Comment by chhh** [comment]
fixed in 9.1
