### ISSUE TITLE
Running large number of files

### ISSUE THREAD

**Issue by SharmaGautam1** [Nesvilab/FragPipe#1021]
I have one query: Can we run around 150 DDA files simultaneously in fragpipe? If yes, then what should be the requirement for the PC in terms of RAM and other configurations?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
150 DDA files should have no issue at all. Taking our CPTAC project for example, we normally run ~500 DDA or even more files together.

As to the RAM requirement, it depends on your settings. For the normal tryptic search without many variable modifications, ~32 GB **free** memory is enough. With nonspecific digestion or many variable modifications, 64 to 128 GB **free** memory should be enough. There is no big requirement for CPU.

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Thanks Fengchao for the clarification.

---
Best Regards
Gautam Sharma
