### ISSUE TITLE
Running DIA-NN without library fails

### ISSUE THREAD

**Issue by chris-discopharma** [Nesvilab/FragPipe#1022]
Hi FragPipe team, 

We have quite a lot of infrastructure set up to automate FragPipe analysis (for both DIA and DDA datasets). These rely on using FragPipe in headless mode. For ultimate flexibility, we would also like an option to run DIA-NN with the same infrastructure/scripts. In conversation recently with @anesvi he suggested we could untick all the other options, and in theory pipe DIA files directly to DIA-NN to run it in library free mode (as per the default with standalone DIA-NN software).

However, when I tried this I got an error. This seems to be because the default FragPipe command uses the "--lib" flag, meaning DIAN-NN in FragPipe always expects a library. This means execution always fails.

Here is the FragPipe command from the logs:
<path_to_FragPipe>/fragpipe/tools/diann/1.8.1/linux/diann-1.8.1 --lib --threads 3 --verbose 1 --out diann-output.tsv --qvalue 0.01 --matrix-spec-q 0.01 --matrices --no-prot-inf --smart-profiling --no-quant-files --peak-center --no-ifs-removal --cfg <path_to_filelist>/filelist_diann.txt

A couple of other things I tried:
- Generating a workflow file, running headless with the parameter deleted
- Generating a workflow file, running headless with the parameter set to "false" or NULL

However in all cases the "--lib" parameter persists, meaning DIA-NN always expects a library. 

Is it possible to modify the way FragPipe executes DIA-NN, such that the "--lib" is left out by default, and only populated in cases where a library is required? This would enable us to run DIA-NN standalone within the FragPipe wrapper, and therefore makes our FragPipe-centric workflow setup even more versatile. 

Thanks for your help!

**Comment by fcyu** [comment]
Yes, we assume there is always a library available. Let me discuss internally to decide if we want to support the DIA-NN library-free mode, which is exactly what DIA-NN standalone version does.

Best,

Fengchao

**Comment by chris-discopharma** [comment]
Hi Fengchao,
Thanks a lot for writing back! I found a solution - if the library is specified as "" in the FragPipe parameters, then execution no longer fails. It seems that with this and the "custom command line" options, the functionality we are looking for already exists. Based on this, I think this issue can be closed.
All the best, 
Chris

**Comment by fcyu** [comment]
Hi Chris,

Glad that you found the solution. I didn't know that DIA-NN can take empty input for library.

Best,

Fengchao

**Comment by chris-discopharma** [comment]
Yes I was also surprised. I found this by simply running the standalone GUI with default settings and seeing what parameters were there. This is also the default behaviour of the standalone software!
