### ISSUE TITLE
PTMProphet cannot read scan in output directory

### ISSUE THREAD

**Issue by missenfai** [Nesvilab/FragPipe#1023]
- Describe the issue or question: 
I found error while running in TMT-10 workflow due to PTMProphet [ERROR:] cannot read scan in data file C:\Intel\split_peptide_index_tempdir\20bCPTAC_CCRCC_P_JHU_20180531_LUMOS_f10_calibrated.mzML exiting.
I have tried used another samples but it remained error.

- Upload your log file
[log_2023-03-01_00-09-03.txt](https://github.com/Nesvilab/FragPipe/files/10857003/log_2023-03-01_00-09-03.txt)

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/994 The fix will be available in the next release. You can either use the pre-released version or disable mass calibration for now.

Best,

Fengchao
