### ISSUE TITLE
DIA-NN and .raw-.mzML peak picking

### ISSUE THREAD

**Issue by SharmaGautam1** [Nesvilab/FragPipe#1025]
Hi,
I tried converting the .raw files into the .mzML using the MSconvertGUI and as directed in "https://fragpipe.nesvilab.org/docs/tutorial_convert.html" to run it in FragPipe

On loading the files to the FragPipe, it shows that ".mzML has non-centroid scans. Please re-convert it with peakPeaking (https://fragpipe.nesvilab.org/docs/tutorial_convert.html).
Process 'CheckCentroid' finished, exit code: 1"
I am attaching the log file. Please look into it and let me know the solution.
[log_2023-03-02_20-35-31.txt](https://github.com/Nesvilab/FragPipe/files/10872700/log_2023-03-02_20-35-31.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Could you send me the screenshot of your msconvert or your mzML file? 

Thanks,

Fengchao

**Comment by SharmaGautam1** [comment]
Here are the screenshots of MSConvert and the mzML file.

**Comment by fcyu** [comment]
GitHub truncated your message. Can you go to https://github.com/Nesvilab/FragPipe/issues/1025 and up load it there?

Thanks,

Fengchao

**Comment by SharmaGautam1** [comment]
Please find it here.

![MSConvert](https://user-images.githubusercontent.com/120696110/222482263-26ce780d-bc7b-427a-8910-861c5661ba8f.JPG)
![mzML_file](https://user-images.githubusercontent.com/120696110/222482271-704e2855-c036-4b8b-aa63-316176d05059.JPG)

**Comment by fcyu** [comment]
You did not added the peak picking filter. Please follow the tutorial https://fragpipe.nesvilab.org/docs/tutorial_convert.html to reconvert your data.

Also please note that the peak picking filter MUST BE at the first row.

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Ok, I got your point. Thanks for that.
One more thing, I have used overlapping window in Oritrap Fusion, so in
MSConvert, we have to use demultiplexing, and what should be the mass
error? Is 10 ppm default setting good to go?
Please confirm.

---
Best Regards
Gautam Sharma

**Comment by fcyu** [comment]
Yes, 10 ppm is good. 

Just in case, does your overlapping windows have half of the width overlapped (staggered)? Overlapping at the edge (e.g., 2 Th out of 20 Th) does not count as "overlapping isolation window".

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
From a scan range of 400–1000, I used 1 overlapping window, keeping
the isolation window at 16. Will it still not be considered as overlapping?

Best,
Gautam

**Comment by fcyu** [comment]
It is not the "overlapping"/staggering windows. 

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Thanks Fengchao, for the clarification.

---
Best Regards
Gautam Sharma

**Comment by LiSheng96** [comment]
> It is not the "overlapping"/staggering windows.
> 
> Best,
> 
> Fengchao

Hi Fengchao,

I used 1m/z overlapping window, 3m/z isolation window. 
Will it be considered as overlapping/staggered windows?

Thakn you!

Best,
Li

**Comment by fcyu** [comment]
Hi Li,

I don't think is should be considered as staggered windows. Staggered windows requires 50% overlapping.

Best,

Fengchao
