### ISSUE TITLE
Process 'PhilosopherFilter' finished, exit code: 2

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/FragPipe#1027]
Hello,

We were running fragpipe 19 on a set of 143 LFQ samples, it seemed to be going well until we received the following error: 
Process 'PhilosopherFilter' finished, exit code: 2

Any advice you can provide would be greatly appreciated. I attached the log file, please let me know if I can provide any additional information

All the best,

Jason
[log_2023-03-04_14-04-30.txt](https://github.com/Nesvilab/FragPipe/files/10889441/log_2023-03-04_14-04-30.txt)

**Comment by prvst** [comment]
can you try increasing the protein FDR threshold ?

**Comment by jmcalist** [comment]
Thank you so much! I have ran a few different iterations. 
I changed the prot FDR at the bottom of the Validation tab from the default 0.01 to 0.05. When I ran this with MBR it still crashed, but with without MBR it did finish. 
With prot FDR at 0.01 and without FDR it still crashed. 
I can provide the logs for these runs if you are interested. For now, we are happy having results at FDR 0.05 and no MBR, although we would prefer FDR 0.01 with MBR
If you have any other thoughts or things for us to try I would certainly be interested

Thanks as always for all your assistance!

**Comment by fcyu** [comment]
Hi @jmcalist .

I guess you mixed different issues here. Can you send all log files?

Best,

Fengchao

**Comment by jmcalist** [comment]
I can send the log files, I do not have access at the moment, but will access the computer remotely when I can

Just to confirm, for the previous reply of 'can you try increasing the protein FDR threshold', does this refer to changing --prot 0.01 to --prot 0.05 in the FDR Filter and Report section on the validation tab?

Thanks!

**Comment by jmcalist** [comment]
Here are the log files for three runs: 
FDR 0.05, MBR On: Crashed
FDR 0.05, MBR Off: Completed
FDR 0.01, MBR Off: Crashed

FDR 0.01, MBR On: Crashed (log file from original message in the thread above: log_2023-03-04_14-04-30.txt)

Please let me know if I can provide any additional information

Thanks so much!

[log_2023-03-08_22-20-42_(FDR_0_05_MBR_On).txt](https://github.com/Nesvilab/FragPipe/files/10946213/log_2023-03-08_22-20-42_.FDR_0_05_MBR_On.txt)

[log_2023-03-08_14-08-42_(FDR_0_05_MBR_Off).txt](https://github.com/Nesvilab/FragPipe/files/10946215/log_2023-03-08_14-08-42_.FDR_0_05_MBR_Off.txt)

[log_2023-03-08_19-24-54_(FDR_0_01_MBR_Off).txt](https://github.com/Nesvilab/FragPipe/files/10946216/log_2023-03-08_19-24-54_.FDR_0_01_MBR_Off.txt)

**Comment by fcyu** [comment]
Thanks for your log files. It looks like none of your jobs finished without any error. MSFragger failed with the Thermo raw file parser's errors like
```shell
[pool-1-thread-7] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Did not get port information from server output within timeout.
[pool-573-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Error while scanning stream
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.scanStreamForPattern(ThermoGrpcServerProcess.java:319)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.lambda$start$7(ThermoGrpcServerProcess.java:261)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[pool-573-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - 
```

Only `FDR 0.05, MBR Off: Completed` "completed" but there are still errors like above. After revising the log in your first message, there are also errors about the Thermo raw file parser. The cause of the crashes is not about MBR or protein FDR. You need to troubleshoot your computer to load the raw file successfully.

Best,

Fengchao

**Comment by jmcalist** [comment]
Thanks so much, I have been loading .raw files, but can also convert to mzML. Is it better to convert to mzML first?

Thanks again!

**Comment by fcyu** [comment]
Converting them to mzML would make the running faster and more robust. But you need to make sure that you used the correct settings in the conversion. Here is the tutorial in case you need one: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by shenghao003** [comment]
Hello,When I use the sequence downloaded by NCBI, I will also encounter similar problems. Figure 1 is the error prompt, and Figure 2 is the original sequence I downloaded. I am afraid that it contains special characters, so I changed the ID and description to figure 3, but the same error is reported.
I saw in the column "how to prepare a protein database" that it supports generic format. Can you give me some suggestions? 
![image](https://github.com/user-attachments/assets/b073287e-931b-448b-adb2-32d2ba2de42c)
![image](https://github.com/user-attachments/assets/92320cdb-1ef8-4b60-b5e7-f5055f098c78)
![image](https://github.com/user-attachments/assets/3b64b6a5-a06f-4e34-8a12-1f23db795c0e)

Thanks.
