### ISSUE TITLE
Ionquant [ERROR] - There is not enough space on the disk

### ISSUE THREAD

**Issue by Maithy15** [Nesvilab/FragPipe#1028]
Dear Fragpipe Team,

I was searching 80 TimsTof DDA files and ionquant errored out sazing that there is not enough space. There is 430 GB free space available. I have attached the complete log here. Should I start all over again?

- Upload your log file
[log_2023-03-04_01-02-24.zip](https://github.com/Nesvilab/FragPipe/files/10891563/log_2023-03-04_01-02-24.zip)

Thanks
Maithy

**Comment by fcyu** [comment]
You need to find a computer with more spaces and try again. Here (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#:~:text=Disk%20space%20requirements%20for%20quantification%20of%20timsTOF%20data%20are%20greater) is some suggestion about the space requirement.

Best,

Fengchao
