### ISSUE TITLE
Stack on Labile-ADP-ribosylation search

### ISSUE THREAD

**Issue by camoin** [Nesvilab/FragPipe#1030]
Hello Developpers,

I'm trying to do a Labile_ADP-ribosylation search on two mzML files. The search is stacked after a while. Can anyone tell me how to solve this problem? Here below the last part of the log file and the full log file attached.

Best

Luc

INFO: Processing standard MixtureModel ... 
Initialising statistical models ...
Iterations: .........10.........20....WARNING: Mixture model quality test failed for charge (1+).
.
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 26 iterations
INFO[15:24:29] Done                                         
Process 'PeptideProphet' finished, exit code: 0
Rewrite pepxml [Work dir: F:\EZH2\output3]
C:\Users\camoin\Desktop\FragPipe-jre-18.0\jre\bin\java.exe -cp C:\Users\camoin\Desktop\FragPipe-jre-18.0\lib/* com.dmtavt.fragpipe.util.RewritePepxml F:\EZH2\output3\interact.pep.xml P:\CRCM_Data\Duprey_Estelle\230204_PoplineauM_EZH2_PTM_Test_Qex_DDA\EZH2.mzML P:\CRCM_Data\Duprey_Estelle\230204_PoplineauM_EZH2_PTM_Test_Qex_DDA\EZH2_20230208183652_runcourt_6microlitres.mzML
Fixing pepxml: F:\EZH2\output3\interact.pep.xml
Writing output to: F:\EZH2\output3\interact.pep.xml13093641498055011741.temp-rewrite
Deleting file: F:\EZH2\output3\interact.pep.xml
Moving rewritten file to original location: [F:\EZH2\output3\interact.pep.xml13093641498055011741.temp-rewrite] -> [F:\EZH2\output3\interact.pep.xml]
Process 'Rewrite pepxml' finished, exit code: 0
PtmProphet [Work dir: F:\EZH2\output3]
C:\Users\camoin\Desktop\philosopher_v4.8.1_windows_amd64\philosopher.exe ptmprophet --keepold --static --fragppmtol 20 --em 1 --mods SKREDTY:541.06111 --minprob 0.5 --maxthreads 11 interact.pep.xml
INFO[15:24:36] Executing PTMProphet  v4.8.1                 
[INFO:] Using statically set 20 PPM tolerance ... 
[INFO:] Writing file interact.pep.xml.tmp.a04652 ...

[INFO:] Creating 11 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
​
[INFO:] processed 1000/1006 spectrum_queries		 
[INFO:] done ... 
[INFO:] Computing EM Models ... 
[INFO:] Iterating PTM Model: .done
[INFO:] done ... 
[INFO:] done ... 

[INFO:] Creating 11 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...
[INFO:] Reading file interact.pep.xml ...

**Comment by danielgeiszler** [comment]
Can you please attach your whole log? It looks like it isn't here.
