### ISSUE TITLE
Unique spectral counts missing in combined_prot.tsv (v19.1)

### ISSUE THREAD

**Issue by varjolab** [Nesvilab/FragPipe#1032]
Hi!

Lately we noticed that the column "unique spectral count" is no longer visible in our combined_prot.tsv file, although using the same workflow as previously (and same V19.1 of FragPipe). Is it still there in the individual protein.tsv files. As we are analysing huge data sets having that column in the combined_prot file has been a great advantage. Is there a way to get it back?

Also, is there a reason why workflow "SpecLib" is no longer part of the workflows in v19.1?

Best,
Salla

[log_2023-03-09_15-46-22.zip](https://github.com/Nesvilab/FragPipe/files/10939635/log_2023-03-09_15-46-22.zip)

**Comment by fcyu** [comment]
Hi Salla,

I think the `Combined Unique Spectral Count` column is generated by IonQuant not by Philosopher. So, it is only available when you use IonQuant for LFQ-MBR.

> Also, is there a reason why workflow "SpecLib" is no longer part of the workflows in v19.1?

We extended it to two workflows `DIA_SpecLib_Quant` and `DIA_DIA-Umpire_SpecLib_Quant`.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, please tell us what workflow you run to get combined_protein.tsv. Was IonQuant run?
