### ISSUE TITLE
Custom fasta database result in Philosopher: panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by yannic-chen** [Nesvilab/FragPipe#1033]
Dear FragPipe team,

I created a custom fasta database with gene name as header. Due to the nature of the analysis, I have the same gene name for multiple sequences. Therefore I added a number suffix ("_#") after each gene name to make them unique. This is so that when adding decoys using the inbuild function my database does not get trimmed. But I still get the error message:

> java.lang.IllegalStateException: Something happened during database update
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException: Process returned non zero value
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
> 	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
> 	... 1 more

Next I ran the Nonspecific-HLA workflow (IM-MS timsTOF data), however I get the following error:

> PhilosopherDbAnnotate [Work dir: D:\data\2022-145\FragPipe\20230310_AtoG_only]
> C:\FragPipe_v18.0\fragpipe\tools\philosopher_v4.2.2_windows_amd64\philosopher.exe database --annotate D:\data\2022-145\2023-03-10-decoys-hg19_lenient_extended_AtoG_long_custom.fasta.fas --prefix rev_
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]:
> philosopher/lib/dat.ProcessTair(0xc0004a7be1, 0x11, 0xc0005fef40, 0x32, 0xc000018138, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
> 	/workspace/philosopher/lib/dat/db.go:472 +0x4ba
> philosopher/lib/dat.(*Base).ProcessDB(0xc0001a0000, 0xc0000620c0, 0x53, 0xc000018138, 0x4)
> 	/workspace/philosopher/lib/dat/dat.go:157 +0x465
> philosopher/lib/dat.Run(0xc00001a9f0, 0x24, 0xc00001aa20, 0x2c, 0xc000022460, 0x48, 0xc00001e440, 0x3b, 0xc00001e480, 0x32, ...)
> 	/workspace/philosopher/lib/dat/dat.go:64 +0xb85
> philosopher/cmd.glob..func4(0x1f0b5a0, 0xc000138f00, 0x0, 0x4)
> 	/workspace/philosopher/cmd/database.go:23 +0xc5
> github.com/spf13/cobra.(*Command).execute(0x1f0b5a0, 0xc000138ec0, 0x4, 0x4, 0x1f0b5a0, 0xc000138ec0)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1f0d7c0, 0x200b60, 0xc00008ff70, 0xc00008ff68)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
> philosopher/cmd.Execute()
> 	/workspace/philosopher/cmd/root.go:35 +0x34
> main.main()
> 	/workspace/philosopher/main.go:25 +0x85
> INFO[12:56:18] Executing Database  v4.2.2                   
> INFO[12:56:18] Annotating the database                      
> Process 'PhilosopherDbAnnotate' finished, exit code: 2
> Process returned non-zero exit code, stopping
> 
> ~~~~~~~~~~~~~~~~~~~~
> Cancelling 4 remaining tasks

My fasta file has the following format:

```
>TSC22D1_1
AAAAAADISARKMAHPAMFPRRGSGGGSASALNAAGTGVGSNATSSEDFPP
>CDK13_2
AAAAAASSSCFSPGPPLEVKRLARGRRRAGGRQKRRRGPRAGQEAEKRRVF
>MAZ_3
AAAAATAVVAPTSTVAVAPVASALERKTKSKGPYICALCAKEFKNGYNLRR
>ARID1B_4
AAAAGAPGSMDPLQNSHEGYPNSQCDHYPGYSRPGAGGGGGGGGGGGGGSG
>ARID1B_5
AAAAGAPGSMDPLQNSHEGYPNSQCSHYPGYSRPGAGGGGGGGGGGGGGSG
>ANKS3_6
AAAAGHEIIVQYFLNHSPSVAQAGVRQLTAISASRVEAILLPQPPE
>ZNF586_7
AAAALRAPAQSSVTFEDVAVNFSLEGWSLLNEAQGCLYHDVMLETLTLISS
>PIPSL_8
AAAASAAEAGIATTGTEDSDDALLKVTISQQEFGHTGLPDLSSMTEEEKIV
>ADNP_9
AAAATGPPPGNTSSTQKWKICTICNGLFPENVYSVHFEKEHKAEKVPAVAN
>ZNF814_10
AAAATLRLSAQESHSVIQTGVQWRDRSSPQPPPTGDILIQGTVTFEDVAVN
>ZNF814_11
AAAATLRLSAQGTVTFEDVAVNFTWGEWNLLSEAQRCLYRDVTLENLALIS
>PPP2R1A_12
AAADGDDSLYPIAVLIDELRNEDVQGRGFTMLARLGRELLTSSDPPASASQ
>CCDC85A_13
AAAESCSPAPAGSSAAPPAPVEDLSEVSDEELLQWSKEELIRSLRRAEAEK
>CCDC85A_14
AAAESCSPAPAGSSAAPPAPVEDLSRVSDEELLQWSKEELIRSLRRAEAEK
>GLT8D1_15
AAAFSEDCDSASTKVVIRGAGNQYNCIGYLDYKKERIRKLSMKASTCSFNP
>ANKS3_16
AAAGHEIIVQYFLNHSPSVAQAGVQRLTAISASRVEAILLPQPPE
```

I use FragPipe v18.0 with Philosopher v4.2.2 on AMD

I also wanted to ask if the header allows transcript ID (instead of gene name) from multiple databases (ucsc, ncbi and ensembl) in a single file.

Many thanks,
Yannic

**Comment by yannic-chen** [comment]
I also wanted to add that, I had a few entries in the database where the sequence is mapped to multiple genes. I separated them, so that there are some entries with different gene name (header), but same sequence.

**Comment by anesvi** [comment]
First, please upgrade the the latest version of the tools. Second, unfortunately, there are restrictions on the headers. Mixing different databases is likely to cerate an error. Here is some info: https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database#header-formatting
This will be hard for us to fix. Your best strategy will be to create entries in a generic format >protein1  >protein2 etc and just use external tools later to map proteins to accession numbers in various databases and to gene names

**Comment by prvst** [comment]
Hi @yannic-chen. There is no problem in mixing headers. Each FASTA entry is handled individually. I recently changed the way how the database file is parsed. Could you please try the latest[ release candidate](https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0)?

**Comment by anesvi** [comment]
Hi Felipe, thanks for correcting me. If we already made that change, can we provide more info on the philosopher wiki page? Thanks!

**Comment by prvst** [comment]
Let me know what other info you want me to add there. I will have it updated once we release it.

**Comment by yannic-chen** [comment]
@prvst @anesvi  thank you very much for the fast reply. I will suggest to my group to upgrade FragPipe and I will update you about the issue.

**Comment by yannic-chen** [comment]
I found a temporary solution until FragPipe will be updated, by converting the header gene name to P# (where # represents a number). I wasnt able to identify what resulted in the error (I even filtered, so that the fasta only contained capital letters and numbers)

**Comment by xiaodfeng** [comment]
I came across similar error as well. 
`philosopher database --custom uniprot_human_W_Trunk.fasta --contam`
The above command works fine with philosopher_v4.1.1.
However,  philospher v4.8.1 or v5.0.0 will result in an error: "index out of range [1] with length 1".
