### ISSUE TITLE
PTM Localization

### ISSUE THREAD

**Issue by hxxhust163** [Nesvilab/FragPipe#1040]
Hello

  I used the offset mode to search some modification with the default setting. But how I evaluate the modification localization? For instance, the PTMiner calculate a probability for the localization of a modification based on the search results. However, in the fragpipe, there is no information about a probability with a specific modification site. So, how should I understand the result of a offset search?

Thanks!

**Comment by hxxhust163** [comment]
I also checked PTMProphet in fragpipe and specified 2 modification( STY: phospho,M:oxidation), but I got the same result compared with the default offset mode search. It seems that the PTMProphet does not work?

**Comment by fcyu** [comment]
There are several ways to evaluate the PTM location confidence globally (sample level) and locally (PSM level). 

If you enable PTM-Shepherd, it will generate a global PTM summary. 

There are also `MSFragger Localization`, `Best Score with Delta Mass`, and `Best Score without Delta Mass` columns in `psm.tsv` than can be used to evaluate the PSM-level localization confidence based on the hyperscore. 

If you set `report mass shift as a variable mod` to `Yes, remove delta mass` and enable PTMProphet by **adding all mass-offsets as the modifications (not just "pecified 2 modification( STY: phospho,M:oxidation)")**, you will have the PSM level PTM localization probabilities.

Some of those advanced settings require you to be vary familiar with our tools' parameters. Please read the documents https://fragpipe.nesvilab.org/ and https://github.com/Nesvilab/MSFragger/wiki, and contact us if you have any questions.

Best,

Fengchao

**Comment by hxxhust163** [comment]
Hello Mr Yu
     Thanks for your instruction and I got through a pipeline with PTMProphet. Here, I still have some questions to ask you.
Q1.  Using the same dataset, offset-commonPTMs mode default setting except for 'mass diff as a variable modification', I tested the three different setting of 'mass diff as a variable modification',  0,1,2. Surprisingly, I got same outcome for 0 and 2, which is different from 1. So, what is the supposed situation for 0,1,2 of 'mass diff as a variable modification' ?
Q2. The default  offset-commonPTMs workflow considers a list of about 72 msaa offsets including oxidation and phospho. This time, I only used 15.9949 and 79.9663  in the mass offsets list and run the same workflow as mentioned in Q1. An error occured in PeptideProphet(offset mode), showing model failed for charge 1 to 7. I wonder why this happens, it works well when the mass list contains 72 values, but broken in 2 offset values?
Q3. Also, I can use closed search with oxidation and phospho as variable modification. So, what is the difference between this closed search and the offset search mentioned in Q2 as they only focused on phospho and oxidation?
Q4. I followed your instruction with 'mass diff as a variable modification=1' to run the offset-commonPTMs workflow with PTMProphet. At the first time, I applied only a few modification sites in list1 as following: 

"M:-105.0248,M:-89.0299,C:-33.9877,M:-32.0085,P:-30.0106,STYNQDCE:-18.0106,STQCN:-17.0265,STYK:-2.0157,C:-1.007825,KLAVTGIDSFRHMEWQNPCY:-0.984,KLAVTGIDSFRHMEWQNPCY:0.984,T:3.9949,M:12.0,QMT:13.9793,Y:14.015,M:15.9949,KS:19.9898,QS:21.969392,MT:21.9819,KD:23.95806,YSA:26.0157,HM:27.9949,P:28.0313,ES:28.990164,VH:29.9742,QM:31.972071,PG:31.9898,MKYT:37.9469,YL:37.955882,YESK:42.0106,V:42.047,QN:43.0058,MPQ:43.9898,AKPT:44.985078,WFVT:47.9847,C:53.9193,CYF:58.0055,FPKC:61.9135,TL:61.921774,LQS:68.026215,KCP:70.041865,VGI:79.9568,STY:79.9663,QGKPA:86.000394,KITV:100.016,CP:119.004099,AHD:146.0579,NSTV:162.0528,WMT:173.051,MFH:176.0321,SNR:178.0477,KGM:183.035399,GLD:189.046,QPY:203.0794,VTL:204.1878,QSM:210.1984,NFV:229.014009,PD:238.2297,KTY:301.9865,LPT:340.1006,GIV:349.1373,MFE:365.1322,EK:365.1322,ST:406.1587,T:541.06111" , 

and I got many warnings and errors showing 'unknown mods may exist' like this: 

WARNING: Unrecognized mod token F[191] on peptide: SPRAAQGLGF[191]
ERROR: Cannot initialize for sequence: SPRAAQGLGF[191], unknown mods may exist in spectrum 20180524_QEh1_LC1_JMI_SA_16AY0F_HLAIp_R01.22046.22046.2
Please specify modification and rerun PTMProphet ...
PTMProphetParser: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Process 'PtmProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
time="20:37:52" level=fatal msg="Cannot execute program. there was an error with PTMProphet, please check your parameters and input files"

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

To solve this problem, I applied all 20 AA as probable modification sites in list2 as following:

M:-105.0248,M:-89.0299,C:-33.9877,M:-32.0085,P:-30.0106,STYNQDCE:-18.0106,STQCN:-17.0265,STYK:-2.0157,C:-1.007825,KLAVTGIDSFRHMEWQNPCY:-0.984,KLAVTGIDSFRHMEWQNPCY:0.984,T:3.9949,ARNDCEQGHILKMFPSTWYV:12.0,ARNDCEQGHILKMFPSTWYV:13.9793,ARNDCEQGHILKMFPSTWYV:14.015,ARNDCEQGHILKMFPSTWYV:15.9949,ARNDCEQGHILKMFPSTWYV:19.9898,ARNDCEQGHILKMFPSTWYV:21.969392,ARNDCEQGHILKMFPSTWYV:21.9819,ARNDCEQGHILKMFPSTWYV:23.95806,ARNDCEQGHILKMFPSTWYV:26.0157,ARNDCEQGHILKMFPSTWYV:27.9949,ARNDCEQGHILKMFPSTWYV:28.0313,ARNDCEQGHILKMFPSTWYV:28.990164,ARNDCEQGHILKMFPSTWYV:29.9742,ARNDCEQGHILKMFPSTWYV:31.972071,ARNDCEQGHILKMFPSTWYV:31.9898,ARNDCEQGHILKMFPSTWYV:37.9469,ARNDCEQGHILKMFPSTWYV:37.955882,ARNDCEQGHILKMFPSTWYV:42.0106,ARNDCEQGHILKMFPSTWYV:42.047,ARNDCEQGHILKMFPSTWYV:43.0058,ARNDCEQGHILKMFPSTWYV:43.9898,ARNDCEQGHILKMFPSTWYV:44.985078,ARNDCEQGHILKMFPSTWYV:47.9847,ARNDCEQGHILKMFPSTWYV:53.9193,ARNDCEQGHILKMFPSTWYV:58.0055,ARNDCEQGHILKMFPSTWYV:61.9135,ARNDCEQGHILKMFPSTWYV:61.921774,ARNDCEQGHILKMFPSTWYV:68.026215,ARNDCEQGHILKMFPSTWYV:70.041865,ARNDCEQGHILKMFPSTWYV:79.9568,ARNDCEQGHILKMFPSTWYV:79.9663,ARNDCEQGHILKMFPSTWYV:86.000394,ARNDCEQGHILKMFPSTWYV:100.016,ARNDCEQGHILKMFPSTWYV:119.004099,ARNDCEQGHILKMFPSTWYV:146.0579,ARNDCEQGHILKMFPSTWYV:162.0528,ARNDCEQGHILKMFPSTWYV:173.051,ARNDCEQGHILKMFPSTWYV:176.0321,ARNDCEQGHILKMFPSTWYV:178.0477,ARNDCEQGHILKMFPSTWYV:183.035399,ARNDCEQGHILKMFPSTWYV:189.046,ARNDCEQGHILKMFPSTWYV:203.0794,ARNDCEQGHILKMFPSTWYV:204.1878,ARNDCEQGHILKMFPSTWYV:210.1984,ARNDCEQGHILKMFPSTWYV:229.014009,ARNDCEQGHILKMFPSTWYV:238.2297,ARNDCEQGHILKMFPSTWYV:301.9865,ARNDCEQGHILKMFPSTWYV:340.1006,ARNDCEQGHILKMFPSTWYV:349.1373,ARNDCEQGHILKMFPSTWYV:365.1322,ARNDCEQGHILKMFPSTWYV:365.1322,ARNDCEQGHILKMFPSTWYV:406.1587,ARNDCEQGHILKMFPSTWYV:541.06111

Although several warnings and errors occurred like the first time, the pipeline got done.  So, what is recommended setting, as you can see that supplying all 20 AA looks very  awkward [laugh] and may dilute the probability of the correct localization.

Q5. The last one is about the '--minprob' command in PTMProphet. Is '--minprob=0.5' the default setting? I used '--minprob=0.5' and '--minprob=0.9' but got the same result in peptide.tsv, psm.tsv, ions.tsv and filter.log.  So, how to got the localization-probability-satisfied result? Is it right to filter the result in psm.tsv based on best localization? Is there any tricky tools in Fragpipe to use? 

Thanks very much!


best regard
xiaoxiang

**Comment by hxxhust163** [comment]
Hello Mr Yu

Thanks for your instruction and I got through a pipeline with PTMProphet. Here, I still have some questions to ask you.

Q1.   Using the same dataset, offset-commonPTMs mode default setting except for 'mass diff as a variable modification', I tested the three different setting of 'mass diff as a variable modification', 0,1,2. Surprisingly, I got same outcome for 0 and 2, which is different from 1. So, what is the supposed situation for 0,1,2 of 'mass diff as a variable modification' ?

Q2.   The default offset-commonPTMs workflow considers a list of about 72 msaa offsets including oxidation and phospho. This time, I only used 15.9949 and 79.9663 in the mass offsets list and run the same workflow as mentioned in Q1. An error occured in PeptideProphet(offset mode), showing model failed for charge 1 to 7. I wonder why this happens, it works well when the mass list contains 72 values, but broken in 2 offset values?

Q3.   Also, I can use closed search with oxidation and phospho as variable modification. So, what is the difference between this closed search and the offset search mentioned in Q2 as they only focused on phospho and oxidation?

Q4.   I followed your instruction with 'mass diff as a variable modification=1' to run the offset-commonPTMs workflow with PTMProphet. At the first time, I applied only a few modification sites in list1 as following:

"M:-105.0248,M:-89.0299,C:-33.9877,M:-32.0085,P:-30.0106,STYNQDCE:-18.0106,STQCN:-17.0265,STYK:-2.0157,C:-1.007825,KLAVTGIDSFRHMEWQNPCY:-0.984,KLAVTGIDSFRHMEWQNPCY:0.984,T:3.9949,M:12.0,QMT:13.9793,Y:14.015,M:15.9949,KS:19.9898,QS:21.969392,MT:21.9819,KD:23.95806,YSA:26.0157,HM:27.9949,P:28.0313,ES:28.990164,VH:29.9742,QM:31.972071,PG:31.9898,MKYT:37.9469,YL:37.955882,YESK:42.0106,V:42.047,QN:43.0058,MPQ:43.9898,AKPT:44.985078,WFVT:47.9847,C:53.9193,CYF:58.0055,FPKC:61.9135,TL:61.921774,LQS:68.026215,KCP:70.041865,VGI:79.9568,STY:79.9663,QGKPA:86.000394,KITV:100.016,CP:119.004099,AHD:146.0579,NSTV:162.0528,WMT:173.051,MFH:176.0321,SNR:178.0477,KGM:183.035399,GLD:189.046,QPY:203.0794,VTL:204.1878,QSM:210.1984,NFV:229.014009,PD:238.2297,KTY:301.9865,LPT:340.1006,GIV:349.1373,MFE:365.1322,EK:365.1322,ST:406.1587,T:541.06111" ,

and I got many warnings and errors showing 'unknown mods may exist' like this:

WARNING: Unrecognized mod token F[191] on peptide: SPRAAQGLGF[191]
ERROR: Cannot initialize for sequence: SPRAAQGLGF[191], unknown mods may exist in spectrum 20180524_QEh1_LC1_JMI_SA_16AY0F_HLAIp_R01.22046.22046.2
Please specify modification and rerun PTMProphet ...
PTMProphetParser: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Process 'PtmProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
time="20:37:52" level=fatal msg="Cannot execute program. there was an error with PTMProphet, please check your parameters and input files"

Cancelling 6 remaining tasks

To solve this problem, I applied all 20 AA as probable modification sites in list2 as following:

M:-105.0248,M:-89.0299,C:-33.9877,M:-32.0085,P:-30.0106,STYNQDCE:-18.0106,STQCN:-17.0265,STYK:-2.0157,C:-1.007825,KLAVTGIDSFRHMEWQNPCY:-0.984,KLAVTGIDSFRHMEWQNPCY:0.984,T:3.9949,ARNDCEQGHILKMFPSTWYV:12.0,ARNDCEQGHILKMFPSTWYV:13.9793,ARNDCEQGHILKMFPSTWYV:14.015,ARNDCEQGHILKMFPSTWYV:15.9949,ARNDCEQGHILKMFPSTWYV:19.9898,ARNDCEQGHILKMFPSTWYV:21.969392,ARNDCEQGHILKMFPSTWYV:21.9819,ARNDCEQGHILKMFPSTWYV:23.95806,ARNDCEQGHILKMFPSTWYV:26.0157,ARNDCEQGHILKMFPSTWYV:27.9949,ARNDCEQGHILKMFPSTWYV:28.0313,ARNDCEQGHILKMFPSTWYV:28.990164,ARNDCEQGHILKMFPSTWYV:29.9742,ARNDCEQGHILKMFPSTWYV:31.972071,ARNDCEQGHILKMFPSTWYV:31.9898,ARNDCEQGHILKMFPSTWYV:37.9469,ARNDCEQGHILKMFPSTWYV:37.955882,ARNDCEQGHILKMFPSTWYV:42.0106,ARNDCEQGHILKMFPSTWYV:42.047,ARNDCEQGHILKMFPSTWYV:43.0058,ARNDCEQGHILKMFPSTWYV:43.9898,ARNDCEQGHILKMFPSTWYV:44.985078,ARNDCEQGHILKMFPSTWYV:47.9847,ARNDCEQGHILKMFPSTWYV:53.9193,ARNDCEQGHILKMFPSTWYV:58.0055,ARNDCEQGHILKMFPSTWYV:61.9135,ARNDCEQGHILKMFPSTWYV:61.921774,ARNDCEQGHILKMFPSTWYV:68.026215,ARNDCEQGHILKMFPSTWYV:70.041865,ARNDCEQGHILKMFPSTWYV:79.9568,ARNDCEQGHILKMFPSTWYV:79.9663,ARNDCEQGHILKMFPSTWYV:86.000394,ARNDCEQGHILKMFPSTWYV:100.016,ARNDCEQGHILKMFPSTWYV:119.004099,ARNDCEQGHILKMFPSTWYV:146.0579,ARNDCEQGHILKMFPSTWYV:162.0528,ARNDCEQGHILKMFPSTWYV:173.051,ARNDCEQGHILKMFPSTWYV:176.0321,ARNDCEQGHILKMFPSTWYV:178.0477,ARNDCEQGHILKMFPSTWYV:183.035399,ARNDCEQGHILKMFPSTWYV:189.046,ARNDCEQGHILKMFPSTWYV:203.0794,ARNDCEQGHILKMFPSTWYV:204.1878,ARNDCEQGHILKMFPSTWYV:210.1984,ARNDCEQGHILKMFPSTWYV:229.014009,ARNDCEQGHILKMFPSTWYV:238.2297,ARNDCEQGHILKMFPSTWYV:301.9865,ARNDCEQGHILKMFPSTWYV:340.1006,ARNDCEQGHILKMFPSTWYV:349.1373,ARNDCEQGHILKMFPSTWYV:365.1322,ARNDCEQGHILKMFPSTWYV:365.1322,ARNDCEQGHILKMFPSTWYV:406.1587,ARNDCEQGHILKMFPSTWYV:541.06111

Although several warnings and errors occurred like the first time, the pipeline got done.  So, what is recommended setting, as you can see that supplying all 20 AA looks very  awkward [laugh] and may dilute the probability of the correct localization.

Q5.   The last one is about the '--minprob' command in PTMProphet. Is '--minprob=0.5' the default setting? I used '--minprob=0.5' and '--minprob=0.9' but got the same result in peptide.tsv, psm.tsv, ions.tsv and filter.log.  So, how to got the localization-probability-satisfied result? Is it right to filter the result in psm.tsv based on best localization? Is there any tricky tools in Fragpipe to use? 

Thanks very much!


best regard
xiaoxiang

**Comment by fcyu** [comment]
> Q1. Using the same dataset, offset-commonPTMs mode default setting except for 'mass diff as a variable modification', I tested the three different setting of 'mass diff as a variable modification', 0,1,2. Surprisingly, I got same outcome for 0 and 2, which is different from 1. So, what is the supposed situation for 0,1,2 of 'mass diff as a variable modification' ?

![image](https://user-images.githubusercontent.com/6926299/226615129-c4c4c9fa-afd5-42af-973f-53fb2d44012b.png)

One corrects the delta mass by subtracting the theoretical value of the mod, the other one does not.


> Q2. The default offset-commonPTMs workflow considers a list of about 72 msaa offsets including oxidation and phospho. This time, I only used 15.9949 and 79.9663 in the mass offsets list and run the same workflow as mentioned in Q1. An error occured in PeptideProphet(offset mode), showing model failed for charge 1 to 7. I wonder why this happens, it works well when the mass list contains 72 values, but broken in 2 offset values?

Can you share the log file?


> Q3. Also, I can use closed search with oxidation and phospho as variable modification. So, what is the difference between this closed search and the offset search mentioned in Q2 as they only focused on phospho and oxidation?

Here is a pre-print that can answer your question well: https://www.biorxiv.org/content/10.1101/2022.10.12.511963v1


> Although several warnings and errors occurred like the first time, the pipeline got done. So, what is recommended setting, as you can see that supplying all 20 AA looks very awkward [laugh] and may dilute the probability of the correct localization.

Unfortunately, you need to give all 20 amino acids because this is how to PTMProphet work.


> Q5. The last one is about the '--minprob' command in PTMProphet. Is '--minprob=0.5' the default setting? I used '--minprob=0.5' and '--minprob=0.9' but got the same result in peptide.tsv, psm.tsv, ions.tsv and filter.log. So, how to got the localization-probability-satisfied result? Is it right to filter the result in psm.tsv based on best localization? Is there any tricky tools in Fragpipe to use?

`--minprob` is not about localization probability. It controls the minimum PSM probability. Here is the doc: http://www.tppms.org/tools/ptm/

Best,

Fengchao

**Comment by fcyu** [comment]
```shell
Iterations: .........10.........20....WARNING: Mixture model quality test failed for charge (1+).
.
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).

/data/xhuang/Tools/FragPipe-17/tools/philosopher/philosopher filter --mapmods --tag DECOY_ --pepxml /data/shared/mhc/test/xhuang/test-ptminer/S026-AYOF/frag11
time="16:48:25" level=info msg="Executing Filter v4.2.1"
time="16:48:25" level=info msg="Processing peptide identification files"
time="16:48:25" level=info msg="Parsing interact.pep.xml"
time="16:48:25" level=warning msg="No PSM was found in data set. interact.pep.xml"
time="16:48:25" level=info msg="1+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="2+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="3+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="4+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="5+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="6+ Charge profile" decoy=0 target=0
time="16:48:25" level=info msg="Database search results" ions=0 peptides=0 psms=0
time="16:48:25" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="16:48:25" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="16:48:25" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="16:48:25" level=info msg="Post processing identifications"
```

There are no IDs from your data. Please double check your data and settings.

Best,

Fengchao

**Comment by hxxhust163** [comment]
Ok, thank  you very much!

best regard

xiaoxiang
