### ISSUE TITLE
Linux utils on windows?

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#1042]
- Describe the issue or question:
- I have a new computer - still installing software, etc.
I would like to run PTMProphet which seems to require operations on the *.mod.pep.xml files.

I get the following message:
[INFO:] Writing file interact-20230303_RJG1_114J_Jurkat_4_Slot1-29_1_2111.mod.pep.xml ...
'chmod' is not recognized as an internal or external command,
operable program or batch file.
[INFO:] done ...

I was using WSL before and maybe that's where it found chmod on its path?  Otherwise, what can be done to make chmod easily findable?

Thanks
Paul

**Comment by fcyu** [comment]
Hi Paul,

We also saw it on Windows. I don't think is warning will affect anything.

Best,

Fengchao

**Comment by rudnickp** [comment]
Hi Fenchao,
Thanks - where can I find the PTMProphet localization scores?

Best
Paul

**Comment by fcyu** [comment]
They can be found in the intermediate file `interact-*.mod.pep.xml` and the final result file `psm.tsv`. In `psm.tsv`, look for the column `[modified residue]:[modification mass]`. Here (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#psmtsv) is a brief toturial.

Best,

Fengchao

**Comment by rudnickp** [comment]
I only see columns for one of three variable mods in the psm.tsv file.  Should I see columns for each varmod / residue pair?

Best
Paul

**Comment by fcyu** [comment]
Have you adjusted the PTMProphet command to include all of your variable mods?

![image](https://user-images.githubusercontent.com/6926299/226416143-2c09f55e-28f2-4f09-b88b-5870676d3b04.png)

Best,

Fengchao

**Comment by rudnickp** [comment]
No, that's it.  I didn't look closely enough at the default parameters to see that they must be listed there.

Thanks
Paul

**Comment by rudnickp** [comment]
That worked.  Cheers, Paul

**Comment by fcyu** [comment]
Glad to hear that. Please feel free to contact us if you have any questions in the future.

Best,

Fengchao
