### ISSUE TITLE
OT and IT spectral files

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#1043]
- Describe the issue or question:
-
How does the parameter optimization work for raw files that contain mixed OT/IT MS2 spectra with differing resolutions?
Would there be any benefit to sub-setting the files by analyzer type, first?

Best
Paul

**Comment by fcyu** [comment]
Hi Paul,

I don't think our tools work for the data with the mix of OT and IT since we only have one fragment mass tolerance. You need to convert one raw file into two mzML files with OT and IT separated.

Best,

Fengchao

**Comment by anesvi** [comment]
But IT and OT subsets likely have different properties and true vs false PSM rates. So doing a single FDR filtering is also not good. Plus Percolator models may be suboptimal. So I think splitting into separate mzML is still a better way

**Comment by rudnickp** [comment]
Yes, good points.  FYI - running as a single file, optimized fragment tolerance was adjusted to 150ppm for what is likely a bimodal distribution.  I'll subset them in msconvert and retry with the pairs of mzMLs.

**Comment by rudnickp** [comment]
Yes, got it.  However, subset function in msconvert is producing errors.
![image](https://user-images.githubusercontent.com/2388060/226428590-efdcb01a-e2fe-4d72-9ac4-4ebaa36eea01.png)
Failed - System.Exception: [SpectrumList_Thermo::spectrum()] Error retrieving spectrum "controllerType=0 controllerNumber=1 scan=3": no matching instrument configuration for analyzer type radial ejection linear ion trap

   at pwiz.CLI.analysis.SpectrumListFactory.wrap(MSData msd, IList`1 wrappers, IterationListenerRegistry ilr)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)

**Comment by rudnickp** [comment]
I know that is not your software and will try the Proteowizard folks.

**Comment by rudnickp** [comment]
Looks like a problem because the instrument is the latest Thermo model (Ascend.)  Curious how Fragpipe handles unknown instruments and analyzer types?

**Comment by rudnickp** [comment]
Where is that filter setting located?
I reported the issue, and Pwiz are working on a fix.  It requires changes to the CV so will take a little time.

**Comment by fcyu** [comment]
![image](https://user-images.githubusercontent.com/6926299/226450561-71ca89a8-e87d-412d-bc26-f76abd212509.png)

Please let us know if it works well for your Ascend data.

Best,

Fengchao

**Comment by rudnickp** [comment]
These files are all HCD but have scans from the OT and IT.  So that wouldn't help the current issue.   And it looks like there is no option to filter by mass analyzer.  Is that correct?

**Comment by fcyu** [comment]
Ah, correct, no filter for mass analyzer. 

Best,

Fengchao
