### ISSUE TITLE
multiple files CAN NOT be generated as a single merged report.

### ISSUE THREAD

**Issue by tangsw22** [Nesvilab/FragPipe#1044]
- Describe the issue or question:
I have five TimsToF DDA files generated from SILAC-labeled samples, they were five fractions of my sample, I want them to be analyzed as unity to generate a single merged report.  I loaded the files into fragpipe 19.1, and leave the “Experiment” and “Bioreplicate” as blank as the instructions of fragpipe, but it did not work. The error message is “When doing label quant, each experiment group can only have one run”. I have done it successfully with version 18.0, I tried many times in version 19.1 but failed. Could you give some suggestions? Thanks.

![image](https://user-images.githubusercontent.com/74590041/226648987-ff26de3a-2754-47b5-9810-43d2131c4bbf.png)
![image](https://user-images.githubusercontent.com/74590041/226649024-74a8caab-22f4-483f-a2b2-863c0472848c.png)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
We have added the support of fractionated SILAC data. Please contact yufe AT umich.edu if you want to test the pre-released version.

Best,

Fengchao
