### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#1047]
Hi all,
I am during a DDA analysis. My workflow is LFQ-MBR with .d raw data from Lumos instrument. My samples is a complex of 2 organisms (plant: solanum lycopersici and a fungi), so for the database I always downloaded though the panel the tomato proteome (UP000004994) and I add my fasta file for the other organism. For a reason the last week Fragpipe couldn't dowload the specific proteome (I tried at least 10 proteomes and for some of them works for other no). So I made a fasta file that I combine the two proteomes. my problem is that comparing the results of the 2 approaches the results are totally different. With the download proteome + fasta, I was able to detect 300 proteins of my target and the number with the same database but combined in one fasta file is just 6 proteins. I assume that something is wrong in the way that the system create the database. 
Could you please give me any idea or alternatives to go over to this problem?
Thank you in advance for yourhelp.
Best
Tasos 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Tasos,

Could you upload your log files and fasta files?

Thanks,

Fengchao

**Comment by tasos2310** [comment]
Hi FengChao,
Thank for your quick response. You will find attached the fasta file and the log file. In the log file you will see that is running normally and giving the results. 
[log_2023-03-22_13-36-08.txt](https://github.com/Nesvilab/FragPipe/files/11044594/log_2023-03-22_13-36-08.txt)

**Comment by tasos2310** [comment]
Sorry this is the fasta file

**Comment by tasos2310** [comment]
[uniprot-proteome_UP000004994tomato_Cfulvum.txt](https://github.com/Nesvilab/FragPipe/files/11044622/uniprot-proteome_UP000004994tomato_Cfulvum.txt)

**Comment by fcyu** [comment]
Your database has the combination of UniProt format and RefSeq format. I am not sure if Philosopher can handle this. I cc Felipe @prvst 

```
>tr|A0A3Q7H8Z0|A0A3Q7H8Z0_SOLLC Uncharacterized protein OS=Solanum lycopersicum OX=4081 PE=4 SV=1
MNCNSKNKITEKTKTVILNREENPRIILSNFNDLEFDALRNFKNMSFVEIGKLIDLIIDGLVTCIAFGSYSKISRQLIEKIDQGLLKCGRLIWISRVEVLKHPSVSYLITHYKWNLLPVP
>XP_047764002.1 uncharacterized protein CLAFUR5_10167 [Fulvia fulva]
MQYKAITAAFALFVSATMAMPAAGPADAVAIQARGEEGLLDGALAGVGGVVAGVLGGLGLFDDVVGWKAYTNDDGVQCEPYTAEYDFQFAYKYKYCYTSSDKWDGHLGGSKYPKCKKWLPYKKEGKDCEPYTISYEYEYAYSTGCYESY
```

Best,

Fengchao

**Comment by tasos2310** [comment]
Ok sounds good. So, in the case for the multiple database how I can make it works. If I change my library to something like that **>tr|XP_047764002.1|** will be ok you believe?

**Comment by prvst** [comment]
Just keep the original header formats.

**Comment by tasos2310** [comment]
Thank you for your response. When I keep the original format I faced the problem that I described, seems that the datadase is not readable in the right way. This is the reason that I think that is betteer to change it. I run them now with the same database and I extract the same problematic results.
Thank you in advance,
Tasos

**Comment by prvst** [comment]
I made some adjustments, your sequences should be fine, just wait a few more days for the upcoming release.

Added to v5.0

**Comment by tasos2310** [comment]
Perfect, appreciate your help. I will check i the next days,
Best,
Tasos
