### ISSUE TITLE
TMT-integrator purity

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#1048]
- Describe the issue or question:
-

Hi,
I got this error:
TMT-Integrator v4.0.4
TMT-Integrator can't find the 'Purity' column. Please check if the column is in the psm tables.
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping

I see the purity filter under Advanced Options on the isobaric quant page.  Any idea why these values would not calculate (and be populated in the psm.tsv files)?

**Comment by rudnickp** [comment]
I am not running  MS1 quant.  Maybe that is the issue?

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchao

**Comment by anesvi** [comment]
Purity is calculated by philosopher freequant command. However, FragPioe will run it automatically if TMT-I checked (even though freequant unchecked in the Quant (MS1)tab). Are you running standard workflow in FragPipe? If so, there should be Purity column or there is an issue with your mzML. Would need to see the log file and your mzML files

**Comment by rudnickp** [comment]
I started from the standard TMT10 template and modified it down for TMT6.
mzMLs 2 and 3 may be non-standard.  These were created using Freestyle to filter out ITMS scans.  This generated a new .raw which was used to generate the mzML with msconvert.  I have another option: generate the mzMLs using subset in msconvert (thanks to Matt Chambers as of yesterday) that I could also try.

[log_2023-03-22_16-08-48.txt](https://github.com/Nesvilab/FragPipe/files/11045385/log_2023-03-22_16-08-48.txt)

**Comment by anesvi** [comment]
Yes, philosopher uses some logic to link ms2 and ms1 scans to calculate purity and trace the peak to get intensity. If that connection is broken or different from expected , you get no quant and or no purity. Sorry you will need to find a way to convert differently

**Comment by rudnickp** [comment]
I'm trying with msconvert subset now.  But it sounds like that may fail also fail.
Is there a way to not filter by purity for now?  Maybe by setting Min purity to -1?

**Comment by anesvi** [comment]
I don't know. I don't understand why there is no Purity column at all. I would expect 0. Perhaps philosopher just not writing it if it cannot calculate it. Is there intensity column and reporter ion intensity columns ? You may need to manually add that column until we can figure it out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anesvi** [comment]
Can you send us one of those bad mzML files

**Comment by rudnickp** [comment]
[mzml](https://drive.google.com/file/d/11p_q7oy1VbmsTcG-nZNquSJ7tXvfb_PI/view?usp=sharing)

**Comment by rudnickp** [comment]
I suppose that I could also try on the unfiltered file.  But the ITMS scans won't have reporter ions.

**Comment by anesvi** [comment]
PSMs with all 0 reporter ions will just be excluded , so that should be ok

**Comment by anesvi** [comment]
I could reproduce the issue. If we have time we will take a look (to see if we can at least write Purity column with all 0), but cannot guarantee. It would not be a priority, and it is some weird dataset anyway as there are only100 PSMs identified anyway.

**Comment by rudnickp** [comment]
Thanks, Alexey.  I will try with the whole file.  If that fails, I will make columns with zeroes and see if it can get past the exception.  It is actually a pretty cool dataset ;) chemical probe + TMT.  But there should be more like 700 PSMs.  So I will look into that.

**Comment by anesvi** [comment]
I did not specify any additional PTMs, so perhaps this is why I got only a hundred PSMs. 

Like I said we can try to fix it so at least that column is written with all 0 but may take us a few weeks as we will make it for the next release.
