### ISSUE TITLE
DIA-PASEF with DDA-PASEF library

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#1049]
Hello, 

I have 20 DDA-PASEF files derived from a high-pH reversed phase concatenated fractionation that I would like to use as files for library generation (--> "Set DIA-lib") and 16 individual DIA-PASEF measurements that would be used for quantification (--> "Set DIA-Quant"), all within a single DIA_SpecLib_Quant workflow analysis. Does this setup make sense, or do I have to e.g. label the DDA files with "Set DDA"?

Best, 
Hannes

**Comment by fcyu** [comment]
Hi Hannes,

You need to set your ddaPASEF to "DDA" data type, and diaPASEF to "DIA-Quant" data type.

Best,

Fengchao

**Comment by hcadre** [comment]
Hi Fengchao, 
many thanx for your ultra-quick reply! I will try as you suggested. 
Best, 
Hannes

**Comment by hcadre** [comment]
Hi Fengchao, 
ProteinProphet and PhilosopherDbAnnotate succesfully finished but then FragPipe issued an error message:

> 1 files will be processed
> [0:00] Loading spectral library library.tsv
> cannot read the file
> ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library
> Process 'DIA-NN' finished, exit code: -1
> Process returned non-zero exit code, stopping
> 
> ~~~~~~~~~~~~~~~~~~~~
> Cancelling 34 remaining tasks

The library.tsv file has been generated and is not empty. Any idea of what might have gone wrong? Log file is attached. 

Best, 

Hannes

[log_2023-03-23_17-11-11.txt](https://github.com/Nesvilab/FragPipe/files/11053133/log_2023-03-23_17-11-11.txt)

**Comment by fcyu** [comment]
Hi Hannes,

You should not assign any experimental groups. Clicking "clear groups" in the "workflow" tab to remove all groups.

Best,

Fengchao

**Comment by hcadre** [comment]
Hi Fengchao,
 
I repeated the analysis after removing all experimental groups as you suggested, however, I received the same error message as before:

> 16 files will be processed
> [0:00] Loading spectral library library.tsv
> cannot read the file
> ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library
> Process 'DIA-NN' finished, exit code: -1
> Process returned non-zero exit code, stopping

Very strange....

[log_2023-03-24_11-19-20.txt](https://github.com/Nesvilab/FragPipe/files/11060980/log_2023-03-24_11-19-20.txt)

Cheers, 
Hannes

**Comment by hcadre** [comment]
Alexey, 
Thank you for pointing at this stupid mistake! I had not realized that the SpecLib tab had been unchecked in the DIA_SpecLib_Quant workflow. Awfully sorry for bothering you all!
