### ISSUE TITLE
Java lang error

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1054]
I am trying to search Thermo .raw files using DDA LFQ-MBR method and FragPipe is exiting the search with the following error:

003. T100_3_1ug_DDA.mzBIN_calibrated java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackHeader(MZBINFile.java:395)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.__unpackBINHeader(MZBINFile.java:584)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:494)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:413)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:67)
	at p.a(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 126 remaining tasks

**Comment by fcyu** [comment]
I believe the file has been corrupted due to some reason. Could you rerun FragPipe from scratch? If the error persist, could you share the log file with us?

Thanks,

Fengchao

**Comment by pankajdwid** [comment]
Thanks Fengchao and queued the searches again, but It failed again, please see the attached log
[log_2023-03-26_13-30-25.txt](https://github.com/Nesvilab/FragPipe/files/11072443/log_2023-03-26_13-30-25.txt)

**Comment by anesvi** [comment]
I noticed you are using quite an old version of the tools. Perhaps you can upgrade to the latest FragPipe and MSFragger first.

**Comment by pankajdwid** [comment]
Thanks @anesvi, where can I go to upgrade the FragPipe?

**Comment by fcyu** [comment]
@pankajdwid  Here is the link to download FragPipe: https://github.com/Nesvilab/FragPipe/releases/latest

You also need to upgrade MSFragger, IonQuant, and Philosopher. You can let FragPipe download those tools for you after you open it.

Best,

Fengchao

**Comment by anesvi** [comment]
https://github.com/Nesvilab/FragPipe/releases

Download the latest, unzip, start FragPipe,use links in the Config tab to download the tools

**Comment by pankajdwid** [comment]
thanks @anesvi and @fcyu do i need uninstall the older version of fragpipe before downloading the newer version?

**Comment by anesvi** [comment]
Ok looks like Fengchao answered, I guess I am too eager to help my team when they are already responding, sorry!

**Comment by pankajdwid** [comment]
> Ok looks like Fengchao answered, I guess I am too eager to help my team when they are already responding, sorry!

:)

**Comment by fcyu** [comment]
No, you don't need to uninstall the old version. Just put all files of the new versions in a new folder.

Best,

Fengchao

**Comment by pankajdwid** [comment]
I tried to download Fragpipe and it did downloaded using .zipped file but all the other depedencies (MSFragger, ion quant etc) were empty and when i hot download/update button it gave me this error:
![image](https://user-images.githubusercontent.com/46572449/227804862-d872ff5f-0ce8-425a-9dd8-77f95f27826c.png)

Am i missing something?

**Comment by fcyu** [comment]
I guess something was wrong with your network. You can manually download them using web browser.

Best,

Fengchao

**Comment by pankajdwid** [comment]
@fcyu @anesvi I downloaded Fragpipe and other related related dependencies and researched the dataset but again errored out, please see the error log below:

[error log](https://github.com/Nesvilab/FragPipe/files/11073708/error.log)

**Comment by fcyu** [comment]
```shell
Could not load file M:\Proteomics\PDwivedi\LCMS\P300_DDA_3hr_50cm_Thermo\Dataset\3T3\T10_2_1ug_DDA.mzBIN_calibrated. The file may be corrupted.
java.lang.NullPointerException: mzBIN header not found!
```

It seems that the intermediate file was corrupted. I see that your files are in `M` drive which seems to be a network drive. You probably need to troubleshoot your file system.

Best,

Fengchao

**Comment by pankajdwid** [comment]
I just transferred all the .raw files on the local computer where Fragpipe is installed and researching the files, lets see if it is somehow the network drive access related issue which causing the crash of searches.

**Comment by pankajdwid** [comment]
@fcyu even after i transferred the .raw file to local computer where Fragpipe is installed and searched there, still got the same error 
[error log_2.txt](https://github.com/Nesvilab/FragPipe/files/11074159/error.log_2.txt)

Could you help me with this? Thanks.

**Comment by fcyu** [comment]
I have no idea now. Could you share `T10_2_1ug_DDA.raw` and the fasta file with me? Here is the link to upload the file: https://www.dropbox.com/request/69RDamzxoDLO0YlCvOSe

Thanks,

Fengchao

**Comment by pankajdwid** [comment]
@fcyu thanks for the link and i just uploaded the FASTA and .raw file for T10_2_1ug

**Comment by pankajdwid** [comment]
@fcyu please have a look and let me know what might be the issue, just by looking at the file, it looks ok to me!

**Comment by pankajdwid** [comment]
@fcyu did you get a chance to look into the files?

**Comment by pankajdwid** [comment]
Thanks @fcyu

**Comment by pankajdwid** [comment]
Hello @fcyu @anesvi 

I searched the individual file which was failing and it did search without any error, however when I tried researching all the files (12) together it failed again on the same file (T10_2), also when I tried removing that file and researching the remaining files (total 11 files) it failed on the other file (in this case T100_1). So, my question is when i am searching individual files or even 2 files at a time it is passing but when I am trying to set up the searches with all 12 files together, it is failing, do you know why it is happening? I have attached the error log here also:
[log_2023-03-28_06-55-23.txt](https://github.com/Nesvilab/FragPipe/files/11088475/log_2023-03-28_06-55-23.txt)

**Comment by fcyu** [comment]
Hi @pankajdwid ,

It is weird. Could you upload all of your 12 files to the link I sent?

Thanks,

Fengchao

**Comment by kwebber3** [comment]
I am encountering the same error on version 21.1, here is my log file:
[log_2024-03-07_09-28-01.txt](https://github.com/Nesvilab/FragPipe/files/14540256/log_2024-03-07_09-28-01.txt)
What fixed this for you @pankajdwid?

**Comment by fcyu** [comment]
@kwebber3 , the file has been corrupted. Could you delete all `*.mzBIN_calibrated` files and re-run the job from scratch?

Best,

Fengchao

**Comment by kwebber3** [comment]
That didn't work. PD works on these same raw files. Version 20 has a different error about building tables with the F$ class
[log_2024-03-08_09-41-52.txt](https://github.com/Nesvilab/FragPipe/files/14546630/log_2024-03-08_09-41-52.txt)

**Comment by fcyu** [comment]
I never saw such kind of error before. Not sure what caused the errors on your computer.

Maybe, could you 1) restart your computer; 2) delete all files including all versions of FragPipe, MSFragger, Philosopher, and IonQuant; 3) delete all unfinished FragPipe results of your data; 4) download the tools and start everything from scratch.

Best,

Fengchao

**Comment by kwebber3** [comment]
We tried all this and it still doesn't work.

2024年3月9日(土) 8:08 Fengchao ***@***.***>:

**Comment by fcyu** [comment]
Sorry to hear that. Maybe we can have a quick Zoom meeting to troubleshoot your problem. Could you send an email to yufe AT umich.edu if you want?

Thanks,

Fengchao
