### ISSUE TITLE
Java FileNotFoundException on psm.tsv

### ISSUE THREAD

**Issue by maxfpoole** [Nesvilab/FragPipe#1058]
Hi,

I'm trying to run Fragpipe and specifically PTM-Shepherd on some DDA data from Rats. I converted .raw to .mzML in the way specified and included PeakPicking. When Fragpipe attempts to Run PTM-Shepherd on my first file (Experimental name Fuzzy1), it encounters an error where it can't fine the relevant psm.tsv file. The file also does not exist in the directory. I'm not sure if this is a bug or more likely I've made some kind of error in selecting my parameter (I'm a very new user). 

Any help would be great,
Thanks.

[log_2023-03-26_18-44-37.txt](https://github.com/Nesvilab/FragPipe/files/11072485/log_2023-03-26_18-44-37.txt)

**Comment by danielgeiszler** [comment]
It looks like you didn’t run Philosopher. PTM-Shepherd runs on Philosopher
output files, i.e. filtered psm lists. You turned off the module that
produces these from raw search results.

Please reload the open workflow in the config tab. Since you already ran
MSFragger, you can disable that tab if you don’t want to run it again.

**Comment by anesvi** [comment]
I see a few issues. First, you need to use an open search workflow or common PTM workflow. You did a standard closed search it seems. Please load 'Open' workflow. Second, if you just want to get a list of common mass shifts in your data, annotate all mzML files to the same experiment. Third, I noticed that your data is low res MS2 data. We generally recommend high res data for PTM profiling using open searching

**Comment by maxfpoole** [comment]
Thanks Both!

I apologise for the triviality and appreciate your helping so quickly! Looks like your suggestions got it working.
