### ISSUE TITLE
Clarification - terminal sites

### ISSUE THREAD

**Issue by Arthfael** [Nesvilab/FragPipe#1064]
Sorry, this is not really an "issue", more a request for clarification:

I am not sure that I understand properly the way the patterns for protein/peptide termini work in the MSFragger tab:
- **[** and **n**, and **]** and **c**, represent respectively protein/peptide N- and C-termini.
- **^** represents a "terminus".
Yet both types are used together, as in the pattern for protein N-term acetylation, **[^**, in the example. This would indicate that **^** alone means "N-terminal amine or C-terminal carboxyl group". Similarly, **[** alone would indicate that the modification is on the N-terminal amino acid's side chain, not the N-terminal amine. Could you please confirm that this is the correct interpretation?

Last question: I have not found an example for the same situation at the C-terminus: should the orders be **^]** and **^c**, or should they be **]^** and **c^**?

Kind regards,

Armel

**Comment by fcyu** [comment]
Hi Armel,

You are correct mostly. `[]nc` are "modifiers" to indicate that the modification happens at terminus. `^`, `*`, and `A-Z` are "amino acids" where the modification is on. `^` means the terminus not a real amino acid. For example, `[C` means the modification is on the protein N-terminal Cysteine, `nK` means the modification is on the peptide N-terminal Lysine, and `n^` means the modification is on the peptide N-terminus.

> Last question: I have not found an example for the same situation at the C-terminus: should the orders be ^] and ^c, or should they be ]^ and c^?

Should be `]^` and  `c^`.
