### ISSUE TITLE
Open search fails

### ISSUE THREAD

**Issue by yashwanthsubbannayya** [Nesvilab/FragPipe#1065]
[log_2023-03-30_16-13-55.txt](https://github.com/Nesvilab/FragPipe/files/11113287/log_2023-03-30_16-13-55.txt)

Open search for Phosphorylation in MSfragger failed and got the following message.

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0xc00ae02100?)
	/home/prvst/sdk/go1.19.4/src/reflect/value.go:260 +0x85
reflect.flag.mustBeAssignable(...)
	/home/prvst/sdk/go1.19.4/src/reflect/value.go:247
reflect.Value.Set({0x16c7aa0?, 0xc0000081e0?, 0x16c7a01?}, {0x16c7aa0?, 0x0?, 0x335c9a0?})
	/home/prvst/sdk/go1.19.4/src/reflect/value.go:2154 +0x6a
github.com/vmihailenco/msgpack/v5.ptrValueDecoder.func1(0x18c4d88?, {0x16c7aa0?, 0xc0000081e0?, 0x194?})
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode_value.go:130 +0x133
github.com/vmihailenco/msgpack/v5.(*Decoder).DecodeValue(0x16776c0?, {0x16c7aa0?, 0xc0000081e0?, 0x0?})
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:309 +0x84
github.com/vmihailenco/msgpack/v5.(*Decoder).Decode(0xc00439a870?, {0x1640260?, 0xc004dd5520?})
	/home/prvst/go/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.5/decode.go:288 +0x825
philosopher/lib/sys.Restore({0x16c7aa0, 0xc0000081e0}, {0xc0026a6090, 0xd}, 0x0)
	/workspace/philosopher/lib/sys/sys.go:270 +0x209
philosopher/lib/id.(*ProtIDList).Restore(0xc000000100?)
	/workspace/philosopher/lib/id/pro.go:302 +0x93
philosopher/lib/fil.Run({{0xc000020780, 0x24}, {0xc000024730, 0x4d}, {0xc000024780, 0x47}, {0xc0000a62a0, 0x5c}, {0xc0000a6300, 0x53}, ...})
	/workspace/philosopher/lib/fil/fil.go:84 +0x8bf
philosopher/cmd.glob..func5(0x333d9c0?, {0x1740615?, 0xa?, 0xa?})
	/workspace/philosopher/cmd/filter.go:43 +0x390
github.com/spf13/cobra.(*Command).execute(0x333d9c0, {0xc0001b8be0, 0xa, 0xa})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x333c2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[16:13:55] the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter 
INFO[16:13:55] Converged to 0.00 % FDR with 0 Proteins       decoy=0 threshold=10 total=0
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

Log attached. Don't know if I am doing something wrong.

Thanks,
Yashwanth

**Comment by anesvi** [comment]
The next release of FragPipe will enable two-pass search. But searching for phospho is certainly possible now with the existing tools. I am traveling now but if you contact me again in a week I can try to provide suggestions
