### ISSUE TITLE
DIA_SpecLib_Quant Workflow: DIA-call broken

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#1067]
Dear FragPipe Team

My recent FragPipe-DIANN searches failed due to a missing specification of the library path in the final DIA-NN call: 

`Done generating spectral library
2023-03-31 13:47:50,042:INFO:took 0:14:56.822794
Process 'SpecLibGen' finished, exit code: 0
DIA-NN [Work dir: Z:\Christian\fpdiann_windows\mzml]
D:\Software\FragPipe-jre-19.1\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe **--lib** --report-lib-info --threads 8 --verbose 1 --out diann-output\diann-output.tsv --qvalue 0.01 --matrix-qvalue 0.01 --matrices --no-prot-inf --smart-profiling --no-quant-files --predictor --dl-no-rt --dl-no-im --strip-unknown-mods --cfg Z:\Christian\fpdiann_windows\mzml\filelist_diann.txt
DIA-NN 1.8.2 beta 8 (Data-Independent Acquisition by Neural Networks)`

I've used this very prompt afterwards directly in the CLI with the additional specification of the library-path and the search worked flawlessly. 

I didn't roll back FragPipe to an earlier version yet. But I've observed this issue on a Ubuntu and a Windows machine (on Windows an additional error is thrown, due to the missing input for DIANN-report.pdf generation).

Do you have an idea, what could cause this strange behavior?

Best,
Christian

log file:
[log_2023-03-31_12-40-48.txt.tar.gz](https://github.com/Nesvilab/FragPipe/files/11121893/log_2023-03-31_12-40-48.txt.tar.gz)

**Comment by fcyu** [comment]
Hi Christian,

You put `--report-lib-info` in `spectral library` box, which causes this issue:

![image](https://user-images.githubusercontent.com/6926299/229132684-5c8c7058-9db7-49e7-a452-6582a27ddce1.png)

That box is for the path of your custom library file. And most of time, you do not need to put anything there.

Best,

Fengchao
