### ISSUE TITLE
EasyPQP on Windows

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#1068]
- Describe the issue or question:
Can't install EasyPQP on Windows
If I try to install pyopenms manually using pip, it can't find a windows build.

WARNING: Skipping easypqp as it is not installed.WARNING: Skipping pyopenms as it is not installed.Collecting easypqp
  Using cached easypqp-0.1.36.tar.gz (196 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: lxml in c:\users\paul\appdata\local\programs\python\python311\lib\site-packages (4.9.2)
Collecting Click>=8.0.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: numpy in c:\users\paul\appdata\local\programs\python\python311\lib\site-packages (from easypqp) (1.24.2)
Requirement already satisfied: scipy in c:\users\paul\appdata\roaming\python\python311\site-packages (from easypqp) (1.10.1)
Collecting scikit-learn
  Using cached scikit_learn-1.2.2-cp311-cp311-win_amd64.whl (8.3 MB)
Collecting statsmodels
  Using cached statsmodels-0.13.5-cp311-cp311-win_amd64.whl (9.0 MB)
Requirement already satisfied: pandas>=1.1.0 in c:\users\paul\appdata\roaming\python\python311\site-packages (from easypqp) (1.5.3)
Collecting biopython
  Using cached biopython-1.81-cp311-cp311-win_amd64.whl (2.7 MB)
Collecting easypqp
  Using cached easypqp-0.1.35.tar.gz (194 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.34.tar.gz (194 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.33.tar.gz (194 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.32.tar.gz (193 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.31.tar.gz (193 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.30.tar.gz (192 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.29.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.28.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.27.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.26.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.25.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.24.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.23.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.22.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.21.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.20.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.19.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.18.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.17.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.16.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.15.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.14.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.13.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.12.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.11.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.10.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.9.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.8.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.7.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.6.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.5.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.4.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.3.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.2.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached easypqp-0.1.1.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pyprophet
  Using cached pyprophet-2.2.5.tar.gz (172 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting easypqp
  Using cached easypqp-0.1.0-py2.py3-none-any.whl (198 kB)
ERROR: Cannot install easypqp==0.1.0, easypqp==0.1.1, easypqp==0.1.10, easypqp==0.1.11, easypqp==0.1.12, easypqp==0.1.13, easypqp==0.1.14, easypqp==0.1.15, easypqp==0.1.16, easypqp==0.1.17, easypqp==0.1.18, easypqp==0.1.19, easypqp==0.1.2, easypqp==0.1.20, easypqp==0.1.21, easypqp==0.1.22, easypqp==0.1.23, easypqp==0.1.24, easypqp==0.1.25, easypqp==0.1.26, easypqp==0.1.27, easypqp==0.1.28, easypqp==0.1.29, easypqp==0.1.3, easypqp==0.1.30, easypqp==0.1.31, easypqp==0.1.32, easypqp==0.1.33, easypqp==0.1.34, easypqp==0.1.35, easypqp==0.1.36, easypqp==0.1.4, easypqp==0.1.5, easypqp==0.1.6, easypqp==0.1.7, easypqp==0.1.8 and easypqp==0.1.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    easypqp 0.1.36 depends on pyopenms>=2.6.0
    easypqp 0.1.35 depends on pyopenms>=2.6.0
    easypqp 0.1.34 depends on pyopenms>=2.6.0
    easypqp 0.1.33 depends on pyopenms>=2.6.0
    easypqp 0.1.32 depends on pyopenms>=2.6.0
    easypqp 0.1.31 depends on pyopenms>=2.6.0
    easypqp 0.1.30 depends on pyopenms>=2.6.0
    easypqp 0.1.29 depends on pyopenms>=2.6.0
    easypqp 0.1.28 depends on pyopenms>=2.6.0
    easypqp 0.1.27 depends on pyopenms>=2.6.0
    easypqp 0.1.26 depends on pyopenms>=2.6.0
    easypqp 0.1.25 depends on pyopenms>=2.6.0
    easypqp 0.1.24 depends on pyopenms>=2.6.0
    easypqp 0.1.23 depends on pyopenms>=2.6.0
    easypqp 0.1.22 depends on pyopenms>=2.6.0
    easypqp 0.1.21 depends on pyopenms>=2.6.0
    easypqp 0.1.20 depends on pyopenms>=2.6.0
    easypqp 0.1.19 depends on pyopenms>=2.6.0
    easypqp 0.1.18 depends on pyopenms>=2.6.0
    easypqp 0.1.17 depends on pyopenms>=2.6.0
    easypqp 0.1.16 depends on pyopenms>=2.6.0
    easypqp 0.1.15 depends on pyopenms>=2.6.0
    easypqp 0.1.14 depends on pyopenms>=2.6.0
    easypqp 0.1.13 depends on pyopenms>=2.6.0
    easypqp 0.1.12 depends on pyopenms>=2.6.0
    easypqp 0.1.11 depends on pyopenms>=2.6.0
    easypqp 0.1.10 depends on pyopenms
    easypqp 0.1.9 depends on pyopenms
    easypqp 0.1.8 depends on pyopenms
    easypqp 0.1.7 depends on pyopenms
    easypqp 0.1.6 depends on pyopenms
    easypqp 0.1.5 depends on pyopenms
    easypqp 0.1.4 depends on pyopenms
    easypqp 0.1.3 depends on pyopenms
    easypqp 0.1.2 depends on pyopenms
    easypqp 0.1.1 depends on pyopenms
    easypqp 0.1.0 depends on pyopenms

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by fcyu** [comment]
Are you using Python 3.8 or 3.9? I think EasyPQP requires that.

Best,

Fengchao

**Comment by rudnickp** [comment]
python 3.11.2

**Comment by fcyu** [comment]
Please use Python 3.8 or 3.9 due to the requirement of pyOpenMS used by EasyPQP.

Best,

Fengchao
