### ISSUE TITLE
DIA-Umpire on DIA PASEF error:  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by MassSpecPostDoc** [Nesvilab/FragPipe#1069]
Hello,

I have been trying to use the Spectral library building from DDA (SpecLib) workflow, with DIA-Umpire, to make a DDA-DIA hybrid library. This is from TIMS-ToF DIA-PASEF data, converted to mzML using MSconvert, I believe the conversion to be done correctly-I had a lot of failed attempts that did not progress as far as shown in the attached log. These included changing geographical (region) settings on Windows, and ensuring the decimal separator is a point ".", and also trying various settings on MSconvert-I am quite sure I have used the correct ones as described in the DIA-Umpire for Bruker .d instructions.  

I am actually not sure if DIA Umpire is compatible with DIA-PASEF data, please confirm?
[log_2023-04-04_16-08-24.txt](https://github.com/Nesvilab/FragPipe/files/11150374/log_2023-04-04_16-08-24.txt)

Please see the log for the error I am getting. 

Thank you,

Andy

**Comment by fcyu** [comment]
DIA-Umpire does not support diaPASEF data. Converting to mzML or not won't change anything. 

Best,

Fengchao

**Comment by witszymanski** [comment]
Hi! 
Does the MSFragger-DIA work now with TimsTof data? 

Greets
Witek

**Comment by fcyu** [comment]
No.

**Comment by witszymanski** [comment]
Any plans for it? it's the only thing that keeps us from switching completely to FP :)

**Comment by fcyu** [comment]
We are working on it around the clock. Stay tuned!

Best,

Fengchao

**Comment by MassSpecPostDoc** [comment]
Hi Fengchao,

Thanks for the update-looking forward to DIA PASEF compatibility.

Cheers,.

Andy

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by witszymanski** [comment]
ping ping
