### ISSUE TITLE
CrystalC command fails to run - "could not find or load main class Main"

### ISSUE THREAD

**Issue by andrewjmc** [Nesvilab/FragPipe#107]
# Describe the problem

* **I'm submitting a:**
  - [X] problem running the software
  - [?] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [X] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
I have run FragPipe successfully on my Windows machine, and am now transferring to a server through the console. I initially replicated the FragPipe pipeline as a bash script with success, and have now switched to running the FragPipe GUI by X11 forwarding. Closed searches work fine, but open searches fail at the crystalX step:

```
Crystal-C [Work dir: /xxx]
java -Xmx120G -cp "/tmp/fragpipe/common-deps-1.0.3.jar:/tmp/fragpipe/original-CrystalC-1.0.4.jar" Main /xxx/crystalc-0-xxx.pepXML.params /xxx/xxx.pepXML
Error: Could not find or load main class Main
Process 'Crystal-C' finished, exit code: 1
```

This suggests the command cannot find the jars in the temporary folder. Yet they are there, and if I run the command from my own console, all is well!

## System info

You can find that printed on the _Config_ tab.
- OS and version: Linux, Architecture: amd64
- Java version: 1.8.0_201, OpenJDK 64-Bit Server VM, Oracle Corporation
- FragPipe: 9.1

----

### General proteomics experiment description

Fractionated human serum

### Input data files

1 mzXML file as a test

### Sequence database

UniProt human + custom antibody database: 50Mb with decoys

----

## Attach fragger.params file

[fragger.params.txt](https://github.com/Nesvilab/FragPipe/files/2970580/fragger.params.txt)

## Run log output

```
Not saved in the output directory, and I was unable to copy wholesale from X11 forwarded window.
```

**Comment by fcyu** [comment]
We may first need to identify the source of this error.
FragPipe has another module called MSAdjuster that also calls a jar file from tmp. Let us try to see if that works well.
Could you please select "recalculated" for the "Precursor mass mode" in the "MSFragger" tab and see what would happen?

Thanks,

Fengchao

**Comment by anesvi** [comment]
If running on linux, edit fragger.param directly to change from ‘selected’ to ‘recalculated’

**Comment by fcyu** [comment]
Yes, if you are using shell script, all you need are editing the fragger.param accordingly and adding the command running MSAdjuster. Following is an example:

```bash
#!/bin/bash

set -xe

# User defined path. Changing it accordingly.
dataDir="/PXD001468/"
fastaPath="./human.fasta"
msadjusterPath="common-deps-1.0.3.jar:original-MsAdjuster-1.0.3.jar"
msfraggerPath="/MSFragger-20190222.jar"
crystalcPath="./CrystalC-1.0.4.jar"
philosopherPath="philosopher_linux_amd64_20190313"

$philosopherPath workspace --clean
$philosopherPath workspace --init

for myFile in $dataDir/*.mzML
do
	java -Xmx500G -cp $msadjusterPath Main 20 $myFile
done

java -Xmx500G -jar $msfraggerPath ./fragger.params $dataDir/*.mzML

mv $dataDir/*.pepXML ./
mv $dataDir/*.ma ./

for myFile in ./*.pepXML
do
	java -Xmx500G -cp $crystalcPath Main ./crystalc.pepXML.params $myFile
done

$philosopherPath database --annotate $fastaPath --prefix rev_

$philosopherPath peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --decoy rev_ --combine --database $fastaPath ./*_c.pepXML

$philosopherPath proteinprophet --maxppmdiff 2000000 ./interact.pep.xml 

$philosopherPath filter --sequential --razor --mapmods --tag rev_ --pepxml ./interact.pep.xml --protxml ./interact.prot.xml

$philosopherPath report

rm -rf ./.meta
rm ./*.pepindex
```

**Comment by andrewjmc** [comment]
Thanks Fengchao,

Yes, this still gives the same problem:

```
java -Xmx120G -cp "/tmp/fragpipe/common-deps-1.0.3.jar:/tmp/fragpipe/original-MsAdjuster-1.0.3.jar" Main 20 /home/ajm3018/data/proteomics/fractions/Qex03_SVH_150909_StephanieMenoikou_SM12.mzXML
Error: Could not find or load main class Main
Process 'MsAdjuster' finished, exit code: 1
```

And again, strangely, runs from shell without a problem!

Andrew

**Comment by fcyu** [comment]
Thanks for your prompt feedback.

It looks like FragPipe cannot find or doesn't have the permission to running the tools in your tmp directory. Since you are using X11 forwarding, it is more tricky than running from shell.

In order to verify my guess, could you please help to check if you can run MSAdjuster or Crystal-C from the command line under your X11 forwarding? If cannot, you may need to find a way to solve it since we have no idea about the environments of your Linux system and X11 forwarding.

Bests,

Fengchao

**Comment by guoci** [comment]
@andrewjmc I think I have found the problem. Attach is my fix, try it and check if it works.
https://drive.google.com/file/d/1YOyv9NPBW6NcGI5KcnEpIU7GH3vo3CwB/view?usp=sharing

**Comment by andrewjmc** [comment]
Alas, still the same error.

I can run any of the java commands successfully from the terminal. I'm unsure how to set up an X11 forwarded terminal so I can test running the command from there.

I did get a warning that fragment_ion_series was an unknown parameter for MSFragger. I suspect this is just a new feature which has been included.

**Comment by anesvi** [comment]
fragment_ion_series   - some new features we are working on. Can be ignored for the purpose of this discussion

**Comment by guoci** [comment]
@andrewjmc please send the FragPipe log to me.

**Comment by andrewjmc** [comment]
Done.

If it's most likely to be an issue with X11 forwarding, perhaps I shouldn't trouble you. I may just need to track down some linux/SSH/X11 expertise!

Worst case scenario, I could export the commands from FragPipe and run them from the terminal.

**Comment by andrewjmc** [comment]
The test version you made works now.

Thanks for all your help.

Andrew
