### ISSUE TITLE
'ProteinProphet' finished, exit code: 2

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#1070]
Hi all,
I am running some DIA data from Timtof instrument. According to the tutorial the system accept .d files but I had a lot of errors when I input my data, so I tried the converted mzml files. The run in this case started normally and seems that I have problem with the PeptideProphet, and more specifically looks like can't find data. I know that my files are fine and correct because I run them independently in DIA-NN. So, i assume that is something related on the way that Fragpipe read the data. I attached the log file  to have a look and tell me if there is a reason to fix it or if its only data independent. In addition I would like to ask you when the new philosopher will release, I had an issue with multiple fasta files, that will be solved with the new version.
Thank you in advance,
Best
tasos
[log_2023-04-04_10-43-33.txt](https://github.com/Nesvilab/FragPipe/files/11151415/log_2023-04-04_10-43-33.txt)

**Comment by fcyu** [comment]
We do not support direct searching diaPASEF data. 

Best,

Fengchao
