### ISSUE TITLE
EasyPQP error

### ISSUE THREAD

**Issue by EayonYang** [Nesvilab/FragPipe#1073]
- Describe the issue or question:
I get an error when I run SpecLib in Fragpipe. The error message is below:
        EasyPQP convert error BEGIN
        E:\anaconda\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
        E:\anaconda\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
        E:\anaconda\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
          warnings.warn("loaded more than 1 DLL from .libs:"
        Info: Converting E:\shuyan\output\interact-CSY_BAOMI_NEGF9_GC3_1_4133.pep.xml.
        Info: Parsing run CSY_BAOMI_NEGF9_GC3_1_4133.
        Info: Parsing pepXML.
        Info: Generate theoretical spectra.
        Info: Processing spectra from file G:\yiyang\CSY_BAOMI_NEGF9_GC3_1_4133_uncalibrated.mzML.
   

I tried reinstalling easyPQP ( code below ) and restarting fragpipe and still had an error. 
        ```
pip uninstall -y easypqp
        pip install git+https://github.com/guoci/easypqp.git
```

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-04-09_20-33-41.txt](https://github.com/Nesvilab/FragPipe/files/11185657/log_2023-04-09_20-33-41.txt)
[log_2023-04-09_22-22-08.txt](https://github.com/Nesvilab/FragPipe/files/11185658/log_2023-04-09_22-22-08.txt)

**Comment by fcyu** [comment]
Could you describe the error or upload the log file?

Thanks,

Fengchao

**Comment by fcyu** [comment]
I need your files to reproduce and find out the reason for the errors. If you are ok with that, could you upload `2023-04-09-decoys-pangenome_propan_cdhit.fasta.fas` and `CSY_BAOMI_NEGF10_GC4_1_4134.d` to https://www.dropbox.com/request/4R37gXBUHqpXvxARs6qh ?

Thanks,

Fengchao

**Comment by EayonYang** [comment]
Dear Fengchao,
 
     I had already submitted these files into Dropbox.

best,
Eayon

**Comment by fcyu** [comment]
Hi Eayon,

Thanks for your files. But I could not reproduce the error.
[log_2023-04-11_22-30-43.txt](https://github.com/Nesvilab/FragPipe/files/11206500/log_2023-04-11_22-30-43.txt)

Best,

Fengchao

**Comment by EayonYang** [comment]
I have tried it under two versions. The first time, under the latest version v19.1, there was a problem about "easypqp" (see attachment log_2023-04-09_22-22-08.txt), and the second time, under v17.1, there was an error related to "msfragger " related error (see attachment log_2023-04-11_12-26-18.txt for details). I would like to know what the problem is and how I can solve these two problems?

best，
Eayon

[log_2023-04-09_22-22-08.txt](https://github.com/Nesvilab/FragPipe/files/11206657/log_2023-04-09_22-22-08.txt)
[log_2023-04-11_12-26-18.txt](https://github.com/Nesvilab/FragPipe/files/11206659/log_2023-04-11_12-26-18.txt)

**Comment by fcyu** [comment]
Regarding the error in [log_2023-04-11_12-26-18.txt](https://github.com/Nesvilab/FragPipe/files/11206659/log_2023-04-11_12-26-18.txt), please troubleshoot your computer. Something was wrong with your file system or operation system.
```
[progress: 128570/128570 (100%) - 17917 spectra/s] 7.2sjava.io.FileNotFoundException: G:\yiyang\CSY_BAOMI_POSF9_GB1_1_4119.pepXML
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (./src/hotspot/os/windows/semaphore_windows.cpp:35), pid=13576, tid=920
#  guarantee(_semaphore != NULL) failed: CreateSemaphore failed with error code: 1450
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9.1+1, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# Can not save log file, dump to screen..
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (./src/hotspot/os/windows/semaphore_windows.cpp:35), pid=13576, tid=920
#  guarantee(_semaphore != NULL) failed: CreateSemaphore failed with error code: 1450
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9.1+1, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
```
 Since three log files have three different errors, I don't think we can reproduce them and give informative help.

Best,

Fengchao

**Comment by EayonYang** [comment]
Ok, thanks for your reply. I would like to know what could be the problem that causes easypqp not to be recognized?

Because I tried to configure python3.8 under fragpipe vv17.1 and it can't recognize easypqp.

But python 3.9 can recognize eaqypqp, why is this? And does it affect the identification result?
