### ISSUE TITLE
DIA-NN in FragPipe versus Standalone DIA-NN

### ISSUE THREAD

**Issue by TeckYewLow** [Nesvilab/FragPipe#1074]
Hi,

I realized there are some functionalities that are lacking in the Fragpipe version of DIA-NN in comparison to the standalone version. Can you please advise me on such differences?

Thank you.

**Comment by fcyu** [comment]
They are for different purpose. The DIA-NN in FragPipe is only for quantification using targeted extraction, identification and library building is from MSFragger and other modules in FragPipe.

Best,

Fengchao
