### ISSUE TITLE
Reference channels

### ISSUE THREAD

**Issue by ChiaraF96** [Nesvilab/FragPipe#1075]
Dear all,
For my Master's internship project I need to design an experiment for a large scale cell-line profiling and consequent data analysis. I would like to use FragPipe for the analysis and since I have never used it before I was wondering if FragPipe accepts more than 1 reference channel and if so, what is the maximum amount accepted.

Thank you in advance.

**Comment by fcyu** [comment]
It can, but it will only use one reference channel in the normalization.

Best,

Fengchao
