### ISSUE TITLE
IonQuant is not downloading 

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1077]
Hello,

We have a trial version of FragPipe while we are waiting to purchase a full license for our company, meanwhile IonQuant is not downloading and when I tried using older IonQuant .jar file, it is not working, please see the screen shot below:

<img width="641" alt="Capture" src="https://user-images.githubusercontent.com/46572449/231187742-289a1bd2-5b71-4ebf-ab6f-b4579cf49354.PNG">

**Comment by fcyu** [comment]
I think something was wrong with your Internet. Could you try again? If the error persist, could you send an email to yufe AT umich,edu? I will send you IonQuant by email.

Thanks,

Fengchao
