### ISSUE TITLE
Moving .mgf files to same folder as the search results for Scaffold

### ISSUE THREAD

**Issue by snnvn** [Nesvilab/FragPipe#1078]
Hello,

We noticed that Scaffold can display the MS/MS spectra as long as the .mgf file present in the same search results folders. Is it possible to move the uncalibrated MGF files to that search result folders after the analysis so that we don't have to move them manually? 

Thanks!

**Comment by anesvi** [comment]
I think it would make more sense for them in their software to look for files where we write them. We may have other tools that expect them next to mzML files.

**Comment by fcyu** [comment]
Several tools in FragPipe depends on the specific location of the (un)calibrated.mgf/mzml files. I believe that most MSFragger users use FragPipe rather than Scaffold. Therefore, I suggest you contact Scaffold to adjust for our tools, not the other way around.

Best,

Fengchao
