### ISSUE TITLE
Having trouble with EasyPQP installation

### ISSUE THREAD

**Issue by LukBorn** [Nesvilab/FragPipe#1080]
No matter how I install the easyPQP packages, I always get an error message as a dialog box stating "Python binary not valid" in the Spectral library generation box on the config page.

When i try to install easyPQP via the button, it gives me the following popup stating "EasyPQP install success", and then proceeds to show the same error message as before, and still doesnt let me run analyses, even on restarting fragpipe. 
![Unbenannt](https://user-images.githubusercontent.com/124793933/231444158-83d19659-6688-44c4-8e8c-c95df1d1963c.png)

Manually installing with pip, including with "--use-pep517" still always results in the same error message.

I have already tried setting the PYTHONPATH to ../lib/site-packages as described [here](https://github.com/Nesvilab/FragPipe/issues/978) but that hasnt worked for me either

Im running FragPipe on Windows 7, so the Python version I'm working with is 3.8.10. The Python box on the config page still gives me the dialog box error message "Python version 3.9+ required" for my python file path, even though [here](https://github.com/Nesvilab/FragPipe/issues/1068) it's been stated that version 3.8 or 3.9 should be used. Im guessing this is not the issue.

I cant start any analyses, Im getting the error message popup "Spectral Library Generation module was not configured correctly. Please make sure that Python and EasyPQP have been installed, then restart FragPipe", so I cant post any log files that arent empty.

**Comment by fcyu** [comment]
> Im running FragPipe on Windows 7, so the Python version I'm working with is 3.8.10. The Python box on the config page still gives me the dialog box error message "Python version 3.9+ required" for my python file path, even though https://github.com/Nesvilab/FragPipe/issues/1068 it's been stated that version 3.8 or 3.9 should be used. Im guessing this is not the issue.

For the released version (version 19.1), you need to use Python 3.9. The information you found regarding the 3.8 support is for the pre-released version after 19.1.

Best,

Fengchao
