### ISSUE TITLE
java.lang.NullPointerException[FragPipe v19.1]

### ISSUE THREAD

**Issue by Ziyuan999** [Nesvilab/FragPipe#1082]
Dear developers,
I've got an error when searching TMT data using NCBI-download fasta [FragPipe 19.1 (MSFragger-3.7; IonQuant-1.8.10; philosopher_v4.8.1)]. 

        'java.lang.NullPointerException
	at java.base/java.util.TreeMap.getEntry(Unknown Source)
	at java.base/java.util.TreeMap.get(Unknown Source)
	at integrate.LoadPsms(integrate.java:155)
	at integrate.run(integrate.java:31)
	at TMTIntegrator.main(TMTIntegrator.java:123)
        Error at: D:\b3\psm.tsv java.lang.NullPointerException
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping

I didn't get this error when using swissprot-downlade fasta using the same rawdata, file directory and settings. I attached the log and looking forward to your replay. 

Best,
Ziyuan

[log_2023-04-16_17-23-43.txt](https://github.com/Nesvilab/FragPipe/files/11242147/log_2023-04-16_17-23-43.txt)

**Comment by anesvi** [comment]
Please send us your log file by email at nesvi at Med.umich.edu. But we will probably need to see your fasta file as well

**Comment by Ziyuan999** [comment]
Thanks for your reply. I've sent the fasta file and log file to the email.
