### ISSUE TITLE
For TMT peptide and PSM table consistently cut off quantified values at 10000 hits

### ISSUE THREAD

**Issue by miwi1** [Nesvilab/FragPipe#1084]
- Describe the issue or question:
Running TMTpro analyses with MS2 or MS3 peptide and PSM tables seeem to have the right number of rows, but counting quantified values always ends up in 10002 +- 2 hits (rows with values different than 0). Any idea what could be the reason?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by anesvi** [comment]
I do not understand it. No one reported a truncation like that. So I do not know what to suggest. Maybe your excel opens only 10000 entries

**Comment by miwi1** [comment]
Hi,

Ok, shame on me. It was an excel bug. Should reactivate my R skills instead of doing this stuff with excel while needing last minute results for a presentation :)

Anyhow congrats to the latest version of Frapipe, which works extremely well for TMT.

Best
Michael





On 18. Apr 2023, at 20:00, Alexey Nesvizhskii ***@***.***> wrote:



I do not understand it. No one reported a truncation like that. So I do not know what to suggest. Maybe your excel opens only 10000 entries
