### ISSUE TITLE
MSBooster error 

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1085]
Error with MSBooster

Please see the screen shot below 

![error_230418](https://user-images.githubusercontent.com/46572449/232872121-97aabbcb-5827-4417-9593-4cb385409e52.JPG)
rop here.)

**Comment by yangkl96** [comment]
Hello,

Could you please attach the entire log file from this run? It seems that there are no PSMs that pass the requirements to be plotted.

Thanks,
Kevin

**Comment by yangkl96** [comment]
Also, if you are able to share the .pin file that generated this error, that would be helpful too.
