### ISSUE TITLE
DIA and PTM open search 

### ISSUE THREAD

**Issue by Pablo-Manfredi** [Nesvilab/FragPipe#1088]
Dear Fragpipe devs,

First of all, thank you so much for your wonderful tools they unlocked many of my research projects.

In the past years I frequently used MSFragger through fragpipe for PTM open searches on DDA data sets and it worked like a charm.

More recently we tend to use DIA as default method. 

Unfortunately, After many trials I did not manage to adapt any of the 2 proposed DIA workflows to perform PTM open searches or adapt the "Open" workflow to DIA.

Is that even possible to perform PTM open searches using FragPipe19.1/MSFragger-3.7.jar/ IonQuant-1.8.10.jar/4.8.1/philosopher ?

If so, do you think you could provide the corresponding workflow ?

Thank you for your time and efforts,
Best
Pablo

**Comment by fcyu** [comment]
Hi Pablo,

Thank you very much for your kind words.

We do not recommend performing open search for DIA data because the MS2 spectra are much noisier than the DDA data. But if you really want to, you can use the `DIA_DIA-Umpire_SpecLib_Quant` workflow, and change MSFragger setting to the open search.

Best,

Fengchao

**Comment by prdawar** [comment]
Hi @fcyu 
While attempting to run an open search using the steps outlined above, I haven’t been able to complete a successful run as FragPipe is returning multiple errors. Could you please review this and advise on the best way to proceed? Thank you.

[log_2026-01-31_01-16-36.txt](https://github.com/user-attachments/files/25061854/log_2026-01-31_01-16-36.txt)

**Comment by fcyu** [comment]
You are using an old version of FragPipe. Could you upgrade it to the latest version and try again?

Thanks.

Fengchao

**Comment by prdawar** [comment]
Dear @fcyu 
It worked. Thank you for the suggestion!

Pranav
