### ISSUE TITLE
Generate in silico sepectral library in semi-tryptic digestion mode

### ISSUE THREAD

**Issue by She1111** [Nesvilab/FragPipe#1096]
- Describe the issue or question:

Dear Fragpipe team,

Thank you for your great effort! I am doing limited proteolysis proteomics. I recently generated tryptic digestion in silico spectral library and searched with it by DIA-NN (dia-pasef data), but it seems that it was not doing that well with low amount of semi-tryptic peptides in the spectral library. I find MSFragger can modify digestion mode and enzyme. Could Fragpipe generate an in silico spectral library in semi-tryptic digestion mode?

Best regards,
Shel

**Comment by fcyu** [comment]
Hi Shel,

FragPipe can generate a spectral library by directly searching DDA (support both non-ion mobility and ddaPASEF data) and/or DIA (only support non-ion mobility data) data. So, if you have ddaPASEF data, you can build a semi-tryptic library.

Best,

Fengchao

**Comment by She1111** [comment]
Hi Fengchao,

Thank you for your so quick reply! As our DDA-PASEF mode is not doing that much good, we run DDA on Lumos which means the data do not contain ion mobility dimension. And our DIA data is from timsTOF... Is there any issues for this case?

Best,
Shel

**Comment by fcyu** [comment]
Hi Shel,

Unfortunately, I don't think the spectral library without ion mobility can be used for diaPASEF data.

Best,

Fengchao

**Comment by She1111** [comment]
Hi Fengchao,

So we have to run DIA on Lumos :). Thanks again for your valuable reply!

Cheers,
Shel
