### ISSUE TITLE
Problem using fewer channels of a TMT16plex kit 

### ISSUE THREAD

**Issue by MP-MS-Spec** [Nesvilab/FragPipe#1097]
Dear Fragpipe team,

thank you for the amazing job and support to FragPipe and the proteomic community.

I recently started to use FragPipe for TMT data extraction and I am having issue when I am using only 12 channels out of a TMT16plex kit.
The small noise/background signal in channel 132C, 133N, etc  is highly boosted by the Median Normalization of TMT integrator.
Is there a way to specify in FragPipe a lower number of channel used than 16 for a TMTpro Kit? (i.e. 12 channel in my case).
I tried to remove the last 5raws/TMT channels in the Annotation table but doesn´t seems to work.

I hope you can guide me though this issue and/or adding this possibility in future version.
Thank you
Michele

**Comment by fcyu** [comment]
Hi Michele,

Could you set those empty channels to `NA` in the TMT-Integrator annotation, and try again?

Best,

Fengchao

**Comment by MP-MS-Spec** [comment]
Hi Fengchao,

thank you for the quick reply. Indeed naming the "sample name" column "NA" worked.
Now I only have 12 TMT quantification columns in the "abundance_protein_MD" table. 
I was looking for this in the FragPipe user guide and among the reported issue and I couldn´t find this info.
I think would be great to include few lines about it in the user guide ;)

Thanks again
Best
Michele

**Comment by fcyu** [comment]
Hi Michele,

Thanks for the suggestion. I have added the description: https://github.com/Nesvilab/FragPipe/commit/2678e5ff213ac689f0453c1449e3f7d2fd381b13 and https://github.com/Nesvilab/FragPipe/commit/c3d442a9082eb4384c5f2feb622e212663c4c2d9

Best,

Fengchao
