### ISSUE TITLE
Not enough peptides found for alignment

### ISSUE THREAD

**Issue by JM-Bader** [Nesvilab/FragPipe#1099]
I run MSFragger to genertate a library from dimethyl (light) labeled non-human samples. 
It is timsTOF DDA data, I selected timsTOF as data format. 

I get this error message: 
![error message](https://user-images.githubusercontent.com/98888664/236447104-f0574d1b-dbbc-4964-a2b1-2a552cb322f9.JPG)

Here is the log: 
[FP09R2_log_2023-05-05_13-28-38.txt](https://github.com/Nesvilab/FragPipe/files/11405792/FP09R2_log_2023-05-05_13-28-38.txt)

There are enough peptides for mass calibration in MSFragger. MaxQuant runs through entirely without issues, so lack of peptides for RT alignment is not a general issue. 

The error says I may try other RT alignments. There are multiple options. How do they differ and which one is recommended. So far I used the default ciRT. 

Thanks!

**Comment by JM-Bader** [comment]
I now tried it with iRT and get the following error message: 
![image](https://user-images.githubusercontent.com/98888664/236458806-2a0239f0-02b4-4a7e-b441-53ce08cce0c3.png)

this is the log
[FP10_log_2023-05-05_14-32-56.txt](https://github.com/Nesvilab/FragPipe/files/11406262/FP10_log_2023-05-05_14-32-56.txt)

**Comment by anesvi** [comment]
Hi Jacob,

ciRT option aligns peptides from each run to a list of commonly observed peptides, but those are mostly human. So for mouse it does not work. If you spiked iRT peptides, then you can change to iRT option and they will be used for alignment.
I am not sure why you got an error. Did you spike in iRT peptides?

You can also select ‘automatic selection of reference run’ in which case all runs are aligned to of the runs (that is selected as reference).

I do not know what MaxQuant is doing for alignment, but I do not think there is any magic MaxQuant can do. You will either need iRT peptides spiked in, or enough overlap between each fraction and the run (fraction) selected as reference.

If you sure you have iRT peptides in there, can you share a few files with us. We will run throiugh the latest pre-release of the tools to see if there is any issue in EasyPQP with iRT alighment

Best,
Alexey

**Comment by anesvi** [comment]
So have you tried changing from ciRT to 'axiomatic selection' in EasyPQP tab?

**Comment by JM-Bader** [comment]
So far I have changed ciRT to iRT. 
I am happy to try axiomatic selection. 
I don't see any tab called 'EasyPQP' but I presume you refer to the 'Spec Lib' tab. (since ciRT is there).

Anyway, there is no 'axiomatic selection' option.
![image](https://user-images.githubusercontent.com/98888664/236466977-5f257d8e-d9e7-4a1e-a29c-6ae31951ec9d.png)

**Comment by JM-Bader** [comment]
of course, sorry! Will try that.

**Comment by JM-Bader** [comment]
FYI: That search has worked. It also lists the number of overlapping peptides. 
typically about 75% overlap
![image](https://user-images.githubusercontent.com/98888664/236485504-6b120440-332f-4514-8292-60466ac976c5.png)

Where do I find information on what 'automatic selection' does ? (different from default)?
And why is it not default?

**Comment by fcyu** [comment]
Hi @JM-Bader ,

`automatic selection`'s idea is quite simple. It picks the runs with the most IDs as the reference run. Then, pair-wisely align other runs to it using the overlapping IDs.

It is the default option. Maybe you changed it to something else, and FragPipe saved the changes in system cache. 

Best,

Fengchao

**Comment by JM-Bader** [comment]
Thanks again. 
FYI: it bothered my why I (unknowningly) ended up with a wrong but non-default setting and tried to figure out why. 
Actually, there are two discrepant defaults and it depends how one gets there... 
![image](https://user-images.githubusercontent.com/98888664/237054830-364b9462-6185-460f-989b-58de54df3ad2.png)

Note: one has ciRT as default, one the 'automatic....'
If a novice use starts using Fragpipe, it appears reasonable to stick to 'default' and then activate 'generate library', ending up with the wrong setting. I suggest you harmonize that.

**Comment by anesvi** [comment]
Thank you for your feedback. It is a bit tricky. For human experiments, ciRT is overall the safest option, because when building the library from fractionated data, there may not be enough common peptides for alignment to one of the fractions used as reference. We will think how to describe things better or adjust defaults based on your feedback.

**Comment by JM-Bader** [comment]
Understood. It can help to state on the interface that the default of setting XY is contextual and information on that can be found on the Fragpipe webpage section XY. (just an idea). As a user, it can be helpful to be guided to which settings make a difference (amongst all the settings)

**Comment by fcyu** [comment]
Thanks for the suggestion. I have added a tooltip (https://github.com/Nesvilab/FragPipe/commit/b5cfd5c67bdb355aea9f3e809b92d6d666f0c583) and some explanations to the tutorial (https://github.com/Nesvilab/FragPipe/commit/349ca5570c5628604bcf74c0602ee411e263227e).

Best,

Fengchao
