### ISSUE TITLE
issues with Thermo files

### ISSUE THREAD

**Issue by jennythemoon** [Nesvilab/FragPipe#1101]
Hello, I am trying to re-search a small set of Thermo Exploris data set I've searched successfully in the past but now it's giving me this error
`ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Did not get port information from server output within timeout.`
and stops. I can't figure out why. I've restarted, updated, re-downloaded everything and nothing changes. THe files are not corrupt as I can open them all on FreeStyle (vendor software)

Any thoughts on what could be going on?

[log_2023-05-06_12-03-20.txt](https://github.com/Nesvilab/FragPipe/files/11415302/log_2023-05-06_12-03-20.txt)

**Comment by fcyu** [comment]
The Thermo file reader was blocked by your computer (maybe due to some security configurations). Please convert your raw files to mzML files: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao
