### ISSUE TITLE
Re-starting workflow after crash

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#1103]
Hello,
I was running the Nonspecific-HLA-DIA workflow (DDA+DIA files) and the pipeline crashed in MSBooster. I have many files and I don't want to repeat the MSfragger search (takes 6 days), so as you previously suggested, I created a new manifest file with the pseudospectra (only DDA). However, because of that, the pipeline stops just after the spectral library building and it does not perform quantification with DIA-NN. How could I fix that? Should I restart the pipeline again with only DIA-NN activated and the original manifest file(DDA+DIA)?

Thanks for your help!

Best regards,

Emma

**Comment by anesvi** [comment]
Hi Emma,
You load pseudo-MS/MS (Q1...Q3 files)  and annotate them as DDA. You load the original mzML files and annotate them  as Quant-Only. That way they will be passed to DIA-NN for quant using the library you built from the other files. I think now that you have the library, you can just run load mzML for Quant-Only DIA-NN and actually pass path to the library you already have (and uncheck everything before DIA-NN)
Alexey

**Comment by ericart89** [comment]
Hello Alexey,

Thanks you very much for your advice. I did a small test before submitting it to the whole data but it crashes because it misses one ".pin" file from the original DIA (see logfile attached). Should I have this file?

As you recommended, I changed the manifest file by adding the pseudospectra as well as the original DIA with the "Quant-Only" tag. I tried to run starting from MSBooster (instead of DIA-NN only) because in this way I will have the "two-steps" pipeline for the future. 

Find the original and second manifest files attached as well, to see if I did any mistake.

Thanks again for your help.

Best,

Emma

[fragpipe.log](https://github.com/Nesvilab/FragPipe/files/11500155/fragpipe.log)
[original.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/11500160/original.fp-manifest.txt)
[from_ms_booster.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/11500161/from_ms_booster.fp-manifest.txt)

**Comment by fcyu** [comment]
Hi Emma,

You should set your DIA files to `DIA` data type, not `DDA` data type. From your log, they were set to `DDA` incorrectly.
```
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230213_INT001-02325-HLAIp_R02.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02359-HLAIp_R01.mzML	DDA
  - ./20230211_DIA_INT001-02359-HLAIp_R01_Q1.mzML	DDA
  - ./20230211_DIA_INT001-02359-HLAIp_R01_Q2.mzML	DDA
  - ./20230211_DIA_INT001-02359-HLAIp_R01_Q3.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02177-HLAIp_R01.mzML	DDA
  - ./20230211_DIA_INT001-02177-HLAIp_R01_Q1.mzML	DDA
  - ./20230211_DIA_INT001-02177-HLAIp_R01_Q2.mzML	DDA
  - ./20230211_DIA_INT001-02177-HLAIp_R01_Q3.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02176-HLAIp_R01.mzML	DDA
  - ./20230211_DIA_INT001-02176-HLAIp_R01_Q1.mzML	DDA
  - ./20230211_DIA_INT001-02176-HLAIp_R01_Q2.mzML	DDA
  - ./20230211_DIA_INT001-02176-HLAIp_R01_Q3.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02325-HLAIp_R01.mzML	DDA
  - ./20230211_DIA_INT001-02325-HLAIp_R01_Q1.mzML	DDA
  - ./20230211_DIA_INT001-02325-HLAIp_R01_Q2.mzML	DDA
  - ./20230211_DIA_INT001-02325-HLAIp_R01_Q3.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230202_CTE-BIO-065235-HLAIp_R01.mzML	DDA
  - /work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230202_CTE-BIO-065235-HLAIp_R02.mzML	DDA
  ```

Best,

Fengchao

**Comment by ericart89** [comment]
Hi Fengchao,

If you have a look at the manifests attached you will see that they were not tag as "DDA", but as "Quant-Only". I understood that this was what I had to do for DIA-NN to run, isn't it? 

This is the manifest:

/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230213_INT001-02325-HLAIp_R02.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02359-HLAIp_R01.mzML			Quant-Only
./20230211_DIA_INT001-02359-HLAIp_R01_Q1.mzML			DDA
./20230211_DIA_INT001-02359-HLAIp_R01_Q2.mzML			DDA
./20230211_DIA_INT001-02359-HLAIp_R01_Q3.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02177-HLAIp_R01.mzML			Quant-Only
./20230211_DIA_INT001-02177-HLAIp_R01_Q1.mzML			DDA
./20230211_DIA_INT001-02177-HLAIp_R01_Q2.mzML			DDA
./20230211_DIA_INT001-02177-HLAIp_R01_Q3.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02176-HLAIp_R01.mzML			Quant-Only
./20230211_DIA_INT001-02176-HLAIp_R01_Q1.mzML			DDA
./20230211_DIA_INT001-02176-HLAIp_R01_Q2.mzML			DDA
./20230211_DIA_INT001-02176-HLAIp_R01_Q3.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230211_DIA_INT001-02325-HLAIp_R01.mzML			Quant-Only
./20230211_DIA_INT001-02325-HLAIp_R01_Q1.mzML			DDA
./20230211_DIA_INT001-02325-HLAIp_R01_Q2.mzML			DDA
./20230211_DIA_INT001-02325-HLAIp_R01_Q3.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230202_CTE-BIO-065235-HLAIp_R01.mzML			DDA
/work/FAC/FBM/LLB/mbassani/ip_msbd/data/mzML/archive/20230202_CTE-BIO-065235-HLAIp_R02.mzML			DDA

Is not correct like that?

Best,

Emma

**Comment by fcyu** [comment]
But your log, which tells what the program really does, shows that they are specified as DDA. Maybe you specified the wrong manifest file?

Best,

Fengchao

**Comment by ericart89** [comment]
I don't think it's possible because I don't have any manifest like this one, isn't it possible that it does not recognize the "Quant-Only" tag and it automatically assigns it as DDA? Could it be that I am missing quotation in the tag? Or maybe everything should be in lowercase letters? I am using fragpipe 18v...is that option available for this version?

Best,

Emma

**Comment by fcyu** [comment]
You are correct. It should be `DIA-Quant`.

Best,

Fengchao

**Comment by ericart89** [comment]
Ahh okay, I will try it like that then! Thank you very much!

Best,

Emma
