### ISSUE TITLE
Very long PTMProphet  process

### ISSUE THREAD

**Issue by johnpleid** [Nesvilab/FragPipe#1104]
Hi I have lunched an open search with FragPipe 19.1 of a thermo Orbitrap File splitted in two because it was acquired by FAIMS
The process stuck at level " Please wait. PTMProphet is running. It can take a long time."
I stopped the run after  5 days thinking that something went wrong . Is this normal considering that only two raw files were running 

Can someone tell me from the log file in attachment if my settings are correct?
Thank you
[log_2023-05-09_22-33-02.txt](https://github.com/Nesvilab/FragPipe/files/11436421/log_2023-05-09_22-33-02.txt)

**Comment by fcyu** [comment]
First of all, you are not performing an open search
```
************************************MAIN SEARCH************************************
Checking database...
Deisotoping doesn't support low resolution tandem mass spectra. Changing deisotope to 0.
deisotope = 0. Changing deneutralloss to 0.
Parameters:
num_threads = 31
database_name = D:\Data\gio\testfragpipe\2023-04-17-decoys-uniprot-homo+sapiens-2022.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
```

Second, your variable modification setting is
```
variable_mod_01 = 15.9949 M 3
```

but your PTMProphet setting has
```
STY:79.966331,M:15.9949
```

Please adjust the parameters. If you are not sure how to, please start from loading the built-in workflows. Here are some tutorials if you need: https://fragpipe.nesvilab.org/

Best,

Fengchao

**Comment by johnpleid** [comment]
thank you Fengchao for the answer
Why is not an open serach? 
I set the parameter as in the tutorial,  setting "open" in workflow  ant Open Search in run PTM Sepherd
At wich level I introduce the phosphorylation? In Validation the PTM site localization was activated could be this the problem?

**Comment by fcyu** [comment]
> Why is not an open serach?

Because the precursor mass tolerance is 20 ppm

> I set the parameter as in the tutorial, setting "open" in workflow ant Open Search in run PTM Sepherd
At wich level I introduce the phosphorylation? In Validation the PTM site localization was activated could be this the problem?

Did you click "load" after selecting the workflow?

Best,

Fengchao

**Comment by johnpleid** [comment]
`Did you click "load" after selecting the workflow?`
yes but then I modified it...
The fragment mass tollerance is automatically set at 20 ppm but I acquired MSMS by a trap can i put 0.5 Da?

**Comment by fcyu** [comment]
Yes, you can. Did you also modify other parameters? Please do not unless you have a good reason.

Best,

Fengchao

**Comment by johnpleid** [comment]
ok i am testing
thank you

**Comment by anesvi** [comment]
Just To add a few comments-first, we do not normally use PTM-Prophet as part of the open workflow. Second, low mass accuracy ms2 data is not ideal for open searching (although it will work).

**Comment by johnpleid** [comment]
thank you i will keep it in mind for the next acquisitions
