### ISSUE TITLE
Error 'Corrupt files' 

### ISSUE THREAD

**Issue by sineadgreally** [Nesvilab/FragPipe#1105]
- Describe the issue or question:
I am running an MSFragger search with timsTof files of nearly 100 samples. I repeatedly get the error "there are corrupt files. Please remove those files and restart the task'.
I have removed the files and restarted and then move files are termed 'corrupt'.
I have re-copied and re-uploaded all of the files onto that computer drive and tried to restart the fragpipe and I still get the error.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-05-10_11-54-07.zip](https://github.com/Nesvilab/FragPipe/files/11443929/log_2023-05-10_11-54-07.zip)

**Comment by fcyu** [comment]
I am sorry but I couldn't get what the issue is. If the files are indeed corrupted, we can't do much except for letting you remove the files.

Best,

Fengchao
