### ISSUE TITLE
PhilosopherFilter failed with exitcode : 2 as combined.prot.xml running

### ISSUE THREAD

**Issue by Yck711** [Nesvilab/FragPipe#1107]
hello,

I'm running the DIA_Speclib_Quant mode, and received the following error:

~~~~~~~~~~~~~~~~~~~~
ERRO[21:19:24] Cannot decode packed binary. XML syntax error on line 3: invalid UTF-8 
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

Cancelling 6 remaining tasks

~~~~~~~~~~~~~~~~~~~~
It seems like something wrong in the "combined.prot.xml"
I would appreciate if the error could be solved! Here is the log file.

best,
Chengkun

[log_2023-05-13_17-09-23.txt](https://github.com/Nesvilab/FragPipe/files/11469801/log_2023-05-13_17-09-23.txt)

**Comment by fcyu** [comment]
Could you replace the Chinese in the folder names (e.g., 于成鲲) to English and try again?

Thanks,

Fengchao

**Comment by Yck711** [comment]
Thank you for your reply ,the error now is solved after doing so !

>
