### ISSUE TITLE
Proteinprophet 'Access is denied.'

### ISSUE THREAD

**Issue by BrendonSeale** [Nesvilab/FragPipe#1110]
Hello,

We have seen an issue with proteinprophet failing to complete on two different computers now. One of them is a Windows 10 virtual machine, the other a standalone Windows 11 system. The database and raw data files seem fine as they can be run on other computers without issue. Fresh installs of Java, python didn't seem to help. I have attached the log files for the two failing computers here. As far as I can tell the error is the same.

[log_2023-05-09_11-43-40.txt](https://github.com/Nesvilab/FragPipe/files/11490566/log_2023-05-09_11-43-40.txt)

[log_2023-05-16_12-43-55.txt](https://github.com/Nesvilab/FragPipe/files/11490577/log_2023-05-16_12-43-55.txt)

**Comment by fcyu** [comment]
Your files are in Dropbox folder. When Dropbox sync the files (it sync the files as soon as it detects changes), it will lock the files, which prevent other program from writing. Can you turn off Dropbox and try again?

Best,

Fengchao

**Comment by BrendonSeale** [comment]
Oh I see. I thought it might be something like that. I will give it at shot. For the virtual machine system do you suppose it is something similar?

Thank you!

**Comment by fcyu** [comment]
Hard to tell about the virtual machine one given the limited information. It depends one how the hard drives are mounted, and some other factors.

Best,

Fengchao

**Comment by fcyu** [comment]
This time, the error is different:
```shell
'C:\Users\cwong\AppData\Local\Temp\de144704-2b92-461f-98dc-8d413244b421/batchcoverage' is not recognized as an internal or external command,
operable program or batch file.
panic: Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files
```

But I don't know what `batchcoverage` is. Sorry that can't help anymore.

Best,

Fengchao
