### ISSUE TITLE
File System Error

### ISSUE THREAD

**Issue by jsalbin1** [Nesvilab/FragPipe#1111]
I have been running the DIA_SpecLib_Quant workflow for GPF-DIA data, which errors out at the DIA-NN quantification step for me. This seems to be some kind of file system error (-1073741819). If I take the library made by the DIA_SpecLib_Quant workflow and then separately run standalone DIA-NN 1.8.1, it will work without issues. When I asked about this on the DIA-NN board, the response was that it seemed like a bug in the version of DIA-NN running in FragPipe (1.8.2 beta 8).

https://github.com/vdemichev/DiaNN/issues/683

Is there some way to run 1.8.1 within the DIA_SpecLib_Quant workflow, or is there some common fix for the error message I'm getting? I've attached a log that shows the kind of message I'm getting.
[log_2023-04-29_21-47-01.txt](https://github.com/Nesvilab/FragPipe/files/11492275/log_2023-04-29_21-47-01.txt)

**Comment by fcyu** [comment]
There is no easy way to run 1.8.1 using the latest FragPipe except you change the source code and compile your custom version. But there was some other issues with 1.8.1 if I remember it correctly (that is why we use 1.8.2 beta 8). I suggest you either use the standalone version 1.8.1 with the `library.tsv` generated by FragPipe or wait for DIA-NN's next formal release (at that time, we will include it in FragPipe).

This is a duplicated issue of https://github.com/Nesvilab/FragPipe/issues/1094 and https://github.com/vdemichev/DiaNN/issues/683

Best,

Fengchao
