### ISSUE TITLE
How to load TMT integrator's annotation tables in headless mode ? 

### ISSUE THREAD

**Issue by Jmonod** [Nesvilab/FragPipe#1112]
- Describe the issue or question:
Hi Fengchao, 

The title says it all. While trying to analyze 3 phospho TMT runs (11 plex) on an hpc system, I'm receiving the following error : 

ERROR - Not all TMT groups have annotation files set. Check <b>Quant (Isobaric)</b> tab, <b>TMT-Integrator config</b>.

This occurs despite having my 3 annotations files in the same folder as the mzml files. Since annotation files are not indicated in  the workflow file, could it be a file labeling issue? 

- Upload your log file
There's no log file generated at this step.

**Comment by fcyu** [comment]
Right, there is no option to specify the annotation file in the headless mode although in the GUI mode you can. I will add this option in the future.

Currently, here must be only one annotation file with file name ending with `annotation.txt`. mzML files from the same experiment must be in the same folder (we will remove this limitation in the future).

Best,

Fengchao

**Comment by Jmonod** [comment]
Got it ! 

Thanks again Fengchao ! 

Joe

**Comment by Jmonod** [comment]
This means that currently we cannot run TMT integrator on multiple TMT runs in headless mode ? Each run, with it's assigned experiment label, needs it's own annotation file isn't ?

**Comment by fcyu** [comment]
You can. Put the mzML files from the same experiment group in the same folder (I think the GUI mode has the same requirement). For example, you have experiment `a`, `b`, and `c`. Then, the corresponding mzML files are in folder a, b, and c. Each folder has one annotation file.

Best,

Fengchao

**Comment by Jmonod** [comment]
Thanks again Fengchao !

**Comment by fcyu** [comment]
Added the description to the tutorial and printed help info.

Best,

Fengchao
