### ISSUE TITLE
No library.tsv output generated by only DDA-lib generation

### ISSUE THREAD

**Issue by She1111** [Nesvilab/FragPipe#1113]
- Describe the issue or question:
Hi Nesvilab,

I want to generate DDA spectral library without DIA data. Fragpipe ran on linux HPC and used DIA-SpecLib_Quant workflow. All Thermo.raw files were converted into mzML format by msconvert.exe in windows. I first had a try with 3 samples, but I could not find the library.tsv output but spectraRT.tsv and spectraRT_full.tsv files. Because I did not load DIA data, I could not activate DIA-NN for quantification. Could you please have a look?
Thanks in advance!

Best regards,
Shel

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-05-17_03-06-43.txt](https://github.com/Nesvilab/FragPipe/files/11498377/log_2023-05-17_03-06-43.txt)

**Comment by She1111** [comment]
Hi Fengchao,

Thank you for your quick reply! I am checking this issue with our HPC team. By the way, is it necessary to activate dia-nn to generate DDA-only spectral library by fragpipe?

Best regards,
Shel

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fcyu** [comment]
That part uses DIA-NN's prediction module to predict the spectra. It is not about DIA.

Best,

Fengchao

**Comment by She1111** [comment]
Hi Fengchao,

Our HPC team has checked the permission of using dia-nn and it has the right permissions. Our HPC has DIA-NN/1.8.1 module and it is run perfectly without any errors occurring. I notice the version of dia-nn integrated in fragpipe is ver.1.8.1.8. Could I install ver.1.8.1 instead the beta version in fragpipe and test whether it could be run or not?

Best,
Shel

**Comment by fcyu** [comment]
Not suggested but you can have a try.

Best,

Fengchao

**Comment by She1111** [comment]
> 



> Not suggested but you can have a try.
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Luckily, after I replace dia-nn in tools folder and 'module load DIA-NN/1.8.1' before launch fragpipe, it works :). Although I do not know what the issue is...

Best,
Shel

**Comment by fcyu** [comment]
There are some issues with the FDR control in version 1.8.1 if you are not using the deep-learning predicted spectral library from the standalone version. In a word, there MIGHT BE more false positives if you use it with FragPipe.

Best,

Fengchao

**Comment by She1111** [comment]
> There are some issues with the FDR control in version 1.8.1 if you are not using the deep-learning predicted spectral library from the standalone version. In a word, there MIGHT BE more false positives if you use it with FragPipe.
> 
> Best,
> 
> Fengchao

Then I'd better find an appropriate way to use the latest dia-nn. Thank you again for your perfect effort!

Best,
Shel
