### ISSUE TITLE
ERROR: src/diann.cpp: 19427: Cannot load spectral library in DIA_Speclib_Quant workflow on Fragpipe v19.1

### ISSUE THREAD

**Issue by ajay16bharadwaj** [Nesvilab/FragPipe#1114]
- Describe the issue or question:

Hello, 

I'm running Fragpipe [ v19.1 ] in headless mode on our HPC system and I'm getting the below error on the DIA_Speclib_Quant workflow.

5 files will be processed
[0:00] Loading spectral library library.tsv
cannot read the file
ERROR: src/diann.cpp: 19427: Cannot load spectral library
Process 'DIA-NN' finished, exit code: 255
Process returned non-zero exit code, stopping

I have 3.9+ version of python with easypqp [ v0.1.36 ] and pyopenms [ v2.7.0 ] installed. 

Attaching the log file and the snapshot of my python/easypqp installations.  I'd appreciate any help in resolving this.  

Thank you so much!!

-Ajay Bharadwaj

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
![image](https://github.com/Nesvilab/FragPipe/assets/329585
[log_2023-05-18_10-54-08.txt](https://github.com/Nesvilab/FragPipe/files/11510550/log_2023-05-18_10-54-08.txt)
85/2f7427ca-dfce-4891-86e2-fb3dfd7c38e4)

**Comment by fcyu** [comment]
You did not enable EasyPQP to generate the library.tsv:

```shell
speclibgen.run-speclibgen=false
```

Best,

Fengchao
