### ISSUE TITLE
TMT-SILAC proteome DDA

### ISSUE THREAD

**Issue by tomonorikaneko** [Nesvilab/FragPipe#1115]
Hello,

I'd like to process DDA proteome data from TMT-SILAC labelled samples. We prepared a dozen of SILAC samples (mixture of light and heavy Lys/Arg-labelled cell lines). Each SILAC sample was labelled with different TMT channel, and these TMT-labelled samples were combined as a 16-plex for a mass spec injection. I'd like to quantify TMT-labelled heavy and light proteomes separately, and would like to know what may be the best way to process the data with FragPipe. While I can add K8(+TMT) or R10 as a fixed modification for heavy-TMT peptides in the TMT workflow, I'd like know if I can exclude peptides that do not contain a K or R from proteome quantification, because I cannot tell if these peptides without a K/R originate from the heavy or light SILAC cell line. 

Thank you,
Tomo

**Comment by fcyu** [comment]
Hi Tomo,

We don't support TMT+SILAC data.

Best,

Fengchao

**Comment by fcyu** [comment]
Yes, the `psm.tsv` table will have TMT channels, but they need to "reorganize" the PSMs by "splitting" SILAC L/M/H to have, say, `3 * 10` channels, and do the normalization by themselves.

Best,

Fengchao

**Comment by anesvi** [comment]
yes, and at that stage filter out peptides without any K or R. So Tomo, you can get to PSM.tsv containing PSM level data with quantification, but will need to take from use and do your own normalization and PSM to protein roll-up.

**Comment by MKoesters** [comment]
Are there plans to support this type of experiment?

And I have 3 other questions
Why is LFQ used/required?
If separate searches are performed as indicated by OP, reorganizing of PSMs  and separate rollups are not needed, right?
Would separate searches for SILAC L/H change disturb normalization?

I have my search running anyway and will try if I can do something useful with the data :)

Best,
Manuel
