### ISSUE TITLE
About the diaPASEF file and its analysis

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1116]
Hi, 

I was using fragpipe to analyze the diaPASEF files, at first these files were drwxrwxr-x permissions but it would report an error, so I changed it to drwxr-xr-x and it worked fine.

But I found that some files were modified during analysis (because I saw that the last modification time of the files was different), like in the picture below (it's a ddaPASEF file).

<img width="401" alt="屏幕截图 2023-05-20 093509" src="https://github.com/Nesvilab/FragPipe/assets/74947198/7bd31b6e-56f8-41d6-a7df-e8c19789d9d1">

Two of the ten ddaPASEF files were modified in this way, and errors were reported for these two files, with the following error report:

`ARN umich.ms.fileio.filetypes.bruker.BrukerTdfFile - tims_read_scans_v2() returned 0, which normally means an error has occurred. However, frame 4212 contained zero peaks according to analysis.tdf. Please, report to developers. [main] WARN umich.ms.fileio.filetypes.bruker.BrukerTdfFile - tims_read_scans_v2() returned 0, which normally means an error has occurred. However, frame 4221 contained zero peaks according to analysis.tdf. Please, report to developers.`

I am very new to diaPASEF analysis, so I am confused. Does fragpipe modify the analysis.tdf file, or am I doing something wrong with the file. If this modification is caused by fragpipe, is it a normal process or is it a bug. And why does it report errors like the one above, is it because the analysis.tdf file was modified, or is there a problem with the .d file itself?

Thanks,
LeeLee

**Comment by fcyu** [comment]
Hi LeeLee,

FragPipe together with MSFragger and IonQuant don't modify any input LC-MS files (mzML, raw, .d, and tdf). As to the Bruker library that was used to load the .d and tdf, as far as I know, it also does not modify the files. Could you test again? 

As to the error, could you share that specific .d folder with us? I can send you a link to upload the files if you need.

Thanks,

Fengchao

**Comment by lbwfff** [comment]
Hi Fengchao.

Thanks for your quick reply, I re-downloaded the analysis.tdf file and re-analyzed the data, the previous error did not appear again. I guess I may have corrupted the file during downloading or unpacking?
I will close this issue.

Thanks，
LeeLee

**Comment by lbwfff** [comment]
> Hi LeeLee,
> 
> FragPipe together with MSFragger and IonQuant don't modify any input LC-MS files (mzML, raw, .d, and tdf). As to the Bruker library that was used to load the .d and tdf, as far as I know, it also does not modify the files. Could you test again?
> 
> As to the error, could you share that specific .d folder with us? I can send you a link to upload the files if you need.
> 
> Thanks,
> 
> Fengchao

Hi，Fengchao

I analyzed a batch of diaPASEF files, and I'm sure fragpipe did make modifications to the analysis.tdf file in the .d file during the analysis (I'm not sure if it modified or rebuilt an analysis.tdf file), but this It seems to have no effect on the analysis.
I also encountered some errors during the analysis, such as the following:

```
[19:01] File #7/20
[19:01] Loading run /home/leelee/share/serum/DIA/C017_Slot1-14_1_3882.d
ERROR: cannot read frame 35871
ERROR: cannot read frame 35888
ERROR: cannot read range 0-408 from frame 35863
ERROR: cannot read frame 35905
[22:11] 29542 library precursors are potentially detectable
[22:11] Processing...
[22:42] RT window set to 2.41737
[22:42] Ion mobility window set to 0.0276679
[22:42] Recommended MS1 mass accuracy setting: 18.9418 ppm
[23:03] Removing low confidence identifications
[23:03] Removing interfering precursors
[23:05] Training neural networks: 23562 targets, 22964 decoys
[23:09] Number of IDs at 0.01 FDR: 8993
[23:09] Calculating protein q-values
[23:09] Number of protein isoforms identified at 1% FDR: 1516 (precursor-level), 1393 (protein-level) (inference performed using proteotypic peptides only)
[23:09] Quantification
```
Such errors seem to have no impact on the analysis process, but I still want to ask will this affect the results?

Thanks,

LeeLee

**Comment by lbwfff** [comment]
I think this may be caused by DIANN, because these diaPASEF files are only quantified.
