### ISSUE TITLE
Modification localisation

### ISSUE THREAD

**Issue by andrewjmc** [Nesvilab/FragPipe#112]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [X] feature request
  - [ ] question

Is there a plan to release the modification localisation pipeline as part of MSFragger?

Many thanks,

Andrew

**Comment by andrewjmc** [comment]
I noticed that modification localisation is turned on by default in Peptide Prophet but couldn't see how this alters the results.

However, I now see that you have published DeltaMass (https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.8b00728) and this is probably the tool I am looking for!

If so, I will close this issue.

**Comment by anesvi** [comment]
Delta mass is a bit different, it shows the histograms of mass shifts but does not localize really

Are you asking about localizing mass shifts in open search?

Or localizing modifications specified as variable modifications?

**Comment by andrewjmc** [comment]
Thanks for getting back to me. Yes, localising mass shifts in open search (as you presented in the paper)

**Comment by anesvi** [comment]
If running open searches with shifted ions turned on, then internally MSFragger put the mass shift on every aminoacid to see what gives the highest score. We do not write that information in pepXML file yet though. Also, it does not have any site localization probability, just the location(s) of the highest score.

PTMProphet can do localization of open search mass shifts as well. It is a bit slow though, and we have not added it to FragPipe yet. We can do that in one of the next releases.

So we need to discuss internally in my group the best strategy.

I will keep you updated.

Thanks for using MSFragger.

Best,
Alexey

**Comment by andrewjmc** [comment]
Many thanks.
