### ISSUE TITLE
Clarification of max occurrences for variable modifications

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#1120]
When setting the max occurrences for variable modifications in the MSFragger tab, does the number apply to each residue for each modification? Or does it apply for all residues for each modification? E.g., if I have set the 'site' variable to MP and set the 'max occurrences' to 3, does that mean 3 modified M and 3 modified P would be allowed per peptide, provided I have set the max variable mods on a peptide to 6?

<img width="292" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/54612207/94f98982-500f-4c5c-9a73-7f5021ded4f1">

**Comment by fcyu** [comment]
It applies for all residues for each modification. In your example, the 3 means the total number of `M` and `P` should be <= 3 (i.e., `3 M + 0 P`, `2 M + 1 P`, `1 M + 2 P`, `0 M + 3 P`).

Best,

Fengchao
