### ISSUE TITLE
about “Process 'MSFragger' finished, exit code: 1”

### ISSUE THREAD

**Issue by Hanqing1205** [Nesvilab/FragPipe#1121]
- Describe the issue or question:
- Hello, 
- I have met a question about“Process 'MSFragger' finished, exit code: 1”; when I was running MSFragger in cleavage“ENZYMATIC”, it was normal. But when I set the cleavage "SEMI", it reports the error"Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping". Do I have any methods to solve this?
Looking forward to your reply. Thanks.
<img width="732" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/133129481/bb15a795-b737-4201-a60d-df90968ee524">

[log_2023-05-24_21-03-38.txt](https://github.com/Nesvilab/FragPipe/files/11554860/log_2023-05-24_21-03-38.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
`java.lang.OutOfMemoryError: Java heap space`. Your computer does not have enough memory. It seems that there are only 10 GB free memory available. 

Best,

Fengchao
