### ISSUE TITLE
msstats.csv compatability with MSstatsTMT

### ISSUE THREAD

**Issue by hboekweg** [Nesvilab/FragPipe#1123]
I'm trying to obtain the msstats.csv file for a TMT run. 
Currently I'm getting one msstats.csv file for each mixture, but it looks like the most recent MSstatsTMT package is built to only accept one msstats.csv file. I tried updating everything (MSFragger, IonQaunt, and Philosopher) and have checked that they're all the most recent version. 

Am I missing something or is it expected that MSFragger results in multiple msstats.csv files?

**Comment by fcyu** [comment]
We have made the changes recently. The next release will have a single msstats.csv file with all plex.

Best,

Fengchao

**Comment by hboekweg** [comment]
I see. Thanks. 
Is there an expected release date for the new version?

**Comment by fcyu** [comment]
Yes, if everything goes well, this week or next week.

**Comment by lolaakinlaja** [comment]
Hello, I also have a question along these lines. I have LFQ phospho data that I would like to analyse with MSStats but I have the msstats.csv file from ionquant I believe and does this go well to msstatsptm? Or shall I also wait for the new release? The file I currently have does not have any columns for PTMs. Thanks so much for your help

**Comment by fcyu** [comment]
The `msstats.csv` from IonQuant is only for the MSstats, not for the MSstatsPTM. You need to wait for the next release.

Best,

Fengchao

**Comment by lolaakinlaja** [comment]
thanks so much for your quick response. Glad to hear this release is coming really soon!

**Comment by fcyu** [comment]
FYI, the new version has been released: https://github.com/Nesvilab/FragPipe/releases/latest

Best,

Fengchao

**Comment by lolaakinlaja** [comment]
Hi Fengchao,
I just want to double check, when I load the phospholfq workflow, the msstats.tsv output is still not compatible with msttatsptm because its from ionquant. I can't use TMT integrator since my data is lfq data right? (thermo dda .raw files). I tried the search again and still don't have a compatible msstats file

**Comment by fcyu** [comment]
Sorry for the confusion. For MSstatsPTM, could you try this: enable `generate msstats files` in the `FDR filter and report` panel, and disable IonQuant. The file is from Philosopher, not IonQuant, but we never tested using the LFQ data.

Best,

Fengchao

**Comment by lolaakinlaja** [comment]
Thanks, will try that and let you know how it goes
