### ISSUE TITLE
Percolator: `Final list yields 0 target PSMs with q<0.01.`

### ISSUE THREAD

**Issue by ashwinkallor** [Nesvilab/FragPipe#1125]
Hi, 

While running Fragpipe, the pipeline seems to break at the "Percolator" step. The log file attached does not state what is the error specifically but all jobs get cancelled while running Percolator. I am not sure what is causing this since I cannot detect what is causing this error. Could you please take a look at the log file and let me know why the pipeline fails at this step? 

Thanks in advance,
Ashwin 
[percolator_error.txt](https://github.com/Nesvilab/FragPipe/files/11584333/percolator_error.txt)

**Comment by fcyu** [comment]
Hi Ashwin,

`Final list yields 0 target PSMs with q<0.01.`. Can you remove `1fmol_2.mzML` and try again?

Thanks,

Fengchao

**Comment by ashwinkallor** [comment]
Thanks for your reply, fengchao. I've relaunched the job after removing '1fmol_1.mzML'. I'll let you know if I run into this again.

**Comment by ashwinkallor** [comment]
Hi Fengchao,

Unfortunately, despite removing '1fmol_2.mzML' and re-running fragpipe, the error persists, as you can see in the attached log-file.
[percolator_error2.txt](https://github.com/Nesvilab/FragPipe/files/11585538/percolator_error2.txt)

Any suggestions on what more needs to be done at this stage? Awaiting your reply.

**Comment by fcyu** [comment]
Another file, `100fmol_Spikein_2.mzML`, has the same issue: no IDs. You can keep removing such files when you see a similar error from Percolator.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @ashwinkallor ,

You can also submit an issue repost to Percolator repository (https://github.com/percolator/percolator/issues) is you want.

Best,

Fengchao

**Comment by ashwinkallor** [comment]
Thanks a lot, Fengchao. The issue was resolved though I had to remove 6 files from the pipeline for Percolator to work. This is okay for a large dataset (like this one) but it would reduce our throughput for smaller datasets. Perhaps I should raise this in the Percolator forum. I am closing this one now.
