### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by feng6544** [Nesvilab/FragPipe#1126]
Hi,I encountered a FileNotFoundException while using MSFragger，but I can't find the files related to it in my computer directory.

![image](https://github.com/Nesvilab/FragPipe/assets/93083550/d1ae134c-199f-4c74-abfe-4c1f52fef755)

Here is my log file.
[log_2023-05-30_22-00-26.txt](https://github.com/Nesvilab/FragPipe/files/11600820/log_2023-05-30_22-00-26.txt)

**Comment by fcyu** [comment]
You skipped many steps, such as PSM validation, protein inference, and FDR filtering, when running FragPipe. As a beginner, please use our built-in workflows.

Best,

Fengchao

**Comment by feng6544** [comment]
If I choose built-in workflows, do I need to uncheck all subsequent modules？

**Comment by fcyu** [comment]
No. For the first time using FragPipe, do not change anything except for the database, enzyme, and variable modifications if you have chemical labelling or PTM enrichment. Here are some tutorials: https://fragpipe.nesvilab.org/ in case you need.

Best,

Fengchao

**Comment by feng6544** [comment]
I have encountered another issue where ProteinProphetseems to be unable to run. Where should I check my parameters and input files

I went to check the  shepherd.config  file，I don't seem to be able to find the file in the dataset path，file is psm.tsv



Here is my error message

ProteinProphet [Work dir: D:\MSFragger9738]
C:\mysoftware\fragpipe\tools\philosopher_v4.8.1_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined D:\MSFragger9738\filelist_proteinprophet.txt
INFO[11:21:52] Executing ProteinProphet  v4.8.1             
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105101442-exported (Windows_NT-x86_64))
 (no FPKM) (no groups) (using degen pep info)
Reading in D:\MSFragger9738\interact.pep.xml...
panic: Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc000028cb0, 0x6c}, {0x990dbc, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ExecutingBinary({0xb09600?, 0xc000178260?}, {0x990dbc, 0x5})
	/workspace/philosopher/lib/msg/msg.go:209 +0x6e
philosopher/lib/ext/proteinprophet.ProteinProphet.Execute({{0xc000021aa0, 0x57}, {0xc000021b00, 0x58}, {0xc000021b60, 0x58}, {0xc000021aa0, 0x57}, {0xc000021b00, 0x58}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:110 +0x7d2
philosopher/lib/ext/proteinprophet.Run({{0xc0000c2510, 0x24}, {0xc00009f710, 0x10}, {0xc0000a45a0, 0x45}, {0xc00009a660, 0x1f}, {0xc0000a28d0, 0x16}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:62 +0x3b3
philosopher/cmd.glob..func14(0x258b740?, {0xc00006c0f0, 0x1, 0x5})
	/workspace/philosopher/cmd/proproph.go:26 +0xb4
github.com/spf13/cobra.(*Command).execute(0x258b740, {0xc00006c0a0, 0x5, 0x5})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x258c2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
Error: multiple databases referenced by D:\MSFragger9738\interact.pep.xml
Use RefreshParser to update all input files to common database
ERRO[11:21:53] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

**Comment by danielgeiszler** [comment]
Please upload the entire log.

**Comment by feng6544** [comment]
[log_2023-05-31_11-21-53.txt](https://github.com/Nesvilab/FragPipe/files/11608392/log_2023-05-31_11-21-53.txt)

**Comment by danielgeiszler** [comment]
You search failed and you did not match enough peptides. Please verify that the MSFragger search settings match the experiment settings.

**Comment by feng6544** [comment]
Do you mean that after I load build in workflows, I still need to configure MSFragger? Is the experimental configuration what I need?

**Comment by fcyu** [comment]
Hi @feng6544 ,

FragPipe got no IDs from your data. Please double check your data and enzyme settings.

Best,

Fengchao

**Comment by feng6544** [comment]
Hello，my input file was converted from. raw to. mzML, and I believe that the error was caused by a configuration error when using MSConvert. Therefore, I added scan Summing and zero samples and encountered a new error. Do I need to modify my settings.
![image](https://github.com/Nesvilab/FragPipe/assets/93083550/f62ae0ff-08b0-4b38-9e38-3a864c25565a)
[log_2023-06-01_09-26-29.txt](https://github.com/Nesvilab/FragPipe/files/11620022/log_2023-06-01_09-26-29.txt)

**Comment by fcyu** [comment]
Adding scan summing for Thermo data does not help but make the data worse. It also caused the error in your log file.
