### ISSUE TITLE
Error in FreeQuant: System cannot find file specified for TMT-10phospho workflow.

### ISSUE THREAD

**Issue by alyssaxin** [Nesvilab/FragPipe#1127]
Hello,
 
I am running the TMT-10 phospho workflow on a set of TMT-10 data with 22 plexes, 6 fractions each. I have turned off MS1 quant but I still get the error message at the FreeQuant process. I am not too sure why FragPipe is running FreeQuant when I have turned off MS1 quant, can anyone please advise?

During the FreeQuant run, the first plex runs fine but the second plex always errors out. I have checked whether it is my file that is corrupted, but it is not. My files are all in the same directory.

I have attached my log file here. Please advise on how to proceed, Thank you.

Alyssa
[log_2023-05-24_11-54-47.txt](https://github.com/Nesvilab/FragPipe/files/11610513/log_2023-05-24_11-54-47.txt)

**Comment by fcyu** [comment]
Hi Alyssa,

The error was not from FreeQuant but from the filter command. You were using a pre-released Philosopher 5.0.0-RC14 but FragPipe 19.1. They are not compatible. You need to either use pre-released or formal released versions for all tools.

ps. We are going to release a next version today. Maybe you can wait a little bit.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Ah okay I see. Thank you so much for the prompt reply. I'll wait for the updated FragPipe version then.

Cheers,
Alyssa

**Comment by fcyu** [comment]
Hi Alyssa,

The new version has been released. Please upgrade FragPipe, MSFragger, IonQuant, and Philosopher all together.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Sorry for bothering, but I've gotten another error after upgrading to the newest version of FragPipe. It says PTM Prophet cannot be started. Can you please advise? 

I've attached my log in this message.
[log_2023-06-02_11-45-30.txt](https://github.com/Nesvilab/FragPipe/files/11631684/log_2023-06-02_11-45-30.txt)

Thanks a lot,
Alyssa

**Comment by fcyu** [comment]
Can you confirm if the file `C:\ALYSSA\fragpipe\tools\PTMProphet\PTMProphetParser.exe` exist and can execute? You can open a command line using cmd.exe and execute that binary file to test.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

I've executed the PTMProphetParser in cmd and gotten this, does this mean that its running?

Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user bioinfo-64 7>cd C:\ALYSSA\fragpipe\tools\PTMProphet

C:\ALYSSA\fragpipe\tools\PTMProphet>start PTMProphetParser.exe

C:\ALYSSA\fragpipe\tools\PTMProphet>

I'm not too familiar with executing binary files, so if I'm not doing it right, please advise.

Thanks,
Alyssa

**Comment by fcyu** [comment]
HI Alyssa,

You were doing mostly right. Just remove `start ` and try again.

Best.

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Thank you for advising. Here's the cmd interface after I've executed PTMProphetParser.exe.

Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user bioinfo-64 7>cd C:\ALYSSA\fragpipe\tools\PTMProphet

C:\ALYSSA\fragpipe\tools\PTMProphet>PTMProphetParser.exe
USAGE: PTMProphetParser.exe <OPTIONS> <input_file.pep.xml> [<output_file>]

OPTIONS
        NOUPDATE        Don't update modification_info tags in pepXML
        EM=<number>:    Set EM models to <number> which can be 0, 1 or 2:
                        0 -> no EM,
                        1 -> Intensity EM Model Applied Only,
                        2 -> Intensity and Matched Peaks EM Models Applied(default),
                        3 -> Matched Peaks EM Model Applied Only
        KEEPOLD  Option to retain old PTMProphet results in the pepXML file (off by default).
        VERBOSE  Option to produce WARNINGS to help troubleshoot potential PTM shuffling or mass difference issues (off by default).
        MODPREC=<integer>        Use specified number of digits after the decimal point for PTMs (default=0 standard or 3 in MASSDIFFMODE).
        STATIC   Use static fragppmtol for all PSMs instead of dynamically estimates offsets and tolerances (off by default).
        FRAGPPMTOL=<number>      When computing PSM-specific mass_offset and mass_tolerance, use specified default +/- MS2 mz tolerance on fragment ions (default: 200, 15 in STATIC mode).
        DALTONTOL=<number>       When computing PSM-specific mass_offset and mass_tolerance, use specified +/- MS2 mz Daltontolerance on fragment ions (default: off by default, setting overrides FRAGPPMTOL=).
        PPMTOL=<number>  Use specified +/- MS1 ppm tolerance on peptides which may have a slight offset depending on search parameters (e.g. iTRAQ4plex) (default=1 ppm).
        MINPROB=<number>         Use specified minimum probability to evaluate peptides (default=0.9).
        MAXTHREADS=<number>      Use specified number of threads for processing (default=1).
        OSCOREMODE       Encode modified peptide string with oscore instead of probability.
        QUANTMODE        Score only peaks that have an intensity in both versions of the peptide
        MASSDIFFMODE     Treat the mass difference between measured and theoretical mass as a modification and localize (default: MODPREC=3)
        EXCLUDEMASSDIFFMIN=<number>      Minimum mass difference excluded for MASSDIFFFMODE analysis (default=0).
        EXCLUDEMASSDIFFMAX=<number>      Maximum mass difference excluded for MASSDIFFFMODE analysis (default=0).
        LABILITY         Compute Lability of PTMs
        DIRECT   Use only direct evidence for evaluating PTM site probabilities
        DENOISE  Remove presumed noise before applying localization (default: off)
        NOSTACK  Disallow stacking of multiple PTMs at the same amino acid location
        IFRAGS   Use internal fragments for localization (default: do not use internal fragments)
        AUTODIRECT       Use direct evidence when the lability is high, use in combination with LABILITY
        MAXFRAGZ=<integer>       Limit maximum fragment charge (default: precursor charge, negative values subtract from precursor charge).
        MINO=<integer>   Use specified number of pseudo-counts when computing Oscore (default=0).
        NOMINOFACTOR     Disable MINO factor correction when MINO= is set greater than 0 (default: apply MINO factor correction)
        NIONS=   Use specified N-term ions, separate multiple ions by commas (default: a,b for CID, c for ETD)
        CIONS=   Use specified C-term ions, separate multiple ions by commas (default: y for CID, z for ETD)
        MASSOFFSET=<number>      Adjust the massdiff by offset <number> (default: 0)
        <amino acids, n, or c>:<mass_shift>:<neut_loss1>:...:<neut_lossN>,<amino acids, n, or c>:<mass_shift>:<neut_loss1>:...:<neut_lossN>     Specify modifications (default: STY:79.9663,MW:15.9949 )

VERSION: TPP v6.3.2 Arcus, Build 202305092202-8951 (Windows_NT-x86_64)

C:\ALYSSA\fragpipe\tools\PTMProphet>

What should I do next? Thank you.

Alyssa

**Comment by fcyu** [comment]
Hi Alyssa,

You should be good to run PTMProphet. Could you try to run FragPipe again to see if the error persists?

Thanks,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Yes, I will run it again and see if there is still an error, I will update you if there is.

Thanks,
Alyssa

**Comment by alyssaxin** [comment]
Hi Fengchao,

It seems that it can be run properly now, however, I have another problem, so sorry about that.

In my latest error, I got the message:

There are more than one 'COLONREF' in the column names. Repeated reference tag at column: 51, 52. Please make sure the reference tag is unique among all the column names.
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping

I believe this is because in the 22Plex for the data, both channels 130c and 131 has similarly been labelled as COLONREF, which are the pooled internal standards. Is there a way for me to get around this error?

I've attached my experimental design .csv file and the log from the run here.

Thank you so much for your help so far.

Cheers, 
Alyssa
[log_2023-06-05_04-24-31.txt](https://github.com/Nesvilab/FragPipe/files/11649293/log_2023-06-05_04-24-31.txt)
[PDC_study_experimental_06052023_141244.csv](https://github.com/Nesvilab/FragPipe/files/11649294/PDC_study_experimental_06052023_141244.csv)

**Comment by fcyu** [comment]
Hi Alyssa,

Could you change the reference channels in different experiments to something like COLONREF_1, COLONREF_2.... No need to change the TMT-Integrator parameters.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Hope this message finds you well. I've changed all the reference channels in each annotation file to COLONREF_1, COLONREF_2, ..., COLONREF_23, but it still gave the same error. Do you have any idea why?
[log_2023-06-07_05-03-55.txt](https://github.com/Nesvilab/FragPipe/files/11671625/log_2023-06-07_05-03-55.txt)

Thanks for helping out,
Alyssa

**Comment by fcyu** [comment]
Hi Alyssa,

There are `130C COLONREF_22` and `131N COLONREF_23` in `22_annotation.txt`, but you can only have one reference channel in one plex.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

In the experimental design of the data I'm running, they did put the pooled standard in both channels for the 22nd plex. Can I have the option to label 130C as empty? Do you know if that would affect my analysis?

Cheers, 
Alyssa

**Comment by fcyu** [comment]
You can rename one of then to other name.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Alright, noted. I will rename and try again, thank you for the help.

Alyssa

**Comment by alyssaxin** [comment]
Hi Fengchao,

The run was successful! Thank you for all your help, it was very much appreciated.

Cheers, 
Alyssa
