### ISSUE TITLE
EasyPQP convert error

### ISSUE THREAD

**Issue by She1111** [Nesvilab/FragPipe#1129]
- Describe the issue or question:
Hi Fengchao,

I had a problem of 'EasyPQP convert error' when I was going to generate spectral library. I have checked previous issues about this problem, but I do not know which is the exact problem in my case. Here is some information:
* Every mzML file is about 3GB;
* The remote linux has 219GB RAM of each node. I requested 20 cores for 20 samples, but it still called 'OUT OF MEMORY' error;
* I ran fragpipe successfully with 9 pre-experiment DDA results with 'RAM=0 (default)' and it reported that 'JVM started with 111 GB memory'. Should I set RAM with 20 samples this time?
* I plan to convert .raw files again if there is something wrong during previous converting.

Best,
Shel

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[DDA_speclib_3.txt](https://github.com/Nesvilab/FragPipe/files/11635948/DDA_speclib_3.txt)

**Comment by guoci** [comment]
@She1111 The errors occur in the EasyPQP `convert` process and all got a SIGKILL, which indicates that it is terminated externally.
Do you know why it was terminated externally?

**Comment by She1111** [comment]
Hi Guoci, hi Fengchao,

Then I will request another node with larger RAM to see whether it could run or not. Are there any other reasons that could cause this problem?

Best,
Shel

**Comment by She1111** [comment]
Hi Guoci, hi Fengchao,

I used another large memory cluster with 900GB RAM and it run well on EasyPQP step! Thank for your help!

Best,
Shel
