### ISSUE TITLE
msfragger_pep_split.py error

### ISSUE THREAD

**Issue by qingfengweiwei** [Nesvilab/FragPipe#113]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:
 
  Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

Traceback (most recent call last):
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 342, in <module>
    main()
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 332, in main
    run_msfragger()
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 136, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\crc\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-jar', '-Dfile.encoding=UTF-8', 'E:\\drivers\\MSFragger-20190222\\MSFragger-20190222\\MSFragger-20190222.jar', 'fragger.params', 'E:\\drivers\\liver1-F10-R1.mzML', '--partial', '0']' returned non-zero exit status 1.

## System info
 
System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_181, Java HotSpot(TM) Client VM, Oracle Corporation
FragPipe version 9.1
MSFragger version 20190222
Philosopher version 20190418 (build 201904182204) 
Python 3.7 
### Genral proteomics experiment description

...

### Input data files  
 one raw data 

### Sequence database
  Human_20190401_reviewed ,34MB
----

## Attach fragger.params file
```
database_name = C:\drivers\moda\database\uniprot-human_reviewed_20190401_reverse.fasta
num_threads = 0			# 0=poll CPU to set num threads; else specify num threads directly (max 64)

precursor_mass_lower = 0
precursor_mass_upper = 100
precursor_mass_units = 0			# 0=Daltons, 1=ppm
precursor_true_tolerance = 20
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 20
fragment_mass_units = 1			# 0=Daltons, 1=ppm
isotope_error = 0			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and phosphorylated peptides (on any residue)
precursor_mass_mode = selected
shifted_ions = 0
shifted_ions_exclude_ranges = (-1.5,3.5)
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 1			# maximum value is 5
clip_nTerm_M = 1
#maximum of 7 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
allow_multiple_variable_mods_on_residue = 1			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50
report_alternative_proteins = 0			# 0=no, 1=yes
precursor_charge = 1 4			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter
digest_min_length = 7
digest_max_length = 30
digest_mass_range = 500.0 2000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 2			# set maximum fragment charge state to analyze (allowed max 5)
#open search parameters
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0.00			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1.00			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0
# spectral processing
minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 100
min_fragments_modelling = 3
min_matched_fragments = 6
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range
# additional modifications
add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000
add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000
```

## Run log output

System info:
System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_181, Java HotSpot(TM) Client VM, Oracle Corporation

Version info:
FragPipe version 9.1
MSFragger version 20190222
Philosopher version 20190418 (build 201904182204)

LCMS files:
  Experiment/Group: 
  - E:\drivers\liver1-F10-R1.mzML

10 commands to execute:
Workspace [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe workspace --clean
Workspace [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe workspace --init
MsFragger [Work dir: E:\New Folder (2)]
C:\Users\crc\AppData\Local\Programs\Python\Python37\python C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py 8 "java -jar -Dfile.encoding=UTF-8" E:\drivers\MSFragger-20190222\MSFragger-20190222\MSFragger-20190222.jar E:\New Folder (2)\fragger.params E:\drivers\liver1-F10-R1.mzML
MsFragger
java -cp E:\drivers\FragPipe_v9.1.exe umich.msfragger.util.FileMove E:\drivers\liver1-F10-R1.pepXML E:\New Folder (2)\liver1-F10-R1.pepXML
Crystal-C [Work dir: E:\New Folder (2)]
java -cp "C:\Users\crc\AppData\Local\Temp\fragpipe\common-deps-1.0.3.jar;C:\Users\crc\AppData\Local\Temp\fragpipe\original-CrystalC-1.0.4.jar" Main E:\New Folder (2)\crystalc-0-liver1-F10-R1.pepXML.params E:\New Folder (2)\liver1-F10-R1.pepXML
ReportDbAnnotate [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe database --annotate C:\drivers\moda\database\uniprot-human_reviewed_20190401_reverse.fasta --prefix REVERSE_
PeptideProphet [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy REVERSE_ --database C:\drivers\moda\database\uniprot-human_reviewed_20190401_reverse.fasta --combine liver1-F10-R1_c.pepXML
ProteinProphet [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe proteinprophet --maxppmdiff 2000000 E:\New Folder (2)\interact.pep.xml
ReportFilter [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe filter --sequential --razor --mapmods --prot 0.01 --tag REVERSE_ --pepxml E:\New Folder (2) --protxml E:\New Folder (2)\interact.prot.xml
ReportReport [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe report
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe workspace --clean
INFO[11:48:46] Executing Workspace 20190418                 
INFO[11:48:49] Removing workspace                           
INFO[11:48:49] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\New Folder (2)]
E:\drivers\philosopher_windows_amd64_20190418.exe workspace --init
INFO[11:48:51] Executing Workspace 20190418                 
INFO[11:48:53] Creating workspace                           
INFO[11:48:53] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: E:\New Folder (2)]
C:\Users\crc\AppData\Local\Programs\Python\Python37\python C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py 8 "java -jar -Dfile.encoding=UTF-8" E:\drivers\MSFragger-20190222\MSFragger-20190222\MSFragger-20190222.jar E:\New Folder (2)\fragger.params E:\drivers\liver1-F10-R1.mzML
STARTED: slice 1 of 8
MSFragger version MSFragger-20190222
MSFTBX version 1.8.6
(c) University of Michigan

System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_181, Java HotSpot(TM) Client VM, Oracle Corporation
JVM started with 247MB memory

Sequence database filtered and tagged in 32ms
Digestion completed in 187ms
Merged digestion results in 15ms
Sorting digested sequences...
	of length 7: 40733
	of length 8: 37763
	of length 9: 34659
	of length 10: 31922
	of length 11: 29840
	of length 12: 26956
	of length 13: 25867
	of length 14: 23215
	of length 15: 21854
	of length 16: 19451
	of length 17: 14567
	of length 18: 8622
	of length 19: 2872
	of length 20: 845
	of length 21: 188
	of length 22: 57
	of length 23: 17
	of length 24: 3
	of length 25: 5
	of length 26: 3
	DONE
Removing duplicates and compacting...
Reduced to 246523  peptides in 156ms
Generating modified peptides...DONE in 530ms
Generated 326762 modified peptides
Merging peptide pools from threads... DONE in 32ms
Sorting modified peptides by mass...DONE in 47ms
Traceback (most recent call last):
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 342, in <module>
    main()
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 332, in main
    run_msfragger()
  File "C:\Users\crc\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 136, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\crc\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-jar', '-Dfile.encoding=UTF-8', 'E:\\drivers\\MSFragger-20190222\\MSFragger-20190222\\MSFragger-20190222.jar', 'fragger.params', 'E:\\drivers\\liver1-F10-R1.mzML', '--partial', '0']' returned non-zero exit status 1.
Peptide index written in 422ms
Insufficient memory! Predicted minimum memory required: 4.00GB
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp E:\drivers\FragPipe_v9.1.exe umich.msfragger.util.FileMove E:\drivers\liver1-F10-R1.pepXML E:\New Folder (2)\liver1-F10-R1.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 8/11 processes (3 already finished)
Processing interrupted, stopping MsFragger

**Comment by guoci** [comment]
You need to set RAM to at least 5GB.
![image](https://user-images.githubusercontent.com/1260178/56904193-d048fd00-6a6b-11e9-8d64-d636f4326d86.png)

**Comment by chhh** [comment]
no response, closing
