### ISSUE TITLE
Errors happened in ProteinProphet of FragPipe 20.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#1131]
- Describe the issue or question:
I loaded the default worflow "LFQ-PHOS", and run the fragpipe.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-06-03_17-04-46.txt](https://github.com/Nesvilab/FragPipe/files/11642871/log_2023-06-03_17-04-46.txt)

**Comment by andyzim111** [comment]
If you need any file, please let me know.

**Comment by anesvi** [comment]
I personally do not know what caused it. We had no othrr recent reports about such a crash. Try with mzML files instead

**Comment by fcyu** [comment]
I also have no clue. Maybe rerun it again or use another computer?

Best,

Fengchao

**Comment by guoci** [comment]
@andyzim111 try avoiding using paths with non-ASCII characters, you have `钟传奇` in your path.
