### ISSUE TITLE
Mixing FAIMS and non-FAIMS breaks IonQuant

### ISSUE THREAD

**Issue by sasvarip** [Nesvilab/FragPipe#1132]
- Describe the issue or question:
Since I downloaded the new version i get the following error when trying to run many DDA measurements:

...
2023-06-05 15:40:23 [WARNING] -There are closed modifications: 4685.6658 and 4685.6659. Will keep 4685.6659
2023-06-05 15:40:23 [INFO] - Collecting variable modifications from all psm.tsv files...
2023-06-05 15:40:23 [INFO] - Loading and indexing all psm.tsv files...
2023-06-05 15:40:23 [INFO] - Collecting all compensation voltages if applicable...
2023-06-05 15:40:25 [ERROR] - There were errors crating tables in B:\Asztal\Fragpipe_20_runs\4\.: java.lang.NullPointerException: Could not find ion with peptide index 1481 charge 4 compensation voltage -50 from the ion index.

With a small number of files (4) i dont get this error and with the old version (19.0) i had no problem with this many files either.

- Upload your log file

[log_2023-06-05_15-40-25.txt](https://github.com/Nesvilab/FragPipe/files/11653207/log_2023-06-05_15-40-25.txt)

**Comment by fcyu** [comment]
It seems that you enabled PTM-Shepherd, which you should not for the closed search. It messed up the files. Could you use one of the built-in workflows and start from the scratch?

Thanks,

Fengchao

**Comment by sasvarip** [comment]
I loaded the same files, made sure to load the LFQ-MBR workflow. In the 'PTMs' section the 'Run PTM-Shepherd' is unticked, even unticked 'Assign Glycans with FDR (using FDR-Shepherd)'. MS1 Quant has been set to defaults as well. As far as I can see it made the warning disappear, but the final error remained and the run was stopped.

[log_2023-06-05_17-49-42.txt](https://github.com/Nesvilab/FragPipe/files/11654531/log_2023-06-05_17-49-42.txt)

**Comment by fcyu** [comment]
Hmm, could you please share the mzML files and the fasta file with us? I can send you a link to download if you need.

Thanks,

Fengchao

**Comment by sasvarip** [comment]
Yeah, sure, no problem. Could yo advise where to upload them? They require quite some space.

**Comment by fcyu** [comment]
Sounds good! Here is the link to upload https://www.dropbox.com/request/LTz2awIFcHDOUoKnlo1A

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi @sasvarip ,

Thank you very much for your mzML files. You analyzed your FAIMS and non-FAIMS data together, which is not supported and not a good idea because IonQuant does not know how to detect and transfer features between FAIMS and non-FAIMS data.

Could you please run the FAIMS and non-FAIMS data separately? I will let IonQuant print an error message and stop in the future version.

Best,

Fengchao

**Comment by fcyu** [comment]
`01_C-` does not have FAIMS, but `5_16_TCL` has FAIMS.

The new version changed the way of indexing an ion, and fixed some bugs.

Best,

Fengchao

**Comment by sasvarip** [comment]
Okay, now i used only the ones that were measured on the same day (so they have to be FAIMS). Unfortunately IonQuant still stops, however now the reason is different.
I tried to change the precursor mass tolerance and the fragment mass tolerance (They are IT HCD so the analyst guy suggested 5 ppm and 0.6 Da respectively). However it didnt help. I attach both log  files. Could you have a look at them?

[log_2023-06-08_11-52-39.txt](https://github.com/Nesvilab/FragPipe/files/11690064/log_2023-06-08_11-52-39.txt)

[log_2023-06-08_16-58-01.txt](https://github.com/Nesvilab/FragPipe/files/11690065/log_2023-06-08_16-58-01.txt)

**Comment by fcyu** [comment]
Thank you very much for your update.

The first hundred of MS1 scans have compensate voltages -30. Normally, the CV values are arranged like -30, -50, -70, -30, -50, -70.... When IonQuant see hundreds MS1 scans with the same CV, it will interoperate that the whole run has one CV. 

I will fix this bug and send you a fixed version if you need.

Best,

Fengchao
