### ISSUE TITLE
Fragpipe Stops with mzML EtHCD File in Glyco N-Hybrid Workflow

### ISSUE THREAD

**Issue by TGleinser** [Nesvilab/FragPipe#1135]
- Describe the issue or question:

Fragpipe Stops with mzML EtHCD File in Glyco N-Hybrid WorkflowFragpipe Stops with mzML EtHCD File in Glyco N-Hybrid Workflow

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-06-06_17-08-30.txt](https://github.com/Nesvilab/FragPipe/files/11666259/log_2023-06-06_17-08-30.txt)

**Comment by fcyu** [comment]
There are no IDs from the MSFragger search. Please double check your data and settings.

Best,

Fengchao

**Comment by johnholmi** [comment]
![grafik](https://github.com/Nesvilab/FragPipe/assets/132134644/99366c2a-a460-4897-abab-258df3f714e8)

**Comment by johnholmi** [comment]
The question is why are there no IDs in the MS Fragger search. When I run the data on PEAKs they look perfectly. I converted the raw file according to you recommendations in the manual

**Comment by fcyu** [comment]
There must be something wrong with your settings. PEAKS does not have many parameters to change. For FragPipe, you need to know your sample and some basic concepts.

Best,

Fengchao

**Comment by johnholmi** [comment]
Thanks this is very helpful. What a valuable software
