### ISSUE TITLE
missing features in Fragpipe-PDV

### ISSUE THREAD

**Issue by HansABakker** [Nesvilab/FragPipe#1137]
Hello,
I start to like using fragpipe, but have an issue with the visualization of my data in PDV. If I open my data, I can only get a list of PSMs for each protein separate when I click on a specific protein. I, however, would like to sort the whole list based on specific post translational modifications.
According to what I read in the manuel of PDV, this should be possible. There seems to be things missing in my Fragpipe-PDV. I think there should be a toolbar on top that I don’t see. Do I overlook something or should I try to reinstall. Or something with Java?
Thanks for any help, Hans

**Comment by HansABakker** [comment]
I have a screenshot here:
![fragpipe_PVP](https://github.com/Nesvilab/FragPipe/assets/130580030/7f10b3d0-c1c1-4558-95b4-24a0a6543215)

**Comment by KaiLiCn** [comment]
Hi Hans,

If I understand it correctly, you want to visualize PSMs for all proteins you identified and sort the PSMs table by the ptm. There are a few steps:

1. Select "All proteins" option on the left bottom corner of "Proteins" table panel;
2. Click "Show all selected" button  on the top of "Proteins" table panel;
3. Then the "PSMs" panel will show psms of all proteins. If you want to sort the whole table, first you can select the item you want to sort in the scroll bar on the right top corner of "PSMs" panel. Second, click the up or down sort button behind it.
<img width="974" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/29800230/c21b2395-359a-481c-b7d4-fef9db85054e">


By the way, based on the screenshot, you might use the old version of FrigPipe-PDV. You could update it by updating your FragPipe, or following this link to update FragPipe-PDV alone: https://github.com/Nesvilab/FragPipe-PDV . 

Please let me know if you have other questions.

Best,
Kai

**Comment by HansABakker** [comment]
Dear Kai,
thanks, now I don't understand why I did not see this, except for that the position of button 2 is a bit strange if this applies to the PSMs. 
Still my next problem is that I want to further organize my results. can I remove everything that does not have my wanted modification to be able to further organize the remaining PSMs, again by protein or peptide sequence.
I can do this in proteome discoverer, but we do not have a licence for this and the visualization for glycans is better in FP-PDV.
Best regards, Hans

**Comment by KaiLiCn** [comment]
Hi Hans,

I don't understand "you did not see this" since I labeled all buttons in the screenshot you shared. 

Right now, we can't filter results based on PTMs. However, you could filter it based on the peptide sequence or protein name. 1, select the level you want to search or filter, such as peptide sequence, protein name, and spectrum title; 2, type the items you want to match; 3, click the search button. For example, if you want to search all psms containing the sequence "STY", select level "Peptide", type "STY", and click search. You can see all PSMs having "STY" from all proteins in the "PSMs" panel.
<img width="974" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/29800230/4c8f3e25-0df8-4332-8f31-6e21aaacb62c">

Kai

**Comment by KaiLiCn** [comment]
Hi Hans,

Searching based on modification will be a good function. I will add this function in the near future.

I am not very familiar about the PD part. @fcyu , do you have any ideas?

Best,
Kai

**Comment by fcyu** [comment]
I don't think PD can take FragPipe result.

Best,

Fengchao

**Comment by anesvi** [comment]
No, you cannot load it in PD. One can use MSFragger node in PD but even that has limited functionality.

**Comment by HansABakker** [comment]
Thank you all.
