### ISSUE TITLE
easypqp convert issue

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/FragPipe#1138]
I am trying to run easypqp convert on unknown modification DIA data, and was referred to look in fragpipe for finding the correct easypqp convert run command
>>easypqp convert --pepxml PATH/filename.pepXML --spectra PATH/filename.mzML --enable_unannotated
it runs but does not populate the psms into the pepxml df with any values. 
any idea what the proper format should be for the run command?
The input pepxml is generated from fragpipe

**Comment by fcyu** [comment]
If you want to reproduce what FragPipe is doing, you can copy the command FragPipe is using. It has more flags than yours.

FragPipe use EasyPQP by system calling the convert and library commands. It has no different compared to running EasyPQP in command line interface. 

Best,

Fengchao
