### ISSUE TITLE
Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 

### ISSUE THREAD

**Issue by alima82** [Nesvilab/FragPipe#1141]
- Describe the issue or question:
Got the error below trying to process TimsTof data. 
" C:\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe report
INFO[10:21:45] Executing Report  v5.0.0                     
INFO[10:21:45] Creating reports                             
ERRO[10:21:45] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 
Process 'PhilosopherReport' finished, exit code: 1
Process returned non-zero exit code, stopping" 
[log_2023-06-12_10-21-45.txt](https://github.com/Nesvilab/FragPipe/files/11725057/log_2023-06-12_10-21-45.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Upgrading the FragPipe to version 20.0 will solve this problem.

Best,

Fengchao

**Comment by alima82** [comment]
It worked. Thank you Fengchao.
