### ISSUE TITLE
EasyPQP parsing error

### ISSUE THREAD

**Issue by silasmellor** [Nesvilab/FragPipe#1142]
I tried reprocessing some old data using the new version of FragPipe and modules. I get an error from easyPQP that i was hoping made some sense to you?

Log attached. Thanks for a great piece of software.
[log_2023-06-12_17-13-26.txt](https://github.com/Nesvilab/FragPipe/files/11725139/log_2023-06-12_17-13-26.txt)

best,Silas

**Comment by fcyu** [comment]
Hi Silas,

It seems that there was not enough memory.

Best,

Fengchao

**Comment by silasmellor** [comment]
Thanks Fengchao, if that is the case I will try again with lower paralellism and see if that fixes it. 
Best,
Silas
