### ISSUE TITLE
How to measure Chromatographic peak width?

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/FragPipe#1143]
Dear Fragpipe team,

I have a general question: is there a way to extract information regarding the chromatographic peak width associated to a peptide identification from a Fragpipe output?

MaxQuant has something called `retention length` in its output(s) and it is a nice quality control metric for the chromatographic behavior  and the LC-MS/MS system in general.

Many thanks in advance!

Best wishes,
Miguel

**Comment by fcyu** [comment]
There is no such output information in the current version. We will add in the future.

Best,

Fengchao
