### ISSUE TITLE
MSFragger License activation

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/FragPipe#1144]
Hello,

My company just purchased the MSFragger licsense for our internal use. However in the license agreement, it doe not show any activation code for this license, should I be expecting to receive secondary message regarding the full license activation with instructions and related details? Please let me know. 

Thanks,
Pankaj

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Pankaj,

As long as your company purchases the license, you can use the software as the way you want. There is no license key or activation. 

Enjoy,

Fengchao
