### ISSUE TITLE
Question about Reference sample settings for TMT10-phospho-bridge workflow

### ISSUE THREAD

**Issue by elenitskorda** [Nesvilab/FragPipe#1146]
Hi everyone,

I am trying to use Fragpipe with TMT10-phospho-bridge workflow. My data consists 12 plexes of 12 fractions each. I have generated annotations files (annotation.txt) for each plex having a unique pool for each plex (pool01, pool02,....pool12). Each annotation file is located in each plex's folder.

 My question is, when it comes to select the parameters from "Quant (Isobaric)" tab, in the "Basic Options" box, do I define reference as a "Reference sample" and then "Ref sample tag" =pool? or do I define reference as Virtual?

Thank you in advance :)

**Comment by fcyu** [comment]
If the `poolXX` is your reference channel, you should select the "reference sample" and set the "ref sample tag" to `pool`.

Best,

Fengchao

**Comment by elenitskorda** [comment]
Thank you Fengchao!

Best,
Eleni

**Comment by fcyu** [comment]
Hi Eleni,

I have no idea. Could you replace the `tmt-integrator-4.0.5.jar` in the `fragpipe/tools` folder with the one in https://www.dropbox.com/t/duArysYDw2pEPCgX, rerun the job, and send me the log file?

Thanks,

Fengchao

**Comment by elenitskorda** [comment]
Hi Fengchao,

yes ofc! I did as you said and i receive kind of the same error. I attach the log file from the second run.
Do you know why this is happening?

[log_2023-06-14_23-01-01.txt](https://github.com/Nesvilab/FragPipe/files/11750594/log_2023-06-14_23-01-01.txt)

Best,
Eleni

**Comment by fcyu** [comment]
Hi Eleni,

Thanks for your log file.

I think the last channel should be `131N`, not `131`. Could you correct all annotation files and try again?

Best.

Fengchao

**Comment by elenitskorda** [comment]
Hi Fengchao,

Yes ofc. I have corrected already and the analysis is running as we speak and i will let you know for the result.
However, CPTAC reports ions as 131 (reference) instead of 131N. Is this the same? Sorry if the question is stupid. I am very new to this.

Thanks,
Eleni

**Comment by elenitskorda** [comment]
Hi Fengchao,

with your recomentations it finally worked!
Many thanks!

Best,
Eleni

**Comment by fcyu** [comment]
You are welcome. Please feel free to contact us if you have any questions in the future.

Best,

Fengchao
