### ISSUE TITLE
Fragpipe without decoys?

### ISSUE THREAD

**Issue by HansABakker** [Nesvilab/FragPipe#1147]
Hello,
me again.
We often analyse recombinantly expressed and purified proteins for post translational modifications (glycosylation). We do this with Skyline, but especially the open search option in Fragpipe is interesting to see unexpected things as well.
We don't want to bother with decoys and FDR there, just see anything that passes the settings in advanced peak matching options. 
I saw a similar question from 2021, but maybe things have changed. I also saw a commit saying: "[Remove decoy checking from the ProteinProphet step].

MSfragger seems to have no problems without decoys, but I am not able to see any data in PDV-viewer. I suppose it has to go through validation first.

Is there a way to pass PeptideProphet or percolator without decoys?

Adding decoys  to my one protein does not help, it finds zero for the 10 peptides in my tested protein.
It starts to work if I add common contaminants, but then I think I have to set FDR to 1. In theory, I can add a whole database, but also then don't want to work with low FDR.

What do you advice?
What do I then exactly write in the command line options for PeptideProphet?

Thanks for your help, Hans

 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by danielgeiszler** [comment]
You can try appending something like an E. coli proteome to the fasta. I've used this for purified protein samples.

**Comment by fcyu** [comment]
Yes, you are right. Should set all levels to 100% FDR. PeptideProphet is not doing any FDR filter but you can add `--minprob 0` to the command if you want.

Best,

Fengchao
