### ISSUE TITLE
TMT labile workflow

### ISSUE THREAD

**Issue by ohovey5** [Nesvilab/FragPipe#1149]
Hello FragPipe Team,

Kevin Yang at ASMS about using the labile workflow for TMT data. I attempted to create the workflow by modifying the labile to add TMT but I'm getting less phosphorylation sites (9500 vs 4170). I would expect to get higher since TMT is fragmented at 32 NCE which is not ideal for phospho. 

Could a specific labile-phospho-TMT workflow be made or someone look the workflow I made?
[Labile_TMT_Phos.txt](https://github.com/Nesvilab/FragPipe/files/11773147/Labile_TMT_Phos.txt)

Cheers,
Owen

**Comment by fcyu** [comment]
Hi Owen,

Could you add `KEEPOLD STATIC EM=1 NIONS=b STY:79.966331,M:15.9949 MINPROB=0.5` to the PTMProphet `cmd line opts` and try again?

Best,

Fengchao

**Comment by yangkl96** [comment]
Hi Owen,

Sorry for the confusion. I was using our labile workflow to search ADP ribosylated data, not TMT. 

Best,
Kevin

**Comment by ohovey5** [comment]
Fengchao, there is no change with that addition to PTM prophet

Kevin, based on the preprint (MSFragger-Labile: A Flexible Method to Improve Labile PTM Analysis in Proteomics) figure 3 shows phospho ID are better using Labile workflow with label-free. Can this be modified for TMT-phospho?

**Comment by fcyu** [comment]
Hi @yangkl96 , I think he confused me with you.

Hi @ohovey5 , can you share two log files? One with labile setting, and the other without.

Thanks,

Fengchao

**Comment by ohovey5** [comment]
Hello Fengchao, 

Thank you for looking into this. Here is the two long files. 10-17-03 is TMT-phospho and 14-59-55 is TMT-phospho-labile


[log_2023-06-16_10-17-03.txt](https://github.com/Nesvilab/FragPipe/files/11775923/log_2023-06-16_10-17-03.txt)
[log_2023-06-16_14-59-55.txt](https://github.com/Nesvilab/FragPipe/files/11775924/log_2023-06-16_14-59-55.txt)

**Comment by fcyu** [comment]
Hi @ohovey5 ,

I guess you were using TMT-Integrator's site report to count the numbers. There are some differences in the setting that might affect the numbers significantly:

log_2023-06-16_10-17-03.txt VS log_2023-06-16_14-59-55.txt

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/7139353b-7be1-447c-8722-34b16c1170f9)

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/ccdbeedb-0b1f-43e5-a96a-159f19a4f651)

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/f83bc738-45f1-49eb-8f55-258bf3092ff5)

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/72d347f3-ef56-4b24-a0d1-f9e8aab1951f)

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/7e3b5573-e7f4-489c-abe0-cbc166763392)

If you want to perform a head-to-head comparison, could you make the parameters the same except for the modification and mass offset related settings?

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi @ohovey5,

I think the issue is because you have a different fixed mass for TMT on K in the labile search (229.2634 instead of 229.1629 in the closed search). You can see from the logs that even the first search (which does not use the labile mode) finds only about 5000 matches for calibration instead of 12000, about the same proportion as the difference  in the final PSM counts. Try changing the fixed TMT mass back to 229.1629. 

Also for comparison, reduce the number of variable phospho in the labile search to 2 so the searches are considering the same number of phospho groups. There are some other spectrum processing parameters for MSFragger (clear_mz_range, precursor mass tolerance, etc.) that are different between the two workflows that should be the same in order to do a good comparison. 

Best,
Dan

**Comment by ohovey5** [comment]
Thank you, I made the changes but unfortunately it is still not as good as the regular TMT workflow (Original 9500 vs labile 8950). In your paper CPTAC TMT-data is used a they observe 30% increase in IDs, Im just looking to replicate that.

**Comment by fcyu** [comment]
Hi @ohovey5 ,

Could you share your log files?

Best,

Fengchao

**Comment by fcyu** [comment]
Also, I don't think it is a good idea to use TMT-Integrator's reports to count the IDs because you have `tmtintegrator.min_site_prob=0.75`. Most labile phosphopeptides won't pass this threshold. Could you count the phosphopeptides using psm.tsv or set the `tmtintegrator.min_site_prob` to 0?

Best,

Fengchao

**Comment by antdit** [comment]
Hi @fcyu and @dpolasky,

apologies for opening this issue again but I am facing the same problem when using labile vs variable modification on a phospho TMT18 dataset where the labile search produces about half the number of psms/phospho-peptides as the variable mod search. I am not sure if it is something in the validation settings that needs to be changed and I cannot figure out what that would be. I am attaching the log files of the two searches (36 fractions, TMT18, phoshpo-enriched). 

I would really appreciate if I can get some feedback on them. 

Thank you!
Antje

[log_2023-08-07_17-33-49_varMod.txt](https://github.com/Nesvilab/FragPipe/files/12309885/log_2023-08-07_17-33-49_varMod.txt)
[log_2023-08-09_14-00-34_labile.txt](https://github.com/Nesvilab/FragPipe/files/12309886/log_2023-08-09_14-00-34_labile.txt)

**Comment by danielgeiszler** [comment]
Hi Antje,

Your labile run only has 21 input files and your variable mod run has 36 input files.

**Comment by fcyu** [comment]
May I ask which file you used to count the numbers?

Thanks,

Fengchao

**Comment by dpolasky** [comment]
Also, you're searching a total of 4 phospho groups in the labile search (3 variable mods and 1 offset) vs just 3 in the varmod search, which increases the search space and decreases the sensitivity. To get an even comparison, you need to have the same number in each search (e.g., 2 variable mods and 1 offset for the labile search). 

Best,
Dan

**Comment by antdit** [comment]
@fcyu I am looking at psm.tsv and peptde.tsv filtered for phospho in the Assigned Modifications column
@dpolasky I corrected the MSFragger settings. Numbers are still a bit lower when using the labile search

[log_2023-08-10_20-24-38_correctedLabile.txt](https://github.com/Nesvilab/FragPipe/files/12319283/log_2023-08-10_20-24-38_correctedLabile.txt)

Best,

Antje

**Comment by antdit** [comment]
Hi Dan,

thanks for the additional information and discussion. The TMT data I am currently looking at were acquired at 32 NCE on an Exploris and the reporter ion region was cleared. Given your answer and your data in the paper I guess it is fair to say that it would need to be tested on the different datasets whether including labile modifications settings in the search is beneficial or not?

Best,

Antje

**Comment by dpolasky** [comment]
Yes, at 32 NCE I could see it going either way whether labile search will provide a substantial boost or not. I would still expect there to be slightly more phosphoPSMs even if the total number of PSMs is slightly lower (you would have to look at the psm.tsv to confirm). But the cases where we saw 10-30% improvements in the phospho searches were at NCE 35 and 37, so a little higher than yours. 

Best,
Dan
