### ISSUE TITLE
TMT10-Phospho workflow doesn't provide combined result file

### ISSUE THREAD

**Issue by RevathyNanda** [Nesvilab/FragPipe#1150]
Hi FragPipe Team,

I am currently working on phosphoproteomics data analysis. I have used TMT10-Phospho workflow for this. Results files after analysis is attached herewith. In this I am not able to find combined results file for all peptides and modified peptides. In older version (version 17.1), I used get results in "combined_modified_peptides.tsv" (Figure 3). Is there any change I have to do to get results in this format?

![image](https://github.com/Nesvilab/FragPipe/assets/93638970/487f38d2-80cd-4277-bbc2-03e2e2763fe6)
![image](https://github.com/Nesvilab/FragPipe/assets/93638970/9ae14013-775e-4915-bab8-9d87afd57e35)
![image](https://github.com/Nesvilab/FragPipe/assets/93638970/4aa3c51a-8411-4245-b507-463cf2147d85)

Thank you,
Revathy

**Comment by fcyu** [comment]
If you are doing TMT, you should use the files in "TMT-report" folder.
combined_*.tsv is for MS1-based quantification.

Best,

Fengchao

**Comment by RevathyNanda** [comment]
Where will I get phosphosite information? The multi-site, single site files doesn't provide phosphosite information.

**Comment by anesvi** [comment]
They provide this information. Please read tutorials and inspect files.
