### ISSUE TITLE
Total ion current plot

### ISSUE THREAD

**Issue by tomthun** [Nesvilab/FragPipe#1153]
- Describe the issue or question: 

I wanted to ask if there is a way to generate the total ion current (TIC) vs retention time for any peptide from the output tables. 
MaxQuant creates this information in a seperate .txt, the MS/MS scans table. Is there anything relateable with Fragpipe?

![image](https://github.com/Nesvilab/FragPipe/assets/35220235/d862692c-2329-4380-8d6e-b5e6f7e94551)

**Comment by fcyu** [comment]
Not available in the current version. If we added it in the future, will keep you posted.

Best,

Fengchao
