### ISSUE TITLE
pep.XML file is missing in the result ouput files.

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1154]
- Describe the issue or question:

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchao
