### ISSUE TITLE
Missing Pep. XML file and other output files

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1155]
- Describe the issue or question:
I cannot find pep. XML file in the result output files. How do you locate other files like ion.tsv, pep.tsv, protein.tsv and psm.tv.

Here is my log file

CheckCentroid
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\jre\bin\java.exe -Xmx2G -cp "C:\Users\Tosin\Desktop\Fragpipe\fragpipe\lib\fragpipe-20.0.jar;C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\batmass-io-1.28.12.jar" com.dmtavt.fragpipe.util.CheckCentroid C:\Users\Tosin\Desktop\tissuedata\MSconvert1\Tosin_Myoglobin_1.mzML 3
Done in 6.2 s.
Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\Users\Tosin\Documents\result-tissue]
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --clean --nocheck
INFO[14:58:54] Executing Workspace  v5.0.0                  
INFO[14:58:54] Removing workspace                           
INFO[14:58:54] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\Users\Tosin\Documents\result-tissue]
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --init --nocheck --temp C:\Users\Tosin\AppData\Local\Temp\f43186af-53ae-4da1-b4c5-b51b08753616
INFO[14:58:54] Executing Workspace  v5.0.0                  
INFO[14:58:54] Creating workspace                           
INFO[14:58:54] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\Users\Tosin\Documents\result-tissue\Tissue]
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --clean --nocheck
INFO[14:58:54] Executing Workspace  v5.0.0                  
INFO[14:58:54] Removing workspace                           
INFO[14:58:54] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\Users\Tosin\Documents\result-tissue\Tissue]
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --init --nocheck --temp C:\Users\Tosin\AppData\Local\Temp\902be4d2-292d-4201-84b0-22c363ef7d5e
INFO[14:58:55] Executing Workspace  v5.0.0                  
INFO[14:58:55] Creating workspace                           
INFO[14:58:55] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
MSFragger [Work dir: C:\Users\Tosin\Documents\result-tissue]
C:\Users\Tosin\Desktop\Fragpipe\fragpipe\jre\bin\java.exe -jar -Dfile.encoding=UTF-8 -Xmx2G C:\Users\Tosin\Desktop\Fragpipe\fragpipe\tools\MSFragger-3.8\MSFragger-3.8.jar C:\Users\Tosin\Documents\result-tissue\fragger.params C:\Users\Tosin\Desktop\tissuedata\MSconvert1\Tosin_Myoglobin_1.mzML
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 2 GB memory
Checking database...
Checking spectral files...
C:\Users\Tosin\Desktop\tissuedata\MSconvert1\Tosin_Myoglobin_1.mzML: Scans = 10345
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 3
database_name = C:\Users\Tosin\Documents\Fasta 2\2023-06-22-decoys-reviewed-contam-UP000002494.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = 0
write_calibrated_mzml = 1
write_uncalibrated_mgf = 0
write_mzbin_all = 0
isotope_error = 0/1
mass_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = CORRECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
ion_series_definitions = 
search_enzyme_name = stricttrypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 = 
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = 1
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = pepxml_pin
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 0
override_charge = 0
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
activation_types = all
group_variable = 0
require_precursor = 1
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 1
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 MFHILVWY 3
variable_mod_02 = 42.0106 [^ 1
add_A_alanine = 0.0
add_B_user_amino_acid = 0.0
add_C_cysteine = 57.02146
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.0
add_E_glutamic_acid = 0.0
add_F_phenylalanine = 0.0
add_G_glycine = 0.0
add_H_histidine = 0.0
add_I_isoleucine = 0.0
add_J_user_amino_acid = 0.0
add_K_lysine = 0.0
add_L_leucine = 0.0
add_M_methionine = 0.0
add_N_asparagine = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.0  # O = pyrrolysine (237.14773 Da)
add_P_proline = 0.0
add_Q_glutamine = 0.0
add_R_arginine = 0.0
add_S_serine = 0.0
add_T_threonine = 0.0
add_U_user_amino_acid = 0.0  # U = selenocysteine (150.95363 Da)
add_V_valine = 0.0
add_W_tryptophan = 0.0
add_X_user_amino_acid = 0.0
add_Y_tyrosine = 0.0
add_Z_user_amino_acid = 0.0
Number of unique peptides
	of length 7: 111172
	of length 8: 107111
	of length 9: 103206
	of length 10: 98424
	of length 11: 94718
	of length 12: 90288
	of length 13: 86939
	of length 14: 82411
	of length 15: 77093
	of length 16: 73795
	of length 17: 68837
	of length 18: 65924
	of length 19: 62262
	of length 20: 58921
	of length 21: 56332
	of length 22: 51396
	of length 23: 48885
	of length 24: 47431
	of length 25: 43255
	of length 26: 41530
	of length 27: 38873
	of length 28: 37069
	of length 29: 34506
	of length 30: 32172
	of length 31: 30672
	of length 32: 28786
	of length 33: 27108
	of length 34: 25695
	of length 35: 23609
	of length 36: 22242
	of length 37: 20421
	of length 38: 19068
	of length 39: 17362
	of length 40: 16601
	of length 41: 15114
	of length 42: 14213
	of length 43: 12194
	of length 44: 9425
	of length 45: 7193
	of length 46: 4650
	of length 47: 2830
	of length 48: 1535
	of length 49: 825
	of length 50: 421
In total 1912514 peptides.
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at s.a(Unknown Source)
	at r.a(Unknown Source)
	at k.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at F.a(Unknown Source)
	at s.a(Unknown Source)
	at s$$Lambda$80/0x000000010028bc40.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 18 remaining tasks



- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Your computer only has 2 GB free memory, which is not enough. We recommend at least 8.

Best,

Fengchao

**Comment by tygrad** [comment]
Alright. Thanks.
