### ISSUE TITLE
Headless mode how to specify FASTA?

### ISSUE THREAD

**Issue by jameswallacew8** [Nesvilab/FragPipe#1156]
I am trying to run FragPipe in Headless mode on a linux machine. How do I specify the Fasta file path? Is this in the Manifest file? If so I would greatly appreciate an example. I was unable to make sense of this from the tutorial.

Currently I am getting 'ERROR - FASTA file path is empty or the file is corrupted'

Thanks

**Comment by fcyu** [comment]
Put `database.db-path=path.fasta` to the workflow file.

Best,

Fengchao
