### ISSUE TITLE
Quantification HLA peptides DIA-NN

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#1157]
Hello,

I am writing because I analysed HLA peptides using the hybrid DIA-DDA workflow, including spectral library creation and DIA-NN quantification. I wanted to quantify the peptides but in the PSMs output (psm.tsv) the intensities are zero. Then, I saw that it can be quantified with the DIA-NN output right? I have several questions regarding that:

1. I guess I should use the Precursor.Quantity column? What is the normalization applied in the Precursor.Normalised otherwise?
2. I was also trying to link the PSMs with the DIA-NN.output, but I don't know how to do it. Is it possible? In which level is the DIA-NN output? I saw that there are peptide sequences repited so it's not in a peptide level, but on the other hand it has less repeptitions than the number of psms. 

Thanks in advance for the clarifications.

Best regards,
Emma

**Comment by fcyu** [comment]
Hi Emma,

> I guess I should use the Precursor.Quantity column? What is the normalization applied in the Precursor.Normalised otherwise?

Please read the document here https://github.com/vdemichev/DiaNN#output

> I was also trying to link the PSMs with the DIA-NN.output, but I don't know how to do it. Is it possible? In which level is the DIA-NN output? I saw that there are peptide sequences repited so it's not in a peptide level, but on the other hand it has less repeptitions than the number of psms.

Please use the output in `diann-output` folder. `psm.tsv` was generated during spectral library generation stage. Please see the above link for the DIA-NN output.

Best,

Fengchao
