### ISSUE TITLE
 can output of the silac workflow provide proteins abundance?

### ISSUE THREAD

**Issue by HYCCHENG** [Nesvilab/FragPipe#1158]
Dear MSFragger team,
i successfully performed the silac sample analysis with fragpipe. However,i can not find the protein abundance at the output. So, where can I pull up the SILAC quantified protein abundance signal value ?

[log_2023-06-26_22-09-38.txt](https://github.com/Nesvilab/FragPipe/files/11870281/log_2023-06-26_22-09-38.txt)

**Comment by HYCCHENG** [comment]
So, I would like to ask if some proteins in the proteome may have random results in repeated experiments because of their low abundance. In this case, is there any parameter in the silac data search results that can be used for reference？



thanks！
---- Replied Message ----
| From | ***@***.***> |
| Date | 06/26/2023 22:18 |
| To | Nesvilab/FragPipe ***@***.***> |
| Cc | HYCCHENG ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Nesvilab/FragPipe] can output of the silac workflow provide proteins abundance? (Issue #1158) |

For the SILAC workflow, ion level has abundance and log-ratio. Peptide and protein levels only have log-ratios because we calculate them from the ion-level log-ratios. Abundance is not normalized and not quite informative.

Best,

Fengchao

**Comment by HYCCHENG** [comment]
What you just mentioned is also an important point! Aside from the previous question, I would like to ask whether the software can not give the normalized abundance of ions？

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/26/2023 22:18 |
| To | Nesvilab/FragPipe ***@***.***> |
| Cc | HYCCHENG ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Nesvilab/FragPipe] can output of the silac workflow provide proteins abundance? (Issue #1158) |

For the SILAC workflow, ion level has abundance and log-ratio. Peptide and protein levels only have log-ratios because we calculate them from the ion-level log-ratios. Abundance is not normalized and not quite informative.

Best,

Fengchao

**Comment by fcyu** [comment]
Do you mean no normalization? You can uncheck normalization in the "MS1 (Quant)" tab.

Best,

Fengchao

**Comment by HYCCHENG** [comment]
Ok, I see. Thank you very much for your help!

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/26/2023 22:39 |
| To | Nesvilab/FragPipe ***@***.***> |
| Cc | HYCCHENG ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Nesvilab/FragPipe] can output of the silac workflow provide proteins abundance? (Issue #1158) |

Do you mean no normalization? You can uncheck normalization in the "MS1 (Quant)" tab.

Best,

Fengchao
