### ISSUE TITLE
stopped in Percolator process with an exit code: -1073741819

### ISSUE THREAD

**Issue by terencetdtd** [Nesvilab/FragPipe#1160]
- Describe the issue or question:
Hi FragPipe team

I have been trying the DIA_SpecLib_Quant workflow but failed every time in this "Percolator" process, would you mind taking a look at the log file and offer me some guidance regarding how to get this work?

I have follow the indicated instruction regarding data input and GUI setting parameters to run the analysis.

Many thanks in advance,
T
[DIA-Speclib_Quant_DT_error_log_2023-06-27_10-42-19.txt.zip](https://github.com/Nesvilab/FragPipe/files/11879846/DIA-Speclib_Quant_DT_error_log_2023-06-27_10-42-19.txt.zip)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Same return code as https://github.com/Nesvilab/FragPipe/issues/1094. It seems to related to the C++. 

I don't know what does that mean because we are not the Percolator developer. Could you submit an issue report to https://github.com/percolator/percolator/issues ?

Thanks,

Fengchao

**Comment by terencetdtd** [comment]
> 
Hi Fengchao, 

Thanks for your reply, I will submit an issue report to the Percolator team.

Best, 
T
