### ISSUE TITLE
Comparing phosphorylation results generated with different workflows for the same data

### ISSUE THREAD

**Issue by mgood3** [Nesvilab/FragPipe#1163]
Hello,

In our lab we have a SILAC dataset that has previously been analyzed in Fragpipe using the SILAC3-phospho workflow to look only for phosphorylations. I have now done an open search with the same dataset to look for additional types of PTMs. 

There were 5 phosphorylated proteins of interest from the first phospho analysis and I have checked for these modified peptides in my latest search to see if the results of the two analyses are comparable. I have noticed the following differences for these 5 proteins:

1. For phosphorylated peptides identified in both analyses, there is a difference in where the phosphorylation is predicted to be localized. In the first search (SILAC3-phospho) the phosphorylations are consistently localized on S/T/Y residues, while in the results from the open search for the same group of modified peptides none of phosphorylations are on S/T/Y residues. Eg. First analysis: GEPAAAAAPEAGAS[79.9663]PVEK and second analysis result: G[137]EPAAAAAPEAGASPVEK[136] (from the modified peptide column in psm file or G[79.9663]EPAAAAAPEAGASPVEK in the ion label quant file modified peptide column).

2. For two of the proteins there were additional modified (phosphorylated) peptides identified in the first analysis compared to the current open search analysis.

3. For one of the five proteins, in the current search no phosphorylated peptides were identified.

The first phospho analysis was done in an older version of Fragpipe (v17), while the open search was done in v19.1. Are these differences to be expected and what could account for them (particularly the difference in localization)?

Thank you for your help,
Mara

Multiple samples and fractions were searched so I have attached a representative log file from each analysis.
[logs for phospho and open searches.zip](https://github.com/Nesvilab/FragPipe/files/11900379/logs.for.phospho.and.open.searches.zip)

**Comment by fcyu** [comment]
Hi Mara,

First of all, the SILAC quantification does not support open search. If you did an open search and then let IonQuant perform SILAC quantification, I suggest you ignore IonQuant's output or redo the open search without enabling IonQuant.

> For phosphorylated peptides identified in both analyses, there is a difference in where the phosphorylation is predicted to be localized. In the first search (SILAC3-phospho) the phosphorylations are consistently localized on S/T/Y residues, while in the results from the open search for the same group of modified peptides none of phosphorylations are on S/T/Y residues. Eg. First analysis: GEPAAAAAPEAGAS[79.9663]PVEK and second analysis result: G[137]EPAAAAAPEAGASPVEK[136] (from the modified peptide column in psm file or G[79.9663]EPAAAAAPEAGASPVEK in the ion label quant file modified peptide column).

It is very likely that this phosphorylation is very labile. During the closed search, the phosphorylation was put on the S because this is the only site available. In the open search, there was no peak to localize it, so MSFragger put it on the first amino acid.

> For two of the proteins there were additional modified (phosphorylated) peptides identified in the first analysis compared to the current open search analysis.

> For one of the five proteins, in the current search no phosphorylated peptides were identified.

They are expected because open search and closed search often have overlapped and non-overlapped peptides. Although I don't know the exact reason for your cases without looking at the result, I don't see any issues here.

Best,

Fengchao

**Comment by fcyu** [comment]
OK, I took a closer look at your log files. The closed search and open search have different sets of input files. The closed search has 4 runs but the open search has 12 runs. There are also some differences in the parameters such as

1. The closed search is tryptic while the open search is semi-tryptic.
2. The peptide length and peptide mass ranges of two searches are different.

Your comparison is not "fair". Thus, I don't think the "issues" you found are really a concern.

BTW, what you did actually was a mass-offset search (which searches against a pre-defined modification mass list), not an open search which searches a wide continues mass range.

Best,

Fengchao

**Comment by mgood3** [comment]
Hi Fengchao,

Yes the log files don’t represent all of the results that I was comparing as the samples/fractions were analyzed across multiple searches (so the log files were just representative for some of the samples). Thank you for your answers about the differences in localization and overlapping/non overlapping peptides.

Could you clarify for your comment about SILAC quantification not supporting open search - does this also apply to offset searches? So depending on the type of PTM search you want to do, you could start with the Mass-Offset-CommonPTMs or an open search workflow and specify SILAC labels as variable mods (and not include MS1 quant)?

Thank you for your time!

**Comment by fcyu** [comment]
> Could you clarify for your comment about SILAC quantification not supporting open search - does this also apply to offset searches?

Correct, unless you set "report mass shift as a variable mod" to "yes, remove delta mass" in the mass-offset search:

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/bebc0a37-a6eb-4aee-b812-ac9748ac98e3)

> So depending on the type of PTM search you want to do, you could start with the Mass-Offset-CommonPTMs or an open search workflow and specify SILAC labels as variable mods (and not include MS1 quant)?

Yes, the peptide identification will work perfectly. Just not enable the quantification module.

Best,

Fengchao
