### ISSUE TITLE
Fragger headless linux - fatal error

### ISSUE THREAD

**Issue by SnowcastR** [Nesvilab/FragPipe#1165]
- Describe the issue or question:

Hi,
I am having problems with running Fragpipe headless on linux (the GUI is works fine).
It stops during Philosopher:

  time="12:35:58" level=info msg="Processing peptide identification files"
  fatal error: all goroutines are asleep - deadlock!

I am using sbatch to send to SLURM taskfarm.
I have included the input_script (as this shows the file locations), and the log.
The data and input script have to be located in /storage whereas fragpipe is in /home - so I wonder if this is a problem.

Assistance much appreciated.

Best regards,

Andrew.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2023-06-29_12-35-59.txt](https://github.com/Nesvilab/FragPipe/files/11905985/log_2023-06-29_12-35-59.txt)
[input_for_sbatch.txt](https://github.com/Nesvilab/FragPipe/files/11905990/input_for_sbatch.txt)

**Comment by fcyu** [comment]
Hi Andrew,

It is the same issue as https://github.com/Nesvilab/philosopher/issues/441 . For now, could you change the number of threads to >= 2?

Best,

Fengchao

**Comment by SnowcastR** [comment]
Hi Fengchao,

here is my input workflow.
number of threads =24
[HPE_workflow.txt](https://github.com/Nesvilab/FragPipe/files/11906091/HPE_workflow.txt)

In the output directory it shows
number of threads =1

[fragger_params.txt](https://github.com/Nesvilab/FragPipe/files/11906181/fragger_params.txt)

Do I need to change this in the GUI??

**Comment by fcyu** [comment]
Set `workflow.threads=24` in the workflow file should be good enough. In your first log, it has `workflow.threads=1` which causes the problem.

Best,

Fengchao

**Comment by SnowcastR** [comment]
Hi Fengchao,
this was a problem with the way my script was requesting CPUs from the taskfarm and nothing to do with Fragger!
Thanks for assistance in helping me pinpoint this!
BW
Andrew
