### ISSUE TITLE
PeptideProphet error, "parseOffset() 4: Syntax error parsing XML."

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#1166]
Hi all,

I am doing an open search on Orbitrap data, with a DIAUmpire-MSFragger-PeptideProphet-ProteinProphet workflow. I have a set FragPipe workflow for this that typically works great, which is what I used here (with some tweaks to the MSFragger variable and fixed mod search settings as appropriate for the current experiment). I'll attach the whole log, but I'm running into the following error, pasted below, when PeptideProphet starts. Any help would be appreciated, because I haven't run into this before. 

D:\Data\2023\ColeR\JS\230623\PPA_benchmarking\FragPipeOutput_opensearch/JS-QC-E480_230623_PPA_K562_200ng_1p8kV_240kMS1_30NCE_Q2.mzML(1) : parseOffset() 4: Syntax error parsing XML.
ERRO[06:13:52] Cannot execute program. there was an error with PeptideProphet, please check your parameters and input files 

Again, I believe I am using the same parameters and input files I normally do for this kind of search, so I'm a bit stumped. 

Thanks,
Josh

[log_2023-06-29_06-13-52.txt](https://github.com/Nesvilab/FragPipe/files/11906501/log_2023-06-29_06-13-52.txt)

**Comment by fcyu** [comment]
Hi Josh,

To troubleshoot the problem, could you share `JS-QC-E480_230623_PPA_K562_200ng_1p8kV_240kMS1_30NCE_Q2.mzML` and `JS-QC-E480_230623_PPA_K562_200ng_1p8kV_240kMS1_30NCE_Q2.pepXML` with us?

Thanks,

Fengchao

**Comment by anesvi** [comment]
You can also try using just Q1 files for open search. Q2 and Q3 often give few IDs even in regular closed search anyway. Just load Q1 files only, annotate as DDA, and continue with the analysis

**Comment by jossmi** [comment]
I can share those files.

I normally include Q1 and Q2 for the reason you stated, but I could try with only Q1. But it normally works with Q1 and Q2.

______________________
Joshua W. Smith, Ph.D.
Research Associate

Department of Environmental Health and Engineering
Johns Hopkins Bloomberg School of Public Health
 ——
Mass Spectrometry and Proteomics Facility
Department of Biological Chemistry
Johns Hopkins University School of Medicine

On Jun 29, 2023, at 10:15 AM, Alexey Nesvizhskii ***@***.***> wrote:

﻿

      External Email - Use Caution



You can also try using just Q1 files for open search. Q2 and Q3 often give few IDs even in regular closed search anyway. Just load Q1 files only, annotate as DDA, and continue with the analysis

**Comment by fcyu** [comment]
Hi @jossmi ,

I could not reproduce the error.

[log_2023-06-29_06-13-52.txt](https://github.com/Nesvilab/FragPipe/files/11908055/log_2023-06-29_06-13-52.txt)

Best,

Fengchao
