### ISSUE TITLE
Failed to open the DropBox link in the Frgapipe tutorial

### ISSUE THREAD

**Issue by Junzhimo** [Nesvilab/FragPipe#1167]
For Example: in the webpage of Using a custom offset workflow with FragPipe: RNA crosslinking analysis（https://fragpipe.nesvilab.org/docs/tutorial_custom_mass_offset.html）, all the DropBox link are failled to open.
I have checked my network connections and I can use the dropbox normally with my own files. However, when I click the DropBox hyperlink showed in the Fragpipe webpage tutorial. I failed to open the DropBox link. It showed:For some reason, the page is unavailable.
I guess If the files you uploaded to the dropbox have benn invalid. Could you please check it？ Without these files I can use some inportant functions of FragPipe.

Thank you very much.

Best Regards.

ZhouQing, PhD student, Fudan University, Shanghai,China.

**Comment by fcyu** [comment]
We are aware of this. Will fix it later.

Best,

Fengchao

**Comment by Junzhimo** [comment]
> We are aware of this. Will fix it later.
> 
> Best,
> 
> Fengchao

Dear Dr. Fengchao

I apologize for bothering you again, but I still haven't seen the Dropbox link restored. However, I am in urgent need of a file named "unimod_20191002_RNAadducts.txt". Would it be possible for you to send this file to my email? My email address is ymbright@foxmail.com. 
Thank you very much!

**Comment by Junzhimo** [comment]
> We are aware of this. Will fix it later.
> 
> Best,
> 
> Fengchao

I apologize for bothering you again, but I still haven't seen the Dropbox link restored. However, I am in urgent need of a file named "unimod_20191002_RNAadducts.txt". Would it be possible for you to send this file to my email? My email address is：  ymbright@foxmail.com

Thank you very much!

**Comment by fcyu** [comment]
I believe the `unimod_20191002_RNAadducts.txt` is distributed with FragPipe. In the `tools` folder.

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed.

**Comment by Junzhimo** [comment]
> Fixed.

Many Thanks.

**Comment by Junzhimo** [comment]
> I believe the `unimod_20191002_RNAadducts.txt` is distributed with FragPipe. In the `tools` folder.
> 
> Best,
> 
> Fengchao

OK，Let me check it. Thank you a lot.
