### ISSUE TITLE
Open Search Not Finding other PTMs

### ISSUE THREAD

**Issue by singjc** [Nesvilab/FragPipe#1168]
Hello,

I am trying to perform an Open Search in a single DDA file that is acquired from a cell line. I have loaded the Open workflow and the Open Search parameters in MSFragger in FragPipe 19.1.

However, when inspecting the results, there only appears to be N-term acetylation and oxidation, but not other modifications. However, if I do a closed search looking specifically for phosphorylation, and some other modifications, then MSFragger is able to find these modified peptides. If I'm not mistaken, the Open Search should be able to search for other types of modifications without me specifying specific ones? Is there other parameters I need to adjust in the settings to do this?

Thanks,

Justin

# Log
[log_2023-06-28_09-56-58.txt](https://github.com/Nesvilab/FragPipe/files/11919434/log_2023-06-28_09-56-58.txt)

# Screenshot of MSFragger settings

![image](https://github.com/Nesvilab/FragPipe/assets/32938975/172385be-ba23-4615-a7fc-ba0d9413189c)

![image](https://github.com/Nesvilab/FragPipe/assets/32938975/71c5d985-efd4-4dd5-8267-0b7a65d998da)

**Comment by fcyu** [comment]
Hi Justin,

If you were looking at the `psm.tsv`, the modifications from open search are in the form of delta mass in the `observed modification` column. 

You can also take a look at the `global.profile.tsv` and `global.modsummary.tsv` files which contains the modification summary from your sample.

Best,

Fengchao

**Comment by singjc** [comment]
Hi Fengchao,

Thank you for your quick reply. I have looked into those files, and they have some information of the modifications found, but there is only a limited amount of modifications found? It didn't find phosphorylation, which it was able to find in a closed search. I am wondering why the Open Search finds fewer modifications than the closed search?

I have attached the `psm.tsv`, and the PTM shephered output files for Open Search and Closed Search if you want to check.

# Open Search Output TSV files
[open_search.zip](https://github.com/Nesvilab/FragPipe/files/11919529/open_search.zip)

# Closed Search Output TSV files
[closed_search.zip](https://github.com/Nesvilab/FragPipe/files/11919550/closed_search.zip)

Thank you,

Justin

**Comment by fcyu** [comment]
Hi Justin,

Your [open_search.zip](https://github.com/Nesvilab/FragPipe/files/11919529/open_search.zip) was corrupted. I couldn't see what is in it. But, your log file shows that you did not perform the open search. Rather, you performed the mass-offset search:
```shell
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
mass_offsets = -0.984/-105.0248/-17.0265/-18.0106/-2.0157/-30.0106/-32.0085/-33.9877/-89.0299/0.0/0.984/100.016/1038.3751/1054.37/12.0/1216.4229/128.095/13.9793/1378.4757/14.0157/146.0579/15.9949/156.1011/162.0528/173.051/176.0321/178.0477/189.046/19.9898/203.0794/204.1878/21.9819/210.1984/228.111/238.2297/26.0157/27.9949/28.0313/29.9742/3.9949/31.9898/340.1006/349.1373/365.1322/37.9469/406.1587/42.0106/42.047/43.0058/43.9898/47.9847/52.9115/53.9193/57.02146/58.0055/61.9135/672.2225/71.0371/730.2644/79.9568/79.9663/876.3223/947.323/963.3179
```

Second, although phosphorylation (79.9663) is in the mass offset list, your data has few PSMs passing the FDR filtering:
```
time="09:56:37" level=info msg="Converged to 0.00 % FDR with 44 Proteins" decoy=0 threshold=0.9974 total=44
time="09:56:37" level=info msg="Applying sequential FDR estimation" ions=116 peptides=103 psms=597
time="09:56:37" level=info msg="Converged to 0.00 % FDR with 597 PSMs" decoy=0 threshold=0.8324 total=597
time="09:56:37" level=info msg="Converged to 0.00 % FDR with 103 Peptides" decoy=0 threshold=0.8931 total=103
time="09:56:37" level=info msg="Converged to 0.00 % FDR with 116 Ions" decoy=0 threshold=0.8767 total=116
```

I am not sure if PTM-Shepherd can get a good summarization with such limited PSMs. But you can take a look at the `Observed Modification` column in `psm.tsv` to see if there are any masses closed to 80.

Best,

Fengchao
