### ISSUE TITLE
Fragpipe analyst error

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1169]
- Describe the issue or question:
After analysis with fragpipe, I'm unabale to analyse my data for differential expression using Fragpipe analyst

I uploaded the combined protein_tsv and experiment annotation on fragpipe analyst but it says error. At the second attempt, it says disconnected from server and I tried to reload but couldnot connect to the server.  

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
I see that you have submitted another issuer here https://github.com/Nesvilab/FragPipe-Analyst/issues/14 . So, I close this one.

Best,

Fengchao
