### ISSUE TITLE
Fragpipe unable to access jar file.

### ISSUE THREAD

**Issue by bbhatt1789** [Nesvilab/FragPipe#117]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [o] question

* **My MSFragger use case:**
  - [o] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
I start the fragpipe.bat and it is unable to launch JVM saying it cannot find the jar file.

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ ** Windows
- Java version: ** _your response here_ ** 20190222

----

**Comment by guoci** [comment]
@bbhatt1789 Try starting the jar file instead.

**Comment by bbhatt1789** [comment]
The jar file works fine.

**Comment by chhh** [comment]
Ah, it's a packaging bug.  Will be fixed with the next release.  In the meantime the solution is to either get the `.exe` for Windows or just run the jar file.

**Comment by chhh** [comment]
Fixed in 9.3
