### ISSUE TITLE
Error: multiple databases referenced with ProteinProphet

### ISSUE THREAD

**Issue by ClaSofMag** [Nesvilab/FragPipe#1172]
Hello,

I got an error with ProteinProphet while running Fragpipe on Linux:

time="18:13:10" level=info msg="Executing ProteinProphet  v5.0.0"
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105021430-exported (Linux-x86_64))
time="18:13:10" level=error msg="Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files"
 (no FPKM) (no groups) (using degen pep info)
Reading in /home/claudia/fragpipe_output/challenge_10/interact-P_T6_P3.pep.xml...
Error: multiple databases referenced by /home/claudia/fragpipe_output/challenge_10/interact-P_T6_P3.pep.xml
Use RefreshParser to update all input files to common database
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

Here is the log
[fragpipe_plasma.5195.txt](https://github.com/Nesvilab/FragPipe/files/11947801/fragpipe_plasma.5195.txt)

Thank you for the support

**Comment by fcyu** [comment]
The error is a little weird. Could you remove the `,` in your fasta file name (`2023-06-29-decoys-contam-uniprot_eupercaria_895,538_2023.06.27.fasta) and try again?

Best,

Fengchao
