### ISSUE TITLE
Did you forget to run PeptideProphet? 

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#1173]
Describe the issue or question:
Apologies for re-opening this issue but there apparently was no definite solution following the previous posting on this issue (#1164) Fragpipe stopped working with this error message after trying to read the pepXML file->

Reading in   E:\QC2_runs_Bruker\202307\20230703\Mixed-II\3922_TEN\interact-20230703_QC2_brukerTen_Slot1-05_1_3922.pep.xml...

did not find any PeptideProphet results in input data! Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+,   0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
ERROR[16:12:23] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files
Process 'ProteinProphet' finished, exit   code: 1
Process returned non-zero exit code,   stopping

If I check the pepXML files, they are populated with data though and appear OK:

![image](https://github.com/Nesvilab/FragPipe/assets/16349515/909597ae-9994-4092-8db0-1d61b3250e84)

This phenomenon appeared on 6 DDA files only so far, 3 of them recorded with exactly the identical separation and MS methods as DDA runs before and afterwards, which worked fine. I am surprised anyway by this PeptideProphet thing, since using the default workflow settings, PSM validation is supposed to be done through Percolator and not PeptideProphet, isn´t it?

- Upload your log file
two log files enclosed (one with default settings, one using PeptideProphet)
[log_2023-07-04_16-07-44.zip](https://github.com/Nesvilab/FragPipe/files/11950596/log_2023-07-04_16-07-44.zip)
[log_2023-07-04_16-16-08.zip](https://github.com/Nesvilab/FragPipe/files/11950597/log_2023-07-04_16-16-08.zip)

**Comment by fcyu** [comment]
I think we have already answered your previous question clearly: https://github.com/Nesvilab/FragPipe/issues/1164#issuecomment-1614025274

The issue was in your data acquisition or searching parameter, not our software. With a different data file (https://github.com/Nesvilab/FragPipe/issues/1164#issuecomment-1613983371), FragPipe works well. It is normal that different mass spectrometry acquisitions get different quality of data, even with the same sample. Mistakes happen all the time.

It is obvious that with your data and setting, there is no ID. There was something wrong with either or data or your FragPipe settings.
```
*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
 002 | Not enough data to perform mass calibration. Using the uncalibrated data.
 003 | Not enough data to perform mass calibration. Using the uncalibrated data.
 004 | Not enough data to perform mass calibration. Using the uncalibrated data.
 005 | Not enough data to perform mass calibration. Using the uncalibrated data.
 006 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      4|      0| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |      4|      4|      0| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |      0
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |      4
-------|-------
```

If you still believe that your data and settings are good, please analyze the exact data with another tool and show me the result.

Best,

Fengchao
