### ISSUE TITLE
Peptide sequence number in PDV

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1174]
- Describe the issue or question:
Is there a way to see the sequence number for each peptide matched after running fragpipe. I can see the peptides, masses and length in PDV but I would like to see the sequence number for each peptide.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
What is the "sequence number" ? Could you elaborate it more?

Best,

Fengchao
