### ISSUE TITLE
 Error: No objects to concatenate

### ISSUE THREAD

**Issue by lzy604** [Nesvilab/FragPipe#1176]
Dear FragPipe developer,

Thanks for your pipeline. I used the Fragpipe to do the immunopeptidomics. I test 10 sample first and run successfully. But when I try to run the whole project, it failed. I attached the log file here. Thanks. 
[log_2023-07-01_22-03-34.txt](https://github.com/Nesvilab/FragPipe/files/11972726/log_2023-07-01_22-03-34.txt)

**Comment by anesvi** [comment]
1) You have some samples where there are no IDs. You will need to remove them. 2) why do you need to build a spectral library? And if you are building a library, you need to assign all files to the same experiment. So please read tutorials and figure out what you are trying to do before running FragPipe. 3) please also upgrade to FragPipe 20 and upgrade other tools as well.
