### ISSUE TITLE
Error: NullPointerException during MSBooster

### ISSUE THREAD

**Issue by owentsai** [Nesvilab/FragPipe#1177]
Hi Fragpipe team,

I'm running a closed search with MSBooster on over 100+ DDA files to generate a spectral library.  It's currently failing at the MSBooster step while processing one of the mzML files.  The error message is:

java.lang.NullPointerException
	at Features.mzMLReader.setPinEntries(mzMLReader.java:257)
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:361)
        at Features.MainClass.main(MainClass.java:588)

I also attached the log file.  I saw a couple similar issues but it seems that the problem was addressed in the later version of MSFragger.  I'm currently using Fragpipe v19.1, MSFragger 3.8, and Philosopher 5.0.0.  Thanks in advance!

[log_2023-07-06_21-46-18.txt](https://github.com/Nesvilab/FragPipe/files/11984465/log_2023-07-06_21-46-18.txt)

Owen

**Comment by fcyu** [comment]
Hi Owen,

I think you attached the wrong log file. But you need to upgrade the FragPipe to version 20. The version incompatibility should be the cause of the error.

Best,

Fengchao

**Comment by owentsai** [comment]
Hi Fengchao,

Sorry, I updated the issue with the right log file.  But I'll try running it again with the latest version of Fragpipe.  Thank you for the prompt response.

Owen

**Comment by owentsai** [comment]
Hi Fengchao,

I reran Fragpipe with the latest version 20 and it's still throwing the same error while processing the same file (see log).  The library generation was working when I used PeptideProphet.

Owen
[log_2023-07-07_18-52-20.txt](https://github.com/Nesvilab/FragPipe/files/11987247/log_2023-07-07_18-52-20.txt)

**Comment by fcyu** [comment]
I have no idea now. @yangkl96 can you take a look?

Thanks,

Fengchao

**Comment by owentsai** [comment]
Hi Fengchao,

I deleted the previously generated uncalibrated mzML files and re-ran Fragpipe and it works! So maybe the mzML files that were created by earlier version of MSFragger are not compatible anymore?

Owen
