### ISSUE TITLE
Export MS/MS spectrum of peptides

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1179]
- Describe the issue or question:
How can I export ms/ms spectrum of peptides from the PSM in mzml format ( not in picture format)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
No, you can't.

Best,

Fengchao
