### ISSUE TITLE
Error when trying to split database

### ISSUE THREAD

**Issue by blucherxeus** [Nesvilab/FragPipe#1181]
Hello MSFragger team

My database is about 270 mb, and i followed instructions, spliting database and reducing peptide length.
I'm getting the following error when I try to run FragPipe:
the log file is uploaded. thanks for your help.

Too many peptides were generated 2456533157! Could not continue. The limit is approximately 2 billion peptides. 
If running using FragPipe: in MSFragger tab, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
Traceback (most recent call last):
  File "E:\WFZ\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "E:\WFZ\fragpipe\tools\msfragger_pep_split.py", line 614, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "E:\WFZ\fragpipe\tools\msfragger_pep_split.py", line 494, in calibrate
    raise AssertionError(p)
AssertionError: <Popen: returncode: 1 args: ['E:\\WFZ\\fragpipe\\jre\\bin\\java.exe', '-jar'...>
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 15 remaining tasks

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-07-11_16-57-56.txt](https://github.com/Nesvilab/FragPipe/files/12012837/log_2023-07-11_16-57-56.txt)

**Comment by fcyu** [comment]
You still need to increase the number of splits. Keep trying until the error message like ` Too many peptides were generated 2456533157! Could not continue. The limit is approximately 2 billion peptides.` is gone.

Also, you probability would better to disable the mass calibration.

Best,

Fengchao
