### ISSUE TITLE
Question!    Extract unmatched Spectra

### ISSUE THREAD

**Issue by seongminlab** [Nesvilab/FragPipe#1184]
- Extract unmatched Spectra

After running pipeline,  how can i extract  unmatched spectra extract to mzML or .raw file for  secondary search?

is there functions or options in pipeline?  
Or does it provide unmatched spectra information in the form of mzML among the result files?

Thanks!

**Comment by fcyu** [comment]
Yes, in the latest FragPipe (version 20.0),  check `write sub mzML` in the `run` tab will work.

Best,

Fengchao
