### ISSUE TITLE
Unable to open FP.PDV file

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe#1186]
- Describe the issue or question:
After running analysis, I have my files saved but am unable to open FP. PDV file to view my result. The PDV the fragpipe would open the result of the last run

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
If you could open the last run but not your previous run sometime ago, it is likely that some of the files have been deleted/moved. Could you perform the search from scratch and try again? 

Best,

Fengchao
