### ISSUE TITLE
Ubiquitinated peptide

### ISSUE THREAD

**Issue by Retabir** [Nesvilab/FragPipe#1187]
Dear Fengchao/Alexey,
I am trying to search ubiquitinated peptide using FragPipe but the identification result does not look right comparing with other search engine o MSGF+. The data is from TMT labeled samples run with FAIMS-DDA. Do you have comment for me on how I should proceed? 
Thanks a lot.

**Comment by fcyu** [comment]
I think we can take a look. Could you please share the log files, mzML files, fasta files, and result files from both tools?

Thanks,

Fengchao

**Comment by anesvi** [comment]
Also, we have two TMT ubiquitination workflows , with TMT and ubiq either both or not on the same K. Make sure you use the right one ( with the modifications that match how you did your experiment? )
