### ISSUE TITLE
easypqp issue - DIA_SpecLib_Quant workflow fails on spectral library building - Linux

### ISSUE THREAD

**Issue by cscaife** [Nesvilab/FragPipe#1188]
- Describe the issue or question:
I am trying to get FragPipe setup on Linux (Ubuntu 22.04) and so far it runs perfectly for a standard LFQ-MBR run with DDA data. However when using the DIA_SpecLib_Quant workflow the run fails repeatedly at the spectral library building stage.

Using the GUI, easypqp _appears_ to be installed correctly, but the traceback information in the log file seem to be pointing to it as a culprit. 
(I have checked and all of the files listed/named in the Traceback are in the specified directories.)

I had downloaded python3.9 as I was having issues with python3.10 and pyopenms. I was wondering if this might have caused issues.

I would appreciate any help,

Caitriona

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-07-18_10-31-15.txt](https://github.com/Nesvilab/FragPipe/files/12080385/log_2023-07-18_10-31-15.txt)

**Comment by cscaife** [comment]
Thanks, I will try that out

Caitriona

**Comment by fcyu** [comment]
> Please use Anaconda Python. https://www.anaconda.com/download

Hi @guoci , in the tutorial, we recommend users to use the standard Python. Could you tell me why having to use the Anaconda Python in this case? I have been using the standard Python for a very long time, and have no issue.

Best,

Fengchao

**Comment by cscaife** [comment]
With that advice I think the issue is finally resolved.

I am using anaconda with a virtual environment for python3.9. After much
grief I finally realised that I was supposed to be running fragpipe *from
within this environment* ... it is now working perfectly

Thank you

Caitriona
