### ISSUE TITLE
Peptidomics cut off points & peptide probabilities

### ISSUE THREAD

**Issue by Litovk** [Nesvilab/FragPipe#1189]
Hello,
I want some help understanding why my data does not provide peptide probabilities with combined_peptides.tsv file. It is only provided in separate file folders for the experiments. How can I solve this issue or is there another way to set cut-off points using only MaxLFQ/Intensities from my combined_peptide file?

Thank you!
[log_2023-07-05_11-59-02.txt](https://github.com/Nesvilab/FragPipe/files/12080499/log_2023-07-05_11-59-02.txt)

**Comment by Litovk** [comment]
Hi, it is set to "Sequential prot 1" as this was the default setting with "Nonspecific peptidome" for DDA, as I understand the threshold is then set to 0.5?

**Comment by fcyu** [comment]
Do you mean `--prot 1`? Yes, the nonspecific peptidome workflow set the protein-level FDR to 100% because does not make much sense to perform the protein filtering in the peptidome data analysis. Other tryptic workflows have `--prot 0.01`.

Best,

Fengchao

**Comment by Litovk** [comment]
Would you happen to have any links to papers or a way to describe this process further? As I am struggling to understand how to verify my data for non-specific peptidome workflow.

**Comment by Litovk** [comment]
Thank you very much for your help!

**Comment by anesvi** [comment]
Validate what? Most Peptidome studies use peptide level FDR only. Setting --prot to 1 means that there is just peptide level FDR applied when looking at peptide.tsv files, as in those studies.
If you want to be more conservative and add protein level FDR, sure you can do it. Remove --prot 1 to get back to default of applying 1 percent protein FDR as well

**Comment by Litovk** [comment]
As we have the protein probabilities and we can decide a cut-off point for those proteins - we have no exact way to do this for the combined_peptide.tsv file.

**Comment by fcyu** [comment]
I don't think you need to worry about the protein probabilities when filtering the results. Four levels (PSM, ion, peptide, and protein) of FDR filters should be good enough for you.

Best,

Fengchao
