### ISSUE TITLE
Different abundance values for same PTM site

### ISSUE THREAD

**Issue by arcolaco** [Nesvilab/FragPipe#1190]
Dear FragPipe team,
We ran a PTM experiment with TMT labelling and are now analysing the results from the TMT-integrator output.
In some cases, we find entries in the multi-site table where the only difference in the identifier is in the "count of the possible sites in that sequence window", as per your documentation, while the abundances for the same sample are quite different.
Please see example below.

![Screenshot 2023-07-18 at 15 06 18](https://github.com/Nesvilab/FragPipe/assets/46528924/00ebf8e0-a5cf-4eec-88cc-c19c11d1e916)

I have been unable to find an explanation for this. Could you help us understand why this happens?
Thank you in advance.

Rita

**Comment by anesvi** [comment]
One entry is doubly phosphorylated version (2_1... in the index), even though only one of the two sites was localized with confidence. The other entry is mono. The multi-site reports tracks them separately.

**Comment by arcolaco** [comment]
That makes sense, thank you.
