### ISSUE TITLE
java.lang.IllegalStateException: Process returned non zero value

### ISSUE THREAD

**Issue by EayonYang** [Nesvilab/FragPipe#1193]
- Describe the issue or question:

When I add the decoy library, the following error occurs, and try to run philosopher and do not get the error result, do not know what the problem is.
![image](https://github.com/Nesvilab/FragPipe/assets/95112283/3fa53ad0-f846-4ecb-b27d-ca109c80ace3)
![image](https://github.com/Nesvilab/FragPipe/assets/95112283/e19c0c97-7bd1-4295-a83e-e1b0b9f48796)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
I think the command you ran was different from the FragPipe one which returned errors. There was no `--contam` and `--contamprefix` flags because you did not click `add contam` in FragPipe.

Could you try without those two flags in the cmd and see if you can reproduce the error?

Thanks,

Fengchao
