### ISSUE TITLE
PhilosopherReport error in FragPipe

### ISSUE THREAD

**Issue by ShelleyJager** [Nesvilab/FragPipe#1197]
Hi, 
I frequently use MS Fragger / Fragpipe to analyze glycoproteomics samples, however, i frequently get the same error and i do not know how to overcome it. 
The error arises in the PhilosopherReport and it reads:

> ERRO[01:32:06] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 
> Process 'PhilosopherReport' finished, exit code: 1

I compared this to a previous run that did succeed, and already in WorkspaceCleanInit it gives warnings (filename replaced by FILENAME):

> WorkspaceCleanInit [Work dir: D:\07-July\5858593\rerun_output2\FILENAME]
> D:\MSfragger\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --clean --nocheck
> INFO[09:10:31] Executing Workspace  v5.0.0                  
> INFO[09:10:31] Removing workspace                           
> WARN[09:10:31] Cannot read file. open .meta\meta.bin: The system cannot find the path specified. 
> INFO[09:10:31] Done                                         
> Process 'WorkspaceCleanInit' finished, exit code: 0
> WorkspaceCleanInit [Work dir: D:\07-July\5858593\rerun_output2\FILENAME]
> D:\MSfragger\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --init --nocheck --temp C:\Users\SCIENC~1.PRO\AppData\Local\Temp\d0cf20a0-f5d2-4834-9641-9e10382ab11f
> INFO[09:10:31] Executing Workspace  v5.0.0                  
> INFO[09:10:31] Creating workspace                           
> INFO[09:10:31] Done                                         

How can I overcome this problem? 

[log_2023-07-20_13-18-38.zip](https://github.com/Nesvilab/FragPipe/files/12169621/log_2023-07-20_13-18-38.zip)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
For the first error `ERRO[01:32:06] Cannot read file. open .meta\pep.bin: The system cannot find the file specified.`, please upgrade FragPipe to the latest version (20.0).

For the warning when running `philosopher clean` command:`WARN[09:10:31] Cannot read file. open .meta\meta.bin: The system cannot find the path specified.`, you can ignore it. This warning is actually not necessary and won't affect the results.

Best,

Fengchao

**Comment by ShelleyJager** [comment]
After updating I get a different error that I don't know how to solve.

> Fixing pepxml: D:\07-July\5858593\hilictest\output2\20230627_TIMSTOF_UM6_5858593_SA_EXT00_glycoQC2_1_BC12_1_1176\interact.pep.xml
Writing output to: D:\07-July\5858593\hilictest\output2\20230627_TIMSTOF_UM6_5858593_SA_E
[log_2023-07-26_22-08-26.zip](https://github.com/Nesvilab/FragPipe/files/12180032/log_2023-07-26_22-08-26.zip)
XT00_glycoQC2_1_BC12_1_1176\interact.pep.xml2891995814159310455.temp-rewrite
Didn't find correct mapping for raw file path in pepxml: D:\07-July\5858593\hilictest\output2\20230627_TIMSTOF_UM6_5858593_SA_EXT00_glycoQC2_1_BC12_1_1176/20230627_TIMSTOF_UM6_5858593_SA_EXT00_glycoQC2_1_BC12_1_1176Process 'Rewrite pepxml' finished, exit code: 1

How can I fix this? I am analyzing timsTOF files.

[log_2023-07-26_22-08-26.zip](https://github.com/Nesvilab/FragPipe/files/12180032/log_2023-07-26_22-08-26.zip)
