### ISSUE TITLE
How to obtain the files "combined_peptide.tsv" and "combined_protein.tsv"

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1199]
Describe the issue or question: 
I am using FragPipe and I would like to obtain the files "combined_peptide.tsv" and "combined_protein.tsv". By running FragPipe, I did not obtain these two files, even if they are included in the list of the main report files on this page: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html. Could you suggest some methods I could try to get them? Thank you very much!

**Comment by danielgeiszler** [comment]
These files are produced by IonQuant after performing LFQ. You need to choose a workflow that performs LFQ if you want these files.

**Comment by RobAlbn** [comment]
Thank you for your answer! Therefore, it's not possible to get them if I am working on TMT data, right? Thank you again

**Comment by fcyu** [comment]
It is possible. Just enable `generate peptide-level summary` and `generate protein-level summary`.

<img width="283" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/27f86312-03fe-4c7c-bf26-a0e3bbac8eed">

But, those two files are not quite useful for the TMT analysis. You need to use the tables in the TMT-Integrator report folder.

Best,

Fengchao

**Comment by RobAlbn** [comment]
Thank you very much for your answer! I plan to use those two files to get information about protein groups by using the columns "Protein ID" and "Indistinguishable Proteins". Regarding quantification, I'll use the abundance values in the TMT-Integrator report folder. 
Best, 
Roberto
