### ISSUE TITLE
Problem running software - keeps halting

### ISSUE THREAD

**Issue by szackloo** [Nesvilab/FragPipe#120]
# Describe the problem - seems to be a memory issue - have 16 Gb

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _Win7 AMD64_ **
- Java version: **1.8.0_211**

----

### Extremely simple - purified protein binary complex (two - five proteins total) and digested by trypsin.

...

### Input data files
mzml files

### Sequence database

** human **  
** 40000 entries**

----

## Attach fragger.params file

** _database_name = C:\Users\Suzanne Ackloo\Documents\Fasta files\Fasta files\2019-06-17-td-rev-UP000005640.fas
num_threads = 4			# 0=poll CPU to set num threads; else specify num threads directly (max 64)

precursor_mass_lower = -50
precursor_mass_upper = 50
precursor_mass_units = 1			# 0=Daltons, 1=ppm
precursor_true_tolerance = 30
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 100
fragment_mass_units = 1			# 0=Daltons, 1=ppm
calibrate_mass = 2			# 0=Off, 1=On, 2=On and find optimal parameters
decoy_prefix = rev_

isotope_error = -1/0/1/2			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted â€˜openâ€™ search that looks for unmodified and phosphorylated peptides (on any residue)
precursor_mass_mode = selected

localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y

search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P

num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 2			# maximum value is 5

clip_nTerm_M = 0

#maximum of 7 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
# variable_mod_06 = 0.00000 site_06
# variable_mod_07 = 0.00000 site_07

allow_multiple_variable_mods_on_residue = 0			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence

output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50
report_alternative_proteins = 1			# 0=no, 1=yes

precursor_charge = 2 4			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter

digest_min_length = 7
digest_max_length = 50
digest_mass_range = 200.0 5000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 3			# set maximum fragment charge state to analyze (allowed max 5)

#open search parameters
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0.00			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1.00			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0

# spectral processing

minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 100
min_fragments_modelling = 3
min_matched_fragments = 4
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range

# additional modifications

add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000

add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000

_ **

## Run log output

```
** copy text from the text console in the gui here **
```
System info:
System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190530
Philosopher version v1.0.1 (build 1558718856)

LCMS files:
  Experiment/Group: 
  - C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.mzML
  - C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1C1 soln_A6483.mzML

12 commands to execute:
Workspace [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe workspace --clean
Workspace [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe workspace --init
MsFragger [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
java -jar -Dfile.encoding=UTF-8 -Xmx1G C:\Users\Suzanne Ackloo\MSFragger-20190530\MSFragger-20190530.jar C:\Users\Suzanne Ackloo\Desktop\Fragger output\fragger.params C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.mzML C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1C1 soln_A6483.mzML
MsFragger
java -cp C:\Users\Suzanne Ackloo\MSFragger-20190530\FragPipe.exe umich.msfragger.util.FileMove C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.pepXML C:\Users\Suzanne Ackloo\Desktop\Fragger output\Digest test-60min_D1 soln_B6486.pepXML
MsFragger
java -cp C:\Users\Suzanne Ackloo\MSFragger-20190530\FragPipe.exe umich.msfragger.util.FileMove C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1C1 soln_A6483.pepXML C:\Users\Suzanne Ackloo\Desktop\Fragger output\Digest test-60min_D1C1 soln_A6483.pepXML
ReportDbAnnotate [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe database --annotate C:\Users\Suzanne Ackloo\Documents\Fasta files\Fasta files\HUMAN_validated.fasta --prefix rev_
PeptideProphet [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Users\Suzanne Ackloo\Documents\Fasta files\Fasta files\HUMAN_validated.fasta Digest test-60min_D1 soln_B6486.pepXML
PeptideProphet [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Users\Suzanne Ackloo\Documents\Fasta files\Fasta files\HUMAN_validated.fasta Digest test-60min_D1C1 soln_A6483.pepXML
ProteinProphet [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe proteinprophet --maxppmdiff 2000000 C:\Users\Suzanne Ackloo\Desktop\Fragger output\interact-Digest test-60min_D1 soln_B6486.pep.xml C:\Users\Suzanne Ackloo\Desktop\Fragger output\interact-Digest test-60min_D1C1 soln_A6483.pep.xml
ReportFilter [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\Users\Suzanne Ackloo\Desktop\Fragger output --protxml C:\Users\Suzanne Ackloo\Desktop\Fragger output\interact.prot.xml
ReportReport [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe report
Workspace [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe workspace --clean
INFO[14:08:01] Executing Workspace v1.0.1                   
INFO[14:08:03] Removing workspace                           
INFO[14:08:03] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
C:\Users\Suzanne Ackloo\MSFragger-20190530\philosopher.exe workspace --init
INFO[14:08:03] Executing Workspace v1.0.1                   
INFO[14:08:04] Creating workspace                           
INFO[14:08:04] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\Users\Suzanne Ackloo\Desktop\Fragger output]
java -jar -Dfile.encoding=UTF-8 -Xmx1G C:\Users\Suzanne Ackloo\MSFragger-20190530\MSFragger-20190530.jar C:\Users\Suzanne Ackloo\Desktop\Fragger output\fragger.params C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.mzML C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1C1 soln_A6483.mzML
MSFragger version MSFragger-20190530
MSFTBX version 1.9.10
(c) University of Michigan

System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 910 MB memory

***********************************FIRST SEARCH************************************
Parameters used in this search:
num_threads = 4
database_name = C:\Users\Suzanne Ackloo\Documents\Fasta files\Fasta files\HUMAN_validated.fasta
decoy_prefix = rev_
precursor_mass_lower = -30.0
precursor_mass_upper = 30.0
precursor_mass_units = 1
precursor_true_tolerance = 30.0
precursor_true_units = 1
fragment_mass_tolerance = 100.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = false
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 2
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 200.0
digest_mass_range_high = 5000.0
max_fragment_charge = 3
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 4
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
variable_mod_03 = 79.96633 STY
Number of unique peptides
	of length 7: 123460
	of length 8: 114318
	of length 9: 108692
	of length 10: 100719
	of length 11: 93074
	of length 12: 86081
	of length 13: 81536
	of length 14: 73427
	of length 15: 69251
	of length 16: 63252
	of length 17: 57909
	of length 18: 54561
	of length 19: 50371
	of length 20: 46341
	of length 21: 43130
	of length 22: 39597
	of length 23: 37183
	of length 24: 34815
	of length 25: 32037
	of length 26: 29648
	of length 27: 28108
	of length 28: 26394
	of length 29: 23979
	of length 30: 22392
	of length 31: 20556
	of length 32: 19144
	of length 33: 17696
	of length 34: 16498
	of length 35: 15033
	of length 36: 14322
	of length 37: 12736
	of length 38: 11904
	of length 39: 10752
	of length 40: 10226
	of length 41: 9543
	of length 42: 8614
	of length 43: 7482
	of length 44: 6104
	of length 45: 4843
	of length 46: 3293
	of length 47: 2120
	of length 48: 1260
	of length 49: 716
	of length 50: 395
In total 1633512 peptides.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.a.a(Unknown Source)
	at edu.umich.andykong.msfragger.K.a(Unknown Source)
	at edu.umich.andykong.msfragger.q.a(Unknown Source)
	at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at edu.umich.andykong.msfragger.b.a(Unknown Source)
	at edu.umich.andykong.msfragger.a.a(Unknown Source)
	at edu.umich.andykong.msfragger.a$$Lambda$22/1161082381.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp C:\Users\Suzanne Ackloo\MSFragger-20190530\FragPipe.exe umich.msfragger.util.FileMove C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.pepXML C:\Users\Suzanne Ackloo\Desktop\Fragger output\Digest test-60min_D1 soln_B6486.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 10/13 processes (3 already finished)
Processing interrupted, stopping MsFragger

**Comment by fcyu** [comment]
Hi,

From the command 
```
java -jar -Dfile.encoding=UTF-8 -Xmx1G C:\Users\Suzanne Ackloo\MSFragger-20190530\MSFragger-20190530.jar C:\Users\Suzanne Ackloo\Desktop\Fragger output\fragger.params C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1 soln_B6486.mzML C:\Users\Suzanne Ackloo\Desktop\Digest test-60min_D1C1 soln_A6483.mzML
```
you only provided 1GB to java, which was far from enough. I suggest you specifying as much as your PC have to `RAM (GB)` in the MSFragger tab of FragPipe.

Bests,

Fengchao

**Comment by guoci** [comment]
Please see https://github.com/Nesvilab/FragPipe/issues/113#issuecomment-487608742
