### ISSUE TITLE
Whether there is a result file description document？

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1201]
Dear author, thank you very much for the convenience of this software developed by your team!
Why does the peptide in the result file and psm contain different information about peptide segments? The peptide table contains more information about peptide segments. Is there any related documentation in the description of the result files?
Hope to get your reply and help.
With best wishes!!!
Mingsong Mao.

**Comment by fcyu** [comment]
https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html
