### ISSUE TITLE
psm.tsv (The system cannot find the file specified). 

### ISSUE THREAD

**Issue by bioinformatic-guy** [Nesvilab/FragPipe#1202]
[log_2023-07-30_17-37-08.txt](https://github.com/Nesvilab/FragPipe/files/12209189/log_2023-07-30_17-37-08.txt)
[log_2023-07-29_17-03-34.txt](https://github.com/Nesvilab/FragPipe/files/12209190/log_2023-07-29_17-03-34.txt)

- I want to run DDA .raw file from Thermo output but facing difficulty. 
- First, I tried with Fragpipe v 20 by taking .raw file
- second, converted .raw file into mzml, considering filter peak picking but result is same. 
- I attached both log file for reference.
- Can anyone tell me, what's the possible solution?

**Comment by danielgeiszler** [comment]
It looks like you've disabled some of the critical modules, such as the validation tab. Please reload one of the included workflows, and try again.

**Comment by bioinformatic-guy** [comment]
Yes, I'm new to this tools. And I used LFQ-MBR workflow. I have tried with validation tab ticked as well but result was kind of similar. @danielgeiszler

**Comment by fcyu** [comment]
As @danielgeiszler pointed out, please load one of the built-in workflow (**Click "Load" to make sure that the workflow is loaded**), and do not make any unnecessary changes.

Your log shows that you were not using any of the built-in workflows:

```
~~~~~~~~~~~~~~~~~~~~~~

Execution order:

    Cmd: [START], Work dir: [D:\Internship_IIT_B\MAPS2023\Output]
    Cmd: [CheckCentroid], Work dir: [D:\Internship_IIT_B\MAPS2023\Output]
    Cmd: [MSFragger], Work dir: [D:\Internship_IIT_B\MAPS2023\Output]
    Cmd: [PTMShepherd], Work dir: [D:\Internship_IIT_B\MAPS2023\Output]

~~~~~~~~~~~~~~~~~~~~~~
```

Best,

Fengchao

**Comment by danielgeiszler** [comment]
You sent two log files, both of which have the validation tab disabled.

Please load a default workflow, do not change any parameters, and try again.

**Comment by bioinformatic-guy** [comment]
Okay, Thanks @fcyu and @danielgeiszler for your help. 

I have tried again with .mzml file with validation ticked. I had successfully generated the output file.
