### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by drstiltz** [Nesvilab/FragPipe#1204]
Hello,

I've been trying to use Fragpipe on a powerful Windows 7 computer. Which version of Fragpipe and attached software are compatible with this version of Windows? Thank you.

**Comment by fcyu** [comment]
Just make sure use Java 9+ and Python 3.9.

Best,

Fengchao

**Comment by drstiltz** [comment]
To install Python 3.9, it needs Windows 8 it says. 
Sadly, due to a background software we have to keep using Windows 7 on our computer. Is there a way I install Python 3.9 on Wİndows 7? or use an older version of Fragpipe?

**Comment by fcyu** [comment]
I don't know if there is a way to install Python 3.9 in Win 7. But, if you won't analyze DIA data or won't split the database due to large search space (likely you won't), you don't need to have Python 3.9 installed.

Best,

Fengchao
