### ISSUE TITLE
Addition of contaminant marking column in combined protein.tsv 

### ISSUE THREAD

**Issue by SC0O8Y** [Nesvilab/FragPipe#1205]
Hey Team, 

I was wondering if it is possible to add a column for denoting a contaminant protein, that is one from the automated addition database. A simple workaround would be the addition of a handle in the protein description so as to pull the proteins out from the analysis i.e. "CON_" or a special character i.e. " * ". I know i could also manually go ahead and edit the contaminants headers from the created .fas file, but this may drive me a tad nuts for the amount searches and databases I generate. 

Also sort of aware that this relates to posts #1081 and #367 but in a slightly different way, the ability to specify a second proteome i.e. the contaminants then mark the origin of the match would be in a similar vain. 

Kindest regards, 
Joel

**Comment by fcyu** [comment]
Currently, you can let FragPipe filter out contaminant proteins by enabling a checkbox in the Validation tab.

Best,

Fengchao

**Comment by SC0O8Y** [comment]
Hi team,

I do understand that their is a checkbox for the removal. But this doesn't
allow you to assess the quality of the experiment and certain contaminants
effects on the quantiation and identification of particular samples. It is
super handy to have the contaminant marked in the output protein level file
(and even yhe peptide file, this is especially important in LIPS and
peptide/ptm centric analysis).

Kindest regards
Joel

**Comment by fcyu** [comment]
I am sorry I don't get it. The contaminant proteins have `contam_` prefix, which makes it easy to parse and filter.

Best,

Fengchao

**Comment by SC0O8Y** [comment]
Ah, yes that is indeed helpful when parsing through regular expression filtering. But if you have a protein that can be both a target and also matches a contaminant, you would then not be filtering correctly if it was in one but not the other column on an entry. The aim here is a simple filtering by one column rather than needing to do both.

Kind regards

Joel Steele
PhD candidate,
Casual Academic, B.MSc (Hons 1)
University of Technology Sydney
Ph: 0434579993
PO Box 123, Broadway, 2007
NSW, Australia
https://www.linkedin.com/in/joel-r-steele

I acknowledge the traditional custodians of knowledge and land; the Gadigal people of the Eora Nation, on whose land I live and work.

￼
________________________________

**Comment by fcyu** [comment]
After protein inference, I think you should use the `protein` column, but not the `mapped proteins` column in the filtering.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, use protein column. If a peptide has a non-contaminant sequence there, I do not see why you would want to remove it. Maybe there are some special cases, but at any rate you can apply your own custom filtering then.
