### ISSUE TITLE
ERRO[09:47:55] Cannot read file. open D:\.meta/protxml.bin: The system cannot find the file specified. 

### ISSUE THREAD

**Issue by alima82** [Nesvilab/FragPipe#1206]
- Describe the issue or question:
Hello,

I'm trying to run a LFQ but I'm getting this error. Any suggestion?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-08-01_09-47-55.txt](https://github.com/Nesvilab/FragPipe/files/12230390/log_2023-08-01_09-47-55.txt)

**Comment by dpolasky** [comment]
It looks like you have two experiments/groups named "High" and "high", which is confusing some of the tools:
`LCMS files:
  Experiment/Group: **High**
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_High_1_250ng_R1_Slot1-3_1_3025.d	DDA
  Experiment/Group: **high**
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_High_1_250ng_R2_Slot1-3_1_3026.d	DDA
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_High_1_250ng_R3_Slot1-3_1_3027.d	DDA
  Experiment/Group: low
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_Low_1_250ng_R1_Slot1-2_1_3022.d	DDA
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_Low_1_250ng_R2_Slot1-2_1_3023.d	DDA
  - D:\Data\Billerica\NE\DDA\NE\20211208_ADH_Low_1_250ng_R3_Slot1-2_1_3024.d	DDA`

Renaming the experiments to unique names (or merging "High" and "high" to a single experiment) I think should resolve the issue. 

Best,
Dan

**Comment by fcyu** [comment]
Right, Windows folder and file names are case insensitive.

Best,

Fengchao
