### ISSUE TITLE
I am getting the following error whic is below when I run FragPipe on my Ubuntu machine 22.04 how do we fix this?

### ISSUE THREAD

**Issue by Mahendra687** [Nesvilab/FragPipe#1207]
[log.txt](https://github.com/Nesvilab/FragPipe/files/12232898/log.txt)
- Describe the issue or question:

CheckCentroid
java -Xmx2G -cp /home/ms/MS/fragpipe/lib/fragpipe-20.0.jar:/home/ms/MS/fragpipe/tools/batmass-io-1.28.12.jar com.dmtavt.fragpipe.util.CheckCentroid /home/ms/MS/Control_1.raw 7
Done in 0.0 s.
Process 'CheckCentroid' finished, exit code: 0
MSFragger [Work dir: /home/ms/MS/Output]
java -jar -Dfile.encoding=UTF-8 -Xmx2G /home/ms/MS/fragpipe/tools/MSFragger-3.8/MSFragger-3.8.jar /home/ms/MS/Output/fragger.params /home/ms/MS/Control_1.raw /home/ms/MS/Treated_1.raw
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 17.0.8, OpenJDK 64-Bit Server VM, Private Build
JVM started with 2 GB memory
Checking database...
Failed in checking /home/ms/MS/Control_1.raw. Will ignore it.
Failed in checking /home/ms/MS/Treated_1.raw. Will ignore it.
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found
There are corrupted files. Please remove those files and re-start the task.
Checking spectral files...
/home/ms/MS/Control_1.raw: Scans = 0
/home/ms/MS/Treated_1.raw: Scans = 0
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks

**Comment by fcyu** [comment]
Yes, please convert the files to mzML format.

Also, it seems that there were only 1 GB free memory. You probably need to find a computer with more memory.

Best,

Fengchao

**Comment by Mahendra687** [comment]
Thanks, after installing the Mono its works properly
