### ISSUE TITLE
Phospho STY best localization report

### ISSUE THREAD

**Issue by Sarkar0224** [Nesvilab/FragPipe#1209]
- Describe the issue or question:
I am using fragpipe to analyze multiple TMT16plex phospho dataset and wanted to know a way to have STY best localization values, which is reported in the PSM file for each plex, in the TMT-report/abundance_singlesite_MD and abundance_multisite_MD files? Any info would be much appreciated. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by anesvi** [comment]
At this point TMT-Integrator does not propagate that info to the output, unfortunately. So you would have to match against PSM.tsv files yourself  to extract that info

**Comment by anesvi** [comment]
I don't have any simple trick to suggest, you need to find all peptides with the specific site marked and see what was the highest localization probability. Certainly writing a script is required, but we do not have anything ready here for such a task, as far as I know

**Comment by Sarkar0224** [comment]
I appreciate the help. Thanks
