### ISSUE TITLE
Crash on processing tims tof pro mgf (from msconvert)

### ISSUE THREAD

**Issue by exactive** [Nesvilab/FragPipe#121]
Log 

System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190222
Philosopher version v1.1.2 (build 1560970349)

LCMS files:
  Experiment/Group: 1
  - C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.mgf
  Experiment/Group: 2
  - C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.mgf
  Experiment/Group: 3
  - C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.mgf

35 commands to execute:
Workspace [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
MsFragger [Work dir: C:\brett\ttp]
java -jar -Dfile.encoding=UTF-8 -Xmx20G C:\brett\fragpipe\Brett\MSFragger-20190222\MSFragger-20190222\MSFragger-20190222.jar C:\brett\ttp\fragger.params C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.mgf C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.mgf C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.mgf
MsFragger
java -cp C:\brett\fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pepXML C:\brett\ttp\1\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pepXML
MsFragger
java -cp C:\brett\fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.pepXML C:\brett\ttp\2\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.pepXML
MsFragger
java -cp C:\brett\fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.pepXML C:\brett\ttp\3\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.pepXML
ReportDbAnnotate [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe database --annotate C:\brett\fragpipe\2018-11-02-td-UP000005640.fas --prefix rev_
ReportDbAnnotate [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe database --annotate C:\brett\fragpipe\2018-11-02-td-UP000005640.fas --prefix rev_
ReportDbAnnotate [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe database --annotate C:\brett\fragpipe\2018-11-02-td-UP000005640.fas --prefix rev_
ReportDbAnnotate [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe database --annotate C:\brett\fragpipe\2018-11-02-td-UP000005640.fas --prefix rev_
PeptideProphet [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\brett\fragpipe\2018-11-02-td-UP000005640.fas 190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.pepXML
PeptideProphet [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\brett\fragpipe\2018-11-02-td-UP000005640.fas 190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pepXML
PeptideProphet [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\brett\fragpipe\2018-11-02-td-UP000005640.fas 190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.pepXML
iProphet [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe iprophet --decoy rev_ --nonsp --output interact --threads 14 C:\brett\ttp\2\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.pep.xml C:\brett\ttp\1\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pep.xml C:\brett\ttp\3\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.pep.xml
ProteinProphet [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 C:\brett\ttp\2\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.pep.xml C:\brett\ttp\1\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pep.xml C:\brett\ttp\3\interact-190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.pep.xml
ReportFilter [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\brett\ttp\2 --protxml C:\brett\ttp\interact.prot.xml
ReportFilter [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\brett\ttp\3 --protxml C:\brett\ttp\interact.prot.xml
ReportFilter [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\brett\ttp\1 --protxml C:\brett\ttp\interact.prot.xml
ReportFreequant [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --isolated --dir C:\brett\ttp
ReportFreequant [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --isolated --dir C:\brett\ttp
ReportFreequant [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --isolated --dir C:\brett\ttp
ReportReport [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe report --mzid
ReportReport [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe report --mzid
ReportReport [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe report --mzid
ReportAbacus [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe abacus --razor --reprint --tag rev_ --protein C:\brett\ttp\interact.prot.xml --peptide C:\brett\ttp\interact.pep.xml 2 3 1
Workspace [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
INFO[14:18:03] Executing Workspace v1.1.2                   
INFO[14:18:04] Removing workspace                           
INFO[14:18:04] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
INFO[14:18:04] Executing Workspace v1.1.2                   
INFO[14:18:04] Creating workspace                           
INFO[14:18:04] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
INFO[14:18:04] Executing Workspace v1.1.2                   
INFO[14:18:05] Removing workspace                           
INFO[14:18:05] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\1]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
INFO[14:18:05] Executing Workspace v1.1.2                   
INFO[14:18:05] Creating workspace                           
INFO[14:18:05] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
INFO[14:18:06] Executing Workspace v1.1.2                   
INFO[14:18:06] Removing workspace                           
INFO[14:18:06] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\2]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
INFO[14:18:06] Executing Workspace v1.1.2                   
INFO[14:18:07] Creating workspace                           
INFO[14:18:07] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --clean
INFO[14:18:07] Executing Workspace v1.1.2                   
WARN[14:18:07] GitHub unreachable for the moment, can't check for versions right now. 
INFO[14:18:07] Removing workspace                           
INFO[14:18:07] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\brett\ttp\3]
C:\brett\fragpipe\philosopher_v1.1.2_windows_amd64\philosopher.exe workspace --init
INFO[14:18:07] Executing Workspace v1.1.2                   
WARN[14:18:07] GitHub unreachable for the moment, can't check for versions right now. 
INFO[14:18:07] Creating workspace                           
INFO[14:18:07] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\brett\ttp]
java -jar -Dfile.encoding=UTF-8 -Xmx20G C:\brett\fragpipe\Brett\MSFragger-20190222\MSFragger-20190222\MSFragger-20190222.jar C:\brett\ttp\fragger.params C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.mgf C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep2_90min_gradient_Slot2-19_01_3372.mgf C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep3_90min_gradient_Slot2-19_01_3373.mgf
MSFragger version MSFragger-20190222
MSFTBX version 1.8.6
(c) University of Michigan

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 18204MB memory

Unknown parmameters:
	calibrate_mass = 1
	decoy_prefix = rev_
	delta_mass_exclude_ranges = (-1.5,3.5)
	fragment_ion_series = b,y
	localize_delta_mass = 0
Peptide index read in 301ms
Selected fragment tolerance 0.20 Da and maximum fragment slice size of 13693.15MB
418266908 fragments to be searched in 1 slices (3.12GB total)
Operating on slice 1 of 1: 2761ms
	190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.mgf Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 16384
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.l.a(Unknown Source)
	at edu.umich.andykong.msfragger.o.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16384
	at edu.umich.andykong.msfragger.l.a(Unknown Source)
	at edu.umich.andykong.msfragger.m.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp C:\brett\fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\brett\ttp\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pepXML C:\brett\ttp\1\190329_Aurora_UCDAVIS_HeLa_spike_A_R1_2_Rep1_90min_gradient_Slot2-19_01_3371.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 27/36 processes (9 already finished)
Processing interrupted, stopping MsFragger

Parameters

database_name = C:\brett\fragpipe\2018-11-02-td-UP000005640.fas
num_threads = 14			# 0=poll CPU to set num threads; else specify num threads directly (max 64)

precursor_mass_lower = -20
precursor_mass_upper = 20
precursor_mass_units = 1			# 0=Daltons, 1=ppm
precursor_true_tolerance = 20
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 40
fragment_mass_units = 1			# 0=Daltons, 1=ppm
calibrate_mass = 1			# 0=Off, 1=On, 2=On and find optimal parameters
decoy_prefix = rev_

isotope_error = 0/1/2			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and phosphorylated peptides (on any residue)
precursor_mass_mode = selected

localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y

search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P

num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 1			# maximum value is 5

clip_nTerm_M = 1

#maximum of 7 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
variable_mod_05 = -18.01060 nE
# variable_mod_06 = 0.00000 site_06
# variable_mod_07 = 0.00000 site_07

allow_multiple_variable_mods_on_residue = 1			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence

output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50
report_alternative_proteins = 0			# 0=no, 1=yes

precursor_charge = 1 4			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter

digest_min_length = 7
digest_max_length = 50
digest_mass_range = 500.0 5000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 2			# set maximum fragment charge state to analyze (allowed max 5)

#open search parameters
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0.00			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1.00			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0

# spectral processing

minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 150
min_fragments_modelling = 2
min_matched_fragments = 4
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range

# additional modifications

add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000

add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000

**Comment by fcyu** [comment]
Hi,

Thanks for your interest in MSFragger. Since MGF format has many flavor of its title, we need an example of yours so that we can add it to the parser function.

Thanks,

Fengchao

**Comment by anesvi** [comment]
Best to use mzML/mzXML from MSConvert, this is what we really support well
