### ISSUE TITLE
ERRO:Cannot read file. open .meta\psm.bin: The system cannot find the file specified. 

### ISSUE THREAD

**Issue by yuewang-wy** [Nesvilab/FragPipe#1210]
- Describe the issue or question:
I'm submitting a:

[ X] problem running the software
✔ bug report
      feature request
      question
My MSFragger use case:

[ X] ✔Closed search (standard small precursor mass tolerance)
      Open search (large precursor mass tolerance)
** put your general problem description here **

System info
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 18.0
MSFragger version 3.8
Philosopher version 5.0.0
IonQuant version 1.9.8

Genral proteomics experiment description
e.g. "TMT, Mouse, full cell lysate with Trypsin，multi-sets of TMT" 

Sequence database
mouse uniprot

- Upload your log file

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
Process 'PhilosopherFilter' finished, exit code: 0
FreeQuant [Work dir: I:\Data\dataIndividual\SCP\20230704\test\set4]
D:\FragPipe-18.0\philosopher_v5.0.0_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --dir I:\Data\dataIndividual\SCP\20230704\test
INFO[10:07:37] Executing Label-free quantification  v5.0.0  
INFO[10:07:38] Indexing PSM information                     
INFO[10:07:38] Reading spectra and tracing peaks            
INFO[10:07:38] Processing TMT18_Set4_20230704 
INFO[10:08:24] Assigning intensities to data layers         
INFO[10:08:24] Done                                         
Process 'FreeQuant' finished, exit code: 0
FreeQuant [Work dir: I:\Data\dataIndividual\SCP\20230704\test\set5]
D:\FragPipe-18.0\philosopher_v5.0.0_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --dir I:\Data\dataIndividual\SCP\20230704\test
INFO[10:08:24] Executing Label-free quantification  v5.0.0  
ERRO[10:08:24] Cannot read file. open .meta\psm.bin: The system cannot find the file specified. 
Process 'FreeQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 13 remaining tasks

**Comment by yuewang-wy** [comment]
I have no idea what's wrong with my procedure，please help me~

**Comment by fcyu** [comment]
Could you upgrade FragPipe to version 20.0, and try again?

Thanks,

Fengchao

**Comment by yuewang-wy** [comment]
> Thank you very much，I have solved！

**Comment by Ale-ksa-ndra** [comment]
hello 
it was working FP v22.0 now
i got this message
level=error msg="Cannot read file. open .meta\\psm.bin: The system cannot find the file specified
can you please help?

**Comment by danielgeiszler** [comment]
Please open a new issue and follow the instructions for uploading your log file.

**Comment by fcyu** [comment]
@Ale-ksa-ndra can you upload the log file?

Thanks,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
[log_2024-06-25_13-13-27.txt](https://github.com/user-attachments/files/15970041/log_2024-06-25_13-13-27.txt)

**Comment by Ale-ksa-ndra** [comment]
this is the one
thank you

**Comment by fcyu** [comment]
You skipped many steps between MSFragger and quant

    Cmd: [START], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [CheckCentroid], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [WorkspaceCleanInit], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [MSFragger], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [FreeQuant], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [PhilosopherReport], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [PTMShepherd], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [WorkspaceClean], Work dir: [C:\Users\achojna1\Documents\results]


Please read the tutorials, load the LFQ-MBR workflow, and try again.

Best,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
ok, thank you.
[log_2024-06-06_11-30-19.txt](https://github.com/user-attachments/files/15970208/log_2024-06-06_11-30-19.txt)
it was working before
thank you
i will

**Comment by fcyu** [comment]
This one has a different but good configuration 

Execution order:

    Cmd: [START], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [CheckCentroid], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [WorkspaceCleanInit], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [MSFragger], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [Percolator], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [ProteinProphet], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [PhilosopherDbAnnotate], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [PhilosopherFilter], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [PhilosopherReport], Work dir: [C:\Users\achojna1\Documents\results]
    Cmd: [WorkspaceClean], Work dir: [C:\Users\achojna1\Documents\results]

Best,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
thank you

**Comment by Ale-ksa-ndra** [comment]
hi i have other problem today which i do not understand pleasee see below 
![11](https://github.com/Nesvilab/FragPipe/assets/147073383/a4a7feee-c4ba-4ed9-9bea-5ad906d783e0)
![12](https://github.com/Nesvilab/FragPipe/assets/147073383/36e4ee24-d0dd-4569-b6dc-c0b3bbf78403)

**Comment by Ale-ksa-ndra** [comment]
ionquant is there, also the newest version

**Comment by fcyu** [comment]
@Ale-ksa-ndra I think you have created a new issue about it https://github.com/Nesvilab/FragPipe/issues/1650
