### ISSUE TITLE
Process 'Percolator' finished, exit code: -1073741819 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by Li-Yueyang** [Nesvilab/FragPipe#1211]
- Describe the issue or question: Hi, I was wondering what's wrong with the processing steps? Process 'Percolator' finished, exit code: -1073741819 Process returned non-zero exit code, stopping

Looking forward to your reply. Thank you!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-08-03_20-57-57.txt](https://github.com/Nesvilab/FragPipe/files/12256900/log_2023-08-03_20-57-57.txt)

**Comment by fcyu** [comment]
We have seen this Percolator error several times, but I have no clue about the cause. You'd better submit a report to https://github.com/percolator/percolator

Best,

Fengchao

**Comment by Li-Yueyang** [comment]
Thank you for your quick reply! I'll try to reach out to them.

**Comment by gcrynen** [comment]
Hi @fcyu , I ran it with the built you shared this morning a few times. I keep getting a MSBooster/ DIANN error. Please see the attached log file. here is last section from log file.
Abnormal DIANN termination: -1073741521, please run the following command from the command line for more information
D:\FragPipe-20.1-build5\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe --lib D:\Transfers\July-2023\MS223066_GT_CS\Fragger_Out_v20_1\spectraRT.tsv --predict --threads 47 --strip-unknown-mods --mod TMT,229.1629 --predict-n-frag 100
Process 'MSBooster' finished, exit code: -1
Process returned non-zero exit code, stopping
[log_2023-08-14_60fractions.txt](https://github.com/Nesvilab/FragPipe/files/12338582/log_2023-08-14_60fractions.txt)

**Comment by yangkl96** [comment]
Hello,

Could you please run the following from your command line?

`D:\FragPipe-20.1-build5\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe --lib D:\Transfers\July-2023\MS223066_GT_CS\Fragger_Out_v20_1\spectraRT.tsv --predict --threads 47 --strip-unknown-mods --mod TMT,229.1629 --predict-n-frag 100`

Doing this should give more details about what is wrong.

**Comment by gcrynen** [comment]
Hi,
Thank you for the command, I ran it and I am getting an error 
DiaNN. exe Bad Image
D:\FragPipe-20.1-build5\fragpipe\tools\diann\1.8.2_beta_8\win\torch_cpu.dll is either not designated to run on Windows or it contains an error. ... Error status 0xc000012f
![FragPipe-DIANN_erroraug152023](https://github.com/Nesvilab/FragPipe/assets/40701423/a6955677-40af-40c7-a1ac-fa558741baa2)

**Comment by fcyu** [comment]
Hi @gcrynen ,

Thank you very much for the feedback. I accidently didn't include some dll files when packaging the FragPipe. Could you please try the new version in https://www.dropbox.com/t/760VXqv2vAvnHKLT ?

Thanks,

Fengchao

**Comment by gcrynen** [comment]
Hi,
Now I get the Percolator error. 
Final list yields 0 target PSMs with q<0.01.
Calculating posterior error probabilities (PEPs).
Process 'Percolator' finished, exit code: -1073741819
Process returned non-zero exit code, stopping

thank you for all your help.
[log_2023-08-15_v20_1_build5_percolatorerror.txt](https://github.com/Nesvilab/FragPipe/files/12352843/log_2023-08-15_v20_1_build5_percolatorerror.txt)

**Comment by fcyu** [comment]
It was due to a known issue: Percolator crashes if there are 0 IDs. Could you remove MS223066_GT_CS_DBS_070623_nonStrap_Soluble_Fraction_59_Slot1-14_1_2763.d and try again?

Thanks,

Fengchao

**Comment by gcrynen** [comment]
Thank you Fengchao, the problem is resolved after I removed the fraction #59.
