### ISSUE TITLE
MSFragger-DIA for Bruker TimsTOF files

### ISSUE THREAD

**Issue by assafkacen1** [Nesvilab/FragPipe#1212]
- Describe the issue or question:
Hi, do you plan to support MSFragger-DIA for Bruker TimsTOF files? is it on your development roadmap? 
thanks
Assaf 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Yes, we are working on it.

Best,

Fengchao

**Comment by fcyu** [comment]
We have released a new tool diaTracer that can generate pseudo-MS/MS for diaPASEF data. Coupled with FragPipe, you can analyze the diaPASEF data without any ddaPASED data as library. Please download the new versions of FragPipe from https://github.com/Nesvilab/FragPipe/releases/latest, and then download the new version of MSFragger, IonQuant, and diaTracer using FragPipe.

Best,

Fengchao
