### ISSUE TITLE
DIA_SpecLib_Quant. ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library

### ISSUE THREAD

**Issue by ChloeZhaoT** [Nesvilab/FragPipe#1215]
DIA-NN failed to load library file after the spectral library is generated and located in the "Library" folder.

1 files will be processed
[0:00] Loading spectral library library.tsv
cannot read the file
ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag
[log_2023-08-11_14-16-27.txt](https://github.com/Nesvilab/FragPipe/files/12319185/log_2023-08-11_14-16-27.txt)
 & drop here.)

**Comment by fcyu** [comment]
Could you clear the experiment group assignment, and try again?

Best,

Fengchao

**Comment by ChloeZhaoT** [comment]
Hi Fengchao,

Thanks for your quick reply. Will try as advised and update you the result.

Regards,
Tianyun







On Friday, August 11, 2023 at 03:08:26 PM GMT+8, Fengchao ***@***.***> wrote: 







Could you clear the experiment group assignment, and try again?

Best,

Fengchao

**Comment by ChloeZhaoT** [comment]
Yes. It worked fine after I cleared the group assignment. Thanks!
