### ISSUE TITLE
Understanding Results of MSFragger-DIA Paper + an Astral Question

### ISSUE THREAD

**Issue by LeeSCantrell** [Nesvilab/FragPipe#1216]
Hello, 

I am interested in your recent Nature Communications paper (congratulations!) and noticed that there is a large time gap between MSFragger and DIANN in search time. Could you please elaborate on how this was achieved? Namely figure 5b where you show diann library prediction took ~1000 minutes (!) and in 5c it took less than 100 minutes? I just ran a 43k protein database on a 32 thread cpu on diann 1.8.1 with 2 missed cleavages, strict trypsin, variable M(ox) and Ac(N-term) but had a generation time of 50 minutes. Conceivably, were you matching msfragger settings looking for a much wider than default range and including up to 3 variable modifications? 

On an unrelated note, what agorithm changes or user method modifications can be made with Astral data to improve the efficiency of search? For DIA Umpire I have >30 minutes per file (I believe it was over an hour, but do not have log files handy) on that noted CPU to handle file first search post mzML conversion. On MSFragger it is a bit faster, but still quite time intensive. I also notice that, for now, the ID performance of MSFragger is substantially below that of DIANN library free (<60%). 

Thank you, 

Lee

**Comment by anesvi** [comment]
Lee,
Please read the paper. Fig. 5: The number of quantified phosphopeptide sequences and runtime for the melanoma-phospho dataset. So this is for phospho searches. 
With Astral data, we are working on optimizing the parameters. You can change to using 1000 peaks, and increase the number of top ranks to 10. When we have an optimized workflow, we will share it. As far as comparison with DIA-NN, it gives very high numbers indeed. I cannot comment on that. This is all uncharted waters really. All I can say we are using Percolator for FDR and methods well established for DDA data, with stringent filters. 
Alexey

**Comment by LeeSCantrell** [comment]
Hello Alexey, 
That makes more sense on the phospho modification. Thank you for the clarifications and suggestions!!
Regards, 
Lee
