### ISSUE TITLE
DIA_spec_lib_Quant issue

### ISSUE THREAD

**Issue by JesusCastano01** [Nesvilab/FragPipe#1217]
Hi,
I'm having some issues running "DIA_SpecLib_DIA" after updating EasyPQP to version 0.1.39. 
Below, you can see an excerpt of the reported error:
I tried to run the same files using another computer where the EasyPQP version was still 0.1.38 (not updated), and it ran without any issues. Therefore, I think there's some compatibility problem or something with the new EasyPQP version. I'm also attaching the log report.
I'd appreciate any advice or comments about this error.
Thanks,
 

 File "C:\Users\qe48769\AppData\Local\Programs\Python\Python311\Lib\site-packages\easypqp\convert.py", line 748, in conversion
    psms, theoretical = psms_fut.result()
                        ^^^^^^^^^^^^^^^^^
  File "C:\Users\qe48769\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qe48769\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
KeyError: 'run_id'
Traceback (most recent call last):
  File "D:\FragPipe-jre-20.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 980, in <module>
    main_easypqp()
  File "D:\FragPipe-jre-20.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 797, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
exit status: 1
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks
[log_2023-08-15_13-23-27.txt](https://github.com/Nesvilab/FragPipe/files/12346894/log_2023-08-15_13-23-27.txt)

**Comment by JesusCastano01** [comment]
Hi, sure, this is the log file from the successful run. I used exactly the same files and parameters. I'd appreciate any insights on this.
Thanks,
[log_2023-08-15_14-14-16.txt](https://github.com/Nesvilab/FragPipe/files/12371354/log_2023-08-15_14-14-16.txt)

**Comment by dpolasky** [comment]
It looks like the run that worked was on Python 3.9 using these raw files:
`  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus31.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus32.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus33.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus34.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus35.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus36.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus37.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus38.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus39.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus40.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus41.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus42.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus43.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus44.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus45.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus46.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus47.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus48.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus49.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus50.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus51.raw	DIA
  - E:\MS_DATA\31ADT-DIA\Plasma-Jesus52.raw	DIA`
  
Whereas the run that crashed was on Python 3.11, using only two raw files:
`  - D:\Postdoc_UMontreal\31ADT-DIA\Plasma-Jesus31.raw	DIA
  - D:\Postdoc_UMontreal\31ADT-DIA\Plasma-Jesus32.raw	DIA
`

Can you try with Python 3.9 (but with updated easyPQP 0.1.39) to see if the crash still occurs? 

Best,
Dan

**Comment by dpolasky** [comment]
It looks like there may be some issues with the new easyPQP (see #1220) - you can submit a ticket at https://github.com/grosenberger/easypqp/issues if it still fails with Python 3.9

**Comment by JesusCastano01** [comment]
Hi, 
Thanks for your response. I tried that, I installed Python 3.9 and changed the environment PATH accordingly. However, the problem still persists... Not sure what the best course of action would be.
Thanks,
[log_2023-08-17_17-53-26.txt](https://github.com/Nesvilab/FragPipe/files/12373847/log_2023-08-17_17-53-26.txt)

**Comment by dpolasky** [comment]
@guoci can you take a look? It looks like the issue might be in the changes to the multi pepxml reading.

**Comment by fcyu** [comment]
This one seems caused by an empty pepXML file, which is different from https://github.com/Nesvilab/FragPipe/issues/1220. I tried to fixed it. @JesusCastano01 could you run the following commands to get the fixed version and try again?
```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

If this version still returns errors, I need your raw, fasta, and workflow files to debug.

Also, your problematic run ([log_2023-08-17_17-53-26.txt](https://github.com/Nesvilab/FragPipe/files/12373847/log_2023-08-17_17-53-26.txt)) still has different sets of LC-MS files compared to the successfully run ([log_2023-08-15_14-14-16.txt](https://github.com/Nesvilab/FragPipe/files/12371354/log_2023-08-15_14-14-16.txt)).

Best,

Fengchao
