### ISSUE TITLE
FDR calculation

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#1219]
Hello, 

I am writing because we would like to test the results of running Fragpipe with different FDR thresholds and we were wondering if there is any way of inferring it by just filtering based on the scores of the run with the highest FDR that we want to test. I was searching for q-scores but I could not find them in the outputs. 

Thanks in advance for your advise!

Best regards,

Emma

**Comment by fcyu** [comment]
The psm, ion, peptide, and protein level tsv files have been filtered with the predefined FDR threshold. If you want to adjust it , please hover the mouse over "FDR filter and report" panel to see the tooltips.

Best,

Fengchao

**Comment by ericart89** [comment]
Hi Fenchao, thank you for your quick reply.

We know how to change the FDR threshhold for a search, our question is a different one.

We want to filter PSMs from the psm.tsv file by their q-value (global and runwise at best). This way we can do one search at e.g. FDR 10%, and then benchmark the number of IDs we get for all FDRs between 0% and 10%. We don't want to run the same set of files 10 times, always at a different FDR threshhold.

The only columns in the psm.tsv file that is similar to the q-value is the PeptideProphet probability - however, we would prefer to work with q-values directly. Is the psm-level q-value in one of the output tables? If not, how can we best apply the PeptideProphet probability to assess the number of PSMs we get at different confidence thresholds?

Thanks!

Best regards,

Emma

**Comment by fcyu** [comment]
I don't think there is a easy way to do what you want because Philosopher does not report FDR/q-value.

You could let FragPipe report decoys to psm.tsv and calculate FDR by yourself using the probability. But it is just PSM level FDR...

Best,

Fengchao
