### ISSUE TITLE
EasyPQP Assertion Error

### ISSUE THREAD

**Issue by ngirardi** [Nesvilab/FragPipe#1220]
I recently downloaded FragPipe 20.0 and have been having issues with the spectral library generation feature of easyPQP. The TimsTOF DDA files were successfully searched, but it looks like it hit an error as soon as it tried constructing the spectral library. Attached is the log from this run.
[log_2023-08-15_19-31-37.txt](https://github.com/grosenberger/easypqp/files/12361053/log_2023-08-15_19-31-37.txt)

**Comment by fcyu** [comment]
It seems that the recent changes in EasyPQP introduced a new bug. Could you submit a ticket to https://github.com/grosenberger/easypqp/issues

Thanks,

Fengchao
