### ISSUE TITLE
Having trouble with zero intensity using DIA_Speclib_Quant 

### ISSUE THREAD

**Issue by DvirMeiri** [Nesvilab/FragPipe#1221]
Hi Nesvilab,

thank you for creating great softwares! I'm trying to run a DIA_Speclib_Quant pipeline but receive 0 intensity values in protein and peptide .tsv. After converting the Thermo RAW file into mzML using Demultiplexing I started the DIA_Speclib_Quant pipeline and changed only the Protein Digestion. The software runs smoothly until it reports that ALL JOBS DONE. what can I do to fix the problem?

[log_2023-08-17_23-31-12.txt](https://github.com/Nesvilab/FragPipe/files/12375866/log_2023-08-17_23-31-12.txt)

Thanks in advance,
Dvir

**Comment by fcyu** [comment]
For DIA workflow, please use the output in the diann_output folder.

Best,

Fengchao
