### ISSUE TITLE
EasyPQP convert error

### ISSUE THREAD

**Issue by rockyzhu1008** [Nesvilab/FragPipe#1223]
![Screenshot 2023-08-23 154402](https://github.com/Nesvilab/FragPipe/assets/63193899/a84d125d-48de-4b6b-8b8e-dc2e9a85ecd9)
- Describe the issue or question:
Hello, I'm trying to build a spec library from DIA run(thermo Astral) but EasyPQP comes back with and error "EasyPQP convert error". The  log file is  uploaded here, Thanks for your assistance.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then 
[log_2023-08-22_01-15-21.txt](https://github.com/Nesvilab/FragPipe/files/12416475/log_2023-08-22_01-15-21.txt)
attach the zipped file by drag & drop here.)

**Comment by rockyzhu1008** [comment]
It seems that file'20230728_AST1_EVO5_ZY_DK_pTyr_K562_10_2_40SPD_OTAT_4Th6ms.mzML' caused the error.
[easypqp_convert_9.log](https://github.com/Nesvilab/FragPipe/files/12417502/easypqp_convert_9.log)

**Comment by fcyu** [comment]
Seems to be the same as https://github.com/Nesvilab/FragPipe/issues/1217#issuecomment-1684897694

Could you try the fixed EasyPQP mentioned in the above?

Thanks,

Fengchao

**Comment by rockyzhu1008** [comment]
It works, thanks
