### ISSUE TITLE
global normalization and interpreted output file  

### ISSUE THREAD

**Issue by Ink-Mo** [Nesvilab/FragPipe#1225]
- Describe the issue or question:
Dear Fragpipe Development Team,

I am currently replicating the data analysis from the article "Integrated Proteogenomic Characterization of Clear Cell Renal Cell Carcinoma." I have encountered an issue where the normalization method mentioned in the article, Aij =(RCij/ MADi) * MAD0 +M0+log2(REFi) （REFik, was estimated using the weighted sum of the MS1 intensities of the top three most intense peptide ions，REFi = Mean(REFik,k=1,.,q)）seems to differ from the global normalization method described in TMT-Integrator, which calculates yij'=(yij/m2)xm1+m0. I would like to confirm this.

Additionally, I have another question: If I have conducted a TMT-11plex experiment with all 11 labels applied to different samples, and I have imported the mzML data files into Fragpipe using the TMT10-bridge workflow, but at the end, I wish to exclude one channel for data analysis (removing one sample, leaving only 10 channels annotated), will this have any impact? What impact, if any, will it have on the final results for both a single TMT-11plex and two TMT-11plex experiments? My speculation is whether this would affect the global normalization process.

Lastly, I noticed that in the Quant module, "Use MS1 intensity“ and ”top3 ions" is selected by default. I would like to know if the TMT-report file does not report MS1 intensity value.

Thank you for your assistance.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by anesvi** [comment]
I am not sure I follow any of this. We used TMT-Integrator in the paper. It was an early version of TMT-Integrator, but nothing should be fundamentally different.  

For the second question, if you have TMT 11 (that is, 10 samples + bridge sample, so 11 total), you should load TMT10-bridge workflow but change from 10 to 11.  And specify the bridge sample ('reference' approach). The resulting table will have 10 samples (the bridge sample will not be there, since everything is calculated as ratio to bridge sample). You should not remove samples from the annotation.tsv file. If you do not want to use one of the samples, you should remove if from the final table. If you are concerned about global normalization, do not use it. We now use MD option (and almost never GN option). If you want to exclude the sample from GN, you can try annotating the sample you want to exclude as NA in the annotation.tsx. I think that way it will not be used.

"Lastly, I noticed that in the Quant module, "Use MS1 intensity“ and ”top3 ions" is selected by default. I would like to know if the TMT-report file does not report MS1 intensity value."
Sorry I do not understand your question.

Alexey

**Comment by Ink-Mo** [comment]
> I am not sure I follow any of this. We used TMT-Integrator in the paper. It was an early version of TMT-Integrator, but nothing should be fundamentally different.
> 
> For the second question, if you have TMT 11 (that is, 10 samples + bridge sample, so 11 total), you should load TMT10-bridge workflow but change from 10 to 11. And specify the bridge sample ('reference' approach). The resulting table will have 10 samples (the bridge sample will not be there, since everything is calculated as ratio to bridge sample). You should not remove samples from the annotation.tsv file. If you do not want to use one of the samples, you should remove if from the final table. If you are concerned about global normalization, do not use it. We now use MD option (and almost never GN option). If you want to exclude the sample from GN, you can try annotating the sample you want to exclude as NA in the annotation.tsx. I think that way it will not be used.
> 
> "Lastly, I noticed that in the Quant module, "Use MS1 intensity“ and ”top3 ions" is selected by default. I would like to know if the TMT-report file does not report MS1 intensity value." Sorry I do not understand your question.
> 
> Alexey



> I am not sure I follow any of this. We used TMT-Integrator in the paper. It was an early version of TMT-Integrator, but nothing should be fundamentally different.
> 
> For the second question, if you have TMT 11 (that is, 10 samples + bridge sample, so 11 total), you should load TMT10-bridge workflow but change from 10 to 11. And specify the bridge sample ('reference' approach). The resulting table will have 10 samples (the bridge sample will not be there, since everything is calculated as ratio to bridge sample). You should not remove samples from the annotation.tsv file. If you do not want to use one of the samples, you should remove if from the final table. If you are concerned about global normalization, do not use it. We now use MD option (and almost never GN option). If you want to exclude the sample from GN, you can try annotating the sample you want to exclude as NA in the annotation.tsx. I think that way it will not be used.
> 
> "Lastly, I noticed that in the Quant module, "Use MS1 intensity“ and ”top3 ions" is selected by default. I would like to know if the TMT-report file does not report MS1 intensity value." Sorry I do not understand your question.
> 
> Alexey

I apologize for the confusion. In Fragpipe's Quant(Isobaric) module, the ratio to abundance conversion is default to have "Use MS1 intensity" and "Top 3 ions" checked. I would like to know where in the TMT report file or which file I can find the MS1 intensity values.

Thinks

**Comment by anesvi** [comment]
PSM.tsv have intensity column. Those intensities are used to estimate the protein abundance in the reference sample, and convert from ratio to abundance values ( shown in abundance_… files)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
