### ISSUE TITLE
PDV viewer spectra annotation with TMT16-MS3 workflow

### ISSUE THREAD

**Issue by himbeerquark** [Nesvilab/FragPipe#1226]
Hi,

we have measured the same TMT-labeled samples in two different aquisition modes: once with MS2 aquisition and once with RTS-MS3 aquisition (MS2 in iontrap with CID). When inspecting the spectra used for identification in the RTS-MS3 dataset using the PDV viewer, we noticed that only few fragment ions were annotated although other matching fragment ions were present in the spectrum and were also targeted for MS3. We attached spectra matched to the same peptide in both datasets as an example. 
[Example_spectra_MS2_vs_MS3.pdf](https://github.com/Nesvilab/FragPipe/files/12439998/Example_spectra_MS2_vs_MS3.pdf)

We were wondering if this has to do with the lower mass accuracy of the ion trap and if these fragment ions could also be annotated/ visualized by PDV viewer?

In addition, we would like to know if there is an easy way to extract a list of all matching fragments between the experimental spectrum and its theoretical spectrum from any of the FragPipe output or intermediate files?

Thank you for your help!

**Comment by himbeerquark** [comment]
Additional question: Is MSBooster compatible with the TMT16-MS3 workflow (CID iontrap MS2)?

**Comment by anesvi** [comment]
About the second question, we currently have a way to extract matched fragments. We can possibly add in the future. But note that MSFragger uses only top N peaks (~ 100-200), and performs deisoping and conversion to 1+ charge when successfully deisotopes. So you cannot easily print this info from MSFragger. When we build the library with EasyPQP, it does the annotation and matching. So library.tsv has this info, but only for one PSM per ion (as it selects the best PSM to put in the library.

**Comment by fcyu** [comment]
The second question is the same as https://github.com/Nesvilab/FragPipe/issues/885. Close this one to remove duplicated issues.

Best,

Fengchao
