### ISSUE TITLE
Process 'Percolator' finished, exit code: -1073741819

### ISSUE THREAD

**Issue by VetSciMS** [Nesvilab/FragPipe#1227]
Hi there,

I'm running into the following error on FragPipe:

**Process 'Percolator' finished, exit code: -1073741819
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 320 remaining tasks**

I've attached the log file here. Any ideas what could be causing the error? I've run the same files on PD no problem.

Thanks!

[log_2023-08-26_23-34-24.zip](https://github.com/Nesvilab/FragPipe/files/12447182/log_2023-08-26_23-34-24.zip)

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/1211. Here the solution: https://github.com/Nesvilab/FragPipe/issues/1211#issuecomment-1678945208

Best,

Fengchao

**Comment by VetSciMS** [comment]
I'll check it out. Thanks a buch!
