### ISSUE TITLE
Error MSFragger - number of results in slice 1 is different from the total number of the spectra

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#1228]
Hello,
I am writing because I got this error while analysing immunopeptidomics data with Fragpipe. It comes from MSFragger but it surprises me because I had previously analysed this data with v18 and it work. Now with Fragpipe version 20 it doesn't. Any idea of what could be the problem? 

Thanks in advance!

Here the last lines of the log file:

3695221532 fragments to be searched in 3 slices (55.06 GB total)
Operating on slice 1 of 3:
	Fragment index slice generated in 7.69 s
	001. 20230113_CTE-BIO-057235b-HLAIp_R01.mzML has fragtmp, skip
	002. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q1.mzML 2.3 s | deisotoping 1.1 s
		[progress: 56285/56285 (100%) - 8241 spectra/s] 6.8s
	003. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q2.mzML 3.8 s | deisotoping 0.4 s
		[progress: 188785/188785 (100%) - 21863 spectra/s] 8.6s
	004. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q3.mzML 3.1 s | deisotoping 0.4 s
		[progress: 134152/134152 (100%) - 20598 spectra/s] 6.5s
Operating on slice 2 of 3:
	Fragment index slice generated in 6.91 s
	001. 20230113_CTE-BIO-057235b-HLAIp_R01.mzML has fragtmp, skip
	002. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q1.mzML 1.3 s | deisotoping 0.2 s
		[progress: 56285/56285 (100%) - 22099 spectra/s] 2.5s
	003. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q2.mzML 4.3 s | deisotoping 0.6 s
		[progress: 188785/188785 (100%) - 30697 spectra/s] 6.2s
	004. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q3.mzML 3.0 s | deisotoping 0.4 s
		[progress: 134152/134152 (100%) - 25734 spectra/s] 5.2s
Operating on slice 3 of 3:
	Fragment index slice generated in 6.45 s
	001. 20230113_CTE-BIO-057235b-HLAIp_R01.mzML has fragtmp, skip
	002. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q1.mzML 1.3 s | deisotoping 0.1 s
		[progress: 56285/56285 (100%) - 30310 spectra/s] 1.9s | postprocessing 0.3 s
	003. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q2.mzML 4.1 s | deisotoping 0.4 s
		[progress: 188785/188785 (100%) - 30449 spectra/s] 6.2s | postprocessing 0.4 s
	004. 20230202_DIA_CTE-BIO-065225-HLAIp_R03_Q3.mzML 3.2 s | deisotoping 0.4 s
		[progress: 134152/134152 (100%) - 33305 spectra/s] 4.0s | postprocessing 0.3 s
The number of results in slice 1 is different from the total number of the spectra.
Process 'MSFragger' finished, exit code: 1

**Comment by dpolasky** [comment]
Hi,
Can you upload the whole log file?

**Comment by anesvi** [comment]
One guess there are frgtmp files left from a previous crashed MSFragger search. deleting those files (located where the database file is located) and rerunning may solve it, but I am not sure.

**Comment by ericart89** [comment]
Hi all,
Thanks for your replies! Indeed, it may be related previous crashed runs because today it's working... Sorry for bothering you! I tried it twice before submitting the issue and it crashed both times...

**Comment by ericart89** [comment]
Hi all!
Yes it's possible that it was what suggests Alexey because today is running well...sorry for bothering you but I tried twice yesterday and it crashed both times.
Best regards,

Emma
