### ISSUE TITLE
Process 'MSFragger' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by Hanna-Wong** [Nesvilab/FragPipe#1230]
- Describe the issue or question: When I searched for DIA data, the software reported an error.
Can someone help me.

[log_2023-08-30_19-30-45.txt](https://github.com/Nesvilab/FragPipe/files/12475217/log_2023-08-30_19-30-45.txt)

**Comment by fcyu** [comment]
The error message shows that one of your MS2 scan's isolation window does not fit into any of your data's isolation windows. Please double check your data acquisition method.

Best,

Fengchao
