### ISSUE TITLE
PTMShepherd exit code 1 

### ISSUE THREAD

**Issue by shumpeim** [Nesvilab/FragPipe#1232]
Running an LFQ-MBR workflow with mostly default settings. I have not selected to turn on PTM-Shepherd, but I still receive this error code.

> PTM-Shepherd version 2.0.5
> 
> (c) 2022 University of Michigan
> 
> Using Java 20.0.2 on 8192MB memory
> 
> Finding spectral data
> 	Indexing data from Control_1
> Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "ls" is null
> 	at edu.umich.andykong.ptmshepherd.PSMFile.getMappings(PSMFile.java:178)
> 	at edu.umich.andykong.ptmshepherd.PSMFile.getMappings(PSMFile.java:179)
> 	at edu.umich.andykong.ptmshepherd.PTMShepherd.getMzDataMapping(PTMShepherd.java:960)
> 	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:347)
> Process 'PTMShepherd' finished, exit code: 1
> Process returned non-zero exit code, stopping
> 
> Cancelling 10 remaining tasks  

Thanks for any help!

[log_2023-08-30_12-04-33.zip](https://github.com/Nesvilab/FragPipe/files/12478215/log_2023-08-30_12-04-33.zip)

**Comment by dpolasky** [comment]
Hi,
It looks like the "Assign Glycans with FDR" box is enabled on the Glyco tab (maybe accidentally). This will run PTM-Shepherd even though the main checkbox for it is disabled, because the glycan assignment is done by PTM-Shepherd. Turning off that check should fix it. 

Best,
Dan

**Comment by shumpeim** [comment]
Thank you! That fixed it
