### ISSUE TITLE
ionquant error using tutorial data

### ISSUE THREAD

**Issue by babsillo** [Nesvilab/FragPipe#1236]
Hi all,

I recently started using Fragpipe. Identifiaction worked. (I am using bruker Qtof files --> so I converted to mzXML)
But Quantification leads to errors and I didnt get any results.

So I decided to use the tutorial data to check where my problem could be. but still the pipeline cannot finish. At some point a specified file cannot be found.
 
![image](https://github.com/Nesvilab/FragPipe/assets/143997279/927c9278-b5a6-44e2-808e-65c36f26d52b)
Experimental design as recommended on homepage.

Files locally saved on the PC. 
If I make just one experiment --> I will get a results table --> but thats not what I want to see. As soon as I have more than one experiment --> I run into troubles.

![image](https://github.com/Nesvilab/FragPipe/assets/143997279/c7d14ff4-494b-4492-83ab-3b2c136141f1)

- Upload your log file: 
- Here I tried LFQ-MBR without validation: (cancelled because of not finding a file)
[log_2023-09-04_00-24-50.zip](https://github.com/Nesvilab/FragPipe/files/12511211/log_2023-09-04_00-24-50.zip)

Here I tried LFQ-MBR with valitation (cancelled becaue of not finding another file).
[log_2023-09-04_00-43-23.txt](https://github.com/Nesvilab/FragPipe/files/12511362/log_2023-09-04_00-43-23.txt)

I somehow have the feeling I am just a small step away - from putting in the data/settings correctly (hopefully). I really hope you can help me --> setting up the tutorial file correctly. 
Best
Babsillo

**Comment by fcyu** [comment]
> Here I tried LFQ-MBR without validation: (cancelled because of not finding a file)
> [log_2023-09-04_00-24-50.zip](https://github.com/Nesvilab/FragPipe/files/12511211/log_2023-09-04_00-24-50.zip)

It will definitely result in an error because there are no outputs from the validation.

> Here I tried LFQ-MBR with valitation (cancelled becaue of not finding another file).
> [log_2023-09-04_00-43-23.txt](https://github.com/Nesvilab/FragPipe/files/12511362/log_2023-09-04_00-43-23.txt)

The error in the above log file was due to version incompatible. Upgrade FragPipe to version 20 should solve this problem.

Best,

Fengchao

**Comment by babsillo** [comment]
Good morning,

Thank you for your very fast reply. I downloaded and updated to fragpipe v20. And now tutorial data works.
Additionally I immediatelly needed to try my qtof converted mzXML files --> also working now.
Thank you so much for your help. and I am so much sorry to bother you with such a stupid problem. 

Best babsillo
