### ISSUE TITLE
"Pyro-Glu and loss of ammonia at peptide N-term" MSFragger settings

### ISSUE THREAD

**Issue by leandroxneves** [Nesvilab/FragPipe#1237]
It seems the default syntax (nQnC) that enables "Pyro-Glu and loss of ammonia at peptide N-term" as variable modification doesn't match the description that shows up in the yellow pop up box. 

![image](https://github.com/Nesvilab/FragPipe/assets/44547240/b705e9bc-80be-484b-ae25-5f0460c5f8bd)

nQnC enables -17.0265 mass shifts in N-term Q and C residues, so maybe the description should be updated to "Pyro-Glu and loss of ammonia at N-term cysteine". Also, say I want to expand this mod to all residues prone to loss of ammonia (T, S and C - according to Unimod) when located at peptide N-terminus. Would the correct syntax be nQTSC or nQnTnSnC? 

Many thanks,
Leandro

**Comment by fcyu** [comment]
If you want to add other amino acids, such as T and S, use `nQnTnSnC`.

Best,

Fengchao

**Comment by leandroxneves** [comment]
Thanks for the quick reply!
Best,
Leandro
