### ISSUE TITLE
Can IBT tag quantification be added to fragpipe?

### ISSUE THREAD

**Issue by Liu-jie8** [Nesvilab/FragPipe#1238]
- Describe the issue or question:
IBT-16plex tags reagent is the same with TMT tags have quantitative principle of isobaric reagents for the relative quantitative analysis of proteomes. IBT tag reagent since 2018 has been widely used, so can add the IBT to fragpipe, expecting your reply, thank you!
References are as follows:
1. Ning X, Li Q, Zi J, Mei Z, Liu J, Zhang Y, Bi M, Ren Y, Liu X, Lv C, Yao H, Sun J, Rao F, Li S, Liu S. New Set of Isobaric Labeling Reagents for Quantitative 16Plex Proteomics. Anal Chem. 2023 Apr 4;95(13):5788-5795. doi: 10.1021/acs.analchem.3c00235. Epub 2023 Mar 23. PMID: 36958307.
2. Ren Y, He Y, Lin Z, Zi J, Yang H, Zhang S, Lou X, Wang Q, Li S, Liu S. Reagents for Isobaric Labeling Peptides in Quantitative Proteomics. Anal Chem. 2018 Nov 6;90(21):12366-12371. doi: 10.1021/acs.analchem.8b00321. Epub 2018 Oct 16. PMID: 30260629.

- Upload your log file
IBT-16plex tags information can be found in the attachment:
[IBT-16plex.pdf](https://github.com/Nesvilab/FragPipe/files/12530414/IBT-16plex.pdf)

**Comment by dpolasky** [comment]
Yes, we can add IBT-16 to FragPipe - will post when a version is ready to test.

Best,
Dan

**Comment by Liu-jie8** [comment]
Thank you, I  look forward to release next version containing the IBT-16plex.

best,
Jie Liu

**Comment by Liu-jie8** [comment]
Want to know when the next version is expected to be released?

best,
Jie Liu

**Comment by anesvi** [comment]
Dear Jie, could you please contact me directly at nesvi at med.umich.edu to clarify who developed and distributes  these reagents, and the licensing issues associated with you using FragPipe with these data.
