### ISSUE TITLE
Error Caused by: java.lang.Exception: The number of results in slice 1 is different from the total number of the spectra.

### ISSUE THREAD

**Issue by yb47620** [Nesvilab/FragPipe#124]
# Describe the problem

* **I'm submitting a:**
  - [x] problem running the software

* **My MSFragger use case:**
  - [x] _Closed_ search (standard small precursor mass tolerance)

 ** _put your general problem description here_ **
The log:
.........
All searches done with slice 7 of 8: skipping
Operating on slice 8 of 8: 
	002. JD_06232014_sample2_A.mzML 31.2 s
	002. JD_06232014_sample2_A.mzML 31.2 s [progress: 31063/37825 (82.12%) - 6155.97 spectra/s]Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.Exception: The number of results in slice 1 is different from the total number of the spectra.
	at edu.umich.andykong.msfragger.r.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more

	002. JD_06232014_sample2_A.mzML 31.2 s [progress: 37825/37825 (100.00%) - 6492.45 spectra/s] - completed 5.8 s
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample1-A.pepXML E:\mzFRAG\A\JD_06232014_sample1-A.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 44/55 processes (11 already finished)
Processing interrupted, stopping MsFragger


## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

## Describe your experiment

### Genral proteomics experiment description
e.g. " yeast, fraction lysate with Trypsin_" , 

...

### Input data files
** e.g. "_fractionated yeast, 12 samples,  **


### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **


## Run log output

```
** copy text from the text console in the gui here **
System info:
System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_181, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190628
Philosopher version v1.4.6 (build 1563480020)


LCMS files:
  Experiment/Group: A
  - E:\TPP\data\JD_06232014_sample1-A.mzML
  - E:\TPP\data\JD_06232014_sample2_A.mzML
  - E:\TPP\data\JD_06232014_sample3_A.mzML
  - E:\TPP\data\JD_06232014_sample4-A.mzML
  Experiment/Group: B
  - E:\TPP\data\JD_06232014_sample1_B.mzML
  - E:\TPP\data\JD_06232014_sample2_B.mzML
  - E:\TPP\data\JD_06232014_sample3_B.mzML
  - E:\TPP\data\JD_06232014_sample4_B.mzML
  Experiment/Group: C
  - E:\TPP\data\JD_06232014_sample1_C.mzML
  - E:\TPP\data\JD_06232014_sample3_C.mzML
  - E:\TPP\data\JD_06232014_sample4_C.mzML
  Experiment/Group: D
  - E:\TPP\data\160817_IP1031.mzML

54 commands to execute:
Workspace [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
Workspace [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
MsFragger [Work dir: E:\mzFRAG]
java -jar -Dfile.encoding=UTF-8 D:\zpw\MSFragger-20190628\MSFragger-20190628\MSFragger-20190628.jar E:\mzFRAG\fragger.params E:\TPP\data\JD_06232014_sample1-A.mzML E:\TPP\data\JD_06232014_sample2_A.mzML E:\TPP\data\JD_06232014_sample3_A.mzML E:\TPP\data\JD_06232014_sample4-A.mzML E:\TPP\data\JD_06232014_sample1_B.mzML E:\TPP\data\JD_06232014_sample2_B.mzML E:\TPP\data\JD_06232014_sample3_B.mzML E:\TPP\data\JD_06232014_sample4_B.mzML E:\TPP\data\JD_06232014_sample1_C.mzML E:\TPP\data\JD_06232014_sample3_C.mzML E:\TPP\data\JD_06232014_sample4_C.mzML E:\TPP\data\160817_IP1031.mzML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample1-A.pepXML E:\mzFRAG\A\JD_06232014_sample1-A.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample2_A.pepXML E:\mzFRAG\A\JD_06232014_sample2_A.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample3_A.pepXML E:\mzFRAG\A\JD_06232014_sample3_A.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample4-A.pepXML E:\mzFRAG\A\JD_06232014_sample4-A.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample1_B.pepXML E:\mzFRAG\B\JD_06232014_sample1_B.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample2_B.pepXML E:\mzFRAG\B\JD_06232014_sample2_B.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample3_B.pepXML E:\mzFRAG\B\JD_06232014_sample3_B.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample4_B.pepXML E:\mzFRAG\B\JD_06232014_sample4_B.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample1_C.pepXML E:\mzFRAG\C\JD_06232014_sample1_C.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample3_C.pepXML E:\mzFRAG\C\JD_06232014_sample3_C.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample4_C.pepXML E:\mzFRAG\C\JD_06232014_sample4_C.pepXML
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\160817_IP1031.pepXML E:\mzFRAG\D\160817_IP1031.pepXML
ReportDbAnnotate [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe database --annotate D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta --prefix rev_
ReportDbAnnotate [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe database --annotate D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta --prefix rev_
ReportDbAnnotate [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe database --annotate D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta --prefix rev_
ReportDbAnnotate [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe database --annotate D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta --prefix rev_
ReportDbAnnotate [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe database --annotate D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta --prefix rev_
PeptideProphet [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample3_A.pepXML
PeptideProphet [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta 160817_IP1031.pepXML
PeptideProphet [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample2_B.pepXML
PeptideProphet [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample2_A.pepXML
PeptideProphet [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample1_B.pepXML
PeptideProphet [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample1-A.pepXML
PeptideProphet [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample4-A.pepXML
PeptideProphet [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample4_B.pepXML
PeptideProphet [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample3_B.pepXML
PeptideProphet [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample3_C.pepXML
PeptideProphet [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample4_C.pepXML
PeptideProphet [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta JD_06232014_sample1_C.pepXML
ProteinProphet [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 E:\mzFRAG\A\interact-JD_06232014_sample3_A.pep.xml E:\mzFRAG\D\interact-160817_IP1031.pep.xml E:\mzFRAG\B\interact-JD_06232014_sample2_B.pep.xml E:\mzFRAG\A\interact-JD_06232014_sample2_A.pep.xml E:\mzFRAG\B\interact-JD_06232014_sample1_B.pep.xml E:\mzFRAG\A\interact-JD_06232014_sample1-A.pep.xml E:\mzFRAG\A\interact-JD_06232014_sample4-A.pep.xml E:\mzFRAG\B\interact-JD_06232014_sample4_B.pep.xml E:\mzFRAG\B\interact-JD_06232014_sample3_B.pep.xml E:\mzFRAG\C\interact-JD_06232014_sample3_C.pep.xml E:\mzFRAG\C\interact-JD_06232014_sample4_C.pep.xml E:\mzFRAG\C\interact-JD_06232014_sample1_C.pep.xml
ReportFilter [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml E:\mzFRAG\D --protxml E:\mzFRAG\interact.prot.xml
ReportFilter [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml E:\mzFRAG\C --protxml E:\mzFRAG\interact.prot.xml
ReportFilter [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml E:\mzFRAG\A --protxml E:\mzFRAG\interact.prot.xml
ReportFilter [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml E:\mzFRAG\B --protxml E:\mzFRAG\interact.prot.xml
ReportReport [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe report
ReportReport [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe report
ReportReport [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe report
ReportReport [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe report
Workspace [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
Workspace [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~

Workspace [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
INFO[18:05:55] Executing Workspace v1.4.6                   
INFO[18:05:59] Removing workspace                           
INFO[18:05:59] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
INFO[18:05:59] Executing Workspace v1.4.6                   
INFO[18:06:03] Creating workspace                           
INFO[18:06:03] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
INFO[18:06:03] Executing Workspace v1.4.6                   
INFO[18:06:06] Removing workspace                           
INFO[18:06:06] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\A]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
INFO[18:06:06] Executing Workspace v1.4.6                   
INFO[18:06:07] Creating workspace                           
INFO[18:06:08] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
INFO[18:06:08] Executing Workspace v1.4.6                   
INFO[18:06:10] Removing workspace                           
INFO[18:06:10] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\B]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
INFO[18:06:10] Executing Workspace v1.4.6                   
INFO[18:06:12] Creating workspace                           
INFO[18:06:12] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
INFO[18:06:12] Executing Workspace v1.4.6                   
INFO[18:06:17] Removing workspace                           
INFO[18:06:17] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\C]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
INFO[18:06:18] Executing Workspace v1.4.6                   
INFO[18:06:19] Creating workspace                           
INFO[18:06:19] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --clean
INFO[18:06:19] Executing Workspace v1.4.6                   
INFO[18:06:21] Removing workspace                           
INFO[18:06:21] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: E:\mzFRAG\D]
D:\zpw\philosopher_v1.4.6_windows_amd64\philosopher.exe workspace --init
INFO[18:06:21] Executing Workspace v1.4.6                   
INFO[18:06:23] Creating workspace                           
INFO[18:06:23] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: E:\mzFRAG]
java -jar -Dfile.encoding=UTF-8 D:\zpw\MSFragger-20190628\MSFragger-20190628\MSFragger-20190628.jar E:\mzFRAG\fragger.params E:\TPP\data\JD_06232014_sample1-A.mzML E:\TPP\data\JD_06232014_sample2_A.mzML E:\TPP\data\JD_06232014_sample3_A.mzML E:\TPP\data\JD_06232014_sample4-A.mzML E:\TPP\data\JD_06232014_sample1_B.mzML E:\TPP\data\JD_06232014_sample2_B.mzML E:\TPP\data\JD_06232014_sample3_B.mzML E:\TPP\data\JD_06232014_sample4_B.mzML E:\TPP\data\JD_06232014_sample1_C.mzML E:\TPP\data\JD_06232014_sample3_C.mzML E:\TPP\data\JD_06232014_sample4_C.mzML E:\TPP\data\160817_IP1031.mzML
MSFragger version MSFragger-20190628
MSFTBX version 1.9.10
(c) University of Michigan
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved.

System OS: Windows 7, Architecture: AMD64
Java Info: 1.8.0_181, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 3623 MB memory

***********************************FIRST SEARCH************************************
Parameters:
num_threads = 8
database_name = D:\zpw\orf_trans_all.fasta\orf_trans_all.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 3
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 10
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 2
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
variable_mod_03 = 79.96633 STY
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 1.89 GB.
945195382 fragments to be searched in 8 slices (14.08 GB total)
All searches done with slice 1 of 8: skipping
All searches done with slice 2 of 8: skipping
All searches done with slice 3 of 8: skipping
All searches done with slice 4 of 8: skipping
All searches done with slice 5 of 8: skipping
All searches done with slice 6 of 8: skipping
All searches done with slice 7 of 8: skipping
Operating on slice 8 of 8: 
	002. JD_06232014_sample2_A.mzML 31.2 s
	002. JD_06232014_sample2_A.mzML 31.2 s [progress: 31063/37825 (82.12%) - 6155.97 spectra/s]Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.Exception: The number of results in slice 1 is different from the total number of the spectra.
	at edu.umich.andykong.msfragger.r.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more

	002. JD_06232014_sample2_A.mzML 31.2 s [progress: 37825/37825 (100.00%) - 6492.45 spectra/s] - completed 5.8 s
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\TPP\data\JD_06232014_sample1-A.pepXML E:\mzFRAG\A\JD_06232014_sample1-A.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 44/55 processes (11 already finished)
Processing interrupted, stopping MsFragger


[parameters.txt](https://github.com/Nesvilab/FragPipe/files/3513945/parameters.txt)

**Comment by fcyu** [comment]
Could you please delete all temporary files ending with `.fragtmp` and run your task again? If the same error happens, could you please send me your `JD_06232014_sample2_A.mzML` and `orf_trans_all.fasta`? 

Thanks,

Fengchao

**Comment by yb47620** [comment]
Hi Fengchao

   Thank you for your reply very much. I will follow your suggestions and try again.

Pengwei

________________________________

**Comment by yb47620** [comment]
Dear Fengchao:

   I ran the task again, but the same errors still happened. Could you help me check the fasta file and mzML file? you can find them from the below link:

    JD_06232014_sample2_A.mzML<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/Edb5I81-utdOi9VvJT4lH3EBpUb-maJG-vR9aDaPTe3eWg?e=bf7Wz7>

[https://r1.res.office365.com/owa/prem/images/dc-generic_40.png]<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/Edb5I81-utdOi9VvJT4lH3EBpUb-maJG-vR9aDaPTe3eWg?e=bf7Wz7>
JD_06232014_sample2_A<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/Edb5I81-utdOi9VvJT4lH3EBpUb-maJG-vR9aDaPTe3eWg?e=bf7Wz7>
Shared via OneDrive
  orf_trans_all.fasta<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ERvi7Km5a_lNgPSTWIPtL9IB_UlVsfDmZpH4-ba-T69qFg?e=V9ohZE>
[https://r1.res.office365.com/owa/prem/images/dc-generic_40.png]<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ERvi7Km5a_lNgPSTWIPtL9IB_UlVsfDmZpH4-ba-T69qFg?e=V9ohZE>
orf_trans_all<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ERvi7Km5a_lNgPSTWIPtL9IB_UlVsfDmZpH4-ba-T69qFg?e=V9ohZE>
Shared via OneDrive

Thank you very much


________________________________

**Comment by fcyu** [comment]
Hi Pengwei:

I found two issues. One relates to your error and the other one does not.

1. You didn't assign an appropriate memory size, which results in some scans being not loaded. I suggest you filling in the memory size your computer has in the `MSFragger` tab:
![image](https://user-images.githubusercontent.com/6926299/63248401-cad12600-c299-11e9-8343-362376957828.png)

2. Your fasta file doesn't have decoy proteins. This one does not relate to your error but will cause errors later.

Best,

Fengchao

**Comment by yb47620** [comment]
Dear Fenghao:

    Thank you very much for pointing the issues. I will revise them and try again.

     Best,

      Pengwei

________________________________

**Comment by yb47620** [comment]
Dear Fengchao:

    Sorry to disturb again. After I add the decoy proteins to the original FASTA file. The msFragger reported another error (as shown in the below figure). Could you please kindly help me check the problem in my sequence DB （origin and decoy.fasta<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ESjRvr6d3ldLlqUpO5Qu2a0B8BZcsLMN2CQPwlJCaIbz5Q?e=QP3lwA>）? Thank you very much.

[https://r1.res.office365.com/owa/prem/images/dc-generic_40.png]<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ESjRvr6d3ldLlqUpO5Qu2a0B8BZcsLMN2CQPwlJCaIbz5Q?e=QP3lwA>
origin and decoy<https://uofmacau-my.sharepoint.com/:u:/g/personal/yb47620_umac_mo/ESjRvr6d3ldLlqUpO5Qu2a0B8BZcsLMN2CQPwlJCaIbz5Q?e=QP3lwA>
Shared via OneDrive


    Pengwei

[cid:1d2f0f47-eca8-4c76-8c2e-fab9df7d4461]

________________________________

**Comment by fcyu** [comment]
Sorry I cannot find the figure you mentioned.

**Comment by yb47620** [comment]
Hi Fengchao

  Please find the pic in the attached file. it said '

decoy_prefix has an empty value.
Process 'MsFragger' finished, exit code: 1' probably it is because my decoy DB, but I cannot figure it out.
pw

________________________________

**Comment by fcyu** [comment]
I still cannot see the figure. But according to your description and fasta file, I guess you filled `###REV###` in the `decoy_prefix` parameter. Unfortunately, MSFragger treats everything after `#` as comment. Could you please replace all `###REV###` with another string, say `rev_`?

Best,

Fengchao

**Comment by anesvi** [comment]
We explain in FragPipe Database tab how to create and label reversed sequences.

Please read those instructions.

If you are not using FragPipe, the same instructions apply

Thanks
Alexey


________________________________

**Comment by yb47620** [comment]
Thank you very much. I will try to create the new DB.
   Best,
    Pengwei
________________________________

**Comment by yb47620** [comment]
Thanks a lot. Finally, I finished a close search!

pengwei

________________________________
