### ISSUE TITLE
Fragpipe freezes while uploading raw files from network drive

### ISSUE THREAD

**Issue by temaia** [Nesvilab/FragPipe#1240]
- In the workflow tab, when trying to add input LCMS files, if these come from a mounted network drive, the program freezes and has to be aborted with Task Manager.
The issue arises with Fragpipe-jre v20.

- Is this a know issue?

**Comment by fcyu** [comment]
Using raw files on a network drive could have several issues related to IO causing the problem not working smoothly. Please move your files to local drive and/or convert them to mzML format: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by temaia** [comment]
Allright. Thank you Fengchao
