### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1

### ISSUE THREAD

**Issue by CassyGu** [Nesvilab/FragPipe#1241]
- Describe the issue or question:

Finished
Done generating DIA-NN predictions
Model running took 40506 milliseconds
Generating edited pin with following features: [unweightedSpectralEntropy, deltaRTLOESS]
Loading predicted spectra
Processing 2_MWXS-23-1834-b_DDA_baihe_753c_Slot2-19_1_4932_uncalibrated.mzML
RT regression using 494 PSMs
com.univocity.parsers.common.TextWritingException: Cannot write 'YP_009186039.1' to index '50000'. Maximum number of columns (50000) exceeded.
Internal state when error was thrown: recordCount=5257, recordData=[YP_009186039.1]
        at com.univocity.parsers.common.AbstractWriter.throwExceptionAndClose(AbstractWriter.java:1046)
        at com.univocity.parsers.common.AbstractWriter.addValue(AbstractWriter.java:1185)
        at Features.percolatorFormatter.editPin(percolatorFormatter.java:480)
        at Features.MainClass.main(MainClass.java:588)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 23 remaining tasks

for a big database (7.8GB) and LFQ-workflow,  How to solve this error when it occurs.

**Comment by yangkl96** [comment]
Hello,

This error occurs when there is a PSM entry in the pin file that has greater than 50000 proteins associated with the peptide. We should be able to get you a fixed prerelease quickly. In your data, do you have an estimate as to the greatest number of proteins listed in a row of your pin file?

Thanks,
Kevin

**Comment by fcyu** [comment]
@yangkl96 has already increased to 75000. I guess it should be enough. 

@CassyGu Let us know if it does not work for you.

Best,

Fengchao

**Comment by CassyGu** [comment]
I changed other parameters of MSFragger, such as calibrate_mass = 0, and then run succeeded; 
I didn't download the pre-release version, but I think it should work.

Thank you very much, Fengchao
