### ISSUE TITLE
MS1 peak areas

### ISSUE THREAD

**Issue by FTCPH** [Nesvilab/FragPipe#1242]
- Describe the issue or question:
Hi, is there a way I can find or calculate the MS1 peak areas for each peptide in the output from a DDA analysis?
If I understood it correctly, the intensity and MaxLFQ intensity columns in the combined_modified_peptide.tsv file both do not describe integrated peak abundances. Thanks you.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
The intensities in the psm.tsv, ion.tsv, and combined_ion.tsv files are the MS1 area of the detected peptides. As to the modified peptide, peptide, and protein level intensities, they are from either top-N algorithm (intensity columns) or MaxLFQ algorithm (MaxLFQ intensity columns).

Here is the brief documentation in case you want to take a look: https://github.com/Nesvilab/FragPipe/blob/gh-pages/docs/tutorial_fragpipe_outputs.md

Best,

Fengchao

**Comment by FTCPH** [comment]
Thanks a lot for the clarification.

Best,
Frederik

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
