### ISSUE TITLE
FragPipe writes incorrect XSD schema reference to mzML files

### ISSUE THREAD

**Issue by mobiusklein** [Nesvilab/FragPipe#1245]
- Describe the issue or question:

The mzML files written out by FragPipe (presumably by MSFragger) write the wrong `schemaLocation` in the top-level `<mzML>` element:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<indexedmzML xmlns="http://psi.hupo.org/ms/mzml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd">
  <mzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="example"
    <!-- This should be the mzML XSD URI, not the mzML index XSD URI -->
    xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd">
    <cvList count="2">...
```
The correct URI is `http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd` or `http://psidev.info/files/ms/mzML/xsd/mzML1.1.1.xsd`

**Comment by fcyu** [comment]
Thanks for the bug report. May I ask if there are any issue with the existing mzML files?

Thanks,

Fengchao

**Comment by mobiusklein** [comment]
I was able to read the files once I overrode the schema. It seemed accurate, but I didn't have access to the raw spectra to compare with.

**Comment by fcyu** [comment]
Hi @mobiusklein ,

We have fixed this one. If you want to test the pre-released version of MSFragger, please send an email to yufe AT umich.edu.

Best,

Fengchao
