### ISSUE TITLE
Nonspecific-HLA-57 workflow's name does not match its description

### ISSUE THREAD

**Issue by mobiusklein** [Nesvilab/FragPipe#1246]
- Describe the issue or question:

The  `Nonspecific-HLA` and ` Nonspecific-HLA-57` workflows have the same description but treat cysteines differently.

Description:
"Nonspecific search, with recommended settings for HLA peptides. Peptide length 7-25. MSFragger search assumes ***cysteines were not alkylated (i.e. samples were not treated with iodoacetamide). Cysteinylation (C+119) is specified as variable modification.*** MSFragger rescoring with MSBooster. PSM validation with Percolator. Protein FDR filter is not applied, so each output file (PSM, ion, peptide) is filtered to 1% FDR at that level. If needed, extend to add label-free quantifcation (using IonQuant) or spectral library building with EasyPQP." (emphasis mine)

The two workflows differ in their default fixed (`57.02146,C (cysteine),false,-1` -> `57.02146,C (cysteine),true,-1`) and variable modifications (`119.0041,C,true,1` -> `61.98264,C,true,1`)

Is the intention for `Nonspecific-HLA-57` for carbamidomethylated cysteines? The modification rules imply so, but I don't recognized the 61.982 alternative modification, or is that supposed to be additive with the 57 to sum to 119 for cysteinylation?

Is my reading of the intent of the workflow accurate and the description is wrong, or am I missing something?

**Comment by anesvi** [comment]
Yes, 61.98 is to allow for C+119 (added to +57 specified as fixed mod). We will correct the description, but the workflows are fine.

**Comment by fcyu** [comment]
Hi @mobiusklein ,

Thank you for reporting this. I have fixed it: https://github.com/Nesvilab/FragPipe/commit/78f5bb666ec61ff0d461a175cc44c67dc7edc9f0

Best,

Fengchao
