### ISSUE TITLE
How to configure DB split in Fragpipe on windows. 

### ISSUE THREAD

**Issue by gprosales** [Nesvilab/FragPipe#1247]
- Describe the issue or question:
**How do I configure the number of fractions I wish to split the database into?** 
I have a large microbiome proteome database that is exhausting the memory used by Fragpipe.
I have updated python to enable DB split.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It is the `split database` spin box in the `protein digestion` panel of the `MSFragger` tab:

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/ffd88d61-3440-4763-aba1-b85edd8335ce)

Best,

Fengchao

**Comment by gprosales** [comment]
Thanks Fengchao.
I have one more, more elaborate question.
I have been unsuccessful in installing the MSFragger node in Proteome Discoverer 2.5. I followed the instructions your lab provides online, with no success. I follow these instructions: https://www.nesvilab.org/PD-Nodes/#installation-of-pd-nodes
Problem is, I don't see MSFragger in the search engine section in Proteome Discoverer.
Help would be appreciated.
Genaro

**Comment by fcyu** [comment]
The PD node is no longer under active maintenance. Please use FragPipe.

Best,

Fengchao
