### ISSUE TITLE
Variable Mods for glycopeptides

### ISSUE THREAD

**Issue by ABB-808** [Nesvilab/FragPipe#1248]
Hi-

I've been using the fragpipe N-Glyco-HCD/LFQ and O-Glyco-HCD workflows for glycopeptide analysis. Some of my protocols involve chemical modifications to terminal glycans. I am wondering if there is a way to add a variable modification to a glycan in these workflows. I believe the only way seems to be manually changing the mass offsets of the glycans to represent the chemically modified glycan. I've tried open search too, but that does not yield any results. 

Is there any way to create a variable mod for glycans? If not, is there any other method supported aside from adding all possible mass offsets?

**Comment by danielgeiszler** [comment]
Open search should return your glycans. Did you make sure that the mass window was large enough to detect glycopeptides?

If you're modifying the glycan chains to essentially create new glycan monomers, I think you're going to introduce additional issues with glycan assignment as well.

**Comment by ABB-808** [comment]
The mass window shouldn't be an issue since I am able to detect glycopeptides with other protocols using the same mass window. The issue I am having sounds more like your second point. 
Basically the hexose and fucose can have a mass change of ~ + 13 Da
and the NeuAC can have a mass change of ~ - 48 Da. 
Not all sugars will have the modifications but at least one sugar per glycan will. Is there any way to search for that?

**Comment by dpolasky** [comment]
Hi,
Unfortunately we don't have full support for glycan modifications yet, but it's very much at the top of my to-do list - I can let you know when we have a pre-release version ready to test. You can still search for the modified glycans in MSFragger by manually computing the glycan masses and setting those masses as mass offsets in a glyco search, but the glycan composition module will not recognize them. If you disable the glycan assignment (uncheck "Assign glycans with FDR") on the Glyco tab, the output psm.tsv tables will have the delta mass corresponding to the modified glycans that can be used for qualitative analysis, but it will not be possible to do any of the quantitative analyses until the updates are done. 

Best,
Dan

**Comment by ABB-808** [comment]
That new update sounds fantastic, I'll be sure to check it out upon release. 

Looking at the delta masses sounds like a good idea, thanks for the support!

-Alex

**Comment by dpolasky** [comment]
Support for user-defined glycan modifications (fixed or variable) is now available in the 22.0 release, and I will post some documentation explaining how to use the new features to the glyco tutorial later today. 

Best,
Dan
