### ISSUE TITLE
FragPipe DIA w/ fractionated data is this possible?

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#1249]
Hello FragPipe developers, 

We are using FragPipe more and more and data aquisition also transitions more and more to DIA methods. 
I was wondering if FragPipe-DIA (with DIA-NN) can handle fractionated datasets. 

Do you have any experience with this?

best regards
jonas

**Comment by fcyu** [comment]
Hi Jonas,

Could you elaborate the question more? FragPipe can identify and quantify fractionated DIA data, just as non-fractionated DIA. If there is no single-shot at all, you need to use the `iRT` or `ciRT` alignment approach in EasyPQP because there are not many overlapped peptides among fractions.

Best,

Fengchao

**Comment by jjGG** [comment]
Hello Fengchao, 

Thanks this already perfectly answers my question. 
best regards
jonas

**Comment by danielgeiszler** [comment]
Hi Jonas,

To add some additional clarity: if you are trying to do quant on your fractionated DIA, it gets difficult quickly.

DIA-NN isn't set up to handle fractionated DIA data and is going to think each fraction is a separate sample. That means you'll need to turn off DIA-NN normalization. You'll also need to roll up your quants from the fraction-ion level to the sample-protein level manually, and you'll probably need to figure out a way to manage the FDR when you do that.

**Comment by danielgeiszler** [comment]
@fcyu If I missed anything from our conversation, please feel free to add.

**Comment by jjGG** [comment]
Hello Daniel, 
That helps even more now ;) .. obviously this is not how I understood the answer of Fengchao.
best regards
jonas
