### ISSUE TITLE
TMT labels and only 9 samples

### ISSUE THREAD

**Issue by pkorner218** [Nesvilab/FragPipe#1250]
- Describe the issue or question:

Our Proteomics Facility gave us data back with only 9 samples and without a 126 channel (see overview below).
Also we did not get a pool as control. The facility told us it would be possible to just run one control sample as reference. 

We have used fragpipe in the past for TTM labelled data and it worked without problems, but then we had always received also a pooled sample.

Now we can not read in the annotation file correctly. It also does not accept a channel 131N.

127C MiaPaca2_Ctrl_01
127N MiaPaca2_Ctrl_02
128C MiaPaca2_Ctrl_03
128N MiaPaca2_-H_01
129C MiaPaca2_-H_02
129N MiaPaca2_-H_03
130C MiaPaca2_-W_01
130N MiaPaca2_-W_02
131N MiaPaca2_-W_03

Is there a way to properly set up fragpipe with this experiment set-up and with this annotation file?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Yes, you can add the 131N channel but set it to `NA`. You can also set the `define reference` to `virtual` if you don't have pooled sample.

Best,

Fengchao

**Comment by anesvi** [comment]
Please use the GUI to annotate and you will see that there is 131 channel. Maybe you need to remove N.
Also you should have all 10 channels in the annotation file (for the missing sample enter NA as sample name)
