### ISSUE TITLE
Importing MSFragger Library to Skyline with on GPF DIA data

### ISSUE THREAD

**Issue by tomvaiuw** [Nesvilab/FragPipe#1251]
- We have tried to import DIA GPF as described here: https://fragpipe.nesvilab.org/docs/tutorial_skyline.html, to populate Skyline target list, but the it fails because there are no "clean" pepxml files that would match the filename of mzML file, just the files with ".rank1/2/3.pep.xml" files for each mzML files.
Is there a way to import GPF data into Skyline? Do we need to combine the individual GPF files first in MSConvert?
Is there something we are doing wrong?

Thanks,
Tomas

**Comment by fcyu** [comment]
I imported GPF DIA to Skyline many times before. Never had any problems. Not sure if the Skyline team has changed recently to break the workflows (they actually did broke it once and haven't fixed it: https://github.com/Nesvilab/FragPipe/issues/969). I suggest you submit a ticket to their forum.

Best,

Fengchao

**Comment by tomvaiuw** [comment]
Thanks a lot Fengchao,
So what you are saying is that if you have mzML and rankX.pep.xml files in the same folder and upload into Skyline using the DIA peptide search pipeline to build the library, it should work?
I will make sure I repeat do screen captures and will post it to the Skyline forum.

Tomas

**Comment by fcyu** [comment]
Yes, it should work. I just checked the files in my computer, I still have the Skyline files generated from the DIA results.

Maybe you can provide more information such as the error message and the contents in your folder.

Best,

Fengchao

**Comment by tomvaiuw** [comment]
BTW – it appears to be an error in Bibliospec blibbuilder.exe – I tried to run it directly specifying only one interact-xxx.pep.xml file.
It found the correct mzML file but then it appears like it did not match up the spectrum ID in pep.xml and the mzML.

This is what I got:
c:\Users\vaisarlab\Documents\Study_198_SEARCH_Phase1_CVD_BDC\FragPipe\TV_fp10_test5good\1>..\blibbuilder\BlibBuild.exe interact-20230706_CL_BDCA_GPF8_SRA2_rank1.pep.xml test.blib
Reading results from interact-20230706_CL_BDCA_GPF8_SRA2_rank1.pep.xml.
Read 745 matches that passed the score filter (281 matches did not pass).
Loading .\20230706_CL_BDCA_GPF8_SRA2.mzML.
Reading spectra from .\20230706_CL_BDCA_GPF8_SRA2.mzML.
[SpectrumList::find] mismatch between spectrum id format of the file (controllerType=0 controllerNumber=1 originalScan=1 demux=0 scan=1) and the looked-up id (controllerType=0 controllerNumber=1 scan=7675)
ERROR: No spectra were found for the new library.

Tomas

**Comment by fcyu** [comment]
Thanks for the update. I think you should contact the Skyline team since it is their tool's problem.

Best,

Fengchao

**Comment by tomvaiuw** [comment]
Fengchao,
Can I have unrelated question for the clear_mz_range parameter in MSFragger? We exclude range 0-300 m/z yet we still get y1,y2 fragment ions reported in the library created from DIA GPF. Our hope was that we could use this to exclude these (and b2) from the library as they are generally very unspecific and convolute peptide peak integration.

Thanks,
Tomas

**Comment by fcyu** [comment]
Sure.

The `clear_mz_range` is only for MSFragger database searching, not for the other steps such as library building.

Best,

Fengchao

**Comment by tomvaiuw** [comment]
Thanks. So they do not factor into the identification score for easypqp finding the peptide retention time for the library? To get rid those ions you just need to edit the library.tsv then.
We found that the library RT is sometimes way off from the actual chromatographic peak apex and it affects subsequent quantification in diann. We can correct this manually be recalibrating RT in the library after inspecting chromatograms and getting correct RT in Skyline, but it is quite laborious, so we are looking for factors that affect this mismatch of RT. I exchange some emails about it with Alexey.

Tomas


Excuse typos, writing from a smart phone.

________________________________

**Comment by fcyu** [comment]
Hi Tomas,

I believe you already have some discussions here https://github.com/Nesvilab/FragPipe/issues/1233. I will close this one if there are no further questions.

Best,

Fengchao
