### ISSUE TITLE
Cannot load spectral library error towards the end of the run.

### ISSUE THREAD

**Issue by fatima98crc** [Nesvilab/FragPipe#1254]
[FC_error_log.txt](https://github.com/Nesvilab/FragPipe/files/12659481/FC_error_log.txt)

Error when running this. Everything else seemed to be working fine:

C:\Users\Fatima\Downloads\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe --lib library.tsv --threads 15 --verbose 1 --out diann-output\diann-output.tsv --qvalue 0.01 --matrix-qvalue 0.01 --matrices --no-prot-inf --smart-profiling --no-quant-files --peak-center --no-ifs-removal --predictor --dl-no-rt --dl-no-im --strip-unknown-mods --cfg C:\Users\Fatima\MS_Sample_files\fasta_files\run00\PE_1\filelist_diann.txt

1 files will be processed
[0:00] Loading spectral library library.tsv
cannot read the file
ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping

Thank you for your help.

**Comment by fatima98crc** [comment]
Hi, 

I have assigned the files to the same experimental group and EasyPQP and Python are correctly configured I believe. I ran it again and I got the same error. I have attached some pictures

![image](https://github.com/Nesvilab/FragPipe/assets/40497385/033aa648-5c14-4ba8-b156-c7f65cb52315)
![image](https://github.com/Nesvilab/FragPipe/assets/40497385/65483891-f830-409c-b64a-6ca70cf4069a)
![image](https://github.com/Nesvilab/FragPipe/assets/40497385/7e857fa9-8ef2-4c7f-9cf4-d68edf31d9e1)

Thank you for your time and help.

Best,

Fatima

**Comment by fcyu** [comment]
You loaded the `default` workflow
<img width="561" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/62a9630b-756d-4dbe-a7d1-6b7a3cb5e957">

Please load the [DIA_SpecLib_Quant](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#dia_speclib_quant) workflow and try again.

Best,

Fengchao
