### ISSUE TITLE
MemoryError during msfragger_pep_split.py

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/FragPipe#1255]
Dear FragPipe team,

I currently try to run FragPipe with extremely large databases (e.g. ~14Gb and ~300Gb, complete or domain-wise uniprot) to check the identity of several organisms (assuming that the majority of identified proteins should match the organism in question seems faster than establishing 16S-RNA sequencing etc. for a proteomics lab). However, the execution fails during execution of msfragger_pep_split.py. As much as I can follow the process it seems that the first few chunks are generated without any problems but at some point the computer runs out of memory with the following error code:

```
Traceback (most recent call last):
  File "C:\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 613, in main
    sample_fasta(fasta_path, fasta_path_sample, min(num_parts, 1))
  File "C:\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 595, in sample_fasta
    fasta_prots: typing.List[bytes] = [b'>' + e + b'\n' for e in fasta_path.read_bytes()[1:].split(b'\n>')]
MemoryError
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Do you have any suggestions how to avoid this or do you know if it would be possible to bypass the splitting and supply the fasta files in separate folders, organised as in the result from this script, from the beginning? The latter would be possible as I used SeqIO.parse from biopython to sequentially read the files during the creation of decoys which did not run into any memory issues. Modifying that script to provide the split fasta files as output should be easy.

Best regards,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Something seems not right in the fasta file. Could you share it with us? I can give you a link to upload if you want.

Best,

Fengchao

**Comment by JB91451** [comment]
Hi Fengchao,

Yes I can share the fasta file with you. It would be great if you could provide an upload link.

Best regards,
Juergen

**Comment by fcyu** [comment]
Sure, here it is: https://www.dropbox.com/request/NfHIEkCVIkFtOmEY5wpI

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Juergen,

Your fasta file has been well received. It seems that you enabled the mass calibration in MSFragger, which results in not enough memory for the first search. Could you disable it by setting it to `None` and try again?

Thanks,

Fengchao

**Comment by JB91451** [comment]
Dear Fengchao,

Thank you for the quick reply (I did not even notice that the upload was complete).

I tried to run the search without mass calibration or parameter optimisation but it still failed. The error log is enclosed.

Best regards,
Juergen
[log_2023-09-25_14-40-18.txt](https://github.com/Nesvilab/FragPipe/files/12716039/log_2023-09-25_14-40-18.txt)

**Comment by fcyu** [comment]
Hi Juergen,

This time, the error was different. It was due to not enough memory. Could you increase the split number and try again?

Also, I see that there were only 4 GB free memory but your fasta file is ~14 GB. I guess you need to set the split number to a big value, say, 1024.

Best,

Fengchao

**Comment by JB91451** [comment]
Dear Fengchao,

Thanks for pointing this out. I assumed that spliting into 14 chunks would be reasonable as files with ~1Gb usually work nicely on that computer. I started it with a split number of 1024 now and yet there is no error. I guess the process will take until tomorrow.

Best,
Juergen

**Comment by JB91451** [comment]
Hi Fengchao,

unfortunately this also did not work. The log now indicates that the first 301 chunks worked and than the splitting failed again. For me it seems odd, that out of the sudden one of the raw files should be corrupted which it was not during the first 301 chunks:

```
DONE: DB split 301 of 1024
STARTED: DB split 302 of 1024
['C:\\Tmp\\FragPipe-jre-20.0\\fragpipe\\jre\\bin\\java.exe', '-jar', '-Dfile.encoding=UTF-8', '-Xmx6G', WindowsPath('C:/Tmp/MSFragger-3.8/MSFragger-3.8.jar'), 'fragger.params', WindowsPath('C:/Tmp/230915_O1_P8_SG_HW_Fnucl-BHI-S_3.raw'), WindowsPath('C:/Tmp/230915_O1_P8_SG_HW_Lrham-BHI-S_2.raw'), WindowsPath('C:/Tmp/230915_O1_P8_SG_HW_Lrham-BHI_1.raw'), '--partial', '301']
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 6 GB memory
Checking database...
Checking spectral files...
C:\Tmp\230915_O1_P8_SG_HW_Fnucl-BHI-S_3.raw: Scans = 19020
Failed in checking C:\Tmp\230915_O1_P8_SG_HW_Lrham-BHI-S_2.raw. Will ignore it.
UNKNOWN: Exception was thrown by handler.
C:\Tmp\230915_O1_P8_SG_HW_Lrham-BHI-S_2.raw: Scans = 0
There are corrupted files. Please remove those files and re-start the task.
C:\Tmp\230915_O1_P8_SG_HW_Lrham-BHI_1.raw: Scans = 21234
Traceback (most recent call last):
  File "C:\Tmp\Sandra\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\Tmp\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 616, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\Tmp\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 133, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Programs\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Tmp\\FragPipe-jre-20.0\\fragpipe\\jre\\bin\\java.exe', '-jar', '-Dfile.encoding=UTF-8', '-Xmx6G', 'C:\\Tmp\\MSFragger-3.8\\MSFragger-3.8.jar', 'fragger.params', 'C:\\Tmp\\230915_O1_P8_SG_HW_Fnucl-BHI-S_3.raw', 'C:\\Tmp\\230915_O1_P8_SG_HW_Lrham-BHI-S_2.raw', 'C:\\Tmp\\230915_O1_P8_SG_HW_Lrham-BHI_1.raw', '--partial', '301']' returned non-zero exit status 1.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 25 remaining tasks
```

**Comment by fcyu** [comment]
It was due to some instability of the IO and Thermo raw parser. Could you convert it to mzML and try again? Here is the tutorial of the conversion in case you need: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by JB91451** [comment]
Yes, I will try it. As we have a lab course currently, it may takes some time but I will inform you as soon as I have done this test.
