### ISSUE TITLE
Running Percolator instead of PeptideProphet from command line

### ISSUE THREAD

**Issue by demhibou** [Nesvilab/FragPipe#1256]
- Describe the issue or question:

We are trying to run FragPipe from the command line. Our current code on a Windows computer is simply:

"D://FragPipe-jre-20.0/fragpipe/bin/fragpipe.bat" --headless --workflow "D://Sara/LFO_AB.workflow" --manifest "D://FragPipe-jre-20.0/testmanifest.fp-manifest" --workdir "//TIMS-10815/Data_QC/ProcessedData/Test_analysis

Our understanding is that this by default runs PeptideProphet. However, we would like to run Percolator instead. In the GUI interface, we noticed this is easy to select. However, we aren't sure how to accomplish this using the command line code. Thanks for any help!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

No log file.

**Comment by fcyu** [comment]
You can set the parameters in GUI, and then export the workflow files. Here is the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_headless.html

Best,

Fengchao
