### ISSUE TITLE
Question about IonQuant STY_79.9663.tsv or other PTM outputs

### ISSUE THREAD

**Issue by vincentroyrichard** [Nesvilab/FragPipe#1259]
Hello!

I am using IonQuant in Fragpipe v20 for LFQ based phosphoproteomics as well as for other PTMs - I am curious to know more about how the STY_79.9663.tsv or other equivalent PTM files are generated, and how the LFQ abundances are calculated. If for example a phosphosite is present in multiple different peptide species (missed cleavages, multiple PTMs on the same peptide, etc) how is the final site-specific LFQ abundance generated? 

Thanks very much,
Vincent

**Comment by fcyu** [comment]
Hi Vincent,

For IonQuant, the site-level intensities are either from top-N or MaxLFQ algorithms. If there are multiple peptides with the same PTM site, their intensities will be used in the top-N or MaxLFQ.

I hope my answer is clear enough. Please feel free to contact us if you have further questions.

Best,

Fengchao
