### ISSUE TITLE
PeptideProphet Unknown file type. No file loaded.E:\mzFRAG/JD_06232014_sample4_C.mzBIN_calibrated WARNING: cannot open data file E:\mzFRAG/JD_06232014_sample4_C.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...

### ISSUE THREAD

**Issue by yb47620** [Nesvilab/FragPipe#126]
# Describe the problem
I finished a task using FragPie, however, I found a warning in the log file. I am not sure whether the results is affected. 
* **I'm submitting a:**
  - [x] problem running the software

* **My MSFragger use case:**
  - [x] _Closed_ search (standard small precursor mass tolerance)
 ** _put your general problem description here_
When the PeptideProhet started, a WARNING like this was reported for each data processing: ****cannot open data file E:\mzFRAG/JD_06232014_sample4_C.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML****  (details are shown in attached pic)

![image](https://user-images.githubusercontent.com/54254763/63429185-f72ca400-c44b-11e9-8175-2004eefb68a8.png)
[log-fragpipe-run-at_2019-08-20_16-13-20.log](https://github.com/Nesvilab/FragPipe/files/3525130/log-fragpipe-run-at_2019-08-20_16-13-20.log)

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

### Genral proteomics experiment description
e.g. yeast shotgun_"

...

### Input data files
** 11 mzML files

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

[parameters.txt](https://github.com/Nesvilab/FragPipe/files/3525143/parameters.txt)

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```

**Comment by fcyu** [comment]
It's because PeptideProphet cannot open the spectra file to correct the scan number. To my knowledge, there is no harm when PeptideProphet failed to do so. You could just ignore those warnings.

Best,

Fengchao
