### ISSUE TITLE
abundance_protein.tsv donnt include unique pool

### ISSUE THREAD

**Issue by xyzcc2007** [Nesvilab/FragPipe#1261]
when I run mixed batch TMT,the abundance dont include unique pool columns,only get a refintensity column.
but when I run single bat,the protein_tsv get the pool column.
I want to campare every pool,how should I do.
![1](https://github.com/Nesvilab/FragPipe/assets/145945874/bdf8584d-02ff-4d85-a13e-d9ca45280747)
[log_2023-09-05_00-34-42.txt](https://github.com/Nesvilab/FragPipe/files/12710383/log_2023-09-05_00-34-42.txt)

**Comment by fcyu** [comment]
I believe I have already answered your question on WeChat unless there were two users having the same question and the same output files at the same time by coincidence.

You are comparing the tsv files from two different steps/tools. The one with `pool22` contains the raw channel intensities in each experiment group/folder. It it before TMT-Integrator and contains raw intensity. The one with `ReferenceIntensity` is after normalization and other process. It is not vary meaningful to compare the reference intensity after normalization. If you want, use the protein.tsv files in each experiment (which you have already found).

Best,

Fengchao

**Comment by xyzcc2007** [comment]
Thank you for your reply

发自我的 iPhone
