### ISSUE TITLE
Problems loading the spectral library (optional)

### ISSUE THREAD

**Issue by EscandonM** [Nesvilab/FragPipe#1263]
Dear FragPipe team,
I am working with data from diaPASEF. The problem I have is that when I load the spectral library (optional) in the DIA quantification tab, it does not work and nothing is triggered when I press the "run" button.
I have tried different libraries (obtained from DIA-NN and also from diaPASEF data passed to mzML using FragPipe).

**Comment by fcyu** [comment]
I could not reproduce it using FragPipe version 20:

![Animation2](https://github.com/Nesvilab/FragPipe/assets/6926299/4edad395-6290-4b85-9491-f4cb5e8b301a)

Best,

Fengchao

**Comment by EscandonM** [comment]
Thank you for your quick response.
In the Imput files I am loading the .d files, only being able to select DIA-quant.

With tmzML transformed data it works, isn't it possible with the .d files?

**Comment by EscandonM** [comment]
Hi Fengchao;
I have found the problem why the "run" was not working. Among the tabs I had "run validaction tools" activated in the validation tab. As soon as it is activated, it doesn't work.
I also had the MSfragger tab enabled, but that doesn't affect it.

Btw, as for the transformation of the data to mzML was because I couldn't generate the library with the DIApasef data, so I transformed it, generated the library and with it I'm going to quantify the data in .d format.
Is there another way to generate the library with diaPaSEF data?

Thank you very much and I look forward to your answer :)

**Comment by fcyu** [comment]
> I have found the problem why the "run" was not working. Among the tabs I had "run validaction tools" activated in the validation tab. As soon as it is activated, it doesn't work.
I also had the MSfragger tab enabled, but that doesn't affect it.

Thanks for the testing and reporting. It seems to be a bug and has been fixed: https://github.com/Nesvilab/FragPipe/commit/f006c4bfe1863625d70a21f5b71442c1103292bc


> Btw, as for the transformation of the data to mzML was because I couldn't generate the library with the DIApasef data, so I transformed it, generated the library and with it I'm going to quantify the data in .d format.
Is there another way to generate the library with diaPaSEF data?

If you convert .d to mzML, some information will be lost. Furthermore, FragPipe does not support directly searching diaPASEF yet. Thus, I don't think your approach will provide good results. If you have both ddaPASEF and diaPASEF, you can set ddaPASEF to `DDA` data type and diaPASEF to `DIA-Quant` data type. Then, FragPipe will build a library using the ddaPASEF and then quantify the diaPASEF. If you only have diaPASEF but no ddaPASEF, you might consider using the DIA-NN standalone version.

Best,

Fengchao

**Comment by EscandonM** [comment]
Thank you Fengchao for your comments, unfortunately we don't have ddaPasef files, so we will do the DIA-NN approach.
I'll keep an eye out for updates in case it becomes possible one day.
Best,
Monica E.
