### ISSUE TITLE
Incorrect fasta file crashed MSFragger.

### ISSUE THREAD

**Issue by patrick-willems** [Nesvilab/FragPipe#1265]
- Describe the issue or question:

MSFragger crashes immediately during searches. It gives an error for length 27 (while maximum peptide length was set to 25..). Unsure how to proceed - any help is greatly appreciated!

- Upload your log file
[log_2023-09-27_10-50-05.zip](https://github.com/Nesvilab/FragPipe/files/12736624/log_2023-09-27_10-50-05.zip)

**Comment by fcyu** [comment]
You provide the incorrect fasta file: 

database.db-path=C\:\\Users\\psbuser\\Documents\\Fragpipe_20.0\\data\\**RUN3_leroy50_3_peptidomics_Jan2022_109.raw**

Best,

Fengchao
