### ISSUE TITLE
What to do to detect biotinylation?

### ISSUE THREAD

**Issue by sasvarip** [Nesvilab/FragPipe#1266]
- Describe the issue or question:
Hi, we are planing to use MS to detect biotinylated proteins. Could you help me what should be changed in Fragpipe to make it detect biotinylation? During the experiment, lysine can be biotinylated.

Thanks in advance.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
What about starting from setting Biotinylation as a variable modification? If it is labile, consider modifying the "Labile_phospho" workflow.

Best,

Fengchao

**Comment by anesvi** [comment]
I think just adding it as variable modification is enough. I try should not be Labile.  However, in many cases the protein is biotinylated somewhere, but the majority of identified peptides are not, and there are only few modified peptides identified if searched for. Hence, people often do not bother adding it as a variable modification, but of course it depends on the details of your particular experiment.
