### ISSUE TITLE
Differences in number of peptides

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#1267]
Hi all,

I am writing because I noticed that the number of peptides in the peptide.tsv file is different than the number of unique sequences in the psm.tsv. The latter (psms) having more than the peptides. I am running the workflow of HLA peptide search (Nonspecific-HLA) with DDA and DIA data. I wonder if there is any explanation for that? Is it something already expected?

Let me know if you need that I send you any data such as the workflow files or the outputs.

Thanks in advance for your help.

Best regards,

Emma

**Comment by anesvi** [comment]
Yes, each level is filtered to that level FDR. So if you want PSM list filtered to 1 percent peptide-level FDR, you need to remove peptides not present in the peptide file.

**Comment by anesvi** [comment]
By the way, if you are building the spectral library, FragPipe will filter to 1 percent peptide FDR. In effect it will additionally filter PSM.tsv based on peptide.tsv file. But, as I said, original PSM files show 1 percent PSM level filtered data.

**Comment by ericart89** [comment]
> Yes, each level is filtered to that level FDR. So if you want PSM list filtered to 1 percent peptide-level FDR, you need to remove peptides not present in the peptide file.

Thanks, that's what I will do then! Thank you very much for your help! :)

**Comment by ericart89** [comment]
Sorry, one last question... the peptide-level FDR is applied on the PSM FDR-filtered data or they are two independent calculations?
