### ISSUE TITLE
Error during DIA-MS runs

### ISSUE THREAD

**Issue by Raghothama1** [Nesvilab/FragPipe#1269]
- Describe the issue or question:
Batmass-IO version 1.28.12
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/C:/Software/FragPipe/FragPipe-jre-20.0/fragpipe/tools/DIA_Umpire_SE-2.3.2.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-09-30 22:39:43
[log_2023-10-01_08-20-04.txt](https://github.com/Nesvilab/FragPipe/files/12777242/log_2023-10-01_08-20-04.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Your error message is `Process 'Percolator' finished, exit code: -1073741819`, which is the same as https://github.com/Nesvilab/FragPipe/issues/1227, https://github.com/Nesvilab/FragPipe/issues/1211, and https://github.com/Nesvilab/FragPipe/issues/1160.

There is no ID in your data. Since you were using DIA-Umpire, could you try another workflow, [DIA_SpecLib_Quant](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#dia_speclib_quant), to use MSFragger-DIA rather than DIA-Umpire?

Best,

Fengchao

**Comment by Raghothama1** [comment]
Hi Fengchao,
I got the same error message when I selected MSFragger-DIA. Do you mind checking the log file? My dataset has only DIA raw files no DDA files for library construction.
Thanks a lot
Raghothama
________________________________

**Comment by fcyu** [comment]
Your log was truncated by GitHub. Could you zip and upload it here?

Thanks,

Fengchao

**Comment by Raghothama1** [comment]
Attached, thank you for your time
Raghothama
________________________________

**Comment by fcyu** [comment]
No, it is not.

**Comment by Raghothama1** [comment]
Reattached
Thank you
Raghothama

**Comment by fcyu** [comment]
Still not. Can you click https://github.com/Nesvilab/FragPipe/issues/1269, login, and then reply the message by upload the zipped file?

Thanks,

Fengchao

**Comment by Raghothama1** [comment]
[log_2023-10-03_13-36-21.zip](https://github.com/Nesvilab/FragPipe/files/12796238/log_2023-10-03_13-36-21.zip)

**Comment by fcyu** [comment]
Thanks for your file. Same error as previously mentioned: `Process 'Percolator' finished, exit code: -1073741819`. Could you remove `20230930_deplPlasma-DIA_120min_1028_1128_1` and try again?

Thanks,

Fengchao

**Comment by Raghothama1** [comment]
This time it partially worked. I could see the protein peptide information but there is still some issue.
Thank you
Raghothama
[DIA_MS_120min_2-2da-FP_IInd_try.zip](https://github.com/Nesvilab/FragPipe/files/12796712/DIA_MS_120min_2-2da-FP_IInd_try.zip)

**Comment by fcyu** [comment]
Could you upgrade EasyPQP to the latest version and try again? You can click the `Install/Upgrade EasyPQP` in the `Config` tab, and then wait a few seconds.

Best,

Fengchao

**Comment by fcyu** [comment]
Also, I see that you were using the raw file. Then, you have to make sure that the correct version of Thermo library is installed because the DIA-NN quant requires that: https://github.com/vdemichev/DiaNN#raw-data-formats

Best,

Fengchao

**Comment by Raghothama1** [comment]
I have used the correct version of Thermo library now (3.0v). I am still getting error messages and data analysis is partial. I have attached the logfile here. In my searches there are only DIA files no DDA files. Will it be an issue for DIA library construction? Thank you for your support.
Raghothama
[log_2023-10-07_20-09-28.zip](https://github.com/Nesvilab/FragPipe/files/12846902/log_2023-10-07_20-09-28.zip)

**Comment by fcyu** [comment]
Same issue as: https://github.com/Nesvilab/FragPipe/issues/1275. Could you uninstall and install the fixed EasyPQP following the instruction in https://github.com/Nesvilab/FragPipe/issues/1275#issuecomment-1749369666 ?

Thanks,

Fengchao

**Comment by Raghothama1** [comment]
[log_2023-10-09_14-02-01.zip](https://github.com/Nesvilab/FragPipe/files/12850968/log_2023-10-09_14-02-01.zip)
Still, it cancelled some tasks. I am not sure whether it worked. 

EasyPQP  is installed properly: Installed Git, and added the path C:\Program Files\Git\bin 
In cmd,
pip install git+https://github.com/Nesvilab/easypqp.git@master 

Thanks
Raghothama

**Comment by fcyu** [comment]
No, you did not **uninstall** and install the EasyPQP correctly. Please following the command in the link I previously mentioned: https://github.com/Nesvilab/FragPipe/issues/1275#issuecomment-1749369666

**pip uninstall easypqp -y**
pip install git+https://github.com/Nesvilab/easypqp.git@master

Best,

Fengchao

**Comment by Raghothama1** [comment]
Thank you for the instructions. Now I installed the EasyPQP correctly. Issue is resolved and searches completed without error. 
Appreciate your help.
-Raghothama
