### ISSUE TITLE
Problem with analyzing TIMS-TOF data

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#1270]
We're having repeated issues with analyzing TIMS-TOF data with the IsoDTB-ABPP workflow. 

[log_2023-10-02_18-01-17.txt](https://github.com/Nesvilab/FragPipe/files/12793631/log_2023-10-02_18-01-17.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1269, https://github.com/Nesvilab/FragPipe/issues/1227, https://github.com/Nesvilab/FragPipe/issues/1211, https://github.com/Nesvilab/FragPipe/issues/1160, 

There are no IDs from the run `TTP-WAT_NL_19249_15-48_2_01082023_07-Aug-23_14-50-48_3891`:
```shell
Calculating q values.
Final list yields 0 target PSMs with q<0.01.
Calculating posterior error probabilities (PEPs).
Process 'Percolator' finished, exit code: -1073741819
Process returned non-zero exit code, stopping
```

Could you remove that run and try again?

Thanks,

Fengchao
