### ISSUE TITLE
Issue with identifying STY modification in MSstats file.

### ISSUE THREAD

**Issue by LoganSmithRSA** [Nesvilab/FragPipe#1271]
Hi there
I am currently struggling to ID the phosphopeptides (mod STY: 79.66331) in my MSstats file. Oxidation of methionine shows in this file, however the STY is completely absent. Even when I include deamidation as a variable mod, this shows up fine. I have also tried running my glyco-enrichment experiments where I've specified deamidation and STY, then both of these show on the MSstats output file. I am running a closed search and the operation runs to completion. 

Are there any solutions to this? Attached is the log file and msstats.csv file.

[log_2023-10-03_01-37-38.txt](https://github.com/Nesvilab/FragPipe/files/12796536/log_2023-10-03_01-37-38.txt)

[msstats.csv](https://github.com/Nesvilab/FragPipe/files/12796537/msstats.csv)

**Comment by fcyu** [comment]
1. I see that you enabled `Generate MSstats files` in the `Validation` tab for the LFQ data. That checkbox is actually only for TMT data.
2. You did not enable either IonQuant or Philosopher free quant to perform label-free quantification, which resulted in 0 intensities for all peptides
3. There seems to be a bug in Philosopher that the phospho was not propagated to msstats.csv

With all those, you got a very weird result. There are also other issues in your settings

1. You set the enzyme name to `nonspecific` but set the `cleavage` to `enzymatic` (`num_enzyme_termini = 2`), which does not make any sense. 
2. You put `-18.01056 79.96633` to reminder fragment masses but `0` to mass offsets.

I only took a brief look. Not sure if there are any other issues. I suggest you start with the built-in workflow.

> I have also tried running my glyco-enrichment experiments where I've specified deamidation and STY, then both of these show on the MSstats output file. I am running a closed search and the operation runs to completion.

Not sure how you did the glyco search. Maybe you should also use the built-in workflow.

Best,

Fengchao

**Comment by LoganSmithRSA** [comment]
My apologies, Fengchao, it looks like I attached the wrong files for you.
For the purpose of this study, I do not need peptide intensity information. I am essentially comparing phosphopeptide enrichment to controls, the same with glycopeptide enrichment. I like the MSstats file format because it makes it easier for me to identify peptides and manually count them. I have now incorporated the default workflow and loaded the closed search default config in MSFragger. Please see attached the correct log file.

If it is a philosopher bug, is there any way I can fix this? 

[log_2023-10-03_23-30-53.txt](https://github.com/Nesvilab/FragPipe/files/12797120/log_2023-10-03_23-30-53.txt)
[msstats.csv](https://github.com/Nesvilab/FragPipe/files/12797121/msstats.csv)

**Comment by fcyu** [comment]
As I mentioned, you should not check the `Generate MSstats files` box because that is not for label-free data. We never tested it for the label-free data, and don't know if it works well (as you have already found, it has a bug). If you want to have msstats.csv for your label-free data, you can use the `LFQ-MBR` workflow which is equivalent to enabling IonQuant. IonQuant will generate the msstats.csv for you.

Best,

Fengchao
