### ISSUE TITLE
Follow up Philosopher #1271

### ISSUE THREAD

**Issue by LoganSmithRSA** [Nesvilab/FragPipe#1272]
Hi there Fengchao
I made a mistake and uploaded the incorrect log file for you.  I like to use the MSSstats file because it is easy for me to navigate through, and I do not need peptide intensities for what I am trying to identify. I've ran my glyco file now again using the default workflow and closed config, STY is once again left out in MSstats file. Attached is the correct log file.
[log_2023-10-04_00-13-00.txt](https://github.com/Nesvilab/FragPipe/files/12797369/log_2023-10-04_00-13-00.txt)

If this is a Philosopher bug, is there a way to fix this, or should I use another method to view my data? I would greatly appreciate your advice with this.

Best wishes,
Logan.

**Comment by fcyu** [comment]
I have already replied here: https://github.com/Nesvilab/FragPipe/issues/1271#issuecomment-1745812348
