### ISSUE TITLE
Cannot read file. open .meta\db.bin: The system cannot find the file specified.

### ISSUE THREAD

**Issue by catlab321** [Nesvilab/FragPipe#1273]
[log_2023-10-05_03-19-20.txt](https://github.com/Nesvilab/FragPipe/files/12807408/log_2023-10-05_03-19-20.txt)
ERRO[02:48:06] Cannot read file. open .meta\db.bin: The system cannot find the file specified. 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks

**Comment by fcyu** [comment]
It may be because you disabled ProteinProphet. Can you load the built-in `Open` workflow and try again?

Thanks,

Fengchao

**Comment by catlab321** [comment]
Thank you for your quick reply. Now it is normal. Thank you very much.
