### ISSUE TITLE
Some peptide intensity and MaxLFQ intensity are 0 in all experiments_IonQuant 

### ISSUE THREAD

**Issue by fengx90** [Nesvilab/FragPipe#1274]
Hello there,

I know there are previous issues posted here regarding the differences between intensity and MaxLFQ intensity in the output files which I totally understand, but I did not find anyone mentioning the 0 value for both. 

I analyzed 4 files (different experiments) without MBR, but enabled the MaxLFQ (minimum ion = 1), meanwhile the Top-N ions was set to 3. I found some proteins and peptides (from the Combined_* file) having 0 intensity in all 4 samples, as well as in each of the protein.tsv and peptide.tsv. I checked some specific peptides in the PDV and they acutally have valid spectrum with more than 3 fragments. Can you explain this a bit? 
Thanks very much!

Regards,
Feng

**Comment by fcyu** [comment]
The spectra you visualized in PDV are MS2, while the LFQ intensities are from MS1. Furthermore, there are some quality control criteria such as min scan = 3 and min isotope = 2 (by default) to filter out low quality XIC. If you are interested in, can you load FragPipe results to Skyline to visualize the MS1 XIC: https://fragpipe.nesvilab.org/docs/tutorial_skyline.html ?

Best,

Fengchao

**Comment by fengx90** [comment]
Hello Fengchao,

Thanks for the quick reply. 
Yes, in PDV we can only visualize the MS2 spectrum, and the peptide quantification is based on the XIC of the precursors. 

But the intensity column in the peptide.tsv file represents "Intensity summed intensity of the top 3 most abundant ions for the peptide", according to the explanation. In this case, what are top-3 most abundant ions? precursors, if I am not misunderstanding? If so, what happens if a peptide only has 1 or 2 precursors?

the setting of Top-N ions in "Advance options" is for protein quantification only, meaning the Top-N abundant peptides will be used to calculated the intensity of the protein, right?  

Best,
Feng

**Comment by fcyu** [comment]
> But the intensity column in the peptide.tsv file represents "Intensity summed intensity of the top 3 most abundant ions for the peptide", according to the explanation. In this case, what are top-3 most abundant ions? precursors, if I am not misunderstanding? 

To prevent any miscommunication, let me first clarify some some terms. The ion is `peptide+modification+charge`, the modified peptide is `peptide+modification`, and the peptide is peptide sequence. So, the peptide intensity is the summation of top 3 most abundant **ion** intensity. The ion intensity is from XIC, not just one or two precursor peaks in the `(intensity, mz)` dimension.

> If so, what happens if a peptide only has 1 or 2 precursors?

I am not sure what the "precursors" refer to in your question. If it means the ions in my above definition, then, the peptide intensity is just the summation of those 1 or 2 ions.

> the setting of Top-N ions in "Advance options" is for protein quantification only, meaning the Top-N abundant peptides will be used to calculated the intensity of the protein, right?

That is correct. The `Top-N` parameter is only for protein-level intensity. For peptide-level, it is always top-3.

Best,

Fengchao

**Comment by fengx90** [comment]
Thanks for clarifying the terms. 
Precursors refer to m/z, so it is as you said peptide+modification+charge state. And now it is pretty clear to me that "ions" in IonQuant only refer to "precursor ions" not "fragment ions". 

With this clarified, I have no more question regarding the quantification. The 0 value in the intensity column could be a result of criteria as you mentioned min.scan etc.

Thanks very much again for your explanation!

Best,
Feng
