### ISSUE TITLE
FragPipe PDV Viewer hangs at "Moving. Please Wait"....

### ISSUE THREAD

**Issue by vikastuteja1** [Nesvilab/FragPipe#1276]
- Describe the issue or question:

After running an analysis, FragPipe PDV Viewer hangs with the message "Moving. Please Wait" (see attached screenshot).

The Java process for PDV Viewer is consuming 8-9% of CPU and Memory consumption is steadily increasing to 1706MB

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
![Screenshot 2023-10-05 142513](https://github.com/Nesvilab/FragPipe/assets/19630196/e3a9e183-551d-48c0-a3de-032530c72c8e)
[log_2023-10-05_14-21-22.txt](https://github.com/Nesvilab/FragPipe/files/12824143/log_2023-10-05_14-21-22.txt)

**Comment by KaiLiCn** [comment]
Hi,

Could you upload your whole FragPipe result folder and your raw file here? I will test it once I recieve it. https://www.dropbox.com/request/hT9zVQjkEMhiKB30iTLB

Best,
Kai

**Comment by KaiLiCn** [comment]
Hi,

I recieved you files. But it looks like it's different with what you shown here. And I can open your files smoothly. Can you upload the files causing the issue?
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/ba4664c4-d843-4bc6-b84d-68e6391c6e47)

Kai

**Comment by vikastuteja1** [comment]
Sorry - I tried out many files before to see if it was an issue with just one dataset. I have reinstalled Fragpipe (again) and now it works on all my files. Please close.
