### ISSUE TITLE
Clarification on Fragpipe mapped proteins output

### ISSUE THREAD

**Issue by ashwinkallor** [Nesvilab/FragPipe#1278]
Hello,

I would like to clarify about the Mapped Proteins and Protein Start/Protein End columns. For example, we have a peptide "AADLVEALY" which was mapped by Fragpipe to three different proteins, EBF1, EBF2 & EBF3 as we can see below: 

"ENSP00000322898|ENST00000313708|ENSG00000164330|EBF1,ENSP00000347463|ENST00000355311|ENSG00000108001|EBF3,ENSP00000357637|ENST00000368648|ENSG00000108001|EBF3,ENSP00000370029|ENST00000380654|ENSG00000164330|EBF1,ENSP00000386178|ENST00000408929|ENSG00000221818|EBF2,ENSP00000428020|ENST00000517373|ENSG00000164330|EBF1,ENSP00000430241|ENST00000520164|ENSG00000221818|EBF2,ENSP00000437909|ENST00000535548|ENSG00000221818|EBF2,ENSP00000477809|ENST00000622875|ENSG00000164330|EBF1" 

The protein start and end co-ordinates were output as 382-390. When we mapped the peptide "AADLVEALY" to the protein sequences of "EBF1", "EBF2" and "EBF3", we found that the protein start and end co-ordinates for the peptide "AADLVEALY" were different in each case and only for EBF1 were the co-ordinates 382-390 correct. 

I would like to ask how to interpret this result? Which specific protein should we consider as being the source of our peptide when we see several proteins identified by Fragpipe for the same peptide (as in the above example)?

**Comment by anesvi** [comment]
It should be the coordinates within the protein shown in Protein column. As to your question how to interpret it, this is a more general protein inference question. If all proteins are indistinguishable based on what peptides were identified, well you just don't know what protein this peptide comes from.

**Comment by ashwinkallor** [comment]
Thanks, Alexei, I will check this once more and if there are no more issues, I will close it immediately.
