### ISSUE TITLE
Exit Code 1 observed when enabling mass calibration and parameter optimization

### ISSUE THREAD

**Issue by vikastuteja1** [Nesvilab/FragPipe#1281]
- Describe the issue or question:
Received exit code 1 when redoing an analysis with mass calibration and parameter optimization enabled (no other changes made).

Found mention of same error here (https://github.com/Nesvilab/FragPipe/issues/350) from April of 2021 - not sure if same cause.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-10-09_06-27-11.txt](https://github.com/Nesvilab/FragPipe/files/12848978/log_2023-10-09_06-27-11.txt)

**Comment by fcyu** [comment]
Could you share your fasta file with us?

Thanks,

Fengchao

**Comment by vikastuteja1** [comment]
Zipped file attached

[2023-09-04-decoys-contam-SPH_25092023_20423p.fasta.zip](https://github.com/Nesvilab/FragPipe/files/12849005/2023-09-04-decoys-contam-SPH_25092023_20423p.fasta.zip)

**Comment by fcyu** [comment]
Thanks for your file. The error looks weird, I need your raw files to debug. Could you upload `K562_Lysate_Trypsin_Tris_FusionLumos_Rep1.raw` to https://www.dropbox.com/request/T9ma8JZFN71gmQKNV8Re ?

BTW, there is an error in the parameter:
```
variable_mod_08 = 57.02146 Carb-C 2
```
I guess you wanted to put `57.02146 C 2`

Best,

Fengchao

**Comment by vikastuteja1** [comment]
Fengchao, Thank you for spotting the error. Am I right in thinking the SW would ignore that input as nonsensical?

**Comment by fcyu** [comment]
Thanks for your files. There was a bug in MSFragger that caused the error. If you are interested in trying the pre-released fixed version. Please send an email yufe AT umich.edu

Best,

Fengchao
