### ISSUE TITLE
Empty PSM list crashes EasyPQP: `ValueError: No objects to concatenate`

### ISSUE THREAD

**Issue by k-p4** [Nesvilab/FragPipe#1283]
- Describe the issue or question:
Easypqp spectral library generation fails:

```
AssertionError
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
```
reproduced the same error on Windows and Linux

- Upload your log file
[log_2023-10-10_12-43-32.zip](https://github.com/Nesvilab/FragPipe/files/12860691/log_2023-10-10_12-43-32.zip)

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1275 and https://github.com/Nesvilab/FragPipe/issues/1269#issuecomment-1753058933

Could you **uninstall** and install the fixed EasyPQP using the following command, and try again?

```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Thanks,

Fengchao
