### ISSUE TITLE
Determining the data type starting from mzML files

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1285]
Hi! Given a set of mzML files that FragPipe takes as inputs, is it possible to determine the type of data (DDA or DIA) that these files contain? Thank you!

**Comment by fcyu** [comment]
It is hard to determine if a mzML is from DDA or DIA because there is no explicit information in the file. Checking the isolation window size is also not always work because there are narrow window DIA.

Best,

Fengchao

**Comment by RobAlbn** [comment]
Thank you for your answer!
