### ISSUE TITLE
PSMs with 0 intensity

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#1286]
Why are PSMs with Intensity = 0 included in the PSM files? How should these be interpreted?

Example:
<img width="929" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/54612207/d0304547-2556-4f33-9849-2dd3941d5b6a">

**Comment by anesvi** [comment]
It means the ms1 peak was not detected, or it did not pass the QC criteria (e.g. those specified in IonQuant tab)

**Comment by ndtivendale** [comment]
But then why are those PSMs included in the file at all?

**Comment by anesvi** [comment]
Because those PSMs were identified and passed the FDR.

**Comment by ndtivendale** [comment]
But with no MS1 intensity. So, should they be counted if I am using spectral counts a proxy for a abundance? Or should they be removed before further processing?

**Comment by anesvi** [comment]
Sorry, this is a forum for technical support related to FragPipe, not for answering basic questions

**Comment by ndtivendale** [comment]
OK.
