### ISSUE TITLE
Duplicate values in ion_label_quant.tsv for same peptide with different compensation values

### ISSUE THREAD

**Issue by EsbenSv** [Nesvilab/FragPipe#1287]
- Describe the issue or question:

I am quantifying light/heavy labelled peptides generated in a isoDTB-ABPP like workflow. While I was looking closer at some of the hits in the data, I noticed identical values between the same peptide at two different compensation voltages with specific labels. In the attached data, there is multiple examples, and I found multiple examples in other replicates. 
One example is for the peptide "NCLTNFHGMDLTR". The psm.tsv file does not have identical values for these peptides. 

<img width="813" alt="ion_label_quant_RPS3A_same_intensities_different_CVs" src="https://github.com/Nesvilab/FragPipe/assets/43599401/b4defc8c-1c10-467a-8933-4201005ddb3a">

I am wondering whether there is some bug in IonQuant that in some weird instances gives identical values?

I am happy to share the raw data that is used to generate this data or any other required information.

Versions:
Windows 10 21H2 64-bit
FragPipe: 20.0
MSFragger: 3.8
IonQuant: 1.9.8
Philosopher: 5.0.0

Workflow:
[fragpipe_workflow.zip](https://github.com/Nesvilab/FragPipe/files/12893328/fragpipe_workflow.zip)

ion_label_quant.tsv:
[220922_BioAEK145-200ng_2hDDA_427_IA1_ion_label_quant.zip](https://github.com/Nesvilab/FragPipe/files/12893331/220922_BioAEK145-200ng_2hDDA_427_IA1_ion_label_quant.zip)

psm.tsv:
[psm.zip](https://github.com/Nesvilab/FragPipe/files/12893333/psm.zip)

- Upload your log file

[log_2023-10-13_12-54-51.txt](https://github.com/Nesvilab/FragPipe/files/12893319/log_2023-10-13_12-54-51.txt)
[log_2023-10-13_12-54-51.zip](https://github.com/Nesvilab/FragPipe/files/12893324/log_2023-10-13_12-54-51.zip)

**Comment by fcyu** [comment]
This is not a bug, it is a feature ;) 

We intentionally distinguish ions with different compensation voltages because they are supposed to have different intensities. It was discovered by a user and here is the discussion: https://github.com/Nesvilab/IonQuant/issues/42

Best,

Fengchao

**Comment by anesvi** [comment]
But if quant is identical, it is suspicious. Why would the values be identical ( duplicated)?

**Comment by EsbenSv** [comment]
Hi Fengchao,

Thank you for your quick response. What I don't understand is that the heavy intensities are different, and match the values in the psm.tsv file, but the light intensities are duplicated?

Here, from the psm.tsv file:
<img width="402" alt="psm_RPS3A_heavy_and_light" src="https://github.com/Nesvilab/FragPipe/assets/43599401/e3eda49b-e1f1-44aa-b76c-804b378291fe">

This would seems to totally skew the HL ratioes for this peptide?

**Comment by fcyu** [comment]
This is a good point! It seems that IonQuant didn't match the CV when pairing light and heavy. I will take a look at the source code and let you know ASAP.

Best,

Fengchao

**Comment by EsbenSv** [comment]
Hi Fengchao @fcyu 

I was wondering whether there is any update on this issue? Alternatively, I can downgrade to an earlier IonQuant version where the issue is not present?

Best,
Esben

**Comment by fcyu** [comment]
Hi Esben,

Sorry for the late response. I just got back from a conference last week.

I have tried to fix the bug. Could you download the pre-released version from https://www.dropbox.com/t/4Kx6VRox2jcfE5Gq , and see if the issue is resolved?

Thanks again for the bug reporting and help.

Best,

Fengchao

**Comment by EsbenSv** [comment]
Hi Fengchao,

A quick look shows that the problem is fixed! Thank you for the quick update, highly appreciated!

Best,
Esben
