### ISSUE TITLE
Conversion from mgf to mzML

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1288]
Is it possible to convert mgf files to mzML format by using MSConvert? If it is possible, is it necessary to select specific options in the Filters section, depending on specific data characteristics, such as the data type (DIA or DDA data) or the specific mass spectrometer that was used? Thank you!

Best regards,
Roberto

**Comment by fcyu** [comment]
It is possible but it won't be very helpful because the mzML won't have more information than the MGF, which still misses MS1 spectra, etc.

Best,

Fengchao

**Comment by RobAlbn** [comment]
Thank you!
