### ISSUE TITLE
could not create Java virtual machine

### ISSUE THREAD

**Issue by muratore1** [Nesvilab/FragPipe#129]
# Hi, I am a new user of Fragpipe. I cannot complete the search because I am having an issue allocating enough memory. My computer has 16GB of RAM. I have tried allocating 10, 8, and 4 GB of RAM in the gui and the error persists. I am not running other applications on the system besides the OS.

* **I'm submitting a:**
  - [ x] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
The search cannot be completed and I get an error message of the following:

MsFragger [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
java -jar -Dfile.encoding=UTF-8 -Xmx10G C:\Users\pjohn\Fragpipe2\MSFragger-20190628.jar C:\Users\pjohn\Fragpipe2\CurrentResults\fragger.params C:\Users\pjohn\Fragpipe2\KM190801_MA1.mzML
**Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx10G
The specified size exceeds the maximum representable size.
Process 'MsFragger' finished, exit code: 1**

## System info

You can find that printed on the _Config_ tab.
- OS and version: Windows 10, MSFragger 20190628
- Java version: 1.8.0_221
Philosopher v1.5.1
Python 3.7.4
----

### Genral proteomics experiment description
e.g. Trichomonas vaginalis exosomes, Trypsin and LysC

...

### Input data files
** one mzml file, 0.2 GB. I only tried to run one file initially to see if I had everything working correctly. I have 6 files in total (3 biological replicates of two experimental conditions)

### Sequence database
Trichomonas vaginalis. I used philosopher to retrieve the database from uniprot and add the decoys. There are about 50,000 proteins. I have to use the non-reviewed database because few Trichomonas proteins have been reviewed. 

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_221, Java HotSpot(TM) Client VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190628
Philosopher version v1.5.1 (build 1566924968)


LCMS files:
  Experiment/Group: 
  - C:\Users\pjohn\Fragpipe2\KM190801_MA1.mzML

12 commands to execute:
Workspace [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe workspace --clean
Workspace [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe workspace --init
MsFragger [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
java -jar -Dfile.encoding=UTF-8 -Xmx10G C:\Users\pjohn\Fragpipe2\MSFragger-20190628.jar C:\Users\pjohn\Fragpipe2\CurrentResults\fragger.params C:\Users\pjohn\Fragpipe2\KM190801_MA1.mzML
MsFragger
java -cp C:\Users\pjohn\Fragpipe2\FragPipe.exe umich.msfragger.util.FileMove C:\Users\pjohn\Fragpipe2\KM190801_MA1.pepXML C:\Users\pjohn\Fragpipe2\CurrentResults\KM190801_MA1.pepXML
MsFragger
java -cp C:\Users\pjohn\Fragpipe2\FragPipe.exe umich.msfragger.util.FileMove --no-err C:\Users\pjohn\Fragpipe2\KM190801_MA1.tsv C:\Users\pjohn\Fragpipe2\CurrentResults\KM190801_MA1.tsv
Crystal-C [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
java -Xmx10G -cp "C:\Users\pjohn\AppData\Local\Temp\fragpipe\common-deps-1.0.3.jar;C:\Users\pjohn\AppData\Local\Temp\fragpipe\original-CrystalC-1.0.5.jar" Main C:\Users\pjohn\Fragpipe2\CurrentResults\crystalc-0-KM190801_MA1.pepXML.params C:\Users\pjohn\Fragpipe2\CurrentResults\KM190801_MA1.pepXML
ReportDbAnnotate [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe database --annotate C:\Users\pjohn\Fragpipe2\2019-08-29-td-UP000001542.fas --prefix rev_
PeptideProphet [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy rev_ --database C:\Users\pjohn\Fragpipe2\2019-08-29-td-UP000001542.fas --combine KM190801_MA1_c.pepXML
ProteinProphet [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe proteinprophet --maxppmdiff 2000000 C:\Users\pjohn\Fragpipe2\CurrentResults\interact.pep.xml
ReportFilter [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\Users\pjohn\Fragpipe2\CurrentResults --protxml C:\Users\pjohn\Fragpipe2\CurrentResults\interact.prot.xml
ReportReport [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe report
Workspace [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe workspace --clean
INFO[14:32:56] Executing Workspace  v1.5.1                  
INFO[14:32:56] Removing workspace                           
INFO[14:32:56] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
C:\Users\pjohn\Fragpipe2\philosopher.exe workspace --init
INFO[14:32:57] Executing Workspace  v1.5.1                  
INFO[14:32:57] Creating workspace                           
INFO[14:32:57] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\Users\pjohn\Fragpipe2\CurrentResults]
java -jar -Dfile.encoding=UTF-8 -Xmx10G C:\Users\pjohn\Fragpipe2\MSFragger-20190628.jar C:\Users\pjohn\Fragpipe2\CurrentResults\fragger.params C:\Users\pjohn\Fragpipe2\KM190801_MA1.mzML
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx10G
The specified size exceeds the maximum representable size.
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp C:\Users\pjohn\Fragpipe2\FragPipe.exe umich.msfragger.util.FileMove C:\Users\pjohn\Fragpipe2\KM190801_MA1.pepXML C:\Users\pjohn\Fragpipe2\CurrentResults\KM190801_MA1.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 10/13 processes (3 already finished)
Processing interrupted, stopping MsFragger

~~~~~~~~~~~~~~~~~~~~
Stopping 0/0 processes (0 already finished)



[log-fragpipe-run-at_2019-08-29_14-33-07.txt](https://github.com/Nesvilab/FragPipe/files/3557464/log-fragpipe-run-at_2019-08-29_14-33-07.txt)

**Comment by muratore1** [comment]
[log-fragpipe-run-at_2019-08-29_14-33-07.txt](https://github.com/Nesvilab/FragPipe/files/3557480/log-fragpipe-run-at_2019-08-29_14-33-07.txt)

**Comment by muratore1** [comment]
[fragger_params.txt](https://github.com/Nesvilab/FragPipe/files/3557482/fragger_params.txt)

**Comment by muratore1** [comment]
I also tried using the command line, using the tutorial here: [https://github.com/Nesvilab/philosopher/wiki/Processing-Filtering-and-Analyzing-Open-Search-Results-Using-Philosopher](url)

and I am still getting a problem with allocating Java. Below is the error message I get: 


C:\Users\pjohn\Fragpipe2\KM190828>java -jar Xmx10G bin/MSFragger-20190628.jar params/fragger.params *mzML
Error: Unable to access jarfile Xmx10G

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe/MSFragger. Could you please help to check if you are using the 64-bit JVM?

Thanks,

Fengchao

**Comment by muratore1** [comment]
Thank you. I uninstalled my current Java and re-installed the 64 bit version. If other users have this issue, here is the link to download the correct Java. [https://www.java.com/en/download/manual.jsp](url) 
Choose windows offline 64 bit. 

The Java issue is now fixed- but I am getting a new error message! 
[log_2019-08-30_09-32-07.txt](https://github.com/Nesvilab/FragPipe/files/3560747/log_2019-08-30_09-32-07.txt)

It says no PSM were found in data set. I have previously analyzed this data in MaxQuant- and was able to match peptides to my database.

Thanks!

**Comment by fcyu** [comment]
Looks like your data not has a good enough quality. Here is my random guess: is your data from high resolution MS2 instrument?

Best,

Fengchao

**Comment by muratore1** [comment]
Data is from Q-Exactive Plus, Orbitrap

**Comment by fcyu** [comment]
There are two mass analyzers in all orbitrap instruments: linear trap (ITMS) and orbitrap (FTMS). You may know what your data is by checking the raw file or the MaxQuant result ("Mass analyzer" column in the "msmsScans.txt" table.

Best,

Fengchao

**Comment by muratore1** [comment]
The mass analyzer column says FTMS. 

Is it possible that the dataset is not complex enough? I am only expecting ~500 protein groups, as this is an exosome sample, not a whole cell lysate. 

I want to get open searches going, because in an experiment I have coming up, I would like to look for some peptides with some modifications that I am unsure of the mass. We have a drug that adducts to Tvag proteins, but are not sure what the mechanism is

**Comment by fcyu** [comment]
I am not sure what's going on. Could you please send me your MaxQuant parameters (mqpar.xml)?

Thanks,

Fengchao

**Comment by muratore1** [comment]
[parameters.txt](https://github.com/Nesvilab/FragPipe/files/3561120/parameters.txt)

When I ran in MaxQuant, I had 6 raw files (3 biological replicates of two conditions). I only tested one of the files in Fragpipe.

Thanks!

**Comment by fcyu** [comment]
I need the mqpar.xml file so that I can know the enzyme settings. Also, looks like you used "trichomonasfasta.fasta" in MaxQuant and "2019-08-29-td-UP000001542.fas" in FragPipe. Do they have the same target proteins?

Best,

Fengchao

**Comment by muratore1** [comment]
It won't let me attach the .xml file. The enzyme settings in MaxQuant were trypsin and LysC. I digested with both. In Fragpipe, I just selected Trypsin (there was only an option to pick 1?)

Yes- the two databases have the same target proteins. The filename for fragpipe is different because I had to add the decoys to it. I used philosopher to do so. 

Thanks!
