### ISSUE TITLE
Servers for updating the modules in FragPipe

### ISSUE THREAD

**Issue by yishai99** [Nesvilab/FragPipe#1290]
Hi, we have FragPipe funning on a server that does not have completely open access to the internet. But we'd like to allow access to be able to update the different modules of Fragpipe: MSFragger, IonQuant ect. Can you provide the server information so we can open the appropriate ports?
Thanks,

Yishai

**Comment by fcyu** [comment]
Hi Yishai,

You can actually download the MSFragger, IonQuant, and Philosopher using browser on another computer, and then copy to the server. Here are the websites: 

https://msfragger.arsci.com/upgrader/
https://msfragger.arsci.com/ionquant/
https://github.com/Nesvilab/philosopher/releases/tag/v5.0.0

As to the automatic download, I think FragPipe uses the port that http is using: 80

Best,

Fengchao
