### ISSUE TITLE
PTMProphet non-matching mass error

### ISSUE THREAD

**Issue by rainearcher** [Nesvilab/FragPipe#1291]
- Describe the issue or question:

Currently running a custom DDA sample on a TMT10-phospho based workflow with multiple MSFragger modifications. I keep getting this PTMProphet error:

PTMProphet [Work dir: D:\Documents\School\_Ping_Lab\Peptide-PTM\tumorigenesis]
D:\Documents\School\_Ping_Lab\Peptide-PTM\fragpipe\tools\PTMProphet\PTMProphetParser.exe KEEPOLD STATIC EM=1 NIONS=b M:15.9949,STY:79.966331,n:42.0106,E:-18.0106,N:0.98402,P:15.9772,C:39.9949 MINPROB=0.5 MAXTHREADS=1 interact-07CPTAC_BCprospective_P_BI_20170204_BL_fA.pep.xml interact-07CPTAC_BCprospective_P_BI_20170204_BL_fA.mod.pep.xml
Please wait. PTMProphet is running. It can take a long time.
[INFO:] Using statically set 15 PPM tolerance ... 
[INFO:] Writing file interact-07CPTAC_BCprospective_P_BI_20170204_BL_fA.pep.xml.tmp.a04644 ...

[INFO:] Creating 1 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact-07CPTAC_BCprospective_P_BI_20170204_BL_fA.pep.xml ...
[WARNING:] Illegal PTM-shuffled peptide detected with non-matching mass: NEEDEGHS[167]NSSP[113]R
	Neutral Mass (from pepXML) = 1781.69
	BAD (SpectraST::Peptide) = NEEDEGHS[167]NSSP[113]R
	Neutral Computed Mass for Evaluation = 1552.53
	PPM difference = 128621
[INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
[WARNING:] Illegal PTM-shuffled peptide detected with non-matching mass: NEEDEGHSNS[167]SP[113]R
	Neutral Mass (from pepXML) = 1781.69
	BAD (SpectraST::Peptide) = NEEDEGHSNS[167]SP[113]R
	Neutral Computed Mass for Evaluation = 1552.53
	PPM difference = 128621
[INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
[WARNING:] Illegal PTM-shuffled peptide detected with non-matching mass: NEEDEGHSNSS[167]P[113]R
	Neutral Mass (from pepXML) = 1781.69
	BAD (SpectraST::Peptide) = NEEDEGHSNSS[167]P[113]R
	Neutral Computed Mass for Evaluation = 1552.53
	PPM difference = 128621
[INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
[ERROR:] Scan 6277 ... number of mod combinations doesn't match the number of peptides ... 
[INFO:] Check the precision of specified PTM masses OR Adjust 'MODPREC=' parameter and rerun ... exiting ...
Process 'PTMProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

I presume I made some mistake in specifying the mass offsets in the PTMProphet options, but I cannot figure it out. Please advise how to address this.

- Upload your log file
[log_2023-10-16_21-45-43.txt](https://github.com/Nesvilab/FragPipe/files/12924378/log_2023-10-16_21-45-43.txt)

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by anesvi** [comment]
You need to move n-term TMT from variable to fixed. If it does not help, then I don't know. You specified to many variable modifications, which is really hard for localization tools to handle

**Comment by fcyu** [comment]
Or, could you add 229.16293 on peptide N-term to PTMProphet? I think PTMProphet requires all mods used in the search.

Best,

Fengchao

**Comment by rainearcher** [comment]
> Or, could you add 229.16293 on peptide N-term to PTMProphet? I think PTMProphet requires all mods used in the search.
> 
> Best,
> 
> Fengchao

This solved the problem. Fragpipe now runs without error. Thank you
