### ISSUE TITLE
Let IonQuant ignore scans without compensation voltage info and continue the program

### ISSUE THREAD

**Issue by michaelwierer** [Nesvilab/FragPipe#1292]
Running DDA files from Ascend stops with following error. Analyses without Ionquant perform fine on these files. Could you please check?

IonQuant version IonQuant-1.9.8
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 117 GB memory
2023-10-18 07:51:06 [INFO] - Collecting variable modifications from all psm.tsv files...
2023-10-18 07:51:06 [INFO] - Loading and indexing all psm.tsv files...
2023-10-18 07:51:06 [INFO] - Collecting all compensation voltages if applicable...
2023-10-18 07:51:25 [INFO] - There are in total 1 compensation voltages: -45
2023-10-18 07:51:25 [ERROR] - Could not get the compensation voltage from scan 20230925_ASC1_NEO1_PRI_X1132_P234_R908_60min_uPAC110cm_PTM_59ms_FAIMSmin45_S1.02908.02908.3.
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2023-10-18_07-51-26.txt](https://github.com/Nesvilab/FragPipe/files/12995211/log_2023-10-18_07-51-26.txt)

**Comment by fcyu** [comment]
Some of your scans seem not having compensation voltage information. Could you double check your data?

Also, I see that there are some errors in your settings that are not related to this error:

1. You set the precursor mass tolerance to -20 ~20 **Da** but not ppm, which does not make any sense. You should either give a small tolerance (-20~20 ppm) for the closes search or a big tolerance (-100~500 Da) for the open search. According to your other parameters, you were doing a closed search. For example, you set `isotope error` to `0/1/2` and enabled IonQuant.
2. The MSFragger precursor mass mode was set to `corrected` this is for open search.
3. And you enabled `localize_delta_mass` which is also only for open search
4. You used PeptideProphet and PTM-Shepherd.

It seems that you mixed the LFQ-MBR and the Open workflow. Please use the built-in workflow and do not change the parameters unless you understand it. In case you don't know, IonQuant does not support open search.

Best,

Fengchao

**Comment by michaelwierer** [comment]
Hi Fengchao

Thanks for getting back to me so quickly.

I will check the scans, but as this problem cannot be easily corrected (e.g. the data comes like that from the Ascend), would there be a way to ignore that error, or just flag, instead of exiting the analysis?

Thanks for your comments on the settings. I was running an open search before, and then switched to a closed one. I actually thought I had loded the default settings, so it is indeed puzzling to see that Da was not changed to ppm. Thanks for realizing!

Best
Michael


From: Fengchao ***@***.***>
Reply to: Nesvilab/FragPipe ***@***.***>
Date: Wednesday, 18. October 2023 at 15:27
To: Nesvilab/FragPipe ***@***.***>
Cc: Michael Wierer ***@***.***>, Author ***@***.***>
Subject: Re: [Nesvilab/FragPipe] Ionquant error with FAIMS-Ascend data (Issue #1292)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


Some of your scans seem not having compensation voltage information. Could you double check your data?

Also, I see that there are some errors in your settings that are not related to this error:

  1.  You set the precursor mass tolerance to -20 20 Da but not ppm, which does not make any sense. You should either give a small tolerance (-2020 ppm) for the closes search or a big tolerance (-100~500 Da) for the open search. According to your other parameters, you were doing a closed search. For example, you set isotope error to 0/1/2 and enabled IonQuant.
  2.  The MSFragger precursor mass mode was set to corrected this is for open search.
  3.  And you enabled localize_delta_mass which is also only for open search
  4.  You used PeptideProphet and PTM-Shepherd.

It seems that you mixed the LFQ-MBR and the Open workflow. Please use the built-in workflow and do not change the parameters unless you understand it. In case you don't know, IonQuant does not support open search.

Best,

Fengchao

**Comment by fcyu** [comment]
> I will check the scans, but as this problem cannot be easily corrected (e.g. the data comes like that from the Ascend), would there be a way to ignore that error, or just flag, instead of exiting the analysis?

Yes, I think it might be a good idea to ignore those scans and let the program continue, rather than crash. I will change IonQuant and let you know when it is ready.

Best,

Fengchao

**Comment by fcyu** [comment]
OK, I took a closer look at the log file. There are compensation voltage in the raw files but not in the `psm.tsv`. I am not sure what caused it, but if you want me to take a look at your data, here is the link to upload the raw files, fasta file, and the workflow file: https://www.dropbox.com/request/vHsk1I5lMg6YsQC5OPmq

Best,

Fengchao

**Comment by fcyu** [comment]
No response.

**Comment by lxiiaanog** [comment]
Hi Fengchao,

I have encountered the same problem as what was described above: 

IonQuant version IonQuant-1.10.27
Batmass-IO version 1.33.4
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
System OS: Windows 11, Architecture: AMD64
Java Info: 23.0.1, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 109 GB memory
2025-05-02 21:04:25 [INFO] - Collecting variable modifications from all psm.tsv files...
2025-05-02 21:04:25 [INFO] - Loading and indexing all psm.tsv files...
2025-05-02 21:04:26 [INFO] - Collecting all compensation voltages if applicable...
2025-05-02 21:04:46 [INFO] - There are in total 2 compensation voltages: -45, 0
2025-05-02 21:04:46 [ERROR] - Could not get the compensation voltage from scan Astral_SCB_20250502_10pg-BG_TMT.06841.06841.2 in D:\liangx\analysis\20250502\Astral_spike-TMT-dda_test-10pg\10pg\psm.tsv
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 3 remaining tasks

I wonder if there has been any update on IonQuant ever since?

Thanks.

Li

**Comment by fcyu** [comment]
There are runs without FAIMS. Please double check your data.

Best,

Fengchao
