### ISSUE TITLE
Error when trying to analyze DIA data with FragPipe

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1294]
I am trying to use FragPipe to analyze DIA data that were obtained with a Waters Synapt G2-Si mass spectrometer and with ion mobility acquisition. I have mgf files, which I converted to mzML format by using MSConvert and by selecting the option "Combine ion mobility scans". Then, I used FragPipe. In the "Workflow" section, I selected the workflow "DIA_SpecLib_Quant" and the MS data type "IM-MS (ion mobility, timsTOF only)". Then, I loaded the mzML files and I specified "DIA" as their data type in the "Data type" column. After specifying the FASTA sequence database and the output directory, I clicked "Run", but I get the following error:  "There is an error in extracting isolation windows: Could not get isolation window info from scan 379.". Am I doing something incorrectly? Do you have any idea or suggestion to solve the issue? Thank you very much!

**Comment by anesvi** [comment]
I am sorry to say we have never tested FragPipe with Waters data, and this is not something we are likely to be able to support.

**Comment by RobAlbn** [comment]
Thank you! Could FragPipe work if I convert the raw data, not the mgf files, to mzML ? Is there a probability, even if low, that it will work in this way?

**Comment by fcyu** [comment]
Since MGF does not have all information, such as MS1 peaks, converting it to mzML format does not help. Maybe you can convert the vendor's format to mzML and try again.

Best,

Fengchao

**Comment by RobAlbn** [comment]
Thank you very much!
