### ISSUE TITLE
defining protease combination in Fragpipe

### ISSUE THREAD

**Issue by talpa25** [Nesvilab/FragPipe#130]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

* **My MSFragger use case:**
  - [x] _Closed_ search (standard small precursor mass tolerance)
  - [x] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
Dear developer,

i have done a consequtive protease digestion of Trypsin and Glu-C, How do i specify the cutting sites (KRE) in the Fragpipe Box?

Best
Roman

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"

...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe and MSFragger. I think you can set the parameter like

![image](https://user-images.githubusercontent.com/6926299/64021335-b135a700-cb01-11e9-9b77-a511d5f453e5.png)

In order to let PeptideProphet recognize the enzyme (it only supported limited enzymes), you need to fill "Trypsin" in the "Enzyme name" entry.

Best,

Fengchao

**Comment by hayse1** [comment]
Hi Roman,
For best results, the enzyme name and cleavage rules used in your search should match those used by PeptideProphet. We recommend that you specify "trypsin_gluc" and the corresponding rules (cut DEKR, no cuts P) as shown in the list at the bottom of [this page](https://github.com/Nesvilab/philosopher/wiki/PeptideProphet).

Regards,
Sarah
