### ISSUE TITLE
The similarities and differences between the combined_peptide.tsv file and the separate experiment peptide.tsv file.

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1302]
Hello，dear author！
Thank  you  for developing such a great tool.
During the usage, I encountered some issues and I hope to receive your assistance. 
I ran msfragger on the time-of-flight mass spectrometry data of two samples, Adjacent and Tumor, and it completed successfully. However, during the analysis, I found inconsistencies between the Intensity values in the separate experiment peptide.tsv and the combined_peptide.tsv, as shown in the figure. I am curious why one sample is consistent while the other is inconsistent?

I hope to receive your reply. Thank you.
Best wishes!!!

amingson

![image](https://github.com/Nesvilab/MSFragger/assets/102129816/497c5678-d485-4ef3-9f28-aac712d62eb7)
![image](https://github.com/Nesvilab/MSFragger/assets/102129816/d78ac1f5-6c6e-4eb3-b757-997ddc7ab66c)
![image](https://github.com/Nesvilab/MSFragger/assets/102129816/4ad25bd6-f0a8-4538-b5dc-15d2d48f6b88)

**Comment by fcyu** [comment]
The intensities in peptide.tsv are not normalized but those in combined_peptide.tsv are normalized.

Best,

Fengchao

**Comment by amingson** [comment]
> The intensities in peptide.tsv are not normalized but those in combined_peptide.tsv are normalized.
> 
> Best,
> 
> Fengchao

Why is the intensity of one sample consistent with the normalized intensity?

**Comment by fcyu** [comment]
It is due to the normalization algorithm developed in IonQuant (the tool performing label-free quantification): https://www.mcponline.org/article/S1535-9476(20)35104-5/fulltext#:~:text=we%20developed%20a%20piecewise%20normalization%20algorithm%20in%20IonQuant

Basically, it picks one run as the reference run and normalizes the other run's intensities.

Best,

Fengchao

**Comment by amingson** [comment]
> It is due to the normalization algorithm developed in IonQuant (the tool performing label-free quantification): https://www.mcponline.org/article/S1535-9476(20)35104-5/fulltext#:~:text=we%20developed%20a%20piecewise%20normalization%20algorithm%20in%20IonQuant
> 
> Basically, it picks one run as the reference run and normalizes the other run's intensities.
> 
> Best,
> 
> Fengchao

I get！ I have one more question - if I want to perform differential analysis on these two group, should I use this normalized data?

**Comment by fcyu** [comment]
It depends on if most of the protein intensities between two samples are unchanged. If yes, you can enable the normalization, if not, you need to disable it (in the `Quant (MS1)` tab).

Best,

Fengchao

**Comment by amingson** [comment]
> It depends on if most of the protein intensities between two samples are unchanged. If yes, you can enable the normalization, if not, you need to disable it (in the `Quant (MS1)` tab).
> 
> Best,
> 
> Fengchao

Okay, I understand. Thank you for your helpful assistance.

Best，

amingson
