### ISSUE TITLE
FragPipe V19.1 is not compatible with Philosopher 5.0.0

### ISSUE THREAD

**Issue by kebincao** [Nesvilab/FragPipe#1308]
Hello,

I am currently running FragPipe V19.1 (MSFragger  3.8, & Philosopher 5.0.0) and I am having an early termination of my workflow. I've highlighted an excerpt of the report below. 

Thank you for your help in advanced.

Process 'PhilosopherFilter' finished, exit code: 0
PhilosopherReport [Work dir: E:\Mass_Spec\Triplicate_EV_idp3_cons1\consMP1_3]
C:\Users\kevin\Downloads\FragPipe-19.1\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe report --removecontam
INFO[19:17:24] Executing Report  v5.0.0                     
INFO[19:17:24] Creating reports                             
ERRO[19:17:24] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. 
Process 'PhilosopherReport' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
[log_2023-10-25_19-17-24.txt](https://github.com/Nesvilab/FragPipe/files/13172401/log_2023-10-25_19-17-24.txt)

Cancelling 21 remaining tasks

**Comment by fcyu** [comment]
Upgrading FragPipe to the latest version will solve this problem.

Best,

Fengchao
