### ISSUE TITLE
Spectral Library building workflow using .d files error

### ISSUE THREAD

**Issue by ajay16bharadwaj** [Nesvilab/FragPipe#1309]
- Describe the issue or question:

Spectral Library building workflow using .d files fails with "ERROR - There are only DIA-Quant or diaPASEF runs, but there is no spectral library provided to the DIA-NN quant."

I need to build a library with TIMSTOF .d files

I've tried running it with DIA_Speclib_Quant and DIA_DIA-Umpire_SpecLib_Quant workflows 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[fragpipe.log.txt](https://github.com/Nesvilab/FragPipe/files/13183591/fragpipe.log.txt)

[DIA_DIA-Umpire_SpecLib_Quant.workflow.txt](https://github.com/Nesvilab/FragPipe/files/13183604/DIA_DIA-Umpire_SpecLib_Quant.workflow.txt)
[DIA_SpecLib_Quant.workflow.txt](https://github.com/Nesvilab/FragPipe/files/13183605/DIA_SpecLib_Quant.workflow.txt)
[single_cell_test.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/13183606/single_cell_test.fp-manifest.txt)

**Comment by fcyu** [comment]
If your input **dda**PASEF or **dia**PASEF? FragPipe currently only support using **dda**PASEF to build a spectral library.

Best,

Fengchao

**Comment by ajay16bharadwaj** [comment]
I was using diaPASEF data. Thank you for the clarification.
