### ISSUE TITLE
PTM Prophet error crashes run

### ISSUE THREAD

**Issue by dooorsa** [Nesvilab/FragPipe#1310]
I am running the labile_ADP-ribosylation workflow on .raw data and fragpipe crashes at this step:

[INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
[WARNING:] Illegal PTM-shuffled peptide detected with non-matching mass: SSSSASK[669]
	Neutral Mass (from pepXML) = 1235.37
	BAD (SpectraST::Peptide) = SSSSASK[669]
	Neutral Computed Mass for Evaluation = 1193.36
	PPM difference = 34006.4
[INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
[ERROR:] Scan 6247 ... number of mod combinations doesn't match the number of peptides ... 
[INFO:] Check the precision of specified PTM masses OR Adjust 'MODPREC=' parameter and rerun ... exiting ...
Process 'PTMProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2023-10-27_13-55-52.txt](https://github.com/Nesvilab/FragPipe/files/13188623/log_2023-10-27_13-55-52.txt)

**Comment by fcyu** [comment]
For PTM-Prophet, you should specify all variable modifications used in the MSFragger search. Can you add the Oxidation and Acetylation, and try again?

Thanks,

Fengchao

**Comment by dooorsa** [comment]
Thanks for the response. We tried the following two settings and it keeps crashing:

once we tried this under Validation > PTM site localization > cmd line opts:
KEEPOLD STATIC FRAGPPMTOL=20 EM=1 SKREDTY:541.0611,M:15.9949,[^:42.0106 MINPROB=0.5 MAXTHREADS=1 interact.pep.xml interact.mod.pep.xml

and once we tried this under Validation > PTM site localization > cmd line opts:
KEEPOLD STATIC FRAGPPMTOL=20 EM=1 SKREDTY:541.0611,M:15.9949 MINPROB=0.5 MAXTHREADS=1 interact.pep.xml interact.mod.pep.xml

Any ideas?

**Comment by fcyu** [comment]
Could you try `KEEPOLD STATIC FRAGPPMTOL=20 EM=1 SKREDTY:541.0611,M:15.9949,n:42.0106 MINPROB=0.5 MAXTHREADS=1 interact.pep.xml interact.mod.pep.xml` ?

Thanks,

Fengchao

**Comment by Shinya-Watanabe** [comment]
I have the same issue unable to resolve. The error happens when searching specific PTM modifications search, like below. I used TMT11 plex. The monoisotopic mass of 156.1151 on CHK and 140.1201 on K are the PTM that I am looking for.

> KEEPOLD STATIC EM=1 NIONS=b M:15.9949,n:42.0106,CHK:156.1151,K:140.1201 MINPROB=0.5 MAXTHREADS=1 interact-01MoTrPAC_PASS1B-06_T58_PR_BI_20200224_GY_f15.pep.xml interact-01MoTrPAC_PASS1B-06_T58_PR_BI_20200224_GY_f15.mod.pep.xml



> Please wait. PTMProphet is running. It can take a long time.
> [INFO:] Using statically set 15 PPM tolerance ... 
> [INFO:] Writing file interact-01MoTrPAC_PASS1B-06_T58_PR_BI_20200224_GY_f14.pep.xml.tmp.a31788 ...
> 
> [INFO:] Creating 1 threads 
> [INFO:] Wait for threads to finish ...
> [INFO:] Reading file interact-01MoTrPAC_PASS1B-06_T58_PR_BI_20200224_GY_f14.pep.xml ...
> ​
> [INFO:] processed 1000/12405 spectrum_queries		 ​
> [INFO:] processed 2000/12405 spectrum_queries		 ​
> [INFO:] processed 3000/12405 spectrum_queries		 ​
> [INFO:] processed 4000/12405 spectrum_queries		 ​
> [INFO:] processed 5000/12405 spectrum_queries		 ​
> [INFO:] processed 6000/12405 spectrum_queries		 ​
> [INFO:] processed 7000/12405 spectrum_queries		 ​
> [INFO:] processed 8000/12405 spectrum_queries		 ​
> [INFO:] processed 9000/12405 spectrum_queries		 [WARNING:] Illegal PTM-shuffled peptide detected with non-matching mass: n[230]ITDFGLC[160]K[653]EGISDGATMK[357]TFC[160]GTPEYLAPEVLEDNDYGR
> 	Neutral Mass (from pepXML) = 5352.71
> 	BAD (SpectraST::Peptide) = ITDFGLCK
> 	Neutral Computed Mass for Evaluation = 895.447
> 	PPM difference = 832711
> [INFO:] please check your specified modification masses for precision or adjust MODPREC= parameter ...
> [ERROR:] Scan 30559 ... number of mod combinations doesn't match the number of peptides ... 
> [INFO:] Check the precision of specified PTM masses OR Adjust 'MODPREC=' parameter and rerun ... exiting ...
> Process 'PTMProphet' finished, exit code: 1
> Process returned non-zero exit code, stopping
> Processing interrupted, stopping PTMProphet
