### ISSUE TITLE
gen_con_spec_lib.py error/no library.tsv

### ISSUE THREAD

**Issue by shadmort** [Nesvilab/FragPipe#1311]
Hi FragPipers,

I am trying to do a basic analysis with the DIA_DIA-Umpire_SpecLib_Quant workflow, but I am running into trouble when I get to Spec Lib. When it is checked, I get an error as in the log attached, but when it is not checked, I get an error from DIA-NN because there is no library.tsv. Please advise.

SpecLibGen [Work dir: E:\PD_Projects\Hela_DIAvsWWA\DIA_Fragpipe9]
C:\Python311\python.exe -u C:\fragpipe\tools\speclib\gen_con_spec_lib.py C:\Databases\2023-10-27-decoys-reviewed-isoforms-contam-UP000005640.fas E:\PD_Projects\Hela_DIAvsWWA\DIA_Fragpipe9 unused E:\PD_Projects\Hela_DIAvsWWA\DIA_Fragpipe9 True unused use_easypqp noiRT;noIM 63 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',] " "--rt_lowess_fraction 0.01" keep_intermediate_files E:\PD_Projects\Hela_DIAvsWWA\DIA_Fragpipe9\filelist_speclibgen.txt
C:\Python311\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Python311\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
C:\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
File list provided
Traceback (most recent call last):
  File "C:\fragpipe\tools\speclib\gen_con_spec_lib.py", line 266, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\fragpipe\tools\speclib\gen_con_spec_lib.py", line 157, in get_bin_path_pip_CLI
    rel_loc, = [e for e in files if pathlib.Path(e).stem == bin_stem]
    ^^^^^^^^
ValueError: not enough values to unpack (expected 1, got 0)
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2023-10-27_16-08-51.txt](https://github.com/Nesvilab/FragPipe/files/13192974/log_2023-10-27_16-08-51.txt)

**Comment by fcyu** [comment]
It seems that you were using Python 3.11 but we require 3.9. 

In case you didn't know, you were using raw file format, so you need to make sure that you have the Thermo library installed, which is required by DIA-NN: https://github.com/vdemichev/DiaNN#raw-data-formats

Best,

Fengchao
