### ISSUE TITLE
Ionquant: "error in normalization ion intensities."

### ISSUE THREAD

**Issue by vikastuteja1** [Nesvilab/FragPipe#1312]
- Describe the issue or question:
Right after: "Combining experiments and estimating protein intensity..."

Received error: 
java.lang.NullPointerException: Had an error in normalization ion intensities.
	at o.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)

Log file uploaded
[log_2023-10-28_16-58-50.txt](https://github.com/Nesvilab/FragPipe/files/13196984/log_2023-10-28_16-58-50.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It seems that there were not many IDs from your data, which made the normalization failed. If you still want to analyze the data, you can disable the normalization in the "Quant (MS1)" tab.

Best.

Fengchao

**Comment by vikastuteja1** [comment]
Great - thanks.
