### ISSUE TITLE
percolator exit code -1073741819

### ISSUE THREAD

**Issue by direnardak** [Nesvilab/FragPipe#1313]
Hello,
I have an DDA phosphoproteomics data. I'm trying to analyze this data using LFQ-phospho pipeline in fragpipe. But I am gettıng thıs error:
`Percolator [Work dir: C:\Users\ardak\Desktop\proteomics\output_mzml_lfq_phospho\tALL]
C:\Users\ardak\Desktop\FragPipe\FragPipe-20.0\fragpipe\tools\percolator-306\percolator.exe --only-psms --no-terminate --post-processing-tdc --num-threads 10 --results-psms EX1_08032023_All17_6of15_r2_percolator_target_psms.tsv --decoy-results-psms EX1_08032023_All17_6of15_r2_percolator_decoy_psms.tsv --protein-decoy-pattern rev_ EX1_08032023_All17_6of15_r2_edited.pin
Process 'Percolator' finished, exit code: -1073741819
Process returned non-zero exit code, stopping
Cancelling 182 remaining tasks`

Does that mean my data is corrupted or are there any other problems? I couldn't find this code's meaning.

My log file:
[2_log_2023-10-30_16-08-03.txt](https://github.com/Nesvilab/FragPipe/files/13210329/2_log_2023-10-30_16-08-03.txt)

**Comment by fcyu** [comment]
It is a known issue: 
https://github.com/Nesvilab/FragPipe/issues/1313
https://github.com/Nesvilab/FragPipe/issues/1269
https://github.com/Nesvilab/FragPipe/issues/1270
https://github.com/Nesvilab/FragPipe/issues/1227
https://github.com/Nesvilab/FragPipe/issues/1211
https://github.com/Nesvilab/FragPipe/issues/1160

Please remove `EX1_08032023_All17_6of15_r2.mzML` and try again.

Best,

Fengchao

**Comment by direnardak** [comment]
Thank you!
