### ISSUE TITLE
fragpipe --headless philosopher

### ISSUE THREAD

**Issue by wendazhoucs** [Nesvilab/FragPipe#1319]
- Describe the issue or question:
In official document, when using "fragpipe --headless --config-philosopher" it mentioned  "specify the location of the Philosopher binary file", just wonder which binary file of Philosopher here mean? 
I installed the fragpipe on EC2. So when I go to Philosopher download page, it has "philosopher_v5.0.0_linux_amd64.zip" and "Source code(zip)". I am not sure which files should I point to the "--confi-philosopher" after I unzip these files. 

Thank you!

**Comment by fcyu** [comment]
After unzip `philosopher_v5.0.0_linux_amd64.zip`, there is an executable file called `philosopher`. You should use that one in FragPipe.

Best,

Fengchao
