### ISSUE TITLE
Philosopher post diaumpire and msfragger error

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/FragPipe#1320]
I received the following error when trying to run fragpipe with philosopher only (calibrated q1 and a subset of successfully calibrated q2 mzml files). I can upload the manifest, workflow and full log upon request. I've never seen this error before and would appreciate guidance.
Tail of log:
15:43:08,352 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:43:08,352 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/users/smburke/fragpipe_slurm/lib/fragpipe
-18.0.jar!/logback.xml]
15:43:08,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:43:08,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/users/smburke/fragpipe_slurm/lib/fragpip
e-20.0.jar!/logback.xml]
15:43:08,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/users/smburke/fragpipe_slurm/lib/fragpip
e-18.0.jar!/logback.xml]
15:43:08,373 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@77b52d12 - URL [jar:file:/users/smburke/fragpipe_slurm/lib/fragpipe-18.0.jar!/l
ogback.xml] is not of type file
15:43:08,440 |-WARN in ch.qos.logback.core.joran.action.ImplicitModelAction - Could not find parent model.
15:43:08,440 |-WARN in ch.qos.logback.core.joran.action.ImplicitModelAction -  Will not add current implicit model as subModel.
15:43:08,441 |-ERROR in ch.qos.logback.classic.joran.JoranConfigurator@2d554825 - Could not find valid configuration instructions. Exiting.

Fixing pepxml: /fastscratch/myscratch/smburke/BSI_Restart/MSFragger_OpenSearch_restart/interact.pep.xml
Writing output to: /fastscratch/myscratch/smburke/BSI_Restart/MSFragger_OpenSearch_restart/interact.pep.xml6521476751273579168.temp-rewrite
Didn't find correct mapping for raw file path in pepxml: /fastscratch/myscratch/smburke/BSI_Restart/MSFragger_OpenSearch_restart/JS-CS-220114_GroopmanJ_JS_
PAA_1_P1_d0_Q1Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Can you share the log file? You need to zip and upload it here https://github.com/Nesvilab/FragPipe/issues/1320

Best,

Fengchao

**Comment by mremachine1** [comment]
Hey Fengchao, the log is (slurm_out), I've also included the manifest, workflow and shell script used to run fragpipe
[log_manifest_workflow_and_fedora_command.zip](https://github.com/Nesvilab/FragPipe/files/13275776/log_manifest_workflow_and_fedora_command.zip)

**Comment by fcyu** [comment]
Can you use the `*_Q1.mzML` and `*_Q2.mzML` files as input and try again? It seems that the `*_Q1_calibated.mzML` files broke the workflow.

Best,

Fengchao

**Comment by jossmi** [comment]
We are trying to restart a workflow at the point of PeptideProphet, using search results from MSFragger. We would like to use the mass calibrations from MSFragger, those will be missing if we don't use the "_calibrated.mzML" files, correct? Can we just re-name them by eliminating the "_calibrated" tag?

**Comment by mremachine1** [comment]
Hello Fengchao,
I renamed the calibrated mzML files and mzXML files to lose the "_calibrated" suffix. It got further along but errored out on parsing the interact.pep.xml on the peptide prophet filter step. I've attached the log, manifest and workflow below. Any advice?
[log_manifest_and_workflow.zip](https://github.com/Nesvilab/FragPipe/files/13284599/log_manifest_and_workflow.zip)

**Comment by fcyu** [comment]
There are temp files from the previous crashed job, which crashed the current job. Could you delete all files with the pattern `interact.pep.xml*.temp-rewrite` and try again?

Thanks,

Fengchao

**Comment by mremachine1** [comment]
hey Fengchao,
That worked. Thanks
