### ISSUE TITLE
Different parameters result in different results

### ISSUE THREAD

**Issue by mcburke-msdc** [Nesvilab/FragPipe#1322]
- The same raw data has been searched using semi-selective and non-selective enzyme cleavage rules.  There are multiple cases where the same scan number was assigned to the same sequence in both searches; however, the num_matched_ions and hyperscore are higher for the non-selective search.  I am a bit puzzled by this as the m/s values in the query and the theoretical fragment ions are the same for both cases.  I am happy to share any data files.  Thank you in advance.

**Comment by fcyu** [comment]
I guess the parameters such as `use top N peaks` and `min ratio` are different. Could you share both log files?

Thanks,

Fengchao

**Comment by mcburke-msdc** [comment]
Thank you for your assistance.  I've attached the log files from the selective ("Sel_FragPipe0.log") and non-selective ("NonSel_FragPipe0.log") searches.

Please let me know if you have any other questions.

Appreciatively,
Meghan

**Comment by mcburke-msdc** [comment]
Uploading the log files again.  Please let me know if you have any trouble.

[NonSel_FragPipe0.log](https://github.com/Nesvilab/FragPipe/files/13282984/NonSel_FragPipe0.log)
[Sel_FragPipe0.log](https://github.com/Nesvilab/FragPipe/files/13282988/Sel_FragPipe0.log)

**Comment by fcyu** [comment]
Just as what I guessed, the following are the parameters that made the differences:

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/32577593-a555-4c95-b129-fed8d97d6547)
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/a34f6b7e-9830-4fc0-aae7-d18ebf04265e)

Best,

Fengchao

**Comment by mcburke-msdc** [comment]
Thank you for your prompt responses, Fengchao and Dan.  It is, indeed, the parameter optimization that caused the different settings.  May I ask if it's possible to write to the output file exactly which ions were matched and counted in the "num_matched_ions" field?

**Comment by fcyu** [comment]
We can let MSFragger "re-match" the ions after the database searching (just like what we do for the spectral library building), but it might not be exactly the same as those used in the database searching since it is infeasible to keep track of the ions used in the database search.

Best,

Fengchao
