### ISSUE TITLE
Philosopher Abacus does not support TMT-6

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/FragPipe#1324]
- Describe the issue or question:
Good day, I am trying to run a TMT workflow on Fragpipe but got this error. Unfortunately, new to handling labeled data in Fragpipe, therefore unsure how to fix this. Any suggestions for this final error would be helpful.

As well as guidance on how the annotation file should look for the TMT-integrator step. From online I see that column 1 is the channels and column 2 then the sample names; but what exactly would sample names refer to?  (I'll attach the annotation file I used).

- Upload your log file
[log_2023-09-23_13-10-47.txt](https://github.com/Nesvilab/FragPipe/files/13299890/log_2023-09-23_13-10-47.txt)
and here is the annotation file I used:
[T131&T130_annotation.txt](https://github.com/Nesvilab/FragPipe/files/13299895/T131.T130_annotation.txt)

Kind regards
Melissa

**Comment by fcyu** [comment]
Hi Melissa,

It seems that Philosopher Abacus doesn't support TMT-6. But it is ok because you don't need to enable the "generate protein-level summary" in the "FDR filter and report" panel. Can you load one of the TMT built-in workflow, adjust essential parameters, and try again?

> As well as guidance on how the annotation file should look for the TMT-integrator step. From online I see that column 1 is the channels and column 2 then the sample names; but what exactly would sample names refer to? (I'll attach the annotation file I used).

Same names can be anything you want to name your sample.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Hi Fengchao, 

Thank you for the quick response. I'll quickly try that. 

Best,
Melissa

**Comment by MelissaVorster** [comment]
It unfortunately, gave the same error after I deselected the "generate protein-level summary" but kept the generate MSStats files option. Should this whole panel be deselected for TMT?

[log_2023-11-08_20-45-16.txt](https://github.com/Nesvilab/FragPipe/files/13300308/log_2023-11-08_20-45-16.txt)

**Comment by fcyu** [comment]
Right, you should not enable MSstats as well. It will enable Philosopher Abacus which crashes with TMT-6.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Ok, thank you. I am rerunning it now again with that in mind.

How would one then use the output from this workflow in MSStats downstream if the reports are not generated?

**Comment by fcyu** [comment]
If Philosopher Abacus crashed with TMT-6, then, MSStats output is not supported with this setting.

**Comment by MelissaVorster** [comment]
hmm, I see.

Do you have any other package suggestions in the place of MSStats?

**Comment by fcyu** [comment]
No

**Comment by fcyu** [comment]
Since TMT-Integrator inside FragPipe can do a similar job, I actually don't see any reasons to run MSstats unless you have some requirements specific for MSstats.

**Comment by MelissaVorster** [comment]
I see. It will be the first time I will be using TMT-Integrator. Therefore unfamiliar with the output. Do you perhaps have any resource that explains the TMT-Integrator output?

**Comment by fcyu** [comment]
https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html
https://fragpipe.nesvilab.org/docs/tutorial_tmt.html
https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html

**Comment by MelissaVorster** [comment]
Brilliant, thank you for those resources.

Unfortunately the run without the FDR filter and reports option checked, still gave the same error. Log file attached. Do you perhaps have any other advice?
[log_2023-11-08_23-21-21.txt](https://github.com/Nesvilab/FragPipe/files/13304313/log_2023-11-08_23-21-21.txt)

**Comment by fcyu** [comment]
I am not sure if there are any miscommunications. You should UNCHECK "generate MSstats files" but KEEP the "generate reports" enables. Like the following screenshot
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/1cdd2edc-ba71-4068-b8ab-49069f5ad0c3)

Please CHECK "generate reports", and then UNCHECK "generate MSstats files".

What you did make the things worse: you still check "generate MSstats files" but uncheck the "generate reports".
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/dd015a04-a4fa-4b57-9ec0-d1ebb9461564)

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Yes this is clear, thank you.
