### ISSUE TITLE
Do FDR Filter and Report settings influence PSMs considered in Spectral Library Generation?

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#1325]
- Describe the issue or question:
I was wondering whether the --picked or --sequential flags would impact the PSMs that are read into the EasyPQP module for spectral library generation? 

Related to this, if my only goal was spectral library generation with DDA data, and no quantification required, which workflow do you suggest?  So far, I have been using the DIA_SpecLib_Quant workflow, which using the --picked flag. In this case, FragPipe ignores DIA-NN because there are no DIA-quant files.

Thanks,
Todd

**Comment by fcyu** [comment]
Yes, the flags in the "FDR filter and report" panel control how the PSMs are filtered and passed to EasyPQP. If running DIA-NN, DIA-NN will have another layer of FDR filter.

And `DIA_SpecLib_Quant` is the correct workflow to use.

Best,

Fengchao

**Comment by enonimos** [comment]
Thank you Fengchao. A quick follow-up question regarding EasyPQP.  As far as I could determine, EasyPQP library.tsv files are not natively supported to build a Skyline library (no PSM scoring threshold?).  If this is true, then would the interact*.xml files be the best alternative?  What probability score threshold would I select to generate a Skyline library that most closely matches the EasyPQP library?  I was considering using the PSM threshold after the 2D FDR estimation.  In the example below, this would be 0.70

![image](https://github.com/Nesvilab/FragPipe/assets/42681821/d558e3d9-5027-4309-9353-ece017fff901)

**Comment by fcyu** [comment]
Yes, you can import interact.pep.xml files. We have a tutorial here: https://fragpipe.nesvilab.org/docs/tutorial_skyline.html, including how to determine the threshold.

Best,

Fengchao

**Comment by enonimos** [comment]
Excellent, thank you for the link out.
