### ISSUE TITLE
Generate combined file in long data format

### ISSUE THREAD

**Issue by Xindong-Sun** [Nesvilab/FragPipe#1327]
Hi, 

I am using MSFragger for glycopeptides identification and thanks so much for prividing such an amazing tool. May I kindly ask if there is an option to generate the combined file in long data format (for different experiments)? This might make the downstream analysis a bit easier. 

Thanks a lot.

**Comment by fcyu** [comment]
We have the MSstats.csv output which might be help. If it is not helpful to you, then we don't have any other options.

Best,

Fengchao
