### ISSUE TITLE
DIA-NN error

### ISSUE THREAD

**Issue by JesusCastano01** [Nesvilab/FragPipe#1328]
- Describe the issue or question:
Hi,

I've been trying to analyze DIA data using the 'DIA_Spec_Lib' workflow, which includes quantification using DIA-NN. However, something went wrong at the DIA_NN step, and the software couldn't complete this step.

This is what the console says at the end of the process:

DIA-NN [Work dir: D:\Postdoc_UMontreal\40ADT\DIA\MSFragger2]
D:\FragPipe-jre-20.0\fragpipe\tools\diann\1.8.2_beta_8\win\dia-nn-plotter.exe diann-output\diann-output.stats.tsv diann-output\diann-output.tsv diann-output\diann-output.pdf
[29312] Failed to execute script dia-nn-plotter
Traceback (most recent call last):
  File "dia-nn-plotter.py", line 347, in <module>
  File "dia-nn-plotter.py", line 179, in report
  File "site-packages\pandas\core\indexes\base.py", line 1520, in droplevel
ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.
Generating report. Stats, main report, output file: diann-output\diann-output.stats.tsv, diann-output\diann-output.tsv, diann-output\diann-output.pdf
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2 remaining tasks



The output file says that the program couldn't find MS2 spectra in the DIA files, which makes no sense since the raw data was identified as DIA. I'm not quite sure what I can do, and I'd appreciate any suggestions. Please, find attached the output.log file from DIA_NN.

Thanks,
Jesus
[diann-output.log.txt](https://github.com/Nesvilab/FragPipe/files/13320844/diann-output.log.txt)
[log_2023-11-09_18-02-25.txt](https://github.com/Nesvilab/FragPipe/files/13320858/log_2023-11-09_18-02-25.txt)



- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
To let DIA-NN process raw format, you need to install [Thermo MS File Reader](https://thermo.flexnetoperations.com/control/thmo/login?nextURL=%2Fcontrol%2Fthmo%2Fdownload%3Felement%3D6306677) as descripted in https://github.com/vdemichev/DiaNN#raw-data-formats

Best,

Fengchao

**Comment by JesusCastano01** [comment]
Thanks, it worked when I converted the RAW files into mzML files. However, FragPipe Analyst is failing to produce any plots with the output files. Not sure, if there is a possible solution to this.
Thanks,
Jesus

![image](https://github.com/Nesvilab/FragPipe/assets/139022774/e9e69360-6868-4afa-96f0-79cdc02d09a4)
[diann-output.log.txt](https://github.com/Nesvilab/FragPipe/files/13322441/diann-output.log.txt)

**Comment by fcyu** [comment]
@hsiaoyi0504 , can you take a look?

Thanks,

Fengchao

**Comment by hsiaoyi0504** [comment]
@JesusCastano01 Could you share me your input files with me? It's a little hard to guess what's going up based on the information provided. yihsiao@umich.edu

**Comment by fcyu** [comment]
No response.
