### ISSUE TITLE
loading Bruker tdf formated data

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/FragPipe#133]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"

...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```
In the FragPipe GUI one needs to select the path to the LC-MS files. In the case of Bruker tdf data should the path point to the d folder, or the ```analysis.tdf``` file or the ```analysis.tdf_bin``` file? Here is a typical d folder listing:

```
 Directory of D:\Data\tobiasko_20190703\20190703_005_PierceHeLa.d

09/09/2019  01:09 PM    <DIR>          .
09/09/2019  01:09 PM    <DIR>          ..
07/12/2019  04:49 PM                 0 20190703_005_PierceHeLa.d
07/12/2019  04:51 PM            97,793 20190703_005_PierceHeLa_BPC 350.0000-2200.0000 +All MS FullScan.xy
07/12/2019  04:51 PM           106,101 20190703_005_PierceHeLa_TIC +All MS FullScan.xy
07/12/2019  04:51 PM           886,951 20190703_005_PierceHeLa_TIC +All MSn.xy
07/12/2019  05:27 PM       362,455,324 20190703_005_PierceHeLa_uncalib_5.1.201.mgf
07/12/2019  04:51 PM               223 91280edb-5928-41d9-9ee9-e4eed08a7250_1.mcf
07/12/2019  04:51 PM            26,624 91280edb-5928-41d9-9ee9-e4eed08a7250_1.mcf_idx
07/12/2019  04:51 PM             9,617 analysis.0.DataAnalysis.method
07/12/2019  04:51 PM         8,586,845 analysis.0.result_c
07/12/2019  04:51 PM               110 analysis.content
07/11/2019  10:24 PM       153,452,544 analysis.tdf
07/11/2019  10:24 PM     6,336,327,680 analysis.tdf_bin
07/12/2019  04:52 PM        44,215,557 BackgroundLinePos.ami
07/12/2019  05:08 PM        61,016,517 BackgroundProfPos.ami
07/11/2019  08:44 PM           265,216 chromatography-data-pre.sqlite
07/11/2019  10:24 PM         1,861,632 chromatography-data.sqlite
07/11/2019  10:24 PM             3,250 configuration.hss
07/12/2019  04:49 PM        30,101,917 DensViewPos.ami
07/12/2019  05:09 PM        29,787,405 DensViewPosBgnd.ami
07/12/2019  04:49 PM     2,258,962,204 linespectra
09/09/2019  02:47 PM    <DIR>          MSFragger
07/11/2019  10:24 PM    <DIR>          One-column-separation_2019-07-11_20-10-45
07/11/2019  10:24 PM    <DIR>          PASEF_200ng_HeLa_Aurora_347.m
07/12/2019  04:44 PM                 0 ProjectCreationHelper
07/11/2019  08:44 PM             4,868 SampleInfo.xml
07/12/2019  04:51 PM            24,576 Storage.mcf_idx
07/12/2019  04:51 PM                 0 SyncHelper
              24 File(s)  9,288,192,954 bytes
               5 Dir(s)  4,429,751,681,024 bytes free

D:\Data\tobiasko_20190703\20190703_005_PierceHeLa.d>
```

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe and MSFragger. The latest FragPipe and MSFragger support selecting .d folder as input. You may download them from [https://github.com/Nesvilab/FragPipe/releases/tag/10.1](https://github.com/Nesvilab/FragPipe/releases/tag/10.1) and https://msfragger.arsci.com/upgrader/.

FYI, we released a new version of MSFragger yesterday with some bug fixed.

Thanks,

Fengchao

**Comment by chhh** [comment]
@tobiasko Select the `.d` folder (so that's it's highlighted in the file browser) and click `Select` button.
