### ISSUE TITLE
semi tryptic peptides identification

### ISSUE THREAD

**Issue by Me9atron** [Nesvilab/FragPipe#1331]
- Describe the issue or question:

Hello Developers,

I need to identify the semi tryptic peptides together with fully tryptic peptides, all the peptides were labelled with TMT-16. 
I select "SEMI" under the MSFrager->Protein Digestion->Cleavage, and use default settings for other parameters. Would you suggest to adjust or change any parameters for obtaining the optimal results? 

Best wishes,

Zhaowei

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Zhaowei,

If you want to perform the TMT analysis, you need to load one of the TMT workflows, such as "TMT-16", and then, change the digestion cleavage to "SEMI". You probability also need to set the TMT annotation table in the "Quant (Isobaric)" tab to annotate our samples. Here is the tutorial for TMT in case you need it: https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html

Best,

Fengchao

**Comment by Me9atron** [comment]
Thank you, Fengchao.
