### ISSUE TITLE
TMT peptide quantification results 

### ISSUE THREAD

**Issue by Me9atron** [Nesvilab/FragPipe#1333]
- Describe the issue or question:
Dear Developers,

I am a beginner to use FragPipe, and am very impressed with its excellent peptide quantification results. Now I have a few questions about interpreting peptide quant results.
I completed a TMT16-MS3 analysis using FragPipe v.20, with "Define Reference" set to "Virtual", "Normalisation" set to "MD (Median Centering)",  "log 2 transform intensity" selected under "Ratio to Abundance conversion".  
Because I need to calculate the intensity addition (e.g., 126+127N) or ratio (e.g., 126/127N), so I want to use the peptide quant results. I have two options, one is using "peptide.tsv", the other is "abundance_peptide_MD.tsv" in folder "tmt-report". 
1. When I use the file "peptide.tsv", I do the normalization through dividing each peptide's reporter ion abundance by sum of all the reporter ions' abundance in that TMT channel,  then I use the normalized abundance for generating final results. Do you think if this procedure will have bigger variations or other issues?

2. In the "abundance_peptide_MD.tsv" of folder "tmt-report", I found the TMT reporter ion abundance values are centered around 20, are these values log2-transformed abundance? If they are log2-transformed, could I converse them back by calculating 2^a (a is the quantification values around 20)? Because I have to calculate the non-log2-transformed abundacne sum or ratio. Or could you give some suggestion to obtain the non-log2-transformed abundacne? Thank you.

Best wishes,

Zhaowei

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Zhaowei,

> When I use the file "peptide.tsv", I do the normalization through dividing each peptide's reporter ion abundance by sum of all the reporter ions' abundance in that TMT channel, then I use the normalized abundance for generating final results. Do you think if this procedure will have bigger variations or other issues?

I didn't write the TMT-Integrator in FragPipe, but let me try to answer this question according to my limited knowledge. What you did is similar to the median centering for each channels separately. Ideally, you could use more information such as the MS1 intensity, etc, which is how FragPipe/TMT-Integrator performs the normalization.


> In the "abundance_peptide_MD.tsv" of folder "tmt-report", I found the TMT reporter ion abundance values are centered around 20, are these values log2-transformed abundance? If they are log2-transformed, could I converse them back by calculating 2^a (a is the quantification values around 20)? Because I have to calculate the non-log2-transformed abundacne sum or ratio. Or could you give some suggestion to obtain the non-log2-transformed abundacne

Yes, they are log-2 transformed. You can either transform it back by yourself or uncheck the "Log2 transform the intensity" box in the "Quant (Isobaric") tab:

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/99bceeed-d910-4ec5-a4ae-070cf73db281)


Best,

Fengchao

**Comment by Me9atron** [comment]
Hi Fengchao,

Thank you for your support, very helpful. If I use the "abundance_peptide_MD.tsv" in folder "tmt-repor” with non-log2 transformed abundance, should I do a normalization by dividing each peptide's reporter ion abundance by sum of all the reporter ions' abundance in that TMT channel? 

Best wishes,

Zhaowei

**Comment by fcyu** [comment]
No, you should not because the intensities have been well normalized.

Best,

Fengchao

**Comment by Me9atron** [comment]
Ok, I see. Thank you, Fengchao.
