### ISSUE TITLE
ProteinProphet error

### ISSUE THREAD

**Issue by yangxinzhi** [Nesvilab/FragPipe#1337]
- Describe the issue or question:
When I used fragpipe to search the label free protein library, the template I used was LFQ-MBM. Then an error was displayed, I took a screenshot of the error and uploaded the log. Any help you can give me would be greatly appreciated！

- Upload your log file
(If a log file hasn't been ge
<img width="913" alt="89994a37ef41bf1137f81969114e1a5" src="https://github.com/Nesvilab/FragPipe/assets/125720871/07f940bc-6cf5-47db-8992-de90eceabcee">
nerated, go to the 'Run' tab in FragPipe, click 'Export Log', zip
[log_2023-11-17_15-32-51.txt](https://github.com/Nesvilab/FragPipe/files/13388793/log_2023-11-17_15-32-51.txt)
 the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by yangxinzhi** [comment]
At the beginning, I suspected that the reason was that my path had Chinese characters. When I moved the whole file to another place, I still reported an error. I took a screenshot of the error and uploaded it. If I don't run this to get the choice, I end up with no combined protein result. Any help you can give me would be appreciated!
[log_2023-11-17_16-29-16.txt](https://github.com/Nesvilab/FragPipe/files/13389264/log_2023-11-17_16-29-16.txt)
<img width="932" alt="1a5b421e6887234109d92d06e0adc92" src="https://github.com/Nesvilab/FragPipe/assets/125720871/72f4ee03-6e15-4d59-9b5a-5201a1762717">

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/495. 

Please make sure that there are no Chinese in your path, including this one `C:\Users\杨鑫智\AppData\Local\Temp`. You probably need to change your windows account name to change the system temp path.

Best,

Fengchao
