### ISSUE TITLE
MSFragger DIA-NN Quant underperforming in a specific experiment 

### ISSUE THREAD

**Issue by MHBI2018** [Nesvilab/FragPipe#1338]
Hello,

I've noticed that MSFragger underperforms significantly when searching against the mouse FASTA. My instrument was calibrated and QC'd so it shouldn't be the problem. Median mass accuracy from the results was also acceptable for the runs. I searched the files in DIA-NN and Spectronaut as well. MSFragger ID counts were ~17% less on protein and ~30% less precursors. 

I understand that MSFragger is more stringent that DIA-NN but it never been lower to this extent. I'm happy to share to share a few raw files and the log as well privately if you'd like to look closely into this.

Thanks

**Comment by anesvi** [comment]
We can take a look at the log file. If it is Thermo Orbitrap data, the difference is indeed more than expected. But, in general, we are less interested in the total number of proteins, you have to see how many were detected without (or with few) missing values, and also see the quality of those extra peptides and proteins identified by other tools
