### ISSUE TITLE
Error in easyPQP conversion

### ISSUE THREAD

**Issue by LKittinun** [Nesvilab/FragPipe#1342]
I get an error while generating the spectral library. I also tried re-installing easyPQP #1283 and #1293, but it caused a new error.
I've attached 3 log files; the first is when I ran since msfragger, the second is rerunning since easypqp, and the third is after reinstalling easypqp from git.

[log.zip](https://github.com/Nesvilab/FragPipe/files/13420826/log.zip)

Sincerely

**Comment by fcyu** [comment]
After you updated the EasyPQP, the issues in the first two log files have been resolved. As to the third one, it looks like your file `56T3EV_SWATH.mzML` caused the issue:

```shell
2023-11-21 01:31:29 - Info: Processing spectra from file F:\Pete\ev_DIA_demultiplex\56T3EV_SWATH.mzML.
D:\a\OpenMS\OpenMS\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(104): While loading 'F:\Pete\ev_DIA_demultiplex\56T3EV_SWATH.mzML': input ended before all started tags were ended; last tag started is 'spectrumList'( in line 11977602 column 1)
...
```

Best,

Fengchao

**Comment by LKittinun** [comment]
Would you mind to elaborate what this error means? Thanks you

**Comment by fcyu** [comment]
Somehow the library inside EasyPQP parsing the mzML file couldn't parse your mzML file.

**Comment by LKittinun** [comment]
Alright I will take a further look in it. Thank you so much.

Kittinun
