### ISSUE TITLE
False Peptide IDs

### ISSUE THREAD

**Issue by ambgrav** [Nesvilab/FragPipe#1343]
Hello,

I have been trying to identify a set of mutant proteins that I can quantify using DIA, as well as modifications made to these peptides. However, I am experiencing issues with validating these quantifications, as I am getting IDs for peptides from mutants that I know should not be in the input lysate, as I did not express these specific mutants in the cell line I am using (I'll just call these "unwanted mutants"). I did include these unwanted mutant sequences (as well as the wanted mutants) in the fasta, as there was a point in time when I was trying to identify them, but I don't know why I am continuing to get hits for the unwanted mutants in data from experiments in which they were not expressed. 

Is it possible that this is related to a default normalization process that occurs in MSFragger or DIA-NN when identifying or filtering the PSMs?  I have discussed this issue with a few others, and they have found that when searching each condition separately, they are getting fewer false IDs for proteins that they know should not be in the lysate. 

Thank you,
Amber

**Comment by fcyu** [comment]
Hi Amber,

May I ask which result files were you using and what is the percentage of your "unwanted mutants" in your final result after FDR filtering?

Thanks,

Fengchao

**Comment by ambgrav** [comment]
Hi Fengchao, 

I am using the diann-output.pr_matrix.tsv files from the DIA-NN output folder. Of the 78 mutant peptides identified, 11 of them are from unwanted mutants. In my search settings, I believe I have a 1% FDR applied; does the DIA-NN output already filter for this or do I need to do that in the pr files as well?

Thank you!
Amber

**Comment by fcyu** [comment]
Hi Amber,

When evaluate the false discovery proportions, we need to count the total peptides not only the mutant ones. What is the number of total peptides in the `diann-output.pr_matrix.tsv`?

Best,

Fengchao

**Comment by ambgrav** [comment]
Gotcha, I was looking at data across multiple experiments before. Looking at just one output, there is a total of 9675 peptides. Of these, 13 contain a sequence that matches with an expected mutant and 2 match unwanted mutants.

**Comment by vdemichev** [comment]
Hi Amber,

What could help is filtering DIA-NN main report further using Ms1.Profile.Corr and Mass.Evidence, also maybe PEP < 0.01. Also recommend the latest beta 27 https://t.co/jA2IQSiION

Best,
Vadim

**Comment by ambgrav** [comment]
Hi Vadim,

The Ms.1.Profile.Corr and Mass.Evidence filters took care of it! Thank you so much. Would you mind explaining what the Ms1.Profile.Corr and Mass.Evidence values mean or pointing me to where I can read about it?

Thanks again!
Amber

**Comment by vdemichev** [comment]
Hi Amber,

Ms1.Profile.Corr reflects how well MS1 signal correlates with MS2 and if close to 1 it's a good indicator that the peptidoform is identified correctly (i.e. correct mutation calling). Mass.Evidence is an MS2 based score, if high (e.g. > 0.5) is also an indicator of likely correct peptidoform identification.

Best,
Vadim

**Comment by ambgrav** [comment]
Makes sense, thank you again for all of your help!
