### ISSUE TITLE
MBR failing crashes FragPipe

### ISSUE THREAD

**Issue by Monod79** [Nesvilab/FragPipe#1344]
- Describe the issue or question:

Despite being a warning, failed in MBR seems to trigger a non-zero exit code. Even if there is no run passing the minimum correlation threshold 0.5, shouldn't FragPipe be able to complete ? 

Thanks Fengchao !

Version info:
FragPipe version 20.0
MSFragger version 3.8
IonQuant version 1.9.8
Philosopher version 5.1.0-RC3

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-11-21_02-28-23.txt](https://github.com/Nesvilab/FragPipe/files/13423433/log_2023-11-21_02-28-23.txt)

**Comment by fcyu** [comment]
Yes, it is a bug. Could you try the fixed version from https://www.dropbox.com/t/SLwJfKOqCAMaJRIk ?

Thanks,

Fengchao

**Comment by Monod79** [comment]
I’ll gladly try the fixed version. But the link is expired

***@***.***


***@***.***

De : Fengchao ***@***.***>
Envoyé : Tuesday, November 21, 2023 11:27 AM
À : Nesvilab/FragPipe ***@***.***>
Cc : BOULAIS Jonathan ***@***.***>; Author ***@***.***>
Objet : Re: [Nesvilab/FragPipe] MBR failing crashes FragPipe (Issue #1344)


Yes, it is a bug. Could you try the fixed version from https://www.dropbox.com/t/SLwJfKOqCAMaJRIk ?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Sorry about that. Could you try https://www.dropbox.com/t/o1ZDo1amvUmwPYF8 ?

Thanks,

Fengchao

**Comment by Monod79** [comment]
Thanks again Fengchao for your prompt response. 

The fixed version addresses the MBR bug. You can close this issue.

**Comment by Monod79** [comment]
Thanks again Fengchao for your prompt response. 

The fixed version addresses the MBR bug. You can close this issue.
