### ISSUE TITLE
False alarm. When mapping peptides to proteins, need to replace `I` with `L` or `L` with `I` because they are indistinguishable in mass spectra. 

### ISSUE THREAD

**Issue by cpaul32015** [Nesvilab/FragPipe#1345]
- Describe the issue or question:

A few peptide sequences are not correctly mapped to the proteins in the fasta sequences for digestion with different enzymes. In the example on the 1st table the digestion was done with chymotrypsin and cysteine-containing peptides are identified but the sequences are not in the proteins shown in the "Protein.ID" column for the reason shown in the "Note" column. I also summarize the unassigned number from each enzyme search and wonder if you have seen it before

![image](https://github.com/Nesvilab/FragPipe/assets/54745839/216134e9-5b6e-44cb-acc3-a75ce1537aa6)

**Comment by fcyu** [comment]
When you mapped the peptide to the protein sequence, have you tried to switch `I` to `L`, and `L` to `I`? Since these two amino acids are almost distinguishable in mass spectra, we treat them the same in the mapping.

Best,

Fengchao

**Comment by cpaul32015** [comment]
Hi Fengchao,

I manually checked a few by switching the aa and they are indeed as you suggested. Is there a way to map the peptide sequence to the correct protein automatically without having to manually checking them? Some of the identified sequences actually matched to decoy protein sequences which we want to avoid.

Thanks!
Zixiang

**Comment by cpaul32015** [comment]
Hi Fengchao,

Thank you for your quick response once again! There is indeed another non-decoy protein that is matched after switching the 'I' or 'L', but it does cause issue when I am trying to locate the cys modification within the protein, as the identified peptide is not found in that protein unless I manually swap out 'I' or 'L' and check all the possible matches (depending the number of 'I' and 'L' in the sequence there could be multiple proteins matched). Will it be possible for future FragPipe release to address this inconvenience? (aka. showing the protein where the identified peptide sequence is from without the need to go to fasta file for searching the alternative protein matches)

**Comment by fcyu** [comment]
> Will it be possible for future FragPipe release to address this inconvenience? (aka. showing the protein where the identified peptide sequence is from without the need to go to fasta file for searching the alternative protein matches)

Yes, the "Protein" and the "Mapped Proteins" columns in psm.tsv and some other tsv files have all mapped proteins. What you did (manually matching a peptide against a fasta file) is not necessary (as I implied in my previous reply) at all.

Best,

Fengchao

**Comment by haiyan-MS** [comment]
I understand that is not a bug or mistake. But we do need to map the peptides to proteins as we did not find a covient way for reporting modification sites. In this case, what should I do?

**Comment by fcyu** [comment]
Several approaches:

1. Do not distinguish `I` and `L` when you map a peptide to a protein, and then adjust the `I` and `L` based on the real sequence of the mapped proteins. A simple regular expression, `[IL]`, can easily do the match.
2. There are `Protein Start` and `Protein End` in the peptide.tsv. You take the information from there.

Best,

Fengchao
