### ISSUE TITLE
glyco-N-HCD search of Thermo Eclipse DDA files no longer working since latest MS software update

### ISSUE THREAD

**Issue by DebWenk** [Nesvilab/FragPipe#1346]
**- Describe the issue or question:**
I'm running glyco-_N_-HCD searches of DDA runs measured at an Thermo Eclipse. Since the last Thermo Eclipse software update (of the Orbitrap Eclipse Tune Application, version 4.0.4091), PeptideProphet seems to have issues with reading the MSFragger output files. Processing raw files from before the MS software update with glyco-_N_-HCD works as usual.

**- Upload your log file**
[log_2023-11-21_13-25-22.zip](https://github.com/Nesvilab/FragPipe/files/13429827/log_2023-11-21_13-25-22.zip)

**Comment by fcyu** [comment]
MSFragger got 0 IDs from your data. Could you share one of your raw files with us? Here is the link to upload the files: https://www.dropbox.com/request/N7xvwVShiabipn64NIB0

Thanks,

Fengchao

**Comment by DebWenk** [comment]
I uploaded one raw file. Thank you!

**Comment by fcyu** [comment]
Thanks for your file. I have checked and there is no issue loading the data. I guess the issue is due to the sample preparation or parameter setting.

Best,

Fengchao

**Comment by DebWenk** [comment]
Thank you for testing the raw file. Can you specify which parameter settings you mean? I don't think it's the FragPipe parameters, as older MS raw files from similar samples measured with the exact same MS method can be processed with the same FragPipe settings. I also don't think it's the sample, since the chromatograms look as expected.

**Comment by fcyu** [comment]
Hard to tell which step went wrong, but at least it was not due to any FragPipe bugs.

**Comment by dpolasky** [comment]
It looks like even the first search cannot find any unmodified peptides - this usually means that the data was TMT but it was not included in the search settings, or other fixed modification is present but not specified, or the fasta file is for the wrong organism, or etc.
