### ISSUE TITLE
Nonspecific search 

### ISSUE THREAD

**Issue by Mohee66** [Nesvilab/FragPipe#1348]
- Describe the issue or question:
- Dear all, 
- I have done one experiment and I am trying to look at the peptides made by microbial fermentation. For this reason after protein extraction from the fermented sample, I used 10KDa and 5KDa molecular cut-offs to filter small peptides without using any enzymes. then the filtered samples were run on a Q Exactive explores.  I am using a 100k database from NCBI for analysis. I managed to analyse the data when I set up the setting on trypsin in Msfragger but it almost gave me nothing but I need to do a nonspecific search to make sure the result is accurate. However, Everytime I use nonspecific in the setting I am facing different errors like below. Would you please help me to solve this problem? 
Thanks 
- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
 "Checking database...
Parameters:
num_threads = 2
database_name = 2023-11-23-decoys-contam-13_10_2023_NCBI.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 0
use_all_mods_in_first_search = 0
write_calibrated_mzml = 0
write_uncalibrated_mgf = 0
write_mzbin_all = 0
isotope_error = 0/1/2
mass_offsets = 0.0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
ion_series_definitions = 
search_enzyme_name = nonspecific
search_enzyme_sense_1 = C
search_enzyme_cut_1 = -
search_enzyme_nocut_1 = 
allowed_missed_cleavage_1 = 0
search_enzyme_sense_2 = C
search_enzyme_cut_2 = -
search_enzyme_nocut_2 = 
allowed_missed_cleavage_2 = 0
num_enzyme_termini = 0
clip_nTerm_M = 0
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = tsv_pepxml_pin
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 1
override_charge = 0
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 91
digest_mass_range_low = 500.0
digest_mass_range_high = 10000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
activation_types = all
group_variable = 0
require_precursor = 0
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 1
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
add_A_alanine = 0.0
add_B_user_amino_acid = 0.0
add_C_cysteine = 57.02146
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.0
add_E_glutamic_acid = 0.0
add_F_phenylalanine = 0.0
add_G_glycine = 0.0
add_H_histidine = 0.0
add_I_isoleucine = 0.0
add_J_user_amino_acid = 0.0
add_K_lysine = 0.0
add_L_leucine = 0.0
add_M_methionine = 0.0
add_N_asparagine = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.0  # O = pyrrolysine (237.14773 Da)
add_P_proline = 0.0
add_Q_glutamine = 0.0
add_R_arginine = 0.0
add_S_serine = 0.0
add_T_threonine = 0.0
add_U_user_amino_acid = 0.0  # U = selenocysteine (150.95363 Da)
add_V_valine = 0.0
add_W_tryptophan = 0.0
add_X_user_amino_acid = 0.0
add_Y_tyrosine = 0.0
add_Z_user_amino_acid = 0.0
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at q.a(Unknown Source)
	at r.a(Unknown Source)
	at k.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at F.a(Unknown Source)
	at q.a(Unknown Source)
	at q.a(Unknown Source)
	at q$$Lambda$117/0x0000000800d3f078.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Traceback (most recent call last):
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 616, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 133, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\46658831\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx4G', 'C:\\fragpipe\\MSFragger-3.8\\MSFragger-3.8\\MSFragger-3.8.jar', 'fragger.params', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k15_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k15_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k15_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k16_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k16_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k16_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k17_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k17_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k17_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k18_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k18_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_10k18_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k1_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k1_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k1_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k2_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k2_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k2_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k3_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k3_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k3_3.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k4_1.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k4_2.raw', 'C:\\13_10_2023_Exploris_ferementation\\230926_5k4_3.raw', '--partial', '0']' returned non-zero exit status 1.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 247 remaining tasks" 


-

**Comment by fcyu** [comment]
There is not enough memory to perform the first search. Can you change the "calibration and optimization" to none, convert all of your raw files to mzML format according to https://fragpipe.nesvilab.org/docs/tutorial_convert.html, and try again?

Since your computer only has 4 GB free memory, you need to set the number of "split database" to a large value, such as 64 or 128.

Best,

Fengchao
