### ISSUE TITLE
Unmatched peptides?

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/FragPipe#1352]
- Describe the issue or question:
Hello,

Thank you for developing, and continually updating, a great product! 

I was wondering if there is a file within the Fragpipe output that includes sequences of identified peptides that are not matched to proteins? 

Thanks again and please let me know if I can provide any additional information

All the best,

Jason 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Jason,

Could you elaborate the question more? What is the meaning of "identified peptides that are not matched to proteins"? Theoretically, all peptides can be mapped to at least one protein.

Best,

Fengchao

**Comment by fcyu** [comment]
If the peptides are not in the given fasta file, they won't be searched and there is no way to know their sequences in the database searching based framework. I guess what you want to use is de novo sequencing.

Best,

Fengchao

**Comment by jmcalist** [comment]
Thanks so much, I completely understand, does Fragpipe have any de novo features available?

**Comment by fcyu** [comment]
In the current version, no.

Best,

Fengchao

**Comment by jmcalist** [comment]
Thanks again! I am always impressed with both the speed of fragpipe searches, and your speed of responses on this forum!

**Comment by fcyu** [comment]
You are welcome. FragPipe's speed is unstoppable, but, unfortunately, I have to go to bed very soon ;)

Best,

Fengchao
