### ISSUE TITLE
TMT zero and TMTprozero labeled peptide quantification analysis

### ISSUE THREAD

**Issue by SMORATUW** [Nesvilab/FragPipe#1356]
I need to get the reporter ion intensity of TMTprozero and TMTzero labeled peptide samples. As I can see, Fragpipe has allowed to analyze TMT6plex, 10plex,11plex, and 16plex. Is there any way that I can quantify TMTzero and TMTprozero samples by Fragpipe

**Comment by fcyu** [comment]
It can be easily done. We just need to add the reporter ion masses to the program. Will let you know when it is ready. 

Best,

Fengchao

**Comment by fcyu** [comment]
Implemented in the new IonQuant and FragPipe (https://github.com/Nesvilab/FragPipe/commit/58fdd2a5a7b6e8bb4b04f348940f28b6ecfb76fa). Please send an email to yufe AT umich.edu to get the pre-released version to test. And we will release a formal version soon.

Best,

Fengchao
