### ISSUE TITLE
download fasta error

### ISSUE THREAD

**Issue by yangxinzhi** [Nesvilab/FragPipe#1359]
- Describe the issue or question:

Why do I always get an error when I use fragpipe to download database? I could have downloaded it before

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
<img width="725" alt="680db1814f2b29f75e8a5af09ccbecd" src="https://github.com/Nesvilab/FragPipe/assets/125720871/3575cde6-6f36-4fff-9036-bff68c96452f">

**Comment by tobiasko** [comment]
I am also experiencing a lot of broken downloads recently. Is it time to complain at EBI again?

**Comment by fcyu** [comment]
The database downloading seems to work well again. Let me know if you still have issues.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
Ok, thank you very much. I also see that this problem has been solved
