### ISSUE TITLE
How to set the contents of Experiment and Bioreplicate in the DIA_SpecLib_Quant template?

### ISSUE THREAD

**Issue by yangxinzhi** [Nesvilab/FragPipe#1360]
- Describe the issue or question:
I would like to ask if I use DIA_SpecLib_Quant as the template when I use fragpipe for DIA search without building a library, but I have some ungraded DDA data from previous experiments, how should I make good use of these data? At the same time, I would like to know how to set the Experiment and Bioreplicate parameters of these DDA data? Which of DIA_SpecLib_Quant or DIA_DIA-Umpire_SpecLib_Quant works better for DIA data without having library?
![image](https://github.com/Nesvilab/FragPipe/assets/125720871/afd7c354-e110-41f3-a8df-247b463863b5)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Neither `DIA_SpecLib_Quant` nor `DIA_DIA-Umpire_SpecLib_Quant` needs a library. If you have both DDA and DIA data, you can load them to FragPipe, as you have already done. And do not set any experiment group. FragPipe will use all of your files to build a (internal) library, and then perform the quantification using your DIA files. The quant results are in `diann-output` folder.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
Do you mean that if part of the same experiment is collected by DIA and part is collected by DDA, DDA data will be loaded into it? But I don't think that's usually the case. I want to use the DDA data I collected from this organization before to see if the DDA data can provide some information for DIA analysis in this new experiment

**Comment by yangxinzhi** [comment]
So I can load multiple DDA data from this organization that I collected before and DIA data from this new experiment, and run together? But I want to know that the final result will also be the DDA data of the old experiment will also be normalized to get a value, right? In this case, will some data be filtered out when there is FDR card value?

**Comment by fcyu** [comment]
I don't think you can or it is a good idea to compare the quantification results from DDA and DIA. What I said is that you can leverage your old DDA data to get a more comprehensive internal spectral library so that the quantification from DIA **only** are supposed to be better.

In case you don't know, to get the DDA label-free quantification done, you should use LFQ-MBR workflow. To get the DIA label-free quantification done, you should use the DIA_SpecLib_Quant or DIA_DIA-Umpire_SpecLib_Quant workflow. Those two are doing things differently.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
I know that DDA data and DIA data cannot be compared, so what I mean is that when I want to use the old DDA to assist DIA data analysis in a new experiment, there will be no DDA data in the final DIA result, right?

**Comment by fcyu** [comment]
Yes, you are correct. The DDA data is only used to build the library. The quantification result table in the diann-output folder is only from DIA.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
Ok, thank you very much. And I'm going to look at the difference between the DIA run and the DDA run for the same sample
