### ISSUE TITLE
Non-specific/peptidomics workflow crashing due to Python? (FragPipe v20, Python 3.9.0)

### ISSUE THREAD

**Issue by dtabang** [Nesvilab/FragPipe#1361]
- Describe the issue or question:

I am trying to do peptidomics with a nonspecific search with both the built-in workflows and Fragger parameters and also previously used modified workflows for peptidomics (done on earlier versions of all the software), though it now keeps failing. The end bits of the log below seem to point to Python as the cause, "cannot unpack non-iterable numpy.float64 object". What should I do? Thanks.  

- Upload your log file

[log_2023-12-11_11-53-27.zip](https://github.com/Nesvilab/FragPipe/files/13638657/log_2023-12-11_11-53-27.zip)

**Comment by dtabang** [comment]
I have that `split_peptide_index_tempdir` folder and can send it - it is about 73 GB, what is the best way to send it? Also zipped and posted here? I have the fasta split in ten and they seem to be the biggest contributors to the folder size. Thanks.

**Comment by fcyu** [comment]
Here is the link to upload the files: https://www.dropbox.com/request/VAiqX6vnYvo5CqNB8PHs

Best,

Fengchao

**Comment by dtabang** [comment]
Thank you, I have just started uploading the folder and the remaining time is fluctuating around 2000 minutes from now.

**Comment by guoci** [comment]
Hi @dtabang , I have attempted to fix the issue.
Can you replace the file
`C:\Users\labst\Downloads\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py`
with
https://github.com/Nesvilab/FragPipe/raw/52e6495d5b755666873ce4c24c5eafc3d9495166/MSFragger-GUI/tools/msfragger_pep_split.py
?

**Comment by dtabang** [comment]
Ok, will do thank you.

**Comment by dtabang** [comment]
Hi, I took the txt file you sent and made it into a py file and replaced the old msfragger_pep_split file, though this did not seem to work. The same error occurred in the same place as before. Zipped log file attached.
[log_2023-12-14_09-43-57.zip](https://github.com/Nesvilab/FragPipe/files/13674686/log_2023-12-14_09-43-57.zip)

**Comment by fcyu** [comment]
@guoci Can you take another look? It seems that the bug is still there.

Best,

Fengchao

**Comment by guoci** [comment]
@dtabang can you upload all files in `split_peptide_index_tempdir` that ends with `_expectscore.tsv`?

**Comment by dtabang** [comment]
Reran with the file replaced the previous one, here is the log: 
[log_2023-12-14_18-50-05.zip](https://github.com/Nesvilab/FragPipe/files/13679366/log_2023-12-14_18-50-05.zip)

**Comment by dtabang** [comment]
Here are the expectscore files too:
[expectscore_12142023.zip](https://github.com/Nesvilab/FragPipe/files/13679458/expectscore_12142023.zip)

**Comment by guoci** [comment]
@dtabang In the most recent log you posted, the Python program path is `B:\fragpipe20\tools\msfragger_pep_split.py`, wheareas in the first log you posted, the path is `C:\Users\labst\Downloads\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py`.
Did you replace the correct file?

**Comment by dtabang** [comment]
Ah I replaced the wrong file, I will rerun.

**Comment by dtabang** [comment]
Seems to have made it further this time however there was another error saying not enough disk space, though there should be enough space where the data files are in B:\ and the output is in D:\ log file attached
[log_2023-12-15_21-00-08.zip](https://github.com/Nesvilab/FragPipe/files/13691033/log_2023-12-15_21-00-08.zip)

**Comment by fcyu** [comment]
I don't know which one, B or D, has more space, but the error message won't lie. Could you double check if there are enough space in B?

Best,

Fengchao

**Comment by dtabang** [comment]
Sure, I can delete some more files off the B drive and try again, though there should be over 300 GB on that drive still. Is there a way to rerun just part of it or would it need to start from the beginning of the process for searching again?

________________________________

**Comment by fcyu** [comment]
Yes, you can rerun from the "Quant (MS1)" tab by uncheck MSFragger and Validation tabs.

Best,

Fengchao

**Comment by dtabang** [comment]
Did this and it successfully finished, thank you! I tried to generate a spectral library by unclicking the Quant (MS1) tab and clicking spec lib, though this resulted in an EasyPQP convert error. Could you help me with this? Log file attached.
[log_2023-12-16_11-00-21.zip](https://github.com/Nesvilab/FragPipe/files/13693615/log_2023-12-16_11-00-21.zip)

**Comment by fcyu** [comment]
It is a known bug: https://github.com/Nesvilab/FragPipe/issues/1275, https://github.com/Nesvilab/FragPipe/issues/1283, https://github.com/Nesvilab/FragPipe/issues/1293. Could you run the following command to uninstall and install the fixed EasyPQP?

```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Thanks,

Fengchao

**Comment by dtabang** [comment]
Done. Thank you for your help, the peptidomics searches and library generation work for me now!
