### ISSUE TITLE
Failed to run the DIA_Speclib_Quant template.

### ISSUE THREAD

**Issue by yangxinzhi** [Nesvilab/FragPipe#1364]
I would like to ask why I failed when I ran DIA data. Attached is my log, could you please help me check it?
[log_2023-12-13_10-59-27.txt](https://github.com/Nesvilab/FragPipe/files/13655459/log_2023-12-13_10-59-27.txt)

**Comment by yangxinzhi** [comment]
Maybe I should just limit the memory？

**Comment by fcyu** [comment]
There is not enough memory. You only have 5 GB free memory in your computer. Also, you probability need to convert your raw fo mzML format unnless you have install the [Thermo MS File Reader](https://thermo.flexnetoperations.com/control/thmo/login?nextURL=%2Fcontrol%2Fthmo%2Fdownload%3Felement%3D6306677) 

Best,

Fengchao
