### ISSUE TITLE
How to increase number of variable modifications 

### ISSUE THREAD

**Issue by studentDenmark** [Nesvilab/FragPipe#1365]
Is it possible to increase number of variable modifications from the already 16 ?

**Comment by fcyu** [comment]
You can actually use the mass-offset search, which can search thousands of modifications very fast. Just load the `Mass-Offset-CommonPTMs` workflow, and edit the "mass offsets" in the MSFragger tab
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/32f0bbb1-bfab-4a51-8667-5e8387032f75)

In the next release, we will also support to specify modified sites, diagnostic ions, and neutral loss ions for each mass offset. If you want to test this new feature, feel free to let me know and we will send you a pre-release version.

Best,

Fengchao
