### ISSUE TITLE
MS2 Spectra with no B/Y ions but high probability (>0.99)?

### ISSUE THREAD

**Issue by BjoernZiehr** [Nesvilab/FragPipe#1368]
I used msFragger to do a protein ID from a DDA run. It generated ~1700 hits. Curiously, for most proteins, there are several MS1 peptides that are IDed with >0.99 probability that have 0 B or Y ions in the MS2. There are even
 some protein IDs where there are no MS2 spectra that have B/Y ions (screen cap). 

I suspect this is an issue with my search settings. I left most settings on Default e.g. FDR 0.01. I'm unsure what "probability threshold" in the "run" tab is for. What does this effect?
MS1 error +/- 20 ppm (orbitrap used, Eclipse); MS2 Error 0.5 Da (ion trap used experimentally)

Any help or pointers to relevant tutorials is welcome. 

Thanks,

[log_2023-12-13_13-37-06.zip](https://github.com/Nesvilab/FragPipe/files/13665506/log_2023-12-13_13-37-06.zip)
![Screenshot 2023-12-13 134033](https://github.com/Nesvilab/FragPipe/assets/153773475/7fb7b439-78f8-4b3c-8937-67717fdd05d4)

**Comment by fcyu** [comment]
> MS2 Error 0.5 Da (ion trap used experimentally)

If your data is from ion trap, you need to adjust the mass tolerance when you visualize the annotated spectra. You can click the "settings" at the bottom of your screenshot to find the way to change the tolerance.

Best,

Fengchao

**Comment by BjoernZiehr** [comment]
Oooh. Thanks you so much. Yes the MS2 scans are in fact filled with B/Y ions.

**Comment by BjoernZiehr** [comment]
While I have your attention.... What is "probability threshold" under the "Run" tab?

**Comment by fcyu** [comment]
That is for generating the sub mzML for the two-pass search approach. Basically, when FragPipe finishing the analysis, you can let it generate sub mzML files containing unidentified spectra. PSMs with probability higher than that value will not be included in the sub mzML file. 

If you are not doing the two-pass search analysis, you don't need to worry about that parameter.

Best,

Fengchao

**Comment by BjoernZiehr** [comment]
Ah ok, thank you again. Have a nice day.
