### ISSUE TITLE
DIANN output with wrong sequence

### ISSUE THREAD

**Issue by haiyan-MS** [Nesvilab/FragPipe#1370]
- Describe the issue or question:
I used Fragpipe to search a file, then used DIA NN to caculate. However, some of the peptides was assigned to protein that does not contain this particular sequence. One example, MELQEIQLKEAK. It was assigned to G5E8R2 (uniprot assession). I can't find that sequence in Uniprot with this assession. WHat I found is the sequence belongs to G5E8R2 is MEIQEIQLKEAK. One I is swichecd  to L in the report. I was wondering if you have some ways to solve this problem.  

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It is not a bug, it is a feature of mass spectrometry. `I` and `L` are not distinguishable from mass spectra so we use them indistinguishily in mapping the proteins. Same questions as https://github.com/Nesvilab/FragPipe/issues/1345

Best,

Fengchao
