### ISSUE TITLE
Multiple enzymes

### ISSUE THREAD

**Issue by pisistrato** [Nesvilab/FragPipe#1371]
For a while, it is possible to specify two enzymes, e.g. trypsin (KR) and gluC (E).
However, I could not find anywhere what Fragger would do in such a case:
- option A: digest the database with trypsin and gluC all at once (i.e. cutting after K, R, and E)
- option B: digest the database first with trypsin, and subsequently digest the tryptic peptides with gluC.

Because it is possible to specify for each enzyme a miss cleavage rate, I have the feeling that option B is performed, is that the case? 🤞 
Typically it shouldn't matter as most proteases have similar fitness, however, if one of them is not so active, option A will be suboptimal...

Thanks.

**Comment by fcyu** [comment]
Option A is performed but we count the number of missed cleavages separately.

> if one of them is not so active, option A will be suboptimal

I am not sure if I get the point. Why this will be an issue? Since we count/control the missed cleavages separately, the outcome should be the same between digesting both enzymes at once and one-by-one.

Best,

Fengchao

**Comment by fcyu** [comment]
If the tool does not count/control the missed cleavages separately for two enzymes, then it is not doing a good job due to the reason you have just explained ;) 

Our tools won't have this problem because we always have a high standard and make them as optimal as possible.

Best,

Fengchao
