### ISSUE TITLE
Error in running DIA_Speclib_Quant workflow

### ISSUE THREAD

**Issue by qingbo11** [Nesvilab/FragPipe#1372]
- Describe the issue or question:
Hello FragPipe Team,

I run the DIA_Speclib_Quant workflow by submitting 28 DIA runs (in that way I would like to do a direct DIA quantification and let FragPipe to generate library after searching the 28 DIA runs against human reference proteome. It just showed the error right after I started the run. I actually upgraded my Java to Jave 21.0, so not sure how to address. Please take a look.
[log_2023-12-14_17-54-26.txt](https://github.com/Nesvilab/FragPipe/files/13689681/log_2023-12-14_17-54-26.txt)

Thanks,

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Did you change anything after loading the DIA_Speclib_Quant workflow? Could you upload your workflow file? You export it by clicking the "save to custom folder" button in the "workflow" tab.

Best,

Fengchao

**Comment by qingbo11** [comment]
Hello Fengchao,

Thank you for your prompt . Attached please find the workflow file I have now.

Qingbo Shu, PhD

Center for Cellular and Molecular Diagnostics
Department of Biochemistry and Molecular Biology
School of Medicine, Tulane University
JBJ Building, Rm 462
New Orleans, LA

Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by fcyu** [comment]
It was truncated by GitHub. Could you go to https://github.com/Nesvilab/FragPipe/issues/1372 and upload there?

Best,

Fengchao

**Comment by qingbo11** [comment]
![image](https://github.com/Nesvilab/FragPipe/assets/81097598/ec12cc6c-2730-4812-ba20-4550d9ba1175)

**Comment by fcyu** [comment]
Could you zip your file?

Best,

Fengchao

**Comment by qingbo11** [comment]
[workflow.txt](https://github.com/Nesvilab/FragPipe/files/13689914/workflow.txt)

**Comment by qingbo11** [comment]
Hi Fengchao,

I cannot directly attach the original workflow file because here it is not supported. I then use notepad++ to open and copy/paste the content of the workflow file to a txt and shar it with you just now.

**Comment by qingbo11** [comment]
[workflow_DIA.zip](https://github.com/Nesvilab/FragPipe/files/13689925/workflow_DIA.zip)
Here is the zip file in case you need it.

**Comment by fcyu** [comment]
Could you do the following and try again?

Re-load DIA_Speclib_Quant workflow and do not change anything except for the database. What you have changed just made it worse.

Best,

Fengchao

**Comment by qingbo11** [comment]
![image](https://github.com/Nesvilab/FragPipe/assets/81097598/505d11c7-6504-49cc-9770-0e734a0b24fb)
Okay, before that, I would like to confirm with you that all the settings for the runs are okay. I have two groups (19 disease patients and 9 controls), and I set up them in the "experiment" abd "bioreplicate" respectively. You like me to close the software and redo this setting, reload the DIA_SpecLib_Quant workflow, then click "run" directly without change anything?

**Comment by fcyu** [comment]
There is no need to close the program. You just need to click "Load workflow" after selecting the DIA_SpecLib_Quant one. After that, check if the fasta file path is correct and then click "run".

Also, you need to remove all experimental groups by clicking the "clear groups" button. In the next release, we will (partially) support the experimental groups.

Best,

Fengchao

**Comment by qingbo11** [comment]
Okay, I realized that I forgot to press the "Load workflow" button. My apologize. Thank you, now it is running. Cheers!

**Comment by qingbo11** [comment]
Hello Fengchao,

Thank you for your help. I've been successfully running the DIA workflow. Now I got another issue for memory space limitation I believe. Please take a look at attached.

Thanks,



Qingbo Shu, PhD

Research Assistant Professor
Center for Cellular and Molecular Diagnostics
Department of Biochemistry and Molecular Biology
School of Medicine, Tulane University
JBJ Building, Rm 462
New Orleans, LA

Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by fcyu** [comment]
The file was discarded by GitHub. Could you go to https://github.com/Nesvilab/FragPipe/issues/1372 and upload the file there?

Thanks,

Fengchao

**Comment by qingbo11** [comment]
[hs_err_pid2416.log](https://github.com/Nesvilab/FragPipe/files/13728839/hs_err_pid2416.log)

**Comment by qingbo11** [comment]
[log_2023-12-20_09-54-33.txt](https://github.com/Nesvilab/FragPipe/files/13728844/log_2023-12-20_09-54-33.txt)

**Comment by fcyu** [comment]
It was due to the inappropriate paging file configurations. Could you change your operating system's settings according to the following screenshot?
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/da232d2a-f284-442c-b049-94e131aab713)

Best,

Fengchao

**Comment by qingbo11** [comment]
Thank you, Fengchao. I changed my operating system's settings, but it turns out that I have to run the tool on another computer with better performance. Now I completed the analysis. I appreciate your help.
