### ISSUE TITLE
DIA-SpecLib-Quant error in running FAIMS-DIA with multiple CV

### ISSUE THREAD

**Issue by fedefratini** [Nesvilab/FragPipe#1373]
Hi!
I'm trying setting up faims-dia acquisition method comparing one vs multiple CVs and single DIA m/z mass range with different DIA m/z fragmets.

I acquired my raw files on Thermo Fusion and converted the raw files to mxML with MSConvertGUI of ProteoWizard.

I set up a workflow with DDA, DIA, FAIMS-DIA, multipleCVs-FAIMS-DIA; multipleCVs-FAIMS-DIA-multiple fragments.

I get an error in the MSFragger main search step, always in the last slice of searching. The same error occur in several attempts (see log files), always whit similar raw files in which there are 2 CVs and MS/MS2 for each CV. I contrelled method and raw files and they seems correct MS1(cv1)/MS2(cv1)/MS1(cv2)/MS2(cv2)

[log_2023-12-15_16-55-29.txt](https://github.com/Nesvilab/FragPipe/files/13701509/log_2023-12-15_16-55-29.txt)
[log_2023-12-16_17-26-16.txt](https://github.com/Nesvilab/FragPipe/files/13701510/log_2023-12-16_17-26-16.txt)
[log_2023-12-16_23-55-19.txt](https://github.com/Nesvilab/FragPipe/files/13701511/log_2023-12-16_23-55-19.txt)
[log_2023-12-17_01-58-25.txt](https://github.com/Nesvilab/FragPipe/files/13701512/log_2023-12-17_01-58-25.txt)
[log_2023-12-17_17-18-01.txt](https://github.com/Nesvilab/FragPipe/files/13701513/log_2023-12-17_17-18-01.txt)
[log_2023-12-17_23-04-19.txt](https://github.com/Nesvilab/FragPipe/files/13701514/log_2023-12-17_23-04-19.txt)
[log_2023-12-18_09-15-52.txt](https://github.com/Nesvilab/FragPipe/files/13701515/log_2023-12-18_09-15-52.txt)

Morevore, the error seems random, these two files are identical just 2 folowwing injections, once give error the first, once the second, as reported in this log [log_2023-12-16_17-26...

005. RD_500ng_1h_FAIMS-45-60_DIA_NOSTAG_40X20-30X20_1.mzBIN_calibrated has fragtmp, skip
006. RD_500ng_1h_FAIMS-45-60_DIA_NOSTAG_40X20-30X20_2.mzBIN_calibrated 2.4 s
		[progress: 45978/45978 (100%) - 811 spectra/s] 56.7s
		Building spectral index for the mzBIN_calibrated file MS1 and MS2 have different compensation voltage sets: [-60, -45] vs [-45]
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

PLEASE HELP :-)
Federica

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
> MS1 and MS2 have different compensation voltage sets: [-60, -45] vs [-45]

That is because your MS1 has scans with two compensation voltages, -60 and -45, while your MS2 scans only have one, -45. The program did a sanity check and thought there might be something wrong with the input data. Normally the number of voltages from MS1 and MS2 should be the same.

Could you elaborate a little more about why there are different voltages from MS1 and MS2?

Thanks,

Fengchao

**Comment by fedefratini** [comment]
Hi 
actually I have a sequence of 4 different acquisitions in the method
1)MS1CV1 then2)MS2-diaCV1 then 3)MS1CV2 then 4)MS2-diaCV2

I checked twice if there is any error in the method setting and I checked the raw files also and effectively the sequence
is correctly executed
so I don't understand why msfragger just  recorgnize only one cv for MS2 , what it does with all dia scans aquired with the second CV (-60)?

now I'm using the thermo script "FAIMS to mxml converter" and of course fragpipe it is running correctly
but it generate an mzML file for each CV and I'll have a quatification for each CV fraction and I don't know how to merge them.....

**Comment by fcyu** [comment]
If you upload your files to https://www.dropbox.com/request/VPMDoX0qDbl7wOUHH7Gt , I can take a look to figure out the reason.

Best,

Fengchao

**Comment by fedefratini** [comment]
Actually I checked the file and in that isolation window I have MS2 also for -60, but it is true that the 2 CV don’t have the same isolation windows list, I mean I set different windows for -60 (30 th) and -45 (20 th)
Is this the problem?
Fede

***@***.***

***@***.***

**Comment by fedefratini** [comment]
> 
> now I'm using the thermo script "FAIMS to mxml converter" and of course fragpipe it is running correctly but it generate an mzML file for each CV and I'll have a quatification for each CV fraction and I don't know how to merge them.....
>
I get an error too ... 
[log_2023-12-18_22-10-43.txt](https://github.com/Nesvilab/FragPipe/files/13708670/log_2023-12-18_22-10-43.txt)

**Comment by fcyu** [comment]
This is a known bug: https://github.com/Nesvilab/FragPipe/issues/1275, https://github.com/Nesvilab/FragPipe/issues/1283, and https://github.com/Nesvilab/FragPipe/issues/1293. Can you upgrade EasyPQP to 0.1.42 by clicking the `Install/Upgrade EasyPQP` button in the `Config` tab?

Thanks,

Fengchao

**Comment by fcyu** [comment]
> Actually I checked the file and in that isolation window I have MS2 also for -60, but it is true that the 2 CV don’t have the same isolation windows list, I mean I set different windows for -60 (30 th) and -45 (20 th)
Is this the problem?

Could you elaborate it more? Also, could you double check if the isolation window [420.0, 440.0] has MS2 scans with -60? 

Best,

Fengchao

**Comment by fedefratini** [comment]
Goodmorning,

I'm sorry I had attached the picture of method summary and the MS2 -60 as image in the email, maybe you didn't receive it. Now I have uploaded on the dropbox: in the method summary I underlined the differences in the settings of the DIA acquisitions for cv-45 and cv -60; then you find the MS2 TIC for window 400-430 cv=-60 and also one scan of it. 

Really thanks for your support
best

Federica

**Comment by anesvi** [comment]
Normally we only support requests likes this as a collaboration. We cannot start making changes for just one project. Perhaps you can contact me directly by email.

**Comment by fedefratini** [comment]
fine

thanks

**Comment by fedefratini** [comment]
Anyway, it doesn't look like to be a question of different DIA windows, if not a general bug with multiple CVs
in this log file  
[log_2023-12-20_09-11-54.txt](https://github.com/Nesvilab/FragPipe/files/13724713/log_2023-12-20_09-11-54.txt)
you will find no error in for example -45;-65 and then again the same error in _40;-55;-70 the difference in the two raws is just the adding of a third CV, I have MS1 and MS2 TIC profile for all CVs, but same error. 

**So the question is if it possible to run experiment with multiple-CVs using MSConvertGUI to convert raw files in mzML (1:1) without splitting each raw file in one mzML for each CV channel** (1:2 or 1:3) to ben analysed separately and then necessarily combine the reports to select the best channel for each precursor . 

Thanks 

Federica

**Comment by fcyu** [comment]
> So the question is if it possible to run experiment with multiple-CVs using MSConvertGUI to convert raw files in mzML (1:1) without splitting each raw file in one mzML for each CV channel (1:2 or 1:3) to ben analysed separately and then necessarily combine the reports to select the best channel for each precursor .

If I understand your question correctly, no, there is no way to analyze a single mzML file multiple times and one CV at a time.

I would worry more about your data acquisition protocol because something must be wrong: for some isolation windows, the number of CVs are different between MS1 and MS2, which should not happen.

Best,

Fengchao

**Comment by fedefratini** [comment]
Ok, thank you.
I got the problem, different window settings for different CV it is not supported. Just for reasoning together actually it should be possible to change the number of DIA windows for different CV
In the meaning that for CV=-45 I do expect more ions that for CV=-65 and then It should be possible to use in the second case (cv =-65) larger windows,
In this way, it could be possible to use double CVs without doubling the cycle time. Or not?

Thanks
Fede

**Comment by a-indra** [comment]
Hi Fengchao,
I am having the same issue as Fede. My experiment is simpler and my isolation windows are identical between CVs. Can I please send you my .raw file for you to have a look at?
Thank you!

[log_2024-12-10_14-15-02.txt](https://github.com/user-attachments/files/18073790/log_2024-12-10_14-15-02.txt)

**Comment by fcyu** [comment]
This is a know bug and will be fixed in the next release.

Best,

Fengchao

**Comment by a-indra** [comment]
Hi Fengchao,
Can I ask whether the new release of Fragpipe (v23.0 at the time of writing) is now compatible with multiple CVs? 

Or, whether you can suggest a solution for re-combining CVs after splitting a .raw file such that it's one CV/file? I understand that in the previous release at least, the functionality of combining fractions/replicates was not available for DIA workflows, therefore necessitating the user to do it externally. Is this still the case?

Thank you!

**Comment by fedefratini** [comment]
Hi,

With a multipleCVs-DIA, I use MSConvertGUI to transform a raw file in a mzML file (1 file> 1 file) and no problems to use FragPipe
the only limitation you need to use the same windows for the different CVs, meaning you have to repeat exactly the same acquisition method just changing the CV (it would be nice to use different CVs for different mz range but not possible). Concerning replicates you need to manually annotate the 'experiment annotation file' to get in fragpipe analyst at least in some case (Volcano plot for example) the combination.

Best,

Federica

**Comment by fcyu** [comment]
For data with different CVs, please split the original raw file into single-CV mzML using https://github.com/PNNL-Comp-Mass-Spec/Thermo-FAIMS-to-MzML

Best,

Fengchao

**Comment by a-indra** [comment]
Hi Fengchao,
I have been using the converter you mentioned. My question is about recombining the fractions back into one sample and how this is most effectively done. Perhaps annotating the experiment annotation file as Federica has suggested is the solution, but I want to know how this recombination is performed. Is it done at the peptide level first?

**Comment by fcyu** [comment]
Yes, editing the experiment annotation file is one approach. Or you could write a R script to process the fractionated data. Here is a good discussion https://github.com/vdemichev/DiaNN/discussions/655#discussioncomment-5558536

Best,

Fengchao
