### ISSUE TITLE
Multi-site tmt-report file

### ISSUE THREAD

**Issue by tomonorikaneko** [Nesvilab/FragPipe#1375]
Hello,

I'd like to know how many sites are phosphorylated in

P28482_181_190_1_2_T185Y187

found in the multi-site tmt-report file.

In separate lines, there are

P28482_181_190_1_1_Y187
P28482_181_190_2_2_T185Y187

which should be singly and doubly phosphorylated peptides. But I am confused about "1_2_". Is it singly phosphorylated but localized to the two sites? The sequence in the peptide column is VADPDHDHTGFLtEyVATR.

Thank you,
Tomo

**Comment by anesvi** [comment]
1_2 should not happen. What version of FragPipe are you using?

**Comment by tomonorikaneko** [comment]
It was FragPipe version 19.1. I just tried version 21.0, and I did not find "_1_2_" sites anymore. However, it seems all residue numbers are shifted by one residue.

Version 19.1 or 20.0:
P28482_181_190_2_2_T185Y187 (correct residue numbers)

Version 21.0:
P28482_182_191_2_2_T186Y188 (one residue shifted?)

I used a same FASTA file between version 20 and 21. I see this shift for other sites as well. I can do more test runs to see if I made any mistake, but I wanted to let you know.

Thanks,
Tomo

**Comment by fcyu** [comment]
Hi Tomo,

Thank you very much for the bug report. We have located the bug and will release a fixed version soon.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Tomo,

We have fixed it in FragPipe 21.1. Could you try that version to see if it works well for you?

Thanks,

Fengchao

**Comment by tomonorikaneko** [comment]
Hi Fengchao,

I think 21.1 is working fine. Thank you for developing FragPipe.

Tomo

**Comment by fcyu** [comment]
Hi Tomo,

Thank you for the positive feedback. I will close this ticket.

Best,

Fengchao
