### ISSUE TITLE
PTM: decoy/target FDR

### ISSUE THREAD

**Issue by Carnegiexulab** [Nesvilab/FragPipe#1376]
- Describe the issue or question:

We would like to calculate target-decoy values specifically for PTM-modified peptides, rather than the entire dataset, which comprises both modified and unmodified peptides. Where can we locate the decoy matches for those PTM-modified peptides? Thanks.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Yes, you can try our group FDR: https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html. Please upgrade all tools to the latest version.

Best,

Fengchao

**Comment by anesvi** [comment]
I think that option would not help with group FDR for modified vs unmodified peptides. But philosopher has a tag to do it ( -- mods). I will look up the command and post here tomorrow. Or we should add a small tutorial. Also they can print decoys in the PSM file (check 'print decoys' box) and do their own FDR analysis.

**Comment by fcyu** [comment]
I added that part to the tutorial.

Best,

Fengchao

**Comment by anesvi** [comment]
Thanks. Let's make one change there - remove --prot 1 (so it is a more conventional case of one percent protein FDR filter). Also, we need to explain that philosopher will create 3 groups: unmodified peptides, peptides with the specified modifications only, and all other modifications. That way, FDR can be computed separately for 3 groups - unmodified, common PTMs (oxidation and n-term acetyl in this example) and rare PTMs (that is, everything else).

**Comment by fcyu** [comment]
Done.

**Comment by Carnegiexulab** [comment]
Dear team,

Thanks for your help!

Shouling
