### ISSUE TITLE
Protein and peptide probability filter

### ISSUE THREAD

**Issue by LKittinun** [Nesvilab/FragPipe#1377]
- Describe the issue or question:
I ran the LFQ-MBR workflow with all FDR = 0.01. However, in the report file, there were still proteins with protein prob or top peptide prob < 0.99. Should I further filter the result to >= 0.99, or was the file ready for downstream analysis already?

Thank you

**Comment by fcyu** [comment]
No, you do not need to filter the result again. They are ready for the downstream analysis. FDR and probability are two related but different things.

Best,

Fengchao
