### ISSUE TITLE
FragPipe 21 search failed while FragPipe 20 worked with same data.

### ISSUE THREAD

**Issue by WeiqiangChen** [Nesvilab/FragPipe#1378]
- Describe the issue or question:
## When I ran LFQ-MBR workflow with slight modification in FragPipe 21, it showed the following error and exited before finishing. 

_Exception in thread "main" java.lang.NumberFormatException: For input string: "0,2876"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source)
	at java.base/java.lang.Float.parseFloat(Unknown Source)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.percolatorToPepXML(PercolatorOutputToPepXML.java:340)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.main(PercolatorOutputToPepXML.java:59)
Process 'Percolator: Convert to pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 76 remaining tasks_

## The same files and settings worked fine with FragPipe 20. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-12-18_12-36-00_FragPipe20.zip](https://github.com/Nesvilab/FragPipe/files/13727471/log_2023-12-18_12-36-00_FragPipe20.zip)
[log_2023-12-20_13-30-35_FragPipe21.zip](https://github.com/Nesvilab/FragPipe/files/13727472/log_2023-12-20_13-30-35_FragPipe21.zip)

**Comment by fcyu** [comment]
I believe the error was due to two reasons:

1. Your computer has the configuration that uses `,` but not `.` as the decimal point.
2. The new version of Percolator decides to follow your computer's configuration, while the old version always used `.` as the decimal point.

Could you change the language and region configuration of your computer to make sure that it follows the common format, and try again?

Thanks,

Fengchao

**Comment by WeiqiangChen** [comment]
That is also my first impression. But I always set the decimal to "." not "," as this screenshot shows.
![image](https://github.com/Nesvilab/FragPipe/assets/45074535/470771b2-a43b-405e-a762-d6a227c2980f)
Maybe it uses my geolocation and sets it to "," ignoring the Windows settings.

**Comment by fcyu** [comment]
Can you change the format to `English (United States)`, **reboot** your computer, and try again?

Best,

Fengchao

**Comment by WeiqiangChen** [comment]
Now it works after following your suggestions.

Thanks!
WeiQiang

**Comment by fcyu** [comment]
Thanks for your positive feedback. Then, I will close this ticket.

Best,

Fengchao

**Comment by guoci** [comment]
@fcyu I think this error originates from MSBooster. There is no `Locale.setDefault(Locale.US);` in MSBooster, so MSBooster uses the user's locale. See https://github.com/Nesvilab/MSBooster/pull/4

**Comment by fcyu** [comment]
Then, why 1) version 20.0 does not have this issue? and 2) Percolator didn't crash?

Best,

Fengchao

**Comment by guoci** [comment]
From the log file, I can see the code is reading columns named either `bray_curtis` or `unweighted_spectral_entropy`, which is generated by MSBooster, not Percolator. https://github.com/Nesvilab/FragPipe/blame/develop/MSFragger-GUI/src/com/dmtavt/fragpipe/tools/percolator/PercolatorOutputToPepXML.java#L319-L340

**Comment by fcyu** [comment]
That's a good point! I also discovered that Percolator actually ignored those two scores generated by MSBooster

```shell
 Split1	 Split2	 Split3	FeatureName
 0.0000	 0.0000	 0.0000	rank
-1.0434	-0.9890	-0.9601	abs_ppm
-0.5347	-0.4921	-0.5887	isotope_errors
-1.1022	-1.2666	-1.2323	log10_evalue
 2.4467	 2.7693	 2.1834	hyperscore
 0.9478	 0.9381	 0.8122	delta_hyperscore
-1.4724	-1.8152	-1.4649	matched_ion_num
-0.3029	-0.2489	-0.2001	complementary_ions
 0.8369	 0.8655	 0.9377	ion_series
-0.5626	-0.5748	-0.5745	weighted_average_abs_fragment_ppm
-0.0206	-0.0032	-0.0253	length_7
 0.0359	 0.0078	 0.0164	length_8
-0.0196	-0.0007	 0.0033	length_9_30
 0.0312	-0.0106	 0.0122	length_31
 0.0000	 0.0000	 0.0000	ntt
-0.5792	-0.5953	-0.5584	nmc
 0.0000	 0.0000	 0.0000	charge_1
-0.0857	-0.0910	-0.1112	charge_2
 0.0443	 0.0551	 0.0618	charge_3
 0.0850	 0.0808	 0.1141	charge_4
 0.0744	 0.0480	 0.0445	charge_5
 0.0442	-0.0065	 0.0428	charge_6
 0.0000	 0.0000	 0.0000	charge_7_or_more
 0.0000	 0.0000	 0.0000	group_1
 0.0000	 0.0000	 0.0000	group_2
 0.0000	 0.0000	 0.0000	group_3
 0.0000	 0.0000	 0.0000	group_other
-0.1570	-0.1799	-0.1676	15.9949M
 0.6170	 0.7373	 0.5897	m0
```

Best,

Fengchao
