### ISSUE TITLE
IonQuant error in TMT16 workflow with Thermo raw but not mzml

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#1379]
Hello,
Thank you for all the updates in the new FragPipe v21.  I was curious to test out the new TMT Integrator version that uses IonQuant.  Running the default TMT16 workflow with ThermoRaw files, the analysis went almost to the end but I received a java ArrayIndexOutOfBoundsException error.  I have attached my full log file.

When I use mzxml files, the same workflow completes successfully. So not a high priority, but given IonQuant should in theory allow using ThermoRaw directly, I thought my observation might be helpful.

Best,
Todd

- Upload your log file
[log_2023-12-20_10-26-40.txt](https://github.com/Nesvilab/FragPipe/files/13730455/log_2023-12-20_10-26-40.txt)

**Comment by fcyu** [comment]
Hi Todd,

Thanks for the bug reporting. I guess IonQuant had some issue when extracting certain information from the raw file. Could you upload `2023Dec_37_F1.raw` to https://www.dropbox.com/request/com7mlVE2vQB5J5hONBA ? I will take a look and fix the bugs if there are any.

Best,

Fengchao

**Comment by enonimos** [comment]
Thanks Fenchao. File uploaded.

**Comment by fcyu** [comment]
Thanks for your raw file. The parent scan number information is not available in the raw file. I have fix this bug. If you want to test the fixed version, please send an email to yufe AT umich.edu. I will probably release a new version in a few days, as well.

Best,

Fengchao

**Comment by enonimos** [comment]
Thanks for the diagnosis, I will wait for the new version.
Todd

**Comment by prdawar** [comment]
Hello
I also ran into this same error. Attached is the log file for the respective run. The issue was also fixed by providing a .mzml file to FragPipe instead of using .mzml file generated by FragPipe itself as described above
[log_2024-05-23_11-51-29.txt](https://github.com/Nesvilab/FragPipe/files/15441761/log_2024-05-23_11-51-29.txt)
.

**Comment by fcyu** [comment]
Thank you for the feedback. We have fixed it and the next release will be available in a few days.

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed in the latest version.

Best,

Fengchao
