### ISSUE TITLE
How to set up experiment containing Fractions / groups / treatment/ replicates ?

### ISSUE THREAD

**Issue by May2020** [Nesvilab/FragPipe#138]
Dear Nesvilab/FragPipe group,

Thanks a lot for making FragPipe available for us! We really appreciation
This is a couple of general questions about FragPipe:

Question 1:
Are we allowed to set up fractions, technical/biological replicates, groups,  different treatments (e.g. control vs treatment) in FragPipe searches for experiments containing multiple MS runs?
If not, what is a practical and appropriate approach to do so based on your experience?

Question 2;
Is label-free function in FragPipe via spectrum counting or MS1 area under the curve ?

Question 3:
Will label-free function be able to support Thermo Raw File in the near future?

Best regards
Mei

**Comment by anesvi** [comment]
Dear Mei,

1)
You can assign a label to experiments, and then click on Multi-experiment report in the REPORT tab of FragPipe

If you have fractions from the same experiment, you can label them
file1.mzML   A
file2.mzML   A
file3.mzML   A
file4.mzML   B
file5.mzML   B
file6.mzML   B

The first 3 files will be combined in A, and the other 3 in B. You will have just 2 columns with spectral counts or intensity-based quantification, A and B.
You will see them in combined_protein.tsv file that will be generated. There will also be combined_peptide.tsv file.
If the files are biological replicates, and you want to keep it separate, then you can assign labels as
file1.mzML   A1
file2.mzML   A2
file3.mzML   A3
file4.mzML   B1
file5.mzML   B2
file6.mzML   B3

and you will have the summary table quantification separately for A1..A3, B1…B3

2)
Label-free function is precursor MS1 intensity-based. Spectral counts are always calculated by default.

3) For thermo, it is very easy to convert to mzML. So I am not sure if or when we would enable MS1-based quant in FragPipe from RAW Thermo data

Best
Alexey

**Comment by Nazrath10R** [comment]
I have a follow-up question about combining different MS fractions/runs.

The feature in FragPipe to do this is very elegant and I really like it. Is there a way this can be done using command line MS-Fragger and philosopher? I am guessing I have to run MS-Fragger for each fraction but how do I combine the pepXML's before philosopher?

Thank you for your time.
Naz

**Comment by prvst** [comment]
please read [this](https://github.com/Nesvilab/philosopher/issues/90#issuecomment-557176932)
