### ISSUE TITLE
Incompatible Windows region configuration breaks FragPipe 21.0

### ISSUE THREAD

**Issue by B0NAN** [Nesvilab/FragPipe#1381]
[log_2023-12-20_17-22-38.txt](https://github.com/Nesvilab/FragPipe/files/13730357/log_2023-12-20_17-22-38.txt)

Hi,
I updated to the latest version of fragpipe etc and after that I was not able to search for HLA peptides (open search) any more. When I reinstalled fragpipe v20 it worked again.
Please find the log attached.

Best regards,
Benedikt

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1378. Can you change the windows configuration according to https://github.com/Nesvilab/FragPipe/issues/1378#issuecomment-1864537724 and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment]
We have also tried to fix this problem in FragPipe 21.1. Could you try that version to see if it works for you?

Thanks,

Fengchao

**Comment by B0NAN** [comment]
Yes thank you, I will try it right away!
Best regards,
Benedikt

**Comment by B0NAN** [comment]
Dear Fengchao,
thank you for the update. However, FragPipe 21.1 had the same error. Now I adjusted the region settings according to your suggestion in #1378 (change region settings to USA, reboot), but the problem persists. 
I am sending the log attached.
[log_2023-12-21_11-40-18.txt](https://github.com/Nesvilab/FragPipe/files/13740452/log_2023-12-21_11-40-18.txt)
Best regards,
Benedikt

**Comment by B0NAN** [comment]
Hi again.
I tried again with the default HLA search settings and then it worked. So the problem might have been in the modified method that I copied from the FragPipe 20. 
So for me this problem is solved. Thank you for your support!
Cheers,
Benedikt

**Comment by fcyu** [comment]
> Dear Fengchao, thank you for the update. However, FragPipe 21.1 had the same error. Now I adjusted the region settings according to your suggestion in #1378 (change region settings to USA, reboot), but the problem persists. I am sending the log attached. [log_2023-12-21_11-40-18.txt](https://github.com/Nesvilab/FragPipe/files/13740452/log_2023-12-21_11-40-18.txt) Best regards, Benedikt

This error is due to a different reason. And it seems that you have figured it out.

Best,

Fengchao
