### ISSUE TITLE
Error with spectral library loading

### ISSUE THREAD

**Issue by kaupuks** [Nesvilab/FragPipe#1382]
- Describe the issue or question:

Could you help fix the error with spectral library loading (Dia_SecLib_Quant):
"Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on "
[log_2023-12-21_05-36-46.zip](https://github.com/Nesvilab/FragPipe/files/13734950/log_2023-12-21_05-36-46.zip)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Although we never saw this error before, I guess it is related to another OpenMS in your computer:

```shell
subprocess.CalledProcessError: Command '['C:\\Users\\LENOVO\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (C:\Program Files\OpenMS-3.0.0\share\OpenMS) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\pyopenms\share/OpenMS).
```

Could you uninstall the one in `C:\Program Files\OpenMS-3.0.0\share\OpenMS` and try again?

Thanks,

Fengchao

**Comment by kaupuks** [comment]
The same error was generated after uninstalling OpenMS.  MS data used for processing was acquired with Waters SynaptG2, MSE mode.
[log_2023-12-21_19-27-46.zip](https://github.com/Nesvilab/FragPipe/files/13744937/log_2023-12-21_19-27-46.zip)

**Comment by fcyu** [comment]
I am clueless now since it seems due to your specific computer environment.  Maybe @guoci can take a look to give some suggestions.

Best,

Fengchao

**Comment by guoci** [comment]
@kaupuks 
Can you try opening up Anaconda prompt, then type:
`pip install --upgrade --force-reinstall pyopenms`
I hope this reinstall will resolve the issue, if not you can try raising this issue at the OpenMS GitHub page.

**Comment by kaupuks** [comment]
Did not help, on another computer, when fresh installed, the same issue.

**Comment by fcyu** [comment]
Seems to be an issue with OpenMS. Maybe you can try contacting them https://github.com/OpenMS/OpenMS/issues

Best,

Fengchao
