### ISSUE TITLE
FragPipe 20.0 is not compatible with Philosopher 5.1.0

### ISSUE THREAD

**Issue by kbarylyuk** [Nesvilab/FragPipe#1383]
Upon processing two files acquired on an Orbitrap from TMTpro-labelled samples, the workflow ends with an error in the second 'PhilosopherFilter' process step:

```
PhilosopherFilter [Work dir: C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2]
...
ERRO[16:46:15] Cannot read file. open C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2\.meta\db.bin: The system cannot find the file specified. 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~

Cancelling 13 remaining tasks
```
I have seen a couple of closed issues with a similar error description where the suggested solution had something to do with re-enabling the disabled ProteinProphet. In this case, I have ticked the respective option in the validation tab.

Please, see the attached log file for details. Thank you for your assistance!

[log_2023-12-21_16-46-15.txt](https://github.com/Nesvilab/FragPipe/files/13743843/log_2023-12-21_16-46-15.txt)
![image](https://github.com/Nesvilab/FragPipe/assets/13316340/c8ddb014-2711-49d9-a1a3-f7f1f02ae0a6)

**Comment by fcyu** [comment]
I think you might messed up the files because there seems to be old `interact.pep.xml` files from your previous searching. 

```shell
PhilosopherFilter [Work dir: C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2]
C:\Users\user1\Downloads\FragPipe-jre-20.0\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe filter --sequential --picked --prot 0.01 --tag rev_ --pepxml C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2 --protxml C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\combined.prot.xml --probin C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set1 --razor
INFO[16:46:09] Executing Filter  v5.1.0                     
INFO[16:46:09] Fetching protein inference from C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set1 
INFO[16:46:09] Processing peptide identification files      
INFO[16:46:09] Parsing C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2\interact.pep.xml 
INFO[16:46:09] Parsing C:\Users\user1\Documents\SYMMETRY_FFvsFFPE_labelCheck\out\Set2\interact-20231004_KB_SYM_FFvsFFPE_TMT18-2_Set2_FFPE_labelCheck_4of10ul_90min_20231004165632.pep.xml 
```

Could you use a new result folder and start from scratch?

Thanks,

Fengchao

**Comment by kbarylyuk** [comment]
Thank you for getting back to me so promptly, Fengchao!
Following your suggestion, I have tried deleting the old output folder, creating a new one, and running a new processing. Unfortunately, the same error occurred.
[log_2023-12-21_17-36-51.txt](https://github.com/Nesvilab/FragPipe/files/13744183/log_2023-12-21_17-36-51.txt)

**Comment by fcyu** [comment]
Could you upgrade FragPipe to 21.1?

Best,

Fengchao
