### ISSUE TITLE
IonQuant 1.10.12 requantify error

### ISSUE THREAD

**Issue by csdaw** [Nesvilab/FragPipe#1387]
Hello, first I'll say thanks for the amazing software! I'm looking forward to trying DDA+ 😄 

- Describe the issue or question:

The default SILAC3 workflow (or likely any MS1 label workflow) fails at the 'requantify' step in the new IonQuant 1.10.12 (FragPipe 21.1, MSFragger 4.0 and Philosopher 5.1.0) with the following error:

```
2023-12-22 23:00:12 [INFO] - Re-quantifying P4_dependent_replicate_reverse_1 ...
2023-12-22 23:00:12 [INFO] - Re-quantifying P4_dependent_replicate_reverse_2 ...
2023-12-22 23:00:13 [INFO] - Combining experiments and estimating protein intensity...
java.lang.ArrayIndexOutOfBoundsException: Index -4573 out of bounds for length 4633
	at r.a(Unknown Source)
	at r.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2023-12-22 23:00:13 [ERROR] - Index -4573 out of bounds for length 4633
```

As a workaround, the workflow runs just fine if you untick 'requantify'. Furthermore, the error does not occur with IonQuant 1.9.8 (FragPipe 20.0, MSFragger 3.8 and Philosopher 5.0.0).
 
Thanks,
Charlotte

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2023-12-22_23-00-13.zip](https://github.com/Nesvilab/FragPipe/files/13757270/log_2023-12-22_23-00-13.zip)

**Comment by fcyu** [comment]
Hi Charlotte,

Thanks for the bug reporting. Could you share your mzML and fasta files with me to reproduce the bug? Here is the link to upload the files: https://www.dropbox.com/request/Dqw4R44sptTqttsRXpJK

Thanks,

Fengchao

**Comment by csdaw** [comment]
Sure thing, I'll upload them now.

**Comment by fcyu** [comment]
Thank you for the files. I have fixed the bug. If you want to try the pre-released version, please send an email to yufe AT umich.edu.

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed in the latest version.

Best,

Fengchao
