### ISSUE TITLE
No MaxquantLFQ

### ISSUE THREAD

**Issue by Amelia811** [Nesvilab/FragPipe#1389]
- Describe the issue or question:
Hi, 
I processed two data files of TimsTOF using FragPipe and checked the MaxLFQ. But the result of combined protein contains no MaxLFQ intensity columns. Can you please tell me why?
I applied the LFQ-MBR workflow and set the Quant(MS1) as defaults.
![1703749268642](https://github.com/Nesvilab/FragPipe/assets/155048109/d82feec9-fbc8-41f4-ab7b-6ce2ebd6e528)

Thank you,
Bing

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by Amelia811** [comment]
I found the reason in the log file. It says: There are only 2 experiments. Will not calculate MaxLFQ intensity.
So can you please tell why it can not calculate MaxLFQ intensity when there are only 2 experiments?
Thank you.

**Comment by fcyu** [comment]
That's because MaxLFQ calculates ion-level log-ratios of two experiments pair-wisely. If there are only two experiments, there won't be many ions having log-ratios, which results in many missing MaxLFQ intensities.

Best,

Fengchao
