### ISSUE TITLE
Corrupted Files

### ISSUE THREAD

**Issue by kebincao** [Nesvilab/FragPipe#1390]
- Describe the issue or question:
Hello, I am rerunning searches on fragpipe with raw files previously ran, having no issues. In running my new searches, the job is terminating during spectral files check. Is this an issue with Java or the actual raw files themselves? Thanks in advance for the help. I am running these searches on Fragpipe v20 with MSFragger at v3.8.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-12-28_08-46-56.zip](https://github.com/Nesvilab/FragPipe/files/13788125/log_2023-12-28_08-46-56.zip)

**Comment by fcyu** [comment]
This was because the Raw file reader could not start normally. Could you restart the computer and try again? If the error persist, could you convert the raw files to mzML format: https://fragpipe.nesvilab.org/docs/tutorial_convert.html ?

Best,

Fengchao

**Comment by kebincao** [comment]
Hi Fengchao,

Thanks for your reply. Rebooting the computer solved the issue.

I appreciate the help.

Kevin

**Comment by fcyu** [comment]
No problem. I will close this ticket but feel free to contact us if you have any other questions.

Best,

Fengchao
