### ISSUE TITLE
Request: mokapot for PSM validation

### ISSUE THREAD

**Issue by dimitri726** [Nesvilab/FragPipe#1391]
- Describe the issue or question: Hello, I was wondering if it would be possible to implement the relatively new _mokapot_ algorithm for PSM validation (building off of the Percolator workflow). If not, is there a way I can test this with MSFragger search results myself? Link to original publication: https://pubs.acs.org/doi/10.1021/acs.jproteome.0c01010.

**Comment by fcyu** [comment]
Yes, the output `*.pin` file is supported to be compatible with both Percolator and Mokapot.

We are also discussing internally to add Mokapot to FragPipe. But, may I ask why do you want to use Mokapot but not the Percolator?

Best,

Fengchao
