### ISSUE TITLE
INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by TimKarr** [Nesvilab/FragPipe#1392]
RAW files do not load..., e.g., 
UNAVAILABLE: io exception
C:\138tissues_RAWfiles\ND_lymph80_18-17.raw: Scans = 0; Isolation sizes = []
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by danielgeiszler** [comment]
Please try moving the files to a different location that isn't in your C: folder.

Also, please upload the entire log if issues persist.
