### ISSUE TITLE
 Cannot read file. open \.meta\db.bin: The system cannot find the file specified

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1396]
- Describe the issue or question:
Hi,
I keep having this problem after I updated Fragpipe with the newest Philosopher version (v5.1.0_Windows_amd64). 
First I thought there was something wrong with the raw file. So I removed that raw file but the same problem happened again. 
Could you please help me with this? Thank you so much.
Best,
Trung
- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-01-05_00-00-15.txt](https://github.com/Nesvilab/FragPipe/files/13841008/log_2024-01-05_00-00-15.txt)
[log_2024-01-04_23-24-25.txt](https://github.com/Nesvilab/FragPipe/files/13841009/log_2024-01-04_23-24-25.txt)

**Comment by fcyu** [comment]
Hi Trung,

Philosopher 5.1.0 it not compatible with the old FragPipe (version 20.0). Could you please upgrade FragPipe to the latest version 21.1, and try again?

Thanks,

Fengchao

**Comment by trungttt** [comment]
Thank you so much Fengchao.
