### ISSUE TITLE
 How to understand the quantitative information of DIA analysis?

### ISSUE THREAD

**Issue by yangxinzhi** [Nesvilab/FragPipe#1398]
- Describe the issue or question:
Hi, after I finished DIA analysis using DIA_SpecLib_Quant module of fragpipe. I would like to ask if the quantitative information form for getting multiple DIA files integrated has been standardized /normalized(i.e. taking into account the reasons for the different loading quantities). In addition, which module of DIA_SpecLib_Quant or DIA_DIA-Umpire_SpecLib_Quant is more suitable for analyzing DIA data?
![image](https://github.com/Nesvilab/FragPipe/assets/125720871/e4687bdb-abd4-408a-8c60-5d549653f1f0)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
> I would like to ask if the quantitative information form for getting multiple DIA files integrated has been standardized /normalized(i.e. taking into account the reasons for the different loading quantities)

If you are using the `_matrix.tsv`, then yes.

>  In addition, which module of DIA_SpecLib_Quant or DIA_DIA-Umpire_SpecLib_Quant is more suitable for analyzing DIA data?

`DIA_SpecLib_Quant` is suitable for most data except for the nonspecific digested ones. `DIA_DIA-Umpire_SpecLib_Quant` is suitable for the nonspecific digested data.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
Can I ask what method is used for the normalization of the merged data? If i delete a sample later in the analysis or filter the data by 50%, do I need to re-normalize it (like using the median normalization)? In addition, do you mean that DIA_SpecLib_Quant can be selected when  using trypsin to digestion?
![image](https://github.com/Nesvilab/FragPipe/assets/125720871/37eb3b45-502f-470b-81dd-dfcee005d71c)
![image](https://github.com/Nesvilab/FragPipe/assets/125720871/f0f6c22c-e5d3-4f2f-ba2b-fd20c05e4bf8)
Like the photo I uploaded, I would like to ask whether W8-15 in the picture is caused by poor biological duplication rather than by different loading quantities.

**Comment by fcyu** [comment]
> Can I ask what method is used for the normalization of the merged data?

The quantification is performed by DIA-NN. Here (https://github.com/vdemichev/DiaNN) has the detailed information. The following is quoted from the README

> **Q: What is normalisation and how does it work?**  
> **A:** The purpose of normalisation is to cancel out some of the undesirable effects which can occur during sample preparation and acquisition. For example, pipetting errors can result in different total amounts being injected, and thus signals of different intensity being recorded by the mass spec. The basic global normalisation addresses this. It should in general be used under the following assumption: when only considering 'biological' variability of interest, most of the peptides are not differentialy abundant, or the numbers of upregulated / downregulated (in comparison to experiment-wide averages) peptides in each sample are about the same. If this condition is not satisfied (e.g. when analysing fractions obtained with some separation technique, like SEC, for instance), then normalisation should not be used.  
>   
> DIA-NN also supports a more advanced normalisation method, which is enabled by default: RT-dependent normalisation. Sometimes, undesirable technical effects can lead to some samples having either hydrophilic or hydrophobic peptides depleted, relative to other samples. These effects are corrected by RT-dependent normalisation. Potentially it might also correct for spray stability issues. 
>   
> The choice of the normalisation strategy in DIA-NN determines the way .Normalised and .MaxLFQ quantities (in the main report), as well as values in output matrices are calculated. So if normalisation is disabled, these quantities are actually non-normalised.  


> If i delete a sample later in the analysis or filter the data by 50%, do I need to re-normalize it (like using the median normalization)?

Normally, you don't need to.

> In addition, do you mean that DIA_SpecLib_Quant can be selected when using trypsin to digestion?

Yes

> Like the photo I uploaded, I would like to ask whether W8-15 in the picture is caused by poor biological duplication rather than by different loading quantities.

I don't know. We normally only answer questions related to our software.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
Therefore, the DIAmerge result provided by fragpipe generally used the DIA-NN value of .MaxLFQ quantities？

**Comment by fcyu** [comment]
More precisely speaking, the quantification tables you are looking at is from DIA-NN. And the intensities in the `*_matrix.tsv` table is form DIA-NN's MaxLFQ intensities.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
When I ran the DDA data before, the final merged result would have two values, including Normalised and.MaxLFQ value.I remember using the same data, using the Normalised values method to get non-zero values is significantly higher. MaxLFQ value. The MaxLFQ value  is more strict right? Then I found a small problem. When using DIA analysis, FWHM was reported in a PDF, but I didn't seem to see it in DDA report.

**Comment by fcyu** [comment]
If you were using the LFQ-MBR workflow for the DDA data, the quantification was perform by IonQuant. The DDA LFQ and DIA use totally different tools to perform quantification.

> The MaxLFQ value is more strict right?

Sort of.

> Then I found a small problem. When using DIA analysis, FWHM was reported in a PDF, but I didn't seem to see it in DDA report.

The PDF is generated by DIA-NN for DIA only.

Best,

Fengchao

**Comment by yangxinzhi** [comment]
ok. Thank you very much for your help!
