### ISSUE TITLE
MSFragger Wide Window Acquisition (WWA) information

### ISSUE THREAD

**Issue by dimitri726** [Nesvilab/FragPipe#1399]
Hello,

We are interested in benchmarking MSFragger WWA against Thermo Proteome Discoverer with CHIMERYS for wide window acquisition (WWA) data, but I cannot find much information on the MSFragger workflow for WWA. If possible, can you please provide an overview on how the WWA workflow in MSFragger/FragPipe works? I've run a couple test searches and it seems to incorporate DIA-NN somehow? Also interested in how the identified peptides from chimeric spectra are quantified. Please let me know if I can provide any additional information or results from my test searches if that would be helpful.

Thanks!

**Comment by fcyu** [comment]
> If possible, can you please provide an overview on how the WWA workflow in MSFragger/FragPipe works?

It is quite easy to use WWA in FragPipe. You just need to load the `WWA` workflow and assign your LC-MS files as `DDA+` data type. MSFragger basically search the peptides within the whole isolation window, and then do the score refining. We will have a paper describing it in the future.

> I've run a couple test searches and it seems to incorporate DIA-NN somehow?

No, it does not rely on DIA-NN. If you have MSBooster enabled, it use DIA-NN's spectral prediction module to predict intensities and retention times. Those two are used to calculate two additional scores. Disabling MSBooster will also work, just the sensitivity is a litter lower because those two additional scores are missing. The whole workflow does not use any identification or quantification parts from DIA-NN.

> Also interested in how the identified peptides from chimeric spectra are quantified.

They are quantified by IonQuant.

Best,

Fengchao

**Comment by anesvi** [comment]
Hi Dimitri, once you finish your comparisons, let us know the results. You can email us directly. As Fengchao said, DDA+ mode is a natural addition to MSFragger. MSFragger is really a universal spectrum-centric strategy for searching any data (DDA or DIA data), so it naturally allows treating DDA data as a reduced version of DIA data when searching (I.e., doing full isolation window search).

**Comment by TomasKoudelka** [comment]
Dear Nesvilab,
I am also curious regarding WWA to increase the number of identifications in my DDA runs from the spectral library. We are using 4 Da windows and so we should also pick up multiple peptides within this window settings during the DDA runs.  
@fcyu commented that running the WWA workflow and changing the DDA files to DDA+ files, will suffice for this. However, The MSFragger settings do not change when you load the "WWA workflow" . Does the software simply take the spectra information and can determine how wide the window is automatically during the search of the DDA files? Also how would this work if you would like to quantify or do the "DIA_SpecLib_Quant", is simply changing the files to DDA+ files enough and then they are searched in the correct way automatically?

Ultimately I would like to run both "direct" DIA and Hybrid DIA searches (preferably with DDA+ files to identify more in my DDA runs), would one have to change anything in the DIA quantification tab for these two different searches? For example would one untick the "Replace library spectra with predicted" for the hybrid search or would this be left checked. Would one have to first build the library with WWA workflow and have the DIA-Quant unchecked and then load the spectral library during the DIA_SpecLib_Quant search? (Sorry this is a separate question that might have been already answered in a separate thread).

**Comment by fcyu** [comment]
Hi @TomasKoudelka ,

First of all, I would like to clarify that WWA and DDA+ are still DDA not DIA.

> The MSFragger settings do not change when you load the "WWA workflow" . Does the software simply take the spectra information and can determine how wide the window is automatically during the search of the DDA files?

If there are `DDA+` data type in FragPipe, FragPipe will generate the MSFragger parameter file with `data_type = 3` to let MSFragger perform DDA+ search. MSFragger reads the isolation window ranges from the LC-MS file automatically. 


> Also how would this work if you would like to quantify or do the "DIA_SpecLib_Quant", is simply changing the files to DDA+ files enough and then they are searched in the correct way automatically?

DDA+ is still DDA, not DIA. For DDA and DDA+ MS1-based quantification, you could use IonQuant. If your data is DIA from wide or narrow isolation window, please set the data type to `DIA` and load the `DIA_SpecLib_Quant` workflow.

Please note that if there are both DDA/DDA+ and DIA data, and you loaded the `DIA_SpecLib_Quant` worklow, the DDA/DDA+ data will only be used to build the spectral library, not for quantifications. The quant is only from the DIA data.

> Ultimately I would like to run both "direct" DIA and Hybrid DIA searches (preferably with DDA+ files to identify more in my DDA runs), would one have to change anything in the DIA quantification tab for these two different searches? For example would one untick the "Replace library spectra with predicted" for the hybrid search or would this be left checked. Would one have to first build the library with WWA workflow and have the DIA-Quant unchecked and then load the spectral library during the DIA_SpecLib_Quant search? (Sorry this is a separate question that might have been already answered in a separate thread).

You don't need to change anything in the DIA quant tab. You can load both DIA and DDA data, assign the correct data types, load the `DIA_SpecLib_Quant` workflow, and perform the analysis.

Best,

Fengchao

**Comment by TomasKoudelka** [comment]
@fcyu 

Thank you for your quick reply! Exactly I have DIA files too, however, I also wanted to add DDA files (DDA+) for the library based search. 

> You don't need to change anything in the DIA quant tab. You can load both DIA and DDA data, assign the correct data types, load the `DIA_SpecLib_Quant` workflow, and perform the analysis.

Ok great. Yeah there is so many things that one can "tick" I wasn't sure if something needed to be changed if one has DIA only files or if one wanted to search DIA + DDA files (DDA files to extend the library), so a "hybrid" search. It is great to know that one does not need to change anything here.
