### ISSUE TITLE
Non-Specific search & Open search & precursor charges

### ISSUE THREAD

**Issue by May2020** [Nesvilab/FragPipe#140]
Dear Prof. Nesvizhskii and your group,

I have some MS runs of samples containing only small peptides (instead of digestion by trypsin) extracted from my material. 
Now my question is:
1.  should I run non-specific search at least ? is it possible to combine non-specific search along with open search ? if not, what is the best strategy would you suggest?
2. we also have some MS2 spectra generated from precursor ions with +1 charges. Is there any settings I need change for these special spectra?

thanks a lot for your great help
Mei

**Comment by fcyu** [comment]
Hi Mei,

1. You may try with non-specific search. You can even try non-specific open search, but the sensitivity may not be high. It really dependent on your database and sample.

2. I don't think you need to change anything.

Best,

Fengchao

**Comment by May2020** [comment]
Dear FengChao,

Thanks a lot for your answer!
I will try now. 

Have a nice weekend!
Mei
