### ISSUE TITLE
Distinguish between different modifcations on the same residue in TMT-report

### ISSUE THREAD

**Issue by SjoerdvanderPost** [Nesvilab/FragPipe#1402]
I'm analyzing a TMT labelled differential alkylated data set in which the cysteines are chemically modified with two different alkylating reagents. 

Unfortuantly this information is lost when I generate a TMT-report (multi- or single site) and only the modified cysteine is indicated (lower case) but not the type of modification. I can generate two individual reports, but in some case peptides include two cysteines that have different modifications. I was wondering if there is an solution for this issue, or if this can be considered in future updates.

Thanks,
Sjoerd

**Comment by fcyu** [comment]
It I remember it correctly, TMT-Integrator does not support different modifications on the same amino acid. You have to run the program twice.

Best,

Fengchao

**Comment by SjoerdvanderPost** [comment]
Dear Fengchao,

Thanks for the quick reply. I will find workaround for now. I will probably generate a third report to identify the differentially labelled peptides. 

Best,
Sjoerd
