### ISSUE TITLE
Analyze samples separately/generate a separate spectral library for each experiment in a DIA_SpecLib_Quant workflow, as in FragPipe v20 and older 

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#1403]
- Describe the issue or question:
In prior versions of FragPipe, if multiple experiments were specified in a DIA_SpecLib_Quant workflow, there was a warning dialog that would pop up upon hitting "Run" that warned that, unless the experiment designations were changed, separate spectral libraries would be generated for each separate experiment. I noticed that the program no longer does this, and there are no longer separate folders with separate spectral libraries for each experiment designation. From the log of my recent run, I also see: "Experiment/Group: (if "spectral library generation" is enabled, all files will be analyzed together)".

I might just be not seeing a checkbox somewhere to do this, but is it possible to activate the old default, in which a separate spectral library is created for each experiment and experiments are analyzed separately? I ask because when we search multiple yeast or other QC samples, I want them searched separately, rather than together. As a hypothetical example, if I have some troubleshooting to do on the instrument and I run pre- and post-fix QCs, the pre-fix QC protein IDs and performance will look better than it really was, because the spectral library includes the post-fix file. 

Thanks,
Josh

- Upload your log file
[log_2024-01-10_12-06-37.txt](https://github.com/Nesvilab/FragPipe/files/13891058/log_2024-01-10_12-06-37.txt)

**Comment by jossmi** [comment]
Here's my manifest for the run from which I attached the log file, showing that I specified separate experiments, although that doesn't seem to be reflected in the log.

[manifest.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/13891189/manifest.fp-manifest.txt)

**Comment by anesvi** [comment]
We decided to make the change as it simplifies creating annotation files for downstream analysis. Unfortunately you need to find a way to deal with it. Fell free to contact me directly. Alexey
