### ISSUE TITLE
Experiments starting with `lib` are not included in the tsv report.

### ISSUE THREAD

**Issue by kabalak** [Nesvilab/FragPipe#1404]
Hi,

I am using FragPipe 21.1 and doing a semi-specific query with a lot of different experiments, DDA-mode, nothing fancy altered in the analysis settings. Attached is the log and the files manifest file for the query - you can see an experiment called "Lib". This experiment does not appear in the combined files, but the original experiment results are written into the folder and are there:
![EXP_Folder](https://github.com/Nesvilab/FragPipe/assets/75732067/2bca1d45-c6b7-41f0-b7fe-66c6b9f3168b)
![EXP_Folder_Contents](https://github.com/Nesvilab/FragPipe/assets/75732067/67d8ef6e-1d77-417f-8863-1c9ee18eb5bb)

This experiment is missing from **all** gathered reports (combined_protein/peptide/ion.tsv), all other experiments are present there:
![Lib_Missing_In_Reports](https://github.com/Nesvilab/FragPipe/assets/75732067/0ce0990c-ec71-4a68-93fa-83bf0f306b06)

Where did it disappear?!? Or did I hid a bare word in the FragPipe code? ;-)

[log_2024-01-10_18-03-52.txt](https://github.com/Nesvilab/FragPipe/files/13893966/log_2024-01-10_18-03-52.txt)
[fragpipe-files.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/13893971/fragpipe-files.fp-manifest.txt)

**Comment by fcyu** [comment]
Ah, yes. This is an undocumented feature (sorry about that. I will add it to the tutorial). 

The LC-MS files with the experiment name starting with `lib` will not be used in the intensity normalization and reporting. They will only be used as "library" during MBR. 

This is originally for the single-cell applications where there are single-cell injections and, then, bulk-cell injections as library (See Fig. 4 and Table 4 in https://www.mcponline.org/article/S1535-9476(21)00050-5/fulltext#secsectitle0095). In this case, people only care about the single-cell intensities and don't want the bulk-cell ones messed up the normalization. 

In the log, there is also a message `2024-01-10 18:03:35 [INFO] - 231204_hsPlasma-T-PICS_Lib_100ng is a library run. Skip transferring ions to it.` indicating that.

Best,

Fengchao

**Comment by kabalak** [comment]
Ok, just to clarify, the experiment name needs to start with "**lib**" or should it not contain any name fragments with **lib**?

**Comment by fcyu** [comment]
Any name starts with `lib` and case insensitive, such as `lib`, `library`, `Lib`, `Library`, `lib2`, etc.

Best,

Fengchao
