### ISSUE TITLE
Output content and MS2 spectra export

### ISSUE THREAD

**Issue by alyssaxin** [Nesvilab/FragPipe#1405]
Hello,

I would like to ask whether all files required to upload to PRIDE is already available in the output folder, and also whether annotated MS2 spectra can be directly exported? Do I need to have the MS2 spectra open in PDV viewer to export it or is there another way to download it?

Thanks,
Alyssa

**Comment by fcyu** [comment]
Hi Alyssa,

FragPipe does not generate all files required for the "complete submission", but you can do a "partial submission" which actually is what most datasets have. I barely see a "complete submission" dataset when I browser PRIDE. Maybe the PRIDE team should adopt commonly used tools' output format, not the other way around.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Hi Fengchao,

Thanks for your speedy response. Can I also ask about the MS2 export, whether it is possible to retrieve MS2 spectra once I have closed the run on FragPipe?

Thanks a lot,
Alyssa

**Comment by fcyu** [comment]
Do you mean open the FragPipe-PDV for the old/existing result? Yes, just put the folder path to the `ourput dir` and then click `Open FragPipe-PDV viewer`.

Best,

Fengchao

**Comment by alyssaxin** [comment]
Thanks so much!

Alyssa

**Comment by fcyu** [comment]
No problem. I will close this issue but feel free to contact us if you have any questions in the future.

Best,

Fengchao
