### ISSUE TITLE
Analyzing SILAC data acquired using DIA

### ISSUE THREAD

**Issue by HYTang69** [Nesvilab/FragPipe#1406]
Hi,
I have acquired a SILAC (heavy Lys8 and Arg10) dataset using DIA and would like to use FragPipe Quant DIA to process the data. I saw the plex DIA check box, but not sure what I should enter in the Light and Heavy fields.

Also, I have fractionated each sample into 10 fractions. How should I enter the fraction information in the workflow? The file input fractions only have Path, Experiment, Bioreplicate and Data type.

Thanks!
Hsin-Yao

**Comment by fcyu** [comment]
The following is from the tooltip. Let me know if you have any questions
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/c9f7269c-10a4-4c4d-9df2-eab1cafa1371)

> How should I enter the fraction information in the workflow?

No, we don't support it.

Best,

Fengchao

**Comment by HYTang69** [comment]
Thanks! Also, do I need to change any parameters in the MSFragger tab, e.g., add the heavy Lys and Arg as variable modifications?

**Comment by fcyu** [comment]
Yes, you need to add the variable modifications in the MSFragger tab.

Best,

Fengchao

**Comment by HYTang69** [comment]
Thanks again. I am wondering which is the the best file to obtain the SILAC ratio. It seems only the diann output files have quantitation values. Is report.pr_matrix_channels.tsv the best file to work on?

**Comment by fcyu** [comment]
Yes, the quantification results are in the DIA-NN output since DIA-NN is used to extract the intensities.

Best,

Fengchao
