### ISSUE TITLE
Error in Windows when building library using easypqp

### ISSUE THREAD

**Issue by Miracheng** [Nesvilab/FragPipe#1407]
- Describe the issue or question:
I found the same error as #210  when trying to build a spectral library using DDA files.

"easypqp, version 0.1.42
Error: No PSMs files present. Need to have tag 'psmpkl' in filename.
Library not generated, not enough peptides could be found for alignment.
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
"
I am running on a Windows system, and I uninstall and install the fixed EasyPQP using the following command:
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master

But errors still exist. What should I do? thank you 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-01-16_00-00-21.txt](https://github.com/Nesvilab/FragPipe/files/13941071/log_2024-01-16_00-00-21.txt)

**Comment by guoci** [comment]
@Miracheng can you also post the file `E:\fragpipe\0115mzml_git\filelist_speclibgen.txt`?

**Comment by Miracheng** [comment]
> @Miracheng can you also post the file `E:\fragpipe\0115mzml_git\filelist_speclibgen.txt`?

[filelist_speclibgen.txt](https://github.com/Nesvilab/FragPipe/files/13945121/filelist_speclibgen.txt)
