### ISSUE TITLE
timstof driverd uncalibrated.mzML

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1409]
Dear author, hello! Thank you very much for developing such a great tool.

During my use, I found that searching the timstof format data would generate a file with the suffix uncalibrated.mzML. What is the purpose of this file? Can I use this file instead of the original timstof file in another protein database search software?

Looking forward to your reply and assistance!!!

Best wishes
 Msong

**Comment by fcyu** [comment]
> What is the purpose of this file?

That file is used by other modules, such as MSBooster, PTMProphet, and EasyPQP, in FragPipe.

> Can I use this file instead of the original timstof file in another protein database search software?

For peptide identification, you can. For quantification, you can't.

Best,

Fengchao

**Comment by amingson** [comment]
> > What is the purpose of this file?
> 
> That file is used by other modules, such as MSBooster, PTMProphet, and EasyPQP, in FragPipe.
> 
> > Can I use this file instead of the original timstof file in another protein database search software?
> 
> For peptide identification, you can. For quantification, you can't.
> 
> Best,
> 
> Fengchao


Thank you for your help! In addition, the software I need to use is pFind. Considering that pFind cannot directly identify peptide segments in timstof files, I am considering using this uncalibrated.mzML file. According to your description, am I able to use it in this way?

Best,
Msong

**Comment by fcyu** [comment]
Yes, you can use uncalibrated.mzML for pFind.

May I ask why you bother running pFind since FragPipe has already given you a good result? Do you just want to compare the IDs of two software?

Best,

Fengchao

**Comment by fcyu** [comment]
If you like, I can take a look to see what made "The running of uncalibrated.mzML generated by msfragger was not very smooth". But no pressure.

Best,

Fengchao
