### ISSUE TITLE
Philosopher filter -- /.meta/db.bin: no such file or directory

### ISSUE THREAD

**Issue by arpansahoo** [Nesvilab/FragPipe#1411]
- Describe the issue or question:
I am running Fragpipe 20.0 with all the latest versions of Philosopher, IonQuant, MSFragger. I am using the provided iTRAQ4.workflow. 

It seems to break at the philosopher filter step, giving me an error of 
```
"Cannot read file. open /work/pi_gblanck/Arpan/OV-CPTAC2/fragpipe-results-OV-TCGA-mini/TCGA_61_1727_01A_25_1323_01A_36_1580_01A_Proteome_JHUZ_20130802/.meta/db.bin: no such file or directory"
```

I am running on a sample set of just 5 .mzML files, 3 of which belong to one plex and the other 2 belong to a second plex. Strangely, the .meta/db.bin was created in the first plex's folder, but not in the second one, which is causing this error.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

Logfile:
[out.17604284.zip](https://github.com/Nesvilab/FragPipe/files/13955164/out.17604284.zip)

**Comment by dpolasky** [comment]
Please update FragPipe to version 21 to use with the latest versions of the tools. You can find the download here: https://github.com/Nesvilab/FragPipe/releases

Best,
Dan

**Comment by arpansahoo** [comment]
> Please update FragPipe to version 21 to use with the latest versions of the tools. You can find the download here: https://github.com/Nesvilab/FragPipe/releases
> 
> Best, Dan

Thanks Dan. Would be happy to switch to v21, but when I tried v21, I was having issues with IonQuant (was giving me a NullPointerException at some point while running Fragpipe). I'm trying to use v20 because the TMT-Integrator doesn't default to using IonQuant. Unless there's another way to work around that?

**Comment by fcyu** [comment]
@arpansahoo Regarding the IonQuant error, could you share the log file?

In v21, you can still use Philosopher when doing TMT by using the `intensity extraction tool` dropdown menu in hte `Quant (Isobaric)` tab.

Best,

Fengchao

**Comment by arpansahoo** [comment]
For switching to `Quant (Isobaric)`, how can I do that in a workflow file? I am using Fragpipe from the CLI on a Linux HPC environment.

As for IonQuant error, here is log file:
I am actually getting a different IonQuant error with this small set of .mzML files. I would have to re-run Fragpipe v21 on my bigger set of ~2000 mzML files to replicate the original error. The new error is "The number of --annotation does not match the number of --psm."
[out.17604741.zip](https://github.com/Nesvilab/FragPipe/files/13955666/out.17604741.zip)

**Comment by fcyu** [comment]
> For switching to Quant (Isobaric), how can I do that in a workflow file? 

tmtintegrator.extraction_tool=Philosopher

> The new error is "The number of --annotation does not match the number of --psm."

Something might be wrong with your configurations/settings. Could you share `/work/pi_gblanck/Arpan/OV-CPTAC2/fragpipe-results-OV-TCGA-mini/filelist_ionquant.txt`?

Thanks,

Fengchao

**Comment by arpansahoo** [comment]
> Something might be wrong with your configurations/settings. Could you share `/work/pi_gblanck/Arpan/OV-CPTAC2/fragpipe-results-OV-TCGA-mini/filelist_ionquant.txt`?

```
flag	value
--psm	TCGA_13_2065_01A_61_1918_01A_61_2613_01A_Proteome_JHUZ_20130625/psm.tsv
--psm	TCGA_61_1727_01A_25_1323_01A_36_1580_01A_Proteome_JHUZ_20130802/psm.tsv
--specdir	/work/pi_gblanck/Arpan/OV-CPTAC2/mzML-files/PDC000113/1/Processed-Mass-Spectra/TCGA_61-1727-01A_25-1323-01A_36-1580-01A_Proteome_JHUZ_20130802
--specdir	/work/pi_gblanck/Arpan/OV-CPTAC2/mzML-files/PDC000113/1/Processed-Mass-Spectra/TCGA_13-2065-01A_61-1918-01A_61-2613-01A_Proteome_JHUZ_20130625
```

**Comment by fcyu** [comment]
Thanks for the file. It seems that although there were two experiment groups, FragPipe only found one `annotation.txt` from `TCGA_61-1727-01A_25-1323-01A_36-1580-01A_Proteome_JHUZ_20130802` but not `TCGA_13_2065_01A_61_1918_01A_61_2613_01A_Proteome_JHUZ_20130625`. If there is a `annotation.txt` in the second one, I am not sure what caused the issue. I don't think we changed anything regarding locating the annotation.txt between version 20.0 and 21.1.

Best,

Fengchao
