### ISSUE TITLE
The output of combined_site from Fragpipe V21.1

### ISSUE THREAD

**Issue by Amelia811** [Nesvilab/FragPipe#1412]
- Describe the issue or question:
Hi, when I used the workflow "LFQ-phospho" in FragpipeV21.1, I got the output of combined_site_STY79.9663 and also the comnbined_stie_M15.9949 (I set the variable modifications of STY phospho and M oxidation).  When I used the workflow "LFQ-MBR", there is no output of combined_site_M or other variable modifications I set such as ubiquitination. I can find modified peptides in the output of combined_modified_peptides, but there is no information of site probability. How can I get the output of combined site and the information of site probability if I am doing identification and quantification for other modifications not phosphorylation.
By the way, if I set the the min site localization probability as 0.75 in the MS1 quantification module, are all the modified peptides listed in the output of combined_modified_peptides have min localization probability 0.75?

Thank you.  

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by Amelia811** [comment]
OK，thanks！
Another issue: When I used the workflow of DIA_SpecLib_Quant_Phospho in FragPipeV21.1, I confirmed that the PTM site localization in the "Validation" tab is enabled, but I did not find the output of combined site reports. I only found the "report.pr_matrix" in the folder "diann-output", this report contains phospho modified peptides and localization prob without filtering. There seems no information of site position in the protein and no site quantification.  I attached the validation settings and the report.pr_matrix. Can I get a report like "combined site report" from DIA SpecLib_Quant_Phospho-analysis? 
![1705542642423](https://github.com/Nesvilab/FragPipe/assets/155048109/8d8ab60e-eefb-44de-bf7f-f520106d39ea)

![1705542767660](https://github.com/Nesvilab/FragPipe/assets/155048109/422fd499-083c-483c-97e6-4e55a693430a)

**Comment by anesvi** [comment]
We do not have it implemented yet. We will add in the future.

**Comment by fcyu** [comment]
The combined_site reports are generated by IonQuant for the **DDA** LFQ-MBR. For DIA, as you also found out, we have the site localization probability in the DIA-NN's quant report but not filtered. Maybe we should generate a new set of combined_site report for DIA too. 

Best,

Fengchao

**Comment by Amelia811** [comment]
Thanks!

**Comment by TeckYewLow** [comment]
I have a (i) phosphorylation datasets generated by DDA and another corresponding full proteome datasets generated by DIA. How I can I use FragPipe or FragPipe Analyst to assess the phosphorylation site occupancy?

**Comment by fcyu** [comment]
You should analyze DDA and DIA separately. Here are two tutorials that might be helpful 

https://fragpipe.nesvilab.org/docs/tutorial_lfq.html 
https://fragpipe.nesvilab.org/docs/tutorial_DIA.html

Best,

Fengchao

**Comment by TeckYewLow** [comment]
> You should analyze DDA and DIA separately. Here are two tutorials that might be helpful
> 
> https://fragpipe.nesvilab.org/docs/tutorial_lfq.html https://fragpipe.nesvilab.org/docs/tutorial_DIA.html
> 
> Best,
> 
> Fengchao

Thanks Fengchao. I am just wondering after I had analyzed both DDA and DIA data sets independently, how can I merge these 2 results so that I can estimate the occupancy of the phospho-sites,  i.e., the ratio of phospho-site abundance vs protein abundance? 

Thank you.

**Comment by fcyu** [comment]
I have never done that, merging DDA and DIA quant results. I think it is not trivial to get reasonable/good merged results because it related to normalization, etc.

Best,

Fengchao

**Comment by fedefratini** [comment]
> We do not have it implemented yet. We will add in the future.

Hi, any news about it? thanks
