### ISSUE TITLE
Trouble understanding my MBR results

### ISSUE THREAD

**Issue by rugenni** [Nesvilab/FragPipe#1413]
Hi, 

I am using Fragpipe 21.1 and IonQuant to analyze a label-free timsTOF set. Coming from MQ, I was interested to see how many MBR events I get with the FDR-controlled MBR of your tool. I used the default parameters of the LFQ-MBR workflow which in my case was MBR min correlation = 0 and MBR top runs = 10. 

Following your guide (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#multi-experiment-report) I played around with those parameters to see if I can increase the number of MBR events. I did not change the MBR min correlation but increased MBR top runs from 10 to 30 and then 60. Instead of >15000 MBR events I now have less than 400 which is quite confusing. Is this due to the FDR-control or is there any chance that I screwed up the settings?

Many thanks,
Nils 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-01-12_20-07-24_MBR_default_settings.zip](https://github.com/Nesvilab/FragPipe/files/13961406/log_2024-01-12_20-07-24_MBR_default_settings.zip)

[log_2024-01-16_15-27-41_MBR_top_runs_30.zip](https://github.com/Nesvilab/FragPipe/files/13961409/log_2024-01-16_15-27-41_MBR_top_runs_30.zip)

**Comment by fcyu** [comment]
I think so. With 1% ion-level FDR, the ion probability threshold is 0.9845 (from the default setting) vs 0.9889 (from the top 30 setting). Since MQ does not have the FDR control for MBR, I guess you would get more and more MBR events when changing a similar parameter?

Best,

Fengchao
