### ISSUE TITLE
N term not a number in TMT integrator version 21.1

### ISSUE THREAD

**Issue by kwebber3** [Nesvilab/FragPipe#1415]
I get the following error:
For input string: "N-term(304.2072)": N-term(304.2072) is not a number.
***
QREEAAR	n[305]QREEAAR	ARIAIIRK.QREEAAR.KKEEERKA	K	K	7	3	1.5575	1162.6376	1162.6361	388.5531	388.5526	1162.6378	388.5532	-0.0017	0.14196870000000	16.5990	13.2170	0.9550	2	1	149	155	1999540.4	N-term(304.2072)		0.99	false	sp|Q13442|HAP28_HUMAN	Q13442	HAP28_HUMAN	PDAP1	28 kDa heat- and acid-stable phosphoprotein
java.lang.NumberFormatException: For input string: "N-term(304.2072)"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
	at java.base/java.lang.Double.parseDouble(Unknown Source)
	at TMTIntegrator.UpdateColumns(TMTIntegrator.java:640)
	at TMTIntegrator.main(TMTIntegrator.java:60)

[log_2024-01-18_08-58-57.txt](https://github.com/Nesvilab/FragPipe/files/13978865/log_2024-01-18_08-58-57.txt)

**Comment by fcyu** [comment]
Thanks for the bug report. It seems that some columns in the psm.tsv files are not correct. Could you share the result folder with us? If yes, here is the link to upload the files https://www.dropbox.com/request/2x68NDPbu7WjYTDXU9TF

Thanks,

Fengchao

**Comment by fcyu** [comment]
No response.

**Comment by kwebber3** [comment]
Sorry, it is working now for some reason, and I lost the original files.
