### ISSUE TITLE
Not enough data to perform mass calibration. Using the uncalibrated data. Workaround for enriched samples?

### ISSUE THREAD

**Issue by ABB-808** [Nesvilab/FragPipe#1419]
Hi-
I want to get access to the deisotoped mzml files for my own analysis. I went into the params file and set write_calibrated_mzml = 1. 
This works for my non-enriched samples, but when I input my highly glycosylated samples, the log shows: Not enough data to perform mass calibration. Using the uncalibrated data and no mzml file is generated. I think one time I was able to get an uncalibrated mzml file to be made when I inputted the raw file but the uncalibrated mzml was not deisotoped. 

I'm fairly sure the reason to why calibration is failing is that there are far too few psms found when using the first search. Is there a way to use the glyco-HCD or glyco-open-HCD workflow as the first search to increase the psms found for calibration. I've tried both workflows and neither seemed to work. I've attached the log of the glyco-open-workflow. 

Alternatively, if there is just an easier way to get the deisotoped mzml file, I would love to hear it. 

[log_2024-01-23_17-11-08.txt](https://github.com/Nesvilab/FragPipe/files/14031057/log_2024-01-23_17-11-08.txt)

Thanks!
-Alex

**Comment by fcyu** [comment]
If you are doing the mass-offset search (glyco-HCD) or open search (glyco-open-HCD), there is no workaround.

You can probability put some common glycans as the variable modifications, and enable the `use all mods in the first search` in the MSFragger tab. In this way, there will be enough high-quality PSMs for mass calibration. But, I never tested that and not sure if it will make the result worse. Use at your own risk.

Best,

Fengchao

**Comment by ABB-808** [comment]
I added the top few glycans as variable mods and it worked! I Was able to get the calibrated mzml after the successful mass calibration. Thanks for your help.

Alex

**Comment by fcyu** [comment]
No problem. 

I will close this issue but feel free to contact us if you have any questions in the future.

Best,

Fengchao
