### ISSUE TITLE
how to use Fragpipe to analyze TMT data acquired by Astral 

### ISSUE THREAD

**Issue by CaiXue11** [Nesvilab/FragPipe#1420]
I acquired TMT-16plex data using Astral, and tried to analysis using FragPipe 21.1, but failed.

I have uploaded the log file. I want to know how to use Fragpipe to analyze TMT data acquired by Astral.
[log_2024-01-24_13-58-10.txt](https://github.com/Nesvilab/FragPipe/files/14033742/log_2024-01-24_13-58-10.txt)

**Comment by anesvi** [comment]
Your log shows that FragPipe run successfully to completion, not failed. I do see that the number of IDs is low.
INFO[16:46:16] Converged to 0.00 % FDR with 77 Proteins      decoy=0 threshold=0.6281 total=77
INFO[16:46:16] Applying sequential FDR estimation            ions=115 peptides=100 psms=183
INFO[16:46:16] Converged to 0.00 % FDR with 183 PSMs         decoy=0 threshold=0.56032 total=183
INFO[16:46:16] Converged to 0.00 % FDR with 100 Peptides     decoy=0 threshold=0.587965 total=100
INFO[16:46:16] Converged to 0.00 % FDR with 115 Ions         decoy=0 threshold=0.587965 total=115

If that is not expected (that is, you think there should be more than 77 proteins), you need to check the settings or quality of your data. Compare with PD results, for example. Cannot say from the log why ID numbers are low.
