### ISSUE TITLE
thermo

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#1421]
Dear FragPipe Team

With the newest FragPipe release (v.21), we are not able to directly process Thermo RAW files anymore, due to an issue with the loading of the 'BatmassIoThermoServer.exe'. Processing of the corresponding mzML was running without any issue. FragPipe is running on a Ubuntu system with Mono version 6.12.0.182 and openJDK version 11.0.21 installed. 
What are we doing wrong?

Thank you already in advance for your help!

Best,
Christian

[log_2024-01-24_17-00-14.txt](https://github.com/Nesvilab/FragPipe/files/14040746/log_2024-01-24_17-00-14.txt)

**Comment by fcyu** [comment]
Hi Christian,

It seems that the Thermo RAW file loader was not working. Could you run `mono BatmassIoThermoServer.exe` and send me the screenshot of the output?

Thanks,

Fengchao

**Comment by fcyu** [comment]
It seems that some of the files in `ext` were corrupted. Could you download and unzip MSFragger zip file, and run `mono BatmassIoThermoServer.exe` again?

Thanks,

Fengchao

**Comment by chscho** [comment]
Wow, that was it! `BatmassIoThermoServer.exe` looks fine now and also within FragPipe it's working again with RAW files!
![Screenshot 2024-01-24 at 17 55 24](https://github.com/Nesvilab/FragPipe/assets/62370919/edaf22b3-53e7-4aa1-b806-d5b67eb54c46)

Thank you very much for your ultrafast help!

Best,
Christian

**Comment by fcyu** [comment]
No problem! I will close this issue but feel free to contact us if you have any other questions in the future.

Best,

Fengchao
