### ISSUE TITLE
Issue with SILAC-based quantitation for DDA-PASEF data

### ISSUE THREAD

**Issue by vincentroyrichard** [Nesvilab/FragPipe#1422]
Hello! I am using Fragpipe v21.1 and I would like to perform SILAC quantitation for a sample in which we have peptides with labelled lysine residues (K+6). When I try to run it with K+6 as a variable modification and MS1 quant based on K0 (light) and K6.020129 (heavy) I get an error (below) and no report is generated. Any assistance with this would be greatly appreciated!

"java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 6904
	at r.a(Unknown Source)
	at r.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2024-01-24 16:17:12 [ERROR] - Index -1 out of bounds for length 6904
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping"

[SILAC-ERROR_log_2024-01-24_16-25-39.txt](https://github.com/Nesvilab/FragPipe/files/14043829/SILAC-ERROR_log_2024-01-24_16-25-39.txt)

**Comment by fcyu** [comment]
This is a known issue: https://github.com/Nesvilab/FragPipe/issues/1387 Could you send an email to yufe AT umich.edu to get a fixed version?

Thanks,

Fengchao

**Comment by vincentroyrichard** [comment]
Sure thing Fengchao! Thanks for the quick response!
