### ISSUE TITLE
Error with FAIMS files

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1423]
Hi,

I am getting an error trying multiple different TMT-FAIMS-MS3 files in Fragpipe 21.1 that had previously been analyzed with FragPipe 20.0 (tried both .raw and .mzml): "2024-01-25 14:22:08 [ERROR] - There were errors creating tables in I:\6097\JPR_data\MLE_UB: java.lang.NullPointerException: Cannot find CV -40 from all" Also happened with a separate dataset. Any idea why we are seeing this error?

Thanks,

Matt Foster

**Comment by fcyu** [comment]
Could you share the log fil?

Thanks,

Fengchao

**Comment by mwfoster** [comment]
[log_2024-01-25_13-46-54.txt](https://github.com/Nesvilab/FragPipe/files/14057944/log_2024-01-25_13-46-54.txt)
[log_2024-01-25_13-59-12.txt](https://github.com/Nesvilab/FragPipe/files/14057946/log_2024-01-25_13-59-12.txt)

**Comment by fcyu** [comment]
Thanks for the files. There are three possibilities for this error

1. IonQuant did not read the CV from the raw/mzML files correctly
2. One raw file has FAIMS but the other does not have
3. MS1 does not have FAIMS but MS2 have

To figure out the exact cause, is it OK to share those two raw files with us? If yes, here is the link to upload the files https://www.dropbox.com/request/Sulkspzhow6YoB0QrIDy

Thanks,

Fengchao

**Comment by mwfoster** [comment]
Yes. I confirmed that the mzml files processed with FP20. Thanks, Matt

**Comment by fcyu** [comment]
Thanks for the files. 

`ID106594_01_FSN20560_6097_080923` does not have FAIMS but `ID106594_02_FSN20560_6097_080823` has. Those two should not be analyzed together theoretically. 

In FragPipe 20, we used Philosopher for the TMT quantification. In FragPipe 21, we switched to IonQuant which is more accurate, precise, and faster. Unfortunately, this is also why you got the error. If you want to switch back to Philosopher, you can use the `intensity extraction tool` in the `Quant (Isobaric)` tab

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/fa688dab-ddf4-4f7b-982a-1b5e40f36346)

Note that with Philosopher, you have to use the mzML format files.

Best,

Fengchao

**Comment by mwfoster** [comment]
Thanks. I had forgotten that they were -/+ FAIMS. Regards, Matt

**Comment by fcyu** [comment]
No problem. I will close this issue but feel free to contact us if you have any other questions in the future.

Best,

Fengchao
