### ISSUE TITLE
Do not distinguish I and L when mapping peptides to proteins.

### ISSUE THREAD

**Issue by jingjing1030** [Nesvilab/FragPipe#1425]
Hi fragpipe team,

I am using fragpipe 20.0 with DIA_SpecLib_Quant workflow to process Astral-DIA data. Then I found  there are some sequences in the diann-output.pr_matrix.tsv cannot reannotated by the fasta?
please see attachment for details.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[issues of fragpipe20.0.pptx](https://github.com/Nesvilab/FragPipe/files/14076470/issues.of.fragpipe20.0.pptx)
[issues.txt](https://github.com/Nesvilab/FragPipe/files/14076473/issues.txt)
[log_2023-11-17_01-21-40.txt](https://github.com/Nesvilab/FragPipe/files/14076474/log_2023-11-17_01-21-40.txt)

**Comment by fcyu** [comment]
Normally do not distinguish `I` and `L` when mapping peptides to proteins.

Best,

Fengchao
