### ISSUE TITLE
Feature request: Workflow for low-complexity samples

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/FragPipe#1426]
Dear Fengchao,

I stumbled already a couple of times on the issue that it is hard to analyse samples with a low complexity (i.e. pull down assays with only few interaction partners, purified proteins where I wanted to identify particular modifications, PRM assay samples to use for library building, GeLC experiments where a high MW or low MW gel piece contains no proteins, ...). This is even more problematic when only few samples of a larger batch are of low complexity as usually the entire search fails. Sometimes this can be circumvented by increasing thresholds but most of the times those searches simply fail.
However, I think it would be preferable in such cases if the search runs through and just returns empty result lists for those samples. In some cases it might be even possible to "rescue" proteins by MBR during the IonQuant step (particularly if there is only one highly purified protein in a sample and an additional "background" sample is analysed; the FDR calculation for the single protein often fails but the presence of it's peptides might be concluded by MBR).
An other example that I am currently working on is the parallel measurement of samples in DDA and PRM mode to identify a particular modified residue. Unfortunately the peptide in concern has a very low detectability (already using a double digestion with AspN and trypsin) and is not visible in the DDA measurements with a normal search. The PRM measurements, on the other hand, show nice chromatographic traces for several transitions and I would like to use them to build a spectral library for searching the DDA measurements. This fails during the filtering and I may would need to apply a fixed score cutoff instead of Percolator of ProteinProphet filtering.

Therefore I would highly appreciate if you could include a workflow that is more robust towards "bad samples" in one of the future versions.

Best,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Thank you for the feedback and suggestion.

In the latest version, we do let FragPipe "runs through and just returns empty result lists for those samples" for most workflows. Here is one typical example that we have addressed: https://github.com/Nesvilab/FragPipe/issues?q=is%3Aissue+is%3Aclosed+percolator+-1073741819+

If you still have some issues with the latest version, could you share some log files with us?

Thanks,

Fengchao

**Comment by JB91451** [comment]
Hi Fengchao,

I have used the most recent version for my latest dataset and realised that the error code looks different from former versions. It would be great if you could have a look on the attached log file and recommend settings.
Besides the (somewhat weird) modification settings I have mainly released the pepProb and protProb (--protProb 0.99 --pepProb 0.99) settings for the filter step but as far as I can follow the log file it did not reach this step yet.

Best regards,
Juergen

[log_2024-01-29_10-45-33.txt](https://github.com/Nesvilab/FragPipe/files/14086881/log_2024-01-29_10-45-33.txt)

**Comment by fcyu** [comment]
Hi Juergen,

Could you share `240117_QE1_PM1_SK_MZ_ZG3145_PRM_3b_edited.pin` with us?

Thanks,

Fengchao

**Comment by JB91451** [comment]
Yes, here it is. File suffix changed to txt. (it's empty except from the header line)

[240117_QE1_PM1_SK_MZ_ZG3145_PRM_3b_edited.txt](https://github.com/Nesvilab/FragPipe/files/14086953/240117_QE1_PM1_SK_MZ_ZG3145_PRM_3b_edited.txt)

**Comment by JB91451** [comment]
ahh, and pepXML is also empty except from the "protocol" information

**Comment by JB91451** [comment]
Thank you again for the afford! 
For now, I think it is fine to simply skip these files during the searches but it would be a nice feature if such empty files could be handled; especially when one analyses really large sample batches where it may takes days to reach the crashing point.

Best regards,
Juergen

**Comment by fcyu** [comment]
Hi @JB91451 ,

Matthew has fixed Percolator (https://github.com/percolator/percolator/issues/371), and I have updated the version in FragPipe (https://github.com/Nesvilab/FragPipe/commit/a32112820792acec9e3f99febe0c530a9cf55e8b).

Let you know if you want to test the pre-released version of FragPipe.

Best,

Fengchao

**Comment by JB91451** [comment]
Dear Matthew and Fengchao,

Thank you both for the fast implementation of this!

For now I have searched the samples as suggested by leaving out the problematic ones. If I will struggle into such samples again before the next official release of FragPipe, it would be great to use the pre-release version. I will let you know in case.

Thanks again and
Best regards,
Juergen
