### ISSUE TITLE
Error Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by amptsmb** [Nesvilab/FragPipe#1427]
- Describe the issue or question:

Fragpipe analyzed the DDA files   without any issues  before and terminates with error: Index O out of bounds for length 0, since yesterday!.  Any solution for this?.

Thanks

  

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-01-30_14-45-49.zip](https://github.com/Nesvilab/FragPipe/files/14100019/log_2024-01-30_14-45-49.zip)

**Comment by fcyu** [comment]
You enabled DIA quant module but did not enable the spectral library building module.

Best,

Fengchao

**Comment by amptsmb** [comment]
Thanks a lot for the reply . I changed the parameters and Fragpipe completed the analysis without error.
