### ISSUE TITLE
RUN error

### ISSUE THREAD

**Issue by RaquelVA** [Nesvilab/FragPipe#1428]
I feel I have a problem with the installation of the MSfragger or something else. 
I downloaded fragpipe v21.0. 

C:\Users\SCIEXProc\Desktop\fragpipe\tools\MSFragger-4.0\MSFragger-4.0.jar
C:\Users\SCIEXProc\Desktop\fragpipe\tools\IonQuant-1.10.12.jar
C:\Users\SCIEXProc\Desktop\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe
C:\Users\SCIEXProc\Desktop\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe
C:\Users\SCIEXProc\AppData\Local\Programs\Python\Python39\pythonw.exe

I have a known workflow and a correct file from someone who has this program, and it works for him. So I'm pretty sure all parameters and the files conversion are correct. I'm using MSFragger for a DDA experiment. All the validation tools aren't working at all, and when I want to activate MSBooster, it says that is not compatible with an open search and it should be disabled, but this is strange for me because all parameters come from a known correct workflow (dafault, closed search). Without the MSbooster and any validation tool, I'm allowed to RUN the file, but percolator shouldn't be activated or any PTM or any tool after the validations tools. If I activate the prophet or the percolator stops the RUN and the remaining tasks are cancelled.

I'm pretty sure I have an informatic problem or something like this because this person RUN my files with the same workflow and it works for him, but not for me. I don't know how to fix this. Thanks for your attention.

I'm going to copy one example RUN (a part of, without MSbooster):

System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
.NET Core Info: N/A

Version info:
FragPipe version 21.0
MSFragger version 4.0
IonQuant version 1.10.12
Philosopher version 5.1.0

LCMS files:
  Experiment/Group: 1_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A.mzML	DDA
  Experiment/Group: 2_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_(2).mzML	DDA
  Experiment/Group: 3_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_10uL.mzML	DDA
  Experiment/Group: 4_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_20uL.mzML	DDA
  Experiment/Group: 5_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_5uL.mzML	DDA
  Experiment/Group: 6_1
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_80min.mzML	DDA

[ ... ]

MSFragger move pin
C:\Users\SCIEXProc\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\SCIEXProc\Desktop\fragpipe\lib\fragpipe-21.0.jar;/C:/Users/SCIEXProc/Desktop/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_20uL.pin D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\4_1\211129_PeptideMapping_Proves-HSA_Option_A_20uL.pin
Process 'MSFragger move pin' finished, exit code: 0
MSFragger move pepxml
C:\Users\SCIEXProc\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\SCIEXProc\Desktop\fragpipe\lib\fragpipe-21.0.jar;/C:/Users/SCIEXProc/Desktop/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_5uL.pepXML D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\5_1\211129_PeptideMapping_Proves-HSA_Option_A_5uL.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pin
C:\Users\SCIEXProc\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\SCIEXProc\Desktop\fragpipe\lib\fragpipe-21.0.jar;/C:/Users/SCIEXProc/Desktop/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_5uL.pin D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\5_1\211129_PeptideMapping_Proves-HSA_Option_A_5uL.pin
Process 'MSFragger move pin' finished, exit code: 0
MSFragger move pepxml
C:\Users\SCIEXProc\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\SCIEXProc\Desktop\fragpipe\lib\fragpipe-21.0.jar;/C:/Users/SCIEXProc/Desktop/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_80min.pepXML D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\6_1\211129_PeptideMapping_Proves-HSA_Option_A_80min.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pin
C:\Users\SCIEXProc\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\SCIEXProc\Desktop\fragpipe\lib\fragpipe-21.0.jar;/C:/Users/SCIEXProc/Desktop/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\PROTEOMICS\FILES_CONVERTER\211129_PeptideMapping_Proves-HSA_Option_A_80min.pin D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\6_1\211129_PeptideMapping_Proves-HSA_Option_A_80min.pin
Process 'MSFragger move pin' finished, exit code: 0
Percolator [Work dir: D:\PROTEOMICS\MS_FRAGGER\OUTPUT7\2_1]
C:\Users\SCIEXProc\Desktop\fragpipe\tools\percolator_3_6_4\windows\percolator.exe --only-psms --no-terminate --post-processing-tdc --num-threads 6 --results-psms 211129_PeptideMapping_Proves-HSA_Option_A_(2)_percolator_target_psms.tsv --decoy-results-psms 211129_PeptideMapping_Proves-HSA_Option_A_(2)_percolator_decoy_psms.tsv --protein-decoy-pattern rev_ 211129_PeptideMapping_Proves-HSA_Option_A_(2).pin
Protein decoy-prefix used is 
All files have been read
Percolator version 3.06.4, Build Date Dec  4 2023 13:59:29
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
C:\Users\SCIEXProc\Desktop\fragpipe\tools\percolator_3_6_4\windows\percolator.exe --only-psms --no-terminate --post-processing-tdc --num-threads 6 --results-psms 211129_PeptideMapping_Proves-HSA_Option_A_(2)_percolator_target_psms.tsv --decoy-results-psms 211129_PeptideMapping_Proves-HSA_Option_A_(2)_percolator_decoy_psms.tsv --protein-decoy-pattern rev_ 211129_PeptideMapping_Proves-HSA_Option_A_(2).pin
Started Tue Jan 30 16:23:07 2024
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile 211129_PeptideMapping_Proves-HSA_Option_A_(2).pin
Features:

ERROR: Reading tab file, too few features present.
No-terminate flag set: ignoring error and using a pseudo-feature of zeroes.
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid.

Process 'Percolator' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 54 remaining tasks

**Comment by fcyu** [comment]
I am pretty sure you messed up the configurations and parameters ;) 

Could you
1. Share the whole workflow file
2. Sent the screenshots of the "config" and "workflow" tab.

Best,

Fengchao

**Comment by RaquelVA** [comment]
Its okey with this? If you have an email I can send you the workflow.

**Comment by RaquelVA** [comment]
Thank you so much, and I did not put the sother creenshots because right now arent activated. However, I completely missed this load. So sorry and thank you so much for your work and this wonderful platform, with which one Im trying to learn to work with.
