### ISSUE TITLE
Bruker TIMSTOF Pro data files can not be imported (2019)

### ISSUE THREAD

**Issue by tobigithub** [Nesvilab/FragPipe#143]
# Describe the problem

* **I'm submitting a:**
  - [ x] problem running the software
  - [ ] bug report
  - [ x] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
Bruker TIMSTOF PRO data (2019) from https://www.omicsdi.org/dataset/pride/PXD010012
can not be imported,  "none of the folders is supported"

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** WIN7 **
- Java version: ** 1.8 **

----

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"

...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **

SEE https://www.omicsdi.org/dataset/pride/PXD010012

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```

**Comment by tobigithub** [comment]
**Solution**:
The MSFragger-2.1.jar file alone is not sufficient for Bruker data, the ZIP updater from http://msfragger.arsci.com/upgrader/ has to downloaded with a \ext\bruker subfolder containing all required DLLs.

**Comment by anesvi** [comment]
Great!

Fengchao, can we make it more clear on the download side? I think someone else had the same problem before – downloaded without Ext folder
