### ISSUE TITLE
PhilosopherReport error, when executing peptidomics pipeline

### ISSUE THREAD

**Issue by DianaSamodova** [Nesvilab/FragPipe#1432]
Hi,
Unfortunately, I am not able to execute the peptidomics pipeline in the FragPipe - apparently, there are some issues with the Philosopher , when generating the report (?). Can you, please, help me with this? I am attaching the log file. Thanks in advance.
Best regards,
Diana
[log_2024-02-05_11-03-21.txt](https://github.com/Nesvilab/FragPipe/files/14164060/log_2024-02-05_11-03-21.txt)

**Comment by fcyu** [comment]
Philosopher 5.0.0 is not compatible with FragPipe 19.0. I guess you just upgraded Philosopher but did not upgrade other tools. 

Best,

Fengchao
