### ISSUE TITLE
Could not get isolation window info

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1434]
Hello Fengchao,

As always, thanks for such a wonderful package for processing data. I am having an issue processing some DIA data for phospho samples. These samples were analyzed in an Exploris 480 with FAIMS PRO. In the MS method, we have a short negative polarity MS1 scans set up at the beginning which we use to clean the instrument before starting the actual method. Although the FAIMS CV here was set to 0. For the rest of the method, we have MS and DIA scans set up with FAIMS CV -45.

We were unable to initially run these samples because the FAIMS CV in the first negative polairty scans was 0 and the rest of the method was set to -45. So we filtered out the 0 CV scans using [FAIMS-MzXML-Generator](https://github.com/coongroup/FAIMS-MzXML-Generator). Then we converted the MzXML files to MZML files using MSConvert with the setting described for raw files [here ](https://fragpipe.nesvilab.org/docs/tutorial_convert.html#convert-thermo-dia-raw-files-with-overlappingstaggered-windows).

Now we get an error which reads: "Could not get isolation window from scan 6" Can you please help us with this? From looking in the mzml file it does not seem there are isolation window entries?

Thanks,
Ronnie

Log file:
[log_2024-02-05_16-51-28.txt](https://github.com/Nesvilab/FragPipe/files/14172257/log_2024-02-05_16-51-28.txt)

**Comment by fcyu** [comment]
FAIMS-MzXML-Generator did not propagate the isolation window info from raw to mzXML. Then, when you converted the mxXML files to mzML, the information is not available, which crashed MSFragger.

Best,

Fengchao

**Comment by cutleraging** [comment]
Hi Fengchao,

Thanks for your response, this makes sense. It sounds like then that the FAIMS-MzXML-Generator is not made for DIA data. So is there a way for us to still process these files in Fragpipe?

Thanks,
Ronnie

**Comment by fcyu** [comment]
I never used it but maybe you could try https://github.com/PNNL-Comp-Mass-Spec/Thermo-FAIMS-to-MzML. It seems converting raw to mzML directly.

Best,

Fengchao
