### ISSUE TITLE
error: index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by kiallsuazo** [Nesvilab/FragPipe#1436]
Hello,

I am new to using FragPipe. I was running a PTM search on a pure protein. When I only hav contaminant database and decoys in the the search, I could view the results using PDV viewer on FragPipe. However, when I include my actual protein sequence the results in many matches, I would encounter the error: Index 0 out of bounds for length after opening the FragPipe-PDV viewer and it takes forever to load my results. Would you possibly know how to fix this issue? Thank you!

**Comment by fcyu** [comment]
@KaiLiCn , can you take a look?

Thanks,

Fengchao

**Comment by kiallsuazo** [comment]
Hi Kai,

Thank you for looking into this. I have uploaded my raw files: 3
replicates, 2 fractions each along with the results folder and the fasta
database. Thank you!

Best,
Kiall

**Comment by KaiLiCn** [comment]
Hi Kiall,

I found a bug related to protein mapping in FP-PDV.  I am working on that and I will let you know when I fix it today or tomorrow. 

Kai

**Comment by kiallsuazo** [comment]
Thank you so much for working on this!

**Comment by KaiLiCn** [comment]
Hi,

I fixed the bug. Can you download the latest FP-PDV .jar file here: https://github.com/Nesvilab/FragPipe-PDV/releases/tag/V1.1.7 

Please follow the `ReadMe` to replace the old one in the FragPipe
https://github.com/Nesvilab/FragPipe-PDV/blob/master/README.md

Kai

**Comment by kiallsuazo** [comment]
Hi Kai,

Works perfect now. Thank you so much for promptly working on this!

Best,
Kiall

**Comment by RSMarta** [comment]
Hello, 
I am using MSFragger within the FragPipe platform, and I have encountered this error in some searches. Additionally, loading my results takes an unusually long time. I am currently using FragPipe v22 and MSFragger v4.1. Could this error be related to setting “none” for calibration and optimization (MSFragger tab)? Thank you in advance for your help!

**Comment by fcyu** [comment]
Hi @RSMarta ,

Could you share the log file (the file with name starts with `log_202`?

Thanks,

Fengchao

**Comment by RSMarta** [comment]
Ok, there is no problem with the log file but I encountered this error when trying to open the FragPipe-PDV viewer to view the results and spectra.
Could you help me fix this?

**Comment by fcyu** [comment]
Please create a new issue in https://github.com/Nesvilab/FragPipe/issues. Your problem has nothing to do with this thread.

Best,

Fengchao
