### ISSUE TITLE
Problem with easypqp

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#1439]
- Describe the issue or question:
I am trying to generate a spectral library from a dda run, but ran into some problem with easypqp. Can you please look a the log file? I can't find out what's causing it. The error is reproducible.

Thank you,
Janos

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-02-06_12-33-56_error.txt](https://github.com/Nesvilab/FragPipe/files/14185790/log_2024-02-06_12-33-56_error.txt)

**Comment by guoci** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/600 . It has been resolved.

**Comment by jd690764** [comment]
Hi Guo,

Thank you, it worked!
Janos
