### ISSUE TITLE
Failed HL Quant Search with FP21.0

### ISSUE THREAD

**Issue by chaudngo** [Nesvilab/FragPipe#1440]
- Describe the issue or question:
Hello, 

I tried to search for HL quant with FP21 using mzml files, but the search kept giving the same "IonQuant finished, exit code: 1" error. Please let me know how I can address this. Thank you!
I've attached the zipped log file for your review. 

[log_2024-02-06_21-30-30.txt.zip](https://github.com/Nesvilab/FragPipe/files/14197227/log_2024-02-06_21-30-30.txt.zip)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
This is a known bug: https://github.com/Nesvilab/FragPipe/issues/1387

Please send an email to yufe AT umich.edu to get a fixed version of IonQuant.

Best,

Fengchao
