### ISSUE TITLE
Apparent garbling in associating Experiment with RAW files

### ISSUE THREAD

**Issue by dtabb73** [Nesvilab/FragPipe#1443]
I tried to create a spectral count table for a very heterogeneous collection of RAW files.  My 63 raw files represented generally four replicates of a particular sample type, and I had fifteen different Experiments that reflected their file names.

When I generated the spectral count table, though, I found that the RAWs were not associated with the correct experiment, and some were missing experiment labels even though I had assigned them labels in the Workflow tab.  For example, CT26_1, CT26_2, CT26_3, and CT26_4 are all correctly associated with the CT26 experiment.  All the files starting with "WT_" are assigned no Experiment in the spectral count table.  Instead, SH_INF_NEG_1 and others appear to be assigned to the WT_POS Experiment, for some reason.

I believe this may be a bug since I cannot find an error on my part.  I am including manifest and log.

[log_2024-02-09_23-33-40.txt](https://github.com/Nesvilab/FragPipe/files/14228547/log_2024-02-09_23-33-40.txt)
[fragpipe-files.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/14228548/fragpipe-files.fp-manifest.txt)

**Comment by fcyu** [comment]
I took a look at the log file, the experiment assignment seems to be correct. Taking the `WT_` for example

PhilosopherFilter [Work dir: E:\Ribon\DDA\20240209-MSFragger-SPC\\**WT_NEG_1**]
C:\Research\fragpipe-21.1\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml E:\Ribon\DDA\20240209-MSFragger-SPC\WT_NEG_1 --dbbin E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 --protxml E:\Ribon\DDA\20240209-MSFragger-SPC\combined.prot.xml --probin E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 --razor
INFO[23:31:11] Executing Filter  v5.1.0                     
INFO[23:31:11] Fetching protein inference from E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 
INFO[23:31:11] Processing peptide identification files      
INFO[23:31:11] Parsing E:\Ribon\DDA\20240209-MSFragger-SPC\WT_NEG_1\interact-**WT_neg_rep1**.pep.xml 
...


PhilosopherFilter [Work dir: E:\Ribon\DDA\20240209-MSFragger-SPC\\**WT_NEG_101**]
C:\Research\fragpipe-21.1\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml E:\Ribon\DDA\20240209-MSFragger-SPC\WT_NEG_101 --dbbin E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 --protxml E:\Ribon\DDA\20240209-MSFragger-SPC\combined.prot.xml --probin E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 --razor
INFO[23:31:16] Executing Filter  v5.1.0                     
INFO[23:31:16] Fetching protein inference from E:\Ribon\DDA\20240209-MSFragger-SPC\CT26_1 
INFO[23:31:16] Processing peptide identification files      
INFO[23:31:16] Parsing E:\Ribon\DDA\20240209-MSFragger-SPC\WT_NEG_101\interact-**WT_neg_rep1_higher**.pep.xml 

Could you share some screenshots showing the experiment-file matchings are not correct?

Thanks,

Fengchao

**Comment by dtabb73** [comment]
Thank you for taking a look so quickly!

I believe the problem of organization is taking place at a later point.  I am attaching the spectral count table for reprint.
[reprint.spc.txt](https://github.com/Nesvilab/FragPipe/files/14229648/reprint.spc.txt)

Am I mis-reading?  I thought that the experiment label in row 2 should appear directly below the raw label.  The last few RAWs seem to have empty experiment fields.

I hope your weekend is a happy one!
Dave

**Comment by anesvi** [comment]
Hi Dave, reprint.tsv file is generated for reprint-apms.org interactome scoring analysis. The second row there is meant to indicate just control or gene name for bait AP. So the format you see is as intended.

**Comment by dtabb73** [comment]
Oh, okay!  I had misunderstood the line to be providing experiment associations for each column.

Thank you both for the assistance on a weekend!
Dave
