### ISSUE TITLE
Options for customizing the combined_peptide.tsv output

### ISSUE THREAD

**Issue by yannic-chen** [Nesvilab/FragPipe#1445]
Hello,

When doing an analysis with different bioreplicates, we get a resulting combined_peptide.tsv. From my understanding, this is limitd to 1% peptide FDR and created from PeptideProphet where the "final" probability is calculated based on how often the peptide was found in the bioreplicates.

Is it possible to obtain such a file for PSMs and also be able to control the FDR cutoff, so that I could for example retrieve all peptides?

Thanks very much,
Yannic

**Comment by fcyu** [comment]
Yes, you could adjust the "filter" box in the "FDR filter and report" panel in the "validation" tab.

Best,

Fengchao

**Comment by yannic-chen** [comment]
as far as I can see, the "Filter" box settings only affect the "peptide.tsv" and "psm.tsv" within each "exp_#" subfolder. But it doesnt affect the "combined_peptide.tsv". I cannot find any peptide with probabilty below 0.9, while in the "peptide.tsv" files I can see probabilities down to 0.5. The settings are shown below:

![image](https://github.com/Nesvilab/FragPipe/assets/63793884/2956d307-311b-4a0a-9be2-52a775750243)

**Comment by dpolasky** [comment]
Hi Yannic,
There is also an ion level filter (--ion 1) that should be set in the filter command. The preceding tools (ProteinProphet and either Percolator or PeptideProphet) also have default minimum probabilities to report PSMs onward - the 0.5 minimum probability you're seeing is most likely from Percolator as that's the default setting. To report peptides from PSMs with lower probabilities, you can rerun from the Percolator step using min probability 0, and either set --minprob 0 for ProteinProphet as well or check the "Do not use ProteinProphet file" box in the filter command. 

Best,
Dan

**Comment by fcyu** [comment]
Hi @yannic-chen 

>  I cannot find any peptide with probabilty below 0.9, while in the "peptide.tsv" files I can see probabilities down to 0.5. 

If you are sure that you got it right, could you share your combined_peptide.tsv and peptide.tsv with us, and also let me the peptide sequence that you are looking at ?

Thanks,

Fengchao

**Comment by yannic-chen** [comment]
Hi both,

@dpolasky I have done the settings as you suggested, but I get the error:
`Process 'PhilosopherFilter' finished, exit code: 0`
`PhilosopherReport [Work dir: E:\data\2022-145-IP-MHC1.2-main\Mixed_Database_Model_github_test\exp_9]`
`C:\Users\PEAKS-CORE#2\Desktop\FragPipe-21.2-build03\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe report`
`INFO[09:53:49] Executing Report  v5.1.0`
`INFO[09:53:49] Creating reports`
`ERRO[09:53:49] Cannot read file. open .meta\pep.bin: The system cannot find the file specified. `
`Process 'PhilosopherReport' finished, exit code: 1`
`Process returned non-zero exit code, stopping`

Here are the settings:
![image](https://github.com/Nesvilab/FragPipe/assets/63793884/b9c9f7de-62e0-4624-8753-ede1efca8e26)

@fcyu I have attached the "peptide.tsv" from "exp_1" and the "combined_peptide.tsv"
[Peptide.zip](https://github.com/Nesvilab/FragPipe/files/14278395/Peptide.zip)

I am not looking for a specific sequence, but looking at how well mixed databases work. For this I need a complete report of all peptides across all samples and for each separate sample.

**Comment by dpolasky** [comment]
Also the "--minprob 0" argument needs to go in the command line for ProteinProphet, not FDR Filter

**Comment by yannic-chen** [comment]
@dpolasky now it did work. And I can also see peptides with probability down to 0 in the peptide.tsv. On this note, does it mean that I now indeed have all peptides identified by Fragpipe? I also wanted to ask, does setting the --ion 1 have any effect on the peptides.tsv, protein.tsv and psm.tsv files? From the Fragpipe website I was under the impression that every filter only affects their own respective file.

@fcyu Ah sorry, it was my mistake, I send you the wrong file (those didnt had any score). I have attached the correct one (in fact, this is the result from the settings suggested by @dpolasky)
[Peptides(scored).zip](https://github.com/Nesvilab/FragPipe/files/14294153/Peptides.scored.zip)

Many thanks,
Yannic

**Comment by fcyu** [comment]
@yannic-chen , I believe the combined files were generated by Philosopher Abacus. FragPipe does not have a way to change the threshold (https://github.com/Nesvilab/philosopher/wiki/Abacus).

If you want to have the unfiltered MSFragger results, just use the pepXML, pin, or <run name>.tsv files generated by MSFragger. There is no need to run "FDR filter and report" at all.

Best,

Fengchao
