### ISSUE TITLE
Flexibility in Glycolists.

### ISSUE THREAD

**Issue by Juz59** [Nesvilab/FragPipe#1446]
Hi FragPipe Devs,

First of all thanks for Your amazing Job here !

I would like to add more exotic monosaccharides/modifications in my glyco-lists to match my potential glycopeptides as I am working on mainly with lower organism (that differs much from mammals).

I know that Hex HexNac Fuc NeuAc NeuGc Phospho and Sulpho are fully supported but I would also others like:
- Pentose (e.g., xylose) at 132,0423 Da 
- Hexuronic acid (e.g., glucuronic acid or GlcA) at 176,0321 Da
- Phosphorylcholine (PC) at 165,0555 Da
- Phosphoethanolamine (PE) at 123,0085 Da

This will really be nice to me. Please tell me if there is a way to include them in my glycolist.

As instance I tried for Hex3HexNac2PC1 to do it like in Byonic:
Hex(3)HexNAc(2)PC(1) or Hex(3)HexNAc(2) 165.0555(1) or Hex(3)HexNAc(2)165.0555 but none of them seems to work ...

Thanks for your support !

**Comment by dpolasky** [comment]
Hi,
We have a new version that supports custom/any monosaccharides in testing now - if you would like to try it out, send me an email at dpolasky [at] umich.edu and I can share it with you. 

Best,
Dan

**Comment by Juz59** [comment]
Thank-You so much for your quick and very helpful answer. I will soon contact You and definitely test it out.
