### ISSUE TITLE
Runs can not be fully completed due to PTMShepherd and InteractParser.exe

### ISSUE THREAD

**Issue by mryanshi** [Nesvilab/FragPipe#1449]
- Describe the issue or question:
Dear Team,

Many thanks for providing FragPipe to he community! I am a new comer in the proteomics field and just started to use FragPipe to look for glycopeptides. Although I followed your instructions to set the software with latest updates installed, the runs could be started but left tasks unfinished. I tried different data and databases but encounter different issues. They seem to related to PTMShepherd and InteractParser.exe. Please find zipped log files attached. 

To me it seems to be strange that the **InteractParser.exe** is stored in a temporary folder under  C:\Users\user\AppData\Local\Temp\. I asked the IT department to whitelist it but I am not sure if this will solve the issue.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-02-16_10-07-33.zip](https://github.com/Nesvilab/FragPipe/files/14308896/log_2024-02-16_10-07-33.zip)
[log_2024-02-12_16-42-28.zip](https://github.com/Nesvilab/FragPipe/files/14308908/log_2024-02-12_16-42-28.zip)

**Comment by fcyu** [comment]
Thanks for your interest in our tools. It looks like your computer's configuration blocked the InteractParser:
```shell
ERRO[16:42:28] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\7d172655-4029-4846-9b77-6e9bcbc6a654\InteractParser.exe: This program is blocked by group policy. For more information, contact your system administrator. 
```

Since it is due to your specific computer, you probably need to contact the your IT team to troubleshoot this problem.

Best,

Fengchao
