### ISSUE TITLE
DIA-Umpire crashes due to a FragPipe bug

### ISSUE THREAD

**Issue by nicolasgrinberg** [Nesvilab/FragPipe#1454]
Hi,

I am trying to run hybridDIA with 54 DIA folders and 57 DDA folders. I set a 3% FDR with group-specific FDR. I want to set the DDA folders as DDA+ but it keeps crashing unfortunately. Is it possible to use DDA+ with hybrid DIA? Thanks in advance,

Nico
[log_2024-02-21_11-19-47.txt](https://github.com/Nesvilab/FragPipe/files/14358053/log_2024-02-21_11-19-47.txt)

**Comment by fcyu** [comment]
The error was from DIA-Umpire. @guoci can you take a look?

Thanks,

Fengchao

**Comment by nicolasgrinberg** [comment]
Hello, are there any news on this? Is it possible to use both DDA+ and hybrid DIA?

**Comment by anesvi** [comment]
I looked at the log file and noticed a few things. DIA-Umpire crashed, as Fengchao pointed out. However, looking in more detail:
 1. From a the file name, you are doing HLA peptidomics
 2. Your DIA data is narrow window
Processing DIA MS2 (mz range):1610.7758_1611.9757( 15/37495 )
Is is Astral data? If so, we have a different workflow we can recommend that works well for Astral DIA data.
I suggest you contact me directly via email.
Best,
Alexey

**Comment by anesvi** [comment]
So we determined there was a bug in FragPipe when DIA and DIA data were searched together and DDA specified as DDA+. Will be fixed in the next release.

**Comment by ds2268** [comment]
> I looked at the log file and noticed a few things. DIA-Umpire crashed, as Fengchao pointed out. However, looking in more detail:
> 
>     1. From a the file name, you are doing HLA peptidomics
> 
>     2. Your DIA data is narrow window
>        Processing DIA MS2 (mz range):1610.7758_1611.9757( 15/37495 )
>        Is is Astral data? If so, we have a different workflow we can recommend that works well for Astral DIA data.
>        I suggest you contact me directly via email.
>        Best,
>        Alexey

@anesvi can you elaborate more on the proposed Astral workflow that we can use with MSFragger-DIA? It would be great to have such information public (README?) for the wider audience to benefit. Thanks!

**Comment by fcyu** [comment]
Hi @ds2268 ,

You can use the existing built-in DIA related workflows, just not set the DDA data to DDA+ data type for now.

Best,

Fengchao

**Comment by ds2268** [comment]
Hi @fcyu.

Just to confirm: for the nDIA data, as collected for example [here](https://www.nature.com/articles/s41587-023-02099-7) you suggest running the MSFragger-DIA workflow, as presented [here](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#dia_speclib_quant)?

The following was mentioned above: _"Is is Astral data? If so, we have a different workflow we can recommend that works well for Astral DIA data."_

**Comment by fcyu** [comment]
Correct. The `DIA_SpecLib_Quant` workflow performs better than the `DIA_DIA-Umpire_SpecLib_Quant` for Astral data.

Best,

Fengchao

**Comment by xiaodfeng** [comment]
> Correct. The `DIA_SpecLib_Quant` workflow performs better than the `DIA_DIA-Umpire_SpecLib_Quant` for Astral data.
> 
> Best,
> 
> Fengchao

It is a useful statement, I am struggling with DIA_DIA-Umpire_SpecLib_Quant these days.
