### ISSUE TITLE
Cannot run in MacOS (M1 chip, 2020) by Docker desktop

### ISSUE THREAD

**Issue by TJ0526** [Nesvilab/FragPipe#1455]
Dear all,

I have attempted to run Fragpipe on MacOS using Docker desktop. I followed the instructions from both the Fragpipe website and Github, but none of them worked.

On the website (https://fragpipe.nesvilab.org) the instructions were as follows:
1. Install Docker by following the instructions provided on https://docs.docker.com/desktop/install/mac-install/
2. Open the terminal and pull the Docker image by running "docker pull fcyucn/fragpipe"
3. Execute the "fragpipe --headless" command in the terminal

On Github, the instructions were as follows:
1. Install Docker by following the instructions provided on https://docs.docker.com/desktop/install/mac-install/
2. Open the terminal and pull the Docker image by running "docker pull fcyucn/fragpipe"
3. FragPipe is located in "/fragpipe_bin"
4. Go to "/fragpipe_bin/fragPipe-x.x/fragpipe/bin" directory and execute "./fragpipe --help" in the terminal

I also attempted to pull the image into the Docker desktop, but I was unable to define the ports for the container when I ran it. Therefore, Fragpipe could not run in the container in Docker Desktop. Does anyone else have the same issue?

I am not sure what the problem is, could anyone give me any suggestions?

Thank you in advance for your help and time.
TJ
![Screenshot 2024-02-21 at 16 36 44](https://github.com/Nesvilab/FragPipe/assets/160758166/7041a24b-cc0d-4151-bac4-5865464fa884)
![Screenshot 2024-02-21 at 16 37 15](https://github.com/Nesvilab/FragPipe/assets/160758166/d5a1c071-5098-426c-a85b-174f57938a5b)
![Screenshot 2024-02-21 at 16 37 28](https://github.com/Nesvilab/FragPipe/assets/160758166/b8881178-49a4-4ba0-b630-6fe2a5f02eaa)
![Screenshot 2024-02-21 at 16 37 22](https://github.com/Nesvilab/FragPipe/assets/160758166/1600f691-0545-41b3-b759-1511bee19427)

**Comment by fcyu** [comment]
Basically, you should install docker on your computer, pull the image to your local computer, start the image and create the container. 

It seems that you need some help about how to use docker. I am afraid you have to find a person helping you locally because we can't do much remotely.

Best,

Fengchao
