### ISSUE TITLE
Split database script crashed

### ISSUE THREAD

**Issue by wagner-mr** [Nesvilab/FragPipe#1456]
- Describe the issue or question:
Running for the first time on a few sample sets I grabbed online. Using the LFQ-Phospho workflow. I designated 100 GB of RAM and set database split to 128. The search crashed after it worked through all 128 DB splits. What happened? 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-02-21_16-24-30.zip](https://github.com/Nesvilab/FragPipe/files/14365326/log_2024-02-21_16-24-30.zip)

**Comment by guoci** [comment]
It looks like some of the `MSFragger` completed without errors, but the process of writing pep.xml files has errors, can you check if the any output files exists? If not, can you check if location of the output is writable?
