### ISSUE TITLE
Not enough PSMs during DIA RT regression

### ISSUE THREAD

**Issue by jongminchoi** [Nesvilab/FragPipe#1457]
- Describe the issue or question:
Hello,
I'm working on DIA analysis with Fragpipe.
With a data expecting very low identification, I met a never-ending step as "Not enough high quality PSMs for RT regression with escore cutoff of 0.01.....RT regression using 0 PSMs."
Once it met that situation, Fragpipe never go more and just stuck there.
Is there any other way to skip this step?
Thank you

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by jongminchoi** [comment]
Hi, Fengchao
Yes, I already tested without that file and it worked.
So, should I conclude no ID in that data? 
Thank you for your reply. :-)

**Comment by yangkl96** [comment]
Hi,

I suspect you are using an older version of FragPipe? Please upgrade to the newest version. If that still does not work, you can uncheck the "Predict RT" button under MSBooster under Validation tab and rerun that file. There are insufficient PSMs with low enough expectation value to calculate a good RT score anyway.

Thanks,
Kevin

**Comment by jongminchoi** [comment]
Oh, it is great information.
I am using v21.0, so I believe it should be up to date.
I will try without predict RT in MSbooster 
Thank you
