### ISSUE TITLE
MSFragger fails on timsTOF DIA without prior mzML conversion

### ISSUE THREAD

**Issue by dtabb73** [Nesvilab/FragPipe#1460]
Hi, again!

I have been creating spectrum libraries from the "Titration DIA" and "Titration DDA" experiments in PXD031848.  MSFragger in FragPipe was perfectly happy to identify from .d raw data from DDA experiments.  When I tried the same search on the .ds from the DIA experiments, however, it failed immediately, with this error:

Does not support scan modes: 9 (DIA) from E:\PXD031848-DUBs-timsTOF\Titration-DIA\TTP0355_MSQ1766_Probe_100_150ng_S4-C7_26382.d
Does not support scan modes: 9 (DIA) from E:\PXD031848-DUBs-timsTOF\Titration-DIA\TTP0355_MSQ1766_Probe_100_20ng_S4-C4_26318.d
Does not support scan modes: 9 (DIA) from E:\PXD031848-DUBs-timsTOF\Titration-DIA\TTP0355_MSQ1766_Probe_100_500ng_S4-C9_26390.d
Does not support scan modes: 9 (DIA) from E:\PXD031848-DUBs-timsTOF\Titration-DIA\TTP0355_MSQ1766_Probe_100_50ng_S4-C3_26366.d
Does not support scan modes: 9 (DIA) from E:\PXD031848-DUBs-timsTOF\Titration-DIA\TTP0355_MSQ1766_Probe_100_100ng_S4-C5_26374.d
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

I converted the Titration DIA .ds to mzML using timsConvert (default options other than "verbose") and provided the mzMLs instead of the .ds, and the search proceeded normally.

Thanks!

**Comment by fcyu** [comment]
Hi Dave,

MSFragger currently does not support searching diaPASEF data, so I let it print an error message and stop. 

But if you provides the mzML file that does not contain the scan type information, MSFragger won't know that it is a diaPASEF and search as normal. However, the result might look bad...

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Dave,

I am not sure what timsConvert writes to the mzML, but the scan mode 9 is from the `*.tdf` file of the `*.d` folder.

Regarding analyzing the diaPASEF, unfortunately, DIA-Umpire also does not support it. BUT, we have a new unpublished tool that can do. You probably need to send an email to Alexey: https://x.com/nesvilab/status/1753533812850692572?s=20

Best,

Fengchao

**Comment by dtabb73** [comment]
I have been quite impressed with how well timsConvert behaves with PASEF data.  I am attaching Google Drive links to a DDA mzML and a DIA mzML produced by timsConvert from .d directories from PXD031848.  They represent the same human sample, I believe.
DDA Example: https://drive.google.com/file/d/1ml4jwLnhaE3KciKpgvqD8HnZh06Gttg-/view?usp=sharing
DIA Example: https://drive.google.com/file/d/1T5hzPPN-1pRY9KjLDOYxGn6K5qZjAEXg/view?usp=sharing
