### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by plyush1993** [Nesvilab/FragPipe#1462]
Hello everyone,
Could you please reveal exactly which type of "intensity normalization across run" is used in FragPipe?
I compared with median normalization and it seems that in FragPipe smth different is used.

Best regards,
Ivan

**Comment by fcyu** [comment]
Hi Ivan,

We described the algorithm here https://www.mcponline.org/article/S1535-9476(20)35104-5/fulltext#:~:text=developed%20a%20piecewise-,normalization,-algorithm%20in%20IonQuant

Best,

Fengchao

**Comment by plyush1993** [comment]
Thanks a lot!

Best regards,
Ivan
