### ISSUE TITLE
When I updated to the newest version FragPipe(V21.0), the page of Quant(Isobaric) was different from the version 20.0, which lacked the option of TMT-integrator 

### ISSUE THREAD

**Issue by Nicolevswy** [Nesvilab/FragPipe#1463]
The absent of TMT-integrator resulted in the decrease of identified proteins and peptides in TMT experiment. Please help me solve the problem. Maybe find the option "Run TMT-integrator" is the key.

**Comment by fcyu** [comment]
I am not sure if I follow the question. Could you elaborate it more? Some screenshots and log files will be helpful.

Best,

Fengchao

**Comment by Nicolevswy** [comment]
![20 0](https://github.com/Nesvilab/FragPipe/assets/128340309/a008f538-6c26-4f57-a4ab-d3c443d5805b)
The version 20.0 is shown above with TMT-integrator.
![21 0](https://github.com/Nesvilab/FragPipe/assets/128340309/6b02f692-aa74-4562-b7e1-36ec8cdebb83)
While the version 21.0 is lack of TMT-integrator.
Although it also runs, the results are not ideal.

**Comment by fcyu** [comment]
We renamed "Run TMT-Integrator" to "Run Isobaric Quant", and add IonQuant as one of the intensity extraction tools (in version 20.0, Philosopher is the only option).  After isobaric ion intensity extraction, TMT-Integrator will be used to normalize the intensity and generate the report, same as what version 20.0 does. You will also see that rest of the parameters are not changed. 

Best,

Fengchao

**Comment by Nicolevswy** [comment]
But When I run the same files, the number of identified proteins and peptides by 21.0 is less than 20.0，why？

**Comment by fcyu** [comment]
Could you share the log files (the file with name starting with log_) of two versions? 

Thanks,

Fengchao
