### ISSUE TITLE
Issues related to TMT6plex quantization

### ISSUE THREAD

**Issue by Hanqing1205** [Nesvilab/FragPipe#1464]
- Describe the issue or question:

Hello, I have encountered some problems when performing a TMT6plex retrieval with a total of 12 fractions in the sample and the following experimental groupings:
![image](https://github.com/Nesvilab/FragPipe/assets/133129481/65efffb3-b312-492f-a8ab-c3962d445337)

We have the following problems with the search results: 1. There are very few results in the TMT output price folder, only a few hundred peptides were quantified. 2. We cannot find the intensity value for each channel under the total output file, such as “combined peptides". There is only one intensity column.
We are using Fragpipe V21.1.
I am looking forward to hearing back from you.
Best wishes
Hanqing

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchao

**Comment by Hanqing1205** [comment]
Thank you very much. This is information you may use.
Since yesterday we have been testing and this is the result of testing with two fraction files.

[log_2024-02-27_09-57-01.txt](https://github.com/Nesvilab/FragPipe/files/14413515/log_2024-02-27_09-57-01.txt)
[combined_modified_peptide.x
[tmt-report.zip](https://github.com/Nesvilab/FragPipe/files/14413530/tmt-report.zip)
lsx](https://github.com/Nesvilab/FragPipe/files/14413523/combined_modified_peptide.xlsx)

**Comment by Hanqing1205** [comment]
> You are looking at wrong files. TMT reports are in TMT-report folder
Hello Anesvi, Thank you for your reply. I have uploaded the TMT-report data. It is another question that we have found very little data has been quantified.

**Comment by fcyu** [comment]
Hi @Hanqing1205 , could you also share the psm.tsv?

Thanks,

Fengchao

**Comment by Hanqing1205** [comment]
> Hi @Hanqing1205 , could you also share the psm.tsv?
> 
> Thanks,
> 
> Fengchao
Sure. psm is in the drug folder. Also, other files you may need.
[TEST.zip](https://github.com/Nesvilab/FragPipe/files/14413814/TEST.zip)

[drug.zip](https://github.com/Nesvilab/FragPipe/files/14413813/drug.zip)

**Comment by fcyu** [comment]
Hi @Hanqing1205 , thanks for the files. Most of the PSMs have zero TMT channel intensities. I am not sure of the cause for now, but could you convert the raw files to mzML format (according to the tutorial here https://fragpipe.nesvilab.org/docs/tutorial_convert.html) and try again? It may be due to the incompatible raw format.

Best,

Fengchao

**Comment by Hanqing1205** [comment]
> Hi @Hanqing1205 , thanks for the files. Most of the PSMs have zero TMT channel intensities. I am not sure of the cause for now, but could you convert the raw files to mzML format (according to the tutorial here https://fragpipe.nesvilab.org/docs/tutorial_convert.html) and try again? It may be due to the incompatible raw format.
> 
> Best,
> 
> Fengchao

Hello, Fengchao, thanks a lot. I'll try it right away.
Thanks,
Hanqing

**Comment by fcyu** [comment]
> People should select MS3 quant level (even MS2 acquisition) or convert the raw files to mzML format, it runs correctly.

Thanks for your positive feedback. Could you do one more testing: use your correct setting and raw file format to see if FragPipe gives good results? Theoretically, both mzML and raw format should give very similar results. Your previous problem should be just due to the incorrect quant level.

Best,

Fengchao

**Comment by Hanqing1205** [comment]
> > People should select MS3 quant level (even MS2 acquisition) or convert the raw files to mzML format, it runs correctly.
> 
> Thanks for your positive feedback. Could you do one more testing: use your correct setting and raw file format to see if FragPipe gives good results? Theoretically, both mzML and raw format should give very similar results. Your previous problem should be just due to the incorrect quant level.
> 
> Best,
> 
> Fengchao

OK, no problem! I am glad that I can help with this good software. I will give my feedback soon.
All best,
Hanqing

**Comment by Hanqing1205** [comment]
[tmt-report-after_covert.zip](https://github.com/Nesvilab/FragPipe/files/14430457/tmt-report-after_covert.zip)
[tmt-report.zip](https://github.com/Nesvilab/FragPipe/files/14430460/tmt-report.zip)

Hi, Fengchao, I have uploaded the TMT files, please take a check. I have found that both mzML and raw format give very similar results, but I also found that protein from Fragpipe lost about 12% (900+) compared with Peaks.
Another question is that the TMT result does not contain peptides with modification. Do I have any other ways to solve this? We use peptides with modification to further quantification.
 
All best,
Hanqing

**Comment by fcyu** [comment]
Hi Hanqing,

Thanks for your test and feedback.

> I also found that protein from Fragpipe lost about 12% (900+) compared with Peaks.

As far as I know, PEAKS performs the FDR filtering in a different way. To compare with FragPipe, you probably need to adjust PEAKS' FDR to filter at both PSM- and portein-level 1%.

> Another question is that the TMT result does not contain peptides with modification. Do I have any other ways to solve this?

Unfortunately, no.

Best,

Fengchao

**Comment by Hanqing1205** [comment]
Ok, thank you for you reply, It helps me a lot.
Best wishes,
Hanqing ---- Replied Message ***@***.***>Date02/28/2024 20:52 ***@***.***> ***@***.***>***@***.***>SubjectRe: [Nesvilab/FragPipe] Issues related to TMT6plex quantization (Issue #1464)
Hi Hanqing,
Thanks for your test and feedback.

I also found that protein from Fragpipe lost about 12% (900+) compared with Peaks.

As far as I know, PEAKS performs the FDR filtering in a different way. To compare with FragPipe, you probably need to adjust PEAKS' FDR to filter at both PSM- and portein-level 1%.

Another question is that the TMT result does not contain peptides with modification. Do I have any other ways to solve this?

Unfortunately, no.
Best,
Fengchao

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Nesvilab/FragPipe/issues/1464#issuecomment-1968921804",
"url": "https://github.com/Nesvilab/FragPipe/issues/1464#issuecomment-1968921804",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
