### ISSUE TITLE
FragPipe Labile mode search_How to get the matching results of fragment ions(b,y) with labile modification

### ISSUE THREAD

**Issue by Lang5991** [Nesvilab/FragPipe#1467]
Dear FragPipe Team,

Recently, I am fucosing on labile-mode search with FragPipe. However, I don't know how to get the matching results of fragment ions(b,y) with labile modification
<img width="428" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/143386047/8052b114-aedd-4176-8bb1-e0a01e7f6acb">
Just  like the above picture,  Could you kindly help me, thank you.

**Comment by KaiLiCn** [comment]
Hi,

To get the match result with labile modification like above pic, you need to manually assign a new mass on the amino acid. 

Right now, there are two ways to do that in FP-PDV.
1. Generate a mirror spectrum like above. 

> Click `Tools `and then select `Check peptide`.
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/e0936785-0781-418c-8777-4e85535bc365)

> Click `Add `button then select `Add peptide`
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/b00a909f-9419-40da-b506-b683c9fc7d67)

> A dialog with same peptide will be shown. In this example, there is a modification on `C`. You could click `C` in the panel and type any mass in dropdown menu or select other modification. And click `Enter ` key then `Add `it
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/c82a721b-fce5-4069-bb6c-6207b2ba270e)

![image](https://github.com/Nesvilab/FragPipe/assets/29800230/fc0e1be8-2649-42ec-95ac-cc28b78c6d72)


2. Change modification mass

> Click `Tools `and then select `Change modifications`

![image](https://github.com/Nesvilab/FragPipe/assets/29800230/a4e6761f-5826-4300-9041-ccac87d04721)

> A table with original modifications will be shown. Click the cell in `New Defined` column. Type any mass in dropdown menu or select other modification. And click `OK`. If you want to reset the mass, click `Re-Set` in the final column.
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/35c8e2f8-5f5c-4a31-8985-5a53d5d16d06)

Let me know if you meet any issue when you try it.

Kai

**Comment by Lang5991** [comment]
> Hi,
> 
> To get the match result with labile modification like above pic, you need to manually assign a new mass on the amino acid.
> 
> Right now, there are two ways to do that in FP-PDV.
> 
> 1. Generate a mirror spectrum like above.
> 
> > Click `Tools `and then select `Check peptide`.
> > ![image](https://private-user-images.githubusercontent.com/29800230/308638732-e0936785-0781-418c-8777-4e85535bc365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2Mzg3MzItZTA5MzY3ODUtMDc4MS00MThjLTg3NzctNGU4NTUzNWJjMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODBhMzQwNWVkOTEwMDZmYzNlYTllNjAwODE2ZGQ4OTgwNTA0MmU0OThkMjYwOWExZTczMzVlMDI0ZTA1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkqqxkB9oZboV3WZryuGqgM_816brMfBgTThxMaDAzM)
> 
> > Click `Add `button then select `Add peptide`
> > ![image](https://private-user-images.githubusercontent.com/29800230/308639279-b00a909f-9419-40da-b506-b683c9fc7d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2MzkyNzktYjAwYTkwOWYtOTQxOS00MGRhLWI1MDYtYjY4M2M5ZmM3ZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMTY0NGMzYTZjODgzMDlkYjc1MjE0NTMwODMxYjlmZjAxZTc4MDlhY2Q4Y2Q4OThjMjQzOGNiYzQ2MDk3MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1emNZ51O9sJ_axDPOClb9g72TJ6KXtMPcPyadIp2qts)
> 
> > A dialog with same peptide will be shown. In this example, there is a modification on `C`. You could click `C` in the panel and type any mass in dropdown menu or select other modification. And click `Enter ` key then `Add `it
> > ![image](https://private-user-images.githubusercontent.com/29800230/308640213-c82a721b-fce5-4069-bb6c-6207b2ba270e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2NDAyMTMtYzgyYTcyMWItZmNlNS00MDY5LWJiNmMtNjIwN2IyYmEyNzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMDFmOGRjMmUwMzU1YTg3NGNlMmYzMmJmNDIzYjY0NDZlODBlYWUzOGFlZTFjODViOWFlOTIyYThhNDM4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2iCvfgdtmHAC_OzlCJ2-62aXqZwPq7ZJ7Xvp_hEkUQ)
> 
> ![image](https://private-user-images.githubusercontent.com/29800230/308643192-fc0e1be8-2649-42ec-95ac-cc28b78c6d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2NDMxOTItZmMwZTFiZTgtMjY0OS00MmVjLTk1YWMtY2MyOGI3OGM2ZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODIyNjU2OGNjMWRlM2ZmODMxYjM5ZjQ5ZmY3MjdkZDJjNGJjMDhmNGVlZDViZGJkYmQ5MzZkZTA0NTZmN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wMU_0SPQuV_kLeFDySQTXH9njzSW6uBZTvm_N7wG3zI)
> 
> 2. Change modification mass
> 
> > Click `Tools `and then select `Change modifications`
> 
> ![image](https://private-user-images.githubusercontent.com/29800230/308641285-a4e6761f-5826-4300-9041-ccac87d04721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2NDEyODUtYTRlNjc2MWYtNTgyNi00MzAwLTkwNDEtY2NhYzg3ZDA0NzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwY2RjNWVhMTNjMDhiYjEwYjY3YjIxMzcyNDcwZTY5MzM2YzE0N2Q3Zjk3OTIzNTc2OTBjOTRlMTY5NWU3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vYXVEYv8FvH2zjcX-C3kd2BKUSx11HmAutGGFmYeuk4)
> 
> > A table with original modifications will be shown. Click the cell in `New Defined` column. Type any mass in dropdown menu or select other modification. And click `OK`. If you want to reset the mass, click `Re-Set` in the final column.
> > ![image](https://private-user-images.githubusercontent.com/29800230/308642114-35c8e2f8-5f5c-4a31-8985-5a53d5d16d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODgzMjAsIm5iZiI6MTcwOTE4ODAyMCwicGF0aCI6Ii8yOTgwMDIzMC8zMDg2NDIxMTQtMzVjOGUyZjgtNWY1Yy00YTMxLTg5ODUtNWE1M2Q1ZDE2ZDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTNlZTUwOTAwNGY2Njk1MGI5OGU0NDViYzVjODY2ZGM3MzBhNWYyYzg1ZmFjYmVkZTI5YzhmZTQyNGUxMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bs0D1myvxn46ca6Hj_4S7y8QcB6p1sQjGMDza-aHtA0)
> 
> Let me know if you meet any issue when you try it.
> 
> Kai

Dear Kai,
Thanks so much for your kind help! I will try the method you provided. 
But I still have the problem that can we get the MS/MS matching results from output files?  I'm desperate to know the actual matching result(real situation of Fragpipe) of fargment ions(b,y) of the matched peptide with labile modification. 
I look forward to hearing from you! Thanks.

**Comment by fcyu** [comment]
@Lang5991 unfortunately, the tsv report doesn't have the matched ions information. 

Best,

Fengchao

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/719

**Comment by Lang5991** [comment]
> @Lang5991 unfortunately, the tsv report doesn't have the matched ions information.
> 
> Best,
> 
> Fengchao

Dear Fengchao,
I found that In Spec Lib part, we can generate spectral library from search results, and the output file "library.tsv" contains the b,y matching ions information.
<img width="506" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/143386047/fc44235b-5374-4a90-bba9-0b0018c42f8c">
<img width="371" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/143386047/adc2592e-a164-4eb2-bcc3-5f89e521e25b">
I wonder Is this the actual right matching ions information?

**Comment by fcyu** [comment]
They are matched ions generated by the spectral library generation module, not from MSFragger. Also, it is for precursor, not PSM.

Best,

Fengchao

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/885

I have implemented the feature to report the matched fragments. Let MSFragger generate the tsv report will have those two new columns. If you want to try the pre-released version, please send an email to yufeATumich.edu (replace `AT` with `@`).

Currently, there are some limitations

The reported fragments are not exactly the one used in the scoring because MSFragger does not record such information (to be fast). I let it "re-match" the fragments when generating the report.
The fragments are deisotoped by default, so the reported matches only have singly charged. Disabling the deisotoping in the database search will have doubly charged fragments being matched, but the sensitivity is sub-optimal.
It only supports closed search now, but I will extend it to open and mass-offset search in the future.
Best,

Fengchao
