### ISSUE TITLE
errors in running fragpipe - reported corrupted files 

### ISSUE THREAD

**Issue by ibphuangchen** [Nesvilab/FragPipe#1469]
Hi,

I run Fragpipe for my cohort but the pipeline got stuck in the MSFragger. Attached please find the log file.
It looks like one or two of the raw input .raw files are 'corrupted'. But I tried three times and each time the pipeline report different corrupted files, while such files are reported good in other runs. Also, this raw files can be run through using maxquant.

Could you please take
[log_2024-02-29_02-54-13.txt](https://github.com/Nesvilab/FragPipe/files/14451727/log_2024-02-29_02-54-13.txt)
 a look at my log file?

**Comment by fcyu** [comment]
Something about the operating system and file system don't seem right. Could you convert the raw files to mzML format (https://fragpipe.nesvilab.org/docs/tutorial_convert.html) ?

Thanks,

Fengchao
