### ISSUE TITLE
question about assigning a specific protein N-term mod

### ISSUE THREAD

**Issue by mt-forrester** [Nesvilab/FragPipe#1470]
Hello.

I'm interested in searching with protein N-term myristoylation as a variable mod. However, this mod is typically restricted to protein N-terminal Gly residues and I'm only able to specify the mod as any protein N-term. While including this variable mod does indeed allow us to ID bona fide N-terminal peptides known to be myristoylated, it would be better if I can specify this variable mod only on N-terminal protein Gly residues rather than any N-term residue. Is this possible within MSFragger variable mods? If so can you kindly advise me?

Thank you in advance

Michael T. Forrester
Duke University

**Comment by fcyu** [comment]
Yes, use `[G` for protein N-term Glycine.

Best,

Fengchao

**Comment by mt-forrester** [comment]
thank you Fengchao. much appreciated!
