### ISSUE TITLE
How to manually calculate protein intensity

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1471]
- Describe the issue or question

Dear developer

I'm using frapipe to analyse some TMT data, but we are only focusing on one particular group of proteins. We want to remove peptides that mapped to both classical proteins as well as these proteins, but I found that if I set peptide-proteins uniqueness to unique in quant, I will lose a very large amount of peptides, this is because there will be a lot of razor peptides within this group of proteins and we want to keep this part of the peptide.

So I was wondering if I could manually calculate the protein intensities based on the peptide intensities from the TMT integrator data? But I am not sure what is the principle of combining peptide intensities into protein intensities in TMT data,can you give me some suggestions?

Thanks,
LeeLee

**Comment by fcyu** [comment]
Yes, you can. There are literatures talking about it. It is mostly using the top-N intensities.

Best,

Fengchao

**Comment by lbwfff** [comment]
Hi Fengchao, thanks for your reply. I am considering to use MSstatsTMT for the analysis so that I can filter out some of the PSM or peptide by myself. and I have some problems with importing the Philosopher output using the PhilosophertoMSstatsTMTFormat function provided by MSstatsTMT. I found that the MSstats.csv output from Philosopher looks like this.

```
(base) lb4489@login4:/scratch/lb4489/project/MS_data/test_fdr/tmt_group_p1$ tail MSstats.csv 
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_02,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_04,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_05,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_06,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_07,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_08,NA
sp|Q9Y6Y8|S23IP_HUMAN,n[229.1629]LEPM[15.9949]IVPDLDLK[229.1629],831,842,2,NA,NA,L,11,11,Carlyle_TMTpool_11_fraction_09,NA
```

This doesn't seem to match the inputs required by MSstatsTMT, and I'm not quite sure if it's caused by my use of TMT10-MS3.workflow. Can you help me see why?

Thanks,
LeeLee

**Comment by fcyu** [comment]
I never used Philosopher output for MSstatsTMT. In the next release, we will have a better support for the MSstatsTMT.

Best,

Fengchao
