### ISSUE TITLE
Runnig FragPipe docker version with raw files

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1474]
Hello

I would like to know if the FragPipe docker version allows to process raw files. I tried and I got this log trace: 

```
MSFragger [Work dir: /home/tmp/work-5-cpus]
java -jar -Dfile.encoding=UTF-8 -Xmx162G /home/tmp/extra-tools-21.1/MSFragger-4.0/MSFragger-4.0.jar /home/tmp/work-5-cpus/fragger.params /users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan/2024MQ006_FCAN_007_01_45pto.raw
MSFragger version MSFragger-4.0
Batmass-IO version 1.30.0
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 18.0.2-ea, OpenJDK 64-Bit Server VM, Private Build
JVM started with 162 GB memory
Checking database...
Failed in checking /users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan/2024MQ006_FCAN_007_01_45pto.raw. Will ignore it.
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found
There are corrupted files. Please remove those files and re-start the task.
Checking spectral files...
/users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan/2024MQ006_FCAN_007_01_45pto.raw: Scans = 0; Isolation sizes = []
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

If I put the mzML converted file the workflow runs without any problem. 

Thanks!

**Comment by fcyu** [comment]
Do you have the `ext` folder located in `/home/tmp/extra-tools-21.1/MSFragger-4.0/` ?

Thanks,

Fengchao

**Comment by rolivella** [comment]
@fcyu yes, I have it. I mounted my local folder to `/home/tmp` like this: 

```
singularity exec -e --bind /users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan:/home/tmp docker://proteomicsunitcrg/fragpipe:21.1 /home/fragPipe-21.1/fragpipe/bin/fragpipe --headless --workflow /home/tmp/open-quickscan-settings.workflow --manifest /home/tmp/open-quickscan-settings.manifest --workdir /home/tmp/work-ionquant-true/
```

**Comment by rolivella** [comment]
And: 
```
~/mysoftware/fragPipe-20.1/open-quickscan$ ll extra-tools-21.1/
total 180552
drwxrwx--- 5 proteomics CRG_Proteomics      238 Feb 27 11:34 ./
drwxrwx--- 6 proteomics CRG_Proteomics      841 Mar  4 16:46 ../
drwxrwx--- 2 proteomics CRG_Proteomics      146 Feb 27 11:34 IonQuant-1.10.12/
-rw-rw---- 1 proteomics CRG_Proteomics 56652033 Feb 27 11:34 IonQuant-1.10.12.zip
drwxrwx--- 3 proteomics CRG_Proteomics      438 Feb 27 11:34 MSFragger-4.0/
-rw-rw---- 1 proteomics CRG_Proteomics 74175925 Feb 27 11:34 MSFragger-4.0.zip
drwxrwx--- 2 proteomics CRG_Proteomics      114 Feb 27 11:34 philosopher_v5.1.0_linux_amd64/
-rw-rw---- 1 proteomics CRG_Proteomics 25697584 Feb 27 11:34 philosopher_v5.1.0_linux_amd64.zip
```

**Comment by fcyu** [comment]
Could you run `/home/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe` in the container to see what does it print?

Thanks,

Fengchao

**Comment by rolivella** [comment]
I get this: 
```
proteomics@makarov:~/mysoftware/fragPipe-20.1/open-quickscan$ singularity exec -e --bind /users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan:/home/tmp docker://proteomicsunitcrg/fragpipe:21.1 /home/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe
INFO:    Using cached SIF image
/home/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe: 1: MZ����@���: not found
/home/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe: 1: Syntax error: "(" unexpected (expecting ")")
```

**Comment by fcyu** [comment]
Thanks for the prompt update. I guess something was not found. Maybe the ext folder was corrupted. Could you download and unzip a new one, and try again?

Thanks,

Fengchao

**Comment by rolivella** [comment]
Ok, I'll do. However, is it possible to run the BatmassIoThermoServer.exe under linux OS?

**Comment by fcyu** [comment]
Yes, it is as long as Mono was installed. 

Oh, it reminds me, you probably should run `mono /home/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe`

Best,

Fengchao

**Comment by rolivella** [comment]
Yes, 
```
proteomics@makarov:~/mysoftware/fragPipe-20.1/open-quickscan$ singularity exec -e --bind /users/pr/proteomics/mysoftware/fragPipe-20.1/open-quickscan:/home/tmp docker://proteomicsunitcrg/fragpipe:21.1 mono /ho
me/tmp/extra-tools-21.1/MSFragger-4.0/ext/thermo/BatmassIoThermoServer.exe
INFO:    Using cached SIF image
FATAL:   "mono": executable file not found in $PATH
``` 

Maybe we miss to put mono in the $PATH at the Dockerfile? I don't remember...

**Comment by fcyu** [comment]
Unfortunately, yes. I will push a new image later. Could you install mono in your container to see if it resolves the problem?

Thanks,

Fengchao

**Comment by rolivella** [comment]
By the way, should this container also support Brucker native output files? Thank you.

**Comment by fcyu** [comment]
Hi @rolivella 

Thanks for the testing. I will add mono to the dockerfile and image.

Yes, it should support Bruker .d as well. 

Best,

Fengchao

**Comment by rolivella** [comment]
Ho @fcyu , I've a related question, for this I reopen the issue: I would like to have the Intensities column after performing an open quick search of a raw file using the linux docker container. For this I put `quantitation.run-label-free-quant=true` but i get this error: `2024-03-05 11:47:34,221 ERROR - FreeQuant doesn't support '.raw' files. Please replace with mzML format or disable the Quant (MS1) tab.`. Can I use IonQuant instead of FreeQuant to get the areas? If yes, what is the parameter to set up? 

Thanks!

**Comment by fcyu** [comment]
Hi @rolivella ,

FreeQuant which is part of Philosopher does not support raw format.
IonQuant supports raw format but it does not support open search for now.

I have a plan to let IonQuant support open search in the future version.

Best,

Fengchao
