### ISSUE TITLE
QuantUMS in DIA-NN Speclib Quant 

### ISSUE THREAD

**Issue by MHBI2018** [Nesvilab/FragPipe#1475]
Hello,

How do we access the QuantUMS feature in the DIA-NN in FragPipe V21.1? In the standalone DIA-NN 1.8.2-beta GUI, it is usually a drop down option. Do we need to add a command to call the UMS function in DIA-NN tab in FragPipe?

Thanks,
MH

**Comment by fcyu** [comment]
If you specify the path of the new DIA-NN to the FragPipe config tab, that `quantification strategy` dropdown menu will be changed accordingly ;) 

Best,

Fengchao
