### ISSUE TITLE
Cannot read file. open .meta\pep.bin: The system cannot find the file specified.

### ISSUE THREAD

**Issue by NusMSMS** [Nesvilab/FragPipe#1477]
# Issue Summary
I encountered a similar premature termination issue during two attempts at processing timsTOF pro raw data with FragPipe's default workflow. It seems to get stuck on Philosopher. I kindly request your assistance in resolving this.

## Description
- **Detailed Issue**: In both attempts, the process terminated prematurely at the PhilosopherReport step. The error message indicates an inability to read the `.meta\pep.bin` file, which seems to be the direct cause of the termination.
PhilosopherReport [Work dir: G:\Workspace\20240302_...\HeLa_..._1]
D:\Software\FragPipe-jre-19.1\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe report
INFO[10:50:09] Executing Report v5.1.0
INFO[10:50:09] Creating reports
ERRO[10:50:09] Cannot read file. open .meta\pep.bin: The system cannot find the file specified.
Process 'PhilosopherReport' finished, exit code: 1
Process returned non-zero exit code, stopping
- **Steps to Reproduce**: Selected Default Workflow and Loaded. Set Global settings to RAM = 0, Parallelism = 15. Loaded 6 .d files produced by timsTOF, chose MS data type as IM-MS, and set the Experiment name.

## Environment
- Device information: Processor: 12th Gen Intel(R) Core(TM) i5-12600KF 3.70 GHz; RAM: 32.0 GB
- Operating System: Windows 11 22H2
- Fragpipe version: 19.1
- MSFragger version: 4.0
- IonQuant version: 1.10.12
- Philosopher version: 5.1.0
- Python version: 3.9.13
- EasyPQP version: 0.1.42

## Attempted Solutions
I tried to perform a database search on the individual .d file corresponding to the error message, and it could be completed normally.

**Comment by fcyu** [comment]
It was due to version incompatibility. FragPipe 19.1 is not compatible with Philosopher 5.1.0. Could you upgrade FragPipe to 21.1 and try again?

Thanks,

Fengchao

**Comment by NusMSMS** [comment]
Thanks so much for your prompt reply. I've tried on FragPipe v21.1 and it worked. Best wishes.
