### ISSUE TITLE
MSFragger OSError: [WinError 1455] The paging file is too small for this operation to complete

### ISSUE THREAD

**Issue by SamueldelaCamaraFuentes** [Nesvilab/FragPipe#1478]
Hello FragPipe team

I am going to detail an error I have just encountered while executing my analysis in FragPipe. First of all these are my software expecifications: 

- FragPipe v21.1
- MSFragger v4.0
- IonQuant v1.10.12
- Philosopher v5.1.0

My purpose is to perform a DDA analysis over 142 ".d" files using the Human Oral Microbiome Database  composed  by 23 million of sequences whose total size is equal to 18GB with decoys. Due to the Database size I establish a "split database" parameter value of 20 in order to split the database in 20 chunks. The error arise when the 20 split are performed displaying the following message:

 Traceback (most recent call last):
  File "C:\Users\userpd\anaconda3\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 378, in write_pepxml
    write_pepxml_single_rank(infile.with_suffix(f'.{output_file_extension}'),
  File "C:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 384, in write_pepxml_single_rank
    pepxml_header, = set(get_pepxml_header(e) for e in pepxml_parts)
  File "C:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 384, in <genexpr>
    pepxml_header, = set(get_pepxml_header(e) for e in pepxml_parts)
  File "C:\FragPipe-jre-21.1\fragpipe\tools\msfragger_pep_split.py", line 275, in get_pepxml_header
    mm= mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
OSError: [WinError 1455] The paging file is too small for this operation to complete

Previously I performed a test analysis with one ".d" file and the same database and it performed correctly that´s why I have no idea why this error is happenning.

My CPU specifications include 256 GB of RAM and the results are being saved in a hard disk of 3 TB of empty space. The analysis where the error arised had set a RAM value equal to 200 GB with a parallelism of 74.
Here I attach both the log and the full fragger parameters file.

Thank you so much in advance for the help,

Samuel
[log_2024-03-05_08-35-19.txt](https://github.com/Nesvilab/FragPipe/files/14493142/log_2024-03-05_08-35-19.txt)
[fragger.txt](https://github.com/Nesvilab/FragPipe/files/14493145/fragger.txt)

**Comment by fcyu** [comment]
Hi Samuel,

I think is was due to not enough memory. The operating system tried to use the hard drive as the virtual memory and got the error.

Best,

Fengchao

**Comment by SamueldelaCamaraFuentes** [comment]
Hi Fengchao, 

I have no other machine with more memory so, do you think that by spliting the initial database by two ( 9GB) in order to reduce the memory required could be a useful solution for my case? and performing two analysis, one with the first half and the other with the other half of the database. Thank you so much again for your help.

Best,

Samuel

**Comment by fcyu** [comment]
Hi Samuel,

It seems that there was not enough memory when FragPipe tried to merge the search results with different chunks of databases. I am not sure if there is a good solution to this problem. 

BTW, I see that you were perform a nonspecific search for 18 GB database with 142 .d files. Not sure if there is an easy way to get it done without try and error.

Best,

Fengchao
