### ISSUE TITLE
Extracting the intensities of [M+4], [M+5], [M+6] ... isotopes

### ISSUE THREAD

**Issue by HijaziHassan** [Nesvilab/FragPipe#1480]
Hello, 

In a 13C-glucose labelling experiment, multiple isotopes can emerge especially for heavily modified peptides by acetylation (more than three sites). 

Is there an option to extract the AUCs of a user-defined number of isotopes? 

Thank you.

**Comment by anesvi** [comment]
Not sure what to suggest exactly except perhaps you can use skyline?

**Comment by HijaziHassan** [comment]
Thank you Alexey. Actually I did use Skyline at the very beginning but then I got stuck since as mentioned by the developers:

> It is limited to including only isotopes expected to have at least 1% of the total distribution.

But then we found a workaround using Skyline itself suggested in this paper:

> To extract the M+0 through M+8 isotopologues for each peptide identified, the results were analyzed as if they were SILAC labeled, considering the M+0 through M+4 isotopologues as the isotope envelope for the “light” peptide (peptide identified by the PD2.1 search) and the M+4 through M+8 isotopologues as the “heavy” peptide (+4.01342 Da was added under the “Isotope Modifications” in the “Peptide Settings” menu to represent the addition of four 13C isotopes).

[McDonnell et al](https://www.sciencedirect.com/science/article/pii/S2211124716313985?via%3Dihub)
