### ISSUE TITLE
Error on Running Quant MS1 and SpecLibrary

### ISSUE THREAD

**Issue by hcahaya** [Nesvilab/FragPipe#1483]
Hello, using a dda pasef data, I was trying to run MS1 Quant (default setting) and also generate spectral library (default setting) at the same time. 
I kept getting a pop-up message about naming my sample run. 
"IonQuant Error" IonQuant with MBR requires designating LCMS runs to experiments. 
I already named my sample run, but I still kept getting the same pop-up error. 
Is it not possible to run both at the same time? 

Thanks

![image](https://github.com/Nesvilab/FragPipe/assets/65641448/50902e0b-3de8-43b8-a555-0bbaaf89892f)

**Comment by fcyu** [comment]
> I was trying to run MS1 Quant (default setting) and also generate spectral library (default setting) at the same time.

Unfortunately, you can't do both at the same time. Please run FragPipe twice.

Best,

Fengchao
