### ISSUE TITLE
Fragpipe run appears not to proceed beyond DIA-NN predictions

### ISSUE THREAD

**Issue by ashwinkallor** [Nesvilab/FragPipe#1484]
Hello,

I am running the Non-Specific HLA workflow for a set of DDA mzML immunopeptidomics experiment files. These are the versions of the tools I am running:

Version info:
FragPipe version 21.1
MSFragger version 4.0
IonQuant version 1.10.12
Philosopher version 5.1.0

I am running this on a computing cluster and had initially set the time-limit for 8 hrs and with 40 Gb of memory per CPU (SLURM). However, I noticed that DIA-NN appears not to converge and the time-limit is overshot as follows:

Edited pin file at /some_dir/PXD017149/out_p3/sample_141230_MDM_RCC476_Tu_Tue39L243_Adjusted_20_Rep3_25cm90min3s_msms15_mzML/141230_MDM_RCC476_Tu_Tue39L243_Adjusted_20_Rep3_25cm90min3s_msms15_edited.pin
Processing 
```

``` some_dir/PXD017149/PXD017149_3/141230_MDM_RCC476_Tu_Tue39L243_Adjusted_20_Rep4_25cm90min3s_msms17.mzML
Loading pin
...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

Not enough high quality PSMs for RT regression with escore cutoff of 0.01. Relaxing escore cutoff to 0.01
Warning: not enough target PSMs are available for regression, setting RT scores equal to 0
RT regression using 0 PSMs
slurmstepd: error: *** JOB 7920598 ON ac0294 CANCELLED AT 2024-03-08T11:59:29 DUE TO TIME LIMIT ***


My question is why is DIA-NN running even though I have set "diann.run-dia-nn=false" in my workflow? Also, is there a workaround assuming that DIA-NN cannot be bypassed? Many thanks for your help.


- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by yangkl96** [comment]
Hello,

This is an error at the MSBooster step, which uses predicted spectra and retention time to get more peptide identifications. Using it with HLA data gets you around 30% more IDs. You can turn it off by unchecking the MSBooster checkbox in the validation tab, or setting msbooster.run-msbooster=false. If you want to keep using it, could you download a more up-to-date version at https://www.dropbox.com/scl/fi/t8cce4wd4lkfs6iaiuuwr/MSBooster-1.2.7.jar?rlkey=xysbba9ppw8tulna8qcjp4wk4&e=1&dl=0

Best,
Kevin

**Comment by ashwinkallor** [comment]
Dear Kevin,

Many thanks for your reply. Please keep this thread open while I try out what you've told me and check the progress. In the meantime I have two other questions:

a) The same issue (as above) has also been observed when I run the "LFQ-MBR" workflow for proteomics runs (with the same versions of the tools). Should MSBooster be likewise adjusted for this workflow too?

b) I would like to change the peptide-level FDR for Percolator from 1% to 10%. How do I do this?

Many Thanks,
Ashwin

**Comment by yangkl96** [comment]
a) Yes you can use the new MSBooster. I would guess you have files with fewer PSMs which affects the retention time calibration. This issue will be fixed in the next release of FragPipe.

b) Is there a reason you want to set it at 10% in Percolator rather than 10% in the Philosopher filtering step in FragPipe?

**Comment by ashwinkallor** [comment]
Dear Kevin,

This issue seems to have resolved but now I seem to be running into a new one:

Split 1:        Selected feature 1 as initial direction. Could separate 1 training set positives with q<0.01 in that direction.
Split 2:        Selected feature 1 as initial direction. Could separate 2 training set positives with q<0.01 in that direction.
Split 3:        Selected feature 1 as initial direction. Could separate 1 training set positives with q<0.01 in that direction.
Error in the input data: too good separation between target and decoy PSMs.
No-terminate flag set: ignoring error.
Process 'Percolator' finished, exit code: 139
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 631 remaining tasks

I am unsure what "too good separation between target and decoy PSMs" means. How could we resolve this?

**Comment by fcyu** [comment]
>  Could separate **1** training set positives with q<0.01 in that direction.

I guess there are no IDs in your data.

Best,

Fengchao

**Comment by yangkl96** [comment]
Does the .pin file you are encountering the issue with have very few IDs? In that case I would remove it from the analysis

**Comment by ashwinkallor** [comment]
Thank you both, @yangkl96  and @fcyu . The pipeline seems to be working now. However, I will confirm later and you can close the thread after that. I'll keep you posted.

**Comment by ashwinkallor** [comment]
Dear both,

Many thanks for all your help. The issue appears to have been resolved now. I am closing it. 

Best,
Ashwin

**Comment by reyes-s** [comment]
What was the solution of this issue? I'm facing the "Error in the input data: too good separation between target and decoy PSMs"

**Comment by fcyu** [comment]
Can you send your log file? 

Best,

Fengchao

**Comment by reyes-s** [comment]
Thanks for your quick replay, this is my log file 
[log_file_16_july_2024.zip](https://github.com/user-attachments/files/16258646/log_file_16_july_2024.zip)

**Comment by fcyu** [comment]
You are using a very old version of FragPipe. The issue should have been fixed in the latest version. Please upload FragPipe, MSFragger, IonQuant, and diaTracer. If the error persist, please send your log file.

Best,

Fengchao
