### ISSUE TITLE
ion.tsv with empty "Observed Modifications" column? 

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1485]
Hello

I made an open quick search with the FragPipe linux docker container and I saw that the [ion.tsv.zip](https://github.com/Nesvilab/FragPipe/files/14539647/ion.tsv.zip) file has no data at the Observed Modifications columns. Am I doing something wrong or some config. parameter is missing? 

Thanks! 

Roger

**Comment by fcyu** [comment]
Hi Roger,

No, you did not do anything wrong. The ion-level collapses PSMs with the same peptide and charge. Thus, there is no single "observed modification" for that. You probably need to take a look at the psm.tsv.

Best,

Fengchao

**Comment by rolivella** [comment]
Hi again, 

I was thinking, if you have this situation, 

`psm.tsv`
| Seq  | Charge  | Modif  |
|---|---|---|
| AAA | +2  |Deamidation |
| AAA | +3  |Deamidation |
| AAA | +3  |Deamidation |

I understand that this will collapse to this in the `ion.tsv` file: 
| Seq  | Charge  | Modif  |#of PSMs|
|---|---|---|---|
| AAA | +2  |Deamidation |1|
| AAA | +3  |Deamidation |2|

So the modification should be preserved at the ion level, right? 

Thanks!

Roger

**Comment by fcyu** [comment]
What about 
Seq | Charge | Modif
-- | -- | --
AAA | +2 | Deamidation
AAA | +3 | Phosphorylation
AAA | +3 | Deamidation

**Comment by rolivella** [comment]
Hi @fcyu I reopen this because I was thinking that if I want only to take into account the deamidation and I don't care the other modification, I still does not have this info at the Observed Modifications column (ion.tsv), but I should have it, right? I attach a sample ion.tsv with all this column empty (and the corresponding peptide.tsv). 

[where_is_deamidation_at_ion_tsv.zip](https://github.com/Nesvilab/FragPipe/files/14743000/where_is_deamidation_at_ion_tsv.zip)

Thanks!
