### ISSUE TITLE
Different number of peptides in different files

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1487]
- Describe the issue or question:

Hi Fragpipe developers, I have some confusion about the output files of fragpipe, for example, I found in LBF analysis that the peptide data of combined_peptide.tsv file and MSstats.csv file will be very different, while in TMT analysis the same combined_peptide.tsv and abundance_ peptide_MD.tsv files will have very different peptide counts.
The combined_peptide.tsv will usually have half as many peptides as the other files, why is that.

**Comment by fcyu** [comment]
I am not sure if I follow your question, but you might need to keep in mind that there are different levels, such as "peptide", "modified peptides", and "ion", in different files when you count the numbers. Different files might have different filters.

Could you elaborate your questions more with some examples?

Best,

Fengchao

**Comment by lbwfff** [comment]
Hi Fengchao, thanks for your reply, sorry the description is not clear. Here I mean "peptide", for example, in TMT analysis, we will output combined_peptide.tsv file and quantitative result abundance_peptide_MD.tsv file. These two files should both output the Philosopher filtered "peptide", but there is a big difference in number.

```
combined_peptide<-read.table('combined_peptide.tsv',sep = '\t',header = T)
abundance_peptide<-read.table('abundance_peptide_MD.tsv',sep = '\t',header = T)

length(unique(combined_peptide$Peptide.Sequence))
[1] 84204
length(unique(abundance_peptide$Peptide))
[1] 146646
```

Why is this, am I misunderstanding the output of combined_peptide.tsv? 

Thanks,

LeeLee

**Comment by fcyu** [comment]
Regarding the comparison between `combined_peptide.tsv` and `abundance_peptide_MD.tsv`, it looks weird. Could you send me both tsv files and the log files?

Regarding the comparison between `combined_peptide.tsv` and `combined_modified_peptide.tsv`, there are duplicated peptide sequences in `combined_modified_peptide.tsv`. Have you considered that? I just checking one of my files, and they look good.

Best,

Fengchao

**Comment by lbwfff** [comment]
Hi Fengchao, considering the size of the file, I used dropbox to upload it, and the link has been sent to your email.

**Comment by lbwfff** [comment]
Oh, I know why, it's because there's some problem with reading combined_peptide.tsv using R. The way the code was reading before skipped a lot of rows, and reading it using data.table::fread would have been many more rows

**Comment by lbwfff** [comment]
Also I have a small problem, in our analysis we customised some proteins like the following.
[demo.txt](https://github.com/Nesvilab/FragPipe/files/14598592/demo.txt)

But the information of these proteins is not parsed well and the output file will look like below:



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/lb4489/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/lb4489/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Peptide Sequence | Prev AA | Next AA | Start | End | Peptide Length | Charges | Protein | Protein ID | Entry Name | Gene | Protein Description | Mapped Genes | Mapped Proteins
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ACAISILGK | M | S | 2 | 10 | 9 | 2 | pep\|sPep_8074\|sPep_8074 | pep\|sPep_8074\|sPep_8074 LDHBP2 OS=Homo sapiens OX=9696 GN=LDHBP2 PE=6 | pep\|sPep_8074\|sPep_8074 LDHBP2   OS=Homo sapiens OX=9696 GN=LDHBP2 PE=6 | pep\|sPep_8074\|sPep_8074 LDHBP2   OS=Homo sapiens OX=9696 GN=LDHBP2 PE=6
ADVPSGSNLYR | R | R | 61 | 71 | 11 | 2 | pep\|sPep_6555\|sPep_6555 | pep\|sPep_6555\|sPep_6555 LYRM9 OS=Homo sapiens OX=9696 GN=LYRM9 PE=6 | pep\|sPep_6555\|sPep_6555 LYRM9   OS=Homo sapiens OX=9696 GN=LYRM9 PE=6 | pep\|sPep_6555\|sPep_6555 LYRM9   OS=Homo sapiens OX=9696 GN=LYRM9 PE=6
AESAFSFKK | M | L | 2 | 10 | 9 | 2 | pep\|sPep_32191\|sPep_32191 | pep\|sPep_32191\|sPep_32191 COPS8 OS=Homo sapiens OX=9696 GN=COPS8 PE=6 | pep\|sPep_32191\|sPep_32191 COPS8   OS=Homo sapiens OX=9696 GN=COPS8 PE=6 | pep\|sPep_32191\|sPep_32191 COPS8   OS=Homo sapiens OX=9696 GN=COPS8 PE=6
AIQESNDTNKGK | K | V | 40 | 51 | 12 | 2,3 | pep\|sPep_6901\|sPep_6901 | pep\|sPep_6901\|sPep_6901 RPL17-C18orf32 OS=Homo sapiens OX=9696   GN=RPL17-C18orf32 PE=6 | pep\|sPep_6901\|sPep_6901   RPL17-C18orf32 OS=Homo sapiens OX=9696 GN=RPL17-C18orf32 PE=6 | pep\|sPep_6901\|sPep_6901 RPL17-C18orf32 OS=Homo sapiens OX=9696   GN=RPL17-C18orf32 PE=6 | C18orf32 | sp\|Q8TCD1\|CR032_HUMAN
AKEAPAPPK | K | A | 5 | 13 | 9 | 3 | pep\|sPep_1560\|sPep_1560 | pep\|sPep_1560\|sPep_1560 RPL23AP49 OS=Homo sapiens OX=9696 GN=RPL23AP49   PE=6 | pep\|sPep_1560\|sPep_1560 RPL23AP49   OS=Homo sapiens OX=9696 GN=RPL23AP49 PE=6 | pep\|sPep_1560\|sPep_1560 RPL23AP49   OS=Homo sapiens OX=9696 GN=RPL23AP49 PE=6



</body>

</html>

can you help me to see what's wrong with my fasta header

Thanks,

LeeLee

**Comment by lbwfff** [comment]
Yes, after replacing header starts with 'tr' the parsing of header information is normal, thank you Fengchao!
