### ISSUE TITLE
PhilosopherFilter: No warning for . and & sign

### ISSUE THREAD

**Issue by kwebber3** [Nesvilab/FragPipe#1488]
- Describe the issue or question:
I was actually able to solve this by renaming folders, but it might be nice to have a warning in case some people put "." or "&" in your parent folder name, which causes problems of course. One of my colleagues wasn't aware of this :)

**Comment by fcyu** [comment]
Thanks for the feedback. Could you tell me which parent folder name? Is that for the LC-MS file, fasta file, or the result folder?

Thanks,

Fengchao

**Comment by kwebber3** [comment]
It was the raw files paths

2024年3月11日(月) 22:19 Fengchao ***@***.***>:

**Comment by fcyu** [comment]
Thanks. I have pushed the fix to https://github.com/Nesvilab/FragPipe/commit/52701d8fd59638fcf44aa8521582e21b0796575c

Best,

Fengchao
