### ISSUE TITLE
Possible configuration issue for timsTOF data

### ISSUE THREAD

**Issue by stharan** [Nesvilab/FragPipe#149]
# Describe the problem

* **I'm submitting a:**
  - [ x] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [x ] _Closed_ search (standard small precursor mass tolerance)
  - [] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
I get an error trying to run a search.  Log file is attached.
[log_2019-11-08_09-26-48.txt](https://github.com/Nesvilab/FragPipe/files/3824940/log_2019-11-08_09-26-48.txt)

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** Windows 10 **
- Java version: **Java 1.8.0_231 **

----

## Describe your experiment
timsTOF PASEF acquistion

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"
HeLa lystate 200ng
...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **
1 timsTOF PASEF acqustion file ~2gb

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **
Human database downloaded via fragpipe

----

## Attach fragger.params file
database_name = C:\Fragpipe\FASTA_database\2019-11-06-td-rev-UP000005640_human.fas
num_threads = 0			# 0=poll CPU to set num threads; else specify num threads directly (max 64)

precursor_mass_lower = -50
precursor_mass_upper = 50
precursor_mass_units = 1			# 0=Daltons, 1=ppm
precursor_true_tolerance = 20
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 50
fragment_mass_units = 1			# 0=Daltons, 1=ppm
calibrate_mass = 2			# 0=Off, 1=On, 2=On and find optimal parameters
decoy_prefix = rev_

isotope_error = 0/1/2			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and phosphorylated peptides (on any residue)
precursor_mass_mode = selected

remove_precursor_peak = 0			# 0 = not remove, 1 = only remove the peak with the precursor charge, 2 = remove all peaks with all charge states. Default: 0
remove_precursor_range = -1.50,1.50			# Unit: Da. Default: -1.5,1.5
intensity_transform = 0			# 0 = none, 1 = sqrt root. Default: 0

localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y

search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P

num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 1			# maximum value is 5

clip_nTerm_M = 1

#maximum of 7 mods - amino acid codes, * for any amino acid, [ and ] specifies protein termini, n and c specifies peptide termini
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
# variable_mod_06 = 0.00000 site_06
# variable_mod_07 = 0.00000 site_07

allow_multiple_variable_mods_on_residue = 1			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence

output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50
report_alternative_proteins = 0			# 0=no, 1=yes

precursor_charge = 1 4			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter

digest_min_length = 7
digest_max_length = 50
digest_mass_range = 500.0 5000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 2			# set maximum fragment charge state to analyze (allowed max 5)

#open search parameters
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0.00			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1.00			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0

# spectral processing

minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 150
min_fragments_modelling = 2
min_matched_fragments = 4
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range

# additional modifications

add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000

add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 11.0
MSFragger version 2.1
Philosopher version 1.5.1 (build 1566924968)


LCMS files:
  Experiment/Group: 
  - C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d

14 commands to execute:
Workspace [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe workspace --clean
Workspace [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe workspace --init
MsFragger [Work dir: C:\MSFragger_results]
java -jar -Dfile.encoding=UTF-8 -Xmx9G C:\Fragpipe\MSFragger-2.1\MSFragger-2.1.jar C:\MSFragger_results\fragger.params C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d
MsFragger
java -cp C:\Fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML C:\MSFragger_results\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML
ReportDbAnnotate [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe database --annotate C:\Fragpipe\FASTA_database\2019-11-06-td-rev-UP000005640_human.fas --prefix rev_
PeptideProphet: Copy pepxml to temp
java -cp C:\Fragpipe\FragPipe.exe umich.msfragger.util.FileCopy C:\MSFragger_results\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML C:\MSFragger_results\fragpipe-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML-temp\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML
PeptideProphet: Workspace init [Work dir: C:\MSFragger_results\fragpipe-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML-temp]
C:\Fragpipe\Philosopher\philosopher.exe workspace --init
PeptideProphet [Work dir: C:\MSFragger_results\fragpipe-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML-temp]
C:\Fragpipe\Philosopher\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Fragpipe\FASTA_database\2019-11-06-td-rev-UP000005640_human.fas 180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML
PeptideProphet: Move pepxmls back
java -cp C:\Fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\MSFragger_results\fragpipe-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML-temp\interact-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pep.xml C:\MSFragger_results\interact-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pep.xml
PeptideProphet: Delete temp
java -cp C:\Fragpipe\FragPipe.exe umich.msfragger.util.FileDelete C:\MSFragger_results\fragpipe-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML-temp
ProteinProphet [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined C:\MSFragger_results\interact-180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pep.xml
ReportFilter [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\MSFragger_results --protxml C:\MSFragger_results\combined.prot.xml
ReportReport [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe report
Workspace [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~ fragpipe.config ~~~~~~~~~
#FragPipe (11.0) runtime properties
#Fri Nov 08 09:25:48 EST 2019
override_charge=false
ui.name.report.check.genspeclib=false
calibrate_mass=On and find optimal parameters
search_enzyme_butnotafter=P
max_variable_mods_per_mod=3
delta_mass_exclude_ranges=(-1.5,3.5)
output_report_topN=1
misc.fragger.remove-precursor-range-hi=1.5
misc.slice-db=1
output_format=PEP_XML
ui.name.downstream.check.run-pep-proph=true
histo_smoothbins=3
peakpicking_width=0.002
ui.name.report.check.dontuseprotprophfile=false
misc.fragger.precursor-charge-hi=4
ui.name.report.check.multiexp=false
misc.fragger.digest-mass-lo=500
min_fragments_modelling=2
ui.name.report.check.printdecoys=false
allowed_missed_cleavage=1
search_enzyme_cutafter=KR
precursor_mass_lower=-50
misc.fragger.clear-mz-hi=0
peakpicking_promRatio=0.3
misc.fragger.remove-precursor-range-lo=-1.5
fragment_mass_units=PPM
num_enzyme_termini=ENZYMATIC
ui.name.report.text.filter=--sequential --razor --mapmods --prot 0.01
ui.name.report.check.labelfree=false
min_matched_fragments=4
max_fragment_charge=2
misc.fragger.precursor-charge-lo=1
ui.name.downstream.text.pep-proph-cmd=--decoyprobs --ppm --accmass --nonparam --expectscore
ui.name.downstream.check.separate-protxml=false
intensity_transform=None
add_topN_complementary=0
num_threads=0
output_max_expect=50
use_topN_peaks=150
remove_precursor_peak=Do not remove
zero_bin_mult_expect=1.00
allow_multiple_variable_mods_on_residue=true
precursor_mass_mode=selected
ui.name.report.check.mzid=false
precursor_mass_units=PPM
mass_offsets=0
misc.ram=0
digest_min_length=7
zero_bin_accept_expect=0.00
minimum_peaks=15
digest_max_length=50
misc.fragger.clear-mz-lo=0
track_zero_topN=0
precursor_true_units=PPM
ui.name.downstream.check.combine-pepxml=false
localize_delta_mass=false
ui.name.downstream.check.run-crystalc=false
max_variable_mods_combinations=5000
ui.name.downstream.check.run-prot-proph=true
search_enzyme_name=Trypsin
clip_nTerm_M=true
ui.name.report.run-shepherd=false
ion_series_definitions=
ui.name.downstream.text.prot-proph-cmd=--maxppmdiff 2000000
fragment_ion_series=b,y
ui.name.report.text.labelfree=--ptw 0.4 --tol 10 --isolated
precursor_true_tolerance=20
precursor_mass_upper=50
report_alternative_proteins=false
isotope_error=0/1/2
misc.fragger.digest-mass-hi=5000
fragment_mass_tolerance=50
minimum_ratio=0.01

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Workspace [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe workspace --clean
INFO[09:25:48] Executing Workspace  v1.5.1                  
INFO[09:25:48] Removing workspace                           
INFO[09:25:48] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\MSFragger_results]
C:\Fragpipe\Philosopher\philosopher.exe workspace --init
INFO[09:25:49] Executing Workspace  v1.5.1                  
INFO[09:25:49] Creating workspace                           
INFO[09:25:49] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\MSFragger_results]
java -jar -Dfile.encoding=UTF-8 -Xmx9G C:\Fragpipe\MSFragger-2.1\MSFragger-2.1.jar C:\MSFragger_results\fragger.params C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d
MSFragger version MSFragger-2.1
Batmass-IO version 1.16.1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 8192 MB memory

***********************************FIRST SEARCH************************************
Parameters:
num_threads = 4
database_name = C:\Fragpipe\FASTA_database\2019-11-06-td-rev-UP000005640_human.fas
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 50.0
fragment_mass_units = 1
calibrate_mass = 2
evaluate_mass_calibration = false
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.50,1.50
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
Selected fragment tolerance 0.25 Da and maximum fragment slice size of 5.56 GB.
159861082 fragments to be searched in 1 slices (2.38 GB total)
Operating on slice 1 of 1: 
	001. 180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.IllegalArgumentException: Not a valid pathDir for Bruker data directory
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFile.<init>(BrukerTdfFile.java:71)
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFileBase.<init>(BrukerTdfFileBase.java:59)
	at edu.umich.andykong.msfragger.t.a(Unknown Source)
	at edu.umich.andykong.msfragger.t.a(Unknown Source)
	at edu.umich.andykong.msfragger.r.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Path must be a directory
	at umich.ms.fileio.filetypes.bruker.BrukerTdfFile.<init>(BrukerTdfFile.java:63)
	... 12 more
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks
MsFragger
java -cp C:\Fragpipe\FragPipe.exe umich.msfragger.util.FileMove C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML C:\MSFragger_results\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.pepXML
Processing interrupted, stopping MsFragger

```

**Comment by fcyu** [comment]
Thanks for your interest in analyzing timsTOF data using MSFragger and FragPipe. 

You should specify the whole .d folder (in your example, should be `C:\data\Caprion\17Sept19\180919_K562_200ng_shortGrad_billerica_lockedAccum_0pt8_Slot1-9_1_367.d`) rather than a .d file inside the .d folder.

Best,

Fengchao

**Comment by stharan** [comment]
Thank you for the quick reply.  Knew it was something silly as I was able
to process data two days ago.

Tharan Srikumar

**Comment by fcyu** [comment]
No problem.

Fengchao
