### ISSUE TITLE
The "Quan usage" implications in the TMT-10 workflow processing PSM.tsv results

### ISSUE THREAD

**Issue by HYCCHENG** [Nesvilab/FragPipe#1490]
- Describe the issue or question:

Hi,We have recently used the TMT workflow for quantitative analysis of data post-translational modification sites, and in the PSM.tsv results， there is a column "quan usage" that does not give a specific meaning in the operating guide. What does this information mean?
Thanks.
- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It means that if that PSM is used in the TMT intensity calculation.

Best,

Fengchao

**Comment by HYCCHENG** [comment]
thanks！Another question is If the “quan usage” output is false and the TMT channel still gives the intensity value, on what basis is this value given？

**Comment by fcyu** [comment]
The intensity is from another PSM of the same peptide/protein/site.

Best,

Fengchao

**Comment by HYCCHENG** [comment]
thank you~~
