### ISSUE TITLE
DIA phospho FDR

### ISSUE THREAD

**Issue by Giu-F** [Nesvilab/FragPipe#1491]
Hi, I have searched some phospho-DIA files with the DIA_SpecLib_Quant_Phospho workflow. 
In the report.tsv output from DiaNN, shall I filter by Global.Q.Value & Global.PG.Q.Value as recomended in the DiaNN GitHub page? 
Thanks in advance.

**Comment by anesvi** [comment]
Please use report-pr matrix file. It is already filtered, and post-priced by FragPipe to add site localization scores
