### ISSUE TITLE
Deploying FragPipe on High-Performance Computing Clusters

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1492]
Hello,

I hope this message finds you in good spirits. I have successfully utilized FragPipe on my Windows platform in the past. Thank you very much for the detailed tutorial! Currently, I am looking to deploy FragPipe on a high-performance computing cluster, but I've observed that the documentation pertaining to command-line execution has been removed from the user guide. I would be grateful if you could clarify a few concerns for me.

Does FragPipe support resuming operations from the point of interruption when executed in the command-line interface? If feasible, could you please outline the procedure to achieve this?

Are there any additional resources or tutorials available that focus on the command-line interface operations for FragPipe?

I appreciate your assistance and look forward to your response.

Warm regards,

LiangXiao

**Comment by fcyu** [comment]
We have the tutorial about running FragPipe in command line here https://fragpipe.nesvilab.org/docs/tutorial_headless.html

> Does FragPipe support resuming operations from the point of interruption when executed in the command-line interface? If feasible, could you please outline the procedure to achieve this?

Yes, it is the same as running in the GUI mode: disable certain tools/steps by unchecking (GUI) or setting to `FALSE` in workflow file (command line). 

As a beginner, it'd better to use GUI to export the workflow file to make sure that the parameters are configured correctly.

Best,

Fengchao

**Comment by liangxiao023** [comment]
I really appreciate your quick and helpful response! I'm setting up parameters in FragPipe's GUI and planning to save them as a workflow for later command-line use.

Could you please clarify something about interrupted runs? If a process, like MSFragger, is stopped halfway, does FragPipe create any interim files? If so, would these intermediate files allow me to pick up from the MSFragger step when I restart the analysis, rather than beginning anew?

Thanks in advance for your guidance!

Best,

Liangxiao

**Comment by liangxiao023** [comment]
> We have the tutorial about running FragPipe in command line here https://fragpipe.nesvilab.org/docs/tutorial_headless.html
> 
> > Does FragPipe support resuming operations from the point of interruption when executed in the command-line interface? If feasible, could you please outline the procedure to achieve this?
> 
> Yes, it is the same as running in the GUI mode: disable certain tools/steps by unchecking (GUI) or setting to in workflow file (command line).`FALSE`
> 
> As a beginner, it'd better to use GUI to export the workflow file to make sure that the parameters are configured correctly.
> 
> Best,
> 
> Fengchao

I really appreciate your quick and helpful response! I'm setting up parameters in FragPipe's GUI and planning to save them as a workflow for later command-line use.

Could you please clarify something about interrupted runs? If a process, like MSFragger, is stopped halfway, does FragPipe create any interim files? If so, would these intermediate files allow me to pick up from the MSFragger step when I restart the analysis, rather than beginning anew?

Thanks in advance for your guidance!

Best,

Liangxiao

**Comment by fcyu** [comment]
> Could you please clarify something about interrupted runs? If a process, like MSFragger, is stopped halfway, does FragPipe create any interim files? If so, would these intermediate files allow me to pick up from the MSFragger step when I restart the analysis, rather than beginning anew?

If it stops before finishing without any error, you have to rerun it. If it has finished, you can skip it in the future.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> > Could you please clarify something about interrupted runs? If a process, like MSFragger, is stopped halfway, does FragPipe create any interim files? If so, would these intermediate files allow me to pick up from the MSFragger step when I restart the analysis, rather than beginning anew?
> 
> If it stops before finishing without any error, you have to rerun it. If it has finished, you can skip it in the future.
> 
> Best,
> 
> Fengchao


Thank you for your assistance. I've encountered an issue with FragPipe when running it from the command line where it seems the logs aren't being printed and the program isn't producing any results. I'm eager to review the logs to identify any errors.

I suspect that I need to download a logging provider, such as `logback-classic.jar` or `slf4j-simple.jar`, and add it to FragPipe's classpath. However, I'm not quite sure where FragPipe's classpath is located or how to properly configure it with the necessary logging provider.

Could you please guide me on how to find FragPipe's classpath and the correct way to include a logging provider in it? Your help would be immensely appreciated as it would allow me to troubleshoot this issue and proceed with my analysis.

log:
[u43170@cpu6 test]$ fragpipe --headless --workflow ~/lx/test/test_workflow.workflow --config-python ~/lx/software/Python-3.9.5/python --config-msfragger ~/lx/software/MSFragger-4.0/MSFragger-4.0.jar --config-philosopher ~/lx/software/Philosopher/philosopher --config-ionquant ~/lx/software/IonQuant/IonQuant-1.10.12/IonQuant-1.10.12.jar --workdir ~/lx/test/test_res --manifest ~/lx/test/test_manifest.fp-manifest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Best,

Liangxiao

**Comment by fcyu** [comment]
Which directory is `fragpipe` in? By default, it should be in something like `fragpipe/bin` but yours is `test`.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> Which directory is in? By default, it should be in something like but yours is .`fragpipe``fragpipe/bin``test`
> 
> Best,
> 
> Fengchao

Hello, previously I set up fragpipe with environment variables and ran the fragpipe command from the path `~/lx/test`. Now I have navigated to the `~/lx/software/fragpipe/bin` directory and executed the command again, but it still seems unable to output logs. I have installed Java 11 and set it as an environment variable. 

(citru) [u43170@cpu6 bin]$ fragpipe --headless --workflow ~/lx/test/test_workflow.workflow --config-python ~/lx/software/Python-3.9.5/python --config-msfragger ~/lx/software/MSFragger-4.0/MSFragger-4.0.jar --config-philosopher ~/lx/software/Philosopher/philosopher --config-ionquant ~/lx/software/IonQuant/IonQuant-1.10.12/IonQuant-1.10.12.jar --workdir ~/lx/software/fragpipe/bin/test --manifest ~/lx/test/test_manifest.fp-manifest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
^C(citru) [u43170@cpu6 bin]$ ls
fragpipe  fragpipe.bat  fragpipe.exe  nohup.out  test
(citru) [u43170@cpu6 bin]$ pwd
/home/u43170/lx/software/fragpipe/bin
(citru) [u43170@cpu6 bin]$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by liangxiao023** [comment]
> Which directory is in? By default, it should be in something like but yours is .`fragpipe``fragpipe/bin``test`
> 
> Best,
> 
> Fengchao

Hello, previously I set up fragpipe with environment variables and ran the fragpipe command from the path ~/lx/test. Now I have navigated to the ~/lx/software/fragpipe/bin directory and executed the command again, but it still seems unable to output logs. I have installed Java 11 and set it as an environment variable.

I'm really puzzled by this. Could you please take a look and see what's going on? Thank you very much.

log:
(citru) [u43170@cpu6 bin]$ fragpipe --headless --workflow ~/lx/test/test_workflow.workflow --config-python ~/lx/software/Python-3.9.5/python --config-msfragger ~/lx/software/MSFragger-4.0/MSFragger-4.0.jar --config-philosopher ~/lx/software/Philosopher/philosopher --config-ionquant ~/lx/software/IonQuant/IonQuant-1.10.12/IonQuant-1.10.12.jar --workdir ~/lx/software/fragpipe/bin/test --manifest ~/lx/test/test_manifest.fp-manifest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
^C(citru) [u43170@cpu6 bin]$ ls
fragpipe fragpipe.bat fragpipe.exe nohup.out test
(citru) [u43170@cpu6 bin]$ pwd
/home/u43170/lx/software/fragpipe/bin
(citru) [u43170@cpu6 bin]$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

Best,

Liangxiao

**Comment by fcyu** [comment]
Hi Liangxiao,

I suspect some files in `/home/u43170/lx/software/fragpipe` were corrupted. Could you download a new FragPipe zip file, unzip it to a new directory, and try again?

Thanks,

Fengchao

**Comment by liangxiao023** [comment]
> Hi Liangxiao,
> 
> I suspect some files in `/home/u43170/lx/software/fragpipe` were corrupted. Could you download a new FragPipe zip file, unzip it to a new directory, and try again?
> 
> Thanks,
> 
> Fengchao

I would like to express my sincere gratitude for your prompt and helpful response. Following your guidance, I have successfully reinstalled FragPipe on a new Linux system, and it is now functioning as expected.

Additionally, I have a further question regarding the process parameter settings. Specifically, I am interested in how to specify a particular type of post-translational modification (PTM) during the MSFragger search that is not included in the provided PTM list, such as citrullination. I have reviewed the MSFragger parameter manual, but I am still unclear on how to incorporate such a parameter within FragPipe. At present, I have configured it as follows:

![PTM_issue](https://github.com/Nesvilab/FragPipe/assets/74865902/97bbe3ed-043d-4a23-8578-c16967ce42ef)

Could you kindly review this setup and advise if it is correct? Your expertise in this matter would be greatly appreciated.

Thank you once again for your time and assistance. I look forward to your reply.

Best, 
Liangxiao

**Comment by fcyu** [comment]
If you wanted to put 0.984 Da variable modification on R, then, you did it correct.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> If you wanted to put 0.984 Da variable modification on R, then, you did it correctly.
> 
> Best,
> 
> Fengchao

I am truly grateful for your prompt and helpful response! I have successfully executed FragPipe and identified peptides with specific PTMs. However, I seem to be missing the desired output file, `combined_peptide.csv`. Should I reconfigure the pipeline? I'm finding it a bit challenging to correlate each step with the specific software functions, such as Validation, Quant(MS1), and Quant(Isobaric). Could you kindly point me in the right direction to find the answers I seek? Your continued assistance would be immensely appreciated. If it's not too much trouble, a link to the relevant information would also be fantastic. Thank you so much for your time and support.


Best,

Liangxiao

**Comment by fcyu** [comment]
> However, I seem to be missing the desired output file, combined_peptide.csv

You need to specify the experiment and/or bioreplicates in the config tab to get the combined table.

> I'm finding it a bit challenging to correlate each step with the specific software functions, such as Validation, Quant(MS1), and Quant(Isobaric). Could you kindly point me in the right direction to find the answers I seek? Your continued assistance would be immensely appreciated. If it's not too much trouble, a link to the relevant information would also be fantastic. Thank you so much for your time and support.

You probably can start by reading our tutorial https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html

Best,

Fengchao

**Comment by liangxiao023** [comment]
> > However, I seem to be missing the desired output file, combined_peptide.csv
> 
> You need to specify the experiment and/or bioreplicates in the config tab to get the combined table.
> 
> > I'm finding it a bit challenging to correlate each step with the specific software functions, such as Validation, Quant(MS1), and Quant(Isobaric). Could you kindly point me in the right direction to find the answers I seek? Your continued assistance would be immensely appreciated. If it's not too much trouble, a link to the relevant information would also be fantastic. Thank you so much for your time and support.
> 
> You probably can start by reading our tutorial https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html
> 
> Best,
> 
> Fengchao

Thank you very much for your patience!

Best,

Liangxiao
