### ISSUE TITLE
peptide.tsv and psm.tsv tables with zero intensities in all identifications

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/FragPipe#1493]
Dear FragPipe team,

We are running a search on a set of DDA .d (Bruker) files that we previously transformed to mzML following your tutorial. I did this because FragPipe was not managing to load the .d file properly (see log1
[log_1](https://github.com/Nesvilab/FragPipe/files/14639623/log_2024-03-18_15-35-37.txt)

We are activating the MS1 quant option using FreeQuant, but in every peptide identification we have Intensity = 0. 

![image](https://github.com/Nesvilab/FragPipe/assets/33185213/cb35445b-aeae-43cc-acfe-3b2e4594b2db)

What could be the reason for this? Does it receive a 0 because of low intensity thresholding?

I am attaching the log fine here and I would like to share the raw files and the search results in a private message in case it is useful [log_2_search_w_zero_intensities](https://github.com/Nesvilab/FragPipe/files/14639586/log_2024-03-18_15-53-02.txt)

Thanks in general for maintaining and developing FragPipe; and thanks in advance for the help on this issue.

Best wishes,
Miguel

**Comment by fcyu** [comment]
I am not sure if FreeQuant works for the mzML file converted from .d.

Is the .d from ddaPASEF?

Best,

Fengchao

**Comment by LarissaMe** [comment]
Hi, 
thanks a lot for your answer!
So those are not ddaPASEF data and we did the freeQuant on mzml files because the ionquant gave us zero intensities. I am attaching the following log files: 

1. IonQuant with .d file [log_2024-03-21_13-53-44.txt](https://github.com/Nesvilab/FragPipe/files/14695689/log_2024-03-21_13-53-44.txt)
2. FreeQuant with .d file [log_2024-03-21_13-53-16.txt](https://github.com/Nesvilab/FragPipe/files/14695683/log_2024-03-21_13-53-16.txt)
3. IonQuant with mzml file 
[log_2024-03-21_14-08-46.txt](https://github.com/Nesvilab/FragPipe/files/14695700/log_2024-03-21_14-08-46.txt)
4. FreeQuant with mzml file [log_2024-03-21_14-09-57.txt](https://github.com/Nesvilab/FragPipe/files/14695696/log_2024-03-21_14-09-57.txt)

Thanks in advance

Kind regards

Larissa

**Comment by fcyu** [comment]
Hi Larissa,

If it is not the PASEF data from Bruker, you need to use the mzML format. 

Regarding the error when using IonQuant, it is actually throw by MSFragger before running IonQuant due to your file system issue

```shell
There was an error in delete file R:\meyerl\P10_PDAC_Maren\LC-MSMS\IMP160125_15068_13_RB5_01_138.200789104.0.fragtmp
R:\meyerl\P10_PDAC_Maren\LC-MSMS\IMP160125_15068_13_RB5_01_138.200789104.0.fragtmp
|There was an error in delete file R:\meyerl\P10_PDAC_Maren\LC-138.200789104.0.fragtmp
R:\meyerl\P10_PDAC_Maren\LC-MSMS\IMP160125_15068_13_RB5_01_138.200789104.0.fragtmp
...
Could not load file R:\meyerl\P10_PDAC_Maren\LC-MSMS\IMP160125_15068_13_RB5_01_138.mzBIN_calibrated. The file may be corrupted.
java.io.FileNotFoundException: R:\meyerl\P10_PDAC_Maren\LC-MSMS\IMP160125_15068_13_RB5_01_138.mzBIN_calibrated (The system cannot find the file specified)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBINStructure(MZBINFile.java:478)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.readMZBIN(MZBINFile.java:427)
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.<init>(MZBINFile.java:79)
	at edu.umich.andykong.msfragger.MSRun.readAsMzBIN(MSRun.java:266)
	at edu.umich.andykong.msfragger.MSRun.loadScans(MSRun.java:113)
	at edu.umich.andykong.msfragger.MSFraggerCore.<init>(MSFraggerCore.java:93)
	at edu.umich.andykong.msfragger.MSFragger.main1(MSFragger.java:695)
	at edu.umich.andykong.msfragger.MSFragger.main0(MSFragger.java:207)
	at edu.umich.andykong.msfragger.MSFragger.main(MSFragger.java:75)
Process 'MSFragger' finished, exit code: 1
```

Best,

Fengchao

**Comment by MiguelCos** [comment]
Dear Fengchao,

thank you very much for taking a look at the log files and for the answers.

What do you think could be the reason of 0 intensities in all identified features in the data in this context?

Let us know if you need more information.

Thanks again and best wishes,
Miguel

**Comment by fcyu** [comment]
> What do you think could be the reason of 0 intensities in all identified features in the data in this context?

I don't know because I barely used FreeQuant. Please use IonQuant.

Best,

Fengchao
