### ISSUE TITLE
questions on open search and 'MSFragger Localization' column

### ISSUE THREAD

**Issue by winnieWei123456** [Nesvilab/FragPipe#1495]
Dear developer, hello!
I have performed an open search with default settings of Frapipe using data in mzML form.
In the psm.tsv, I have some question regarding to the entry of 'Assigned Modifications', 'Observed Modifications' and 'MSFragger Localization'.
I know that Assigned modifications are those that were specified as variable modifications in MSFragger search. Observed modifications are what open search finds and the MSFragger Localization indicates where the modification found by open search is located. What is going on when the MSFragger Localization column is not empty but the content in the other two columns, Assigned Modifications, Observed Modifications is empty? If this represents a potential modification on the peptide, why is there no relevant information provided in the Observed modifications column?
[psm.csv](https://github.com/Nesvilab/FragPipe/files/14651328/psm.csv)

I have attached a partial data of psm.tsv, and the situation I described is similar to the 3rd, 10th, and 11th rows.

Additionally, I would like to ask, if my MS2 data is of low precision and I want to perform an open search, but it keeps giving me an error. I have attached a screenshot of the error message. How should I adjust the parameters?

![error](https://github.com/Nesvilab/FragPipe/assets/111028404/6732e5ab-7bf6-4efe-9201-7dbf7d753acb)

The version of my Fragpipe is 20

**Comment by fcyu** [comment]
>  What is going on when the MSFragger Localization column is not empty but the content in the other two columns, Assigned Modifications, Observed Modifications is empty? If this represents a potential modification on the peptide, why is there no relevant information provided in the Observed modifications column?

The file was from PTM-Shepherd edited psm.tsv. @danielgeiszler or @dpolasky could you take a look?

> Additionally, I would like to ask, if my MS2 data is of low precision and I want to perform an open search, but it keeps giving me an error. I have attached a screenshot of the error message. How should I adjust the parameters?

The log shows that the PeptideProphet modeling failed so that there are no IDs reported.

Best,

Fengchao

**Comment by dpolasky** [comment]
@winnieWei123456 Can you share the log file from the run that generated that psm table?

**Comment by winnieWei123456** [comment]
Sure. Here it is.
[log_2024-03-18_14-12-44.txt](https://github.com/Nesvilab/FragPipe/files/14652571/log_2024-03-18_14-12-44.txt)

**Comment by dpolasky** [comment]
Thanks. It looks like this psm.csv file is not the original psm.tsv table (it only has 20 PSMs but the log says it should have 852), and the PTM-Shepherd annotations look very strange. If the problem is present in the original psm.tsv as well, could you try running the search without PTM-Shepherd to see if the same issue is present in the table from MSFragger? 
Thanks,
Dan

**Comment by winnieWei123456** [comment]
I apologize for any inconvenience caused. I only extracted a portion of the psm.tsv file for your convenience. The original file also had the same problem. 
Furthermore, I followed your instructions and disabled PTM Shepherd, then reran the process. I have attached the new psm.tsv file for you. Is the output correct this time? My intention is to identify some modifications that I'm not familiar with. If I disable PTM Shepherd in the parameter settings of open search, how can I determine potential modifications? Since in this case the Observed Modification column will be empty.
[psm.csv](https://github.com/Nesvilab/FragPipe/files/14661548/psm.csv)
 
[Uploading log_2024-03-20_10-12-09.txt…]()

**Comment by dpolasky** [comment]
Thanks, that is very helpful. Disabling PTM-Shepherd was just to help us trace the cause of the issue, you can continue to use it for your actual searches. Based on that file, it looks like the problem is actually coming from MSFragger, since it persists after disabling PTM-Shepherd. For some reason MSFragger is localizing near-zero delta masses that should be within the exclusion range. There are some changes in the latest version that may have fixed this - would you mind testing with MSFragger 4.0 (it requires updating FragPipe to 21.1 and Philosopher to 5.1.0 as well)? 

Best,
Dan

**Comment by winnieWei123456** [comment]
Thank you for your assistance. I plan to conduct a mass offset search first before upgrading the software to run an open search and see the results. I will keep you informed of the progress. Additionally, I encountered a peculiar situation while running the mass offset search. I have multiple .mzML files, and when I run the mass offset search with all of them together, it throws an error. However, when I run it with each file individually, there are no issues. I have attached the log file containing the error message. Could you please take a look and help me identify the problem?
[log_2024-03-22_16-41-21.txt](https://github.com/Nesvilab/FragPipe/files/14720933/log_2024-03-22_16-41-21.txt)

**Comment by dpolasky** [comment]
PeptideProphet could not distinguish the targets from decoys, so the search stopped. We don't recommend doing nonspecific or open searches with low-resolution MS2 data - there is usually not enough information to confidently assign peptides. Whether or not the modeling fails completely or only gives a few results in any given run is a bit random. 

Best,
Dan
