### ISSUE TITLE
Non-Specific Peptidome

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1497]
Greetings,

I would like to thank you for this amasing tool!

Currently, I am in the process of analysing depleted serum proteomics data using non-specific peptidome workflow with IonQuant [MBR]. Based on the workflow, the protein level FDR is set to 1.

Based on the above, for downstream analysis is it appropriate for me to use the output MSstat file to generate protein level abundance matrix for downstream analysis?

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

If you want to study at the protein level but not the peptide level for the peptidome data, I guess you probably need to change the protein-level FDR to 0.01.

I will let Alexey to comment if there is anything to add.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Thank you for your prompt response. Currently I have about 2000 proteins in my combined protein file using the default non-specific peptidome search. The data is impressive. I will take your advise and add protein --0.01. Hopefully, I don't lose much protein.

Regards,
Ben

**Comment by anesvi** [comment]
That's right, you have to change prof to --prot 0.01. Perhaps we should do change that in our built-in peptidome workflows in the future.
