### ISSUE TITLE
Fragpipe error

### ISSUE THREAD

**Issue by jjjjjj17** [Nesvilab/FragPipe#1498]
- Describe the issue or question:
Why is my fragpipe failed? I can't solve it.

[log_2024-03-21_19-22-04.txt](https://github.com/Nesvilab/FragPipe/files/14720085/log_2024-03-21_19-22-04.txt)

**Comment by fcyu** [comment]
It is a known bug: https://github.com/Nesvilab/FragPipe/issues/1387. Please send an email to yufe AT umich.edu to get the fixed version.

Thanks,

Fengchao
