### ISSUE TITLE
Fragpipe grouping FDR setup parameters and parallel computation

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1499]
Dear Fragpipe Developers,

I hope this message finds you well. I would like to express my sincere gratitude for the outstanding tool you have provided, along with the comprehensive documentation. Following the guidance in the documentation, I have successfully run Fragpipe on two raw files, each approximately 1GB in size, which took around 40 minutes. This was a smooth experience, and I appreciate the effort you've put into making this tool accessible.

I am reaching out to inquire about the parameter settings for group FDR based on modifications. While I have reviewed the relevant documentation, I've noticed that it primarily offers textual explanations without concrete examples. This leaves me somewhat uncertain about how to configure the parameters for my specific needs.

![FDR_issue](https://github.com/Nesvilab/FragPipe/assets/74865902/9fb06ebe-32ce-407a-bbbd-9f883b640acb)

Additionally, I am curious about the feasibility of running Fragpipe on 300 mass spectrometry data files, each about 1GB, while searching for specific modifications. I am concerned about the possibility of encountering memory insufficiency during the process. Is there a mechanism within Fragpipe to automatically run these files in batches and then consolidate the results? If not, does Fragpipe support parallel computation to handle such a large dataset?

I am looking forward to your valuable insights and guidance on these matters. Thank you very much for your time and assistance.

Warm regards,

Liangxiao

**Comment by fcyu** [comment]
> I am reaching out to inquire about the parameter settings for group FDR based on modifications. While I have reviewed the relevant documentation, I've noticed that it primarily offers textual explanations without concrete examples. This leaves me somewhat uncertain about how to configure the parameters for my specific needs.

There is actually a screenshot with an example between two paragraphs that you pasted. I guess your browser didn't load the image.

<img width="846" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/685b59d4-4c06-4c68-9bc6-15bced4cc781">


> Additionally, I am curious about the feasibility of running Fragpipe on 300 mass spectrometry data files, each about 1GB, while searching for specific modifications. I am concerned about the possibility of encountering memory insufficiency during the process.

Analyzing 300 files is not a big deal to FragPipe. A mainstream desktop could finish the job in one day for most cases as long as you have enough memory.

> Is there a mechanism within Fragpipe to automatically run these files in batches and then consolidate the results? If not, does Fragpipe support parallel computation to handle such a large dataset?

Unfortunately, no.

Best,

Fengchao
