### ISSUE TITLE
Error parsing file/PhilosopherFilter error

### ISSUE THREAD

**Issue by dtabang** [Nesvilab/FragPipe#1500]
- Describe the issue or question:

I am trying to search DDA IM-MS files for library generation using a human FASTA concatenated with some bacterial proteins, but my search encounters an error when it is parsing the pep.xml files. I am using FragPipe 21.1 and Philospher 5.1.0. Could I get some insight into this error? Thanks!

- Upload your log file
[log_2024-03-23_16-58-09.zip](https://github.com/Nesvilab/FragPipe/files/14733613/log_2024-03-23_16-58-09.zip)

**Comment by fcyu** [comment]
Your fasta file is not well formatted, some protein headers don't start with '>', and some proteins don't have sequences. Please fix it and rerun again.

Best,

Fengchao

**Comment by dtabang** [comment]
Is there an easy way to combine fasta files to avoid any formatting errors? There is no reference proteome for the bacteria's proteins I want to combine the human fasta so I could not do it through Fragpipe.

**Comment by fcyu** [comment]
You have to edit and combine the fasta files using a text editor.

Best,

Fengchao

**Comment by dtabang** [comment]
Got it to work this time using a different text editor. Thanks.
