### ISSUE TITLE
There is no protein grouping in the protein.tsv file and the INTENSITY is 0

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1501]
- Describe the issue or question:
I checked the documentation for instructions and there should be Group and SubGroup in the protein.tsv file. why is it that the protein.tsv result file after my run does not have these two columns in it and the intensity is both 0. Here is my log file.

In addition to that, I see in fragpipe that when the dataset is too large, it will not be able to generate combined_peptide.tsv and combined_protein.tsv, but I really need these summary files, is there any way to save each protein.tsv and peptide.tsv, and 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-03-23_16-57-12.txt](https://github.com/Nesvilab/FragPipe/files/14735531/log_2024-03-23_16-57-12.txt)

**Comment by fcyu** [comment]
> I checked the documentation for instructions and there should be Group and SubGroup in the protein.tsv file.

These two columns have been deprecated since they are not informatiive.

Your log file if not available to download, could you upload it again?

Thanks,

Fengchao

**Comment by liangxiao023** [comment]
Okay, thank you, but the column where intensity indicates protein abundance is still 0. Here's the log I just ran
[log_2024-03-24_21-46-51.txt](https://github.com/Nesvilab/FragPipe/files/14735649/log_2024-03-24_21-46-51.txt)


> > I checked the documentation for instructions and there should be Group and SubGroup in the protein.tsv file.
> 
> These two columns have been deprecated since they are not informatiive.
> 
> Your log file if not available to download, could you upload it again?
> 
> Thanks,
> 
> Fengchao

**Comment by fcyu** [comment]
You did not enable "Quant (MS1)` to get extract the MS1 intensity values.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> You did not enable "Quant (MS1)` to get extract the MS1 intensity values.
> 
> Best,
> 
> Fengchao

Thank you very much, I just solved the problem.
