### ISSUE TITLE
FragPipe and UNIMOD short questions

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1503]
Hello, two short questions: 

* Whenever FragPipe reports found modifications for an open search, does it compares with all UNIMOD (1500 entries) or a tailored subgroup?.
* Related to the previous question, as a users could we customize the the list of modifications that we want to report for an open search? 

Thanks!

**Comment by danielgeiszler** [comment]
It will map to almost the entire
Unimod. Several modifications have been removed that consistently messed with automatic annotation (some chemical labels, etc.).

If you want to only map to a portion of Unimod, you can pass your modification subgroup to PTM-Shepherd. Just provide the path under PTMs > PTM Profiling > Annotation > Custom Annotation File and select the Custom Annotation File button.

The XRNAX-MassOffset feature uses this feature if you need an example of how to set up the PTM-Shepherd parameters. You
can also find an example custom PTM annotation file can be found at fragpipe/0019/unimod_20191002_RNAadducts.txt .

I should also point out that if you are only interested in identifying specific modifications, an offset search is generally more suitable than a fully open search (e.g., Mass-Offset-CommonPTMs).

**Comment by rolivella** [comment]
Hi again @danielgeiszler , I'm using the command line version of FragPipe. Do you know how can I perform an offset search? Thank you.

**Comment by danielgeiszler** [comment]
We recommend configuring the workflow in the GUI, saving the workflow, then running it via the CLI.

https://fragpipe.nesvilab.org/docs/tutorial_headless.html
