### ISSUE TITLE
Continue running after unexpected interruption

### ISSUE THREAD

**Issue by cindysimm** [Nesvilab/FragPipe#1505]
- Describe the issue or question:
Hi, the fragpipe suddenly closed due to the network problem. Can the fragpipe continue to run based on the previous results? Just like the 'Partial processing' in maxquant.
Thanks!

**Comment by danielgeiszler** [comment]
It will start from the beginning unless you disable the steps that have already completed. If you disable the steps that have already completed, it should run from that point without issues.

**Comment by fcyu** [comment]
Same question as https://github.com/Nesvilab/FragPipe/issues/268 and https://github.com/Nesvilab/FragPipe/issues/631

Best,

Fengchao
