### ISSUE TITLE
>1000 .raw files to be searched

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1506]
Greetings,

Currently I am searching patient derived data as batches of 100. The patients are progressively required to the study. I am planning to perform LFQ-MBR. Everytime a new batch of 100 samples comes, I have to re-search all the older files together with the newer once.

By any chance is there an easier way to do this? Maybe I can combine the independent searches?

Regards
Ben

**Comment by fcyu** [comment]
Hi Ben,

Yes, you could perform the MSFragger, MSBooster, and Percolator analysis for these batches separately. And then, after getting the output files of all batches, move them to the same "result folder", load all raw/mzML files in FragPipe, assign the experiment group, and perform ProteinProphet, FDR filtering and reporting, and Quant (MS1) by unchecking MSFragger, MSBooster, and Percolator. When you move the output files, need to make it look like from a single MSFragger, MSBooster, and Percolator analysis.

BTW, to make the process robust and fast, it would be better to convert the raw files to mzML format beforehand: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao
