### ISSUE TITLE
question on validation of DDA+ peptideprophpet 

### ISSUE THREAD

**Issue by assafkacen1** [Nesvilab/FragPipe#1507]
Hi,

I wonder if you can elaborate more on how peptideprophet calculates its validation score with multiple ranks in dda+ analysis. Is it done per rank separately? How is it translate to the FDR calculation in the filter step?

thanks

Assaf

**Comment by fcyu** [comment]
Yes, the probability is calculated per rank separately but the FDR is calculated with all ranks together. But, we recommend using Percolator.

Best,

Fengchao

**Comment by fcyu** [comment]
This is a little non-trivial. Basically, the current database split and search result merging code does not work very well with > 1 ranks. We need to overhaul it to fix it.

Best,

Fengchao

**Comment by assafkacen1** [comment]
I am running the same DDA file as DDA (LFQ-MBR) default setting and as DDA+ default setting. I do get an enrichment of 6% more psm identified but in quantification values (Ionquant ms1) I drop from 46% psm with intensity values (non zero) to 10% with intensity values (non zero). how can I keep or increase my quantified PSMs?
thanks
Assaf

**Comment by fcyu** [comment]
> I drop from 46% psm with intensity values (non zero) to 10% with intensity values (non zero). how can I keep or increase my quantified PSMs?

It doesn't look right. Could you share some of our mzML/raw and fasta files? Here is the link to upload the files https://www.dropbox.com/request/aJ6TwaccLOuMHIiNL1bw

Thanks,

Fengchao

**Comment by assafkacen1** [comment]
I uploaded the raw file, fasta file and two logs: DDA , DDA+ 
Assaf

**Comment by fcyu** [comment]
Hi Assaf,

Thanks you so much for sharing the files. 

It tunes out that there are big mass errors in the data. In the DDA+ mode, after MSFragger calibrated them, it didn't write such calibration info to the report so that IonQuant didn't know, which resulted in detecting wrong XIC features with ~10 ppm mass shift.

We have fixed it. If you want to try the pre-released version, could you send an email to yufe AT umich.edu?

```shell
*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |  11.53   1.32 |   0.13   0.61 |  11.05   3.18 |   0.58   3.25  
-----|---------------|---------------|---------------|---------------
```

Thanks,

Fengchao

**Comment by assafkacen1** [comment]
Thanks
