### ISSUE TITLE
About Fragpipe DIANN output

### ISSUE THREAD

**Issue by Andy021403** [Nesvilab/FragPipe#1508]
Hi, fcyu
I run a DIA_SpecLib_Quant_phospho analyis with Fragpipe and quantify with DIA-NN these days. The resulted output seem there are no modified_peptides file. All result is following.
![D_20240330173233](https://github.com/Nesvilab/FragPipe/assets/148791455/5dc6a484-558a-4dff-8dd9-ff4206e053df)
Moreover, many modified peptides have more than one phospho-modification site. But the output file don't show more specific assigned information about different phospho- site respectively to the same modifid peptide, for example the following attached screenshot.
![%7BA7B74713-EE1C-4361](https://github.com/Nesvilab/FragPipe/assets/148791455/2a97584d-17b7-45b2-8aa4-80a91dc8521b)
How to tranform the one modified-site one row?
Best,
Thanks.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
> The resulted output seem there are no modified_peptides file. 

Because DIA-NN does not generate such file.


> How to tranform the one modified-site one row?

We might add a module in FragPipe to generate site reports in the future. 

Best,

Fengchao

**Comment by Nicolevswy** [comment]
Please help me how to use this workflow, is there any user manuals, I can't find it. And this DIA_SpecLib_Quant_phospho workflow is for generating phospho library or just for quanting? Thanks.

**Comment by fcyu** [comment]
Here are the list of tutorials: https://fragpipe.nesvilab.org/
Here is the DIA tutorial: https://fragpipe.nesvilab.org/docs/tutorial_DIA.html

> this DIA_SpecLib_Quant_phospho workflow is for generating phospho library or just for quanting? 

For both.

After you load the workflow by clicking "**load**", DO NOT change any parameters unless necessary.

Best,

Fengchao
