### ISSUE TITLE
running fragpipe headless with shepherd.conf

### ISSUE THREAD

**Issue by akyocum-UMICH** [Nesvilab/FragPipe#1509]
Hi,

I want to run a custom glyco modification database using PTM shepherd.  I have the shepherd.conf file, but I don't understand how to call it from funning Fragpipe in headless mode (CLI) on linux machine.  

I see other ways to run other algorithms; but not PTM Shepherd.  Is it possible? Or do I need to run PTM shepherd outside of fragpipe, and in that case; the instructions read.  

Datasets are passed to PTM-Shepherd in the form of [Philosopher](https://philosopher.nesvilab.org/) psm.tsv files. Will each .mzML file have it's own psm.tsv file?

Thanks,

**Comment by fcyu** [comment]
You don't need to worry about the shepherd.conf because FragPipe will generate one for you. Just make sure that the workflow file is configured correctly and run the headless mode following https://fragpipe.nesvilab.org/docs/tutorial_headless.html

Best,

Fengchao

**Comment by akyocum-UMICH** [comment]
Thanks!

**Comment by fcyu** [comment]
No prob.
