### ISSUE TITLE
singly charged spectra

### ISSUE THREAD

**Issue by May2020** [Nesvilab/FragPipe#151]
Dear FragPipe developing team,

Just wondering whether FragPipe 12.0 can search MS2 spectra from singly charged precursor ions. 
If it can, what kind of setting I should use other than the default setting?

thanks a lot
May

**Comment by fcyu** [comment]
Hi May,

Thanks for your interest in FragPipe. Yes, it can. The default setting already support singly charged ions.

Best,

Fengchao

**Comment by May2020** [comment]
Great!

Thanks a lot for your instruction! Have a nice weekend!

**Comment by May2020** [comment]
The new version v12.0 and v12.1 really works better than before. I am working on nonspecific search and now got much less error message. I will keep working on it. Thanks a lot for your hard work!
