### ISSUE TITLE
MBR toggle either off or on produces the same results

### ISSUE THREAD

**Issue by akyocum-UMICH** [Nesvilab/FragPipe#1510]
In FragPipe (v21.1) Windows GUI, I'm using a custom glyco database for glyco-N-LFQ workflow.  I'm trying to compare the different outputs of using MBR or NOT in IonQuant, and then comparing various parameters within MBR.  However, the outputs are the exact same, but the workflow parameters are not:  

no MBR:

[fragpipe.workflow_noMBR.txt](https://github.com/Nesvilab/FragPipe/files/14812988/fragpipe.workflow_noMBR.txt)

MBR
[fragpipe.workflow_MBR.txt](https://github.com/Nesvilab/FragPipe/files/14812990/fragpipe.workflow_MBR.txt)

Am I doing something obviously incorrect.

**Comment by fcyu** [comment]
Can you share the log files?

Thanks,

Fengchao

**Comment by akyocum-UMICH** [comment]
thanks, 

with MBR:
[log_2024-02-23_20-38-31.txt](https://github.com/Nesvilab/FragPipe/files/14812997/log_2024-02-23_20-38-31.txt)

no MBR:
[log_2024-03-29_21-35-28.txt](https://github.com/Nesvilab/FragPipe/files/14813000/log_2024-03-29_21-35-28.txt)

**Comment by fcyu** [comment]
The log files look OK. Which result files were you looking at? You should see differences in the `combined_*.tsv` files. The `psm.tsv` won't be affected by MBR because the entries are from MS/MS matches.

Thanks,

Fengchao

**Comment by akyocum-UMICH** [comment]
Oh, that makes sense.  

Thanks!

**Comment by fcyu** [comment]
No prob. I will closed this issue but feel free to contact us if you have any questions in the future.

Best,

Fengchao

**Comment by akyocum-UMICH** [comment]
Hey, sorry, but I want to make sure

I want to look at each file independently, not the combined.  Can I use the individual file results F20230904_2539.tsv to get the MBR results?

Thanks,

**Comment by fcyu** [comment]
You have to use the combined files if you want to get the IDs from MBR.

Best,

Fengchao

**Comment by akyocum-UMICH** [comment]
I realize the issue is closed, but I want to make sure I can see the MBR results in the individual tsv file results.

Anastasia
________________________________

**Comment by akyocum-UMICH** [comment]
Yea, but I’m trying to identify spectra in each file that was MBR or real results.

Anastasia
________________________________

**Comment by fcyu** [comment]
There are columns in the combined file indicating if the ID is from `MS/MS` or `MBR`.

Best,

Fengchao

**Comment by akyocum-UMICH** [comment]
ok, I see that but using the combined, I can't tell which file / files that peptide was identified.  

Experimental design is 100+ files, case v control, and I want to know at the spectra level per sample if the findings was MBR.  Is that possible?

thanks again!

**Comment by fcyu** [comment]
I am not sure if I follow your question. Do you mean that you want to see the detection types and intensities of each sample/file? You just need to specify the experiments and/or bioreplicates for your files in the config tab. Here is the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#multi-experiment-report

Best,

Fengchao

**Comment by akyocum-UMICH** [comment]
Nah, I really just want an indication at the sample level whether a spectra was found or MBR.

Anastasia
________________________________

**Comment by akyocum-UMICH** [comment]
I could compare each individual file output.tsv between running MBR or not if the finding from MBR is written out at the individual file.

Anastasia
________________________________

**Comment by fcyu** [comment]
> Nah, I really just want an indication at the sample level whether a spectra was found or MBR.

First of all, there are no (MS2) spectra for MBR. I am not sure what level of IDs are you looking at, but at the PSM level, there is no MBR. At the ion, modified peptide, and peptide levels, there are columns in the `combined_*.tsv` to indicate if an ion is from `MS/MS` or `MBR`.

> I could compare each individual file output.tsv between running MBR or not if the finding from MBR is written out at the individual file.

It won't work.

Best,

Fengchao
