### ISSUE TITLE
PeptideProphetParser.exe: Access is denied.

### ISSUE THREAD

**Issue by akyocum-UMICH** [Nesvilab/FragPipe#1512]
Hi all,

Working with Fragpipe and got this error where it is exiting prior to finishing.  

The following error seems to be the start of it, but after running the pipeline twice, this error happens at different files during the PeptideProphet part. So I don't think it's a specific file.  Further, running this pipeline with the Experiment field empty, or with the same value, the pipeline works fine.  I really do want the individual file results without combining.  

panic: remove C:\Users\A2user\AppData\Local\Temp\266a6731-d104-467d-b41d-0a848371b368\PeptideProphetParser.exe: Access is denied.

Attached is the log file
[log_2024-03-30_23-17-57.txt](https://github.com/Nesvilab/FragPipe/files/14824235/log_2024-03-30_23-17-57.txt)
[log_2024-03-31_22-07-06.txt](https://github.com/Nesvilab/FragPipe/files/14824236/log_2024-03-31_22-07-06.txt)

Thanks,

**Comment by fcyu** [comment]
Did you run multiple FragPipe at the same time?

Does your computer has any antivirus or privilege manager software that prevent FragPipe access some files?

Thanks,

Fengchao

**Comment by akyocum-UMICH** [comment]
No to both of those quesitons. 

Thanks,

**Comment by fcyu** [comment]
Thanks for the updated info. Could you replace the existing Philosopher with this one https://www.dropbox.com/t/SosJlF2cTtrcj4S0 and see if the error goes away?

Thanks,

Fengchao

**Comment by akyocum-UMICH** [comment]
Hey that worked and also the combined_modified_peptide.tsv provides the exact information I was looking for.  

Appreciate it!

Thanks,

**Comment by fcyu** [comment]
Glad to know that it works now. I will close this issue but feel free to contact us if you have any questions in the future.

Best,

Fengchao

**Comment by JadeyMac** [comment]
Hi @fcyu. I am having the same problem. Could you re-enable that Dropbox link? 

Thanks,

**Comment by fcyu** [comment]
The latest FragPipe should have this one fixed.
