### ISSUE TITLE
Screening of PTM peptides

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1513]
- Describe the issue or question:

I'm having some problems analyzing the results. When I implement a library search process for HLA-binding peptides, there are a lot of post-translationally-modified peptides that come up in my search, but I'd like to streamline it a bit - which metrics should I use to help me with the sorting? Can I use INTENSITY to represent the abundance of peptides for sorting?

**Comment by anesvi** [comment]
You are doing a complicated analysis and this forum is for helping with technical questions.  You need to apply group FDR filtering to filter modified peptides separately to 1 percent FDR. There is literature and tutorial you can find, but you need to figure it out, we cannot answer all questions here.
