### ISSUE TITLE
diann cannot read file(libtorch_cpu.so)

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1517]
- Describe the issue or question:
Dear developer team,

My diann can't read the file(libtorch_cpu.so), but I found that the file still exists in the directory. Should I reinstall diann? Looking forward to your reply, I will appreciate your answer very much.

/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8: error while loading shared libraries: /home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so: cannot read file data

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

It's not convenient for me to upload files now. I posted the relevant log contents below, please check it.

Process 'MSFragger move pin' finished, exit code: 0
MSBooster [Work dir: /home/liangx/results/immunopep_res]
java -Xmx853G -cp /home/liangx/software/fragpipe/tools/msbooster-1.1.28.jar:/home/liangx/software/fragpipe/tools/batmass-io-1.30.0.jar Features.MainClass --paramsList /home/liangx/results/immunopep_res/msbooster_params.txt
MSBooster v1.1.28
Using 111 threads
2022224 unique peptides from 4636561 PSMs
createFull input file generation took 35309 milliseconds
Input file at  /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT_full.tsv
Generating input file for DIA-NN
2003270 unique peptides from 4636561 PSMs
Writing DIA-NN input file
Diann input file generation took 36378 milliseconds
Input file at  /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv
Generating DIA-NN predictions
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --lib /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv --predict --threads 111 --strip-unknown-mods --predict-n-frag 100
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8: error while loading shared libraries: /home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so: cannot read file data
Abnormal DIANN termination: 127, please run the following command from the command line for more information
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --lib /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv --predict --threads 111 --st- Describe the issue or question:
Dear developer team,

My diann can't read the file(libtorch_cpu.so), but I found that the file still exists in the directory. Should I reinstall diann? Looking forward to your reply, I will appreciate your answer very much.

/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8: error while loading shared libraries: /home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so: cannot read file data

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

It's not convenient for me to upload files now. I posted the relevant log contents below, please check it.

Process 'MSFragger move pin' finished, exit code: 0
MSBooster [Work dir: /home/liangx/results/immunopep_res]
java -Xmx853G -cp /home/liangx/software/fragpipe/tools/msbooster-1.1.28.jar:/home/liangx/software/fragpipe/tools/batmass-io-1.30.0.jar Features.MainClass --paramsList /home/liangx/results/immunopep_res/msbooster_params.txt
MSBooster v1.1.28
Using 111 threads
2022224 unique peptides from 4636561 PSMs
createFull input file generation took 35309 milliseconds
Input file at  /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT_full.tsv
Generating input file for DIA-NN
2003270 unique peptides from 4636561 PSMs
Writing DIA-NN input file
Diann input file generation took 36378 milliseconds
Input file at  /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv
Generating DIA-NN predictions
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --lib /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv --predict --threads 111 --strip-unknown-mods --predict-n-frag 100
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8: error while loading shared libraries: /home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so: cannot read file data
Abnormal DIANN termination: 127, please run the following command from the command line for more information
/home/liangx/software/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --lib /home/liangx/results/immunopep_res/PXD012308_HLA_II/spectraRT.tsv --predict --threads 111 --strip-unknown-mods --predict-n-frag 100
Process 'MSBooster' finished, exit code: 255
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 844 remaining tasksrip-unknown-mods --predict-n-frag 100
Process 'MSBooster' finished, exit code: 255
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 844 remaining tasks

**Comment by fcyu** [comment]
Something was wrong with our operating system or file system. I am afraid that we won't be able to do much about it because you need to contact your IT people to troubleshoot your computer.

Best,

Fengchao
