### ISSUE TITLE
Version string not found for DIA-NN 

### ISSUE THREAD

**Issue by yan1365** [Nesvilab/FragPipe#1518]
Hi,

Thank you for your wonderful tool. I was trying to run fragpipe with command line in a supercomputer cluster (GUI version indicates not enough memory for my PC). However, when I ran the command:
./fragpipe --headless --workflow xxx/workflow --manifest xxx/manifest.txt --workdir xxx/result_dirs --config-philosopher xxx/philosopher --config-ionquant xxx/IonQuant-1.10.12.jar --config-msfragger xxx/MSFragger-4.0/MSFragger-4.0.jar --config-python xxx/bin/python3.9 (the parent dir is masked).

ps. I loaded the java with module load java before running the command.

I had below error:
![image](https://github.com/Nesvilab/FragPipe/assets/77165748/4a44c760-98a5-4475-843c-7fc4a2c7c612)

Could you please tell me how could I resolve this? I searched the github but did not find similar issue.

Thanks,
Ming

**Comment by fcyu** [comment]
Hi Ming,

Could you check if `/users/PAS1855/yan1365/bin/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8` has the permission to execute? You could run `ls -al /users/PAS1855/yan1365/bin/fragpipe/tools/diann/1.8.2_beta_8/linux/` to find out.

Best,

Fengchao

**Comment by yan1365** [comment]
Hi Fengchao,

Thank you for your prompt response. I checked and I do have the permission to execute.

Thanks,
Ming


________________________________

**Comment by fcyu** [comment]
Hi Ming,

Thanks for the prompt update. Could you run `https://docs.google.com/presentation/d/1FGKEwkt6Zep02pCybydjRxWAa9ZbxqKHkVoT1d6CIvU/edit#slide=id.p` in the command line to see what it prints?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Ming,

Thanks for the prompt update. Could you run `/users/PAS1855/yan1365/bin/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8` in the command line to see what it prints?

Thanks,

Fengchao

**Comment by yan1365** [comment]
It shows: "/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /users/PAS1855/yan1365/bin/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8)"

Thanks,
Ming
________________________________

**Comment by fcyu** [comment]
Hi Ming,

That's the cause: `/lib64/libm.so.6: version `GLIBC_2.27' not found`. Your Linux system has old glibc that does not support DIA-NN.

Best,

Fengchao

**Comment by yan1365** [comment]
May I ask how I could resolve this. Can I install the dependencies with conda?

Thanks,
Ming
________________________________

**Comment by fcyu** [comment]
No, because glibc is system dependency. The only easy way is using docker https://hub.docker.com/r/fcyucn/fragpipe

Best,

Fengchao

**Comment by yan1365** [comment]
Ok, thank you for your help. I will try docker instead.

Best,
Ming
________________________________
