### ISSUE TITLE
Did not find any PeptideProphet results in input data!

### ISSUE THREAD

**Issue by JoshEbner** [Nesvilab/FragPipe#152]
Hello everyone,

After ProteinProphet starts I get the following warning: no data - output file will be empty (but see the log file). The remaining tasks are then stopped.

I was wondering what I did wrong there, the interact.pep.xml file is clearly in the output directory and not empty. What is going on?

Best regards,
Joshua

----------------------
[log_2019-11-20_17-48-23.txt](https://github.com/Nesvilab/FragPipe/files/3870336/log_2019-11-20_17-48-23.txt)

**Comment by fcyu** [comment]
Hi Joshua,

Thanks for your interest in FragPipe. Your log shows that there is not much PSMs in your data:
```
*********************************MASS CALIBRATION**********************************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------
  MS2  |    7  |   10  |   15  |   20  |   25  |   30  
-------|-------|-------|-------|-------|-------|-------
 Count |     17|     40|     24| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------
 Peaks | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------
 Count |     40|     40|     39| skip rest
-------|-------|-------|-------|-------|-------
```
Could you please double check if your parameters meet the properties of your data?

Best,

Fengchao

**Comment by JoshEbner** [comment]
Hi Fengchao,

Thank you for your reply. Yes, I noticed the low PSMs and was confused since a MaxQuant narrow search worked quite well.
I am a novice in Proteomics/FragPipe as I have a background in ecology. Could you recommend me the correct parameters for conducting an open search for the following type data?:
Orbitrap Fusion Lumos Tribrid MS (.raw file was converted to .mzML via MSConvert). A detailled information on how the data was obtained is here: https://onlinelibrary.wiley.com/doi/full/10.1111/mec.15225

Sorry if i am being naive here but I hope you can help me out.

Best regards,

Joshua

**Comment by anesvi** [comment]
I see you search against a custom database
database_name = C:\Users\Wotuli32\Desktop\FragPipe_Trial\2019-11-20-td-OgDB_plus_Rf_Clean_CdHit.fasta

did you format it properly?
Does your decoy start with rev_?

https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database

**Comment by fcyu** [comment]
Hi Joshua,

As what Alexey pointed out, your fasta file most likely to be the reason of the error. Could you please send your fasta file to us?

Thanks,

Fengchao

**Comment by prvst** [comment]
It seems to be the search parameters, not the database.

**Comment by JoshEbner** [comment]
Hi everyone,

Like Felipe, I also suspect that I have the wrong search parameters. I followed the database guidelines in the link you attached Alexey: "philosopher database --custom "file.fasta" --contam".

Here is a link to the database and the mzML file (hope this works): https://gofile.io/?c=q1UWWL

And here is a screenshot of the fasta file: 
![Screenshot](https://user-images.githubusercontent.com/58002390/69265094-e3b6e380-0bc8-11ea-85e5-e4d0db9409fd.png)

Thank you for all the input,
Josh

**Comment by fcyu** [comment]
Hi Josh,

Looks like your data is from low resolution MS2. There is a `<cvParam cvRef="MS" accession="MS:1000512" name="filter string" value="ITMS + c NSI r d Full ms2 382.18@cid35.00 [95.00-775.00]"/>` in your mzML indicates that the MS2 scan was from ion trap, while you set `fragment_mass_tolerance = 20.0`. I guess you need to change it to `fragment_mass_tolerance = 300` and have another try.

BTW, your database is not well formulated. You need to follow the instruction in [https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database)

Best,

Fengchao

**Comment by JoshEbner** [comment]
Hi Fengchao,

Ok, thanks! I will retry the run tomorrow with `fragment_mass_tolerance = 300` and re-formulate the database. I'll keep this post updated tomorrow if the "problem" got resolved.

Best,
Josh

**Comment by fcyu** [comment]
Hi Josh,

Sounds good. 

FYI, we do not recommend doing open search with low MS2 resolution data. 

Best,

Fengchao

**Comment by JoshEbner** [comment]
Hi Fengchao,

first of all thanks for all the help!
I know that open searching with low MS2 resolution data is not recommended but I will have high MS2 res data soon and wanted to test out the pipeline.

After reformatting the database and setting `fragment_mass_tolerance = 300` I got everything up and running. The only problem is that I run into a memory issue with FragPipe slowing down massively after ca. 50% of spectra have been searched and then giving me the `java.lang.outofmemoryerror java heap space` error message. I used the Split database feature but then the "Localize delta mass" open search option has to be turned off. What exactly is Localize delta mass doing and is it vital to keep it checked during an open search?

Best,
Josh

**Comment by fcyu** [comment]
Hi Josh,

`localize_delta_mass` tries to put delta mass to the residue(s) that result in the best match. Turning it off may reduce the sensitivity a little bit but won't hurt the whole result too much. If what you want was finding out what modifications your sample has, it would be totally fine without `localize_delta_mass`.

Best,

Fengchao

**Comment by TluckDucky** [comment]
Hello, dear FragPipe team.

Thanks for this software and sorry for reopening this issue, but I just started studying LC-MS/MS, proteomics and FragPipe. I'm not familiar with this field yet. 

I'm running the same problem described above. I'm using FragPipe to search for all possible PTMs in DDA data using Open Search, to perform a second run for specific PTMs found in the Open Search analysis. But I'm getting no peaks at all.

Apparently, my db is in the recommended format.

In the Google Drive link bellow you may find the publicly available mzML files obtained by Menezes et al., [https://www.sciencedirect.com/science/article/pii/S1874391920302153](url), the FASTA used containing decoys and contaminants (2026-03-20-decoys-contam-CLBrener_UP000002296_2026_03_17_redundancy_filtered.fasta), the original FASTA (TCC_UP000246078_2026_03_17_redundancy_filtered) as well as the log file of the run.

[https://drive.google.com/drive/folders/1ui7ZNF-94vyX0bjzLfiWskxfDm6kah_-?usp=sharing](url)

Could you please help me? Thank you!

**Comment by fcyu** [comment]
Can you share the log file?

Thanks,

Fengchao

**Comment by TluckDucky** [comment]
Hey, Fengchao,

I'm sorry, I sent a broken link, the right ones:

Folder with mzML and FASTA files: https://drive.google.com/drive/folders/1ui7ZNF-94vyX0bjzLfiWskxfDm6kah_-?usp=drive_link
Log file: https://drive.google.com/file/d/1USWN_x1OUHmhLvo0O_TXe_ajQZxu_GA1/view?usp=sharing

Thanks!

**Comment by fcyu** [comment]
You enabled PTMProphet, which doesn't work for open search. Can you load the built-in "Open" workflow and make minimal changes?

Thanks,

Fengchao

**Comment by TluckDucky** [comment]
> You enabled PTMProphet, which doesn't work for open search. Can you load the built-in "Open" workflow and make minimal changes?
> 
> Thanks,
> 
> Fengchao

I see, Fengchao, I will try that and let you know the outcome.

Thank you so much.

**Comment by TluckDucky** [comment]
Hello, @fcyu,

I disabled the PTMProphet and addded lysine propionylation as variable modification and N-term peptide propionylation as fixed modification. I didn't do any other change. I'm still getting the `did not find any PeptideProphet results in input data! Did you forget to run PeptideProphet?` message. I can't understand the reason.

Here's the log file when running without PTMProphet: [https://drive.google.com/file/d/14a1MQBZ15f8SaT-Z_YEDso8gZfAvod88/view?usp=drive_link](url)

I'm still not getting PSMs.

<img width="1059" height="461" alt="Image" src="https://github.com/user-attachments/assets/86804408-3c86-4599-8b8f-f5bd96d9b10f" />

Thanks for your help.

**Comment by fcyu** [comment]
The log file link is broken.

Best,

Fengchao

**Comment by TluckDucky** [comment]
I'm sorry @fcyu.

Here's again: https://drive.google.com/file/d/1oAcQMUPTHi2HWAvgJbyisOGytYh8R9Xy/view?usp=sharing

Thanks.

**Comment by fcyu** [comment]
There are several issues.

1. Your data has low resolution MS2, which should not be used in open search.  Please use closed search if possible.
2. I didn't see lysine propionylation in the setting
```
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
add_A_alanine = 0.0
add_C_cysteine = 57.02146
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.0
add_E_glutamic_acid = 0.0
add_F_phenylalanine = 0.0
add_G_glycine = 0.0
add_H_histidine = 0.0
add_I_isoleucine = 0.0
add_K_lysine = 0.0
add_L_leucine = 0.0
add_M_methionine = 0.0
add_N_asparagine = 0.0
add_Nterm_peptide = 56.0263
add_Nterm_protein = 0.0
add_P_proline = 0.0
add_Q_glutamine = 0.0
add_R_arginine = 0.0
add_S_serine = 0.0
add_T_threonine = 0.0
add_V_valine = 0.0
add_W_tryptophan = 0.0
add_Y_tyrosine = 0.0
```

Please double check your data and settings.

Best,

Fengchao

**Comment by TluckDucky** [comment]
Hi, @fcyu, 

I performed a closed search (LFQ-MBR) and I'm still getting the message `did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?`

Here's the log file: https://drive.google.com/file/d/1a46FtzcgdWZ3F4rmARfx_HdNPcsb27T6/view?usp=drive_link

I'm sorry, I just don't know what could be doing that. I'm reading some stuff online but I can find a way. Is there a tutorial for DDA analysis?

Thank you so much for the input and your time.

Thalles

**Comment by fcyu** [comment]
Either your data doesn't have anything, or your parameters, such as enzyme and modification, are wrong.

Here are tutorials about using FragPipe: https://fragpipe.nesvilab.org/

If you are looking for the tutorials for DDA analysis in general, I am sorry that due to the limited bandwidth, we only answer questions directly related to our tools.

Best,

Fengchao

**Comment by TluckDucky** [comment]
> Either your data doesn't have anything, or your parameters, such as enzyme and modification, are wrong.

That's odd. I'll try to check this up. About the enzyme, I selected ArgC once the peptides were treated with trypsin and propionylation. In my understading, if the propionylation had high efficiency, almost all lysines are propionilated, then the enzyme will cut only after arginine. I'll set to trypsin and see how it goes. 

> Here are tutorials about using FragPipe: https://fragpipe.nesvilab.org/

Thanks.

> If you are looking for the tutorials for DDA analysis in general, I am sorry that due to the limited bandwidth, we only answer questions directly related to our tools.

Yeap, I'm looking for a DDA analysis tutorial, I understand, thanks for your help. I appreciate it.

> Best,
> Fengchao

Best regards,

Thalles
