### ISSUE TITLE
FragPipe 20.0 is not compatible with Philosopher 5.1.0

### ISSUE THREAD

**Issue by Jianan106** [Nesvilab/FragPipe#1520]
- Describe the issue or question:
**To it may concern,

I have an issue here when I was running LFQ-MBR for pulldown samples. Here is the error:** 

ERRO[13:36:47] Cannot read file. open D:\FragPipeProcessed\2024-04-05-VS053\LFQ-MBR_output\CTx_2\.meta\db.bin: The system cannot find the file specified. 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 49 remaining tasks

**Would you mind helping me fix it?**

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-04-05_13-36-47.txt](https://github.com/Nesvilab/FragPipe/files/14904083/log_2024-04-05_13-36-47.txt)

**Comment by fcyu** [comment]
It is due to the version incompatibility. Could you upgrade FragPipe, MSFragger, and IonQuant to the latest version?

Thanks,

Fengchao

**Comment by Jianan106** [comment]
> It is due to the version incompatibility. Could you upgrade FragPipe, MSFragger, and IonQuant to the latest version?
> 
> Thanks,
> 
> Fengchao

Thank you so much Fengchao!

Yes, as I updated the version from FragPipe 20.0 to FragPipe 21.1, now it works!

Many thanks,
Jianan
