### ISSUE TITLE
IonQuant stops and report the "java.lang.NullPointerException" Error

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/FragPipe#1523]
- Describe the issue or question:
Dear developer,

I am try to use the modified TMT10-Acetyl workflow to quantify my data. However, before the start of TMT-integrator, IonQuant reported an error and stopped:
"java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at l.a(Unknown Source)
	at l.a(Unknown Source)
	at l.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)"

Are there anything wrong with my parameters settings?

Thank you!

- Upload your log file
[log_2024-04-08_13-00-06.txt](https://github.com/Nesvilab/FragPipe/files/14909081/log_2024-04-08_13-00-06.txt)

**Comment by fcyu** [comment]
It seems that one of your annotation file is empty. Could correct it and try again?

```shell
~~~~~~annotation files~~~~~~~
C:\Users\MSI13900K\Desktop\NormalSearching\Recent_2_NtermDegradation\MzmlFiles\2GroupA_annotation.txt:
126 sample-01
127N sample-02
128C sample-03
129N sample-04
130C sample-05
131N sample-06
C:\Users\MSI13900K\Desktop\NormalSearching\Recent_2_NtermDegradation\MzmlFiles\2GroupB_annotation.txt:
C:\Users\MSI13900K\Desktop\NormalSearching\Recent_2_NtermDegradation\MzmlFiles\2GroupC_annotation.txt:
126 sample-01
127N sample-02
128C sample-03
129N sample-04
130C sample-05
131N sample-06
~~~~~~~~~~~~~~~~~~~~~~
```
 Thanks,

Fengchao

**Comment by helloworld1631** [comment]
Sorry about that, I correct the annotation.txt and run Quant(isobaric) module again, but it still reports the same error. Do I need to run the whole workflow again?

[log_2024-04-08_13-57-50.txt](https://github.com/Nesvilab/FragPipe/files/14909228/log_2024-04-08_13-57-50.txt)

**Comment by fcyu** [comment]
Your annotation files have 6 channels but you selected `TMT 10`. Could you correct it and try again?
 
Best,

Fengchao

**Comment by helloworld1631** [comment]
I see. Yes, it works now. 
Thank you!
