### ISSUE TITLE
What does "DataBase Split" do?

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1524]
Dear author,

While using FragPipe, I followed the recommended procedure and split my database. However, I am uncertain about the underlying logic behind this action. Could you kindly clarify whether this step will have any impact on the final results? What potential effects could it bring about? My dataset pertains to HLA immunopeptidomics data obtained from QE instruments.

Looking forward to your response. Thank you so much!

Best regards,

**Comment by fcyu** [comment]
It is needed when your computer doesn't have enough memory to search the whole database at once, or the number of peptides is larger than ~2 billion.

Best,

Fengchao

**Comment by amingson** [comment]
> It is needed when your computer doesn't have enough memory to search the whole database at once, or the number of peptides is larger than ~2 billion.
> 
> Best,
> 
> Fengchao

Compared with those without split, would there be any difference in the final outcome, such as in the number of unique peptide segments identified?

**Comment by fcyu** [comment]
Slightly different.

**Comment by amingson** [comment]
> Slightly different.

Thank you for your response! Under favorable conditions, would it be better not to perform the split?

**Comment by fcyu** [comment]
Correct.

Best,

Fengchao

**Comment by amingson** [comment]
> Correct.
> 
> Best,
> 
> Fengchao

Thank you very much for your help, I understand now!

Best，

Anler
