### ISSUE TITLE
TMT-Integrator can't find the corresponding site localization column

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/FragPipe#1525]
- Describe the issue or question: 
Dear developer, 
I want to quantify the N-terminal acetylated peptides, so I loaded the TMT10-acetyl workflow, with the change of the PTMProphet and TMT Integrator settings. But TMT integrator reported an error said that: 
"TMT-Integrator can't find the corresponding site localization column. Please check if the column: s:42.01 is in the psm tables.
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping"

I check the psm table and found the N-term Ac was not in that table. 
![image](https://github.com/Nesvilab/FragPipe/assets/44239564/0b5f4d7e-140b-4ef1-b95a-4e54fa4b191f)

Does that mean there is something wrong with the PTM Site Localization in the Validation module? I clicked the "Load Mods from MSFragger Settings".
![image](https://github.com/Nesvilab/FragPipe/assets/44239564/54b9b8d8-0d5c-4f30-a217-251940314703)

Thank you!

- Upload your log file
[log_2024-04-08_16-40-09.txt](https://github.com/Nesvilab/FragPipe/files/14910814/log_2024-04-08_16-40-09.txt)

**Comment by fcyu** [comment]
The TMT-Integrator mod tag was set to `-termius(42.0106): Ac`, which is the cause of the error. Here is the tutorial incase you need it https://fragpipe.nesvilab.org/docs/tutorial_tmt.html . And here is a list of all tutorials: https://fragpipe.nesvilab.org/

Best,

Fengchao

**Comment by helloworld1631** [comment]
Thank you for the advice. I can generate a single-site TMT report for a specific amino acid modification site, just like the instruction mentioned.

My question is how to obtain a single-site TMT report for an N-terminal modification site. In the Validation settings, it automatically converts the peptide N-terminal modification "n^" to "-terminus". Based on what you said, there seems to be an issue with this format.


![image](https://github.com/Nesvilab/FragPipe/assets/44239564/09eb61a0-354a-46dc-bfdb-5b5f0bd3e575)

**Comment by fcyu** [comment]
There was a bug in "load Mods from MSFragger Settings", and has been fixed in https://github.com/Nesvilab/FragPipe/commit/9ffd5e2e384cfb438e25665b19a6fc77f6e474ed. It should be `n` not `-terminus`.

Best,

Fengchao

**Comment by helloworld1631** [comment]
I see. That should be the reason. 

Thank you!
