### ISSUE TITLE
Inquiry on Two-Pass Search Process and File Location Requirements

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1527]
Greetings MSFragger Team,

Thank you for consistently maintaining this tool. 

I am currently in the midst of utilizing the two-pass search method as outlined in your tutorial (https://fragpipe.nesvilab.org/docs/tutorial_two_pass_search.html). During this process, I have encountered a question regarding the organization of output files, specifically relating to the sub-mzML files generated. My workflow has resulted in all raw files, along with their respective uncalibrated .mzML and .mzBIN_all files, being stored in the following directory: D:\MSFragger_Temp\SLAS\Batch_1_2. Concurrently, all output files generated by FragPipeGUI are located in a separate subdirectory: D:\MSFragger_Temp\SLAS\Batch_1_2\Nonspecific_Peptidome_Output.

Given this arrangement, I am curious if the FragPipe Search output files need to be positioned in the same directory where the sub-mzML files are being written, or if the current file organization is suitable for the two-pass search process to function correctly. To provide some context, the scope of my search encompasses 140 files, with the process currently being halfway complete. I would greatly appreciate your guidance on this matter to ensure the continuation of a smooth and efficient workflow. Thank you for your time and assistance.

Regards,
Ben.

**Comment by fcyu** [comment]
Hi Ben,

Thanks for trying our two-pass search workflow.

> Given this arrangement, I am curious if the FragPipe Search output files need to be positioned in the same directory where the sub-mzML files are being written, or if the current file organization is suitable for the two-pass search process to function correctly.

The current file organization should be good. After FragPipe finished the first-pass analysis, the `fragpipe-second-pass.manifest` file in the result folder should have the correct paths of the sub mzML files. You just need to load that manifest file and the `fragpipe-second-pass.workflow` to perform the second-pass search.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Thank you.

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

I tried the Two_Pass_Search and hit an error. Have attatched the log in this thread for your reference. Please advise me on how to troubleshoot the error. Thank you.

Regards,
Ben

[Two_Pass_Search_Error.txt](https://github.com/Nesvilab/FragPipe/files/14932917/Two_Pass_Search_Error.txt)

**Comment by fcyu** [comment]
Hi Ben,

There are non-UTF-8 encoded characters in your raw files: `java.io.CharConversionException: Invalid UTF-8 Encoding`. Could you share `20230814_Eclipse_VQ_PTB_Sample_11.raw` with me to take a look? Here is the link to upload the file https://www.dropbox.com/request/odjk1bXWKeKTKSTd8b6B

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Have uploaded. Thank you.

**Comment by BenSamy2020** [comment]
Greeting @fcyu,

To follow-up I tried performing 2-pass search with 3 files only and hit the same error. Please refer to attachment for the log. This time, the error is with a different file. 

[log_2024-04-11_00-13-40.txt](https://github.com/Nesvilab/FragPipe/files/14934891/log_2024-04-11_00-13-40.txt)

**Comment by fcyu** [comment]
Hi Ben,

Thanks for your updates. It turned out to be a fixed bug: https://github.com/Nesvilab/FragPipe/commit/c89338bed5898631c8f0e57995ff8f34d685895f

If you want to try the pre-released version, could you send an email to yufe AT umich.edu ?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Or, converting the mzML files to raw files.

Best,

Fengchao

**Comment by fcyu** [comment]
Or, converting the raw files to mzML format.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Thank you. Have emailed you.

Regards,
Ben
