### ISSUE TITLE
The protein names listed in the 'peptide.tsv' file do not match those found in the ref-database.

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1528]
Dear author，

Upon reviewing the peptide.tsv file following the execution of the fragger tool, I have observed some discrepancies within the protein column where several names do not correspond to those found in the reference database.

![image](https://github.com/Nesvilab/FragPipe/assets/102129816/6a5027b2-0cb9-488a-a3f5-5690d9c6c7a0)

However, what is present in the database is as follows. Noncoding_ref.fasta is my database.  In the protein names, the 'Swiss-Prot' portion is missing.

![image](https://github.com/Nesvilab/FragPipe/assets/102129816/686e747d-2b85-4b08-ad87-ffc63a1e392f)

I sincerely hope to receive your assistance! Thank you so much!

Best,
Anler

**Comment by fcyu** [comment]
Hi Anler,

There must be proteins with `sp|P04264|K2C1_HUMAN` and `sp|P35908|K22E_HUMAN` in your fasta file because they are common contaminants. FragPipe will add them to your fasta file if you click `add decoys and contaminants` in FragPipe.

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/20939ceb-5c5b-423a-aad0-c0d1f2fba3e0)

Best,

Fengchao

**Comment by amingson** [comment]
> Hi Anler,
> 
> There must be proteins with `sp|P04264|K2C1_HUMAN` and `sp|P35908|K22E_HUMAN` in your fasta file because they are common contaminants. FragPipe will add them to your fasta file if you click `add decoys and contaminants` in FragPipe.
> 
> ![image](https://private-user-images.githubusercontent.com/6926299/321248568-20939ceb-5c5b-423a-aad0-c0d1f2fba3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTQ4NTQsIm5iZiI6MTcxMjc1NDU1NCwicGF0aCI6Ii82OTI2Mjk5LzMyMTI0ODU2OC0yMDkzOWNlYi01YzViLTQyM2EtYWFkMC1jMGQxZjJmYmEzZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTMwOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRkOTIxYWNiMGVmMDIxOTNhZDRiY2ZiZjhhMDM5YmRhNDZjNmNmMzdkNWRjNzA4MWMyZmNlMjZmZDBiZTVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O8UNn2KLeUHIR0ok7BQBg492eXEbdimomxnsj1H42lo)
> 
> Best,
> 
> Fengchao

Yes, while uploading the database, I indeed enabled the option to 'add decoys and contaminants'. Are you suggesting that these peptides are surfacing precisely due to this action? Since all the sequence IDs in my initial database commence with 'swissport', would it be feasible during the course of analysis to automatically eliminate sequences not starting with 'swissport'? For instance, could I disregard the segments highlighted in red within the image? Furthermore, how might I discern which entries in the peptide.tsv file represent decoys and contaminants? In MaxQuant output files, there exist specific columns to denote such information; is there a comparable method for identifying these within the current context?

Best,

Anler

**Comment by fcyu** [comment]
> Are you suggesting that these peptides are surfacing precisely due to this action?

Yes.

> how might I discern which entries in the peptide.tsv file represent decoys and contaminants?

If you let FragPipe download the fasta file for you and add the contaminants, contaminant proteins will have `contam` prefix.

Best,

Fengchao
