### ISSUE TITLE
There are corrupted files. Please remove those files and re-start task.

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1530]
Dear Author,

During batch execution of my program, I've come across a recurring error despite having more than 400 raw files organized into 95 separate groups. 
Upon deleting the last file flagged for causing the error, highlighted within a red frame, the same error still arises. 
Interestingly, executing this very file independently doesn't yield any errors. 
Could you kindly shed light on what might be the underlying cause of this issue? 
To provide context, my system configuration includes a RAM capacity of 300 (assumedly gigabytes), 20 threads, and operates in a non-MBR mode.

![image](https://github.com/Nesvilab/FragPipe/assets/102129816/9421f5d4-a002-4c37-b556-667146b15e03)

Best,

Anler

**Comment by fcyu** [comment]
The corrupted file is not the last one. You need to search the log to see which file threw the error.

Best,

Fengchao

**Comment by amingson** [comment]
> The corrupted file is not the last one. You need to search the log to see which file threw the error.
> 
> Best,
> 
> Fengchao


I checked the logs and found this error message. Should I consider deleting the sample "C20150427_JGA_3uLof6uL_1e8ceq_HLA_A31_IP_rep2.raw" based on this information?

`/media/zzp/Elements/HLApep/Search/MSV000084172/Alleles_ABCG_IAA/B5201_20171013/GN20171013_SK_HLA_B5201_R1_01.raw: Scans = 48274; Isolation sizes = [1.7]
/media/zzp/Elements/HLApep/Search/MSV000084172/Alleles_ABCG_IAA/A1101_2017/YE_20180517_SK_HLA_A1101_3Ips_a50mio_R2_02.raw: Scans = 37960; Isolation sizes = [1.0]
[pool-1-thread-3] ERROR umich.ms.fileio.filetypes.thermo.ThermoRawFile - PRC method Open() returned ErrorStatus. Messages: Could not open the specified file.
Failed in checking /media/zzp/Elements/HLApep/Search/MSV000080527/A3101/C20150427_JGA_3uLof6uL_1e8ceq_HLA_A31_IP_rep2.raw. Will ignore it.
Server could not open location
/media/zzp/Elements/HLApep/Search/MSV000080527/A3101/C20150427_JGA_3uLof6uL_1e8ceq_HLA_A31_IP_rep2.raw: Scans = 0; Isolation sizes = []
/media/zzp/Elements/HLApep/Search/MSV000084172/Alleles_ABCG_IAA/B1302_20171016/GN20171016_SK_HLA_B1302_R1_02.raw: Scans = 50582; Isolation sizes = [1.7]
/media/zzp/Elements/HLApep/Search/MSV000084172/Alleles_ABCG_IAA/B3701_20171019/GN20171019_SK_HLA_B3701_R1_01.raw: Scans = 49875; Isolation sizes = [1.7]
/media/zzp/Elements/HLApep/Search/MSV000080527/A0201/M20160113_JGA_HLA_A0201_5e7ceq_oncolumn_biorep2_techrep2.raw: Scans = 50301; Isolation sizes = [1.7]
`
Best, 

Anler

**Comment by fcyu** [comment]
The better way is converting all of your raw files to mzML format just in case: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by amingson** [comment]
> The better way is converting all of your raw files to mzML format just in case: https://fragpipe.nesvilab.org/docs/tutorial_convert.html
> 
> Best,
> 
> Fengchao


OK, thank you! I will try!

Best,

Anler
