### ISSUE TITLE
FragPipe-PDV sorting issue in FragPipe 20

### ISSUE THREAD

**Issue by WeiqiangChen** [Nesvilab/FragPipe#1532]
- Describe the issue or question:

In FragPipe 20, when I open PDV to view a spectrum, and click ModifiedPeptide column to sort the table, I could not find the PSM that I could see in the psm.tsv. Finally, I realized this table has 3 pages and the sorting only works on the first page! I will need to sort on each page and try to find the PSM, if not, try the next page. 
I thought sorting should sort the whole table. I don't get why there are multiple pages here. 

I have not tried FragPipe 21.1 on this issue. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by KaiLiCn** [comment]
Hi,

If you want to sort your whole PSM records, here is the way:
1. Select the item you want to sort in the dropdown menu located on the top right;
2. Click the `A to Z` or `Z to A` button.
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/ecb4415d-4478-4042-99f7-a797be3e1417)

**Comment by WeiqiangChen** [comment]
Thanks for your feedback. 

I have found out first to search for the peptide in the top right corner. Then it is just one page anyway.

**Comment by KaiLiCn** [comment]
The sorting function is on the top right corner of the PSMs panel.
