### ISSUE TITLE
Out of memory. PhilosopherFilter process returned non zero exit code, stopping

### ISSUE THREAD

**Issue by Miracheng** [Nesvilab/FragPipe#1533]
- Describe the issue or question:
I used a 1.35GB Fasta database and selected "Split Database". After spending about 20 hours, I still I received an error: “fatal error: out of memory”, and the analysis was stopped with "PhilosopherFilter 'finished, exit code: 2. Process returned non zero exit code, stopping".

My computer only has 8GB of RAM, what should I do next? thank you

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-04-13_11-37-23.txt](https://github.com/Nesvilab/FragPipe/files/14967097/log_2024-04-13_11-37-23.txt)

**Comment by anesvi** [comment]
First, get a decent computer with 64 or 128 gb RAM. Second, test on a single file first before running on all data.
