### ISSUE TITLE
Protein grouping: Proteome Discoverer 2.5 vs. FragPipe 21.1

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1535]
Hello

We are comparing the protein grouping between Proteome Discoverer 2.5 and FragPipe 21.1 and we get systematically around 15-20% less with FragPipe. We don't know why so I open the issue because maybe we are telling FragPipe the wrong way to count. As a sample file we can take a QC sample of HeLa available [here](https://www.dropbox.com/scl/fi/ikszvyl81yqnqtugdpps5/190219_Q_QC02_01_01_100ng.raw?rlkey=a72jo07y72haiy26eozeghyyv&dl=0). When we search using PD we get this protein file 
[proteins_PD_25.zip](https://github.com/Nesvilab/FragPipe/files/14997347/proteins_PD_25.zip) and with Fragpipe we get this protein file [proteins_fragpipe_211.tsv.zip](https://github.com/Nesvilab/FragPipe/files/14997360/proteins_fragpipe_211.tsv.zip). If you just count the proteins you get: 

| Fragpipe | PD (by High and IsMasterProtein) |
|------------|-----------------|
| 3478 | 4152| 4170|

We want to understand why this difference but we don't know. We checked the workflow file [massoffset-search.workflow.zip](https://github.com/Nesvilab/FragPipe/files/14997390/massoffset-search.workflow.zip) and it seems fine. Maybe is because we do a mass shift closed search? We also put `ionquant.proteinfdr=1`. 

Could you help us? Thanks!

**Comment by fcyu** [comment]
Thanks for contacting us. When I filter the `Protein FDR Confidence: Combined` with `High`, I got 3878 proteins

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/a4f23e72-6a01-4c0a-81dc-ea6d23b46bfe)

It seems that your data has low-resolution MS2 (ion trap), I think FragPipe performs better with high-resolution data (orbitrap)

Best,

Fengchao
