### ISSUE TITLE
How to set the parameter in FragPipe if I want to establish a phospho-library from fractionated DDA data with phosphorylation enrichment？

### ISSUE THREAD

**Issue by Nicolevswy** [Nesvilab/FragPipe#1538]
- Describe the issue or question:
How to set the parameter in FragPipe if I want to establish a phospho-library from fractionated DDA data with phosphorylation enrichment for subsequent quanting with DIA data with this library. I have tried but failed，and I can’t find anything significant in FragPipe website for this question. Please tutor me.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
 
Which workflow should I choose? DIA_SpecLib_Quant_Phospho or DIA_DIA-Umpire_SpecLib_Quant ? Can I mix the DDA and DIA data for a hybrid library?

Should I choose PTM-Shepherd?

**Comment by anesvi** [comment]
Load DIA_SpecLib_Quant_Phospho workflow, load DIA and (optional) DDA data, and run. Do not make any changes to the workflow.

**Comment by Nicolevswy** [comment]
Thank you very much. I got it.
