### ISSUE TITLE
Multiple errors while running FragPipe: Process 'SpecLibGen' finished, exit code: 1 ; Process 'PhilosopherFilter' finished, exit code: 1

### ISSUE THREAD

**Issue by Cllozano** [Nesvilab/FragPipe#1539]
Hi, 

We've been trying to interpret DIA data using the DIA_SpecLib_Quant worklow and encountered different issues. 

We tried different version of python (3.9.13 & 3.9.1) along with different version of easyPQP (0.1.35 & 0.1.42).

Everything seems fine in the configuration window but I've obtained the following messages: 

**Via anaconda - Python 3.9.13**

01

INFO[15:43:17] Parsing D:\MSfragger_pipeline\OUT\Baleneola_ptm_v21\interact-E03698_4D_TrypsinGold_DIA_03_rank2.pep.xml 
ERRO[15:43:17] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks

02

'D:\Anaconda3\Scripts\easypqp.exe' library --psmtsv 'D:\MSfragger_pipeline\OUT\test\psm.tsv' --peptidetsv 'D:\MSfragger_pipeline\OUT\test\peptide.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.0 'D:\MSfragger_pipeline\OUT\test\filelist_easypqp_library.txt'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Traceback (most recent call last):
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "D:\Anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

**Using Python 3.9.1**

'D:\_INSTALL\Python391\Scripts\easypqp.exe' library --psmtsv 'D:\MSfragger_pipeline\OUT\test\psm.tsv' --peptidetsv 'D:\MSfragger_pipeline\OUT\test\peptide.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.0 'D:\MSfragger_pipeline\OUT\test\filelist_easypqp_library.txt'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Traceback (most recent call last):
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "D:\_INSTALL\Python391\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\_INSTALL\\Python391\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.

Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks


I've attached the logs. 

Do you have any recommendation/turnaround to these issues ? 

Thanks for your help !
Best 
Clem 

[log_2024-04-17_15-43-17.txt](https://github.com/Nesvilab/FragPipe/files/15021724/log_2024-04-17_15-43-17.txt)
[log_2024-04-17_16-46-40.txt](https://github.com/Nesvilab/FragPipe/files/15021725/log_2024-04-17_16-46-40.txt)
[log_2024-04-17_21-49-06.txt](https://github.com/Nesvilab/FragPipe/files/15021726/log_2024-04-17_21-49-06.txt)
[log_2024-04-17_23-56-08.txt](https://github.com/Nesvilab/FragPipe/files/15021727/log_2024-04-17_23-56-08.txt)

**Comment by Cllozano** [comment]
Maybe it's unrelated but I have attempted with a different computer with python 3.12.0 and easyPQP 0.1.42 and got the following message: 

INFO[12:05:33] Parsing E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\interact-E03699_4D_Trypsin_LysC_DIA_03_rank5.pep.xml 
ERRO[12:05:33] Cannot read file. Error parsing the file     
INFO[12:05:33] Parsing E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\interact-E03694_4D_TrypsinGold_DIA_01_rank1.pep.xml 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks

**Comment by danielgeiszler** [comment]
Please post the full log.

**Comment by Cllozano** [comment]
Here you go 

[log_2024-04-18_12-05-33.txt](https://github.com/Nesvilab/FragPipe/files/15024036/log_2024-04-18_12-05-33.txt)

**Comment by Cllozano** [comment]
[log_2024-04-17_15-43-17.txt](https://github.com/Nesvilab/FragPipe/files/15021724/log_2024-04-17_15-43-17.txt)
[log_2024-04-17_16-46-40.txt](https://github.com/Nesvilab/FragPipe/files/15021725/log_2024-04-17_16-46-40.txt)
[log_2024-04-17_21-49-06.txt](https://github.com/Nesvilab/FragPipe/files/15021726/log_2024-04-17_21-49-06.txt)
[log_2024-04-17_23-56-08.txt](https://github.com/Nesvilab/FragPipe/files/15021727/log_2024-04-17_23-56-08.txt)

**Comment by fcyu** [comment]
Thanks for your files. There are two types of errors

```shell
E:\ClemLozano\soft\philosopher_v5.1\philosopher.exe filter --picked --prot 0.01 --minPepLen 8 --tag rev_ --pepxml E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig --protxml E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\combined.prot.xml --razor
INFO[12:05:33] Executing Filter  v5.1.0                     
INFO[12:05:33] Processing peptide identification files      
INFO[12:05:33] Parsing E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\interact-E03694_4D_TrypsinGold_DIA_01_rank3.pep.xml 
INFO[12:05:33] Parsing E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\interact-E03699_4D_Trypsin_LysC_DIA_03_rank5.pep.xml 
ERRO[12:05:33] Cannot read file. Error parsing the file     
INFO[12:05:33] Parsing E:\ClemLozano\FragPipe_results\Fragpipe_Bvulgaris_PTM_02Goodconfig\interact-E03694_4D_TrypsinGold_DIA_01_rank1.pep.xml 
```
and

```shell
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in <module>
    main_easypqp()
  File "D:\_INSTALL\FragPipe-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "D:\_INSTALL\Python391\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\_INSTALL\\Python391\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
```

Both of them were due to the files not readable. Please double check your computer, file system, and hard drive to make sure. And also make sure that there were no other software preventing FragPipe reading the files.

Best,

Fengchao

**Comment by Cllozano** [comment]
Hi Fengchao, 

Is there any other software you have in mind ? 

Nothing special was running on the computer. One of the query was made on a local computer with 24 go RAM and plenty of hard drive. The other one was on a server with 256go RAM. 

Best
Clem

**Comment by fcyu** [comment]
Hi Clem,

I don't have much clue. The error seems to be random, because in the first a few log file, the program couldn't read the `D:\MSfragger_pipeline\OUT\Baleneola_ptm_v21\interact-E03699_4D_Trypsin_LysC_DIA_03_rank5.pep.xml`, but in the last few logs, the program could read the file but got stuck at the spectral library generation stage.

Best,

Fengchao

**Comment by Cllozano** [comment]
Hi Fengchao,

Thanks for your help. 

I've tried  converting one file in mzML via MSconvert using the "non staggered" scheme advised here (https://fragpipe.nesvilab.org/docs/tutorial_convert.html#convert-thermo-dia-raw-files-with-overlappingstaggered-windows) (25% overlap DIA)

and it worked !

I'll give it a try on a bigger database and files to see if it goes through. 

Cheers
Clem
