### ISSUE TITLE
DIANN quantification don't do normalization

### ISSUE THREAD

**Issue by ningzaizai** [Nesvilab/FragPipe#1541]
Hi fcyu,
I want to ask you a question: Does Fragpipe in Linux normalize the quantification of proteins by default workflow when analyzing DIA data? I want to use Fragpipe to analyze DIA data now, but I hope Fragpipe does not normalize the protein quantification matrix. How should I set the parameters in the **DIA_SpecLib_Quant.workflow**. (below attachment)
[DIA_SpecLib_Quant.workflow.txt](https://github.com/Nesvilab/FragPipe/files/15022156/DIA_SpecLib_Quant.workflow.txt)

I look forward to your reply！
Best
Xiaolian

**Comment by fcyu** [comment]
> Does Fragpipe in Linux normalize the quantification of proteins by default workflow when analyzing DIA data?

Yes.

> I want to use Fragpipe to analyze DIA data now, but I hope Fragpipe does not normalize the protein quantification matrix. How should I set the parameters in the DIA_SpecLib_Quant.workflow

Add `--no-norm` to `diann.fragpipe.cmd-opts`.

Best,

Fengchao

**Comment by zoe1985** [comment]
Hi, Fengchao, 

Could I add "--mod id,301.1426 --no-norm" in Cmd line opts if new modification and no-normalization at the same time?

Thanks

Zoe

**Comment by fcyu** [comment]
Yes.
