### ISSUE TITLE
How to continue running based on the previously saved results of a program?

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1542]
Dear author,

While running Fragger, I encountered a parameter setting error that resulted in the program crashing. 
Despite this issue, the process had been running for quite some time and produced numerous files. 
Now that I have corrected the problematic parameter, I'm wondering if it's possible to resume the execution from where it left off and how to go about doing so. 

Your assistance on this matter would be greatly appreciated. Thank you very much!!

Best,

Anler

**Comment by fcyu** [comment]
Yes, same as https://github.com/Nesvilab/FragPipe/issues/268, https://github.com/Nesvilab/FragPipe/issues/631, and https://github.com/Nesvilab/FragPipe/issues/1505

Best,

Fengchao

**Comment by amingson** [comment]
> Yes, same as #268, #631, and #1505
> 
> Best,
> 
> Fengchao


Thank you!!!

Best,

Anelr
