### ISSUE TITLE
Cannot load pyopenms libraries to successfully generate spectral libraries in FragPipe v21.1

### ISSUE THREAD

**Issue by jkennedy-hutch** [Nesvilab/FragPipe#1543]
Good afternoon,

  I have not been able to successfully fire off spectral library generation.  We're running FragPipe v21.1 and have EasyPQP v0.1.42 loaded.  We are getting a bunch of errors associated with OpenMS libraries, such as "ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed." and "Error when loading pyOpenMS libraries!  Libraries could not be found / could not be loaded."  These issues are possibly due to corrupt versions of OpenSwathAlgo.dll and/or Qt5Core.dll under C:\ProgramData\Python_3.9\lib\site-packages\pyopenms.  I've tried going through the Anaconda3 & OpenMS libraries to try to fix this problem, but with no luck.  Any thoughts about how I can get spectral library generation going in our FragPipe?

Thanks,
-Jake

**Comment by fcyu** [comment]
Seems to be the same as https://github.com/Nesvilab/FragPipe/issues/1431

The OpenMS team is working on it https://github.com/OpenMS/OpenMS/issues/7333

Best,

Fengchao

**Comment by jkennedy-hutch** [comment]
Thank you very much!  I’ll head over there!

**Comment by Andre-C-M** [comment]
the following fixed it for me: 
I was using a freshly installed Anaconda base (root) environment which caused it not to work.
I created a new environment and selected the new python.exe within fragpipe. Clicking 'Install/Upgrade EasyPQP' afterwards will install all dependencies and versions properly.

**Comment by guoci** [comment]
@Andre-C-M thanks for the feedback.
I think this is the same as #1836. In both cases, the user uses an administrator installed Python, then installs Python packages using a non-administrator account, and that combination causes PyOpenMS to break.
