### ISSUE TITLE
How should parameters be set to increase the number of unique peptides identified in the final results?

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1544]
Dear author,

In my job, I am responsible for performing peptide identification within HLA immunopeptidomes, and I would like to inquire if you have any suggestions for improving the number of unique peptides that are successfully identified in the end results.

Best,

Anler

**Comment by fcyu** [comment]
We have tuned and optimized our programs to have the best performance compared to the competitors. If you wonder how to get a better result than state-of-the-art, it is a research question, but we only answer the questions about using our tools.

Best,

Fengchao

**Comment by amingson** [comment]
> We have tuned and optimized our programs to have the best performance compared to the competitors. If you wonder how to get a better result than state-of-the-art, it is a research question, but we only answer the questions about using our tools.
> 
> Best,
> 
> Fengchao


OK，thank you!!!

Best, 

Anler
