### ISSUE TITLE
Setting FDR threshold for PSMs (apparently the user set the parameters wrong)

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1545]
I would like to get PSMs with an FDR < 0.1 in the output file "psm.tsv". To do this, I specified "--sequential --picked --prot 0.01 --psm 0.1" in the Filter section of "FDR Filter and Report" in the Validation tab. You can see the details in the attached screenshot. 

However, based on what I read in the log file of the search, the default FDR threshold (0.01) was used for PSMs. How could I change the threshold to 0.1 (for PSMs only)? Thank you very much!

<img width="1127" alt="Screenshot 2024-04-19 at 11 01 13" src="https://github.com/Nesvilab/FragPipe/assets/64355618/ecf65543-1657-41bf-b175-1a5ac35d4d5a">

**Comment by danielgeiszler** [comment]
Please post your log.

**Comment by RobAlbn** [comment]
Thank you! I found the part about "PhilosopherFilter" in the log file. The "PhilosopherFilter" commands use the parameter values that I specified and that are in the attached screenshot. In general, how can I check which FDR threshold was used to select the PSMs of the file "psm.tsv"?  Thank you again!

**Comment by dpolasky** [comment]
The screenshot did not get uploaded to github. You can try again, or just post the filter.log file, which only has information about the filtering. You are looking for a line that says "converged to ## % FDR with #### PSMs" to confirm the FDR used. 

Best,
Dan

**Comment by RobAlbn** [comment]
Here is the final part of the filter.log file (again, I replaced numbers with the symbol #). Where can I find the FDR threshold that was used for PSMs? Thank you very much for your help and, in general, for FragPipe!

_""""
Database search results                      
Converged to 2.67 % FDR with # PSMs      
Converged to 1.00 % FDR with # Peptides 
Converged to 1.00 % FDR with # Ions       
Protein inference results                     
Converged to 0.98 % FDR with # Proteins   
Applying sequential FDR estimation            
Converged to 0.07 % FDR with # PSMs      
Converged to 0.11 % FDR with # Peptides  
Converged to 0.10 % FDR with # Ions      
Post processing identifications              
Assigning protein identifications to layers  
Processing protein inference                 
Synchronizing PSMs and proteins              
Final report numbers after FDR filtering, and post-processing
Saving                                       
Done  
""""_

**Comment by dpolasky** [comment]
I see - the final PSM FDR was 0.07% because you used the sequential filter (which removes PSMs from proteins that themselves did not pass FDR). To get your specified 0.1% PSM level FDR, you need to remove the --sequential from the filter command (it should be either --sequential or --picked, not both).

**Comment by RobAlbn** [comment]
_"""" 
Database search results                       
Converged to 2.67 % FDR with # PSMs      
Converged to 1.00 % FDR with # Peptides  
Converged to 1.00 % FDR with # Ions      
Protein inference results                     
Converged to 0.98 % FDR with # Proteins   
2D FDR estimation: Protein mirror image       
Second filtering results                     
Converged to 1.40 % FDR with # PSMs      
Converged to 1.00 % FDR with # Peptides  
Converged to 1.00 % FDR with # Ions      
Post processing identifications              
Assigning protein identifications to layers  
Processing protein inference                 
Synchronizing PSMs and proteins              
Final report numbers after FDR filtering, and post-processing  
Saving                                       
Done 
""""_

**Comment by danielgeiszler** [comment]
It's filtering on PSMs, peptides, ions, and proteins. If you only want a PSM filter, you need to change the others as well.

A complete guide to the filter commands can be found here:

https://github.com/Nesvilab/philosopher/wiki/Filter

**Comment by RobAlbn** [comment]
Thank you! Do I just need to change the other filters? Can I keep "--picked" in the command or do I need to remove that parameter?

**Comment by dpolasky** [comment]
Yes I think you need to remove the protein filter entirely, although to actually do that you need to check the "Do not use ProteinProphet file" checkbox. 

If you are still seeing <10% PSM FDR (e.g., 2.67%) after that, you may also need to reduce the min probability in Percolator/PeptideProphet - you can set it to 0 to include all PSMs in filtering, for example. 

Best,
Dan

**Comment by RobAlbn** [comment]
Thank you very much!
