### ISSUE TITLE
Whether the data of TMT-10 and TMT-11 can be searched together?

### ISSUE THREAD

**Issue by cindysimm** [Nesvilab/FragPipe#1546]
Hello, 
I'd like to know whether the data of TMT-10 and TMT-11 can be searched together using FragPipe?
I try to search these two kind of rawdata together, using TMT10 workflow with TMT-11 label type. However, the channel 131C of TMT-10 labeled samples also has a high intensity. What is the reason for such a high intensity value? If I still want to search the two kind of data together, do I need to change some parameters?
Looking forward to your reply! Thank you very much!

**Comment by cindysimm** [comment]
Thank you for your reply!
Does the annotation file of TMT10 datasets upload like this?

126	sample1
127N	sample2
127C	sample3
128N	sample4
128C	sample5
129N	sample6
129C	sample7
130N	sample8
130C	sample9
131N	sample_pool
131C	NA

Whether the output contains 131C channels? The search of two kind of datasets do not have an impact on integrating information using pool sample, right?

**Comment by fcyu** [comment]
I think so.

Best,

Fengchao

**Comment by cindysimm** [comment]
Thank you very much!

**Comment by cindysimm** [comment]
Excuese me, I have another questions: If the pool samples are different across TMT-plex, can I use the 'TMT-10 Bridge' workflow?

For example, pool sample of the first 10 plex and the last 10 plex is different. When these 20 samples are searched together, can I use the 'Bridge' workflow? Or do I need to search separately?

**Comment by fcyu** [comment]
Yes, you can. Set the `ref sample tag` to, say, `pool`. And then, name the pool channel to `pool01` and `pool02` for the first and second 10 ples, respectively. 

Here is the tutorial in case you need it https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html

Best,

Fengchao

**Comment by anesvi** [comment]
I think they are asking about two datasets with different reference samples? If so, the question goes well beyond what this GitHub forum is for. You should probably find a collaborator who can advise you on best ways to merge datasets that use different references.

**Comment by cindysimm** [comment]
> I think they are asking about two datasets with different reference samples?

Yeah.  Thank you for your reply.
Then another question is, does the defult 'TMT-10' workflow use **match between run** process?

**Comment by fcyu** [comment]
No, the current version of the TMT workflow does not support MBR.

Best,

Fengchao

**Comment by cindysimm** [comment]
Thank you again for your great help!
