### ISSUE TITLE
IonQuant out of bounds 

### ISSUE THREAD

**Issue by StephenHol** [Nesvilab/FragPipe#1548]
Hello, 
Thank you so much for Fragpipe. 
I am trying to run some SILAC data using Fragpipe v21.1 I am now able to do open search fine now. But when i try to search my data set to get quant data I keep encountering this error: 

2024-04-19 15:40:45 [INFO] - Combining experiments and estimating protein intensity...
java.lang.ArrayIndexOutOfBoundsException: Index -29001 out of bounds for length 29662
	at r.a(Unknown Source)
	at r.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2024-04-19 15:40:51 [ERROR] - Index -29001 out of bounds for length 29662
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

I have attached the log from the most recent run. Any help or guidance would be greatly appreciated. 
[log_2024-04-19_15-40-51.txt](https://github.com/Nesvilab/FragPipe/files/15042421/log_2024-04-19_15-40-51.txt)

best wishes, 
Stephen

**Comment by fcyu** [comment]
It is a known bug: https://github.com/Nesvilab/FragPipe/issues/1387

Could you send an email to yufeATumich.edu (replace `AT` with `@`) to get the fixed version?

Thanks,

Fengchao
