### ISSUE TITLE
How to customize house-made isobaric tags in FragPipe/MSFragger

### ISSUE THREAD

**Issue by Miqimiaomiaow** [Nesvilab/FragPipe#1549]
Dear authors,

I am trying to edit our house-made isobaric tags (DiLeu) in MSFragger. However, I didn't find any place for customized tags. Could you please let me know if MSFragger allows customized tags and how to do so? Thank you very much for your help!

Best regards,

Fei

**Comment by fcyu** [comment]
I guess you meant FragPipe and isobaric quantification? Current version does not support customized the tags but we can add it for you if you send us the masses. And the new changes will be available in the next release.

Best,

Fengchao

**Comment by Miqimiaomiaow** [comment]
Hi Fengchao,

Thanks a lot for your reply. Please see the attached mass of reporter ions of DiLeu isobaric tags. The first page is the list of masses and the second is the format we used in Proteome Discover software for your reference.

Could you let me know about when the new release will be available so we can plan accordingly? Please free to reach out if you need further information. Thank you very much!


Best regards,


Feixuan Wu

Graduate Student, School of Pharmacy

Lingjun Li Lab

University of Wisconsin--Madison


________________________________

**Comment by fcyu** [comment]
Hi Feixuan,

The attachment was truncated by GitHub.  Could you go to https://github.com/Nesvilab/FragPipe/issues/1549 and do it again?

Thanks,

Fengchao

**Comment by Miqimiaomiaow** [comment]
[DiLeu 12-plex.method.xlsx](https://github.com/Nesvilab/FragPipe/files/15239795/DiLeu.12-plex.method.xlsx)

Please let me know if it works for you. Thanks!

**Comment by fcyu** [comment]
Hi Feixuan,

Thanks for the file. It works. 

May I ask if DiLeu-12's variable modification mass is 145.12801 (https://pubs.acs.org/doi/10.1021/ac503276z)?

Thanks,

Fengchao

**Comment by Miqimiaomiaow** [comment]
Hi Fengchao,

Yes, the static modifications consisted of DiLeu labels on peptide N termini is 145.12801 Da.


Best regards,


Fei

________________________________

**Comment by fcyu** [comment]
Thanks for the prompt reply. I have pushed the changes regarding FragPipe (need to have the new IonQuant to make it work). 

I think the new versions will be released this month.

Best,

Fengchao

**Comment by Miqimiaomiaow** [comment]
[like]  Feixuan Wu reacted to your message:
________________________________
