### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by vdemichev** [Nesvilab/FragPipe#155]
**Describe the bug**

Launch FragPipe.exe (v12.1), click "Select LC/MS Files", click "Add files". 
java.lang.NullPointerException error is then produced (please see the full error attached)
Java version 1.8.0_231 x86_64 on Windows 19 Pro x64. Tested on two machines.
[Java error.txt](https://github.com/Nesvilab/FragPipe/files/3907412/Java.error.txt)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by chhh** [comment]
@vdemichev What is the current location of the files? Are they on some sort of network storage?
Could you please try moving LCMS files to some other path? The error is strange in that it couldn't find a parent directory of your files, but that shouldn't normally happen.

**Comment by vdemichev** [comment]
Hi @chhh ! I am not trying to open any specific files, I just click "Add files" and get this error. So I don't even see the file open menu. Trying to drag and drop a file from a local folder also yields the same error. I have just tried moving FragPipe to a third PC (copy-pasted FragPipe.exe to its Desktop), the PC did not have Java - I installed OpenJDK 13 (a link to download OpenJDK was opened automatically in the browser when I tried to launch FragPipe) - same error.

**Comment by chhh** [comment]
@vdemichev Ok, that's something new, we've never seen this before. That certainly works for everyone else, so there must be something special about the computers you ran this on. Are they in any sort of a managed/restricted environment?

Tracing the code path for that button click I have no idea why this might be happening. Could you please try this build: https://github.com/chhh/FragPipe/releases/tag/add-files-error

**Comment by vdemichev** [comment]
Same error with that build. Should be nothing special about the PCs, one is just a home PC (no network drives, not on a domain).

**Comment by vdemichev** [comment]
Solved :) The error occurs when MSFragger.jar path is not specified. I thought it would work with just DIA-Umpire & Philosopher. Thank you!

**Comment by chhh** [comment]
Oh, ok, thanks for the report, I'll look into why this might be happening.
