### ISSUE TITLE
Process 'PhilosopherFilter' finished, exit code: 1

### ISSUE THREAD

**Issue by RevathyNanda** [Nesvilab/FragPipe#1550]
Hello,
I was running TMT-10 phospho workfow in Fragpipe v20.0. I am getting this error and not able to solve.
"time="15:03:49" level=error msg="Cannot read file. open /media/csbmm/working_dir/Revathy/PhD/Rawdata_reanalysis_02222023/TMT/PXD029432/BRCA1/PXD029432_BRAC1_Run2_Trial_04192024/.meta/db.bin: no such file or directory"
Process 'PhilosopherFilter' finished, exit code: 1"

In the same run, for set 1 PhilosopherFilter ran successfully ,
"Command: /home/csbmm/Documents/Tools&Softwares/FragPipe-20.0/fragpipe/tools/philosopher_v5.1.0_linux_amd64/philosopher filter --sequential --picked --prot 0.01 --mapmods --tag rev_ --pepxml /media/csbmm/working_dir/Revathy/PhD/Rawdata_reanalysis_02222023/TMT/PXD029432/BRCA1/PXD029432_BRAC1_Run1_Trial_04192024 --protxml /media/csbmm/working_dir/Revathy/PhD/Rawdata_reanalysis_02222023/TMT/PXD029432/BRCA1/combined.prot.xml --razor
Run result:time="15:03:33" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=37754 peptides=26037 proteins=5770 psms=75416
time="15:03:33" level=info msg=Saving
time="15:03:35" level=info msg=Done "

What might be the reason? And how to solve this? 
Thank you,
Revathy

**Comment by anesvi** [comment]
Please upgrade to the latest tools and try again, if you still have a problem, send us the full log file

**Comment by RevathyNanda** [comment]
Thank you. I updated FragPipe to version 21.0. Now PhilosopherFilter is working properly
