### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by haowBio** [Nesvilab/FragPipe#1551]
Hellow, 

I encountered an issue while running the TMT-Integrator. When attempting to integrate the results from multiple psm.tsv files into TMT-11, I'm unable to generate the result report and receive the following error message: `java.lang.NullPointerException
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.base/java.util.TreeMap.get(TreeMap.java:277)
	at integrate.LoadPsms(integrate.java:155)
	at integrate.run(integrate.java:31)
	at TMTIntegrator.main(TMTIntegrator.java:109)
Error at: /data/haowu/proteome/Pancreas/Result/test/result/02CPTAC_PDA_Proteome_JHU_20191022/psm.tsv java.lang.NullPointerException
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping` Interestingly, the process runs successfully when working with a single psm.tsv file. Any suggestions on how to resolve this?
[log_2024-04-24_17-15-54.txt](https://github.com/Nesvilab/FragPipe/files/15091925/log_2024-04-24_17-15-54.txt)

**Comment by fcyu** [comment]
You are using old versions of the tools. The bug might have been fixed in the new version. Could you upgrade FragPipe, MSFragger, IonQuant, and Philosopher, and try again?

Thanks,

Fengchao
