### ISSUE TITLE
Using IonQuant directly without MSfragger

### ISSUE THREAD

**Issue by aly1020** [Nesvilab/FragPipe#1552]
Dear FragPipe team,

I am searching data using MSfragger and IonQuant. The search stopped at IonQuant because of a lack of memory. I am now repeating the search allocating more memory to FragPipe. Still, the search with MSfragger has to be repeated to get to IonQuant which is time-consuming.
Is there a way to bypass all the other steps I have already performed and use directly IonQuant ?

Thank you for all the work and effort you put into FragPipe.
Angelo

**Comment by fcyu** [comment]
Hi Angelo,

Yes, you just need to check the steps that have completed: https://github.com/Nesvilab/FragPipe/issues/268

Best,

Fengchao

**Comment by aly1020** [comment]
Dear Fengchao,
Thank you very much for the help!

All the best,
Angelo
