### ISSUE TITLE
Quantify unmatched peptide like features

### ISSUE THREAD

**Issue by eldenrowland** [Nesvilab/FragPipe#1553]
Hi FragPipe team,
 
I am wondering if FragPipe is able to quantify all peptide like features (or multiply charged ions perhaps)? IonQuant exports a list of intensities for matched peptides (or PSMs). We would like to know the peak areas for all unmatched peptides as well.

OpenMS has a TIC calculator tool that tells you the sum of all peak intensities (e.g. 6e12) but I am unsure how comparable this is to the IonQuant intensities output (1.7e12). This The TIC calculator draws from ThermofileParser I do believe.    

I think we essentially need to use a feature finder tool but I'm not sure which would be most compatible/comparable with the IonQuant intensity values. Ideally we would like to generate a table with all features and their intensities that can be parsed with the matched PSM or peptide intensities.

Any suggestions are most welcome, 

All the best,

Elden Rowland
Research Associate, Bertrand lab
Dalhousie University
Halifax, NS

**Comment by fcyu** [comment]
Thanks for the feature request. Due to the algorithm in IonQuant, it is hard to detect the features without a PSM. 

I also don't understand why you wanted to compare the intensity values of IonQuant with OpenMS. As far as I know, the intensities are not comparable across different tools because they have different ways to integrate/calculate the XIC.

Best,

Fengchao

**Comment by eldenrowland** [comment]
Hi Fengchao,

I think the OMS tool simply takes the intensity values from the raw file. i.e. sums all intensities in all spectra. I understand that it's not really comparable. It was used as a rough starting place. 

So it seems we really do need a proper feature finder. And it should integrate ions in a similar fashion to IonQuant. Do you think this is possible? 

Best,

Elden

**Comment by fcyu** [comment]
It is possible but not trivial. I need to discuss with other team members internally since we have many requested features to implement.

Best,

Fengchao

**Comment by eldenrowland** [comment]
Hi Fengchao,

Thank you for looking into this. I'm beginning to realize it's not so straight forward. I totally understand if it's beyond the scope of your project at the moment. 

One thing to consider is using the list of MS2 precursors (that can be extracted with RawTools) to generate features. I know that's not really all of the features but it might approximate most of the more abundant peptides in the sample. 

Curious to hear what your team thinks.

All the best,

Elden

**Comment by fcyu** [comment]
Hi Elden,

> One thing to consider is using the list of MS2 precursors (that can be extracted with RawTools) to generate features.

I am not familiar with the RawTools. Could you please briefly tell me how the list of MS2 precursors and the features are generated?

Thanks,

Fengchao

**Comment by eldenrowland** [comment]
Hi, 
RawTools is generally used to get some basic stats on each raw file and asses the efficiency and reproducibility of your LC-MS run. https://github.com/kevinkovalchik/RawTools

If you run the following command it will output a table of all MS2 scans and the precursor mass that triggered each MS2 scan in a DDA run. I'm not sure if these precursors could be used for the MBR, MaxLFQ type quant in IonQuant?

mono ~/Projects/rawtools/RawTools.exe -f ~/Projects/Match_rate_features_test/221031_1099_097_BB40_10_130.raw -p

All the best,

Elden

**Comment by fcyu** [comment]
Hi Elden,

Yes, it could be used by IonQuant to detect and extract XICs for those MS2 scans. But note that the MS2 scans don't contain all "peptide features". There are many "peptide features" without any MS2 scans.

If you just want to get the XICs for all MS2 scans, you actually don't need to run RawTools. You just need to set all FDR thresholds to 100%, and all probability thresholds to 0 when running FragPipe.

Best,

Fengchao

**Comment by eldenrowland** [comment]
That's great Fengchao, I'll give it a try! Thanks so much!

I definitely agree that there will be many peptides not captured by the DDA duty cycle as MS2s. 

From our perspective, what would be helpful is if we could generate an 'intensity' value for, (1) all features, (2) all peptide-like features (3) matched features, which of course fragpipe/Ionquant already gives us. 

Cheers,
