### ISSUE TITLE
PTMShepherd could not find mzData for run

### ISSUE THREAD

**Issue by dfermin** [Nesvilab/FragPipe#1554]
Hi

I'm having an error with PTMShepherd with reading my mzML files on linux.

```
PTMShepherd [Work dir: /data/MS_2024-10-01-001/finalDB_MBR_3ppm3minRT_10topRuns_0.5cor/out]
java -Xmx490G -Dlibs.thermo.dir=/usr/local/apps/MSFragger-4.0/ext/thermo -cp /usr/local/apps/fragpipe/tools/ptmshepherd-2.0.6.jar:/usr/local/apps/fragpipe/tools/batmass-io-1.30.0.jar:/usr/local/apps/fragpipe/tools/commons-math3-3.6.1.jar:/usr/local/apps/fragpipe/tools/hipparchus-1.8/hipparchus-core-1.8.jar:/usr/local/apps/fragpipe/tools/hipparchus-1.8/hipparchus-stat-1.8.jar edu.umich.andykong.ptmshepherd.PTMShepherd "/data/MS_2024-10-01-001/finalDB_MBR_3ppm3minRT_10topRuns_0.5cor/out/shepherd.config"

PTM-Shepherd version 2.0.6
(c) 2022 University of Michigan

Using Java 22 on 501760MB memory

Finding spectral data
        Indexing data from F20230904_1092_uncalibrated
Fatal error: In dataset "F20230904_1092_uncalibrated" could not find mzData for run F20230904_1092_uncalibrated
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping
```

The files are named as F20230904_1092_uncalibrated.mzML

Here is the top of my fragpipe-files.fp-manifest file in case that helps:
```
/data/MS_2024-10-01-001/mzML/F20230904_1092_uncalibrated.mzML        F20230904_1092_uncalibrated             DDA
/data/MS_2024-10-01-001/mzML/F20230904_604_uncalibrated.mzML F20230904_604_uncalibrated              DDA
```

In case it helps here is my java version info:
```
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+36-2370)
OpenJDK 64-Bit Server VM (build 22+36-2370, mixed mode, sharing)
```

Any suggestions what migh be wrong?
Thanks

**Comment by danielgeiszler** [comment]
Please upload your log and your shepherd.config file.

**Comment by dfermin** [comment]
I think these are the files you requested. 
The log file is from the `F20230904_1092_uncalibrated` folder created in the output directory.
I had to had the `*.txt` extension to `sheperd.config` to upload it otherwise it wouldn't be there.

[shepherd.config.txt](https://github.com/Nesvilab/FragPipe/files/15108708/shepherd.config.txt)
[filter.log](https://github.com/Nesvilab/FragPipe/files/15108709/filter.log)

**Comment by danielgeiszler** [comment]
This isn't the log file for the run, only for the filtering. In one directory up there should be a a file with the format "log_[date_time].txt". If none, exists, please click "Export Log" under the run tab.

Can you please confirm that the appropriate mzML files are in the /data/MS_2024-10-01-001/mzML directory? And can you please also confirm that the psm.tsv files have file names that match the mzMLs in the Spectrum column?

Are these reruns from a previous FragPipe run, or did you have the uncalibrated tag in the file name previously?

**Comment by dfermin** [comment]
Hello
I can confirm the mzML files are in the correct path. 
I have confirmed that the psm.tsv "Spectrum" column has the correct file name (example: `F20230904_1092_uncalibrated.00726.00726.3`).

Is there a way to specify "Export Log" within the fragpipe.workflow file? I'm running this on a linux machine without using the GUI?

**Comment by danielgeiszler** [comment]
I'm not sure about that @fcyu will know.

Are these reruns from a previous FragPipe run, or did you have the uncalibrated tag in the file name previously? I think this tag is what is causing the issue.

**Comment by fcyu** [comment]
> Is there a way to specify "Export Log" within the fragpipe.workflow file? I'm running this on a linux machine without using the GUI?

If you run FragPipe in command line, you could either redirect the stdout to a log file using `tee`, or FragPipe will generate the log file if it finishes successfully.

Best,

Fengchao

**Comment by dfermin** [comment]
I have removed the `_uncalibrated` from the mzML file names and started the run over redirecting STDOUT and STDERR to a file. I'll post an update as soon as it's done.

Thanks

**Comment by danielgeiszler** [comment]
Tested and reproduced the issue. You can't run files containing the _calibrated or _uncalibrated tag.

I'm not sure if there's an easy way to fix this since it needs to be able to match scans produced by files from Fragger that have this tag.

**Comment by dfermin** [comment]
Yes that seems to be the issue (at least with these test cases).
What is the specific pattern that causes an issue? The presence of the `_` character? 

Here is my STDOUT/STDERR for the run.
I just symlink the input files to a new name for testing. 

[msfragpipe-2024-04-25.log](https://github.com/Nesvilab/FragPipe/files/15111230/msfragpipe-2024-04-25.log)

**Comment by danielgeiszler** [comment]
MSFragger will produce spectral files that contain either the _calibrated or _uncalibrated tags at the end, and PTM-Shepherd will preferentially read these as input over other raw files, but it has to maintain the mapping to the original file name internally. So it's really just that these particular tags are "reserved".

**Comment by dfermin** [comment]
Okay so the best thing to do in my case is remove the `_calibrated` or `_uncalibrated` text from the names of the mzML files correct?

**Comment by dfermin** [comment]
Thanks for your help. The pipeline now runs to completion.
