### ISSUE TITLE
Corrupted FASTA file broke the program

### ISSUE THREAD

**Issue by Cllozano** [Nesvilab/FragPipe#1555]
Hi, 

I am trying to interpret data from an Astral instrument with a predefined DIA workflow. 

While it works with a smaller dataset (and database) from an exploris 480, it doesn't go through with the Astral data. 

I've tried with mzML and raw files and got the same message. 

You can find the log files with that link [transfer_7348040_files_f162cc91.zip](https://github.com/Nesvilab/FragPipe/files/15110767/transfer_7348040_files_f162cc91.zip)

Thanks for your help, 
Best
Clem

**Comment by fcyu** [comment]
Hi Clem,

Your fasta file looks weird. Could you zip and upload the file `D:\DIA_databases\2024-04-11-decoys-DB48.fasta.fas`?

There seems to be lowercase and non-alphabet characters in the protein sequence.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Clem,

Thanks for your fasta file. There are protein sequences like the following, which broke the tools.


MLFPKRLIVWGVLLILSLSQFVLYLPATTCTNSKGLRLCAPQFTITVIGGSSTANEFIASVREFLRLISYLTIDMGWSNEFTDPSVYEDENLVDTFQPDKVFELNYFGFCKRSNKSKVYCTSNENYGMDVLEVLVRDVGIQLGNISTTRSNETKKFGDSLVLTYRLALTSIRDFLKHDKHTGNALSKALIGSPDPNVKGASPTKNYLKGVNLAFILMMFNGMVFYFAVLEIIVGFLSICVVSAFGGALSVGKRHRLFPILLKSSSSILVVIATLTILCNIVYLIALKTLEPEEVTDVGSDNAAVHTTGWELLKVNVGSGFIMGLARYAIQWVLLVLAFLAANHYKAKPKKSDKYTEDTSNSPSPDLM**EK">A6ZML5.1** Altered inheritance of mitochondria protein 36, mitochondrial [Saccharomyces cerevisiae YJM789]MLRPLRKSVLASCRHCFKVCGGLPQKQLPLFSPLLLRARYSSTDSSTKRSNKSDKIDAPGFKKIFLVAIIGTVIFVKTVQSLDKNKPKTTLSEEEFENVVKGLKRRVAIFPQGEVDIKFSLSPSIEETRKVLQKSQGDDINELQFVDPVKVIDYYRTLRDDRYEALLNEYYKKYGCDTYAYNLPTGMLVMLLGRYFKENFKAGDKLVVVNFPHSIADATRFENEVSIVSKIFVPRKLSGSDVCKYYETVG**KADII"">A6ZMQ6.1** Cx9C motif-containing protein 4, mitochondrial [Saccharomyces cerevisiae YJM789]MSNPCQKEACAIQDCLLSHQYDDAKCAKVIDQLYICCSKFYKDNGKDSRSPCCPLPSLL**ELKMKQRKLTPGDS"**

Best,

Fengchao
