### ISSUE TITLE
Java Out of Memory error

### ISSUE THREAD

**Issue by edf4n** [Nesvilab/FragPipe#1557]
**- Upload your log file**

[log_2024-04-25_11-50-28.zip](https://github.com/Nesvilab/FragPipe/files/15112673/log_2024-04-25_11-50-28.zip)

**- Describe the issue or question:**

I received this error when trying to complete a DIA search (5 mzML files; using DIA_SpecLib_Quant workflow; Orbitrap Astral data)

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.C.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.a(Unknown Source)
	at edu.umich.andykong.msfragger.o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

I am not sure what to do to fix the memory issue.
Thank you!

**Comment by edf4n** [comment]
Thank you for your reply.

Could you please tell me what the memory requirements are? I checked my computer system and the device is 64GB of RAM with 63.7GB available. 

Is there any way to break up the search into pieces so that the search can be completed?
Here are the full specifications for my computer system.

Processor	Intel(R) Xeon(R) W-2265 CPU @ 3.50GHz   3.50 GHz
Installed RAM	64.0 GB (63.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Thank you for your guidance!

**Comment by fcyu** [comment]
FragPipe only detected 12 GB free memory from your computer: `-Xmx12G`. Maybe at that point, there were other programs using additional memory? 

Could you re-run FragPipe again? If FragPipe still only detected 12 GB, could you reboot your computer and try again?

Thanks,

Fengchao

**Comment by edf4n** [comment]
Thank you, I will try closing down other programs, rebooting my PC and trying again!
