### ISSUE TITLE
Found peptides are not matching protein sequences

### ISSUE THREAD

**Issue by LifeWorks** [Nesvilab/FragPipe#1558]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/feng626/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/feng626/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Peptide Sequence | Prev AA | Next AA | Start | End | Peptide Length | Charges | Protein | Protein ID
-- | -- | -- | -- | -- | -- | -- | -- | --
EIIEQIR | R | N | 154 | 160 | 7 | 2 | sp\|P31948\|STIP1_HUMAN | P31948
CVIGGDGSLTGANIFR | L | K | 123 | 138 | 16 | 2 | sp\|Q01813\|PFKAP_HUMAN | Q01813
GITNLCVIGGDGSLTGANIFR | R | K | 118 | 138 | 21 | 2,3 | sp\|Q01813\|PFKAP_HUMAN | Q01813
ILPLVVK | K | F | 256 | 262 | 7 | 2 | sp\|Q86VP6\|CAND1_HUMAN | Q86VP6
SVLLSLK | R | Q | 236 | 242 | 7 | 2 | sp\|P09496\|CLCA_HUMAN | P09496
QIIDEAER | Q | S | 381 | 388 | 8 | 2 | sp\|P78371\|TCPB_HUMAN | P78371
SLHDALCVI | R | A | 389 | 397 | 9 | 2 | sp\|P78371\|TCPB_HUMAN | P78371
IIGELAK | R | E | 79 | 85 | 7 | 2 | sp\|Q99584\|S10AD_HUMAN | Q99584
FRDSLLR | R | S | 516 | 522 | 7 | 2,3 | sp\|P49327\|FAS_HUMAN | P49327
LLEQGIR | K | H | 437 | 443 | 7 | 2 | sp\|P49327\|FAS_HUMAN | P49327
AGALEGDLFIGPK | M | A | 49 | 61 | 13 | 2 | sp\|P61163\|ACTZ_HUMAN | P61163
SHLEILR | K | G | 165 | 171 | 7 | 2 | sp\|P00390\|GSHR_HUMAN | P00390
AELELQK | K | D | 108 | 114 | 7 | 2 | sp\|P07741\|APT_HUMAN | P07741
QIHDLVLVGGSTR | S | I | 330 | 342 | 13 | 3 | sp\|P11142\|HSP7C_HUMAN | P11142
MPLIGLGTWK | K | S | 13 | 22 | 10 | 2 | sp\|P15121\|ALDR_HUMAN | P15121
PLIGLGTWK | M | S | 14 | 22 | 9 | 2 | sp\|P15121\|ALDR_HUMAN | P15121
ELIGTCK | R | M | 320 | 326 | 7 | 2 | sp\|P18206\|VINC_HUMAN | P18206
IIGAVAK | R | V | 824 | 830 | 7 | 2 | sp\|P18206\|VINC_HUMAN | P18206
SLLYDER | K | S | 54 | 60 | 7 | 2 | sp\|P25787\|PSA2_HUMAN | P25787
GIATVLR | K | Y | 458 | 464 | 7 | 2 | sp\|Q7KZF4\|SND1_HUMAN | Q7KZF4
AAVPSLK | K | F | 42 | 48 | 7 | 2 | sp\|P00558\|PGK1_HUMAN | P00558
ALLDETK | Q | G | 326 | 332 | 7 | 2 | sp\|P04083\|ANXA1_HUMAN | P04083
CLTALVK | K | C | 263 | 269 | 7 | 2 | sp\|P04083\|ANXA1_HUMAN | P04083
LGVTVLSR | K | I | 199 | 206 | 8 | 2 | sp\|P16152\|CBR1_HUMAN | P16152
ADTPEIQR | V | I | 102 | 109 | 8 | 2 | sp\|Q14847\|LASP1_HUMAN | Q14847
ALILIPK | D | V | 443 | 449 | 7 | 2 | sp\|P40227\|TCPZ_HUMAN | P40227

</body>

</html>

There are around 135 from ~18000 peptides are not matching their protein sequences.

**Comment by danielgeiszler** [comment]
@fcyu I checked the first one, it's a I->L flattening issue

**Comment by fcyu** [comment]
It is due to the `I` and `L` interchange. When Philosopher matched the peptides to proteins, it does not distinguish `I` and `L` because they have the identical mass.

Best,

Fengchao
