### ISSUE TITLE
Claims no experiment assigned and prevents MBR, though experiment is clearly assigned

### ISSUE THREAD

**Issue by candidaorelmex** [Nesvilab/FragPipe#1563]
**- Upload your log file**
No log file has been generated, problem occurs before anything is actually run

**- Describe the issue or question:**
I've been trying to search regular proteomics data with the default workflow. As mentioned in the title, fragpipe claims that no experiment is assigned and prevents MBR, though the experiment is clearly assigned.

The files can get processed with no issues when I uncheck MBR

error message:
![image](https://github.com/Nesvilab/FragPipe/assets/90688191/e3bbabab-a423-4207-aa0c-ffe192e0a02a)

screenshot of workflow window:
![image](https://github.com/Nesvilab/FragPipe/assets/90688191/88b49ad6-8f00-4c0a-846f-abb1ff95f2e2)

Please let me know if there is any other information that you need.
Thanks for your help!

**Comment by fcyu** [comment]
Did you enable the `SpecLib`?

Thanks,

Fengchao

**Comment by candidaorelmex** [comment]
Yes, I did. After unchecking it the workflow started. WAI?

Best,
Ilja

**Comment by fcyu** [comment]
Hi Ilja,

With `SpecLib` enabled, we need to build a spectra library using all files, so we disable the experimental groups.

Best,

Fengchao
