### ISSUE TITLE
Philosopher issue - exit code 1, stopping

### ISSUE THREAD

**Issue by HaynesLabMQ** [Nesvilab/FragPipe#1564]
Hi,

I am running fragpipe v20.0 with ms-fragger 4.0, philosopher 5.1.0.
I am trying to analyse three replicates each of cryptococcus proteins from wildtype (WT) and treated (CBD). 
I have tried both default and LFQ-MBR workflows but get the same issue.
It does a lot of processing but then exits with an error message:

Cannot read file. open F:\PH010524_crypto_WT_CBD\CBD_2\.meta\db.bin: The system cannot find the file specified. 

I have hopefully attached the log file for your reference.

[log_2024-05-02_12-54-35.txt](https://github.com/Nesvilab/FragPipe/files/15183361/log_2024-05-02_12-54-35.txt)
Do you have any idea how to fix this please?

thanks

Paul A. Haynes

**Comment by fcyu** [comment]
Hi Paul,

It was because the old version of FragPipe does not support the new version of Philosopher. Could you upgrade FragPipe, MSFragger, and IonQuant?

Thanks,

Fengchao

**Comment by HaynesLabMQ** [comment]
OK. I updated all the tools recently, but not fragpipe. I just did updated them all again and it fixed the problem. All jobs done in 24 minutes.
Thanks SO much for your prompt and accurate response!

regards

Paul A. Haynes

**Comment by fcyu** [comment]
Hi Paul,

Thanks for the update. I will close this issue now, but feel free to contact us if you have any questions in the future.

Best,

Fengchao
