### ISSUE TITLE
EasyPQP not installed

### ISSUE THREAD

**Issue by JesseIL** [Nesvilab/FragPipe#1566]
I tried installing Fragpipe 20.1 on a server (Win Server 2016 OS) and everyone is fine accept for the EasyPQP. I installed Python v 3.9.13 which is recognized fine, but it gives an error when installing the EasyPQP (see attached).
<img width="1640" alt="Screenshot 2024-05-02 at 12 59 43" src="https://github.com/Nesvilab/FragPipe/assets/33388490/992fbcfe-ef06-44b8-8da2-e49bffb0c10d">
Thanks,
Yishai

**Comment by fcyu** [comment]
Hi Yishai,

It seems that the computer didn't have access to pypi.org. Maybe due to some security config?

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Yishai,

Got it. Could you download the zip file from https://github.com/grosenberger/easypqp/releases/latest, copy the file to your computer, unzip it, go to the folder, and run `python setup.py install`?

Thanks,

Fengchao

**Comment by anesvi** [comment]
I think EasyPQP requires installing some python libraries. I recall we tried doing this with someone else, and without internet EasyPQP install was still failing. Alexey

**Comment by fcyu** [comment]
Ah, yes. It requires some external packages... Then, I am not sure if there is an easy way to do that except for download and install each of them (and their dependencies) one by one.

Best,

Fengchao

**Comment by JesseIL** [comment]
OK.
What do you by install ‘each of them’? What are ’them’?


On 2 May 2024, at 16:51, Fengchao ***@***.***> wrote:



Ah, yes. It requires some external packages... Then, I am not sure if there is an easy way to do that except for download and install each of them (and their dependencies) one by one.

Best,

Fengchao

**Comment by dpolasky** [comment]
I think you can use run 'python -m pip wheel easypqp' on the command line to generate "wheel" (.whl) files for easypqp and all the packages it depends on (on the computer with internet). Then you can copy the .whl files to the other computer and run 'python -m pip install [filename].whl] on the easypqp wheel to install them. I think that should work without internet, but haven't ever tried it - you might have to install each wheel individually. 

Best,
Dan
