### ISSUE TITLE
Coverage not being output in combined_protein.tsv?

### ISSUE THREAD

**Issue by carlosg-czbiohub** [Nesvilab/FragPipe#1567]
Ive checked through several jobs we have running through our pipeline (v21) and it seems that protein coverage is no longer being output in the combined_protein.tsv file. Is this correct? I can see it in the individual protein.tsv for the same job files but it seems omitted from the combined data. I am attaching the (truncated) data tables, both combined and individual file, + log + param + workflow for a specific job but I can see it in many jobs I currently have access to and they all have the same pattern. Thanks for your help!
[random_job.zip](https://github.com/Nesvilab/FragPipe/files/15204233/random_job.zip)

**Comment by fcyu** [comment]
That's correct.

Best,

Fengchao

**Comment by carlosg-czbiohub** [comment]
Thanks for the comfirmation! The current docs still suggest it from what I can see, just a heads up.

**Comment by fcyu** [comment]
Thanks for the feedback. I think we probably should propagate the coverage to the combined protein table in the future version.

Best,

Fengchao
