### ISSUE TITLE
Contextual amino acid residues in peptides

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1568]
**- Describe the feature:**
Dear fragpipe developer team,
Thank you very much for developing this excellent tool, I would like to ask if fragpipe supports searching peptides for 3 amino acids other than the C-terminal and N-terminal? I see that Prev AA and Next AA are given in the result file, but I rather need the number of amino acids to be extended to 3. Is this something that can be set?
Best,
liangxiao

**Comment by fcyu** [comment]
If I understand your question correctly, you want to have "Prev 3 AA" and "Next 3 AA"? If yes, no, FragPipe doesn't support that.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> If I understand your question correctly, you want to have "Prev 3 AA" and "Next 3 AA"? If yes, no, FragPipe doesn't support that.如果我正确理解了您的问题，您想要“上一个 3 AA”和“下一个 3 AA”吗？如果是，则不，FragPipe不支持此功能。
> 
> Best, 最好
> 
> Fengchao 凤巢

Yes, you understood my question correctly, thanks for the answer.

Best,
liangxiao
