### ISSUE TITLE
Discrepancy between intensity and MaxLFQ intensity identification numbers using nonspecific-HLA workflow with Quantification

### ISSUE THREAD

**Issue by L3ft2di3** [Nesvilab/FragPipe#1569]
Hey,

first thank you for the awesome software and the support offered here on GitHub, keep it up!
Now to my problem:
We analyzed a small pilot project of 3 HLA peptidomic samples using the nonspecific-HLA workflow with Quantification enabled. All default settings were kept, the data were acquired on a timsTOF Flex HT.
When checking the peptide_combined.tsv I noticed 2 types of intensity columns: "Intensity" and "MaxLFQ Intensity". I am aware that MaxLFQ is a specific Quantification method, however I noticed quite extensive discrepancy regarding the peptide identifications between the two columns for one of the three samples. While 15106 non-zero values were listed in the intensity column, only 438 values were listed in MaxLFQ. For the other samples, the discrepancy was much less severe (637/438 and 504/299). Please find the combined_peptide.tsv and log file attached.

1. Do you have an explanation for this finding?
2. Which column should be considered?

[pepcombined_and_log.zip](https://github.com/Nesvilab/FragPipe/files/15249844/pepcombined_and_log.zip)

Thank you in advance and all the best,
Thorben

**Comment by fcyu** [comment]
Hi Thorben,

It should be because two of your three samples have much fewer quantified IDs(637, 504 vs 15106). MaxLFQ requires a peptide being observed in at least two samples. Thus, the number of non-zero MaxLFQ intensity was "capped" by the sample with the fewest quantified IDs.

Best,

Fengchao

**Comment by L3ft2di3** [comment]
Hey Fengchao,

thank you for the explanation, I didn't know about this precondition of MaxLFQ.

Best,
Thorben
