### ISSUE TITLE
IonQuant error

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1570]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-05-09_10-36-10.txt](https://github.com/Nesvilab/FragPipe/files/15256893/log_2024-05-09_10-36-10.txt)

**- Describe the issue or question:**
Hello, when I run IonQuant quantization, I get the following error, can you please see what's going on?

IonQuant version IonQuant-1.10.12
Batmass-IO version 1.30.0
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
System OS: Linux, Architecture: amd64
Java Info: 11.0.1, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 718 GB memory
2024-05-09 10:35:48 [WARNING] - There are only 1 experiments. Will not calculate MaxLFQ intensity.
2024-05-09 10:35:48 [INFO] - Collecting variable modifications from all psm.tsv files...
2024-05-09 10:35:48 [INFO] - Loading and indexing all psm.tsv files...
2024-05-09 10:35:49 [INFO] - Collecting all compensation voltages if applicable...
2024-05-09 10:36:09 [ERROR] - There were errors creating tables in /home/liangx/results/DRB1_1602_DRA1_0101/.: java.lang.NullPointerException: Cannot find CV -50 from all indexed CVs: [0]
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Something was wrong with your settings. Could you load `LFQ-MBR` workflow (remember to **click** "load"), and run the whole workflow?

Best,

Fengchao

**Comment by liangxiao023** [comment]
> Something was wrong with your settings. Could you load `LFQ-MBR` workflow (remember to **click** "load"), and run the whole workflow?您的设置有问题。你能加载 `LFQ-MBR` 工作流（记得点击“加载”），并运行整个工作流吗？
> 
> Best, 最好
> 
> Fengchao 凤巢

![图片](https://github.com/Nesvilab/FragPipe/assets/74865902/08b2fc46-4ca9-4bcc-8145-f5d82ae42ce7)
Is this the parameter setting you are talking about? I used this setting in my previous run

**Comment by fcyu** [comment]
No. Go to the `workflow` tab, select the `LFQ-MBR` from the dropdown menu at the top, click load.

Best,

Fengchao

**Comment by liangxiao023** [comment]
> No. Go to the `workflow` tab, select the `LFQ-MBR` from the dropdown menu at the top, click load.
> 
> Best,
> 
> Fengchao

[log_2024-05-09_11-12-37.txt](https://github.com/Nesvilab/FragPipe/files/15257192/log_2024-05-09_11-12-37.txt)
Hi, I set the parameters as you instructed and reran the whole process, but it seems that IonQuant is still giving an error.

**Comment by fcyu** [comment]
Then, it seems to be the same issue with https://github.com/Nesvilab/FragPipe/issues/1423 and https://github.com/Nesvilab/FragPipe/issues/1132. Please check your data to see if all have FAIMS and CV -50.

Best,

Fengchao
