### ISSUE TITLE
location of cache files

### ISSUE THREAD

**Issue by doug-oneal-nih** [Nesvilab/FragPipe#1571]
Following up on [issue 461](https://github.com/Nesvilab/FragPipe/issues/461), setting the java tmpdir will change where large files are located but does not affect where configuration files are read/saved. Is/can there be a setting where fragpipe-runtime.cache and fragpipe-ui.cache be stored on a per-user basis. Better would be to have them stored globally but read-only and without an warning that the user cannot update the global settings?

**Comment by fcyu** [comment]
Do these two answer your question: https://github.com/Nesvilab/FragPipe/issues/306 and https://github.com/Nesvilab/FragPipe/issues/755 ?

Thanks,

Fengchao
