### ISSUE TITLE
Without DDA data and spectral library, can we directly search for DIA data using only protein sequences in Fragpipe

### ISSUE THREAD

**Issue by shenghao003** [Nesvilab/FragPipe#1572]
Dear Nesvilab,,
      I have a question I would like to ask,Without DDA data and spectral library, can we directly search for DIA data using only protein sequences in Fragpipe? If possible, could you please provide a workflow.

Thanks,
Huang

**Comment by fcyu** [comment]
Yes, FragPipe can. Please read this tutorial https://fragpipe.nesvilab.org/docs/tutorial_DIA.html

Best,

Fengchao

**Comment by shenghao003** [comment]
Thank you for your timely feedback. Based on the manual you provided, I attempted to modify the configuration and received an error message stating "There are only DIA Quant or diaPASEF runs, but there is no spectral library provided to the DIA-NN quant.". I am running Fragpipe in a Linux environment. and the link is the workflow I used during runtime. Can you help me check where the configuration is incorrect. 
Thanks
[DIA_nolib_workflow.txt](https://github.com/Nesvilab/FragPipe/files/15282127/DIA_nolib_workflow.txt)

**Comment by fcyu** [comment]
Ah, I thought your data is from the traditional mass spectrometer that doesn't have ion mobility. For the diaPASEF data, the new version that is going to release this month will support.

Stay tuned,

Fengchao

**Comment by fcyu** [comment]
We have a new tool diaTracer that can generate pseudo-MS/MS for diaPASEF data. Coupled with FragPipe, you can analyze the diaPASEF data without any ddaPASED data as library. Please download the new versions of FragPipe from https://github.com/Nesvilab/FragPipe/releases/latest, and then download the new version of MSFragger, IonQuant, and diaTracer using FragPipe.

Best,

Fengchao

**Comment by shenghao003** [comment]
Thank you very much. I will conduct tests in the near future, and if I have any questions, I will consult you again. Thank you!
