### ISSUE TITLE
Running FP in replicate batches then doing MBR after?

### ISSUE THREAD

**Issue by carlosg-czbiohub** [Nesvilab/FragPipe#1577]
Hi,
Maybe this is already a feature and I can't find out how to set it off, but I was wondering if it was possible to search small sets of files separately and then use the intermediate or output files to do a MBR with files run separately? We run lots of files on our HPC in parallel instances of FragPipe but they only MBR within a set and we were wondering if it was possible to also do that for sets that were not processed together.

**Comment by fcyu** [comment]
I think here is the similar question and answer: https://github.com/Nesvilab/FragPipe/issues/1506

Let me know if you still have questions.

Best,

Fengchao

**Comment by carlosg-czbiohub** [comment]
Yes exactly apologies for not finding that issue!
