### ISSUE TITLE
Cannot execute program - RefreshParser.exe

### ISSUE THREAD

**Issue by mryanshi** [Nesvilab/FragPipe#1579]
**- Upload your log file**
(If a log file hasn't been gene
[log_2024-05-16_09-11-13.zip](https://github.com/Nesvilab/FragPipe/files/15331019/log_2024-05-16_09-11-13.zip)
rated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Well, this seems to be a persisting issue. I had this issue before with the same version 21.1. I managed to solve it by using the Oracle Java instead of Adoptopenjdk. The software worked well in Jan 2024. After a long break, it gave me the same error and cancelled remaining tasks (see below). I don't think it is due to the "group policy" because I've asked the IT to whitelist this RefreshParser.exe. Why this exe file randomly stored in the Temp folder? It is something to do with the Windows environment (currently Wind 10 Version 21H2) as the Uni tends to make updates? 

Thank you in advance!! 

***************************MAIN SEARCH DONE IN 0.163 MIN***************************

*******************************TOTAL TIME 0.731 MIN********************************
Process 'MSFragger' finished, exit code: 0
MSFragger move pepxml
java -cp C:\TEMP\FRAGPIPE211-0\fragpipe\lib\fragpipe-21.1.jar;/C:/TEMP/FRAGPIPE211-0/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err C:\Users\i116gast\Documents\HAPNGase\HA_PNGase.pepXML C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1\HA_PNGase.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move tsv
java -cp C:\TEMP\FRAGPIPE211-0\fragpipe\lib\fragpipe-21.1.jar;/C:/TEMP/FRAGPIPE211-0/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err C:\Users\i116gast\Documents\HAPNGase\HA_PNGase.tsv C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1\HA_PNGase.tsv
Process 'MSFragger move tsv' finished, exit code: 0
PeptideProphet [Work dir: C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1]
C:\TEMP\FRAGPIPE211-0\fragpipe\tools\philosopher_v5.1.0_windows_amd64\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 4000.0 --glyc --decoy rev_ --database C:\Users\i116gast\Documents\HAPNGase\2024-05-16-decoys-HA_ACP41105.fasta.fas --combine HA_PNGase.pepXML
Please wait. PeptideProphet is running. It can take a long time.
INFO[09:10:56] Executing PeptideProphet  v5.1.0             
Unknown file type. No file loaded.C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1/HA_PNGase.raw
Unknown file type. No file loaded.C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1/HA_PNGase.raw
 file 1: C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1\HA_PNGase.pepXML
 processed altogether 1355 results
INFO: Results written to file: C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1\interact.pep.xml

  - C:\Users\i116gast\Documents\HAPNGase\HAtest\1_1\interact.pep.xml
ERRO[09:10:58] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\54dd1e76-95e1-478c-8326-d317758b3d14\RefreshParser.exe: This program is blocked by group policy. For more information, contact your system administrator. 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks

**Comment by fcyu** [comment]
Please contact your IT department regarding the computer configuration

```shell
ERRO[09:10:58] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\54dd1e76-95e1-478c-8326-d317758b3d14\RefreshParser.exe: This program is blocked by group policy. For more information, contact your system administrator. 
```

Best,

Fengchao

**Comment by anesvi** [comment]
You can also switch to Percolator from PeptideProphet but for open searches it may not control the error rates well.

**Comment by mryanshi** [comment]
> Please contact your IT department regarding the computer configuration
> 
> ```shell
> ERRO[09:10:58] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\54dd1e76-95e1-478c-8326-d317758b3d14\RefreshParser.exe: This program is blocked by group policy. For more information, contact your system administrator. 
> ```
> 
> Best,
> 
> Fengchao

Thank you, Fengchao! Yes, I did. Our IT has whitelisted RefreshParser.exe. But the problem remained. I think this has something to do with Java or windows settings.

**Comment by mryanshi** [comment]
> You can also switch to Percolator from PeptideProphet but for open searches it may not control the error rates well.

Thank you very much! I chose Percolator instead of PeptideProphet and switched off ProteinProphet. The run was finished with no error message. But, I could not open the result with FragPipe-PDV viewer. A dialog pops up, saying something wrong with protein.fas.  See log file attached.
[log_2024-05-16_15-44-39.zip](https://github.com/Nesvilab/FragPipe/files/15336144/log_2024-05-16_15-44-39.zip)

**Comment by fcyu** [comment]
@KaiLiCn , can you take a look?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi,

I checked the log file. It looks like you didn't run the ProteinProphet. So there is no protein.fas file which is required for FragPipe-PDV. 

Good news is that I am working on the new version to remove the requirement for some cases. I will let you know when we have the new version.

Kai

**Comment by fcyu** [comment]
```shell
ERRO[17:43:09] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\37f4d741-32fc-46b0-8f9e-dbfb083bf42b\ProteinProphet.exe: This program is blocked by group policy. For more information, contact your system administrator. 
```

Same reason as your first error, but for a different executable file. 

Best,

Fengchao

**Comment by mryanshi** [comment]
> ```shell
> ERRO[17:43:09] Cannot execute program. fork/exec C:\Users\i116gast\AppData\Local\Temp\37f4d741-32fc-46b0-8f9e-dbfb083bf42b\ProteinProphet.exe: This program is blocked by group policy. For more information, contact your system administrator. 
> ```
> 
> Same reason as your first error, but for a different executable file.
> 
> Best,
> 
> Fengchao

That's correct. I wonder why such important executable files are stored under AppData\Local\Temp\...
