### ISSUE TITLE
Questions on IMQuant

### ISSUE THREAD

**Issue by zrpeak** [Nesvilab/FragPipe#158]
**Is your feature request related to a problem? Please describe.**
I was analyzing a set of timsTOF data. During quantification with IMQuant, the program met an out-of-memory error at the 10th file of the 12 and stopped.

**Describe the solution you'd like**
Is there a parameter for IMQuant to skip the quantified files (***_quant.csv files was generated) and restart from the unquantified files? It would be great if there is such an option because it can save much time.

**Comment by fcyu** [comment]
Thanks for your interest in IMQuant. This can be done by using command line. Following is an example:
```shell
java -Xmx64g -jar IMQuant.jar --psm <path to psm.tsv> --multidir <dir to the multi-experiment folder> *_quant.csv
```
There can be multiple `--psm <path to psm.tsv>` flags according to your data. IMQuant will process all `*_quant.csv` files by skipping peak tracing and quantifying.

You may get detailed help info by typing
```shell
java -jar IMQuant.jar
```

Best,

Fengchao

**Comment by fcyu** [comment]
Sorry I forgot to mention that you can find those jar files by checking the command line printed by FragPipe. Here is an example from my computer:

```shell
java -Xmx119G -cp "C:\Users\yufe\AppData\Local\Temp\fragpipe\batmass-io-1.17.0.jar;C:\Users\yufe\AppData\Local\Temp\fragpipe\imquant-1.6.2.jar" imquant.IMQuant ......
```

Best,

Fengchao

**Comment by fcyu** [comment]
You are welcome.
