### ISSUE TITLE
Empty "Gene" and "Mapped Genes" columns in psm.tsv files

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1580]
I am using FragPipe to analyze TMT data of different replicates. However, the psm.tsv files of the different replicates have empty "Gene" and "Mapped Genes" columns. I think I could solve this by changing the headers of my FASTA file, and I found your documentation explaining how to prepare a FASTA file for Philosopher: https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database. 

The section "Header formatting" contains examples of headers for Uniprot, NCBI and ENSEMBL protein sequences. However,  I am analyzing protein sequences that do not belong to any of these 3 examples. How should the headers be formatted in my case? Thank you very much for your help and support on this!

**Comment by fcyu** [comment]
>  How should the headers be formatted in my case?

You should make the header looks like from UniProt starting with `sp` or `tr`.

Best,

Fengchao

**Comment by anesvi** [comment]
Those columns show genes/proteins other than what is shown in Protein/Gene columns. Are you sure you have peptides mapping to multiple proteins in your database to begin with?

**Comment by RobAlbn** [comment]
Yes, columns "Protein" and "Mapped Proteins" have values, so I have protein/protein group for each PSM. However, the columns "Gene" and "Mapped Genes" are empty.

**Comment by RobAlbn** [comment]
Thank you very much! I'll try and follow the suggestion by @fcyu, and I'll see if the columns "Gene" and "Mapped Genes" are then filled with values.
