### ISSUE TITLE
Comparing a short BSA peptide intensity with Skyline

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1583]
Hello! 

I just made a test with a small QC file we use in our lab but I get very different intensities so maybe I'm doing something wrong. At the PSM level I obtain this intensity 1345950.8 for the monitored peptide LVNELTEFAK: 

```
190215_Q_QC01_01_32_6583a564-93dd-4500-a101-b2fe56496b25_QC01_93d2a97b9d0b35c9668663223bdef998.02742.02742.2	C:\rolivella\QC01-fragpipe-run3\1_1\interact-190215_Q_QC01_01_32_6583a564-93dd-4500-a101-b2fe56496b25_QC01_93d2a97b9d0b35c9668663223bdef998.pep.xml	LVNELTEFAK		CPFDEHVK.LVNELTEFAK.TCVADESH	K	T	10	2	758.487	1162.6222	1162.6234	582.3184	582.319	1162.6233	582.3189	0.0001	0.01476345	20.297	11.831	0.9848	2	0	66	75	1345950.8
```

At the PEPTIDE level, the same: 
```
LVNELTEFAK	K	T	66	75	10	2	1.0	10	1345950.8	MS/MS			sp|P02769|ALBU_BOVIN	P02769	ALBU_BOVIN	ALB	Albumin		
```

But with Skyline the intensity is way bigger and more or less at the same RT: 

![Screenshot from 2024-05-17 16-48-31](https://github.com/Nesvilab/FragPipe/assets/1679820/de1b5c34-00c9-417a-bcff-7ce460712d71)

Do you know what's going on? 

I put all the related files (TSVs, RAW, logs, etc.) here https://www.dropbox.com/scl/fo/iacf14g8ot61fiuvdnlpy/AIgliv4KXMqE4qeoJklpGZw?rlkey=cqg6z7gvbx2rbaljtzokyhr5y&st=6418rmcq&dl=0

Thanks!

**Comment by fcyu** [comment]
I guess different tools have different ways to calculate the intensity. The absolute values are not comparable.

Best,

Fengchao

**Comment by rolivella** [comment]
I see. And a related question: how can I know the RT of the peptide that is reported at `peptide.tsv`? I've seen also a list of PSM with RT port the peptide at `psm.tsv` but I don't know which one FragPipe use. Thanks!

**Comment by rolivella** [comment]
Yes! Founded at this column: "1_1 Apex Retention Time". Thanks.
