### ISSUE TITLE
How to fix python version N/A in Linux

### ISSUE THREAD

**Issue by huizhu2020** [Nesvilab/FragPipe#1585]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
When configuring python to /python/3.9.17/bin/python3 in Linux, I get errors python version N/A and python binary not valid. I also tried to configure it as python 3.11.1 and the same problem occurred. How to fix it? Thanks

**Comment by fcyu** [comment]
Please contact your IT department regarding the configuration of your computer and software installation.

Best,

Fengchao
