### ISSUE TITLE
Annotation file for analyzing CPTAC whole proteome data

### ISSUE THREAD

**Issue by emilyhmwong-vir** [Nesvilab/FragPipe#1586]
Hi,

I was trying to analyze the whole proteome of CPTAC LUAD samples (I am new to proteomics analysis). How can the annotation file be constructed? What kind of format does it follow? Would it be this file on the CPTAC portal: `S046_S056_BI_CPTAC3_TMT10_Label_to_Sample_Mapping_File_LUAD_v2.1-sample-annotation_plexes_01-25_20191219.xlsx`?

Best,
Emily

**Comment by fcyu** [comment]
Hi Emily,

You need to generate the annotation file for each experiment by yourself using the sample annotation information you got from CPTAC protal. Here is the tutorial in case you need it https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html

Best,

Fengchao
