### ISSUE TITLE
IonQuant java.lang.NoClassDefFoundError: Could not initialize class F$d

### ISSUE THREAD

**Issue by RTKlab-BYU** [Nesvilab/FragPipe#1589]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
IonQuant gives an error when running TMT files

[annotation_file_annotation.txt](https://github.com/Nesvilab/FragPipe/files/15418973/annotation_file_annotation.txt)
[log_2024-05-23_09-09-52.txt](https://github.com/Nesvilab/FragPipe/files/15418982/log_2024-05-23_09-09-52.txt)

I am trying Fragpipe for TMT on these public files switched to centroid mzML using MSConvet:
https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=bfd7f21d718940fdbaccc0d58ad6b

**Comment by RTKlab-BYU** [comment]
It seems that I had MS1 and Isobaric Quant checked: sorry for the bother

**Comment by fcyu** [comment]
Actually, you were using an old version (20.0) of FragPipe. It might be better to upgrade to 21.1 (also upgrading MSFragger, Philosopher, and IonQuant).

Best,

Fengchao
