### ISSUE TITLE
Crash for PSM = 0

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#1590]
Hello,

I did high-pH fractionation on my sample and ran fragpipe using non-specific HLA workflow. 
I had the impression that some fractions are empty (have no peptide identifications) and this make crash fragpipe. I'm expecting to have empty fractions because I did an extensive fractionation. 
This is not the first time I observe such behavior. Usually, I remove those file with zero identification prior to running again fragpipe or use MaxQuant. Is there a way to continue the analysis even with the presence of zero peptide identified raw files? I suppose this is the error but it could be something else. I then attached the log file. I also had the impression that the process stop or stuck during MSBoost. So I manually stopped.

I look forward to hearing back from you

Best

HuiSong
[log_2024-05-24_14-12-03.txt](https://github.com/Nesvilab/FragPipe/files/15434095/log_2024-05-24_14-12-03.txt)

**Comment by fcyu** [comment]
Hi HuiSong, 

I think we have made FragPipe not crash and continue running if there are any files with no IDs. I guess we didn't check each steps carefully. 

@yangkl96 , can you take a look? The error was from MSBooster.

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed in the new FragPipe release: https://github.com/Nesvilab/FragPipe/releases/latest

Best,

Fengchao
