### ISSUE TITLE
Error Reading PSM 

### ISSUE THREAD

**Issue by rabdo17** [Nesvilab/FragPipe#1593]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-05-24_13-17-34.txt](https://github.com/Nesvilab/FragPipe/files/15439685/log_2024-05-24_13-17-34.txt)

**- Describe the issue or question:**
Hello, I am very new to fragpipe but I am attempting to run a default closed search to simply confirm the amino acid sequence by comparing the data obtained from the mass-spec with the known sequence . I am also trying to detect and characterize post-translational modifications which include glycosylation and phosphorylation. However, when I attempt a run I get the following error message: 

"ERROR: Reading tab file, too few features present.
No-terminate flag set: ignoring error and using a pseudo-feature of zeroes.
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid.

Process 'Percolator' finished, exit code: 1
Process returned non-zero exit code, stopping"

Any assistance or suggestions on how to fix this problem would be much appreciated. When I try to do the same thing for another protein construct compared to its own known sequence I get another error which is:
"Error in the input data: too good separation between target and decoy PSMs.
No-terminate flag set: ignoring error.
Process 'Percolator' finished, exit code: 139
Process returned non-zero exit code, stopping"

The log file for this run is: 
[log_2024-05-24_13-42-43.txt](https://github.com/Nesvilab/FragPipe/files/15439832/log_2024-05-24_13-42-43.txt)
 
Thank you!

**Comment by danielgeiszler** [comment]
You don't have enough PSMs. Please check your parameters and database to make sure they match your data.

**Comment by rabdo17** [comment]
I checked the parameters and attempted to use a much broader database that I downloaded from Uniprot, but unfortunately I am still receiving an error message of: 

ERROR: Reading tab file, too few features present.
No-terminate flag set: ignoring error and using a pseudo-feature of zeroes.
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid.

with the following log file: 
[log_2024-05-24_14-30-18.txt](https://github.com/Nesvilab/FragPipe/files/15440210/log_2024-05-24_14-30-18.txt)

Is there anything that I can do to further broaden the search and allow for more potential PSMs?

**Comment by fcyu** [comment]
Hi @rabdo17 ,

May I ask

1. Is your sample digested by trypsin?
2. Is there any chemical labeling in your sample?
3. Where is your mzML file from?
4. Is your sample from human species?

Thanks,

Fengchao

**Comment by rabdo17** [comment]
1. Yes, the sample was digested by trypsin.
2. There should not be any chemical labeling, the constructs we have are pretty standard with the only thing being FLAG tags on the C and N terminals for 2 constructs respectively, and the third construct has an MBP tag. 
3.  The MZML files were generated from MSconvert. The raw Mass spec data were in the form of a .lcd file and we used MSconvert to make the file into the .mzml file. 
4. It is a human sequence that was expressed in insect cells, there might be slight variations due to expression in insect cells but the protein sequence should be very similar to the human one.

**Comment by fcyu** [comment]
Hi @rabdo17 ,

> the constructs we have are pretty standard with the only thing being FLAG tags on the C and N terminals for 2 constructs respectively, and the third construct has an MBP tag.

Sorry that I am not an expert of these things. May I ask if those tags will result in any modifications on the peptide?

> The MZML files were generated from MSconvert. The raw Mass spec data were in the form of a .lcd file and we used MSconvert to make the file into the .mzml file.

Something was wrong when parsing the mzML files, because MSFragger couldn't get the isolation windows, which was not used in DDA search at all but it implied that some parts were not well parsed. Could you share one of the mzML or .lcd file with us? I will send you a link to upload the file if you need one.

Thanks,

Fengchao

**Comment by anesvi** [comment]
I am sorry but it looks like the issue is with your data. If that's the case, this is not something we have the bandwidth to help you troubleshoot.

**Comment by rabdo17** [comment]
Hi @fcyu 
The tags should not result in any major modifications other than an additional 6-7 short peptide sequence which would be added to either the N or C terminus. 

I would be more than happy to share the MZML and .lcd files, please send a link whenever possible so I can upload them. 

Thank you.

**Comment by fcyu** [comment]
Sure, here it is https://www.dropbox.com/request/KgCormdRPnkl8cFocYfA

Thanks,

Fengchao

**Comment by rabdo17** [comment]
@fcyu 
Just uploaded one of the .mzml and .lcd files respectively,
thank you very much.

**Comment by fcyu** [comment]
Hi @rabdo17 ,

Thanks for sharing the files. I took a look at the file, and the following are my comments

1. The data was generated by a Shimadzu mass spectrometer. This is my first time seeing Shimadzu data ;) 
2. Most MS/MS scans only have a handful of peaks. The largest peak count in an MS/MS scan is 49.
3. I tried both low-resolution MS1 + low-resolution MS2 and high-resolution MS1 + low-resolution MS2. Neither them give more than 5 IDs in the parameter optimization testing.

With the above observations, I am not sure if there are any IDs in your data. May I ask if you have tried other tools and getten a good number of IDs? If yes, could you share the parameter and log file?

Thanks,

Fengchao

**Comment by rabdo17** [comment]
Hi @fcyu, 
unfortunately I have not tried tools other than the default closed search parameters in Fragpipe. It is strange that there might not be enough IDs as the peptide samples from which the data was taken were tested by running on a gel, which proved that fragmentation with trypsin did occur successfully. It might be that the parameters I am currently using are not suitable for Shimadzu data. May I ask if you have any suggestions about how I can run fragpipe successfully and avoid the aforementioned error messages given the nature of my data? 

Thank you.

**Comment by fcyu** [comment]
Hi @rabdo17 ,

Using the "Default" workflow should be OK. 

Best,

Fengchao
