### ISSUE TITLE
How can I combine whole proteome data and phosphoproteome data for site occupancy and other further analysis?

### ISSUE THREAD

**Issue by TeckYewLow** [Nesvilab/FragPipe#1594]
**- Describe the feature:**
Hi,

I have been using Fragpipe to analyze proteome and phosphoproteome data from one experiment. I am just wondering if I could combined the results from these 2 analyses?

Thank you.

**Comment by fcyu** [comment]
In the current version, no. You have to write your own script to implement that. Maybe something FragPipe-Analyst can do?

Best,

Fengchao

**Comment by TeckYewLow** [comment]
Thanks! Fengchao.


*Low Teck Yew, PhD*
Associate Professor /Senior Research Fellow
Secretary-General, Asia Oceania Human Proteome Organisation (AOHUPO)
UKM Medical Molecular Biology Institute (UMBI)
UKM Medical Center
Universiti Kebangsaan Malaysia
Jalan Yaacob Latiff
Bandar Tun Razak,
56000 Cheras
Kuala Lumpur
E-mail: ***@***.***
Web: http://www.ukm.my/umbi
