### ISSUE TITLE
'IonQuant with MBR requires designating LCMS runs to experiments' message

### ISSUE THREAD

**Issue by JesseIL** [Nesvilab/FragPipe#1596]
Hi, 
I tried setting up an experiment, and entered the experimental groups in the 'Workflow' tab but I still get the above error (see attached). 
Am I doing something wrong?
Thanks,
Yishai
<img width="1160" alt="Screenshot 2024-05-27 at 11 06 16" src="https://github.com/Nesvilab/FragPipe/assets/33388490/fb279ec4-3e7a-48a3-9ccb-491e14b84e69">

**Comment by danielgeiszler** [comment]
Hi Yishai,

Do you have SpecLib enabled?

**Comment by JesseIL** [comment]
Oh, you’re right. That was it. Thanks!


On 27 May 2024, at 12:42, Daniel Geiszler ***@***.***> wrote:



Hi Yishai,

Do you have SpecLib enabled?

**Comment by danielgeiszler** [comment]
No problem!
