### ISSUE TITLE
Error with ProteinProphet

### ISSUE THREAD

**Issue by patmartinezb** [Nesvilab/FragPipe#1598]
Hello!

I've been trying to run a single 18-plex TMT (12 fractions, acquired with FAIMS), but it keeps crashing (see log). I've tried different fastas, running it with just one fraction, different parameters... but it always crashes in the same point.

I feel like I'm overlooking something, so I'd greatly appreciate if you guys could help me.

Much appreciated!

[log_2024-05-28_12-49-15.txt](https://github.com/Nesvilab/FragPipe/files/15468068/log_2024-05-28_12-49-15.txt)

**Comment by danielgeiszler** [comment]
Hi,

Can you please upload the filelist_proteinprophet.txt ?

**Comment by patmartinezb** [comment]
[filelist_proteinprophet.txt](https://github.com/Nesvilab/FragPipe/files/15468192/filelist_proteinprophet.txt)

Sure!

**Comment by fcyu** [comment]
Hi @patmartinezb,

Some files might be messed up. Could you delete all files in `C:\Users\Patricia\Documents\Prau_lab\Masspike_fragpipe\fp_res_masspike_params\tmt02` and try again?

Thanks,

Fengchao

**Comment by patmartinezb** [comment]
Hi Fengchao,

That seemed to do the trick, thank you! Now I'm curious as to why it happened the first time around.

Thanks!
