### ISSUE TITLE
Diagnostic Ion mining crashed 

### ISSUE THREAD

**Issue by Dobrokhotov1989** [Nesvilab/FragPipe#1599]
Hi there,

I was running Diagnostic ion mining workflow that finished with the following message:

> Identifying candidate ions
> 		Building feature histograms
> Exception in thread "main" java.lang.NullPointerException
> 	at edu.umich.andykong.ptmshepherd.diagnosticmining.DiagnosticPeakPicker.process(DiagnosticPeakPicker.java:260)
> 	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:637)
> 		Testing histogram peaks for significance

After this, the processor essentially is not engaged (based on the Task Manager) and after 15 min or so of waiting, I've aborted further execution. Am I not patient enough or is it an actual bug?

I'm using an 18-core workstation with 128 GB RAM and Windows OS.

Log file:
[log_2024-05-22_16-31-50.zip](https://github.com/Nesvilab/FragPipe/files/15472984/log_2024-05-22_16-31-50.zip)

**Comment by danielgeiszler** [comment]
Hi,

No, nothing wrong on your end. It looks like it just hung when it crashed there.

Can you upload the peaksummary.annotated.tsv for me?

**Comment by danielgeiszler** [comment]
Ah, I think I see what the issue is.

WT_plus_1 seems to be a problematic sample. It has no PSMs. I think if you remove that it should run.
