### ISSUE TITLE
Skyline output folder empty

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1602]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
Hi all,
Thank you for the new updated version. I tried to use it today to generate input files for Skyline but the folder is empty. Before Skyline documentation generation was a part of Fragpipe, I had successfully imported DDA-Pasef search results into Skyline from Fragpipe to run PRM-Pasef on Brukers instruments a few months ago. I have tried several times in the past few days but couldn´t import the results in Skyline either using the interact or the pepxml files. It keeps saying that it could find the spectra for many IDs. I don´t know if this could be an issue with Skyline or Fragpipe. I used the latest version of Skyline daily and I tried both MSfragger version 22.0 and 21.1. It would be great if I could have some help from you all. Thank you so much in advance.
Best,
Trung 
**- Describe the issue or question:**

**Comment by fcyu** [comment]
Can you share the log file?

Thanks,

Fengchao

**Comment by trungttt** [comment]
Hi Fengchao,

Thanks for your quick response. Here are the log files of the last few runs that I did. I appreciate your help. Thank you so much. 
Best,
Trung 
[log_2024-05-30_08-59-11.txt](https://github.com/user-attachments/files/15510028/log_2024-05-30_08-59-11.txt)
[log_2024-05-30_10-42-16.txt](https://github.com/user-attachments/files/15510029/log_2024-05-30_10-42-16.txt)
[log_2024-05-30_16-12-46.txt](https://github.com/user-attachments/files/15510030/log_2024-05-30_16-12-46.txt)
[log_2024-05-31_00-07-16.txt](https://github.com/user-attachments/files/15510031/log_2024-05-31_00-07-16.txt)

**Comment by fcyu** [comment]
>  I used the latest version of Skyline daily and I tried both MSfragger version 22.0 and 21.1.

The log file shows that you were using Skyline version 22.2.0.351, which is an very old version. The latest daily version is 23.1.1.503. Could you upgrade our Skyline daily and try again?

You'd better to delete all files in the output folder and re-run from scratch.

Thanks,

Fengchao

**Comment by trungttt** [comment]
Hi Fengchao,
Thanks for your help. I run Fragpipe on a server but not on my PC, I didn't realize we have an older version of Skyline installed there. To be clear, Skyline (preferably the newest version) should also be installed with the latest version of Fragpipe on the same system. Is that what you meant? 
I also have some issues with unrelated problems, the last few searches I had done have crashed but I don´t know what the problem is. Could you please help me take a look at these log files if that is possible? Thank you so much.

[log_2024-05-30_16-12-46.txt](https://github.com/user-attachments/files/15518916/log_2024-05-30_16-12-46.txt)
[log_2024-05-31_00-07-16.txt](https://github.com/user-attachments/files/15518917/log_2024-05-31_00-07-16.txt)
[log_2024-05-31_10-03-23.txt](https://github.com/user-attachments/files/15518918/log_2024-05-31_10-03-23.txt)

Best,
Trung

**Comment by fcyu** [comment]
> To be clear, Skyline (preferably the newest version) should also be installed with the latest version of Fragpipe on the same system. Is that what you meant?

No, you should install Skyline in your computer by yourself.

> I also have some issues with unrelated problems, the last few searches I had done have crashed but I don´t know what the problem is. Could you please help me take a look at these log files if that is possible?

Something was wrong with your files. Please delete all files in the output folder and re-run from scratch.

Best,

Fengchao

**Comment by bsphinney** [comment]
Have the same problem, verified the latest version
[log_2024-05-31_14-28-26.txt](https://github.com/user-attachments/files/15519193/log_2024-05-31_14-28-26.txt)
 of skyline is installed. Attached my log file :)

**Comment by fcyu** [comment]
Hi @bsphinney ,

Same reason. You are using version 22.2.0.527. Could you try the latest Skyline **daily** ?

Thanks,

Fengchao

**Comment by bsphinney** [comment]
> Hi @bsphinney ,
> 
> Same reason. You are using version 22.2.0.527. Could you try the latest Skyline **daily** ?
> 
> Thanks,
> 
> Fengchao

Still empty. Maybe I did something else wrong? 
[log_2024-06-03_09-58-35.txt](https://github.com/user-attachments/files/15537192/log_2024-06-03_09-58-35.txt)

**Comment by fcyu** [comment]
Hi @bsphinney ,

The log file is not complete or truncated. Could you check if FragPipe finished successfully?

Thanks,

Fengchao

**Comment by bsphinney** [comment]
> Hi @bsphinney ,
> 
> The log file is not complete or truncated. Could you check if FragPipe finished successfully?
> 
> Thanks,
> 
> Fengchao

This is the end of it. Had it run over the weekend so not sure what happened 

[2024/05/31 20:32:01]	File fragpipe.sky opened.

**Comment by bsphinney** [comment]
> > Hi @bsphinney ,
> > The log file is not complete or truncated. Could you check if FragPipe finished successfully?
> > Thanks,
> > Fengchao
> 
> This is the end of it. Had it run over the weekend so not sure what happened
> 
> [2024/05/31 20:32:01] File fragpipe.sky opened.

I tried to run this on the command line. 

F:\Analysis_software\FragPipe-jre-22.0\fragpipe\jre\bin\java.exe -Xmx48G -cp F:\Analysis_software\FragPipe-jre-22.0\fragpipe\tools\batmass-io-1.33.4.jar;F:\Analysis_software\FragPipe-jre-22.0\fragpipe\lib\commons-lang3-3.14.0.jar;F:\Analysis_software\FragPipe-jre-22.0\fragpipe\lib\fragpipe-22.0.jar;F:\Analysis_software\FragPipe-jre-22.0\fragpipe\lib\maven-artifact-3.9.6.jar;F:\Analysis_software\FragPipe-jre-22.0\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.skyline.Skyline F:\Analysis_software\FragPipe-jre-22.0\fragpipe\tools\SkylineDailyRunner.exe F:\Brett\Spectronaut_BPS_Test\fRAGPIPE_22_TEST\try4 23.1.1.503 0 0

It responds with this and just hangs

Running command: F:\Analysis_software\FragPipe-jre-22.0\fragpipe\tools\SkylineDailyRunner.exe --timestamp --dir=F:\Brett\Spectronaut_BPS_Test\fRAGPIPE_22_TEST\try4 --batch-commands=F:\Brett\Spectronaut_BPS_Test\fRAGPIPE_22_TEST\try4\filelist_skyline.txt
[2024/06/03 14:47:54]   File fragpipe.sky opened.

Not sure if this is helpful, but thought I'd pass it on

**Comment by fcyu** [comment]
This is weird. I just tested it using one diaPASEF .d and it went well. May be due to some file system? Hard to tell.

Best,

Fengchao

**Comment by trungttt** [comment]
Hi Fengchao,
I tried different runs or removing the files with the error message. But it will just show the error message with some other files. I have tried it three times but always end up with this error, just different file names. I don´t know if you have seen this problem before. 

As for the skyline problem, I am not sure I understand you correctly. We have Fragpipe installed on our server because my searches require a lot of power and memory, I couldn´t perform the searches on my PC. Several searches on the server always return an empty folder for "Skyline output" even though the searches ended successfully.  So how will the latest version of Skyline installed on my PC help solve this problem? 

Again, I really appreciate your help. Thank you so much. 

Best,

Trung

<img width="1238" alt="Screenshot 2024-06-04 at 10 34 59" src="https://github.com/Nesvilab/FragPipe/assets/15610885/fe51b4d6-cd7a-4efc-9db8-f8d938e45abd">

**Comment by fcyu** [comment]
Hi Trung,

> But it will just show the error message with some other files. I have tried it three times but always end up with this error, just different file names. I don´t know if you have seen this problem before.

The error was because Percolator could not find the MSBooster edited pin file. Not sure of the cause. Maybe @yangkl96 can take a look.

> As for the skyline problem, I am not sure I understand you correctly. We have Fragpipe installed on our server because my searches require a lot of power and memory, I couldn´t perform the searches on my PC. Several searches on the server always return an empty folder for "Skyline output" even though the searches ended successfully. So how will the latest version of Skyline installed on my PC help solve this problem?

It won't. You need to run FragPipe on the computer with Skyline installed. 

Best,

Fengchao
