### ISSUE TITLE
Lowess fraction config

### ISSUE THREAD

**Issue by LKittinun** [Nesvilab/FragPipe#1603]
What is the lowess fraction, and how to choose the proper value?

I tried to run some old DIA files in Fragpipe but could not pass the library construction at lowess fraction = 0. Everything went well in Fragpipe 21.0 and 22.0 for lowess fraction >0.

Here are logs of lowess fraction = 0, 0.3, and 1 (3 cell lines data).

[log_2024-05-31_13-08-39-lowess0.txt](https://github.com/user-attachments/files/15509222/log_2024-05-31_13-08-39-lowess0.txt)
[log_2024-05-31_13-20-21-lowess03.txt](https://github.com/user-attachments/files/15509217/log_2024-05-31_13-20-21-lowess03.txt)
[log_2024-05-31_13-14-31-lowess1.txt](https://github.com/user-attachments/files/15509221/log_2024-05-31_13-14-31-lowess1.txt)

Regards,
Kittinun

**Comment by fcyu** [comment]
Hi Kittinun

`RT lowess fraction = 0` means letting the tool find the best lowess using cross-validation.

Best,

Fengchao

**Comment by LKittinun** [comment]
If that is the case, there should be no error presented for lowess fraction = 0, so I expected this to be an unintended behavior. Could you please take a moment to investigate the logs I've provided? (0 -> error, 0.3 and 1 worked fine.)

Sincerely,
Kittinun

**Comment by fcyu** [comment]
I have taken a brief look and had no idea with your error. Could you see if you can reproduce it? If yes, I will need your files to debug.

Thanks,

Fengchao

**Comment by LKittinun** [comment]
Absolutely, here are the files.

https://emailpsuac-my.sharepoint.com/:u:/g/personal/kittinun_l_psu_ac_th/EZaLdFuyw-1JrY7TtNs0bE0BOZUylGTGy7rAY2gMqdEPZA?e=jVrZKP

**Comment by fcyu** [comment]
Hi @LKittinun ,

Thanks for sharing the files. The last mzML, `C20_3_DIA_10mz.mzML`, was corrupted, so I tested using the first two. And it completed without any error: 
[log_2024-06-08_17-30-05.txt](https://github.com/user-attachments/files/15749716/log_2024-06-08_17-30-05.txt)

Could you re-run FragPipe using the first two mzML and see if you could reproduce the error?

Thanks,

Fengchao

**Comment by LKittinun** [comment]
Thank you very much Fengchao. I re-ran the first two files and found no error so the corrupted file might be the case. However, I still wonder why setting `lowess fraction != 0` let the third file pass the analysis if it was corrupted.

Sincerely,
Kittinun

**Comment by fcyu** [comment]
Hi Kittinun,

I am not quite sure without looking closer at the code, but I guess the `lowess fraction = 0` uses more information in the mzML file since it performs cross-validation to find the best lowess fraction.

Best,

Fengchao
