### ISSUE TITLE
failed to generate skyline document with v22.0

### ISSUE THREAD

**Issue by wtbxsjy** [Nesvilab/FragPipe#1607]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-06-04_10-05-37.txt](https://github.com/user-attachments/files/15541808/log_2024-06-04_10-05-37.txt)
[log_2024-06-04_10-08-19.txt](https://github.com/user-attachments/files/15541809/log_2024-06-04_10-08-19.txt)

**- Describe the issue or question:**
HI, fengchao, I have already finished database search with my PRM data, and trying to generate the Skyline document with Fragpipe v22.0, but the process failed on both current stable and daily-build of Skyline. 

I have tried to run the command in the log file in powershell, the error is shown as below.

```
[2024/06/04 10:16:08]   错误：值“ion 3”对于参数 --tran-product-start-ion 无效。使用 离子 1, 离子 2, 离子 3, 离子 4, 质荷比 > 母离子, （质荷比 > 母离子） - 1, （质荷比 > 母离子） - 2, （质 荷比 > 母离子） + 1, （质荷比 > 母离子） + 2 中的一个
[2024/06/04 10:16:08]   退出中...
```

Is there any clue how to fix it ?

Thanks

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchap

**Comment by fcyu** [comment]
Hi @wtbxsjy ,

Thanks for editing your previous message to include the log file. You did not run any other modules except for Skyline, which caused the error. 

```shell
CheckCentroid
java -Xmx21G -cp D:\tools\fragpipe\FragPipe-22.0\fragpipe\lib\fragpipe-22.0.jar;D:\tools\fragpipe\FragPipe-22.0\fragpipe\tools\batmass-io-1.33.4.jar com.dmtavt.fragpipe.util.CheckCentroid C:\Users\renzhe\Documents\Work\data\stroke\exosome_PRM\MS2300470001.raw 15
Done in 0.0 s.
Process 'CheckCentroid' finished, exit code: 0
Skyline [Work dir: C:\Users\renzhe\Documents\Work\data\stroke\exosome_fragpipe]
java -Xmx21G -cp D:\tools\fragpipe\FragPipe-22.0\fragpipe\tools\batmass-io-1.33.4.jar;D:\tools\fragpipe\FragPipe-22.0\fragpipe\lib\commons-lang3-3.14.0.jar;D:\tools\fragpipe\FragPipe-22.0\fragpipe\lib\fragpipe-22.0.jar;D:\tools\fragpipe\FragPipe-22.0\fragpipe\lib\maven-artifact-3.9.6.jar;D:\tools\fragpipe\FragPipe-22.0\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.skyline.Skyline D:\tools\fragpipe\FragPipe-22.0\fragpipe\tools\SkylineDailyRunner.exe C:\Users\renzhe\Documents\Work\data\stroke\exosome_fragpipe 23.1.1.503 1 0
Running command: D:\tools\fragpipe\FragPipe-22.0\fragpipe\tools\SkylineDailyRunner.exe --timestamp --dir=C:\Users\renzhe\Documents\Work\data\stroke\exosome_fragpipe --batch-commands=C:\Users\renzhe\Documents\Work\data\stroke\exosome_fragpipe\filelist_skyline.txt
Process java.lang.ProcessBuilder@7f1302d6 returned non zero value. Message:

[2024/06/04 10:03:45]	???????ion 3????????? --tran-product-start-ion ??��????? ???? 1, ???? 2, ???? 3, ???? 4, ???? > ?????, ?????? > ?????? - 1, ?????? > ?????? - 2, ?????? > ?????? + 1, ?????? > ?????? + 2 ?��????
[2024/06/04 10:03:45]	?????...
Process 'Skyline' finished, exit code: 0
```

Skyline is just a visualization tool in FragPipe. Please load one of the built-in workflows and try again.

Please read our tutorials before using FragPipe: https://fragpipe.nesvilab.org/

Best,

Fengchao
