### ISSUE TITLE
Process 'WriteSubMzml' finished, exit code: 1

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1608]
Dear Developers, 

Thanks for the recent update, I'm very excited about two-pass search, but I'm experiencing an error reported when I Write sub mzML.

Here is the message:

```

Please wait. WriteSubMzml is running. It can take a long time.
Please wait. WriteSubMzml is running. It can take a long time.
Failed to find scan name or probability threshold in /scratch/lb4489/project/MS_data/NBT_pro/fragpipe/test/twostep/trypsin_HCD/psm.tsv
Found /scratch/lb4489/project/MS_data/NBT_pro/trypsin/trypsin_HCD/20151201_alr_CompleteHumanProteome_HepG2_HCD_trypsin_fr2.mzBIN_all.
Failed to find scan name or probability threshold in /scratch/lb4489/project/MS_data/NBT_pro/fragpipe/test/twostep/trypsin_HCD/psm.tsv
Found /scratch/lb4489/project/MS_data/NBT_pro/trypsin/trypsin_HCD/20151201_alr_CompleteHumanProteome_HepG2_HCD_trypsin_fr1.mzBIN_all.
Process 'WriteSubMzml' finished, exit code: 1
Process 'WriteSubMzml' finished, exit code: 1
Process returned non-zero exit code, stopping
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

```

Here is the full log:
[slurm-7833617.txt](https://github.com/user-attachments/files/15545105/slurm-7833617.txt)

How do I fix this?

Thanks,

LeeLee

**Comment by fcyu** [comment]
Hi LeeLee,

Could you share `/scratch/lb4489/project/MS_data/NBT_pro/fragpipe/test/twostep/trypsin_HCD/psm.tsv` with us?

Thanks,

Fengchao

**Comment by lbwfff** [comment]
Hi Fengchao, thanks for your reply. I uploaded the file to dropbox and you should be able to download it through this
[link](https://www.dropbox.com/scl/fi/wk1ed77ajkhx9jbzat3st/psm.tsv?rlkey=2g164fm6bnzacn45zkfaygo3s&st=i98ty2bj&dl=0).

**Comment by fcyu** [comment]
Hi LeeLee,

Thanks for the prompt response. The psm.tsv file looks OK. Then, I have no idea about the error. Could you first run a small dataset on Windows to see if it works well? Not sure if some configurations on you Linux server caused the issue.

Thanks,

Fengchao

**Comment by lbwfff** [comment]
Hi, Fengchao. tried to analyze one of the fractions on my pc, and at least there is no error in the first-pass search.  It seems that the problem occurs only on Linux.

**Comment by lbwfff** [comment]
Hi, Fengchao. 

Are there any plans to address this issue in a future update? I apologize for any extra workload this may cause, but due to the large amount of data, it's challenging to complete the analysis on Windows. It would be incredibly helpful if this could be supported. 

Thanks a lot for considering this.

Best, 

LeeLee

**Comment by jwframe28** [comment]
I'm also having this issue, but it's slightly different:

`
WriteSubMzml [Work dir: /home/projects/elinav/johnf/ADIN_URINE/20251120_TIERED_SEARCH/first_pass/ExGF_23]
java -Xmx200G -Dlibs.bruker.dir=/home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/tools/MSFragger-4.3/ext/bruker -Dlibs.thermo.dir=/home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/tools/MSFragger-4.3/ext/thermo -cp /home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/tools/batmass-io-1.35.4.jar:/home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/lib/commons-lang3-3.17.0.jar:/home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/lib/maven-artifact-3.9.9.jar:/home/projects/elinav/johnf/miniconda3/envs/fragpipe23-1/share/fragpipe-23.1-0/lib/fragpipe-23.1.jar org.nesvilab.fragpipe.util.WriteSubMzml /home/projects/elinav/johnf/ADIN_URINE/20251120_TIERED_SEARCH/TTP/TTP_EE_25075_23_Urine_10112025_12-Nov-25_22-21-35_11092.d /home/projects/elinav/johnf/ADIN_URINE/20251120_TIERED_SEARCH/first_pass/ExGF_23/psm.tsv /home/projects/elinav/johnf/ADIN_URINE/20251120_TIERED_SEARCH/first_pass/TTP_EE_25075_23_Urine_10112025_12-Nov-25_22-21-35_11092_sub.mzML 0.5 1
Please wait. WriteSubMzml is running. It can take a long time.
Please wait. WriteSubMzml is running. It can take a long time.
Found /home/projects/elinav/johnf/ADIN_URINE/20251120_TIERED_SEARCH/TTP/TTP_EE_25075_23_Urine_10112025_12-Nov-25_22-21-35_11092.mzBIN_all.
Found 4920 scans to exclude.
java.lang.Exception: Unsupported file format: TTP_EE_25075_23_Urine_10112025_12-Nov-25_22-21-35_11092.d
        at org.nesvilab.fragpipe.util.WriteSubMzml.removeScans(WriteSubMzml.java:113)
        at org.nesvilab.fragpipe.util.WriteSubMzml.writeSubMzml(WriteSubMzml.java:95)
        at org.nesvilab.fragpipe.util.WriteSubMzml.main(WriteSubMzml.java:62)

Process 'WriteSubMzml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 95 remaining tasks


`

**Comment by fcyu** [comment]
Your issue is the same as https://github.com/Nesvilab/FragPipe/issues/1417. The "write sub mzML" isn't compatiable with timsTOF data yet.

Best,

Fengchao
