### ISSUE TITLE
Can the fragpipe analyze the dimethylation-peptides? 

### ISSUE THREAD

**Issue by ningzaizia** [Nesvilab/FragPipe#1609]
Hi fcyu,
I know the DIANN can analyze the multiplexed DIA raw data (plexDIA). Can the Fragpipe do it?
If it can, how do I configure the parameters in the Linux workflow (attachment)?
Now I want to analyze the dimethyl labeling peptides from plexDIA (light：Δ0=28.0313，intermediate：Δ4=32.0564，heavy：Δ8=36.0757) using the Fragpipe in Linux. But I don't know how to set up the parameters.
Can you help me?

![fragpipe_parameters](https://github.com/Nesvilab/FragPipe/assets/86302235/99d38017-3dd0-4936-9073-ba51b61becca)

**Comment by fcyu** [comment]
Yes, FragPipe can. We have a "plex DIA" panel in the "Quant (DIA)" tab dedicated for that. Hover over the mouse and read the tooltip for more details.

<img width="820" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/9fd7517c-e032-49a4-9e99-b76e4ce71c9f">

Best,

Fengchao

**Comment by ningzaizia** [comment]
Hi Fengchao,
I have set up the plexDIA  parameter based on the "Quant (DIA)" tab dedicated for that for my dimethyl-peptides in the FragPipe in Linux(below screenshot1) .
And the spectra library used in the analysis was constructed by AlphaPeptDeep. However, I run into a error when I run the script(screenshot2).
I don’t know if I can correctly set up the light, medium or heavy paramerters.  Can you help me?

***@***.***


***@***.***


发件人: Fengchao ***@***.***>
发送时间: 2024年6月11日 2:48
收件人: Nesvilab/FragPipe ***@***.***>
抄送: 宁小莲(Xiaolian Ning) ***@***.***>; Author ***@***.***>
主题: Re: [Nesvilab/FragPipe] Can the fragpipe analyze the dimethylation-peptides? (Issue #1609)


外部邮件/External Mail


Closed #1609<https://github.com/Nesvilab/FragPipe/issues/1609> as completed.

―

**Comment by fcyu** [comment]
Could you upload your log file by replying to https://github.com/Nesvilab/FragPipe/issues/1609

Thanks,

Fengchao

**Comment by ningzaizai** [comment]
Hi Fengchao,
Thanks your reply. The attachment is the log file. 
[log_2024-06-14_12-11-09.txt](https://github.com/user-attachments/files/15845953/log_2024-06-14_12-11-09.txt)

Best

**Comment by fcyu** [comment]
You only enabled DIA-NN but it is the last step just for quantification. You need to run all steps starting from MSFragger. Here is a brief tutorial for the label-free DIA: https://fragpipe.nesvilab.org/docs/tutorial_DIA.html. The `diaTOP_ABPP` workflow is the one you should take a look at.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fucy,
I have built a spectral library, I think I just need to provide the library and DIA data file. In addition,  I want to analyze the dimethyl-labeled DIA.
Best

**Comment by fcyu** [comment]
How did you build the library? Could you upload the log file?

It seems that there is `Dimethyl` string that is not recognized by DIA-NN, which makes sense since you didn't define it using the command line options. If you want the DIA-NN quant module to recognize `Dimethyl`, you need to type the additional command in the `opt cmds` box. Or, you could use our workflow to run from scratch.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fucy,
I used the DIANN in window to analyze the dimethyl-based DIA, it is ok by setting up modification in the command line options. but it doesn't work using the Fragpipe in linux. 
The attachment is the log file to build the library using the AlphapeptDeep. 
[logfile.zip](https://github.com/user-attachments/files/15948758/logfile.zip)

Best

**Comment by fcyu** [comment]
I believe when you raw DIA-NN in Windows, you added additional command line options to let DIA-NN recognize your custom modifications in the spectral library. You should do the similar when running FragPipe in Linux.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fucy,
if I can add the custom modifications in the FragPipe in Linux, how I do it？ Can I copy the parameter and paste it in FragPipe? Please read the screenshots. 
![DIANN_parameter](https://github.com/Nesvilab/FragPipe/assets/81786796/95bcba7d-5b00-4052-92cd-feaf68817905)
![Fragpipe_parameter](https://github.com/Nesvilab/FragPipe/assets/81786796/c521f678-23f4-49b0-861b-8a865184f481)

Best

**Comment by fcyu** [comment]
Yes, you should copy the DIA-NN's command to the `cmd line opts` box in the `Quant (DIA)` tab. And you should also uncheck `plex DIA` box, and remove all entries in the `light`, `medium`, and `heavy` boxes since you build the spectral library by your own.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Thanks for your reply.
If I use your FragPipe workflow to run dimethyl-based  DIA data from scratch, how I set up the parameters in Linux?
Now I want to built the library based on DDA fractions by FragPipe in Linux and analyze the DIA data.

Best

**Comment by fcyu** [comment]
1. Load the `DIA_SpecLib_Quant.workflow` in the `workflow` tab (remember to click "**load**").
2. Load both of your DDA and DIA data in the `input LC-MS Files` panel of the `workflow` tab.
3. Set your DDA files to the `DDA` data type, and your DIA files to the `DIA` data by using the `set DDA` and `set DIA` buttons.
4. Specify your fasta file in the `database` tab.
5. Add the dimethyl modifications to the variable modification panel in the `MSFragger` tab.
6. Enable the `plex DIA` checkbox, and configure the `light` and `heavy` labels in the `plex DIA` panel of the `Quant (DIA)` tab.
7. Go to the `result` tab, specify the path of the result folder, and click run.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fcyu,
I configured the parameters according to your recommends(read the screenshots belowed), are they correct?
![variable_modification](https://github.com/Nesvilab/FragPipe/assets/81786796/ab12d4b2-4321-4153-9db5-c37d85e7afff)
![plexDIA_parameter](https://github.com/Nesvilab/FragPipe/assets/81786796/72eb1e94-6111-4408-8b20-8f2590879b04)

Best

**Comment by fcyu** [comment]
I think the settings look good. If you are not sure, could send me the log file to take a look after FragPipe finishes.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fcyu,
Now I can run the FragPipe to analyze dimethyl-peptide DIA. But I have a little confuse that I configured the dimethyl as variable modification, but the log file reported that the 28.0313 was the fix modification(screenshot). why?
![library_log](https://github.com/Nesvilab/FragPipe/assets/81786796/743521e3-d386-4ceb-b766-045649d5164c)
Best

**Comment by ningzaizai** [comment]
The library was bulit based on the dimethyl-peptides DDA rawdata using the FragPipe and all labels(light, intermedian, heavy) were configured as variable modification.

**Comment by fcyu** [comment]
Briefly speaking, because a better approach is setting the light as fixed, and the differences between the heavy/medium and the light as variable. FragPipe optimized that for you.

Check the messages a few lines below

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/e9df1ebd-94d0-4c7c-8081-1f8dba5e8080)

Best,

Fengchao

**Comment by ningzaizai** [comment]
Hi fcyu,
I can run the Fragpipe to analyze the dimethyl-peptides DIA rawdata.  I checked the results and found the label in N-terminal is not 'label-N-L(screenshot)', but is 'UniMod:1'. Why is it such?
![label_term](https://github.com/Nesvilab/FragPipe/assets/81786796/95ab2f1c-2dcd-4e51-b790-db9ce57602cd)

Best

**Comment by fcyu** [comment]
`UniMod:1` is another modification, Acetylation. Could you check the psm.tsv and library.tsv to troubleshoot?

Thanks,

Fengchao

**Comment by ningzaizai** [comment]
The library was built  using dimethyl-labeled DDA and the generated library have the dimethyl label. 
Could it be that the N-terminus is acetylated, making it less reactive with dimethyl labeling?
![label_library](https://github.com/Nesvilab/FragPipe/assets/81786796/8a21a1e8-45f2-4550-b985-491de6462c49)

**Comment by fcyu** [comment]
I apologize for the miscommunication. I meant you could check the same peptide `ADQLTEEQIAEFK` against the `psm.tsv` and `library.tsv` to see if it indeed have acetylation on N-term. What you showed is a different peptide.

> Could it be that the N-terminus is acetylated, making it less reactive with dimethyl labeling?

Yes. That was why in the MSFragger settings, both N-term acetylation and dimethyl labeling were variable modifications (one or the other or none).

Best,

Fengchao

**Comment by ningzaizai** [comment]
Thank you for your detailed explanation. I have reviewed the labeling status of the same peptide in the psm.tsv file, as shown in the screenshot below:
![Uploading label_library.png…]()

**Comment by ningzaizai** [comment]
Thank you for your detailed explanation. I have reviewed the labeling status of the same peptide in the psm.tsv file, as shown in the screenshot below.
![Uploading label_library.png…]()

**Comment by fcyu** [comment]
The figure was not uploaded successfully.

Best,

Fengchao

**Comment by ningzaizai** [comment]
![label_information](https://github.com/Nesvilab/FragPipe/assets/81786796/36977951-1907-4def-a22a-0fdf2a03e9e2)

**Comment by fcyu** [comment]
Thanks, so there are no issues in FragPipe. Good to know.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Thank you very much for your patient and detailed explanation.

**Comment by ningzaizai** [comment]
Hi fcyu,
I now want to build a large DDA spectral library based on dimethylation for methylated DIA analysis. Should I only use dimethylation as the light label for building the spectral library in DDA, and then use Fragpipe for analysis where DIANN extracts ion chromatograms based on light, medium, and heavy label mass differences? Or do I need to label with light, medium, and heavy labels separately, collect DDA data for each, and then build the spectral library?

**Comment by fcyu** [comment]
> Should I only use dimethylation as the light label for building the spectral library in DDA, and then use Fragpipe for analysis where DIANN extracts ion chromatograms based on light, medium, and heavy label mass differences?

Do you mean only generate light dimethyl labeled DDA data? Yes, it should work. But in the MSFragger search, since you load both DDA and DIA, you still need to specify light, medium, and heavy as variable modifications.

> Or do I need to label with light, medium, and heavy labels separately, collect DDA data for each, and then build the spectral library?

Generate the DDA data with light, medium, and heavy labeling also works.

Best,

Fengchao

**Comment by fcyu** [comment]
> I understand that I should use only the light labeling sample, then collect DDA fractions. 

If you want, you could use light, medium, and heavy samples to collect DDA fractions, respectively.

> When building spectra library using Fragpipe, MSFraggers should be set to use only the modifications corresponding to the light label (n28.0313 as variable modification, K28.0313 as fixed modification), and then generate a spectral library containing only the light label.

No, you should still set all of light, medium, and heavy if you have loaded both DDA and DIA data, because there are three labels in DIA.

>  DIANN generates corresponding spectral libraries for medium and heavy labels based on the mass differences between light and medium, and heavy labels

It is not exactly how DIA-NN plexDIA works. DIA-NN only accept light-only spectral library. It did a "match-within-run" to detect the medium and heavy peptides.

>  I can simplify the experiment by using only the light label for labeling and acquiring DDA data.

You can only generate light DDA data. But remember to set all of light, medium, and heavy in the MSFragger search if you have loaded the DIA data.

Best,

Fengchao

**Comment by ningzaizai** [comment]
Thank you for your detailed reply!
I just tested the Fragpipe workflow by constructing spectra library using only the light label and only analyzing DIA data containing only the light label. However, strangely, although I only labeled with the light tag in DIA data, the results still contain information about medium and heavy labels
![DIAresult](https://github.com/Nesvilab/FragPipe/assets/81786796/c0ca229e-8b68-4f46-98fe-754812556838)

**Comment by fcyu** [comment]
Which file is the screenshot from? Do those medium and heavy peptides have non-zero intensity?

Thanks,

Fengchao

**Comment by ningzaizai** [comment]
The screenshot from the 'diann-output.tsv ' file.  
Those medium and heavy peptides have intensity.

**Comment by fcyu** [comment]
Could you upload the file?

Thanks,

Fengchao

**Comment by ningzaizai** [comment]
Hi fcyu,
I have identified the issue: when I set the cmd-opts in the workflow file to --fixed-mod Dimethyl,28.0313,nK --channels Dimethyl,0,nK,0:0; Dimethyl,4,nK,4.0251:4.0251; Dimethyl,8,nK,8.0444:8.0444, even with only one label in the DIA data, the results show three labels. However, when I set only --fixed-mod Dimethyl,28.0313,nK --channels Dimethyl,4,nK,4.0251:4.0251, the corresponding labels are only Dimethyl-n-4 or Dimethyl-K-4 modifications.
Best

**Comment by fcyu** [comment]
The first command seems to be correct and the second one seems to be wrong, that was why you didn't see the light labels.

But, you should not add any command to DIA-NN's `cmd opts` if you enabled `plex DIA`, because FragPipe have taken care of that. 

Best,

Fengchao

**Comment by ningzaizai** [comment]
This analysis is based on the spectral library I built using DDA components, analyzing another set of DIA data. Therefore, this analysis is equivalent to having an existing spectral library. So I disabled plex DIA and configured the parameter in  DIA-NN's cmd opts. Now, the result is ok.
