### ISSUE TITLE
The 2-D scan index in SCIEX data broke MSFragger and other tools.

### ISSUE THREAD

**Issue by solabthomas** [Nesvilab/FragPipe#1611]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
Dear Author, 

Hello. I am currently running on Fragpipe DIA_SpecLib_Quant workflow for my .wiff files on DIA mode. I have converted .wiff files into mzml files using MSconvert. But I encounter an error and it stopped running with the following error code:

In total 5044866 peptides.
Generated 7224922 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.15 Da.
283067836 fragments to be searched in 1 slices (4.22 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 1.43 s
	001. 20221029_CTL_10_SWATH_T1.mzBIN_calibrated 910.0 s
		[progress: 200083/200083 (100%) - 1415 spectra/s] 141.4s
		Building spectral index for the mzBIN_calibrated file 9.8 s
		Rescoring with peak tracing 13.6 s
		Picking top PSMs for each precursor 1.9 s
		Rescoring 3.5 s
		Writing results 11.0 s
	002. 20221029_CTL_10_SWATH_T2.mzBIN_calibrated 1272.5 s
		[progress: 224352/224352 (100%) - 1148 spectra/s] 195.4s
		Building spectral index for the mzBIN_calibrated file 11.1 s
		Rescoring with peak tracing 13.3 s
		Picking top PSMs for each precursor 3.6 s
		Rescoring 0.7 s
		Writing results 13.9 s
	003. 20221029_CTL_115_SWATH_T1.mzBIN_calibrated 702.0 s
		[progress: 200774/200774 (100%) - 1365 spectra/s] 147.1s
		Building spectral index for the mzBIN_calibrated file 10.3 s
		Rescoring with peak tracing 6.7 s
		Picking top PSMs for each precursor 0.8 s
		Rescoring 0.2 s
		Writing results 6.2 s
	004. 20221029_CTL_115_SWATH_T2.mzBIN_calibrated 1022.0 s
		[progress: 221199/221199 (100%) - 1092 spectra/s] 202.5s
		Building spectral index for the mzBIN_calibrated file 10.8 s
		Rescoring with peak tracing java.lang.NegativeArraySizeException: -1
	at f.a(Unknown Source)
	at f.a(Unknown Source)
	at b.d(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 682 remaining tasks

What would be the cause for this error and how could I solve for that. 

Thank you 

Yours Sincerely, 
SO

**Comment by fcyu** [comment]
Could you share `20221029_CTL_115_SWATH_T2.mzML` and your fasta file with us? Here is the link to upload the files https://www.dropbox.com/request/5IF5FvVob3lHWZKSsNL8

Thanks,

Fengchao

**Comment by solabthomas** [comment]
Dear Fengchao, 

Thank you for your prompt reply. Could I also contact you via email with this issue. Thanks

SO

**Comment by fcyu** [comment]
Sure. yufeATumich.edu replace AT with @

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi So,

Thanks for sharing the file. The error was due to how SCIEX mass spectrometry records the scans. Rather than using a 1-D index, it uses a 2-D index that breaks a lot things in the code. The following are some examples. The same "spectrum=7" exists in multiple places with different "cycle".....

```xml
<spectrum index="0" id="sample=1 period=1 cycle=1 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="139" id="sample=1 period=1 cycle=4 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="246" id="sample=1 period=1 cycle=6 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="296" id="sample=1 period=1 cycle=7 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="381" id="sample=1 period=1 cycle=9 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="501" id="sample=1 period=1 cycle=11 experiment=7" defaultArrayLength="2" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="585" id="sample=1 period=1 cycle=12 experiment=7" defaultArrayLength="1" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="675" id="sample=1 period=1 cycle=13 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="762" id="sample=1 period=1 cycle=14 experiment=7" defaultArrayLength="1" dataProcessingRef="pwiz_Reader_ABI_conversion">
<spectrum index="852" id="sample=1 period=1 cycle=15 experiment=7" defaultArrayLength="0" dataProcessingRef="pwiz_Reader_ABI_conversion">
```

Here are some discussions if you want more details https://github.com/ProteoWizard/pwiz/commit/a7042cee6181275c42b5f8cf333a3e43afb49b94#commitcomment-141999983

Best,

Fengchao
