### ISSUE TITLE
Warning: not enough target PSMs are available for regression.

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1613]
Dear author,

Hello. This time, when I ran the program, there was no error reported, but a warning appeared. After that, the program did not make any progress and has been stuck for over 6 hours. I request your assistance.

![image](https://github.com/Nesvilab/FragPipe/assets/102129816/be08b8b8-bdfa-4ced-82c2-415df77edbf2)

Best,

Anler

**Comment by yangkl96** [comment]
Hi Anler,

Are you using the most recent FragPipe version 22.0? If you are still getting this warning with the newest version, please attach your log file.

Thanks,
Kevin

**Comment by amingson** [comment]
> Hi Anler,
> 
> Are you using the most recent FragPipe version 22.0? If you are still getting this warning with the newest version, please attach your log file.
> 
> Thanks, Kevin

Thank you for your response. I'm using V21.1, and here is my log.
[log_2024-06-07_10-36-53.txt](https://github.com/user-attachments/files/15691168/log_2024-06-07_10-36-53.txt)

Best,

Anler

**Comment by yangkl96** [comment]
This is the same issue as #1590 . This is fixed in the [latest release](https://github.com/Nesvilab/FragPipe/releases/tag/22.0)

**Comment by amingson** [comment]
> This is the same issue as #1590 . This is fixed in the [latest release](https://github.com/Nesvilab/FragPipe/releases/tag/22.0)


Thank you. I've been quite busy these past few days and just now had the time to continue working. I'll try it right away.

Best，

Anler
