### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by PietroCrivello** [Nesvilab/FragPipe#1614]
[log_2024-06-06_10-51-35.txt](https://github.com/user-attachments/files/15612649/log_2024-06-06_10-51-35.txt)

Hi,

I am running Fragpipe to identify HLA peptides using a large database and group specific FDR analysis.
The workflow crashed at the MSbooster step.

Initially I thought that the issue might be related to the relatively old version of Fragpipe (v20.0), I have now run the version v22 which is giving the same issue. Can anybody help to solve this problem?

Many thanks in advance,
Pietro

**Comment by yangkl96** [comment]
Hi Pietro, 

Could you please attach one PIN file here or at this [DropBox link](https://www.dropbox.com/request/MpPF9DlpykLTC32UDwCi) for me to help troubleshoot?

Thanks,
Kevin

**Comment by PietroCrivello** [comment]
Thank you very much for your help.
I uploaded one of the pin file as requested.

I also recognized yesterday that my fasta file not clear how, included the symbol " for delimiting some of the sequence names (not sure now if it was the same even for some of the actual sequences. Can this cause the issue somehow?

**Comment by PietroCrivello** [comment]
Apparently the problem was indeed caused by the wrong sequence headers. It worked fine with a clean fasta and finished all jobs in a couple of hours.
Thanks.
