### ISSUE TITLE
MSFragger Error: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by rabdo17** [Nesvilab/FragPipe#1615]
Hello, I am attempting a basic search with a default workflow but the run halts with the following error message: "java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space"

The computer I am using has around 60 GB RAM. I attempted to keep the memory value in the workflow tab at 0 so it would perform an auto-detect and assign a safe amount of memory itself, as well as set it at 45 myself (parallelism at 15 for both). Both approaches yielded the same error message however.  I am unable to increase the computer's RAM beyond this point, so is there anyway that I can limit the memory needed whilst still successfully running the search? 

I have attached the log file below:
[log_2024-06-06_15-02-56.txt](https://github.com/user-attachments/files/15687120/log_2024-06-06_15-02-56.txt)

Thank you.

**Comment by bnewt2k** [comment]
Hi Rabdo,

What kinda of search (DIA, DDA etc..?)   How many files on what instrument platform?  With DDA library or library free?

Thanks

**Comment by fcyu** [comment]
Hi @rabdo17 ,

Your search configuration requires lots of memory 

'''Shell
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
variable_mod_03 = 79.96633 STY 3
variable_mod_10 = 203.0794 * 1
'''

I suggest you try putting 80 and 203 as mass offsets and perform a mass offset search.

Also, there are no IDs from the first search. Is that Glyco data? We have the Glyco workflows for it.

Best,

Fengchao
