### ISSUE TITLE
MSBooster shows an error for non-specific HLA peptidomics - timsTOF data

### ISSUE THREAD

**Issue by mshahbazy** [Nesvilab/FragPipe#1616]
[log_2024-06-06_18-51-57_Bjoren_AB_run1-25_06062024_test01.txt](https://github.com/user-attachments/files/15688923/log_2024-06-06_18-51-57_Bjoren_AB_run1-25_06062024_test01.txt)

Dear MSFragger team,

I encountered an error when trying to use FragPipe to search a timsTOF DDA dataset for immunopeptidomics, as follows:

**Loading predicted spectra
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 91 remaining tasks**

The log is attached. Would you please let me know how I can resolve the issue? 

Thanks and regards, 
Moh

**Comment by fcyu** [comment]
@yangkl96 , can you take a look when you have time?

Thanks,

Fengchao

**Comment by yangkl96** [comment]
Hi Moh,

Do you have any noncanonical amino acids in your protein sequences?

Thanks,
Kevin

**Comment by mshahbazy** [comment]
Hi Kevin,

Thanks for your reply.

No, only canonical amino acids. I used the standard reviewed Uniprot
proteome database.

Best,
Moh

**Comment by yangkl96** [comment]
Could you please share one pin file and the file at D:\MSFragger_Results\Asolina\Bjoren_AB_run1-25_06062024_test01\spectraRT_full.tsv? You can deposit them [here](https://www.dropbox.com/request/P3ZWJpvfjWVby357hjWK)

**Comment by mshahbazy** [comment]
Sure, I uploaded the requested files. I only uploaded one pin file; please
let me know if you need any further items.
Thanks for your help.

Best,
Moh

**Comment by yangkl96** [comment]
Thanks for sharing those. Msfragger 4.1 made some changes incompatible with the old msbooster. Could you please upgrade to the newest fragpipe release?

**Comment by mshahbazy** [comment]
OK, I tried running it with MSFragger v4.0, and it seems to be compatible now with the version of MSBosster that I am using in FragPipe v21.1. Thanks for your help.
