### ISSUE TITLE
No identifications for ETCID? 

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1617]
Hello

I'm running FragPipe 22.0 (linux container version) for analyzing this [file](https://www.dropbox.com/scl/fi/rlsprfzhvy0oxgn7g6bba/QC03_2bf4293c4d1c8c891fab774cf973f7e9.raw?rlkey=scwvcmf5iv3suh3k9c5zlq15j&st=0x5eas12&dl=0) but I get 0 identifications for proteins and peptides if the activation type is ETCID. For the other activation methods I got identifications (CID, HCD, ETHCD) but for ETCID nothing. And I know there're a lot of ETCID spectra like for example: 
![Screenshot from 2024-06-07 10-34-24](https://github.com/Nesvilab/FragPipe/assets/1679820/9e95ae81-5e67-43e4-bd8e-95807c55169d)
Am I doing something wrong? I put the activation type like `msfragger.activation_types=ECD`. And here is my workflow file: 
[fragpipe-qc03-run4-etcid.zip](https://github.com/user-attachments/files/15725612/fragpipe-qc03-run4-etcid.zip). Also the log file: [fragpipe_etcid.log.zip](https://github.com/user-attachments/files/15726101/fragpipe_etcid.log.zip)

Thanks!

**Comment by dpolasky** [comment]
Hi, 
ETciD is ETD-based and should be specified as the ETD activation type, not ECD.
Best, 
Dan

**Comment by rolivella** [comment]
So I understood that: 

 public static final String ACTIVATION_TYPE_ETD = "ETD"; --------> ETHCD
 public static final String ACTIVATION_TYPE_ECD = "ECD"; --------> ETCID

**Comment by dpolasky** [comment]
ECD is election capture dissociation and ETD is election transfer dissociation - it has nothing to do with the supplemental activation. 

It is not currently supported to distinguish between EThcD and ETciD in msfragger, but you can extract them to separate mzML files with MSConvert and search them separately that way. 

Best, 
Dan
