### ISSUE TITLE
Question about multiple space search (e.g. canonical and non-canonical)

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#1618]
Hello,

I started to use this feature for multiple space searches with Fragpipe. 
I have one question about PSM assignment and fdr calculation : "when a PSM has a hit in two different groups (Uniprot and the non-canonical FASTA), meaning a non-unique mapping, is it assigned to the Uniprot group prior to the group-specific FDR calculation?"

Many thanks in advance for your help

Best

HuiSong

**Comment by fcyu** [comment]
Hi HuiSong,

I think it depends on the configurations. If you perform a single search with the default setting and a fasta file with both canonical and non-canonical proteins, the PSM assignment won't consider the canonical vs non-canonical information. If you perform the group FDR or two-pass search, yes.

Best,

Fengchao
