### ISSUE TITLE
Combining results from different workflows

### ISSUE THREAD

**Issue by cybastam** [Nesvilab/FragPipe#1619]
I wanted to take a moment to extend my sincere gratitude for the incredible work you’ve done on MSFragger and FragPipe. The functionality and efficiency it provides have been immensely valuable to our work.

I have a question regarding the software’s capabilities: Is there a way to combine search results from different workflows, such as TMT-MS2 and TMT-MS3, and return a combined result? Any guidance or documentation on this feature would be greatly appreciated.

Thank you once again for your dedication and expertise.

**Comment by fcyu** [comment]
Hi @cybastam ,

Thanks for your kind word. 

To combine the results from two different workflows, I think you could write some small script using either Python or R to do that. You probability also want to perform some normalization during the process.

Best,

Fengchao
