### ISSUE TITLE
Problem with FreeQuant

### ISSUE THREAD

**Issue by Peer2011** [Nesvilab/FragPipe#162]
Hey guys, 
Trying your new FragPipe. Unfortunately, I got this error message during the Freequant task. Any idea how to solve this issue? Thanks for your efforts. 

Best, Peer 

Freequant [Work dir: D:\Mass_Spectrometry\Anal_Carcinoma_Projekt\MSFRAGGER_Analysis]
C:\Users\Public\Massenspektrometrie\FragPipe\philosopher.exe freequant --ptw 0.4 --tol 10 --isolated --dir D:\Mass_Spectrometry\Anal_Carcinoma_Projekt
INFO[10:10:05] Executing Label-free quantification  v2.0.0  
INFO[10:10:19] Indexing PSM information                     
INFO[10:10:19] Reading spectra and tracing peaks            
INFO[10:10:19] Processing AK_01_Z_00173_04                  
INFO[10:12:02] Processing AK_02_Z_00674_99                  
INFO[10:13:40] Processing AK_03_Z_01533_13                  
FATA[10:14:04] Cannot decode packed binary. XML syntax error on line 2178689: unexpected EOF 
Process 'Freequant' finished, exit code: 1

Process returned non-zero exit code, stopping
ReportReport [Work dir: D:\Mass_Spectrometry\Anal_Carcinoma_Projekt\MSFRAGGER_Analysis]
C:\Users\Public\Massenspektrometrie\FragPipe\philosopher.exe report

**Comment by prvst** [comment]
there seems to be something wrong with your spectra file AK_03_Z_01533_13 , could you convert it again to mzML and try one more time ?

**Comment by fcyu** [comment]
No feedback.
