### ISSUE TITLE
Python Version 

### ISSUE THREAD

**Issue by Meera-Asokan** [Nesvilab/FragPipe#1620]
Hi team,

Thank you for the amazing software.

I am trying to use DIA-NN and receiving an error that the python version is not detectable.
Can you please help resolve this.

Thank you,
Meera

[log_2024-06-07_10-55-33.txt](https://github.com/user-attachments/files/15742078/log_2024-06-07_10-55-33.txt)

**Comment by fcyu** [comment]
H Meera,

Could you open the FragPipe GUI, and configure Python path there? 

You could also do a similar configuration in command line mode. Check our tutorial https://fragpipe.nesvilab.org/docs/tutorial_headless.html

Thanks,

Fengchao

**Comment by Meera-Asokan** [comment]
Hi Fengchao,

Thank you for the quick response.
I am attaching a screenshot of the GUI here for your reference.
***@***.***

Meera

**Comment by fcyu** [comment]
I didn't see the screenshot. Could you go to https://github.com/Nesvilab/FragPipe/issues/1620 and paste it there? Replying the email won't get the attachment attached.

Thanks,

Fengchao

**Comment by Meera-Asokan** [comment]
![Fragpipe_Python_Error](https://github.com/Nesvilab/FragPipe/assets/172061382/9551ed7a-cd11-4606-9ec4-c9b5c6174959)
Please find the attached

**Comment by fcyu** [comment]
Hi @Meera-Asokan ,

Thanks for sharing the screenshots. Those two warnings indicate the cause of the error

<img width="100" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/26e3b92f-2e69-4252-b5de-27f156319fcb">

<img width="87" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/7bee5fc2-c0c6-4226-9eb2-a54877121826">


Best,

Fengchao

**Comment by Meera-Asokan** [comment]
Yes, I downloaded python through the GUI.
Can you help me with how to resolve.

Best,
Meera
________________________________

**Comment by fcyu** [comment]
What you downloaded is a Python installer. You need to installed it to your computer. We have a brief tutorial here https://fragpipe.nesvilab.org/docs/tutorial_setup_fragpipe.html#:~:text=Download/Update%E2%80%99%20button.-,Optional,-%3A%20install%2C%20update%2C%20or. But I suggest you contact your IT department to install Python for you. It is hard for us to remotely help you installing Python.

Best,

Fengchao
