### ISSUE TITLE
How to process RAW files from Astral using FragPipe?

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#1621]
**- Upload your log file**
[log_2024-06-06_19-35-08.txt](https://github.com/user-attachments/files/15751128/log_2024-06-06_19-35-08.txt)

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
I acquired two HeLa DIAs with Astral and analysed them with FragPipe (version 22).
But only about 6000 proteins were identified, which is far from the results from Nature Biotechnology.
So I wonder if my FragPipe settings are wrong.
Could you tell me how to get FragPipe to analyse the Astral data correctly?

**Comment by dpolasky** [comment]
There are many reasons why your results may differ from what others get, many of which are not related to the software. This is a forum for technical issues with our software tools, we cannot help troubleshoot a whole proteomics workflow. If you think it is a software issue, try searching the data from the paper as a starting point. 

Best,
Dan
