### ISSUE TITLE
Percolator could not find the MSBooster edited pin file.

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1622]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-06-08_23-57-38.txt](https://github.com/user-attachments/files/15754160/log_2024-06-08_23-57-38.txt)

**- Describe the issue or question:**
Hi,
I kept getting this error recently. Even if I removed that mentioned .d file from the search, then the error will just show up with another .d file. These samples are DDA runs of Immunopeptidomics samples. I am not sure why this is happening. If you guys can help me take a look, I would really appreciate it. If it is necessary, I could also send you guys these .d files. 
Best,
Trung

**Comment by trungttt** [comment]
[240408_TTT32_0_0_B721221_A02021_50_3KD3_Twin_Thunder_Slot1_20_1_11330_2.zip](https://github.com/user-attachments/files/15754176/240408_TTT32_0_0_B721221_A02021_50_3KD3_Twin_Thunder_Slot1_20_1_11330_2.zip)
Hi,
Just in case you need them, here are the pin files. Thanks for your help.
Best,
Trung

**Comment by fcyu** [comment]
It was actually not due to Percolator not finding the edited pin file. It was because Percolator could you write the files:

```shell
Exception caught: ERROR: Could not open the file 240408_TTT32_0_0_B721221_A02021_50_3KD3-Twin-Thunder_Slot1-20_1_11330_percolator_target_psms.tsv for writing. Check if the folder exists and if you have permission to write.
```

Please check your folder permission or file system.

Best,

Fengchao

**Comment by fcyu** [comment]
I saw another similar error message and it reminded me that the cause might be because the file path was too long. By default, Windows only support 256 characters, but yours has 261

```shell
E:\Trung\2024_New_unirpot_Canonical_Isoforms\240530_2024_accumulated\2024_Optimization_Part4\240408_TTT32_0_0_B721221_A02021_50_3KD3_Twin_Thunder_Slot1_20_1_11330_2\240408_TTT32_0_0_B721221_A02021_50_3KD3-Twin-Thunder_Slot1-20_1_11330_percolator_target_psms.tsv
```

You could configure the Windows register to extend the max length to ~32K. Google can show you the steps.

Best,

Fengchao

**Comment by trungttt** [comment]
Hi Fengchao,

Thank you so very much. I will check and try this. Have a great day.

Best,

Trung Trần
