### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200

### ISSUE THREAD

**Issue by naiyoubuding** [Nesvilab/FragPipe#1623]
[log_2024-06-11_08-58-34.txt](https://github.com/user-attachments/files/15780671/log_2024-06-11_08-58-34.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200

**Comment by fcyu** [comment]
Thanks for the bug reporting. 

I think we have seen at least two people reported similar error messages. @KaiLiCn , can you take a look?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi there,

Could you please share your .d file with me? You could put your file here: https://www.dropbox.com/request/LeFjdQ3ZltiBHOEW9VEx

Best,
Kai

**Comment by BrendonSeale** [comment]
Hi,

I've got the same issue. Log file attached, .d added to dropbox.

[log_2024-06-11_09-04-39.txt](https://github.com/user-attachments/files/15788334/log_2024-06-11_09-04-39.txt)




Thanks,
Brendon

**Comment by fcyu** [comment]
Hi @naiyoubuding  and @BrendonSeale ,

Kai @KaiLiCn has fixed the bug. If you want to try the pre-released version of diaTracer, please send an email to yufeATumich.edu (replace `AT` with `@`).

Thanks,

Fengchao

**Comment by BrendonSeale** [comment]
Hi,

Seems to be working now. I will let you know if the entire search completes or if there are any further errors.

Thank you!

**Comment by trungttt** [comment]
Hi all,
I am still having this error, what should I do?
Best,
Trung

**Comment by fcyu** [comment]
Released the version 1.1.5 that has this bug fixed.

Best,

Fengchao
