### ISSUE TITLE
Group FDR

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1624]
Greetings @fcyu,

I am currently testing the group_fdr feature using the guide at https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html. I created a database with PE=1 and PE=4 labels in the FASTA headers. I changed the group variable setting to "Protein evidence from FASTA file" and added "--group" to the FDR filtering. However, when I add decoy and contaminant sequences using FragPipe, an SV=1 label is being added to the FASTA headers. Example:

>rev_sp|O00762|UBE2C_HUMAN Ubiquitin-conjugating enzyme E2 C OS=Homo sapiens OX=9606 GN=UBE2C PE=1 SV=1
MPEQSTVQKSYTEQLYKKFATPNKWLEAAHTNLPSDINPEGLLSQISLLITRVDYLASWKEKLIDLCINGQTDVNPHYCPTLFKVTPANPYYGSPFELSLKYRLDEYVTGAAGHITGVWKFLNDSEPFASIGKDGSMMLTMLEQQLRKGVPGRAAGGSPEAGKRAAAVSTAAPDRNQSA
>rev_sp|O43790|KRT86_HUMAN Keratin, type II cuticular Hb6 OS=Homo sapiens OX=9606 GN=KRT86 PE=1 SV=1
MCRKCSGGCVGVRASPACANTTGVVVNSNSPVSSVRTSVVPATTSACLDGCVVGGRSSSVCVNVSGVGECLRQEEGELLRRYTAIEIDLGLKSNMVEQYERILCAMDQKAKQLAGELEALKCRADSLAAEGQQESQAVAAELKSNQCKANEVEATLRQIMRNLENIEEKTRRLTEGHRIVTAKMEECKSRYWSEAEARSRTVIDDYQAKIEAIICDMNLDRSNDLKVVVSTDSIHSQLVRIEEEYLRRLFDIEQILAEVNAELDSKRLYACDVDKKLAVFENEATARLSVEEEYKKKYGELVEQVHNLESALRGSDAEVCEAERRLTEIYGEFLPELNSQCCERNQYFQLKTELLKNQQELFRVKDIFAAFRSNLSKIQEKEEQKVCQANPDIELNLPTLLSENVSVTTICPPSPGCVGGSRYGFSRGCSGARFGGCVSHSGFGGTLGRYCSIGRYPAATICCRGPRPGCASICSFARGGCYSGCT
>rev_sp|O76009|KT33A_HUMAN Keratin, type I cuticular Ha3-I OS=Homo sapiens OX=9606 GN=KRT33A PE=2 SV=2
MYGFTNCPGCRARLGCPNSICPGTSKDCANTTACPNSPLKCDESELLSRYTNIECELRARVDLLVQYEQNQRELDSRIEALQSEVNTILRQVQSLQSSYRAESETLTNELSDRLNHQAQLEIELANVTRRLEIIEAQYSQLQESSSVVQKNLEETQTAFWQEVERRNTEVLAEYQSRTENLVQNLDVTPAADVEVNLRDGLQCRLTNVEQEHNQKLCLLEEKLSEVQAELDSRCLTLEDLIRRLGNIDSEVLQRLSLETEYKTRFDDSALKANDIQVVLRANESKSCLIKQQLEEITKFYSQYSACVLPEQQQSRERILNELEANDRELQRVKELYSALRDNLFQMTEKESGNFSGECFWNCNSVNAPINCAGPLTCGHCSPPVCPRSSCSTRCSLSPLGCSYS
>rev_sp|O76011|KRT34_HUMAN Keratin, type I cuticular Ha4 OS=Homo sapiens OX=9606 GN=KRT34 PE=1 SV=2
MNCCGKQSTGCPGCSNGSANTTACPNCPLKCDESELLSRYTNIECELRARVDLLVQYEQNQRELDCRIEALQSEVNTILSQVQSLQSSYHAESETLTNELSDRLNHQAQLEIELANVTRRLEIIEAQCSQLQESSSVVQKNLEETQTAFWQEVERRNIEVLAEYQSRTENLVQNLDVTPATDVEVNLRDGLQSRLTNVEEEHNKKLCILEERLSEVQSELDSKCLTLEDLIRRISNIDSEVLLRLSQETQYKSRFDDSALKANDINVVLRANEAKACLIKQQLEEITKFYSQYSPCLLPEQQQSREQILKELEANDRELQRVKELYSALRDNLFQMTEKESGNFSGECFWNCNSVNAPINCAGPLTYGHCSPPVCPRSSCSTRCGLSPLCCSYSMTSSCTISFCTLQQLHIHAPKLREKRQLGKIGNITPPPKAYL
>rev_sp|O76013|KRT36_HUMAN Keratin, type I cuticular Ha6 OS=Homo sapiens OX=9606 GN=KRT36 PE=1 SV=1
MLPRSQVHERSSIVKGDRIEETITRIQTGVQPAPTCPVSPVCPVPPVSPVRIVPKCATACPQPPLKCDEGELLHRYTAIEGELRAKVDLLVQYEQNQRELDCRIESLQAEVNSILCQMQALQSSYRAETEALTSELSNRMSHQAQLEIELANVTRRLEIIETQCCQLQESSSVVQQNLEETQTNFWAEVDRRNNEVLAEYQCRMDELIKNLDVPPAADVEVNLRDGLQCRLVSEVEEHNKKLCMLEEKLSEVQAELDAKCLTLEDLIRRLGNIDAEVLQRLSLETEYKTRFDDAALKANDIQLVLRANESKTLLIKQQFDEITKFYSQYDPCIYPIQFEYWEQIRSELEANERELQRVKELYNALRDNLFQMTEKESGNFSGECFWGGSGVFGSTHCESSLYSGPLCSGLGSLGSRASSIYGAAGALSPVRCSGVSRISSVRSIGGATGCLGKISGTSFTPTCTQTA
>rev_sp|O76014|KRT37_HUMAN Keratin, type I cuticular Ha7 OS=Homo sapiens OX=9606 GN=KRT37 PE=1 SV=3
MRGMSAGHGSPSGGTVPGCSPCSTCSAPTSCPNCPLKCDESELLNRYTAIENELRAKVDLLVQYEQNQRELDARIESLQEELNSILSQMQALETGYRDEAECLSNQLCDKLTHQAQREVELANVTCRLELIESQCCQLEESCSMAQLSIGESQAQFWQEVDQHNTEVMAEYQARMEGLVRNLDITPEIDLEIRFKEGLQSRLIKVEQEHNSKLSLQEEKLSEQQEALDAKALTADDLLKQTGCKDAEVLQHLSRESELKIRFDDAALKANDIQVILRANEAKSCLIKQQLEEITRFYSQYDPCVTSEHCKSRELLTTELEANEQELQRVKELYNALRDNLFKMTEKEHGNLTNKGYAGCIGINGPIHCTGPLPCATHSTPPLCLSPRGLPTSGVRVRNAHAVNALLCMSAANAEAVPQCGVDIPSVFVNRAGPAMTCGLPCSSTSYFST
>rev_sp|O76015|KRT38_HUMAN Keratin, type I cuticular Ha8 OS=Homo sapiens OX=9606 GN=KRT38 PE=1 SV=3
MFRSGTTSAGCTPGCTTCPGCSPRPACPATVCSPSTSCPNCPLKCDESELLNRYTAIENELRTKVDLLVQYEQNQRELDARIESLQEEVNSILSQMQALETGFRDEAECLSNQLCDKLTHQAQREVELANVTCRLELIESQCCQLEESCSMDQLSIGESQAQFWQEVDQRNTELMAEYQARMEGLVRNLDITPEIDLEIRLKEGLQSRLIKVEQEHNSKLSLQEEKLSEQQAELDAKALTADDLLKQTGCKDAEVLQRLSRESELKIRFDDAALKANDIQVILRANEAKSCLIKQQLEEITHFYSQYDPCVTSEHCKSRELLTAELEANEQELQRVKELYNALRDNLFQMTEKEHGNLTNEGYAGCIGINGPIHCTGPLPCATHCTPPLCLSPRGLPTSGVRVRNAHAVNALLCMPAINAEAGPQCGIDIPSVSVNRAGPAMTCGLPCSSSSYSST
>rev_sp|O77727|K1C15_SHEEP Keratin, type I cytoskeletal 15 OS=Ovis aries OX=9940 GN=KRT15 PE=2 SV=1
MIERKRSSVVKGDVSEEVNIRVKGGGGGGLSAEGTGIGAMRADQGELLSHYTAIEQELRTKIDLLMKYEQNQAEMESRLESLQAEISSILGQIQQLQAAYRGDTEALTSELGAKMSLQSQLEIELGQITRRLDTIESKSTQIMETNSAVEKNLEETKSFFWAEADRRNKEAMAEYQERMESLVRTLDVGPAADMEVNVQGALQNSFEKMEEEHNKKLYALEENLSEQIMELDTKTLTLEDLVRRLGNIDAEVSQRLAMENEYKLRFDDAALRANDIELIVRSNDIAAALIKDRLEDTTKFYPSYDREPSTPSQRQYWDRIKVELDANAEELARVKELYSALRDNLNQMTIKENGSLLGGDGGGFDGFGSGFGGGFGGGFGGGYGSGAGGGFGGGYGGASGSSVFRASSASITRSGGGGYLSGGGFGGGGALLSGGRTSSGGFTSSSTQLLTTA
>rev_sp|O82803|SRPP_HEVBR Small rubber particle protein OS=Hevea brasiliensis OX=3981 GN=SRPP PE=1 SV=1
MSAEDGFVKTIKETPLLPLYSSVRYGQETTGRVVDNYKESFYVATPVVVNAVQPVLPLKNLARWTIVAYQEAKPELNAYLAKAGEQVGTNFVSSAVDLVIRPADQAVSYTQASVQKIVPPVVGDLSTVSVDVTKDVFKVAELPIYYVPTVVTKVVNEITDVGPKLPGSIDKAYLYLTSFSDVAYVGAARVFDLYKLREEEVEEA

**_1. Will the "SV=X" labels added to my FASTA headers after PE=1 affect the group FDR calculation?
2. Can I use the MSstats file directly produced from FragPipe with the group FDR calculation?_**

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben

> 1. Will the "SV=X" labels added to my FASTA headers after PE=1 affect the group FDR calculation?

No, it won't affect the group FDR calculation.

> 2. Can I use the MSstats file directly produced from FragPipe with the group FDR calculation?

Yes, I think so.

Best,

Fengchao
