### ISSUE TITLE
FragPipe 22.0 requires EasyPQP 0.1.44+

### ISSUE THREAD

**Issue by jasminesmn** [Nesvilab/FragPipe#1625]
[log_2024-06-12_12-37-59.txt](https://github.com/user-attachments/files/15806888/log_2024-06-12_12-37-59.txt)

**Hi, I've been using FragPipe for many of my large scale proteomics and immunopeptidomics analysis and never had any trouble with errors and such. Now my lab is trying to make a switch from DDA to DIA mass spec. With version v20.0 I kept getting errors for the immunopeptidomics DIA datasets and eventually switched to DIA-NN for that. 
I have been able to finish an analysis with a large DIA cancer proteomics dataset from CPTAC using your built in  DIA_SpecLib_Quant.workflow  workflow (with v20.0) 

Now with the newest version I wanted to try the DIA immunopeptidomics again, using your new built in Nonspecific-HLA-DIA workflow for this. Unfortunately, I still get errors. It says that the pep.xml files don't exist. However, they are present in the work directory. 

What am I missing here?

Thanks for the help!**

**Comment by fcyu** [comment]
Regarding your error, could you upgrade EasyPQP to the latest version in the "config" tab of FragPipe?

Best,

Fengchao

**Comment by jasminesmn** [comment]
Thank you, that fixed it!
