### ISSUE TITLE
FragPipe could not download MSFragger with message error like the image. I manually download MSFragger and put it under Tools folder of FragPipe, but when I browse the folder by FragPipe, I could not see .jar document in MSFragger folder.

### ISSUE THREAD

**Issue by Pom22** [Nesvilab/FragPipe#1626]
![error in FragPipe](https://github.com/Nesvilab/FragPipe/assets/55813234/53138c3c-d7ca-4fc7-a590-9c41b8f9655f)

**- FragPipe could not download MSFragger with message error like the image. I manually download MSFragger and put it under Tools folder of FragPipe, but when I browse the folder by FragPipe, I could not see .jar document in MSFragger folder.Describe the issue or question:**

**Comment by fcyu** [comment]
Could you try again?

Thanks,

Fengchao

**Comment by Pom22** [comment]
Before I received your email, I downloaded MSFragger in FragPipe. But I am unsure how it worked because I also re-installed JAVA JDK and JRE.

**Comment by Pom22** [comment]
After I downloaded the MSFragger and configured it through browse in FragPipe. I navigated to ..\fragpipe 22-0\fragpipe\tools\MSFragger-4.1 and could not see MSFragger-4.1.jar. However, when I navigated to the same folder on my local disk, I could see the MSFragger-4.1.jar execution file. Sorry for asking so many questions; I am a beginner

**Comment by fcyu** [comment]
No worries. You just need to specify the folder of the tools, not the path of the jar files, in FragPipe.

Best,

Fengchao
