### ISSUE TITLE
Site specific variable mod search

### ISSUE THREAD

**Issue by Jack-Moen** [Nesvilab/FragPipe#1628]
**- Describe the feature:**
I haven't found a direct way to do this, but am trying to set certain amino acids to only be searchable with variable mods. For instance looking at methylation on say 3 lysines for one protein and 1 specific lysine on another protein.

The closest I've been able to come is using U/O/J in my fasta and setting those as variable mods with the corresponding mass shifts. The problem is I have a larger search space than those three amino acids (closer to 10 mods, but only occuring on less than 20k potential sites).

I think in my idealized request we could denote lowercase amino acids in a fasta as custom masses to set variable mods to. I understand X can be denoted as custom mod, but as far as I know this is the only letter that allows this.

**Comment by fcyu** [comment]
> The closest I've been able to come is using U/O/J in my fasta and setting those as variable mods with the corresponding mass shifts. The problem is I have a larger search space than those three amino acids (closer to 10 mods, but only occuring on less than 20k potential sites).

If you count `U` and `O`, you actually have 6: `BJXZUO`. If 6 is not enough, I am sorry that there is not much we can do for now.

Best,

Fengchao

**Comment by Jack-Moen** [comment]
I think 6 would cover most of the search space, but my understanding is that B and Z are somewhat ambiguous in the mass to begin with. Is there a way to set those as more defined? I thought B is Asp or Asn so it can already be 115 or 114. I guess I don't understand how I can set this as a variable mod to be either methyllysine or acetyllysine when it has two masses to start.

Please let me know if there is a non-standard amino acid page I am missing. I have only inferred this from other github posts.

**Comment by fcyu** [comment]
In MSFragger, `U` and `O` have non-zero masses, 150.95363 and 237.14773 respectively (I think I let MSFragger print these info in the log). `BJXZ` have zero masses. So, you could set your own masses using the statis mod options. 

Best,

Fengchao

**Comment by Jack-Moen** [comment]
Thank you Fengchao, I think understand now. I can set a fixed mod mass for BJXZ in the GUI for my base and then set the difference for each in the variable section. I appreciate the help!

**Comment by fcyu** [comment]
Correct, and you could also borrow U and O if they are not in your original fasta file. Just remember that U and O have their own masses. You need to take the subtraction.

Best,

Fengchao
