### ISSUE TITLE
Failure to propagate to DIA-NN output

### ISSUE THREAD

**Issue by BrendonSeale** [Nesvilab/FragPipe#1629]
**- Upload your log file**

[log_2024-06-13_12-31-30.txt](https://github.com/user-attachments/files/15827007/log_2024-06-13_12-31-30.txt)

**- Describe the issue or question:**

Running DIA_SpecLib_Quant_diaPASEF workflow. The process fails at (I think) the very end with the following error:

DIA-NN: Propagate information [Work dir: D:\Vesal\Fragpipe_22_diatracer_6files_diaworkflow\diann-output]
C:\fragpipe\jre\bin\java.exe -cp C:\fragpipe\tools\batmass-io-1.33.4.jar;C:\fragpipe\lib\fragpipe-20.0.jar;C:\fragpipe\lib\fragpipe-21.1.jar;C:\fragpipe\lib\fragpipe-22.0.jar;C:\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.Propagation D:\Vesal\Fragpipe_22_diatracer_6files_diaworkflow
Exception in thread "main" java.lang.NoSuchMethodError: 'java.nio.file.Path com.dmtavt.fragpipe.cmd.ToolingUtils.getUnimodOboPath(java.lang.String)'
	at com.dmtavt.fragpipe.tools.diann.Propagation.<init>(Propagation.java:79)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:68)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping

So no propagation of various columns makes it to the DIA-NN reports.

Can provide files if necessary.

Thanks,
Brendon

**Comment by fcyu** [comment]
It seems that you messed up different versions of the FragPipe according to the command:

C:\fragpipe\jre\bin\java.exe -cp C:\fragpipe\tools\batmass-io-1.33.4.jar;C:\fragpipe\lib\fragpipe-**20.0**.jar;C:\fragpipe\lib\fragpipe-**21.1**.jar;C:\fragpipe\lib\fragpipe-**22.0**.jar;C:\fragpipe\lib\fragpipe-**22.0**.jar com.dmtavt.fragpipe.tools.diann.Propagation D:\Vesal\Fragpipe_22_diatracer_6files_diaworkflow

Could you re-download FragPipe to a new folder and start from scratch?

Thanks,

Fengchao

**Comment by BrendonSeale** [comment]
Yep, that fixed it. Thanks!

**Comment by fcyu** [comment]
No problem. I will close this ticket but feel free to contact us if you have any questions in the future.

Best,

Fengchao
