### ISSUE TITLE
Incompatible options: MSFragger-DIA split database is incompatible with DIA, GPF-DIA, DIA-Lib, or DDA+ data types

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/FragPipe#1633]
Hi Fengchao,

Following your suggestion, I tried to search my semi-specific cleaved DIA raw files using the DIA_DIA-Umpire_SpecLib_Quant workflow. However, due to the large search space, I need to split the database to fit my PC memory capacity.

However, after clicking Run, an error message immediately appeared (as shown in the image), despite confirming that I loaded the DIA_DIA-Umpire_SpecLib_Quant workflow. Could you advise on the correct way to use the Split Database function in DIA searching mode?
![image](https://github.com/Nesvilab/FragPipe/assets/44239564/9ec5bf89-7da0-442a-bf57-1f7932b5e961)

Thank you!
Zeyu

**Comment by fcyu** [comment]
> Could you advise on the correct way to use the Split Database function in DIA searching mode?

It is not supported well.

Best,

Fengchao

**Comment by helloworld1631** [comment]
I see. Will this be supported in the future?

Thanks,
Zeyu

**Comment by fcyu** [comment]
Yes.
