### ISSUE TITLE
A small bug in the latest version of fragpipe

### ISSUE THREAD

**Issue by crf2213** [Nesvilab/FragPipe#1635]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

When I set the Experiment name of my raw data in the Workflow UI, it will automatic change the hyphen label to underline, for example from C-1 to C_1.

**Comment by fcyu** [comment]
It is on purpose because `-` is not allowed.

Best,

Fengchao
