### ISSUE TITLE
SpecLibGen fails in FragPipe 22.0; "A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0"

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#1636]
There is a bit of preceding detail prior to the error I am currently getting, so my apologies, but please bear with me because I was not sure what would be most relevant to you for troubleshooting. 

I upgraded to FragPipe v22.0, directed it to use my existing Anaconda3 distribution of Python (which had been working fine for FragPipe v21.0 and earlier), and tried installing EasyPQP. I got an error message that it could not install EasyPQP, because of the following issue:
"Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

Unfortunately, I do not have a log or documentation to share other than that error message. I tried to solve this myself and Google led me to a StackOverflow post suggesting I bypass the llvmlite uninstall issue and force easypqp installation with "pip install easypqp --ignore-installed llvmlite". This seemed to work in the moment, as FragPipw now recognized an installed easypqp. However, this may have caused a new issue. 

I ran a test search and everything up until SpecLibGen worked fine, when it crashed saying it couldn't find a necessary module (see log_2024-06-18_13-39-02):
"ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found."

After some further Googling and worrying I would break things further if I fiddled more, I figured I should try to start with a clean slate and I uninstalled Anaconda3 and installed Python 3.9 using the link on the FragPipe setup page. Set up FragPipe with the new Python, installed EasyPQP without issues, and picked back up on the search with building a spectral library. Now I am getting a different error, saying that there is a compatibility issue with a module. See log_2024-06-18_13-59-03 and the error pasted below: 

"A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'."

It suggested a fix by downgrading NumPy, but I didn't want to go down that road and possibly cause other bugs without checking in with you guys first. Any suggestions?

Thanks,
Josh

[log_2024-06-18_13-39-02.txt](https://github.com/user-attachments/files/15890875/log_2024-06-18_13-39-02.txt)
[log_2024-06-18_13-59-03.txt](https://github.com/user-attachments/files/15890876/log_2024-06-18_13-59-03.txt)

**Comment by fcyu** [comment]
Hi Josh,

First of all, which Python version did you use?

Thanks,

Fengchao

**Comment by jossmi** [comment]
Currently, Python 3.9. I am not exactly sure which version was used in the Anaconda3 distribution, but I'm guessing it was 3.8 or 3.9 because I had been doing FragPipe searches successfully since 2022 with that version. Since I have uninstalled it I can't check and I do not see which Python version it was in any of the logs.

**Comment by fcyu** [comment]
For the Python 3.9 one, could you downgrade numpy to 1.x? I don't think numpy 2.x is supported by most packages.

Thanks,

Fengchao

**Comment by fcyu** [comment]
```shell
pip uninstall numpy
pip install numpy<2
```

**Comment by jossmi** [comment]
Thanks, that worked!

**Comment by fcyu** [comment]
Fixed in https://github.com/grosenberger/easypqp/commit/1feec53d241877b0607faa295d080b4987b23131

The latest EasyPQP (version 0.1.45) should be good.

Best,

Fengchao
