### ISSUE TITLE
MS1 quantitation IonQuant error

### ISSUE THREAD

**Issue by Angelwitch** [Nesvilab/FragPipe#1637]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
IonQuant error
IonQuant [Work dir: D:\user\Angel\Ennio\IP\2406_DYNC1H1_GFPpulldown\GFP_OpenMod\ClosedMS1Q]
D:\software\msfragger\FragPipe-jre-20.0\fragpipe\jre\bin\java.exe -Xmx148G -Dlibs.bruker.dir="D:\software\msfragger\FragPipe-jre-20.0\fragpipe\tools\MSFragger-4.0\ext\bruker" -Dlibs.thermo.dir="D:\software\msfragger\FragPipe-jre-20.0\fragpipe\tools\MSFragger-4.0\ext\thermo" -cp "D:\software\msfragger\FragPipe-jre-20.0\fragpipe\tools\jfreechart-1.5.3.jar;D:\software\msfragger\FragPipe-jre-20.0\fragpipe\tools\batmass-io-1.28.12.jar;D:\software\msfragger\FragPipe-jre-20.0\fragpipe\tools\IonQuant-1.10.27.jar" ionquant.IonQuant --threads 42 --ionmobility 0 --minexps 1 --mbr 1 --maxlfq 1 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 10 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 1 --minisotopes 2 --minscans 3 --writeindex 0 --tp 0 --minfreq 0 --minions 2 --locprob 0.75 --uniqueness 0 --multidir . --filelist D:\user\Angel\Ennio\IP\2406_DYNC1H1_GFPpulldown\GFP_OpenMod\ClosedMS1Q\filelist_ionquant.txt --modlist D:\user\Angel\Ennio\IP\2406_DYNC1H1_GFPpulldown\GFP_OpenMod\ClosedMS1Q\modmasses_ionquant.txt
IonQuant version IonQuant-1.10.27
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
System OS: Windows Server 2012 R2, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 148 GB memory
2024-06-18 17:20:05 [WARNING] - There are only 1 experiments. Will not calculate MaxLFQ intensity.
2024-06-18 17:20:06 [INFO] - Collecting variable modifications from all psm.tsv files...
2024-06-18 17:20:06 [INFO] - Loading and indexing all psm.tsv files...
2024-06-18 17:20:07 [INFO] - Collecting all compensation voltages if applicable...
2024-06-18 17:20:27 [INFO] - B240613_08_Astral_ZC_QC_47_Ennio_DYNC1H1pulldown-GFP does not have FAIMS. If there are any other runs having FAIMS, IonQuant will crash.
2024-06-18 17:20:27 [INFO] - There is no FAIMS in the dataset.
java.lang.NoSuchMethodError: 'com.google.protobuf.Internal$ProtobufList N$j.makeMutableCopy(com.google.protobuf.Internal$ProtobufList)'
	at N$j.a(Unknown Source)
	at N$j$a.f(Unknown Source)
	at N$j$a.a(Unknown Source)
	at aa.a(Unknown Source)
	at k.a(Unknown Source)
	at k.b(Unknown Source)
	at k.a(Unknown Source)
	at ionquant.IonQuant.a(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2024-06-19_09-29-54.txt](https://github.com/user-attachments/files/15897058/log_2024-06-19_09-29-54.txt)

**Comment by fcyu** [comment]
It was due to version incompatibility. Could you upgrade FragPipe, MFragger, and diaTracer to the latest version, and try again?

Thanks,

Fengchao

**Comment by Angelwitch** [comment]
Dear Fengchao,
Thank you very much for the suggestion.
Unfortunately, the issue is not solved.
I have updated all software listed in the config tab (screenshot attached)
After update we had few more errors occurred when analysing the same raw files.

  1.  Closed search without ionQuant only run through with “Run MSbooster” unticked.
  2.  Open search stopped with a Crystal C error (log attached)
  3.  Closed search with ionQunat stopped with an ionQuant error (log attached)

Please let us know what can we do to get the software running.
Thank you very much.

Best regards

Zhuo Chen

**Comment by fcyu** [comment]
The log files were truncated by GitHub. Could you go to https://github.com/Nesvilab/FragPipe/issues/1637 and upload the files there?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Actually, no need to re-upload the log files. The untruncated one already tells the reason. You were still using the old version of FragPipe. Could you upgrade FragPipe?

```shell
Version info:
FragPipe version 20.0
MSFragger version 4.1
IonQuant version 1.10.27
Philosopher version 5.1.0
```

Best,

Fengchao
