### ISSUE TITLE
Incorrect settings broke PTMProphet

### ISSUE THREAD

**Issue by brunoalex7** [Nesvilab/FragPipe#1639]
Hi,

I am trying to use fragpipe for phosphopeptide ID for the first time. I have read the information you provided about labile and offset and made a few tries changing some parameters, but I am getting the same error every time. I am sending the log containing the error on PTMProphet and also the 3 workflows I used, so that you can help me fixing the parameters and be able to perform the searches.

Thank you in advance,
Bruno

[log_2024-06-19_14-56-33.txt](https://github.com/user-attachments/files/15901979/log_2024-06-19_14-56-33.txt)
[workflows.zip](https://github.com/user-attachments/files/15902116/workflows.zip)

**Comment by fcyu** [comment]
@anesvi @dpolasky  I think it would be nice to let FragPipe automatically refresh the command line options or update the options in the background when running the PTMProphet. I have seen several users had the similar issues. 

I will push some commits to implement the logic if this idea sounds good. 

Best,

Fengchao

**Comment by brunoalex7** [comment]
Hi Fengchao,

I did as you suggested (and I saw the parameters changing), but I am still getting the same error.

[log_2024-06-19_16-03-20.txt](https://github.com/user-attachments/files/15902838/log_2024-06-19_16-03-20.txt)

**Comment by fcyu** [comment]
Hi @brunoalex7 , could you change MSFragger tab's "report mass shift as a variable mod" to "yes, remove delta mass" as the following screenshot?

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/408a7e41-34b8-4ad4-9181-7496d1e18b5b)

In case you don't know, we have a `Labile_phospho` workflow that can do the thing that you are trying to do. After loading that workflow, do not change the parameters unless you are sure of that.

Best,

Fengchao

**Comment by brunoalex7** [comment]
Hi @fcyu,

I changed it and it still doesn't work.
However, using the default labile_phospho works, so I will stick to that.
Thank you for your support!
Best regards,
Bruno

**Comment by dpolasky** [comment]
@fcyu you mean if PTMProphet is enabled, automatically update the mod settings instead of making users click the button? That makes sense to me, especially if users who don't want it can disable it by unchecking run PTMProphet while they edit MSFragger settings (or something like that).

**Comment by fcyu** [comment]
@dpolasky , that's correct. I guess most users won't know that they need to click that button to refresh the mod setting. I was just not sure if you wanted to have a set of mods different from MSFragger's in some cases.

 Best,

Fengchao
