### ISSUE TITLE
Defining N-terminal protease

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#164]
Hi,
 I'm using some N-temrinal enzymes (lysN, LysArginase, AspN) alone or in combination with other enzymes. Can you add the possibility of using these to the GUI?

Thanks!
D.

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe and MSFragger. Currently, it doesn't support N-terminal enzymes.

Best,

Fengchao

**Comment by fcyu** [comment]
There is already this open issue (https://github.com/Nesvilab/MSFragger/issues/9).

**Comment by fcyu** [comment]
Supported in MSFragger 3.4 and FragPipe 17.0
