### ISSUE TITLE
Instrument not detected, how to specify?

### ISSUE THREAD

**Issue by BjoernZiehr** [Nesvilab/FragPipe#1642]
In the log I find:
" If a different instrument was used, specify using '--instrument' via the command line or 'instrument=' in the param file."

but I'm unsure how to do this

yes I will upload

**Comment by fcyu** [comment]
Thanks for the log file. That warning message was from MSBooster, and it should not affect your result much. I think you could ignore it for now.

```shell
2024-06-21 15:28:54 [INFO] - Could not detect instrument type. Setting to Lumos. If a different instrument was used, specify using '--instrument' via the command line or 'instrument=' in the param file.
```

Hi @yangkl96 , I thought I have encoded the instrument type in the `_uncalibrated.mzML`. Not sure why MSBooster still complains about it. We can discuss about it when you have time.

Thanks,

Fengchao

**Comment by BjoernZiehr** [comment]
Ok thank you

**Comment by yangkl96** [comment]
Yes this only matters if you are using a spectral prediction model that cares about the instrument type, but you are using DIA-NN for prediction, which does not.

@fcyu MSBooster searches for certain strings in the mzml metadata to determine instrument type. It is possible what MSFragger writes is not included in the list of strings that are considered, or not in the same metadata fields. We should discuss when I am back
