### ISSUE TITLE
How to match Chromatogram peak with Protein ID?

### ISSUE THREAD

**Issue by BjoernZiehr** [Nesvilab/FragPipe#1643]
**- Describe the feature:**
I have very few positive hits (unique labelled peptide) and I am trying to troubleshoot. It would be helpful if I could see which peaks in the chromatogram were identified. I am unsure which output files contain this information.

Thank you,

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchao

**Comment by BjoernZiehr** [comment]
Ok, here it is. I label, capture, and chemically cleave peptides with variable mod: Cys404 (light) and Cys406 (heavy). There appears to be many peptides in the initial search, but very few PSM and peptides in the final output. 
[log_2024-06-21_15-29-10.txt](https://github.com/user-attachments/files/15938031/log_2024-06-21_15-29-10.txt)

**Comment by BjoernZiehr** [comment]
Final PSMs: 2500, peptides: 2000, proteins: 900

**Comment by fcyu** [comment]
Your data has low-resolution (ion trap) MS2. I don't think it is a good idea to apply low-resolution MS2 for the phospho-enriched isotopic labelled data:
```shell
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
variable_mod_03 = 79.96633 STY 2
variable_mod_04 = -17.0265 nQnC 1
variable_mod_10 = 404.1518 C 2
variable_mod_11 = 57.0215 C 2
variable_mod_12 = 406.16415 C 2
```

Using high-resolution (Orbitrap) MS2 should significantly improve the result.

Best,

Fengchao

**Comment by BjoernZiehr** [comment]
Hmm, OK. The data isn't actually Phospho-enriched, I could remove this parameter, I think I just had it on by chance. 

Should I still acquire high res MS2 because of the 404 and 406 mass detection attempt?

**Comment by fcyu** [comment]
Thanks for the clarification. Then, I think you could remove phospho.

And yes, I suggest you still acquire high-res MS2.

Best,

Fengchao

**Comment by BjoernZiehr** [comment]
Ok, thanks a lot for the rapid feedback. I will consult and try again.
