### ISSUE TITLE
Error happened when analyzing ddaPASEF (glycopeptide) with FragPipe (V22).

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#1648]
**- Upload your log file**
[log_2024-06-26_09-48-59.txt](https://github.com/user-attachments/files/15982745/log_2024-06-26_09-48-59.txt)
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

**Comment by danielgeiszler** [comment]
Are you running this in a directory with old results?

**Comment by fcyu** [comment]
Please rerun the whole workflow from scratch.

Best,

Fengchao
