### ISSUE TITLE
Java issue error in when using Windows 10

### ISSUE THREAD

**Issue by pavanu-niper** [Nesvilab/FragPipe#165]
**Describe the bug**

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by pavanu-niper** [comment]
[log_2020-02-05_18-51-49.txt](https://github.com/Nesvilab/FragPipe/files/4162594/log_2020-02-05_18-51-49.txt)

**Comment by pavanu-niper** [comment]
[log-fragpipe-run-at_2020-02-05_18-51-45.log](https://github.com/Nesvilab/FragPipe/files/4162597/log-fragpipe-run-at_2020-02-05_18-51-45.log)
[log-fragpipe-run-at_2020-02-05_18-47-23.log](https://github.com/Nesvilab/FragPipe/files/4162598/log-fragpipe-run-at_2020-02-05_18-47-23.log)

**Comment by chhh** [comment]
Can you share the file `HCC1806_F-2_E-1_M22_5µl_I-1_01.mzML`? Looks like the file is corrupted or something.

**Comment by pavanu-niper** [comment]
Hi 

My raw data file is generated from Agilent Q-TOF with format.d. I have converted this file to .mxML.

How to share the raw data file.

**Comment by chhh** [comment]
How did you convert? With ProteoWizard's MsConvert program?
How to share a file? - Upload it somewhere, maybe to dropbox or google drive or some ftp server.

**Comment by chhh** [comment]
Or send your email to dmitriya@umich.edu and we will create a public folder for you to upload the files

**Comment by pavanu-niper** [comment]
Hi
Here is the link
https://drive.google.com/open?id=1qCNbh5yHBnRMafEqyyTjMM5U7xKSlet8

Yeah used MSConvertGUI

**Comment by chhh** [comment]
@pavanu-niper Most likely problem is file naming - file name has a greek "mu" symbol in the name. This symbol is then used inside mzml and causes problems with indexing scans inside the file.
Inserting special symbols in file names / paths is not a very good idea in general, a lot of tools won't like it.
Try renaming the original file (`μ` -> `u`), converting with msconvert, and running again.

**Comment by chhh** [comment]
This will likely be fixed in the next release though

**Comment by chhh** [comment]
@pavanu-niper Has this solved the problem?

**Comment by fcyu** [comment]
No feedback.
