### ISSUE TITLE
Browse directly to pasted folder in "Choose raw data files dialog"

### ISSUE THREAD

**Issue by chambm** [Nesvilab/FragPipe#1652]
**- Describe the feature:**
Because the dialog is the old style with the "Look in" dropdown box at the top instead of a breadcrumb textbox, there's no easy way to browse directly to a deep path. The Windows-conventional way to browse directly to a path is to type or paste it in the "File name:" text box and then press enter. Instead of trying to select the file and closing the dialog, it will browse to the folder and let the user select a file from there.

**Comment by fcyu** [comment]
I am not sure if I following it. Is that a question or a feature request? But yes, Java's native file system dialog is different from Windows'. There is no place to paste the file path, which also bother me.

Best,

Fengchao

**Comment by chambm** [comment]
A video is worth a thousand words: :)
https://github.com/Nesvilab/FragPipe/assets/5011937/7f83f9fb-5afe-4c4d-8eb3-38cce52b278f

There's got to be a way to jury-rig that behavior with Java. In the worst case, if the user selects a folder with the "Choose raw data files" dialog, you can let the native dialog close and then immediately reopen it with the chosen folder selected.

**Comment by chambm** [comment]
I just realized the Select FASTA dialog DOES work like that. So it must be you're short-circuiting that behavior in the "Choose raw files" dialog (I assume to handle Bruker directories).

**Comment by fcyu** [comment]
Wait, I think they are the same

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/96622d74-4731-4a4b-88ad-695bc3732102)
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/69368971-7a1b-4d7b-8331-297fc37523b2)

Best,

Fengchao

**Comment by chambm** [comment]
Yes but they don't behave the same. When I type a path to a folder in "Choose raw data files" and press Enter, it says: 
![image](https://github.com/Nesvilab/FragPipe/assets/5011937/6344c036-ed14-4ae9-a7c4-94d46def78e9)

**Comment by fcyu** [comment]
Wait, I think they are the same

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/de6200d0-a7f5-4079-a3c4-2d98d2dd588e)
![image](https://github.com/Nesvilab/FragPipe/assets/6926299/a710ecfe-75e8-41a6-99a6-24fb028c447d)

Best,

Fengchao

**Comment by fcyu** [comment]
Is your path folder or file? If it is a folder, than has to be `.d` because that dialog if for LC-MS "files". 

The `add folder recursively` button should bring what you want if you want to put a folder path.

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/119ccc38-918d-4b73-9efe-43a82d52ec69)


Best,

Fengchao

**Comment by chambm** [comment]
Entering the full path to a file and pressing Enter selects the file and closes the dialog. That's expected and correct. It's entering a folder so I can select some RAW files in it that isn't working. Perhaps only do the "If you are analzying timsTOF" behavior if the folder ends in `.d`?

**Comment by fcyu** [comment]
Hi @chambm , 

Guo Ci @guoci has fixed it in https://github.com/Nesvilab/FragPipe/pull/1653 . Let me know if you want to test the pre-released version or have any questions.

Thanks,

Fengchao
