### ISSUE TITLE
FragPipe-PDV viewer "Invalid spectrum file path, please check it"

### ISSUE THREAD

**Issue by rugenni** [Nesvilab/FragPipe#1655]
[log_2024-07-01_16-12-19.zip](https://github.com/user-attachments/files/16054239/log_2024-07-01_16-12-19.zip)

Hi, 

I processed three timsTOF .d files with FragPipe 22 using the LFQ-phospho workflow. When I try to open Fragpipe-PDV I get the error message "Invalid spectrum file path, please check it". All files are located within the same folder, I did not move any file. I noticed some warnings during PTMProphet like "chmod 664 interact-Steffi_A_rank5.mod.pep.xml" failed: Operation not permitted". Is this a known problem? (I ran FragPipe on a Windows 10 PC as Administrator). 

Many thanks,
Nils

**Comment by fcyu** [comment]
@KaiLiCn , could you take a look when you get a chance? 

Note that it is a DDA+ search with the ddaPASEF data. PDV was supposed to look at the `*_uncalibrated.mzML` files, and there were multiple ranks per scan. 

Best,

Fengchao

**Comment by KaiLiCn** [comment]
Hi Nils,

Could you also share the `Fragpipe.workflow` file inside your result folder with me?

Kai

**Comment by rugenni** [comment]
Hi Kai, 

here it comes: 
[fragpipe_workflow.zip](https://github.com/user-attachments/files/16054868/fragpipe_workflow.zip)

Thanks,
Nils

**Comment by KaiLiCn** [comment]
Hi Nils,

I fixed the bug. Could you try the latest version of FragPipe-PDV? You could find it here: https://github.com/Nesvilab/FragPipe-PDV/tree/V1.2.2 . There is a `README` showing how to update it mannually inside FragPipe. We also update a tutorial file. You could find everything there.

Let me know if you have any iusse when you update it.

Kai

**Comment by rugenni** [comment]
Hi Kai and Fengchao, 

thank you very much for your quick help, everything is working now. 

Best,
Nils

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/FragPipe/commit/9c205796f647e03daab587258313c46afc0503ea
