### ISSUE TITLE
Difficulty in analyzing DIA data using DIA-NN

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#1656]
**- Upload your log file**
I am trying to analyze DIA data but the analysis crashes before running DIA-NN for quantification due to an issue with the spectral library.

**- Describe the issue or question:**

[log_2024-07-02_09-17-38.txt](https://github.com/user-attachments/files/16063010/log_2024-07-02_09-17-38.txt)

**Comment by fcyu** [comment]
Have you configured Python, installed EasyPQP, and enabled the spectral library building module?

Thanks,

Fengchao
