### ISSUE TITLE
MSBooster failed

### ISSUE THREAD

**Issue by WShaoLab** [Nesvilab/FragPipe#1657]
**- Upload your log file
[log_2024-06-24_14-08-03.txt](https://github.com/user-attachments/files/16063749/log_2024-06-24_14-08-03.txt)
**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Hi

I ran fragpipe using the DIA_DIA-Umpire_SpecLib_Quant workflow in my windows server. But it failed when running MSBooster.  I am writing to ask for help. Thanks very much!

Best wishes
Xiaoxiang

**Comment by yangkl96** [comment]
MSBooster from FragPipe 20 is incompatible with MSFragger 4.1. Please download the most recent FragPipe 22.0

**Comment by WShaoLab** [comment]
Oh, Yes! I figure this out. Thanks a lot!
