### ISSUE TITLE
Error "java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by VirginiaCarayol** [Nesvilab/FragPipe#1659]
Good morning,

As I show in the attached log file, I get the error "java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space".

[log_2024-07-01_17-12-54.txt](https://github.com/user-attachments/files/16065194/log_2024-07-01_17-12-54.txt)

I have tried setting Workflow > Global settings, RAM = 0 (auto) and Parallelism = 6, but the error persists. Also, I have tried splitting the database, but it is not big enough. I have also tried indicating in MSFragger > Common Options > Calibration and optimizations = None, but the error continues.

I have read in other answers that it may be due to the free RAM memory of the computer, but this is approximately 50.8 GB. On the other hand, I have also increased the Java memory on Windows, but the error persists.

![error3](https://github.com/Nesvilab/FragPipe/assets/155262131/642e6037-2cb1-44d3-8481-f653940c1270)
![error5](https://github.com/Nesvilab/FragPipe/assets/155262131/0c51cdae-612f-47e1-a5fc-2e2214caf36c)
![error4](https://github.com/Nesvilab/FragPipe/assets/155262131/b159849d-2e1b-47a4-a159-62a22e55fad7)

How can I solve that?

Thanks in advance,

Virginia Carayol Gordillo

**Comment by fcyu** [comment]
> I have tried setting Workflow > Global settings, RAM = 0 (auto) and Parallelism = 6, but the error persists. Also, I have tried splitting the database, but it is not big enough. I have also tried indicating in MSFragger > Common Options > Calibration and optimizations = None, but the error continues.

Increase the `split database` and set `calibration and optimization` to `none` should work.

Best,

Fengchao
