### ISSUE TITLE
Fragpipe runs PTMShepherd without it being enabled and then results in exit code 1?

### ISSUE THREAD

**Issue by vikascinderbio** [Nesvilab/FragPipe#1660]
[log_2024-07-03_05-17-39.txt](https://github.com/user-attachments/files/16084990/log_2024-07-03_05-17-39.txt)

**- Describe the issue or question:**

After running through most of a search, fragpipe opened PTMShepherd and ran a series of commands culminating in exit code "1". The thing is, PTMShepherd was not enabled for the search. Please advise

**Comment by fcyu** [comment]
It is because one of the glycan module was enabled accidently. Could you go to the `Glyco` tab and disable everything there?

Thanks,

Fengchao
