### ISSUE TITLE
SpecLibGen nonzero exit code 

### ISSUE THREAD

**Issue by jekiert2** [Nesvilab/FragPipe#1662]
[log_2024-07-03_11-08-28.zip](https://github.com/user-attachments/files/16088370/log_2024-07-03_11-08-28.zip)

**- Describe the issue or question:**
Hello. I have an mTB sample that I ran with DIA and each time it gets to the spectral library generation it gives me an error message "Library not generated, not enough peptides could be found for alignment.". At first I thought my sample did not have enough quality peptides and I re ran the sample with 4x the amount and there's definitely peptide in there just by manually checking the spectra and the heatmaps. I also tried running my sample against the mTB FASTA and human FASTA and both failed. 

How can I resolve this issue?

**Comment by fcyu** [comment]
The log shows that there are only 1 peptide in your sample. Could you double check your sample prep and search settings?

```shell
ime="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 PSMs" decoy=0 threshold=0.873811 total=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 Peptides" decoy=0 threshold=0.873811 total=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 Ions" decoy=0 threshold=0.873811 total=1
time="10:58:32" level=info msg="Protein inference results" decoy=0 target=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 Proteins" decoy=0 threshold=0.8729 total=1
time="10:58:32" level=info msg="2D FDR estimation: Protein mirror image" decoy=1 target=1
time="10:58:32" level=info msg="Second filtering results" ions=1 peptides=1 psms=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 PSMs" decoy=0 threshold=0.873811 total=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 Peptides" decoy=0 threshold=0.873811 total=1
time="10:58:32" level=info msg="Converged to 0.00 % FDR with 1 Ions" decoy=0 threshold=0.873811 total=1
```

Thanks,

Fengchao
