### ISSUE TITLE
Extracting precursor quantity when multiple PSMs present

### ISSUE THREAD

**Issue by candidaorelmex** [Nesvilab/FragPipe#1664]
Hi, I would like to extract a single quantification value for a given precursor in a raw file where said precursor has been identified multiple times (DDA raw file analyzed with DDA+, FDR = 1%).

I noticed that often, PSMs of the same precursor matched to several scans have the same intensity value but not always. 
I was going to just sum up all intensity values of all PSMs in the run that represent said precursor, is this the right way to extract a single quantification value for a given precursor from the psm.tsv output or is there better way?

Thanks in advance.

Best,
Ilja

**Comment by fcyu** [comment]
If a precursor is Chimeric, each of its PSM's intensity is from the same MS1 XIC, so they will have similar values. If you want to know the intensity of that precursor, you could take the maximum of all PSMs' intensities. Note that you need to make sure that the PSMs indeed from the same precursor with a narrow m/z and RT.

Best,

Fengchao

**Comment by candidaorelmex** [comment]
Ok, so to assess the quantity of a precursor in an entire run it is best to just take the highest intensity of all PSMs for that precursor in a reasonable m/z and RT window. 

To then get back to a peptide quantity for that run I just sum up all best PSM intensities for all precursors that belong to a single peptide?

Thanks a lot!

Best,
Ilja

**Comment by fcyu** [comment]
> To then get back to a peptide quantity for that run I just sum up all best PSM intensities for all precursors that belong to a single peptide?

To get the peptide-level intensity, you could sum all **precursors'/ions'** intensities or using MaxLFQ. IonQuant generates such report you want if you are using the LFQ-MBR workflow.

Best,

Fengchao
