### ISSUE TITLE
Get FDR

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1666]
**- Describe the feature:**

Dear author,

Could you please advise where or how I can obtain the FDR information corresponding to each peptide? Also, how can I obtain all unfiltered peptide information?

Best regards,

Anler

**Comment by fcyu** [comment]
> Could you please advise where or how I can obtain the FDR information corresponding to each peptide? 

Reported peptides have been filtered with the pre-definded FDR threshold. There is no FDR information in the report.

> Also, how can I obtain all unfiltered peptide information?

There are several layers of filtering: Percolator or PeptideProphet has min prob filter, and Philosopher has psm, ion, pep, prot FDR, and also min prob: https://github.com/Nesvilab/philosopher/wiki/Filter. To get unfiltered result, please change each of them.

Best,

Fengchao
