### ISSUE TITLE
Mapped Proteins

### ISSUE THREAD

**Issue by shenghao003** [Nesvilab/FragPipe#1667]
Dear Fragpipe Team：
       We recently did a test（LFQ）and searched the database together for two proteins with the same amino acid sequence. As a result, the two proteins had a common peptide segment and were identified. One of the protein IDs was found in the Protein column of the peptide.tsv table. , another protein ID is in the Mapped Proteins column. How should we understand the results of the Mapped Proteins column? Does this mean that the protein has also been identified? On the other hand, we found that the proteins in the Mapped Proteins column cannot be found in the protein.tsv table. Could you please tell me the reason?

Thanks.

**Comment by fcyu** [comment]
The "mapped proteins" are the proteins that contain the peptide but not "as good as" the protein in the "Protein" column. The "Protein" column should have more peptides identified than the "mapped proteins". 

>  Does this mean that the protein has also been identified? On the other hand, we found that the proteins in the Mapped Proteins column cannot be found in the protein.tsv table. 

"Mapped proteins" can not be treated as identified. Only proteins in the "Protein" column are. That is also why the "mapped proteins" are not in the protein.tsv table.

Best,

Fengchao

**Comment by shenghao003** [comment]
Thank you for your prompt reply. As shown in the figure below, I found two proteins Q0QF43 and P04636 in the peptide.tsv table. Their identified amino acid sequences are the same, but only P04636 can be found in protein.tsv.
![图片](https://github.com/Nesvilab/FragPipe/assets/47234121/95e30c8b-7af3-4772-8425-318d0bfa84da)
In addition, I would like to confirm with you whether the Indistinguishable Proteins column in the protein.tsv table is equivalent to Proteingroup.

Thanks.

**Comment by fcyu** [comment]
Thanks for the update. I think your screenshots explain everything. There is one more peptide in `P04636`. The protein inference uses the peptides and proteins from all experiments.

Best,

Fengchao

**Comment by fcyu** [comment]
> I would like to confirm with you whether the Indistinguishable Proteins column in the protein.tsv table is equivalent to Proteingroup.

That's correct. The proteins in `Protein` and `Indistinguishable Proteins` could be in the same protein group.

Best,

Fengchao

**Comment by shenghao003** [comment]
Great, thank you.

**Comment by shenghao003** [comment]
Hello, fengchao, I have a question that I would like to ask. In the protein.tsv table, the Unique Peptides of some proteins is 0, but they are still identified. How should I understand this?
![图片](https://github.com/Nesvilab/FragPipe/assets/47234121/72e61f4b-7920-41a7-82f8-5d829f6d3aef)

Thanks.
