### ISSUE TITLE
MSBooster finished when using LFQ-phospho workflow

### ISSUE THREAD

**Issue by michellefai** [Nesvilab/FragPipe#1672]
**- Upload your log file**

[log_2024-07-15_10-14-20.txt](https://github.com/user-attachments/files/16229579/log_2024-07-15_10-14-20.txt)

**- Describe the issue or question:**
Do you have any suggestion to overcome 'FileParsingException' caused by java.util.concurrent.TimeoutException? I am uploading the raw file to perform LFQ-phospho workflow. 

Your feedback is much appreciated. Thanks

**Comment by michellefai** [comment]
Hello, 

Thanks for your reply. 
The max RAM capacity of my pc is only 16 GB. What do you think?

**Comment by yangkl96** [comment]
If you do not have access to a computer with more RAM, you could try running just the MSBooster step multiple times, each time with a different subset of your files (3 or 4 subsets should be sufficient). Once they are all completed, you can run the remaining downstream steps with all files together

**Comment by yangkl96** [comment]
You can also replace the old `C:\Users\User\Downloads\FragPipe-jre-22.0\fragpipe\tools\MSBooster-1.2.31.jar` with the a pre-release jar file here: https://github.com/Nesvilab/MSBooster/releases/tag/v1.2.38

This version requires less memory, potentially enough of a decrease for you to run it on your current computer
