### ISSUE TITLE
No decoys found in the FASTA file?

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1675]
Hello

I formatted a Human FASTA file using my own scripts for creating the decoy and Philosopher but I get from FragPipe this error:
 
`2024-07-16 11:01:27,686 ERROR - No decoys found in the FASTA file.`

I reviewed the FASTA and it seems OK and following the guidelines seen at the Philospher doc. Do you know why this error? 

Thanks!

The file: [sp_human_decoy_cont_formatted.fasta.zip](https://github.com/user-attachments/files/16247644/sp_human_decoy_cont_formatted.fasta.zip)

**Comment by fcyu** [comment]
Could you share your workflow file!

Thanks,

Fengchao

**Comment by rolivella** [comment]
Yes, here it is: [fragpipe-220.workflow.zip](https://github.com/user-attachments/files/16248380/fragpipe-220.workflow.zip)

**Comment by rolivella** [comment]
@fcyu I reopen the issue because after running the fragpipe I got some unexpected messages and stopped before ending properly. I think that the problem is that it cannot run PeptideProphet: 
```
time="15:54:08" level=info msg="Executing PeptideProphet  v5.1.1"
Unknown file type. No file loaded./home/proteomics/mygit/atlas-runs/520c5201-cc4e-4e32-a566-8504c41c27cc/59/571dd10648593fae17bab5703e7f3c/output/1_1/2024MQ024_MSGA_052_01_25pto.raw
Unknown file type. No file loaded./home/proteomics/mygit/atlas-runs/520c5201-cc4e-4e32-a566-8504c41c27cc/59/571dd10648593fae17bab5703e7f3c/output/1_1/2024MQ024_MSGA_052_01_25pto.raw
```
I searched for a similar error in the issues and I found this one: 

https://github.com/Nesvilab/FragPipe/issues/1556

That was related with precisely the decoy sequences but I think that in my case they are OK...Any idea? This is my log: 

[fragpipe22_manual_decoy.log.zip](https://github.com/user-attachments/files/16250422/fragpipe22_manual_decoy.log.zip)

Thanks!

**Comment by fcyu** [comment]
The warnings you found won't affect the results. The crash was because the PeptideProphet models failed, and then there was no IDs. If you are doing a closed search, why not using Percolator?

```shell
Iterations: .........10.........20....WARNING: Mixture model quality test failed for charge (1+).
.
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
```

Best,

Fengchao

**Comment by rolivella** [comment]
Ok, I see. Do you mean `percolator.run-percolator=true`? I did it and got the same error log: [fragpipe22_manual_decoy_v2.log.zip](https://github.com/user-attachments/files/16252460/fragpipe22_manual_decoy_v2.log.zip)

**Comment by fcyu** [comment]
You still have PeptideProphet running

```shell
peptide-prophet.run-peptide-prophet=true
percolator.run-percolator=false
```

Best,

Fengchao

**Comment by Vidhiii5** [comment]
Hey, Do I need to download Java if I am using Fragpipe in windows?
