### ISSUE TITLE
Python error from split database

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#1676]
**- Upload your log file**
[log_2024-07-16_15-27-36.txt](https://github.com/user-attachments/files/16249858/log_2024-07-16_15-27-36.txt)

**- Describe the issue or question:**
Dear Fengchao, 
When executing a nonspecific search on two timsTOF DDA runs (6-30 amino acids peptide length; database split to 64) MSFragger exits after going through all 64 database chunks with this error message:

![image](https://github.com/user-attachments/assets/68b25fcf-a8fb-4b2f-82a5-612b1254fb50)

Any idea as to why this might happen?

Python and EasyPQP seem to be properly installed....

![image](https://github.com/user-attachments/assets/6ed7f0ee-a54b-45e1-93c1-0a46abb5a768)

Best, 

Hannes

**Comment by fcyu** [comment]
Another Python error.... @guoci can you take a look when you have time?

Thanks,

Fengchao

**Comment by guoci** [comment]
@hcadre Your installation of pandas might be broken.
In Anaconda Prompt, please run 
`pip uninstall pandas`
`conda uninstall pandas`
to uninstall pandas.
Then run `pip install easypqp`.
