### ISSUE TITLE
Diagnostic ion mining workflow error (corrupted files)

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1677]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-07-17_11-21-30.txt](https://github.com/user-attachments/files/16258792/log_2024-07-17_11-21-30.txt)

**- Describe the issue or question:**

Hi, I followed the tutorial (https://fragpipe.nesvilab.org/docs/tutorial_diagnostic_mining.html)  to download the sample data and ran the process, but MSFragger reported the following error, can I ask what is the reason? It looks like it can't handle raw files, but why is that?

MSFragger [Work dir: /home/liangx/test]
java -jar -Dfile.encoding=UTF-8 -Xmx741G /home/liangx/software/fragpipe/tools/MSFragger-4.1/MSFragger-4.1.jar /home/liangx/test/fragger.params /home/liangx/data/mRBS_dTamicon30K_4SU_HCD_half_1.raw
MSFragger version MSFragger-4.1
Batmass-IO version 1.33.4
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 11.0.1, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 741 GB memory
Checking database...
Parameter 'analyzer_types' was not supplied. Using default value: all
Checking spectral files...
Failed in checking /home/liangx/data/mRBS_dTamicon30K_4SU_HCD_half_1.raw. Will ignore it.
Could not get ThermoIndex
There are corrupted files. Please remove those files and re-start the task.
2024-07-17 11:20:26 ERROR - Could not find Batmass-IO Thermo binary BatmassIoThermoServer from /home/liangx/software/fragpipe/tools/MSFragger-4.1/ext/thermo, /home/liangx/software/fragpipe/tools/MSFragger-4.1/./ext/thermo, /home/liangx/software/fragpipe/tools/MSFragger-4.1/../ext/thermo, /home/liangx/software/fragpipe/tools/MSFragger-4.1/../../../../ext/thermo, /home/liangx/software/fragpipe/tools/MSFragger-4.1/../../../../../ext/thermo 
/home/liangx/data/mRBS_dTamicon30K_4SU_HCD_half_1.raw: Scans = 0; ITMS: false; FTMS: false; Isolation sizes = []
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Could you upgrade FragPipe to 22.0 and try again?

Thanks,

Fengchao

**Comment by liangxiao023** [comment]
> Could you upgrade FragPipe to 22.0 and try again?
> 
> Thanks,
> 
> Fengchao

Hi, thank you very much for your reply, I troubleshooted the error and found that the Mono software was deleted by someone else, and after installing it back it works fine, thank you.
