### ISSUE TITLE
LFQ-phospho PTMprophet "Unknown file type. No file loaded"

### ISSUE THREAD

**Issue by MassSpecPostDoc** [Nesvilab/FragPipe#1680]
Log File:
[log_2024-07-18_12-11-55.txt](https://github.com/user-attachments/files/16283451/log_2024-07-18_12-11-55.txt)

Hello FragPipe team, 

I loaded the LFQ-phospho workflow and I am trying to run it on some DDA-PASEF data. Something seems to be going wrong with PTMprophet, it reports:

 Unknown file type. No file loaded.E:\20240712_MC_DYRK1APhospho_DDA_HET5_S2-B10_1_7581.d
[ERROR:] cannot read scan in data file E:\20240712_MC_DYRK1APhospho_DDA_HET5_S2-B10_1_7581.d exiting ...

I have tried shortening the file path, but apart from that I could not think of any other troubleshooting. Apologies if this issue has been previously resolved, I could not find a solution elsewhere.  Please suggest a solution?

Cheers,

Andy

**Comment by fcyu** [comment]
Could you share `interact-20240712_MC_DYRK1APhospho_DDA_HET4_S2-B9_1_7580.pep.xml` with us?

Thanks,

Fengchao

**Comment by MassSpecPostDoc** [comment]
Hello Fengchao,

Here it is, I had to zip it or it would not upload:

[interact-20240712_MC_DYRK1APhospho_DDA_HET4_S2-B9_1_7580.pep.zip](https://github.com/user-attachments/files/16283601/interact-20240712_MC_DYRK1APhospho_DDA_HET4_S2-B9_1_7580.pep.zip)

Thanks for looking at this, Cheers,

Andy

**Comment by fcyu** [comment]
Thanks for sharing the files. I think something was messed up but I am not sure which one exactly. 

Could you delete all files in `C:\Users\Public\Documents\fragpipe_22`, redownload FragPipe, MSFragger, IonQuant, and diaTracer, and try again?

BTW, you'd better to specify the result folder to something other than the root directory `E:\`.

Best,

Fengchao

**Comment by MassSpecPostDoc** [comment]
Hello Fengchao,

This appears to have worked and I have a result. Please do mark as complete.

Thank you very much for the advice! Not sure how it went wrong with the first download and setup. 

Cheers,

Andy
