### ISSUE TITLE
Quantitative indicators of PTM confidence

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1682]
**- Describe the feature:**

Hi, I would like to ask if there are some metrics calculated in the MSFragger or PTM-Shepherd section that can somewhat indicate that the PTM is plausible on the peptides detected by fragpipe? Such as differential p-values between modified and unmodified peptides, signal intensity of specific ions this type of metrics and accompanied by a threshold for screening these modifications.
Thank you very much for developing this excellent software!

**Comment by fcyu** [comment]
Please read our tutorial: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html
