### ISSUE TITLE
Optimization of Fragpipe for Special Sample with Isotopologue Peptides

### ISSUE THREAD

**Issue by rolivella** [Nesvilab/FragPipe#1686]
Hello,

I am seeking advice on optimizing Fragpipe for a specific type of sample we are working with. Our samples are HeLa cells mixed with 6 peptides, each of which has 5 isotopologue versions. Here’s what I have done so far:

1. Added the amino acid sequences of the 6 peptides to the FASTA file.
2. Modified the workflow file to include the variable modifications for the heavy versions of the peptides.
```
msfragger.table.var-mods=15.9949,M,true,3; 42.0106,[^,true,1; 79.96633,STY,false,3; -17.0265,nQnC,false,1; -18.0106,nE,false,1; 4.025107,K,false,2; 6.020129,R,false,2; 8.014199,K,true,2; 10.008269,R,tr    ue,2; 6.020129,KR,false,2; 4.007099,S,true,2; 5.010454,T,true,2; 4.007099,A,true,2; 6.013809,V,true,2; 7.017164,L,true,2; 10.027228,F,true,2
```

However, the current setup consumes a lot of memory and takes 45 minutes to complete. I believe this is because Fragpipe searches for variable modifications across all peptides in the sample.

**My questions are:**

1. Is there a way to configure Fragpipe to optimize this search, specifically to focus only on our peptide mix? Any suggestions to reduce memory usage and processing time would be greatly appreciated.
   
2. I also observed that after the search, I cannot find the `combined_protein.tsv` file in the output folder, despite setting `ionquant.run-ionquant=true` and `ptmshepherd.run-shepherd=true`. Do you know what could be the problem?

Thank you!

**Comment by fcyu** [comment]
> Is there a way to configure Fragpipe to optimize this search, specifically to focus only on our peptide mix? Any suggestions to reduce memory usage and processing time would be greatly appreciated.

I think there is a trick to largely reduce the search space since there are only 6 peptides having the labels. I posted it for the Pierce iRT peptide search https://github.com/Nesvilab/FragPipe/issues/1673#issuecomment-2230833796, but I think the same trick should work for your data too.

One thing to notice that there are at most 6 "idle amino acids" to be re-used: BJXZ plus UO (for U and O, please note that they have non-zero masses, and make sure that your fasta file does not have U or O).

> I also observed that after the search, I cannot find the combined_protein.tsv file in the output folder, despite setting ionquant.run-ionquant=true and ptmshepherd.run-shepherd=true. Do you know what could be the problem?

Have you specified the experiment or bioreplicates in the "workflow" tab? 

BTW, why did you enable PTM-Shepherd? Is that an open or mass-offset search?

Thanks,

Fengchao

**Comment by rolivella** [comment]
Thanks @fcyu I'll try an let you know. I think I set PTM-Shepherd "true" by error.

**Comment by rolivella** [comment]
Hi @fcyu , for my peptides mix I think that I would need the internal masses you use for BJXZUO in order the compute the delta mass.

**Comment by rolivella** [comment]
I'm clarifying my previous post. For my peptide mix analysis, I need the specific internal masses used by FragPipe for the amino acids BJXZUO to calculate the delta mass. Could you please let me know if there is a resource or location where I can find these masses?

**Comment by fcyu** [comment]
BJZX have zero mass. O's mass is 237.14773 Da, and U's mass is 150.95363 Da.

Best,

Fengchao
