### ISSUE TITLE
Uploading Fragpipe results to PRIDE

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#1687]
We would like to upload our results to PRIDE but for a full submission we are required to submit an .mzTab file (as is produced by MaxQuant) or something equivalent. Do you know if there is an equivalent fragpipe output file that can be used?

Thank you

**Comment by fcyu** [comment]
No, FragPipe does not generate the mzID or mzTab files. But, you could do a partial submission in PRIDE, which is what most people do. 

Best,

Fengchao
