### ISSUE TITLE
In correct settings broke FragPipe

### ISSUE THREAD

**Issue by douyue623** [Nesvilab/FragPipe#1688]
**- Upload your log file**
[log_2024-07-22_10-50-17.txt](https://github.com/user-attachments/files/16336129/log_2024-07-22_10-50-17.txt)

**- Describe the issue or question:**

Hi I tried to analyze TMT data, but there is no table I can edit for different channels. When I started run, it stopped for some reason. I dont know if it is associated with this problem. Can you help me check, please?

And for the validation, do I need to run MSBooster? If so, which model I should use? This is just normal analysis for protein identification and quantification.

Thanks,
Yue

**Comment by fcyu** [comment]
> Hi I tried to analyze TMT data, but there is no table I can edit for different channels. When I started run, it stopped for some reason. I dont know if it is associated with this problem. Can you help me check, please?

Here is where you put your reporter ion annotations. I load some dummy data for the demonstration purpose.

![image](https://github.com/user-attachments/assets/9fe6f11b-f880-4ccc-9251-df2aa4aa2f6b)


> And for the validation, do I need to run MSBooster? If so, which model I should use? This is just normal analysis for protein identification and quantification.

The default setting works well.

BTW, I don't think your MSFragger configurations are correct because there are no TMT in either variable or fixed modifications. Please use one of our built-in TMT workflows.

Best,

Fengchao

**Comment by douyue623** [comment]
I upload the workflow again, but it's still no edit button
![edit](https://github.com/user-attachments/assets/11dc56fd-c9db-4ae7-8d60-9ab1ef588fd7)

**Comment by fcyu** [comment]
Can you show me the screenshot of the "workflow" tab?

Thanks,

Fengchao

**Comment by douyue623** [comment]
![workflow](https://github.com/user-attachments/assets/00d92463-63b4-4af0-a8bc-a3369cd68caf)

**Comment by fcyu** [comment]
Can you remove the raw file, load again, and then specify the experiment?

Thanks,

Fengchao

**Comment by douyue623** [comment]
yeah I remove and load again, but I still cannot edit.

**Comment by fcyu** [comment]
Then, I am not sure what the issue is now... Maybe we could have a zoom call to troubleshoot if you want... My email is yufeATumich.edu (replace AT with @).

Best,

Fengchao
