### ISSUE TITLE
Error generating skyline report

### ISSUE THREAD

**Issue by zouboulk** [Nesvilab/FragPipe#1689]
[log_2024-07-22_16-18-55.txt](https://github.com/user-attachments/files/16336239/log_2024-07-22_16-18-55.txt)

**- Describe the issue or question:**
I am trying to generate a Skyline report for an o-glyco search following the description on the website (see below). However, when I run the search I encounter an error that my document does not contain any peptides (see below). No Skyline document is generated.

DDA results currently require a workaround method, but will be supported fully in future. To view DDA results in Skyline: 1) On the MSFragger tab, under Open Search Options, set “Report mass shift as a variable mod” to “Yes, remove delta mass”. NOTE: this prevents using Glycan Composition Assignment or O-Pair search on the Glyco tab! Run a separate search to generate a Skyline document vs using those methods. Note also that this means that the results viewed in Skyline will NOT have glycan FDR applied.
2) Set the Skyline running mode to “Use pep.xml as input” on the Skyline tab and the Special Modifications Mode according to your analysis type.

[2024/07/22 16:18:46]	Importing FASTA file protein.fas...
[2024/07/22 16:18:46]	Associating peptides with proteins from FASTA file protein.fas
[2024/07/22 16:18:46]	Failed to associate proteins
[2024/07/22 16:18:46]	The document does not contain any peptides.
[2024/07/22 16:18:46]	Error: Failure occurred. Exiting...
Process 'Skyline' finished, exit code: 0

**Comment by dpolasky** [comment]
Hi,
The lack of peptides issue is because the enzyme is currently not passed to Skyline, so it is looking for tryptic peptides by default and cannot find the GluC peptides. We are implementing support for other enzymes now - if you would like the prerelease version that supports other enzymes, send me an email at dpolasky [at] umich.edu and I can share it with you.

Best,
Dan

**Comment by dpolasky** [comment]
fixed in 00ad7b9
