### ISSUE TITLE
Provide detailed instructions for running Fragpipe in docker container

### ISSUE THREAD

**Issue by rjcorb** [Nesvilab/FragPipe#1690]
**- Describe the feature:**

The repository README should be updated to include additional instructions for running Fragpipe in docker container. Currently there are instructions for pulling the docker image, but no additional instructions for running and entering docker container. I have executed the following commands, but when I try to run the docker container, it exits immediately after starting. 

```
git clone https://github.com/Nesvilab/FragPipe.git

cd FragPipe

docker pull fcyucn/fragpipe

docker run --platform linux/amd64 --name fragpipe -d -e PASSWORD=ANYTHING -p 80:8787 -v $PWD:/home/rstudio/FragPipe fcyucn/fragpipe:latest
```

Any updates to the README that would provide insights into how to get this running would be greatly appreciated!

**Comment by fcyu** [comment]
Let me paste some commands in the following.

```shell
docker image ls -a # get the image ID
docker run -it -v <local dir>:<container dir> <docker image ID> /bin/bash # you probably need to mount the local dir to container
```

FragPipe is located in `/fragpipe_bin`

Best,

Fengchao

**Comment by rjcorb** [comment]
Thank you, I was able to get into the docker container with the above instructions. However, it looks like some of the FragPIpe dependencies (MSFragger, diaTracer, IonQuant) are not installed as part of the docker image. I see that these are all available to download through a web browser, but is there a way to download and install these tools from the command line?

**Comment by fcyu** [comment]
Unfortunately, no. You have to either download it using browser or FragPipe GUI. In case you wonder, we could not put those three tools in the docker image due to the license constraint.

Best,

Fengchao

**Comment by fcyu** [comment]
I have write a tutorial: https://fragpipe.nesvilab.org/docs/tutorial_docker.html 

Let me know if you have any other questions.

Best,

Fengchao

**Comment by fcyu** [comment]
Yes, you can. It is a text file, and the following is an example. You could also export one by running the GUI on any computer.

```
<path to LC-MS file>	<experiment name>	<bioreplicate>	<data type>
```

Best,

Fengchao
