### ISSUE TITLE
Issue with mzML file 

### ISSUE THREAD

**Issue by boehmpjn** [Nesvilab/FragPipe#1691]
**- Upload your log file**
CheckCentroid
`
C:\Users\boehmp\Downloads\ab\fragpipe\jre\bin\java.exe -Xmx8G -cp C:\Users\boehmp\Downloads\ab\fragpipe\lib\fragpipe-22.0.jar;C:\Users\boehmp\Downloads\ab\fragpipe\tools\batmass-io-1.33.4.jar com.dmtavt.fragpipe.util.CheckCentroid Y:\Projects\LiP-Collab\20240717_TestOfAscent\FragPipe\20240722_LipSchool_Rapamycin_IA\20240722_LiPMS_IA00107.mzML 4
java.lang.RuntimeException: Does not support the scan "controllerType=3 controllerNumber=1 scan=1". It is not from MS. If you believe that it is a bug, please contact the software developers.
	at umich.ms.util.ScanIdNum.getNumFromId(ScanIdNum.java:32)
	at umich.ms.datatypes.index.impl.IndexElementDefault.<init>(IndexElementDefault.java:45)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedIndexElement.<init>(AbstractXMLBasedIndexElement.java:33)
	at umich.ms.fileio.filetypes.mzml.MZMLIndexElement.<init>(MZMLIndexElement.java:27)
	at umich.ms.fileio.filetypes.mzml.MZMLIndexParser.parse(MZMLIndexParser.java:168)
	at umich.ms.fileio.filetypes.mzml.MZMLFile.parseIndex(MZMLFile.java:68)
	at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:57)
	at umich.ms.fileio.filetypes.mzml.MZMLFile.fetchIndex(MZMLFile.java:32)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:116)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
	at com.dmtavt.fragpipe.util.CheckCentroid.isCentroid(CheckCentroid.java:76)
	at com.dmtavt.fragpipe.util.CheckCentroid.main(CheckCentroid.java:39)
Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping
`
[log_2024-07-24_15-39-58.txt](https://github.com/user-attachments/files/16362926/log_2024-07-24_15-39-58.txt)

**- Describe the issue or question:**
Thank you for maintaining this very usuell proteomics pipeline! 
I have an issue I believe is caused by the mzML file I am putting in as the error seems to indicate a problem with a scan, however I could not find a scan with the indicated ID in the mzML file when importing it using the python pyteomics (`pyteomics.mzml.read`) package. I converted the file from a .raw file and would like to run a DIA_SpecLib_Quant workflow. 

Thank you for the help!

**Comment by fcyu** [comment]
What instrument is you data from? `controllerType=3` is not something we normally see from a mass spectrometer.

Best,

Fengchao

**Comment by boehmpjn** [comment]
Hey,

The data is from our new Ascent, which could be the problem as it can record MSn spectra. In this file only MS1 and MS2 data should be present.

Best,
Paul

**Comment by boehmpjn** [comment]
Of course. 

https://polybox.ethz.ch/index.php/s/Xqd5xGjUaqC9Uws 

Best,
Paul

**Comment by boehmpjn** [comment]
Hello Fengchao,

There are UV-Vis spectra as I am currently optimizing the gradient on our device and wanted to see the Absorption. Therefore, for FragPipe they are not relevant at all. Do I need to filter them out before or can I get FragPipe ignore them?

Best,
Paul

**Comment by fcyu** [comment]
Hi Paul,

Thank you for the explanation. I think for now, you have to filter them out. I will implement the feature to let FragPipe ignore them in the next release.

Best,

Fengchao

**Comment by boehmpjn** [comment]
Hey Fengchao,

Thank you for all the help! After filtering I was able to run most of the analysis but DIA-NN is not able to read the files (except the first one). I can correctly open the file in OpenMS and see the MS1 and MS2 spectra.
[log_2024-07-26_14-37-11.txt](https://github.com/user-attachments/files/16392328/log_2024-07-26_14-37-11.txt)

Best,
Paul

**Comment by fcyu** [comment]
If DIA-NN could read the first one, I am not sure if there were some IO issues when reading the rest of the files. Could you try again by re-runing it?

Thanks,

Fengchao

**Comment by boehmpjn** [comment]
Hi Fengchao,

Yes that is what I thought and tried that but got the same error. The difference between the first and the other files is that the first is not zlib compressed. I send the second error log, the frist was this one: 
[log_2024-07-26_03-26-44.txt](https://github.com/user-attachments/files/16392884/log_2024-07-26_03-26-44.txt)

Best,
Paul

**Comment by fcyu** [comment]
I don't know the cause of the error. Maybe you could submit a ticket to https://github.com/vdemichev/DiaNN/issues

Best,

Fengchao

**Comment by boehmpjn** [comment]
Hi Fengchao,

Thank you for your help, I was able to run it with files without UV spectra. However, the filtered (filtered using the transform function of the psims package) were not compatible with Dia-NN. 

Best,
Paul

**Comment by fcyu** [comment]
I will make MSFragger support the data with UV spectra. It will skip those UV spectra. If you want to try the fixed pre-released version, let me know.

Best,

Fengchao
