### ISSUE TITLE
Glycan database has issue for glycans

### ISSUE THREAD

**Issue by Weiming-Yang** [Nesvilab/FragPipe#1693]
[log_2024-07-25_02-06-31.zip](https://github.com/user-attachments/files/16382325/log_2024-07-25_02-06-31.zip)

**- Describe the issue or question:**
Hi Dan,
When I searched O-glycopeptide data and set the glycan database, I got the errors below. The analysis finished successfully, but the result missed sialic acid. For example, 656.2276 was in the data when I used Fragpipe 21.1, but it did not appear when I used Fragpipe 22.0. That may be because of the errors below. The log file did not seem to show the error.

14:09:33 ERROR: Glycan 203.0794 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 365.1322 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 406.1588 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 494.1748 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 511.1901 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 527.185 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 568.2116 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 656.2276 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 673.2429 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 714.2695 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 730.2644 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 802.2855 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 818.2804 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 859.307 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 860.3274 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 876.3223 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 947.323 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 964.3383 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1005.3649 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1021.3598 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1022.3802 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1095.3966 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1109.3758 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1167.4177 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1238.4184 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1241.4545 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1312.4552 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1313.4756 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1386.492 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1387.5124 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1441.4978 could not be parsed. This glycan will be ignored!
14:09:33 ERROR: Glycan 1458.5131 could not be parsed. This glycan will be ignored!

**Comment by dpolasky** [comment]
The issue with missing sialic acid was due to a bug in O-Pair search, fixed in b53113b. The glycan parsing warnings were due to a non-standard database format, but did not impact the results.
