### ISSUE TITLE
Results Issue with FragPipe

### ISSUE THREAD

**Issue by azying312** [Nesvilab/FragPipe#1697]
Hi,

I am running FragPipe and while looking at my results from a run from 07/03 and 07/28, I have drastically different results. Between these runs, diaTracer and EasyPQP have upgraded their versions. The overlap between the two runs peptides is 5588 (07/03 run has 59686 identified peptides while 07/28 only has 6111). The overlap between proteins is 0 (besides the iRT), and 07/03 has 2711 identified proteins while 07/28 has 1958. I used the default workflow for both with edits for the number of missed cleaves, adding the modification (same for both), and the peptide length (7-52). I don't think there should be 0 overlap between the proteins, and I noticed this also because one of the identified peptides with high confidence and many fragment ions was not identified in the 07/28 run despite being in the 07/03 run. I have attached the log files for both. Please let me know if you have any insight into what might happen/what I can upload to help with this.

Best,
Alice

[log_2024-07-29_12-13-20.txt](https://github.com/user-attachments/files/16419440/log_2024-07-29_12-13-20.txt)
[log_2024-07-03_16-41-57.txt](https://github.com/user-attachments/files/16419447/log_2024-07-03_16-41-57.txt)

**Comment by fcyu** [comment]
Hi Alice,

You assigned your data to `DDA` data type, so it is not related to diaTrader.
 
The fasta files between those two log files are different: `2024-07-03-decoys-uniprot_mouse_proteome_2018_biognosys_irt11.fasta.fas` vs `2024-07-18-decoys-human_uniprot_proteome_biognosys_irt11.fasta.fas`, which result in big differences in the MSFragger first search, mass calibration, and parameter optimization.

<img width="1602" alt="image" src="https://github.com/user-attachments/assets/a2c059a8-8c06-4677-b1d0-2c6bd5a17b6f">

It seems that the fasta file in the 07/29 one is not as good as the 07/03 one's.

Could you switch to the same fasta file and try again?

Thanks,

Fengchao

**Comment by azying312** [comment]
Hi Fengchao,

Thanks, I can run them again with the same one. The base FASTA file is the same, but I added the iRT and decoys on different days (and resaved it). Is there a difference in how/what the decoys are added?

Best,
Alice

**Comment by azying312** [comment]
I also unfortunately got rid of the FASTA file from 07/03, but I am still using the same base FASTA file. I can add iRT and decoys again, but it would be a new file.

**Comment by fcyu** [comment]
> The base FASTA file is the same, but I added the iRT and decoys on different days (and resaved it). Is there a difference in how/what the decoys are added?

The decoys and iRT should be the same given the same target sequences. Could you test using the same fasta (the old or the new one)?

Thanks,

Fengchao

**Comment by azying312** [comment]
I got it to work again, thank you!
