### ISSUE TITLE
Python error `ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.`

### ISSUE THREAD

**Issue by laraholoidov** [Nesvilab/FragPipe#1698]
Hello FragPipe team, 
recently I am having trouble searching DIA data, and getting the following error: 
"ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
2024-07-29 15:03:11 - Info: easypqp_rt_alignment_2024-05-16-LH-FAIMS-JURcys-DDA-40v-x1-1; Lowess fraction used: 0.08.
Library not generated, not enough peptides could be found for alignment."

The log file is attaches
[log_2024-07-29_15-03-13.txt](https://github.com/user-attachments/files/16419633/log_2024-07-29_15-03-13.txt)

I noticed that a similar issue was reported here #932 and the solution was to use the latest FP and philosopher version, however, unfortunatelly it didnt help my case. I was searching this kind of datasets using FP21 and it went through just fine, until now. I swiched toFP22 but got the same error.

Would deeply appreciate you help,
thank you

**Comment by fcyu** [comment]
I think it was due to the version incompatibility of some Python packages becase
```shell
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

I am not sure what the cause it. Hopefully @guoci can take a look. If he couldn't, I will spend more time to investigate it.

Best,

Fengchao

**Comment by fcyu** [comment]
I took another look and tried to reproduce the error with the latest pandas (version 2.2.2), but I couldn't reproduce this error: [log_2024-07-29_19-44-48.txt](https://github.com/user-attachments/files/16420140/log_2024-07-29_19-44-48.txt)

Could you uninstall and install some python packages by running the following commands in command line interface

```shell
pip uninstall pandas numpy easypqp -y
pip install easypqp -y
```

If the error still persist, I need to send you a new FragPipe to print more debug info.

Thanks,

Fengchao

**Comment by laraholoidov** [comment]
Hi Fengchao,
thank you for looking into that. 
I tried to reinstall it but unfortunatelly it did not help

Lara

**Comment by fcyu** [comment]
Hi Lara,

Thank you for the testing. I have made some changes trying to fix this issue. Could you uninstall and install the EasyPQP using the following command, and try again? It requires git installed because it pulls the code from our GitHub repository.

```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Thanks,

Fengchao

**Comment by laraholoidov** [comment]
Good morning Fengchao,
I re-installed it and still got the same error.

I am attaching the last log file just in case you need it
[log_2024-07-30_09-47-54.txt](https://github.com/user-attachments/files/16431250/log_2024-07-30_09-47-54.txt)

Thank you,
Lara

**Comment by fcyu** [comment]
Hmm, then, I need your data to reproduce the error. Could you upload the mzML and fasta files to https://www.dropbox.com/request/QGBumk50xHklggfXkCI1 ?

Thanks,

Fengchao

**Comment by laraholoidov** [comment]
Hi Fengchao,

the files were uploaded 

Thank you,
Lara

**Comment by fcyu** [comment]
Hi Lara,

Thanks for sharing your files. I couldn't reproduce the error, and FragPipe finished the running without any errors [log_2024-07-30_17-41-33.txt](https://github.com/user-attachments/files/16442595/log_2024-07-30_17-41-33.txt). 

I think some of the Python packages don't have the compatible versions or wasn't installed properly. Maybe we could have a Zoom meeting to troubleshoot by looking at your command line interface window.

Best,

Fengchao

**Comment by laraholoidov** [comment]
Hi Fengchao,
Sorry for the late response, let me know when you are available for a Zoom call. I am quite free tomorrow.

**Comment by fcyu** [comment]
No worries. I am available 9:30AM - noon EDT, tomorrow. Could you send an email to `yufeATumich.edu` (replace `AT` with `@`) for the specific time?

Thanks,

Fengchao

**Comment by yuxin-zh** [comment]
so what is the final method?dou you solve it? I have the same erros

**Comment by fcyu** [comment]
Yes, please run the following command to install the fixed EasyPQP

```shell
pip uninstall easypqp
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Best,

Fengchao
