### ISSUE TITLE
ddaPASEF searches error. 

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#170]
**Describe the bug**
I used FagePipe to search ddaPASEF RAW data. Error happened, and it shows "Bruker native libraries not found." 
The FagePipe version is 12.2, and MSFagger version is 2.3. 
[log-fragpipe-run-at_2020-02-16_23-21-04.log](https://github.com/Nesvilab/FragPipe/files/4210020/log-fragpipe-run-at_2020-02-16_23-21-04.log)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe and MSFragger. Do you have the `ext` folder along with MSFragger-2.3.jar?

Best,

Fengchao

**Comment by andyzim111** [comment]
Yes, I have the ext folder.
you can see the attached screenshot.
![image](https://user-images.githubusercontent.com/46341795/74626904-33875580-518c-11ea-9f82-fbdf590b78d4.png)
![ext](https://user-images.githubusercontent.com/46341795/74626965-5dd91300-518c-11ea-99ba-e599dbc3e3d4.png)

**Comment by fcyu** [comment]
Thanks for your prompt reply, Another possible reason is that Bruker's library needs [Visual C++ Redistributable for Visual Studio 2017](https://aka.ms/vs/16/release/VC_redist.x64.exe). In few cases, Windows doesn't have this installed. Could you please help to check and install it?

@chhh This is the only reason I can figure out. Could you please take a look and see if there is any other reasons?

Thanks,

Fengchao

**Comment by chhh** [comment]
@fcyu Unfortunately there's not much to look at. It should be working..

@andyzim111 Could you please try the following: Start fragpipe from command line (`cmd.exe` or `powershell`) with an additional parameter, like this:

```shell
cd D:\Fragpipe
java -Dbruker.lib.path="D:\Fragpipe\MSFragger-2.3\ext\bruker" -jar FragPipe-12.2.jar
```

and try a TIMS file again?

**Comment by fcyu** [comment]
@chhh I had a similar problem with our Linux server because the C++ std library was too old. The error message is still "Bruker native libraries not found.". I wonder if it is possible to print a more informative message.

**Comment by andyzim111** [comment]
I used "java -Dbruker.lib.path="D:\Fragpipe\MSFragger-2.3\ext\bruker" -jar FragPipe-12.2.jar"
It shows "Error: Unable to access jarfile FragPipe-12.2.jar".

**Comment by chhh** [comment]
@andyzim111 This error is shown when it can't find the file. Did you change (`cd`) to the directory where the jar file is? Alternatively specify the full path to the jar file.

**Comment by andyzim111** [comment]
I downloaded the FragPipe.exe file to run. 
I will download the FragPipe.jar to try.

**Comment by andyzim111** [comment]
I used "java -Dbruker.lib.path="D:\Fragpipe\MSFragger-2.3\ext\bruker" -jar FragPipe-12.2.jar"
It shows " cannot find or load .lib.path=D:\Fragpipe\MSFragger-2.3\ext\bruker".

**Comment by andyzim111** [comment]
I successfully search RAW files from thermo lumos and mzML files converted from .d files.

**Comment by andyzim111** [comment]
@fcyu, I have downloaded Visual C++ Redistributable for Visual Studio 2017 and installed it. 
FragPipe can search .d files now. Thanks.

**Comment by anesvi** [comment]
I am glad to hear it is resolved

Looks like we need to add a note somewhere (on the Website? Informative error message from FragPipe or MSFragger? ) that using .d files may require installing Visual C++ Redistributable for Visual Studio 2017

**Comment by fcyu** [comment]
Sounds great! Added the notes to [https://github.com/Nesvilab/MSFragger/blob/master/README.md](https://github.com/Nesvilab/MSFragger/blob/master/README.md) and [https://github.com/Nesvilab/MSFragger/blob/master/tutorial_fragpipe_pasef.md](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_fragpipe_pasef.md).

Best,

Fengchao
