### ISSUE TITLE
Is FragPipe analyst down?

### ISSUE THREAD

**Issue by RoberthAnthonyRojasChavez** [Nesvilab/FragPipe#1700]
Hi, 

Thank you for supporting this great tool! Yesterday morning I was using FragPipe Analyst and it was working correctly. Later that day it began to take a long time to load the page and eventually fail. Today I am still encountering these issues. I tried with different computers, browsers, and networks. Is this a broader problem or an issue on my end?

Kind regards,
Anthony
![image](https://github.com/user-attachments/assets/c9891385-deec-4d19-bf97-ebbb680156c8)

**Comment by fcyu** [comment]
Thanks for the report. We are trying to fix it. Stay tuned.

Best,

Fengchao

**Comment by fcyu** [comment]
It is back online now.

Thank you again for your report.

Best,

Fengchao

**Comment by RoberthAnthonyRojasChavez** [comment]
> It is back online now.
> 
> Thank you again for your report.
> 
> Best,
> 
> Fengchao

Thank you for your fast response! It is working perfectly for me now :)

Kind regards,
Anthony
