### ISSUE TITLE
Question about parameters for LFQ quantification

### ISSUE THREAD

**Issue by paulinecoulon** [Nesvilab/FragPipe#1702]
Good evening, 

I would like to know how to properly set up quantification for LFQ analysis. I would like to set up a quantification on proteins having at least two peptides and with at least 3 spectral counts each.

Could you please assist me?

Thanks

**Comment by fcyu** [comment]
If it is a DDA data, you could use the built-in LFQ-MBR workflow. And then, filter the proteins in `combined_protein.tsv` based on your criteria.

Best,

Fengchao

**Comment by bluemooninvestor** [comment]
Hi Fengchao

There seem to be a lot of command line options possible in Fragpipe itself. Wouldn't it be possible to set it the following way inside your tool itself:

1) Proteins should be summarized only when there are X no of unique peptides 

OR

1) Proteins should be summarized only when there are X no unique + shared peptides

This should be possible using options inside the tool, isn't it? Some options in the validation tab?

**Comment by fcyu** [comment]
> This should be possible using options inside the tool, isn't it? Some options in the validation tab?

No.

Best,

Fengchao
