### ISSUE TITLE
Question about cysteine with carbamidomethylation and mass shift in open search

### ISSUE THREAD

**Issue by MattiaRediti** [Nesvilab/FragPipe#1704]
Hello,
First of all, thank you for your tool and the continuous development. 
I would like to clarify how to deal with mass shifts in open searches in the presence of cysteine carbamidomethylation as fixed modification.
In particular, for "delta masses" with "best position" at a cysteine, is the delta mass reported in the psm.tsv (for instance 42.0469, just a random example) already taking into account the carbamidomethylation (57.0214) of that cysteine (thus, I would assume all cysteines in the peptide sequence are assigned by default, a priori, a mass of 121.154 + 57.0214, and the delta mass compared to the molecular mass of cysteine would be 57.0214 + 42.0469), or is it compared to the unmodified cysteine molecular mass (thus truly being 42.0449)?

I assume it is the first hypothesis, but I would like to make sure of it.
Thank you for the help.

**Comment by dpolasky** [comment]
Hi,
Your guess is correct, a reported delta mass (like 42.0469) at cysteine from open search would be in addition to the fixed carbamidomethylation, so the actual cysteine mass in the peptide would be  57 + 42 = 121. The fixed and variable mods are accounted for before computing the delta mass, so it is the difference between the observed precursor mass and the calculated mass of the peptide sequence and fixed/variable mods. 

Also keep in mind that the localization confidence is generally less than the identification confidence, so it is possible that the delta mass may actually be at a residue nearby the cysteine, especially if the difference in score between the best position and other position(s) is small. 

Best,
Dan
