### ISSUE TITLE
Few clarifications necessary regarding the MS1 Quant options (DDA data)

### ISSUE THREAD

**Issue by bluemooninvestor** [Nesvilab/FragPipe#1705]
Hello

Thank you for making this wonderful tool. I am a newbie and I was hoping you could help me with few queries so that I can quickly start the proper analysis.

1) What does the maxLFQ minimim ions do? Is it the minimum number of peptides to quantify a protein? Or is it the minimum number of samples which should have the ion in order for maxLFQ to perform quantitiation for a peptide level.

2) What is the intensity top N ions option do? What happens if the protein has less ions than mentioned in topN? Is this only applicable to intensity and not max LFQ?

3) Why are these options being referred to as ions and not PSMs? You mean the same thing essentially, right? Or two ions corresponding to same peptide are considered as two ions?

4) Can I somehow specify the tool to only quantify proteins if they have 2 unique peptides from this MS1 Quant tab.

Thank you for your help!

**Comment by fcyu** [comment]
1. Minimum number of ions per protein.
2. Number of peptides used to calculate the protein intensity. Use all if there are less than N peptides. It is another algorithm to calculate the protein intensity not related to MaxLFQ.
3. Ions are the MS1 XIC features but PSMs are at the MS2 scan level.
4. No.

Best,

Fengchao
