### ISSUE TITLE
Where can I find command line reference for Percolator and Protein prophet for use in Fragpipe?

### ISSUE THREAD

**Issue by bluemooninvestor** [Nesvilab/FragPipe#1706]
As the title says. I will to find a way to infer proteins only when they have 2 unique peptides observed in each sample. I want to do it in Fragpipe itself. These command line options are not referenced in the Fragpipe tutorials anywhere.

Kindly guide me about the command line reference for Percolator and Protein prophet.

Additionally, I see some flags for the "FDR filter and report" option. Are they all, or are there more command line options for this too?

**Comment by fcyu** [comment]
If you run FragPipe, you will see those commands in the log.

> Additionally, I see some flags for the "FDR filter and report" option. Are they all, or are there more command line options for this too?

They are just part of the options for FDR filtering.

Best,

Fengchao
