### ISSUE TITLE
loading custom workflows that aren't saved in built-in workflow folder

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1708]
Hi all,

Thank you for your help with my recent issue. I had a question regarding workflow sharing as described here:

https://github.com/Nesvilab/FragPipe/tree/gh-pages/docs/workflow-sharing

The installation of fragpipe-22.0 I am working with is installed on our institution's HPC, and I cannot save custom workflows to the FragPipe installation workflows folder. Is there somewhere else I can save them so I can load them and view them in the GUI on our HPC?

Sorry if this is already in the docs, it wasn't entirely clear to me how to do this.

Thanks for your time and help!

Best,
Asher

**Comment by fcyu** [comment]
Hi Asher,

Yes, you can save the workflow to any folder using the "save to custom folder" 

![image](https://github.com/user-attachments/assets/26b3518e-5922-49b7-a9d4-a8a564c483cc)

And you can load the workflow file from any folder by selecting "custom" and click load.

![image](https://github.com/user-attachments/assets/9c876736-926a-4e5d-9435-f21bd92e883f)

Best,

Fengchao

**Comment by apsteinberg** [comment]
This worked perfectly. Thank you for the quick response!

Best,
Asher
