### ISSUE TITLE
Question about instrument settings in MSBooster

### ISSUE THREAD

**Issue by medardus333** [Nesvilab/FragPipe#1710]
Hi,

I would have following question: I'm using MSBooster via the GUI, but the search fails to detect the correct instrument for the Deep Learning Prediction. The log states I can set this via the parameter file with "instrument=". However, I could not find a list of instruments and how they are specified (in my case it is a Q-Exactive HF), and how can this be implemented when running the search from the GUI?

Is there also a possibility to set the TMT batch specific correction factors?

Thank you!

**Comment by fcyu** [comment]
I let Kevin answers this question because he knows it better, but if I remember it correctly, it is just a warning not an error. You can ignore it. 

Best,

Fengchao

**Comment by medardus333** [comment]
Hi Kevin,

thank you! I have uploaded an mzml to your dropbox.

Cheers

Florian

**Comment by yangkl96** [comment]
Hi Florian,

When I ran MSBooster 1.2.31, it was able to detect your mzML came from a QE instrument. Could you attach your log file? It's possible that the very first mzML read in was not detected as QE, in which case I would need to test on that first one (if you could upload that too).

To confirm, are you using DIA-NN or the Koina models with MSBooster? With DIA-NN, it will make no difference if it is read in as QE or not.

Best,
Kevin

**Comment by medardus333** [comment]
Hi Kevin,
that is interesting. I ran the search using the .raw files and the instrument was not detected, but I now also repeated with the mzML file and the instrument was detected. I used ProteoWizard to convert the raw to mzML.

I'm using DIA-NN for the RT prediction, the Prosit TMT model for the spectra prediction.

Cheers

Florian

**Comment by yangkl96** [comment]
Thanks for bringing this to my attention. When raw files are converted to mzml in FragPipe, the instrument information is lost, but conversion to mzml with ProteoWizard keeps that info. I will work on a fix for the next release, but in the meantime, your results should be unaffected, as only AlphaPeptDeep uses instrument information for its spectral predictions. PrositTMT does not use this information (https://koina.wilhelmlab.org/docs#post-/Prosit_2020_intensity_TMT/infer).

I will close the issue for now
