### ISSUE TITLE
Converting .d files to .mzML on linux-based HPC

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1712]
Hi all,

I am trying to execute a workflow similar to issue #1309, in which we build a spectral library using diaPASEF data. Do I need to convert these files to mzML format to build a spectral library from them? If so, how would you recommend doing this on a linux-based HPC? I see you have this repo here:

https://github.com/Nesvilab/msconvert-scripts

But it looks like these scripts are for conversion from .raw to .mzml but not for conversion from .d to .mzml?

Thanks for you time and help with this.

Best,
Asher

**Comment by fcyu** [comment]
No, it is always a bad idea to convert .d to mzML, which will make the data worse in most cases. The script you found is just for Thermo raw files. 

FragPipe can load the .d natively.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Got it that's great to know. I guess then I must have selected something incorrectly in my workflow then. I'm attaching the log file as well as the workflow and manifest I used. Is there something very obviously incorrect that I did here?

[trypsin_diapasef.zip](https://github.com/user-attachments/files/16514599/trypsin_diapasef.zip)

Apologies again if this is a very basic question. Appreciate your help here!

Best,
Asher

**Comment by fcyu** [comment]
No worries. For the diaPASEF data, you should use the DIA_SpecLib_Quant_**diaPASEF** workflow. Different from the DIA_SpecLib_Quant workflow, it applies diaTracer to perform the spectra deconvolution.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Got it, okay thank you!

I will give this a try now.

Best,
Asher

**Comment by apsteinberg** [comment]
Hi Fengchao,

I can confirm that this worked. Thank you for your help!

Best,
Asher

**Comment by fcyu** [comment]
No problem. I will close this issue, but feel free to contact us if you have any questions in the future.

Best,

Fengchao
