### ISSUE TITLE
Processing interrupted, stopping PTMProphet

### ISSUE THREAD

**Issue by ChenYouming98** [Nesvilab/FragPipe#1713]
**- Upload your log file**
Please wait. PTMProphet is running. It can take a long time.
Please wait. PTMProphet is running. It can take a long time.
Please wait. PTMProphet is running. It can take a long time.
[INFO:] Using statically set 15 PPM tolerance ... 
[INFO:] Writing file interact-H3_Slot2-11_1_7783.pep.xml.tmp.a19156 ...

[INFO:] Creating 1 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact-H3_Slot2-11_1_7783.pep.xml ...
​
[INFO:] processed 53000/53240 spectrum_queries		 
[INFO:] done ... 
[INFO:] Computing EM Models ... 
[INFO:] Iterating PTM Model: ....5....10done
[INFO:] done ... 
[INFO:] done ... 

[INFO:] Creating 1 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact-H3_Slot2-11_1_7783.pep.xml ...
​
[INFO:] written 17000/53240 spectrum_queries		 WARNING: running job exception ... std::bad_alloc ... exiting ... 

[INFO:] done ... 
[INFO:] Writing file interact-H3_Slot2-11_1_7783.mod.pep.xml ...
'chmod' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[INFO:] done ... 

command "chmod 664 interact-H3_Slot2-11_1_7783.mod.pep.xml" failed: Operation not permitted
Process 'PTMProphet' finished, exit code: 0
[INFO:] Using statically set 15 PPM tolerance ... 
[INFO:] Writing file interact-H1_Slot2-10_1_7766.pep.xml.tmp.a21036 ...

[INFO:] Creating 1 threads 
[INFO:] Wait for threads to finish ...
[INFO:] Reading file interact-H1_Slot2-10_1_7766.pep.xml ...
​
[INFO:] processed 65000/65970 spectrum_queries		 
[INFO:] done ... 
[INFO:] Computing EM Models ... 
[INFO:] Iterating PTM Model: ..WARNING: running job exception ... std::bad_alloc ... exiting ... 
WARNING: running job exception ... std::bad_alloc ... exiting ... 
.terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Process 'PTMProphet' finished, exit code: 3
Process returned non-zero exit code, stopping
Processing interrupted, stopping PTMProphet

~~~~~~~~~~~~~~~~~~~~
Cancelling 14 remaining tasks


**- Describe the issue or question:**

**Comment by fcyu** [comment]
I think it is due to not enough hard drive space or memory space.

Best,

Fengchao
