### ISSUE TITLE
workflow for IBT-16 isobaric tag analysis

### ISSUE THREAD

**Issue by shenghao003** [Nesvilab/FragPipe#1714]
Hello，Philosopher 5.1.0 has supported IBT-16 isobaric tag analysis, but I don't see the corresponding workflow in the latest version of fragpipe 22. Will it be updated?

**Comment by fcyu** [comment]
You can load one of the TMT workflows, adjust the variable modifications and the label type to IBT-16. I don't think it is a good idea to enumerate all possible labels to generate many "duplicated" workflows.

![image](https://github.com/user-attachments/assets/c9792318-9f84-410a-931a-d4c39b620634)

Best,

Fengchao
