### ISSUE TITLE
Optimizing the Identification Results

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1717]
Dear respected author, hello!
 I am currently conducting the database search work of immune peptidomics.
May I ask, apart from simply setting the threshold of peptide false discovery rate (pep FDR), if I aim to enhance the authenticity of the identification results, what kind of filtering measures should I adopt?
 I wonder if you have any excellent suggestions? Thank you very much!

Best,
Anler

**Comment by fcyu** [comment]
You could try out group FDR (https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html) and two-pass search (https://fragpipe.nesvilab.org/docs/tutorial_two_pass_search.html) approach.

Best,

Fengchao

**Comment by amingson** [comment]
> You could try out group FDR (https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html) and two-pass search (https://fragpipe.nesvilab.org/docs/tutorial_two_pass_search.html) approach.
> 
> Best,
> 
> Fengchao



Thank you for your assistance. I deeply apologize for not providing you with a response promptly!

Best,
Anler
