### ISSUE TITLE
Error message generated when used Frapipe(v19.1)

### ISSUE THREAD

**Issue by FragPipe** [Nesvilab/FragPipe#1718]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-08-08_14-19-53.zip](https://github.com/user-attachments/files/16552044/log_2024-08-08_14-19-53.zip)

**- Describe the issue or question:**
I have been trying to use the FragPipe(v20.0) and FragPipe(v19.1). But unfortunately an error message was generated while using it and the run stopped. I have attached the error message generated with respect to (v19.1).
I would like to know how this matter could be resolved. 
![Fragpipe(v19 1)08072024](https://github.com/user-attachments/assets/ba423ab7-9f60-436f-8de9-dbf18d969e7d)

**Comment by yangkl96** [comment]
I can't confirm if you are using the newest MSFragger because your log file is empty, but it is incompatible with the old versions of MSBooster. Please upgrade to the newest FragPipe release: https://github.com/Nesvilab/FragPipe/releases

**Comment by FragPipe** [comment]
I am using the old version (v19.1).

**Comment by yangkl96** [comment]
Yes, can you please upgrade to FragPipe 22.0: https://github.com/Nesvilab/FragPipe/releases/tag/22.0? Or if you would like to stick to 19.1, you will need to use an older version of MSFragger

**Comment by FragPipe** [comment]
I downloaded the new version. (v22.0)
[log_2024-08-08_15-33-02.zip](https://github.com/user-attachments/files/16552629/log_2024-08-08_15-33-02.zip)

But when I clicked the Fragpipe Windows Batch File, the following messages were generated -1, 2

In the Run of Fragpipe, the following message was encountered. -3
![1 V22 2](https://github.com/user-attachments/assets/20a6ce1f-3dfb-4126-a388-e55dcdf13031)
![2  V22 2](https://github.com/user-attachments/assets/96e6adb2-314d-4062-aff9-559916fed127)
![3  Run](https://github.com/user-attachments/assets/ed5386fe-2659-481e-8420-6b89cf14f304)

**Comment by fcyu** [comment]
I refuse to answer any FragPipe-related questions to "FragPipe" because I see it as a violation of our intellectual property. Please change your user name.

**Comment by FragPipe** [comment]
I will change the profile name
