### ISSUE TITLE
Generation of error message while using FragPipe (v22.0)

### ISSUE THREAD

**Issue by Lab123-prog** [Nesvilab/FragPipe#1719]
**- Uplo
[log_2024-08-08_16-43-45.zip](https://github.com/user-attachments/files/16553247/log_2024-08-08_16-43-45.zip)
ad your log file**

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
I downloaded the new version. (v22.0)
But when I clicked the Fragpipe Windows Batch File, the following messages were generated -1, 2
In the Run of Fragpipe, the following message was encountered. -3

![1 V22 2](https://github.com/user-attachments/assets/52b5534b-c8a4-4890-b182-f5d96d8abfb0)
![2  V22 2](https://github.com/user-attachments/assets/2d09d535-829d-432a-bd06-de0d22450ae9)
![3  Run](https://github.com/user-attachments/assets/22ab74bc-b005-4e2c-b6cd-16b8a530d775)

**Comment by fcyu** [comment]
Could you go to the "config" tab and click "clear cache and close" at the top? Then, start FragPipe again to see if the error presists.

Best,

Fengchao

**Comment by Lab123-prog** [comment]
I tried it.
Next, I performed a run and it finished within 7 minutes. When I checked the generated combined_protein.tsv file the intensities for each sample was zero.
![time](https://github.com/user-attachments/assets/fc1be54a-0000-47db-baf8-3e6d37073bfd)

**Comment by fcyu** [comment]
If your data is DDA, could you try the LFQ-MBR workflow?

Best,

Fengchao

**Comment by Lab123-prog** [comment]
Yes, its DDA 
I did select LFQ-MBR as the workflow.

**Comment by fcyu** [comment]
Have you download IonQuant in the config tab of FragPipe? If not, please download it again by clicking "download".

Best,

Fengchao

**Comment by Lab123-prog** [comment]
I did download it.
But I can try it again.

![workflow](https://github.com/user-attachments/assets/d1b141d2-2e98-457d-a793-001b9cb83718)

**Comment by fcyu** [comment]
Did you click "load" after selecting the workflow? If yes, could you share your log file with the name starting with `log_2024`?

Thanks,

Fengchao

**Comment by Lab123-prog** [comment]
No, I didn't .

Thank you. I will try it out.

Can I please know how to unselect the FreeQuant under MS1 qunatification?
![remove](https://github.com/user-attachments/assets/e1849a9c-1263-4725-8ffd-dcd843148f3a)

**Comment by fcyu** [comment]
Click "IonQuant" at the top.

Best,

Fengchao

**Comment by Lab123-prog** [comment]
Thank you.

**Comment by Lab123-prog** [comment]
Thank you so much for your assistance. I was able to generate the data files.

**Comment by fcyu** [comment]
No problem. I will close this issue. Feel free to contact us if you have any questions in the future.

Best,

Fengchao
