### ISSUE TITLE
Crashed with 2 space searches

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#1720]
Hi,

I ran a set of raw files and all went smoothly when I used one space search (e.g uniprot entries only) but when I performed multiple space search it kept failing. I don't know what makes crash fragpipe. Could you please have a look at the log file and let me know?

Thank you 

HuiSong
[log_2024-08-08_15-28-43.txt](https://github.com/user-attachments/files/16558755/log_2024-08-08_15-28-43.txt)

**Comment by fcyu** [comment]
Hi Hui Song,

The error was thrown by DIA-Umpire before the database searching, so it is not about different search space. Could you double check if there are enough space in the hard drive, and try again?

Thanks,

Fengchao

**Comment by hupak2022** [comment]
Hi Fengchao,


I just checked and I do have something like 900gb. IT should be enough right?

Anyway, I will run again


Thank you


Best


HuiSong


CHUV
centre hospitalier universitaire vaudois

UNIL
université de Lausanne

DrSc. Hui Song PAK, Responsable de recherche
Centre de thérapie expérimentale/unité immunopeptidomics
Département d'oncologie
Bureau 04 - 172
Agora Research Center, Rue du Bugnon 25A, CH-1005 Lausanne
Tel. 021 314 65 72
***@***.******@***.***>
www.chuv.ch<https://oweb.chuv.ch/owa/redir.aspx?C=TL7dYQf_ELiPpqJD77prbSFaZvIQ-8x5jpWNcU72-7okFXOHOA7UCA..&URL=http%3a%2f%2fwww.chuv.ch%2f>
________________________________
De : Fengchao ***@***.***>
Envoyé : vendredi, 9 août 2024 15:52:21
À : Nesvilab/FragPipe
Cc : Pak Hui Song; Author
Objet : Re: [Nesvilab/FragPipe] Crashed with 2 space searches (Issue #1720)


Hi Hui Song,

The error was thrown by DIA-Umpire before the database searching, so it is not about different search space. Could you double check if there are enough space in the hard drive, and try again?

Thanks,

Fengchao

**Comment by hupak2022** [comment]
Hi,

It still keep crashing... do you think it could be related to fastA?
Thank you

**Comment by fcyu** [comment]
I don't think so because

> The error was thrown by DIA-Umpire **before** the database searching, so it is not about different search space. Could you double check if there are enough space in the hard drive, and try again?
> 
> Thanks,
> 
> Fengchao

**Comment by hupak2022** [comment]
I'm saying that because with regular Uniprot fastA with 1 space serach it passed smoothly.




Im-------- Message d'origine --------
De : Fengchao ***@***.***>
Date : 11.08.24 20:40 (GMT+01:00)
À : Nesvilab/FragPipe ***@***.***>
Cc : Pak Hui Song ***@***.***>, Author ***@***.***>
Objet : Re: [Nesvilab/FragPipe] Crashed with 2 space searches (Issue #1720)


I don't think so because

The error was thrown by DIA-Umpire before the database searching, so it is not about different search space. Could you double check if there are enough space in the hard drive, and try again?

Thanks,

Fengchao
