### ISSUE TITLE
Unknown file type error in peptide prophet during open search

### ISSUE THREAD

**Issue by vikascinderbio** [Nesvilab/FragPipe#1723]
**- Upload your log file**
[log_2024-08-10_13-37-26.txt](https://github.com/user-attachments/files/16571619/log_2024-08-10_13-37-26.txt)

**- Describe the issue or question:**
Error "Unknown File Type. No File Loaded" received from peptide prophet during an open search. Please advise on what I did wrong.

Thanks.

**Comment by fcyu** [comment]
The PeptideProphet modeling failed. Please provide more files in the search.

```shell
Iterations: .........10.........20........WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
.30
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 31 iterations

...

...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05
```

Best,

Fengchao

**Comment by vikascinderbio** [comment]
Compressed output directory attached:
[Results_60min_Open_Search.zip](https://github.com/user-attachments/files/16574055/Results_60min_Open_Search.zip)

Raw file is too large to attach. Please advise on how to get it to you if you need it.

Vikas

**Comment by anesvi** [comment]
You are doing nonspecific open search. This is a very advanced search that we do not provide a default workflow for. So please stick to either nonspecific or open, but not both at the same time

**Comment by anesvi** [comment]
Or contact us directly to discuss the details of your experiment

**Comment by vikascinderbio** [comment]
Understood. Had the same error with semi-specific. Is that also not compatible with the default "open search" workflow?
Associated log file: 
[log_2024-08-10_21-29-20.txt](https://github.com/user-attachments/files/16574126/log_2024-08-10_21-29-20.txt)

To test a hunch I changed the name of the raw file and re-ran semi-specific. This time it worked.
Associated log file:
[log_2024-08-11_08-10-11.txt](https://github.com/user-attachments/files/16574130/log_2024-08-11_08-10-11.txt)

Will contact directly on the nonspecific coupled with open search question. Thank you.

Vikas

**Comment by fcyu** [comment]
Hi Vikas,

For the first semi-specific one, the reason is that the enzyme name "Krakatoa" is not supported. After you replaced it with "nonspecific", it works according to the second log file

Best,

Fengchao

**Comment by vikascinderbio** [comment]
Got it. Thank you.VikasSent from my iPhoneOn Aug 11, 2024, at 09:13, Fengchao ***@***.***> wrote:﻿
Hi Vikas,
For the first semi-specific one, the reason is that the enzyme name "Krakatoa" is not supported. After you replaced it with "nonspecific", it works according to the second log file
Best,
Fengchao
