### ISSUE TITLE
Fragpipe crash with custom enzyme

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1725]
Hi there,

I am trying to run Fragpipe in headless mode with a custom enzyme using the DIA_SpecLib_Quant_diaPASEF workflow. It appears to be crashing at the end of the diaTracer step completes, and I am not sure why. Here is a link to the log, workflow and manifest:

[github_issue.zip](https://github.com/user-attachments/files/16575771/github_issue.zip)

Any clues as to what I've done wrong here? Thanks for your time and help.

Best,
Asher

**Comment by fcyu** [comment]
Hi Asher,

Sorry for the late reply. I thought I have replied this one but actually I haven't.

Could you check if there are `analysis.tdf` in the `/data1/shahs3/users/preskaa/proteomics/A673_Proteogenomics/Multienzyme_MSK_Core_July_2024/ProAlanase/A673_Proalanase_F42_Slot2-54_1_2963.d` folder?

Thanks,

Fengchao
