### ISSUE TITLE
changed column header in FP22 psm.tsv output

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#1726]
Dear FP Developers

We've recently updated to the newest release of FragPipe (v.22) and realized, that the column header of the psm.tsv changed from "PeptideProphet Probability" to "Probability". This breaks compatibility with the Scaffold5 import functionality for FragPipe results. Hence I'd like to clarify, if the "Probability" column still corresponds to the "PeptideProphet Probability" column of earlier FragPipe psm.tsv outputs? If yes, what was the reason for the change in column headers? If not, could you please quickly explain the difference to older psm.tsv files? 

Thank you very much for your reply. I hereby just want to ensure that our workaround (renaming the respective column) and the respective issue report to ProteomeSciences (Scaffold) is not based on an accidental renaming...

Best,
Christian

**Comment by fcyu** [comment]
> Hence I'd like to clarify, if the "Probability" column still corresponds to the "PeptideProphet Probability" column of earlier FragPipe psm.tsv outputs?

Yes.

> If yes, what was the reason for the change in column headers? If not, could you please quickly explain the difference to older psm.tsv files?

Because it is not always generated by PeptideProphet.

Best,

Fengchao
