### ISSUE TITLE
Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1727]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-08-14_06-33-45.txt](https://github.com/user-attachments/files/16610568/log_2024-08-14_06-33-45.txt)

**- Describe the issue or question:**
Hi,
I am trying to run the Nonspecific_HLA_diaPASEF workflow but my search kept crashing. could you please help me take a look. Thank you very much. 
Best,
Trung

**Comment by fcyu** [comment]
It seems that you were actually using the wrong workflow, or the `Nonspecific_HLA_diaPASEF` one was not loaded after you selected it. You need to click "load" to load the workflow.

Best,

Fengchao
