### ISSUE TITLE
Not all given paths exist: Process 'Rewrite pepxml' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by FlashN01** [Nesvilab/FragPipe#1729]
[log_2024-08-11_13-11-16.txt](https://github.com/user-attachments/files/16617088/log_2024-08-11_13-11-16.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
When running DIA via the DIA_DIA-Umpire_SpecLib_Quant workflow, both Umpire and MSFragger analyses succeed, but peptideprophet fails due to an apparent missing file.   What is especially odd, is that the file that is missing, (a _Q3_c.pep.xml) is one that is made by the workflow itself.  It may be of note that we are attempting to use a spectral library generated from DDA data for the same samples.

This process returns an exit code of '1' for the process 'Rewrite pepxml'

**Comment by fcyu** [comment]
I am pretty sure that you did not load the `DIA_DIA-Umpire_SpecLib_Quant` workflow successfully according to your log:

```shell
Execution order:

    Cmd: [START], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [CheckCentroid], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [WorkspaceCleanInit], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [UmpireSe], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [diaTracer], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [MSFragger], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [Crystal-C], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PeptideProphet], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PTMProphet], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [ProteinProphet], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PhilosopherDbAnnotate], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PhilosopherFilter], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PhilosopherReport], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [PTMShepherd], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [WorkspaceClean], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [SpecLibGen], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
    Cmd: [DIA-NN], Work dir: [D:\Fragpipe_Export\DDADIATest108072024]
```

Please not that you need to click "**load**" after selecting the workflow.

Best,

Fengchao
