### ISSUE TITLE
Error when searching timsTOF data with Fragpipe v22 version

### ISSUE THREAD

**Issue by humility3239** [Nesvilab/FragPipe#1731]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[result_0816.zip](https://github.com/user-attachments/files/16634969/result_0816.zip)

![image](https://github.com/user-attachments/assets/4c1c492d-8135-49e1-98f3-ece0a217957c)

**- Describe the issue or question:**
As shown in the title, when using Fragpipe v22 to search the data collected by the TimsTOF instrument, an error was reported, indicating that the file may be corrupted, or there may be a precursor 272435 mismatch when reading the PASEF spectra. how to fix the bugs?

**Comment by fcyu** [comment]
Your .d folder was corrupted. 

Best,

Fengchao
