### ISSUE TITLE
Problem with IonQuant at the end of running IsoDTB analysis

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#1732]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

We run the analysis of IsoDTB data but it crashes when performing IonQuant at the end.

[log_2024-08-14_18-20-16.txt](https://github.com/user-attachments/files/16640613/log_2024-08-14_18-20-16.txt)

**Comment by fcyu** [comment]
This bug has been fixed in the latest version. Could you upgrade FragPipe, MSFragger, and IonQuant, and try again?

Thanks,

Fengchao
