### ISSUE TITLE
Error when running glyco-N-HCD workflow on FP 22

### ISSUE THREAD

**Issue by yishai99** [Nesvilab/FragPipe#1735]
[log_2024-08-18_11-06-17.txt](https://github.com/user-attachments/files/16647658/log_2024-08-18_11-06-17.txt)

Hi, I tried processing N glyco samples that ran on the timsTOF Pro with the glyco-N-HCD workflow on FP 22 and got the attached error. Can you tell what's wrong?
Thanks,
Yishai

**Comment by fcyu** [comment]
It was due the same reason as https://github.com/Nesvilab/FragPipe/issues/1734. 

You might consider switching to Percolator. 

But note that for the glyco workflow, PeptideProphet performs better than Percolator. It is different from the closed search where Percolator is better than PeptideProphet.

Best,

Fengchao
