### ISSUE TITLE
Query regarding open search mode: how is it analyzed in the MS2 spectra

### ISSUE THREAD

**Issue by bluemooninvestor** [Nesvilab/FragPipe#1737]
Hi

I am trying to use the Open Search mode in Fragpipe, and I am getting some hits. For example, I am getting few PSMs with a 500 Da shift. However, when I look at the MS2 spectra for that particular 500 shifted PSM, I am finding that the observed ions are all corresponding to the unshifted PSM. My questions are:

1) What does the open search algorithm look for in MS2? Does it look for unshifted or shifted spectra? Which one is default and can it be changed by the user?

*** I also glanced the publication about the labile mode where the MS2 spectra is  analyzed assuming that the modifications are labile and gets lost during MS2 fragmentation. But I am not using the labile mode. 

2) I noticed that the particular PSM I chose lacked localization information (in the Mod file produced by PTM-Shepherd). Can I expect to see the mass shifted MS2 spectra in cases where localization data is present? 

Even then, I would like to know what is the default assumption made by the algorithm. Does the algo continue to look for unshifted ions, because multiple ions would still be unshifted even if one of the residues is modified?

Thank you in advance.

**Comment by fcyu** [comment]
> What does the open search algorithm look for in MS2? Does it look for unshifted or shifted spectra? Which one is default and can it be changed by the user?

Yes, it look for both shifted and unshifted peaks in the spectra by default. Please check our publication about it https://www.nature.com/articles/s41467-020-17921-y. 

I am not sure which tool you used to visualize the spectra, but I guess it didn't shift the peaks according to the delta mass.

> I also glanced the publication about the labile mode where the MS2 spectra is analyzed assuming that the modifications are labile and gets lost during MS2 fragmentation. But I am not using the labile mode.

Labile search is another topic, which I guess is not what you wanted.

> Can I expect to see the mass shifted MS2 spectra in cases where localization data is present?

Yes, but the non-labile case.

> Even then, I would like to know what is the default assumption made by the algorithm. Does the algo continue to look for unshifted ions, because multiple ions would still be unshifted even if one of the residues is modified?

I guess you should read some literatures first. Starting from https://www.nature.com/articles/nmeth.4256 and https://www.nature.com/articles/s41467-020-17921-y

Best,

Fengchao

**Comment by bluemooninvestor** [comment]
I will read the literature as suggested. I was observing the spectra in Fragpipe-PDV Viewer but found no shifts

**Comment by fcyu** [comment]
Thanks for the update. FragPipe-PDV does not use the delta mass and MSFragger localization information. You need to specify the location of the delta mass using the "change modifications" option:

![image](https://github.com/user-attachments/assets/3816e1e5-23e3-406b-a0f7-81d0d770a958)

Best,

Fengchao

**Comment by bluemooninvestor** [comment]
Thank you Dr Fengchao
