### ISSUE TITLE
PTMShepherd returned non-zero exit code

### ISSUE THREAD

**Issue by ZZigeaeC** [Nesvilab/FragPipe#1739]
**- Describe the issue or question:**
[log_2024-08-20_11-52-46.txt](https://github.com/user-attachments/files/16680639/log_2024-08-20_11-52-46.txt)

Hey, 
I was using the Open workflow to detect any PTM and hoping to assign them to specific amino acid residues, and I've done this for multiple samples already. 
Recently, upon getting a new sample, I kept receiving error messages [log updated]. Initially I suspected if there's something wrong with my settings so I used some old mzml files to test it, and the program run perfectly.  

1. Can you please help me identify where the error comes from? Is it about the setting, or is it about my file? 
2.  I do see a pepXML output file being generated, however when I try to put it through GNPS2 analysis it failed to analyze it. Is it because of the pepXML file being compromised, or is there any other way I can still view and analyze the pepXML file? 
 
Thank you.

**Comment by dpolasky** [comment]
Hi @ZZigeaeC,
The error is from finding no PSMs in the file. Usually this means there's a problem with the search settings, but if it worked for a different file with the same settings (and the files are of the same type of sample and same processing), then more likely it is an issue with the new file. 

I'm not familiar with GNPS2, but you can inspect the pepXML with any text editor. There's no reason to suspect that it is compromised based on the log, but it likely has only a few results in it. 

Best,
Dan

**Comment by ZZigeaeC** [comment]
> Hi @ZZigeaeC, The error is from finding no PSMs in the file. Usually this means there's a problem with the search settings, but if it worked for a different file with the same settings (and the files are of the same type of sample and same processing), then more likely it is an issue with the new file.
> 
Hi Dan, thanks for the reply. Actually after you mentioned, the sample processing were different.  Would you mind help me determine what parameters I can toggle with, to expand the search? No PSMs in the file seems to be impossible for me. Normally they would have oxidation or methylation sites across but now there's nothing.

**Comment by dpolasky** [comment]
The usual suspects for losing all PSMs are things that change all or most peptides, so fixed modifications (e.g., changes to alkylation or derivatization), enzyme digestion, a different species than what's in the fasta, etc. Without knowing more about your sample and the differences in processing it's hard to make a guess, but you can find the reference for all the parameters and how to adjust them on our website (fragpipe.nesvilab.org and https://github.com/Nesvilab/MSFragger/wiki)

Best,
Dan

**Comment by ZZigeaeC** [comment]
Thank you Dan. 
After I increased the tolerance, the program could run without problem.

**Comment by dpolasky** [comment]
Great, glad to hear it! I will close the issue now, but feel free to contact us if you have other issues. 

Best,
Dan
