### ISSUE TITLE
total/unique/razor Peptides in protein.tsv table

### ISSUE THREAD

**Issue by martyq91** [Nesvilab/FragPipe#1740]
Hi team, I have just recently started using FragPipe (and am fairly new to proteomics) and have a question regarding the unique/razor peptide concept. Razor peptides are shared peptides and can be assigned to multiple proteins whereas unique peptides do not map to other identified proteins - so far so good. Consequently, an identified protein can have 0 unique peptides but >= 1 razor peptides. What I do not understand is how it is possible that I have, for example, 25 total peptides for a given protein but 0 unique and 0 razor peptides (see screenshot attached from the protein.tsv table for one sample)? And should the Total Peptides column not always be the sum of razor + unique peptides? Unfortunately, I cannot share much of the output with you due to compliance issues. Thanks a lot for your help already in advance, it is well appreciated. 

![FragPipe_unique_razor_peptides](https://github.com/user-attachments/assets/2d092317-2f84-40a5-beb9-07c97b98b760)

**Comment by fcyu** [comment]
Could you share your log file (the file name starts with `log_2024`) and protein.tsv with us?

Thanks,

Fengchao

**Comment by martyq91** [comment]
Hi Fengchao, thanks for your swift reply. I will double check but I'm afraid I cannot share the log file and the protein.tsv is a definite no, unfortunately. Are there certain keywords I could read out from the .txt log file and from the protein.tsv without sharing the entire file that would help you? Sorry about this complication.

**Comment by fcyu** [comment]
No worries. I think you got the numbers wrong. That was why I need to take a look and count by myself.

Best,

Fengchao

**Comment by martyq91** [comment]
Just to clarify, if a peptide was identified by a match-between-run, it would neither be categorized as a razor nor as a unique peptide? This particular case is from the protein.tsv table though. I see 25 peptides that are associated with that particular protein when I look into the peptide.tsv table, however said protein (25 total peptides, 0 razor, 0 unique) is in the "Mapped Proteins" column and not in the "Protein" column.

**Comment by fcyu** [comment]
> however said protein (25 total peptides, 0 razor, 0 unique) is in the "Mapped Proteins" column and not in the "Protein" column.

This is exactly why I needed to take a look at your protein.tsv. The proteins in the "Mapped proteins" are not "identified". They are have zero unique and razor peptides.

Best,

Fengchao

**Comment by martyq91** [comment]
I understand that sharing log files and output tables is the easiest way to resolves issues and am myself at times annoyed that it does not work like this in corporate life, but I really appreciate your patience and understanding. 

If this protein is not identified, how does it end  up in the protein.tsv table in the Protein column? If there is a resource where this is explained in more detail, I would appreciate it if you could direct me to it. Thanks!

**Comment by fcyu** [comment]
> If this protein is not identified, how does it end up in the protein.tsv table in the Protein column?

Didn't you just said "however said protein (25 total peptides, 0 razor, 0 unique) is in the "Mapped Proteins" column and **not** in the "Protein" column."? 

There are two different columns. Please read our tutorial https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html

Best,

Fengchao

**Comment by fcyu** [comment]
Can you tell me exactly how you count those total, unique, and razor peptides for the specific protein in protein.tsv?

Thanks,

Fengchao

**Comment by martyq91** [comment]
Yes, I did say that. However, we are talking about two different tables here: 

1.) peptide.tsv: protein x is in the Protein colum. It has 25 total peptides, 0 unique peptides, 0 razor peptides
2.) peptide.tsv: protein x is not in the Protein column, but in the Mapped Proteins column.

I did read your documentation and all related GitHub entries and did not find an answer to my question, ergo this threat came to life. Again, this is raw data from Fragpip without any prior manipulation. There was no counting or anything else happening on my side. It says even in the documentation that these columns (unique, razor, total as integers) are in the protein.tsv output. I will double check if there is a way to share data.

**Comment by fcyu** [comment]
Thanks for the clarification. I think there is either a bug in the program or an issue when counting the numbers. Either way, I can't confirm or debug unless you share all of the files including the input mzML/raw files, fasta files, and log files.

Best,

Fengchao

**Comment by anesvi** [comment]
If you are in a company and cannot share the data, we can have a zoom call and look that way. Or you can repeat the search using public data to replicate your issue. Please make sure you have an active commercial license for our tools though (unless you just downloaded for evaluation). 
Best,
Alexey

**Comment by martyq91** [comment]
Hi Alexey, thanks for your input. I will try to replicate the issue with publically available data. However, we would appreciate a quick zoom call regardless, thanks for the offer - I will reach out via email. We recently purchased licenses for FragPipe and IonQuant.

**Comment by anesvi** [comment]
Sure, email me at nesvi at med.umich.edu or directly Fengchao if you like.
