### ISSUE TITLE
Allow Multiple Variable Mods on Residue

### ISSUE THREAD

**Issue by roofj01** [Nesvilab/FragPipe#1742]
Hello!

I am trying to search for a peptide on a protein N-terminus that may be N-terminally acetylated, oxidized, or both. The N-terminal residue is a methionine. I am not sure whether Fragger distinguishes between the N-terminus and the first residue in terms of modifications, so I was trying to allow multiple variable mods on the same residue. 

I see in the console/parameters file that there is an option for "allow_multiple_variable_mods_on_residue" that is default to 0 but do not see an option for changing this in the Fragger interface. The workflow files also do not have this option. I have tried changing it in the fragger.params file and loading it in as a custom file, but it doesn't end up changing it during the search in Fragpipe. 

Where would I go to change the default on this parameter?

Thanks!

**Comment by fcyu** [comment]
You'd better add a variable modification corresponding to the "both" case instead of enabling the allow_multiple_variable_mods_on_residue because not all downstream tools support it smoothly,

Best,

Fengchao

**Comment by roofj01** [comment]
Okay, thank you!
