### ISSUE TITLE
Cannot perform mass calibration, too few confidently identified precursors

### ISSUE THREAD

**Issue by shenghao003** [Nesvilab/FragPipe#1745]
Hello,fengchao.I was recently doing a test, using the DDA library I built to analyze DIA samples, but I found that some samples could not be quantified as shown in the figure. Have you encountered similar problems, or have you any comments?

![图片](https://github.com/user-attachments/assets/4b67424b-60d2-41a2-a29a-9084b3a8cc63)

Thanks.

**Comment by fcyu** [comment]
It is mostly because there are no IDs in that specific sample.

Best,

Fengchao

**Comment by shenghao003** [comment]
Hello,I have a total of 101 samples and found that this happens in 1/3 of the Fragpipe. When I analyzed these abnormal samples using spectronaut, the results were normal.

**Comment by fcyu** [comment]
Then, something was wrong with your parameter settings. Could you share your log and fasta files.

Thanks,

Fengchao

**Comment by shenghao003** [comment]
[log_2024-08-25_00-08-06.txt](https://github.com/user-attachments/files/16783842/log_2024-08-25_00-08-06.txt)

**Comment by fcyu** [comment]
It seems that you use your own library.tsv as input and only run DIA-NN quant. How did you generate your library.tsv? Did Spectronaut run normally with your library.tsv file (`/jdfsyt2/BC_PT/USER/huangshenghao/database/dda_lib/human/mzml/result/library.tsv`)?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Could you share the log file of the FragPipe library generation?

Thanks,

Fengchao

**Comment by shenghao003** [comment]
[log_ddalib.txt](https://github.com/user-attachments/files/16784151/log_ddalib.txt)

**Comment by fcyu** [comment]
Thank you for the prompt response. The spectral library generation seems OK. Then, my guess is that your diaPASEF runs have different mass and RT windows. Could you add `--individual-mass-acc --individual-windows` to the "cmd line opts" when running the DIA quantification?

![image](https://github.com/user-attachments/assets/18eb18d2-b865-4e26-8f30-43c38d4f1dd2)

If it still has issues, maybe you can try our new library-free approach for the diaPASEF data: the "DIA_SpecLib_Quant_diaPASEF" workflow in the FragPipe version 22.0. You need to set the diaPASEF data to the "DIA" data type.

Best,

Fengchao

**Comment by shenghao003** [comment]
Thank you for your prompt reply.
I am using Fragpipe for Linux, how do I add it

**Comment by fcyu** [comment]
Actually, you just need to enable the "unrelated runs" (I have edited my previous message). When running in command line interface, set `diann.unrelated-runs=true` in the workflow file.

Best,

Fengchao

**Comment by shenghao003** [comment]
Okay, thank you very much. I'll test it again.
