### ISSUE TITLE
How does the “single combined pepxml file per experiment/group” option work?

### ISSUE THREAD

**Issue by SamuelLozanoJuarez** [Nesvilab/FragPipe#1746]
Hi,

I'm using FragPipe v22.0 to perform Open Search on a dataset, and I have seen that there is an option in the “Validation” module, specifically in “PSM Validation”, called “single combined pepxml file per experiment/group”.

When doing Open Search this option is checked by default, and as a consequence of checking or unchecking this option the number of peptides identified in the _ion.tsv_ file varies significantly.

I have searched the documentation but nowhere does it describe how this option “single combined pepxml file per experiment/group” works. Please help me to understand how it affects the number of peptides identified and whether or not it is advisable to leave this option checked in Open Search.

Thank you very much.

**Comment by anesvi** [comment]
Yes, what we set as defaults is what we advise. In open search, in PeptideProphet, PSMs with different mass shifts are modeled differently. Pulling all data together increases the number of PSMs in each mass shift bin, making it more robust
