### ISSUE TITLE
Unable to handle spaces in path strings

### ISSUE THREAD

**Issue by Usman095** [Nesvilab/FragPipe#175]
Hi,
I'm getting the following error near the end of the execution:
![image](https://user-images.githubusercontent.com/6886675/76022787-d4e50a00-5ef5-11ea-9c10-0678634697d3.png)

Is there a workaround for this or is there a timeline on when it might get a fix?

Thanks,
Usman

**Comment by guoci** [comment]
@Usman095 try this fix:
https://drive.google.com/file/d/1aHqb_BRgWPRK0zzVpyulBsYw0ycwcJgH/view?usp=sharing

**Comment by guoci** [comment]
@Usman095 try this fix:
https://drive.google.com/file/d/1aHqb_BRgWPRK0zzVpyulBsYw0ycwcJgH/view?usp=sharing

**Comment by fcyu** [comment]
No feedback after 11 days.
