### ISSUE TITLE
FP crash

### ISSUE THREAD

**Issue by TimKarr** [Nesvilab/FragPipe#1751]
[log_2024-08-25_23-50-13.zip](https://github.com/user-attachments/files/16751272/log_2024-08-25_23-50-13.zip)

FP crashes inexplicably at the "MSBooster" stage.

Thanks,
Tim

**Comment by yangkl96** [comment]
This issue has been fixed in the most recent FragPipe release: https://github.com/Nesvilab/FragPipe/releases/tag/22.0
