### ISSUE TITLE
FragPipe v22.0 Skyline launch issue? "Application cannot be started"

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#1760]
I upgraded FragPipe from 21.1 to 22.0 and when I started FragPipe, I got an error message "Application cannot be started. Contact the application vendor" in a popup window. It provided an error log, which I have attached, along with screenshots. 

After I hit "Ok", FragPipe started and I got the normal GUI window. The log seems to indicate it is an issue with Skyline? I have upgraded to 22.0 on another computer and have not had any issues. Just wanted to flag this and see if it will affect anything.

Thanks,
Josh

![image](https://github.com/user-attachments/assets/550e3d76-c86a-4448-9c95-54eab2434d3d)
![image](https://github.com/user-attachments/assets/99e48132-74bf-44f9-b2ac-a2c449fb7a65)
[OI4XDPJ4.log](https://github.com/user-attachments/files/16805505/OI4XDPJ4.log)

**Comment by fcyu** [comment]
Seems to be an issue in Skyline. Could you create a ticket in https://skyline.ms/project/home/support/begin.view ?

Thanks,

Fengchao
