### ISSUE TITLE
Change intrsument form Lumos to QE

### ISSUE THREAD

**Issue by alima82** [Nesvilab/FragPipe#1761]
[log_2024-08-30_16-24-53.txt](https://github.com/user-attachments/files/16821446/log_2024-08-30_16-24-53.txt)

**- Describe the issue or question:**
Hello team,

I'm trying to process some DDA data from QE and i'me getting the message"
Process 'MSBooster' finished, exit code: -1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 82 remaining tasks"

I have uploaded the log. 
Thank you in advance.
Lari

**Comment by fcyu** [comment]
It might be because one of the library is missing: Microsoft Visual C++ Redistributable is missing. Please download at https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

Best,

Fengchao

**Comment by alima82** [comment]
It worked!!
