### ISSUE TITLE
"Cannot deploy asset. ProteinProphet" Astral DIA Data, Windows Headless

### ISSUE THREAD

**Issue by chad-hyer** [Nesvilab/FragPipe#1762]
Hey. I am running FragPipe headless on windows on some DIA Astral data and am running into an issue where ProteinProphet is not deploying. I have made it through the entire workflow with other Astral DIA data in the past, so I'm not sure why it is crashing out at this step. Earlier, I was having issues with running out of memory on this dataset, so I suspect that the error is related to that. The command I ran was:

`bin/fragpipe.bat --headless --workflow workflows/IPSA_DIA_Quant_CH1125_C.workflow --manifest G:/CH1125/C_DIA_Methods/C_Old/C_Old_FP/C_Old.fp-manifest --workdir G:/CH1125/C_DIA_Methods/C_Old/C_Old_FP --config-tools-folder tools`

I've attached the log, manifest, and workflow files. Please advise.

Thanks,
Chad Hyer

[C_Old.txt](https://github.com/user-attachments/files/16822174/C_Old.txt) (Manifest)
[IPSA_DIA_Quant_CH1125_C.txt](https://github.com/user-attachments/files/16822175/IPSA_DIA_Quant_CH1125_C.txt) (Workflow)
[C_Old_log.txt](https://github.com/user-attachments/files/16822176/C_Old_log.txt) (Log)

**Comment by anesvi** [comment]
Perhaps Fengchao would know what that issue is. However, looking at your log, I also see you are doing a very unusual search with many PTMs. This is not a good idea to add so many variable mods for DIA data, even narrow window, unless there is a good reason to do so and you understand the tools well.

**Comment by fcyu** [comment]
I think Philosopher couldn't put the ProteinProphet to the temp folder due to some unknown reasons, mostly due to file system or antivirus software.

@chad-hyer could you try again by reruning from protein inference? You can uncheck MSFragger, MSBooster, Percolator, and PTM localization.

Best,

Fengchao

**Comment by chad-hyer** [comment]
> Perhaps Fengchao would know what that issue is. However, looking at your log, I also see you are doing a very unusual search with many PTMs. This is not a good idea to add so many variable mods for DIA data, even narrow window, unless there is a good reason to do so and you understand the tools well.

The PTM search is for a specific use case. It is computationally heavy, but it is very important to the work we do. We have gotten it to work multiple times before. It just definitely opens up several problems for us.



> I think Philosopher couldn't put the ProteinProphet to the temp folder due to some unknown reasons, mostly due to file system or antivirus software.
> 
> @chad-hyer could you try again by reruning from protein inference? You can uncheck MSFragger, MSBooster, Percolator, and PTM localization to skip those steps already finished.
> 
> Best,
> 
> Fengchao

I wasn't aware that you can run from several steps in. How do I go about doing that in FragPipe?

Thanks,
Chad

**Comment by fcyu** [comment]
> I wasn't aware that you can run from several steps in. How do I go about doing that in FragPipe?

In FragPipe GUI, you just need to uncheck the checkboxes, such as "Run MSFragger" and "Run MSBooster", at the top left of the panels.

In the headless mode, you need to edit the workflow file by changing some parameters to false. You could uncheck them in GUI mode and export the workflow file to see which parameters to edit.

Best,

Fengchao

**Comment by chad-hyer** [comment]
Rerunning from that step made it past the last break point. It is currently going through the next steps, so we'll see if it makes it to the end. I'll see if my other datasets hit the same problem when I queue them up to run over the weekend.

**Comment by anesvi** [comment]
Good luck with your project, Chad. Let us know how the results look. Astral is a new type of data and we are happy to get more feedback on how things work, especially with nonstandard applications like what you are doing. You can also contact us by email if that is preferable to you.

**Comment by fcyu** [comment]
> Rerunning from that step made it past the last break point. It is currently going through the next steps, so we'll see if it makes it to the end. I'll see if my other datasets hit the same problem when I queue them up to run over the weekend.

Glad to hear the rerunning ProteinProphet resolved the issue. That one should be due to the random file system or OS error.

Best,

Fengchao

**Comment by chad-hyer** [comment]
> > Rerunning from that step made it past the last break point. It is currently going through the next steps, so we'll see if it makes it to the end. I'll see if my other datasets hit the same problem when I queue them up to run over the weekend.
> 
> Glad to hear the rerunning ProteinProphet resolved the issue. That one should be due to the random file system or OS error.
> 
> Best,
> 
> Fengchao

Thanks for the assistance. I'll let you know if the problem is reproducible as I run more sets.

> Good luck with your project, Chad. Let us know how the results look. Astral is a new type of data and we are happy to get more feedback on how things work, especially with nonstandard applications like what you are doing. You can also contact us by email if that is preferable to you.

Thanks! I'll keep you all updated. We just moved over to FragPipe from PEAKS recently and have really liked it. Astral data has been daunting to deal with, but FragPipe is doing a really good job with it (both DDA and DIA) from what we can tell thus far. Our work is in structural proteomics using iodine labeling and protein turnover and kinetics facilitated by deuterium labeling, hence all the strange PTMs, so we will be figuring out a lot of nonstandard workflows for FragPipe in the coming months. If you want to know more about the things we are trying to do with FragPipe, these are our use cases:

- Turnover and kinetics: https://doi.org/10.1093/bioinformatics/btx009
- Protein folding stability: https://doi.org/10.1021/acs.jproteome.2c00323 https://doi.org/10.1021/acs.jproteome.2c00619

**Comment by chad-hyer** [comment]
I ran more sets, and the same problem didn't occur. I ran out of memory, but that wasn't really surprising with all the variable mods, so I'll just make some adjustments on memory allocation, so I think the original reported problem was just a fluke.

Thanks for all the help,
Chad Hyer
