### ISSUE TITLE
IonQuant crashes on NAS when analyzing many files

### ISSUE THREAD

**Issue by KlemensFroehlich** [Nesvilab/FragPipe#1765]
[log_2024-02-23_12-44-28.txt](https://github.com/user-attachments/files/16833606/log_2024-02-23_12-44-28.txt)
[log_2024-08-21_21-15-17.txt](https://github.com/user-attachments/files/16833612/log_2024-08-21_21-15-17.txt)

Dear FragPipe Team

I recently tried to analyze some DDA-PASEF Phospho files directly on our NAS drive. This usually works nicely for FragPipe searches in the case of .raw files.

However, when analyzing more than 1 file from this project at once, IonQuant consistently crashed, but always with a different file. So we copied the data manually to the local hard drive of the machine and the search went through.

File size of the .d folders is around 1.3 GB mzBIN around 500MB and mzml around 1GB. 20 fles in total.

Our hypothesis is that there is a bandwidth issue when analyzing many files that leads to a time out in IonQuant. The bandwidth was upgraded recently so it should already be 5 or 10 Gbit/s.

Would it be possible to increase the threshold of the time out, or do you think this is something else entirely? Please find attached two of the log files that we generated.

Any help would be highly appreciated.

Best, Klemens

**Comment by fcyu** [comment]
Hi Klemens,

It seems that there were some IO issues: `SQLITE_IOERR_UNLOCK] I/O error within xUnlock (disk I/O error)`

Best,

Fengchao
