### ISSUE TITLE
DIA search crashed - searching pasefDIA data

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#1766]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
[log_2024-09-03_17-27-21.txt](https://github.com/user-attachments/files/16850354/log_2024-09-03_17-27-21.txt)

Hi,
I'm trying to run diapasef quant workflow, and it appears that the bruker library is missing (is it?) 

Thanks!
David.

**Comment by fcyu** [comment]
> java.lang.UnsupportedOperationException: Bruker native libraries not found. If you are using Windows, please make sure that Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) is installed. If you are using Linux, please maks sure that all dependencies are installed (can check using ldd command).

Do you have Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) installed?

Thanks,

Fengchao

**Comment by Dmorgen** [comment]
Apparently not... :) but now it generates another (new?) error...

 
[log_2024-09-03_18-31-35.txt](https://github.com/user-attachments/files/16851143/log_2024-09-03_18-31-35.txt)
Thanks!
D.

**Comment by fcyu** [comment]
I guess there is no analysis.tdf in your D:\PXD053895\1-10_Slot1-28_1_2917.d

Could you double check?

Thanks,

Fengchao
