### ISSUE TITLE
Fragpipe 22.0 Docker ERROR - MSFragger path does not exist

### ISSUE THREAD

**Issue by Allen188** [Nesvilab/FragPipe#1767]
hi，
I attempted to download the Docker version of FragPipe 22.0, but encountered an error stating ‘ERROR - MSFragger path does not exist’ when running it. May I ask if you did not include the plugins MSFragger, IonQuant, and dirTracer in the Docker image you encapsulated? If you haven’t included them, I can try to add them to the image myself. Could you please advise on which versions would be best to use for each?

**Comment by fcyu** [comment]
>  May I ask if you did not include the plugins MSFragger, IonQuant, and dirTracer in the Docker image you encapsulated?

No I didn't because of the licenses.

> If you haven’t included them, I can try to add them to the image myself. 

You can download them to your docker container, but can't release a Docker image with those three tools restricted by the licenses.

Best,

Fengchao
