### ISSUE TITLE
Missing MaxLFQ Intensity in Combined_Protein.TSV

### ISSUE THREAD

**Issue by FuntoshS** [Nesvilab/FragPipe#1770]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & 
[log_2024-09-04_17-19-18.txt](https://github.com/user-attachments/files/16873985/log_2024-09-04_17-19-18.txt)
drop here.)

**- Describe the issue or question:**
I used FragPipe for the first time to analyze DDA data using LFQ-MBR workflow with one replicate for the test and control.
Unfortunately, the combined_protein.tsv file has the data for MaxLFQ intensity missing.
The same was not true when I processed the data supplied as part of LFQ tutorial.
Can you please help?
Thank you very much.

**Comment by fcyu** [comment]
`2024-09-04 16:32:49 [WARNING] - There are only 2 experiments. Will not calculate MaxLFQ intensity.`

Best,

Fengchao

**Comment by FuntoshS** [comment]
Thank you Fengchao.
