### ISSUE TITLE
Invalid spectrum file path error for PDVviewer

### ISSUE THREAD

**Issue by jongminchoi** [Nesvilab/FragPipe#1771]
Hello, 
Thanks, Fragpipe team for your support with Fragpipe.
Recently, I cannot open spectrum file with PDVview. The Loading spectrum file error with Invalid spectrum file path. 
My data is from timsTOF ultra and ddaPASEF data.
Is it not compatible with PDV view in Fragpipe? 
Please help me to see the spectra match.

Thanks,

**Comment by fcyu** [comment]
No response.
