### ISSUE TITLE
Wrong .d path broke the program.

### ISSUE THREAD

**Issue by Ale-ksa-ndra** [Nesvilab/FragPipe#1772]
i completely do not understand why those file can not be processed. can you see this from the logfile?
this is tims tof data with very narrow widows 10Da
[log_2024-09-06_16-06-34.txt](https://github.com/user-attachments/files/16909330/log_2024-09-06_16-06-34.txt)

**Comment by fcyu** [comment]
Could you check if there are `analysis.tdf` file in `C:\Users\achojna1\bruker5\RH_Bruker_MassResolved\20231012_RH_BRUKER_MR_260\260_300SPD_DIA_M1_S2-D10_1_2377.d`?

Best,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
Hi
yes, there is.

**Comment by fcyu** [comment]
Can you share the screenshot of the `C:\Users\achojna1\bruker5\RH_Bruker_MassResolved\20231012_RH_BRUKER_MR_260\260_300SPD_DIA_M1_S2-D10_1_2377.d` folder?

Thanks,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
A.Chojnacka, PhD│Van 't Hoff Institute for Molecular Sciences (HIMS)│University of Amsterdam│Science Park 904│1098 XH  Amsterdam│The Netherlands│+31 (0)20 525 6486│room ***@***.******@***.***>

**Comment by Ale-ksa-ndra** [comment]
Hello,
I have the same situation with files delta 10 Da and 50 Da (m/z) low mass range…if wider window was recorded then its processed, without error.
Is this correct what I am thinking?
If so, is there a way to analyze it?
Kind regards,

A.Chojnacka, PhD│Van 't Hoff Institute for Molecular Sciences (HIMS)│University of Amsterdam│Science Park 904│1098 XH  Amsterdam│The Netherlands│+31 (0)20 525 6486│room ***@***.******@***.***>

**Comment by fcyu** [comment]
It is not about the window size, but about your files being corrupted. Your log file was truncated by email. You need to go to this GitHub issue page to upload.

BTW, you haven't uploaded the screenshot I asked for. Please go to this issue page and upload it.

Best,

Fengchao

**Comment by Ale-ksa-ndra** [comment]
hi, sorry
[log_2024-09-10_10-47-28.txt](https://github.com/user-attachments/files/16959171/log_2024-09-10_10-47-28.txt)
[log_2024-09-10_09-57-54.txt](https://github.com/user-attachments/files/16959172/log_2024-09-10_09-57-54.txt)

and indeed there is nothing from tdf in C:\Users\achojna1\bruker5\RH_Bruker_MassResolved\20231012_RH_BRUKER_MR_260\260_300SPD_DIA_M1_S2-D10_1_2377.d 
![Capture1](https://github.com/user-attachments/assets/4d87a37b-2dc3-4116-abe5-8c9770463c43)

**Comment by fcyu** [comment]
Same reason as your previous one. Your screenshot shows the reason of the error: your data is in `C:\Users\achojna1\bruker5\RH_Bruker_MassResolved\20231012_RH_BRUKER_MR_260\260_300SPD_DIA_M1_S2-D10_1_2377.d\260_300SPD_DIA_M1_S2-D10_1_2377.d`, not `C:\Users\achojna1\bruker5\RH_Bruker_MassResolved\20231012_RH_BRUKER_MR_260\260_300SPD_DIA_M1_S2-D10_1_2377.d`.

Best,

Fengchao
