### ISSUE TITLE
No Ms1 scans detected in LFQ-MBR 

### ISSUE THREAD

**Issue by aarondemingg** [Nesvilab/FragPipe#1774]
Dear Fragpipe team,

I have encountered an issue with the LFQ-MBR workflow. To start with, I converted my (.mgf) files into mzML with MSconvert and ran the default LFQ-MBR workflow (DDA datatype). I tried numerous ways in the conversion step to solve the issue but was unable to do so. Would appreciate it greatly if anyone could help me out. I have attached the log below. Thanks!

[log_2024-09-08_21-55-17.txt](https://github.com/user-attachments/files/16922454/log_2024-09-08_21-55-17.txt)

**Comment by fcyu** [comment]
> I converted my (.mgf) files into mzML with MSconvert and ran the default LFQ-MBR workflow 
MGF files don't have MS1 scans. Please use the raw format files or the mzML files converted from the raw.

Best,

Fengchao

**Comment by aarondemingg** [comment]
Dear FengChao,

Ahh. Thank you so much! 

cheers,
Aaron
