### ISSUE TITLE
fragment sequence alignment problem

### ISSUE THREAD

**Issue by ZhaoTY2077** [Nesvilab/FragPipe#1776]
Dear Feng Chao:
here is my log file first of all:
[log_20240909.txt](https://github.com/user-attachments/files/16927494/log_20240909.txt)

I used modified workflow DIA_SpecLib_Quant to do proteins search and quantification with DIANN on a Linux server. the modification was only adding the path of database file(the protein sequence fasta file). After I got the quantification results by DIANN, I tried to map the precursors in result file report.pr_matrix.tsv back to the initial fasta file (that i provided to fragpipe for protein search) to see the positions of precursors. 

The problem is: some of the precursors would have miss matches of the amino acid residues when doing the mapping, and most of the miss matches are 1 , only few are 2. I'm wondering if this results from the transfer of runing results between different processes? like diann have different judgement logic compare with msfragger? 

I am curious about this phenomenon because I also did protein search and quantification using diann only, with same data provided. And I also tried to map the precursors back to the sequences. The results was no miss matches. (I set Missed cleavages to 1 in DIANN, not sure if this matters). 

Do you have any idea why this happens to fragpipe? 

Best, Troy. 
looking forward to your reply. 
ps: thanks for all your effort on developing fragpipe!

**Comment by fcyu** [comment]
When you matched the sequences, did you treat `I` and `L` the same? MSFragger doesn't distinguish `I` and `L` because they have the identical mass.

Best,

Fengchao
