### ISSUE TITLE
Invalid Spectrum File Path 

### ISSUE THREAD

**Issue by Rachitha17** [Nesvilab/FragPipe#1777]
**- Upload your log file**
[log_2024-09-09_11-51-34.txt](https://github.com/user-attachments/files/16935232/log_2024-09-09_11-51-34.txt)

I keep getting an error " Invalid Spectrum File Path", kindly help! Below is the screenshot
![Screenshot 2024-09-09 115504](https://github.com/user-attachments/assets/6c986bfd-3c94-40be-b151-6fdacb72d1da)
![Screenshot 2024-09-09 115646](https://github.com/user-attachments/assets/d38dca1a-2e02-4d46-9312-654e08bcadf0)

**Comment by KaiLiCn** [comment]
Hi,

Looks like you didn't finish the search correctly. Can you check your searching parameters and run FragPipe again? FragPipe-PDV only works on completed search result. If you are new to the FragPipe, please follow our tutorial. https://fragpipe.nesvilab.org/

Kai

**Comment by Rachitha17** [comment]
Thank you so much  I shall try again

**Comment by Rachitha17** [comment]
I would like to know if Fragpipe supports Bruker .d files, or do you recommend converting to mzmL format

**Comment by fcyu** [comment]
It support .d files, but we don't recommend converting .d to mzML format.

Best,

Fengchao

**Comment by Rachitha17** [comment]
The bruker instrument used is not ddaPASEF, it was mentioned in the tutorial that other .d files need to converted to mzmM files, any guidance on this!

Thank you,
Rachitha

**Comment by fcyu** [comment]
Oh, if it is neither ddaPASEF nor diaPASEF, which means no ion mobility separation, then you need to convert it to mzML.

Best,

Fengchao

**Comment by Rachitha17** [comment]
Thank you so much
