### ISSUE TITLE
IonQuant failed

### ISSUE THREAD

**Issue by shubham1637** [Nesvilab/FragPipe#1779]
Hi,
   I am using MSfragger 3.8 using Fragpipe. It generated the psm.tsv however it crashed at IonQuant. I wonder what could be wrong here? The files are timsTOF DDA files.

**- Upload your log file**
C:\Users\Ruiqi\Downloads\FragPipe-jre-20.0\fragpipe\jre\bin\java.exe -Xmx207G -Dlibs.bruker.dir="C:\Users\Ruiqi\Downloads\MSFragger-3.8\MSFragger-3.8\ext\bruker" -Dlibs.thermo.dir="C:\Users\Ruiqi\Downloads\MSFragger-3.8\MSFragger-3.8\ext\thermo" -cp "C:\Users\Ruiqi\Downloads\FragPipe-jre-20.0\fragpipe\tools\jfreechart-1.5.3.jar;C:\Users\Ruiqi\Downloads\FragPipe-jre-20.0\fragpipe\tools\batmass-io-1.28.12.jar;C:\Users\Ruiqi\Downloads\FragPipe-jre-20.0\fragpipe\tools\IonQuant-1.10.27.jar" ionquant.IonQuant --threads 39 --ionmobility 1 --minexps 1 --mbr 0 --maxlfq 1 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 10 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 0 --minisotopes 2 --minscans 3 --writeindex 0 --tp 0 --minfreq 0 --minions 2 --locprob 0.75 --uniqueness 0 --filelist D:\Data\Snuy\MSfraggerOut\filelist_ionquant.txt --modlist D:\Data\Snuy\MSfraggerOut\modmasses_ionquant.txt
IonQuant version IonQuant-1.10.27
Batmass-IO version 1.28.12
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 207 GB memory
2024-09-12 21:45:45 [INFO] - Collecting variable modifications from all psm.tsv files...
2024-09-12 21:45:45 [INFO] - Loading and indexing all psm.tsv files...
java.lang.NoSuchMethodError: 'com.google.protobuf.Internal$ProtobufList N$j.makeMutableCopy(com.google.protobuf.Internal$ProtobufList)'
	at N$j.a(Unknown Source)
	at N$j$a.f(Unknown Source)
	at N$j$a.a(Unknown Source)
	at aa.a(Unknown Source)
	at k.a(Unknown Source)
	at k.b(Unknown Source)
	at k.a(Unknown Source)
	at ionquant.IonQuant.a(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

**Comment by fcyu** [comment]
I don't think IonQuant 1.10.27 is compatible with FragPipe 20.0. Please upgrade FragPipe and MSFragger to the latest version.

Best,

Fengchao
