### ISSUE TITLE
non-specific search issues

### ISSUE THREAD

**Issue by mcundell** [Nesvilab/FragPipe#178]
Hi,

I am having difficulty running non-specific search.  I load the default non-specific search configuration and add a few variable mods (oxidation MHW, deamidation NQ).  However, I cannot get the job to complete and I have various errors.  I can get the search to complete with the default mods selected with the non-specific search configuration.  I presume therefore that all my issues are due to the size of the search space and I am getting memory and database splitting errors.  The PC I am processing on has 128GB RAM with Intel Xeon E5-2687W (2 processors - 32 threads).  

Presumably I am doing something basic wrong?  I am getting the following errors:

GC overhead limit error: [log_2020-03-11_16-45-45.txt](https://github.com/Nesvilab/FragPipe/files/4324120/log_2020-03-11_16-45-45.txt)

Too many peptides were generated: [log_2020-03-12_11-50-45.txt](https://github.com/Nesvilab/FragPipe/files/4324130/log_2020-03-12_11-50-45.txt)

so I set split database from 1 to 2: 
[log_2020-03-12_12-18-43.txt](https://github.com/Nesvilab/FragPipe/files/4324132/log_2020-03-12_12-18-43.txt)
I have Python installed and it says "Database Splitting enabled" under the "DB Splitting" section of the config tab so I am not sure why the splitting failed?

I have also noticed after loading default non-specific search parameters that "search_enzyme_cutafter" is set to trypsin... might this cause issues?
search_enzyme_name = nonspecific
search_enzyme_cutafter = KR

Any help would be appreciated.  

Best,

Michael

**Comment by anesvi** [comment]
You may need to set Split to a higher value than 2. However, I am not sure if the error is actually memory related.
Guo Ci, can you take a look.

**Comment by guoci** [comment]
It looks like there is some error with the parsing.
```
Failed in checking D:\MSFragger\MS0295_nqnc_deam_MHW\split_peptide_index_tempdir\MS0295_A2_F9.mzBIN_calibrated
UNAVAILABLE: Channel shutdown invoked
Checking D:\MSFragger\MS0295_nqnc_deam_MHW\split_peptide_index_tempdir\MS0295_A2_F9.mzBIN_calibrated...
```

**Comment by mcundell** [comment]
Do you think it looks like a bug or might I have set something up wrong?  Let me know if you need me to test any variables.  Thank you for looking into this!

**Comment by fcyu** [comment]
@mcundell I am not sure about the reason. Can you try it one more time? If still failed, could you convert raw files to mzML according to [this tutorial](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md) and try it?

Best,

Fengchao

**Comment by mcundell** [comment]
I tried again with slightly different mods and it failed at main search: 
[log_2020-03-13_15-58-27.txt](https://github.com/Nesvilab/FragPipe/files/4330425/log_2020-03-13_15-58-27.txt)

I will try the convert.  It may take me a few days as I will have to wait for our IT department to do the install of Proteowizard.  I will let you know how i get on.  Thank you for the help.

Best,

Michael

**Comment by fcyu** [comment]
Sorry to hear that. If appropriate, we can try your data for you. Send an email to yufe@umich.edu if you want.

Best,

Fengchao

**Comment by mcundell** [comment]
Hi, 

I tried converting the files with msconvert as described in your guide but I still have an issue when it gets to database splitting: 
[log_2020-03-16_14-09-21.txt](https://github.com/Nesvilab/FragPipe/files/4338593/log_2020-03-16_14-09-21.txt)

Unfortunately I am not allowed to share these files i was working with.  What I will do is grab a public dataset and try and process that, then, if neccessary, we could work with the same files.

**Comment by fcyu** [comment]
Hi @mcundell 

This time, the error was due to the number of modified peptides exceeding the maximum number allowed by Java. This is a hard limit that we cannot go break. You may need to increase the number of split database.

Best,

Fengchao

**Comment by mcundell** [comment]
Thanks, I will increase the split value and rerun.  Is there some rule I can follow to know what split database value I will need to get a dataset processed?

**Comment by fcyu** [comment]
Unfortunately, there is analytical expression to calculated the needed number of split databases. Normally, we try different values and find the smallest workable one.

Best,

Fengchao

**Comment by mcundell** [comment]
Thank you for the explanations.  I reduced the search space and used split database as recommended and the data processed fine after conversion to mzML with msconvert.  

After that ran fine, I replaced the files to be processed with the parent .raw files and set the search going again.  As such all settings should be identical.  However, using identical settings i was not able to process the .raw files without error: 
[log_2020-03-17_16-00-56.txt](https://github.com/Nesvilab/FragPipe/files/4344397/log_2020-03-17_16-00-56.txt)

**Comment by fcyu** [comment]
Hi @mcundell ,

If I understand correctly, the error occurs only when using raw and checking the calibrated_mzBIN after calibration. The error looks like related to raw file reader but I cannot figure out why it was thrown during checking the calibrated_mzBIN. Need the help from @chhh 

Best,

Fengchao

**Comment by mcundell** [comment]
Yes I believe that to be the case.  

I think I suffered from two issues.  Firstly on my part I was not controlling the split database function properly and had too many peptides (>2billion) so I hit a number of issues there. 

Secondly, this raw file issue.  In my first post the same can be seen in "so I set split database from 1 to 2: log_2020-03-12_12-18-43.txt"

**Comment by chhh** [comment]
Hm, I thought I replied to this one already.
@fcyu I don't think I can help here - we have bascially zero diagnostic info and can't get the files to test it with. It's a little suspicious that the problem occurs with the final file.
@mcundell Coud you try a few things please:
- run with just the last file that gave the error: MS0295_A2_F9.raw
- run the whole thing without recalibration
Looks like you only have a handful of files, hopefully, if nothing works, converting to mzML is not too much of a problem in this case.

**Comment by mcundell** [comment]
Thanks for the input.  

If I remove MS0295_A2_F9 leaving 13 .raw files that seems to process fine.  It suggests there was an issue with that file. 

But... MS0295_A2_F9 processed fine on its own: 
[log_2020-03-18_15-42-56.txt](https://github.com/Nesvilab/FragPipe/files/4351639/log_2020-03-18_15-42-56.txt)

I tried an alternate dataset and that failed on the final file after mass recalibration also:
[log_2020-03-18_21-31-37.txt](https://github.com/Nesvilab/FragPipe/files/4351645/log_2020-03-18_21-31-37.txt)

So i loaded up 14 Hela 1ug QC files and that failed on the last file also: 
[log_2020-03-18_22-15-43.txt](https://github.com/Nesvilab/FragPipe/files/4351654/log_2020-03-18_22-15-43.txt)

I should be able to send those QC files if neccessary but I think the issue should be possible to recreate with any files and it seems in my case to occur when I load up any 14 .RAW files and apply mass recalibration.

I am happy to convert to mzML, but it you would like to look into this error I would be happy to do more and provide logs (and files where possible) to see if its something that requires a fix, or is just my user error.  

I will try process the MS0295 data without mass recalibration on.  I set that going overnight, but it seems to be progressing fine and I anticipate that it will go through fine from the look of it now.

Thanks for your help!

**Comment by mcundell** [comment]
FYI, the RAW files processed with mass recalibration turned off (I am running non-specific search but these are actually tryptic peptide runs, but i only cared to test if it could process to completion rather than the actual data). 
[log-fragpipe-run-at_2020-03-19_17-01-01.log](https://github.com/Nesvilab/FragPipe/files/4356938/log-fragpipe-run-at_2020-03-19_17-01-01.log)

I loaded up 4 more Hela 1ug QC files and turned mass recalibration back on and it failed but at the same file as in the 14xHela 1ug processing (log_2020-03-18_22-15-43.txt) above.
[log-fragpipe-run-at_2020-03-19_17-55-49.log](https://github.com/Nesvilab/FragPipe/files/4356969/log-fragpipe-run-at_2020-03-19_17-55-49.log)


As above, I am happy to just convert to mzML so we can close this thread if you wish.  Otherwise let me know if you would like me to test anything else.  I can provide QC files if neccessary.

Thanks!

Michael

**Comment by anesvi** [comment]
Looks like some bug when using raw files + calibration + Split?  Is that something for Guo Ci to take a look?
