### ISSUE TITLE
Regarding open search strategy

### ISSUE THREAD

**Issue by bluemooninvestor** [Nesvilab/FragPipe#1780]
Hello

I am asking this because the software maintainers would better know about the underlying algo.

Suppose I have 5 control samples and 5 test samples (drug-treated). I expect to find some kind of modification in the test samples (due to covalent drug binding), and I want to use the "Open Search" strategy. Would it be prudent to search all 10 samples together, or does it make better sense to search only the 5 test samples where I expect to find the drug-bound modifications? Sorry if this is naive.

Since I have already asked a question, another small query. How does the quantification system handle peptides that are not present in all samples? Suppose a peptide is present in all control samples, but not detected in test samples because it contains an unknown modification. Does this peptide take part in quant (MaxLFQ specifically)

Sorry, I know I should read up literature. I have downloaded all 13-14 papers from Nesvi Lab. I am just under a deadline and all this needs some time to understand on my own. My apologies for asking here.

**Comment by fcyu** [comment]
> Would it be prudent to search all 10 samples together, or does it make better sense to search only the 5 test samples where I expect to find the drug-bound modifications?

If the modifications that you are interest in only exist in the 5 test samples, you probably just need to search those sample.

> Since I have already asked a question, another small query. How does the quantification system handle peptides that are not present in all samples? Suppose a peptide is present in all control samples, but not detected in test samples because it contains an unknown modification. Does this peptide take part in quant (MaxLFQ specifically)

No. But note that open search does not support quantification in the current version. You need to perform the closed search for the quantification.

Best,

Fengchao

**Comment by bluemooninvestor** [comment]
Thank you very much! What I meant to ask is that if I search all 10 samples, do I have inferior chances of getting the modifications which are specific to only 5 samples (due to FDR control or similar)?

**Comment by fcyu** [comment]
Yes

**Comment by bluemooninvestor** [comment]
Thanks! I will search the specific samples only. Please close this thread.
