### ISSUE TITLE
Unknown modification

### ISSUE THREAD

**Issue by jasminesmn** [Nesvilab/FragPipe#1784]
Dear Nesvilab,

I am running a DIA proteomics experiment with samples that contain the threonine analog called B-ethylserine (BES). So instead of threonine, the cells used BES during translation and incorporate this non-canonical amino acid into the proteins.
This modification adds 9.984 Dalton which I want to put as a variable modification.
This modification is not in the UniMod database as the technique is quite new. So I get this error:

ERROR: src/diann.cpp: 2774: unknown modification: 111.031685

How can I fix this error?  I am using the DIA_SpecLib_Quant workflow.

Thanks in advance,
Jasmine

**Comment by fcyu** [comment]
Hi Jasmine,

You need to add the option `--mod [name],[mass]` to declare rare modifications in the `Cmd opts` box of the `Quant (DIA)` tab. Examples: `--mod UniMod:5,43.005814`.

Best,

Fengchao

**Comment by jasminesmn** [comment]
Hi Fengchao,

Thanks for your response. I am not sure which name to put in there because the modification is not present in the UniMod database. Can I use a made up name for this? 

Best,
Jasmine

**Comment by fcyu** [comment]
Yes, you can use any names.

Best,

Fengchao

**Comment by fcyu** [comment]
Site is not needed. Just the mass.

Best,

Fengchao

**Comment by jasminesmn** [comment]
Thanks for your help. I still get the same error, I think because UniMod doesn't hold this modification: 
![Screenshot 2024-09-17 at 14 42 09](https://github.com/user-attachments/assets/2b6b1e48-37fe-48af-9bb1-4aac60f4f1e2)
![Screenshot 2024-09-17 at 14 41 28](https://github.com/user-attachments/assets/02194432-b059-4a61-a7dd-633dd38de5da)

Are there any other solutions?

Best,
Jasmine

**Comment by fcyu** [comment]
The value should be 111.031685. It the mod+amino acid mass.

Best,

Fengchao

**Comment by anesvi** [comment]
I think can also uncheck ' replace spectral library with predicted'. I believe in the latest FragPipe release when unchecked it in all workflows?

**Comment by jasminesmn** [comment]
Unchecking  'replace spectral library with predicted' seemed to fix that error, thanks for the help!
