### ISSUE TITLE
SILAC DIA analysis

### ISSUE THREAD

**Issue by ftsai98** [Nesvilab/FragPipe#1787]
Hi, I have process some SILAC data using fragpipe/DIA-NN and now am trying to analyze it. I am interested in quantifying my precursor ions. I ran my data through Fragpipe and now in the diann-output folder there are multiple files (report.pr_matrix_channels_ms1_extracted.tsv, report.pr_matrix_channels_ms1_translated.tsv, report.pr_matrix_channels_ms1.tsv, report.pr_matrix_channels_translated.tsv, report.pr_matrix.tsv). What exactly is the difference between these files as the same precursor seems to be giving different quantification values and is there a recommended file I should use for my precursor quantification?

**Comment by fcyu** [comment]
https://github.com/vdemichev/DiaNN?tab=readme-ov-file#multiplexing-using-plexdia

Best,

Fengchao
