### ISSUE TITLE
Global proteome and Phosphoproteome study in fragpipe

### ISSUE THREAD

**Issue by shilly99** [Nesvilab/FragPipe#1790]
I am new to fragpipe and want to analyze global and phosphoproteome data for WT and Knock out cell line. I have DDA-LFQ data. I am not sure how to set up the experiment. 
- Should I analyze phospho WT and global WT separately and compare it with the Knock out condition. or I should do all of it in one experiment. 
- Should I use PTM shepherd or not?

Please help. 

Thanks!

**Comment by fcyu** [comment]
Thanks for your interest in FragPipe. 

> Should I analyze phospho WT and global WT separately and compare it with the Knock out condition. or I should do all of it in one experiment.

I think you should analyze the phospho and global data separately because they have different content and PTM settings.

> Should I use PTM shepherd or not?

For the quantitive differential analysis, no, you don't need to use PTM-Shepherd.

In case you need some tutorial, here is one https://fragpipe.nesvilab.org/docs/tutorial_lfq.html in our webpage, and another one used in the US HUPO 2023 short course https://docs.google.com/document/d/1Y3irUF1cPImOWdjvcQo1wZ5Pdqd4jg8bo_PSDOG173k/edit?usp=sharing

Best,

Fengchao

**Comment by shilly99** [comment]
Thanks for your prompt response. 

To sum up, this is what I will do: 
- I will load WT and Knock out global proteome data and run that through LFQ-MBR workflow, run the analysis and get the reports and visualize in Fragpipe analyst. 
- I will load the phosphoproteome-enriched raw files of WT and KO and run the analysis using LFQ-phospho workflow and visualize in Fragpipe analyst. 
- If I want to compare global proteome with enriched phosphoproteome then how to set that up?
- Also, how will I normalize the global and phospho data?

Thanks in advance!

**Comment by fcyu** [comment]
First two points look good. 

Regarding the third one, I don't have much experience about it. Maybe @hsiaoyi0504 or @anesvi can comment.

To the forth question, IonQuant (one module in FragPipe) will perform the normalization for global and phospho proteome data, separately. If you are asking about how to normalize globan and phospho together, I would let @hsiaoyi0504 to answer it.

Best,

Fengchao

**Comment by shilly99** [comment]
Thanks @fcyu!
Looking forward to learning more from the people you have mentioned here.

**Comment by anesvi** [comment]
This is a FragPipe forum. How to perform downstream processing like normalizing whole proteome and phospho abundances is not something that we can help here, as it is dependent on your biological questions. You can also read FragPipe-Analyst paper and also CPTAC papers.
