### ISSUE TITLE
parameters for retention time calibration for spectral library generation from fractionated samples

### ISSUE THREAD

**Issue by vincentroyrichard** [Nesvilab/FragPipe#1791]
Hello!

I am trying to build a spectral library from a fractionated (n=24) filarial nematode digest and am a bit confused as to which RT calibration parameter should be selected under the Spec Lib tab . Is it possible to bypass RT calibration entirely or which setting would be optimal in this case?

Thanks very much for your help,
Vincent

**Comment by fcyu** [comment]
I don't think it makes sense to bypass RT calibration/alignment entirely.

If your data is from human sample, you can use ciRT. If not, use "automatic selection of a run as reference RT".

Best,

Fengchao
