### ISSUE TITLE
[9692] Failed to execute script dia-nn-plotter

### ISSUE THREAD

**Issue by Ale-ksa-ndra** [Nesvilab/FragPipe#1792]
Dear reader, i have processed this data in different set and it was working well.
can you please help me to understand what this  error means?
kind regrads, 
[9692] Failed to execute script dia-nn-plotter
[log_2024-09-24_10-58-10.txt](https://github.com/user-attachments/files/17111506/log_2024-09-24_10-58-10.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

**Comment by fcyu** [comment]
Your data has no IDs quantified. Please double check your data and settings.

Best,

Fengchao
