### ISSUE TITLE
Clarification - peptides with PTMs in MSBooster rescoring

### ISSUE THREAD

**Issue by PominovaMS** [Nesvilab/FragPipe#1796]
Hi FragPipe team,

I am running MSBooster rescoring using the default MSBooster features along with Prosit-generated features. I have a dataset with multiple PTMs, but from what I understand, the current Prosit model only supports the most common modifications like oxidation (possibly even only oxidation of methionine). 

Could you please clarify how MSBooster handles peptides with PTMs that are not supported by the Prosit model?
Does the rescoring process skip these peptides, or they are included despite the unsupported modifications and somehow handled on the Prosit's side, or is there any other strategy? 

Thanks in advance for your help!

Best,
Marina

**Comment by fcyu** [comment]
For the unsupported PTMs, MSBooster strips the PTMs and performs the prediction for the unmodified peptide. And then, shifted the predicted fragment peaks according to the PTM's delta mass.

Best,

Fengchao
