### ISSUE TITLE
"combined_site_K_114" file missing after processing data with "TMT16_ubiquitination-K_tmt_or_ubiq" workflow

### ISSUE THREAD

**Issue by lxavierneves** [Nesvilab/FragPipe#1797]
**Log file**: [log_2024-09-25_14-48-40.txt](https://github.com/user-attachments/files/17132139/log_2024-09-25_14-48-40.txt)

**Description**
Hello, I've trying to analyse ubiquitination on K-GG enriched samples prepared using on-beads TMT labeling protocol, so I'm loading the TMT16_ubiquitination-K_tmt_or_ubiq workflow, but I'm not seeing the "combined_site_K_114.0429.tsv" file in the output folder. 
My input files are bRP fractions so I left Experiment and Bioreplicate columns blank so the fractions merge during search and TMT quantification.
![image](https://github.com/user-attachments/assets/76c60ae7-4d02-4314-a5c2-733dd3f4b125)

PTMProphet is active and +114 is indicated as it should be.
![image](https://github.com/user-attachments/assets/e33c8497-f649-4149-bc03-f8d904f34f19)

I understand that TMT Integrator will generate the multi-site and single-site reports but shouldn't the "combined_site_K_114.tsv" be generated as well? It seems the combined_site_K is the only file where I can find all modification sites and PTMprophet probabilities for each.

A last note, the isotope error for this workflow is 0/1/2 whereas for other tmt workflows it can be -1/0/1/2, for example. Is it advised to keep 0/1/2?

Many thanks,
Leandro

**Comment by fcyu** [comment]
First of all, I need to clarify that the `combined_site_*.tsv` reports are generated by IonQuant for the MS1-based quant. There are no TMT intensities in that file. For the TMT workflow, please use the reports in the `tmt-report` folder.

To make IonQuant generated `combined_*.tsv` files, you need to specify the experiment groups in the workflow tab.

> It seems the combined_site_K is the only file where I can find all modification sites and PTMprophet probabilities for each.

Such information is also in `psm.tsv`

Best,

Fengchao

**Comment by lxavierneves** [comment]
Thank you for the clarification and promptly reply Fengchao.

Best,
Leandro

**Comment by lxavierneves** [comment]
Thank you for the clarification and promptly reply Fengchao.

Best,
Leandro

**Comment by lxavierneves** [comment]
Thank you for the clarification and promptly reply Fengchao.

Best,
Leandro
