### ISSUE TITLE
[ERROR] - There are only 0 MS1 scans

### ISSUE THREAD

**Issue by Shinya-Watanabe** [Nesvilab/FragPipe#1798]
IonQuant shows an error below. I have 11 plex TMT and search for PTM. It would be helpful if you could help me to fix this.

> 2024-09-25 11:32:53 [ERROR] - There are only 0 MS1 scans in C:\Users\u1440477\Desktop\Motrpac\proteomics\global\MSV000092922\mzml_heart\Calibrated\S1\01MoTrPAC_PASS1B-06_T58_PR_BI_20200224_GY_f01_calibrated.mzML.
> Process 'IonQuant' finished, exit code: 1
> Process returned non-zero exit code, stopping

[log_2024-09-25_11-40-51.txt](https://github.com/user-attachments/files/17135814/log_2024-09-25_11-40-51.txt)

**Comment by fcyu** [comment]
`*_calibrated.mzML` is not supposed to be used as the input of FragPipe. Please use the original mzML file.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
Is there any way to get away with the calibration once it's done? The calibration takes time, and when I troubleshot other sections like PTMProphet, I do not want to run the same calibration multiple times. 

Best,
Shinya

**Comment by fcyu** [comment]
Yes, uncheck the steps that have been done (find the `run XXX` checkbox on the top left of each tab). 

For this to work, you need to use the original input files, make sure that the input file and intermediate result files are not changed and moved, and the parameters are not changed.

Best,

Fengchao

**Comment by Shinya-Watanabe** [comment]
For example, the analysis stopped at IonQuant, but I want to change a variable modification in MSFragger. The calibration is under MSFragger, so do I need to run it every time I re-run MSFragger despite the _calibrated.mzML files exist? If I remove "_calibrated" from the file name, does it work?

Best,
Shinya

**Comment by Shinya-Watanabe** [comment]
I got it.

Thank you. 
Shinya
