### ISSUE TITLE
LFQ

### ISSUE THREAD

**Issue by bioinf-dev** [Nesvilab/FragPipe#1799]
Hello Fragpipe team,
I tried running FragPipe with LFQ. I have peptidomics data and set MaxLFQ min ions to 1. 
In the output the intensity was converted to 0 following LFQ normalization. The value of the intensity was not small so it is not clear why FragPipe converts it to zero after normalization.

Thanks,
Ronen

**Comment by fcyu** [comment]
What does the "In the output the intensity was converted to 0 following LFQ normalization" mean? Could you elaborate it more?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Rolling from peptide intensity to protein intensity has additional filters/criteria. For MaxLFQ, it requires the same ion having non-zero intensities in at least two files. For your example, that specific peptide might not quantified in multiple files. The "Intensity" column, which is from top-N summation, should be non-zero.

Best,

Fengchao
