### ISSUE TITLE
New species proteome

### ISSUE THREAD

**Issue by shilly99** [Nesvilab/FragPipe#1801]
Hi all,

I have to analyze a few serum samples that are from a different avian species. What FASTA file should I use for that and how should I download that in Fragpipe?

**Comment by dpolasky** [comment]
Hi,
Instructions for downloading a reference proteome or loading your own fasta file in FragPipe can be found here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#specify-a-protein-sequence-database. If you don't know where to get a fasta file for your organism, that's not something we can help with here. 

Best,
Dan
