### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by ECHOFREE28** [Nesvilab/FragPipe#1803]
Greetings,

I am currently trying to perform DIA search. I am utilizing fragpipe default workflow with DIA_DIA-Umpire_SpecLib_Quant. Unfortunately, I am hitting the error of -

"Generating edited pin with following features: [unweightedSpectralEntropy, deltaRTLOESS]
Loading predicted spectra
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping"

Please do advise me on how to troubleshoot this error and I would like to thank you in advance for your assistances.

[log_2024-09-30_10-58-24.txt](https://github.com/user-attachments/files/17185669/log_2024-09-30_10-58-24.txt)

Regards,
Echo

**Comment by yangkl96** [comment]
Please upgrade to the newest Fragpipe

**Comment by ECHOFREE28** [comment]
Thank you for your advice, I have upgraded Fragepipe to the newest version, but there is a new problem that haven't been solved, could you please help advise me on how to troubleshoot this error and I would like to thank you in advance for your assistance.
Traceback (most recent call last):
  File "D:\gaomengmeng\Fragepipe22.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 580, in <module>
    main()
  File "D:\gaomengmeng\Fragepipe22.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 552, in main
    main_easypqp(params, irt_df, allcmds, easypqp_convert_cmds)
  File "D:\gaomengmeng\Fragepipe22.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 306, in main_easypqp
    subprocess.run([os.fspath(params.easypqp), '--version'], check=True)
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\dell\\AppData\\Roaming\\Python\\Python312\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping


<img width="801" alt="Snipaste_2024-09-30_17-37-55" src="https://github.com/user-attachments/assets/658f56e2-5304-4930-9e44-9cd207b21a65">

[log_2024-09-30_16-19-23.txt](https://github.com/user-attachments/files/17187650/log_2024-09-30_16-19-23.txt)

**Comment by fcyu** [comment]
EasyPQP was not correctly installed. Please remove EasyPQP and Python entirely, and reinstall them.

Best,

Fengchao

**Comment by ECHOFREE28** [comment]
Thank you for your advice, I have reinstall EasyPQP, but there still is a new problem that haven't been solved, could you please help advise me on how to troubleshoot this error and I would like to thank you in advance for your assistance. 
Hope that I can get your help.

Yours,
Echo

Process 'PhilosopherDbAnnotate' finished, exit code: 0
PhilosopherFilter [Work dir: D:\gaomengmeng\MCP_Aging\test\test1]
D:\FragPipe-jre-22.0\tools\Philosopher\philosopher-v5.1.1.exe filter --picked --prot 0.01 --tag rev_ --pepxml D:\gaomengmeng\MCP_Aging\test\test1 --protxml D:\gaomengmeng\MCP_Aging\test\test1\combined.prot.xml --razor
time="15:15:58" level=info msg="Executing Filter  v5.1.1"
time="15:15:58" level=info msg="Processing peptide identification files"
time="15:15:58" level=info msg="Parsing D:\\gaomengmeng\\MCP_Aging\\test\\test1\\interact-InVitroAgingOocyte-DIA-Aging-R1-20220123_Q3.pep.xml"
time="15:15:58" level=info msg="Parsing D:\\gaomengmeng\\MCP_Aging\\test\\test1\\interact-InVitroAgingOocyte-DIA-Aging-R1-20220123_Q1.pep.xml"
time="15:15:58" level=info msg="Parsing D:\\gaomengmeng\\MCP_Aging\\test\\test1\\interact-InVitroAgingOocyte-DIA-Aging-R1-20220123_Q2.pep.xml"
time="15:15:58" level=error msg="Cannot read file. Error parsing the file "
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks
[log_2024-10-09_15-15-58.txt](https://github.com/user-attachments/files/17304151/log_2024-10-09_15-15-58.txt)

**Comment by fcyu** [comment]
It is weird that the files couldn't be read. I guess something was wrong with your file system.

BTW, why did you use the DIA-Umpire but not the DIA_SpecLib_Quant workflow? You were perform a tryptic search, which the DIA_SpecLib_Quant workflow should give better result.

Best,

Fengchao
