### ISSUE TITLE
Question regarding installation: 

### ISSUE THREAD

**Issue by sfarkona** [Nesvilab/FragPipe#1804]
Hello all, I have no previous experience with FragPipe. We (our IT team and I) are trying to install FragPipe on our lab's PC, which runs on a Windows system. It is asking for a very old Java version (I think they told me Java 19, but our PC has a more updated version). We found it weird. Is this normal? Should we install the older JAVA version? Is there anything else I should know?

Please let us know.
Best,
Sofia

**Comment by fcyu** [comment]
> Is this normal?

Yes

> Should we install the older JAVA version? 

Java 11 - 19 should work. 

>  Is there anything else I should know?

No.

Best,

Fengchao

**Comment by sfarkona** [comment]
So fast. Thank you Fengchao.
Best,
Sofia
