### ISSUE TITLE
spectral count and intensity

### ISSUE THREAD

**Issue by tjiangUNM** [Nesvilab/FragPipe#1806]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Hi!

When I finished the analysis and checked the modified peptide result, I saw that some of the peptide had >0 spectral count, but the intensity value was 0. Just wonder that shouldn't we expect >0 intensity in this case?

Thanks,
Ting

**Comment by fcyu** [comment]
I suppose you have enabled the "Quant (MS1)" tab. Then, the quantification has higher criteria than the identification. A peptide could be identified based on MS2 but doesn't have good signal on MS1.

Best,

Fengchao

**Comment by tjiangUNM** [comment]
Yes, I enabled quant. That makes sense. Thank you!

Best,
Ting
