### ISSUE TITLE
Open search Crystal-C error

### ISSUE THREAD

**Issue by wleiter1999** [Nesvilab/FragPipe#1807]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-09-30_16-28-03.txt](https://github.com/user-attachments/files/17196651/log_2024-09-30_16-28-03.txt)

**- Describe the issue or question:**

Running open search and search is stopped after Crystal-C process finishes:

Process 'Crystal-C' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
It was due to version incompatibility. Please upgrade FragPipe to version 22.0.

Best,

Fengchao

**Comment by wleiter1999** [comment]
That worked, thanks!!

Will
