### ISSUE TITLE
Question: Fixed PSM FDR without protein level filter.

### ISSUE THREAD

**Issue by mcundell** [Nesvilab/FragPipe#181]
Hi,

Quick FDR question.  I read a previous FDR post (https://github.com/Nesvilab/MSFragger/issues/16) and you mention that "if you do not want to apply any protein level filter, uncheck 'Report Protein FDR' box.".  I cannot seem to find that checkbox in fragpipe v12.2.  I am trying to simply apply a fixed 5% FDR to my PSM (I added --psm 0.05) without applying any additional protein level filter to them, as in --sequential and --2d which i currently have removed from "report tab > generate report > Filter".  I am running peptideprophet and proteinprophet with default options for non-specific search in the downstream tab.

Thanks for the help.

Best,

Michael

**Comment by fcyu** [comment]
Hi Michae,

You can check `Do not use ProteinProphet file` in the `Report` tab:
![image](https://user-images.githubusercontent.com/6926299/77595250-0dfa1400-6ecf-11ea-9103-d5c312868606.png)

Best,

Fengchao
