### ISSUE TITLE
Using spectral library built in skyline

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1811]
Hello Fragpipe team,

I am analyzing histone peptides which are decorated with many PTMs. Usually the analysis is done in skyline, but I would like to try this out with a search engine for DIA data. I have a custom built spectral library in skyline (.blib) that contains the histone peptides I am interested in. It seems like fragpipe is only able to build spectral libraries from MS data files and not able to use a pre-built spectral library? The reason I don't want to use fragpipe to build the spectral library is because there are too many modifications and it is much simpler to use the pre-built spectral library. Is there a solution for this?

Thanks,
Ronnie

**Comment by fcyu** [comment]
> It seems like fragpipe is only able to build spectral libraries from MS data files and not able to use a pre-built spectral library? 

Mostly correct. But if you have the spectral library in the supported tsv format, you can specified it in "Quant (DIA)" tab. But it seems that yours is in blib format.

Best,

Fengchao

**Comment by anesvi** [comment]
Why do you even need FragPipe if you already have a library from another tool?

**Comment by cutleraging** [comment]
Hi all,

Thanks for the quick responses. I was indeed able to run my analysis by providing the spectral library that I built in skyline. The reason why I want to use fragpipe is that it seems to be much faster than DIANN for the same analysis and I have a lot of samples to analyze. Another reason is that I would like to import my results into skyline as detailed here: https://fragpipe.nesvilab.org/docs/tutorial_skyline.html

So when I use the DIA-Umpire_Speclib_Quant workflow with my spectral library, though I do get the DIA-NN results, it seems I am missing the interact-pep.xml, _uncalibrated.mgf, and protein protein.fas

Here is the log
[log_2024-10-03_17-21-30.txt](https://github.com/user-attachments/files/17261210/log_2024-10-03_17-21-30.txt)

I know that DIANN also has this capability, but I am analyzing histone PTMs with modifications not present in UNIMOD (due to derivatization), and currently DIANN only supports exporting results to skyline that only have UNIMOD modifications.

**Comment by fcyu** [comment]
> So when I use the DIA-Umpire_Speclib_Quant workflow with my spectral library, though I do get the DIA-NN results, it seems I am missing the interact-pep.xml, _uncalibrated.mgf, and protein protein.fas

Those files are generated when you perform database searches and spectral library generation. Since you started with existing library, they will not be generated.

> Another reason is that I would like to import my results into skyline as detailed here

The latest FragPipe has made the process more smooth. It has a "Skyline" tab that can automatically generate a Skyline document with your DIA quant. You just need to select "speclib" as input in that tab.

Best,

Fengchao
