### ISSUE TITLE
No reports generate

### ISSUE THREAD

**Issue by Li5459000** [Nesvilab/FragPipe#1812]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
Hi,

This is my first time using Fragpipe. I followed a tutorial and went through the steps for analysis, but no results were generated. 
Could you help me? I'm a beginner in proteomics.

[log_2024-10-03_13-55-14.txt](https://github.com/user-attachments/files/17239488/log_2024-10-03_13-55-14.txt)

**Comment by yangkl96** [comment]
Please upgrade to fragpipe 22

**Comment by Li5459000** [comment]
Thank you so much.
Solved!!!
