### ISSUE TITLE
Pause point between generating .pepXML and .pin file

### ISSUE THREAD

**Issue by bingnanzhao** [Nesvilab/FragPipe#1813]
**- Hi Fragpipe team: I tried to open the MSFragger search result (XXX.rank1.pepXML) as a pandas dataframe, and made some midifications based on my criteria. I want to write it back to .pepXML format and proceed downstream modules. The question I have now is: 1) could you provide the schema of .pepXML file so that I can write it back to the format MSFragger need, 2) Could you also make a pause point right before generating .pin file for validation module, so that once I upload my modified .pepXML it will successfully proceed? I know this is not a popular request, but if you could just provide me some instruction on this it would be helpful.

Thanks,
Bingnan
**

**Comment by fcyu** [comment]
> 1) could you provide the schema of .pepXML file so that I can write it back to the format MSFragger need

http://tools.proteomecenter.org/wiki/index.php?title=Formats:pepXML

> 2) Could you also make a pause point right before generating .pin file for validation module, so that once I upload my modified .pepXML it will successfully proceed?

Unfortunately no.

Best,

Fengchao

**Comment by anesvi** [comment]
I think you should modify the pin file. Then you can just rerun from master of percolator.

**Comment by bingnanzhao** [comment]
Thanks Fengchao and prof. Nesvizhskii,

Thanks for your suggestions and I believe we will formally collaborate on this later some time! Prof. Nesvizhskii just propose a very helpful suggestion and I will definitely try to work on .pin file directly. Just one last question remains on this: can I put the modified pin file in the work directory as a .csv file for proceeding msbooster or percolator?

Thanks,
Bingnan

**Comment by yangkl96** [comment]
You can save the modified pin file as a tsv file, but make sure to keep the same name as the original pin files, including the .pin extension

**Comment by bingnanzhao** [comment]
Got it that would be very helpful! Thanks you all!

Best,
Bingnan

**Comment by fcyu** [comment]
The modified file should have the `pin` extension and the columns separated with tab. Also remember to uncheck/disable the MSFragger tab when you run it the second time, otherwise, MSFragger will overwrite your pin files.

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Thanks so much Fengchao, I will try this very quickly and hopefully it would work!

Thanks,
Fengchao
