### ISSUE TITLE
Invalid Spectrum File Path

### ISSUE THREAD

**Issue by Rachitha17** [Nesvilab/FragPipe#1814]
[log_2024-10-03_13-13-33.txt](https://github.com/user-attachments/files/17249616/log_2024-10-03_13-13-33.txt)

I followed all steps according to the tutorial, but i cannot see the spectrum after i open the PDV viewer, I can see all the other results but not the spectrum, kindly help
![Screenshot 2024-10-03 131647](https://github.com/user-attachments/assets/a4d38b8d-4019-4a68-8b08-6f575912c2b1)
![Screenshot 2024-10-03 131815](https://github.com/user-attachments/assets/9cb6a268-8bcd-45d6-b6c3-65b1f0cd97e3)
![Screenshot 2024-10-03 131925](https://github.com/user-attachments/assets/5268b99d-8d6c-4404-bc9a-d87a1ff07377)

**Comment by fcyu** [comment]
For the error in the first screenshot and the log file, the "assign glycans with FDR" was enabled by mistake. Could you disable that one and rerun?

![image](https://github.com/user-attachments/assets/1eb170a9-ad41-4518-8a81-120e2835e575)

For the FragPipe-PDV errors, could you try again after rerunning FragPipe?

Thanks,

Fengchao

**Comment by Rachitha17** [comment]
Thank you so much for the immediate response, I am very thankful!

I did as you mentioned and the error on the first screenshot got solved, as I did not get that error again but I still get Invalid spectrum file path

**Comment by fcyu** [comment]
Kai @KaiLiCn can you take a look?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi, looks like you failed to finish your analysis in the beginning. Did you finish the analysis after changing the parameter? Please make sure your last output is something like this: 
![image](https://github.com/user-attachments/assets/1a50e4dd-ccc6-4a38-9385-2bb989766090)

If you still get the same error message, please share the new log file with me.

Thanks,
Kai
