### ISSUE TITLE
N term modification

### ISSUE THREAD

**Issue by Kokoushin** [Nesvilab/FragPipe#1817]
Hi,

I labeled the N-terminus of proteins at the protein level and set the search parameters "fixed modification, N-term protein" . In the results, both the "peptides" and "protein.tsv" files indicate successful labeling.

But, I would like to know if there is a way to identify which N-terminal peptides were detected but not successfully labeled.

**Comment by fcyu** [comment]
You could set your modification to variable modification.

Best,

Fengchao

**Comment by Kokoushin** [comment]
Thank you very much for your prompt response. 

I changed to use variable modification, but I still have two questions:

1. I would like to assess my labeling efficiency by determining whether there are any N-terminal peptides that were not labeled in the results. possible?

2. Could you briefly explain under what circumstances fixed modifications versus variable modifications should be applied?

**Comment by anesvi** [comment]
Please read some tutorial literature about search engines. This is a FragPipe support forum.  Variable means both labeled and unlabeled allowed. So that's what you need to use.

**Comment by Kokoushin** [comment]
Thanks a lot.
