### ISSUE TITLE
"shepherd.config" does not exist

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#182]
While performing an open search (of DDA data), the analysis stops at PTM-Shepherd, because the shepherd.config file is missing (see below). - Despite the fact, that the respective file is there!

Closer analysis of the shepherd.config-file shows, that 2 out of 33 analyzed mzML files (organized in 6 experimental groups with 3 replicates each) are not listed in the automatically generated shepherd.config file.

What could be the reason for this & how can I fix it?

I'm running FragPipe 12.2 with MSFragger2.3 and Philosopher 3.2.3

Thanks you for your help!

```
PTMShepherd [Work dir: /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp2]
java -Dbatmass.io.libs.thermo.dir="/home/bioinf/bioinf_data/49_scch/Tools/msfragger/MSFragger-2.3/ext/thermo" -cp /tmp/fragpipe/batmass-io-1.17.2.jar:/tmp/fragpipe/commons-math3-3.6.1.jar:/tmp/fragpipe/ptmshepherd-0.2.16.jar edu.umich.andykong.ptmshepherd.PTMShepherd "/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp2/shepherd.config"
Fatal error: Parameter file "/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp2/shepherd.config" does not exist
PTM-Shepherd version 0.2.16(c) University of Michigan

Using Java 1.8.0_221 on 27305MB memory

Process 'PTMShepherd' finished, exit code: 1

Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 100 remaining tasks
```

**Comment by chhh** [comment]
@danielgeiszler Is that the same problem you and Sarah had? How was that resolved?

**Comment by danielgeiszler** [comment]
@chhh Yes, it is.

@chscho Can you do a couple things for me to help resolve this?

1. Send us your shepherd.config file so we can see what is missing. That is not a known issue, although probably not related.
2. Try rerunning FragPipe, but with everything turned off except for PTM-Shepherd. I.e., start from where it died and see if it will finish.

Thanks!

**Comment by chscho** [comment]
Thank you for the quick reply.

The machine I'm using, runs on Ubuntu 18.04.4 LTS.

Here is the content of the shepherd.config file:

```
database = /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/iPtgxDBs/Trypsin/SIHUMI_iPtgxDB_Tryp_crap.revCat.fasta
dataset = GF_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/GF_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = InSol_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/InSol_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = InSol_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/InSol_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = FASP_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/FASP_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = C8_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/C8_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = C8_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/C8_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = C8_nofrac_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/C8_nofrac_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = SP3_1 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/SP3_1/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = C8_nofrac_3 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/C8_nofrac_3/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = GF_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/GF_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = InSol_3 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/InSol_3/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = C8_nofrac_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/C8_nofrac_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = SP3_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/SP3_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = FASP_3 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/FASP_3/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = GF_3 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/GF_3/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp
dataset = FASP_2 /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/FASP_2/psm.tsv /home/bioinf/bioinf_archive/49_scch_storage/Projects/SPP2002_SIHUMI/PTX/Proteomic-Data/mzML/tryp

histo_bindivs = 5000
histo_smoothbins = 2
localization_background = 4
mass_offsets = 0
output_extended = false
peakpicking_promRatio = 0.3
peakpicking_topN = 500
peakpicking_width = 0.002
precursor_tol = 0.01
spectra_condPeaks = 100
spectra_condRatio = 0.02
spectra_ppmtol = 20.0
threads = 31
varmod_masses = Failed_Carbamidomethylation:-57.021464
```

Re-running FragPipe with only PTM-Shepherd activated results in the same error message as reported before:
```
PTMShepherd [Work dir: /home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4]
java -Dbatmass.io.libs.thermo.dir="/home/bioinf/bioinf_data/49_scch/Tools/msfragger/MSFragger-2.3/ext/thermo" -cp /tmp/fragpipe/batmass-io-1.17.2.jar:/tmp/fragpipe/commons-math3-3.6.1.jar:/tmp/fragpipe/ptmshepherd-0.2.16.jar edu.umich.andykong.ptmshepherd.PTMShepherd "/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/shepherd.config"
Fatal error: Parameter file "/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/shepherd.config" does not exist
PTM-Shepherd version 0.2.16(c) University of Michigan

Using Java 1.8.0_221 on 27305MB memory

Process 'PTMShepherd' finished, exit code: 1

Process returned non-zero exit code, stopping
```

I've just realized, that the two samples which seemed to be missing, were actually assigned to the wrong replicate... - Hence not missing. But the reason why PTM-Shepherd reports a missing config file remains elusive. (The file is there for sure!)

**Comment by danielgeiszler** [comment]
Would you mind also trying to run this command as well?

/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4]
java -Dbatmass.io.libs.thermo.dir="/home/bioinf/bioinf_data/49_scch/Tools/msfragger/MSFragger-2.3/ext/thermo" -cp /tmp/fragpipe/batmass-io-1.17.2.jar:/tmp/fragpipe/commons-math3-3.6.1.jar:/tmp/fragpipe/ptmshepherd-0.2.16.jar edu.umich.andykong.ptmshepherd.PTMShepherd "/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4/shepherd.config"

I can get it to work on my Linux machine by running the FragPipe command manually.

I'm still trying to figure out what's causing this.

**Comment by chscho** [comment]
Hi Daniel

Thank you very much for your help. PTM-Shepherd executed from the command line worked like a charm. 
Tell me, if I can try running something else to help you figure out what caused the problem with the FragPipe GUI. 

Best,
Christian

**Comment by chhh** [comment]
Seconds time that happens and I don't have an idea what might be wrong. The only thing in common is linux.

Command from fragpipe doesn't work, but the same command (composed by fragpipe) executed by the user from terminal works, right?
Sounds like it must be some sort of permissions stuff. Or working folder stuff mixed with permissions. 

@chscho When the command worked from the terminal for you, did you execute it from `/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4` or was the working directory some place else?

**Comment by chscho** [comment]
@chhh: Yes, I did execute the command directly from: `/home/bioinf/bioinf_data/49_scch/Projects/SPP2002_SIHUMI/PTX/MSFragger/tryp4`
Shall I try execution from the home directory?

**Comment by chhh** [comment]
@danielgeiszler Try the `linux-fix` branch in PTMS repo, posted possible bugfix there

**Comment by danielgeiszler** [comment]
Fixed for FragPipe on Linux systems in release v0.3.5

https://github.com/Nesvilab/PTM-Shepherd/releases
