### ISSUE TITLE
How to understand that the number of Unique Peptides and Razor Peptides is equal in the protein-tsv table

### ISSUE THREAD

**Issue by shenghao003** [Nesvilab/FragPipe#1821]
Hello,how to understand that the number of Unique Peptides and Razor Peptides is equal in the protein-tsv table
![图片](https://github.com/user-attachments/assets/d0c07d34-2eff-405d-9be9-fcb082a80869)

**Comment by anesvi** [comment]
Razor column is actually unique plus razor

**Comment by shenghao003** [comment]
Thank you, there is another question I would like to ask. In some rows of the protein-tsv table, the number of Total Peptides is greater than the number of Razor Peptides. May I know which peptide segments are the extra? Additionally, I can only find Razor Peptides in the peptide.tsv table, not Total Peptides.

**Comment by fcyu** [comment]
> May I know which peptide segments are the extra? 

Please cross reference the psm.tsv to find out.

Best,

Fengchao

**Comment by anesvi** [comment]
You can find that info by looking at Mapped Proteins column in PSM.tsv. Protein column shows razor protein assignment. Mapped Proteins column shows all other proteins a shared peptide maps too.
