### ISSUE TITLE
fasta headers for group FDR estimation

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1822]
Hi all,

I have a couple quick questions about formatting fasta headers when using the group FDR feature, I wanted to use UniProt format for the headers in the custom protein fasta file we are searching. For example, some of the headers look like this:

```
>pg|ORF1000_ENST00000597346.1|PG309770 ORF1000_ENST00000597346.1 OS=Homo sapiens OX=9606 GN=ENSG00000269821.2 PE=1
>pg|ORF12_GF652|PG11033 ORF12_GF652 OS=Homo sapiens OX=9606 GN=FP671120.2:UBA2 PE=2
>pg|ORF16_GF11641|PG221554 ORF16_GF11641 OS=Homo sapiens OX=9606 GN=RNU6-32P:DDX1 PE=2
```

Reading through your tutorial [here](https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html), this should be compatible with the group FDR feature, correct? The runs worked, but it was difficult to tell from the logs if the group FDR estimation was performed.

My second question was that, given that I included the gene name in the fasta headers, I expected in the protein.tsv from Philosopher that these gene names would populate the gene name column. Did I mess up the fasta header format here? It is not obvious to me what's missing.

Thanks for your time and help.

Best,
Asher

**Comment by fcyu** [comment]
> Reading through your tutorial here, this should be compatible with the group FDR feature, correct? 

There is a small problem. It'd better to start with `sp` or `tr`. For example, `>tr|ORF12_GF652|PG11033 ORF12_GF652 OS=Homo sapiens OX=9606 GN=FP671120.2:UBA2 PE=2`
`

> The runs worked, but it was difficult to tell from the logs if the group FDR estimation was performed.

The Philosopher filter command part in the log will tell you if there are different groups of FDR. If you are not sure, could you share the log file?

> My second question was that, given that I included the gene name in the fasta headers, I expected in the protein.tsv from Philosopher that these gene names would populate the gene name column. Did I mess up the fasta header format here? It is not obvious to me what's missing.

It should be because the headers don't start with `sp` or `tr`, so Philosopher didn't detect them as UniProt format.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Hi Fengchao,

Thanks for the quick response. Got it, I will fix the headers so they start with `sp` or `tr` going forward.

Regarding the philosopher group FDR filter, thank you for explaining. I took another look and it does seem like the group FDR worked, but I am attaching the log as well as it would be great if you could confirm.

[241013_github_issue.zip](https://github.com/user-attachments/files/17357956/241013_github_issue.zip)

Thanks again for your time and help.

Best,
Asher

**Comment by fcyu** [comment]
Hi Asher,

Oh, wait, you should add the `--sequential` to the `phi-report.filter`, otherwise, the 2D filtering will overwrite the group FDRs due to the how Philosopher performs the filtering:

```shell
time="12:07:47" level=info msg="Database search results" ions=356992 peptides=273972 psms=2286036
time="12:07:50" level=info msg="Converged to 1.00 % FDR with 2076501 PSMs" decoy=20765 threshold=0.796414 total=2097266
time="12:07:50" level=info msg="Converged to 1.00 % FDR with 144371 Peptides" decoy=1444 threshold=0.966667 total=145815
time="12:07:51" level=info msg="Converged to 1.00 % FDR with 216778 Ions" decoy=2168 threshold=0.954153 total=218946
time="12:07:51" level=info msg="Separating PSMs based on group"
time="12:07:52" level=info msg="Filtering group 1"
time="12:07:54" level=info msg="Converged to 1.00 % FDR with 1633823 PSMs" decoy=16338 threshold=0.785434 total=1650161
time="12:07:54" level=info msg="Filtering group 2"
time="12:07:54" level=info msg="Converged to 1.00 % FDR with 441712 PSMs" decoy=4417 threshold=0.826381 total=446129
time="12:07:54" level=info msg="Filtering group 3"
time="12:07:54" level=info msg="Converged to 0.00 % FDR with 1 PSMs" decoy=0 threshold=1 total=1
time="12:07:54" level=info msg="Protein inference results" decoy=52548 target=91462
time="12:07:57" level=info msg="Converged to 1.00 % FDR with 15048 Proteins" decoy=150 threshold=0.9911 total=15198
time="12:08:00" level=info msg="2D FDR estimation: Protein mirror image" decoy=15048 target=15048
time="12:08:07" level=info msg="Second filtering results" ions=255486 peptides=174274 psms=2156700
time="12:08:09" level=info msg="Converged to 0.55 % FDR with 2144976 PSMs" decoy=11724 threshold=0.500005 total=2156700
time="12:08:09" level=info msg="Converged to 1.00 % FDR with 153023 Peptides" decoy=1531 threshold=0.863246 total=154554
time="12:08:09" level=info msg="Converged to 1.00 % FDR with 231866 Ions" decoy=2318 threshold=0.808972 total=234184
time="12:08:09" level=info msg="Post processing identifications"
time="12:08:30" level=info msg="Assigning protein identifications to layers"
time="12:11:50" level=info msg="Processing protein inference"
time="12:11:55" level=info msg="Synchronizing PSMs and proteins"
time="12:12:05" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=231835 peptides=153002 proteins=15048 psms=2144726
```

Best,

Fengchao

**Comment by fcyu** [comment]
You need to add `--sequential`. So the command becomes `--sequential --picked --prot 0.01 --minPepLen8 --group`.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Got it, okay thanks for the help!

Best,
Asher

**Comment by apsteinberg** [comment]
Got it okay thanks, so presumably for the sequential filtering without grouping the command would be?

`--sequential --picked --prot 0.01 --minPepLen 8`

Best,
Asher

**Comment by fcyu** [comment]
Correct.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Great, thanks again!

Asher
