### ISSUE TITLE
Cannot find a peptide in the Viewer, although it is found in the psm table

### ISSUE THREAD

**Issue by yishai99** [Nesvilab/FragPipe#1823]
I am using FP v20, HLA peptidomics workflow, tried to find a peptide sequence in the Viewer but it says 'no match'. The peptide shows up in all the output files, including the PSM table. Does the Viewer apply any filtering? Is this a bug?
Thanks,

Yishai

**Comment by KaiLiCn** [comment]
Hi Yishai,

Please make sure there is no " " after the sequence when you search it. There is usually a " " in the sequence if you copy it from the table directly.

Please let me know if it still doesn't work.

Kai
