### ISSUE TITLE
Multiple FAIMS CVs and Open Search

### ISSUE THREAD

**Issue by MattiaRediti** [Nesvilab/FragPipe#1824]
Hello,

I would like to clarify how to manage experiments with multiple FAIMS files coming from different CVs for the same sample in DDA experiments (say already after conversion to .mzML files, one file/CV), in particular in the context of open searches (as I understand that, for quantification, IonQuant is able to deal with this situation).

In particular, I would like to ask if there are there specific suggestions/considerations for building the manifest file and/or for downstream analyses.
- Is it recommended to work on a full psm.tsv file obtained without specifying Experiment/bioreplicates in the manifest, or is it preferable to obtain separate psm.tsv files for each sample obtained specifying Experiment/bioreplicates in order to link the different CVs to each sample?
- Is there a risk to obtain "duplicates" for PSMs in each sample? If so, how to safely manage this in the downstream analyses?

Thank you very much for the help.

Best,
Mattia

**Comment by fcyu** [comment]
For the search (not the quantification), there is no difference between with and without FAIMS. 

> Is it recommended to work on a full psm.tsv file obtained without specifying Experiment/bioreplicates in the manifest, or is it 
> preferable to obtain separate psm.tsv files for each sample obtained specifying Experiment/bioreplicates in order to link the different CVs to each sample?

It dependents on your sample groups, not dependents on if your data has FAIMS.

> Is there a risk to obtain "duplicates" for PSMs in each sample? If so, how to safely manage this in the downstream analyses?

There is no such risk. Even without FAIMS, there are redundant PSMs/peptides.

Best,

Fengchao

**Comment by MattiaRediti** [comment]
Hi Fengchao,

Than you for the quick reply. 
Just to make sure I understood correctly, so for open search there is no difference between splitting the single .raw file obtained with FAIMS with multiple CVs into, for instance, 2 .raw files (one for each CV), or analyzing the original .raw file not divided?

Best,
Mattia

**Comment by fcyu** [comment]
Correct, no significant difference.

Best,

Fengchao
