### ISSUE TITLE
Question about Discrepancies in Protein Identification between FragPipe and DIA-NN

### ISSUE THREAD

**Issue by Tan-Jiahua** [Nesvilab/FragPipe#1828]
Hi,

Thank you for developing FragPipe! I recently compared the search results from the DIA_SpecLib_Quant workflow in FragPipe with those from DIA-NN, using the same experimental data (2 instrumental parameters, each with 3 replicates) on the same sample.
While both pipelines yielded similar protein identification coverage across the 6 runs, I observed that the FragPipe-integrated DIA pipeline identified 3578 common protein groups, whereas the standalone DIA-NN identified 4639.

I am puzzled by the discrepancy in the number of protein groups identified. I also noticed that the number of precursors in the spectral libraries differs between the two pipelines (29994 vs. 3024184). Are there any possible explanations for these differences? Did I make an error in my analysis?

Thank you for your assistance! I’ve attached the logs for both FragPipe ([log_2024-10-10_15-06-30.txt](https://github.com/user-attachments/files/17370017/log_2024-10-10_15-06-30.txt) and [report.log.txt](https://github.com/user-attachments/files/17370020/report.log.txt)) and standalone DIA-NN ([report.log.txt](https://github.com/user-attachments/files/17370021/report.log.txt)).

**Comment by fcyu** [comment]
FragPipe is more stringent than DIA-NN in terms of the quality of the identifications. But "29994 vs. 3024184", are you sure?

Best,

Fengchao

**Comment by anesvi** [comment]
Yes you are doing something wrong.

**Comment by Tan-Jiahua** [comment]
These two numbers are from "[1:27] 29994 library precursors are potentially detectable" in [report.log.txt](https://github.com/user-attachments/files/17370020/report.log.txt) and "[41:08] 3021530 library precursors are potentially detectable" in [report.log.txt](https://github.com/user-attachments/files/17370021/report.log.txt). Please correct me if I am wrong.

**Comment by fcyu** [comment]
Those are the number of precursors in the library BEFORE the identification. 

Best,

Fengchao

**Comment by Tan-Jiahua** [comment]
Sorry for not expressing the point clearly. Could this be a reason for the difference in the number of the commonly detected protein groups?

**Comment by fcyu** [comment]
Those are the numbers of precursors in the library BEFORE DIA-NN performs the quantification. For DIA-NN, it is the predicted library from your fasta file, which contains all theoretical precursors. But for FragPipe, it is already after the identification and FDR control. 

ps, it is not trivial to perform a fair comparison between DIA-NN and FragPipe because the levels of FDR controls are different. Please read our paper https://www.nature.com/articles/s41467-023-39869-5

Best,

Fengchao

**Comment by Tan-Jiahua** [comment]
Thank you very much for your response and for sharing the paper. I would read it soon.
