### ISSUE TITLE
slicePASEF

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1830]
Hello Fragpipe team,

Will there be support for slicePASEF soon? I saw this was mentioned in the latest diaPASEF paper, but when I try to use this option in the DiaNN module, it says it is not recognized.

Best,
Ronnie

**Comment by anesvi** [comment]
There are too many diagonal PASEF versions now, and none seem to be well supported by Bruker. There is ASMS2024 poster on diagonal PASEF (yet another term) showing that the gains are frankly minimal. We will support it if there is strong interest. People who work with these data -please contact us to discuss, we need some motivation.

**Comment by anesvi** [comment]
We can discuss a collaboration and possibly looking at your data - could you please contact me by email and I will connect you with the rest of my team working with diaPASEF data.
