### ISSUE TITLE
restarting a DIA-PASEF search

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#1832]
Hi,

I'm using the version you've sent me (it's working), and my computer shutdown mid-run. is there a way to restart using the diatracer generated files? should I add them instead of the .d files? how should I treat them? as DIA? DIA with IM? 

Thanks!
David.

**Comment by anesvi** [comment]
Yes. Load diatracer.mzML as DDA files. And the original .d change to DIA-Quant. This way it will not do the conversion again

**Comment by enonimos** [comment]
I also had this exact question, so this trick is very helpful, thank you. This created another question for me, is there an advantage to using DDA+ on the mzML files from diatracer, or does diatracer already handle the issue of multiple precursors / spectrum.

Todd

**Comment by anesvi** [comment]
At the moment diatracer.mzML may not even work as DDA+ because there is no MS1 data there. And I don't think the results will be good if it does not crash. I think it would not be a good idea because diatracer should have split ms2 into separate scans already.

**Comment by Dmorgen** [comment]
Thanks for the answer - kjust to be sure: load both diatracer AND the .d files?

Thanks!
David.

**Comment by anesvi** [comment]
Yes, with .d annotated as DIA-Quant

**Comment by Dmorgen** [comment]
Thank you!
