### ISSUE TITLE
Integration of DDA and DIA data

### ISSUE THREAD

**Issue by AIDDocking** [Nesvilab/FragPipe#1834]
Dear Fragpipe team,
I have a quick question regarding the integration of DIA and DDA data. For example, I have a batch of DIA data (100 tumor samples, Thermo .raw files available) and I want to integrate this with a public DDA dataset of the same tumor (100 samples, Thermo .raw files available). I’m wondering if this is feasible using the Fragpipe (perhaps with DIA_SpecLib_Quant workflow?) to generate a single combined proteomics dataset (n=200). Thank you in advance!

**Comment by anesvi** [comment]
Yes, totally possible. Load DDA files as DDA type and DIA files as DIA. Use DIA_SpecLib_Quant workflow. You may need to convert RAW to mzML first since DIA-NN requires separate installation of the Thermo raw file reader. So use mzML instead

**Comment by anesvi** [comment]
Ok, I am not clear now if I understood your question. You can build a combined library and use it to extract quant from DIA data. But you will not have both DDA and DIA files quantified in one analysis. If that is what you asked, then no ( and I am not sure any tool can do it). You will need to to run a separate LFQ-MBR workflow on DDA data to get MS1 quant for those files. then somehow merge quant from the DDA and DIA tables (but harmonizing data would be hard)
