### ISSUE TITLE
All modified peptides have zero intensity when quantifying with labile-phospho. 

### ISSUE THREAD

**Issue by POde97** [Nesvilab/FragPipe#1835]
Hi all, 

I can't understanding why all the peptides are quantified to zero intensity when using labile-phosphor default workflow despite the flag ionquant.run-ionquant=true in the workflow file. (While when using LFQ-phospho I get a proper quantification ) 

Also is not totally clear to me the structure of the output and why I'm not getting anymore the combined_modified_peptide.tsv
If I well understood some of the informations that can be found in the combined_modified_peptide.tsv are present in the msstats.csv  but still every PTMs has zero intensity. 
Further it is not super clear to me what is the combined_protein.tsv output of labile phospho. 
Also following the tutorial https://fragpipe.nesvilab.org/docs/tutorial_labile.html  I noticed that I'm not getting any psm.tsv from the labile-phosphor workflow. 

Can you please help me in understanding what I'm doing wrong? 
I attached my log 

Thank you in advance ! 

[log_2024-10-17_14-53-06.txt.zip](https://github.com/user-attachments/files/17434516/log_2024-10-17_14-53-06.txt.zip)

**Comment by fcyu** [comment]
You should also set `quantitation.run-label-free-quant=true` as well.

Best,

Fengchao
