### ISSUE TITLE
EasyPQP couldn't import PyOpenMS package

### ISSUE THREAD

**Issue by actopossum** [Nesvilab/FragPipe#1836]
Hi,

I am running Fragpipe22 and it was working fine but I upgraded to easypqp v.1.5.0 and it seems to now have issues. I tried looking for the pyOpenMS libraries but I couldn't find the pyopenms*.so file within the directory as suggested in the dependency walker debug comment. 

I had recently installed a standalone DIA-nn which messed up the skyline document functionality in Fragpipe22 but I think that's a separate issue.

Thanks for your help!

[log_2024-10-22_11-37-21.txt](https://github.com/user-attachments/files/17480615/log_2024-10-22_11-37-21.txt)

**Comment by fcyu** [comment]
Could you run the following to uninstall and install some Python packages in command line interface?

```shell
uninstall easypqp pyopenms -y
install easypqp
```

Thanks,

Fengchao

**Comment by actopossum** [comment]
Hi Fengchao!
Thanks for the quick response. Is this a cmd prompt or python prompt? I tried both and it's not working. Is 'uninstall.exe' in a fragpipe directory?

**Comment by fcyu** [comment]
Ah, I am sorry. I guess my head was not clear when I was typing. The commands should be

```shell
pip uninstall easypqp pyopenms -y
pip install easypqp
```

> Is this a cmd prompt or python prompt?

Should be the cmd prompt that with pip (and Python) in the PATH.

Best,

Fengchao

**Comment by actopossum** [comment]
Ok I was able to uninstall and reinstall but I still get the same error as before. I did notice it seemed to not install in the site-packages folder so I tried adding that to PATH but it didn't help.

#### last few lines of the output from install command.
Installing collected packages: pyopenms, easypqp
  WARNING: The script easypqp.exe is installed in 'C:\Users\shaoen\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed easypqp-0.1.50 pyopenms-3.2.0

**Comment by guoci** [comment]
@actopossum 
Please do:
```
C:\ProgramData\anaconda3\pip uninstall easypqp pyopenms -y
C:\ProgramData\anaconda3\pip install easypqp
```

**Comment by actopossum** [comment]
I did do that but it seems to not make a difference. Not sure it matters but this is on a Windows Server 2019 box.

**Comment by guoci** [comment]
@actopossum 
I would suggest you try on a new install of Python. Using an existing installation may be causing the problem.
Can you install a new Python using Miniconda? https://docs.anaconda.com/miniconda/miniconda-install/
Please use Python 3.11 https://repo.anaconda.com/miniconda/Miniconda3-py311_24.7.1-0-Windows-x86_64.exe
Then, change the FragPipe Python path to the newly installed Python.

**Comment by actopossum** [comment]
Thanks Fengchao! 
That seems to have done the trick. Didn't solve the Skyline document issue but maybe I should open a new thread for that.

**Comment by fcyu** [comment]
Fixed in https://github.com/OpenMS/OpenMS/pull/7699
