### ISSUE TITLE
regional settings for 'Generate Skyline Document' for default setting --import-search-cutoff-score=0.852736 causes Error: The value '852736' for the argument --import-search-cutoff-score must be between 0 and 1.

### ISSUE THREAD

**Issue by Andre-C-M** [Nesvilab/FragPipe#1838]
Dear Fragpipe team,

Enabling the Skyline document creation feature in Fragpipe causes:

Error: The value '852736' for the argument --import-search-cutoff-score must be between 0 and 1.

The log file shows the default setting:
--import-search-cutoff-score=0.852736

running on a European system this looked like being caused by the same old ',' vs '.' separator issue. Indeed switching Windows system settings (from ',' seperator to '.') fixed the issue.

Hope this helps others or might be worth fixing.

Thx

**Comment by fcyu** [comment]
Thanks for the feedback. I think we saw similar problems years ago when a German team used our tools. It is a little tricky to fix from our side. I think the easiest way is changing the operating system's format (as you have already done).

Best,

Fengchao
