### ISSUE TITLE
Spectral Library Generation: PeptideProphet failing

### ISSUE THREAD

**Issue by tryhard124** [Nesvilab/FragPipe#1839]
Hi all, 

I'm having a similar proplem to that deatiled in this [thread ](https://github.com/Nesvilab/FragPipe/issues/152) so I thought I'd open up a new issue. I double-checked and I didn't have any problems with my FASTA file, so I'm not sure why PeptideProphet is failing. I'm attaching my log and fasta file (in my workflow i have it as a fasta.fas file but converted to .txt to attach it here) in case y'all might be able to help. This is a spectral library for a single protein using DDA data generated on TF Orbitrap Ascend. 

[log_2024-10-23_17-43-33.txt](https://github.com/user-attachments/files/17499569/log_2024-10-23_17-43-33.txt)

[2024-10-23-decoys-Martin_P37840.txt](https://github.com/user-attachments/files/17499578/2024-10-23-decoys-Martin_P37840.txt)

Cheers, 
Martín

**Comment by anesvi** [comment]
Your database has only 42 peptides. Is it just a single protein ? Tools like Percolator or PeptideProphet are not applicable when too few PSMs. You can see if percolator works but I doubt. You need to search a bigger database or not use those tools and not apply FDR filters

**Comment by tryhard124** [comment]
Yes it's just a single protein. I'm trying to build up a PRM method for this single protein and its PTMs. I was trying to build a spectral library but since the list of peptides is short, do I just manually selecting precursors w/ rt's from the data since the list is so short? I was under the impression that it's still needed for data processing. As you predicted, percolator failed when I orginally tried to process this data on PD so I used Fixed Value PSM validator.

**Comment by anesvi** [comment]
I am not sure. Yes you can look at MSFragger output. You can also try to search a bigger database. Often there are a many contaminant or copurifying  proteins, which would give enough PSMs for modeling. Or use Skyline instead of FragPipe, they have search engines incorporated, and must have a good way to build PRM assays
