### ISSUE TITLE
Process returned non-zero exit code

### ISSUE THREAD

**Issue by Li5459000** [Nesvilab/FragPipe#1842]
Hi,

I'm analyzing peptides with dimethyl modification and facing this issue.
Could you help me with it.

[log_2024-10-25_10-59-32.txt](https://github.com/user-attachments/files/17529732/log_2024-10-25_10-59-32.txt)

**Comment by fcyu** [comment]
There are no identifications from your files. Please double check the parameter settings and your data.

Best,

Fengchao

**Comment by Li5459000** [comment]
Wrong parameters setteing.
I fixed it. 

Thank you
