### ISSUE TITLE
Error with TMT intergrator

### ISSUE THREAD

**Issue by TomasKoudelka** [Nesvilab/FragPipe#1843]
Hi,
I am running MS Fragger with a modified standard TMT workflow, though I need MS fragger to do a semi-tryptic search
Unfortunately it stops at TMT Intergrator. 

"For input string: "3M(15.9949), N-term(304.2071)": 3M(15.9949), N-term(304.2071) is not a number.

Attached is also the log file.

I tried a few things but I could get it to work, but nothing seemed to work and it came up with the same error.

Any help would be greatly appreciated. 
Thanks,
Tom

[Errorlog_2024-10-26_20-56-24.txt](https://github.com/user-attachments/files/17531710/Errorlog_2024-10-26_20-56-24.txt)

**Comment by fcyu** [comment]
The TMT intensity extraction tool was set to "Skip extraction. Run TMT-Integrator only", which caused the error. Please change it back to the default settings.

Best,

Fengchao
