### ISSUE TITLE
diaTracer issue

### ISSUE THREAD

**Issue by jaydeb8** [Nesvilab/FragPipe#1844]
I've been trying to run the DIA_SpecLib_Quant_Phospho_diaPASEF workflow, and I keep getting a non-zero exit code (137) in diaTracer that cancels the workflow. I've attached the log. I'm happy to provide any additional information and appreciate any help!

[log_2024-10-27_14-35-03.txt.zip](https://github.com/user-attachments/files/17535069/log_2024-10-27_14-35-03.txt.zip)

**Comment by fcyu** [comment]
Exit code 137 means not enough memory.

FragPipe detected that there are 619 GB free memory. Could you double check if it is correct? If not, could you tell me how much memory is available in your computer? FragPipe/Java might have issues getting the correct memory size in some HPC.

Best,

Fengchao

**Comment by jaydeb8** [comment]
I'm not sure exactly how much memory I have access to. I'm working in a
visualization node, and I think it depends on how many people are using it.
I just checked, and it says that there is currently 569GB free. Is there a
way I can specify how much memory FragPipe/Java uses?

Thanks,
Jayde

**Comment by fcyu** [comment]
Yes, you can specify it in the "RAM (GB, 0=auto)" spinbox of the "workflow" tab.

Best,

Fengchao

**Comment by jaydeb8** [comment]
I’ll try that. Thanks!

**Comment by KaiLiCn** [comment]
Hi Jayde,

What's the size of your .d files? The running time was longer than what I expected. Could you share one of you file with us? You can upload it here: https://www.dropbox.com/request/pMxCvDrGIjYuDKkIWAWm . Can you tell us your MS/MS setting?

Best,
Kai

**Comment by jaydeb8** [comment]
Hi Kai,

They are pretty large files, like 10gb. I've uploaded one to the dropbox.
I'll have to go back and look at the MS/MS setting because they were run at
a Bruker facility.

Thanks,
Jayde

**Comment by KaiLiCn** [comment]
Hi Jayde, thank you for sharing the file. I will take a look and let you know.

**Comment by KaiLiCn** [comment]
Hi Jayde,

I ran a test on your data. It's a big file and diaTracer detects high numbers of MS2 signals compared with other datasets I tested. But it still worked on my side using Xmx100G. So I think your server was busy and there was no enough memory when you ran FragPipe. 

We are working on the performance and memory optimization. We will reduce the memory usage in the future.

Best,
Kai
