### ISSUE TITLE
EasyPQP couldn't import PyOpenMS package

### ISSUE THREAD

**Issue by bingnanzhao** [Nesvilab/FragPipe#1845]
[log_2024-10-25_16-14-59.txt](https://github.com/user-attachments/files/17543641/log_2024-10-25_16-14-59.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
Hi Fragpipe team, last week I used DIA_specLib_Quant workflow and encountered this error. I never met this before last week when I used the same workflow. 

Thanks,
Bingnan

**Comment by fcyu** [comment]
Seems to be the same as https://github.com/Nesvilab/FragPipe/issues/1836, https://github.com/Nesvilab/FragPipe/issues/1543, and https://github.com/Nesvilab/FragPipe/issues/1431

> the user uses an administrator installed Python, then installs Python packages using a non-administrator account, and that combination causes PyOpenMS to break.

Could you either 

> I created a new environment and selected the new python.exe within fragpipe. Clicking 'Install/Upgrade EasyPQP' afterwards will install all dependencies and versions properly.

or 

> I would suggest you try on a new install of Python. Using an existing installation may be causing the problem.
> Can you install a new Python using Miniconda? https://docs.anaconda.com/miniconda/miniconda-install/
> Please use Python 3.11 https://repo.anaconda.com/miniconda/Miniconda3-py311_24.7.1-0-Windows-x86_64.exe
> Then, change the FragPipe Python path to the newly installed Python.

Thanks,

Fengchao
