### ISSUE TITLE
Process 'MSFragger' finished, exit code: 1

### ISSUE THREAD

**Issue by XiheNiu** [Nesvilab/FragPipe#1846]
Dear Fragpipe team,
I encountered an error while using Fragpipe in the process of mass calibration and parameter optimization.

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
java.lang.NegativeArraySizeException: -233194112
	at umich.ms.fileio.filetypes.mzbin.MZBINFile.writeMZBIN(MZBINFile.java:239)
	at e.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.c(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

And I would like to inquire about the appropriate settings for PTM (Post-Translational Modification) configuration when using Fragpipe to search for lipidations in my samples.  Additionally, I am interested in attempting to discover new types of lipid modifications in my samples.  Could you please guide me on how to correctly utilize Fragpipe to achieve this?

Looking forward to your reply!
Xihe.

**Comment by XiheNiu** [comment]
> Dear Fragpipe team, I encountered an error while using Fragpipe in the process of mass calibration and parameter optimization.
> 
> **_**MASS CALIBRATION AND PARAMETER OPTIMIZATION**_ -----|---------------|---------------|---------------|--------------- | MS1 (Old) | MS1 (New) | MS2 (Old) | MS2 (New) -----|---------------|---------------|---------------|--------------- Run | Median MAD | Median MAD | Median MAD | Median MAD java.lang.NegativeArraySizeException: -233194112 at umich.ms.fileio.filetypes.mzbin.MZBINFile.writeMZBIN(MZBINFile.java:239) at e.(Unknown Source) at edu.umich.andykong.msfragger.MSFragger.c(Unknown Source) at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source) at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source) Process 'MSFragger' finished, exit code: 1 Process returned non-zero exit code, stopping
> 
> And I would like to inquire about the appropriate settings for PTM (Post-Translational Modification) configuration when using Fragpipe to search for lipidations in my samples. Additionally, I am interested in attempting to discover new types of lipid modifications in my samples. Could you please guide me on how to correctly utilize Fragpipe to achieve this?

Looking forward to your reply!
Xihe.

**Comment by fcyu** [comment]
Could you share your log file (the file with the name starts with "log_2024").

Thanks,

Fengchao

**Comment by XiheNiu** [comment]
Hi Fengchao, please see attached.
[log_2024-10-29.txt](https://github.com/user-attachments/files/17550881/log_2024-10-29.txt)

Best,
Xihe

**Comment by fcyu** [comment]
Is your data from timeTOF ddaPASEF? If so, please don't convert it to mzML but use the .d

Best,

Fengchao

**Comment by XiheNiu** [comment]
Thank you!
As you mentioned, there was no error when I used.d before, and the above error would occur when converting to mzML.

I have another inquiry: I have set up the dynamic modification information for palmitoylation, but in the final result file, I encountered a large number of unexpected outcomes where peptides that were not supposed to have the modification are showing as modified. Could you please advise if there might be an issue with my settings?

Best,
Xihe

**Comment by fcyu** [comment]
Could you share the log file of the other analysis? Also the "final result file" that you were referring to?

Thanks,

Fengchao

**Comment by XiheNiu** [comment]
Please see attached.

[log_2024-10-17_00-03-15.txt](https://github.com/user-attachments/files/17551052/log_2024-10-17_00-03-15.txt)
[combined_modified_peptide.txt](https://github.com/user-attachments/files/17551260/combined_modified_peptide.txt)

Upon reviewing the combined_modified_peptide file, we have noticed that many peptides are being flagged with numerous lipidations (the modification information was set by me). However, upon closer inspection, it appears that these lipidations did not actually occur. I am seeking your guidance to determine if there might be an issue with my parameter settings.

Best,
Xihe

**Comment by anesvi** [comment]
Yes, please do not deviate from the standard workflows unless you understood the tools well enough. If you see evidence of lipidation from the standard open search (mass shifts corresponding to lipidation), perform a closed search with lipidation as variable modifications, or use mass offset search instead.
