### ISSUE TITLE
Quick way to find PE

### ISSUE THREAD

**Issue by NikolaMonteverde** [Nesvilab/FragPipe#1847]
**- Describe the feature:**
This may already exist but I haven't seen it. I use group specific FDR for my searches. In my FASTA file I have PE=1, 2 or 3 for each group. I would like to be able to see what group a peptide was identified from.

**Comment by anesvi** [comment]
If you set group FDR option "from fasta" in MSFragger, it should propagate PE to PSM.tsv files. There will be a column called Class or something like it
