### ISSUE TITLE
Replicates merged

### ISSUE THREAD

**Issue by kreitman** [Nesvilab/FragPipe#1848]
[log_2024-10-28_18-13-57.txt](https://github.com/user-attachments/files/17559065/log_2024-10-28_18-13-57.txt)

I'm trying to analyze two DIA datasets in the same Workflow and although the DIA-NN quantification tab executes these separately, they are merged in the final peptide.tsv and protein.tsv etc. output files. I'm also unable to locate the .mgf exported file specified 
in the MSFragger tab. Hopefully this is all simple user error and thanks for your assistance.

**Comment by fcyu** [comment]
The TSV files outside of the diann-output folder are temp files generated during the spectral library building. For the DIA quant result, please use the files in the diann-output folder.

Regarding the mgf file generation, I don't think it works for the DIA data.

Best,

Fengchao
