### ISSUE TITLE
FragPipe is not generating a Spectral Library

### ISSUE THREAD

**Issue by eunseokim37** [Nesvilab/FragPipe#1849]
![102924_SpecLIb_error](https://github.com/user-attachments/assets/f5965240-bd9c-432e-8097-b3b6d5197284)
FragPipe is not generating a spectral library. I installed PQP 0.1.50 to see if it would fix the problem but it is not working. Picture of error message is attached.

**Comment by fcyu** [comment]
Could you share the log file?

Thanks,

Fengchao

**Comment by eunseokim37** [comment]
[log_2024-10-29_10-31-54.txt](https://github.com/user-attachments/files/17560193/log_2024-10-29_10-31-54.txt)

**Comment by fcyu** [comment]
There are spaces in the path: `C:/Program Files/FragPipe-22.0/...`. Please move FragPipe-22.0 to a folder without any spaces and try again.

Best,

Fengchao

**Comment by eunseokim37** [comment]
Thank you for getting back to me. I tried moving FragPipe-22.0 to different locations without spaces, and FragPipe still did not generate a library. Could you take a look at this new log file and tell me if there is still something wrong with my path? 
Thank you! 

[log_2024-10-29_12-50-01.txt](https://github.com/user-attachments/files/17561777/log_2024-10-29_12-50-01.txt)

**Comment by fcyu** [comment]
It seems that you didn't. There are still `C:\Program Files\FragPipe-22.0....`

Best,

Fengchao

**Comment by eunseokim37** [comment]
It works now, thank you!
