### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#185]
the old version (msfragger 2019 and philosopher 2.1.2) works the last no (msfragger 2.4 and philosopher 3.2.3) on the same file 
[log_2020-04-09_16-09-04.txt](https://github.com/Nesvilab/FragPipe/files/4456700/log_2020-04-09_16-09-04.txt)
 
log:
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\fragpipe\speclib\gen_con_spec_lib.py", line 705, in <module>
    edit_raw_con_lib()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\fragpipe\speclib\gen_con_spec_lib.py", line 674, in edit_raw_con_lib
    axis=1, result_type='expand')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4262, in apply
    ignore_failures=ignore_failures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4358, in _apply_standard
    results[i] = func(v)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4239, in f
    return func(x, *args, **kwds)
TypeError: ("f() got an unexpected keyword argument 'result_type'", 'occurred at index 0')
Process 'SpecLibGen' finished, exit code: 1

Process returned non-zero exit code, stopping
SpecLibGen
java -cp C:\MSFragger\FragPipe.exe umich.msfragger.util.FileDelete E:\Proteomica\RAW_DATA_Challenge\MSFragger\2\RAW_DATA_Challenge\TN_CSF_062617_03.mzML

~~~~~~~~~~~~~~~~~~~~
Cancelling 3 remaining tasks
Processing interrupted, stopping SpecLibGen

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by guoci** [comment]
@Angrist75 please upgrade your python modules with `conda update --yes --all` in Anaconda prompt.

**Comment by Angrist75** [comment]
I did as you asked, but the problem persists, I enclose logs.
[log_2020-04-09_18-33-41.txt](https://github.com/Nesvilab/FragPipe/files/4457525/log_2020-04-09_18-33-41.txt)

**Comment by guoci** [comment]
Can you type `python -c "import pandas; print(pandas.__version__)"` in your Anaconda Prompt and tell me what you get?

**Comment by Angrist75** [comment]
0.20.3

**Comment by guoci** [comment]
that module was not updated, you should get `1.0.3`

**Comment by Angrist75** [comment]
so what should I type? I'm just a poor chemist :)

**Comment by guoci** [comment]
try `conda update pandas`
and show me the output

**Comment by Angrist75** [comment]
![Screenshot 2020-04-09 22 31 21](https://user-images.githubusercontent.com/63410174/78938237-2adb3d80-7ab2-11ea-9bd1-d679ff1f6459.png)

**Comment by guoci** [comment]
try reinstalling Ananconda, and then `conda update --yes --all`

**Comment by Angrist75** [comment]
Thank you very much I solved it as you told me to. Everything's working out for the best now.
