### ISSUE TITLE
JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by mdjones** [Nesvilab/FragPipe#1850]
docker pull fcyucn/fragpipe
sudo docker run -it -v  /tmp/fragpipe:/fragpipe fcyucn/fragpipe /bin/bash

$ cd /fragpipe_bin/fragPipe-22.0/fragpipe/bin/
$ ./fragpipe --help

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-17-openjdk-amd64/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

$ env | grep JAVA_HOME
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
$ ls /usr/lib/jvm/java-17-openjdk-amd64/
bin  conf  docs  include  jmods  legal  lib  man  release

**- Describe the issue or question:**

fragpipe complains that JAVA_HOME is set to an invalid directory

**Comment by fcyu** [comment]
Could you change the `JAVA_HOME` to the real one in your computer using the command such as `ENV JAVA_HOME <path>`? 

If you are not familiar with the command line interface or Linux, I suggest you use the FragPipe in GUI mode.

Best,

Fengchao

**Comment by mdjones** [comment]
Thanks,

Is there anything else that I should be looking out for that is not in the fcyucn/fragpipe image? 

I added my local JAVA_HOME but I am still getting the error even though java is present and executable. 

```
cat Dockerfile
FROM fcyucn/fragpipe

ENV JAVA_HOME /usr/prog/Java/1.8.0_162/
RUN export JAVA_HOME

docker build -t dpro-fragpipe -f Dockerfile .

docker run -it -v /tmp/fragpipe:/fragpipe \
        -v  /usr/prog/Java/1.8.0_162/:/usr/prog/Java/1.8.0_162/ \
        dpro-fragpipe /bin/bash

./fragPipe-22.0/fragpipe/bin/fragpipe

ERROR: JAVA_HOME is set to an invalid directory: /usr/prog/Java/1.8.0_162/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

root@4204385f4a69:/fragpipe_bin# ls -l /usr/prog/Java/1.8.0_162/bin/java
-rwxr-xr-x. 1 1000 1000 7734 Dec 20  2017 /usr/prog/Java/1.8.0_162/bin/java
```
Also, would you please tell me the required java version?

**Comment by mdjones** [comment]
I noticed you do a yum install java on your image so I shouldn't need to set the JAVA_HOME to my local installation. 

Here is how I did it in my initial post as described here: https://fragpipe.nesvilab.org/docs/tutorial_docker.html
```
docker pull fcyucn/fragpipe
Using default tag: latest
latest: Pulling from fcyucn/fragpipe
Digest: sha256:d790a9f499c5036750f560e52dfbf7a3501a6d27e466b94c49f240c48601bbd4
Status: Image is up to date for fcyucn/fragpipe:latest
docker run -it -v /tmp/fragpipe:/fragpipe fcyucn/fragpipe /bin/bash
root@a4314f1de0c1:/fragpipe_bin# echo $JAVA_HOME
/usr/lib/jvm/java-17-openjdk-amd64/
root@a4314f1de0c1:/fragpipe_bin# ls -l /usr/lib/jvm/java-17-openjdk-amd64/bin/java
-rwxr-xr-x. 1 root root 14464 Jan 17  2024 /usr/lib/jvm/java-17-openjdk-amd64/bin/java

root@a4314f1de0c1:/fragpipe_bin# ./fragPipe-22.0/fragpipe/bin/fragpipe

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-17-openjdk-amd64/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
It seems to be there and should pass the test which I assume is here: https://github.com/Nesvilab/FragPipe/blob/b5075fe5ea8a123988eef9308452e2601081abc7/MSFragger-GUI/gradlew#L120


Note: Java will also not execute. 

```
root@a4314f1de0c1:/fragpipe_bin# /usr/lib/jvm/java-17-openjdk-amd64/bin/java
[0.011s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /fragpipe_bin/hs_err_pid8.log
```

**Comment by mdjones** [comment]
Sorry, typo, yes apt-get. 

There is 10 GB available. 

```
root@bda58ef3016f:/fragpipe_bin# free -h
               total        used        free      shared  buff/cache   available
Mem:            62Gi       4.6Gi        10Gi        50Mi        47Gi        57Gi
Swap:           99Gi       8.0Mi        99Gi
```


Mike

**Comment by fcyu** [comment]
Could you run `/usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xmx4G`?

Thanks,

Fengchao

**Comment by mdjones** [comment]
``` 
root@bda58ef3016f:/fragpipe_bin# /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xmx4G
[0.012s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /fragpipe_bin/hs_err_pid17.log
```

**Comment by fcyu** [comment]
Could you uninstall the java 17 and reinstall? I am not sure why it has issues on your host computer.

Best,

Fengchao

**Comment by guoci** [comment]
@mdjones your issue is explained here with a fix: https://github.com/adoptium/containers/issues/215#issuecomment-1142046045

**Comment by mdjones** [comment]
@guoci - that makes sense. I have tried it on a more current version of Docker and it seems to work. Thanks

```
root@fee12fd9d458:/fragpipe_bin# ./fragPipe-22.0/fragpipe/bin/fragpipe --headless
Please provide --workflow <path to workflow file> in the headless mode.
```
