### ISSUE TITLE
Could not get isolation window info from scan 7557

### ISSUE THREAD

**Issue by aakendra11** [Nesvilab/FragPipe#1851]
Trying to perform analysis on a DIA dataset, and keep getting an error where the process stops at an arbitrary scan because it cannot identify an isolation window.  Unsure how 7556 scans could be read properly, then encounter an issue on the 7557th scan. 

I'm using the default DIA settings.  I've performed data-acquisition on this sample twice, exported as an MZML and ultimately got this issue both times, albeit with a different scan number that triggers the error.  Also unsure if the issue is with the input MZML file or with Fragpipe failing to read it.

[log_2024-10-29_17-04-25.txt](https://github.com/user-attachments/files/17563250/log_2024-10-29_17-04-25.txt)

Thank you for your help, Beyond this issue Fragpipe has been a joy to use as I'm learning proteomic bioinformatics.

Best,
-Aidan

**Comment by fcyu** [comment]
Hi Aidan,

Could you share the `FK506pdDIA.mzML` and also the raw format file with us? I will give you a link to upload if you need one.

Thanks,

Fengchao

**Comment by aakendra11** [comment]
Hi Fengchao, thanks for looking into this problem with me.
Could you please send me an upload link?  Github doesn't seem to support the .d or .mzml filetype
Best,
-Aidan

**Comment by fcyu** [comment]
Wait, is your file from timsTOF diaPASEF? Then, you should use the .d and the DIA_SpecLib_Quant_diaPASEF workflow.

Best,

Fengchao

**Comment by aakendra11** [comment]
Hi Fengchao, the instrument I'm using is an Agilent 6546 Q-TOF, no IMS on this instrument. The default file extension I get from the Agilent software is also .d
-Aidan

**Comment by fcyu** [comment]
Oh, OK. Thanks for clarifying. Agilent's native format is also .d.....

Here is the link to upload the .d and mzML files: https://www.dropbox.com/request/bsU0i83zZ5EZD7XCuXNS

Best,

Fengchao

**Comment by fcyu** [comment]
Thank you for sharing the files. I have confirmed that there is no isolation window info (such as boundary and width), which is critical for the DIA analysis. Please contact the vendor because it is beyond our scope.

Best,

Fengchao
