### ISSUE TITLE
Process 'Percolator' finished, exit code: 1 - Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by pkarousi** [Nesvilab/FragPipe#1853]
[log_2024-10-30_09-49-46.txt](https://github.com/user-attachments/files/17567942/log_2024-10-30_09-49-46.txt)

Hello,

I'm getting this error for the first time, any ideas?

**Comment by anesvi** [comment]
I see there is at least one run where there are no IDs. Not sure if that is the problem. You can try to remove those files. Check the log, find bad runs. Then rerun. You do not need to rerun from the beginning. Load diatracer.mzML files as DDA type. Load the original .d as DIA-Quant. But, again, do not load diatracer.mzML files that have 0 IDs in Percolator. See if that works
