### ISSUE TITLE
stat lib: Don't have that file or directory

### ISSUE THREAD

**Issue by amingson** [Nesvilab/FragPipe#1854]
**- Describe the feature:**

Hello dear author, 
I encountered an error when searching the timstof file. I prompted the following error content. At the same time, the running log is placed in the attachment for your reference. Please help guide.
![image](https://github.com/user-attachments/assets/b0435684-9c5e-49bf-a5cd-6466e48335b1)
[log_2024-10-31_02-50-40.txt](https://github.com/user-attachments/files/17578584/log_2024-10-31_02-50-40.txt)

Best，
Anler

**Comment by fcyu** [comment]
Something was wrong with your OS or file system because MSFragger ran well and suddenly couldn't find a brunch of cache files.

Best,

Fengchao

**Comment by amingson** [comment]
> Something was wrong with your OS or file system because MSFragger ran well and suddenly couldn't find a brunch of cache files.
> 
> Best,
> 
> Fengchao

Thank you for replying so quickly, but this didn't happen when I searched for other data. Is it because the random access memory set by your is not enough? Or is there a good direction for me to check?

Best,
Anler

**Comment by fcyu** [comment]
Hard for me to tell with the limited info and remotely. Please contact your local IT department for help.

Best,

Fengchao

**Comment by amingson** [comment]
> Hard for me to tell with the limited info and remotely. Please contact your local IT department for help.
> 
> Best,
> 
> Fengchao

OK, thank you very much for your enthusiastic help!

Best,
Anler
