### ISSUE TITLE
PeptideProphet fails to estimate "perfect “spectras

### ISSUE THREAD

**Issue by molshatzki** [Nesvilab/FragPipe#1855]
We are simulating DIA data (using synthedia https://github.com/mgleeming/synthedia/) and putting it through FragPipe. When we simulate "perfect" fragmentation of spectras, it fail at PeptideProphet and we hardly get any PSMs ("perfect_log" attached below). In comparison, when we simulate partial ("regular_log" attached below) fragmentation (which is much more resembling of real data), we get good results and much more PSMs identified (which match the expected peptides).
We are using the DIA_SpecLib_Quant workflow on FragPipe, with one change of using PeptideProphet (with closed search defaults) instead of Percolator.
Do you know why PeptideProphet fails to estimate "perfect “spectras? Maybe the mixture of the two (correct/ incorrect) distributions is too separated? Maybe the empirical discrimination scores don’t follow the fitted curves well? Is there a way to extract estimated discrimination score so we can learn more on its distribution?
Best, Noa

[perfect_log.txt](https://github.com/user-attachments/files/17585302/perfect_log.txt)
[regular_log.txt](https://github.com/user-attachments/files/17585305/regular_log.txt)

**Comment by fcyu** [comment]
> Maybe the mixture of the two (correct/ incorrect) distributions is too separated? 

Yes.

> Is there a way to extract estimated discrimination score so we can learn more on its distribution?

Yes, check the `interact-*.pep.xml` file.

Best,

Fengchao

**Comment by anesvi** [comment]
If PeptideProphet failed, there will be no interaction-.pep.xml file. They probably have to plot it based on the MSFragger pep.xml or pin file. And yes PeptideProphet models the distributions, with no negative component the model is not applicable.

**Comment by molshatzki** [comment]
Thank you @fcyu and @anesvi!
@anesvi do you know if there's a minimal number / percentage of negative component required?
