### ISSUE TITLE
Process 'MSFragger' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by Hongbo-Jiao** [Nesvilab/FragPipe#1856]
Dear Fragpipe team,
I am a beginner and am trying to follow the official label-free quantification tutorial to process the raw data obtained from the timsTOF pro 2. However, I did not get the expected results. Fragpipe gave the following error:

```
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

On GitHub's issues, I found someone who had the same problem as me, but in fact, what I submitted was indeed a` .d `file, that is very confusing to me.The following is the log file [log_2024-10-31_23-16-27.txt](https://github.com/user-attachments/files/17590121/log_2024-10-31_23-16-27.txt)
I would be very grateful if you could tell me how to solve it.

Hongbo

**Comment by KaiLiCn** [comment]
Hi,

Can you share your log file with us? It's located in your result folder.

Thanks,
Kai

**Comment by Hongbo-Jiao** [comment]
Sure, this is the log file found in my result folder.[log_2024-10-31_23-16-27.txt](https://github.com/user-attachments/files/17590186/log_2024-10-31_23-16-27.txt)

best

**Comment by KaiLiCn** [comment]
Based on your log, you only set 3G memory which was not enough for FragPipe and caused the insufficient memory error. Please increase the memory under workflow panel.

**Comment by Hongbo-Jiao** [comment]
Thank you. I changed the RAM from 0 to 6G and solved the problem.
