### ISSUE TITLE
How to treat searches with independent FASTA files

### ISSUE THREAD

**Issue by NikolaMonteverde** [Nesvilab/FragPipe#1858]
**- Describe the feature:**
In a recent experiment, I was searching 10 different sets of immunopeptidomics samples against 10 unique FASTAs. Each set of samples is from a tumor with known mutations which is why we use a custom FASTA for each. I want to compare the 10 samples side by side to see how broad changes in the immunopeptidome look not just the mutations. I think that if I simply fuse together the results tables, I will get a lot of missing values due to accumulation of false identifications in the 10 sample sets. Is there a way to correct for this? One alternative is avoiding the issue altogether by running all the samples together with a canonical FASTA for broad changes in immunopeptidome and then search with unique FASTAs for the mutations.

**Comment by fcyu** [comment]
Maybe combine those 10 databases and search your data together?

Best,

Fengchao

**Comment by anesvi** [comment]
I don't think there one clear way we can suggest. Depends on how noisy the databases are, what you plan to do with the IDs later. This is more of a research question.
