### ISSUE TITLE
Crash post search - insufficient memory?

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#1859]
Hi,

I'm running DIA-PASEF spec-lib-quant analysis (the same as before...) and it crashed again, now post search. maybe insufficient memory? (how to deal with it in later stages of validation and quantification?)
please see attached,
Thanks!
David.

[log_2024-11-01_00-21-51.txt](https://github.com/user-attachments/files/17604765/log_2024-11-01_00-21-51.txt)

[hs_err_pid10704.log](https://github.com/user-attachments/files/17604767/hs_err_pid10704.log)

**Comment by fcyu** [comment]
Yes, not enough memory.

I am not sure why MSBooster requires so much memory because there seems to have 50 GB:

```shell
MSBooster [Work dir: E:\PXD053895\MSF2]
C:\Apps\fragpipe\jre\bin\java.exe -Xmx50G -cp C:\Apps\fragpipe\tools\MSBooster-1.2.31.jar;C:\Apps\fragpipe\tools\batmass-io-1.33.4.jar Features.MainClass --paramsList E:\PXD053895\MSF2\msbooster_params.txt
2024-11-01 00:21:25 [INFO] - MSBooster v1.2.31
2024-11-01 00:21:28 [INFO] - Using 20 threads
2024-11-01 00:21:34 [INFO] - Initializing E:\PXD053895\1-10_Slot1-28_1_2917_diatracer.mzML
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000271ac000000, 6442450944, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 6442450944 bytes for G1 virtual space
# An error report file with more information is saved as:
# E:\PXD053895\MSF2\hs_err_pid10704.log
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Maybe Kevin can take a look.

Best,

Fengchao

**Comment by yangkl96** [comment]
I'll download the data and take a look

**Comment by yangkl96** [comment]
Hi David,

I was not able to replicate this memory error, even when I used just 20GB of memory and 20 threads. Have you rerun this analysis to see if it consistently crashes on your end?

Thanks,
Kevin

**Comment by yangkl96** [comment]
Could you include the log file from your run where it crashed at DIA-NN quant? Was it also an out of memory error?

**Comment by Dmorgen** [comment]
[log_2024-11-03_00-50-38.txt](https://github.com/user-attachments/files/17653274/log_2024-11-03_00-50-38.txt)
[log_2024-11-03_00-51-20.txt](https://github.com/user-attachments/files/17653275/log_2024-11-03_00-51-20.txt)
[hs_err_pid10704.log](https://github.com/user-attachments/files/17653279/hs_err_pid10704.log)


[log_2024-11-04_08-22-03.txt](https://github.com/user-attachments/files/17653295/log_2024-11-04_08-22-03.txt)
I've added here logs from two runs. with and without MSBooster. both cases quantification failed.
the first 2 are from one run and 2 from the 2nd.

**Comment by Dmorgen** [comment]
And another one - first tried to split DBs, which failed for some reason (after updating easyPQP). the it failed again.


[log_2024-11-07_00-20-18.txt](https://github.com/user-attachments/files/17653709/log_2024-11-07_00-20-18.txt)
[log_2024-11-07_00-11-51.txt](https://github.com/user-attachments/files/17653712/log_2024-11-07_00-11-51.txt)

**Comment by fcyu** [comment]
> [log_2024-11-03_00-50-38.txt](https://github.com/user-attachments/files/17653274/log_2024-11-03_00-50-38.txt)
> [log_2024-11-03_00-51-20.txt](https://github.com/user-attachments/files/17653275/log_2024-11-03_00-51-20.txt)

The process was interrupted by either the operating system or a human. Could be because of not enough memory

> [log_2024-11-04_08-22-03.txt](https://github.com/user-attachments/files/17653295/log_2024-11-04_08-22-03.txt)

You started the analysis from the middle of the workflow, which skipped MSFragger and all PSM validation steps. It resulted in inconsistent protein mappings (maybe) because your existing results were not analyzed all together before.

> [log_2024-11-07_00-20-18.txt](https://github.com/user-attachments/files/17653709/log_2024-11-07_00-20-18.txt)
> [log_2024-11-07_00-11-51.txt](https://github.com/user-attachments/files/17653712/log_2024-11-07_00-11-51.txt)

Please read the error message carefully. It says `There are corrupted files. Please remove those files and re-start the task.`

The corrupted files can be found from the previous messages, such as

```shell
Unhandled Exception: System.ArgumentOutOfRangeException: Instrument index not available for requested device
Parameter name: instrumentIndex
   at ThermoFisher.CommonCore.RawFileReader.RawFileAccessBase.SelectInstrument(Device instrumentType, Int32 instrumentIndex)
   at DmtAvt.BatmassIo.Thermo.ISourceFactoryImplThermo.SelectDataSource(SelectSourceRequest request)
   at DmtAvt.BatmassIo.Thermo.BatmassIoThermoServer.ParseIndex(String[] args)
   at DmtAvt.BatmassIo.Thermo.BatmassIoThermoServer.Main(String[] args)
Failed in checking E:\PXD042003\Raw_File\FL1158_MSQ1018E_StephanieMenikou_44.raw. Will ignore it.
Could not get ThermoIndex
E:\PXD042003\Raw_File\FL1158_MSQ1018E_StephanieMenikou_44.raw: Scans = 0; ITMS: false; FTMS: false; Isolation sizes = []
```

Best,

Fengchao

**Comment by Dmorgen** [comment]
Thanks!
1. assuming I've the search run already, and it failed in the quantification step. which step should I begin with, if I'd like to try and continue the analysis? 
2. corrupt files - I'm seeing mentions of several files at several points of the analysis. does it check all of the files when that happens? 
Thanks!
David.

**Comment by Dmorgen** [comment]
Thanks!
