### ISSUE TITLE
Open Search

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#186]
I'm trying to use the open search on raw files converted to mzML (RAWs are left too). The closed search ends successfully, however, the open search ends with an error that I report below. I also attach the export Log file. The software is updated to the latest version.
unrecognized extension: raw (the file is in the folder but has not been indicated in the select LC|MS! should I remove all the raw?)
[log_2020-04-14_11-50-37.txt](https://github.com/Nesvilab/FragPipe/files/4474610/log_2020-04-14_11-50-37.txt)

fatal error invalid ms2 counts for run ....

**Comment by fcyu** [comment]
Hi @Angrist75 ,

Your issue seems to be the same as this one (https://github.com/Nesvilab/PTM-Shepherd/issues/1). You may address this issue by moving the raw files to somewhere else to prevent PTM-Shepherd from reading them.

Best,

Fengchao

**Comment by Angrist75** [comment]
ok, I will try and I'll let you Known.
thanks for your suggestion!
all the best
Andrea

**Comment by Angrist75** [comment]
I have just read 
and I found this  (Nesvilab/PTM-Shepherd#1). 
"Once you do that, you should be able to restart your fragpipe process from PTM-Shepherd by unchecking everything else."
Does this mean that if I encountered a process error I can restart the partial process?
can you be kind enough to extend the concept so that I can avoid repeating everything from the beginning every time I make a mistake?
all the best
Andrea

**Comment by fcyu** [comment]
Yes, you can start from the middle by unchecking the tools that have been successfully finished as long as all files are there.

Best,

Fengchao

**Comment by Angrist75** [comment]
ok thanks!
Andrea

**Comment by Angrist75** [comment]
I have successfully finished the open search in order to identify the largest number of PTMs in the different samples (and groups). I am satisfied with the speed with which the software was able to handle a large amount of data. 
I have some questions to maximize the result.
1) Is it possible to view the search result with a viewer? 
2) is it possible to import the data in skyline? This option would be very interesting considering the potential of Skyline visualization both as chromatographic peak extraction and as MS2 library.
3) Which tables and columns should I use in order to do statistics on **a) proteins,** **b) peptides**, **c) peptides with open search ptms**.

thank you very much for your support.
all the best
Andrea

**Comment by fcyu** [comment]
Hi @Angrist75 

1. You can use [PDV](https://github.com/wenbostar/PDV) which supports MSFragger's outputs. The only issue is that for PSMs with open modification (big mass diff), you have to manually put the mass to a certain residue because such a modification is not coded in the sequence.
2. Yes, you can use Skyline. Need the [Skyline-daily](https://skyline.ms/project/home/software/Skyline/daily/register-form/begin.view?).
3. They are a) `protein.tsv`, b) `peptides.tsv`, and c) `psm.tsv` coupled with `<run name>.tsv` (this table contains localized open modifications).

Best,

Fengchao

**Comment by Angrist75** [comment]
is there a reference paper that helps me understand the different voices what they mean?

PeakApex | PeakLower | PeakUpper
(PSMs)
(PSMs/million)
and what columns to use to make statistics?

**Comment by fcyu** [comment]
It's from PTM-Shepherd. The paper is under preparation. 

@danielgeiszler, can you answer this question when you have time?

Thanks,

Fengchao

**Comment by Angrist75** [comment]
**thank you it would be really helpful to have a couple of guidelines on data processing in order to give it biological meaning.**
a general question: are the peptides found with the open search also integrated into the protein file as for example new accessions for peptides-proteins excluded from the closed search but also for intensity or are the results kept separate and need separate considerations?
all the best
andrea

**Comment by fcyu** [comment]
I am not sure if I understand your question correctly. All of the PSMs, peptides, and proteins from one task are included in those tables.

**Comment by Angrist75** [comment]
let me explain better, if on the same samples I do a closed search and an open search the results of the combined protein table is different?

**Comment by fcyu** [comment]
Since the closed search and the open search have to be performed separately, there must be two `combined_protein.tsv` files. These two files are very likely to be different because open search finds more peptides and proteins.

**Comment by danielgeiszler** [comment]
Hello Andrea,

You can find a description of those columns here:

https://github.com/Nesvilab/PTM-Shepherd/wiki/PTM-Shepherd

Mass shifts in open search are subject to instrumental error. The result is a distirbution of mass shifts corresponding to the same modification. The Peak Apex is essentially the most common mass shift we observe for a particular modification.

The number of PSMs are the number of times we identify that mass shift. The number of PSMs/million is the same value but scaled by the number of scans collected.
