### ISSUE TITLE
Description for different workflow

### ISSUE THREAD

**Issue by Yonghao-Holden** [Nesvilab/FragPipe#1861]
Hello Fragpipe development team,

Thank you so much for building this amazing tool and making it so easy to use. I also appreciate the detailed explanation of each workflow (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_workflows.html). I have two quick questions/requests regarding the different workflows that you provided.

1.  It's still a little unclear to me which workflow I should use. For example, I'm still confused about the differences between [Nonspecific-HLA-DIA] and [Nonspecific-HLA-DIA-Astral]. It would be great if there's a table describing the differences between each workflow and what application each workflow is best applicable for. 

2. I have HLA mass spec data generated with DIA and treated with iodoacetamide. May I ask which workflow I should use in this case ([Nonspecific-HLA], [Nonspecific-HLA-C57], [Nonspecific-HLA-DIA], or [Nonspecific-HLA-DIA-Astral])? And if I want to run an open search, which workflow i should use?

Thank you again for the great work! And look forward to your response. 
Holden

**Comment by fcyu** [comment]
Hi Holden,

Is your data from Astral? If yes, use the `Nonspecific-HLA-DIA-Astral`, otherwise, use `Nonspecific-HLA-C57` or `Nonspecific-HLA-DIA` and adjust the variable/fixed modification settings accordingly.

Best,

Fengchao

**Comment by anesvi** [comment]
And if you have Astral and used C*57 treatment, you will need to modify the astral nonspecific DIA workflow: add c+57 as fixed and adjust the mass of cysteinylation on variable mods to 61.98264

**Comment by Yonghao-Holden** [comment]
Thank you so much for your prompt response! 

It's not from Astral, it's from Orbitrap Fusion™ Lumos™ Tribrid™ Mass Spectrometer. If I use `Nonspecific-HLA-C57`, I saw the `diann.run-dia-nn` is set to false, but my data is DIA, should I change this to true? Or maybe it's easier for me to use the `Nonspecific-HLA-DIA` workflow and change the `msfragger.remainder_fragment_masses`, `msfragger.table.fix-mods` and `msfragger.table.var-mods` to ones in the `Nonspecific-HLA-C57` workflow?

Also, if i want to run an open search on this HLA data, should I use the `Open.workflow`? 

Thank you again for your help! I really appreciate it!
Holden

**Comment by fcyu** [comment]
> If I use Nonspecific-HLA-C57, I saw the diann.run-dia-nn is set to false, but my data is DIA, should I change this to true?

Are you using the FragPipe GUI or command line interface? From your description, I suspect that you are using the command line mode. 

I strongly suggest you start with the GUI because I don't think a beginner can get all those settings done correctly by editing the workflow file manually. 

Did you have the Python and EasyPQP installed?

> Or maybe it's easier for me to use the Nonspecific-HLA-DIA workflow and change the msfragger.remainder_fragment_masses, msfragger.table.fix-mods and msfragger.table.var-mods to ones in the Nonspecific-HLA-C57 workflow?

`msfragger.remainder_fragment_masses` is unrelated. But you can change the `msfragger.table.fix-mods` and `msfragger.table.var-mods`. But again, please start with using the FragPipe GUI.

> Also, if i want to run an open search on this HLA data, should I use the Open.workflow?

No. DIA+HLA+open search is not a good idea due to many reasons.

Best,

Fengchao

**Comment by Yonghao-Holden** [comment]
Hello Fengchao,

Thank you for the suggestions! I set up the GUI and am trying to process the DIA, iodoacetamide treated samples. May i ask what's the correct way to process them? Is it correct to use the `Nonspecific-HLA-C57` workflow and then select the datatype as DIA in the table? Or should i select the `Nonspecific-HLA-DIA` workflow and then edit the Modifications in the MSFragger tab?

Thank you so so much for your help!! I greatly appreciate it!
Holden

**Comment by fcyu** [comment]
select the Nonspecific-HLA-DIA workflow and then edit the Modifications in the MSFragger tab

Best,

Fengchao

**Comment by Yonghao-Holden** [comment]
OK!! Thank you for your fast response! Just wanted to make sure, should I edit the Modification according the setting in the Nonspecific-HLA-C57 workflow?
