### ISSUE TITLE
PTMShepherd "Exception in thread"

### ISSUE THREAD

**Issue by OLWatUNSW** [Nesvilab/FragPipe#1863]
Hello,

I am repeatedly running into this error on FragPipe. PTMShepherd will return exit code 1, stopping the other tasks in the workflow. Appears to be caused by the exception thrown up when the array is 0 peaks? I don't know how to work around this/ if this is intended behaviour. When same files are used in "Deafult" workflow, workflow works as expected.

Cheers.

"Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at edu.umich.andykong.ptmshepherd.core.FastLocator.getIndex(FastLocator.java:90)
	at edu.umich.andykong.ptmshepherd.peakpicker.PeakAnnotator.getDeltaMassMappings(PeakAnnotator.java:361)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:536)
Annotated summary table

Mapping modifications back into PSM lists

Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping"

[log_2024-11-08_14-16-51.zip](https://github.com/user-attachments/files/17672146/log_2024-11-08_14-16-51.zip)

**Comment by fcyu** [comment]
You are using the glycan related workflow but there may be no glycopeptides in your sample.

Best,

Fengchao

**Comment by OLWatUNSW** [comment]
Hi Fengchao,

I thought this may be the case but trying with two of the raw files that I know have some glycopeptides in them. When viewed, it is clear that FragPipe has "picked them up" .

![image](https://github.com/user-attachments/assets/3be8c28a-e1d9-47b9-874d-2454837d18fc)


Thanks.

**Comment by dpolasky** [comment]
> 	Picked top 13 peaks
	Removed 13 peaks with insufficient PSMs

It looks like all the delta mass peaks were removed due to insufficient PSMs per peak, causing the crash. Can you try reducing the "Peak minimum PSMs" setting in the PTM Profiling box on the PTMs tab from 10 to 1?

Best,
Dan
