### ISSUE TITLE
No combined_proteins.tsv output file

### ISSUE THREAD

**Issue by larsonlarsoff** [Nesvilab/FragPipe#1864]
Hi there how are y'all doing?

I'm tying to perform using LFQ-analyst but I am not getting a combinedproteins.tsv output file. I am using the LFQ-MBR workflow with MBR off and FDR rate --prot threshold of 2%. Does IonQuant rename the output file to something different?

I have attached a log file here:

Secondly, when trying to use default settings of the LFQ-MBR workflow. I am faced with this error. 

![image](https://github.com/user-attachments/assets/e0a311ec-3e8c-4ba3-bb51-838c2e6d5f24)

**Comment by fcyu** [comment]
Did you assigned the experiment and the bioreplicates in the workflow tab?

Best,

Fengchao

**Comment by larsonlarsoff** [comment]
Hi Fengchao, 

Sorry I believe I sent my message early before I filled it out completely.

Yes I did. My controls I didn't assign biological replicates since they are just technical.
Below is an image and log:

![image](https://github.com/user-attachments/assets/0b4ac864-ee12-4abc-9744-73fbfeb7075a)

[log_2024-11-08_12-51-21.txt](https://github.com/user-attachments/files/17683224/log_2024-11-08_12-51-21.txt)

Thanks
Larsen

**Comment by fcyu** [comment]
Hi Larsen,

You enabled the spec lib gen by accident. Please disable it.

Best,

Fengchao

**Comment by larsonlarsoff** [comment]
Fengchao,

I re-did the run and it worked.
Thank you, this fixed both of my issues!

Have a great day,
Larsen
