### ISSUE TITLE
plexDIA

### ISSUE THREAD

**Issue by li20041** [Nesvilab/FragPipe#1865]
Hi,

Thank you for developing such an amazing software. 

For plexDIA analysis, should I set the parameters in the MSFragger panel or the Quant (DIA) panel?

I know that DIA-NN supports plexDIA.
Is the plexDIA function simply integrated from DIA-NN into Fragpipe, or does MSFragger-DIA have its own plexDIA feature?

 Also, is there a specific tutorial available for plexDIA?

**Comment by fcyu** [comment]
> should I set the parameters in the MSFragger panel or the Quant (DIA) panel?

You should set labels as var mod in MSFragger, and also configure the `plex DIA` panel in the `Quant (DIA)` tab.

> Is the plexDIA function simply integrated from DIA-NN into Fragpipe, or does MSFragger-DIA have its own plexDIA feature?

The peptide identification is performed by MSFragger and the quant is performed by DIA-NN.

> Also, is there a specific tutorial available for plexDIA?

No, will add in future.

Best,

Fengchao
