### ISSUE TITLE
DIA_SpecLibQuant workflow crashing

### ISSUE THREAD

**Issue by tomvaiuw** [Nesvilab/FragPipe#1868]
Running a search on DIA data from Astral acquired with 3 mz window keeps crashing when gets to Spectral Library building.
For details see the log file.
Thanks for any suggestions as to what I may be doing wrong.

Tomas

[log_2024-11-12_10-40-18.txt](https://github.com/user-attachments/files/17721391/log_2024-11-12_10-40-18.txt)

**Comment by guoci** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/1836, please follow intructions from https://github.com/Nesvilab/FragPipe/issues/1836#issuecomment-2430217130 to resolve.

**Comment by tomvaiuw** [comment]
Thanks. Works now.
Tomas
