### ISSUE TITLE
100% FDR not possible?

### ISSUE THREAD

**Issue by 07liesin** [Nesvilab/FragPipe#1869]
[log_2024-11-13_15-31-00.zip](https://github.com/user-attachments/files/17735499/log_2024-11-13_15-31-00.zip)

I am trying to get reports from fragpipe containing all IDs equivalent to 100% FDR rate and filter them afterwards.
But the log file tells me that e.g.:

time="15:16:32" level=info msg="Database search results" ions=7467 peptides=6950 psms=23378
time="15:16:32" level=info msg="Converged to 7.71 % FDR with 21704 PSMs" decoy=1674 threshold=0.500004 total=23378
time="15:16:32" level=info msg="Converged to 27.64 % FDR with 5445 Peptides" decoy=1505 threshold=0.500004 total=6950
time="15:16:32" level=info msg="Converged to 25.45 % FDR with 5952 Ions" decoy=1515 threshold=0.500004 total=7467
time="15:16:32" level=info msg="Protein inference results" decoy=10191 target=19576
time="15:16:32" level=info msg="Converged to 71.73 % FDR with 14165 Proteins" decoy=10161 threshold=0.4995 total=24326
time="15:16:32" level=info msg="Applying sequential FDR estimation" ions=7467 peptides=6950 psms=23378
time="15:16:32" level=info msg="Converged to 7.71 % FDR with 21704 PSMs" decoy=1674 threshold=0.500004 total=23378
time="15:16:32" level=info msg="Converged to 27.64 % FDR with 5445 Peptides" decoy=1505 threshold=0.500004 total=6950
time="15:16:32" level=info msg="Converged to 25.45 % FDR with 5952 Ions" decoy=1515 threshold=0.500004 total=7467
time="15:16:32" level=info msg="Post processing identifications"
time="15:16:32" level=info msg="Assigning protein identifications to layers"
time="15:16:40" level=info msg="Processing protein inference"
time="15:16:45" level=info msg="Synchronizing PSMs and proteins"
time="15:16:45" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=5951 peptides=5444 proteins=3543 psms=21703

So it never seems to reach the 100% with my settings, especially for the proteins:
filter --sequential --prot 1 --ion 1 --pep 1 --psm 1

Additionally I set (as the above settings did not help) the MBR ion FDR to 1 and the percolator test and trainFDR to 1.

Do the reported values maybe originate from a different filter setting (post-processing) and FDR is set as high as possible? Or is the percolator a problem?

Any suggestion how I can get the right reports?
Thanks!

**Comment by 07liesin** [comment]
But as far as I know the filtering of the IDs happens at the Philosopher step using Percolators input. But it seems that this is not properly working. Also switching from Percolator to Peptide prophet did not help. 

Any more suggestions?

**Comment by fcyu** [comment]
I apologize if the previous reply is not clear. There are min prob thresholds in the Percolator. Please change it to 0 if you want 100% FDR.

![image](https://github.com/user-attachments/assets/3057037e-9347-49d0-8547-ea38c5ee23af)

Best,

Fengchao

**Comment by shubham1637** [comment]
@fcyu When I look at log file, I see qvalue threshold being 0.01, is there any flag to change that in percolator? in Cmd line opts?
```
Found 2423 test set PSMs with q<0.01.			
Selected best-scoring PSM per file+scan+expMass (target-decoy competition): 10829 target PSMs and 7662 decoy PSMs.			
Calculating q values.			
Final list yields 2439 target PSMs with q<0.01.			
Calculating posterior error probabilities (PEPs).			
Processing took 2.9470 cpu seconds or 3 seconds wall clock time.			
Process 'Percolator' finished, exit code: 0			
```

**Comment by fcyu** [comment]
That line is used by Percolator internally and won't affect the result.

Best,

Fengchao
