### ISSUE TITLE
open search

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#187]
connected to
https://github.com/Nesvilab/FragPipe/issues/186

I have successfully finished the open search in order to identify the largest number of PTMs in the different samples (and groups). I am satisfied with the speed with which the software was able to handle a large amount of data.
I have some questions to maximize the result.

Is it possible to view the search result with a viewer?
is it possible to import the data in skyline? This option would be very interesting considering the potential of Skyline visualization both as chromatographic peak extraction and as MS2 library.
Which tables and columns should I use in order to do statistics on a) proteins, b) peptides, c) peptides with open search ptms.
thank you very much for your support.
all the best
Andrea

**Comment by fcyu** [comment]
Answered here https://github.com/Nesvilab/FragPipe/issues/186#issuecomment-614044956
