### ISSUE TITLE
Issue with TMT-Integrator for TMTzero with Philosopher

### ISSUE THREAD

**Issue by FehrAaron** [Nesvilab/FragPipe#1870]
Hi, 

I am encountering an issue when analyzing my TMT-zero data. I loaded the TMT-10plex standard workflow and changed the modifications in the MS-Fragger tab to 224.1.. for the TMTzero tag. I selected TMT-0 as label and ran the analysis. If I use IonQuant for the intensity extraction, everything works fine. But if I use Philosopher, the error message: 

TMT-Integrator v5.0.9
Load parameters and check PSMs--- 0.00687 min.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 37 out of bounds for length 37
	at tmtintegrator.TMTIntegrator.UpdateColumns(TMTIntegrator.java:636)
	at tmtintegrator.TMTIntegrator.main(TMTIntegrator.java:62)
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 1 remaining tasks

appears. 

Here is the corresponding log-file: [log_2024-11-13_18-23-53.zip](https://github.com/user-attachments/files/17736733/log_2024-11-13_18-23-53.zip)

Thanks in advance!

**Comment by fcyu** [comment]
Philosopher doesn't support TMTzero. Please use IonQuant for the intensity extraction.

Best,

Fengchao

**Comment by FehrAaron** [comment]
Thanks a lot for the swift response!

**Comment by FehrAaron** [comment]
Hello Fengchao,

a follow-up issue arose. For some reason, TMT integrator is not able to quantify the reporter ion for most precursors. While MS-Fragger was able to identify over 13000 peptides (on which all lysines and most n-termini were labelled), only around 130 TMT intensities were reported. Removing the filters on minimum intensity and purity did not improve my results. Also, I tested a range of different collision energies and the reporter is clearly visible at high intensities (often at 50-100% of the MS2-intensity). The issue of getting a much lower number of reference intensities compared to peptide ids also persisted when analyzing TMTzero data from Zecha et al. (PXD012703, log attached, 41 ratios while 9676 mod. peptides were identified).

Do you maybe have an idea what could be the reason for my issues?


[log_2024-11-12_12-04-11.zip](https://github.com/user-attachments/files/17803340/log_2024-11-12_12-04-11.zip)

**Comment by fcyu** [comment]
In your log file, the TMT-Integrator crashed because you still use Philosopher but not IonQuant as intensity extractor.

Best,

Fengchao

**Comment by FehrAaron** [comment]
Hi Fengchao,

sorry, I accidentially sent you the old log. Here is the correct one:

[log_2024-11-12_13-57-11.zip](https://github.com/user-attachments/files/17805963/log_2024-11-12_13-57-11.zip)

Thanks for the quick support!

**Comment by fcyu** [comment]
No worries. 

Since you are using neither TMT-10/11 or TMT-16, could you check `allow unlabeled` in the `Quant (Isobaric)` tab?

![image](https://github.com/user-attachments/assets/5a1af0ea-82bb-4c49-90d2-2e1e9a659b76)

Thanks,

Fengchao
