### ISSUE TITLE
Speed up DIA analysis

### ISSUE THREAD

**Issue by Li5459000** [Nesvilab/FragPipe#1871]
Hi,

Thank you for developing this platform and for your support of the community.

How can I speed up DIA analysis without compromising performance?

In DIA-NN or MaxQuant, it's possible to adjust the "threads" setting to optimize processing speed. Can this also be done in FragPipe?

Also, does the current version support DIA-NN 1.9.2, and what's the latest version of DIA-NN that is supported?

**Comment by anesvi** [comment]
Yes you need to set the number of threads in in the workflow tab. As far as speeding up more, it depends on what workflow you are running. Some parameters in MSFragger can be adjusted to speed it up. But we need to know more ( see the log) to suggest what to change.
