### ISSUE TITLE
EasyPQP couldn't import PyOpenMS package

### ISSUE THREAD

**Issue by JM-Bader** [Nesvilab/FragPipe#1872]
[log_2024-11-14_11-26-09.txt](https://github.com/user-attachments/files/17748404/log_2024-11-14_11-26-09.txt)

I am trying to run DIA-NN through FragPipe on Astral DIA raw files with the DIA_SpecLib_Quant workflow. I have used Proteowizard to create 32bit mzml files with vendor peak picking for centroiding. 

However, I get the following error message (see log): 

ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.

======================================================================
Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on 

C:\Users\maxquant\anaconda3\Lib\site-packages\pyopenms\pyopenms*.so

======================================================================
PyQt5 was found to be installed. When building pyopenms qmake said:

    QMake version 3.1
    Using Qt version 5.12.6 in D:/a/OpenMS/Qt/5.12.6/msvc2017_64/lib
PYQT has version 5.15.7

This might cause a conflict if both are loaded.  You can test this by importing pyopenms
first and then import PyQt5.QtCore.
        
Note: when using the Spyder IDE, the usage of PyQt might be circumvented
by not using the 'Automatic' backend. Please change this in Tools ->
Preferences -> IPython -> Graphics to 'Inline'.
In general, try to install everything with conda in the same environment to make sure Qt is used in the same version.

======================================================================

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/1836, please follow intructions from https://github.com/Nesvilab/FragPipe/issues/1836#issuecomment-2430217130 to resolve.

Best,

Fengchao
