### ISSUE TITLE
DIA-NN error: Could not read Thermo RAW file

### ISSUE THREAD

**Issue by cdw0101** [Nesvilab/FragPipe#1873]
**- Upload your log file**
[log_2024-11-14_15-32-24.txt](https://github.com/user-attachments/files/17750176/log_2024-11-14_15-32-24.txt)

**- Describe the issue or question:**
I keep getting the error that is described. #561 
I have installed Thermo MS File Reader and confirmed that the raw files can be read through Thermo freestyle software.

However, I kept getting this error that Could not read Thermo RAW file. The Thermo .dll likely was not loaded or out of date.
Instrument: Thermo exploris 480.
File: Thermo .raw DIA file

Thank you in advance. Best,

**Comment by fcyu** [comment]
> I have installed Thermo MS File Reader and confirmed that the raw files can be read through Thermo freestyle software.

Did you install the correct version mentioned in https://github.com/vdemichev/DiaNN#raw-data-formats?

Please convert the raw files to mzML format according to the tutorial https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by cdw0101** [comment]
Dear Fengchao,

Thank you for your quick reply.
It finally worked after converting the raw files to mzML.
Thank you so much for the solution.

By the way, I forgot to mention that the DIA data are two split compensation voltage (45v, 65v) files with non-staggered windows. 

Best,

Dan
