### ISSUE TITLE
PDV viewer vs TSV file

### ISSUE THREAD

**Issue by tjiangUNM** [Nesvilab/FragPipe#1875]
**- Upload your log file**
[log_2024-11-12_09-46-50.txt](https://github.com/user-attachments/files/17756203/log_2024-11-12_09-46-50.txt)

**- Describe the issue or question:**
Hi,

I was trying to check unnatural amino acid incorporation, and found the information of modified peptides to be different in PDV viewer and the "peptide" TSV file.

For example, in TSV I can see a peptide with desired modification on F underlined in the screenshot below
![image](https://github.com/user-attachments/assets/508ce65e-cf3a-49c7-bcf3-77e0ea9a8fa0)
but not in the PDV viewer
![image](https://github.com/user-attachments/assets/c3fe203f-490b-4481-ba95-f2447d303ba4)

Another question is the number on the modified amino acid, for example, in the 2nd screenshot, why is it 147 rather than 16 on M for M oxidation?

Thanks!
T

**Comment by KaiLiCn** [comment]
Hi T,

The PSM information in PDV is based on "psm.tsv" file. Please refer "psm.tsv" file as the reference if you want to check the original result. In "peptide.tsv" file, the result is shown on the peptide level, which means the "Assigned Modifications" column shows all modifications that occurred on this peptide. And they might be from different spectrum matches.

The number of modified amino acids is also read from "psm.tsv" file.  It's equal to the mono mass of amino acid plus modification mass.

Kai

**Comment by tjiangUNM** [comment]
Got it. Thank you for your prompt response and helpful information!
