### ISSUE TITLE
Numeric ordering of column in quantitative tables

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1877]
Hi,

When we assign numbers in the Experiment column of the manifest, 1, 2, 3 ...10,11,12,...20,21,22...., the order that the samples appear in a quant table will be 1, 10, 11....2, 20, 21...etc. Is there a way to maintain strict numerical order in the reports?

Thanks,

Matt

**Comment by fcyu** [comment]
Ah, it is in lexicographical order. Set it to 01, 02, 03, .... 10, 11, 12.... should work. If the largest number has three digits, use 001, 002....

Best,

Fengchao

**Comment by mwfoster** [comment]
Makes sense, thanks. Matt
