### ISSUE TITLE
Dimethy labeling 

### ISSUE THREAD

**Issue by poorichaya** [Nesvilab/FragPipe#1878]
**- Describe the feature:**
Dear Sir

I just wonder if i did dimethyl labeling ( Light and Medium)

I set up in Quant (MS1) as below
Light  = Kn28.013
Medium = Kn32.056
it work very wells

I look at in combine protein as excle file. It show the head coloum. It show light and medium intensity value or LFQ intensity

but the desciptive of column in the experiment annotation file is differenct from the desciptive of column in combine protein.
It show below:
file	sample	sample_name	condition	replicate
D:\GC1FLT_F1.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F2.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F3.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F4.raw	Exp1_1	Exp1_1	Exp1	1
D:GC1FLT_F5.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F6.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F7.raw	Exp1_1	Exp1_1	Exp1	1
D:\GC1FLT_F8.raw	Exp1_1	Exp1_1	Exp1	1

 
I cannot do Fragpipe-analyst 
it show Error: The column 'Description' is not found in the FragPipe combined_protein.tsv

Please advice me how to set up dimethyl labeling in frgapipe?

**Comment by fcyu** [comment]
Does FragPipe-Analyst support isotopic labelled data? @hsiaoyi0504 

Best,

Fengchao

**Comment by poorichaya** [comment]
please answer

**Comment by hsiaoyi0504** [comment]
No one really tested it and we don’t officially support that. If it’s combined protein then there is a chance to use, but you need to make sure
(1) sample and sample_name are unique
(2) sample is matched columns in combined protein file in a one to one manner
