### ISSUE TITLE
Process 'CheckCentroid' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by talithar-star** [Nesvilab/FragPipe#1880]
**- Upload your log file**

[log_2024-11-18_12-07-32.txt](https://github.com/user-attachments/files/17805768/log_2024-11-18_12-07-32.txt)

**- Describe the issue or question:**

MS Fragger is no longer running file. Error message is: Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Please re convert your data to **mzML** format and try again.

Best,

Fengchao
