### ISSUE TITLE
desthiobiotin modification of lysine

### ISSUE THREAD

**Issue by maohuanyang** [Nesvilab/FragPipe#1882]
I did an open search using Fragpipe version22 (MSFragger 4.1) and I got a modification with molecule 196.12, which showed desthiobiotin modification of lysine. I wonder how this entry came to be and is there any literature to support it?

I appreciate your help here.
<img width="568" alt="微信图片_20241119122450" src="https://github.com/user-attachments/assets/8d750434-e888-4b7d-90bd-186b024a74fa">

**Comment by fcyu** [comment]
The information in that column is from UniMod: https://www.unimod.org/modifications_view.php?editid1=1031

Best,

Fengchao

**Comment by maohuanyang** [comment]
Thank you very much
