### ISSUE TITLE
format for MSFraggerDIA

### ISSUE THREAD

**Issue by wangss3** [Nesvilab/FragPipe#1884]
Hi,

I don't quite understand the format issue with the DIA data.

Does MSFragger-DIA currently support the diaPASEF format, must convert to mzml?
For astral files, is it recommended to use the Thermo raw format, or converted to mzml?

Thank you so much in advance

**Comment by fcyu** [comment]
> Does MSFragger-DIA currently support the diaPASEF format, must convert to mzml?

For diaPASEF, we have a new tool, diaTracer, and please use the `DIA_SpecLib_Quant_diaPASEF` workflow.

> For astral files, is it recommended to use the Thermo raw format, or converted to mzml?

mzML format is preferred.

Best,

Fengchao

**Comment by wangss3** [comment]
Thank you!
