### ISSUE TITLE
plexDIA - Propagate information error

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1885]
Hi Fengchao and team,

I have some dia-PASEF runs where I did dimethyl labeling for 3 channels. I am now trying to use fragpipe for the quantification. I have put the masses of the labels in the MSFragger section at K (3 max occurrences) and n^ (1 max occurrence). I then put the masses in for the plexDIA section of the Quant (DIA) tab.

I notice that there is an error after DIA-NN seems to finish...
`
Process 'DIA-NN' finished, exit code: 0
DIA-NN [Work dir: D:\SharedspaceTIMSTOF\Giulia\Plate485\4-fragpipe-plexdia]
D:\FragPipe-jre-21.1\fragpipe\tools\diann\1.8.2_beta_8\win\dia-nn-plotter.exe diann-output\report.stats.tsv diann-output\report.tsv diann-output\report.pdf
Generating report. Stats, main report, output file: diann-output\report.stats.tsv, diann-output\report.tsv, diann-output\report.pdf
Process 'DIA-NN' finished, exit code: 0
DIA-NN: Propagate information [Work dir: D:\SharedspaceTIMSTOF\Giulia\Plate485\4-fragpipe-plexdia\diann-output]
D:\fragpipe-jre-22.0\jre\bin\java.exe -cp D:\fragpipe-jre-22.0\tools\batmass-io-1.33.4.jar;D:\fragpipe-jre-22.0\lib\fragpipe-22.0.jar;D:\fragpipe-jre-22.0\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.Propagation D:\SharedspaceTIMSTOF\Giulia\Plate485\4-fragpipe-plexdia
java.lang.NumberFormatException: For input string: "label-K-L"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source)
	at java.base/java.lang.Float.parseFloat(Unknown Source)
	at com.dmtavt.fragpipe.util.UnimodOboReader$Precursor.getModMass(UnimodOboReader.java:221)
	at com.dmtavt.fragpipe.util.UnimodOboReader$Precursor.<init>(UnimodOboReader.java:208)
	at com.dmtavt.fragpipe.tools.diann.Propagation.editReport(Propagation.java:262)
	at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:190)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping
`

I want to make sure that I am running this correctly and what this error means.

Log: [log_2024-11-19_10-34-38.txt](https://github.com/user-attachments/files/17817648/log_2024-11-19_10-34-38.txt)

Thanks,
Ronnie

**Comment by fcyu** [comment]
Hi Ronnie,

This is a known bug but won't affect the results. Just some additional columns are missing.

Best,

Fengchao
