### ISSUE TITLE
MSFragger for Histone PTMs?

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#1889]
Hi MSFragger Team,  
We are currently processing Histone PTM samples using bottom-up proteomics and would like guidance on optimizing the search settings for successful results. Our workflow involves:  Histone extraction, Lysine derivatization, Enzymatic digestion with trypsin, and Data collection in DDA mode.  
Are there specific settings or recommendations in MSFragger that you suggest for such analyses? Any advice would be greatly appreciated.  
Thank you for your continued support.

**Comment by fcyu** [comment]
First of all, please use FragPipe together with MSFragger and other downstream tools (that's why I transferred it to the FragPipe repository). 

Second, may I ask if you have a list of PTMs that you want to search? Or do you want to perform the open search to detect any unknown PTMs?

Thanks,

Fengchao

**Comment by fazeliniah** [comment]
I am definitely using MSFragger through FragPipe. Apologies if my original message was unclear.  
Open search is an excellent suggestion, and I will definitely give that a try. 
The list of modifications includes some common ones, such as acetylation, methylation, phosphorylation, and ubiquitylation. In addition, we are interested in exploring less well-studied modifications, such as sumoylation and biotinylation.  
Thank you for your help and prompt reply.

**Comment by fcyu** [comment]
Then, I would starts with closed search using the "Default" workflow (if the number of PTMs is less than, say, 16) or mass-offset search using the "Mass-Offset-CommonPTMs" workflow (if there are many PTMs to search).

For the "Mass-Offset-CommonPTMs" workflow, you need to edit the mass-offset list in the MSFragger tab with the PTMs you are interested in.

Best,

Fengchao

**Comment by anesvi** [comment]
We hosted a student in the lab earlier this year for two months who worked to develop a workflow in FragPipe specifically for histone PTM data. If you email me, I can connect you with him, but I am not sure where he is with his manuscript describing the analysis. But perhaps he can share the workflow. Best, Alexey
