### ISSUE TITLE
Hyperplexing setup

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1890]
Hello Fengchao and team,

I have performed a sample prep which uses both isotopic and isobaric labeling to essentially multiply the multiplexing capabilities. Specifically, for isotopic labeling I have 3 channels using the dimethyl strategy, and for isobaric labeling I have 16 channels using the TMT pro labeling strategy. The dimethyl is just labeling the peptide N-termini, while the TMT is labeling the lysines. In total total there are 48 channels.

What I am doing now is setting the N-termini fixed mod to 1/3 of the dimethyl channels and the K fixed mod to the TMT mass. With this I have to run 3 separate analyses. So I have some questions about this:

1. Is it possible to include all the dimethyl channels to be simultaneously analyzed at once?
2. Should the mods for dimethyl and TMT be fixed or variable? I see that in the TMT-16 workflow the peptide N-termini mod is variable while the K mod is fixed, why is this?

Here's the protocol in case you are interested:
https://pmc.ncbi.nlm.nih.gov/articles/PMC9153850/#S2

Best,
Ronnie

**Comment by fcyu** [comment]
> Is it possible to include all the dimethyl channels to be simultaneously analyzed at once?

Identification yes. Quantification, no.


> Should the mods for dimethyl and TMT be fixed or variable? I see that in the TMT-16 workflow the peptide N-termini mod is variable while the K mod is fixed, why is this?

You should set both dimethyl and TMT to variable modification on both peptide N-term and K.

Best,

Fengchao

**Comment by cutleraging** [comment]
Hi Fengchao,

Thanks for that!

Can you explain to me the reasoning behind using fixed vs variable mods here? Is it because if you use variable mods you are able to recover more peptides that might be partially modified? In the paper I linked, the searches were done using fixed modifications for the N-termini dimethyl and lysine TMT.

Ronnie

**Comment by fcyu** [comment]
Hi Ronnie,

The key point is that whether dimethyl and TMT can be on the peptide N-terminal at the same time.

In the paper you posted, it seems that they searched the light and heavy dimethyl separately, and didn't specify the peptide N-terminal TMT:

> Static modifications: light demethylation (+28.031, peptide N-terminus) or heavy demethylation (+36.076 Da, peptide N-terminus), carbamidomethyl (+57.021 Da, C), Dynamic modifications: oxidation (+15.995 Da, M), 11-plex isobaric tag (229.163 Da, K), 1% FDR, reporter ion quantification with 30 ppm peak integration tolerance, most confident centroid for integration method.

Thus, it looks like the dimethyl and TMT can't happen together and dimethyl is labelled first, so there it no peptide N-terminal TMT.

If you want to search the light and heavy dimethyl together, you have to set both light and heavy as variable modifications, or set the light one as a fixed modification and set the mass difference as a variable modification.

Best,

Fengchao

**Comment by cutleraging** [comment]
HI Fengchao,

Okay this makes more sense. But I am still wondering for this type of search why the TMT is set to a variable modification and not just a fixed? Wouldn't you only want to quantify the peptides which have both the dimethyl and the TMT? What's the point of getting the peptides which may only have the dimethyl?

I know that if I am setting variable modifications that this will increase the search space as opposed to setting fixed modifications. So what I am really asking is what is the tradeoff here, especially in the context of analyzing labeled data for multiplexing?

Also, how does one determine the setting for the amount of allowed modifications? When the modification is on the N-termini, it makes sense to use 1, but other wise how do you set it? The higher it is the larger the search space?

Thanks,
Ronnie

**Comment by fcyu** [comment]
Hi Ronnie,

If there are many peptides in the sample that have dimethyl but not TMT, and you set TMT as fixed modification, those peptides will become false or decoy matches, which harm the sensitivity after FDR cut-off.

> Also, how does one determine the setting for the amount of allowed modifications? When the modification is on the N-termini, it makes sense to use 1, but other wise how do you set it? The higher it is the larger the search space?

The number is mostly empirical. Most tools normally set 3 as default for the modifications on amino acids.

Best,

Fengchao

**Comment by cutleraging** [comment]
HI Fengchao,

Okay thanks for that it makes sense. One last question, if you may. Why is it in the TMT workflow that the N-termini mod is variable while the K mod is fixed? Wouldn't this create the same issue as you just mentioned above? Why not have them both be variable?

Best,
Ronnie
