### ISSUE TITLE
Threads and midification

### ISSUE THREAD

**Issue by Li5459000** [Nesvilab/FragPipe#1893]
Hi,

I want to compare the analysis speed between DIA-NN and MSFragger-DIA.

For DIA-NN, I set the threads to 16. For MSFragger-DIA, how should I configure the settings?

In the global settings, I noticed options for RAM and parallelism, but I’m not sure how to configure them to match the 16 threads used in DIA-NN.

Also, how should I configure the Methionine excision (N-term)? Should I set it to [^ -131.0405?

**Comment by fcyu** [comment]
Set `parallelism` to 16.

> Also, how should I configure the Methionine excision (N-term)? Should I set it to [^ -131.0405?

Peptide N-term or protein N-term? For peptide N-term `n^ -131.0405`, for protein N-term `[^ -131.0405`.

Best,

Fengchao

**Comment by anesvi** [comment]
If they asked about protein N-terminal M removal, we already have that box checked by default. No extra changes are needed.

**Comment by Li5459000** [comment]
Thank you!
