### ISSUE TITLE
java.io.IOException: There is not enough space on the disk

### ISSUE THREAD

**Issue by IliyanaKan** [Nesvilab/FragPipe#1897]
Hi

I am trying to run an immunopeptidomics search on Fragpipe v22.0 and after a few seconds I'm getting the error "java.io.IOException: There is not enough space on the disk". I have 17.9 TB space on the disc where the data is stored and 82.2 GB of space on the C drive where the Fragpipe folder is located. Could you please help me figure this problem out?
 
[log_2024-11-25_17-12-58.txt](https://github.com/user-attachments/files/17906802/log_2024-11-25_17-12-58.txt)7

Many thanks
Iliyana

**Comment by IliyanaKan** [comment]
The F drive is 18.1 TB but only 4MB are free.

**Comment by fcyu** [comment]
> but only 4MB are free.

That is the reason.

Best,

Fengchao

**Comment by IliyanaKan** [comment]
Thank you very much, it's working now. 👍
