### ISSUE TITLE
Percolator: Convert to pepxml: cannot find output_report_top_N parameter

### ISSUE THREAD

**Issue by bingnanzhao** [Nesvilab/FragPipe#1898]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-11-25_11-59-35.txt](https://github.com/user-attachments/files/17908376/log_2024-11-25_11-59-35.txt)

**- Describe the issue or question:**
Hi dear Fragpipe team, I was trying to apply some sort of criteria to filter for PSMs both in .pin file and .pepxml files. If I only modify .pin file, then downstream process went smoothly. But after I modified pin file and pepxml files together, it says in the modified pepxml file the output_report_top_N parameter is not found. However, I checked and it does exist. I wonder if you could help me figure out if the format is wrong or not. And if you are ok I would like to share the modified .pepxml file to you somewhere else because it's not allowed here.

Thanks,
Bingnan

**Comment by fcyu** [comment]
Hi Bingnan,

If you just want to add a few scores for the Percolator to rescore, you don't need to edit the pepXML file. Without more detailed information about what you have changed or the edited pepXML file, I am afraid I can't tell the reason of the error.

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Hi Fengchao,

I've modified my code to output the truncated .pepXML file without additional space before /> and it passed the original error, wonderful! However it got stuck at PhilosophorFilter. The log file is provided below:

[log_2024-11-26_08-53-36.txt](https://github.com/user-attachments/files/17923143/log_2024-11-26_08-53-36.txt)

The truncated .pepXML rank1 and the combined.prot.xml are here:
https://drive.google.com/file/d/1nXWFLau-PsZOnR-FARK-SNe-ecUI4Q9Y/view?usp=sharing
https://drive.google.com/file/d/1B2OYavFssMV5yp7Tc3YK7opYYGwQUgip/view?usp=sharing

I noticed the attributes' order in <msms_pipeline_analysis> has been changed in modified pepxml, I changed it as its original version but that did not help. 

Thanks for your patience again and I hope it is fixable.

Thanks,
Bingnan

**Comment by fcyu** [comment]
Hi Bingnan,

I guess the edited pepXML file broke Philosopher. I don't know how Philosopher parse the pepXML file, but I guess you have to diff the unedited and edited pepXML file to locate the issue.

I am not sure why you need to edit the pepXML file, but I couldn't figure out a common case requiring that, especially you are not adding new scoring to the pin file (which also doesn't require editing the pepXML file).

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Thanks for your suggestions Fengchao. I will email you once I finished diffing them. Have a good thanksgiving!

Best,
Bingnan
