### ISSUE TITLE
Label 131 does not have annotation: TMT10 with valid annotations.txt

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#1899]
Despite several attempts on the format of the annotations.txt, I'm still getting the same error message complaining about the annotation for channel 131. Perhaps I'm missing something obvious!

As a feature request, it'd really helpful to pre-valid the input parameters such as "annotations.txt" prior to the start the long search. Otherwise we'd have to wait for a day or longer for the error message.

Thanks again for the wonderful works you've done!

Wen 

[annotation.txt](https://github.com/user-attachments/files/17923963/annotation.txt)
[log_2024-11-26_12-57-27.txt](https://github.com/user-attachments/files/17923986/log_2024-11-26_12-57-27.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
![Screenshot 2024-11-26 at 1 00 50 PM](https://github.com/user-attachments/assets/9d8b626a-1379-426c-a816-931f5d5604a6)

**Comment by fcyu** [comment]
The channel name should be unique among all samples/plexes, but you have `pool` and `poool` in each of the sample/plex.

Best,

Fengchao

**Comment by fcyu** [comment]
Since your reference channel name is 'pool', you could set the reference channels to 'pool1', 'pool2', ..., for each plex.

`poool` is not used as a reference channel. You could rename them to different names.

Best,

Fengchao

**Comment by wyu** [comment]
[log_2024-11-26_22-34-25.txt](https://github.com/user-attachments/files/17928492/log_2024-11-26_22-34-25.txt)
[annotation.txt](https://github.com/user-attachments/files/17928495/annotation.txt)
 Hi, I made the changes to the annotation.txt as suggested and re-run the search (without the MsFragger the validation steps). The same error happened again. The last two digits of the pool channels correspond to the plate and instrument so they should be unique across all the plates.
 
Thanks!
Wen

 126 pool_1_1
127N GTEX-12WSD-0526-SM-9KNJH
127C GTEX-11DXX-1226-SM-9KI3K
128N GTEX-12WSD-1326-SM-9KMWZ
128C GTEX-13D11-0226-SM-9KI5R
129N GTEX-1211K-0226-SM-9KMWV
129C GTEX-YEC4-1426-SM-9KI3B
130N GTEX-12WSD-1426-SM-9KMX4
130C GTEX-12WSD-2626-SM-9KMX7
131 poool_1_1

**Comment by fcyu** [comment]
I just checked the first two channel name and  found that there are two `GTEX-12WSD-0526-SM-9KNJH`. Please double check and correct all names.

Best,

Fengchao
