### ISSUE TITLE
Settings influencing IonQuant intensity values 

### ISSUE THREAD

**Issue by eldenrowland** [Nesvilab/FragPipe#1900]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Hi Fragpipe team, 

I'm looking for some clarification on Ionquant settings.  

Specifically I would like to know how the retention time tolerance, rttol=0.4 min(default) influences peak picking. I am analyzing a long 3 hr run where the peaks widths are sometimes 1 min. Therefore, I adjusted the rttol to 1 min. Adjusting this setting quite drastically changes the intensity values. Am I thinking about this correctly? 

I have read the ionquant paper but still wasn't sure about this particular setting. 

All the best,

Elden Rowland

**Comment by fcyu** [comment]
It controls the max distance between an identified MS2 scan and the XIC's apex.

Best,

Fengchao

**Comment by eldenrowland** [comment]
Hi Fengchao, 

That's super helpful. So, if the rttol was set too low, and the peak apex was more than 0.4 min from the MS2 identification, then that peak would not be quantified? Or would the integrated peak be truncated?

Thanks very much,

Elden

**Comment by fcyu** [comment]
It won't be quantified.

Best,

Fengchao

**Comment by eldenrowland** [comment]
Thanks for your help Fengchao,

I had a few questions on the outputs from an FDR=1 search. I am following a post on how to export unfiltered psm.tsv reports (https://github.com/Nesvilab/FragPipe/issues/670).

I applied the suggested settings to generate the unfiltered psm.tsv table with IonQuant intensities (attached is the fragpipe workflow and a filter.log for one of the samples).

(1) Do I have the settings correct to yield completely unfiltered results? I noticed that for a sample containing 117994 MS2s, 89739 PSMs were exported. Is there a prefilter that limits the MS2s submitted for the database search?      

Thanks very much,

Elden Rowland
[filter.log](https://github.com/user-attachments/files/17951524/filter.log)
[Fragipe_workflow.txt](https://github.com/user-attachments/files/17951525/Fragipe_workflow.txt)

**Comment by fcyu** [comment]
> (1) Do I have the settings correct to yield completely unfiltered results? 

For the ProteinPophet cmd opt, you should not delete `--maxppmdiff 2000000`.

> I noticed that for a sample containing 117994 MS2s, 89739 PSMs were exported. Is there a prefilter that limits the MS2s submitted for the database search?

MSFragger will filter out low quality spectra and PSMs before and after the database search.

Best,

Fengchao
