### ISSUE TITLE
No MBR feature and no quantification results

### ISSUE THREAD

**Issue by drstiltz** [Nesvilab/FragPipe#1901]
[log_2024-11-26_18-48-29.txt](https://github.com/user-attachments/files/17929728/log_2024-11-26_18-48-29.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

1) Even though I choose the same experiment name for all samples, MBR feature does not turn on for my DDA run
2) I don't get any quantification results. Normally I would get them in a folder

**Comment by fcyu** [comment]
Could you send the log file or screenshots?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Do you have the "Spec Lib" tab enabled? If yes, please disable it.

Best,

Fengchao

**Comment by drstiltz** [comment]
When I turned off speclib tab, MBR worked, but I still don't get the 'combined' files. what could be the reason?

**Comment by drstiltz** [comment]
[log_2024-11-30_14-03-42.txt](https://github.com/user-attachments/files/17967452/log_2024-11-30_14-03-42.txt)
here is the log file

**Comment by fcyu** [comment]
You didn't specify any experimen or bioreplicate groups.

And you actually didn't enable MBR

Best,

Fengchao
