### ISSUE TITLE
TMT integrator - PTM on same AA, but different mass

### ISSUE THREAD

**Issue by jayieh** [Nesvilab/FragPipe#1902]
Hi,

I was running a search on TMT data (based on the TMT phospho template) - with 3 variable modifications on **one** amino acid - all with distingt masses (as opposed to pSTY - 3 different AA, same mass).

I added the tags within the TMTintegrator tab. (X(delta mass 1),X(delta mass 2),X(delta mass 3), - Group by = All)

The different mass shifts are found within the same peptide on the same AA - leading to various entries in the mod specific peptide table, but they are condensed to just one entry in the TMT report.

Is there a way to get a TMT report per modification (AA + mass), rather then by site?

**Comment by fcyu** [comment]
> Is there a way to get a TMT report per modification (AA + mass), rather then by site?

Currently, no.

Best,

Fengchao

**Comment by jayieh** [comment]
Hi @fcyu 

thank you for the quick reply. 

2 follow up questions:

- Is it planned to implement a mod / tag-specific grouping any time soon?

- Is it fine to run just the TMTintegrator with the different tags on the same search, or would you advice to run separate searches / validations?

**Comment by fcyu** [comment]
> Is it planned to implement a mod / tag-specific grouping any time soon?

AFAIK, there is no such plan in the near future.

> Is it fine to run just the TMTintegrator with the different tags on the same search, or would you advice to run separate searches / validations?

What is the "tag"? Do you mean the TMT tag or the variable modifications that you are interested in?

Thanks,

Fengchao

**Comment by jayieh** [comment]
The TMT tag / mass is the same (the PTM is not sitting at a K)

I was referring to the PTM / mod tag argument of TMT integrator. 
Should one run TMTintegrator with the different mass shifts (on the same AA) sequentially on the same search, or would you advice to run separate searches / validations one mass at a time?


Besides that, I am running into another problem:

I just ran a search with M and W + 15.9949 (as variable mod in fragger and PTMProphet) - on a TMT dataset, so i put 

W(15.9949),M(15.9949) as PTM mod tags in TMT-Integrator, but get the following error:

TMT-Integrator v5.0.9
TMT-Integrator can't find the corresponding site localization column. Please check if the column: WM:15.99 is in the psm tables.

This also happens when i just do M(15.9949) - TMT-Integrator asking for "M:15.99" with just 2 digits.

the respective psm.tsv has the 4 digit mass in the respective header.

**Comment by fcyu** [comment]
> Should one run TMTintegrator with the different mass shifts (on the same AA) sequentially on the same search, or would you advice to run separate searches / validations one mass at a time?

You could run the same search with all of your modifications/mass shifts so that the FDR will be controlled for all modifications globally.

> This also happens when i just do M(15.9949) - TMT-Integrator asking for "M:15.99" with just 2 digits.

You should put the same mass strings that displayed in the psm.tsv file. The mass shown in the error message is the one used internally. 

Best,

Fengchao

**Comment by jayieh** [comment]
I just realized, they were in a different order - it had to be MW in TMT integrator as in fragger...

Thank you so much for the help!
