### ISSUE TITLE
add files

### ISSUE THREAD

**Issue by maohuanyang** [Nesvilab/FragPipe#1903]
hello，
I want to know why this error occurs when adding a file, and the same file is on different computers, some can be added, and some can't.And how can I solve this problem?
Thank you and look forward to your reply
<img width="400" alt="微信图片_20241127175841" src="https://github.com/user-attachments/assets/15aae786-edcb-453a-a2fe-356c2caffb9d">

**Comment by guoci** [comment]
You have spaces in the file path.
