### ISSUE TITLE
DIA-spectlib-Quant output

### ISSUE THREAD

**Issue by Kim03143** [Nesvilab/FragPipe#1904]
Hi,

I'm new to MSFraggerDIA and recently worked with the DIA-spectlib-Quant workflow. 

I noticed that the IDs in the ”protein.tsv“ is slightly higher than that in the ”pg_matrix“ from the “diann-output”.

I followed the tutorial exactly as described without modifying any parameters. Are these default settings generally recommended?

**Comment by fcyu** [comment]
`protein.tsv` is generated during the spectral library building stage, and `pg_matrix` is generated after DIA quantification. Thus, you should use the tables in the `diann-output` folder for the DIA quant.

Best,

Fengchao

**Comment by Kim03143** [comment]
Thanks!
