### ISSUE TITLE
Issue with DiaNN ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library

### ISSUE THREAD

**Issue by chad-hyer** [Nesvilab/FragPipe#1908]
Hey, I am running a workflow that has worked before for doing quant on some DIA data and am getting an error I haven't encountered before and on multiple data sets. I am trying to use DiaNN on some Astral data without using a spectral library and am getting the error:
ERROR: C:\diann\src\diann.cpp: 19427: Cannot load spectral library

Looking through the log, it looks like it is trying to find a spectral library that doesn't exist even though the spectral library option is off. The rest of the outputs look fine. Please advise.

Thanks,
Chad Hyer

[DIA_1_log.txt](https://github.com/user-attachments/files/17981659/DIA_1_log.txt)
[DIA_2_log.txt](https://github.com/user-attachments/files/17981662/DIA_2_log.txt)

**Comment by fcyu** [comment]
Hi Chad,

It seems that you didn't have the Python and EasyPQP spectral library generation enabled.

Best,

Fengchao

**Comment by chad-hyer** [comment]
I didn't realize that I needed to enable spectral library generation to do this.
Thanks,
Chad
