### ISSUE TITLE
Processing interrupted, stopping Crystal-C

### ISSUE THREAD

**Issue by yb47620** [Nesvilab/FragPipe#191]
**Describe the bug**
Hello, a problem always occur when I am runing a open search.Could you help me figur it out. Thank you very much.
Part oof the log file said:
**Process 'Crystal-C' finished, exit code: 1

Process returned non-zero exit code, stopping**
Crystal-C [Work dir: D:\zpw\MSFragger-20171106]
java -Dbatmass.io.libs.thermo.dir="D:\zpw\MSFragger-20190628\MSFragger-20190628\ext\thermo" -Xmx16G -cp "C:\Users\admin\AppData\Local\Temp\fragpipe\batmass-io-1.16.1.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\grppr-0.3.23.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\original-CrystalC-1.0.7.jar" crystalc.Run D:\zpw\MSFragger-20171106\crystalc-1-fc150617_C3.pepXML.params D:\zpw\MSFragger-20171106\fc150617_C3.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 11/23 processes (12 already finished)
Processing interrupted, stopping Crystal-C

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by huiyinc** [comment]
Hi, can you please download the latest version of FragPipe and try again?
Thanks

Huiyin


yb47620 <notifications@github.com> 於 2020年5月22日 上午7:56 寫道：

﻿

*Describe the bug*
A clear and concise description of what the bug is.
Hello, a problem always occur when I am runing a open search.Could you help
me figur it out. Thank you very much.
Part oof the log file said:
**Process 'Crystal-C' finished, exit code: 1

Process returned non-zero exit code, stopping**
Crystal-C [Work dir: D:\zpw\MSFragger-20171106]
java
-Dbatmass.io.libs.thermo.dir="D:\zpw\MSFragger-20190628\MSFragger-20190628\ext\thermo"
-Xmx16G -cp
"C:\Users\admin\AppData\Local\Temp\fragpipe\batmass-io-1.16.1.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\grppr-0.3.23.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\original-CrystalC-1.0.7.jar"
crystalc.Run D:\zpw\MSFragger-20171106\crystalc-1-fc150617_C3.pepXML.params
D:\zpw\MSFragger-20171106\fc150617_C3.pepXML

Stopping 11/23 processes (12 already finished)
Processing interrupted, stopping Crystal-C

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/FragPipe/issues/191>, or unsubscribe

**Comment by anesvi** [comment]
Not just FragPipe, but MSFragger and philosopher
MSFragger looks a bit old

**Comment by yb47620** [comment]
Hello every one, thank all of your suggestions. After I updated all the software. The search stopped again and log file said:
	[progress: 51708/53691 (96%) - 4 spectra/s]Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.y.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp D:\zpw\FragPipe.exe umich.msfragger.util.FileMove E:\yeast\msFrageropen\20190704_ZJ_DJB_5.pepXML D:\temp\20190704_ZJ_DJB_5.pepXML

~~~~~~~~~~~~~~~~~~~~
Cancelling 13 remaining tasks
Processing interrupted, stopping MsFragger 
##########################################################################
is this because my PC's RAM is not sufficient? I allocated 16-GB RAM to the MSfragger.
[log-fragpipe-run-at_2020-05-23_20-28-11.log](https://github.com/Nesvilab/FragPipe/files/4672043/log-fragpipe-run-at_2020-05-23_20-28-11.log)

**Comment by fcyu** [comment]
Yes, not enough memory. Try to increase the number after `-Xmx` if you still have more memory.

**Comment by yb47620** [comment]
It is a bit strange. because I have finished a open search of 10 raw files using the same parameters before. This time I only searched 2 raw files, and it reported this problem. does it mean the new version software take more memory?
________________________________

**Comment by fcyu** [comment]
There is no big difference in terms of memory usage comparing to old versions. However, memory usage is the only thing that we don't have a fully control: it is managed by JVM's GC. There can be different reasons causing out-of-memory: MSFragger happens to use more memory because the GC doesn't managed to release the used memory, operator system level fluctuation, memory is being used by other software, and etc. 

I suggest you trying to increase the memory or increase the number of split database in the MSFragger Tab.

Best,

Fengchao

**Comment by yb47620** [comment]
Thank you very much, Fengchao. To save the memory, I didnot use the mass calibrate option in MSfragger. However, it report a nother error, could you help me find what is the problem?
#####################################################
Error at: 20190704_ZJ_DJB_5.1452.1452.3
java.lang.NullPointerException
at crystalc.p_Operator.CalculatePepMonoMass(p_Operator.java:21)
at crystalc.p_ProcessPSM.FindMissedCleavagePeptides(p_ProcessPSM.java:133)
at crystalc.p_ProcessPSM.CheckMissedCleavagePeptides(p_ProcessPSM.java:44)
at crystalc.WorkerThread.call(WorkerThread.java:97)
at crystalc.WorkerThread.call(WorkerThread.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Process 'Crystal-C' finished, exit code: 1

Process returned non-zero exit code, stopping
Crystal-C [Work dir: D:\temp]
java -Dbatmass.io.libs.thermo.dir="D:\zpw\MSFragger-2.4\MSFragger-2.4\ext\thermo" -Xmx32G -cp "C:\Users\admin\AppData\Local\Temp\fragpipe\batmass-io-1.17.2.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\grppr-0.3.23.jar;C:\Users\admin\AppData\Local\Temp\fragpipe\original-crystalc-1.1.0.jar" crystalc.Run D:\temp\crystalc-1-20190704_ZJ_DJB_6.pepXML.params D:\temp\20190704_ZJ_DJB_6.pepXML

~~~~~~~~~~~~~~~~~~~~
Cancelling 13 remaining tasks
Processing interrupted, stopping Crystal-C
________________________________
From: Fengchao <notifications@github.com>
Sent: Sunday, May 24, 2020 9:53 PM
To: Nesvilab/FragPipe <FragPipe@noreply.github.com>
Cc: yb47620 <yb47620@um.edu.mo>; Author <author@noreply.github.com>
Subject: Re: [Nesvilab/FragPipe] Processing interrupted, stopping Crystal-C (#191)


There is no big difference in terms of memory usage comparing to old versions. However, memory usage is the only thing that we don't have a fully control: it is managed by JVM's GC. There can be different reasons causing out-of-memory: MSFragger happens to use more memory because the GC doesn't managed to release the used memory, operator system level fluctuation, memory is being used by other software, and etc.

I suggest you trying to increase the memory or increase the number of split database in the MSFragger Tab.

Best,

Fengchao

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nesvilab_FragPipe_issues_191-23issuecomment-2D633234385&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=97E3fPNR-pF6p1yicV_ZK6NTIH0GQpoJOwptX_JuTTA&m=SnOL1Xl_9nJy_Y9nhJ4owMudp5EukvQ-JJUINeuh9V4&s=px5Dci6tqWqU6iGNloRNBqKFhg8LfgjIKOSQFwREVjY&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM55ZK4RJBE7WR2JOSL6JCLRTERFRANCNFSM4NHXC53A&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=97E3fPNR-pF6p1yicV_ZK6NTIH0GQpoJOwptX_JuTTA&m=SnOL1Xl_9nJy_Y9nhJ4owMudp5EukvQ-JJUINeuh9V4&s=K9CrZx_XD7DZTPTrFPMcFnb8120rrIzqINMgSkl-f1w&e=>.

**Comment by fcyu** [comment]
This error is from Crystal-C. Need @huiyinc 's help.

Best,

Fengchao

**Comment by huiyinc** [comment]
Hi,

One possible reason is that there are some characters (other than amino acids) in you protein fasta file. Could you please check if there is ‘*’ in your fasta file? If yes, please remove ‘*’. If not, could you please send us the pepxml files, fasta and mzML files? Thanks.

Huiyin

**Comment by yb47620** [comment]
Thank all of you. I find there is a‘*’ in my fasta file. After remove it, the MsFragger fisnished a open search. Thank you again!
________________________________

**Comment by anesvi** [comment]
Great

Hui-yin:
maybe we can make it more robust by skipping * and other similar characters in Crystal-C and just giving a warning?

Thanks
Alexey

**Comment by yb47620** [comment]
Hello all,
   The MSfragger said it can  ‘Generate Spectral Library from search results’ , could anyone tell me which file is the generated spectra library in the output file?
   Thank you very much!
    Pengwei
________________________________

**Comment by anesvi** [comment]
Not MSFragger. FragPipe has SpecLib module, currently with SpectraST. You need to check the box. You can also wait a few days for the new release of FragPipe that will make SpecLib module better

Sent from my iPhone

On May 26, 2020, at 7:18 AM, yb47620 <notifications@github.com> wrote:

﻿
External Email - Use Caution

Hello all,
The MSfragger said it can ‘Generate Spectral Library from search results’ , could anyone tell me which file is the generated spectra library in the output file?
Thank you very much!
Pengwei
________________________________

**Comment by fcyu** [comment]
@yb47620 Just in case, the spectral library generating is for closed search only.

Best,

Fengchao

**Comment by huiyinc** [comment]
Hi Prof. Alexey,

Sure, I will add a warming message if characters (not amino acids) are in
the fasta file. Thanks.

Huiyin

**Comment by chhh** [comment]
there's also BJOUX

**Comment by fcyu** [comment]
I think Crystal-C 1.3.1 fixes this.
