### ISSUE TITLE
Process 'DIA-NN' finished, exit code: -1073741819

### ISSUE THREAD

**Issue by chad-hyer** [Nesvilab/FragPipe#1910]
Hey, I am running some Astral DIA data on FragPipe, and am running into an unclear error in DIA-NN. The workflow is using a spectral library generated from this same set. Please advise.

Thanks,
Chad Hyer

[log_2024-12-03_16-00-40.txt](https://github.com/user-attachments/files/18000323/log_2024-12-03_16-00-40.txt)

**Comment by fcyu** [comment]
Same as https://github.com/Nesvilab/FragPipe/issues/1582

Best,

Fengchao
