### ISSUE TITLE
About thermo raw files convert

### ISSUE THREAD

**Issue by Li5459000** [Nesvilab/FragPipe#1912]
Hi,

When using MSConvert to convert Astral files, I encountered the error: "No matching instrument configuration for analyzer type Astral". So, I have to directly use raw files. But I noticed that it is recommended to convert Thermo raw files to mzML format.

1. Could you clarify the differences between directly using Thermo raw files and converting them to mzML in the DIA_speclib_Quant workflow? Specifically, will it affect analytical performance (e.g., peptides/proteins Ids)?

2. Considering that I have a large number of files and the conversion to mzML requires additional processing time, how about the analysis time difference?

**Comment by fcyu** [comment]
> Could you clarify the differences between directly using Thermo raw files and converting them to mzML in the DIA_speclib_Quant workflow? Specifically, will it affect analytical performance (e.g., peptides/proteins Ids)?

You will see small differences because the Thermo raw file parser library is different from what MSConvert is using. MSConvert is using the old C++ library while we are using the latest C# library.

> Considering that I have a large number of files and the conversion to mzML requires additional processing time, how about the analysis time difference?

The time difference is not significant.

Best,

Fengchao

**Comment by fcyu** [comment]
With the FragPipe version 23.0, they can be analyzed directly from RAW.

Best,

Fengchao
