### ISSUE TITLE
User's badly formatted manifest file crashed FragPipe

### ISSUE THREAD

**Issue by frankligy** [Nesvilab/FragPipe#1914]
Hello,

I am trying to run FragPipe on our HPC. To explain I did the following steps:

1. download Fragpipe.zip from the official website and unzip it
2. I then further download MSFragger, IonQuant, diaTracer and put the .jar files to the unzipped /fragpipe/tools folder, I also copied the /ext folder from MSFragger to Fragpipe tools to overwrite the existing /ext
3. I created a manifest file as below, so basically one raw file and named as `test_manifest.fp-manifest`:

```
/gpfs/data/yarmarkovichlab/MSFragger/test_thermo_data/20240110_E_OdinLC_IC_PDX_HD_19.raw    HN19    1   DDA
```

4. I modify the default `Nonspecific-HLA.workflow` by adding the fasta database that contains reverted decoys:

```
# Workflow: Nonspecific-HLA

database.db-path=/gpfs/data/yarmarkovichlab/MSFragger/test_db/ensembl_protein_add_decoy.fasta

crystalc.run-crystalc=false
```

I also loaded jdk/21.0.1 and python/3.9.13, now I ran as:

```bash
./fragpipe/bin/fragpipe --headless --workflow ./fragpipe/workflows/Nonspecific-HLA-customized.workflow --manifest ./test_manifest/test_manifest.fp-manifest --workdir ./test_thermo_data --config-tools-folder ./fragpipe/tools --config-diann /gpfs/data/yarmarkovichlab/MSFragger/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --config-python /gpfs/share/apps/python/cpu/3.9.13/bin/python
```
But I kept getting this:

```
2024-12-04 11:47:49,003 ERROR - Some loaded files don't exist. Please double check.
2024-12-04 11:47:49,007 ERROR - /gpfs/data/yarmarkovichlab/MSFragger/test_thermo_data/20240110_E_OdinLC_IC_PDX_HD_19.raw    DDA
```

While I can confirm the raw file path is correct.

So would you share some hints on what I have done wrong?

Best,
Frank

**Comment by fcyu** [comment]
Do you have mono installed https://fragpipe.nesvilab.org/docs/tutorial_setup_fragpipe.html#:~:text=Visual%20C%2B%2B%20redistibutable.-,Install%20Mono,-(required%20for%20Thermo ?

Thanks,

Fengchao

**Comment by frankligy** [comment]
Hi @fcyu,

Thanks for the prompt response, so this time I loaded mono as well, but the same issue persists:

```bash
(base) [lig08@bigpurple-ln4 MSFragger]$ module load java/9.0.4
(base) [lig08@bigpurple-ln4 MSFragger]$ module load python/cpu/3.9.13
Loading python/cpu/3.9.13
  Loading requirement: tk/8.6.8 tcl/8.6.8
(base) [lig08@bigpurple-ln4 MSFragger]$ module load mono/5.20.1
Loading mono/5.20.1
  Loading requirement: openmpi/gcc/64/3.1.0
(base) [lig08@bigpurple-ln4 MSFragger]$ ./fragpipe/bin/fragpipe --headless --workflow ./fragpipe/workflows/Nonspecific-HLA-customized.workflow --manifest ./test_manifest/test_manifest.fp-manifest --workdir ./test_thermo_data --config-tools-folder ./fragpipe/tools --config-diann /gpfs/data/yarmarkovichlab/MSFragger/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --config-python /gpfs/share/apps/python/cpu/3.9.13/bin/python
2024-12-04 13:21:40,019 ERROR - Some loaded files don't exist. Please double check.
2024-12-04 13:21:40,024 ERROR - /gpfs/data/yarmarkovichlab/MSFragger/test_thermo_data/20240110_E_OdinLC_IC_PDX_HD_19.raw    HN19    1   DDA
```

**Comment by fcyu** [comment]
Then, please double check if the paths in the manifest file are correct, and have the read permission.

Best,

Fengchao

**Comment by frankligy** [comment]
Hi @fcyu,

I appreciate it, but as far as I can tell, all the manifest, workflow and input files are in 777 as permission:

```
(base) [lig08@cn-0002 MSFragger]$ ls -l /gpfs/data/yarmarkovichlab/MSFragger/test_thermo_data/20240110_E_OdinLC_IC_PDX_HD_19.raw
-rwxrwxrwx 1 lig08 yarmarkovichlab 876443763 Dec  4 10:12 /gpfs/data/yarmarkovichlab/MSFragger/test_thermo_data/20240110_E_OdinLC_IC_PDX_HD_19.raw
(base) [lig08@cn-0002 MSFragger]$ ls -l ./test_manifest/test_manifest.fp-manifest
-rwxrwxrwx 1 lig08 yarmarkovichlab 108 Dec  4 11:51 ./test_manifest/test_manifest.fp-manifest
(base) [lig08@cn-0002 MSFragger]$ ls -l ./fragpipe/workflows/Nonspecific-HLA-customized.workflow
-rwxrwxrwx 1 lig08 yarmarkovichlab 12712 Dec  4 11:47 ./fragpipe/workflows/Nonspecific-HLA-customized.workflow
```
Is there any possibility due to some other more hidden issue?

**Comment by fcyu** [comment]
> sorry I figured that out, the manifest file should only contain the path, not the other columns as generated by the GUI.

It is not correct. The one generated by the GUI is the one you should use (after adjusting the path).

And it reminds me that the columns in your manifest file are separated by four spaces rather than a tab. Clearly, you edited it to have the wrong format.

> Also I had a very hard time trying to figure out where I can find instructions like that, that's why I am just guessing and tried different ways. I apologize if I missed any documentations.

This is the tutorial you should follow: https://fragpipe.nesvilab.org/docs/tutorial_headless.html. And DO NOT change anything unnecessary as a beginner.

Best,

Fengchao

**Comment by frankligy** [comment]
Thank you for spotting that, I think that's the issue.
