### ISSUE TITLE
TMT 18

### ISSUE THREAD

**Issue by lukasz536** [Nesvilab/FragPipe#1915]
Hi, I have a run to analyze a sample treated with TMTpro-134C (reporter ion mass 134.15466). I believe it is part of the TMT 18-plex. However, after installing the newest version, I see that TMT 16 is the highest available. Is there a way to adjust the reporter ion mass to include TMTpro-134C? Alternatively, can I use the table for TMT 18 and run the TMT 16 workflow instead? Thanks! Lukas

**Comment by fcyu** [comment]
Yes, you can use the TMT-16 workflow and adjust the related parameters to match the TMT-18's.

Best,

Fengchao

**Comment by fcyu** [comment]
Communicated by email.
