### ISSUE TITLE
Fragpipe stopped at Philosopher

### ISSUE THREAD

**Issue by ibphuangchen** [Nesvilab/FragPipe#1916]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-12-04_12-06-05.txt](https://github.com/user-attachments/files/18013846/log_2024-12-04_12-06-05.txt)
[msbooster_params.txt](https://github.com/user-attachments/files/18013855/msbooster_params.txt)
[fragger.params.txt](https://github.com/user-attachments/files/18013856/fragger.params.txt)

**- Describe the issue or question:**
Dear Fragpipe team,

I run the Fragpipe for a PDX MS datasets and the pipeline stopped at the Philosopher step. Could you take a look at the log file uploaded above and let me know how to address that issue? Thank you in advance!

Best,
Chen

**Comment by dpolasky** [comment]
Hi Chen,
You are using a newer Philosopher version (5.1.0) with a very old FragPipe version (18), and they are not compatible. Please update FragPipe to the latest version, which includes the correct Philosopher version internally.

Best,
Dan

**Comment by ibphuangchen** [comment]
Thank you for the prompt response, Dan!
