### ISSUE TITLE
DDA nonspecific HLA search not enough memory

### ISSUE THREAD

**Issue by frankligy** [Nesvilab/FragPipe#1918]
hello,

Sorry to bother again, I am the one who asked (https://github.com/Nesvilab/FragPipe/issues/1914). 

This time, program is running fine but crashes due to insufficient memory at one point. I attached both stdout and stderr. What I noticed is in stdout, the 394 GB sounds a lot to me, and I wonder if that has anything I do with my database or I should modify the number of slice/thread in workflow file (right now I kept the default for non-specific hla search), and my database is just normal 20k protein coding genes, and I added reverted decoy for each, so 40k in total.

```
26458493802 fragments to be searched in 2 slices (394.26 GB total)
```

[55760856_msfragger.out.txt](https://github.com/user-attachments/files/18026695/55760856_msfragger.out.txt)

[55760856_msfragger.err.txt](https://github.com/user-attachments/files/18026694/55760856_msfragger.err.txt)

**Comment by fcyu** [comment]
Your search space is quite big. Please enable the "split database" in the "MSFragger" tab by changing the number to, say, 4.

Best,

Fengchao

**Comment by frankligy** [comment]
Thanks for the prompt response.

Regarding the "split database", sorry I am not using the GUI, and I apologize if I missed the instructions somewhere, but do you know how to set this in the workflow file? Attaching what I am using now.

[Nonspecific-HLA-customized.workflow.txt](https://github.com/user-attachments/files/18026963/Nonspecific-HLA-customized.workflow.txt)

Regarding the low-res and high-res, I am not an expert (I didn't generate data), but I guess it is because our proteome core acquire MS2 based on the precursor charge state, and use different fragmentation method, energy and resolution.

Thanks again,
Frank

**Comment by fcyu** [comment]
I suggest you follow the tutorial here https://fragpipe.nesvilab.org/docs/tutorial_headless.html. Configure the parameters in the GUI and export the workflow file.

Best,

Fengchao

**Comment by frankligy** [comment]
I appreciate it, I'll play with the GUI on my end.
