### ISSUE TITLE
I and L still occasionally mixed up

### ISSUE THREAD

**Issue by hollenstein** [Nesvilab/FragPipe#1919]
Dear Fengchao,

I've already commented on the relevant and still open issue in the [philosopher repository](https://github.com/Nesvilab/philosopher/issues/430). But since I didn't get a reply yet I wasn't sure if you have also seen it. I just wanted to let you know that the wrong reporting of `L` and `I` still exists in FragPipe/Philosopher (5.1.1).

In case you don't remember what it was about. This time found a peptide in the `combined_peptide.tsv` table with `I` in its sequence that didn't exist in the reported protein, the actual sequence in the protein was the same but with an `L` instead of the `I`. We then checked the FASTA file and found the reported sequence in a decoy protein.

Best,
David

**Comment by fcyu** [comment]
Hi David,

Thanks for the reminding. I am aware of that. Philosopher is the program that I am not familiar with because it was developed by Felipe and in Go.

There are several bugs that have been bothering the users and us for a long time. We are discussing internally how to deal with that.

Best,

Fengchao

**Comment by hollenstein** [comment]
Hi Fengchao,

thanks for the update. I might have an idea how to fix this particular issue in philosopher. At least if I am guessing correctly that you use the `filter` command from philosopher in the FragPipe pipeline for updating your output files.

But this seems to be the case because in the ".workflow" files I found the following line pretty close to the end of the pipeline.
`phi-report.filter=--sequential --picked --prot 0.01`

Let me know if you want me to help.

Best,

David

**Comment by fcyu** [comment]
Hi David,

Sound great! Yes, the filter and report command are what FragPipe is using to get the peptide to protein mapping and generate the tsv tables.

A pull request to https://github.com/Nesvilab/philosopher is more than welcome.

Best,

Fengchao

**Comment by hollenstein** [comment]
Hi,

I’ll give it a try but the more I look at the code bases the less certain I am what is going on … it might also take a bit because I’ll be on vacation for two weeks soon.

Anyways, I’ve been thinking about what is required to properly fix this issue.
1) it should be consistently fixed in all FragPipe workflows
2) it should be fixed as early in the workflow as possible
3) it should be done in exactly one place and fix the peptide sequence in all relevant files

The issue most likely emerges at the step of protein inference, when peptides are reassigned to the one entry of the mapped proteins that selected as the representative protein in the protein table. So immediately or shortly after the protein inference is done, we should update the peptide sequences (and also modified peptide sequences) in all tables that have been created so far. So the question is, when does this happen?

First of all, I’ll need some help in understanding how FragPipe actually works. I’ve tried to understand it myself but I got completely lost at first =). What I am trying to figure out is where the order of commands and tools is determined when FragPipe is run.

What I understand (or rather believe to understand) is the following. In the `.workflow` files you specify parameters that are somehow used for the commands in the `fragpipe/cmd` modules. The `cmd` modules all contain a helper function to run a command line tool (like msfragger or philosopher report). The order in which the command line tools are run is specified in `fragpipe/FragPipeRun.java`. I suspect the order is determined by the dependencies that a command function is passed to `addToGraph`, so the graph is the representation of the workflow?

```java
addToGraph(graphOrder, cmdMsfragger, DIRECTION.IN, cmdCheckCentroid, cmdUmpire);
```

For example here you add the `cmdMsfragger` command to the graph, and you specify that it depends on `cmdCheckCentroid` and `cmdUmpire` so it can only run once those two are finished.

Is all of this correct so far?


If so, then the order of events (not including all), is you run MsFragger for peptide spectrum matching and then MsBooster. For FDR calculation you then use PeptideProphet, Percolator, PtmProphet and ProteinProphet. But then you also run Philosopher filter with sequential and picked, so that seems to also calculate the FDR again?
- Is ProteinProphet the tool responsible for protein inference?

Afterwards you run several philosopher commands. Here it becomes even more confusing for me.
- You run PhilosopherDbAnnotate, which runs the Philosopher `database --annotate` command, but I am not 100% sure what it does. Maybe read the FASTA file?
- Then PhilosopherFilter is used to calculate the protein FDR again? Or does it calculate protein FDR (again?) and uses this to filter the table? Or do you not use ProteinProphet to calculate protein level FDR? Anyways, it seems that the `filter` command removes entries from various xml files that do not pass certain filter criteria.
- Then you run PhilosopherReport, which seems to create the `.tsv` files for the individual runs?
- After PhilosopherReport, you run PhilosopherAbacus, which creates the `combined_.tsv` report files.
- And later you run IonQuant, and I suspect that IonQuant itself again modifies the individual evidence files `.tsv` for each run, and also the `combined_.tsv` report files, to update the quantified MS1 intensities. Does IonQuant change additional entries except the intensities?

Again, I am not sure if I got these things right. But if so, then I guess the best place would be to correct the peptide sequences before `PhilosopherReport`, maybe around the same time that `PhilosopherFilter` is run. Or maybe in `PhilosopherDatabaseAnnotate`, but I have the feeling this does nothing but read and process a FASTA file, so it can be used later by other commands? Would it make more sense to fix the pepide sequnces in the `xml` files? `PhilosopherFilter` seems to operate on the `xml` files, and probably modify them? Then I would guess `PhilosopherReport` reads the `xml` files and outputs `tsv` files, but I couldn’t figure that out.

- There are the "original" `pepXML` files and then there are the `interact-...pepXML` files, which are created by PeptideProphet. I guess all downstream steps of Philosopher is using the `interact` files, right? 

Sorry for the extremely long post. Maybe it’s just me but Philosopher seems to be awfully complex, or at least the lack of any documentation makes it really hard to understand what the individual commands and their flags actually do. 

Best,
David

**Comment by fcyu** [comment]
Hi David,

I don't think you need to digest the FragPipe code base. What you need to do is fixing Philosopher filter command: https://github.com/Nesvilab/philosopher because that it the root of the issue.

Best,

Fengchao

**Comment by anesvi** [comment]
Let me talk to Yamei and see if she can find time to fix it. David, thanks for trying to understand FragPipe though! Few people try to look into the vide hoping to help us fix things.

**Comment by hollenstein** [comment]
I might have gotten carried away a bit =). However, I am hesitant to make changes to a code base I don’t understand at all, so I tried to figure out how `filter` and `report` are used and what their purpose is. I am still motivated to try and fix it, but if Yamei starts working on it please let me know so I don’t spend unnecessary time on it. Fengchao, don’t worry about not having the time to help me out.

Btw, you don’t need to respond to the following part. I just wanted to add my thoughts here as it might be useful for someone else looking into the issue in the future.

Fixing the issue seems in principle to be quite straightforward. The problem for me is rather to be sure there are no unexpected side effects of what I am doing, and to change the sequence in all relevant places. The best place to introduce a fix seems to be in `UpdateLayerswithDatabase` in `lib/rep/updater.go`. 

There is still at least one problem I need to figure out. One also needs to update the modified peptide entry (e.g. in the PSM Report), so I am still looking for where in the library the modified sequence is constructed in the first place, so I don't have to write a new function for doing that.

Best,
David

**Comment by fcyu** [comment]
> I still need to figure out how exactly I build philosopher, and then I need to test it locally if it still works and if the issue is fixed. I will keep you updated.

I normally build it in Ubuntu or Windows WSL. Cd it to the philosopher directory and run `make rc`

Hope it helps and saves you some time.

Best,

Fengchao

**Comment by guoci** [comment]
@hollenstein the Philosopher build instructions are here: https://github.com/Nesvilab/philosopher/wiki/How-to-Build
For the exact commands, you can check the GitHub Actions workflow file: https://github.com/Nesvilab/philosopher/blob/master/.github/workflows/go.yml

**Comment by hollenstein** [comment]
Hi, thanks for pointing me in the right direction. I've managed to build philosopher and, as far as I can tell, I've also managed to fix the issue. I've made a pull request in the philosopher repository.

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/philosopher/pull/517
