### ISSUE TITLE
Peptides vs PSM files - Counts of identified peptides

### ISSUE THREAD

**Issue by diegomagassis** [Nesvilab/FragPipe#1920]
Dear Fragpipe Team. 

that's not a crash but I would to understand Peptide.tsv vs PSM.tsv output files. After searching some samples (non specific HLA workflow), peptides .tsv reports some sequences with an empty probability. These sequences are not present in the psm.tsv file. However numbers shown on the PDV viewer aligns with the peptides.tsv. Thus, are these peptides really confirmed because there are not listed in psms or are they from low scores/decoys and etc? In summary, should peptides or psms be used to validate/confirm identification? 

Thank you very much 

Diego

**Comment by fcyu** [comment]
Did you have the MBR enabled? If yes, those peptides should be from MBR.

Best,

Fengchao

**Comment by diegomagassis** [comment]
HI Feng. 

Thank you for the quick response. 

Yes. MBR was enabled. Follow up question. Therefore as the intensity is calculated, these peptides are confirmed and can be count in the sample, right? 

Thanks again

Diego

**Comment by fcyu** [comment]
> Therefore as the intensity is calculated, these peptides are confirmed and can be count in the sample, right?

It's correct.

Best,

Fengchao
