### ISSUE TITLE
Narraw (regular) search is working, but open search is not?

### ISSUE THREAD

**Issue by Ming339-uw** [Nesvilab/FragPipe#1921]
[log_2024-12-07_21-57-58-open.txt](https://github.com/user-attachments/files/18054155/log_2024-12-07_21-57-58-open.txt)
[log_2024-12-07_22-20-38-regular.txt](https://github.com/user-attachments/files/18054157/log_2024-12-07_22-20-38-regular.txt)

**- Describe the issue or question:**
Hi, our group just started to try to implement the Fragpipe workflow, we like the speed and the open search feature! However, we recently ran into one bizarre issue: We would like to test drive an Ecoli peptide library and generate one run from a QE. However, if we run an open search, no result is generated (as the protein prophet commended there is no result generated). However, we run a regular narrow search we get over 5000 peptides. Would you mind helping to give us a clue what might be wrong? Both searches used the same database and the same raw files.

Thanks a lot

**Comment by fcyu** [comment]
There are almost no identifications from your data:
```shell
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |      1|      0| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |      1|      1|      1|      1|      1|      1
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |      0
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |      1
-------|-------
```

Please double check your parameter settings and databases.

Best,

Fengchao

**Comment by Ming339-uw** [comment]
Thanks for the fast reply. I added the variable modification (dimethylation) and I get some results. So just being curious, if some universal modification (e.g dimethylation on N-term and K) exists and I did not specify that in the open search, will open search give out near 0 id? like what I experienced?

**Comment by fcyu** [comment]
If your samples have chemical labeling, you should add them as car mod. Because most peptides will have one or more of those modifications.

Best,

Fengchao
