### ISSUE TITLE
Issue with SAINTexpress

### ISSUE THREAD

**Issue by larsonlarsoff** [Nesvilab/FragPipe#1924]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-12-09_15-08-04.txt](https://github.com/user-attachments/files/18067545/log_2024-12-09_15-08-04.txt)
[log_2024-12-09_15-08-25.txt](https://github.com/user-attachments/files/18067544/log_2024-12-09_15-08-25.txt)

**- Describe the issue or question:**

Hi there, I have been running default LFQ-MBR analysis for AP-MS and I am trying to perform the SAINTexpress downstream process. Whenever I run it, I am provided with an exit code of 3 and a cancelling of my remaining task:

terminate called after throwing an instance of 'char const*'
Process 'SaintExpress' finished, exit code: 3
Process returned non-zero exit code, stopping

I am not sure how to fix this, I have uploaded the logs for my runs. First is before I ran SAINTexpress. Second is after I ran it.

Any help would be appreciated.
Thank you

**Comment by larsonlarsoff** [comment]
Hi Fengchao,

Thank you for your help. I followed the instructions here as I couldn't find other documentation regarding this.
https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#affinity-purification-data

I re-named my experiments to the official gene ID of the bait protein. However, the ID for my organism contains a colon, periods, and a dash. The experiment name changes all of them to an underscore and I think that might be causing an issue. Can you let me know if this is the case and if there's a way to correct it.

Here are the logs for some runs I tried:
[log_2024-12-09_15-57-24.txt](https://github.com/user-attachments/files/18068073/log_2024-12-09_15-57-24.txt)
[log_2024-12-09_16-10-28.txt](https://github.com/user-attachments/files/18068075/log_2024-12-09_16-10-28.txt)

Kind regards,
Larsen

**Comment by larsonlarsoff** [comment]
Hi Alexey,

Thanks for getting back to me, I do have my control experiments labelled as CONTROL. Are they not visible as CONTROL in the second set of logs I provided?

Unfortunately, the issue still persists unless I missed something here.

Kind regards,
Larsen

**Comment by fcyu** [comment]
Could you share the `reprint.spc.tsv` and `reprint.int.tsv` files?

Thanks,

Fengchao

**Comment by anesvi** [comment]
I see it now. Please try assigning each CONTROL file to a different replicate (you have them all together) and name all BAIT IP files as just TB92785510 (and also replicates), without any underscores

**Comment by larsonlarsoff** [comment]
Hi Alexey,

I completed another run as per your suggestions and it worked! Thank you for your help and to Fengchao as well.

Hope you both have a great rest of your day!

Kind regards,
Larsen
