### ISSUE TITLE
Labeling quantification on phosphopeptides using DDA

### ISSUE THREAD

**Issue by GNMiller0114** [Nesvilab/FragPipe#1925]
Hello,
          We are using FragPipe to analyze isotopically labeled peptides using DDA and want to analyze the phosphoproteome. However, when we try to change the minimum site localization probability in MS1 quant, the number of unique phosphopeptides does not change. Additionally, we didn't get the combined_site_STY.tsv files. Are the phosphopeptides in the combined_modified_peptide_label_quant filtered by the localization probability cutoff?
                         Thanks.

**Comment by fcyu** [comment]
> Additionally, we didn't get the combined_site_STY.tsv files. 

Do you have PTM localization in the "validation" tab enabled?

> Are the phosphopeptides in the combined_modified_peptide_label_quant filtered by the localization probability cutoff?

No.

Best,

Fengchao

**Comment by GNMiller0114** [comment]
We have tried enabling and disabling the PTMProphet, but both results didn't show the combined_site.tsv files. If combined_modified_peptide_label_quant.tsv doesn't have the localization scores, is there another file we should be looking in to find them?
Thanks.

**Comment by fcyu** [comment]
psm.tsv.

Could share the log file?

Thanks,

Fengchao

**Comment by GNMiller0114** [comment]
[log_2024-11-09_21-39-29_withPTMProphet.txt](https://github.com/user-attachments/files/18084691/log_2024-11-09_21-39-29_withPTMProphet.txt)
 Here is our log file.

**Comment by fcyu** [comment]
Ah, I got it. The isotopic labelling quant won't generate the site report.

Best,

Fengchao
