### ISSUE TITLE
Skyline stopped generating documents

### ISSUE THREAD

**Issue by ambgrav** [Nesvilab/FragPipe#1926]
Hello,

I am trying to process DIA files with FragPipe, and while DIA-NN and the other programs seem to be working, no Skyline document is generated. There is a Skyline folder generated in my output file, but it only contains a .txt file that says "library.tsv.skyline.speclib". Skyline has worked for me in the past, but stopped working some time in the past month or so. Log file and generated Skyline file attached.

Thank you for your help!

Best,
Amber

[fragpipe.redundant202412020518.stdin.txt](https://github.com/user-attachments/files/18069854/fragpipe.redundant202412020518.stdin.txt)

[log_2024-12-04_18-11-00.txt](https://github.com/user-attachments/files/18069849/log_2024-12-04_18-11-00.txt)

**Comment by fcyu** [comment]
Hi Amber,

The Skyline module currently has some issues with DIA-NN 1.9.1. Could you change back to the FragPipe built-in one by deleting the DIA-NN path in the config tab, and try again?

Thanks,

Fengchao

**Comment by ambgrav** [comment]
Hi Fengchao,

Thanks for your response! I reran the search with the built in DIA-NN v1.8.2_beta_8 (was auto selected after deleting the path), and I am still running into the same issue. I've attached the log file from the new search.

[log_2024-12-09_17-20-34.txt](https://github.com/user-attachments/files/18070148/log_2024-12-09_17-20-34.txt)

Thanks,
Amber

**Comment by fcyu** [comment]
Thanks for the testing and feedback. There are 203.09 on C as variable modification, (by the way, please put the precise mass value with more decimal points), and 57.02146 on C as fixed modification, which might confuse Skyline. 

Could you change the 57.02146 on C as a variable modification, and change 203.09 to the summation of 203.09 (with more decimal points) and 57.02146?

Thanks,

Fengchao

**Comment by ambgrav** [comment]
Hi Fengchao,

I changed the variable mods (including a more precise mass) and this fixed the issue! Thank you so much for your help!

Best,
Amber

**Comment by fcyu** [comment]
No prob.

Best,

Fengchao
