### ISSUE TITLE
nocleavage enzyme cut but error

### ISSUE THREAD

**Issue by ABChh26** [Nesvilab/FragPipe#1927]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[Uploading log_2024-12-10_11-17-30.txt…]()
![Uploading image.png…]()

**- Describe the issue or question:**

I searched the raw file library in fragpipe22, then workflow selected LFQ-MBR and enzyme cleavage mode ‘nocleavage’, but an error was reported in the "FIRST SEARCH" section.
 'In total 0 peptides.
Generated 0 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Java. Lang. ArrayIndexOutOfBoundsException: Index - 1 out of bounds for length 0 ', 
is it because some parameters set is too strict？Whether this 'nocleavage' enzyme cutting  method requires that the sequence is all the same to be counted as a match？Please give any Suggestions! Thanks very much!

**Comment by fcyu** [comment]
`nocleavage` means no cutting. 

BTW, your uploaded log and image files are not available.

Best,

Fengchao
