### ISSUE TITLE
Fatal Error at PeptideProphet FragPipe v13

### ISSUE THREAD

**Issue by xLinkKnight** [Nesvilab/FragPipe#193]
Fatal error during timsTOF ddaPASEF data analysis. I receive this error when attempting to use the MSFragger 3.0/FragPipe 13 combination for timsTOF data analysis and spectral library generation (EasyPQP). MSFragger 2.4/FragPipe 12.2 was successful in the past with this same data.

Log file is attached:
[log_2020-06-08_17-18-09.txt](https://github.com/Nesvilab/FragPipe/files/4749118/log_2020-06-08_17-18-09.txt)

Workflow: LC/MS Files, IM-MS, 6 files grouped into 1 experiment
Database: Human, Philosopher generated with common contaminants and decoys
MSFragger: Standard trypsin digest, output TSV_and_PEPXML and calibrated MGF
Validation: Run PeptideProphet (closed search), run ProteinProphet, and Generate Report
Quant (LFQ): LFQ by IonQuant, match between runs enabled
PTMs: Run PTM-Shepherd (Open search)
Spec Lib: Generate Spectral Library with EasyPQP, automatic selection of a run as reference

Software versions:
FragPipe v13
MSFragger v3.0
Philosopher v3.2.7
Anaconda3 Python v3.7.4, msproteomicstools and EasyPQP

System:
Windows 10
32c AMD
128 GB RAM

**Comment by fcyu** [comment]
@xLinkKnight Can you try an old version of Philosopher, for example 3.2.3? You can uncheck MSFragger since you already have all those files.

@prvst Can you take a look when you have time?

Thanks,

Fengchao

**Comment by xLinkKnight** [comment]
Appreciate the quick response! The downgrade to 3.2.3 helped. I haven't checked any of the intermediate version between 3.2.3 and 3.2.7. The problem is now at the last step, spectral library generation. It fails to execute the easypqp conversion and I'm not sure what to make of the log file interpretation.

Log file:
[log_2020-06-08_21-04-14.txt](https://github.com/Nesvilab/FragPipe/files/4749775/log_2020-06-08_21-04-14.txt)

For clarity, the data and system used which generated the attached log file is different than that of the original comment. Our two systems had the same issue and the Philosopher downgrade was easier to perform on the second system.

Should I make a new post about the EasyPQP problem or is this thread okay for now?

**Comment by anesvi** [comment]
Regarding the Philosopher crash, none of us have seen such an error in the past.  Not sure what Felipe (cc’ed) can do -  he is the main Philosopher developer.

Regarding EasyPQP: when did you install easyPQP ? You may need to re-install it unless you installed it very recently. If this does not solve, need to check with Guo Ci

Alexey

**Comment by prvst** [comment]
@xLinkKnight The issue you see with Philosopher and PeptideProphet seems to be between your computer system and the language compiler. Unfortunately, this is beyond what I can do in terms of support. Out of curiosity, could you give me more details about the (first) computer that you tried running our programs?

**Comment by chhh** [comment]
@prvst apparently the reason must be somewhere in the chages between between those 4 minor versions.

**Comment by guoci** [comment]
@xLinkKnight there should be some log files from `easypqp` named as `easypqp_convert_*.log`. Please upload them.
Also, update EasyPQP if it is outdated, with:
```
pip uninstall --yes easypqp
pip install git+https://github.com/grosenberger/easypqp.git@master
```

**Comment by xLinkKnight** [comment]
@guoci Thank you for the tip. I must have not seen the EasyPQP 0.1.7 release. I was on 0.1.6 at the time of the errors.
```
pip uninstall --yes easypqp
pip install git+https://github.com/grosenberger/easypqp.git@master
```
I processed the data once again from start to finish just for completeness. I've attached one of the ```easypqp``` log files. The others are the same except for file name differences. No report of errors, unless it's missing the library generation part.

[easypqp_convert_0.log](https://github.com/Nesvilab/FragPipe/files/4755677/easypqp_convert_0.log)

Attached are the processing log files: (Not sure why the export option sometimes truncates the text. Attached is a full and truncated export.)
[log_2020-06-09_15-07-08.txt](https://github.com/Nesvilab/FragPipe/files/4755685/log_2020-06-09_15-07-08.txt)
[log_2020-06-09_15-35-28.txt](https://github.com/Nesvilab/FragPipe/files/4755686/log_2020-06-09_15-35-28.txt)

The ```Spectral library building``` section of the log file seems to be slightly worrying. The EasyPQP logs claim it was successful and I do have ```*.peakpkl``` and ```*.psmpkl``` files. They are not empty in size. So the ```easypqp convert``` task is working but it fails at ```easypqp library```? Let me know if having the ```*.peakpkl``` and ```*.psmpkl``` files would be helpful.

@prvst Hello Felipe. Would you still like more information about the system? If so, may I ask for the type of information you would like? I'm naive when it comes to the type of information which would benefit a developer.

**Comment by xLinkKnight** [comment]
I'll try it with both DIA-NN and Spectronaut. Have to extend my Spectronaut trail as I haven't had time to thoroughly test it.

**Comment by anesvi** [comment]
I do not recall if you have Thermo or Bruker data. DIA-NN has limited support for diaPASSEF at the moment, although I am sure that will change in the future.
At any rate, let us know if you have any other questions.
Best
Alexey

**Comment by xLinkKnight** [comment]
@anesvi Primarily used for the processing of Bruker data (timsTOF). Building up my knowledge for when we utilize diaPASEF more frequently. I was able to process some of my data using the ciRT option. My fractionated dataset fails no matter what I try. It was my mistake of not included iRT peptides when they were ran.

@prvst @chhh I did some basic testing of the different Philosopher versions. The issue seems to stem from the latest release, v3.2.7. Using v3.2.6 and the revisions before it cause no issue. Is this just a problem on my end caused by a certain set of system conditions?

v3.2.7 log file:
[log_2020-06-12_22-23-32.txt](https://github.com/Nesvilab/FragPipe/files/4773996/log_2020-06-12_22-23-32.txt)
v3.2.6 log file:
[log_2020-06-12_22-14-54.txt](https://github.com/Nesvilab/FragPipe/files/4773997/log_2020-06-12_22-14-54.txt)

Software and version used:
FragPipe v13
MSFragger v3.0
Java v1.8
Anaconda3 Python v3.7.4
EasyPQP v0.1.7

**Comment by anesvi** [comment]
I hope Felipe @prvst can take a look at why v3.2.7 fails when v3.2.6 and earlier are fine. There were minor changes related to finding the pep.xml files when the full path to the folder is passed to philosopher. You can use the previous version, maybe Felipe can fix your problem in the next release.

If you use human data, I am not sure why fractionated data fails. Even with plasma, I expected enough peptides would be in each fraction that included in the ciRT peptide list. But we have not tested, so not sure.

Best,
Alexey
