### ISSUE TITLE
 database is locked. 'diaTracer' finished

### ISSUE THREAD

**Issue by Kokoushin** [Nesvilab/FragPipe#1930]
Hi, 

I encountered this error while analyzing a DIA-PASEF dataset: 'database is locked.' 

Could this be caused by my local setup? 
[log_2024-12-11_00-52-44.txt](https://github.com/user-attachments/files/18087767/log_2024-12-11_00-52-44.txt)

**Comment by fcyu** [comment]
I think your file `Z:\AD_MS-DATA\Ko\6_DIA\dia-PASEF\Raw\diaPASEF_Condition_B_02.d` was either corrupted or being used by another program.

Best,

Fengchao
