### ISSUE TITLE
Nonspecific-peptidome

### ISSUE THREAD

**Issue by nishimuy87** [Nesvilab/FragPipe#1931]
Dear FragPipe team,

Could you please let me know if the nonspecific-peptidome pipeline was designed for tryptic peptides in addition to plasma and CSF samples? I would like to search truncated peptides using FragPipe, but do you know if anyone has tried it already? Any information would be highly appreciated.

Best wishes,
Yusuke

**Comment by nishimuy87** [comment]
Thank you for your response, would you recommend LFQ-MBR with SEMI in the enzyme setting to search truncated peptides?

**Comment by anesvi** [comment]
Yes, load LFQ-MBR workflow and change to Semi.
