### ISSUE TITLE
invalid spectrum file path

### ISSUE THREAD

**Issue by littlestar-416** [Nesvilab/FragPipe#1933]
Hello, 
When I used Fragpipe-PDV to view the analyzed data, PDV could not display the spectrum diagram, but other modules could. The error message is: invalid spectrum file path.
Below is the folder of data that I imported that has been analyzed

![屏幕截图 2024-12-11 235652](https://github.com/user-attachments/assets/b49298b4-d1b1-45c0-b386-b60c6b38764a)

![屏幕截图 2024-12-12 000017](https://github.com/user-attachments/assets/a76d0ab8-cfa4-4c99-abe2-bad75ad275b7)

![屏幕截图 2024-12-12 000109](https://github.com/user-attachments/assets/32ea84d7-8b14-415b-a6f0-af259b58dfdc)

**Comment by KaiLiCn** [comment]
Hi,

Can you share your log and fp-manifest files with us? Did you move your files after searching?

Kai

**Comment by littlestar-416** [comment]
> Hi,
> 
> Can you share your log and fp-manifest files with us? Did you move your files after searching?
> 
> Kai

Thanks for your quick reply!
I didn't analyze the data, I copied it on my hard drive after someone else analyzed it. I don't know if it will have any impact. 
Below is a screenshot of the fp-manifest file after it is opened.

![屏幕截图 2024-12-12 002828](https://github.com/user-attachments/assets/35151106-8f4e-4a6b-a3c6-fea57740dbda)

**Comment by KaiLiCn** [comment]
Yes, FragPipe-PDV uses the path information from the fp-manifest file. Please update the spectrum file path to your current one in the fp-manifest file.

**Comment by littlestar-416** [comment]
> Yes, FragPipe-PDV uses the path information from the fp-manifest file. Please update the spectrum file path to your current one in the fp-manifest file.

 I changed the file path and tried again, and it still shows the same error as before. I'm not sure if I made the correct change, here is the changed screenshot, and the path where my files are located. Please help me to see what the problem is. Thank you very much.

![屏幕截图 2024-12-12 005051](https://github.com/user-attachments/assets/ab9edce8-96cb-4ef0-a4fb-61e93a397f2d)

![屏幕截图 2024-12-12 005139](https://github.com/user-attachments/assets/205be0c1-2aa3-45c1-9437-abefefb6e61b)

**Comment by littlestar-416** [comment]
> OK. Can you share your log and manifest file with me?
Here are my log and manifest files.
[新建文件夹.zip](https://github.com/user-attachments/files/18099503/default.zip)

**Comment by littlestar-416** [comment]
> Yes, FragPipe-PDV uses the path information from the fp-manifest file. Please update the spectrum file path to your current one in the fp-manifest file.

Sorry, I want to confirm, do you mean to change the location of the spectrum file to the path shown in the manifest file, or change the path in the manifest file to the current location of the spectrum file? I did it the latter way. Because the path in the original manifest file that I copied to my computer still showed the path on someone else's computer, I couldn't change the position of my spectrum file by following that path.

**Comment by littlestar-416** [comment]
> You did it correctly. Please change the path in the manifest file to the current location of the spectrum file and save the file. Otherwise the manifest file is not actually updated.

I was careless!!! I didn't save it just now. 
It's all settled now. Thank you very, very much for your help!
