### ISSUE TITLE
Question about protein grouping method of "combined_protein.tsv" + missing column in the file "combined_peptide.tsv" 

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1936]
Hi! I used Fragpipe 20.0 to analyze a TMT dataset, and I used the columns "Protein.ID" and "Indistinguishable.Proteins" of the file "combined_protein.tsv" to obtain protein groups. How are these protein groups defined by Fragpipe? Is there a way to obtain peptide-level information which was used to define these protein groups? 

I also noticed that the column "Mapped.Proteins" is missing in the file "combined_peptide.tsv" (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_peptidetsv). Is this a bug or is this something that is related to changes in the content of this output file of FragPipe?
Thank you very much! 

Best regards, 
Roberto Albanese

**Comment by fcyu** [comment]
> How are these protein groups defined by Fragpipe?

It is generated by ProteinProphet (https://proteinprophet.sourceforge.net/prot-proph.pdf), which is based on the Occam's razor.

>  Is there a way to obtain peptide-level information which was used to define these protein groups?

The peptide level table has the protein and mapped proteins information.

> I also noticed that the column "Mapped.Proteins" is missing in the file "combined_peptide.tsv" (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_peptidetsv). Is this a bug or is this something that is related to changes in the content of this output file of FragPipe?

No, the "Mapped Proteins" column is in the "combined_peptide.tsv" table.

Best,

Fengchao

**Comment by fcyu** [comment]
If you run IonQuant in your workflow, which you should when doing TMT, there are "mapped proteins" in the "combined_peptide.tsv".

Best,

Fengchao

**Comment by anesvi** [comment]
Your post says "Fragpipe 20.0 ". This is an old version, the latest release is 22.

**Comment by RobAlbn** [comment]
I also ran searches with Fragpipe 22.0. Actually, when using the latest release, I obtain "combined_peptide.tsv" files with the "Mapped Proteins" column. Was this column missing from Fragpipe v20.0 search results because of differences between the two Fragpipe versions? Finally, the file "combined_peptide.tsv" contains peptide-level informaton that is used to define protein groups in the file "combined_protein.tsv", right? Thank you very much!

**Comment by fcyu** [comment]
> Was this column missing from Fragpipe v20.0 search results because of differences between the two Fragpipe versions?

> Finally, the file "combined_peptide.tsv" contains peptide-level informaton that is used to define protein groups in the file "combined_protein.tsv", right? 

I guess so.

Best,

Fengchao

**Comment by RobAlbn** [comment]
Thank you very much!
