### ISSUE TITLE
Insufficient Memory Process 'MSFragger' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by talithar-star** [Nesvilab/FragPipe#1938]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zippe
[log_2024-12-12_13-41-55.txt](https://github.com/user-attachments/files/18117758/log_2024-12-12_13-41-55.txt)
d file by drag & drop here.)

**- Describe the issue or question:**
Insufficient Memory
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
According to your log file, there are only 1 GB free memory available, which is not enough for the analysis you are doing.

Best,

Fengchao
