### ISSUE TITLE
Don't bundle the Python zip files

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#1940]
There are both `python` and `python.zip` in the `python_Linux` and `python_Windows` folders. Maybe don't need to bundle the zip files.

Thanks,

Fengchao

**Comment by guoci** [comment]
I do not see any duplication there. Only two items there `python_packages` and `python.zip`.
https://github.com/Nesvilab/FragPipe/tree/a61270461c58819c9dd6aba01851799304445956/MSFragger-GUI/tools/python_Windows
https://github.com/Nesvilab/FragPipe/tree/a61270461c58819c9dd6aba01851799304445956/MSFragger-GUI/tools/python_Linux

**Comment by fcyu** [comment]
The following two are duplicated.

![image](https://github.com/user-attachments/assets/7e1bf8d0-c9cd-4e76-b6b7-4543be20caff)

**Comment by guoci** [comment]
Do you mean in the unzipped FragPipe?

**Comment by fcyu** [comment]
Same as the zipped 
![image](https://github.com/user-attachments/assets/68debc21-b96f-4aee-9f11-571f7a1ddb49)

**Comment by guoci** [comment]
Got it, I am not getting it here, so probably, some OS differences.
![image](https://github.com/user-attachments/assets/57bafd0c-af16-428c-936c-97f8d31988e1)
