### ISSUE TITLE
How MSFRagger differentiate between DIA/DDA files? 

### ISSUE THREAD

**Issue by yonist** [Nesvilab/FragPipe#1943]
We are building an analytical pipeline that utilize MSFragger. We would like to use the same method that differentiate between DIA/DDA that MSFragger is using. Do you base it solely on the "Isolation window" property? or do you use something else?

If this is propriety can you give an option to identity the file type?  

Thanks

**Comment by fcyu** [comment]
There is a `data_type` parameter that switch mode in MSFragger. In FragPipe, there is a "data type" column in the "workflow" tab.

Best,

Fengchao

**Comment by yonist** [comment]
I was under the impression that MSFragger can auto detect the type, doesn't it?

**Comment by fcyu** [comment]
Detecting the data type is tricky. FragPipe will "guess" the data type by looking at the file and folder names. 

Best,

Fengchao
