### ISSUE TITLE
IonQuant: java.lang.NullPointerException

### ISSUE THREAD

**Issue by kenlzh1996** [Nesvilab/FragPipe#1945]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-12-15_01-02-24.txt.zip](https://github.com/user-attachments/files/18157135/log_2024-12-15_01-02-24.txt.zip)

**- Describe the issue or question:**
Hello,
Thank you for developing this amazing pipeline! I am attempting to perform an iTRAQ4 DDA search. The raw files were converted to mzML suggested by your tutorial, and there were 37 experiment sets each containing 25 fractions. I am confused by the error in IonQuant- _java.lang.NullPointerException: Cannot read the array length because the return value of "java.util.Map.get(Object)" is null_. It seems these files passed the validation processes and I am not sure which array it is referring to. I attached the log and I appreciate your time to point out what could be the issues. If you need more information, please let me know. Thank you!

Best regards,
Zhuoheng

**Comment by fcyu** [comment]
Thank you for the reporting. There is a typo that caused the exception. The fix will be available in the next release. If you want to try the pre-released version, please send an email to `yufeATumich.edu` (replace `AT` with `@`).

Best,

Fengchao

**Comment by kenlzh1996** [comment]
Hi Fengchao,
Thank you for your quick response! I will send you an email to try the pre-released version. Now I am curious that if this issue is specific for iTRAQ4 run, because when I performed other two TMT10plex DDA searches, I did not encounter this error. 

Best regards,
Zhuoheng
