### ISSUE TITLE
crashed with more LFQ files

### ISSUE THREAD

**Issue by zoe1985** [Nesvilab/FragPipe#1946]
**- Upl
[log_2024-12-17_09-47-08.txt](https://github.com/user-attachments/files/18159115/log_2024-12-17_09-47-08.txt)
oad your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Dear fengchao,

During I try the pre-released version，althoug only two of orbi480 LFQ files run fine，more is still crashed as attachment.
It seems similar problem about memory?  If so, I think I shoud update my CPU...

Thanks

Rui

**Comment by fcyu** [comment]
The error message is different this time 

```shell
2024-12-17 09:44:07 [ERROR] - There were errors creating tables in F:\labelingAPEX20241214\hct\.: java.util.concurrent.ExecutionException: umich.ms.fileio.exceptions.FileParsingException: Error while parsing Thermo RAW file index
Process 'IonQuant' finished, exit code: 1
```

Something was wrong when reading your raw files. Please double check your file system, including `F:\labelingAPEX20241214\hct\.`.

Best,

Fengchao

**Comment by zoe1985** [comment]
I think you're right, after convert raw files into mzml, everything runs fine.

Thanks, fengchao!

Sincerely
Rui
