### ISSUE TITLE
Fragpipe decoys

### ISSUE THREAD

**Issue by ds2268** [Nesvilab/FragPipe#1947]
Hey!

Fragpipe (optionally) generates decoys with Philosopher.

Does it first perform in-silico digestion with the provided enzyme and then reverses the sequence, except for the last K/R with tryptic digestion, which is similar/the same as Comet's?

https://comet-ms.sourceforge.net/parameters/parameters_201302/decoy_search.php

**Comment by fcyu** [comment]
Philosopher reverses the whole protein sequence.

Best,

Fengchao
