### ISSUE TITLE
TMT18 workflow for immunopeptidomics

### ISSUE THREAD

**Issue by NikolaMonteverde** [Nesvilab/FragPipe#1948]
**- Describe the feature:**
Hi, is it possible to have a fragpipe v22 protocol for TMT18 for immunipeptidomics? Ideally DDA+ compatible. Regards,

Nicolas

**Comment by fcyu** [comment]
TMT 18 for immunipeptidomics is easy, you just need to make the following changes in the "MSFragger" tab

1. "cleavage" to "nonspecific"
2. "peptide length" to 7 - 25
3. Uncheck 57+C fixed modification 
4. Add the following variable modification if you want
![image](https://github.com/user-attachments/assets/9f0848f4-df0f-4af4-a98d-ac78edd87f19)


I don't think doing DDA+ for TMT data is a good idea. Check our discussion in the manuscript: https://www.biorxiv.org/content/10.1101/2024.10.12.618041v1.full#:~:text=Finally%2C%20not%20all%20DDA%2Dbased%20workflow%2C%20most%20notably%20quantitative%20workflows%20based%20on%20isobaric%20labeling%20such%20as%20tandem%20mass%20tag%20(TMT)%2C%20would%20benefit%20from%20an%20increase%20in%20the%20number%20of%20peptide%20identifications%20afforded%20by%20MSFragger%2DDDA%2B.

Best,

Fengchao

**Comment by anesvi** [comment]
Actually we already have a nonspecific-TmT10 workflow. So I would use that as a template and change the modification mass and to TMT18 mass in MSFragger than and change to tmt-18 in TMT -integrator tab.

As Fengchao said, I don't think DDA+ will help for nonspecific search
