### ISSUE TITLE
Unnormalized Data

### ISSUE THREAD

**Issue by aDenos24** [Nesvilab/FragPipe#1953]
**- Describe the feature:**
It would be nice if on the combined.proteins files, the raw intensities were available. This being so you can perform your own normalization if necessary. As far as I understand, you can maybe access that information in each individual sample folder, but for large sample groups this is not desirable.

**Comment by fcyu** [comment]
You could run the data with and without normalization if you want.

Best,

Fengchao

**Comment by aDenos24** [comment]
Is this handled by unchecking 'Normalize Intensity across runs'. This will make the combined_proteins file not have normalized intensities?

**Comment by fcyu** [comment]
Correct.

Best,

Fengchao

**Comment by aDenos24** [comment]
Thank you!
