### ISSUE TITLE
Adding decoys and contaminants from the commandline?

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1955]
Hi all,

I am running Fragpipe on ~140 samples for which we've created custom proteome fasta files for. I am wondering if there is a way to add decoys and contaminants to each of the files from the command line vs opening each one in the Fragpipe GUI?

Thanks,
Asher

**Comment by fcyu** [comment]
Yes, FragPipe runs Philosopher database command to add the decoys and contaminants https://github.com/Nesvilab/philosopher/wiki/Database

```shell
philosopher workspcse --init --nocheck
philosopher database --custom<path to fasta file> --contam --contamprefix
philosopher workspace --clean --nocheck
```

Best,

Fengchao

**Comment by apsteinberg** [comment]
Hi Fengchao,

Just tested it out and it works great, thank you! Saves me a huge amount of time.

Best,
Asher

**Comment by fcyu** [comment]
You are welcome. Let me know if there are any other questions in the future.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Hi Fengchao,

Sorry I am now realizing that when I go to run Fragpipe on the fasta file I'm getting this message:
```
2024-12-20 16:33:00,331 ERROR - Error saving ui cache. It won't affect the results.
2024-12-20 16:33:00,332 ERROR - Error saving runtime cache. It won't affect the results.
2024-12-20 16:33:00,363 ERROR - FASTA file contains 19.2% decoys.
```
And then Fragpipe stops. However, when I open the fasta file in the GUI it says that the file is 50% decoys. This is the command I used to generate the decoys:

```
sif_path=/data1/shahs3/users/preskaa/singularity/fragpipe_22.0.sif
philosopher=/fragpipe_bin/fragPipe-22.0/fragpipe/tools/Philosopher/philosopher-v5.1.1
proteome=/data1/kentsisa/AML_proteogenomics/Proj_B-101-985/F1/experiment/combined.proteome.unique.fasta

singularity exec -e -B /data1/shahs3:/data1/shahs3 \
  -B /data1/kentsisa:/data1/kentsisa ${sif_path} bash -c "
  ${philosopher} workspace --init --nocheck &&
  ${philosopher} database --custom ${proteome} --contam --contamprefix &&
  ${philosopher} workspace --clean --nocheck
"
```

**Comment by apsteinberg** [comment]
Actually, I realized it was an issue with the header formatting in my files -- I reformatted and it works. Thanks again!

Asher
