### ISSUE TITLE
WWA workflow - MSFragger: .pin is empty. Will not process this file. (SCIEX 7600)

### ISSUE THREAD

**Issue by rtool1** [Nesvilab/FragPipe#1956]
**- Upload your log file**
Please find attached zipped:
1. Log file
2. Fragpipe DDA plus params
3. Fragpipe workflow
[log_2024-12-22_11-29-33.zip](https://github.com/user-attachments/files/18222594/log_2024-12-22_11-29-33.zip)

Please also find attached a mzML file from 80 scans as a sampling of the acquired SCIEX DDA/IDA data, with an Q1 isolation set at "Open".
[100min_WWDA-1ug_100min.zip](https://github.com/user-attachments/files/18222592/100min_WWDA-1ug_100min.zip)

**- Describe the issue or question:**
Dear Fragpipe team,
I'm either to check out your WWA (WWDDA) workflow after reading your PrePrint on MS-Fragger-DDA+.
However, I suspect MSFragger doesn't recognize my SCIEX 7600 files.

Here are the steps I have taken:
1) Generated DDA files (which SCIEX calls IDA files); instead of the usual "Unit" resolution isolation, I selected "Open" Q1 isolation.  SCIEX tech support has told me "Open" corresponds to about 5-6 Th isolation width (vs. 0.7 Th for Unit isolation). Sample injected on column was 1ug of the Pierce HeLa digest.
2) Converted the SCIEX wiff2 files into mzML files.
3) Loaded Fragpipe v22.0
4) Loaded "WWA" workflow
5) Populated the mzML files, selecting "DDA+" in the Data Type column.
6) Left the MSFragger tab alone; also left the other tabs alone, except specifying the output directory under the Run tab.

However, based on the log file, MSBooster was not able to run
2024-12-22 11:29:24 [INFO] - C:\Data_Folder\Fragpipe_Output\20241222_HeLa_WWA_runs\1\100min_WWDA-1ug_100min.pin is empty. Will not process this file
....
2024-12-22 11:29:33 [INFO] - No fragmentation type detected. Setting fragmentation type to HCD. You can specify this with '--FragmentationType' via the command line or 'FragmentationType=' in the param [file.]
2024-12-22 11:29:33 [INFO] - No NCE detected. Setting NCE to 25. You can specify this with '--NCE' via the command line or 'NCE=' in the param file.
2024-12-22 11:29:33 [INFO] - No pin files to process. Continuing without MSBooster.

Based on your comment from [Issue 1399]((https://github.com/Nesvilab/FragPipe/issues/1399#issuecomment-1885023587)), is it possible MSFragger cannot figure out what my isolation is?  I am not familiar with other instruments, but I do not have the option to type in a numerical value when defining the isolation window.
I've noticed that, even with the WWA workflow loaded, the MSFragger parameters look like the ones loaded for LFQ-MBR workflow.

Do you have any advice on adapting the WWA for use with SCIEX 7600 DDA (IDA) files with an "Open" Q1 isolation setting, even if necessary by command line and/or manually editing parameters files?  Thank you.

**Comment by fcyu** [comment]
Thanks for testing our DDA+ mode and the WWA workflow. Although we never tested it on the SCIEX data, but I am happy to help and troubleshoot. 

Your log file shows that MSFragger couldn't parse the isolation window info: 

C:\Data_Folder\MSConvert_Output\HeLa_DDA\100min_WWDA-1ug_100min_(2).mzML: Scans = 135986; ITMS: false; FTMS: false; **Isolation sizes = []**


And then, results in no IDs in the DDA+ mode

100min_WWDA-1ug_100min.mzBIN_calibrated 2.5 s
	[progress: 133902/133902 (100%) - 48568 spectra/s] 2.8s
	Building spectral index for 100min_WWDA-1ug_100min.mzBIN_calibrated 2.0 s
	**Tracing MS1 0.0 s
	Rescoring 0.0 s
	Writing results 0.0 s**


> Please also find attached a mzML file from 80 scans as a sampling of the acquired SCIEX DDA/IDA data, with an Q1 isolation set at "Open".
[100min_WWDA-1ug_100min.zip](https://github.com/user-attachments/files/18222592/100min_WWDA-1ug_100min.zip)

There are no spectra in the data you shared. Could you share it again?

Thanks,

Fengchao

**Comment by rtool1** [comment]
Hi Fengchao,

My apologies for the blank files.
Please find attached a different mzML file with about 20 seconds' worth of DDA/IDA scans with "Open" Q1 isolation; there should be some MS1 and MS2 scans mixed in.
[100min_WWDA-1ug_100min (2).zip](https://github.com/user-attachments/files/18228152/100min_WWDA-1ug_100min.2.zip)
For comparison, please find attached a comparable 20 seconds' worth of DDA/IDA scans with the (default) "Unit" Q1 isolation; these conventional DDA/IDA files work file with your "LFQ-MBR" workflow.
[100min_DDA-1ug_100min.zip](https://github.com/user-attachments/files/18228167/100min_DDA-1ug_100min.zip)

Thanks very much for looking into this.
-Eric

**Comment by fcyu** [comment]
Hi Eric,

Thanks for sharing the file. There are no isolation window boundary information in the file. See the following example
```xml
<precursorList count="1">
  <precursor>
    <isolationWindow>
      <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="304.162174484842" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
    </isolationWindow>
    <selectedIonList count="1">
      <selectedIon>
        <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="304.162174484842" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
        <cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="2"/>
      </selectedIon>
    </selectedIonList>
    <activation>
      <cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" value=""/>
      <cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="17.208108724242" unitCvRef="UO" unitAccession="UO:0000266" unitName="electronvolt"/>
    </activation>
  </precursor>
</precursorList>
```

Best,

Fengchao

**Comment by rtool1** [comment]
Hi Fengchao,
Thanks for following up.

Since unlike Thermo (the only other acquisition software I'm familiar with), SCIEX OS doesn't allow us to specify an Isolation Window, it seems like for now, I will have to let MSFragger understand what my upper and lower limits are?  I can confirm that even when opening up the original SCIEX wiff2 files, the Proteowizard SeeMS software shows the same value for target and for Isolation Window.

I will try to play around with my mzML files and see if I can work in the isolation window information.

One last question for now: could you advice if MSFragger is looking for the values for "isolation window lower offset" and "isolation window upper offset" in the mzML scan header?  I'm using a Thermo-derived mzML file as my reference.
[https://github.com/ProteoWizard/pwiz/issues/1783#issuecomment-933850352]

Best,
-Eric

**Comment by fcyu** [comment]
> One last question for now: could you advice if MSFragger is looking for the values for "isolation window lower offset" and "isolation window upper offset" in the mzML scan header? I'm using a Thermo-derived mzML file as my reference.

That's correct. More specifically, they are `MS:1000828` and `MS:1000829` in the `isolationWindow` tag of the `precursor` tag.

Best,

Fengchao

**Comment by rtool1** [comment]
Hi Fengchao, thanks for calling out those two tags.
I've managed to manually insert the isolation window lower and upper offsets (+/- 2.5 Th):
[insert_isolation_window.txt](https://github.com/user-attachments/files/18333464/insert_isolation_window.txt)

Injecting the same (1ug HeLa digest on-column), I got ~1600 proteins with 0.7 Th isolation + Fragpipe's Default/DDA workflow vs. ~1800 proteins with ~5.0 Th Isolation + Fragpipe's WWA workflow.  That is in line with expectation with a WWA workflow.

Since I'm not truly certain what the isolation window on my SCIEX 7600 instrument is, is there a way to find out, for a given PSM, what the original value in "MS:1000827" "isolation window target m/z" was?

The only way I can think of is to look at the ion.tsv in each individual experiment, then compare the "M/Z" value in the tsv file against the value from MS:1000827 in the mzML file, one at a time.

I understand this doesn't add any new functionality to Fragpipe, but any pointers would help the (few) SCIEX ZenoTOF folks who are trying out the WWA workflow.  Thanks for your advice.

**Comment by rtool1** [comment]
Thanks for your quick responses, Alexei and Fengchao.
I'll experiment more and see what the ideal lower & upper offsets should be for the "Open" isolation setting on the 7600.

I've noticed the same communication issues with SCIEX; I'll submit a feature request, as well as making more noise at SCIEX events.
