### ISSUE TITLE
Fragpipe crashes with .raw files on linux system

### ISSUE THREAD

**Issue by apsteinberg** [Nesvilab/FragPipe#1957]
Hi all,

I am encountering an issue using Fragpipe on a linux-based HPC with .raw files. I am wondering if it has to do with the Mono package? I am attaching logs, workflow and manifest, and slurm submission script for a run I did using the latest docker image which I am not sure if it includes Mono, but I also tried using a conda environment that had the Mono package and I encountered a similar error:

[241223_github_issue.zip](https://github.com/user-attachments/files/18233013/241223_github_issue.zip)

Thanks for your time and help.

Best,
Asher

**Comment by fcyu** [comment]
Could you run `mono /data1/kentsisa/fragpipe_ondemand/fragpipe_config_tools/MSFragger-4.1/ext/thermo/BatmassIoThermoServer.exe` and share the screenshot?

Thanks,

Fengchao

**Comment by apsteinberg** [comment]
Hi Fengchao,

Thanks for the quick reply. Here's the result from the cluster and then from within the container (I assume you wanted the latter?):

<img width="1054" alt="Screenshot 2024-12-23 at 3 33 57 PM" src="https://github.com/user-attachments/assets/70222677-e04b-49e4-a438-831df4cd9789" />

**Comment by fcyu** [comment]
Is MSFragger also running in that singularity container?

Thanks,

Fengchao

**Comment by apsteinberg** [comment]
Ah no it's not. this is a great point -- I think it's running out of a
locally installed version. Should I try to install msfragger into the
docker image and re-run?

**Comment by fcyu** [comment]
Yes, please. Or, you might also install mono in the host.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Hi Fengchao,

I installed msfragger into the container because I don't think I have the right permissions to install it on the host. I am still however getting the same error. I've attached the log, nothing changed in the submission script except that I pointed fragpipe to the version of msfragger installed in the container:

[slurm10852828_fragpipe.txt](https://github.com/user-attachments/files/18235428/slurm10852828_fragpipe.txt)

I realized though that I think that the issue was that I am using a symlink for the .raw file in the manifest in an attempt to re-direct the .mzML file fragpipe creates to another directory. Does this workflow not work with symlinks? I'm using the DIA_SpecLib_Quant workflow. Previously I did this with the diaPASEF_SpecLib_Quant workflow and it worked fine with symlinks as input files. The reason I'm doing this is because I would like to run Fragpipe in parallel jobs on the same input file.

I guess another option could be is I could copy over the .raw file to a new location for each job. Thanks again for your time and help.

Best,
Asher

**Comment by fcyu** [comment]
> I realized though that I think that the issue was that I am using a symlink for the .raw file in the manifest in an attempt to re-direct the .mzML file fragpipe creates to another directory. Does this workflow not work with symlinks? 

According to my tests, Thermo's raw file reader doesn't support symlink. Symlink of mzML files work well in FragPipe (I have used it many times).

Best,

Fengchao

**Comment by apsteinberg** [comment]
Got it okay thanks again for the quick reply. So it sounds like the best solution would just be to copy over the files to a new directory if I want to have multiple Fragpipe runs going at once on the same .raw file?

Best,
Asher

**Comment by fcyu** [comment]
That's correct.

Best,

Fengchao

**Comment by apsteinberg** [comment]
Great, thanks again for your time and help. Greatly appreciated. :)

Best,
Asher
