### ISSUE TITLE
IonQuant error when trying to access bruker folder

### ISSUE THREAD

**Issue by roberthardt** [Nesvilab/FragPipe#198]
**Describe the bug**
While processing Orbitrap (Lumos) data in a closed search with MSFragger trough FragPipe the following error occured during label-free quantification:

Fehler: Hauptklasse Files\MSFragger-3.0\ext\bruker konnte nicht gefunden oder geladen werden
Process 'IonQuant' finished, exit code: 1

Its German basically saying: major class Files\MSFragger-3.0\ext\bruker could not be found or loaded.

I suspect it might have something to do with the file path, but there are no spaces in it:
![grafik](https://user-images.githubusercontent.com/24385067/85420047-0819da80-b573-11ea-883b-7e2e51d53e1b.png)

----------------------
## If you're submitting a bug report, please attach log file
[log_2020-06-23_16-50-23.txt](https://github.com/Nesvilab/FragPipe/files/4820187/log_2020-06-23_16-50-23.txt)

**Comment by fcyu** [comment]
Hi,

According to your log, IonQuant tried to file the library from `C:\Program Files\MSFragger-3.0\ext\bruker`, but your screenshot shows that it was in `C:\MSFragger-3.0\ext\bruker`. Did you move it later? Also, can you put all those tools, including the library, in a folder other than system folders?

Best,

Fengchao

**Comment by roberthardt** [comment]
Yeah your right I moved it later, because I was suspecting it to been caused by spaces in the file path. Afterwards I changed the path of MSFragger within Fragpipe, but obviously this only takes effect after restarting the software. I did this now and it is running trough smoothely. 

Thanks
