### ISSUE TITLE
RefSeq Download/Usage

### ISSUE THREAD

**Issue by neely** [Nesvilab/FragPipe#202]
It would be great to be able to download a RefSeq assembly within FragPipe, with automagical addition of decoys and cRAP.

The current FragPipe (specifically Philosopher within) seems to work seamlessly with UniProtKB and the main model species. It would be great to add in the ever growing list of RefSeq releases, maybe via taxon ID and NCBI API (see below via datasets). Another benefit of using taxon ID for download is to generate higher level (and larger) databases at family/order/etc levels. Although I haven't tried it, it seems the Philosopher side of things can take the NCBI fasta format, but this requires me to download, manually add in decoys (with appropriate pre-fix) and contaminants (again, assume with appropriate header), then add to FragPipe.

Alternatives: this is all possible manually, but it might make FragPipe more broadly applicable to use both UniProt and RefSeq sources. I am not as familiar with their API, but Ensembl is also an excellent and growing source of fasta.

Given a taxon ID, it should be possible to retrieve the protein fasta from the "representative" RefSeq release. I am not sure how FragPipe currently adds in the cRAP (ex. whether you use the full cRAP for every species), but having decoys and cRAP added within FragPipe would be great.
https://www.ncbi.nlm.nih.gov/datasets/

Finally, I want to say this is an amazing resource and thank you for continued development.

**Comment by anesvi** [comment]
Thank you so much for your comments!

Everything is compatible with RefSeq once you have the database.

Felipe would need to make that functionality in philosopher to download RefSeq database automatically. Felipe, is that something that we can add in the future?

Best
Alexey

**Comment by prvst** [comment]
So far I have no intention of adding support for downloading sequences from NCBI. Unfortunately, NCBI never had a friendly API, or something that we could easily use to quickly get a reference proteome, for example. They have developed their own set of [tools](https://www.ncbi.nlm.nih.gov/books/NBK25499/) that you can use to fetch sequences, which are not that popular for being too complicated and slow. The current API does allow programmatic access to their databases, but it takes a lot of time to fetch the sequences (it took me 5 minutes to fetch the reference human proteome). The dataset resource that you pointed out is quite interesting, but the API does not seem to have methods to download a set of proteins from a reference proteome.

**Comment by anesvi** [comment]
Perhaps we can add a tutorial specifically for manual RefSeq download + adding decoys and contaminants with philosopher. We already have something on the website, maybe just add additional instructions for RefSeq download.

**Comment by neely** [comment]
Thank you both for the consideration. I really only suggested this since Alexey asked for feature requests.

Since NCBI recently (or maybe "currently in progress" is a better term) revamped their API (linked above and [here](https://api.ncbi.nlm.nih.gov/datasets/v1alpha/)), I wasn't sure if this was a functionality to add. I only ask since UniProt is very inconsistent about what species they update and how frequently, meaning that beyond the big model organisms, the best database likely isn't on UniProt.

I used an older mascot decoy perl script to mod a RefSeq fasta before using in FragPipe.

Again, thank you for your help and continued efforts.

**Comment by prvst** [comment]
I totally agree with you. UniProt has a different rationale behind their updates and on the way, they maintain the organisms up to date.

If you have a database already downloaded, you can use Philosopher to build a target-decoy version of it. Check the examples we have [here](https://github.com/Nesvilab/philosopher/wiki/Database) with the `--custom` flag.

**Comment by anesvi** [comment]
Thanks for the feedback. Note that even now you can add decoys and contaminants, but you have to run philosopher command line. So the manual steps are 1) download RefSeq and 2) add decoys and contaminants using philosopher run command line. Since Felipe thinks it would be hard to automate RefSeq download,  what we at least can do is to enable addition of decoys and contaminants in FragPipe (using GUI, instead of running command line philosopher) to a manually downloaded database.
Alexey
PS. And yes,  thanks for the suggestions. While we cannot always implement them, we love to hear from people what they would like to see in our tools!
