### ISSUE TITLE
Failed search using DIA-Umpire

### ISSUE THREAD

**Issue by csang66** [Nesvilab/FragPipe#203]
Hi,

I'm trying to do a DIA-Umpire search using Fragpipe (V13.0). Not sure what happened but runs kept stopping. I've got data from spectronaut so quite sure there is no fault with the raw files. Have already converted them to mzxml format.

Would appreciate if you can advise what I can do or fix my method..

Thanks! 

[log_2020-07-10_16-39-04.txt](https://github.com/Nesvilab/FragPipe/files/4901444/log_2020-07-10_16-39-04.txt)

**Comment by guoci** [comment]
Please try the following fix:
https://drive.google.com/file/d/1YhIo-wxLP232txhqWA-Cmpg4kckIDf8m/view?usp=sharing

**Comment by csang66** [comment]
Thanks! The new version of FragPipe works.
