### ISSUE TITLE
Condition and replicate annotation

### ISSUE THREAD

**Issue by daniswan** [Nesvilab/FragPipe#204]
For large experiments using the GUI for annotating conditions and replicates is tedious.  It would be great to offer the ability to upload that information via text file.  For example, in MaxQuant you load your MS filles, and then there is a function where you click a button and it will write a template file for you with all of your MS file names, and then you can use a text editor to fill in condition and replicate information, and then import that file.  This is also nice for record keeping of how files were annotated.

**Comment by anesvi** [comment]
This is a good suggestion, thank you
Alexey

**Comment by fcyu** [comment]
Hi @daniswan ,

The released [FragPipe-14.0](https://github.com/Nesvilab/FragPipe/releases/latest) has this function.

Please feel free to let us know if there is any further questions.

Best,

Fengchao
