### ISSUE TITLE
Setting PSM score probability on fragpipe linux version

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/FragPipe#205]
I would like to identify the PSMs which are assigned and unassigned from my data. The data I have is close to 250 raw files and because of this I use Linux version of fragpipe to do my analysis. Is there a way in which I can set the probability score within the linux version of fragpipe?

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Sorry, I am not sure about the meaning of "setting PSM score probability", but if you want to set a min probability threshold, you can add `--minprob x` to the PeptideProphet's `Cmd line opts`.

Best,

Fengchao

**Comment by javanOkendo** [comment]
this may look spammy; so when I set minimum probability to 0.05 whle the results having > 0.05 be reported? I am keen to know the identities of the PSMs have a probaility > 0.05

**Comment by fcyu** [comment]
Yes. If what you want is knowing the probability of the PSMs passing the FDR threshold, they are listed in the `PeptideProphet Probability` column of the `psm.tsv` file.

**Comment by javanOkendo** [comment]
Another one last question: 
If I get you correctly then it mean that `protein.tsv' only contains the proteins which <= 0.05 PSM probability? Is my interpration right?

**Comment by fcyu** [comment]
No. `protein.tsv` and `peptide.tsv` are from the PSMs in the `psm.tsv`, and most of the PSMs in `psm.tsv` have probability > 0.05.

**Comment by javanOkendo** [comment]
So will I be wrong to say that the PSMs having probability > 0.05 are unassigned and the ones having prob <= 0.05 are assigned? The reason I want to understand this is because my project is about understanding the contents of these PSMs with the prob > 0.05

**Comment by fcyu** [comment]
No. if "assigned" means "identified", most identified PSMs have > 0.05 probability. I guess you may be confused by the difference of probability and FDR.

**Comment by javanOkendo** [comment]
if "assigned" means "identified" this is correct. If I get you correctly then it means prob <= 0.05 is unassigned and prob > 0.05 is assigned.......this now makes sense. I will filter my data using this creteria and thanks for having sometime to discuss this. Am a student at the University of Cape Town South Africa. I am a new bae in proteomics

**Comment by fcyu** [comment]
If a PSM is assigned or not is decided by its FDR, which is estimated using probability, most of the time. So, 0.05 prob is not a threshold to separate assigned from unassigned. Also, all the PSMs in the `psm.tsv` are assigned.
