### ISSUE TITLE
Linux version not running on HPC

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/FragPipe#207]
I am trying to run this fragpipe in hpc and I seems not to be getting the linux scripts in the `bin directory`. Where can I get the latest linux version of fragpipe which runs `PTM_prophet`?

**Comment by fcyu** [comment]
FragPipe is the same one. It cross-platform. 

And there is no PTMProphet in FragPipe.

**Comment by anesvi** [comment]
Hopefully in the next release…
