### ISSUE TITLE
Computer freezes

### ISSUE THREAD

**Issue by daniswan** [Nesvilab/FragPipe#208]
I am trying to search a set of 56 timsTOF files, closed search, with LFQ.  I have tried to search several times and it consistently freezes/crashes my computer.  It is a 128GB RAM computer with over 1 TB of free hard drive space.  It seems to make it through the search, as I see the filter.txt files for individual runs, but not the overall filter.txt or the MSstats input file.  Any suggestions as to how to troubleshoot?

**Comment by fcyu** [comment]
Can you share the log with us?

**Comment by daniswan** [comment]
It doesn't seem to have generated one unfortunately.  Maybe I will try to search without the LFQ function and see if it will finish?

**Comment by fcyu** [comment]
That is weird. You should be able to find a file with the name like `log_2020-07-03_10-57-43.txt` if you were using FragPipe. If not, could you copy the text in the `Console` of the `Run` tab?

Thanks,

Fengchao

**Comment by daniswan** [comment]
I was able to solve the issue by setting my computers max CPU usage to
90%.  I think this is likely a problem specific to my system.

-Danielle
