### ISSUE TITLE
Error: Could not find or load main class Files\MSFragger-3.0\ext\bruker

### ISSUE THREAD

**Issue by Pierref29** [Nesvilab/FragPipe#209]
**Describe the bug**
Running files from Thermo Eclipse, program stop at Error: Could not find or load main class Files\MSFragger-3.0\ext\bruker

Thanks for your help
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:
[log_2020-07-16_17-47-22.txt](https://github.com/Nesvilab/FragPipe/files/4930168/log_2020-07-16_17-47-22.txt)

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Could you delete all those spaces in your folder names and try again?

Thanks,

Fengchao
