### ISSUE TITLE
About spectra library buliding 

### ISSUE THREAD

**Issue by Clovernana** [Nesvilab/FragPipe#212]
Hi,
I am going to build a spectra library with MSFragger and I have already checked the  'Generate spectral library from search results' option in the report tab of FragPipe. But this did not produce a spectral library in .tsv format and no  file name like con_lib.tsv or something like that.Here is the whole ouput.

![image](https://user-images.githubusercontent.com/50875585/88396188-c63fb680-cdf4-11ea-8cf2-d221e25ed746.png)

And I just follow the instructions [https://msfragger.nesvilab.org/tutorial_fragpipe.html#configure-fragpipe](url)
(for library free and no fancy PTM)
And here is the "export log" file
[log_2020-07-24_21-30-53.txt](https://github.com/Nesvilab/FragPipe/files/4972165/log_2020-07-24_21-30-53.txt)

It's really strange.Could you please help me?

Best wishes!

Clover

**Comment by fcyu** [comment]
Hi Clover,

Can you delete the spaces in your folder names and try again?

Thanks,

Fengchao

**Comment by Clovernana** [comment]
Hi，
But there‘s no spaces in my folder names.I am sure.

**Comment by fcyu** [comment]
What about this one: `D:\installation package\FragPipe-13.0\fragpipe\....`?
