### ISSUE TITLE
Not enough memory allocated to MSFragger.

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/FragPipe#215]
I am running fragpipe on metaproteomic database and I ge the following error. I have tried to split the database into different chunks but it still does not work. Could you advise on how to overcome this problem? I am running the linux version of fragpipe on HPC.

Not enough memory allocated to MSFragger.
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Spli
t database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase t
he “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the r
ange of allowed peptide length (from 7-50 to e.g. 7-35).
For users running the stand-alone version of MSFragger (i.e. not through FragPipe):  try allocating more memory using the `-Xmx` option.

**Comment by fcyu** [comment]
I think other than splitting the database into more chunks, there is no better way to solve this for now.
