### ISSUE TITLE
Inconsistent Scaling

### ISSUE THREAD

**Issue by xLinkKnight** [Nesvilab/FragPipe#216]
The designated parallelism value under global settings isn't completely adhered to when performing a search.

For example, the limit is ignored when first parsing raw timsTOF data and during the LFQ-IonQuant routine. Its behavior seems to overrule/ignore the setting and utilize complete CPU resources. However, the setting seems to be enforced at other processing steps.

The result is minimal differences of processing time when testing the same dataset with different thread count limits. Two timsTOF files take on average 40 min to search regardless of the parallelism value (16 vs 64 threads).

Log files from the comparison between 16 and 64 threads.
[log_2020-07-31_12-49-45_16thread.txt](https://github.com/Nesvilab/FragPipe/files/5008758/log_2020-07-31_12-49-45_16thread.txt)
[log_2020-07-31_12-02-39_64thread.txt](https://github.com/Nesvilab/FragPipe/files/5008759/log_2020-07-31_12-02-39_64thread.txt)

System:
AMD Threadripper 3990X (64C/128T)
Windows 10 Enterprise (1909, Build 18363.997)

MSFragger v3
Fragpipe v13.0
IonQuant 1.3.6
Python 3.7.4
Java 1.8_242

Please let me know if I've just made a mistake with the configuration or if this is abnormal behavior. Windows seems to view the processor as two nodes or processing groups. Not sure if that has any impact.

**Comment by fcyu** [comment]
When reading timsTOF data, we call Bruker's library, which we cannot control the number of used threads, to reading the raw data. I think that is why you saw "_Its behavior seems to overrule/ignore the setting and utilize complete CPU resources. However, the setting seems to be enforced at other processing steps._".

Also, as you can see from the log, most of the time was spent on loading the timsTOF data, so different threads won't result in big difference in the total run time.

Best,

Fengchao

**Comment by anesvi** [comment]
Just an additional comment, fortunately, the conversion needs to be done only once. If running again, mzBIN files will be found and used, without doing the conversion from .d to mzBIn again.

Alexey

**Comment by xLinkKnight** [comment]
Thanks! I totally forgot about the constraints imposed by the Bruker library.

I guess this can be closed as it's all working as intended.
