### ISSUE TITLE
Error: multiple databases

### ISSUE THREAD

**Issue by Tangpoyang** [Nesvilab/FragPipe#222]
Hi,
I am a new user of MSfragger, and I was trying to do an open search with .mzmL file acquired on the Thermo orbitrap. When I ran the program, I got the following errors. Attached is the log. txt for your reference. Could someone help me out? Thanks so much!

**Error: multiple databases referenced by C:/Users/tpoya/Documents/ytp_6_63_OpenSearch_Output2/interact.pep.xml
Use RefreshParser to update all input files to common database
FATA[22:26:21] Cannot execute program. There was an error with ProteinProphet, please check your parameters and input file**s 

[Error#2_log_2020-08-13_22-29-35.txt](https://github.com/Nesvilab/FragPipe/files/5072748/Error.2_log_2020-08-13_22-29-35.txt)

**Comment by Tangpoyang** [comment]
Problem solved!

**Comment by feng6544** [comment]
May I ask how you solved this problem? I also encountered the same problem.
