### ISSUE TITLE
IonQuant quits with error message

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#225]
Executing FragPipe on a single Bruker .d file results in a protein.tsv file, that contains 3500 IDed proteins, but with Intensity columns filled with 0 values only. Apparently, IonQuant cannot locate or load "Files\MSFragger-20171106\MSFragger-3.0\MSFragger-3.0\ext\bruker" after the philosopher report has been generated. However, the path seems to be correct. 

The corresponding part of the console message is this one here:

Process 'PhilosopherReport' finished, exit code: 0
IonQuant [Work dir: E:\MSFragger_test\results]
C:\Program Files\MSFragger-20171106\FragPipe-jre-13.0\fragpipe\jre\bin\java.exe -Xmx105G -Dlibs.bruker.dir="C:\Program Files\MSFragger-20171106\MSFragger-3.0\MSFragger-3.0\ext\bruker" -Dlibs.thermo.dir="C:\Program Files\MSFragger-20171106\MSFragger-3.0\MSFragger-3.0\ext\thermo" -cp "C:\Program Files\MSFragger-20171106\FragPipe-jre-13.0\fragpipe\tools\ionquant-1.3.6.jar;C:\Program Files\MSFragger-20171106\FragPipe-jre-13.0\fragpipe\tools\batmass-io-1.17.4.jar" ionquant.IonQuant --threads 4 --ionmobility 1 --mbr 0 --proteinquant 1 --requantify 0 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0.5 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 3 --ionfdr 0.01 --proteinfdr 0.01 --peptidefdr 0.01 --normalization 1 --minisotopes 1 --tp 3 --minfreq 0.5 --minions 1 --psm E:\MSFragger_test\results\psm.tsv E:\MSFragger_test\20200518_exp1027_Christina_4_frac1_Slot2-62_1_546.d 20200518_exp1027_Christina_4_frac1_Slot2-62_1_546.pepXML
Fehler: Hauptklasse Files\MSFragger-20171106\MSFragger-3.0\MSFragger-3.0\ext\bruker konnte nicht gefunden oder geladen werden
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stoppingWorkspaceClean [Work dir: E:\MSFragger_test\results]
C:\Program Files\MSFragger-20171106\philosopher.exe workspace --clean --nocheck

**Comment by fcyu** [comment]
Can you move our tools to a place where there is no space in the paths?

**Comment by hcadre** [comment]
Many thanks for your quick reply! I did as you suggested and FragPipe worked like a gem! Now all the intensity values are there. Thank you very much again!
