### ISSUE TITLE
Unable to run .mgf files

### ISSUE THREAD

**Issue by HiteshKore** [Nesvilab/FragPipe#226]
Hi, 

I want to search my proteomic data using MSFragger. I converted the RAW mass-spectrometry files to mgf files using  MSConvert. I was able to successfully run MSFragger on some of the mgf files. However, for several files I got below java error:

Failed in checking Gel_Elite_69_f24.mgf
java.lang.ArrayIndexOutOfBoundsException

Here is my command:

java -Xmx100G -jar MSFragger-3.0.jar Gel_Elite_69_f24.mgf --num_threads 13 --allowed_missed_cleavage 2 --variable_mod_01 15.9949_M --add_C_cysteine 57.021464 --output_format pepXML --output_file_extension xml --database_name 2020-01-08-td-UniProt_and_sORF.FASTA --min_matched_fragments 4 --minimum_ratio 0.05 --min_fragments_modelling 2 --precursor_mass_units 1 --fragment_mass_tolerance 0.05 --fragment_mass_units 0 --precursor_mass_tolerance 10 --isotope_error 0 --num_enzyme_termini 2 --clip_nTerm_M 1 --allow_multiple_variable_mods_on_residue 1 --max_variable_mods_per_mod 3 --max_variable_mods_combinations 1000 --digest_min_length 7 --digest_max_length 25

Could you please help me fix this error?

I greatly appreciate your help.

Thank you 

Kind regards,
Hitesh

**Comment by fcyu** [comment]
Hi Hitesh,

Since MGF format is quite flexible in its header, it is quite difficult to support all flavors well. We suggest you converting your raw file to mzML according to the [tutorial](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md).

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Hitesh,

Can you send us your mgf (Gel_Elite_69_f24.mgf) to us? We would like to figure out the reason of the failure.

Thanks,

Fengchao

**Comment by HiteshKore** [comment]
Hi Fengchao,

Thank you for the quick response.

The mgf file can be downloaded from the link below-

https://drive.google.com/drive/folders/1ZH9kIzsbL3eae3IM_aBq35sOqL6WLbG_?usp=sharing

Please let me know the error. 

I ran the same pipeline by converting raw files to mzML and It's  working fine.

Thank you once again.

Kind regards,
Hitesh

**Comment by fcyu** [comment]
Hi @HiteshKore ,

Thanks, could you please accept my request of downloading your file from your link?

Best,

Fengchao

**Comment by HiteshKore** [comment]
Hi Fengchao,

Please let me know if you are able to download the file.

Thanks,
Hitesh

**Comment by fcyu** [comment]
Hi Hitesh,

Thanks for your file. Looks like it was converted without peak picking, which results in a huge number of peaks, which reaches a limit (at most 8192 peaks) in MGF parsing. If you still want to use MGF format, could you convert your files according to the [tutorial](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md) and change the format from 'mzML' to 'MGF'? At the meantime, I will change the MGF parsing code to make it more robust.

Best,

Fengchao

**Comment by HiteshKore** [comment]
Thank you so much.

Kind regards,
Hitesh
