### ISSUE TITLE
Labile modifications Search mode

### ISSUE THREAD

**Issue by LakminiSenavirathna** [Nesvilab/FragPipe#228]
I am trying to identify glycation modifications ( either in K/R or D/E), but there are no Y Ion masses and Diagnostic Fragment masses.
If I try to run with labile mode in MSFragger, without Y Ion and Diagnostic Fragment masses (those are selected as 0 or none), it gives an error.
("0' can be put to Y ion masses, but the issue is diagnostic fragment masses can not be left "0")

Only way  I can do the run is that , I need to change labile modification mode to "off"

Is there any possibility to develop this software as follows to run without error messages,

 Labile search modification mode is  "labile" with Y Ion masses "0" and  diagnostic fragment masses "None or 0".

**Comment by LakminiSenavirathna** [comment]
Hi Dan,

Thank you for your reply. I tried your suggestion. It ran without error messages. But, in the both situations, 1). labile modification mode "off" and 2). labile modification mode is "labile" with Y Ion masses and Diagnostic Fragment masses are zero, I get the similar results. In labile mode with with zero for Y ion and Diagnostic fragment masses , I set the allowed residues to"KR". I am expecting to have my modifications in K/R, but it gives the modifications in other amino acids as well (like in labile modification "off" mode).

If you have any suggestions, please let me know.

**Comment by dpolasky** [comment]
Yes, that is how it currently works, but this been fixed for next release: modifications will only be localized to the specified residues (in both "labile" and "off" modes). We are planning to release the update soon - thanks for your patience!

**Comment by fcyu** [comment]
Hi @LakminiSenavirathna ,

We just released [FragPipe-14.0](https://github.com/Nesvilab/FragPipe/releases/latest) which should solve your problem.

Please feel free to let us know if there is any further questions.

Best.

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi,

 I am trying to identify glycation modifications in K and R. But, when I tried to switch to labile mode in MSFragger in Fragpipe-14.0, there is no option to select amino acids as in previous release 13.0. In release 13.0, there is a option " allowed residues" to put the amino acids. 

In new release (FragPipe 14.0) is that, under MSFragger--> advanced options--> restric delta masses to ---, where I can put the selected amino acids carrying the glycation modification. 

 Could you please let me know how to solve the problem in this new release. 

Thank you,
Lakmini

**Comment by fcyu** [comment]
Hi Lakmini,

'Restrict delta mass to' is the replacement of the old 'allowed residues'. They are basically the same.

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

OK thank you !

Lakmini

**Comment by LakminiSenavirathna** [comment]
Hi, 

I was trying to use MSFragger for identifying Advanced glycated end products (AGEs) in K and R amino acids. I used previous version 13.0 and used the labile modification search mode. Even though I used labile modification search mode in version 13.0 the AGEs modification appeared on other amino acids residues also. So, recently I installed latest version FragPipe 14.0 and trying to use this version for labile modification search mode. However, now I encountered a problem that the both of these version do not work for my search. During running in both versions it show a error message of insufficient memory. My computer has 8GB RAM. This was not happened earlier when version 13.0 only was installed. It ran smoothly. Do you think, having two versions of FragPipe in my computer could create some issues.

I used following parameters,
1. Workflow:common-mass-offsets
2. MSFragger: Mass Offset search default Config
  protein digestion--> Enzyme: trypsin
    Advanced options--> Mass Offsets--> I included delta M of AGEs. 
  Labile Modifications search mode: labile    Allowed residues: KR
  Open search options--> Report mass shift as variable mode : Yes
4. Validation: Run Peptide Prophet Default for: Offset search
                     Run Protein prophet
                     Filter and report--> Generate report and generate peptide level summary

All the other parameters were kept as default.

 If you have any suggestion, greatly appreciated.

Thank you,
Lakmini

**Comment by fcyu** [comment]
Hi Lakmini,

I don't think your memory issue is due to having both versions. Since you have in total 8GB RAM, it is possible that your available memory (free memory) variable a lot due to the programs running in your computer. You can restart your computer, close all other programs, and try the latest version.

BTW, what is "Labile Modifications search mode: labile Allowed residues: KR"? I think sending us the fragger.params, config files, or log files is more helpful.

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

Thank you for your suggestion. I did restart my computer and tried to run my file in the latest version. But another error comes.

[Files_Lakmini.zip](https://github.com/Nesvilab/FragPipe/files/5731517/Files_Lakmini.zip)

I attached those files in the zip folder.

Please let me know your suggestions.

Thank you,
Lakmini

**Comment by fcyu** [comment]
Hi Lakmini,

I found two issues from your log: 
1. MSFragger cannot find the "ext" folder. After you download the MSFragger-3.1.1.zip and unzipped it, you need to keep the JAR file and the "ext" folder together when you move the files. 
2. Your mzML is corrupted. You need to re-convert your file. Here is a [tutorial](https://msfragger.nesvilab.org/tutorial_convert.html).

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

Thank you !
The JAR file and ext folder seem together if you can see the image attached. OK I will re-convert the mzML file and try again.

Thanks,
Lakmini
![image](https://user-images.githubusercontent.com/70040193/102924066-75d98d00-4456-11eb-8df8-ef15672bad83.png)

**Comment by fcyu** [comment]
Hi Lakmini,

Then, I think that is due to another reason: your computer doesn't have Visual C++ Redistributable for Visual Studio 2017. You can find the way of downloading if from here ([https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html](https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html)):

![image](https://user-images.githubusercontent.com/6926299/102924560-d4573900-445f-11eb-9308-d7298949f1ed.png)

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

I'll download and try it again.

Thank you !
Lakmini

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

I could be able to run MSfragger when I free the memory of my computer. I am looking for glycation modifications in proteins. So I want to look at different glycation modifications occur in lysine (K) and Arginine (R) amino acids. I followed common-mass offsets workflow. So I followed following parameters in my analysis in MS Fragger. (attached screenshots). So I put detaM values of glycation modification in the space given for Mass offsets and then, in open search option I selected "report mass shift as variable mod". 

But, the problem is when I give the exact deltM values in the mass offsets field, the results files show only a few glycation modifications in the K and R amino acids (5-10). But, when I placed the increased  value of deltaM (by one mass addition in each carbon in the modification) it showed acceptable amount of modification (about 90). But this increased deltaM is not the correct deltaM I am looking for the selected glycation medications.

The deltaM values I placed as follows:
exact delta M: 108.0211/ 80.0262/ 54.016/270.0740
increased deltaM: 114.0211/85.0262/57.016/282.0740

I really appreciate if you could clarify or give me any suggestion.

Thank you,
Lakmini

![image](https://user-images.githubusercontent.com/70040193/103931395-db2fae00-50e5-11eb-8045-958b678bfa6b.png)
![image](https://user-images.githubusercontent.com/70040193/103931447-ee427e00-50e5-11eb-8aa4-04b12db012af.png)
![image](https://user-images.githubusercontent.com/70040193/103931506-031f1180-50e6-11eb-9e1b-71764cf0efe9.png)

[log_2021-01-07_12-36-21_exactDeltaM.txt](https://github.com/Nesvilab/FragPipe/files/5783391/log_2021-01-07_12-36-21_exactDeltaM.txt)

[PeptideFiles.zip](https://github.com/Nesvilab/FragPipe/files/5783401/PeptideFiles.zip)
[log_2021-01-04_15-20-11_increasedDeltaM.txt](https://github.com/Nesvilab/FragPipe/files/5783387/log_2021-01-04_15-20-11_increasedDeltaM.txt)

**Comment by fcyu** [comment]
Your diagnostic fragment mass and Y ion masses (0 is fine but not optimal) don't look right to me. I suggest you load the corresponding glyco workflow and change the mass offset based on your data. Here ([https://msfragger.nesvilab.org/tutorial_glyco-fragger.html](https://msfragger.nesvilab.org/tutorial_glyco-fragger.html)) is a tutorial about it.

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Lakmini,
Two of the "increased" masses you mention are very close to the masses of other common modifications (114.0211 is very close to ubiquitination and 57.016 is very close to carbamidomethylation), and I suspect that these are being found rather than the glycations you're interested in, which is why you see more PSMs with delta masses. Are you sure that there are more glycations in your data than you are finding? If so, I would suggest looking at some spectra that you know are modified and confirming whether the MSFragger search does or doesn't find identify them. 
Best,
Dan

**Comment by LakminiSenavirathna** [comment]
Thank you Dan and Fengchao !

Thank you for bringing the points of ubiquitination and spectra which I have to carefully look. 

My problem, that low number of modifications seems solved. 
I re-run my mzML file with all the 9 modifications (actual deltaM) and it came up with what I expected. I got about 70-80 modifications which was I obtained in TPP analysis as well. The problem in TPP is, it took couple of days for a single file to run the search with 9 modifications, while MSfragger does it within minutes. 

Now, I kindly request your help in determining the parameters I used below are suitable for  this type of glycation modification analysis. Because in TPP I put these glycation modifications as variable modifications, but in MSFragger when I put them as variable modifications the run ends with errors. So I put them in the mass offset field and run the common mass offset workflow. 

Could you please go through the following parameters and let me know your thoughts.
I am happy to share my raw/mzML file with you if you think you need it.
Thank you very much.
Lakmini
![image](https://user-images.githubusercontent.com/70040193/104051185-5ad48000-51ad-11eb-95a3-839bc5a25c99.png)
![image](https://user-images.githubusercontent.com/70040193/104051217-6b84f600-51ad-11eb-9516-2a9f780b7428.png)
![image](https://user-images.githubusercontent.com/70040193/104051250-793a7b80-51ad-11eb-98c7-313b9b078896.png)
![image](https://user-images.githubusercontent.com/70040193/104051277-848da700-51ad-11eb-8d50-73d657cb27e0.png)

**Comment by fcyu** [comment]
Since you set `0` for all `Y Ion Masses`, `Diagnostic Ion Minimum Intensity`, and `Diagnostic Fragment Masses`, you basically "disabled" the glyco mode. If you think you don't need these three settings, you can change `Labile Modifications Search mode` to `off` and put `KR-` to `Restrict delta mass to`, which will give you the same result but faster. The `-` in `KR-` tells MSFragger allow labile modifications.

Best,

Fengchao

**Comment by fcyu** [comment]
I think you also should add `0` to the mass offsets.

**Comment by LakminiSenavirathna** [comment]
Thank you Fengchao !

Lakmini

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao and Dan,

Is there a place to look at corresponding peptide prophet probability for 1% FDR. I need to upload interact file generated from MSFragger to skyline and which requires peptide prophet probability.

Thank you !
Lakmini

**Comment by fcyu** [comment]
Yes. There is actually a tutorial ([https://msfragger.nesvilab.org/tutorial_pasef_skyline.html](https://msfragger.nesvilab.org/tutorial_pasef_skyline.html)) about loading files to Skyline, and there is a way to get the probability threshold:

> 1) Specifying the peptide probability threshold that corresponds to 1% ion FDR as the ‘Cut-off score’. (This can be found in the FragPipe log or .log file, a cut-off of 0.9024 would be used in this example: INFO[15:56:25] Converged to 1.00 % FDR with 57143 Ions decoy=576 threshold=0.9024 total=57719)

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Thank you !
Please see the attached. I believe I can choose Converged to 0.99 % FDR with 4526 Ions decoy=45 threshold=0.9896 total=4571 in the below example log file. (0.99% FDR which is almost 1% FDR)
![Capture](https://user-images.githubusercontent.com/70040193/105382537-c834d780-5bd5-11eb-878d-37edd9efbd3d.JPG)

Thanks,
Lakmini

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao

**Comment by anesvi** [comment]
Dear Lakmini,
Looks fine.
Once you are do with your analysis, let us know what you think overall regarding the results. Your suggestions/feedback that would help us to create a tutorial for people interested in similar analyses.
Best
Alexey
