### ISSUE TITLE
Error: Could not find or load main class Files\MSFragger-3.0\ext\thermo

### ISSUE THREAD

**Issue by CKFF** [Nesvilab/FragPipe#231]
**Describe the bug**
Running an open search via fragpipe results in this error:

Error: Could not find or load main class Files\MSFragger-3.0\ext\thermo
Process 'Crystal-C' finished, exit code: 1

A closed search with the same raw files as input works just fine without errors. When I run an open search without Crystal-C the same error occurs at the PTM Shepherd step. I suspect it has something to do with the files in the ext\thermo folder. 

I attached the logfiles and an overview of the files in this folder that causes the error. 

[log_2020-08-27_17-32-56.txt](https://github.com/Nesvilab/FragPipe/files/5137379/log_2020-08-27_17-32-56.txt)
[filename.txt](https://github.com/Nesvilab/FragPipe/files/5137380/filename.txt)

----------------------

**Comment by fcyu** [comment]
Can move your `FragPipe-jre-13.0` folder to a place where there is no space in the name?

Best,

Fengchao

**Comment by CKFF** [comment]
I moved fragpipe, msfragger and philosopher folders into a new directory without spaces in the directory names. Also the raw data has no spaces in the directory names. 
Still, the same error occurs, see the log file attached here

[log_2020-08-27_19-43-27.txt](https://github.com/Nesvilab/FragPipe/files/5137920/log_2020-08-27_19-43-27.txt)

**Comment by fcyu** [comment]
The cache was not been refreshed. Could you click 'Clear Cache and Close' in the 'Config' tab?

Best,

Fengchao
