### ISSUE TITLE
Identifying cysteine modifications in closed search

### ISSUE THREAD

**Issue by hdesai17** [Nesvilab/FragPipe#234]
I've been having issues searching data from isotopically labeled cysteines (heavy and light modifications ~460 and ~470).
I've been setting variable modifications in closed search mode for cysteines (e.g. var_mod = ## C), but the results are only outputting the heavy modified peptides. I have also expanded the upper mass range to 600 instead of 20.
Any way to fix this?

Thanks much

**Comment by fcyu** [comment]
Can you send us your fragger.params and log?

Thanks,

Fengchao

**Comment by hdesai17** [comment]
[log_2020-09-14_12-09-26.txt](https://github.com/Nesvilab/FragPipe/files/5279318/log_2020-09-14_12-09-26.txt)

[fragger.params.zip](https://github.com/Nesvilab/FragPipe/files/5279325/fragger.params.zip)

**Comment by fcyu** [comment]
Thanks for your files. 

First, should you change `add_C_cysteine = 57.021460` to `add_C_cysteine = 0` if your data doesn't not have 57+C as the fixed modification?

Second, the `fragment_mass_tolerance = 600` you changed is for MS2 mass tolerance, but your data looks like from high resolution MS2 (ignore this if I am wrong). Could you double check it?

Best,

Fengchao

**Comment by hdesai17** [comment]
We normally include 57 as a static modification in other searches with heavy and lights masses as variable mods.
The data is from lower res iontrap
Thanks,
Heta

**Comment by fcyu** [comment]
OK, then, your parameters look good if the modifications' masses are correct. I cannot see any reason of missing heavy ones if your data has it.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
What are the masses of your cysteines after labeling?

**Comment by hdesai17** [comment]
464.28595 
470.29976 (only this one is showing up after the search)

after initial labeling with IAA the mass is 137.08352

**Comment by anesvi** [comment]
Can you try with allow_multiple_variable_mods_on_residue = false.

But we may need to get some data if still does not work, can you transfer a file to us

Thanks
Alexey

**Comment by danielgeiszler** [comment]
I know this is already closed, but I think your masses are wrong.

Cysteine + IAA should be 160.03065, not 137.08352.

If the final masses of your labeled cysteines are 464 and 470, you can't do this:

variable_mod_06 = 464.28595 C 1
variable_mod_07 = 470.29976 C 1

These masses are added *on top of* the IAA-labeled Cysteine. It looks like you're putting the expected masses of the residues in, but you need to put the expected masses of the modification in.

If your Cys already has a mass of 160.03065 and you want it to be either 464.28595 or 470.29976, you need to change your modifications to 304.2553 and 310.2691.

**Comment by hdesai17** [comment]
thanks you! I'll try out the other mods and get back to you

**Comment by hdesai17** [comment]
I tried 304.2553 and 310.2691. I also tried 333.21624 and 327.20243 but none of these identified the amount of peptides we'd expect. In other search engines, we use the 137 and the 464/470 masses.

Should I send a file over?

**Comment by hdesai17** [comment]
Hello,

We were wanting to circle back on this. I believe we do need to use ~464
and ~470 numbers as these are the expected modification masses.

We used a different pair tags (with masses in the 400s)  and were able to
find those masses without a problem; only the ~464 mass seems to be
problematic.
Also, is there a way to perform quantitation with these, ratio
calculations?

Shall I send a file over?

Thank you!

**Comment by anesvi** [comment]
Yes, we have a way to do SILAC like ratio in IonQuant
But this may be hard to explain here, perhaps best to contact directly (me, or Fengchao)
