### ISSUE TITLE
LFQ is not working for TIMS TOF PASEF DDA

### ISSUE THREAD

**Issue by 1-stephan** [Nesvilab/FragPipe#236]
**Describe the bug**
I wanted to use FragePipe and MSFragger to perform protein LFQ for Bruker TIMS TOF PASEF DDA data. When I start the pipeline with LFQ Match between runs and MaxLFQ, I get protein identifications but no LFQ values. All columns are zero values.

The pipeline stops ion quant with following error message:

_Error: Could not find or load main class Software\fragpipe\tools\MSFragger-3.0\ext\bruker
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stoppingWorkspaceClean [Work dir: F:\MS_data\Stephan\Output]
C:\MS Software\fragpipe\lib\..\tools\philosopher\philosopher.exe workspace --clean --nocheck_

The folder bruker is exactly at this location. I am not sure if this is a bug or if I have to install additional software. Java and Microsoft Visual C++ are installed.

I hope you can help me setting up fragpipe for TIMS TOF DDA PASEF data.

Thanks for your help,
Stephan
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
[log_2020-09-25_14-44-54.txt](https://github.com/Nesvilab/FragPipe/files/5282885/log_2020-09-25_14-44-54.txt)

- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Could you please move all the tools to a folder without any space in the path? Right now, there is a space in `C:\MS Software\fragpipe...`.

Thanks,

Fengchao

**Comment by 1-stephan** [comment]
Many Thanks for the quick reply. I have renamed the folder in MS_software and restarted the analysis. Ionquant seems to work now. I'll let you know if everything has worked for LFQ.

Best,
Stephan

**Comment by 1-stephan** [comment]
Thanks again Fengchao,
Ionquant has worked now and I got the LFQ intensities in the output table.
Compared to Maxquant, I even got more IDs and Quantifications.

Best,
Stephan

**Comment by fcyu** [comment]
Thanks, and glad to hear that. Please feel free to contact us if you have any further questions.

Best,

Fengchao
