### ISSUE TITLE
FragPipe 14 - unable to load .d files

### ISSUE THREAD

**Issue by stharan** [Nesvilab/FragPipe#238]
**Describe the bug**
I'm unable to add .d files to Fragpipe 14 and MSFragger 3.1.  I had no issues previously using Fragpipe 13.0.

Please see attached screenshots.
![image](https://user-images.githubusercontent.com/40571915/94741971-f9497d80-0342-11eb-811e-66b8ff2dbbb2.png)
![image](https://user-images.githubusercontent.com/40571915/94742042-11b99800-0343-11eb-967b-da66a8426ea0.png)
![image](https://user-images.githubusercontent.com/40571915/94742076-1c742d00-0343-11eb-8655-a58b19916366.png)

----------------------
## If you're submitting a bug report, please attach log file

no log created

**Comment by fcyu** [comment]
Thanks for your feedback. We also found and fixed this issue. Can you download FragPipe 14.0 again? After downloading and unzip, you may need to click 'Clear cache and close'. Then start FragPipe again.

Sorry for the trouble,

Fengchao

**Comment by stharan** [comment]
Worked after 'clear cache and close'!  Thanks again.
