### ISSUE TITLE
Error with SpecLibGen

### ISSUE THREAD

**Issue by melechco** [Nesvilab/FragPipe#239]
Dear friends.
I am trying to generate a spectral library using either SpectraST or EasyPQP but it failed in all attempts. 
For EasyPQP the following error is presented:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/easypqp/data/unimod.xml'
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

Thanks a lot!

[log_2020-10-01_04-36-58.txt](https://github.com/Nesvilab/FragPipe/files/5308718/log_2020-10-01_04-36-58.txt)

**Comment by guoci** [comment]
try reinstalling EasyPQP with:
```
pip uninstall --yes easypqp
pip install git+https://github.com/grosenberger/easypqp.git@master
```

**Comment by melechco** [comment]
Thanks Guoci!
You nailed it.
