### ISSUE TITLE
no calibrated mgf created

### ISSUE THREAD

**Issue by stharan** [Nesvilab/FragPipe#240]
**Describe the bug**
Despite checking off the box for create calibrated mgf (see config file) no mgf is created.

[fragpipe_2020-09-30_21-33-04.config.txt](https://github.com/Nesvilab/FragPipe/files/5311610/fragpipe_2020-09-30_21-33-04.config.txt)
[fragger.params.txt](https://github.com/Nesvilab/FragPipe/files/5311611/fragger.params.txt)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:
[log_2020-09-30_22-19-40.txt](https://github.com/Nesvilab/FragPipe/files/5311607/log_2020-09-30_22-19-40.txt)

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Hi @stharan ,

Thanks for your feedback. That is indeed a bug in MSFragger. We fixed it in version 3.1.1. Could you please download ([https://msfragger.arsci.com/upgrader/](https://msfragger.arsci.com/upgrader/)) and try it?

Best,

Fengchao
