### ISSUE TITLE
About outputs of FragPipe 14 processing phospo-DDA data.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#242]
I have used FragPipe-14 to analyze phospho-DDA data. PTMProphet option is enabled.

I can find the PTMProphet probability of phosphopeptide in psm.tsv file, but there is no PTMProphet probability in ion.tsv or peptide.tsv [file.]

So how can I get the phosphopeptide ion list with PTMProphet probability?

**Comment by prvst** [comment]
@andyzim111 Can you share the log?

**Comment by andyzim111** [comment]
[log_2020-10-01_23-01-00.txt](https://github.com/Nesvilab/FragPipe/files/5318402/log_2020-10-01_23-01-00.txt)
