### ISSUE TITLE
"Cannot Run Program mono"

### ISSUE THREAD

**Issue by hhabra** [Nesvilab/FragPipe#244]
I'm not sure if this error has been covered in the issues, but I tried running Fragpipe with five or six .raw files and almost immediately got this error. I'm not sure how to overcome it.

![image](https://user-images.githubusercontent.com/8129799/95123168-89127180-071f-11eb-9f75-293dd70158b7.png)

The full error log will be attached to my next post.

**Comment by anesvi** [comment]
Hani, please also upgrade to FragPipe 14. Isee you are running v 13
And we still recommend conversion to mzML (except for Bruker data)
Best,
Alexey

**Comment by hhabra** [comment]
@fcyu and @anesvi  Thank you so much for the quick replies. I'm not sure if I missed that instruction somewhere or it's just a lack of linux familiarity on my part.

By the way @anesvi, this fragpipe was assigned for the BIOINF 551 class. Since some of these students don't have Macs, I got them access to a Linux server, which unfortunately has only 6 GB total RAM. Do you think this is sufficient for a simple (relatively restricted) use with 5-6 files? (I can show you the parameters that we expect to run with it through email, if you wish)

**Comment by fcyu** [comment]
Hi @hhabra , 

No, you didn't miss anything. We forgot to add a note regarding installing Mono. I just put it to our tutorial [https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html](https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html).

Best,

Fengchao

**Comment by anesvi** [comment]
FragPipe does not run on mac. Windows or Linux.
I am not sure about 6 GB of RAM. Only basic analyses would work with so little memory I think

**Comment by hhabra** [comment]
@fcyu Ah okay. Having the added instruction helps

@anesvi I meant to say they have macs and not windows, not that they "don't have macs". Sorry for the confusion there. Yeah that was my thought about memory as well. I will try it, but I suspect that it may not complete and the server does time out, which I think may cause all progress to be lost. Bummer.
