### ISSUE TITLE
DIA

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#245]
Dear developer
I can't run both DIA workflows because of an error with MSConverter.
What are the differences between DIA Umpire and DIA MSFragger? 
all the best 
Andrea
[HELP_log_2020-10-06_14-12-53.txt](https://github.com/Nesvilab/FragPipe/files/5333822/HELP_log_2020-10-06_14-12-53.txt)

**Comment by fcyu** [comment]
Hi Andrea,

Thank you for using our tools. You may need to specify your msconvert.exe in DIA Umpire tab.

DIA Umpire extracts pseudo MS/MS scan based on peak tracing. Then, MSFragger searches those MS/MS scan in DDA approach. MSFrgger-DIA directly searches the DIA data, refine scores, and report top-N hits.

From my-point-of-view, DIA Umpire is suitable for wide-window DIA and MSFragger-DIA is suitable for narrow-window DIA.

Best,

Fengchao

**Comment by Angrist75** [comment]
![image](https://user-images.githubusercontent.com/63410174/95205713-0bfdff80-07e6-11eb-9143-0ea787077b1f.png)
I did it but the error remains!
why?

**Comment by Angrist75** [comment]
![image](https://user-images.githubusercontent.com/63410174/95205983-68f9b580-07e6-11eb-9691-57a3f42291e1.png)
I apologize, I made the wrong copy-screen!

**Comment by fcyu** [comment]
Could you send us your log this time?

Thanks,

Fengchao

**Comment by Angrist75** [comment]
[HELP_log_2020-10-06_14-12-53.txt](https://github.com/Nesvilab/FragPipe/files/5334014/HELP_log_2020-10-06_14-12-53.txt)

**Comment by anesvi** [comment]
For some reason it points to MY folder (on my computer). Must be because I created the workflow, and it remembered the path. Obviously you need to change that to where you have it on YOUR computer

**Comment by fcyu** [comment]
Hi @Angrist75 

Your new log shows that

> java.io.IOException: Cannot run program "C:\Users\nesvi\AppData\Local\Apps\ProteoWizard 3.0.20255.0b0ffcfd5 64-bit\msconvert.exe" (in directory "E:\Proteomica\MaxQuant_DIA\MF_DIA_Fragger"): CreateProcess error=2, The system cannot find the file specified

I think the path is still not corrected.

Best,

Fengchao

**Comment by Angrist75** [comment]
![image](https://user-images.githubusercontent.com/63410174/95207064-baef0b00-07e7-11eb-889e-3652f7fbf7d1.png)
the directory you see is the Output directory, I don't understand why it relates to the MSConvert directory.

**Comment by fcyu** [comment]
No, the key point is this: Cannot run program "C:\Users\nesvi\AppData\Local\Apps\ProteoWizard 3.0.20255.0b0ffcfd5 64-bit\msconvert.exe"

**Comment by anesvi** [comment]
You need to change in DIA-U tab from
C:\Users\nesvi\AppData\Local\Apps\ProteoWizard 3.0.20255.0b0ffcfd5 64-bit\msconvert.exe
To
Your msconvert folder. You need to find where Proteowizard is installed on your machine, and select msconvert.exe from that folder

**Comment by anesvi** [comment]
We do not have a good tutorial for DIA analysis yet, but I am happy to send you a zoom link (contact me directly) and do a hands-on tutorial via zoom for you.
Best
Alexey

**Comment by Angrist75** [comment]
I understood and immediately try to correct the error. In case it turns out to be true, I apologize for the naivety but I was convinced I marked the directory in the right way, but the LOG does not lie :)
