### ISSUE TITLE
Philosopher creating empty fasta files instead of concatenated forward/reverse fasta files

### ISSUE THREAD

**Issue by stharan** [Nesvilab/FragPipe#249]
**Describe the bug**
Either using the "add decoy" button in Fragpipe or running Philisopher v3.3.10 in command line (philosopher.exe database --custom d:\FASTA_databases\Homo_sapiens_SwissProt_TaxID_9606.fasta --contam) an empty .fas file is created.

c:\FragPipe\fragpipe14.0\tools\philosopher>philosopher.exe database --custom d:\FASTA_databases\Homo_sapiens_SwissProt_TaxID_9606.fasta --contam
INFO[14:41:54] Executing Database  v3.3.10
INFO[14:41:54] Processing decoys
INFO[14:41:54] Creating file
INFO[14:41:54] Processing decoys
INFO[14:41:54] Creating file
INFO[14:41:54] Done
[2020-10-08-decoys-contam-.fas.txt](https://github.com/Nesvilab/FragPipe/files/5350717/2020-10-08-decoys-contam-.fas.txt)

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Hi @stharan ,

Thanks for using our tools. This bug was fixed in Philosopher [3.3.11](https://github.com/Nesvilab/philosopher/releases/tag/v3.3.11).

Best,

Fengchao
