### ISSUE TITLE
MSFragger DIA search mode not compatible with easypqp

### ISSUE THREAD

**Issue by jgriss** [Nesvilab/FragPipe#251]
In FragPipe 14.0 the new DIA mode creates `_rank[1-3].pep.xml` files while the respective mzML files do not exist.

In order to create the specral library with easypqp we had to 

  1) change the reference mzML file in the pep.xml file
  2) merge the converted easypqp data (the pkl files of the rank[1-3] into a single pkl file

I don't know if this is more leated with easypqp or with FragPipe. But a more integrated way would be great.

**Comment by anesvi** [comment]
Strange. I am able to build the library without any file renaming. Using DIA-MSFragegr_SpecLib
EsyPQP can find mzML even though the files are called _rank[1-3].pep.xml
I will run again just in case now, and can post the log.

Alexey

**Comment by jgriss** [comment]
Thanks for the quick reply @anesvi !

I realised that in FragPipe you ship a python script to adapt several settings to the library creation. Unfortunately, on a fresh install of anaconda on a Windows system easypqp failed to find the unimod.xml file in its own package. That's why I moved to a manual creation of the spectral library.

I used the `grosenberger/easypqp` docker container for my test. Looking at the easypqp code on GitHub it seems that the tool does have specific expectations if "rank[1-3]" is found in the filenames.

Do you ship a different version of easypqp with FragPipe?

Thanks a lot for the help!

**Comment by fcyu** [comment]
Hi @jgriss ,

I think you can still use the python script in FragPipe with command line. You can have a dry run in FragPipe to get the commands. That python script should be able to solve the problems for you.

Best,

Fengchao

**Comment by jgriss** [comment]
Hi @fcyu ,

Thanks for the information! Is there any specific mapping you do in order to get easypqp working?

The reason I ask is that I try to replicate FragPipe in [nextflow](https://nextflow.io) in order to better use our compute resources.

**Comment by fcyu** [comment]
Hi @jgriss ,

Nothing special, just the pepxml being `<run name>_rankN.pep.xml`. I think you can get all the command and options with FragPipe's dry run.

Best,

Fengchao

**Comment by anesvi** [comment]
For FragPipe, the user needs to install EasyPQP
https://msfragger.nesvilab.org/tutorial_fragpipe.html#spectral-library-generation

What happens is that you may have an older version of it. So we recommend uninstalling and reinstalling
pip uninstall --yes easypqp
pip install git+https://github.com/grosenberger/easypqp.git@master

Other than doing this, I am personally not doing anything special, and I a m pretty basic Windows user

Alexey

**Comment by jgriss** [comment]
Hi,

Thanks for the great help!

I'll keep on trying to get it to work without merging the easypqp intermediate files.

Kind regards,
Johannes
