### ISSUE TITLE
Multi-Organism Database Generation Error

### ISSUE THREAD

**Issue by xLinkKnight** [Nesvilab/FragPipe#253]
Benign error when creating a fasta database from a combination of two organisms through the FragPipe GUI. The task appears to finish successfully despite the error message, as the generated fasta file seems to be complete. I've compared it to the combined file when creating separate human and mouse databases (which don't error). The only "off" thing is that the temporary .meta folder remains in the directory.

FragPipe v14
Philosopher v3.3.11

Options: 
Reviewed sequences
Add decoys
Add isoforms
Select organism / proteome ID: Other: ```UP000005640,UP000000589```

Error output:

```
java.lang.IllegalStateException: Something happened during database download
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:162)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalThreadStateException: process has not exited
	at java.lang.ProcessImpl.exitValue(ProcessImpl.java:501)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:259)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:159)
	... 1 more
```

**Comment by fcyu** [comment]
Thanks for your feedback. 

```
at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:259)
```
has the code 
```java
final int exitValue = pr.getProcess().exitValue();
```

It looks like Philosopher didn't return a exit value. I cannot reproduce this error in my Windows. Are you also using Windows?

Regarding the `.meta` folder, we also noticed this issue. We may be able to figure out a way to run the `clean` command if something went wrong, but it is not easy because FragPipe needs to recursively run the `clean` command in all of the places.

Best regards,

Fengchao

**Comment by xLinkKnight** [comment]
Hello Fengchao,

This was on a Windows system. 

I now believe the issue is isolated to my end and not an issue with the software. I too can't reproduce the issue, where as I constantly observed it earlier in the day. Monitoring internet traffic, I noticed impaired throughput during the times it errored. Now it's stable and consistently works as intended. 

Sorry for taking up your time.

**Comment by fcyu** [comment]
No problem. Please feel free to contact us if there is any further questions.

Best,

Fengchao
