### ISSUE TITLE
Issues of own fasta file causing Fragpipe stop processing!!

### ISSUE THREAD

**Issue by WeiqiangChen** [Nesvilab/FragPipe#255]
**Describe the bug**
FragPipe stopped processing when I search it against my fasta file. The error is that psm.txt is empty (1kb).

I found the problem is that the extra enters(\n) in my fasta sequence caused process stop, although fragpipe read out the correct numbers of sequences in my fasta.

My fasta file has following sequence:
>sp|A0A0B7P3V8|YP41B_YEAST Transposon Ty4-P Gag-Pol polyprotein OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) (Baker's yeast) OX=559292 GN=TY4B-P PE=5 SV=2
MATPVRDETRNVIDDNISARIQSKVKTNDTVRQTPSSLRKVSIKDEQVKQYQRNLNRFKTILNGLKAEEEKLSETDDIQM
LAEKLLKLGETIDKVENRIVDLVEKIQLLETNENNNILHEHIDATGTYYLFDTLTSTNKRFYPKDCVFDYRTNNVENIPI
LLNNFKKFIKKYQFDDVFENDIIEIDPRENEILCKIIKEGLGESLDIMNTNTTDIFRIIDGLKNKYRSLHGRDVRIRAWE
KVLVDTTCRNSALLMNKLQKLVLMEKWIFSKCCQDCPNLKDYLQEAIMGTLHESLRNSVKQRLYNIPHNVGINHEEFLIN
TVIETVIDLSPIADDQIENSCMYCKSVFHCSINCKKKPNRELRPDSTNFSKTYYLQGAQRQQQLKSSAKEQKSWNKTQKK
SNKVYNSKKLVIIDTGSGVNITNDKTLLHNYEDSNRSTRFFGIGKNSSVSVKGYGYIKIKNGHNNTDNKCLLTYYVPEEE
STIISCYDLAKKTKMVLSRKYTRLGNKIIKIKTKIVNGVIHVKMNELIERPSDDSKINAIKPTSSPGFKLNKRSITLEDA
HKRMGHTGIQQIENSIKHNHYEESLDLIKEPNEFWCQTCKISKATKRNHYTGSMNNHSTDHEPGSSWCMDIFGPVSSSNA
DTKRYMLIMVDNNTRYCMTSTHFNKNAETILAQIRKNIQYVETQFDRKVREINSDRGTEFTNDQIEEYFISKGIHHILTS
TQDHAANGRAERYIRTIVTDATTLLRQSNLRVKFWEYAVTSATNIRNCLEHKSTGKLPLKAISRQPVTVRLMSFLPFGEK
GIIWNHNHKKLKPSGLPSIILCKDPNSYGYKFFIPSKNKIVTSDNYTIPNYTMDGRVRNTQNIYKSHQFSSHNDNEEDQI
ETVTNLCEALENYEDDNKPITRLEDLFTEEELSQIDSNAKYPSPSNNLEGDLDYVFSDVEESGDYDVESELSTTNTSIST
DKNKILSNKDFNSELASTEISISEIDKKGLINTSHIDEDKYDEKVHRIPSIIQEKLVGSKNTIKINDENRISDRIRSKNI
GSILNTGLSRCVDITDESITNKDESMHNAKPELIQEQFNKTNHETSFPKEGSIGTKCKIPKYRQ

The downloaded fasta from FragPipe has the following sequence:
>sp|A0A0B7P3V8|YP41B_YEAST Transposon Ty4-P Gag-Pol polyprotein OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TY4B-P PE=5 SV=2
MATPVRDETRNVIDDNISARIQSKVKTNDTVRQTPSSLRKVSIKDEQVKQYQRNLNRFKTILNGLKAEEEKLSETDDIQMLAEKLLKLGETIDKVENRIVDLVEKIQLLETNENNNILHEHIDATGTYYLFDTLTSTNKRFYPKDCVFDYRTNNVENIPILLNNFKKFIKKYQFDDVFENDIIEIDPRENEILCKIIKEGLGESLDIMNTNTTDIFRIIDGLKNKYRSLHGRDVRIRAWEKVLVDTTCRNSALLMNKLQKLVLMEKWIFSKCCQDCPNLKDYLQEAIMGTLHESLRNSVKQRLYNIPHNVGINHEEFLINTVIETVIDLSPIADDQIENSCMYCKSVFHCSINCKKKPNRELRPDSTNFSKTYYLQGAQRQQQLKSSAKEQKSWNKTQKKSNKVYNSKKLVIIDTGSGVNITNDKTLLHNYEDSNRSTRFFGIGKNSSVSVKGYGYIKIKNGHNNTDNKCLLTYYVPEEESTIISCYDLAKKTKMVLSRKYTRLGNKIIKIKTKIVNGVIHVKMNELIERPSDDSKINAIKPTSSPGFKLNKRSITLEDAHKRMGHTGIQQIENSIKHNHYEESLDLIKEPNEFWCQTCKISKATKRNHYTGSMNNHSTDHEPGSSWCMDIFGPVSSSNADTKRYMLIMVDNNTRYCMTSTHFNKNAETILAQIRKNIQYVETQFDRKVREINSDRGTEFTNDQIEEYFISKGIHHILTSTQDHAANGRAERYIRTIVTDATTLLRQSNLRVKFWEYAVTSATNIRNCLEHKSTGKLPLKAISRQPVTVRLMSFLPFGEKGIIWNHNHKKLKPSGLPSIILCKDPNSYGYKFFIPSKNKIVTSDNYTIPNYTMDGRVRNTQNIYKSHQFSSHNDNEEDQIETVTNLCEALENYEDDNKPITRLEDLFTEEELSQIDSNAKYPSPSNNLEGDLDYVFSDVEESGDYDVESELSTTNTSISTDKNKILSNKDFNSELASTEISISEIDKKGLINTSHIDEDKYDEKVHRIPSIIQEKLVGSKNTIKINDENRISDRIRSKNIGSILNTGLSRCVDITDESITNKDESMHNAKPELIQEQFNKTNHETSFPKEGSIGTKCKIPKYRQ

----------------------

**Comment by fcyu** [comment]
Your format looks good. Could you please send us your log and the whole fasta file?

Thanks,

Fengchao

**Comment by WeiqiangChen** [comment]
Thanks for the quick feedback.

The log file:
[log_2020-10-23_18-23-55.txt](https://github.com/Nesvilab/FragPipe/files/5430664/log_2020-10-23_18-23-55.txt)

problematic fasta:
[2020-10-22-decoys-20201022_human_20595_yeast_6049_contaminant_309_total_26953.fasta.fas.zip](https://github.com/Nesvilab/FragPipe/files/5430676/2020-10-22-decoys-20201022_human_20595_yeast_6049_contaminant_309_total_26953.fasta.fas.zip)

With exactly the same settings and downloaded fasta. There is no problem.
[2020-10-19-decooys-reviewed-contam-human-yeast_26247.zip](https://github.com/Nesvilab/FragPipe/files/5430684/2020-10-19-decooys-reviewed-contam-human-yeast_26247.zip)

**Comment by prvst** [comment]
Hi @WeiqiangChen, it looks like the extra hidden characters are breaking the database parsing. I suggest you clean or remove them before moving on. I see things like this for example:

`>xx|CBP-tag|CBP-tag
GVMPREETDSKTASPWKSARLMVHTVATFNSIKELNERWRSLQQLA`
