### ISSUE TITLE
Out of memory error w/ large MetaproteomicsDB (170M sequences, 136gb)

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#257]
Dear Developers, 

Finally I run my fragpipe-workflow (LFQ-MBR) completely from a script (that was developed with a smaller DB and it run successfully). 
Using now my large MetaproteomicsDB I end up with a "out-of-memory" error in PeptideProphet (and also later in ProteinProphet) for the combined results.. (it looks like in the individual experiments it is possible to do it but not on the combined one)

Is there anything I can do about it or shall I forget about it?

BTW: The MSFragger was NO problem with 10 splits on the db and was finished in about 30 min.. the Prophets took then 20hrs.

My linux machine has 1TB of Ram. My ulimit is "unlimited".

Thanks for looking into it.
Best regards-  jonas

I started the PeptideProphet like this:
# run peptideProphet
cd /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4
/usr/local/nesvilab/philosopher-3.3.11/philosopher peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database /scratch/p3635/2020-10-07-decoys-contam-p3635_db3_UHGP_20200930.fasta.fas --combine 20201022_005_S223360_474-B5_2.pepXML
cd /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3
/usr/local/nesvilab/philosopher-3.3.11/philosopher peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database /scratch/p3635/2020-10-07-decoys-contam-p3635_db3_UHGP_20200930.fasta.fas --combine 20201022_004_S223360_474-B5_1.pepXML
cd /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2
/usr/local/nesvilab/philosopher-3.3.11/philosopher peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database /scratch/p3635/2020-10-07-decoys-contam-p3635_db3_UHGP_20200930.fasta.fas --combine 20201022_003_S223358_474-B1.pepXML
cd /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1
/usr/local/nesvilab/philosopher-3.3.11/philosopher peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database /scratch/p3635/2020-10-07-decoys-contam-p3635_db3_UHGP_20200930.fasta.fas --combine 20201022_002_S223359_474-B4.pepXML
echo "Peptide Prophet done"

----------------------
from the log:
INFO[14:29:36] Executing PeptideProphet  v3.3.11
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzML in msms_run_summary tag...
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/20201022_005_S223360_474-B5_2.mzML in msms_run_summary tag...
INFO: Results written to file: /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/interact.pep.xml
  - Building Commentz-Walter keyword tree... PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 19970 2+, 6455 3+, 933 4+, 164 5+, 26 6+, and 0 7+ spectra.
Found 9798 Decoys, and 17750 Non-Decoys
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
INFO[16:55:49] Done
INFO[16:55:49] Executing PeptideProphet  v3.3.11
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzML in msms_run_summary tag...
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/20201022_004_S223360_474-B5_1.mzML in msms_run_summary tag...
INFO: Results written to file: /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_3/interact.pep.xml
  - Building Commentz-Walter keyword tree... PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 19873 2+, 6850 3+, 1133 4+, 197 5+, 26 6+, and 1 7+ spectra.
Found 9990 Decoys, and 18090 Non-Decoys
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
INFO[19:25:33] Done
INFO[19:25:33] Executing PeptideProphet  v3.3.11
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzML in msms_run_summary tag...
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/20201022_003_S223358_474-B1.mzML in msms_run_summary tag...
INFO: Results written to file: /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_2/interact.pep.xml
  - Building Commentz-Walter keyword tree... PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 19261 2+, 6270 3+, 1211 4+, 236 5+, 29 6+, and 0 7+ spectra.
Found 9153 Decoys, and 17854 Non-Decoys
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
INFO[21:47:09] Done
INFO[21:47:09] Executing PeptideProphet  v3.3.11
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzML in msms_run_summary tag...
Unknown file type. No file loaded./scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzBIN_calibrated
WARNING: cannot open data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzBIN_calibrated in msms_run_summary tag... unrecognized extension .mzBIN_calibrated, trying .mzML ...
WARNING: CANNOT correct data file /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/20201022_002_S223359_474-B4.mzML in msms_run_summary tag...
INFO: Results written to file: /scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_1/interact.pep.xml
  - Building Commentz-Walter keyword tree... PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 23299 2+, 8201 3+, 1335 4+, 241 5+, 46 6+, and 4 7+ spectra.
Found 12018 Decoys, and 21108 Non-Decoys
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (7+).
INFO[00:16:00] Done
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
INFO[00:16:01] Executing ProteinProphet  v3.3.11
INFO: mu=3.35872e-09, db_size=250387063531
INFO[02:36:41] Done
INFO[02:36:41] Executing Database  v3.3.11
INFO[02:36:41] Processing database
INFO[04:36:30] Done
INFO[04:37:20] Executing Database  v3.3.11
INFO[04:37:20] Processing database
INFO[07:39:15] Done
INFO[07:40:03] Executing Database  v3.3.11
INFO[07:40:03] Processing database
fatal error: runtime: out of memory

**Comment by jjGG** [comment]
Dear Fengchao, 

Thanks for the comment. Do you have by experience an "upper bound" for the fasta file?
We can process the DB with Mascot easily but dont get quants out.. therefore my idea would be to first only see what genomes are identified in these samples and then down-size the large DB to only genomes that are identified by Mascot. 
But it will still be a huge DB.. 

Best regards - jonas

**Comment by fcyu** [comment]
Hi Jonas,

The only limitation is from Philosopher (the quantification after than won't need to read fasta). I think @prvst is a better person than me to answer this question.

Best,

Fengchao

**Comment by anesvi** [comment]
I do not think you should run ProteinProphet in such case. What is ‘protein group’ in this case? Complicated. May need protein inference for metaproteomics done differently.

However, I am surprised by ‘out of memory in PeptideProphet’. Should not be related to the database size.

Is it this part you are referring to?
INFO[00:16:00] Done
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar
Error: Could not find or load main class .export.data01.FragPipe14.fragpipe.lib.antlr4-runtime-4.7.2.jar

INFO[00:16:01] Executing ProteinProphet v3.3.11
INFO: mu=3.35872e-09, db_size=250387063531

Maybe PeptideProphet finished? Do you see these files ?
/scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4/interact.pep.xml

Alexey

**Comment by jjGG** [comment]
Hello Alexey,

Yes - in each individual exp_X I have the pepXMLs.
///////
```
jonas@fgcz-r-033:/scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits/exp_4$ ls
20201022_005_S223360_474-B5_2.pepXML  interact.pep.xml
```
/////
also I have the combined ones:
```
jonas@fgcz-r-033:/scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits$ ls -lrth
total 1.5G
-rw-r--r-- 1 jonas SG_Employees 8.2K Oct 29 14:05 fragger.params
-rw-r--r-- 1 jonas SG_Employees 534M Oct 30 02:36 combined.prot.xml
-rw-r--r-- 1 jonas SG_Employees 999M Oct 30 12:09 combined.pep.xml
drwxr-xr-x 2 jonas SG_Employees   86 Oct 30 12:10 exp_3
drwxr-xr-x 2 jonas SG_Employees   84 Oct 30 12:10 exp_2
drwxr-xr-x 2 jonas SG_Employees   86 Oct 30 12:10 exp_4
drwxr-xr-x 2 jonas SG_Employees   84 Oct 30 12:10 exp_1

```

and they look complete to me:
////////
```
jonas@fgcz-r-033:/scratch/jj_p3635_wFragPipeOTOT/output_UHGP10splits$ tail *.xml
==> combined.pep.xml <==
<parameter name="nsi" value="0"/>
<parameter name="nsm" value="0"/>
</search_score_summary>
</interprophet_result>
</analysis_result>
</search_hit>
</search_result>
</spectrum_query>
</msms_run_summary>
</msms_pipeline_analysis>

==> combined.prot.xml <==
            <annotation protein_description="hypothetical protein"/>
         </indistinguishable_protein>
         <indistinguishable_protein protein_name="rev_GUT_GENOME282113_01226">
            <annotation protein_description="hypothetical protein"/>
         </indistinguishable_protein>
         <peptide peptide_sequence="ENEEEQALR" charge="2" initial_probability="0.2460" nsp_adjusted_probability="0.1184" fpkm_adjusted_probability="0.1184" weight="0.50" group_weight="1.00" is_nondegenerate_evidence="N" n_enzymatic_termini="1" n_sibling_peptides="0.00" n_sibling_peptides_bin="0" n_instances="1" exp_tot_instances="0.25" is_contributing_evidence="N" calc_neutral_pep_mass="1116.5046">
         </peptide>
      </protein>
</protein_group>
</protein_summary>
jonas@fgcz-r-033:/sc
```

**Comment by anesvi** [comment]
That’s good. So the Prophets run fine actually.

As Fengchao said, the crash is in Philosopher. It parses the whole database and stores it in memory.
Unfortunately it makes it incompatible with applications requiring huge database.

Alexey

**Comment by prvst** [comment]
Hi @jjGG 

As Alexey pointed, the issue is not with the Prophets. It's also not related to the quantification. Philosopher was designed for shotgun proteomics pipelines. Its methods were not tuned for huge database files like yours. I'll plan some changes to the code to have this fixed. Hopefully, I will have something working soon. Would you mind sharing your database file with me? A real-world test data would help a lot.

**Comment by jjGG** [comment]
Hei @prvst,

Of course I can share the database .. Do you have an FTP server where I can upload it?
or here would be a link that you could use to download it via http (but it is the not-yet-the-decoyed version).
We had to re-route the tmp-dir to get it decoyed with FragPipe.

https://fgcz-r-035.uzh.ch/fasta/p3635_db3_UHGP_20200930.fasta

thanks for looking into it 
best regards- jonas

**Comment by prvst** [comment]
Thanks, the link will do. I need the database without decoys. I'll let you know when the download is done.

**Comment by jjGG** [comment]
No worry - the database will stay there.. 

just realize - in case you have issues with r-035 .. you can use:
http://fgcz-ms.uzh.ch/fasta/p3635_db3_UHGP_20200930.fasta

cheers - jonas

**Comment by jjGG** [comment]
Dear FragPipe Developers,

We are still trying to get LFQ quant data out of our Metaproteomics-gut
samples. Meanwhile we have a running workflow to "downsize" and subset
the ridiculously huge 185-gig-DB to "Gut_genomes" that have been
identified in a first comet-search.
We tried already multiple subset-DBs (45GB, 30GB, 7GB, 3.5GB) and
finally we can process one (7GB) that still is very comprehensive and we are not loosing too much on proteinIDs.


However, we only manage, if we set `calibrate_mass = 2` in the parameters file and run `msfragger_pep_split.py` as follows:

```
python3 /export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py 10 "java -jar -Dfile.encoding=UTF-8 -Xmx2000G" /usr/local/nesvilab/MSFragger-3.1.1/MSFragger-3.1.1.jar /scratch/jj_p3635_wFragPipeOTOT/output_db11/fragger.params /scratch/jj_p3635_wFragPipeOTOT/20201022_002_S223359_474-B4.raw /scratch/jj_p3635_wFragPipeOTOT/20201022_003_S223358_474-B1.raw /scratch/jj_p3635_wFragPipeOTOT/20201022_004_S223360_474-B5_1.raw /scratch/jj_p3635_wFragPipeOTOT/20201022_005_S223360_474-B5_2.raw
```

We get an Error at the calibration step:

```
Not enough memory allocated to MSFragger.
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
For users running the stand-alone version of MSFragger (i.e. not through FragPipe):  try allocating more memory using the `-Xmx` option.
Traceback (most recent call last):
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 470, in <module>
    main()
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
```

Increasing the split parameter `--split 4` in the `calibrate` function in the python file as suggested solved the issue, but we get the following new error:

```
Database  does not exist.
Traceback (most recent call last):
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 483, in <module>
    main()
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 468, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 358, in calibrate
    raise AssertionError(p)
```

Our workaround for the moment is to set `calibrate_mass = 0` in the parameters file avoiding the calibration step. 

1) Do you have a solution for the `Database  does not exist.` error, when the split parameter in the calibration search is increased?

2) Can you confirm that the "db-splitting option" is only effective for
the real search and NOT for the calibration search? Because we do manage
to process the 7gig DB but only if we deactivate the calibration search
(and I think this is only possible in a commandline-workflow and not via
GUI? or where can I set "no-calibration" in the FragPipeGUI?

3) Can you maybe comment on what is the "largest" DB that you managed in
a workflow with FragPipe?

Best regards-
jonas grossmann & Maria d'Errico

**Comment by fcyu** [comment]
Hi Jonas,

Following are my answers.
1. I don't think split database searching can split database in mass calibration step. @guoci Can you confirm that?
2. Yes, the split database module is only available in main search. You can disable mass calibration in GUI by setting 'Calibration and Optimization' to 'None':
![image](https://user-images.githubusercontent.com/6926299/102364540-90a69000-3f84-11eb-8aa3-f27db3955905.png)
3. If memory is not an issue, MSFragger can handle at most 2^31-1 (may be a little bit fewer on certain JVM), which is a limit from Java, modified peptides. If using split database, the number of peptides can be larger than that because you basically run MSFragger with smaller databases sequently. But you need to disable the mass calibration option and (maybe) don't use Philosopher (I don't think Philosopher can handle a very large database).

Best,

Fengchao

**Comment by jjGG** [comment]
Hei Fengchao

1) Yes - I confirm we had to switch-off `mass calibration` in order to process the 7gig DB because we still ran into "out-of-memory" issues although we used the splittin option and it would not work - only when we switched it off.. 
2) We changed the python-file (in the calibration search function) from split 1 to split 4 and then ran into the `Database does not exist` error.. -> so we have to keep the calibration `off`?
3) We would like to do LFQ-MBR workflow so I think we need Philosopher.. 
--> what is the file size limit that Philosopher can handle by your experience?

Best regards- jonas

**Comment by fcyu** [comment]
Hi Jonas,

Regarding the second question, I think it is possible to make the splitting support mass calibration if you modified the python script well. Maybe Guo Ci @guoci can help.

Regarding the third question, I am sorry that I don't have a good answer.

Best,

Fengchao

**Comment by anesvi** [comment]
About #3, we talked with Felipe that maybe we can make some changes in philosopher to read larger databases. Maybe something we can discuss again

**Comment by prvst** [comment]
Seems to be resolved. If not, please open again.
