### ISSUE TITLE
Process returned non-zero exit code

### ISSUE THREAD

**Issue by boluosuannai** [Nesvilab/FragPipe#260]
Dear MSFragger group,
When I run a data file, the following error occurred and I put the log file below：
[log_2020-11-11_09-37-16.txt](https://github.com/Nesvilab/FragPipe/files/5528029/log_2020-11-11_09-37-16.txt)

If you can help to answer, it would be greatly appreciated

**Comment by fcyu** [comment]
Thanks for your interest in our tools.

Your log has an error: `It is a closed search while localize_delta_mass = 1. Please change localize_delta_mass to 0.`. Please double check your parameters.

Best,

Fengchao

**Comment by boluosuannai** [comment]
Thanks for your reply，
According to your answer, I checked the MSFragger, Validation, and PTMS parameters in FragPipe, but I don’t know how to modify “localize_delta_mass” parameter. 
If you can give me a screenshot of the “localize_delta_mass” parameters, thank you very much

**Comment by fcyu** [comment]
Sorry for the confusion. The corresponding UI is 
![image](https://user-images.githubusercontent.com/6926299/98959505-581d1d80-24d1-11eb-8798-22bbe056abd9.png)
