### ISSUE TITLE
EasyPQP: No iRT protein in built spectral library

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#262]
Hi @guoci ,

This is an issue from a user.

There are iRT proteins in fasta and Philosopher's tsv files have entries from the iRT proteins, but the built library does not have it.

Following is the screenshot of the iRT proteins.

![image](https://user-images.githubusercontent.com/6926299/99343155-4f26a600-285b-11eb-9a28-c7d2a707ff87.png)

I don't have that user's data but I think it should be easy to reproduce: searching some mzml files with a normal fasta containing iRT proteins.

Thanks,

Fengchao

**Comment by guoci** [comment]
@fcyu Is it generated with EasyPQP or SpectraST?

**Comment by guoci** [comment]
@fcyu You should post this in the EasyPQP's github page too. Please send me the files needed to test this.

**Comment by fcyu** [comment]
@guoci I'm sorry that I don't know which part causes this issue (your python script or easypqp itself). Could you please take over from here and look into it (by you or George) when you have time?

I don't have specific files for testing. I think you should be able to reproduce this issue with any mzml and a fasta with iRT.

Thanks,

Fengchao

**Comment by lifeinfo** [comment]
I put the test file temp.zip includes one mzXML file and one fasta file in the following link. 
https://westlakeu-my.sharepoint.com/:u:/g/personal/zhutiansheng_westlake_edu_cn/EdR46sTI8ShLnBPz7uzvAsUBGq1iN2X066QvY79QCStOng?e=bNBjQg

**Comment by guoci** [comment]
@lifeinfo can you also send `*.pep.xml`,  `psm.tsv`, `peptide.tsv` and your library?

**Comment by lifeinfo** [comment]
[data2.zip](https://github.com/Nesvilab/FragPipe/files/5563580/data2.zip)

It seems fragpipe can't build a library with one mzXML file, I used two files to build the library (empty file except header line).

**Comment by lifeinfo** [comment]
@https://github.com/guoci

**Comment by lifeinfo** [comment]
@guoci

**Comment by lifeinfo** [comment]
https://github.com/grosenberger/easypqp/issues/37

**Comment by lifeinfo** [comment]
@guoci how are things going? We are still waiting.

**Comment by guoci** [comment]
@lifeinfo I am putting this on hold, I have some urgent matters to work on for now.

**Comment by guoci** [comment]
Resolved at https://github.com/grosenberger/easypqp/issues/37
