### ISSUE TITLE
DB splitting issue

### ISSUE THREAD

**Issue by miriamfou** [Nesvilab/FragPipe#264]
Hello, 

I'm quite new in using fragpipe. I started with a basic proteomic setup which worked well. Now I'm trying peptidomic (unspecific search) workflow which didn't finish properly. It cannot find the file "...Peptidomics/split_peptide_index_tempdir/Qplus_00027635.mzBIN_calibrated" (see below). I can see that the folder "split_peptide_index_tempdir" was not created.

Do you think this is as well related to using raw files instead of mzML files as previously mentioned as potential problem for another issue (in "non-specific search issues #178")? Or do you know something else which could be the problem here? I thought I could avoid converting but if it is related I'll try.

----------------------
No log file was created. I copied the part with the error:
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 16.905 MIN*********
*******************************TOTAL TIME 26.256 MIN********************************
STARTED: slice 1 of 10
['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx237G', WindowsPath('C:/Users/lcp_proc/Documents/Fragpipe_Pipeline/MSFragger-3.1.1/MSFragger-3.1.1/MSFragger-3.1.1.jar'), 'fragger.params', WindowsPath('E:/Local_Data_for_Maxquant/2020-11/MFO/Fragpipe/Peptidomics/split_peptide_index_tempdir/Qplus_00027632.raw'), WindowsPath('E:/Local_Data_for_Maxquant/2020-11/MFO/Fragpipe/Peptidomics/split_peptide_index_tempdir/Qplus_00027633.mzBIN_calibrated'), WindowsPath('E:/Local_Data_for_Maxquant/2020-11/MFO/Fragpipe/Peptidomics/split_peptide_index_tempdir/Qplus_00027634.raw'), WindowsPath('E:/Local_Data_for_Maxquant/2020-11/MFO/Fragpipe/Peptidomics/split_peptide_index_tempdir/Qplus_00027635.mzBIN_calibrated'), '--partial', '0']
MSFragger version MSFragger-3.1.1
Batmass-IO version 1.19.5
timsdata library version timsdata-2-7-0
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows Server 2016, Architecture: AMD64
Java Info: 1.8.0_261, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 210 GB memory
Checking database...
Checking E:\Local_Data_for_Maxquant\2020-11\MFO\Fragpipe\Peptidomics\split_peptide_index_tempdir\Qplus_00027632.raw...
Failed in checking E:\Local_Data_for_Maxquant\2020-11\MFO\Fragpipe\Peptidomics\split_peptide_index_tempdir\Qplus_00027633.mzBIN_calibrated
UNAVAILABLE: Channel shutdown invoked
Checking E:\Local_Data_for_Maxquant\2020-11\MFO\Fragpipe\Peptidomics\split_peptide_index_tempdir\Qplus_00027633.mzBIN_calibrated...
Traceback (most recent call last):
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 459, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 149, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\lcp_proc\Anaconda3\envs\msfragger\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx237G', 'C:\\Users\\lcp_proc\\Documents\\Fragpipe_Pipeline\\MSFragger-3.1.1\\MSFragger-3.1.1\\MSFragger-3.1.1.jar', 'fragger.params', 'E:\\Local_Data_for_Maxquant\\2020-11\\MFO\\Fragpipe\\Peptidomics\\split_peptide_index_tempdir\\Qplus_00027632.raw', 'E:\\Local_Data_for_Maxquant\\2020-11\\MFO\\Fragpipe\\Peptidomics\\split_peptide_index_tempdir\\Qplus_00027633.mzBIN_calibrated', 'E:\\Local_Data_for_Maxquant\\2020-11\\MFO\\Fragpipe\\Peptidomics\\split_peptide_index_tempdir\\Qplus_00027634.raw', 'E:\\Local_Data_for_Maxquant\\2020-11\\MFO\\Fragpipe\\Peptidomics\\split_peptide_index_tempdir\\Qplus_00027635.mzBIN_calibrated', '--partial', '0']' returned non-zero exit status 1.
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingPeptideProphet: Workspace init [Work dir: E:\Local_Data_for_Maxquant\2020-11\MFO\Fragpipe\Peptidomics\fragpipe-Qplus_00027633.pepXML-temp]
C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\philosopher_v3.3.11_windows_amd64\philosopher.exe workspace --init --nocheck

~~~~~~~~~~~~~~~~~~~~
Cancelling 21 remaining tasks
Processing interrupted, stopping PeptideProphet: Workspace init

**Comment by miriamfou** [comment]
Hello, 
I have an update regarding my issue. I tried to convert raw into mzML files with Proteo Wizard (MSConvert). Since I'm not really sure about all the settings I didn't change anything. I used those mzML files for Fragpipe again and I guess something went wrong with converting. It gives the error "There are non-centroid MS2 spectra. Please prepare the spectral file with peak picking."
and I'm not sure what it means so if you have any solution for my former problem or this I would highly appreciate your help :-) 

In total 167548586 peptides.
Generated 335097172 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.13 Da.
7050579268 fragments to be searched in 1 slices (105.06 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 145.43 s

There are non-centroid MS2 spectra. Please prepare the spectral file with peak picking.
	001. Qplus_00027632.mzML Traceback (most recent call last):
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\FragPipe-14.0\fragpipe\tools\msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
AssertionError: <subprocess.Popen object at 0x0000020574269A08>
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingPeptideProphet: Workspace init [Work dir: E:\Local_Data_for_Maxquant\2020-11\MFO\FraggerPeptidomics\fragpipe-Qplus_00027635.pepXML-temp]
C:\Users\lcp_proc\Documents\Fragpipe_Pipeline\philosopher_v3.3.11_windows_amd64\philosopher.exe workspace --init --nocheck

~~~~~~~~~~~~~~~~~~~~
Cancelling 21 remaining tasks
Processing interrupted, stopping PeptideProphet: Workspace init

**Comment by hayse1** [comment]
We've got an MSConvert tutorial [here](http://msfragger.nesvilab.org/tutorial_convert.html), can you check that you used the settings shown there?

**Comment by guoci** [comment]
@miriamfou in your log, you have:
`There are non-centroid MS2 spectra. Please prepare the spectral file with peak picking.`
Did you select `peak picking` at step 5?
![image](https://user-images.githubusercontent.com/1260178/101209958-b6f23480-3642-11eb-81bc-41220916b97e.png)

**Comment by miriamfou** [comment]
Thank you a lot for your help! I tried both algorithms but indeed forget to klick on "Add" button. 
Sorry for bothering you!
