### ISSUE TITLE
Errors when running protein and peptide prophet

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#266]
I have been trying to analyse a batch of mzml files using Fragpipe and have been getting the errors shown in the attached output code. Please advise what I need to do to fix this.
[FragPipeErrors_NTivendale.txt](https://github.com/Nesvilab/FragPipe/files/5620177/FragPipeErrors_NTivendale.txt)

**Comment by fcyu** [comment]
The error from PeptideProphet is
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The system cannot find the file specified.​
```

Not sure about the reason. Hopefully, Felipe @prvst can take a look.

Best,

Fengchao

**Comment by prvst** [comment]
That's a "file not found' error. I suggest taking a look at all your files, folders and paths. Make sure all drives are mounted, and that you don't have white spaces or special characters anywhere.

**Comment by ndtivendale** [comment]
I did that. Still have the same issue. Is there a limit to file names? How long can they be? Does PeptideProphet need to be running from the same directory as FragPipe?

**Comment by hayse1** [comment]
Did you happen to move the pepXML files? I can get the same error if I start from the PeptideProphet step and set the output to an empty directory. FragPipe will handle all the filepaths for you, so all the steps in the workflow for a particular analysis should be run with the same output directory.

**Comment by ndtivendale** [comment]
No, I didn't move the pepXML files, but when I look in the directory where FragPipe is looking for them, they are not there.

I've moved python to the same directory now. I'm not sure if that will help...

**Comment by ndtivendale** [comment]
Moving Python didn't help. When I just try running PeptideProphet, this is the output. Which file is the 'failed opening file: The system cannot find the file specified.' referring to? the pep.XML file? How could that have been written to any other directory.

​
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\HPG_enriched_1]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-21-25A.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\HPG_enriched_2]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-21-26A.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\HPG_unenriched_1]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-10_F10.pepXML NT-19-47-10_F11rr.pepXML NT-19-47-10_F1rr.pepXML NT-19-47-10_F3rr.pepXML NT-19-47-10_F7.pepXML NT-19-47-10_F4.pepXML NT-19-47-10_F1.pepXML NT-19-47-10_F8.pepXML NT-19-47-10_F12.pepXML NT-19-47-10_F5.pepXML NT-19-47-10_F2rr.pepXML NT-19-47-10_F6.pepXML NT-19-47-10_F9.pepXML
PeptideProphetPeptideProphet [Work dir: C:\data\Nathan\new-v-old\AHA_unenriched_3] [Work dir: C:\data\Nathan\new-v-old\AHA_unenriched_2]

C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-4f10.pepXML NT-19-47-4f2.pepXML NT-19-47-4f6.pepXML NT-19-47-4f3.pepXML NT-19-47-4f1.pepXML NT-19-47-4f7.pepXML NT-19-47-4f11.pepXML NT-19-47-4f4.pepXML NT-19-47-4f12.pepXML NT-19-47-4f8.pepXML NT-19-47-4f5.pepXML
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-4f9.pepXML NT-19-47-7f7.pepXML NT-19-47-7f10.pepXML NT-19-47-7f4.pepXML NT-19-47-7f1.pepXML NT-19-47-7f8.pepXML NT-19-47-7f5.pepXML NT-19-47-7f9.pepXML NT-19-47-7f2.pepXML NT-19-47-7f6.pepXML NT-19-47-7f12.pepXML NT-19-47-7f11.pepXML NT-19-47-7f3.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\AHA_unenriched_1]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-1_F5.pepXML NT-19-47-1_F10.pepXML NT-19-47-1_F8.pepXML NT-19-47-1_F9.pepXML NT-19-47-1_F6.pepXML NT-19-47-1_F2rr.pepXML NT-19-47-1_F2.pepXML NT-19-47-1_F12.pepXML NT-19-47-1_F4.pepXML NT-19-47-1_F3rr.pepXML NT-19-47-1_F1.pepXML NT-19-47-1_F7.pepXML NT-19-47-1_F1rr.pepXML NT-19-47-1_F11.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\AHA_enriched_1]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-21-23A.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\HPG_enriched_3]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-21-27A.pepXML
PeptideProphet [Work dir: C:\data\Nathan\new-v-old\AHA_enriched_3]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-92-2A_2nd_attempt.pepXML
PeptideProphetPeptideProphet [Work dir: C:\data\Nathan\new-v-old\AHA_enriched_2]
 [Work dir: C:\data\Nathan\new-v-old\HPG_unenriched_3]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-20-21-24A.pepXML
PeptideProphetC:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-16f11.pepXML NT-19-47-16f9.pepXML NT-19-47-16f6.pepXML NT-19-47-16f3.pepXML NT-19-47-16f12.pepXML NT-19-47-16f7.pepXML NT-19-47-16f4.pepXML NT-19-47-16f8.pepXML NT-19-47-16f1.pepXML NT-19-47-16f5.pepXML NT-19-47-16f10.pepXML NT-19-47-16f2.pepXML
 [Work dir: C:\data\Nathan\new-v-old\HPG_unenriched_2]
C:\data\Nathan\philosopher_v3.3.12\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\data\Nathan\athal.fa --combine NT-19-47-13f11.pepXML NT-19-47-13f8.pepXML NT-19-47-13f5.pepXML NT-19-47-13f2.pepXML NT-19-47-13f10.pepXML NT-19-47-13f9.pepXML NT-19-47-13f6.pepXML NT-19-47-13f3.pepXML NT-19-47-13f12.pepXML NT-19-47-13f7.pepXML NT-19-47-13f1.pepXML NT-19-47-13f4.pepXML
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            
INFO[11:00:06] Executing PeptideProphet  v3.3.12            

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The system cannot find the file specified.​

: iostream error
FATA[11:00:29] Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 64 remaining tasks
Processing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphetProcessing interrupted, stopping PeptideProphet

**Comment by prvst** [comment]
Can you check your database file ? see if the path is correct.

**Comment by ndtivendale** [comment]
Yes it is correct.

**Comment by ndtivendale** [comment]
The error seems to have evolved. Now it's saying: Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files.

Is that just referring to mzml files and my fasta file?

**Comment by ndtivendale** [comment]
I think I've figured it out. I had set the output in the MSFragger tab to 'TSV'. I've now changed it to 'PEPMXML' and it's running again. Hopefully that does it.

**Comment by fcyu** [comment]
Yes, that explains everything. I suggest you loading the built-in workflows and only making necessary changes (e.g., variable modifications, mass tolerance, digestion).

Best,

Fengchao
