### ISSUE TITLE
 Philosopher: there are peptides shown to be not unique but don't have any mapped proteins

### ISSUE THREAD

**Issue by mwakabayash** [Nesvilab/FragPipe#267]
Hello MSFragger team,

I'm trying to run LFQ searches with MBR, but receive the error attached.
Sometimes it occurs, and somtimes it doesn't. 
Each file seems to have good quantification results, but MSstats file is not produced.
What could be the cause of the error?

Thanks,
Masaki
[log_2020-12-02_08-34-06.txt](https://github.com/Nesvilab/FragPipe/files/5626164/log_2020-12-02_08-34-06.txt)

**Comment by fcyu** [comment]
Hi Masaki,

I think some runs don't have any data. Such as 
```
D:\MSFragger_installer\philosopher_v3.3.12_windows_amd64\philosopher.exe filter --sequential --razor --prot 0.01 --tag rev_ --pepxml D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\54 --protxml D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\combined.prot.xml
INFO[23:11:08] Executing Filter  v3.3.12                    
INFO[23:11:08] Processing peptide identification files      
WARN[23:11:08] No PSM was found in data set. D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\54\interact-200721_hAAExosome_sEV54_Slot2-4_1_875.pep.xml 
INFO[23:11:08] 1+ Charge profile                             decoy=0 target=0
INFO[23:11:08] 2+ Charge profile                             decoy=0 target=0
INFO[23:11:08] 3+ Charge profile                             decoy=0 target=0
INFO[23:11:08] 4+ Charge profile                             decoy=0 target=0
INFO[23:11:08] 5+ Charge profile                             decoy=0 target=0
INFO[23:11:08] 6+ Charge profile                             decoy=0 target=0
INFO[23:11:08] Database search results                       ions=0 peptides=0 psms=0
INFO[23:11:08] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[23:11:08] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[23:11:08] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
INFO[23:11:15] Protein inference results                     decoy=10132 target=11595
INFO[23:11:15] Converged to 1.08 % FDR with 2310 Proteins    decoy=25 threshold=0.9965 total=2335
INFO[23:11:17] Applying sequential FDR estimation            ions=0 peptides=0 psms=0
INFO[23:11:17] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[23:11:17] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[23:11:17] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
```
```
D:\MSFragger_installer\philosopher_v3.3.12_windows_amd64\philosopher.exe filter --sequential --razor --prot 0.01 --tag rev_ --pepxml D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\16 --protxml D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\combined.prot.xml
INFO[23:14:11] Executing Filter  v3.3.12                    
INFO[23:14:11] Processing peptide identification files      
WARN[23:14:11] No PSM was found in data set. D:\MSFragger_temp\test11_each11-20_nogroup_databaseChanged\16\interact-200721_hAAExosome_sEV16_Slot2-16_1_787.pep.xml 
INFO[23:14:11] 1+ Charge profile                             decoy=0 target=0
INFO[23:14:11] 2+ Charge profile                             decoy=0 target=0
INFO[23:14:11] 3+ Charge profile                             decoy=0 target=0
INFO[23:14:11] 4+ Charge profile                             decoy=0 target=0
INFO[23:14:11] 5+ Charge profile                             decoy=0 target=0
INFO[23:14:11] 6+ Charge profile                             decoy=0 target=0
INFO[23:14:11] Database search results                       ions=0 peptides=0 psms=0
INFO[23:14:11] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[23:14:11] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[23:14:11] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
INFO[23:14:18] Protein inference results                     decoy=10132 target=11595
INFO[23:14:18] Converged to 1.08 % FDR with 2310 Proteins    decoy=25 threshold=0.9965 total=2335
INFO[23:14:20] Applying sequential FDR estimation            ions=0 peptides=0 psms=0
INFO[23:14:20] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[23:14:20] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[23:14:20] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
```

My guess is that these runs triggered this error
```
2020-12-02 02:14:57 [ERROR] - 0
```

Could you please remove the runs with 0 PSM and try again?

Also, there are a lot of peptides shown to be not unique but don't have any mapped proteins. Not sure if it is related. Could you please help to check if those peptides are indeed not unique but don't have any mapped proteins?

Thanks,

Fengchao

**Comment by mwakabayash** [comment]
Hi Fengchao,

Some runs lack many data (peptide.tsv, ion.tsv, psm.tsv, ....) as you said. (e.g. lack in sample 54 in attached file)
![PSMnull](https://user-images.githubusercontent.com/75050252/100831167-84accf80-34a8-11eb-88b7-77e8cf9b842b.png)
What I don't understand is that the error is not happening every time. It seems to be inconsistent.
(e.g.  At first sample1 lacks data, next time sample1 has data but sample2 lacks data....)
It may depend on the combination of files..??
All submitted raw data (.d folder) have same structures and components...

There seems to be some errors also in peptides assignments. Those peptides should be uniquely assigned for a single protein, as far as I confirmed.

Thanks,
Masaki

**Comment by fcyu** [comment]
HI Masaki,

Regarding the randomness, I don't think the ID numbers have any randomness. The same run should have the same result. Can you double check it based on the run name?

Regarding the peptide assignments, you may send some psm.tsv to us for check if you want.

Best,

Fengchao

**Comment by mwakabayash** [comment]
Hi Fengchao,

I verified some problems.
The error basically seems due to poor or 0 psm as you said. When all runs have sufficient psm, the error has not happened so far.
If a run doesn't have enough data, the run can have different results in different batches (see attached file)
The difference between the two batches is just combination of files. (sample 1-5, or sample 1-10)
![differentSize_samerun](https://user-images.githubusercontent.com/75050252/101120801-ea789300-3631-11eb-8540-d0df26032a73.png)
Anyway, with enough data, it will work fine.

The peptide assignment problems also occur in analyses with enough data. It is not related to the above problem.
I will email you the log and a psm.tsv file with the assignment error. (psm.tsv file cannot be attached here)
Could you please check what is happening?

Thanks,

Masaki

**Comment by fcyu** [comment]
Sure. I will take a look at your files. I will also try to reproduce the error that happens when there is 0 PSMs to make IonQuant not crash in this case.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Masaki,

I verified that those warning are true. Those are peptides shown to be not unique but don't have any mapped proteins:
![image](https://user-images.githubusercontent.com/6926299/101173844-1899ab00-3611-11eb-9d43-d2e83f25c115.png)

Felipe @prvst, could you take a look when you have time?

Thanks,

Fengchao

**Comment by mwakabayash** [comment]
Hi Fengchao,

Thanks you for the verification.
I'm a bit confused.
The Wiki describes that Mapped protein means "additional proteins the peptide may originate from".
Why are the peptides (without Mapped protein) shown to be not unique ??

**Comment by fcyu** [comment]
Yes, you are right. If a peptide is shown to be not unique, there should be mapped proteins. So, this is a bug and we are trying to fix it. 

BUT, if a peptide is shown to be unique, there MIGHT BE mapped proteins because of the definition of uniqueness in ProteinProphet.

Best,

Fengchao
