### ISSUE TITLE
Is it possible to do partial processing, so I don't need to re-run the whol process when it falls over towards the end?

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#268]

**Comment by fcyu** [comment]
Yes, it is. You just need to uncheck finished tools.

Best,

Fengchao

**Comment by ndtivendale** [comment]
Where do I do that?

**Comment by fcyu** [comment]
![image](https://user-images.githubusercontent.com/6926299/100818017-4ca97c00-3417-11eb-976f-3c322046d08b.png)
![image](https://user-images.githubusercontent.com/6926299/100818074-61860f80-3417-11eb-9272-3eedb553da00.png)
![image](https://user-images.githubusercontent.com/6926299/100818109-7662a300-3417-11eb-907f-14289439fc1b.png)
![image](https://user-images.githubusercontent.com/6926299/100818161-93977180-3417-11eb-97b0-75ecad090562.png)
![image](https://user-images.githubusercontent.com/6926299/100818190-a27e2400-3417-11eb-88d1-2d7c47ca7e5d.png)
![image](https://user-images.githubusercontent.com/6926299/100818230-b1fd6d00-3417-11eb-9771-273af801b575.png)

**Comment by ndtivendale** [comment]
Ohhhh, I feel kind of stupid now.

**Comment by fcyu** [comment]
Not at all.

Please feel free to contact us if you have any questions.

Best,

Fengchao

**Comment by cindysimm** [comment]
In addition to uncheck finished tools, how do I start the partial processing? Re-open the program, re-upload rawdata, select workflow, and select the previous output folder? In my previous run, 'Process 'quant(isobaric)' finished, exit code: 0' is displayed. Can I just select 'Quant(isobaric)' when partial processing?

**Comment by fcyu** [comment]
> Re-open the program, re-upload rawdata, select workflow, and select the previous output folder? 

Correct.

> Can I just select 'Quant(isobaric)' when partial processing?

In the `Quant (isobaric)` tab.

Best,

Fengchao

**Comment by cindysimm** [comment]
Thank you very much!
