### ISSUE TITLE
Error in installing msproteomicstools package

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#269]
I have the latest version of Visual C++, but for some reason it's not recognized.  please see the error log below.

Thanks!
David.

Building wheel for PyMSNumpress (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\protolab\AppData\Local\Temp\pip-wheel-ybv0d865'
       cwd: C:\Users\protolab\AppData\Local\Temp\pip-install-fhx62ny5\pymsnumpress\
  Complete output (6 lines):
  running bdist_wheel
  running build
  running build_ext
  skipping 'PyMSNumpress.cpp' Cython extension (up-to-date)
  building 'PyMSNumpress' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for PyMSNumpress
  Running setup.py clean for PyMSNumpress
Failed to build PyMSNumpress
Installing collected packages: scikits.datasmooth, PyMSNumpress, cluster, pyteomics, configobj, retrying, plotly, pymzml, biopython, msproteomicstools
    Running setup.py install for PyMSNumpress ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\protolab\AppData\Local\Temp\pip-record-02v_4pcc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\PyMSNumpress'
         cwd: C:\Users\protolab\AppData\Local\Temp\pip-install-fhx62ny5\pymsnumpress\
    Complete output (6 lines):
    running install
    running build
    running build_ext
    skipping 'PyMSNumpress.cpp' Cython extension (up-to-date)
    building 'PyMSNumpress' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"'; __file__='"'"'C:\\Users\\protolab\\AppData\\Local\\Temp\\pip-install-fhx62ny5\\pymsnumpress\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\protolab\AppData\Local\Temp\pip-record-02v_4pcc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\PyMSNumpress' Check the logs for full command output.

**Comment by guoci** [comment]
Can try you installing `Cython` and `biopython` with `conda` before installing `msproteomicstools`?
```
conda install Cythonl biopython
pip install msproteomicstools
```

**Comment by Dmorgen** [comment]
Thanks! - I'm getting the following error: 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cythonl

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by guoci** [comment]
@Dmorgen there was a typo, I have edited it, please retry.

**Comment by Dmorgen** [comment]
I've write permissions issue here. I will talk to our IT guys. thanks for the help!
