### ISSUE TITLE
FragmentSeriesNumber from easypqp is truncated

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#271]
Hi Guo Ci @guoci ,

This is an issue from users. The FragmentSeriesNumber is truncated, for example, the FragmentSeriesNumber of `y15` is 5 and the truncated of `b12` is 2. Could you please check and fix this issue?

Thanks,

Fengchao

**Comment by guoci** [comment]
Fixed at e064c42b02911c2386d92bcaf344b2cb6eab2559
