### ISSUE TITLE
Normalized retention time need to be restricted in the range

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#272]
Hi Guo Ci @guoci ,

There are outliers in normalized retention time (out of [-100, 200]). It looks like the range needs to be restricted in the range during the fitting. Could you please check and fix this issue?

Thanks,

Fengchao

**Comment by guoci** [comment]
Please provide data.

**Comment by fcyu** [comment]
I also don't have the specific data, but I think every data has this issue since it is a systemic issue. You can start with the data you already have to see if there is this issue. I think you can also fix them by just checking the code.

**Comment by fcyu** [comment]
But let me try to contact the users to get the data first.
