### ISSUE TITLE
Philosopher: Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files

### ISSUE THREAD

**Issue by hkim-scripps** [Nesvilab/FragPipe#274]
The results file (pepXML) is not generated normally.

[log_2020-12-09_04-16-38.txt](https://github.com/Nesvilab/FragPipe/files/5665773/log_2020-12-09_04-16-38.txt)

**Comment by fcyu** [comment]
Can you share your `EK293T_tryptic_2ug.pepXML` and `EK293T_tryptic_2ug_c.pepXML` with us?

Thanks,

Fengchao

**Comment by fcyu** [comment]
No reply.
