### ISSUE TITLE
Fragger_output

### ISSUE THREAD

**Issue by singhsk2622** [Nesvilab/FragPipe#275]
Hi 
I ran MSFragger LFQ MBR script and i have different form of intensity which one correspond to  normalize LFQ. I see same values in all three forms of intensity (total, unique and razor). My LFQ-MBR did not work? I am using combined proteins file. could someone explain output file of MSFragger?
I am also seeing ION count error msg? could someone suggest any solution? 
[log_2020-12-05_06-15-26.txt](https://github.com/Nesvilab/FragPipe/files/5666329/log_2020-12-05_06-15-26.txt)

One more thing, is it possible to get output in following form of intensity : sample intesnity, samples 2 intensity and then there razor inetsnity , peptides, spectra etc,. this will help us for further using this file for perseus analysis. 
I am attaching my log search

**Comment by fcyu** [comment]
All of `total`, `unique`, and `razor` are normalized LFQ. The difference is the peptides (total/all peptides, unique peptides, or unique+razor peptides) used in calculating protein intensity.

For most cases, you can use `razor` intensity column which has the same definition as MaxQuant's LFQ intensity (unique+razor).

Regarding the 'ION count error msg', is `2020-12-05 06:04:46 [WARNING] - Peptide FDVSGYPTIK is shown to be not unique but does not have mapped proteins. Treating it as a unique peptide.` you are talking about? There is a small bug in [Philosopher](https://github.com/Nesvilab/philosopher) and @prvst is trying to fix it.

Regarding the format, I think you can adjust or only select certain columns when loading the table into Perseus.

Best,

Fengchao

**Comment by singhsk2622** [comment]
Hi Fengchao,
Thanks for detail information. regarding format, it was just suggestion. I ran 72 raw files in MSFragger and then i took that to perseus and it was bit hectic and risky to look for all razor intensity for all 72 files (they were separated by spectra, peptides, unique intensity, total intensity) as if all razor intensity are grouped in place and others grouped separately that will be easy for further analysis.
its just suggestion, I dont know if it is possible or not.   
Thanks for help !!
best,
sachin

**Comment by fcyu** [comment]
Thanks Sachin,

We will discuss this change internally.

Best,

Fengchao
