### ISSUE TITLE
Maxquant and MSFragger comparison 

### ISSUE THREAD

**Issue by singhsk2622** [Nesvilab/FragPipe#276]
Hi compared MSFragger and Maxqunat result in perseus. i found big difference of significant quantification between Maxquant and MSfragger. I dont know if anyone have compared this. i am wondering if i am using or selecting any wrong parameter in MSFargger.
[MQ_Vs_Fragger.pptx](https://github.com/Nesvilab/FragPipe/files/5668878/MQ_Vs_Fragger.pptx)

**Comment by fcyu** [comment]
Your information is too little to figure out the reason. I suggest you start from comparing identification results, then quantified intensities of ions, then quantified intensities of proteins.

Best,

Fengchao

**Comment by singhsk2622** [comment]
Hi Fengchu,
Why in my fragger output total intensity, unique and razor intensity values are same? any comment on that?
[combined_protein.xlsx](https://github.com/Nesvilab/FragPipe/files/5681383/combined_protein.xlsx)
