### ISSUE TITLE
Is there any way to export phosphosites on proteins from FragPipe analyzing phosphoproteomics data?

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#278]
I used Fragpipe to analyze phosphoproteomics data, and I can not find a way to export the phosphosites on proteins.
 
So could you tell me how to obtain the list of phosphosites?

Any solution processing output of Fragpipe will be welcomed.

BTW. I do not want to use Maxquant.

**Comment by hcadre** [comment]
I would like to assist andyzim111, in that there is currently no possibility implemented in MSFragger to link back identified modifications within a particular peptide to the position in the protein sequence, from which this peptide is derived.

**Comment by anesvi** [comment]
Unfortunately Philosopher does not generate those, yes.

For TMT data, TMT-Integrator generates site-level reports.
We discussed adding similar reports for label-free (generated using IonQuant), but have not implemented yet.

If someone already wrote some parsers/tools for doing it, please share it with us. I am sure other will benefit.

Thanks
Alexey

**Comment by fcyu** [comment]
IonQuant 1.7.16 in FragPipe 17.0 can generate modification site report.
