### ISSUE TITLE
Did not find any PeptideProphet results in input data! - Executing ProteinProphet  v3.3.11

### ISSUE THREAD

**Issue by cesarrivera** [Nesvilab/FragPipe#280]
Hello community, good morning.
I'm trying to identify bacterial proteins in human saliva.
I have had the same error in FragPipe v14 and v13:

**INFO[21:31:15] Executing ProteinProphet  v3.3.11            
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64))
 (no FPKM) (using degen pep info)
Reading in D:/oralmicrobiomepart1/b_ulcer_3/interact-ulcer3.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/c_remission_3/interact-remission3.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/c_remission_2/interact-remission2.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/b_ulcer_2/interact-ulcer2.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/b_ulcer_1/interact-ulcer1.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/a_healthy_3/interact-control3.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/a_healthy_2/interact-control2.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/a_healthy_1/interact-control1.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in D:/oralmicrobiomepart1/c_remission_1/interact-remission1.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
FATA[21:31:59] Cannot execute program. There was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stoppingPhilosopherDbAnnotate [Work dir: D:\oralmicrobiomepart1\b_ulcer_2]
D:\protprog\philosopher3311\philosopher.exe database --annotate D:\oralmicrobiomepart1\oralmicrobiomepart1.fasta --prefix rev_**

- Is it due to a poor quality of my data? (low resolution)
- A bad configuration of my base?
Database:
https://drive.google.com/file/d/1c20fuKEzZQmq_V1NpPMSfM9LS4IExm8m/view?usp=sharing
- Do I need to change my fragment_mass_tolerance?

**pepXML and pep.xml files are not empty**.

Sorry if I am being naive here but I hope you can help me out.

I added my log file.

Best regards,

César Rivera
Chile
[log_2020-12-13_21-44-02.txt](https://github.com/Nesvilab/FragPipe/files/5689636/log_2020-12-13_21-44-02.txt)

**Comment by fcyu** [comment]
Your fasta file doesn't have any decoy proteins. You can add them by clicking 'Add decoys'
![image](https://user-images.githubusercontent.com/6926299/102121147-7b5d2480-3e11-11eb-8790-d61058408e5e.png)

Best,

Fengchao

**Comment by cesarrivera** [comment]
@fcyu It is true, it does not have decoys. From where I download the files there is no base of decoys or contaminants. Analysis without decoys is not possible?
If not possible, is there an online tool to solve this challenge?
Thanks so much,
César

**Comment by fcyu** [comment]
It is easy to add decoy.  Just clicking 'Add decoys' in FragPipe

![image](https://user-images.githubusercontent.com/6926299/102121147-7b5d2480-3e11-11eb-8790-d61058408e5e.png)

Best,

Fengchao

**Comment by cesarrivera** [comment]
Excellent, I was looking at version 13 not 14.
Thanks!

**Comment by fcyu** [comment]
No problem.
