### ISSUE TITLE
FragPipe OpenSearch Failure using High Performance Desktop

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#282]
Greetings,

Thank you for providing such an amazing open source tool!

I was trying to run 30 .RAW file using fragpipe opensearch settings. Due to some reason I am experiencing search failure. Have attatched the error log here for your reference and high performance desktop specs. 

I was monitoring the RAM usage, MSFragger did not reach its max capacity. Searching with a small set of files (~10) with open search setting was possible. Please do advise me on how to troubleshoot this issue.

Regards Ben

![High_Performance_Computer_Specs](https://user-images.githubusercontent.com/69944967/102782494-2b6bf800-43e5-11eb-995f-2a3e5bec8077.JPG)
[hs_err_pid14016.log](https://github.com/Nesvilab/FragPipe/files/5724526/hs_err_pid14016.log)

**Comment by fcyu** [comment]
Thanks for your interest in our tools. 

Your error was from JVM not our tools. It is likely due to some bugs in JVM. The reasons of causing this is not clear to us. We saw an example due to too much memory. Could you please reduce the memory in FragPipe and try again?

![image](https://user-images.githubusercontent.com/6926299/102784180-025a5180-436a-11eb-8126-7c934e3a17b8.png)

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings,

Setting it to 0=auto should be alright? 
Will try that setting and up date you mate.
Thanks for your speedy reply!

Regards Ben

**Comment by fcyu** [comment]
Hi Ben,

`0` means let FragPipe detects the free memory size. You may need to put something like 64 or 32 to it.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, I also recall someone with HPC and 500Gb memory had a problem since ‘0’ allocated all 500Gb memory. Seem to be HPC related

**Comment by prvst** [comment]
Perhaps, instead of using all free memory, the program could allocate RAM equal to free RAM minus a certain percentage, like 5 or 10%. For certain shared environments like an HPC, the kernel will likely be configured not to allow users to take over all resources at once.

**Comment by anesvi** [comment]
I would say if free memory is determined  to be above 120Gb (I doubt desktop people would have more than that, so more than 120 means HPC), then apply extra ‘minus 5-10%’ logic)

**Comment by fcyu** [comment]
Sounds good. Will add this logic.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings All,

I gave FragPipe 64GB worth of RAM and the runs were successful. 
I also like to re-mention, that I am not using a HPC but a HPD (high performance desktop).
Interestingly, providing 120 GB worth of RAM seem to crash the searches, but 64GB is perfectly fine..

Anyways, thanks alot guys! OpenSearch is not just a tool, it a weapon!

Regards Ben

**Comment by fcyu** [comment]
Hi Ben,

You are welcome. Please feel free to contact us if you have any further questions.

Best,

Fengchao
