### ISSUE TITLE
Parameter setting failure in building library by easypqp

### ISSUE THREAD

**Issue by lifeinfo** [Nesvilab/FragPipe#283]
Hi Guo Ci @guoci ,

I used following command to build the library:
`python -u ../fragpipe13/tools/speclib/gen_con_spec_lib.py $fastaPath ./ ${mzfiles:1} $output True unused use_easypqp c
iRT 7 "--rt_lowess_fraction 0.01"
`
Is there any way to filter ions in the library conforming to the down criterions like spectrast2tsv? 

1. Lower and upper mass limits of fragment ions
2. remove transitions with Q3 falling in the swath mass range when provided the swath/dia window.
3. Fragment ion charge states allowed.

Could you please check and fix this issue?

Thanks,

**Comment by guoci** [comment]
@lifeinfo Pleas post this issue at https://github.com/grosenberger/easypqp/issues
