### ISSUE TITLE
Search failure using OpenSearch with high performance desktop - Error Message of Exception_Access_Violation 

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#286]
Greetings,

I am trying to perform OpenSearch using 81 .raw files. I am consistently experience unsuccessful searches/ failed runs. I have attached the log file here for your reference. I had previous also submitted an issue with regards to this problem. Previously, I was using 30 .raw file and sorted out the issue by your suggestion of reducing memory usage to 64 GB. The previous issue was #282 FragPipe OpenSearch Failure using High Performance Desktop which was successfully sorted.

Initially, to perform this search using 81 .raw files I utilized 64 GB memory. But the runs failed due to memory issue I believe. I had deleted all the files associated with that run, therefore I am not able to provide you the log file. Thereafter I increased to 100 GB memory and the run failed again. The error log for the 100 GB memory failed run is attached below.

Please do advise me on how I should troubleshoot this issue?
I have also attached the specs of my desktop in this thread for your reference.

Regards, Ben       

[hs_err_pid7760.log](https://github.com/Nesvilab/FragPipe/files/5781031/hs_err_pid7760.log)
![image](https://user-images.githubusercontent.com/69944967/103883194-a0029e80-5128-11eb-8ce4-42efd57a4d52.png)

**Comment by fcyu** [comment]
These error are also from Java, not from our tools. It is rare that such errors appear so frequently. Maybe your system has some issues with the memory. You may try to upgrade your java to the latest version from ([https://www.oracle.com/java/technologies/javase-downloads.html](https://www.oracle.com/java/technologies/javase-downloads.html)). In order to use your system's java, you need to use `FragPipe-14.0.zip` from [https://github.com/Nesvilab/FragPipe/releases/tag/14.0](https://github.com/Nesvilab/FragPipe/releases/tag/14.0).

Best,

Fengchao

**Comment by BenSamy2020** [comment]
I am currently using FragPipe-14 with my current system. 

So to get FragPipe working, I should install Java SE 15 on my current system?  (upgrading from Java 8.0 to Java SE15). 
Will update you about the search outcome.

Regards, Ben

**Comment by BenSamy2020** [comment]
Opps, I just realized that both the FragPipe files are different. One already with Java and the other does not. Will down the one without Java and try.

**Comment by fcyu** [comment]
Yes, the log shows that you were using the one with Java (java 8). In order to use a new java, you need to download the one without Java.

**Comment by BenSamy2020** [comment]
Hi,

Would like to inform you that when I utilised the FragPipe-14.0.zip without Java, the runs were successful. Thanks for you support.

Regards Ben
