### ISSUE TITLE
EOFException and .NoClassDefFoundError

### ISSUE THREAD

**Issue by christophgil** [Nesvilab/FragPipe#291]
I try to get started with msfragger.
I have an mgf file made on brukertimstof  and add it in the tab "Config" of msfragger.
I use java jdk 15 I am on a Windows server 2012 R2
at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.EOFException
	at java.base/java.io.RandomAccessFile.readInt(RandomAccessFile.java:846)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)

Unfortunately, the stack trace does not give the source line where the error occured. It looks to me that it is in another jar 
file within the msfragger jar.

Now I try to  msconvert.exe --mzML   or --mzXML
Your parser complaint about the mzML format and indeed, it  looks odd to me 
There are many lines like
<cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="512.76161 6481"
I replaced  all lines like this and kept  512.76161" removing the " 6481" with the command
tr '\t' ' ' | sed -e 's|name="selected ion m/z" value="\([0-9.]\+\)\+ \+[^"]*"|name="selected ion m/z" value="\1"|1'

Now I get 
at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: umich/ms/fileio/filetypes/LCMSDataSource

However this is strange because this class is in the msftbx-1.7.0.jar  and msftbx-1.7.0.jar  which is in the msfragger jar.

Apparently there is a Class loader problem with nested jars.

I am used to have all jars separatly and enumerated in the CLASSPATH

Why do you nest them and include another level of complexity by using 
this special class loader?

I do not know to get any further here.

I have not found a tutorial with sample files to be downloaded.
Is there one?

How should my fasta header look like. I have a fasta from uniprot with several fields divided by bar. Is this ok?

I got the class loading problem also on a Ubuntu PC

Many thanks

Christoph

**Comment by fcyu** [comment]
Hi Christoph,

First of all, MSFragger can load timsTOF raw file (.d). It can also read the MGF from Bruker's Compass DataAnalysis software. You don't need to convert anything.

> Why do you nest them and include another level of complexity by using
this special class loader?

MSFragger uses the library to parse spectral files.

> How should my fasta header look like. I have a fasta from uniprot with several fields divided by bar. Is this ok?

As long as all protein are from uniprot and unchanged, they should be OK.

Best,

Fengchao

**Comment by christophgil** [comment]
Thanks,
I found my error, I downloaded an old jar version of fragpipe.
Cheers

Christoph
