### ISSUE TITLE
Error in PeptideProphet via FragPipe when using custom enzyme 

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#292]
I am using MSFragger 3.1.1, Philopher 3.4.13, and FragPipe 14.0 in Windows.

I am doing an open search and have digested my samples using a fairly uncommon enzyme (wild-type alpha-lytic protease, aka WALP; citation: 10.1074/mcp.M113.034710), which cleaves after TASV. In the MsFragger tab of FragPipe, I have selected "custom" for enzyme rules, entered "WALP" for enzyme name, and entered "TASV" for cut after. On the Validation tab of FragPipe, under PeptideProphet, i have entered:
--nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --enzyme WALP : cut(TASV) sense(C)

I got the following error:

INFO[17:04:56] Executing PeptideProphet  v3.4.13            
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The filename, directory name, or volume label syntax is incorrect.​

: iostream error
FATA[17:04:58] Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

I am sure my syntax is wrong on the PeptideProphet command line, but I wanted to see if you could help. I've attached my log and parameter files. 

Thanks,
Josh

[fragger_params.txt](https://github.com/Nesvilab/philosopher/files/5876493/fragger_params.txt)
[fragpipe_2021-01-26_17-00-13_config.txt](https://github.com/Nesvilab/philosopher/files/5876494/fragpipe_2021-01-26_17-00-13_config.txt)
[log_2021-01-26_17-07-19.txt](https://github.com/Nesvilab/philosopher/files/5876495/log_2021-01-26_17-07-19.txt)
[shepherd_config.txt](https://github.com/Nesvilab/philosopher/files/5876496/shepherd_config.txt)
[umpire-se_2021-01-26_17-00-13_params.txt](https://github.com/Nesvilab/philosopher/files/5876497/umpire-se_2021-01-26_17-00-13_params.txt)

**Comment by jossmi** [comment]
Thanks, Felipe. 

Just to be a bit more clear on my enzyme settings, In MSFragger, I selected "custom" from the dropdown menu, entered "nonspecific" in the enzyme name. See screenshot.

<img width="1440" alt="Screen Shot 2021-01-27 at 12 38 49 PM" src="https://user-images.githubusercontent.com/77409436/106031361-2d3c7180-609d-11eb-8d07-437e826b08e1.png">

Josh

**Comment by fcyu** [comment]
This issue has been solved. There is a new issue created. 

Best,

Fengchao

**Comment by jossmi** [comment]
Fengchao, sorry, I'm assuming you're referring to a new issue I posted in in PTM-S about a similar, but separate PTM-S issue (that was with a regular Trypsin digestion, this is with an uncommon enzyme; I'm unfortunately juggling a couple different issues). The issue for this particular thread has not been resolved yet.

I still would like any input on how to get PTM-S to accept my custom digestion rules (cut after TASV).

Thanks,
Josh

**Comment by fcyu** [comment]
Hi Josh,

Sorry for the oversight. I will re-open it.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
PTM-Shepherd does not do anything with enzymes. This is an unrelated issue.

You only have 359 PSMs. This is simply not enough data to run PTM-Shepherd when you have such a large mass range. If you are certain your parameters are correct, I would suggest disabling it.
