### ISSUE TITLE
Error in FragPipe when finishing PTM-Shepherd and generating spectral library

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#293]
I am using MSFragger 3.1.1, Philopher 3.4.13, and FragPipe 14.0 in Windows and doing an open search with PeptideProphet, ProteinProphet, PTM-Shepherd, and SpectraST library generation enabled. 

Everything runs fine up until PTM-Shepherd, at which point it throws back an error, which is pasted between the asterisks below. I've attached my log and parameter files and a screenshot of the PTM-Shepherd settings tab in FragPipe.

Thanks,
Josh

***********************************************************************
74496 MS2 scans present in dataset default-ptmshepherd-dataset

Creating combined histogram
	Generated histogram file for dataset default-ptmshepherd-dataset [-151 - 497]
Created combined histogram!

Running peak picking

Exception in thread "main" java.lang.NullPointerException
	at edu.umich.andykong.ptmshepherd.peakpicker.ModSummary.toFile(ModSummary.java:104)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:379)
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stoppingSpecLibGen [Work dir: C:\Users\jossmith\Documents\Adductomics\ColeLabData\200509\MSFragger\MSFragger_output]
C:\Users\jossmith\Python\python.exe -u C:\Users\jossmith\MSFragger\FragPipe-14.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py C:\Users\jossmith\MSFragger\Philosopher\2020-02-03-decoys-contam-HSA.fasta C:\Users\jossmith\Documents\Adductomics\ColeLabData\200509\MSFragger\MSFragger_output C:\Users\jossmith\Documents\Adductomics\ColeLabData\200509\MSFragger\MSFragger_output\combined.prot.xml C:\Users\jossmith\Documents\Adductomics\ColeLabData\200509\MSFragger\MSFragger_output True C:\Users\jossmith\MSFragger\FragPipe-14.0\fragpipe\lib\..\tools\philosopher\philosopher.exe
Picked top 500 peaks

created summary table

annotated summary table
***********************************************************************

[shepherd_params.txt](https://github.com/Nesvilab/FragPipe/files/5882506/shepherd_params.txt)
[fragpipe_2021-01-27_12-59-40_params.txt](https://github.com/Nesvilab/FragPipe/files/5882508/fragpipe_2021-01-27_12-59-40_params.txt)
[umpire-se_2021-01-27_12-59-40_params.txt](https://github.com/Nesvilab/FragPipe/files/5882509/umpire-se_2021-01-27_12-59-40_params.txt)
[fragger_params.txt](https://github.com/Nesvilab/FragPipe/files/5882510/fragger_params.txt)
[log_2021-01-27_13-46-00.txt](https://github.com/Nesvilab/FragPipe/files/5882511/log_2021-01-27_13-46-00.txt)

**Comment by anesvi** [comment]
Unrelated to the PTM-Shepherd crash, I wonder why do you need SpectraST?
If you want to build a library from open search results, I think EasyPQP would be the way. Also, you would need to place the mass shift on the sequence in MSFragger (we have not tested it much ourselves yet though!)
Alexey

**Comment by jossmi** [comment]
Thanks Alexey, I changed the library generation tool to EasyPQP. Haven't gotten that to work yet though, because it's
still hanging up at PTM-Shepherd. Same error as before, so I haven't attached the log again.

When you say,
"Also, you would need to place the mass shift on the sequence in MSFragger (we have not tested it much ourselves yet though!)"

are you referring to the deamidation I had listed  as a custom mod in the PTM-Shepherd window (first screenshot)? I do have a custom variable mod for deamidation in the MSFragger tab entered and selected (second screenshot). 

<img width="1440" alt="Screen Shot 2021-01-27 at 3 45 17 PM" src="https://user-images.githubusercontent.com/77409436/106051715-d348a580-60b6-11eb-8425-b202e5930aed.png">

<img width="1440" alt="Screen Shot 2021-01-27 at 3 33 14 PM" src="https://user-images.githubusercontent.com/77409436/106051765-e196c180-60b6-11eb-855e-665caf5df16c.png">


Josh

**Comment by danielgeiszler** [comment]
Hi Josh,

1. I'm working on your issue now.
2. You probably don't want to add Deamidation as a custom modification for annotation if it was a variable mod in your search. 
3. On the other issue: PTM-Shepherd does not deal with protein digestion and there is no need to pass your enzyme rules to it.

**Comment by anesvi** [comment]
I was asking about the spectral library step, EasyPQP. Unrelated to PTM-Shepherd.

I think by mixing two separate issues:

1)      EasyPQP with open search

2)      PTM-Shepherd crash
I get confused

So, can you explain what you are trying to do?
Why do you need open search + deamidation as variable mod? Open search will get that.

Why do you need spectral library?

**Comment by danielgeiszler** [comment]
Josh, can you please upload your peaksummary.annotated.tsv file?

**Comment by danielgeiszler** [comment]
Hi Josh,

I see what your issue is from your other ticket. I'm leaving this ticket open so you may continue to ask questions, because these are the same issue.

PTM-Shepherd does not have enough data and is crashing. The only solution is to disable PTM-Shepherd.

**Comment by jossmi** [comment]
Thanks all for your help. Sorry for the confusion and the multiple posts. 

Alexey, 

First, I'll admit that I am not classically trained in proteomics, but have been learning "on the job" for the past couple years. So that may explain some puzzling choices/assumptions/dumb questions. Apologies for any of that.

The overall goal of this project is untargeted analysis of covalent modifications to serum albumin, identifying novel mass shifts where possible. Certainly, PTMs in the traditional sense, but we are particularly interested in chemical modifications from endogenous reactive metabolites, and especially adducts formed from exogenous exposures. There is a fairly robust literature using targeted analysis of albumin adducts to confirm and quantify exposure to a variety of compounds, and we are trying to use DIA and open search to advance this into the realm of unbiased and untargeted analysis. I am running my DIA data through DIA-Umpire and then passing it to MSFragger.

Regarding the deamidation variable modification:
Our sample buffer is TEAB and I have seen a publication reporting that TEAB can increase deamidation, so I figured I may have an increased prevalence of this artifact in my samples. I included deamidation as a variable modification because I figured that I wanted to be able to find unknown mass shifts on peptides that included deamidations. I presumed that having MSFragger include deamidation as a variable mod would improve the likelihood of properly localizing mass shifts within deamidated peptides, as opposed to the LOS algorithm accidentally lumping the +0.984 deamidation shift into an unknown mod present on another residue. Is this concern at all warranted? 

Regarding the spectral library:
I am doing downstream analysis of my MSFragger results in Skyline (after some Python manipulation to get the custom modifications into Skyline), with targeted analysis/validation/QC on the hits from the MSFragger output. My rationale for building a spectral library was that I would like to import a spectral library into Skyline, built off of the MSFragger output, so that I could utilize the library match feature in Skyline to more easily identify unknown adducts across the various replicates in my experiments. 

Question regarding the PTM-Shepherd crash:
Since I am (at the moment) only interested in modifications to albumin, I figured that I have no need to have MSFragger search for modifications on other proteins/peptides. Thus, I made a custom FASTA database that only includes the human albumin sequence, with contaminants and decoys added through Philosopher (per instructions on your Philosopher Github wiki).
Obviously, it is a much smaller database than typical, and a benefit (in my view) has been that searches are much, much quicker. However, is this small database causing other issues?
-  Is this why PTM-Shepherd doesn't have enough PSMs to use? 
- I am routinely getting a message in the MSFragger log saying that I have insufficient data for mass calibration. I'm acquiring in an Orbitrap Fusion at 30K for MS1 and MS2, so it seems it's not an issue of low resolution data.

Thanks again to the whole team for all your help.
Josh

**Comment by anesvi** [comment]
Dear Josh,

You are doing some interesting things that have not been fully explored yet (although I did play with open searches on DIA data and adductomics before). But I propose that we take the conversation off the github forum. I would be happy to have a zoom call with you, with a few members of my lab, if you are willing to present a few slides about your project. We can provide a better advice then. You can contact me at nesvi at med.umich.edu

Best,
Alexey
