### ISSUE TITLE
installing FragPipe on Linux Clutser

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#294]
Hi FragPipe developer team, 
I am curious to know if there is a tutorial of how to use the FragPipe on linux HPC. I tried to use the provided shell script but wasn't successful. Please see the attached image of my terminal. I appreciate any help. 
Thanks
<img width="831" alt="Screen Shot 2021-01-28 at 3 26 10 PM" src="https://user-images.githubusercontent.com/19155957/106194866-621ff580-617d-11eb-8e8a-0ed5c4fb2622.png">

**Comment by fcyu** [comment]
[https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html](https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html)

Best,

Fengchao
