### ISSUE TITLE
Parallelism setting not respected during fragment index slice generation

### ISSUE THREAD

**Issue by fabianegli** [Nesvilab/FragPipe#295]
I realized that the resource usage exceeds the set `Parallelism` value in the steps that precede the "Fragment index slice generated" log entry.

Is that again the issue of an "unconfigurable" library as in #216 or is there something you can do to make the analysis adhere to the limits set?

**Comment by fcyu** [comment]
> the resource usage exceeds the set Parallelism value in the steps that precede the "Fragment index slice generated" log entry.

I don't think this is true. Maybe showing us your analysis and evidence can help us to troubleshoot it for you.

Best,

Fengchao

**Comment by fabianegli** [comment]
I spent quite some time looking at the CPU usage in the TaskManager and at the run tab in FragPipe in parallel. From the looks of it this issue definitely exists, although the spikes are relatively short in time. 

Please let me know what kind of "evidence" you would like - and if there is some internal log that would help I would appreciate a short hint how to gather it.

PS: I try to avoid this kind of CPU usage spikes because I work on shared infrastructure with sometimes unpredictable process termination when the resource usage is above the guidelines.

**Comment by fcyu** [comment]
You can use VisualVM (https://visualvm.github.io/) to see if there are indeed more **MSFragger's threads** running. You can send us your screenshot of VisualVM if you see such a case. Please note that, MSFragger can only control the threads in MSFragger. Other threads from Java is out of our control. To my experience, the usage of those threads are minor.

Best,

Fengchao

**Comment by fabianegli** [comment]
It will take some time before I can troubleshoot this issue because I am running a big search at the moment, but I will do it once it runs through. The machine unfortunately doesn't have JDK, so visualvm won't work. Would screenshots of the TaskManager be of some value?

**Comment by fcyu** [comment]
TaskManger is not very informative for this case because it is the total usage of all programs in your computer and the spike you mentioned may be due to other reasons or programs (for Windows, anti-virus could consume additional CPU resource when there is a program reading files). The troubleshooting can be performed on another computer with a small data (if there is such a bug in MSFragger, you should be able to reproduce it in any computer with any data).

Best,

Fengchao
