### ISSUE TITLE
Raw file in read-only directory fails

### ISSUE THREAD

**Issue by christophgil** [Nesvilab/FragPipe#296]
fragpipe works like a charm! Thanks for this cool tool.

It is not a good idea to create temporary files in the parent folder  when the raw file is in a read-only file system.
Please add the option to specify a temp folder.
 
Caused by: java.nio.file.AccessDeniedException: C:\Volumes\200ng_Hela_dda_referenzgradient_long_RE5_1_27.d.zip\200ng_Hela_dda_referenzgradient_long_RE5_1_27.d\200ng_Hela_dda_referenzgradient_long_RE5_1_27_5.3.342.mgf.1756059272.0.fragtmp

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
	at edu.umich.andykong.msfragger.E.b(Unknown Source)
	at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Many thanks

**Comment by fcyu** [comment]
Thanks for your suggestion. Can you try to see if creating shortcuts/softlinks for your files helps?

Best,

Fengchao

**Comment by christophgil** [comment]
Hi Fengchao

I am impressed that you answer requests even on Weekends. That is cool!

Symlinks work fine. However, it requires an additional step and my
colleagues are already confused because
I bundle the  output files  of the instrument PCs in a zip. This zip  needs
to be mounted. This works fine  with Pismo mount.
This allows us to access the files in the zip through the file system
mounted on C:/Volumes.
mspipe is able to read it but then stumbles when it tries to write into the
same folder unless I symlink the mgf file to a folder
with r/w access.

I want to move the msfragger as soon as possible to our Ubuntu Linux server.
Do you have a HowTo?

Perhaps an idea for an enhancement in the future - Java has a
ZipInputStream class.
I see that you use the nio package for faster file reading.
 and I do not know whether ZipInputStream can be mapped on a Bytearray.


Windows shortcuts on the other hand do not work in mspipe.
One could use powershell to derefeference them.
In case it is useful to you, here is my bash function to find the target
path of a shrtcut.
You could do something similar with Runtime.exec()
shortcut_target(){
    [[ -z "$1" ]] && return 0
    local f ps target
    f=$(cygpath -m -a "$1")
    ps="(New-Object -ComObject
WScript.Shell).CreateShortcut('$f').TargetPath"
    target=$(powershell -c "$ps")
    if [[ -z "$target" ]];then
        echoerr $RED_FAILED' shortcut_target '$1
        return 1
    fi
    cygpath "$target"
}



Cheers

Christoph

**Comment by fcyu** [comment]
Hi Christoph,

MSFragger writes the temp file, mzBIN file, and pepXML file to the spectral files' directory. We will not change it because there are too many tools dependending on it. Changing it may break them. If creating soft links helps, I suggest you using this approach.

Regarding using MSFrager and FragPipe in Ubuntu, it is quite easy because they are platform independent. You can also remote control FragPipe with x-forwarding. We have a [tutorial](https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html) which may be helpful to you.

Best,

Fengchao

**Comment by christophgil** [comment]
Dear Dr Fengchao,

softlinks work - I will teach my colleagues.

In the next days I am going to install fragpipe on a Linux Ubuntu
and I guess I will run into problems with the proprietary formats.
mgf, raw and perhaps {.wiff .wiff.scan}
Is there any Howto which could help.


Cheers
Christoph

**Comment by fcyu** [comment]
[Here](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_fragpipe.md) has a table regarding which formats are supported by our tools.

Soft link works well for mgf, mzML, and mzXML format. It won't work for raw format, and I am not sure about .d from timsTOF. As to .wiff and .wiff.scan, you need to convert it to mzML. Here is a [tutorial](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md) about the converting

Best,

Fengchao

**Comment by christophgil** [comment]
Thanks, I'll check it out.

**Comment by fcyu** [comment]
You are welcome.

**Comment by christophgil** [comment]
Hi Fengchao,

I still do not fully understand the directory structure of FragPipe.
I have installed with owner root.
Unless I change ownership of the cache directory I get:
   java.nio.file.AccessDeniedException: /local/MS/FragPipe.d/17.1/lib/../cache
And it seems that changes in the GUI will not be saved.


There is also a directory 
~/.config/FragPipe/fragpipe/ with two cache files.

A file with name cache implicates that one can remove it without losing data. 
Is it meant like this?
But to me these files look like the saved state of the GUI and I get confused.

Cheers

Christoph

**Comment by fcyu** [comment]
Hi Christoph,

There are two places having FragPipe's cache/temp files. On is in user's HOME directory. Depending on the operation system, the directories are different. The other one is in FragPipe folder (`fragpipe/cache`). You can find the paths by clicking `Clear cache and close` button in the `Config` tab. Following is an example of mine in the Linux server.

![image](https://user-images.githubusercontent.com/6926299/143270809-247fb781-97b5-471b-b9cd-0db617eddb8e.png)

BTW, I don't recommend you put FragPipe in the root directory. Putting it in HOME directory or other directory that don't need root permission is better.

Best,

Fengchao
