### ISSUE TITLE
identify phosphpeptide sequence

### ISSUE THREAD

**Issue by clin888** [Nesvilab/FragPipe#298]
Is any quick way to find out the phosphopeptide sequence from the output file?
for example:
TALDO1_sp|P37837|TALDO_HUMAN_231_237_1_1_S237
Thanks

**Comment by anesvi** [comment]
Dear “Clin888”,

What file are you looking at?

Our multi-site and single site reports from TMT-Integrator have peptide sequence columns

E.g.
sp|A0FGR8|ESYT2_HUMAN_S743

ESYT2

SSSSLLAsPGHISVK


Best,
Alexey

**Comment by clin888** [comment]
Hi Alexei,

I apologize for the confusion. It is our fault.
I just checked this with our statistician. In fact, she manipulated the data to facilitate her pipeline (combined ids into a single entry). Now, I find all the phosphopeptide sequences.

Thank you for all your help,

Chenwei
________________________________
