### ISSUE TITLE
MSFragger Result Viewer

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/FragPipe#300]
The more I work with MSFragger, the more I think I can appreciate the quality of the results obtained. Being a long time MaxQuant user though, I am missing the Viewer functionality that serves as a common platform to access all result files from one central point (peptides, proteins, modifications, MSMS spectra etc). Are there any plans to implement a similar tool also for MSFragger?

**Comment by anesvi** [comment]
This is a good, valid suggestion. However, we also do not want to write another big viewer program. Perhaps there is something already available where we can feed our data into?
I have not looked at Peptide Shaker for a while. Not sure what else is there that is freely available

**Comment by hcadre** [comment]
Thanks for your suggestions! MSConvert is slow as molasses though in converting .d files to mgf format and converting dozens of files will take aeons then. And then I have access to the spectra only. But what about the combined.prot.xml file? Doesn´t it contain the all the combined protein data in a format that could be rendered accessible to PDV or maybe Peptide Shaker?

Best, 

Hannes

**Comment by fcyu** [comment]
PDV supports psm.tsv and pep.xml. Not sure about PeptideShaker.

Best,

Fengchao

**Comment by JurajLenco** [comment]
PeptideShaker currently supports X!Tandem, MS-GF+, MS Amanda, OMSSA, MyriMatch, Comet, Tide, Mascot, Andromeda, MetaMorpheus, Novor, DirecTag, and mzIdentML. It would be great if it works with MSFragger too.
J. Lenco

**Comment by anesvi** [comment]
Thank you for the suggestion. Our problem is we need to convert the output to mzIdentML.
We need to check the format, and I am hoping to find someone who can help us with the process a bit.
Best,
Alexey

**Comment by hcadre** [comment]
On the MZIdentML page of the Seattle Proteome Center (http://tools.proteomecenter.org/wiki/index.php?title=Software:MZIdentML) it says: "...  The program idconvert which is part of the ProteoWizard suite is capable of converting a number of different formats into mzIdentml. When doing the conversion it is useful to have all of the source files available to the converter because the converter is smart enough to find multiple sources and to weave the data into a single document. In particular the combination of prot.xml and pep.xml is supported. If you use this combination it is a good idea to have the original sources used for the search available and in the same spots that they were used in the search because the pep.xml file will not contain the original spectra but only a reference to the file from which they were read. 

Would that help or represent a part of the solution?
