### ISSUE TITLE
Path issue during philosopher workspace setup

### ISSUE THREAD

**Issue by fabianegli** [Nesvilab/FragPipe#301]
The workspace initialization throws a warning about not finding `.meta/meta.bin`. 

```
WorkspaceCleanInit [Work dir: \\path\to\MSFragger-output]
\\path\to\philosopher.exe workspace --clean --nocheck
INFO[09:36:52] Executing Workspace  v3.4.13                 
INFO[09:36:52] Removing workspace                           
WARN[09:36:52] Cannot read file. open .meta\meta.bin: The system cannot find the path specified. 
INFO[09:36:52] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
```

Is the warning expected or is this a path handling issue? 

Could it be related to having the philosopher binary stored on a NAS?

Setup: Windows Server 2016, MSFragger 3.1.1, FragPipe 14.0

**Comment by anesvi** [comment]
This is a common question. You can ignore this warning

FragPipe always cleans the folder to remove old meta files from philosopher in case they exist. When nothing to clean, it gives a warning, but no problem

We will try to suppress this warning, or detect if there is something to clean before cleaning.

**Comment by fcyu** [comment]
OK, I will let FragPipe don't print this warning. I have actually 'muted' `WARNING: CANNOT correct data file...` and `WARNING: cannot open data file...` from PeptideProphet.

Best,

Fengchao

**Comment by anesvi** [comment]
Sounds good

**Comment by fcyu** [comment]
Muted in FragPipe. Will be available in the next release.

Best,

Fengchao
