### ISSUE TITLE
Error in locating pepXML files

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#302]
Trying to use Philosopher (within FragPipe) to analyse pepXML files, but keep getting this error. 'FATA[12:10:57] Missing input parameters. missing pepXML files'. But I have checked the directory in which Philosopher is looking for the pepXML files, and they are there (e.g. one of the files is called: 'NT_19-68-5.pepxml' and I'm pretty sure there is data in the files because they are each about 35 MB. Any advice as to what is going on would be much appreciated.

**Comment by fcyu** [comment]
Felipe @prvst ,

Can you change the error message to `Missing input parameters. missing interact*-pep.xml files. Please check if PeptideProphet was run.`? The current error message is misleading.

Thanks,

Fengchao
