### ISSUE TITLE
How to obtain intensities of PTM peptides from PTMprophet and IonQuant

### ISSUE THREAD

**Issue by algom** [Nesvilab/FragPipe#305]
Hello Fragpipe developers,

I'm really interested in doing PTM type of studies using Fragpipe, so far I have gained some experience doing LFQ analysis and I'm happy with results I'm getting. For PTM I'm really impressed with the speed so far. I want to have the IonQuant results at the modified peptide level and the PTMprophet results to be able to filter by localization probability and to be able to normalize by the protein level. 

I have some questions regarding this:

1. In the output after a run, including PTMprophet, I see the final pep.xml and combined prot.xml, besides the combined peptide and protein tsv files. Looking at the pep.xml I see that it run with iProphet using the pep.xml before PTMprophet (not with the mod.pep.xml) so the information is not there. If I go to each sample folder (of replicates/samples) I see the mod.pep.xml (PTMprophet) files and in the `PSM.txt` I see a reported intensity. Looking at the `Ion.tsv` for some peptides that I checked seems to have the same value, so I guess this is coming from Ionquant, is this right? 
If so, I guess I could use this as the intensity of the modified peptide.
2.   Unfortunately, I'm not only interested in phosphorylations but other PTMs, e.g. Acetylation, methylation. and on the `PSM.txt` I only see two columns reporting the probability of PTMProphet : Number of Phospho Sites and Phospho Site Localization, which has the probabilities for phosphorylation but not of acetylation and methylation that I included in my search and are present in the mod.pep.xml. Is phosphorylation the only PTM supported in the `PSM.txt` ouput, i.e. is this hard coded? 
3. As the mod.pep.xml files do not have the intensities (don't see them inside) I cannot go back, and try to parse the xml file and export it. I don't know how the `PSM.txt` table is generated, if it is just a merging of the outputs of the files or if it is an iProphet run of the mod.pep.xml in case there are several files in a folder, e.g. technical replicates (as in my case) and then the IonQuant results are merged by a PSM identifier?

I would be really happy for any help or hint. If the PTMprophet probabilties like the Phospho Site Localization can be added for other PTMs defined in PTMprophet, like Acetylation, methylation, or dimethylation, would be great! 
Then is just a matter of collecting the `PSM.txt` files and merging it to a unique file a-la PTM.sites.txt of MaxQuant and would be relatively easy to use for normalization with the combined protein tsv output in other software, like R. I can share scripts for doing that if needed.

Sorry for the lengthy questions. Thank you very much for developing these tools.

Regards,

Alejandro

PS I look in the issues and this might be related to #278 but somehow this seem to be a more expanded related question(s)

**Comment by dpolasky** [comment]
Hi Alejandro,
You are correct that only phosphorylation is read from the PTMProphet results in the current version. We are actively working on incorporating the localization information for all modifications from the PTMProphet results into the PSM table for an upcoming release

**Comment by algom** [comment]
Hi Daniel,

I see. Well, I really look forward to the upcoming release! I'm happy with the performance of the tools and hope to integrate them and use them in my analysis. If you ever have a pre-release version and need some testing, I will be happy to help.

Alejandro

**Comment by fcyu** [comment]
Added in FragPipe 17.0
