### ISSUE TITLE
tmp dir full ->  

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#306]
Hello FragPipe Team, 

We are still trying to process rather large databases.. (~ 10gigs). 
We can process it with a script but when trying to do it with the GUI, we ran into memory issues again. Where and how do I need to change the tmpdir location when I use the GUI (via ssh -Y Xwindow forwarding)? I did put the command in my ssh shell before starting the GUI but it was either not working or I have to put it differently.. 
`JAVA_OPTS=-Djava.io.tmpdir=/scratch/myuser/fragpipe_tmp`

Thanks for your help - really appreciated.. 
- jonas

///error in GUI///
"OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   129890
Try using the -Djava.io.tmpdir= option to select an alternate temp location."

**Comment by guoci** [comment]
To pass the environment variable to `FragPipe` you can either do
`$ JAVA_OPTS=-Djava.io.tmpdir=<your_preferred_tempdir> <path_to_fragpipe>/fragpipe`
or
```
$ export JAVA_OPTS=-Djava.io.tmpdir=<your_preferred_tempdir>
$ <path_to_fragpipe>/fragpipe
```

**Comment by jjGG** [comment]
Thanks for this - issue is solved now - when I start the FragPipeGUI

**Comment by jiyoungyoun** [comment]
Great. Solved the issue.
