### ISSUE TITLE
Out of bounds error w IonQuant

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#308]
Dear Fragpipe Team

I am running FragPipe via Xwindow-GUI on a Linux machine. I get an IonQuant error for "index out of bounds".
Do you have any idea what went wrong?

There are 15 raw files in the game and a huge metaproteomicsDB of 8.2G (which I manage to run successfully to run the full FragPipe-MBR workflow for 3 test files).

Best regards
jonas

///
2021-02-18 09:27:27 [INFO] - matched run percentage: 0.1495889380762246
2021-02-18 09:27:27 [INFO] - Fitting a mixture model...
2021-02-18 09:27:27 [INFO] - Estimating match-between-runs FDR...
2021-02-18 09:27:30 [ERROR] - Index 11095 out of bounds for length 10001
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Hi Jonas,

It looks like the modeling does not work well for your data. We've improved it recently and will be available in the next release. If you like, you can give you a pre-release one to try. We need your email address to send the file.

Best,

Fengchao

**Comment by jjGG** [comment]
Hei Fengchao - your new release solves the issue. Thanks for this - you guys are a great team. Best regards - jonas
