### ISSUE TITLE
IonQuant error - failed to correct modification mass

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/FragPipe#310]
Hello,

I am testing IonQuant together with Open Search by setting the report of mass shifts as variable mods as variable modifications on a semi-specific search.

My session just crashed after initiating IonQuant. The last lines of the log file are here:

```
2021-02-24 22:27:21 [INFO] - Building index...
2021-02-24 22:27:22 [INFO] - Writing index to D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\BPH\UK181.quantindex
2021-02-24 22:27:22 [INFO] - Loading D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\MSFragger_search\BPH\UK181.pepXML...
2021-02-24 22:27:23 [ERROR] - Failed to correct the modification mass 81.01369062500001. The closest theoretical mass is 57.0215.
Process 'IonQuant' finished, exit code: 1
``` 

Do you have any idea what can be causing this and how to avoid happening again?

I just modified the precursor mass mode in MSFragger to selected instead of corrected.

I am attaching the log file here.

Many thanks in advance for taking a look.

Best wishes,
Miguel
[log_2021-02-25_10-30-01_ion_quant_error_failed_to_correct.txt](https://github.com/Nesvilab/FragPipe/files/6041972/log_2021-02-25_10-30-01_ion_quant_error_failed_to_correct.txt)

**Comment by fcyu** [comment]
Hi Miguel,

Because [Philosopher](https://github.com/Nesvilab/philosopher) cannot show the open modification in psm.tsv (you can see that the assigned modification column is empty for those peptides with open modification in the sequences), IonQuant still cannot recognize them. 

The current workaround is using the common mass offset workflow and report mass shifts as variable mods. In this way, [Philosopher](https://github.com/Nesvilab/philosopher) can show the open modifications in the assigned modification column.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Hello Fengchao,

I was reading in this issue #256 and understood that setting the option 'Report Mass Shift as Variable Modification' to 'Yes' would allow IonQuant to catch these peptides with mass shifts from the open search and do quantitation on them. 

I think I misunderstood this, I have set MSFragger to report the mass shifts as variable modifications after open search.

Would I need instead to use the mass offset workflow and not the open search workflow in order to quantify the modified peptides? I would then need to get a list of mass offsets based from an initial open search, am I correct?

Many thanks in advance.

Best,
Miguel

**Comment by fcyu** [comment]
Hi Miguel,

Unfortunately, we cannot do quantification for open search for now. We are working on it, and should be ready within this year.

And yes, you need to load `common-mass-offsets` workflow which has a list of common modifications. You can also prepare your own list from your open search: you can get the list from `global.profile*.tsv` from open search.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Hello Fengchao,

I ran a new test with the Mass Offset search in MSFragger +  'Report Mass Shift as Variable Modification' to 'Yes'. 

I turned on IonQuant and got a similar error in a second test search.

```
2021-02-25 22:30:17 [INFO] - Building index...
2021-02-25 22:30:17 [INFO] - Loading D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\MSFragger_search\Mass_offset_search\BPH\UK181.pepXML...
2021-02-25 22:30:18 [ERROR] - Failed to correct the modification mass -162.04629342041017. The closest theoretical mass is -105.0248.
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stoppingWorkspaceClean [Work dir: D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\MSFragger_search\Mass_offset_search]
C:\Data_analysis_software\FragPipe\fragpipe\lib\..\tools\philosopher\philosopher.exe workspace --clean --nocheck
```

Again, many thanks for taking a look.

I am attaching the log file here.

Best,
Miguel
[log_2021-02-26_10-37-52_IonQuant_error_Mass_Offset_search.txt](https://github.com/Nesvilab/FragPipe/files/6048741/log_2021-02-26_10-37-52_IonQuant_error_Mass_Offset_search.txt)

**Comment by fcyu** [comment]
Hi Miguel,

I am sorry that I forgot that there is a bug in MSFragger 3.1.1. You need to set at least one variable modification (e.g., protein N-terminal acetylation) to trigger it writing the modifications to the header of pepXML so that Philosopher can recognize the open modifications.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Hello Fengchao,

I am testing it now, many thanks for letting me know.

Best wishes,
Miguel

**Comment by MiguelCos** [comment]
Hello Fengchao,

The error is persistent when using Mass Offset parameters + N-terminal acetylation (variable) + Reporing mass shift as variable modification. 

```
2021-02-26 15:15:53 [INFO] - Loading D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\BPH\UK181.raw...
2021-02-26 15:16:20 [INFO] - Building index...
2021-02-26 15:16:20 [INFO] - Loading D:\data\Miguel\z_Urinary_Biomarkers\temp_raws\Batch1\MSFragger_search\Mass_offset_search\Test_3_massoff_wf_selected_yes_n_correct_reportasvar\BPH\UK181.pepXML...
2021-02-26 15:16:21 [ERROR] - Failed to correct the modification mass 147.16630657958984. The closest theoretical mass is 146.0579.
Process 'IonQuant' finished, exit code: 1
```

Any idea what I might be doing wrong?

Many thanks, as always, for your support.

Best wishes,
Miguel

[log_2021-02-27_11-14-41_error_ionquant.txt](https://github.com/Nesvilab/FragPipe/files/6054157/log_2021-02-27_11-14-41_error_ionquant.txt)

**Comment by fcyu** [comment]
Hi Miguel,

I am sorry that there are still errors. One possible reason is that there are modifications on C which has already been modified. In the future release, we will prevent this from happening. Right now, you can solve this by putting `ADEFGHIKLMNOPQRSTUVWY-` to `restrict delta mass to`.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Hello Fengchao,

Thanks for the suggestion. Testing again. 

Best wishes,
Miguel

**Comment by MiguelCos** [comment]
Hello again,

Just reporting. This:

> you can solve this by putting `ADEFGHIKLMNOPQRSTUVWY-` to `restrict delta mass to`.

Solved the issue.

I really liked the IonQuant output! Especially because it throws an MSstats formatted table :)... 

Best wishes,
Miguel

**Comment by fcyu** [comment]
Hi Miguel,

Glad to hear that it finally works for you. In the future release, we will make quantifying open search research easier.

Best,

Fengchao
