### ISSUE TITLE
Easypqp error when making library from DIA-Umpire SE track using FragPipe

### ISSUE THREAD

**Issue by sjr24** [Nesvilab/FragPipe#311]
Greetings,

The following error occurs during SpecLibGen of the DIA-U track in FragPipe.

SpecLibGen [Work dir: C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU]
C:\ProgramData\Anaconda3\python.exe -u C:\Users\srice\Downloads\FragPipe-14.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py C:\Users\srice\Downloads\FragPipe-14.0\2021-02-24-decoys-reviewed-contam-UP000005640.fas C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3_calibrated.mgf;C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3_uncalibrated.mgf;C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_calibrated.mgf;C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_uncalibrated.mgf;C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_calibrated.mgf;C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_uncalibrated.mgf C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU True unused use_easypqp ciRT 7 "--rt_lowess_fraction 0.01"
Using (un)calibrated.mgfs.
Spectral library building
Commands to execute:
'C:\ProgramData\Anaconda3\Scripts\easypqp.exe' convert --pepxml 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\interact.pep.xml' --spectra 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_uncalibrated.mgf' --exclude-range -1.5,3.5 --psms 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.psmpkl --peaks 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.peakpkl
'C:\ProgramData\Anaconda3\Scripts\easypqp.exe' convert --pepxml 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\interact.pep.xml' --spectra 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_uncalibrated.mgf' --exclude-range -1.5,3.5 --psms 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.psmpkl --peaks 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.peakpkl
'C:\ProgramData\Anaconda3\Scripts\easypqp.exe' convert --pepxml 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\interact.pep.xml' --spectra 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3_calibrated.mgf' --exclude-range -1.5,3.5 --psms 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.psmpkl --peaks 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.peakpkl
'C:\ProgramData\Anaconda3\Scripts\easypqp.exe' library --psmtsv 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\psm.tsv' --peptidetsv 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\peptide.tsv' --rt_reference 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\irt.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.01 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.psmpkl' 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.psmpkl' 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.psmpkl' 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.peakpkl' 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.peakpkl' 'C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.peakpkl'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
easypqp, version 0.1.10
Executing ['C:\\ProgramData\\Anaconda3\\Scripts\\easypqp.exe', 'convert', '--pepxml', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\interact.pep.xml', '--spectra', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_uncalibrated.mgf', '--exclude-range', '-1.5,3.5', '--psms', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.psmpkl', '--peaks', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.peakpkl']
Executing ['C:\\ProgramData\\Anaconda3\\Scripts\\easypqp.exe', 'convert', '--pepxml', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\interact.pep.xml', '--spectra', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_uncalibrated.mgf', '--exclude-range', '-1.5,3.5', '--psms', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.psmpkl', '--peaks', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.peakpkl']
Executing ['C:\\ProgramData\\Anaconda3\\Scripts\\easypqp.exe', 'convert', '--pepxml', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\interact.pep.xml', '--spectra', 'C:\\Users\\srice\\Downloads\\HeLa_Evosep_diaPASEF_RAW\\diaU\\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3_calibrated.mgf', '--exclude-range', '-1.5,3.5', '--psms', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.psmpkl', '--peaks', '20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q3.peakpkl']
EasyPQP convert error BEGIN
Info: Converting C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\interact.pep.xml.
Info: Parsing run 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1.
Info: Parsing pepXML.
Info: Generate theoretical spectra.
Info: Processing spectra from file C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_uncalibrated.mgf.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\main.py", line 58, in convert
    psms, peaks = conversion(pepxmlfile, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\convert.py", line 606, in conversion
    peaks = read_mgf(spectralfile, psms[['scan_id', 'modified_peptide', 'precursor_charge']], theoretical, max_delta_ppm)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\convert.py", line 474, in read_mgf
    mz_intensity_array = tims_data[scan_id]
KeyError: 12
EasyPQP convert error END
EasyPQP convert error BEGIN
Info: Converting C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\interact.pep.xml.
Info: Parsing run 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2.
Info: Parsing pepXML.
Info: Generate theoretical spectra.
Info: Processing spectra from file C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_uncalibrated.mgf.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\easypqp.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\main.py", line 58, in convert
    psms, peaks = conversion(pepxmlfile, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\convert.py", line 606, in conversion
    peaks = read_mgf(spectralfile, psms[['scan_id', 'modified_peptide', 'precursor_charge']], theoretical, max_delta_ppm)
  File "c:\programdata\anaconda3\lib\site-packages\easypqp\convert.py", line 474, in read_mgf
    mz_intensity_array = tims_data[scan_id]
KeyError: 1
Traceback (most recent call last):
  File "C:\Users\srice\Downloads\FragPipe-14.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 849, in <module>
    main_easypqp()
  File "C:\Users\srice\Downloads\FragPipe-14.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 675, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Can you send us the whole log?

Best,

Fengchao

**Comment by sjr24** [comment]
Fengchao,

I attached the log file, diau log file, and an easypqp log file.

Thanks,

Shawn

**Comment by fcyu** [comment]
The log file was truncated by GitHub. Can you zip it and attach it? But I have a question: is your data from diaPASEF since your folder name is `HeLa_Evosep_diaPASEF_RAW`?

Best,

Fengchao

**Comment by sjr24** [comment]
Yes, it is diaPASEF.

**Comment by fcyu** [comment]
OK. DIA-Umpire does not support diaPASEF. 

Best,

Fengchao

**Comment by sjr24** [comment]
Zipped file is attached.  Is the workflow not compatible with diaPASEF?

**Comment by fcyu** [comment]
Correct, the workflow is not compatible with diaPASEF.

Best,

Fengchao

**Comment by sjr24** [comment]
Thanks for the information.

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao

**Comment by fcyu** [comment]
Sorry that I cannot find the zip file. Can you send them to yufe@umich.edu?

Thanks,

Fengchao

**Comment by sjr24** [comment]
Sorry,  I left the lab.  I’ll send it later this evening.

Thanks,
Shawn

________________________________

**Comment by guoci** [comment]
@sjr24 can you also send 
```
C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q1_uncalibrated.mgf
C:\Users\srice\Downloads\HeLa_Evosep_diaPASEF_RAW\diaU\20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450_Q2_uncalibrated.mgf
```

**Comment by sjr24** [comment]
I am using data from Meier et al. 2020 (diaPASEF keyword) downloaded from pride db.  If you can not find I can send.

Thanks,
Shawn

________________________________

**Comment by anesvi** [comment]
We have that data, but not able to get the same error.

Sjr24, how did you convert the data? When I tested with DIA-Umpire, I got better results than what I see in your log file. I think you converted with a very aggressive peak filtering or something. At any rate,  we are not “officially” supporting diaPASEF with DIA-Umpire at this point because it does not take IM (so suboptimal performance), although it works.

Best
Alexey

**Comment by sjr24** [comment]
Alexey,

Greetings.  I used ProteoWizard to convert the files.  Could you send me instructions on how you converted the files and how you ran the files with DIA-U?  I can see if it works for me.

Thanks,
Shawn

**Comment by anesvi** [comment]
I don’t think I can send a screenshot of my Proteowizard settings via github. But I just selected mzXML, and checkbox ‘sum ion mobility scans’. Vendor peak picking was specified as usual.

In DIA-Umpire, use Max missed Scan= 1, AutomaticBG=yes, MS1 and MS2 SN  set to 2.

If need more help here, contact by email, as this is a bit untested territory at this point.

Best
Alexey

**Comment by sjr24** [comment]
Thanks Alexey, it worked.  There was an issue with building a library using fragpipe since the Q2 file failed calibration.  The uncalibrated .mgf file was not able to be used.  A library was able to be generated when I manually ran easypqp with the Q1 and Q2 files.

Thanks,
Shawn

**Comment by anesvi** [comment]
I will ask Gui Ci to add a check in FragPipe. But as I said, DIA-Umpire for DiaPASEF need to be extended to read IM and use it to constrain peak tracing. If people convince me there is a need for that, we can do it... just a question of resources/priorities at this point.
Alexey


Sent from my iPhone

On Mar 2, 2021, at 9:08 AM, sjr24 <notifications@github.com> wrote:

﻿
External Email - Use Caution

Thanks Alexey, it worked. There was an issue with building a library using fragpipe since the Q2 file failed calibration. The uncalibrated .mgf file was not able to be used. A library was able to be generated when I manually ran easypqp with the Q1 and Q2 files.

Thanks,
Shawn
