### ISSUE TITLE
merging psm.tsv files after analysis

### ISSUE THREAD

**Issue by raphaelhtdi** [Nesvilab/FragPipe#312]
Hi there, is there a way to merge the psm.tsv files post-analysis? There doesn't seem to be a common denominator I could use to merge it myself, or am I missing sth? Thanks for your help
Raphael

**Comment by raphaelhtdi** [comment]
sorry, maybe I should add, I'd like to compare retention times and ion mobility.
Could also use the quant.csv file.

**Comment by fcyu** [comment]
You can let psm.tsv have the PSMs from multiple runs by setting the runs in the same experiment. 

Please note that the retention time and ion mobility in psm.tsv are from MS2, not from the traced MS1 apex. If you want MS1 apex retention time and ion mobility, have to use _quant.tsv file.

Best,

Fengchao

**Comment by raphaelhtdi** [comment]
thanks for your prompt response, Fengchao. Ok, I see. Basically this means we have to search each dataset (at least)  twice to get comparable information for RT and IM which is kind of impractical especially for bigger searches (hundreds to thousands of runs). 
Do you think you could include RT and IM information in the combined_peptide.tsv ?

**Comment by fcyu** [comment]
I am sorry that I don't get the reason of searching the dataset twice?

> Do you think you could include RT and IM information in the combined_peptide.tsv ?
Yes, I can let IonQuant to include this information. But have to wait for the next release.

Best,

Fengchao

**Comment by anesvi** [comment]
Combined_peptide.tsv has peptides, each can be identified from multiple charge states (and modifications are collapsed too). So what retention time/IM one would put there? That would belong to ion-level file?

**Comment by fcyu** [comment]
Good point! A combined_ion.tsv would be more suitable for it.

Best,

Fengchao

**Comment by anesvi** [comment]
Which we do not generate…. Do we?

**Comment by fcyu** [comment]
No we do not generate it now. But we can add if it is helpful.

Best,

Fengchao

**Comment by anesvi** [comment]
Raphaelhtdi:

Could you contact us directly (e.g. at nesvi at med.umich.edu) and explain what you are trying to do? That way we can see how to best support it in a future release of the tools.

Best
Alexey
