### ISSUE TITLE
There are errors in running EasyPQP

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#315]
Hi Guo Ci,

Some users report two errors from EasyPQP:
![1](https://user-images.githubusercontent.com/6926299/109971653-79925700-7cc4-11eb-9769-bfb2484c909a.png)
![2](https://user-images.githubusercontent.com/6926299/109971660-7ac38400-7cc4-11eb-863b-8e1dd13c372f.png)

Can you take a look when you have time?

Thanks,

Fengchao

**Comment by guoci** [comment]
This is a EasyPQP issue and should be posted in that repo https://github.com/grosenberger/easypqp
Also, post the pep.xml file.

**Comment by guoci** [comment]
transfered to grosenberger/easypqp/issues/50
