### ISSUE TITLE
SpecLib script seems pairing pep.xml with wrong spectral file

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#316]
Hi Guo Ci,

Some users report that the SpecLib script (gen_con_spec_lib.py) seems pairing interact-*.pep.xml with wrong spectral file. Following is a screenshot from the users.
![3](https://user-images.githubusercontent.com/6926299/109972503-5fa54400-7cc5-11eb-9697-46c009575aca.png)

Can you take a look when you have time?

Thanks,

Fengchao

**Comment by guoci** [comment]
Please test the fix, if it works, close this.

**Comment by guoci** [comment]
Tested at 02179b093176387e52740706dae0709b604cd002, closing.
