### ISSUE TITLE
Philosopher filter reads subfolders

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/FragPipe#318]
I just discovered that Philosopher will read all pep.xml files from subfolders

E.g. I have
D:\Chick2015\March7_1file_m35\clevel-2\interact.pep.xml
D:\Chick2015\March7_1file_m35\interact.pep.xml

I run in D:\Chick2015\March7_1file_m35 and only want to use 
D:\Chick2015\March7_1file_m35\interact.pep.xml

but it will read from the subfolder D:\Chick2015\March7_1file_m35\clevel-2 as well.
I think it is a bit dangerous. Took me a while to figure out why I get twice as many PSMs as I expected

**Comment by prvst** [comment]
which command did you use?

**Comment by anesvi** [comment]
filter

**Comment by prvst** [comment]
Fixed. Added to v3.6.0
