### ISSUE TITLE
Restricted semi-specific searches with fixed N/Cterm (like MQs SemiSpecFreeNt/Ct)

### ISSUE THREAD

**Issue by kabalak** [Nesvilab/FragPipe#321]
A possible desired feature from people working on N-terminomics could be to have semi-sided restriction of the semi-specific searches like in MaxQuants SemiSpecFreeNt setting for the digestion, where exact tryptic specificity for the C-terminus of each peptide is assumed, but one sided a semi-specific search is performed.

Or is the completely open semi-specific search im MSFragger so effective, that such an option in FragPipe would be not necessary?

**Comment by danielgeiszler** [comment]
Hi Fatih,

Can you elaborate a bit more on what it is you’re looking for?

If you need C-terminal K/R and an N-term that can move freely, I think all you need is a regular semitryptic search.

**Comment by kabalak** [comment]
I am aware of that possibility, but it is dramatically improving the "yield" of such N-terminomics experiments, if we could set the fixed C-terminal specificity to the digestion protease - at least this is my personal experience with MaxQuant. In N-termini experiments we enrich proteolytically processed N-termini (e.g., https://doi.org/10.1074/mcp.TIR119.001560) which are totally variable on only one side - restricting the search space for the C-terminal side to be rigidly specific will normally improve the resultset greatly.

If I search semi-specifically with MSFragger it would look for both sides to be semi-specific within the given 5-50 AA default window, I guess?

**Comment by fcyu** [comment]
Yes, MSFragger looks for the semi-specific digestion on both sides. Restricting it to single side should be able to increase the sensitivity. We will discuss internally to see how and when to implement this functionality. Right now, you have to let MSFragger search for both sides. Evey so, I guess MSFragger still has high sensitivity than MaxQuant because MaxQuant only looks for 0 missed cleavage in semi-specific searching.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, we can add such an option.
We can introduce SEMI-NTERM which will require that the peptide tryptic on Cterm but OK to be semi on N-term. I think it should be feasible,
We can add in the next version
Alexey

**Comment by kabalak** [comment]
> Yes, MSFragger looks for the semi-specific digestion on both sides. Restricting it to single side should be able to increase the sensitivity. We will discuss internally to see how and when to implement this functionality. Right now, you have to let MSFragger search for both sides. Evey so, I guess MSFragger still has high sensitivity than MaxQuant because MaxQuant only looks for 0 missed cleavage in semi-specific searching.
> 
> Best,
> 
> Fengchao

Nej Fengchao,

during semi-specific searches MaxQuant does **not** apply any such missed cleavages filters at all! I have personal datasets with up to 7-8 missed cleavages with alternative proteases and up to 4 with trypsin, so there is not even the possibility to regulate this in MQ (at least in v1.6.17.0). In theory it could be as many missed cleavages as your search window for the semi-specific window allows for.

**Comment by kabalak** [comment]
> Yes, we can add such an option. We can introduce SEMI-NTERM which will require that the peptide tryptic on Cterm but OK to be semi on N-term. I think it should be feasible, We can add in the next version Alexey

Sounds great - to be future proof, I would advise to make it fully flexible to allow also for semi-specific restrictions for C-terminal enrichment fans (think of Carboxypeptidases for example)..

**Comment by fcyu** [comment]
Added in MSFragger 3.4 and FragPipe 17.0
