### ISSUE TITLE
4 socket cpu server issue

### ISSUE THREAD

**Issue by chbang454544** [Nesvilab/FragPipe#322]
Hi !
I ask you a question.
On ubuntu 18.04 I unzup file fragpipe14.0 and tried to run it, but I got an error. Is there a solution?
[java version ==1.8]

That server is a 4 socket CPU.

![image](https://user-images.githubusercontent.com/80405953/110643659-ad570a80-81f7-11eb-8f75-590edbd53a7f.png)

**Comment by chbang454544** [comment]
frag-pipe jre12.2 has the same problem. .....

**Comment by chbang454544** [comment]
> FragPipe가 CPU 코어를 성공적으로 가져올 수없는 것 같습니다. 4 소켓 CPU 때문일 수 있습니다. 불행히도 우리는 좋은 해결책이 없습니다.
> 
> 베스트,
> 
> Fengchao

Is there any other way?
Thank you for answer!

**Comment by fcyu** [comment]
Unfortunately, no for now.

Best,

Fengchao

**Comment by guoci** [comment]
Please try the following fix https://drive.google.com/file/d/1gD_qTlC4DrXbmiOVUdv6Nsisv8fnYP6M/view?usp=sharing
May I know how many processors you have?

**Comment by chbang454544** [comment]
> Please try the following fix https://drive.google.com/file/d/1gD_qTlC4DrXbmiOVUdv6Nsisv8fnYP6M/view?usp=sharing
> May I know how many processors you have?

intel Xeon Gold 6252N * 4ea   
Total 192Thread 

Fragpipe will be executed.
Thank you very much.
