### ISSUE TITLE
Visualization of annotated spectra

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#323]
Dear FragPipe developer team, 
We have done enrichment for o-linked glyco proteome and using FragPipe to search the raw files. Thank you very much for this amazing tool: the search was fast and generated a lot of hits. However, I have struggles visualizing the annotated spectra.   It seems in PDV I can't do visualization for the o-linked glyco results yet. Is there any other visualization tool that I can use?
Thanks

**Comment by dpolasky** [comment]
Hi fazeliniah,
The short answer is no, we use PDV primarily, even for O-glyco studies. In our experience, HCD fragmentation of O-glycopeptides tends not to generate many ions with glycan fragments remaining, so there is not much to visualize other than the peptide sequence ions anyway (and that's mostly what we've looked at). For hybrid methods, I think the O-glyco ions are not well represented (I believe PDV currently only shows Y-type ions for the core N-glycan structure, which includes some overlap with potential O-glycan ions, but not all). What kinds of fragment ions are you looking to visualize specifically?

**Comment by fazeliniah** [comment]
Thanks for your quick reply. You were right. We are only doing HCD fragmentation of O-linked glycopeptides. One way that we would like to validate the glyco enrichment MS results is by visualizing the spectra and checking for Oxonium ions. I know MsFragger is looking for the diagnostic fragments masses but it would be nice to visualize the final annotation and see the diagnostic peaks.

**Comment by dpolasky** [comment]
that makes sense! It might be possible to ask the PDV developers to add an option to display oxonium (or other diagnostic) ions - not sure if they'd be interested, but (in theory) they should be pretty straightforward to annotate. I've also found that the oxonium ions are usually intense enough in HCD data that I can recognize them without needing special annotation, but that does mean looking at spectra one by one

**Comment by fazeliniah** [comment]
It is one of the "enhancements" I requested on PDV page. Hopefully it will be available in a near future.
