### ISSUE TITLE
Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by rnirujogi** [Nesvilab/FragPipe#326]
[
[log_2021-03-14_23-26-40.txt](https://github.com/Nesvilab/FragPipe/files/6140547/log_2021-03-14_23-26-40.txt)
](url)

Dear Developers,

Could you advise on this error.
Many thanks,
Raja

**Comment by fcyu** [comment]
Hi Raja,

Could you explain to me why you selected `DIA` for the data type in MSFragger tab?

Thanks,

Fengchao

**Comment by rnirujogi** [comment]
Hi Fengchao,

Thanks for your reply. 
The previous job I set is for DIA even that failed (See the log: 
[log_2021-03-14_19-24-54.txt](https://github.com/Nesvilab/FragPipe/files/6142753/log_2021-03-14_19-24-54.txt))

However, I think I disabled diaumpire (In line 842 in my DDA log) but not sure If I am missing something. Any help in configuring this correctly would be greatly appreciated.

Best regards,

Raja

**Comment by fcyu** [comment]
If you are using DIA-Umpire, and then MSFragger, you need to set `data type` to DDA for MSFragger because the pseudo scans from DIA-Umpire is like DDA. DIA in MSFragger is for the workflow without DIA-Umpire.

Best,

Fengchao

**Comment by rnirujogi** [comment]
Hi Fengchao,

Sorry, I am bit confused with your reply. For conventional DDA LFQ search, I can either choose default closed search or LFQ-MBR in Workflow tab in Fragpipe.

If I need to do a search for DIA data, can I simply select DIA-Umpire or DIA-Umpire_SpecLib? or this is what you are referring above using DIA-Umpire and then MSFragger that I need to set **data type** to DDA for MSFragger. If so, where do I find set data type to DDA in MSFragger tab? I can't find this option in this tab. 

I am using Fragpipe version v15.0.

Thanks,
Raja

**Comment by fcyu** [comment]
That is correct. If you want to search DIA data, you can use DIA-Umpire_SpecLib workflow. 

Following is what the `data type` dropdown menu looks like
![image](https://user-images.githubusercontent.com/6926299/111187489-687dfb80-858a-11eb-8baa-67d764d24965.png)

Best,

Fengchao

**Comment by rnirujogi** [comment]
Perfect. Thank you so much.

Bet,
Raja
