### ISSUE TITLE
raw-support instead of mzML also for PTM-Prophet?

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#327]
Dear FragPipe Developer Team, 

I discovered the "labile ADP-Ribsoliation" workflow in FP15 and wanted to give it a try immediately. I only then discovered, that PTM-Prophet is only possible if you start from mzML. 
Of course this is doable but I was wondering if you also plan to upgrade PTM-Prophet to make it also compatible with native formats?

Best regards - 
jonas

**Comment by fcyu** [comment]
Hi Jonas,

We are not maintaining PTM-Prophet. Could you contact PTM-Prophet develop team regarding supporting the native format?

Best,

Fengchao

**Comment by jjGG** [comment]
Hei Fengchao, 

Yes of course I can forward the question to the PTM-Prophet devel team. But I did not find it on the NesviLab github.. or is this the same like PTM-Shepherd?

Best regards - jonas

**Comment by anesvi** [comment]
We should ask the TPP team to add MGF support. Because when using RAW as input, we create MGF files in the process in our pipeline, and can feed those to PTM-Prophet if it is extended to support it
Alexey
