### ISSUE TITLE
MSFragger output

### ISSUE THREAD

**Issue by ekvall93** [Nesvilab/FragPipe#328]
Hi, 

I'm using DIA-UMPIRE + MSFRAGGER and stop there. I have selected TSV_PEPXML_PIN as output format. However, I have noticed that the TSV and PIN files get different modification info i.e., the same peptide with the same scan number get [147.035@25] in the pepXML and 25M(15.9949) in the TSV and PIN file.  Is there some specific option I should select to get the same modification in the PIN/TSV as the pepXML?

Here's an example notebook:

https://github.com/ekvall93/percolatorQ/blob/main/compare_tsv_pepXML.ipynb

best regards,

Markus Ekvall

**Comment by fcyu** [comment]
Hi Markus,

They are the same because the mass in pepXML equals amino acid mass + modification mass.

Best,

Fengchao
