### ISSUE TITLE
reuse index

### ISSUE THREAD

**Issue by mcundell** [Nesvilab/FragPipe#329]
Hi,

Alexey kindly pointed out that the time to build the index during searches is the same for 1 file or hundreds of files.  Also, if I understood correctly, that the index could be reused for any analysis using the same sequence database and search parameters?  

For testing I would like to process a few experiments using the same database and search parameters (including split database). Of course I could load the multiple experiments up at the same time and include them in a single search.  However, I would like to test reusing the index as we tend to process our data the same way for every new experiment.  How does one reuse the index? or is this not possible and i got the wrong idea? At the end of a search the pepindex gets deleted from 'split_peptide_index_tempdir'.  

Thank you for your help.

Best,

Michael

**Comment by fcyu** [comment]
Hi Michael,

Yes, MSFragger will reuse the index (*.pepindex), and it is fully automatic. You don't need to worry about it.

Best,

Fengchao

**Comment by mcundell** [comment]
Hi,

Sorry, I am not understanding.  The same pepindex is used when one searches many files together.  But what if I do one search (pepindex gets deleted once the search is done), close fragpipe, then wish to perform the same search (ie with the same database/parameters) and hence use the same pepindex but on some different files.  I dont see how the pepindex is reused in this latter case as it isnt stored anywhere.  

Best,

Michael

**Comment by fcyu** [comment]
Hi Michael,

pepindex won't be deleted unless users do that. MSFragger will reuse it if it is in the same folder of the fasta file.

Best,

Fengchao

**Comment by fcyu** [comment]
Alexey reminds me that if you are using the split database function, the pepindex from the split fasta cannot be reused because FragPipe creates temp folders, and puts each split fasta and it peptidex file in it. After search, those temp folders are deleted.

Best,

Fengchao

**Comment by mcundell** [comment]
I suspected it might be caused by the split.  I was just processing a test with no split.  If possible, that would be a nice feature to have (the option to be able to keep the pepindex on split databases).  Thank you for helping me understand this one and supporting my tests.

Best,

Michael

**Comment by anesvi** [comment]
Using SSD should help with the speed of building and reading the index in the memory.
But for regular HLA searches, I don’t think that index building is a time consuming steps. On my desktop at least. And you do not need Split for HLA unless you go above max 25 peptide length or put more PTMs than our defaults.

Best,
Alexey

**Comment by mcundell** [comment]
Thanks both.  Thats good to know.
