### ISSUE TITLE
Command line execution of fragpipe

### ISSUE THREAD

**Issue by xuel12** [Nesvilab/FragPipe#330]
I am trying to replicating the workflow of fragpipe step-by-step.

For the open search, after crystal-C, peptideprophet and before proteinprophet, there is a cmd called Rewrite pepxml. Can anyone explain what is happening there? Is there a way to run this cmd in scripts? When I try something like "java -cp lib/* com.dmtavt.fragpipe.util.RewritePepxml ", the error says "Error: Could not find or load main class com.dmtavt.fragpipe.util.RewritePepxml".

By the way, is there a way to run Fragpipe without GUI? Sorry if I missed it somewhere in your website.

Many thanks!
Leo

**Comment by fcyu** [comment]
Hi Leo,

That step is correcting the path of the spectral file in interact-*.pep.xml. You don't need it if you are not running PTM-Prophet.

There is no way to run FragPipe without GUI. But you can use x-forwarding (https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html) if you like.

Best,

Fengchao

**Comment by xuel12** [comment]
Thanks for quick response Fengchao. I didn't run PTM-prophet in Fragpipe but the rewrite pep.xml still executed.

More interestingly, having that extra step in Fragpipe makes the interact-pep.xml different, althought the *_c-pep.xml are the same. The steps before are MSfragger and Crystal-C, I am doing open-search in order to find new chemical modification.

Do you have any suspect that I should look for?

Thanks,
Leo
________________________________
发件人: Fengchao ***@***.***>
发送时间: 2021年3月19日 3:17
收件人: Nesvilab/FragPipe ***@***.***>
抄送: Liang Xue ***@***.***>; Author ***@***.***>
主题: Re: [Nesvilab/FragPipe] Command line execution of fragpipe (#330)


Hi Leo,

That step is correcting the path of the spectral file in interact-*.pep.xml. You don't need it if you are not running PTM-Prophet.

There is no way to run FragPipe without GUI. But you can use x-forwarding (https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html) if you like.

Best,

Fengchao

―

**Comment by fcyu** [comment]
Hi Leo,

FragPipe always rewrite interact-*.pep.xml just in case PTM-Prophet will be run. If you won't run PTM-Prophet, you can skip this step in your commands.

And yes, it rewrites interact-*.pep.xml, not *_c-pep.xml which is taken by PeptideProphet to generate interact-*.pep.xml.

I think there is no issue according to your information.

Best,

Fengchao
