### ISSUE TITLE
FragPipe/MSFragger Precursor Tolerance Question

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#334]
Hello,
I have a question related to precursor mass tolerances in FragPipe/MSfragger. I have previous experience with SEQUEST and Percolator in Proteome Discoverer software. I have typically used no greater than 5ppm as the precursor tolerance. I know there is some debate on this topic, but I have a few reasons for this narrow window. First, work from David Muddiman’s lab showed false identification of unmodified(amidated) asparagine-containing peptides as deamidated peptides, which occured in 5-10ppm mass accuracy range. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3976439/ Second, it's possible that post-search scoring could be impacted, but I haven’t noticed any issues with Percolator scoring at these time tolerances. For example, I tested a 20ppm vs 5ppm tolerance with SEQUEST/Percolator. After filtering PSMs @ <1% FDR, but with a mass accuracy > 5 - 10 ppm, I would almost exclusively find low quality matches (though I suppose they could still be correct).

In FragPipe, I noticed the workflow defaults for precursor tolerance in MSFragger are usually between 20 – 50ppm. In past versions of FragPipe, I thought the precursor tolerances were updated during the main search based on the calibration and parameter optimization steps. However, in MSFragger 3.2, this no longer appears to be the case? (only the fragment mass tolerance appears to be updated).

This bring up the question of whether the wider precursor tolerance window is required for MSFragger and PeptideProphet. Is this wider tolerance to allow sufficient data for accurate mass scoring in PP?

Thanks for your thoughts on this topic.
Best,
Todd

**Comment by fcyu** [comment]
Hi Todd,

I don't think there is any problem to use 20 ppm or even narrower one for MSFragger and PeptideProphet. And MSFragger never updates precursor lower and upper tolerance, which is the actual tolerance used in search. It updates precursor true tolerance, which is used as a tiebreaker, in the open search, though.

Best,

Fengchao

**Comment by anesvi** [comment]
Hi Todd,

To add to this, I usually use 20ppm. Sometimes 10ppm. For simple searches (tryptic only, and especially if small database like yeast or smaller)  using 50ppm may actually help. But we do get this question a lot, so I think we should update all defaults to 20ppm. And if you have a large search space (phospho searchers, nonspecific), and you use mass calibration, 10ppm should be fine, I never used below 10ppm.

Alexey

**Comment by enonimos** [comment]
Hi Fengchao and Alexey,
 
Thank you for the recommendations and clarification. And especially for small databases, this is a good point I forgot about.  In this case, I can imagine there may not be enough precursor candidates at 5ppm to provide accurate scoring.

Cheers!
