### ISSUE TITLE
Issue with PeptideProphet and interact- files

### ISSUE THREAD

**Issue by plbaldoni** [Nesvilab/FragPipe#336]
Hi there,

I am using MSFragger on the command line with PeptideProphet for validation of peptide hits. I have gotten the following error message when calling IonQuant:

> IonQuant version IonQuant-1.5.5
Batmass-IO version 1.22.1
timsdata library version timsdata-2-7-0
(c) University of Michigan
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_252, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 57 GB memory
2021-03-24 01:15:01 [WARNING] - ionmobility = 0 but the spectral file is from timsTOF (.d): /Users/baldoni/data/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-A10_1_2051.d. Change to ionmobility = 1
Cannot read file /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/psm.tsv.

After skimming through the log, I noticed the following:

>  file 1: /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.pepXML
Unknown file type. No file loaded./Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.d
WARNING: cannot open data file /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.d in msms_run_summary tag... unrecognized extension .d, trying .mzML ...
WARNING: CANNOT correct data file /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.mzML in msms_run_summary tag...
Unknown file type. No file loaded./Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.d
WARNING: cannot open data file /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.d in msms_run_summary tag... unrecognized extension .d, trying .mzML ...
WARNING: CANNOT correct data file /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.mzML in msms_run_summary tag...
 processed altogether 12397 results
INFO: Results written to file: /Users/baldoni/msfragger/output/PXD010012/HeLa_5min_raw/interact-20180924_50ngHeLa_1.0.25.1_Hystar5.pep.xml

What exactly is going on here? 

Also, shouldn't the results be written to `interact-20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-B4_1_2057.pep.xml` instead of `interact-20180924_50ngHeLa_1.0.25.1_Hystar5.pep.xml`? All the 'interact' files from other runs of the same experiment are being written to the same .pep.xml file. I did not observe this truncation on the file name in other successful searches.

Thanks!

**Comment by fcyu** [comment]
Thanks for your interest in our tools. I think there are two issues

1. You need to set `--ionmobility 1` if you are using ddaPASEF data (.d). please find all of the options from https://github.com/Nesvilab/IonQuant
2. The file name cannot have `.` that breaks PeptideProphet.

Best,

Fengchao

**Comment by plbaldoni** [comment]
Thanks, Fengchao.
