### ISSUE TITLE
#Philosopher issue: "Cannot decode packed binary"

### ISSUE THREAD

**Issue by DianaSamodova** [Nesvilab/FragPipe#337]
Dear Alexey,
I am trying to run TIMS Tof data with the FragPipe, however, getting the same error again again: "FATA[16:01:37] Cannot decode packed binary. XML syntax error on line 1531: invalid character entity &_additional_ (no semicolon)". Can you, please, help with this? Thank you in advance.
Kind regards,
Diana

**Comment by fcyu** [comment]
Hi @prvst ,

This error should be from Philosopher. Could you take a look when you have time?

Best,

Fengchao

**Comment by anesvi** [comment]
Can you send us the full log?
You can email me (nesvi at med.umich.edu) and I will discuss with Felipe  @prvst
