### ISSUE TITLE
Python 3.7+ is required for msfragger_pep_split.py

### ISSUE THREAD

**Issue by caetera** [Nesvilab/FragPipe#338]
Hello,
`msfragger_pep_split.py` uses `reconfigure` method for stdout and stdin, this method was introduced only in python 3.7 and, thus, the script fails for earlier versions of python.
Please, consider if you want to update requirements\installation instructions.
Otherwise the small patch below seems to work well for python 3.1 and above. Sorry, could find which repo to PR.
```
import io

if sys.version_info[1] > 0 and sys.version_info[1] < 7: #versions 3.1 - 3.6
	sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
	sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
elif sys.version_info[1] > 6: #version 3.7+
	sys.stdout.reconfigure(encoding='utf-8')
	sys.stderr.reconfigure(encoding='utf-8')
else:
	raise Exception("Python 3.1 or above is required")
```

**Comment by guoci** [comment]
thanks @caetera, fixed at 9c9fe475daac3b1a91cebc2176fbe4335a8c9484
