### ISSUE TITLE
Could I a generate deisotoped MGF file without running MSFragger search process?

### ISSUE THREAD

**Issue by zhiyuan-Cheng** [Nesvilab/FragPipe#340]
Dear FragPipe/MSFragger Developer Team,
I have recently read your paper "Fast Deisotoping Algorithm and Its Implementation in the MSFragger Search Engine, J. Proteome Res. 2021, 20, 498−505." which said that "Raw data deisotoped with our method in MSFragger can also be saved as an MGF file and searched with other database search programs or used for other purposes". So I hope to use FragPipe&MSFragger to obtain a deisotoped MGF file for further analysis.
By checking "Write calibrated MGF", I can get a deisotoped MGF file after MSFragger searching. However, is it possible to run only the deisotope process instead of the entire search process?
Thanks and best regards,
Zhiyuan

**Comment by fcyu** [comment]
No, you cannot.

Best,

Fengchao

**Comment by zhiyuan-Cheng** [comment]
Thank you for your reply!

Sincerely,

Zhiyuan
