### ISSUE TITLE
Error during initiation of main search/missing calibrated files

### ISSUE THREAD

**Issue by biomscholz** [Nesvilab/FragPipe#344]
Dear developer team,

I'm trying to re-analyze some data with Fragpipe 15 (default labile_phospho workflow) that I have previosuly succesfully analyzed with Fragpipe 14. Sadly, Frapipe crashes each time the main search starts. I noticed that the mzbin_calibrated files are created but are deleted when MSfragger begins working on slice 1. Also, the log file automatically created during processing is empty. The log file below was exported manually.
I went back to Fragpipe 14 (with MSFragger 2.4) but surprisingly it crashed as well. So far I have tried it on three different computers and all the time I get the same error. I was suspecting the latest Java update to be the culprit, so I tried Fragpipe bundled with its own JRE but without success.  Could this error be caused by an incompatibility  with the latest version of  Windows (20H2, build 19042.906) or am I missing something obvious?

Best,
Martin

[log_2021-03-31_11-28-28.txt](https://github.com/Nesvilab/FragPipe/files/6242265/log_2021-03-31_11-28-28.txt)

**Comment by fcyu** [comment]
Hi Martin,

This is due to a known bug. The workaround for now is put some fake masses, such as `1/2`  to 'diagnostic fragment masses'. 

Best,

Fengchao

**Comment by biomscholz** [comment]
The workaround worked fine. Thanks a lot!

**Comment by fcyu** [comment]
You are welcome.
