### ISSUE TITLE
"Not a valid pathDir for Bruker data" - bruker data, fragpip v14.0

### ISSUE THREAD

**Issue by GregStacey** [Nesvilab/FragPipe#345]
Hello, I'm trying to analyze one Bruker file with Fragpipe v14.0 on Ubuntu (details below).

Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 5.4.0-58-generic
Architecture: x86-64

Unfortunately I almost immediately get the above error ("Not a valid pathDir for Bruker data"). I checked that the quoted path /home/msfragger/Desktop/Aicha_MSFragger/bruker/P02-5S2_A8_01_6507.d is a real path on the machine, so I'm unsure where to go next. Any help would be appreciated!

**Comment by fcyu** [comment]
Can you send us the screenshot of your `/home/msfragger/Desktop/Aicha_MSFragger/bruker/P02-5S2_A8_01_6507.d`?

Best,

Fengchao

**Comment by GregStacey** [comment]
Thanks for the quick reply. Screenshot attached.

<img width="957" alt="Screen Shot 2021-04-01 at 11 51 39 AM" src="https://user-images.githubusercontent.com/14293882/113340391-b01dba80-92e0-11eb-9f35-dda98ec09907.png">

**Comment by GregStacey** [comment]
Thanks for the fast reply. Having problems screenshotting over x2go, but here's a picture.

![20210401_115327](https://user-images.githubusercontent.com/14293882/113340779-28847b80-92e1-11eb-83a7-d18fded423b1.jpg)

**Comment by fcyu** [comment]
Is your data from ddaPASEF? I cannot find any tdf and tdf_bin files?

Best,

Fengchao

**Comment by GregStacey** [comment]
Hi Fengchao, thanks again. Our data is not ddaPASEF, just regular MS on a Bruker Q-TOF. I'm guessing that's the problem (?)

**Comment by fcyu** [comment]
Yes, we can only read .d from ddaPASEF. For other data types, you need to convert it to mzML using ProteoWizard. We have a tutorial here (https://msfragger.nesvilab.org/tutorial_convert.html).

Best,

Fengchao

**Comment by GregStacey** [comment]
Thanks again for your help running non-PASEF bruker files.

I see in the link that .d is needed for LFQ. Is it possible to get LFQ quantitation after converting to mzml?

**Comment by fcyu** [comment]
Yes, LFQ can work with mzml files. But we never tested the mzml files from Bruker's non-PASEF data. Please feel free to let us know when you have any questions.

Best,

Fengchao
