### ISSUE TITLE
ValueError: max_workers must be <= 61

### ISSUE THREAD

**Issue by mcundell** [Nesvilab/FragPipe#347]
Hi,

I receive this error when attempting to test process a bigger batch of files which I presume is caused during python split which sets max_workers of concurrent.futures.ProcessPoolExecutor to >61 as mp.cpu_count() ends up the smaller (min) value compared to the length of infiles, but this PC I am using has 64 threads which is more than what is permitted by this python subclass? (https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor):

Is there a simple fix for this? 

python output:
```
>>> import multiprocessing as mp
>>> print(mp.cpu_count())
64
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\Public\Desktop\FragPipe-jre-15.0\fragpipe\tools\msfragger_pep_split.py", line 480, in <module>
    main()
  File "C:\Users\Public\Desktop\FragPipe-jre-15.0\fragpipe\tools\msfragger_pep_split.py", line 475, in main
    combine_results()
  File "C:\Users\Public\Desktop\FragPipe-jre-15.0\fragpipe\tools\msfragger_pep_split.py", line 333, in combine_results
    with concurrent.futures.ProcessPoolExecutor(max_workers=min(len(infiles), mp.cpu_count())) as exe:
  File "C:\ProgramData\Anaconda\lib\concurrent\futures\process.py", line 523, in __init__
    raise ValueError(
ValueError: max_workers must be <= 61
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

**Comment by guoci** [comment]
Please try the following fix:
https://drive.google.com/file/d/1_Uq4U93kDaLpTWiGAOseRSVXVk1Yqll1/view?usp=sharing

**Comment by mcundell** [comment]
Thank you for your time to take a look at this.  I will have to get our IT department to provide the admin rights to get this installed.  I will let you know how we get on as soon as possible..

**Comment by mcundell** [comment]
Hi,

Sorry for the delay.  I attempted v15.1-build4 but hit this error when attempting to process a single file:
  File "C:\Users\Public\Desktop\FragPipe-jre-15.1-build4\fragpipe\tools\msfragger_pep_split.py", line 54, in <module>
    output_file_extension = re.compile(r'^output_file_extension *= *(\S+)', re.MULTILINE).search(params_txt).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by guoci** [comment]
please try this fix: https://drive.google.com/file/d/1dCAfSm_zvV6v96KxE8cUNhlnbUV6mcVk/view?usp=sharing

**Comment by mcundell** [comment]
Thank you.  I think that solved the second issue with v15.1-build4 as this time the search started.  However, I think I returned back to the first issue as after the first split is done I receive this error.  So I think the fix for the first issue in the thread unfortunately did not work?:

```
Traceback (most recent call last):
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 465, in <module>
    main()
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 460, in main
    combine_results()
  File "C:\fragpipe\tools\msfragger_pep_split.py", line 316, in combine_results
    max_workers0 = min(len(infiles), len(os.sched_getaffinity(0)))
AttributeError: module 'os' has no attribute 'sched_getaffinity'
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Thanks for your help.

**Comment by guoci** [comment]
@mcundell that function was added at Python version 3.3. Which Python version are you using?

**Comment by mcundell** [comment]
Hi,  I am using Python 3.8.3

**Comment by guoci** [comment]
@mcundell can you start your Python interpreter, type the following and show me the output?
```
import os
os.sched_getaffinity(0)
```

**Comment by mcundell** [comment]
Hi I get... 

```
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.sched_getaffinity(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

**Comment by mcundell** [comment]
It seems that function is absent from Windows.

**Comment by guoci** [comment]
@mcundell you are right! Link to the fix:
https://drive.google.com/file/d/1ildd0bYSEbfUqzSMcc3ld8u18URG6G5M/view?usp=sharing

**Comment by mcundell** [comment]
Thank you for all your help, that fixed that problem and I got past the DB search.  I hit another error with philosopher but I will open a ticket on the philosopher issues github for that one.  Thanks!
