### ISSUE TITLE
Peptideprophet error - Unrecognized enzyme custom

### ISSUE THREAD

**Issue by tsbatth** [Nesvilab/FragPipe#352]
Hello,

I am trying to run Fragpipe and I have customized the protease specificity. When I try to change the specificity it automatically changes the load rules to "custom" . I have set the cleavage to enzymatic and it seems to process fine until it gets to executing Peptideprophet where I get the following error:

PeptideProphet [Work dir: D:\Data\fragpipetest\test]
D:\fragpipe\tools\philosopher\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --nontt --enzyme nonspecific --decoy rev_ --database D:\Fasta\Human\UP_2020_10\2021-04-12-decoys-contam-UP000005640_9606.fasta.fas --combine HEPG2_TMT_.pepXML
INFO[11:48:30] Executing PeptideProphet  v3.4.13            
ERROR: Unrecognized enzyme custom - please specify enzyme with -E option
 file 1: D:\Data\fragpipetest\test\HEPG2_TMT_.pepXML
FATA[11:48:33] Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 12 remaining tasks

**Comment by fcyu** [comment]
This is a known issue. You have to change the `custom` to `nonspecific`.

Best,

Fengchao

**Comment by tsbatth** [comment]
Thanks for the reply. However whenever I change to "nonspecific" in the GUI, and try to set the specificity, it automatically changes to "custom" so I cannot change it to "nonspecific" . Unless I guess I change it in the .workflow file, but I haven't tried that yet.

**Comment by tsbatth** [comment]
Update: I tried changing it in the .workflow file, but it does not save the enzyme cleavage specificity.

**Comment by fcyu** [comment]
No need to use the dropdown menu. You just need to change `enzyme name` to `nonspecific`. `cut after` and `but not before` can be your enzyme's rule.

![image](https://user-images.githubusercontent.com/6926299/115025777-c0609880-9e8f-11eb-97e1-9da011e1cc95.png)

Best,

Fengchao

**Comment by tsbatth** [comment]
Thank you that fixed the issue!
