### ISSUE TITLE
PTM Shepherd Issues

### ISSUE THREAD

**Issue by tyjrh9** [Nesvilab/FragPipe#353]
Hi there,

A couple things tripped up the code while I was running a fragpipe workflow that included PTM Shepherd analysis:

At the end of an otherwise smooth analysis, I was repeatedly getting this error message as the PTM shepherd module started:

```
PTM-Shepherd version 1.0.0(c) University of Michigan

Using Java 11.0.9.1 on 5116MB memory

Process 'PTMShepherd' finished, exit code: 1
Fatal error: In dataset "XXX" could not find mzData for run XXX-1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks
```

I traced this down to a couple of my .mzML files, for which the extension was written in all lowercase ".mzml" rather than ".mzML". Once I noticed this and edited the extension it worked, but I thought I'd bring this to your attention since the other tools in fragpipe workflow don't seem to be sensitive to this and it's a bit odd it throws an error right at the end.

Second thing:
While troubleshooting the above issue I was running PTMShepherd from the command line and repeatedly hit this roadblock:

```
Creating combined histogram

....


Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at edu.umich.andykong.ptmshepherd.peakpicker.Histogram.mergeHistogram(Histogram.java:61)
        at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:310)
```

 After a bit of troubleshooting I was able to get around this by manually expanding the java memory allocation using `-Xmx`. It would be useful to add this to the PTM shepherd documentation if this is intended behaviour.

**Comment by danielgeiszler** [comment]
Hi,

Thanks for the feedback! The first issue has been fixed for the next release.

As for the second issue, it isn't really a PTM-Shepherd issue. You can run into memory issues with any Java program if you don't specify an amount. Had you tried to run MSFragger the same way, you probably would have run into the same issue. Do you know how much memory you have on your computer?

**Comment by tyjrh9** [comment]
Yes once I gave java a couple GB it worked fine, I just thought it was strange that it’s impossible to know how much it needs except by trial and error.

Thanks for your time!

**Comment by tyjrh9** [comment]
Oh and to answer your question I’m running a Windows VM allocated 32GB ram.

**Comment by dfermin** [comment]
Hi
Sorry to re-open this issue but I'm experiencing this same error:

```
PTMShepherd [Work dir: /data/MS_2024-10-01-001/finalDB_MBR_3ppm3minRT_10topRuns_0.5cor/out]
java -Xmx490G -Dlibs.thermo.dir=/usr/local/apps/MSFragger-4.0/ext/thermo -cp /usr/local/apps/fragpipe/tools/ptmshepherd-2.0.6.jar:/usr/local/apps/fragpipe/tools/batmass-io-1.30.0.jar:/usr/local/apps/fragpipe/tools/commons-math3-3.6.1.jar:/usr/local/apps/fragpipe/tools/hipparchus-1.8/hipparchus-core-1.8.jar:/usr/local/apps/fragpipe/tools/hipparchus-1.8/hipparchus-stat-1.8.jar edu.umich.andykong.ptmshepherd.PTMShepherd "/data/MS_2024-10-01-001/finalDB_MBR_3ppm3minRT_10topRuns_0.5cor/out/shepherd.config"

PTM-Shepherd version 2.0.6
(c) 2022 University of Michigan

Using Java 22 on 501760MB memory

Finding spectral data
        Indexing data from F20230904_1092_uncalibrated
Fatal error: In dataset "F20230904_1092_uncalibrated" could not find mzData for run F20230904_1092_uncalibrated
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping
```

The files are named as `F20230904_1092_uncalibrated.mzML`

Here is the top of my fragpipe-files.fp-manifest file in case that helps:
```
/data/MS_2024-10-01-001/mzML/F20230904_1092_uncalibrated.mzML        F20230904_1092_uncalibrated             DDA
/data/MS_2024-10-01-001/mzML/F20230904_604_uncalibrated.mzML F20230904_604_uncalibrated              DDA
```

In case it helps here is my java version info:
```
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+36-2370)
OpenJDK 64-Bit Server VM (build 22+36-2370, mixed mode, sharing)
```

Any suggestions what migh be wrong? 
Thanks,
Damian

**Comment by danielgeiszler** [comment]
Please upload your log.

**Comment by shenghao003** [comment]
![afdc375cc8d50633ab3189b111629ce](https://github.com/user-attachments/assets/50db2dcf-feda-473b-86e3-3b0671b3d806)
Hello,I have a similar problem. Can you help me see the reason?

Thanks.

**Comment by fcyu** [comment]
Please upgrade all tools to the latest version and rerun from scratch.

Best,

Fengchao

**Comment by shenghao003** [comment]
![image](https://github.com/user-attachments/assets/d65249d0-28cf-4bbd-871c-eec4e49baa40)
Hello , I have updated the tool to the latest version

**Comment by fcyu** [comment]
No, you are not. Please also upgrade FragPipe and Philosopher.

Please also remember to delete all temp files before rerunning.

Best,

Fengchao
