### ISSUE TITLE
Error when loading a Thermo raw file - not recognised

### ISSUE THREAD

**Issue by JesseIL** [Nesvilab/FragPipe#357]
Hi, when trying to load Thermo raw files, from time to time I get an error that it is not a recognised raw data format. See attached screenshots. Any idea? I tried closing FragPipe and reopening and it didn't help.
FragPipe 15, MSFragger 3.2.
<img width="1044" alt="Screen Shot 2021-04-20 at 8 30 33" src="https://user-images.githubusercontent.com/33388490/115342371-d7b2c500-a1b2-11eb-9eeb-442845a48957.png">
<img width="1052" alt="Screen Shot 2021-04-20 at 8 30 26" src="https://user-images.githubusercontent.com/33388490/115342385-dc777900-a1b2-11eb-8af7-d4f7a5ee1cee.png">

**Comment by fcyu** [comment]
Does your MSFragger folder has an `ext` folder and your Linux has mono? If yes, you can try clicking `clear cache and close`.

Best,

Fengchao
