### ISSUE TITLE
Unable to load library "timsdata-2-7-0"

### ISSUE THREAD

**Issue by PavHru** [Nesvilab/FragPipe#358]
Dear developers, 

I have just recently downloaded the latest version of FragPipe (v15.0) and I tried analyzing Bruker Tims TOF Pro data. However, I receive this error no matter what I try. 

[main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - JNA could not load native Bruker library
[main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - The ext folder with timsdata-2-7-0.dll (Win) or libtimsdata-2-7-0.so (Linux) is needed. If you are using an old ext folder, please upgrade.
java.lang.UnsatisfiedLinkError: Unable to load library 'timsdata-2-7-0':

[log_2021-04-20_11-57-12.txt](https://github.com/Nesvilab/FragPipe/files/6342590/log_2021-04-20_11-57-12.txt)

I have checked that the ext folder and bruker folder is at the place after extracting the downloaded package with the latest version. 

I am trying to decide whether this would be an alternative for MaxQuant and I really like the speed of it for orbitrap data so far, so it would be nice if it works for TimTOF data as well. By any chance, do you plan to support also orbitrap FAIMS data?

Thank you very much!

Best,
Pavel

**Comment by fcyu** [comment]
Hi Pavel,

You need to install [Install Visual C++ Redistributable for Visual Studio 2017](https://aka.ms/vs/16/release/VC_redist.x64.exe). Details can be found from https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html

And our tools, including MSFragger and IonQuant, already support FAIMS data. We demonstrate the performance here (https://www.mcponline.org/article/S1535-9476(21)00050-5/fulltext)

Best,

Fengchao

**Comment by PavHru** [comment]
Hi Fengchao, 

Thank you very much. It has resolved the issue but it still crashes right below the First search by saying: 

Insufficient memory!
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

I guess there will not be any way to bypass it. Perhaps I will be able to try it on some server. Thank you very much. 

Best, 
Pavel

**Comment by fcyu** [comment]
Hi Pavel,

Yes, you need to find a computer with more memory. If you want to use FragPipe remotely on a Linux server, here (https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html) is the tutorial.

Best,

Fengchao
