### ISSUE TITLE
Cannot execute InteractParser.exe due to lack of admin privileges in windows machine

### ISSUE THREAD

**Issue by avera1988** [Nesvilab/FragPipe#364]
Hello,

We are trying to run FragPipe on a windows computer, however, due to university policies, we are not able to log in as admin on that machine.  After start FragPipe with a single experiment I got this error in the log:
```
*******************************TOTAL TIME 11.376 MIN********************************
Process 'MSFragger' finished, exit code: 0
MSFragger move pepxml
C:\Users\auve\scratch\Bin\FragPipe-jre-15.0\fragpipe\jre\bin\java.exe -cp C:\Users\auve\scratch\Bin\FragPipe-jre-15.0\fragpipe\lib\fragpipe-15.0.jar;/C:/Users/auve/scratch/Bin/FragPipe-jre-15.0/fragpipe/lib/commons-io-2.6.jar com.github.chhh.utils.FileMove C:\Users\auve\scratch\Project\FragPipeTest\20210128_IA_R1.pepXML C:\Users\auve\scratch\Project\FragPipeTest\Run\exp_1\20210128_IA_R1.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
PeptideProphet: Workspace init [Work dir: C:\Users\auve\scratch\Project\FragPipeTest\Run\exp_1\fragpipe-20210128_IA_R1.pepXML-temp]
C:\Users\auve\scratch\Bin\FragPipe-jre-15.0\fragpipe\tools\philosopher\philosopher.exe workspace --init --nocheck
INFO[11:41:02] Executing Workspace  v3.4.13                 
INFO[11:41:02] Creating workspace                           
INFO[11:41:02] Done                                         
Process 'PeptideProphet: Workspace init' finished, exit code: 0
PeptideProphet [Work dir: C:\Users\auve\scratch\Project\FragPipeTest\Run\exp_1\fragpipe-20210128_IA_R1.pepXML-temp]
C:\Users\auve\scratch\Bin\FragPipe-jre-15.0\fragpipe\tools\philosopher\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database C:\Users\auve\scratch\Project\FragPipeTest\2021-03-15-decoys-genes.faa.fas ..\20210128_IA_R1.pepXML
INFO[11:41:02] Executing PeptideProphet  v3.4.13            
FATA[11:41:05] Cannot execute program. fork/exec C:\Users\auve\AppData\Local\Temp\76ca8ba6-9547-4c45-a07f-bd882a21a71f\InteractParser.exe: This program is blocked by group policy. For more information, contact your system administrator. 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 13 remaining tasks
```
It looks like PeptideProphet tries to run InteractParser on AppData\Local\Temp but this is locked by the admin. Is there any way we can specify PeptideProphet to run InteractParser in a different folder or maybe without admin privileges? 

Thank you!

Arturo.

**Comment by prvst** [comment]
Hi @avera1988. You normally do not need extra permissions, and privileges to use the system temporary folders. Every user account has access to it by default. Apparently, the sysadmin at your institution took extra steps into preventing people from running external programs, and blocked you from using some of the system's resources. Philosopher allows you to use a custom temporary folder, bunt to do that, you have to run the workspace init command with the --temp flag. The only thing is that I don't think you can do it through FragPipe.

**Comment by avera1988** [comment]
Hi Felipe, thanks for answering. Okay we will contact the IT department and see if they can write an exception to the executables  running by PeptideProphet.

Best!

Arturo.
