### ISSUE TITLE
PeptideProphet Processing Error

### ISSUE THREAD

**Issue by kevinnestler** [Nesvilab/FragPipe#367]
Hello,

I am trying to run a search containing 848 raw files (label-free data) with default parameters. This search crashed because PeptideProphetProcessing was interrupted, but I am not sure why this is the case. I am able to successfully run a search on a small subset of these files with no issues. Is there a known limit with how many files it can handle on windows? Any help with this would be greatly appreciated.

Thanks,
Kevin

[log_2021-05-04_16-38-07.txt](https://github.com/Nesvilab/FragPipe/files/6426979/log_2021-05-04_16-38-07.txt)

**Comment by prvst** [comment]
I don't see any errors in the log file. What kind of workstation, and operational system are you using?

**Comment by kevinnestler** [comment]
I am working directly on the server which is a Microsoft Windows Server 2019 standard running Windows 10 pro

**Comment by prvst** [comment]
OK. There is no evident error from the log, except for the FragPipe messages saying that the jobs are being killed.

**Comment by fcyu** [comment]
It seems that the process was interrupted without any error. It normally happens when operating system has some issue or users stop it manually.

Best,

Fengchao

**Comment by kevinnestler** [comment]
Okay thank you very much. I will try to rerun and see.
