### ISSUE TITLE
FragPipe - MSstats

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#369]
Greetings @fcyu,

Currently, I am analyzing FragPipe MSstat file using MSstats. I am using this as a guide: https://msfragger.nesvilab.org/tutorial_msstats.html

I would like to apologies for asking support with regards to R-programming (I am extremely new to this) 

Based on the instruction provided,  under the section of "# Processing the data using MSstats"
Can I replace the processedData <- dataProcess(raw, logTrans = 10) to processedData <- dataProcess(raw, normalization = 'quantile')? (I would like to normalize my data and not log transform my data).

If I look further down your R-script provided, there are commands that contain $LogIntensities

e.g. - if (length(x[x$Protein == protein & x$SUBJECT_NESTED == subject,]$LogIntensities) > 0) {
      y[y$Protein == protein, match(subject, colnames(y))] <- x[x$Protein == protein & x$SUBJECT_NESTED == subject,]$LogIntensities

**By only just changing logTrans = 10 to normalization = 'quantile' from the script that has been provided, it should not have any implication with the way the data is being processed?**    

Please do advise me if this is the appropriate way to normalize my FragPipe output MSstat.csv file data ?

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

No worries!

> Can I replace the processedData <- dataProcess(raw, logTrans = 10) to processedData <- dataProcess(raw, normalization = 'quantile')? (I would like to normalize my data and not log transform my data).

If you don't provide `logTrans` option, `dataProcess` will use `logTrans=2` by default. The default normalization is `normalization="equalizeMedians"` if `normalization` is provided. Your `normalization = 'quantile'`uses a different one. Here ([https://www.bioconductor.org/packages/release/bioc/manuals/MSstats/man/MSstats.pdf](https://www.bioconductor.org/packages/release/bioc/manuals/MSstats/man/MSstats.pdf)) is the documentation. 

Different normalizations are for different types of data. Here ([https://www.bioconductor.org/packages/release/bioc/vignettes/MSstats/inst/doc/MSstats.html](https://www.bioconductor.org/packages/release/bioc/vignettes/MSstats/inst/doc/MSstats.html)) is another resources with some tutorials. Hope they are helpful.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Thank you for your rapid response.

Regards,
Ben
