### ISSUE TITLE
Error: Could not find or load main class ionquant.IonQuant

### ISSUE THREAD

**Issue by giorgiolivi** [Nesvilab/FragPipe#372]
Dear all,

I have a small issue, despite going through the other feedback, which I guess had similar issues
I can’t let quantified the LFQ values work for me

here the errors:

IonQuant [Work dir: C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\K4result]
C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-15.0\fragpipe\jre\bin\java.exe -Xmx23G -Dlibs.bruker.dir="C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-15.0\fragpipe\tools\MSFragger-3.2\ext\bruker" -Dlibs.thermo.dir="C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-15.0\fragpipe\tools\MSFragger-3.2\ext\thermo" -cp "C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-15.0\fragpipe\tools\ionquant-1.5.5.jar;C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-15.0\fragpipe\tools\batmass-io-1.22.1.jar" ionquant.IonQuant --threads 16 --ionmobility 1 --mbr 1 --proteinquant 2 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.4 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 10 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 1 --minisotopes 2 --minscans 3 --writeindex 0 --tp 3 --minfreq 0.5 --minions 2 --minexps 1 --psm exp3_3\psm.tsv --psm exp4_4\psm.tsv --psm exp2_2\psm.tsv --psm exp1_1\psm.tsv --multidir . --specdir C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\k4 exp3_3\210508kw_Giorgio_HistonePD_UNK4_RA_1_Slot1-10_1_4634.pepXML exp1_1\210508kw_Giorgio_HistonePD_K4_RA_1_Slot1-19_1_4653.pepXML exp2_2\210508kw_Giorgio_HistonePD_K4_RA_1_Slot1-19_2_4654.pepXML exp4_4\210508kw_Giorgio_HistonePD_UNK4_RA_1_Slot1-10_2_4635.pepXML
Error: Could not find or load main class ionquant.IonQuant
Caused by: java.lang.ClassNotFoundException: ionquant.IonQuant
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks


[log_2021-05-18_12-40-44.txt](https://github.com/Nesvilab/FragPipe/files/6500979/log_2021-05-18_12-40-44.txt)

**Comment by fcyu** [comment]
Your error is weird. Could you re-download FragPipe and re-run it again? If the error is still there, could you send us the screenshot of `fragpipe/tools` folder?

Best,

Fengchao

**Comment by giorgiolivi** [comment]
Dear  Fengchao,
I just found out that the JAVA wasn't updated.
I erased it and installed the last version.
Now all works,
Thanks

**Comment by fcyu** [comment]
Thanks for your feedback. I will close this issue.

Best,

Fengchao
