### ISSUE TITLE
DIA Umpire library pipeline fails

### ISSUE THREAD

**Issue by SimionKreimer** [Nesvilab/FragPipe#374]
I've tried generating a library from Thermo DIA files, however the pipeline fails each time. For some reason Fragpipe is looking for mzML files corresponding to the generated Q1 to Q3 mgf files, but those do not appear to be created. What do I do? I've attached the log.
[log_2021-05-18_23-12-41.txt](https://github.com/Nesvilab/FragPipe/files/6506285/log_2021-05-18_23-12-41.txt)

**Comment by SimionKreimer** [comment]
I moved the raw files to a new folder, for raw files I get this error:
[log_2021-05-19_11-56-55.txt](https://github.com/Nesvilab/FragPipe/files/6511031/log_2021-05-19_11-56-55.txt)
I converted them to mzML in a new folder and I get this error:
[log_2021-05-19_12-47-02.txt](https://github.com/Nesvilab/FragPipe/files/6511211/log_2021-05-19_12-47-02.txt)

**Comment by fcyu** [comment]
The DIA-Umpire version is old (version 2.1.5). In FragPipe 15.0, we are using version 2.2.1. Can you download a new FragPipe, delete all temp files, and try again?

Best,

Fengchao

**Comment by SimionKreimer** [comment]
I'm already running FragPipe 15.0, is there something different I need to do to update DIA-Umpire?

**Comment by fcyu** [comment]
The DIA-Umpire in FragPipe 15.0 is version 2.2.1, which means that something was wrong with your downloaded files. Can you download FragPipe again and see if there is a `DIA_Umpire_SE-2.2.1.jar` in the `fragpipe/tools` folder?

Best,

Fengchao

**Comment by SimionKreimer** [comment]
Wow, no idea how I ended up with the old DIA-Umpire version, but downloading the new FragPipe totally fixed this. I just ran Umpire_SpecLib pipeline using .raw files all the way to the end, and it worked perfectly. Thank you very much for all of your help!

**Comment by fcyu** [comment]
You are welcome!

Best,

Fengchao
