### ISSUE TITLE
Fragpipe error on Windows

### ISSUE THREAD

**Issue by im281** [Nesvilab/FragPipe#378]
Unable to run to completion

![image](https://user-images.githubusercontent.com/10081392/119282186-3216c980-bc28-11eb-9d88-a80a6cd2b3d8.png)

**Comment by prvst** [comment]
Hi @im281. Could you describe to us what kind of analysis are you running, and what type of Windows you have?

**Comment by im281** [comment]
Hi it is an MSFragger search and then Peptide/Protein Prophet (basic search)

**Comment by fcyu** [comment]
Hi @im281 ,

Could send us the log file?

Best,

Fengchao

**Comment by im281** [comment]
The error is in the writing of the log. This is a Windows system too

**Comment by fcyu** [comment]
We need the **whole** log to troubleshoot.

Best,

Fengchao

**Comment by im281** [comment]
[log_2021-05-26_11-54-01.txt](https://github.com/Nesvilab/FragPipe/files/6546462/log_2021-05-26_11-54-01.txt)

**Comment by im281** [comment]
here is the log

**Comment by anesvi** [comment]
What is the issue here? The log just shows the  command (“dry run”), so nothing is actually executed

**Comment by fcyu** [comment]
Hi @im281 ,

After perform an actual run, can you export the log by clicking “export log" in the "Run" tab?

Best,

Fengchao

**Comment by im281** [comment]
my apologies. It works. I didn't notice that
