### ISSUE TITLE
PhilosopherFilter nocheck

### ISSUE THREAD

**Issue by ZhangXiangye** [Nesvilab/FragPipe#381]
I am sorry to bother you, but this problem bother us a long time. 
We just use open search (default setings), but it always returns an error as below,

FATA[21:22:19] Missing input parameters. missing pepXML files 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks

Could you please give us some advice? We download the PhilosopherFilter by the button on "Config", and choose "Automatiocally".

Thank you very much!

**Comment by fcyu** [comment]
Hi @ZhangXiangye ,

Your task did not run PeptideProphet or ProteinProphet. Can you load the "open" workflow, specifying your data and fasta file, and do not change other settings unless you have a good reason?

Best,

Fengchao

**Comment by ZhangXiangye** [comment]
> This seems to be related to FragPipe workflow, I'm transferring this to the other repository so others can help

Thanks for your help! And I have solved this problem. When I load the "open search" in "workflow", "Validation" and "PTMs", it works.

**Comment by ZhangXiangye** [comment]
> Hi @ZhangXiangye ,
> 
> Your task did not run PeptideProphet or ProteinProphet. Can you load the "open" workflow, specifying your data and fasta file, and do not change other settings unless you have a good reason?
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Thanks for your help! And I have solved this problem. When I load the "open search" in "workflow", "Validation" and "PTMs", it works.

But I have another question now, can MSFragger display pictures showing BY ions? Or does it come with any visual plugins?

Have a great day,

ZhangXiangye

**Comment by fcyu** [comment]
PDV (https://github.com/wenbostar/PDV) support our outputs (psm.tsv).

Best,

Fengchao

**Comment by ZhangXiangye** [comment]
> PDV (https://github.com/wenbostar/PDV) support our outputs (psm.tsv).
> 
> Best,
> 
> Fengchao

Thank you very much for your reply! : )
