### ISSUE TITLE
pSILAC data missing sample identifier columns and wrong label assigned

### ISSUE THREAD

**Issue by anfoss** [Nesvilab/FragPipe#382]
I searched a Tims-TOF DDA pulse silac dataset (heavy K and R) following [this link](https://msfragger.nesvilab.org/tutorial_silac.html), however, even after defining the experiment and replicates, there is no sample information in either peptide_label_quant/protein_label_quant/ion_label_quant.tsv.

Moreover while I added as modifications only heavy K and R (K8 R10), in all the _label_quant files the ratios reported are medium with the heavy column being complete empty.

I am attaching the log and the workflow (pSILAC.txt) used as well as one of the reports generated. Both in the log and the workflow the modification selected is heavy K and R but in the output there is only a medium label.

[log_2021-05-26_14-00-53.txt](https://github.com/Nesvilab/FragPipe/files/6562784/log_2021-05-26_14-00-53.txt)

[peptide_label_quant.txt](https://github.com/Nesvilab/FragPipe/files/6562787/peptide_label_quant.txt)
[pSILAC.txt](https://github.com/Nesvilab/FragPipe/files/6562788/pSILAC.txt)

**Comment by fcyu** [comment]
> even after defining the experiment and replicates, there is no sample information in either peptide_label_quant/protein_label_quant/ion_label_quant.tsv.

I am sorry that I cannot follow. Do you mean that there is no experiment name in those tsv files? There is no experiment name because those files are in individual folders (named with the experiment). All entries in the files are from the corresponding experiment.


> Moreover while I added as modifications only heavy K and R (K8 R10), in all the _label_quant files the ratios reported are medium with the heavy column being complete empty.

I tested three files and could not reproduce your issue. Can you double check by running it again?

Best,

Fengchao

**Comment by anfoss** [comment]
Seems I got my folder structure screwed up and mixed up files. Indeed in every folder there is the correct ratio.
Thanks for the quick answer!
Closed
