### ISSUE TITLE
Issue with SpecLib generation

### ISSUE THREAD

**Issue by rnirujogi** [Nesvilab/FragPipe#383]
Hello,
I am searching a DDA data set with 40 fractions to generate a Spectral library with EasyPQP. Search finishes successfully without a SpecLibrary generated. Tried with both iRT(We Spiked iRT peptides) as well as ciRT. Also, log file size is zero. The only difference is I have updated EasyPQP as it prompted to update upon opening the Fragpipe

Appreciate any he
![image](https://user-images.githubusercontent.com/80681570/120111816-4e0bf500-c16b-11eb-8d0f-c9651a82088e.png)
[Fragpipe error.odp](https://github.com/Nesvilab/FragPipe/files/6566503/Fragpipe.error.odp)

Best,
Raja

**Comment by rnirujogi** [comment]
See the log file. I just realised it can be exported.

Best,
Raja
[log_2021-05-30_17-24-54.txt](https://github.com/Nesvilab/FragPipe/files/6566514/log_2021-05-30_17-24-54.txt)

**Comment by fcyu** [comment]
Hi Raja,

Current version does not support building a spectral library with raw format. Could you convert your files to mzML according to the [tutorial](https://msfragger.nesvilab.org/tutorial_convert.html)?

Next version will support raw format.

Best,

Fengchao

**Comment by rnirujogi** [comment]
Thanks, Fenchago. Apologies, I forgot about it.

Best,
Raja

**Comment by fcyu** [comment]
No worries.

Best,

Fengchao
