### ISSUE TITLE
Continuing with partial results?

### ISSUE THREAD

**Issue by patruong** [Nesvilab/FragPipe#384]
Hi,

If I run FragPipe with only DIAUmpire, is it possible to continue using the MSFragger part on the resulting output from the DIAUmpire run?

Thanks!

**Comment by fcyu** [comment]
Yes, you can. Just need to give FragPipe those Q1.mzML, Q2.mzML, and Q3.mzML files, and treat them as from DDA.

Best,

Fengchao

**Comment by patruong** [comment]
Thank you! :)
