### ISSUE TITLE
Error reading PASEF spectra with tims_read_pasef_msms_for_frame(): CorruptFrame

### ISSUE THREAD

**Issue by LP-FPM** [Nesvilab/FragPipe#386]
Hi

I am trying to do a MSfragger search using fragpipe with TIMSTOF raw data, but I am getting a lot of errors and I dont know how to solve this. Can you help. Thank you.

Best regards Lone

[log_2021-06-04_09-41-41.zip](https://github.com/Nesvilab/FragPipe/files/6596714/log_2021-06-04_09-41-41.zip)
 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Your file is corrupted.

Best,

Fengchao
