### ISSUE TITLE
error in extracting isolation windows: Cannot get isolation window info from scan

### ISSUE THREAD

**Issue by kguehrs** [Nesvilab/FragPipe#390]
[log_2021-06-11_10-52-33.zip](https://github.com/Nesvilab/FragPipe/files/6637134/log_2021-06-11_10-52-33.zip)
Pipe/files/6637097/log_2021-06-11_10-14-33.txt)
- Describe the issue or question:

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
If you are using DIA-Umpire, then MSFragger. You should choose "DDA" as the data type in MSFragger because the pseudo-spectra from DIA-Umpire are like DDA spectra. Could you please load the corresponding workflow (DIA-Umpire_Speclib), do not change any parameters other than those related to digestion and modification, and try again?

Best,

Fengchao

**Comment by kguehrs** [comment]
Hello Fengchao,

Thanks for the response.

The default workflow worked for me for a small dataset now. There is some “Time outwaiting for sequential executor shutdown “ notice after the DONE was printed that I cannot fully understand but I will go into the data now to compare the results with those of other approaches.

Perhaps, it would be a good idea to make options of the real “master workflows” that should not be touched unchangeable or even hidden. If one can kind of clone a workflow from the “master” and save differently flagged using a different name this could be used as an user adaptable template. I know that this is lot of scripting but shall help you and the users to keep track with all settings that can go wrong.

Mit freundlichen Grüßen/Best regards

Dr. Karl-Heinz Gührs
CF Proteomics

Leibniz Institute on Aging – Fritz Lipmann Institute (FLI)
Beutenbergstraße 11
07745 Jena, Germany
Phone:        +49(0)3641-65-6433
Email:          ***@***.***
WWW:        http://www.leibniz-fli.de
Scientific Director: Prof. Dr. Alfred Nordheim
Administrative Director:  Dr. Daniele Barthel
Chairman of the Board of Trustees:  Burkhard Zinner
Register of Associations: No. 230296 at Amtsgericht Jena
VAT No.: DE 153 925 464

From: Fengchao ***@***.***>
Sent: Friday, June 11, 2021 13:45
To: Nesvilab/FragPipe ***@***.***>
Cc: Karl-Heinz Gührs ***@***.***>; Author ***@***.***>
Subject: [External] Re: [Nesvilab/FragPipe] error in extracting isolation windows: Cannot get isolation window info from scan (#390)


If you are using DIA-Umpire, then MSFragger. You should choose "DDA" as the data type in MSFragger because the pseudo-spectra from DIA-Umpire are like DDA spectra. Could you please load the corresponding workflow (DIA-Umpire_Speclib), do not change any parameters other than those related to digestion and modification, and try again?

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Karl-Heinz,

"Time out waiting for sequential executor shutdown" is kind of debug message and it won't affect the result. You can ignore it,

All those built-in workflows cannot be overwritten inside FragPipe. Users can make some changes and create a custom workflow. 

Best,

Fengchao
