### ISSUE TITLE
Not getting any Intensity values in the output

### ISSUE THREAD

**Issue by Maithy15** [Nesvilab/FragPipe#392]
I searched two files generated from Bruker Impact II QTOF by loading the LFQ MBR search option. The problem is that I am not getting any intensity values in the output file, all the values are zero. 

In the log file Ion quant says 

2021-06-15 13:46:57 [WARNING] - There are only 2 experiments. Using Top-N protein intensity calculation algorithm with min exps = 1.
2021-06-15 13:46:57 [WARNING] - ionmobility = 0 but the spectral file is from timsTOF (.d): D:\MK\Fragpipe\210310_A_QCA_2h_GE11_1_1896.d. Change to ionmobility = 1

I only loaded the mzML file that I converted using msconvert. How is Ionquant recognising the .d file?

**Comment by fcyu** [comment]
You were using `D:\MK\Fragpipe\210310_A_QCA_2h_GE11_1_1896.d` which is a .d from Bruker. But IonQuant only support the .d from timsTOF Pro. You can convert your .d to mzML using msconvert. In the converting, please remember to add peak picking as the first filter.

Best,

Fengchao

**Comment by Maithy15** [comment]
I was not using the .d files. I converted them to mzML and used those files only.

**Comment by Maithy15** [comment]
The .d files were in the same folder. Why is Ionquant recognizing those files is my question.

**Comment by fcyu** [comment]
If there are both .d and mzML, IonQuant gives .d a higher priority. You need to move your .d to another place.

Best,

Fengchao
