### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by Alemarcohen** [Nesvilab/FragPipe#396]
This is not an issue, rather an issue request:
I run a Core Facility, and I'm looking for a tool which is able to handle most of our proteomics projects. I'm very pleased with Fragpipe so far, but for me to switch completetly as my GO TOOL in the lab, the following would be great features:
-Ability to handle multiple Fasta Databases,
-Ability to -automatically- generate the Decoy DB from any custom Fasta DB, whithout having to use an external tool or code.
-Include a spectrum visualizer and annotator that can be directly hyper inked to the results PSM table. Ideally, integrate all results (MSMS, PSM, Pepitde and Proteins) similar to what ProteomeDiscoverer does. 

Is any of this in your plans??

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Thanks for your interest in our tools!

> -Ability to handle multiple Fasta Databases,

We will discuss it internally to see if this feature can be added in the next release.

> -Ability to -automatically- generate the Decoy DB from any custom Fasta DB, whithout having to use an external tool or code.

FragPipe already has this feature. It's "add decoy" button in the database tab:
![image](https://user-images.githubusercontent.com/6926299/123433860-e1cdb700-d599-11eb-8d13-b1426df62a46.png)


> -Include a spectrum visualizer and annotator that can be directly hyper inked to the results PSM table. Ideally, integrate all results (MSMS, PSM, Pepitde and Proteins) similar to what ProteomeDiscoverer does.

PDV (https://github.com/wenbostar/PDV) can load psm.tsv from our tools. But is it not integrated inside FragPipe. We will discuss it internally too.

Best,

Fengchao

**Comment by Alemarcohen** [comment]
Thank you Fenchao,

I used PDV, it works fine, but it is a little cumbersome to navigate from data in fragpipe ot PDV. Working in a CORE facility, time is limitted... so any tool that will expedite the process would be helpfull. Same as combining databases using an external tool. Most other tools allow to select multiple .fasta files.
