### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by qingbo11** [Nesvilab/FragPipe#397]
- Describe the issue or question:
Hi Fragpipe developers,
I have an issue in running the fragpipe tool with speclib workflow as attached. Could you please help fixing it?

Thanks,

Qingbo

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2021-06-25_15-42-55.txt](https://github.com/Nesvilab/FragPipe/files/6719250/log_2021-06-25_15-42-55.txt)

**Comment by fcyu** [comment]
There is not enough memory. It looks like your computer only has 4 GB free memory available, but your were performing a semi-specific search with 6 variable modifications. I suggest you either add more memory to your computer or use split database function (increasing split from 1 to a bigger number):
![image](https://user-images.githubusercontent.com/6926299/123494694-c17c1780-d5ee-11eb-9b2f-53d9392f37f8.png)

Please note that split database function needs python installed. Please check our tutorials (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html) for detail.

Best,

Fengchao
