### ISSUE TITLE
Submitting not related experiments in the same workflow gives unexpected result

### ISSUE THREAD

**Issue by FredSoftwares** [Nesvilab/FragPipe#398]
Hi,
I try to analyse independent experiments with FragPipe.

But if I perform the search one by one, such as 
Method 1

Experiment | Replicate
-- | --
treatment1 | 1

Then I start another fragpipe session with,

Experiment | Replicate
-- | --
treatment2 | 1

When I do this separate analysis I obtain, as expected, protein lists with different proteins for treatment1 and treatment2

I do not obtain the same results  if I try to submit both searches in the same workflow  such as

Method 2

Experiment | Replicate
-- | --
treatment1 | 1
treatment2 | 2

In this last situation the proteins list in protein.tsv files of treatment1 and treatment2 are the same, only the number of peptides, spectral counts... are not identical.

When I have a lot of different experiments not related together to analyse, it is time consuming to submit the experiments one by one to fragpipe (method 1). Is there a way to submit  a processing list of independent experiments to fragpipe in one table (method 2)  and obtain truly independent results with different lists of proteins for each experiment (such as method 1) ?

Thanks for your help !

**Comment by fcyu** [comment]
The protein list are from the combination of proteins from all experiments. But if some experiments don't have a certain protein, you will see 0 spectral count indicating this protein is not found from the experiment. That explains your observation.

Analyzing unrelated samples together might be problematic dependending on how you run the software. If you enabled MaxLFQ, normalization, and/or MBR, protein intensities from different samples would interference with each other. But if you don't use quantification (only do the identification), it should be fine.

Best,

Fengchao

**Comment by FredSoftwares** [comment]
Thank you @fcyu ! Indeed when I analyse unrelated experiments I do no use quantification. I think it should be interesting to add this comment in FAQ or , better, in the manual, since other could be interested :)
