### ISSUE TITLE
Process 'IonQuant' finished, exit code: 137

### ISSUE THREAD

**Issue by dr6666** [Nesvilab/FragPipe#399]
Hi! I´m trying to analyze some data with Fragpipe, but I  got the following error code: The process 'IonQuant' finished, exit code: 137. I suspect something is wrong with the database, because when I use other database it run well, but I`m not sure. 

[log_2021-07-02_18-06-09.txt](https://github.com/Nesvilab/FragPipe/files/6760723/log_2021-07-02_18-06-09.txt)

Thank you very much for your support,
Daniela 
-

**Comment by fcyu** [comment]
Hi Daniela,

Your computer does not have enough memory.

Best,

Fengchao
