### ISSUE TITLE
IBAQ quantification with IonQuant?

### ISSUE THREAD

**Issue by borfebor** [Nesvilab/FragPipe#404]
Rather than an issue, it would be a doubt or a suggestion. Is it possible to calculate iBAQ intensities for quantification using IonQuant (or maybe FreeQuant)? 

Thanks for your help.

Borja

**Comment by fcyu** [comment]
Hi Borja,

Using Top-N protein quan algorithm in IonQuant should be able to get the intensity similar to iBAQ.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, and set top N to 6 or 10. The main difference would be that in iBAQ summed intensity is divided by the number of observable peptides. I don’t think this additional normalization helps much.
Alexey
