### ISSUE TITLE
FATA[13:36:52] Cannot decode packed binary. XML syntax error on line 46481: expected attribute name in element

### ISSUE THREAD

**Issue by DanielConole** [Nesvilab/FragPipe#416]
-Search is failing due to the above error

[log_2021-07-28_20-01-03.txt](https://github.com/Nesvilab/FragPipe/files/6895874/log_2021-07-28_20-01-03.txt)
:

**Comment by fcyu** [comment]
The protein sequences in your fasta file contains letters other than A-Z. Please check your files.

Best,

Fengchao
