### ISSUE TITLE
Cannot find protein.tsv

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#417]
- Describe the issue or question:
I got an error  in ionquant that it cannot read protein.tsv - and indeed the file is missing. The steps I took to get the error is as follows:

- on enqueuing the process, I first updated msfragger to the latest (3.3) from fragpipe 
- got an error that the bruker library is not found (see first log file) 
- I copied the bruker file to the correct place and restarted the process
- got the new error as above (see second log file).

Any help would be appreciated!
Thank you,
Janos
[log_2021-07-30_11-21-23.txt](https://github.com/Nesvilab/FragPipe/files/6909390/log_2021-07-30_11-21-23.txt)
[log_2021-07-29_10-42-00.txt](https://github.com/Nesvilab/FragPipe/files/6909391/log_2021-07-29_10-42-00.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Please upgrade FragPipe and Philosopher if you haven't done so.

Thanks,

Fengchao
