### ISSUE TITLE
Error with PTM-Shepherd when using OpenSearch - FragPipe V16

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#422]
Greetings,

I am currently performing open search with a set of files. I am experiencing issue with PTM-Shepherd (I might be wrong). Please refer to attachment for run log. I tried using the exact workflow with just a single file, the run completed successfully.

Regards,
Ben
[log_2021-08-09_13-48-41.txt](https://github.com/Nesvilab/FragPipe/files/6952040/log_2021-08-09_13-48-41.txt)

**Comment by danielgeiszler** [comment]
Hi Ben,

I’ll take a look today. I think I know what the issue is, so I don’t need your files.

**Comment by BenSamy2020** [comment]
Good morning @danielgeiszler,

Thank you for have a look at this issue. Looking forward for the update.

On a side note, @fcyu, can OpenSearch perform quant in the latest release of FragPipe?

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

It cannot perform quantification directly for open search. But you can perform a mass-offset search with the mass list from your open search (summarized by PTM-Shepherd). You also need to set "report mass shift as a variable mod" to "yes, keep delta mass" in MSFragger tab, and disable PTM-Shepherd.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
Hi @BenSamy2020 ,

This prerelease version of PTM-Shepherd will fix your issue.

https://www.dropbox.com/sh/19qsmurhyxendts/AADuMvQEwBJWrt3nObiwBlT3a?dl=0

**Comment by BenSamy2020** [comment]
Greetings @danielgeiszler,

The updated version of PTM-Shepherd has fixed the issue. Thank you for your assistance.

Regards,
Ben
