### ISSUE TITLE
Error, Total Intensity, Unique Intensity, Razor Intensity, and other intensity was 0

### ISSUE THREAD

**Issue by kongzhi12** [Nesvilab/FragPipe#426]
- Describe the issue or question:
Dear Nesvi lab team,
  I use the DIA-Umpire_SpeciLib workflow, then add my raw data (.raw files from Orbitrap fusion),  and the run was done. However, in ion, psm, peptide and protein.tsv, all the intenstiy was 0. I don't know the reasons.
 please give me some advices.
By the way in upgrade FragPipe to v16.0, the EasyPQP was not available. and click the install/Upgrade EasyPQP button without response. why? The easyPQP was installed by typing pip install easypqp into the Anaconda prompt window,  and it was succesed.
thanks
 
[log_2021-08-15_08-11-46.txt](https://github.com/Nesvilab/FragPipe/files/6987341/log_2021-08-15_08-11-46.txt)
![intensity is 0](https://user-images.githubusercontent.com/88951916/129463465-3ffff110-b835-433b-acda-1754315253e6.PNG)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
1. The pseudo scans from DIA-Umpire (_Q1, _Q2, and _Q3) do not contain MS1.
2. The quantification modules in FragPipe (IonQuant, FreeQuant or TMT-I) only support DDA data.
3. If you want to quantify DIA data, you can using FragPipe to generate a spectral library. Then, quantify the proteins using DIA-NN. There is a tutorial: https://fragpipe.nesvilab.org/docs/tutorial_DIA.html
4. After you clicking "install/upgrade EasyPQP", there is a command running in the background trying to install EasyPQP. There is no message shown, but after a while, EasyPQP should have been installed. Hopefully, @guoci can ad a window showing the installation progress.

Best,

Fengchao

**Comment by kongzhi12** [comment]
thanks for your answers.
 I hope FragPipe will integrate the fuction of DIA-NN for DIA quantification in the future. It will be more easier for users.
 EasyPQP is still not installed, maybe  the reason of my Win system.
thanks a lot.

**Comment by fcyu** [comment]
Regarding EasyPQP installation, does your system have git installed?

Best,

Fengchao

**Comment by guoci** [comment]
@kongzhi12 It is most likely caused by not having git installed.
I have recently fixed the PyPI (non-git) install for EasyPQP, and you can install it by typing `pip install easypqp` in Anaconda Prompt.
FragPipe v16 is still using the pip+git install, but I have changed it in the development branch to use PyPI install.
