### ISSUE TITLE
The site report illustration in tutorial_tmt.md is not correct

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#438]
Hi Sarah @sarah-haynes 

In the tutorial (https://github.com/Nesvilab/FragPipe/blob/gh-pages/docs/tutorial_tmt.md#results), the protein ID in the illustration does not meet what TMT-Integer actually generates. TMT-Integer uses the ID between two `|`. For example it should be `A0FGR8_S736` rather than `sp|A0FGR8_S736|ESYT2_HUMAN_S736`.
![image](https://user-images.githubusercontent.com/6926299/130467743-16a1e7d3-a076-4860-a749-94dead4bc5f2.png)

Best,

Fengchao

**Comment by prvst** [comment]
When did the column setting change?

**Comment by fcyu** [comment]
I don't know. I was running TMT-I with the latest FragPipe.

**Comment by prvst** [comment]
The image above is compatible with results I have, but I haven't tested the latest version with a UniProt database.
