### ISSUE TITLE
PhilosopherFilter error inside FragPipe workflow

### ISSUE THREAD

**Issue by prvst** [Nesvilab/FragPipe#444]
### Discussed in https://github.com/Nesvilab/FragPipe/discussions/443

<div type='discussions-op-text'>

<sup>Originally posted by **gozzdzik** August 26, 2021</sup>
Hi All,
I have tried to test FragPipe 16.0 with Philosopher 4.0.0 to test library building. The workflow crashed during Philosopher stage with the following error:

> INFO[15:58:03] Executing Filter  v4.0.0                     
INFO[15:58:03] Processing peptide identification files      
FATA[15:58:03] Cannot decode packed binary. strconv.ParseFloat: parsing "0,856529": invalid syntax 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

Did anyone saw such error in your processing? Have an idea how to fix this? 
Thank you for any help!

Tomasz</div>

See #432

**Comment by fcyu** [comment]
Should be the same as https://github.com/Nesvilab/FragPipe/issues/415 and https://github.com/Nesvilab/FragPipe/issues/413.
