### ISSUE TITLE
Skyline tutorial hangs up

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#453]
I am trying to follow the tutorial https://fragpipe.nesvilab.org/docs/tutorial_skyline.html  where DDA-Search import seems to have worked 
![image](https://user-images.githubusercontent.com/21457/132687595-a0b8ca8e-e987-40fb-94b1-cddbe87f54f0.png)
 but it gets stuck at building-molecular-search-library stage ![image](https://user-images.githubusercontent.com/21457/132687396-0f21b48b-cd93-44c0-94ae-f350cb1d11a8.png) ?

I have loaded the IO files at https://drive.google.com/drive/folders/1ILiqR2mvWeMWIpeM55qyj9jehPebWBrF which includes the logs, wondering if you can take a look/identify the issue and tell me how to proceed? Or if there is an alternative way to view the results?

**Comment by fcyu** [comment]
Although I didn't try your file, but your screenshot indicates that you are not following our tutorial. The DDA search is supposed to be performed by FragPipe, not Skyline. Can you double check your processing and try again?

Best,

Fengchao

**Comment by animesh** [comment]
I am trying to import the results from the fragpipe results uploaded here https://drive.google.com/drive/folders/1ILiqR2mvWeMWIpeM55qyj9jehPebWBrF , not sure why skyline is (re)performing it? I must say that screenshot in the tutorial don't match the current skyline to begin with, so probably that is the issue?

**Comment by fcyu** [comment]
I am using the latest Skyline-daily, and found it similar to what the tutorial shows.

As you can see, Skyline does not perform a search, but imports the interact-*.pep.xml file and builds the library.

![image](https://user-images.githubusercontent.com/6926299/133494591-8d335484-fc07-49a0-9a0e-49e1b3bd3425.png)

Best,

Fengchao
