### ISSUE TITLE
library.tsv not generated 

### ISSUE THREAD

**Issue by fabsen-87** [Nesvilab/FragPipe#458]
Hello FragPipe team! I have an issue with the library generation using EasyPQP and the SpecLib workflow. I tried both Bruker and Thermo raw files and also two different versions (Fragpipe 15 and 16). I do not get the library.tsv file at the end. I also clicked on 'Generate spectral library from search results'.  It writes out psm.tsv, peptide.tsv, protein.tsv and ion.tsv though.

Please see below the last messages:

_Traceback (most recent call last):
  File "C:\FragPipe-jre-16.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 212, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
  File "C:\FragPipe-jre-16.0\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 121, in get_bin_path
    if dist.get('files') is None and sys.platform == "win32":
AttributeError: '_PackageInfo' object has no attribute 'get'
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping_

Thanks a lot for your support!! 
Best,
Fabian

**Comment by guoci** [comment]
This is a known issue (#421) and has been fixed, link to the fixed version below.
https://drive.google.com/drive/folders/1yLxJmXjN8tHpOos_eFRRfz4WjlMoAtV7?usp=sharing

**Comment by fabsen-87** [comment]
Fantastic, thanks a lot! Now it works :-)
