### ISSUE TITLE
Error in SpecLib generation

### ISSUE THREAD

**Issue by xuel12** [Nesvilab/FragPipe#459]
Issues:

With v16 and v16.1-build5, library generation step has error complaining "Peptide overlap between run and reference: 12651.
Exception in thread Thread-1:". 

The input is single TimsTOF .d file. Have tried multiple files and Orbitrap data, same errors.

[log_2021-09-12_14-45-19.txt](https://github.com/Nesvilab/FragPipe/files/7150131/log_2021-09-12_14-45-19.txt)

**Comment by guoci** [comment]
This is a known issue, please see the following link to resolve.
https://github.com/Nesvilab/FragPipe/issues/421#issuecomment-897030890
