### ISSUE TITLE
Multistage search

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/FragPipe#460]
Dear all,

I am working with a Riboseq-generated fasta file for the identification of peptides from non-canonical ORFs.

I would like to perform a multistage search such as the one described here (see figure below). In which I discard spectra that matches canonical sequences and PTMs in an initial search and use the non-matching spectra to search against the ribo-seq DB.

Is this something that can somehow be done within FragPipe? Do you have any recommendations for executing such a multistage search?

Many thanks in advance.

![image](https://user-images.githubusercontent.com/33185213/133103906-87e2bc4a-4f5c-4b09-b4e8-64a218168369.png)

Source: https://pubs.acs.org/doi/10.1021/acs.jproteome.9b00498

**Comment by MiguelCos** [comment]
Thanks Fengchao, that's exactly what I needed!

Best wishes,
Miguel

**Comment by fcyu** [comment]
You are welcome!
