### ISSUE TITLE
ownership problems:

### ISSUE THREAD

**Issue by christophgil** [Nesvilab/FragPipe#461]
The following  files are owned by the user who used fragpipe the last time.
Consequently, Fragpipe fails to save the altered settings. 
cache/fragpipe-runtime.cache
cache/fragpipe-ui.cache

Suggestion: Save it in the user's home directory i.e. ~/.FragPipe/15.0/cache/

Cheers 
Christoph

**Comment by fcyu** [comment]
Hi Christoph,

The temp path can be modified. Please check https://github.com/Nesvilab/FragPipe/issues/306#issuecomment-777693128 for instructions.

Best,

Fengchao
