### ISSUE TITLE
EasyPQP (v0.1.25) in FragPipe (v16.0) `TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

### ISSUE THREAD

**Issue by GianArauz** [Nesvilab/FragPipe#473]
### Context
I'm trying to use the predefined `DIA-Umpire_SpecLib` [workflow](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#build-a-library-directly-from-dia-data) to generate a spectral library leveraging `EasyPQP`.

### Problem
I get the following error message in the FragPipe Console (please check attached `easypqp_logs.zip` for a full error description):

```
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
EasyPQP convert error END
~~~~~~~~~~~~~~~~~~~~

Cancelling 1 remaining tasks
```

### What I tried?
1. I launched the search either with `raw` and `mzML` spectrum file formats (`raw` to `mzML` conversion following [this guidelines](https://fragpipe.nesvilab.org/docs/tutorial_convert.html)).
2. I changed the default `RT Lowess fraction` from `0` to `0.05` (inspired by [this other issue response](https://github.com/Nesvilab/FragPipe/issues/421#issuecomment-897030890)).
3. Uninstall and reinstall `EasyPQP` package using Anaconda (inspired by [this other issue response](https://github.com/Nesvilab/FragPipe/issues/421#issuecomment-896140530)).
4. Change machine.

### Attached
As said above, I attach the EasyPQP logs in a zip folder ([easypqp_logs.zip](https://github.com/Nesvilab/FragPipe/files/7234630/easypqp_logs.zip)) along with the full FragPipe log ([log_2021-09-25_19-59-05.txt](https://github.com/Nesvilab/FragPipe/files/7234629/log_2021-09-25_19-59-05.txt)).

### Acknowledgment
Thank you so much for developing FragPipe and for devoting your time dealing with our issues.

**Comment by guoci** [comment]
The version of `pandas` you used was too old, somehow you manage to to install `easypqp` without satisfying the dependencies.
In Anaconda Prompt, type the following to upgrade `pandas`
`conda upgrade pandas`

**Comment by GianArauz** [comment]
### Try

I tried `conda upgrade pandas`, but the transaction did not start because my Python version was also too old. Thus I tried `conda upgrade python` (from 3.6.13 to 3.9.7), which by the way also updates `pandas` (from 1.1.5 to 1.3.2). Here is the log of the transaction: [conda upgrade python.txt](https://github.com/Nesvilab/FragPipe/files/7257824/Update.Python.transaction.Balandrau.txt).

### Result

The `DIA-Umpire_SpecLib` [workflow](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#build-a-library-directly-from-dia-data) now returns the following error (check FragPipe log: [log_2021-09-30_10-30-31.txt](https://github.com/Nesvilab/FragPipe/files/7258070/log_2021-09-30_10-30-31.txt)):

```
Traceback (most recent call last):
  File "C:\FragPipe\FragPipe-16.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 13, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml.etree'
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks
```

This is weird because the `lxml` (v4.6.3) module is installed in my `FragPipe` Anaconda environment (check `conda list` output: [conda_list.txt](https://github.com/Nesvilab/FragPipe/files/7258165/conda_list.txt)):

```
(FragPipe) C:\Users\Administrator>conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\FragPipe:
#
# Name                    Version                   Build  Channel
...
lxml                      4.6.3                    pypi_0    pypi
...
(FragPipe) C:\Users\Administrator>
```

### My conclusion

Since when I first `DIA-Umpire_SpecLib` [workflow](https://fragpipe.nesvilab.org/docs/tutorial_DIA.html#build-a-library-directly-from-dia-data) with FragPipe v15.0 I did not get all these problems, I suspect that I somehow ruined the FragPipe dependencies when updating to FragPipe v16.0, just as @guoci [pointed out](https://github.com/Nesvilab/FragPipe/issues/473#issuecomment-928106031) above.

### Next

Since I have multiple machines, I will try two strategies in parallel:

- Wait for @guoci feedback.
- Remove the `FragPipe` Anaconda environment, then uninstall and reinstall FragPipe.

**Comment by guoci** [comment]
@GianArauz You can try downloading a new version of Anaconda instead of upgrading the currently installed. I have had issues in the past where continually upgrading will not work due to failed package resolution.

**Comment by GianArauz** [comment]
### Close
Drastic but effective solution. Many many thanks @guoci !
