### ISSUE TITLE
timsTOFpro DIA files not supported?

### ISSUE THREAD

**Issue by animesh** [Nesvilab/FragPipe#474]
I am trying to run SILAC-phospho workflow on files generated by timsTOFpro in DIA mode but looks like the format is not supported ( loaded up the analysis folder at https://drive.google.com/drive/folders/14CGJ5ZZiDhHUeW16-eUYaNWln3inrqS7?usp=sharing ) , wondering if there is a workaround?

**Comment by fcyu** [comment]
Right, DIA mode does not support diaPASEF.

Best,

Fengchao
