### ISSUE TITLE
Split Database 

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#477]
Greetings @fcyu,

For split database option in fragpipe, is there any difference between 4 or 10 chunk size with regards to search result outcome (e.g. different peptides identified)?

From my understanding, the protein database ( of >200 MB in size) is split into smaller chunks. MSFragger would search the .raw files against these different chunks. Collectively, this results in significantly different search spaces with different chunk sizes. Please correct me if I am incorrect.

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

We merge the results from all chunks and estimate the expectation value with merged score histogram. We are not able to remove redundant peptides from different chunks, the merged score histogram is a little bit different from the one without splitting. Thus, most of the scores are the same as searching without splitting except for the the expectation value. But the difference is minor according to our test.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Thank you @fcyu
