### ISSUE TITLE
Linux MSFragger: could not create directory structure

### ISSUE THREAD

**Issue by jiyoungyoun** [Nesvilab/FragPipe#478]
Hi,

I have installed FragPipe on Linux Ubuntu 20.04. I'm new to using a Linux computer.
For test run, I have submitted several Thermo Raw files to search MSFragger, closed search. I have designated output files to be saved in /home/'my account'.

I receive attached error stating that 'could not create directory structure to save properties' (see attached log).

[log_2021-09-30_11-16-47.txt](https://github.com/Nesvilab/FragPipe/files/7260691/log_2021-09-30_11-16-47.txt)

Is this error due to ownership / access privilege to a given folder?

**Comment by fcyu** [comment]
FragPipe cannot write to the system cache. You can fix your permission settings or change the cache directory as described here (https://github.com/Nesvilab/FragPipe/issues/306#issuecomment-777693128).

Best,

Fengchao
