### ISSUE TITLE
easypqp error 

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#480]
- Describe the issue or question:
I am testing spectral library generation but keep getting an error message:

> Traceback (most recent call last):
>   File "C:\Users\PKJ\Desktop\msfragger2\FragPipe\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 212, in <module>
>     easypqp = get_bin_path('easypqp', 'easypqp')
>   File "C:\Users\PKJ\Desktop\msfragger2\FragPipe\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 121, in get_bin_path
>     if dist.get('files') is None and sys.platform == "win32":
> AttributeError: 'list' object has no attribute 'get'

Any help would be appreciated, Thank you,
Janos

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-09-30_18-26-24.txt](https://github.com/Nesvilab/FragPipe/files/7263441/log_2021-09-30_18-26-24.txt)
)

**Comment by guoci** [comment]
This is a known issue (#421) and has been fixed, link to the fixed version below.
https://drive.google.com/drive/folders/1yLxJmXjN8tHpOos_eFRRfz4WjlMoAtV7?usp=sharing

**Comment by andrewyy677** [comment]
Hi guoci,

When I open the above link (https://drive.google.com/drive/folders/1yLxJmXjN8tHpOos_eFRRfz4WjlMoAtV7?usp=sharing), it shows "the dir is empty". Could you please confirm if the files are present or tell me how to fix the error? Thank you!

The error message:
+ python3 -u /metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py 2023-06-05-decoys-protein_cycle2_humanswiss_contam_irt.fasta.fas ./ unused ./ True unused use_easypqp ciRT:noIM 40 '--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'\''b\'\'',\'\''y\'\'',]' '--rt_lowess_fraction 0.01' non_delete_intermediate_files
easypqp
Traceback (most recent call last):
  File "/metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py", line 213, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
  File "/metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py", line 122, in get_bin_path
    if dist.get('files') is None and sys.platform == "win32":
AttributeError: '_PackageInfo' object has no attribute 'get'

Yingying

**Comment by andrewyy677** [comment]
Hi guoci,

When I open the above link (https://drive.google.com/drive/folders/1yLxJmXjN8tHpOos_eFRRfz4WjlMoAtV7?usp=sharing), it shows "the dir is empty". Could you please confirm if the files are present or tell me how to fix the error? Thank you!
<img width="791" alt="d55974102e00a6d394f99cb9e49449e" src="https://github.com/Nesvilab/FragPipe/assets/111746469/ca041692-d9ba-45c9-b319-f5775fdd506b">

The error message:

python3 -u /metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py 2023-06-05-decoys-protein_cycle2_humanswiss_contam_irt.fasta.fas ./ unused ./ True unused use_easypqp ciRT:noIM 40 '--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types ['''b''','''y''',]' '--rt_lowess_fraction 0.01' non_delete_intermediate_files
easypqp
Traceback (most recent call last):
File "/metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py", line 213, in
easypqp = get_bin_path('easypqp', 'easypqp')
File "/metaEx/software/fragpipe/tools/speclib/gen_con_spec_lib.py", line 122, in get_bin_path
if dist.get('files') is None and sys.platform == "win32":
AttributeError: '_PackageInfo' object has no attribute 'get'
Yingying

**Comment by fcyu** [comment]
That link contains a pre-released version. Since we have released a formal one, you should upgrade yours.

Best,

Fengchao
