### ISSUE TITLE
Philosopher error when running the specLib workflow with Fragpipe v16

### ISSUE THREAD

**Issue by MarcIsak** [Nesvilab/FragPipe#483]
- Describe the issue or question:

Fragpipe stopped due to some strange Philosopher error. The last message said: _Cannot decode packed binary. strconv.ParseFloat: parsing "0,965119": invalid syntax_

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[error_fragpipe_v16.txt](https://github.com/Nesvilab/FragPipe/files/7280179/error_fragpipe_v16.txt)

**Comment by fcyu** [comment]
This is a known issue (https://github.com/Nesvilab/FragPipe/issues/444). Please change your operating system's local for now.

Best,

Fengchao
