### ISSUE TITLE
FragPipe TMT workflow script version on linux 

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/FragPipe#486]
- Describe the issue or question:
I am trying to run FragPipe TMT pipeline using a script on linux  system.
Can you share with me the goal of the command RewritePepxml ? Currently, my proteinProphet doesn’t work, and I suspect I skipped the rewrite command.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It corrects the path of the spectral file (mzml/mzxml/raw) in the interact-*.pep.xml file. But I don't think it is matter for ProteinProphet.

Best,

Fengchao
