### ISSUE TITLE
SILAC Quantification and multiple files

### ISSUE THREAD

**Issue by diegomagassis** [Nesvilab/FragPipe#487]
- Describe the issue or question:
Hello, 

 I have setup a SILAC (Leu +3) workflow for multiple files in order to compare ratios across those different runs. FragPipe was able to finish processing without any error and peptide_label_quant / protein_label_quant.tsv files with ratio values were generated. However, those files are individual for each run. Combined_protein.tsv also was generated properly containing spectra count, intensity and etc. for all samples but it seems to be related to label free quantitation.   

As we need compared ratios across the samples, is possible to generate a combined_protein file containing ratios for all samples instead of individual files? 

Thank you so much

Diego Assis
Proteomics Application Scientist - Bruker Daltonics - Billerica-MA-USA

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2021-09-26_16-51-12.txt](https://github.com/Nesvilab/FragPipe/files/7296512/log_2021-09-26_16-51-12.txt)

**Comment by fcyu** [comment]
Hi Diego,

Thanks for your interest in our tools. Currently, we don't have the combined SILAC report, but we are working on it. It should be available in the next release (or next next release if I am too busy ;) ).

Best,

Fengchao

**Comment by fcyu** [comment]
Combined label quant tsv files are available in FragPipe 18.0.

Best,

Fengchao

**Comment by lbwfff** [comment]
> Hi Diego,
> 
> Thanks for your interest in our tools. Currently, we don't have the combined SILAC report, but we are working on it. It should be available in the next release (or next next release if I am too busy ;) ).
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Regarding the quantification of SILAC with multiple files, what should I do if I want to combine the quantification? I am more interested in the peptide level than the protein level, is it appropriate to simply sum the MaxLFQ Intensity values? Or is there any other recommended method

Thanks,
LeeLee

**Comment by fcyu** [comment]
Hi LeeLee,

There have been already combined SILAC quantification reports in the latest version: combined_ion_label_quant.tsv, combined_modified_peptide_label_quant.tsv, and combined_protein_label_quant.tsv.

Best,

Fengchao
