### ISSUE TITLE
Fragpipe 16.0 mis-identifying a peptide as unique

### ISSUE THREAD

**Issue by mazbradberry** [Nesvilab/FragPipe#491]
Hi,

Fragpipe v16/msFragger v3.3 appears to identify at least one peptide as unique when it is, in fact, not. The peptide, IQLWDTAGQER, is shared among many proteins in the Rab family; for some reason, using Fragpipe v16 causes this peptide to be identified as unique to Rab33b, which is incorrect (and gives incorrect results when IonQuant is applied). The issue is NOT present with msFragger 3.3/Fragpipe v15.  I don't see any immediate examples of this occurring with other peptides/proteins, there does not appear to be a global increase in the percent of peptides identified as unique with v16 vs v15, and the two different software configurations otherwise give essentially the same results regarding uniqueness of peptides for Rab33b, but I have not compared the two results in a systematic way.  It does appear that this particular peptide is causing trouble. Both software configurations used the same database. Log and psm files from both runs are attached; please let me know if more information would be helpful.

Many thanks in advance for your help, and thank you for making great software!

-Maz Bradberry, MD/PhD student, University of Wisconsin-Madison

[log_2021-10-11_19-00-27 (FP15, MSF3.3).txt](https://github.com/Nesvilab/FragPipe/files/7326107/log_2021-10-11_19-00-27.FP15.MSF3.3.txt)

[log_2021-10-11_19-24-10 (FP16,MSF3.3).txt](https://github.com/Nesvilab/FragPipe/files/7326108/log_2021-10-11_19-24-10.FP16.MSF3.3.txt)

[psm_FP16_incorrect.txt](https://github.com/Nesvilab/FragPipe/files/7326124/psm_FP16_incorrect.txt)

[psm_FP15_correct.txt](https://github.com/Nesvilab/FragPipe/files/7326135/psm_FP15_correct.txt)

**Comment by fcyu** [comment]
Hi Maz,

The peptide IQLWDTAGQER is unique in my UniProt database (reviewed only) downloaded today. I attach it as a reference

As to "gives incorrect results when IonQuant is applied", can you elaborate it more because I don't see you ran IonQuant according to your log files.

Best,

Fengchao

[2021-10-11-decoys-reviewed-contam-UP000000589.zip](https://github.com/Nesvilab/FragPipe/files/7326328/2021-10-11-decoys-reviewed-contam-UP000000589.zip)
.

**Comment by mazbradberry** [comment]
Hi Fengchao -- yes, thank you for saving me some typing -- that is indeed the issue here (though I'm still unsure why Uniprot's website tells me those I/L switches still maintain "100% identity" when I blast the Rab33b sequence: https://www.uniprot.org/blast/uniprot/B2021101292C7BAECDB1C5C413EE0E0348724B682016B15T). 

Re: "incorrect results" in IonQuant, I meant only to say that the change from non-unique to unique status for this peptide caused a change in the identification of the most-abundant Rab in my sample from Rab3a to Rab33b, while many years of study have consistently identified Rab-3a as the most abundant Rab in this preparation. 

The next question is whether the new I/L assignment rule in the updated Philosopher is appropriate. It would seem that, in this particular case, it may not be (see e.g. https://pubs.acs.org/doi/pdf/10.1021/ac501200h). How does MSFragger/Philosopher distinguish between I and L? Perhaps it would be reasonable to let the user choose re: I/L switching when assigning peptide IDs? In case it's helpful, these data are all acquired in an Orbitrap with HCD fragmentation, with no ion mobility measurements. 

Thanks much for your quick response -- I really appreciate it.

Best,
Maz

**Comment by anesvi** [comment]
The mapping of peptide to fasta is done by PeptideProphet, which does allow both I/L possibilities. I am not sure Philosopher ever did the mapping. I think it just takes the results (the list of mapped proteins) from pep.xml. Need to check with Felipe.
However, in FragPipe 16 we changed to Percolator from PeptideProphet as default. Can you check if you used PeptideProphet in v 15 and Percolator in v 16? So perhaps with Percolator, we need to take a closer look and make minor fixes.  Thanks for letting us know, we need to investigate.
Best,
Alexey

**Comment by fcyu** [comment]
Fixed in MSFragger 3.5.
