### ISSUE TITLE
Out of memory in `philospher filter`

### ISSUE THREAD

**Issue by acesnik** [Nesvilab/FragPipe#492]
I am running into out of memory exceptions in `philosopher filter`. Is this a typical place to run into this error? Is there a way I can reduce the memory footprint of this step or skip it? It looks like it may be trying to allocate 4 TB of RAM: `runtime: VirtualAlloc of 4398220886016 bytes failed with errno=1455`

Thanks! -AC

[log_2021-10-12_06-29-55_1.txt](https://github.com/Nesvilab/FragPipe/files/7327125/log_2021-10-12_06-29-55_1.txt)

**Comment by prvst** [comment]
We'll keep an eye on the program and see if we can reproduce your problem. Thanks for reporting.
