### ISSUE TITLE
Acetylomics using TMTpro

### ISSUE THREAD

**Issue by WReiter** [Nesvilab/FragPipe#493]
- Dear Fragpipe Support Team,

we would like to use Fragpipe to analyse an acetyl-proteomics dataset. In short, we used TMTpro16plex labeling for quantification, acetyl(K)-peptides were enriched using an anti-acetyl-lysine antibody, samples were measured on a Thermo Exploris with FAIMS activated, and we performed MS2 measurements.

I have searched an exemplary file of this dataset using Fragpipe with the following settings: K 304.207146 (TMTpro) and K  42.0106 (acetyl-lysine) as variable modifications. Alternatively, I used K304.207146 as fixed and K -262.1965446 (acetyl-lysine instead of TMTpro) as variable. Both ways seem to work… Furthermore, I used Percolator or PeptideProphet (Percolator seems to work slightly better judged by the number of quantified PSMs), PTMProphet and ProteinProphet in the Validation settings.

However, the tables in the TMT-report folder are always empty (file size 1kb). Hence, my question: does the TMT report work with acetyl-proteomics approaches? If yes, which settings need to be adjusted (in what way)?

On a side note: A similar setup for a phospho-proteome study worked well in our hands…

Thank you very much for your help!

Kind regards, 

Wolfgang Reiter

**Comment by fcyu** [comment]
Fixed in version 17.1: https://github.com/Nesvilab/FragPipe/releases/tag/17.1
