### ISSUE TITLE
Error with Percolator

### ISSUE THREAD

**Issue by plbaldoni** [Nesvilab/FragPipe#494]
Hi there,

I am getting an error message when using Percolator for PSM validation (PeptideProphet works fine). Could this be somehow related to an issue with my OS?

```
Process 'Percolator' finished, exit code: -1073741515
Process returned non-zero exit code, stopping
```

The log file is [here](https://github.com/Nesvilab/FragPipe/files/7333211/log.txt).

Thanks,
Pedro

**Comment by fcyu** [comment]
Hi Pedro,

I have no clue. Can you try to run the command 

```shell
C:\\Programs\\fragpipe-16.0\\lib\\..\\tools\\percolator-v3-05.exe --only-psms --no-terminate --post-processing-tdc --num-threads 3 --results-psms 20190504_TIMS1_FlMe_SA_HeLa_frac01_A10_1_93_percolator_target_psms.tsv --decoy-results-psms 20190504_TIMS1_FlMe_SA_HeLa_frac01_A10_1_93_percolator_decoy_psms.tsv 20190504_TIMS1_FlMe_SA_HeLa_frac01_A10_1_93.pin
```
In your folder `S:\\featurePrediction\\fragpipe\\PXD019086\\combined\\test_percolator` with a command line window? Please send us the message you received from the command.

Best,

Fengchao
