### ISSUE TITLE
ProteinProphet wstring: error in Windows

### ISSUE THREAD

**Issue by maoweisd123** [Nesvilab/FragPipe#495]
- Describe the issue or question:

Computing 4140 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating sensitivity...and error tables...
terminate called after throwing an instance of 'boost::system::system_error'
  what():  boost::filesystem::path codecvt to wstring: error
FATA[15:37:42] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zip
[log_2021-10-14_15-37-42.txt](https://github.com/Nesvilab/FragPipe/files/7344146/log_2021-10-14_15-37-42.txt)
ped file by drag & drop here.)

**Comment by maoweisd123** [comment]
> @maoweisd123 Do you have any special characters in your file path? Any accentuated character?
Thank you fro your help.
It did exist some special characters in my file path. This problem was resolved.
However, when we continued to run the program, a new issue occurred about "easypqp.exe".

Traceback (most recent call last):
  File "D:\FragPipe16\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 918, in <module>
    main_easypqp()
  File "D:\FragPipe16\fragpipe\lib\..\tools\speclib\gen_con_spec_lib.py", line 726, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "D:\FragPipe16\anaconda\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\FragPipe16\\anaconda\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Using (un)calibrated.mgfs.
Spectral library building
Commands to execute:
'D:\FragPipe16\anaconda\Scripts\easypqp.exe' convert --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types '['"'"'b'"'"','"'"'y'"'"',]' --enable_unannotated --pepxml 'D:\FragPipe16\testdata\111111\interact-ZSJ05.pep.xml' --spectra 'D:\FragPipe16\testdata\ZSJ05_uncalibrated.mgf' --exclude-range -1.5,3.5 --psms ZSJ05.psmpkl --peaks ZSJ05.peakpkl
'D:\FragPipe16\anaconda\Scripts\easypqp.exe' library --psmtsv 'D:\FragPipe16\testdata\111111\psm.tsv' --peptidetsv 'D:\FragPipe16\testdata\111111\peptide.tsv' --rt_reference 'D:\FragPipe16\testdata\111111\irt.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.0 filelist_easypqp_library.txt



[log_2021-10-15_10-50-39.txt](https://github.com/Nesvilab/FragPipe/files/7350633/log_2021-10-15_10-50-39.txt)

**Comment by danielgeiszler** [comment]
@maoweisd123 Did an error with easypqp?

@guoci Have you see this one?

**Comment by maoweisd123** [comment]
> @maoweisd123 Did you also have an error with easypqp?
> 
> @guoci Have you see this one?

When I created a new user account in English, and the error with easypqp was also resolved.
