### ISSUE TITLE
PTM-Shepherd failed

### ISSUE THREAD

**Issue by chuliangcui** [Nesvilab/FragPipe#496]
- Hi, when I tried the custom offset search using MSFragger. I kept getting certain errors for PTMshepherd. However the same code can run through on others laptop. I have updated everything in the latest version.

> ~~~~~~~~~~~~~~~~~~~~
> PTMShepherd [Work dir: C:\Users\xx\Desktop\MSFragger\output]
> C:\Users\xx\fragpipe\jre\bin\java.exe -Xmx3G -Dbatmass.io.libs.thermo.dir="C:\Users\xx\fragpipe\tools\MSFragger-3.3\ext\thermo" -cp "C:\Users\xx\fragpipe\tools\ptmshepherd-1.1.0.jar;C:\Users\xx\fragpipe\tools\batmass-io-1.23.4.jar;C:\Users\xx\fragpipe\tools\commons-math3-3.6.1.jar" edu.umich.andykong.ptmshepherd.PTMShepherd "C:\Users\xx\Desktop\MSFragger\output\shepherd.config"
> 
> PTM-Shepherd version 1.1.0(c) University of Michigan
> 
> Using Java 11.0.9.1 on 3072MB memory
> 
> Counting MS2 scans for dataset sample_1
> 	0 MS2 scans present in dataset sample_1
> Counting MS2 scans for dataset sample_2
> 	0 MS2 scans present in dataset sample_2
> Counting MS2 scans for dataset sample_3
> 	0 MS2 scans present in dataset sample_3
> 
> Creating combined histogram
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -5000 out of bounds for length 0
> 	at edu.umich.andykong.ptmshepherd.peakpicker.Histogram.mergeHistogram(Histogram.java:64)
> 	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:395)
> 	Generated histogram file for dataset sample_1 [2147483647 - -2147483648]
> 	Generated histogram file for dataset sample_2 [2147483647 - -2147483648]
> 	Generated histogram file for dataset sample_3 [2147483647 - -2147483648]
> Process 'PTMShepherd' finished, exit code: 1
> Process returned non-zero exit code, stopping
> Cancelling 1 remaining tasks
> ~~~~~~~~~~~~~~~~~~~~

-Then I downloaded and also tried the example files https://fragpipe.nesvilab.org/docs/tutorial_offset.html#examine-the-results. But also got errors as below:

> ~~~~~~~~~~~~~~~~~~~~
> java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.simontuffs.onejar.Boot.run(Boot.java:340)
> 	at com.simontuffs.onejar.Boot.main(Boot.java:166)
> Caused by: umich.ms.fileio.exceptions.FileParsingException: java.util.concurrent.ExecutionException: umich.ms.fileio.exceptions.FileParsingException: Could not allocate arrays during spectra decoding step
> 	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:198)
> 	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
> 	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
> 	at edu.umich.andykong.msfragger.b.a(Unknown Source)
> 	at edu.umich.andykong.msfragger.b.a(Unknown Source)
> 	at edu.umich.andykong.msfragger.C.a(Unknown Source)
> 	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
> 	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
> 	... 6 more
> Caused by: java.util.concurrent.ExecutionException: umich.ms.fileio.exceptions.FileParsingException: Could not allocate arrays during spectra decoding step
> 	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
> 	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parse(AbstractXMLBasedDataSource.java:191)
> 	... 13 more
> Caused by: umich.ms.fileio.exceptions.FileParsingException: Could not allocate arrays during spectra decoding step
> 	at umich.ms.fileio.filetypes.mzml.MZMLPeaksDecoder.decode(MZMLPeaksDecoder.java:211)
> 	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.tagBinaryDataListStart(MZMLMultiSpectraParser.java:514)
> 	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.call(MZMLMultiSpectraParser.java:156)
> 	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.call(MZMLMultiSpectraParser.java:55)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 	at umich.ms.fileio.filetypes.mzml.MZMLPeaksDecoder.decode(MZMLPeaksDecoder.java:207)
> 	... 7 more
> Process 'MSFragger' finished, exit code: 1
> Process returned non-zero exit code, stopping
> Cancelling 12 remaining tasks
> ~~~~~~~~~~~~~~~~~~~~

-Is there anything wrong with my laptop settings?
-Thanks.
-Liangcui

**Comment by danielgeiszler** [comment]
If there’s nothing else, I’m going to close this.
