### ISSUE TITLE
annotation in TMT6plex

### ISSUE THREAD

**Issue by Danrather** [Nesvilab/FragPipe#499]
- Describe the issue or question:
I am using FragPipe to analyse a TMT6plex dataset comparing 2 conditions in triplicates (set C versus set D). When loading the annotation stubs for TMT-6  I get the correct list of labels. But then in the result tables not all of my sample names are listed but some are exchanged by labels that are not part of TMT6plex.

my annotation.txt is
126 C1
127N D1
128C C2
129N D2
130C C3
131 D3

and in the basic quantification options I selected the "TMT-6" as label type. 
Yet in the result tables I have the following column headers for the quan values :
C1 / D1 / **127C / 128N** / C2 /  D2

Label 127 should be a sample from set D , but the values in column **127C** clearly show that is a sample from set C.

Thank you in advance for your help.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2021-10-19_12-48-05.zip](https://github.com/Nesvilab/FragPipe/files/7373581/log_2021-10-19_12-48-05.zip)

**Comment by prvst** [comment]
We got this issue reported some months ago, and we implemented the correction. It will be available in the next version, soon to be released.
