### ISSUE TITLE
Error when processing a TIMS-ToF data file with FP17

### ISSUE THREAD

**Issue by JesseIL** [Nesvilab/FragPipe#513]
Tried processing one Bruker raw file (TIMS-ToF Pro) with FragPipe 17 and it failed.
Here's a link to the log file: https://owncloud.incpm.weizmann.ac.il/index.php/s/aJ3XaNJwu5zqaU6

**Comment by fcyu** [comment]
This is a known issue: https://github.com/Nesvilab/FragPipe/issues/431. For now, you can install Visual C++ 2010 or put `msvcr100.dll` to the folder where Percolator is.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @JesseIL ,

Here (https://www.dropbox.com/s/s8wlt6camz5wrhq/FragPipe-17.1-build2.zip?dl=0) is the fixed version. Can you try to see if it fixes your problem?

Thanks,

Fengchao
