### ISSUE TITLE
Error with Protein Prophet 

### ISSUE THREAD

**Issue by hcahaya** [Nesvilab/FragPipe#517]
Hello, 
I tried to process my .d Bruker timsTOF data and encountered this error that I never saw before. 
I saw an older post on the same error and it suggested that it could be due to the data. So I used an old data that was successfully processed by Fragpipe. Interestingly, it has the same Protein Prophet error as well. Any advise on what to do? Thank you 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-11-08_14-48-15.txt](https://github.com/Nesvilab/FragPipe/files/7500766/log_2021-11-08_14-48-15.txt)
)

**Comment by fcyu** [comment]
The log from PeptideProphet looks weird. I guess there are old temp `interact-*` files in your result folder, which caused the issue. Can you deleting all `interact-*` files and run from PeptideProphet again? You can uncheck MSFragger.

Best,

Fengchao

**Comment by hcahaya** [comment]
Hi Fengchao, 
I removed the folder where the result was dumped. In other words, I started everything from scratch with new result folder. 
I also ran PeptideProphet only. 
Still same error :(
Any advice? Truly appreciate your help. 
[log_2021-11-09_15-05-44.txt](https://github.com/Nesvilab/FragPipe/files/7508546/log_2021-11-09_15-05-44.txt)

**Comment by fcyu** [comment]
This error is weird. I have no clue. Can you try switching to Percolator for now?
![image](https://user-images.githubusercontent.com/6926299/141027375-b9dbdf6b-3917-4aeb-b643-b61d73e43bb4.png)

Best,

Fengchao

**Comment by hcahaya** [comment]
Ran it on Percolator as you advised. It still has some issues :( 
[log_2021-11-10_14-44-50.txt](https://github.com/Nesvilab/FragPipe/files/7516411/log_2021-11-10_14-44-50.txt)

**Comment by fcyu** [comment]
Everything looks good until Philosopher filter command. 

Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by anesvi** [comment]
We had this error before, looks like it came back? Felipe, what was causing it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by danielgeiszler** [comment]
This happens when there are incomplete temp interact* files in the folder. Do you have anything that looks like a temporary file that didn’t finish writing?

**Comment by fcyu** [comment]
I think I can let FragPipe delete all files starting with `interact-` if it runs from PeptideProphet or Percolator.

Best,

Fengchao

**Comment by hcahaya** [comment]
After deleting the incomplete temp interact* files, running FragPipe with Percolator worked smoothly. 
But, when I switched back to run on PeptideProphet, it still gave me an error (there were no temp files before running this). 
When PSM validation needs to be done, when should one run with PeptideProphet or Percolator? 
Thank you

[log_2021-11-10_15-57-23.txt](https://github.com/Nesvilab/FragPipe/files/7516780/log_2021-11-10_15-57-23.txt)
.

**Comment by fcyu** [comment]
PeptidePrpohet has the error same as the one you reported. I can't figure out the cause.

Normally, you can use Percolator in most cases except for open search, glyco search, and mass-offset search.

Best,

Fengchao

**Comment by prvst** [comment]
I checked the logs, and the filter wasn't even executed. The problem happens during Peptideprophet execution. Although I can't say without sure without handling the file, I suspect something is not right with the file assignment or file name

**Comment by prvst** [comment]
Also, please ensure you have enough permissions to run the program in that particular location, try running it in a different place inside your user folder.

**Comment by fcyu** [comment]
```
Computing MU for 16840 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO[14:44:37] Done                                         
Process 'ProteinProphet' finished, exit code: 0
PhilosopherDbAnnotate [Work dir: D:\FragResults\211103_PS15_ShortGrad_30SPD_60C_HeLa\250ng\3\3]
C:\fragpipe\tools\philosopher\philosopher.exe database --annotate C:\FASTA\2021-11-04-decoys-reviewed-contam-UP000005640.fas --prefix rev_
INFO[14:44:37] Executing Database  v4.1.0                   
INFO[14:44:37] Annotating the database                      
Process 'PhilosopherDbAnnotate' finished, exit code: 0
INFO[14:44:40] Done                                         
PhilosopherDbAnnotate [Work dir: D:\FragResults\211103_PS15_ShortGrad_30SPD_60C_HeLa\250ng\3]
C:\fragpipe\tools\philosopher\philosopher.exe database --annotate C:\FASTA\2021-11-04-decoys-reviewed-contam-UP000005640.fas --prefix rev_
INFO[14:44:40] Executing Database  v4.1.0                   
INFO[14:44:40] Annotating the database                      
INFO[14:44:43] Done                                         
Process 'PhilosopherDbAnnotate' finished, exit code: 0
PhilosopherFilter [Work dir: D:\FragResults\211103_PS15_ShortGrad_30SPD_60C_HeLa\250ng\3\3]
C:\fragpipe\tools\philosopher\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml D:\FragResults\211103_PS15_ShortGrad_30SPD_60C_HeLa\250ng\3\3 --protxml D:\FragResults\211103_PS15_ShortGrad_30SPD_60C_HeLa\250ng\3\combined.prot.xml --razor
INFO[14:44:44] Executing Filter  v4.1.0                     
INFO[14:44:44] Processing peptide identification files      
FATA[14:44:49] Cannot decode packed binary. EOF             
Process 'PhilosopherFilter' finished, exit code: 1
```

ProteinProphet followed by database annotation have finished. The error was from the filter command. As Danny explained (and confirmed by the user), that is because there are temp files starting with `interact-` from the previous analysis. Philosopher filter command tried to read it and then, crashed. 

Best,

Fengchao

**Comment by prvst** [comment]
Which log is that? the ones I have here end with PeptideProphet

**Comment by fcyu** [comment]
That is a different one. There are two errors. One is from PeptideProphet, which I cannot figure out the reason. The other one is from filter command.

Best,

Fengchao

**Comment by prvst** [comment]
Look the way how the lines end with `D: -`. Does that look normal?

![image](https://user-images.githubusercontent.com/403705/141218859-6f5278c3-8f08-47c8-9328-bb9ce1aafcc2.png)

**Comment by danielgeiszler** [comment]
Are you trying to write the output to a remote server, by chance?

**Comment by fcyu** [comment]
@prvst I think this is due to your editor. This is what I see with Sublime text
![image](https://user-images.githubusercontent.com/6926299/141219238-e1fca6a8-fd39-45d8-a770-4f7c983abdfd.png)

**Comment by anesvi** [comment]
We should recognize and delete those temp files I guess

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fcyu** [comment]
> We should recognize and delete those temp files I guess

Implemented in https://github.com/Nesvilab/FragPipe/commit/b536f03894ac617b8de0cd473ca05a1b29761e59 and https://github.com/Nesvilab/FragPipe/commit/02f6a2d8b0432f702f11cb1503d58c16b2ebf866

Best,

Fengchao

**Comment by hcahaya** [comment]
Hello, after moving the raw file to another folder and creating a new result folder, FragPipe ran smoothly with PeptideProphet. 
Not exactly sure why that is, But I'll do whatever it takes to make it work. 
Thank yo
[log_2021-11-11_15-37-14.txt](https://github.com/Nesvilab/FragPipe/files/7529977/log_2021-11-11_15-37-14.txt)
u

**Comment by hcahaya** [comment]
Hello, after moving the raw file to another folder and creating a new result folder, FragPipe ran smoothly with PeptideProphet. 
Not exactly sure why that is, But I'll do whatever it takes to make it work. 
Thank you
[log_2021-11-11_15-37-14.txt](https://github.com/Nesvilab/FragPipe/files/7529989/log_2021-11-11_15-37-14.txt)
