### ISSUE TITLE
Would wrapping FragPipe into a Nextflow pipeline make sense?

### ISSUE THREAD

**Issue by fabianegli** [Nesvilab/FragPipe#518]
Nextflow would be kind of an alternative to FragPipe and it would allow easy adoption, modification and extension of the workflow by the community.

This issue is to some extent a continuation of #462 but it is Nextflow specific.

Nextflow is the easiest to use if all software can simply be downloaded from the internet to the compute infrastructure running the pipeline. However, this is not possible for MSFragger -  it has to be downloaded separately as a means to inform the user about the licensing terms. This is also the case when MSFragger is used in FragPipe.

I found some other Nextflow modules/pipelines (e.g. [epitopeprediction](https://github.com/nf-core/epitopeprediction/pull/73) that depend on 3rd party software and it should be possible to use the same techniques they use for MSFragger. 

There is currently no Nextflow module for MSFragger or any other tool in the FragPipe pipeline, as far as I know. I also don't know of anyone working on this apart from my own rudimentary attempts.

Wrapping a Nextflow module around a headless FragPipe should be relatively straight forward.

I believe that while being straight forward, that this approach would also null some of the resource management benefits that would arise form having one module per tool in the Nextflow pipeline. So I think it is a trade-off between flexibility and performance and the convenience of the implementation.

**Comment by fcyu** [comment]
I think we mostly care about if it is easy to use and fast (sensitivity and accuracy are not related to a user interface). We normally don't care too much about if it is easy to implement. I would rather write more code to make is faster. For example, to get a smaller file size and faster IO, we handcraft serialization and deserialization functions in MSFragger and IonQuant.

With this in mind, could you please tell us if Nextflow can make users (mostly biologist and bioinformatician) easier to use our tools compared to a headless FragPipe (basically a jar-file-based command line tool)?

Guo Ci and I think it is not difficult to implement a headless FragPipe. After having the headless FragPipe, I don't think it is very helpful to have Nextflow wrapping the headless FragPipe, since they basically do the same thing.

Best,

Fengchao

**Comment by fabianegli** [comment]
The simple answer is yes, Nextflow provides benefits. Especially if it will end up being an nf-core pipeline it will be easier to use for biologist. Check out the web interface for the nf-core [proteomicslfq](https://nf-co.re/proteomicslfq) pipeline. The things to note: The self-documenting properties, the fact that code and documentation live in the same place makes it easier to keep it in sync, the fact that you can "launch" it from the web interface where you put in the parameters in a easy to use and documented form, that you can then go ahead and youse the parameter set just created on the website in your environment, ... There are many convenience and usabilit benefits that Nextflow provides compared to simply a command line tool. I don't have the answer if these benefits weigh up the the additional hassle of the implementation, added maintenance load. That answer probably mainly depends on who gives it. And if you want to go ahead and see if you can grow you user base by providing a range of another interfaces to your software.

**Comment by fabianegli** [comment]
And what I forgot to mention is that Nextflow basically takes care of the software installation (apart form what can't be freely downloaded.)

Now, for  example one still has to install Anaconda, create an environment, install the dependencies and set the Python path in FragPipe. All manually. And of course the same goes for the philosopher installation. That's the work you can have Nextflow do for your users. That's a big win for usability.

**Comment by fabianegli** [comment]
And then there's reproducibility. Nextflow tracks all software versions and it's possible to use containers for even better reproducibility.

**Comment by fcyu** [comment]
I am afraid I cannot agree with you regarding the installation. 

Users don't need to install FragPipe if they don't use the split database and spectral library building modules. They just need to unzip it. Same applies to MSFragger and Philosopher. However, users need to install Nextflow and docker/singularity before really downloading and installing a specific workflow. 

I am not sure about installing Nextflow, but installing docker is pain in the ass, especially in Windows. You need to have admin permission, and your system need to be compatible with something. Our Windows in the lab can't install docker due to the permission/compatibility issue. I think some universities' IT department have even more strict regulations. Thus, if it needs to install something needs Adimin permission, we will not use it.

If the reproducibility requires containers, then no thanks. We can have the same reproducibility ability since we have clear version history.

Best,

Fengchao

**Comment by fabianegli** [comment]
I feel your pain about the containerization, installation requirements and unsurmountable permission hurdles for users of shared resources. And I applaud you for making Software that allows users to easily use it!

I am more a unix than a Windows person, so please let me know if I get some Windows related things wrong.

Docker is just one way to run Nextflow pipelines, you can run them with conda instead or use Singularity or Podman or ... run it in the cloud. So admin rights are not strictly required to run a Nextflow pipeline. The really mandatory requirement is Java, but that's a dependency that FragPipe has too.

Some systems come with a containerization tool preinstalled and then all the installation hassle disappears. I can only recommend to browse https://www.nextflow.io/docs/latest/index.html to get some idea about how/where people use it. 

I do need to use the split database and the sysadmins on the infrastructure I use reset the systems every month. So I have the pleasure to go through the process of installing the necessary tools every couple of weeks. It doesn't bother me much but I would appreciate it if I didn't have to do it. Inexperienced users may even fail to install the requirements without help.

> If the reproducibility requires containers, then no thanks. We can have the same reproducibility ability since we have clear version history.

Having a version history of the software you control required but not sufficient for reproducibility in data analysis pipelines. e.g. it does not protect against changes in the OS, OS version or other dependencies for which the versions are not tracked or which have been customized for some reason.

**Comment by tobiasko** [comment]
I would like to add some points to the discussion from a core facility perspective: We are more and more looking into scaleable data analysis workflows for proteomics and workflow managers like Galaxy or nextflow might be a good tool (we haven't really tested them yet) to get there. But we are already using docker containers. I just read this review https://pubmed.ncbi.nlm.nih.gov/31657527/ and mostly agree with their proposal. Is it less work for the "normal" user? I guess not, but for our environment GUI applications are a no-go area and we would like to have workflows that can be controlled using web interface und use our comp. backend (HPC).

**Comment by sarah-haynes** [comment]
@tobiasko a Galaxy version of FragPipe is in the works, there should be some discussion at this event on Dec 15: https://docs.google.com/document/d/10lECIsd9tqC4IXWjqcINZDSduKn-1afoN9Q5r7IW8vg/edit

**Comment by tobiasko** [comment]
UHHHH! I totally missed this post @sarah-haynes Was the session recorded?

**Comment by fcyu** [comment]
Hi @tobiasko ,

It is recorded, although I don't know where to find the link. The talk is mostly about the stuff we already have. There is just one slide about the screen record of FragPipe running in the command line.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi all,

The first beta version of FragPipe headless is ready. Here (https://www.dropbox.com/sh/68iwzfmk1fmpxms/AAB49KjH_-7H_vIO_yMnjavOa?dl=0) is the link to download it. It is actually part of FragPipe. To trigger the headless mode, type `fragpipe.bat` in Windows or `fragpipe` in Linux followed by the options:

```shell
Running without GUI. Usage:
        Windows: fragpipe.bat --headless --workflow <path to workflow file> --manifest <path to manifest file> --workdir <path to result directory>
        Linux: fragpipe --headless --workflow <path to workflow file> --manifest <path to manifest file> --workdir <path to result directory>
Options:
        -h
        --help                          # Print this help message.
        --headless                      # Running in headless mode.
        --workflow <string>             # Specify path to workflow file.
        --manifest <string>             # Specify path to manifest file.
        --workdir <string>              # Specify the result directory.
        --dry-run                       # (optional) Dry run, not really run FragPipe.
        --ram <integer>                 # (optional) Specify the maximum allowed memory size. Set it to 0 to let FragPipe decide. Default = 0
        --threads <integer>             # (optional) Specify the number of threads. Default = core number - 1
        --config-msfragger <string>     # (optional) specify the location of the MSFragger jar file. If not specified, using the one in the cache.
        --config-philosopher <string>   # (optional) specify the location of the Philosopher binary file. If not specified, using the one in the cache.
        --config-python <string>        # (optional) specify the location of the Python directory. If not specified, using the one in the cache.
```

For the first time using it, we recommend loading the spectral files in FragPipe GUI, saving the workflow and manifest files. Then, update the `database.db-path` parameter at the beginning of the workflow file. Run FragPipe headless using the workflow and manifest files.

Please feel free to let us know if you have any questions or find any bugs.

Merry Christmas and happy new year,

Fengchao

**Comment by tobiasko** [comment]
Thanks for this cool Christmas present! Downloading!

Have a nice holiday season and a happy new year! 🥳 

Tobi

**Comment by nilselars** [comment]
@fabianegli Did you progress with the Nextflow wrapper for MSFragger? So far I cannot find any pipeline in [nf-core](https://nf-co.re/). Thanks.

**Comment by fcyu** [comment]
Hi @nilselars ,

I don't think it is still necessary to wrap it in nextflow because we have implemented a native headless mode https://fragpipe.nesvilab.org/docs/tutorial_headless.html . It uses the same code base of FragPipe GUI, so it produces the identical results and also easier to use than the nextflow pipeline. Please have a try and let me know if you have any suggestions and questions.

Best,

Fengchao
