### ISSUE TITLE
diaPASEF with FragPipe 17

### ISSUE THREAD

**Issue by uonnet** [Nesvilab/FragPipe#519]
Hi,

I was using the latest FragPipe 17 on some diaPASEF data, trying to run DIA-NN on it. But I got the pop-up message that no LCMS files were provided after excluding diaPASEF runs. Does the lastest FragPipe release support diaPASEF? Thank you!
![2021-11-09-02](https://user-images.githubusercontent.com/54391198/140881288-4c5093bd-7a2f-493c-93bf-e5bbd717c681.png)
![2021-11-09-01](https://user-images.githubusercontent.com/54391198/140881293-c3b43eea-8ef0-4099-a0e3-bcc696365088.png)

**Comment by fcyu** [comment]
FragPipe cannot build a spectral library using diaPASEF. To quantify diaPASEF, you need to have ddaPASEF to build a library.

Best,

Fengchao

**Comment by uonnet** [comment]
If I just want to do directDIA, which workflow do I use or how do I set up FragPipe?

**Comment by fcyu** [comment]
directDIA only support non-diaPASEF file. You can use `DIA_SpecLib_Quant` workflow.

Best,

Fengchao

**Comment by uonnet** [comment]
And `DIA_SpecLib_Quant` workflow needs ddaPASEF for the spectral library?

**Comment by fcyu** [comment]
Yes.
