### ISSUE TITLE
nonspecific peptidome search issue - likely related to python

### ISSUE THREAD

**Issue by jadv12** [Nesvilab/FragPipe#522]
Hi (again),

I am also trying to run a peptidomic analysis using the default workflow on FragPipe with some minor changes:

- tims = selected
- precursor mass tolerancen = 70 ppm
- fragment mass tolerance= 40 ppm
- MS1 Quant turned on
- MBR turned on with minimim ion = 1
- Human UniProt database containing isoforms

I am running into an error, something about splitting. I checked previous issues and maybe this is similar to #403 (though I am not sure).

![image](https://user-images.githubusercontent.com/93340685/140999838-3eecbae8-3efa-477f-9a48-f7912e175d76.png)
[log_2021-11-09_14-53-22.txt](https://github.com/Nesvilab/FragPipe/files/7507769/log_2021-11-09_14-53-22.txt)

Thank you as always!

**Comment by jadv12** [comment]
I ran it again last night with completely default parameters, aka MSQuant1 was left unchecked. And the run completed successfully within 83 minutes. So maybe there is an issue with the IonQuant tab?

**Comment by jadv12** [comment]
I ran it again last night with completely default parameters, aka MSQuant1 was left unchecked. And the run completed successfully within 83 minutes. So maybe something goes awry with the IonQuant quantification? (Again, I am only guessing.)

**Comment by fcyu** [comment]
The error was from split script and not related to IonQuant. The specific error message is `FileNotFoundError: [Errno 2] No such file or directory: 'split_peptide_index_tempdir/0/20210708_timsTOF_EVO_CDS_VanJ_MW1_S1-B5_1_321_scores_histogram.tsv'`.

If it ran successfully, then I don't think this error can be reproduced. I guess something was wrong with your file system to make the file `split_peptide_index_tempdir/0/20210708_timsTOF_EVO_CDS_VanJ_MW1_S1-B5_1_321_scores_histogram.tsv` gone.

If you want, you can re-run it with IonQuant enabled.

Best,

Fengchao

**Comment by jadv12** [comment]
I can confirm that everything worked out successful with and without IonQuant on. Thank you!
