### ISSUE TITLE
The same protein group has different protein IDs in protein.tsv files from different experiments

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#523]
- Describe the issue or question:
Hi,

I am trying to quantitate a group of timsTof dda experiments using ionQuant and close to end of the process I got an error that I don't quite understand. Could you help me find out what the issue is and how to get around it?

Thank you,
Janos

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-11-09_20-49-57_error.txt](https://github.com/Nesvilab/FragPipe/files/7509948/log_2021-11-09_20-49-57_error.txt)
)

**Comment by fcyu** [comment]
Hi Janos,

The error message is `The protein group 3053 and subgroup a in G:\Mohammad_2103_\210330_nasal_drugs\nasal_imac_msf2\CAY_1/protein.tsv are not consistent with those in another protein.tsv`, which means that the protein group 3053 a has different protein IDs in you protein.tsv. It should not happen. Can you help to check? You can also send all of your protein.tsv to us to take a look.

Thanks,

Fengchao

**Comment by jd690764** [comment]
Hi Fengchao,

This is very strange, here is the protein that is causing the trouble:

    group sub_group      protein   protein_id   entry_name gene length
                   ds
 1:   984         a NP_001349898 NP_001349898 NP_001349898         795
  ./CAY_1/protein.tsv
 2:  3053         a NP_001349898 NP_001349898 NP_001349898         364
  ./CAY_1/protein.tsv
 3:  3053         a NP_001349898 NP_001349898 NP_001349898         364
  ./CAY_2/protein.tsv
 4:   984         a NP_001349898 NP_001349898 NP_001349898         795
 ./DMSO_1/protein.tsv
 5:  3053         a NP_001349898 NP_001349898 NP_001349898         364
 ./DMSO_1/protein.tsv
 6:  3053         a NP_001349898 NP_001349898 NP_001349898         364
 ./DMSO_2/protein.tsv
 7:  3053         a NP_001349898 NP_001349898 NP_001349898         364
 ./DMSO_3/protein.tsv
 8:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./Forskolin_1/protein.tsv
 9:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./Forskolin_2/protein.tsv
10:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./Forskolin_3/protein.tsv
11:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./SPIKE_1/protein.tsv
12:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./SPIKE_2/protein.tsv
13:  3053         a NP_001349898 NP_001349898 NP_001349898         364
./SPIKE_3/protein.tsv

I double checked it, it's only present once in the library. (A side
question: What does subgroup mean here?)

Thank you,
Janos

**Comment by fcyu** [comment]
Hi Janos,

Thanks for your info. Can you show me all proteins with `3053 a` and `984 a` groups?

Thanks,

Fengchao

**Comment by jd690764** [comment]
Here they are:

    group sub_group      protein   protein_id   entry_name gene length
                                protein_description
 ds
 1:   984         a NP_001349898 NP_001349898 NP_001349898         795 zinc
finger C2HC domain-containing protein 1A isoform 2       ./CAY_1/protein.tsv
 2:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2       ./CAY_1/protein.tsv
 3:   984         a NP_001349997 NP_001349997 NP_001349997         795
 cell cycle and apoptosis regulator protein 2 isoform 2
./CAY_2/protein.tsv
 4:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2       ./CAY_2/protein.tsv
 5:   984         a NP_001349898 NP_001349898 NP_001349898         795 zinc
finger C2HC domain-containing protein 1A isoform 2      ./DMSO_1/protein.tsv
 6:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2      ./DMSO_1/protein.tsv
 7:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2      ./DMSO_2/protein.tsv
 8:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2      ./DMSO_3/protein.tsv
 9:   984         a NP_001349989 NP_001349989 NP_001349989         795
microtubule-associated tumor suppressor 1 isoform 9
./Forskolin_1/protein.tsv
10:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2 ./Forskolin_1/protein.tsv
11:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2 ./Forskolin_2/protein.tsv
12:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2 ./Forskolin_3/protein.tsv
13:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2     ./SPIKE_1/protein.tsv
14:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2     ./SPIKE_2/protein.tsv
15:  3053         a NP_001349898 NP_001349898 NP_001349898         364 zinc
finger C2HC domain-containing protein 1A isoform 2     ./SPIKE_3/protein.tsv

Thanks,
Janos

**Comment by fcyu** [comment]
Thanks Janos,

This is a bug in Philosopher that creates the same protein group ID with different proteins. For group `984 a`, there are protein.tsv having protein `NP_001349898`, `NP_001349997`, and `NP_001349989`. Theoretically, the same protein group always has the same protein ID.

Hopefully, Felipe @prvst can fix this bug soon.

Best,

Fengchao

**Comment by prvst** [comment]
Hi @fcyu, philosopher does not create or alter the protein groups, it borrows from ProteinProphet, which is the program that makes them. I need to see more data before guessing what's the issue. @jd690764, could you send me your prot.xml, psm.tsv, and protein.tsv files?

**Comment by jd690764** [comment]
Hi Felipe,

I gave you access to the data with your umich email - I sent you an email
to that address. Please, let me know if there are any issues accessing it.

Thank you,
Janos

**Comment by prvst** [comment]
@jd690764 The file share is requesting an authentication from my @med.umich account, which does not exist (in Google). To make it easier, I'm sending you a file share request via my [Dropbox](https://www.dropbox.com/request/nxNI1LOApZ8Ax3k3ob7k)

**Comment by jd690764** [comment]
Hi Felipe,

I uploaded the data - thank you for looking into this.

Janos

**Comment by Monod79** [comment]
Hi everyone, 

Maybe this can help, I've got the same issue as Janos while running FragPipe v17.0. I ran the same analysis with FragPipe v16.1 build 5 and everything ran smoothly with no error. 

Joe

**Comment by fcyu** [comment]
Thank you! Here is the link: https://www.dropbox.com/request/kG1NENHn00REagbkFepR

Best,

Fengchao

**Comment by Monod79** [comment]
Which files do you need Fengchao?

**Comment by fcyu** [comment]
Spectral files (mzML, raw, or .d), fragger.params, fasta file, and the log file.

Thanks,

Fengchao

**Comment by Monod79** [comment]
Files have been uploaded. 

Thanks for your help Fengchao !

**Comment by prvst** [comment]
@jd690764 can you also upload your database?

**Comment by jd690764** [comment]
Hi Felipe,

I uploaded the library.

Thanks,
Janos

**Comment by prvst** [comment]
I found and corrected a mismatch between ProteinProphet, and Philosopher. Its seems to have resolved both cases. The fix will be added to the next release. Thanks for the feedback.

**Comment by jd690764** [comment]
Thank you, Felipe!

When do you think the new update will be available?

Janos

**Comment by Monod79** [comment]
Thanks Felipe!

**Comment by jd690764** [comment]
Hi Felipe,

v17.1 is working fine!

Thanks,
Janos

**Comment by fcyu** [comment]
Hi Felipe @prvst ,

Have you made any changed in Philosopher for this issue? If not, I don't think this issue has been fixed. There are two users in this thread. I have @Monod79 's file and reproduced the issue. I am putting my files to `Z:\yufe\for_Felipe\github_fragpipe_523`.

Best,

Fengchao
