### ISSUE TITLE
does the "DIA_SpecLib_Quant" (v17.0) have the same function with "SpecLib" (v16.0)? how to build the spectral libraries using DDA data in the new version of Fragpipe?

### ISSUE THREAD

**Issue by zhucuilicas** [Nesvilab/FragPipe#524]
- Describe the issue or question: 
- 
- Hi, I'm trying to build the spectral library using only DDA data in Fragpips (v17.0), I tried the "DIA_SpecLib_Quant" workflow but didn't get the "library.tsv" file. I am wondering which workflow in the new version of Fragpipe has the same function as the "SpecLib" (v16.0)? could we get the library with the same name "library.tsv"?  
Thank you so much for your help!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
>  I am wondering which workflow in the new version of Fragpipe has the same function as the "SpecLib" (v16.0)? could we get the library with the same name "library.tsv"?

You are using the correct workflow. There will be library.tsv if everything goes well. Please upload your log file.

Best,

Fengchao

**Comment by zhucuilicas** [comment]
Attached please check the newest log file. Would you like to give me some suggestions? Thanks a lot!


[log_2021-11-10_17-14-54.txt](https://github.com/Nesvilab/FragPipe/files/7516450/log_2021-11-10_17-14-54.txt)

**Comment by fcyu** [comment]
There is an error in your spectral library generating step:
```
F:\FragPipe-jre-17.0\Python\python -u F:\FragPipe-jre-17.0\fragpipe\tools\speclib\gen_con_spec_lib.py F:\DIA_Hela\Hela_library_DDAdata_Fragpipe\DIA_NN_results\2021-11-10-decoys-reviewed-contam-UP000005640.fas F:\DIA_Hela\Hela_library_DDAdata_Fragpipe\results unused F:\DIA_Hela\Hela_library_DDAdata_Fragpipe\results True unused use_easypqp noiRT;noIM 11 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.0" delete_intermediate_files F:\DIA_Hela\Hela_library_DDAdata_Fragpipe\results\filelist_speclibgen.txt
Traceback (most recent call last):
  File "F:\FragPipe-jre-17.0\fragpipe\tools\speclib\gen_con_spec_lib.py", line 13, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'
```

Guo Ci @guoci, can you take a look?

Thanks,

Fengchao

**Comment by danielgeiszler** [comment]
It looks like python is missing one of the libraries it needs for spectral library generation.

This should be fixable by opening the command line and running “pip install lxml” to grab the necessary library.

Have you changed python versions or operating systems since the last time you ran this?

**Comment by zhucuilicas** [comment]
> It looks like python is missing one of the libraries it needs for spectral library generation. This should be fixable by opening the command line and running “pip install lxml” to grab the necessary library. Have you changed python versions or operating systems since the last time you ran this?

Thank you so much for your valuable suggestion! FragPipe is working well now. I installed the lxml and then I got the library.tsv file.
