### ISSUE TITLE
PTM sheperd fails

### ISSUE THREAD

**Issue by Peer2011** [Nesvilab/FragPipe#527]
Dear Alexey and Fengchao, 

Any idea why this could have happened. I analyzed 5 mzml files with open search settings to identify which modifications I should add for the open search. I got this error message from PTM sheperd. 

Best, Peer 

Process 'PhilosopherAbacus' finished, exit code: 0
PTMShepherd [Work dir: C:\01_Data_Analysis\TEST]
C:\01_ScientificSoftware\Fragpipe_17.0\jre\bin\java.exe -Xmx108G -Dbatmass.io.libs.thermo.dir="C:\01_ScientificSoftware\Fragpipe_17.0\tools\MSFragger-3.4\ext\thermo" -cp "C:\01_ScientificSoftware\Fragpipe_17.0\tools\ptmshepherd-1.2.5.jar;C:\01_ScientificSoftware\Fragpipe_17.0\tools\batmass-io-1.23.6.jar;C:\01_ScientificSoftware\Fragpipe_17.0\tools\commons-math3-3.6.1.jar" edu.umich.andykong.ptmshepherd.PTMShepherd "C:\01_Data_Analysis\TEST\shepherd.config"

PTM-Shepherd version 1.2.5(c) University of Michigan

Using Java 11.0.9.1 on 110592MB memory

Finding and caching spectral data
	Indexing data from 1
	Caching data from 1
		MS(1) - 54117 (2792 ms, 353 ms)
	Done caching data from 1
	Indexing data from 2
	Caching data from 2
		MS(2) - 51200 (1864 ms, 285 ms)
	Done caching data from 2
	Indexing data from 3
	Caching data from 3
		MS(3) - 54235 (1628 ms, 207 ms)
	Done caching data from 3
	Indexing data from 4
	Caching data from 4
		MS(4) - 50158 (1490 ms, 220 ms)
	Done caching data from 4
	Indexing data from 5
	Caching data from 5
		MS(5) - 42860 (1471 ms, 223 ms)
	Done caching data from 5
Done finding and caching spectral data
Counting MS2 scans for dataset 1
Fatal error: Invalid MS2 counts for run MS(1) in dataset 2
	54117 MS2 scans present in dataset 1

Counting MS2 scans for dataset 2
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by Peer2011** [comment]
What I do not get is why PTM sheperd is starting though it was not activated in the configuration.

**Comment by anesvi** [comment]
What do you “not activated”? The open search workflow has it. Did you uncheck ptm-shepherd and it still run?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Peer2011** [comment]
I was confused by PTM prophet and PTM sheperd. So PTM prophet was deactivated and PTM sheperd activated as it should be and it ran smoothly until the point that PTM sheperd is supposed to do the localization of identified modifications with the error message that I have attached to my first post. Do you happen to have any idea why this could be. I configured Fragpipe just by loading the open search preset.

**Comment by danielgeiszler** [comment]
Hi Peer2011,

This is already fixed and will be released with the next FragPipe release.

If you can't wait, you can download the standalone version of PTM-Shepherd from this ticket:

https://github.com/Nesvilab/FragPipe/issues/514#issue-1047107194

Best,
Danny

**Comment by anesvi** [comment]
We are releasing FragPipe 17.1 with this and a few other fixes very soon, hopefully today
