### ISSUE TITLE
Ion mobility information in spectral library

### ISSUE THREAD

**Issue by cacagong** [Nesvilab/FragPipe#528]
Dear developers,

Thank you for this amazing software. 
Recently, I am trying to analyze diaPASEF data from timTOF Pro. For doing that I generated a spectral library from PASEF-DDA data through using EasyPQP. 
But, it seem like that there is **no column or information of ion mobility** in the output spectral library from EasyPQP.
Where I can find that information if it is generated or do I need to specify something else to have that information?

Thanks,
Dong-Gi

**Comment by cacagong** [comment]
I am sorry, that was my mistake! I got it. 
I wonder one more thing regarding MS1Quant. I had no issues with Orbitrap data. 
But I cannot find total intensity value using timTOF Pro file. Every value on 'total intensity' column is zero.
It seems like there is error during the run, I am attaching a part of log.

Thanks,

[log.txt](https://github.com/Nesvilab/FragPipe/files/7549874/log.txt)

**Comment by guoci** [comment]
@cacagong you are using and old version of FragPipe. Please try the latest release.

**Comment by fcyu** [comment]
Hi @cacagong ,

It is not about the version. I think you don't have the `ext` folder or don't have Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) installed.

Best,

Fengchao
