### ISSUE TITLE
Inconsistency in Assigned Modifications column of combined_modified_peptide.tsv

### ISSUE THREAD

**Issue by turtlypo** [Nesvilab/FragPipe#529]
Hello FragPipe team!

I'm currently running FragPipe v17.0, and believe I'm noticing a Philosopher inconsistency in the combined_modified_peptide.tsv file generated.  The issue seems similar to [Issue #279](https://github.com/Nesvilab/FragPipe/issues/279), but what I'm experiencing is with a combined table.  

In the combined_modified_peptide.tsv, there is a Modified Sequence column and an Assigned Modifications column.  Sometimes the Modified Sequence will show variable mods not present in the Assigned Modifications, and sometimes the Assigned Modifications will show variable mods not present in the Modified Sequence.  

<img width="1728" alt="Screen Shot 2021-11-16 at 6 16 56 PM" src="https://user-images.githubusercontent.com/52044377/142081418-7c4310de-1ef0-4076-8444-cdfb72235704.png">

Both combined_ion.tsv and combined_modified_peptide.tsv seem to have this issue.  When I go into individual sample tables, the ion.tsv and psm.tsv tables do not have this inconsistency.

For the time being, I can just use the individual ion.tsv or psm.tsv tables for each sample and combine/collapse them myself.  I'm not sure if this is a known issue (or if I'm using the application wrong), but I thought it was worth a mention.  

If helpful, [here's a link](https://drive.google.com/drive/folders/1FQZYqD1d0_g_bPi9s10-R7icZ7MnWDHV?usp=sharing) to a Google Drive folder of my FragPipe output folder, which includes the combined tables.

[Linked here](https://github.com/Nesvilab/FragPipe/files/7550476/log_2021-11-12_14-26-01.txt) is my output log for easy access.

**Comment by fcyu** [comment]
Thanks for the bug report.

All combined_*.tsv file are generated by IonQuant if you enable it. Thus, it is a bug in IonQuant. I will look into it and get back to you ASAP.

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed the bug. We will release a new version soon. But if you want to have a try before the releasing, here is the link https://www.dropbox.com/s/ivkh58t7s7uy6cb/FragPipe-17.1-build7.zip?dl=0

FYI, this bug only affect the `assigned modification` column in `combined_ion.tsv` and `combined_modified_peptide.tsv` files.

Best,

Fengchao

**Comment by turtlypo** [comment]
Thank you so much! I really appreciate the fast response time. 😊
