### ISSUE TITLE
philosopher pipeline does not run through - only if steps started separately

### ISSUE THREAD

**Issue by fstein** [Nesvilab/FragPipe#530]
Hi,

I tried to set up the pipeline for running msfragger and philosopher. When I do this, I stops after the Protein Inference step. If I then modify the parameter.yml file and set only one step to yes to be executed, the analysis does finish if I execute it in the following order:
FDR Filtering:
Label-Free Quantification
Isobaric Quantification
Individual Reports
Integrated Reports

I have a TMT11 plex experiment (1 raw file which I converted to an mzML file with the following command: 'msconvert" *.raw --mzML --64 --zlib --filter "peak
[philosopher.yml.txt](https://github.com/Nesvilab/FragPipe/files/7552904/philosopher.yml.txt)
Picking true 1-"'

I attached my parameter file.
I also have another issue: When trying to print the philosopher.yml file using the "philosopher pipeline --print" command, it would print me a philosopher.yml file from version Version 3.6.0. The latest version is 4.0.1. If I use the Version 3.6.0, the pipeline complains alot about missing parameter.

Thanks for your help.

Cheers,

Frank

**Comment by fstein** [comment]
Sorry, just realized that it's probably the wrong location to ask. I will ask again at Nesvilab/Philosopher.

**Comment by sarah-haynes** [comment]
moved to https://github.com/Nesvilab/philosopher/issues/289
