### ISSUE TITLE
MSbooster not writing tsv file for percolator

### ISSUE THREAD

**Issue by BrendonSeale** [Nesvilab/FragPipe#533]
Hello,

I think this may be similar to the bug that prompt 17.1. When I run a file with msbooster enabled, the resulting tsv file is empty leading to percolator crashing. Using FragPipe 17.1build2, the file is correctly processed. I have attached the log file from the full release 17.1 version showing the error as well as a screenshot showing the empty PIN and tsv files.

![image](https://user-images.githubusercontent.com/75998063/142445894-ae4647ee-4c56-4872-9e2b-324392a06a09.png)
[log_2021-11-18_09-17-06.txt](https://github.com/Nesvilab/FragPipe/files/7563963/log_2021-11-18_09-17-06.txt)

**Comment by fcyu** [comment]
Hi Kevin,

```
Loading NO-75x50x2_120min_DDA_250ngK562_200nL_Slot1-5_1_2446_uncalibrated.mgf
java.lang.NullPointerException
	at Features.mzMLReader.setPinEntries(mzMLReader.java:251)
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:338)
	at Features.MainClass.main(MainClass.java:481)
```

The old issue is back?

Best,

Fengchao

**Comment by yangkl96** [comment]
Hi Brendon,

I think you may be using an older version of the MSBooster jar (sorry, I'll be updating version numbers from now on). The error line shown is just a comment line in the newest MSBooster version. Could you retry unzipping Fragpipe in a new folder to see if that works?

Thanks,
Kevin

**Comment by BrendonSeale** [comment]
Unzipped into new folder. Result is the same. FragPipe did mention it found some settings or something and I didn't load them but most of the fields were populated anyway. Here's the new log:

[log_2021-11-18_11-12-17.txt](https://github.com/Nesvilab/FragPipe/files/7564263/log_2021-11-18_11-12-17.txt)

**Comment by fcyu** [comment]
Hi Brendon,

It is weird. Can you zip and send the msbooster-1.0.jar from `fragger/tools` folder to us?

Thanks,

Fengchao

**Comment by BrendonSeale** [comment]
Here is is (from the freshly unzipped fragpipe directory):
[msbooster-1.0.jar.zip](https://github.com/Nesvilab/FragPipe/files/7564360/msbooster-1.0.jar.zip)

**Comment by yangkl96** [comment]
Hi Brendon,

Could you zip the pin (unedited) and mgf and send that to me? Thanks

**Comment by BrendonSeale** [comment]
Sure:

https://1drv.ms/u/s!AqAzfSxL_4mUgutAzFdH-Pethg8v9g?e=PPxjyo

Let me know if this works.

**Comment by yangkl96** [comment]
[msbooster-1.0.zip](https://github.com/Nesvilab/FragPipe/files/7566076/msbooster-1.0.zip)

Sorry for the issues, could you try replacing the msbooster.jar in tools/ with this new one?

**Comment by BrendonSeale** [comment]
Looks like this is working! Thanks!

**Comment by kabalak** [comment]
I have the same problem with the current FragPipe 17.1 and the updated msbooster.jar file from this thread; I also get the same error condition (though I have the semispecific N-term searches on the agenda):

`Process 'MSBooster' finished, exit code: 0
Percolator [Work dir: E:\RAW\Fatih\FragPipe_SemiSpecNt_ClosedFull\CTRL_1]
C:\MSPrograms\fragpipe-17.1\tools\percolator-v3-05.exe --only-psms --no-terminate --post-processing-tdc --num-threads 47 --results-psms 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_percolator_target_psms.tsv --decoy-results-psms 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_percolator_decoy_psms.tsv 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_edited.pin
Percolator version 3.05.0, Build Date May 18 2020 02:35:01
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
C:\MSPrograms\fragpipe-17.1\tools\percolator-v3-05.exe --only-psms --no-terminate --post-processing-tdc --num-threads 47 --results-psms 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_percolator_target_psms.tsv --decoy-results-psms 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_percolator_decoy_psms.tsv 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_edited.pin
Started Sat Nov 20 00:07:38 2021
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile 211013_FD_SLE_I_Simplex_HUNTER-Ctrl-Pool_edited.pin
Features:

ERROR: Reading tab file, too few features present.
No-terminate flag set: ignoring error and using a pseudo-feature of zeroes.
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid.

Process 'Percolator' finished, exit code: 1
Process returned non-zero exit code, stopping
`

If I switch off MSBooster, things seem to be working fine - is this the same bug still persisting or is it rather maybe a feature of non-specific searches not working together with MSBooster??

**Comment by yangkl96** [comment]
Hi Faith,

Could you attach the entire log file?

Thanks,
Kevin

**Comment by kabalak** [comment]
> 

Nevermind, I realized that the file was flawed from the beginning as it was not a good run; but I will attach the log file anyways. But I guess, that MSBooster seems to be optimized for specific searches?
[log_2021-11-19_13-08-45.txt](https://github.com/Nesvilab/FragPipe/files/7598881/log_2021-11-19_13-08-45.txt)

**Comment by yangkl96** [comment]
MSBooster itself doesn't mind if it is specific or not, it's more about how
well the prediction models can predict spectra and retention time for
semispecific peptides. Future versions will allow users to upload their own
predicted spectral libraries, but the default prediction model used by
MSBooster was only trained on tryptic peptides
