### ISSUE TITLE
FragPipe-17.1: selecting enzyme sets back Cleavage specificity setting

### ISSUE THREAD

**Issue by kabalak** [Nesvilab/FragPipe#534]
With FragPipe-17.1, if you select a different enzyme, the cleavage specificity (Specific, Semi_Nt) is always reverted to Specific.
In my case, if I first select Semi_Nt, then set ArgC specificity for my N-termini analysis, then the specificity is always set back to Specific, so I have to alter to Semi_Nt again. Normally, the cleavage specificity should not be altered by changing only the enzyme of choice. It is just annoying, but should be fixed.

**Comment by fcyu** [comment]
Thanks for your feedback. Fixed in 8f89acb0db4f5b99fc13f17976b3b7369eeca589

Best,

Fengchao
