### ISSUE TITLE
How to run PTMProphet for timstof data?

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#535]
- Describe the issue or question:
I am trying to include PTMProphet into the analysis of phospho dataset (timstof pro) but having trouble finding out how to do it. 

- PTMProphet apparently also needs the raw data file (in addition to pep.xml?) and it cannot accept them in bruker format, it needs mzML
- I converted the .d files to mzML according to https://fragpipe.nesvilab.org/docs/tutorial_convert.html - but then I got an error running fragpipe saying centroided data is required
- I had some issues with getting the required format in MSconvert starting with the .d folder, so ended up following comments here: https://github.com/Nesvilab/FragPipe/issues/339, and used mgf files from an earlier run of the same data to convert them to mzML. Unfortunately, I got an error in IonQuant - please see the attached log.-

Can you advise how best to include PTMProphet into a workflow using timstof data?

Thank you much for your help,
Janos

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-11-19_15-31-04_error.txt](https://github.com/Nesvilab/FragPipe/files/7573405/log_2021-11-19_15-31-04_error.txt)
)

**Comment by fcyu** [comment]
Hi Janos,

As you noticed, PTMProphet needs mzML. But we never tested the mzML converted from .d for PTMProphet. If it doesn't need to use MS1, it should work theoretically.

> I converted the .d files to mzML according to https://fragpipe.nesvilab.org/docs/tutorial_convert.html - but then I got an error running fragpipe saying centroided data is required

Did you following the second part of the tutorial ("Convert Bruker timsTOF .d files")? The first part is for Thermo data.

> I had some issues with getting the required format in MSconvert starting with the .d folder, so ended up following comments here: MSFragger exit code 1 #339, and used mgf files from an earlier run of the same data to convert them to mzML. Unfortunately, I got an error in IonQuant - please see the attached log.-

The uncalibrated.mgf only has MS2. Even after you convert it to mzML, it still cannot be used for MS1-based quantification. That is why IonQuant gave an error.

Best,

Fengchao

**Comment by jd690764** [comment]
Hi Fengchao,

Thank you for the quick response.

Yes, I did the conversion for Bruker files.

With respect to using MSconvert with .d folders, I used settings shown on
the attached screenshot. Does that look correct to you?

So a possible way to make an mzML from .d is xxx.d => mgf => mzML?

Thank you,
Janos

**Comment by fcyu** [comment]
Hi Janos,

The screenshot should work for the .d.

If you don't need MS1-based quantification, you can use the mgf file from MSFragger and uncheck IonQuant.

Best,

Fengchao

**Comment by jd690764** [comment]
Hi Fengchao,

I think I finally found out what the problem was with msconvert: it may
have been just the order of the filters - see attached screenshot. I
changed some of the filters also (the scanSumming values were suggested to
me by a person from Bruker who worked on finding the optimal ones), so I am
not completely sure. The resulting mzML did not break PTMprophet/ionQuant
subsequently.

Thank you for your help.
Janos

**Comment by fcyu** [comment]
Hi Janos,

Glad to hear that you figured it out. I didn't see the figure but can you confirm that the order of the filters in https://fragpipe.nesvilab.org/docs/tutorial_convert.html is correct?

Thanks,

Fengchao

**Comment by jd690764** [comment]
Hi Fengchao,

here is the screenshot.

Thanks again,
Jano
![msconvert2](https://user-images.githubusercontent.com/10483811/143140727-946e4bbd-355b-4057-a345-e3f3ac07a3e8.PNG)
s

**Comment by fcyu** [comment]
Thanks. BTW, if you have "count 150 most-intense" threshold, the mzML file cannot be used for MS1-based quantification because most of the MS1 peaks are removed.

Best,

Fengchao

**Comment by jd690764** [comment]
What should I use then?
Thanks,
Janos

**Comment by fcyu** [comment]
It depends on if you need to perform MS1-based quantification. If yes, need to remove the threshold filter.

Best,

Fengchao

**Comment by jd690764** [comment]
Great, thank you! 
Janos
