### ISSUE TITLE
MSstats

### ISSUE THREAD

**Issue by ohovey5** [Nesvilab/FragPipe#536]
Is Fragpipe compatible with MSstatsTMT and MSstatsTMTPTM? If so how would you set that up?

**Comment by fcyu** [comment]
We will support MSstatTMT in the future. As to MSstatsPTM, we need to discuss internally.

Best,

Fengchao

**Comment by anesvi** [comment]
I think we already support MSstats TMT. Although it has not been extensively tested. Check the box in validation tab to print msstats files

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KlemensFroehlich** [comment]
Fengchao recently commented on this:

https://github.com/Nesvilab/FragPipe/issues/510

Best Klemens
