### ISSUE TITLE
Problem with Ionquant

### ISSUE THREAD

**Issue by Peer2011** [Nesvilab/FragPipe#540]
Dear Fengchao, 

Any Idea why that happend? Happened the first. Reinstallation of FragPipe did not help. I performed a partial processing as peptide interference was already performed. 

Best, Peer 

2021-11-27 16:19:42 [INFO] - Writing index to C:\01_Data_Analysis\04_DLBCL_FRAGPIPE\INPUT\P051616-35-45-55-65-75_R1.quantindex
2021-11-27 16:19:42 [INFO] - Loading C:\01_Data_Analysis\04_DLBCL_FRAGPIPE\Output\9\P051616-35-45-55-65-75_R1.pepXML...
2021-11-27 16:19:43 [INFO] - Use each MS2 scan's calculated MZ in peak tracing.
2021-11-27 16:19:43 [INFO] - Quantifying...
2021-11-27 16:19:44 [INFO] - Updating Philosopher's tables...
java.lang.NullPointerException
	at s.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2021-11-27 16:19:45 [ERROR] - null
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Can you share the whole log?

Thanks,

Fengchao

**Comment by Peer2011** [comment]
Dear Fengchao, 

Please find attached the log File. As I pointed out it is only partial processing using IonQuant because I wanted to try a few settings. In the meantime I deleted all Output files and started with a new directory just to see whether this caused any issues. 

Best, Peer 

[log_2021-11-27_16-19-46.txt](https://github.com/Nesvilab/FragPipe/files/7613469/log_2021-11-27_16-19-46.txt)

**Comment by fcyu** [comment]
Hi Peer,

I guess there might be something incompatible between your previous analysis and your current analysis, since you were just running IonQuant this time. Please let me know if you still get the error when you start everything from scratch.

Best,

Fengchao

**Comment by Peer2011** [comment]
Dear Fengchao
I deleted all former files. When I reran the whole procedure everything worked fine. By the way are there any major changes to IonQuant 1.7.18 in comparison to 1.7.17?  

Best, Peer

**Comment by fcyu** [comment]
Hi Peer,

1.7.18 fixed a bug regarding the `lib` experiment. It is a pre-release version but you can use that if you want.

Best,

Fengchao
