### ISSUE TITLE
DDA data from timsTOF "seems from DIA but MS Fragger in DDA mode" then exits

### ISSUE THREAD

**Issue by TomClarkMassSpec** [Nesvilab/FragPipe#543]
Hello,

Newer version of Fragpipe v17.1 (MS Fragger 3.4, Win 10) seems to have introduced an issue. I have collaborator samples I need to reanalyze acquired on a timsTOF in QTOF mode aka DDA (SILAC). Files won't load from bruker folder directly but as in past, converted to mzML using proteowizard. Seemed to work in earlier versions.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-11-30_14-43-26.txt](https://github.com/Nesvilab/FragPipe/files/7629366/log_2021-11-30_14-43-26.txt)
)

Thank You,
Tom

**Comment by fcyu** [comment]
Your data's isolation window is larger than 4 Th. MSFragger though it was from DIA.

Best,

Fengchao

**Comment by TomClarkMassSpec** [comment]
Hi Fengchao,

I just saw that msg go out this morning to someone else. I'll check, but I am pretty sure my peak widths are close to isotopic isolation on that method. Perhaps it peaked above 4Da for some mass / charge state. I will check.

Best,
Tom

**Comment by fcyu** [comment]
Hi Tom,

Thanks for the info. I though 4 Th was a safe boundary for DDA vs DIA. It looks not. I will increase it to, say 5 Th, in the future release.

Best,

Fengchao

**Comment by TomClarkMassSpec** [comment]
You are correct Fengchao,

I include an optimized for intensity table of isolation mass widths.

I will roll back to earlier version to get through this task.

Thank You, T
[SILACTimsOFF6.csv](https://github.com/Nesvilab/FragPipe/files/7629492/SILACTimsOFF6.csv)
om
