### ISSUE TITLE
Close search- iTRAQ data

### ISSUE THREAD

**Issue by zyh4482** [Nesvilab/FragPipe#546]
Hi. 
Thanks for your wonderful tool. The tutorial is very clear and helps a lot for a beginner! 
I have a very basic question. I don't know how to achieve it. Assuming that a 4-plex iTRAQ data containing 114 for normal1, 115 for tumor1, 116 for normal2, 117 for tumor2 (the number refers to each patients), is it possible to know the predicted peptide comes from which sample after searching target-decoy database? 

First, I created a target-decoy database. Then I followed the tutorial of multiplex iTRAQ/TMT with a pooled reference, taking the 114 channel as reference and perform peptide search and quantification. Because the predicted peptide expression is relatively low, there is no hit in TMT-report. But I can get some predicted peptides from peptide.tsv. The last four columns contains a relative abundance of 114 to 117 reporter ion. How to determine whether the peptide is expressed in each samples? 

In some cases, all of the four columns are 0. Could you please suggest why it happens and is it a wrong call? 

Thank you so much

**Comment by sarah-haynes** [comment]
Hi, the 4 reporter ion abundance columns correspond to the amount of that peptide (or protein if you're looking at the protein-level report) detected in the sample. You are correct that there is [additional filtering applied](https://tmt-integrator.nesvilab.org/) to the reports in the 'tmt-report' folder, so fewer peptides are shown than in peptide.tsv. You can still use the abundances reported directly in the peptide.tsv. Sometimes a peptide is identified, but iTRAQ reporter ions cannot be quantified well, so all channels may have 0 intensity. Does that help answer your question?

It sounds like you may only have one 4-plex sample, if so, this tutorial is more appropriate: https://fragpipe.nesvilab.org/docs/tutorial_tmt.html

Sarah

**Comment by zyh4482** [comment]
Thank you Sarah! It helps a lot. 

May I ask another question? 
It would be strange if abundance columns represent the amount of the peptides in those four samples because the predicted peptide should not exist in a normal sample. I can clearly get a positive score of abundance in 114(Normal1) and 116(Normal2) channels. Not to mention that it seems impossible to distinguish which tumor sample have a predicted peptide expressed.  
For instance, how to interpret the result below?  
> Peptide N1 T1 N2 T2
> TPNSTGEEVPVQR  20000 27000 25000 16000

Would you mind giving some clues how to get this straight? Thanks.

**Comment by sarah-haynes** [comment]
You may want to double check the sample-iTRAQ channel annotations (especially if you are seeing trends inverse to what you expect), but we can't help much in interpreting the meaning of the results since you know the experiment best.

**Comment by zyh4482** [comment]
Thank you!
