### ISSUE TITLE
Experiment and Replicates setting

### ISSUE THREAD

**Issue by yxiao32** [Nesvilab/FragPipe#548]
Hi,

I have 16 samples which are divided into 4 groups, WT-control, WT-treatment, KO-control, and KO-treatment. Each group has 4 samples (bio-replicates) and each sample has 3 MS runs (triplicates). My question is what I should define in the Experiment and Replicates setting.

Thanks for your help in advance.

Cindy

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Please check our tutorial: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#select-workflow-and-add-spectral-files

Best,

Fengchao

**Comment by yxiao32** [comment]
Thank you, Fengchao. In the tutorial it has no suggestion on the input for the repeat runs for one sample. Should I treat them as different fractions from the same sample?

Thanks,
Cindy

**Comment by fcyu** [comment]
You can put technical replicates and fractions into the same experiment and bioreplicate group.

Best,

Fengchao

**Comment by yxiao32** [comment]
Okay, thanks, Fengchao.

Cindy
