### ISSUE TITLE
FAiled to execute dia-nn-plotter

### ISSUE THREAD

**Issue by DRock420** [Nesvilab/FragPipe#549]
HI There

AS a regular user of  DIA-NN I thought that I would give it a try in the newest realse of Fragpipe. The problem is that at the end of the analysis I get the error message "failed to execute script dia-nn-plotter" and it ends there without genration the reuslts (see below). I have tried running fragpipe with admin persimissions but this still had the sme error. I run DIA-NN on this computer without problems and so I am hoping that you have a solution

C:\Fragpipe\Fragpipe1_7_1\fragpipe\tools\diann\1.8\win\dia-nn-plotter.exe diann-output.stats.tsv diann-output.tsv diann-output.pdf
[9024] Failed to execute script dia-nn-plotter
Traceback (most recent call last):
  File "dia-nn-plotter.py", line 347, in <module>
  File "dia-nn-plotter.py", line 179, in report
  File "site-packages\pandas\core\indexes\base.py", line 1520, in droplevel
ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.
Generating report. Stats, main report, output file: diann-output.stats.tsv, diann-output.tsv, diann-output.pdf
Process 'DIA-NN' finished, exit code: -1
Process returned non-zero exit code, stopping

Thanks

Derek

**Comment by fcyu** [comment]
Can you send us the whole log file, please? You need to zip the file in case GitHub truncate the text file.

Thanks,

Fengchao

**Comment by DRock420** [comment]
HI Fengchao

Of course, please find attached

Derek

**Comment by fcyu** [comment]
I am sorry that I cannot find the attachment. Can you send it to yufe@umich.edu, please?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Derek,

Thanks for your log file. 

It looks like EasyPQP is not enabled so that there is no spectral library generated for DIA-NN. Please use the `DIA_SpecLib_Quant` workflow.  If you haven't installed  EasyPQP, please checkout our tutorial (https://fragpipe.nesvilab.org/docs/tutorial_setup_fragpipe.html).

I also attached the log file as a reference

[log_2021-12-02_10-53-46.txt](https://github.com/Nesvilab/FragPipe/files/7644576/log_2021-12-02_10-53-46.txt)

Best,

Fengchao

**Comment by DRock420** [comment]
Thanks Fenchao

So I need easypqp to run DIA-NN? I thought that I could use any spectral library as long as its in the right format.

Actually, that brings me to another question. I can’t get the software to recognize that I have easypqp installed in python. I have Fragpipe running on 3 different computers, all with recent versions of python and I can’t get Fragpipe to recognize that its installed, although it know that python is installed.

Any suggestions?


Thanks

Derek

**Comment by fcyu** [comment]
Hi Derek,

If you want to use existing spectral library for DIA-NN, there is no need to run MSFragger and other tools except for DIA-NN.

I see that you have `N:\databases\Uniprot human\human_hcd_labelfree_phospho_selected_passed.msp` for DIA-NN, but it looks like DIA-NN cannot read your library:
```
[0:00] Loading spectral library N:\databases\Uniprot human\human_hcd_labelfree_phospho_selected_passed.msp
WARNING: support for .sptxt/.msp spectral libraries is experimental; fragment ions must be annotated; 5 ppm mass accuracy filtering will be used; use --sptxt-acc <ppm> to change this setting
ERROR: amino acid mismatch at modification position 20 in AAAAAAAAAAGAAGGRGSGPGR/3_2(0,A,Acetyl)(17,S,Phospho)_26eV: expected G, got C, see "Comment: Single Pep=N-Semitryptic Mods=2(0,A,Acetyl)(17,S,Phospho) Fullname=M.AAAAAAAAAAGAAGGRGSGPGR.R Charge=3 Parent=611.2901 Mz_diff=-1.4ppm HCD=25.979772567749eV Scan=50232 Origfile="20120208_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_Nocodazole_rep2_FT1.raw.FT.hcd.ch.MGF" Sample="KusterSyn_MOD" Protein="sp|Q86U42|PABP2_HUMAN(pre=M,post=R)" Unassign_all=0.1561 Unassigned=0.0227 max_unassigned_ab=0.20 num_unassigned_peaks=1/20 FTResolution=17500 ms2IsolationWidth=1.60 ms1PrecursorAb=201081499.00 Precursor1MaxAb=191984705.53 PrecursorMonoisoMZ=611.2893 Filter="FTMS + p NSI d Full ms2 611.29@hcd25.00 [100.00-1890.00]""
[0:01] Assembling elution groups
[0:01] Spectral library loaded: 0 protein isoforms, 0 protein groups and 0 precursors in 1 elution groups.
[0:01] Initialising library
[0:01] Saving the library to N:\databases\Uniprot human\human_hcd_labelfree_phospho_selected_passed.msp.speclib
```

You can use our `DIA_SpecLib_Quant` workflow to build a spectral library using your DIA data, and do the quantification with the library and DIA-NN.

> Actually, that brings me to another question. I can’t get the software to recognize that I have easypqp installed in python. I have Fragpipe running on 3 different computers, all with recent versions of python and I can’t get Fragpipe to recognize that its installed, although it know that python is installed.

It looks like EasyPQP is not well installed. Can you open the command line window and run `pip install easypqp`?

Best,

Fengchao

**Comment by DRock420** [comment]
HI Fengchao

I don’t understand this. I swear that I have run pip install easypqp before and it did install it but Fragpipe could not detect it. However, this time, it did work so thank you!

Now, I am off to try to use Fragpipe to build some spectral libraries. Any advice for creating phospo- specific libraries?

Thanks

Derke

**Comment by fcyu** [comment]
You can load the `DIA_SpecLib_Quant` workflow, and load your DIA data and DDA data if you have them. Then, load your fasta file, and enable phosphorylation variable modifications in MSFragger tab. After specifying the result folder, you are good to click `Run` button.

MSFragger-DIA will first search the data with phosphorylation as variable modifications, and then build a spectral library containing phosphorylation.

Best,

Fengchao

**Comment by anesvi** [comment]
You can also enable PTM-prophet
But the localization probability will not propagate from PSM.tsv to library.tsv. For now we have to parse that info from PSM.tsv if we want to keep only localized sites in the library.
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DRock420** [comment]
Thanks Alexey!

I will give it a shot


Derek

**Comment by DRock420** [comment]
I should also say that I am really impressed. Right now, I am using Fragpipe to make a phospho-DIA library out both DDA and GPF DIA data. Normally I only use  GPF-DIA to make my libraries. Pretty cool!

Thanks

Derek

**Comment by DRock420** [comment]
Thanks again Fengchao

I have made a library successfully and now want to test some files against it. Is there a workflow that I can start from for this or do I just start from the default? Specifically, I am wondering what validation settings would be normally used in DIA and specifically PTM based DIA

Thanks

Derek

**Comment by fcyu** [comment]
Hi Derek,

The `DIA_SpecLib_Quant` workflow is the one you can use (I think you are already using it). It uses MSFragger-DIA to search the data, generates a spectral library, and performs the quantification. Alternatively, you can use `DIA_DIA-Umpire_SpecLib_Quant` workflow, which does a similar job but uses DIA-Umpire to generate pseudo-MS/MS, and then uses MSFragger to search it.

>  I am wondering what validation settings would be normally used in DIA and specifically PTM based DIA

If the validation means FDR filtering, the spectral library is filtered with 1% global peptide and protein FDR. The quantified precursors are filtered with 1% precursor FDR by default. If you want to have the PTM localization score, you can add `--monitor-mod UniMod:21` (for phosphorylation) to the `Cmd line opts` option in `Quant (DIA)` tab:

![image](https://user-images.githubusercontent.com/6926299/144672114-2984fd42-e6ca-433d-bf8e-1c9cadd31f19.png)

Best,

Fengchao

**Comment by fcyu** [comment]
Oh, if you want to test some other DIA files with an existing library, you can load your DIA files, disable all steps except for the `Quant (DIA)`, and load your library.tsv in that tab.

Best,

Fengchao

**Comment by DRock420** [comment]
Thanks Fenchao!

Derek

**Comment by DRock420** [comment]
Sorry Fengchao but I have more problems.

Trying to search 3 DIA samples using the library that I created earlier. It looks like a percolator error but on file #3. Each sample file is a replicate injection and should be nearly identical.

Any ideas?

Thanks

Derek

**Comment by fcyu** [comment]
Hi Derek,

The log file was truncated by GitHub. Can you send it to yufe@umich.edu?

Regarding the analysis, I think I need to clarify something.

If you have DIA runs (plus DDA and/or GPF-DIA runs) but no spectral library, you can use the `DIA_SpecLib_Quant` workflow to search the data, build a spectral library, and perform DIA quantification using the spectral library.

If you have a library that you want to use, and don't want to build a new library, you need to load the DIA runs, specify them as `DIA` data type, **uncheck** all steps except for the `Quant (DIA)`, set your spectral library in the `spectral library (optional)` box. It basically means that you don't need to run MSFragger and build another spectral library if you already have one.

Best,

Fengchao

**Comment by fcyu** [comment]
Contacted by email.
