### ISSUE TITLE
Failed to create spectral library from fractioned dataset

### ISSUE THREAD

**Issue by stharan** [Nesvilab/FragPipe#556]
- Describe the issue or question:
Spectral library creation with easypqp fails at RT alignment step.  I have tried using Percolator and Peptide Prophet input files and iRT and ciRT for the alignment options.

This is a fractioned dataset consisting of 15 pooled groups.

Thanks in advance for you help.

- Upload your log file
[Human_Trypsin_Semi.zip](https://github.com/Nesvilab/FragPipe/files/7668380/Human_Trypsin_Semi.zip)

**Comment by fcyu** [comment]
Hi Guo Ci @guoci ,

The error was from EasyPQP. Can you take a look?
```
\\TS5410D1EE\Share\Jon_Krieger\Golden_Dataset_SK_Fractionation\MSFragger_output\Human_Trypsin_Semi\Human_Trypsin_Semi\peptide.tsv
                                            base_name  modified_peptide
0   Human_Trypsin_SK_Fractionation_Concatenation_G...             45856
1   Human_Trypsin_SK_Fractionation_Concatenation_G...             34480
2   Human_Trypsin_SK_Fractionation_Concatenation_G...             45374
3   Human_Trypsin_SK_Fractionation_Concatenation_G...             47441
4   Human_Trypsin_SK_Fractionation_Concatenation_G...             47020
5   Human_Trypsin_SK_Fractionation_Concatenation_G...             47075
6   Human_Trypsin_SK_Fractionation_Concatenation_G...             38557
7   Human_Trypsin_SK_Fractionation_Concatenation_G...             44583
8   Human_Trypsin_SK_Fractionation_Concatenation_G...             40920
9   Human_Trypsin_SK_Fractionation_Concatenation_G...             43977
10  Human_Trypsin_SK_Fractionation_Concatenation_G...             47264
11  Human_Trypsin_SK_Fractionation_Concatenation_G...             50240
12  Human_Trypsin_SK_Fractionation_Concatenation_G...             53120
13  Human_Trypsin_SK_Fractionation_Concatenation_G...             50165
14  Human_Trypsin_SK_Fractionation_Concatenation_G...             48882
Info: easypqp_rt_alignment_Human_Trypsin_SK_Fractionation_Concatenation_Group_10_3uL_H5_1_1041; Peptide overlap between run and reference: 7708.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 555, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 609, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 81
```

Thanks,

Fengchao

**Comment by guoci** [comment]
Can you set `RT lowess fraction` to a non-zero value e.g. `0.05` and try again?
![image](https://user-images.githubusercontent.com/1260178/129079122-1de894ca-6df3-412c-a22d-8ee7cc2ff99f.png)

**Comment by stharan** [comment]
Thank you, that worked.  Is there a recommended value for fractioned data vs samples that are more technical replicates?

**Comment by fcyu** [comment]
For the fractionated data, `automatic selection of a run as reference RT` might not work if there are too few overlapped peptides. For this case, you can choose `ciRT` if your data is from human sample, user's iRT file, or put an unfractionated run to be used as a reference.

You don't need to worry about the `RT lowess fraction` too much because the program will adjust it according to the data automatically.

Best,

Fengchao

**Comment by guoci** [comment]
Currently setting `RT lowess fraction` to `0` will trigger the bug, I have pushed a fix to `EasyPQP` and it should be available in a few days.
For now, you can leave it at `0.05` and look at the RT alignment plots generated, if there is an underfit decrease it.
