### ISSUE TITLE
EasyPQP spectral library threading issue

### ISSUE THREAD

**Issue by emhumphries** [Nesvilab/FragPipe#558]
I'm looking at phospho in SWATH data using the DIA_SpecLib_Quant workflow in Fragpipe v17.1 GUI. I used MSconvert to generate MZML files from Wiffs and from the logs it looks like I run into threading issues when building the spectral library. I have checked that I have the right MS data type selected and the latest version of EasyPQP0.1.25. 

I've tried using python3.8.3 [log_2021-12-09_08-13-08.txt](https://github.com/Nesvilab/MSFragger/files/7682117/log_2021-12-09_08-13-08.txt) as well as python3.9.7 [log_2021-12-09_11-45-52.txt](https://github.com/Nesvilab/MSFragger/files/7682122/log_2021-12-09_11-45-52.txt) 

Do you have any advice on what I should try next? Thanks for your help

**Comment by fcyu** [comment]
Hi Guo Ci @guoci ,

Can you take a look? The errors were from EasyPQP:
```
C:\Users\ehumphries\Desktop\DIAspeclibv17-1-easypqpinstallattempt2\peptide.tsv
                              base_name  modified_peptide
0  200612_B1-1-T1-1_00VCS_00Y1S_M05_S_1              8506
1  200612_B1-2-T1-1_00VCU_00Y1T_M05_S_1              9358
Info: easypqp_rt_alignment_200612_B1-1-T1-1_00VCS_00Y1S_M05_S_1; Peptide overlap between run and reference: 5738.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 555, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "c:\programdata\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 609, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\programdata\anaconda3\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 65
```

Thanks,

Fengchao

**Comment by guoci** [comment]
same issue as #556, waiting for my fix to be pushed.
For now you can try the following, on Anaconda Prompt type:
```
pip uninstall --yes easypqp
pip install git+https://github.com/guoci/easypqp.git@workaround_loky_issue
```
