### ISSUE TITLE
Easy PQP fails

### ISSUE THREAD

**Issue by KathrinVV** [Nesvilab/FragPipe#563]
Hi,
I want to create a spectral library from DDA .d files and fragPipe v16. I have used my workflow successfully before but this time it fails at the last step. PSM, peptide and protein results were generated but the library wasn't.
(pandas and numpy are up to date)

Here's the log: 

[Error_EasyPQP.txt](https://github.com/Nesvilab/FragPipe/files/7729998/Error_EasyPQP.txt)

Thanks for any help!

**Comment by guoci** [comment]
@KathrinVV can you post the file `G:\Kathrin\MSFragger_Results\TEKO_allSamples_Library\interact-20211201_KW_APOE4_cohort2_Lys_DDA_A2_Slot1-23_1_6235.pep.xml`?

**Comment by KathrinVV** [comment]
I shared the file via google drive with you. I used the email of your github account for that. Let me know if it worked.

**Comment by guoci** [comment]
In the `.pep.xml` file, you have a protein `sp|1N4R`. That is causing the error.
Can you post the fasta too?

**Comment by KathrinVV** [comment]
I shared the. fasta with you

**Comment by KathrinVV** [comment]
Sorry I shared the wrong .fasta

06102019_uni_mouse_rev_can_iso_NOmouseTAU_human1N4Ronly_for PS19 is the correct one. I shared it with you as well

**Comment by guoci** [comment]
The header is invalid, after the 1st and before the 2nd `|` there should be no spaces.
`>sp|1N4R (P301S)| (P10636-7_412aa) TAU_HUMAN Isoform Tau-E of Microtubule-associated protein tau OS=Homo sapiens OX=9606 GN=MAPT`

**Comment by KathrinVV** [comment]
I renamed it to:
>sp|1N4R(P301S)|(P10636-7_412aa)TAU_HUMAN Isoform Tau-E of Microtubule-associated protein tau OS=Homo sapiens OX=9606 GN=MAPT

and restarted the search. I'll let you know if it went through.

**Comment by KathrinVV** [comment]
The search ran through. Thank you for your help :)
