### ISSUE TITLE
Issue with PeptideProphet error code:1

### ISSUE THREAD

**Issue by flore37** [Nesvilab/FragPipe#564]
Hi All,
I'm running 6 files in Fragpipe v16.0 with philosopher v4.0.0, 
I convert them in mzML in centroid, peak peaking as suggest and I get this  error 

WARNING: no data - output file will be empty
FATA[12:02:57] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

I checked I have some information on my data but it appear they can not be found.
I change the place of my data and reprocess, same issue.

Does anyone have any idea what might be going on?
Thanks for any help!




[log_2021-12-20_13-11-15.txt](https://github.com/Nesvilab/FragPipe/files/7747458/log_2021-12-20_13-11-15.txt)

**Comment by fcyu** [comment]
Same reason as https://github.com/Nesvilab/FragPipe/issues/539 . Can you tell us why did you change ` --minprob` to 0.9 for ProteinProphet? If there is no good reason, you should not change the parameters.

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi @flore37,
Also it looks like something might be going wrong with your fasta file, since the program is looking for the tag "rev_rev_" to indicate a decoy instead of the usual "rev_". This means it found no decoys and couldn't perform the FDR calculation. Can you try loading (or downloading) your fasta again and making sure the message on the database tab after loading your fasta says that it detected 50% decoy sequences instead of 0%? 

Best,
Dan

**Comment by fcyu** [comment]
Also, something else is wrong with your search parameter:
```
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |   1.67   1.29 |  -0.01   0.84 |   0.33   1.27 |   0.09   1.24  
 002 |   1.70   1.30 |  -0.05   0.79 |   0.28   1.34 |   0.04   1.32  
 003 |   2.27   1.40 |   0.03   0.84 |   0.70   1.18 |  -0.02   1.12  
 004 |   2.18   1.45 |   0.04   0.95 |   0.67   1.15 |   0.02   1.06  
 005 |   1.92   1.20 |   0.07   0.88 |   0.46   1.14 |   0.04   1.10  
 006 |   1.77   1.29 |  -0.10   0.85 |   0.50   1.22 |   0.05   1.16  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      0|      0|      0|      0|      0|      0
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      0|      0|      0|      0
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |      0
-------|-------
-------|-------
 Rm P. |    1  
-------|-------
 Count |      0
-------|-------
```

I see that your mzml files have the name like `D:\Flore\testfragpipie\Depleted_Serum_pool_F4_SCX.mzML`, if you are searching DIA data, please label your data with the correct datatype.


And as Dan pointed, our, you "double appended" decoys: `2021-12-17-decoys-2021-12-17-decoys-contam-2021-12-17-decoys-COVIDuniprot-proteome_UP000005640+reviewed_yes.fasta.fas.fas.fas`.

Best,

Fengchao

**Comment by flore37** [comment]
> e ` --minprob` to 0.9

Thanks for your reply.
I want to use my  scx fractionation analyzed in DDA  to create my DIA library.
I load again my fasta file and just add once the decoy, so it should have no other issue on this side
about the parameter, I had no idea that I changed this parameter. Should it be 0.05? 
I run again the software this time with the  good fasta file with  or without the PSM validation  and with different value for minprob (0.05, 0.2, 0.5, 0.9) .
It works each time, so definitely it comes from the fasta file .
But about the parameter, I checked after protein list  and the library , they are just  a difference of 1 id of protein  and the more difference on the precursor on the library> Much more abundant with 0.05 than 0.9 which was expected.

Thanks for your help,
Regards,
Flore

**Comment by fcyu** [comment]
`--minprob` controls the PSMs being used in protein inference before FDR filtering. Theoretically, the FDR-filtered results should have no big difference with 0.05 and 0.9. But 0.9 is a little bit too stringent in case there are not many PSMs with probability > 0.9, so we set 0.7 in some workflows.

Best,

Fengchao
