### ISSUE TITLE
0.00% FDR and 0 PSMs in Philosopher

### ISSUE THREAD

**Issue by SimionKreimer** [Nesvilab/FragPipe#566]
- Describe the issue or question:
I'm trying to create a GPF DIA library using 1 m/z isolation windows but for each attempt something weird happens in Philosopher where the IDs converge to 0.0% FDR and after this the pipeline fails at various stages without creating the library. I didn't have this issue with earlier versions of FragPipe.

- Upload your log file
(If a log file hasn't been generated, go to
[log_2021-12-20_11-53-57.txt](https://github.com/Nesvilab/FragPipe/files/7747663/log_2021-12-20_11-53-57.txt)
 the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It seems that you were using PeptideProphet... 

Can you load the `DIA_SpecLib_Quant` workflow, adjust the data type, fasta files, enzyme, variable modification, and try again?

Best,

Fengchao

**Comment by fcyu** [comment]
Also, if your data is from staggered DIA, you need to demultiplexed it using msconverter:

![image](https://user-images.githubusercontent.com/6926299/146825736-bdab093f-1dbe-4eb8-a52b-dba78de0b05b.png)

Hi Sarah @sarah-haynes , can you add the conversion of staggered DIA to the tutorial? Thanks.

Best,

Fengchao

**Comment by SimionKreimer** [comment]
Oh it was from staggard DIA, thank you for the hint!
