### ISSUE TITLE
Label-free quantification with FragPipe

### ISSUE THREAD

**Issue by Irkcy** [Nesvilab/FragPipe#568]
Hi Fragpipe,

I loaded the "LFQ-MBR" workflow. Then I added 48 .d DDA files. Alao I annotated them by editing the ‘Experiment’. On the ‘Database’ tab, I used Philosopher to add the contaminants and decoys to my FASTA file. On the ‘MSFragger’ tab, I setted "Fragment mass to tolerance" to "0.05Da",  and ‘Calibration and Optimization’ to ‘None’ in the ‘Peak Matching’ section. Other parameters was followed as the default of Fragpipe. The following error occured: ERROR: java.util.concurrent.ExecutionException: java.io.IOException. 

Best,
Irkcy

![1](https://user-images.githubusercontent.com/95337087/147429284-083f33f1-bed0-47b4-9a01-a9aaa8bf9f5c.jpg)
![2](https://user-images.githubusercontent.com/95337087/147429293-7ade431f-b2dc-4c33-a625-7fb44d8cf64b.jpg)
![3](https://user-images.githubusercontent.com/95337087/147429296-030bf0e4-ea37-4924-8075-2abce9296d85.jpg)
![4](https://user-images.githubusercontent.com/95337087/147429303-b2e2acfa-27a6-4cd4-9309-d8addb0074e9.jpg)
![5](https://user-images.githubusercontent.com/95337087/147429310-197fc0c3-a82c-4eea-83b1-ad68411fff49.jpg)
![6](https://user-images.githubusercontent.com/95337087/147429316-36a94d17-36ba-4c83-8eb2-7c33016e424f.jpg)
![7](https://user-images.githubusercontent.com/95337087/147429318-1665f0cb-b479-4ee4-828d-0326d9c5123d.jpg)
[log_2021-12-26_06-33-52.txt](https://github.com/Nesvilab/FragPipe/files/7778103/log_2021-12-26_06-33-52.txt)

**Comment by fcyu** [comment]
Hi Irkcy,

It looks like something was wrong in reading the files. 

Could you please tell me what those `?` are from your computer:
![image](https://user-images.githubusercontent.com/6926299/147429705-2e89b0d1-1119-48cf-8806-de7b9ce5580d.png)

I guess they are not English so my computer cannot display them.

Best,

Fengchao

**Comment by Irkcy** [comment]
> Hi Irkcy,
> 
> It looks like something was wrong in reading the files.
> 
> Could you please tell me what those `?` are from your computer: ![image](https://user-images.githubusercontent.com/6926299/147429705-2e89b0d1-1119-48cf-8806-de7b9ce5580d.png)
> 
> I guess they are not English so my computer cannot display them.
> 
> Best,
> 
> Fengchao

Hi @fcyu ,

Those "?" are nothing in my computer.
![1640574681(1)](https://user-images.githubusercontent.com/95337087/147430531-d14dfa4c-86f6-42f1-ae50-90c872398292.jpg)

Best,
Irkcy

**Comment by fcyu** [comment]
Hi Irkcy,

Thanks for your prompt reply. I guess it is due to some errors in reading the `psm.tsv`. Can you re-run IonQuant? You can uncheck all tools except for IonQuant to save some time.

Best,

Fengchao

**Comment by Irkcy** [comment]
> Hi Irkcy,
> 
> Thanks for your prompt reply. I guess it is due to some errors in reading the `psm.tsv`. Can you re-run IonQuant? You can uncheck all tools except for IonQuant to save some time.
> 
> Best,
> 
> Fengchao

Hi @fcyu 

Thanks for your prompt reply.  I will re-run  IonQuant as you suggest.

With kind regards,
Irkcy

**Comment by fcyu** [comment]
BTW, you can also check if there are other programs, such as antivirus, Dropbox, OneDrive, Google Drive, etc, locking or blocking the files when IonQuant is running.

Best,

Fengchao

**Comment by Irkcy** [comment]
> BTW, you can also check if there are other programs, such as antivirus, Dropbox, OneDrive, Google Drive, etc, locking or blocking the files when IonQuant is running.
> 
> Best,
> 
> Fengchao

@fcyu ，thanks for pointing it out. It's a pity that there were no other programs when IonQuant was running. I tried as you suggested and it didn't work. It seems to be the same error as yesterday.

![1640684152(1)](https://user-images.githubusercontent.com/95337087/147552239-517cd401-cfb0-437f-b070-3aa69316a7eb.jpg)
[log_2021-12-28_16-31-39.txt](https://github.com/Nesvilab/FragPipe/files/7783976/log_2021-12-28_16-31-39.txt)

Best,

Irkcy

**Comment by fcyu** [comment]
Hi Irkcy,

This time, the `IOException` error was thrown from a different place:
```
2021-12-28 16:27:08 [INFO] - Writing index to Z:\lidan\WOSP00101\DDA\CAD20211212chenc_WOSP00101_DDA_60min_K562_rep1_3_Slot1-13_1_3169.quantindex
```
vs the last time:
```
2021-12-26 05:52:26 [INFO] - Calculating correlations between all other runs...
```

One is from writing the file, and the other is from reading the file. It looks like something was wrong with your file system. I am afraid you have to troubleshoot by yourself because I don't think I can reproduce it.

BTW, it looks like there is a message after `java.io.IOException` this time, but it is not displayed correctly.

![image](https://user-images.githubusercontent.com/6926299/147573781-4dab862d-82b5-49e9-8e27-d0dd4b976758.png)

Best,

Fengchao

**Comment by guoci** [comment]
@Irkcy you can try to `Change system locale` to `English (United States)` before running FragPipe to get the error message to display properly. https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html
If you have resolved this issue already, please let us know how you resolved it.

**Comment by Irkcy** [comment]
Hi, Fragpipe
&nbsp; Sorry for late reply. Thanks for your prompt reply. I will try as you suggest.&nbsp;
&nbsp; I have resolved the issue. The DDA files was generated from two mass spectrometers. Firstly, I moved this files from the server to a local disk. Then I splited the files from two mass spectrometers into separate folders. Then I run Fragpipe separately. Finally, it worked successfully.


Best,
Irkcy&nbsp;&nbsp;

---Original---
From: ***@***.***&gt;
Date: Thu, Dec 30, 2021 03:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Nesvilab/FragPipe] Label-free quantification with FragPipe(Issue #568)




 
@Irkcy you can try to Change system locale to English (United States) before running FragPipe to get the error message to display properly. https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html
 If you have resolved this issue already, please let us know how you resolved it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
