### ISSUE TITLE
Two scan modes. Library generation. 

### ISSUE THREAD

**Issue by bsarvin** [Nesvilab/FragPipe#572]
For library generation, I am working with a long DDA Method, and the method starts with a short scanning segment for autocalibration. 

When I am trying to generate a library, it returns me an error that “there are at least two scan modes” and terminates the entire process.

Is it any simple solution to specify which scan mode to use for library generation? 

```
Process 'MSFragger' finished, exit code: 1
There are at lease two scan modes: 0 and 8 in D:\Data\TS_LAB\2021_12_Dec\Boris\20211229_Lib_Gen\Promega_95C_Lib_Gen_125ramp_20cycles.d
Process returned non-zero exit code, stoppin
```

**Comment by fcyu** [comment]
It looks like your data has both PASEF and normal MS (non-PASEF) scans. Can you check your acquisition settings? If there is no problem in your settings, can you send the .d folder to us?

Thanks,

Fengchao

**Comment by bsarvin** [comment]
Dear Fengchao,

Yes, indeed, my method contains two parts: 10s scan mode for autocalibration followed by PASEF-DDA. 

Yes, it is clear why do I have this error. The question is: can I work with this type of method, or do I need only to work with solely DDA acquisition?

Boris

**Comment by fcyu** [comment]
HI Boris,

Yes, I think we can make MSFragger work for this type of data. Before I modify MSFragger, could you please tell me which type of scans do you want to analyze? PASEF, or non-PASEF, or both?

And, could you also send one of such data to us to test if it is appropriate?

Best,

Fengchao

**Comment by bsarvin** [comment]
PASEF segment only,

I will prepare the file and send it tomorrow,

Thank you,
Boris

**Comment by bsarvin** [comment]
> HI Boris,
> 
> Yes, I think we can make MSFragger work for this type of data. Before I modify MSFragger, could you please tell me which type of scans do you want to analyze? PASEF, or non-PASEF, or both?
> 
> And, could you also send one of such data to us to test if it is appropriate?
> 
> Best,
> 
> Fengchao

.d file is available via the following link:

https://www.dropbox.com/sh/or42thds0rp0ibw/AAANBCmOj10O2l3EhsDfteIGa?dl=0

Thank you,
Boris

**Comment by fcyu** [comment]
Hi Boris,

Thank you very much for your file. Here (https://www.dropbox.com/s/1uiceyscb5fuqwz/MSFragger-3.5-rc7.zip?dl=1) is the link to the pre-release of MSFragger. Can you try to see if it works for you?

Thanks,

Fengchao

**Comment by bsarvin** [comment]
> Hi Boris,
> 
> Thank you very much for your file. Here (https://www.dropbox.com/s/1uiceyscb5fuqwz/MSFragger-3.5-rc7.zip?dl=1) is the link to the pre-release of MSFragger. Can you try to see if it works for you?
> 
> Thanks,
> 
> Fengchao

Thank you a lot,

I will check it out tomorrow and let you know. 

Boris

**Comment by bsarvin** [comment]
> Hi Boris,
> 
> Thank you very much for your file. Here (https://www.dropbox.com/s/1uiceyscb5fuqwz/MSFragger-3.5-rc7.zip?dl=1) is the link to the pre-release of MSFragger. Can you try to see if it works for you?
> 
> Thanks,
> 
> Fengchao

Dear Fengchao,

MSFrager works correctly now, and I can see a number of proteins, etc.

Previously I have worked with IonQuant. 

![image](https://user-images.githubusercontent.com/96970708/148032710-02bae7a1-aea0-41a0-b03a-8f032bc65055.png)

But now it gives me the similar error that my file contains to scan modes. I suppose it can be fixed similarly to MSFragger. 

Can you please check it out?

P.S. when I remove the flag "Run MS1 quant" the entire process works OK.


Boris

**Comment by fcyu** [comment]
Hi Boris,

Right, I also need to change IonQuant. Could you try the pre-release from (https://www.dropbox.com/s/c4cyof5jlfwxm5o/FragPipe-17.2-build9.zip?dl=0) to see if it works for your data?

Best,

Fengchao

**Comment by bsarvin** [comment]
> Hi Boris,
> 
> Right, I also need to change IonQuant. Could you try the pre-release from (https://www.dropbox.com/s/pyzroyb49t0tkqu/FragPipe-17.2-build9.zip?dl=1) to see if it works for your data?
> 
> Best,
> 
> Fengchao

Dear Fengchao,

I have tried a new version of fragpipe but it returns me the following error:

CheckCentroid
java -Xmx30G -cp "D:\Methods\Boris\Applications\fragpipe\lib\fragpipe-17.2-build9.jar;D:\Methods\Boris\Applications\fragpipe\tools\batmass-io-1.24.1.pom" com.dmtavt.fragpipe.util.CheckCentroid D:\Data\TS_LAB\2021_12_Dec\Boris\20211229_Lib_Gen\Promega_RT_Lib_Gen_400uL.d 15
Error: Unable to initialize main class com.dmtavt.fragpipe.util.CheckCentroid
Caused by: java.lang.NoClassDefFoundError: umich/ms/fileio/filetypes/AbstractLCMSDataSource
Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping


I checked with the previous version and it work ok.

The Java version was updated as it was requested by the app:

![image](https://user-images.githubusercontent.com/96970708/148191603-992b8ef5-9c69-45de-bf8a-3192c79d53dc.png)


Best,
Boris

**Comment by bsarvin** [comment]
> Hi Boris,
> 
> I apologize that I introduced a new bug when I was upgrading one of the libraries. Could you try this one (https://www.dropbox.com/s/t2a0q3gl2i89dpw/FragPipe-17.2-build10.zip?dl=1)?
> 
> Thanks,
> 
> Fengchao

Dear Fengchao,

Now it works,

Thank you!

**Comment by fcyu** [comment]
No problem!

Best,

Fengchao
