### ISSUE TITLE
Philosopher abacus out of memory

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#573]
Hi 

  I'm totally new to fragpipe and I'm trying to run it on my desktop and having memory related problems during my runs. My computer is not the best but I wanted to make sure I'm not doing something silly with setting up the parameters before I go to the direction of upgrading the hardware.

  Anyway, I'm trying to analyze DDA data (12 files, converted to mzXML using the standard parameters in MSconvert), combined with LFQ quantification. I'm getting the following error during the run (regradless of whether I allocated 4 GB or 8 GB to the run):

PhilosopherReport [Work dir: C:\Protemics_analysis\20-02-28_RG66\Results\DMSO_4]
C:\fragpipe\tools\philosopher\philosopher.exe report
INFO[00:26:02] Executing Report  v4.1.1                     
INFO[00:26:19] Creating reports                             
INFO[00:26:22] Done                                         
Process 'PhilosopherReport' finished, exit code: 0
PhilosopherAbacus [Work dir: C:\Protemics_analysis\20-02-28_RG66\Results]
C:\fragpipe\tools\philosopher\philosopher.exe abacus --razor --reprint --tag rev_ --protein 100_1 100_2 100_3 100_4 50_1 50_2 50_3 50_4 DMSO_1 DMSO_2 DMSO_3 DMSO_4
INFO[00:26:24] Executing Abacus v4.1.1                      
INFO[00:26:24] Processing combined file                     
INFO[00:26:37] Converged to 1.02 % FDR with 5896 Proteins    decoy=60 threshold=0.996 total=5956
INFO[00:26:47] Restoring protein results                    
Process 'PhilosopherAbacus' finished, exit code: 2
runtime: VirtualAlloc of 169877504 bytes failed with errno=1455
fatal error: out of memory

The computer has 8GB ram (7.88 GB usable), and 0.5 TB hard drive. 

  Thanks for any help and let me know if any more information is needed.

**Comment by fcyu** [comment]
Hi @RonenGabizon ,

This is an known issue (https://github.com/Nesvilab/FragPipe/issues/489). Philosopher abacus require lots of memory when there are many files. If you are using the last version of our tools and load the `LFQ-MBR` workflow, this issue should not be triggered. Can you try again? If the issue is still there, can you send us your log file?

BTW, it's better to use convert your raw files to mzML format, which contains more information, according to the tutorial here (https://fragpipe.nesvilab.org/docs/tutorial_convert.html).

Best,

Fengchao

**Comment by RonenGabizon** [comment]
Thanks !

  I indeed used the LFQ-MBR workflow, and converted the files to mzXML before running. I'm fairly sure the versions I use are up to date because I just downloaded them, the version of MSconvert I'm using might be a bit older. I tried running again but haven't really changed anything so I'm not sure what will come out of that. Anyway here are the log files from my first two attempts.
[log_2022-01-04_17-43-51.txt](https://github.com/Nesvilab/FragPipe/files/7816993/log_2022-01-04_17-43-51.txt)
[log_2022-01-05_01-42-08.txt](https://github.com/Nesvilab/FragPipe/files/7816994/log_2022-01-05_01-42-08.txt)

**Comment by fcyu** [comment]
I am 100% sure that you are not using the `LFQ-MBR` workflow. Following is the diff of the `LFQ-MBR` workflow (you can find it in your `fragpipe/workflow` folder or https://github.com/Nesvilab/FragPipe/blob/master/MSFragger-GUI/workflows/LFQ-MBR.workflow), and the settings from your log (the left is from the LFQ-MBR workflow and the right is from your log):

![image](https://user-images.githubusercontent.com/6926299/148270807-f66c7e40-95b6-48e1-9361-537e8b18b46b.png)

The above difference crashed your task.

There are also some other differences.

![image](https://user-images.githubusercontent.com/6926299/148270719-8eff67cc-3491-4425-b43e-667f702918b2.png)
![image](https://user-images.githubusercontent.com/6926299/148270742-9d52147f-8f93-40e5-9d24-aec1af7cd0cf.png)
![image](https://user-images.githubusercontent.com/6926299/148270828-b907b45d-930f-4bad-9428-dc09469167e2.png)


Please load (remember to click **Load workflow**) the `LFQ-MBR` workflow and try again.

Best,

Fengchao

**Comment by RonenGabizon** [comment]
Thanks I must have screwed up something after I loaded it, but I'll give it another shot now.

**Comment by RonenGabizon** [comment]
Hi, I managed to run it successfully without problems this time. Thanks!

**Comment by fcyu** [comment]
No problem!

Best,

Fengchao
