### ISSUE TITLE
LFQ normalization

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#575]
Hi

  I'm using LFQ-MBR to analyze data from multiple experiments, each one with its own set of replicates. While I would like all the files to be searched together, for the LFQ step I would prefer that each set of replicates would be normalized only within itself, not with all the other run. Is there a way to do this?

Thanks

**Comment by fcyu** [comment]
No for now. We will add this functionality in the future.

Best,

Fengchao
