### ISSUE TITLE
columns with "MaxLFQ Intensity" suffix.

### ISSUE THREAD

**Issue by wolski** [Nesvilab/FragPipe#578]
I am running Ionquant (onQuant-1.7.17.jar) with:
`-mbr 1 --ionmobility 0 --maxlfq 1 --normalization 0`

The 'combined_protein.tsv' file contains intensity columns with e.g. "MaxLFQ Unique Intensity"  but also columns with  " Unique Intensity" suffix. 

The [tutorial_fragpipe_outputs documentation](https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_proteintsv) reads: 

Unique Intensity normalized protein intensity from the sequences mapping only to the selected protein (from Philosopher freequant; if IonQuant is used, this is calculated using **EITHER** MaxLFQ or Top-N algorithm, depending on selection)

What are the intensity columns without "MaxLFQ"? Do they contain topN intensities?
Is this an undocumented feature (that both types of intensities are reported) and is there an option to switch it off, so that the maxlfq intensities are written into the columns as documented?

**Comment by wolski** [comment]
Thanks. 

PS. I am also getting the Total and Unique columns when extracting the "Intensity" columns from the combined_protein files using "Intensity$" regexp. Therefore, how about restoring the column suffix "Razor Intensity" instead of "Intensity", or changing the other column types too, e.g., "Intensity Total" and "Intensity Total MaxLFQ". Sure I also could grep for "MaxLFQ" only but there are NO guaranties that someone will not use MaxLFQ as Experiment name.

**Comment by fcyu** [comment]
We changed `Razor Intensity` to `Intensity` to suggest that this is one should be used in most cases. 

I think the `\t[^ \t]+ Intensity` regex should work for the "Intensity" column, and `\t[^ \t]+ MaxLFQ Intensity` regex should work for the "MaxLFQ Intensity" column. Supposing there is no space or tab in the experiment name, which is also what we recommended. If there is an experiment having name "MaxLFQ", those two regex should still work.

Please feel free to contact us if you have any questions regarding those regex.

Best,

Fengchao
