### ISSUE TITLE
Problem with 'PhilosopherFilter' exit code

### ISSUE THREAD

**Issue by KR-15** [Nesvilab/FragPipe#579]
Hi, 

I'm currently using FragPiPe with those specific versions:

Version info:
FragPipe version 17.1
MSFragger version 3.4
Philosopher version 4.1.0 (build 1635640020)

I am using the LFQ-phospho workflow for basic phosphoenrichment experiment with 2 groups (8vs8) on timsTOF Pro data.

As the LFQ-phospho workflow only accepts mzML files as an input, I previously used MSConvert to transform .d raw files into mzML files and I think it goes well for this part (I used the tutorial to convert .d into mzML of this page https://fragpipe.nesvilab.org/docs/tutorial_convert.html). Then I run the LFQ-phospho workflow analysis without changing any default parameters (maybe only the "min ions" parameter) and I get an error message probably related with PhilosopherFilter as the end of the analysis:

> INFO[18:06:06] Executing Filter  v4.1.0                     
> INFO[18:06:06] Processing peptide identification files      
> FATA[18:06:06] Cannot decode packed binary. expected element type <msms_pipeline_analysis> but have <msms_run_summary> 
> Process 'PhilosopherFilter' finished, exit code: 1
> Process returned non-zero exit code, stopping

You can find attached the log file of the analysis.

[log_2022-01-11_18-06-07.txt](https://github.com/Nesvilab/FragPipe/files/7853427/log_2022-01-11_18-06-07.txt)

If you need other information from me do not hesitate.

Thank you

Best,

KR

**Comment by fcyu** [comment]
Seems to be an error from Philosopher:
```
PhilosopherFilter [Work dir: D:\Orbidata\IsSE_MaAU\Results_FragPipe_Phospho_mzML_PTMProphet\TRI_4]
C:\Users\Admin\Desktop\FragPipe-16.0\fragpipe\tools\philosopher\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml D:\Orbidata\IsSE_MaAU\Results_FragPipe_Phospho_mzML_PTMProphet\TRI_4 --protxml D:\Orbidata\IsSE_MaAU\Results_FragPipe_Phospho_mzML_PTMProphet\combined.prot.xml --razorbin D:\Orbidata\IsSE_MaAU\Results_FragPipe_Phospho_mzML_PTMProphet\DMSO_1\.meta\razor.bin
INFO[18:06:06] Executing Filter  v4.1.0                     
INFO[18:06:06] Processing peptide identification files      
FATA[18:06:06] Cannot decode packed binary. expected element type <msms_pipeline_analysis> but have <msms_run_summary> 
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Felipe @prvst , can you take a look when you have time?

Thanks,

Fengchao

**Comment by KR-15** [comment]
Hi prvst,

Thank you for your reply.

I have relaunch the exact same analysis with only 4 CPUs and 2 CPUs instead of 8 CPUs (first try). It seems that the analysis runs further but there is still a new error message almost at the end of the analysis (see log files below). The error message is the same for both. Just to precise that there is a DIA-NN analysis that are currently running in the same computer but not all available threads are used for it.

For curiosity, why the number of threads used can impact the proper creation of a specific file (here xml) ?

Thank you for your help.

KR

[log_2022-01-12_18-41-28_4_CPU.txt](https://github.com/Nesvilab/FragPipe/files/7862818/log_2022-01-12_18-41-28_4_CPU.txt)
[log_2022-01-13_10-44-29_2_CPU.txt](https://github.com/Nesvilab/FragPipe/files/7862821/log_2022-01-13_10-44-29_2_CPU.txt)

**Comment by fcyu** [comment]
Hi KR,

Could you please send the file 211220_IsSE_MaAU_nE_LFQ-P_CL_n1-8_F3_DMSO_2886.mzML to us? I can give you a link to upload the data if you need it.

Best,

Fengchao

**Comment by KR-15** [comment]
Hi fcyu,

Yes of course, could you please provide a safe link for the upload ?

Best,

KR

**Comment by fcyu** [comment]
Sounds good! Here (https://www.dropbox.com/sh/i1zeuv8510hd9i9/AADXlXWgoAWbdFQm4UD0k4f9a?dl=0) is the link.

Thanks,

Fengchao

**Comment by KR-15** [comment]
I had a problem uploading in the dropbox so I send a filesender link with de mzML file in your personal email address sorry.

Thanks for your help.

KR

**Comment by fcyu** [comment]
Hi KR,

The file is well received.

I perform an analysis using human database and the default LFQ-MBR workflow. But I cannot reproduce the issue. 

I need all of the files in your `DMSO_1` folder (corresponding to run `211220_IsSE_MaAU_nE_LFQ-P_CL_n1-8_F3_DMSO_2886.mzML`), your fasta file, and `fragger.params` file to debug.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Yes, I am using the LFQ plus phospho. I guess I need at least your fasta file and fragger.params to reproduce the error.

Best,

Fengchao

**Comment by KR-15** [comment]
Hi Fengchao,

I have just sent you all the files that you may need to reproduce the error in a new filesender link.

Thanks for your time and help.

KR

**Comment by fcyu** [comment]
Hi KR,

The files are well received. I see that, this time, you also included a `.d.zip` file, which reminds me that your data is from timsTOF Pro. And you do specified `IM-MS` during the FragPipe analysis, but there is no ion mobility array in your mzML file. I think that is the cause of the error you were having. (When I was trying to reproducing the issue, I didn't specify `IM-MS`. Then IonQuant won't look for the ion mobility array. That is also why I could not reproduce the error).

Can you confirm that your data is from ddaPASEF with ion mobility module enabled. If so, you need to convert your .d according to the tutorial here (https://fragpipe.nesvilab.org/docs/tutorial_convert.html). I see that you were not using `scanSumming` filter, which you should.

Or, you can use use .d without any converting.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi KR,

I think we have figured out the cause if the issue. Please read https://github.com/Nesvilab/FragPipe/issues/581#issuecomment-1013909453 for details.

Best,

Fengchao
