### ISSUE TITLE
Purity column is missing with Philosopher 4.1.1 and raw file format

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#583]
Greetings,

I am currently trying to re-analysis the proteomics data from PXD008443 (https://www.ebi.ac.uk/pride/archive/projects/PXD008443) using MSFragger version 17.1. This is a iTRAQ-8plex data (http://www.unimod.org/modifications_view.php?editid1=730). Due to some reason, I am facing errors. I have attatched the error log in this thread for your reference. Please do advise on how to troubleshoot this error.

Lastly, I would like to thank you for assisting me in advance and providing this amazing tool. 

Regards,
Ben
[log_2022-01-16_15-25-05.txt](https://github.com/Nesvilab/MSFragger/files/7876590/log_2022-01-16_15-25-05.txt)

**Comment by fcyu** [comment]
Hi Ben,

I see that you are using raw format. And the error message is

```
TmtIntegrator [Work dir: D:\MSFragger_Temp\PXD008443\MSFragger_CloseSearch_Output]
D:\FragPipe-jre-17.1\fragpipe\jre\bin\java.exe -Xmx100G -cp "D:\FragPipe-jre-17.1\fragpipe\tools\tmt-integrator-3.2.1.jar" TMTIntegrator D:\MSFragger_Temp\PXD008443\MSFragger_CloseSearch_Output\tmt-integrator-conf.yml D:\MSFragger_Temp\PXD008443\MSFragger_CloseSearch_Output\psm.tsv
Process 'TmtIntegrator' finished, exit code: 1
TMT-Integrator can't find the 'Purity' column. Please check if the column is in the psm tables.
Process returned non-zero exit code, stopping
```

Thus, I think it is a known issue (https://github.com/Nesvilab/FragPipe/issues/571). For now, you can convert your files to mzML format. We will address this issue in the future.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

My apologies, I should have searched this before starting a new thread. 

Regards,
Ben
