### ISSUE TITLE
Error when running 48 batches of TMT10 (single cell)

### ISSUE THREAD

**Issue by yishai99** [Nesvilab/FragPipe#584]
Hi, I tried processing 48 batches of TMT10 labeled samples (SCOPEMS), single cell analysis and get an error. 
[log_2022-01-17_08-36-11.txt](https://github.com/Nesvilab/FragPipe/files/7879578/log_2022-01-17_08-36-11.txt)
Not sure what it means.

Thanks,

Yishai

**Comment by fcyu** [comment]
Hi Yishai,

There are 0 PSMs identified from your data. Please double check your settings.

Best,

Fengchao

**Comment by anesvi** [comment]
To add a  few questions/comments:


  1.  What workflow did you use? I see there is no calibration specified. And PeptideProphet is used. Our TMT workflows have calibration and Percolator. It is always best to use a default workflow before making changes



  1.  Please confirm that you have high mass accuracy MS2 data?


  1.  I suggest converting from raw to mzML for all TMT based workflows.

If you are using the right workflow, you are sure your data is OK (e.g. other tools give reasonable ID numbers), could you share a few files with us
Thanks
Alexey

**Comment by yishai99** [comment]
1. I tried the default workflow and got an error. The tried changing the validation method. As for calibration it is very sparse data so thought it might be related.
2. high mass accuracy ms2 Yes
3. Will try to covert.

I will send the data directly to your email.
Thanks,

Yishai

**Comment by fcyu** [comment]
Hi Yishai,

> 1. I tried the default workflow and got an error. 

Can you send us the log file?

Thanks,

Fengchao
