### ISSUE TITLE
Possible to bring back Matching-between-runs correlation value in log?

### ISSUE THREAD

**Issue by algom** [Nesvilab/FragPipe#586]
Hello,

I can't pin point in which version there was a change, but before it was possible (for sure Fragpipe 15) to see in the log the Match-between-runs (MBR) correlation value of every run:

Previously:

Matching-between-runs: NAME_of_RAW_fIle.....
Date [INFO] - Calculating correlations between all other runs...
Date [INFO] - Correlation with NAME_of_RAW_fIle_2 **VALUE**

As of now Fragpipe 17 reports it different:

Date [INFO] - Matching-between-runs: NAME_of_RAW_fIle.....
Date [INFO] - Calculating correlations between all other runs...
Date [WARNING] - There is no run passing the minimum correlation threshold 0.4

I founded the previous behavior more informative as in some cases it is not desirable to MBR between files that have nothing in common. Even though the FDR settings helps a lot, I found that by choosing a correlation value as a cut-off on top of the FDR helped as well. So, sometimes I would do a run and checked the log and see the correlation values, and based on that I would choose a cut-off and re-run Fragpipe to for example be sure to only match between technical replicates that naturally tend to have a higher correlation than biological replicates or between experimental condition.

I don't know if that strategy was very sound, but it also gave a good overview of how similar the id's features were between the files and allowed also to pin-point extreme case. I don't know what are your thoughts on this or if it would be possible or makes sense to have that information.

Thank you for the great software,

Alejandro

**Comment by fcyu** [comment]
Hi Alejandro,

We stop printing the correlation because it is not very informative and it is verbose when there are many runs. Imaging that there were 100 runs, there would be `100 * 99` such lines.

Best,

Fengchao
