### ISSUE TITLE
Percolator keeps crashing

### ISSUE THREAD

**Issue by hboekweg** [Nesvilab/FragPipe#587]
This is the first time I've run msfragger with the percolator update and it crashes and says to "check if the correct file-format was used".  I looked into that a little bit and found that the percolator_decoy_psms.tsv and percolator_target_psms.tsv files are empty, and no .pin file was created.  I can't figure out what I'm doing wrong.  I'm using all the default settings for DDA and I'm using the fasta file that I downloaded from msfragger.

**Comment by fcyu** [comment]
Can you send us your log file?

Thanks,

Fengchao

**Comment by fcyu** [comment]
The output format setting of MSFragger was set to `tsv_pepXML`, which will not generate pin files for Percolator. Please change it to `pepXML_pin`, or simply re-load the `Default` workflow.

Best,

Fengchao
