### ISSUE TITLE
Open Search does not work - It is recognized as a closed search

### ISSUE THREAD

**Issue by dkueltz** [Nesvilab/FragPipe#588]
**Describe the bug**
The open search function in Fragpipe (latest version) does not work. When using default open search settings then processing is halted by the error message:
"Count It is a closed search while localize_delta_mass = 1. Please change localize_delta_mass to 0.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping"
Tried everything and many different DBs and samples - they all work well with closed search but when using open search even in the most basic default config it never works and always gives the same error.
Thanks, Dietmar

**Comment by fcyu** [comment]
Can you send us your log?

Thanks,

Fengchao

**Comment by dkueltz** [comment]
Hi Fengchao,

The error log is below. For this run I checked "Report mass shift as a variable mod" = "No". I tried the other two options before with the same result. Thanks for looking into this!

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_301, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation


Version info:
FragPipe version 17.1
MSFragger version 3.4
Philosopher version 4.1.0 (build 1635640020)


LCMS files:
  Experiment/Group: 
  - F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML	DDA


13 commands to execute:
CheckCentroid
java -Xmx50G -cp "D:\FragPipe-17.1\fragpipe\lib\fragpipe-17.1.jar;D:\FragPipe-17.1\fragpipe\tools\batmass-io-1.23.6.jar" com.dmtavt.fragpipe.util.CheckCentroid F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML 15
WorkspaceCleanInit [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe workspace --clean --nocheck
WorkspaceCleanInit [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe workspace --init --nocheck
MSFragger [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
java -jar -Dfile.encoding=UTF-8 -Xmx50G D:\fragpipe17.0\tools\MSFragger-3.4\MSFragger-3.4.jar F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\fragger.params F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML
Crystal-C [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
java -Dbatmass.io.libs.thermo.dir="D:\fragpipe17.0\tools\MSFragger-3.4\ext\thermo" -Xmx50G -cp "D:\FragPipe-17.1\fragpipe\tools\original-crystalc-1.4.2.jar;D:\FragPipe-17.1\fragpipe\tools\batmass-io-1.23.6.jar;D:\FragPipe-17.1\fragpipe\tools\grppr-0.3.23.jar" crystalc.Run F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\crystalc-0-EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.pepXML.params F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.pepXML
PeptideProphet [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy rev_ --database D:\Databases\Oreni\2021-12-22-decoys-Oreni_histones39_NCBI-IdentProtGroups_05Dec2021.fasta.fas --combine EAM0034_S0F1G_V8-AmBic_2-A1_01_4349_c.pepXML
Rewrite pepxml [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
java -cp D:\FragPipe-17.1\fragpipe\lib/* com.dmtavt.fragpipe.util.RewritePepxml F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\interact.pep.xml F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML
ProteinProphet [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\filelist_proteinprophet.txt
PhilosopherDbAnnotate [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe database --annotate D:\Databases\Oreni\2021-12-22-decoys-Oreni_histones39_NCBI-IdentProtGroups_05Dec2021.fasta.fas --prefix rev_
PhilosopherFilter [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe filter --sequential --prot 0.01 --mapmods --tag rev_ --pepxml F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill --protxml F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\combined.prot.xml --razor
PhilosopherReport [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe report
PTMShepherd [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
java -Xmx50G -Dbatmass.io.libs.thermo.dir="D:\fragpipe17.0\tools\MSFragger-3.4\ext\thermo" -cp "D:\FragPipe-17.1\fragpipe\tools\ptmshepherd-1.2.6.jar;D:\FragPipe-17.1\fragpipe\tools\batmass-io-1.23.6.jar;D:\FragPipe-17.1\fragpipe\tools\commons-math3-3.6.1.jar" edu.umich.andykong.ptmshepherd.PTMShepherd "F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\shepherd.config"
WorkspaceClean [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe workspace --clean --nocheck
~~~~~~~~~~~~~~~~~~~~~~

Execution order:

    Cmd: [START], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [CheckCentroid], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [WorkspaceCleanInit], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [MSFragger], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [Crystal-C], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [PeptideProphet], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [ProteinProphet], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [PhilosopherDbAnnotate], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [PhilosopherFilter], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [PhilosopherReport], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [PTMShepherd], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
    Cmd: [WorkspaceClean], Work dir: [F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]

~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ fragpipe.config ~~~~~~~~~
# FragPipe v17.1ui state cache

crystalc.run-crystalc=true
database.db-path=D\:\\Databases\\Oreni\\2021-12-22-decoys-Oreni_histones39_NCBI-IdentProtGroups_05Dec2021.fasta.fas
database.decoy-tag=rev_
diann.fragpipe.cmd-opts=
diann.library=
diann.q-value=0.01
diann.quantification-strategy=0
diann.run-dia-nn=false
diaumpire.AdjustFragIntensity=true
diaumpire.BoostComplementaryIon=false
diaumpire.CorrThreshold=0
diaumpire.DeltaApex=0.2
diaumpire.ExportPrecursorPeak=false
diaumpire.Q1=true
diaumpire.Q2=true
diaumpire.Q3=true
diaumpire.RFmax=500
diaumpire.RPmax=25
diaumpire.RTOverlap=0.3
diaumpire.SE.EstimateBG=false
diaumpire.SE.IsoPattern=0.3
diaumpire.SE.MS1PPM=10
diaumpire.SE.MS2PPM=20
diaumpire.SE.MS2SN=1.1
diaumpire.SE.MassDefectFilter=true
diaumpire.SE.MassDefectOffset=0.1
diaumpire.SE.NoMissedScan=1
diaumpire.SE.SN=1.1
diaumpire.run-diaumpire=false
fragpipe-config.bin-msfragger=D\:\\fragpipe17.0\\tools\\MSFragger-3.4\\MSFragger-3.4.jar
fragpipe-config.bin-philosopher=D\:\\fragpipe17.0\\tools\\philosopher\\philosopher.exe
fragpipe-config.bin-python=C\:\\ProgramData\\Anaconda3\\python
freequant.mz-tol=10
freequant.rt-tol=0.4
freequant.run-freequant=true
ionquant.excludemods=
ionquant.heavy=
ionquant.imtol=0.05
ionquant.ionfdr=0.01
ionquant.light=
ionquant.locprob=0.75
ionquant.maxlfq=1
ionquant.mbr=0
ionquant.mbrimtol=0.05
ionquant.mbrmincorr=0
ionquant.mbrrttol=1
ionquant.mbrtoprun=100000
ionquant.medium=
ionquant.minexps=1
ionquant.minfreq=0.5
ionquant.minions=2
ionquant.minisotopes=2
ionquant.minscans=3
ionquant.mztol=10
ionquant.normalization=1
ionquant.peptidefdr=1
ionquant.proteinfdr=1
ionquant.requantify=1
ionquant.rttol=0.4
ionquant.run-ionquant=false
ionquant.tp=3
ionquant.writeindex=0
msbooster.predict-rt=true
msbooster.predict-spectra=true
msbooster.run-msbooster=false
msfragger.Y_type_masses=
msfragger.add_topN_complementary=0
msfragger.allowed_missed_cleavage_1=2
msfragger.allowed_missed_cleavage_2=2
msfragger.calibrate_mass=2
msfragger.clip_nTerm_M=false
msfragger.deisotope=1
msfragger.delta_mass_exclude_ranges=(-1.5,3.5)
msfragger.deneutralloss=1
msfragger.diagnostic_fragments=
msfragger.diagnostic_intensity_filter=0
msfragger.digest_max_length=50
msfragger.digest_min_length=6
msfragger.fragment_ion_series=b,y,a,x,c,z
msfragger.fragment_mass_tolerance=15
msfragger.fragment_mass_units=1
msfragger.intensity_transform=0
msfragger.ion_series_definitions=
msfragger.isotope_error=1
msfragger.labile_search_mode=off
msfragger.localize_delta_mass=true
msfragger.mass_diff_to_variable_mod=0
msfragger.mass_offsets=0
msfragger.max_fragment_charge=2
msfragger.max_variable_mods_combinations=5000
msfragger.max_variable_mods_per_peptide=3
msfragger.min_fragments_modelling=2
msfragger.min_matched_fragments=4
msfragger.minimum_peaks=15
msfragger.minimum_ratio=0.01
msfragger.misc.fragger.clear-mz-hi=0
msfragger.misc.fragger.clear-mz-lo=0
msfragger.misc.fragger.digest-mass-hi=5000
msfragger.misc.fragger.digest-mass-lo=500
msfragger.misc.fragger.enzyme-dropdown-1=gluc_bicarb
msfragger.misc.fragger.enzyme-dropdown-2=null
msfragger.misc.fragger.precursor-charge-hi=4
msfragger.misc.fragger.precursor-charge-lo=1
msfragger.misc.fragger.remove-precursor-range-hi=1.5
msfragger.misc.fragger.remove-precursor-range-lo=-1.5
msfragger.misc.slice-db=1
msfragger.num_enzyme_termini=2
msfragger.output_format=tsv_pepXML_pin
msfragger.output_max_expect=50
msfragger.output_report_topN=1
msfragger.override_charge=false
msfragger.precursor_mass_lower=-15
msfragger.precursor_mass_mode=corrected
msfragger.precursor_mass_units=1
msfragger.precursor_mass_upper=15
msfragger.precursor_true_tolerance=15
msfragger.precursor_true_units=1
msfragger.remove_precursor_peak=0
msfragger.report_alternative_proteins=true
msfragger.restrict_deltamass_to=all
msfragger.run-msfragger=true
msfragger.search_enzyme_cut_1=E
msfragger.search_enzyme_cut_2=
msfragger.search_enzyme_name_1=gluc_bicarb
msfragger.search_enzyme_name_2=null
msfragger.search_enzyme_nocut_1=P
msfragger.search_enzyme_nocut_2=
msfragger.search_enzyme_sense_1=C
msfragger.search_enzyme_sense_2=C
msfragger.table.fix-mods=0.000000,C-Term Peptide,true,-1; 0.000000,N-Term Peptide,true,-1; 0.000000,C-Term Protein,true,-1; 0.000000,N-Term Protein,true,-1; 0.000000,G (glycine),true,-1; 0.000000,A (alanine),true,-1; 0.000000,S (serine),true,-1; 0.000000,P (proline),true,-1; 0.000000,V (valine),true,-1; 0.000000,T (threonine),true,-1; 57.021460,C (cysteine),true,-1; 0.000000,L (leucine),true,-1; 0.000000,I (isoleucine),true,-1; 0.000000,N (asparagine),true,-1; 0.000000,D (aspartic acid),true,-1; 0.000000,Q (glutamine),true,-1; 0.000000,K (lysine),true,-1; 0.000000,E (glutamic acid),true,-1; 0.000000,M (methionine),true,-1; 0.000000,H (histidine),true,-1; 0.000000,F (phenylalanine),true,-1; 0.000000,R (arginine),true,-1; 0.000000,Y (tyrosine),true,-1; 0.000000,W (tryptophan),true,-1; 0.000000,B ,true,-1; 0.000000,J,true,-1; 0.000000,O,true,-1; 0.000000,U,true,-1; 0.000000,X,true,-1; 0.000000,Z,true,-1
msfragger.table.var-mods=15.994900,M,true,3; 42.010600,[^,true,1; 79.966330,STY,false,3; -17.026500,nQnC,false,1; -18.010600,nE,false,1; 4.025107,K,false,2; 6.020129,R,false,2; 8.014199,K,false,2; 10.008269,R,false,2; 0.000000,site_10,false,1; 0.000000,site_11,false,1; 0.000000,site_12,false,1; 0.000000,site_13,false,1; 0.000000,site_14,false,1; 0.000000,site_15,false,1; 0.000000,site_16,false,1
msfragger.track_zero_topN=0
msfragger.use_all_mods_in_first_search=false
msfragger.use_topN_peaks=150
msfragger.write_calibrated_mgf=false
msfragger.zero_bin_accept_expect=0
msfragger.zero_bin_mult_expect=1
peptide-prophet.cmd-opts=--nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2
peptide-prophet.combine-pepxml=true
peptide-prophet.run-peptide-prophet=true
percolator.cmd-opts=--only-psms --no-terminate --post-processing-tdc
percolator.keep-tsv-files=false
percolator.run-percolator=false
phi-report.dont-use-prot-proph-file=false
phi-report.filter=--sequential --prot 0.01 --mapmods
phi-report.pep-level-summary=false
phi-report.philosoher-msstats=false
phi-report.print-decoys=false
phi-report.prot-level-summary=true
phi-report.run-report=true
protein-prophet.cmd-opts=--maxppmdiff 2000000
protein-prophet.run-protein-prophet=true
ptmprophet.cmdline=
ptmprophet.run-ptmprophet=false
ptmshepherd.adv_params=false
ptmshepherd.annotation-common=false
ptmshepherd.annotation-custom=false
ptmshepherd.annotation-glyco=false
ptmshepherd.annotation-unimod=true
ptmshepherd.annotation_file=
ptmshepherd.annotation_tol=0.01
ptmshepherd.assign_glycans=false
ptmshepherd.cap_y_ions=
ptmshepherd.decoy_type=1
ptmshepherd.diag_ions=
ptmshepherd.glyco_adducts=
ptmshepherd.glyco_fdr=1.00
ptmshepherd.glyco_isotope_max=3
ptmshepherd.glyco_isotope_min=-1
ptmshepherd.glyco_mode=false
ptmshepherd.glyco_ppm_tol=50
ptmshepherd.glycodatabase=
ptmshepherd.histo_smoothbins=2
ptmshepherd.iontype_a=false
ptmshepherd.iontype_b=true
ptmshepherd.iontype_c=false
ptmshepherd.iontype_x=false
ptmshepherd.iontype_y=true
ptmshepherd.iontype_z=false
ptmshepherd.localization_allowed_res=all
ptmshepherd.localization_background=4
ptmshepherd.max_adducts=0
ptmshepherd.n_glyco=true
ptmshepherd.normalization-psms=true
ptmshepherd.normalization-scans=false
ptmshepherd.output_extended=false
ptmshepherd.peakpicking_mass_units=0
ptmshepherd.peakpicking_minPsm=10
ptmshepherd.peakpicking_promRatio=0.3
ptmshepherd.peakpicking_width=0.002
ptmshepherd.precursor_mass_units=0
ptmshepherd.precursor_tol=0.01
ptmshepherd.print_decoys=false
ptmshepherd.prob_dhexOx=
ptmshepherd.prob_dhexY=
ptmshepherd.prob_neuacOx=
ptmshepherd.prob_neugcOx=
ptmshepherd.prob_phosphoOx=
ptmshepherd.prob_regY=
ptmshepherd.prob_sulfoOx=
ptmshepherd.remainder_masses=
ptmshepherd.remove_glycan_delta_mass=false
ptmshepherd.run-shepherd=true
ptmshepherd.spectra_maxfragcharge=2
ptmshepherd.spectra_ppmtol=20
ptmshepherd.varmod_masses=
quantitation.run-label-free-quant=false
run-psm-validation=true
speclibgen.easypqp.extras.max_delta_ppm=15
speclibgen.easypqp.extras.max_delta_unimod=0.02
speclibgen.easypqp.extras.rt_lowess_fraction=0
speclibgen.easypqp.im-cal=Automatic selection of a run as reference IM
speclibgen.easypqp.rt-cal=ciRT
speclibgen.easypqp.select-file.text=
speclibgen.easypqp.select-im-file.text=
speclibgen.keep-intermediate-files=false
speclibgen.run-speclibgen=false
tmtintegrator.add_Ref=-1
tmtintegrator.aggregation_method=0
tmtintegrator.allow_overlabel=true
tmtintegrator.allow_unlabeled=false
tmtintegrator.best_psm=true
tmtintegrator.channel_num=10
tmtintegrator.dont-run-fq-lq=false
tmtintegrator.groupby=-1
tmtintegrator.max_pep_prob_thres=0
tmtintegrator.min_ntt=0
tmtintegrator.min_pep_prob=0.9
tmtintegrator.min_percent=0.05
tmtintegrator.min_purity=0.5
tmtintegrator.min_site_prob=-1
tmtintegrator.mod_tag=none
tmtintegrator.ms1_int=true
tmtintegrator.outlier_removal=true
tmtintegrator.print_RefInt=false
tmtintegrator.prot_exclude=none
tmtintegrator.prot_norm=-1
tmtintegrator.psm_norm=false
tmtintegrator.quant_level=2
tmtintegrator.ref_tag=pool
tmtintegrator.run-tmtintegrator=false
tmtintegrator.top3_pep=true
tmtintegrator.unique_gene=0
tmtintegrator.unique_pep=false
workdir=F\:\\EAM0034-36_Oremo_V8-AmBic\\DDA_mzML-MSfragger\\Gill
workflow.input.data-type.im-ms=false
workflow.input.data-type.regular-ms=true
workflow.ram=0
workflow.threads=15

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CheckCentroid
java -Xmx50G -cp "D:\FragPipe-17.1\fragpipe\lib\fragpipe-17.1.jar;D:\FragPipe-17.1\fragpipe\tools\batmass-io-1.23.6.jar" com.dmtavt.fragpipe.util.CheckCentroid F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML 15
Done in 5078 ms.
Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe workspace --clean --nocheck
INFO[11:33:03] Executing Workspace  v4.1.0                  
INFO[11:33:03] Removing workspace                           
INFO[11:33:03] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
D:\fragpipe17.0\tools\philosopher\philosopher.exe workspace --init --nocheck
INFO[11:33:04] Executing Workspace  v4.1.0                  
INFO[11:33:04] Creating workspace                           
INFO[11:33:04] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
MSFragger [Work dir: F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill]
java -jar -Dfile.encoding=UTF-8 -Xmx50G D:\fragpipe17.0\tools\MSFragger-3.4\MSFragger-3.4.jar F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\fragger.params F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML
MSFragger version MSFragger-3.4
Batmass-IO version 1.23.6
timsdata library version timsdata-2-8-7-1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_301, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 44 GB memory
Checking database...
Checking spectral files...
F:\EAM0034-36_Oremo_V8-AmBic\DDA_mzML-MSfragger\Gill\EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML: Scans = 22247
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 15
database_name = D:\Databases\Oreni\2021-12-22-decoys-Oreni_histones39_NCBI-IdentProtGroups_05Dec2021.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -15.0
precursor_mass_upper = 15.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 15.0
precursor_true_units = 1
fragment_mass_tolerance = 15.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = false
write_calibrated_mgf = 0
isotope_error = 0/1
mass_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = CORRECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y,a,x,c,z
ion_series_definitions = 
search_enzyme_name = gluc_bicarb
search_enzyme_sense_1 = C
search_enzyme_cut_1 = E
search_enzyme_nocut_1 = P
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = false
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = tsv_pepxml_pin
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 6
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
deisotope = 1
deneutralloss = true
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = true
variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
add_A_alanine = 0.000000
add_B_user_amino_acid = 0.000000
add_C_cysteine = 57.021460
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_J_user_amino_acid = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.000000  # O = pyrrolysine (237.14773 Da)
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_U_user_amino_acid = 0.000000  # U = selenocysteine (150.95363 Da)
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_X_user_amino_acid = 0.000000
add_Y_tyrosine = 0.000000
add_Z_user_amino_acid = 0.000000
Selected fragment index width 0.08 Da.
154236 fragments to be searched in 1 slices (0.00 GB total)
Operating on slice 1 of 1: 
	Fragment index slice generated in 0.08 s
	001. EAM0034_S0F1G_V8-AmBic_2-A1_01_4349.mzML 7.3 s | deisotoping 5.2 s
		[progress: 22247/22247 (100%) - 12071 spectra/s] 1.8s | postprocessing 0.0 s
***************************FIRST SEARCH DONE IN 0.418 MIN**************************

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |     69|     84|     90|     93|     92| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |     93|     96|     97|     93| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |    101
-------|-------
-------|-------
 Rm P. |    1  
-------|-------
 Count It is a closed search while localize_delta_mass = 1. Please change localize_delta_mass to 0.
|    101
-------|-------
New fragment_mass_tolerance = 15 PPM
New use_topN_peaks = 175
New minimum_ratio = 0.000000
New intensity_transform = 1
New remove_precursor_peak = 1
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 1.996 MIN*********

************************************MAIN SEARCH************************************
Checking database...
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 10 remaining tasks

**Comment by fcyu** [comment]
···
msfragger.precursor_mass_lower=-15
msfragger.precursor_mass_units=1
msfragger.precursor_mass_upper=15
···

You changed the precursor mass to a small range (e.g., closed search). Please re-load the `open search`  workflow and do not change the parameters that you are not sure of.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
It also says you’re searching for a,b,c,x,y,z ions, is that correct?

**Comment by dkueltz** [comment]
Thanks, Fengchao, I see the logic behind keeping the mass error limits very wide now. I did reset those and it works now with b and y ions selected. i will try all six fragment ions (a,b,c,x,y,z) next. I routinely observe these other ions in my spectra under the specific frgmentation conditions I use.
Thanks for your help - much appreciated!
Dietmar

**Comment by dkueltz** [comment]
HI Daniel,
Yes i normally use all six ion types but did try just now with only y and b. will try all six next. Is there any concern with using all six in fragpipe?

**Comment by anesvi** [comment]
Even though one can observe more than y and b ions, using more than y and b in scoring often leads to a loss of IDs. I recall observing it in various tests in closed searches. Even though the score for correct IDs increases, false IDs also get an increase in score (since more ions to match by chance). So you are not gaining actually by adding those ions. I would think in open searches, you are even less likely to gain from extra ions than in closed searches.
Note my comments is about HCD data. If you do hybrid methods like EthCD then of course you need y/b/c/z
Alexey

**Comment by dkueltz** [comment]
Thank you for the explanation of msfragger scoring when adding a,x,c,z ions. Knowing this, I will limit searches to y and b ions.
Best,
Dietmar
