### ISSUE TITLE
Intensity column clarification

### ISSUE THREAD

**Issue by ajaj93** [Nesvilab/FragPipe#589]
Hi, 

I was wondering if the different intensity columns in the combined_protein.csv fragpipe output are as follows:

Unique intensity: only unique peptides
Razor intensity: a mixture of razor and unique peptides?
Total intensity: any peptide contributing to that protein even if it's shared with another protein? 

If this is not the case then please can you clarify what their definitions are? It is clear in the description of the protein.csv file that total intensity is only unique and razor, but the description for the combined_protein.csv file is not as clear, and it is written as though the total intensity is for any peptide, not just unique and razor. 

Thanks

**Comment by fcyu** [comment]
Yes, you are correct about those three intensities. 

> It is clear in the description of the protein.csv file that total intensity is only unique and razor, but the description for the combined_protein.csv file is not as clear, and it is written as though the total intensity is for any peptide, not just unique and razor.

Total intensities in both combined_protein.tsv and protein.tsv are from any peptides contributing to that protein.

Best,

Fengchao

**Comment by fcyu** [comment]
It includes unique + razor + all other mapped peptides.

Best,

Fengchao

**Comment by sarah-haynes** [comment]
Hi Hannah, fixed in [this commit](https://github.com/Nesvilab/FragPipe/commit/b29b2643164f5e40b198486e596c5c2272489282). Thanks for catching this!
Sarah
