### ISSUE TITLE
Fragpipe Sample Annotation - MBR

### ISSUE THREAD

**Issue by vegesnam** [Nesvilab/FragPipe#590]
I am analyzing TimsToF Samples using Fragpipe. In the MS1 Quant Step, I have selected IonQuant and have enabled MBR. I have both Plasma and HeLa samples and have annotated them as below:

![image](https://user-images.githubusercontent.com/87665957/150440431-c256fe59-2ebf-43e7-81b5-a1e77d7f7154.png)

In this case, I want to know how the MBR setting would work. Will it try to do match between runs across the Hela and Plasma samples based on the Bioreplicate column? For example, will it match between Plasma_1 and Hela_1?

**Comment by fcyu** [comment]
It depends on the `MBR min correlation` and `MBR top runs` parameters. The default values are 0 and 100000, respectively, which means using all runs in transferring ions. You can adjust the `MBR top runs` to control the number of runs used in ion transfer.

Best,

Fengchao
