### ISSUE TITLE
Large fraction of zero-values  

### ISSUE THREAD

**Issue by liveha** [Nesvilab/FragPipe#592]
Dear Nesvilab, 

First of all, thank you for this great software! Due to database size limitations, I recently shifted from MaxQuant to FragPipe for metaproteomics analysis. I am currently facing an issue that I am not able to solve myself, and I am hoping that someone could help me. 
I am working on a dataset from animal gut microflora that consist of two experimental groups; ‘AP’ and ‘BP’. There are 8 biological replicates within each experimental group. I have timsTOF MS data from Bruker (.d), and use the LFQ-MBR workflow. I use a costume fasta database, with decoys and contamination added. 

Then I have done two FragPipe runs: 
I first did a test using a small subset of the raw data: One raw file from control and one from the diet group. This gave ~9000 proteins in combined_protein.tsv, and all of the proteins had a quantitative value for either AP or BP, or both. 

In the second run, all 16 samples (8 AP, 8 BP) were included. The parameters and database were the same as the test run, only MS datafiles added and paths changed. This gave a total of 15 000 proteins. However, ~2/3 have a quantitative value of zero.  

Any ideas on why I am getting a large fraction of zero-values for intensities when including all samples in run 2, including several of those that had a quantitiative value i run 1?  

I have attached the log file from the second run, please let me know if you would like me to share anything else or provide more information. Thank you!

Kind regards, 
LHH

[log_2022-01-07_07-24-37.txt](https://github.com/Nesvilab/FragPipe/files/7928189/log_2022-01-07_07-24-37.txt)

**Comment by fcyu** [comment]
Hi LHH,

I think there are not many overlapped ions between any two runs of your sample. When you use MaxLFQ algorithm in IonQuant, many proteins will have no intensity. When you only have two runs in your first analysis, IonQuant automatically changes to Top-N algorithm, which will not suffer from the low overlapping issue. Can you try to use Top-N in MS1 quant tab?

Best,

Fengchao

**Comment by liveha** [comment]
Hi Fengchao, 

Thank you! I will try that asap, and let you know how it goes. 

Also; wow - impressive response time!!

**Comment by liveha** [comment]
Hello again! Just want to let you know that your suggestion seems to work, the number of proteins are more in line with what I expected. Will therefor close this issue. Thanks again for the help, and for a great tool! 

Best, 
Live
