### ISSUE TITLE
How is "Mass calibration and parameter optimization performed"?

### ISSUE THREAD

**Issue by juank1892** [Nesvilab/FragPipe#593]
I am running some open searches on DDA data this curiosity came up:

How does MSFragger decide which MS file has enough data points to perform a mass calibration both at the ms1 and ms2 levels?

I have seen that for instrumental replicates for some the mass recalibration is performed, but for others it is not. E.g.
File 04  S4_21_48_11.mzXML
File 05  S4_21_48_12.mzXML
File 06  S4_21_48_13.mzXML

[MassCal_question.pptx](https://github.com/Nesvilab/FragPipe/files/7934816/MassCal_question.pptx)

Thank you for your time and support.
Sincerely,
Juan C.

**Comment by fcyu** [comment]
Hi Juan,

It requires at least 100 PSMs with `e-value < 0.005` and the ppm is smaller than the `precursor_true_tolerance`.

Best,

Fengchao
