### ISSUE TITLE
Philosopher Filter: out of memory

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/FragPipe#594]
Hi Fragpipe,

Im trying to do a Philosopher Filter command on a large (3348 bruker files) dataset. Im using quit the powerful machine on this, but I run into an error that states im out of memory. See attached the error log.
[ProteinProphet_31124.log](https://github.com/Nesvilab/FragPipe/files/7943862/ProteinProphet_31124.log)

See attached also a picture that tracks RAM of the HPC cluster I am using. It does not show any peak or anything telling me it hits maximum memory. I also checked and I have enough disk space.

![image](https://user-images.githubusercontent.com/56233030/151215400-4fa5926b-d2bf-4997-900d-acb63de6bd04.png)

Please let me know if you would like me to check anything else.

Also; im running this in an ubuntu container.

Best,
Patrick

**Comment by PatrickvanZalm** [comment]
Just a few more notes here:
1. The HPC node I am using here is 360GB ram.
2. Total size of all *.xml files is 43G, that of all .pepXML is 64G and the combined.prot.xml is 262MB.

Goal here is to create a DIA library. I know I could in theory split it up, but this would not be my preference since I want to build some standardized pipelines for our large-scale proteomics work.

I do notice that in a regular fragpipe run there seems to be conversion to .pin files? Im clueless what they really do, but could perhaps these be used and thus reduce memory usage?

Best,
Patrick

**Comment by guoci** [comment]
From the log, I can see that the OOM happened at the saving stage, which means that your RAM is a little below the required memory. I have recently optimized the `filter` command to significantly reduce memory usage, and it is currently being reviewed by @prvst, you might need to wait some time for him to publish a new version with my optimizations.

**Comment by PatrickvanZalm** [comment]
Hi Guoci,

thanks a ton for that work! If the two of you want it I would be more than happy to test it with such amounts of data with a beta version of some sort.

Cheers,
Patrick

**Comment by anesvi** [comment]
Hi Patrick,

Generally speaking, building huge spectral libraries is not necessarily the best idea.
Maybe you can provide some background why you want to combine so many mass spec runs?
Can email us directly.

Best,
Alexey

**Comment by PatrickvanZalm** [comment]
Hi Alexey,

Thanks for pointing it out. The samples are from plasma samples and we can identify many proteins using fragpipe in a usual LFQ type of run. We just want to see if usage of such amount of data can also lead to increased protein numbers in DIA samples we have from the same samples. To keep it systematic we just want to include all samples.

Best,
Patrick

**Comment by anesvi** [comment]
Guo Ci revised philosopher to reduce the memory usage.

Also, in pre-release of FragPipe we can share, if you are using Percolator change ‘Min probability; from default 0.5 to 0.9 or even higher, like 0.99 when really a lot of files. That will reduce the number of PSMs read by philosopher

So, with a  combination of new philosopher (we can probably share a test version) and increased minimum probability, maybe you can get it processed. Depends on how much RAM you have

Felipe, Guo Ci, Fengchao, should we send what we have to Patrick to test?

Thanks

Alexey

**Comment by fcyu** [comment]
Sure.

Hi Patrick,

Please find the pre-released FragPipe from https://www.dropbox.com/s/7t0rwzb22umh8yb/FragPipe-17.2-build16.zip?dl=1 .

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
Hi Fengchao,

Thanks for sending it along but to test it out I would need Philospher.

Best,
Patrick

**Comment by anesvi** [comment]
Felipe says philosopher fix still needs work… so have to wait a bit more

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guoci** [comment]
@PatrickvanZalm the memory usage issue should be resolved in the latest release, if you are interested.
https://github.com/Nesvilab/philosopher/releases/tag/v4.2.1
