### ISSUE TITLE
non-zero exit code for IonQuant => no LFQ results 

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/FragPipe#595]
[log_2022-02-03_16-21-07.txt](https://github.com/Nesvilab/FragPipe/files/7995093/log_2022-02-03_16-21-07.txt)

Hi everyone! 

I'm currently using FragPiPe with those specific versions:

Version info:

- FragPipe version 17.1
- MSFragger version 3.4
- Philosopher version 4.1.1 (build 1637179075)

I am using the LFQ workflow with 4 groups (6*4 = 24) on timsTOF Pro data (ddaPASEF files Bruker .d). I run the LFQ analysis in Quant (MS1) tab without changing any default parameters and I get an error message:

java.io.IOException: ������������ ����� �� �����
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
	at java.base/java.nio.channels.Channels$1.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.write(Unknown Source)
	at java.base/java.io.DataOutputStream.write(Unknown Source)
	at java.base/java.io.FilterOutputStream.write(Unknown Source)
	at r.a(Unknown Source)
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-02-02 00:30:07 [ERROR] - ������������ ����� �� �����
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

"combined_protein.tsv" does not contain any columns with MaxLFQ Intensity. 

Thank you, 

Ivan

**Comment by fcyu** [comment]
Hi Ivan,

Could you please tell me that the message of `������������ ����� �� �����` is in your computer? 

I guess something was wrong with your hard drive. Can you double check and try again? You can uncheck all steps except for IonQuant since other steps have finished successfully.

Best,

Fengchao

**Comment by ihorrible** [comment]
Hi Fengchao, 

I cannot read this either ������������ ����� �� �����
My hard drive is almost full, but anyway I have free 142 Gb. 

[log_2022-02-03_18-43-13.txt](https://github.com/Nesvilab/FragPipe/files/7996043/log_2022-02-03_18-43-13.txt)
I re-run Quant (MS-1) with unticking all other tabs and I have got a new immediate error: 

Percolator [Work dir: D:\data\VICS_vs_OST4\VIC_diff_213]
C:\Users\user\Desktop\fragpipe\tools\percolator-v3-05.exe --only-psms --no-terminate --post-processing-tdc --num-threads 47 --results-psms vic_213_dif_Slot1-35_1_2466_percolator_target_psms.tsv --decoy-results-psms vic_213_dif_Slot1-35_1_2466_percolator_decoy_psms.tsv vic_213_dif_Slot1-35_1_2466.pin
Process 'Percolator' finished, exit code: 1
Process returned non-zero exit code, stopping
Percolator version 3.05.0, Build Date May 18 2020 02:35:01
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
C:\Users\user\Desktop\fragpipe\tools\percolator-v3-05.exe --only-psms --no-terminate --post-processing-tdc --num-threads 47 --results-psms vic_213_dif_Slot1-35_1_2466_percolator_target_psms.tsv --decoy-results-psms vic_213_dif_Slot1-35_1_2466_percolator_decoy_psms.tsv vic_213_dif_Slot1-35_1_2466.pin
Started Thu Feb  3 18:43:13 2022
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile vic_213_dif_Slot1-35_1_2466.pin
ERROR: Cannot open data stream.
ERROR: Failed to read in file, check if the correct file-format was used.

~~~~~~~~~~~~~~~~~~~~
Cancelling 197 remaining tasks

Thank you,

Ivan

**Comment by guoci** [comment]
@ihorrible you can try to `Change system locale` to `English (United States)` before running FragPipe to get the error message to display properly. https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html

https://github.com/Nesvilab/FragPipe/issues/568#issuecomment-1002743321

**Comment by fcyu** [comment]
Hi Ivan,

You also have Percolator, ProteinProphet, FDR filter and report checked.....

Also, you need to make sure that all the files are still there for FragPipe to continue the process. If you are not sure, please go to a new folder and process everything from scratch.

Best,

Fengchao

**Comment by ihorrible** [comment]
> @ihorrible you can try to `Change system locale` to `English (United States)` before running FragPipe to get the error message to display properly. https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html
> 
> [#568 (comment)](https://github.com/Nesvilab/FragPipe/issues/568#issuecomment-1002743321)

done

**Comment by ihorrible** [comment]
> Hi Ivan,
> 
> You also have Percolator, ProteinProphet, FDR filter and report checked.....
> 
> Also, you need to make sure that all the files are still there for FragPipe to continue the process. If you are not sure, please go to a new folder and process everything from scratch.
> 
> Best,
> 
> Fengchao

Fengchao, now I unticked everything except for Quant (MS-1) and put all files in one folder. I still have an error: 

CheckCentroid
C:\Users\user\Desktop\fragpipe\jre\bin\java.exe -Xmx108G -cp "C:\Users\user\Desktop\fragpipe\lib\fragpipe-17.1.jar;C:\Users\user\Desktop\fragpipe\tools\batmass-io-1.23.6.jar" com.dmtavt.fragpipe.util.CheckCentroid D:\data\Ksyusha\project_DDA\ost_d11_cont_Slot1-41_1_2454.d 47
Done in 0 ms.
Process 'CheckCentroid' finished, exit code: 0
IonQuant [Work dir: D:\data\VICS_vs_OST]
C:\Users\user\Desktop\fragpipe\jre\bin\java.exe -Xmx108G -Dlibs.bruker.dir="C:\Users\user\Desktop\fragpipe\tools\MSFragger-3.4\ext\bruker" -Dlibs.thermo.dir="C:\Users\user\Desktop\fragpipe\tools\MSFragger-3.4\ext\thermo" -cp "C:\Users\user\Desktop\fragpipe\tools\ionquant-1.7.17.jar;C:\Users\user\Desktop\fragpipe\tools\smile-core-2.6.0.jar;C:\Users\user\Desktop\fragpipe\tools\smile-math-2.6.0.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\javacpp.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\javacpp-windows-x86_64.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\javacpp-linux-x86_64.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\openblas.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\openblas-windows-x86_64.jar;C:\Users\user\Desktop\fragpipe\tools\javacpp-presets-platform-1.5.6-bin\openblas-linux-x86_64.jar;C:\Users\user\Desktop\fragpipe\tools\batmass-io-1.23.6.jar" ionquant.IonQuant --threads 47 --ionmobility 1 --mbr 1 --maxlfq 1 --requantify 1 --mztol 10 --imtol 0.05 --rttol 0.5 --mbrmincorr 0 --mbrrttol 1 --mbrimtol 0.05 --mbrtoprun 100000 --ionfdr 0.01 --proteinfdr 1 --peptidefdr 1 --normalization 1 --minisotopes 1 --minscans 3 --writeindex 0 --tp 3 --minfreq 0.5 --minions 2 --minexps 1 --locprob 0.75 --multidir . --filelist D:\data\VICS_vs_OST\filelist_ionquant.txt
Process 'IonQuant' finished, exit code: 1
IonQuant version IonQuant-1.7.17
Batmass-IO version 1.23.6
timsdata library version timsdata-2-8-7-1
(c) University of Michigan
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 108 GB memory
2022-02-03 20:07:30 [ERROR] - Cannot read file D:\data\VICS_vs_OST\Ost_cont_11\ost_d11_cont_Slot1-41_1_2454.pepXML.
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

What is the reason he could not read this file?

**Comment by ihorrible** [comment]
These files were also successfuly processed in Training Peaks Pro.

**Comment by fcyu** [comment]
> 2022-02-03 20:07:30 [ERROR] - Cannot read file D:\data\VICS_vs_OST\Ost_cont_11\ost_d11_cont_Slot1-41_1_2454.pepXML.

Clearly, not all files are available now. I suggest you create a new folder, load the LFQ-MBR workflow, and process everything from scratch.

Best,

Fengcho

**Comment by ihorrible** [comment]
> > 2022-02-03 20:07:30 [ERROR] - Cannot read file D:\data\VICS_vs_OST\Ost_cont_11\ost_d11_cont_Slot1-41_1_2454.pepXML.
> 
> Clearly, not all files are available now. I suggest you create a new folder, load the LFQ-MBR workflow, and process everything from scratch.
> 
> Best,
> 
> Fengchao

the folder is empty 
![empty](https://user-images.githubusercontent.com/63013549/152395572-947ff174-4df0-44b9-9973-16f56f709ae7.PNG)

**Comment by fcyu** [comment]
That is why IonQuant cannot find the file. Please re-analysis everything from scratch.

**Comment by ihorrible** [comment]
I feel so dumb. I did not choose the correct workflow on the workflow tab and even when I selected it correctly I did not press LOAD button to make changes. Now it seems good and working ... Thank you very much !!!!

**Comment by fcyu** [comment]
You are welcome.

**Comment by ihorrible** [comment]
[log_2022-02-04_02-53-09.txt](https://github.com/Nesvilab/FragPipe/files/8000752/log_2022-02-04_02-53-09.txt)

Unfortunately, I have the same error and Change system locale to English (United States) did not help to deal with ???:

java.io.IOException: ???????????? ????? ?? ?????
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.base/java.nio.channels.Channels.writeFully(Unknown Source)
	at java.base/java.nio.channels.Channels$1.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.write(Unknown Source)
	at java.base/java.io.DataOutputStream.writeInt(Unknown Source)
	at r.a(Unknown Source)
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-02-04 02:53:02 [ERROR] - ???????????? ????? ?? ?????
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

**Comment by fcyu** [comment]
Please make sure that your disk have enough space.

We only answer questions about our tools. Please ask your IT department regarding your operating system language setting.

Best,

Fengchao

**Comment by ihorrible** [comment]
It's finally works at another computer!!! So, the problem really is in having enough space at hard drive. Thank you very much !!!
