### ISSUE TITLE
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found

### ISSUE THREAD

**Issue by giorgiolivi** [Nesvilab/FragPipe#596]
**Describe the bug**

output failed : Batmass-IO binaries for Thermo support and/or Thermo native libraries not found
Failed in checking spectral files.
Process returned non-zero exit code, stopping

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.
[log_2022-02-03_17-23-40.txt](https://github.com/Nesvilab/FragPipe/files/7996836/log_2022-02-03_17-23-40.txt)

**Comment by fcyu** [comment]
Do you have the `ext` folder sitting next to the `MSFragger-3.4.jar`?

Best,

Fengchao

**Comment by giorgiolivi** [comment]
Hi Fengchao,
Raw files folder saved on the desktop and the
Result folder as well.
Fragpipe folders are saved on c drive .
Best ,
Giorgio

**Comment by fcyu** [comment]
Hi Giorgio,

Can you open a command line window, run `C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-16.1-build16\fragpipe\tools\MSFragger-3.4\ext\thermo\BatmassIoThermoServer.exe`, and send me the screenshot of the output?

Thanks,

Fengchao

**Comment by giorgiolivi** [comment]
![image](https://user-images.githubusercontent.com/77282827/152505801-30a40c31-dc91-45f6-8e4d-6da23b9ab07a.png)

Hi Fengchao, 

somehow it open the previus version 16.


[log_2022-02-04_09-31-23_error.txt](https://github.com/Nesvilab/FragPipe/files/8001648/log_2022-02-04_09-31-23_error.txt)

![Capture_error](https://user-images.githubusercontent.com/77282827/152506017-b6951266-3d41-43ad-a485-957eb01b0b89.JPG)

thanks,
Giorgio

**Comment by fcyu** [comment]
Hi Giorgio,

Your first log do show that you are using the MSFragger-3.4 located in FragPipe 16:
```
java -jar -Dfile.encoding=UTF-8 -Xmx14G C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-16.1-build16\fragpipe\tools\MSFragger-3.4\MSFragger-3.4.jar C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test_result\fragger.params C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_HHEX-KO_IgG.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_HHEX-KO_1.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_HHEX-KO_2.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_HHEX-KO_3.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_WT_1.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_WT_2.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_WT_3.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_WT_IgG_1.raw C:\Users\giorgio.DESKTOP-OR8T69I\Desktop\simone_test\20220125_Simone_Dapeng_PP2_WT_IgG_2.raw
```

However, the command I gave you is to start batmass-io server. It has nothing to do with FragPipe.....

Could you open cmd.exe in your windows and run the command `C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-16.1-build16\fragpipe\tools\MSFragger-3.4\ext\thermo\BatmassIoThermoServer.exe`?

Best,

Fengchao

> Hi Giorgio,
> 
> Can you open a command line window, run `C:\Users\giorgio.DESKTOP-OR8T69I\Downloads\FragPipe-jre-16.1-build16\fragpipe\tools\MSFragger-3.4\ext\thermo\BatmassIoThermoServer.exe`, and send me the screenshot of the output?
> 
> Thanks,
> 
> Fengchao

**Comment by giorgiolivi** [comment]
Hi Fengchao,

So basically. I hope I've sorted out my problems:
here 2 screenshots how to solve them:
1-convert properly the RAW files, in mzML and include centroide.
[image: image.png]

import Ms fragger and philosopher in the correct last version
[image: image.png]

At the moment the search is running without any problem.
Thanks
giorgio

**Comment by fcyu** [comment]
Hi Giorgio,

I cannot find the screenshot. But since you already figured out a way by converting raw files to mzML, I think there is no problem now.

Best,

Fengchao
