### ISSUE TITLE
mbr_ion file doesn't is not including all of the input files

### ISSUE THREAD

**Issue by daishavdw** [Nesvilab/FragPipe#597]
I am running 6 files through MsFragger and enabling MBR. The program runs without errors, and when I look at the log, MBR is happening for all of them. When I pull up the mbr_ion.tsv, only 3 of the files are present in the 'acceptor_run_name' column. The results for the other 3 files never appear in the mbr_ion.tsv. Why does it appear that MBR is not happening for 3 of my files? 

The files input into MsFragger were the six 2ng file found in the MassIVE dataset MSV000087524. 

Attached is the log file, parameter file, and mbr_ion.csv in case you would like to look at them. 

Thank you.

[log_2022-01-19_12-23-34.txt](https://github.com/Nesvilab/MSFragger/files/8005007/log_2022-01-19_12-23-34.txt)
[fragger_params.pdf](https://github.com/Nesvilab/MSFragger/files/8005057/fragger_params.pdf)
[mbr_ion.csv](https://github.com/Nesvilab/MSFragger/files/8005062/mbr_ion.csv)

**Comment by fcyu** [comment]
The `mbr_ion` file is FDR filtered. I guess some of the runs don't have any transferred ion passing the FDR.

Also, the `mbr_ion` file is a intermediate file which is not supposed to be used as a result file.

Best,

Fengchao
