### ISSUE TITLE
Spectral library unknown error

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/FragPipe#598]
Hi everyone! 

Version info:

FragPipe version 17.1
MSFragger version 3.4
Philosopher version 4.1.1 (build 1637179075)

I am trying to generate a spectral library for DDA based on d.files from Bruker Tims TOF: 

- first time I run as a user and I have error access denied (see file attached);
- second time I run MS Fragger as an administrator and I have an unknown error (see file attached). 

Traceback (most recent call last):
  File "C:\Users\iataraskin\Desktop\Projects\MIPT\Thesis\FragPipe-jre-17.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 965, in <module>
    main_easypqp()
  File "C:\Users\iataraskin\Desktop\Projects\MIPT\Thesis\FragPipe-jre-17.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 768, in main_easypqp
    subprocess.run([os.fspath(easypqp), '--version'], check=True)
  File "C:\Users\iataraskin\Anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\iataraskin\\Anaconda3\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2 remaining tasks


I have selected a default workflow on a workflow tab. It seems to me like a problem with easypqp library installed in python, but everything looks OK on a config tab where it shows that easypqp 0.1.26 and no problem (see also file attached)
![ok](https://user-images.githubusercontent.com/63013549/152727067-5fd75c30-ff40-4596-9695-eaba6201f10c.PNG)
. 

Could please help me with this error and what should I change in order to fix it? 

Thanks,

Ivan 

![permission error](https://user-images.githubusercontent.com/63013549/152726710-8a67098a-2515-4503-acd0-254b2517bd42.PNG)
![unknown errror_spectral library](https://user-images.githubusercontent.com/63013549/152726713-918d11f5-193a-468b-bd92-375befe3811f.PNG)


[log_2022-02-07_07-47-33.txt](https://github.com/Nesvilab/FragPipe/files/8012408/log_2022-02-07_07-47-33.txt)
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by guoci** [comment]
@ihorrible Can you run the following command line and show me the output?
`C:\Users\iataraskin\Anaconda3\Scripts\easypqp.exe --version`

**Comment by ihorrible** [comment]
> @ihorrible Can you run the following command line and show me the output? `C:\Users\iataraskin\Anaconda3\Scripts\easypqp.exe --version`

![Снимок](https://user-images.githubusercontent.com/63013549/152935983-8e52bca8-f0a6-4f9e-90c0-1050da358c12.PNG)
![Снимок2](https://user-images.githubusercontent.com/63013549/152935988-f683316d-4f1d-42d6-895d-8256cbfe1f17.PNG)

It is stated that access is denied. Any guess what I should do to unblock this?

**Comment by guoci** [comment]
@ihorrible can you click on the `"Install/Upgrade EasyPQP` and try again?

**Comment by ihorrible** [comment]
the problem was with access rights on my laptop. now everything works OK. thank you !
