### ISSUE TITLE
diaPASEF data is not supported at this time 

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/FragPipe#601]
Hi everyone ! 

It is stated in MS Fragger tutorial that diaPASEF data is not supported (https://fragpipe.nesvilab.org/docs/tutorial_DIA.html)
But at the same time, there is an article where MS Fragger is used with diaPASEF data analysis (https://www.biorxiv.org/content/10.1101/2021.03.08.434385v1.full)

What are the consequences and restrictions of using MS Fragger with diaPASEF data? 
When the official support of diaPASEF data will be announced? 

Thanks,

Ivan

**Comment by fcyu** [comment]
If you read the biorxiv paper carefully, you would find that we use ddaPASEF to build spectral libraries, and using DIA-NN to do the quantification.

> What are the consequences and restrictions of using MS Fragger with diaPASEF data?

MSFragger just doesn't support it.

> When the official support of diaPASEF data will be announced?

I don't know.

Best,

Fengchao
