### ISSUE TITLE
mzML seems from DIA but MSFragger is in DDA mode

### ISSUE THREAD

**Issue by MSomics** [Nesvilab/FragPipe#604]
I tried to analyze my peptidomics data (no enzymatic digestion during sample prep) after converting the .d file from Bruker TOF MS (Impact HD)  to mzML/mzXML using MSconvert module of Proteowizard (PeakPicking using CWT). The workflow module correctly identifies the data acquisition mode i.e. DDA, however, the task is later cancelled with an error "mzML seems from DIA but MSFragger is in DDA mode".

Could you please let me know the reason behind this error and how to avoid it? Thanks.

----------------------
[log_2022-02-15_17-10-04.txt](https://github.com/Nesvilab/FragPipe/files/8075375/log_2022-02-15_17-10-04.txt)

**Comment by fcyu** [comment]
It looks like the isolation window is larger than 4 Th. Can you confirm that? 

Also, we suggest you analyze the ddaPASEF using the raw `.d`. If you want to convert it to mzML format, please follow the tutorial here (https://fragpipe.nesvilab.org/docs/tutorial_convert.html).

Best,

Fengchao

**Comment by MSomics** [comment]
Hi,

Thanks a lot for the suggestion.  **The isolation width is indeed  >4 Da**.  In this situation, can I still go ahead with DDA analysis?

Initially I started with raw .d data files, however, it returned following error, so I tried file conversion.  (Log attached for more details)

--------------------------------------------------------------------------------------
Failed in checking D:\Fragpipe\SampleFile\SPE_ser_2X_R1_BB1_1_1778_Copy.d
Not a valid pathDir for Bruker data directory
Failed in checking spectral files.
--------------------------------------------------------------------------------------
[log_2022-02-15_19-43-04.txt](https://github.com/Nesvilab/FragPipe/files/8076028/log_2022-02-15_19-43-04.txt)

**Comment by anesvi** [comment]
Just curious, why > 4Da in DDA mode?
Alexey

**Comment by MSomics** [comment]
@anesvi .. Thanks, I checked with my colleague only after @fcyu inquired about it. It looks like they used default values for isolation width. This is study is in initial phase and they are trying to optimize the parameters. Thanks again @fcyu for highlighting that.

@fcyu .. What should be the enzyme parameters under section "protein digestion" if endogenous peptides were to be searched? Thanks.

**Comment by fcyu** [comment]
FragPipe will generate an appropriate `fragger.params` file with the following enzyme settings:
```
search_enzyme_name_1 = nonspecific			# Name of the first enzyme.
search_enzyme_cut_1 = -			# First enzyme's cutting amino acid.
search_enzyme_nocut_1 = 			# First enzyme's protecting amino acid.
search_enzyme_sense_1 = C			# First enzyme's cutting terminal.
allowed_missed_cleavage_1 = 2			# First enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.

search_enzyme_name_2 = null			# Name of the second enzyme.
search_enzyme_cut_2 = -			# Second enzyme's cutting amino acid.
search_enzyme_nocut_2 = 			# Second enzyme's protecting amino acid.
search_enzyme_sense_2 = C			# Second enzyme's cutting terminal.
allowed_missed_cleavage_2 = 2			# Second enzyme's allowed number of missed cleavages per peptide. Maximum value is 5.

num_enzyme_termini = 0			# 0 for non-enzymatic, 1 for semi-enzymatic, and 2 for fully-enzymatic.
```

Your log shows that your `fragger.params` has the old format which is not generated by FragPipe 17.1. That is why I suggest you delete your FragPipe and download again from scratch.

Best,

Fengchao

**Comment by MSomics** [comment]
@fcyu .. Thank you for sharing the parameters. I have downloaded all the tools again.

**Comment by fcyu** [comment]
Hi Jaran,

I believe that in the latest version (MSFragger 3.5), this issue has been fixed. 

You will only see this warning when your isolation window is larger than 8 Th, which is OK for now. We might remove this threshold in the future release.

Best,

Fengchao

**Comment by jjnbdal** [comment]
> Hi Jaran,
> 
> I believe that in the latest version (MSFragger 3.5), this issue has been fixed.
> 
> You will only see this warning when your isolation window is larger than 8 Th, which is OK for now. We might remove this threshold in the future release.
> 
> Best,
> 
> Fengchao

Dear Fengchao,

Thank you. Will give version 3.5 a try now.

Thank you.
Jaran
