### ISSUE TITLE
Can I specify where Philosopher creates directories instead on /tmp?

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/FragPipe#605]
Hi Fragpipe,

I noticed that philosopher does create directories when running items such as peptideprophet:
![image](https://user-images.githubusercontent.com/56233030/154234918-ebb3ff89-9fce-4b61-8780-ea6ed6c17fa2.png)

Is there anyway to specify where such files/directories would be written? 

Best,
Patrick

**Comment by prvst** [comment]
Hi @PatrickvanZalm . The workspace command has a flag called `--temp` that you can use to designate the place for the temporary files.

**Comment by PatrickvanZalm** [comment]
Thanks Felipe!! I was not aware of that.

**Comment by PatrickvanZalm** [comment]
While this fixes one of my issues, I wonder if I could also specify such a directory for, for example, peptideprophet?

**Comment by prvst** [comment]
that's for everything that philosopher manages, including the prophets.
