### ISSUE TITLE
java.lang.NumberFormatException: MSBooster

### ISSUE THREAD

**Issue by andrewjmc** [Nesvilab/FragPipe#607]
**Describe the bug**
Running two RAW files in closed searches with MSBooster enabled (Fragpipe v17.1, MS Windows), we get to "generating edited pin" and "loading predicted spectra" but when loading a converted MGF I receive a number format exception because the string '2 File:"[filename]"' is being converted to an integer.

I'll run without MSBooster for the moment, but interested if there's an easy/obvious fix.

Thanks!

Andrew

----------------------
## If you're submitting a bug report, please attach log file

[log_edited.txt](https://github.com/Nesvilab/FragPipe/files/8097280/log_edited.txt)

**Comment by andrewjmc** [comment]
Strange thing is they are not MGF files but RAW files. One of the files does have a similarly named MGF in the directory - so I moved it. It worked! It looks like it might be inadvertently using the MGF at a given step even though I only added the RAW files. Is this possible?

**Comment by fcyu** [comment]
Hi @yangkl96 ,

I think I might know the reason. In the log file, there is `Loading File_2.mgf`. But given raw files, MSBooster should look for `<run name>_uncalibrated.mgf`, not `<run name>.mgf`.

Best,

Fengchao

**Comment by yangkl96** [comment]
Ah yes this makes sense. MSBooster is supposed to use the uncalibrated.mgf made from the RAW file, but it read the regular mgf instead. @andrewjmc , can you confirm that the log file from the run where it worked successfully says `Loading File_2_uncalibrated.mgf` instead?

Thanks for the catch, @fcyu

**Comment by andrewjmc** [comment]
Yes, it does. Apols for the delay!
