### ISSUE TITLE
A separate folder for temporary files

### ISSUE THREAD

**Issue by I-Beer** [Nesvilab/FragPipe#61]
It would be nice to separate the index files and other temporary files from the data files by allowing the user to specify a folder for this purpose.

**Comment by chhh** [comment]
@I-Beer Which temporary files?
Index files, IIRC, are generated in the same location as the fasta file, so they could be reused for later analyses (with same digestion parameters).

**Comment by I-Beer** [comment]
In the manual it is written that .fragtmp files are in the directory of the MS/MS files.
They are deleted later but I prefer that tools will not change my data repository.

**Comment by chhh** [comment]
@I-Beer We'll try to accommodate this in the next release, looks to be easy to implement.
However there might be some difficulties with name clashes if multiple input files from different directories share the same name.

**Comment by chhh** [comment]
This will be available with the latest Fragger
