### ISSUE TITLE
Illegal interval left<right in checking Eclipse TMT data

### ISSUE THREAD

**Issue by SC0O8Y** [Nesvilab/FragPipe#612]
![image](https://user-images.githubusercontent.com/29248208/156067078-040d7f49-4fc2-4bac-96b2-2cf11b4d6ed1.png)

TMT data failing to parse and resulting in 0 scans. 

This is an eclipse running with no FAIMS in a RTS-TMT-SPS-MS3 method with a close out of 10 peptides per protein. 

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
[log_2022-02-28_16-56-26.txt](https://github.com/Nesvilab/FragPipe/files/8157245/log_2022-02-28_16-56-26.txt)

- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Thanks for your report. Could you please send one of your raw files to us to troubleshot the problem?

Thanks,

Fengchao

**Comment by fcyu** [comment]
No response.

**Comment by SC0O8Y** [comment]
Oh  my sorry, got swamped by other work

**Comment by SC0O8Y** [comment]
https://drive.google.com/file/d/1bQUJulALk3-CEo9Hh50-HeC3iXaAVYsm/view?usp=sharing

Here is another file that is reporting same error.

**Comment by fcyu** [comment]
Thank you for your file. I will investigate and get back to you ASAP.

Best,

Fengchao

**Comment by SC0O8Y** [comment]
Cheers Fenchao,
My sincerest apologies on the lag

**Comment by fcyu** [comment]
Hi @SC0O8Y ,

The bug has been fixed. If you want to have a try, please contact me by email. I will send you a pre-release version of MSFragger.

Best,

Fengchao

**Comment by SC0O8Y** [comment]
Hi @fcyu 

Just wondering where the issue was?

Is this the same version that you sent to us for LFQ analyst?

Kind regards 
Joel

**Comment by fcyu** [comment]
Hi Joel,

The bug is from parsing the raw file in MSFragger. The link I sent to your for LFQ analysis is for FragPipe. If you want the new MSFragger, please feel free to let me know.

Best,

Fengchao
