### ISSUE TITLE
Error and questions with DIA tutorial

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#614]
Hi,
I have been trying to follow the DIA tutorial on the FragPipe page (https://fragpipe.nesvilab.org/docs/tutorial_DIA.html) to verify my installation and parameters are setup correctly (FragPipe 17.1). I have all Python/EasyPQP requirements "available" according to FP.  I downloaded the abbreviated dataset from the Dropbox (2 DDA and 2 DIA files). I loaded the dia_speclib_quant workflow, the four files, and the database provided.
![image](https://user-images.githubusercontent.com/42681821/156802733-2c9ae078-e31b-4c68-99c4-21d175133252.png)

The only setting I changed was in EasyPQP to specify iRT as suggested in the tutorial.

The analysis does not finish successfully and exits with the error code below (I have attached my complete log file for reference). I also get this message if I set DIA files to "DIA-Quant", and if I run a standard closed search of the DDA data with spec lib generation.  I have tried to uninstall Python and then reinstall it and EasyPQP, but the error code remains. I have the most recent EasyPQP version 0.1.27 installed.

In addition to this issue, going through the tutorial has generated a few questions. 

1) I assume that labeling the DIA data as "DIA" instead of "DIA Quant" means that DIA data (in addition to the DDA data) will be included in the spectral library creation process?  

2) If I leave all Experiment labels blank in the Workflow and one spectral library is generated, when it is time for DIA-NN to quantify the results, will the quantification analysis report two DIA runs separately or will a combined quantitative value be generated?

3) In contrast, if I label the Experiment fields for all the runs to generate multiple spectral libraries, how are the libraries handled as they are passed to DIA-NN?  Will a unified spectral library be generated?

Thanks in advance for your assistance
Todd   

**Error code:**
SpecLibGen [Work dir: D:\Data\DIA_testing\DIA_FP_tut\libDIA]
C:\Python39\python.exe -u C:\Fragpipe17_1\tools\speclib\gen_con_spec_lib.py D:\Data\DIA_testing\DIA_FP_tut\2021-05-13-decoys-UPS-reviewed-contam-UP000000589.fas D:\Data\DIA_testing\DIA_FP_tut\libDIA unused D:\Data\DIA_testing\DIA_FP_tut\libDIA True unused use_easypqp iRT;noIM 15 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.0" keep_intermediate_files D:\Data\DIA_testing\DIA_FP_tut\libDIA\filelist_speclibgen.txt
File list provided
Traceback (most recent call last):
  File "C:\Fragpipe17_1\tools\speclib\gen_con_spec_lib.py", line 253, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
  File "C:\Fragpipe17_1\tools\speclib\gen_con_spec_lib.py", line 143, in get_bin_path_pip_CLI
    files = [location / e[2:] for e in a.search(stdout).group().splitlines()[1:]]
AttributeError: 'NoneType' object has no attribute 'group'
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2022-03-04_10-14-57.txt](https://github.com/Nesvilab/FragPipe/files/8187330/log_2022-03-04_10-14-57.txt)

**Comment by fcyu** [comment]
Hi Todd,

The following are my point-to-point answers to  your questions.

> I assume that labeling the DIA data as "DIA" instead of "DIA Quant" means that DIA data (in addition to the DDA data) will be included in the spectral library creation process?

Yes, you are correct.

> If I leave all Experiment labels blank in the Workflow and one spectral library is generated, when it is time for DIA-NN to quantify the results, will the quantification analysis report two DIA runs separately or will a combined quantitative value be generated?

Two DIA runs' intensities will be reported in separated columns from DIA-NN's report.

> In contrast, if I label the Experiment fields for all the runs to generate multiple spectral libraries, how are the libraries handled as they are passed to DIA-NN? Will a unified spectral library be generated?

Runs in the same experiment use the spectral library from that experiment. There will be DIA-NN's report in each experiment folder.

As to the error, @guoci can you take a look when you have time?

Thanks,

Fengchao

**Comment by enonimos** [comment]
Thanks Fengchao for your quick responses, very helpful.

**Comment by guoci** [comment]
@enonimos Did you install easyPQP?
In your command prompt, can you run the following and show me the output?
`C:\Python39\python.exe  -m pip show --files easypqp`

**Comment by enonimos** [comment]
I installed easyPQP through the Config page script.
![image](https://user-images.githubusercontent.com/42681821/156901538-e04c6f64-f847-4c7a-9163-a480283c4308.png)


**This is the output from the command:**
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Name: easypqp
Version: 0.1.27
Summary: EasyPQP: Simple library generation for OpenSWATH
Home-page: https://github.com/grosenberger/easypqp
Author: George Rosenberger
Author-email: gr2578@cumc.columbia.edu
License: UNKNOWN
Location: c:\python39\lib\site-packages
Requires: Click, numpy, scipy, scikit-learn, statsmodels, pandas, biopython, pyopenms, matplotlib, seaborn
Required-by:
Files:
Cannot locate RECORD or installed-files.txt

**Comment by guoci** [comment]
@enonimos can you try clicking on the `Install/Upgrade EasyPQP` button again and then rerun the command?

**Comment by enonimos** [comment]
@guoci I clicked on the button but didn't see any response/message (not sure if that is expected or not).  Re-running the command gives the same response as above.

**Comment by guoci** [comment]
@enonimos The installation is probably broken. Can you do the following and show me the output?
```
C:\Python39\python.exe -m pip uninstall easypqp
C:\Python39\python.exe -m pip uninstall pyopenms
C:\Python39\python.exe -m pip install easypqp
C:\Python39\python.exe -m pip show --files easypqp
```
If there are still errors after this, then try installing Anaconda Python.
https://www.anaconda.com/products/individual

**Comment by enonimos** [comment]
@guoci Thank you for the suggestions and troubleshooting. I was able to resolve the issue!  When you said broken installation, I looked in my python package folder and found an incomplete/corrupt upgrade of pip. So any package I tried to install was only partially complete. After deleting these folders, re-installing pip, then EasyPQP, I was able to run the searches to completion.
