### ISSUE TITLE
Plant proteins not appearing in output files

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#616]
**Describe the bug**
I have used MSFragger to analyse proteomics data from Arabidopsis before, but when I tried with the latest version of MSFragger (in the FragPipe wrapper), it did not return any Arabidopsis protein IDs. I only got IDs for trypsin and some proteins from humans. I don't remember changing any settings from when it has worked previously.

----------------------
## If you're submitting a bug report, please attach log file
[log_2022-03-07_12-58-04.txt](https://github.com/Nesvilab/FragPipe/files/8194943/log_2022-03-07_12-58-04.txt)

Log file is attached.

**Comment by fcyu** [comment]
It might because Philosopher cannot recognize the protein header in the fasta file. 

Felipe @prvst , can you take a look when you have time?

Thanks,

Fengchao

**Comment by ndtivendale** [comment]
Yes.

**Comment by prvst** [comment]
Can you share the database with me? I'll include rules for parsing TAIR sequences. While it's not ready, I suggest you try again using sequences from NCBI.

**Comment by ndtivendale** [comment]
I can't seem to share the FASTA file. I guess I could email it to you, right?

**Comment by ndtivendale** [comment]
Link to fasta file. [?txt icon]  athal.fasta.txt<https://uniwa-my.sharepoint.com/:t:/g/personal/00102016_uwa_edu_au/EePdff4rRyxNsl6fbZO80UIB8g2vcKQWb-xAbuVJT_KSHA?email=reply%2BANAVB3ZHDN57H7GGTSK4IEOAGPXWTEVBNHHEKMQQIQ%40reply.github.com&e=PWIeu7>

**Comment by ndtivendale** [comment]
I have shared the FASTA file with you via email. Hopefully that worked.

**Comment by ndtivendale** [comment]
a { color: #0072bc; text-decoration: none; }






    
    
    
    
    Time of Access


  Time of Access v2
  
  
  

table td {border-collapse:collapse;margin:0;padding:0;}










 











 


 








 
 
 


 
Hello,


 
For security purposes, you must enter the code below to verify your account to access athal.fasta.txt. The code will only work for 15 minutes and if you request a new code, this code will stop working.


 




Account verification code:


32384089






 
Having problems with the code?


 
View the error and make sure that the email identifier is "86XG1XC". If it's not, look for an updated email or try requesting a new code.








 


 

© 2017 Microsoft   Privacy & Cookies

**Comment by prvst** [comment]
Got it. I'll work on the format and include a new rule for the next version.

**Comment by fcyu** [comment]
> Got it. I'll work on the format and include a new rule for the next version.

@prvst Have you added the format to the Philosopher 4.6.0?

Best,

Fengchao

**Comment by prvst** [comment]
added
