### ISSUE TITLE
mzxml extension not recognized

### ISSUE THREAD

**Issue by I-Beer** [Nesvilab/FragPipe#62]
If it is mzxml rather than mzXML, the following error message is displayed:

seq46812_qe2.mzxml Unsupported file format: seq46812_qe2.mzxml0ms

In windows filenames are case insensitive.

**Comment by I-Beer** [comment]
Update: the file name can be .mzxml as long as the name in the fragger command line is .mzXML.

**Comment by chhh** [comment]
@prvst I can't move this issue to MSFragger repo, it belongs there

**Comment by chhh** [comment]
I believe this was fixed a few versions of MSFragger ago.
