### ISSUE TITLE
Error creating Spec Library with DIA-GFP data

### ISSUE THREAD

**Issue by tomvaiuw** [Nesvilab/FragPipe#620]
I am searching DIA GFP data and want to generate spectral library at the end. The search itself works fine but at the end I get error from SpeLibGen
SpecLibGen [Work dir: F:\Tomas\HDL\S119\ChromLib_DIA1]
C:\Python36\python -u C:\Bin\fragpipe\tools\speclib\gen_con_spec_lib.py F:\Databases\Fragpipe_dbases\2022-03-03-decoys-reviewed-contam-UP000005640.fas F:\Tomas\HDL\S119\ChromLib_DIA1 unused F:\Tomas\HDL\S119\ChromLib_DIA1 True unused use_easypqp noiRT;noIM 11 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.01" delete_intermediate_files F:\Tomas\HDL\S119\ChromLib_DIA1\filelist_speclibgen.txt
Traceback (most recent call last):
  File "C:\Bin\fragpipe\tools\speclib\gen_con_spec_lib.py", line 253, in <module>
    easypqp = get_bin_path('easypqp', 'easypqp')
  File "C:\Bin\fragpipe\tools\speclib\gen_con_spec_lib.py", line 139, in get_bin_path_pip_CLI
    check=True).stdout
  File "C:\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
File list provided
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

I am also attaching corresponding Log from the failed run. (I also ran it with DIA-GFP as data type and got the same error).
Any advice on the reasons for the failure would be greatly appreciated.

Tomas

[log_2022-03-08_11-39-50.txt](https://github.com/Nesvilab/FragPipe/files/8209194/log_2022-03-08_11-39-50.txt)

**Comment by guoci** [comment]
Your Python version is too old.
Please use a recent version of Anaconda Python https://www.anaconda.com/products/individual

**Comment by tomvaiuw** [comment]
Thanks. So this means Fragpipe does not run on Windows 7 since it appears python 3.9 does not?

Thanks,
Tomas
________________________________

**Comment by guoci** [comment]
@tomvaiuw Do you mean you cannot install Anaconda on Windows 7?

**Comment by tomvaiuw** [comment]
I could not. Got error during installation. Then I checked python.org directly and 3.9 is said not to work on Win 7. 3.8 is latest. I installed it and all packages and got the error from Fragpipe again.

Tomas


Excuse typos, writing from a smart phone.

________________________________

**Comment by guoci** [comment]
@tomvaiuw Can you post the log when you run with Python 3.8?

**Comment by tomvaiuw** [comment]
Should be attached here.

Tomas
________________________________

**Comment by guoci** [comment]
@tomvaiuw the log is truncated, you need to post it as a file just as you did the first time

**Comment by tomvaiuw** [comment]
Sorry attached it as a file to the email so I thought it would work.
Will do through github when I get to the lab,
Thanks,
Tomas


Excuse typos, writing from a smart phone.

________________________________

**Comment by tomvaiuw** [comment]
Here it the log file with the python 3.
[log_2022-03-08_16-04-23.txt](https://github.com/Nesvilab/FragPipe/files/8225963/log_2022-03-08_16-04-23.txt)
8

**Comment by tomvaiuw** [comment]
Sorry - that was mistake.
Tomas

**Comment by guoci** [comment]
@tomvaiuw This error should be easy to fix. Please do the following and rerun.
`C:\Python38\python.exe -m pip install lxml`

**Comment by fcyu** [comment]
Hi @guoci , can you put the `lxml` to the dependency list when install easypqp? 

Thanks,

Fengchao

**Comment by guoci** [comment]
@fcyu done at https://github.com/Nesvilab/FragPipe/commit/1a595f984558692b45150f93209d901cd1703ec7

**Comment by guoci** [comment]
@tomvaiuw if there are still issues, try installing the last Anaconda available for Windows 7, version `2020.02` https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe

**Comment by tomvaiuw** [comment]
Thanks – it worked after the lxml install.

Tomas
