### ISSUE TITLE
Panic runtime error in PhilosopherDbAnnotate

### ISSUE THREAD

**Issue by gigi-mt** [Nesvilab/FragPipe#622]
Dear FragPipe team.
I am re-running an analysis of two TMT11plex sets on FragPipe, same parameter as before, just with a custom made FASTA, decoys were added using FragPipe. 
MSFragger, Percolator and ProteinProphet are executed without warnings or errors. 
There is, however, a problem with Philosopher. 
I had received a warning for philosopher.exe about .meta\meta.bin not being found, and the dbannotate step is being aborted giving a panic: runtime error: index out of range [2] with length 0.  

I am using the latest Philosopher version and emptied the FragPipe cache but I still receive the same error. 
Does it have to do with the FASTA file? 

Here is the log report. 
[log_2022-03-14_08-12-29.txt](https://github.com/Nesvilab/FragPipe/files/8244766/log_2022-03-14_08-12-29.txt)

Thanks for your help,
G

**Comment by prvst** [comment]
Also, please send me your database file, I want to take a look at it

**Comment by prvst** [comment]
@gigi-mt I don't accept files sent to my personal email, please upload your file here (https://www.dropbox.com/request/T4wVIVH43OjS6du48TEK)

**Comment by prvst** [comment]
Can you tell me how you came across to this database file? The Uniprot headers are changed in a way that the program cannot understand them.

**Comment by gigi-mt** [comment]
It is a canonical FASTA downloaded from UniProt and contains experimental sequences of mutated proteins written in the regular FASTA format. To distinguish between mutated and canonical proteins, the mutated UniProt accession contains the amino acid change.
Decoy sequences were added using FragPipe, and make up 50% of the FASTA file.

The database works well with other proteomics tools.

**Comment by gigi-mt** [comment]
I made the changes to the FASTA as recommended and ran the workflow again with the same error. 
I had also tried a FASTA downloaded in FragPipe, and get the same error. 

[log_2022-03-14_16-15-53.txt](https://github.com/Nesvilab/FragPipe/files/8248289/log_2022-03-14_16-15-53.txt)

**Comment by prvst** [comment]
A FASTA file downloaded from UniProt should not give any issues, we use them routinely. Which organism did you fetch?

**Comment by gigi-mt** [comment]
Homo sapiens. See attached.

[2022-03-14-decoys-reviewed-contam-UP000005640.zip](https://github.com/Nesvilab/FragPipe/files/8256766/2022-03-14-decoys-reviewed-contam-UP000005640.zip)

**Comment by prvst** [comment]
According to your most recent log, you used 2022-03-14-decoys-2022_0314_Canonical_WES_FASTA.fasta.fas

**Comment by gigi-mt** [comment]
Yes, that is correct. As I mentioned, after the corrected custom FASTA (2022-03-14-decoys-2022_0314_Canonical_WES_FASTA.fasta.fas) failed again , I ran the human UniProt FASTA fetched from FragPipe receiving the same error as with my custom FASTA.

I can share the the custom FASTA with you or any other file of this search if this helps figuring out the cause.

Thanks.

**Comment by gigi-mt** [comment]
Reinstalling FragPipe and it's components for the third time did the trick. UniProt human DB and my custom DB ran without a problem. 
Thanks for your support fixing this.
