### ISSUE TITLE
Wish to make the split database compatible with percolator

### ISSUE THREAD

**Issue by thaumP** [Nesvilab/FragPipe#626]
In the current version, split database cannot be used with percolator. I found that percolator can significantly improve my results, but some databases are very large. So I made the following attempts.

1. use the msfragger output file and run percolator separately. But after splitting the database the .pin file is missing.

2. run fragpipe with HPC, but still can't solve the problem. For example, my current computer (64G RAM) can run with split databsae = 2. But on HPC with 1.5 TB RAM it still doesn't work with split databsae = 1.  The example database is cog 2020 (https://ftp.ncbi.nih.gov/pub/COG/COG2020/data/cog-20.fa.gz).  The detail I have described in issue #619 ，but now I hope to finish my task with percolator+msbooster.

**Comment by fcyu** [comment]
It is already available in the pre-release version. If you want to have a try, please download it from https://www.dropbox.com/s/uyc01xb8ytj998k/FragPipe-17.2-build28.zip?dl=1.

Please also disable mass calibration if your database is very large.

Best,

Fengchao

**Comment by thaumP** [comment]
Thank you Fengchao

**Comment by thaumP** [comment]
> It is already available in the pre-release version. If you want to have a try, please download it from https://www.dropbox.com/s/uyc01xb8ytj998k/FragPipe-17.2-build28.zip?dl=1.
> 
> Please also disable mass calibration if your database is very large.
> 
> Best,
> 
> Fengchao

Thank you for the gift. The new version of the software achieved my purpose. 
But I found the min-probability feature in percolator. The default is 0.5, what is the default value for 17.1? I found the result is a little different from 17.1.

Is this parameter the same as --minprob in peptideprohibit?

What should I choose for the value of this parameter, I found that after lowering the value of this parameter, the protein coverage is elevated, but the run time is a bit longer.

**Comment by fcyu** [comment]
The error seems similar to this one (https://github.com/Nesvilab/FragPipe/issues/560#issuecomment-1080676109). Maybe Guo Ci @guoci already have a fixed version. Guo Ci, can you send him the zip file to test?

Thanks,

Fengchao

**Comment by guoci** [comment]
@thaumP please use https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi?usp=sharing

**Comment by thaumP** [comment]
> @thaumP please use https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi?usp=sharing

Thank you！ build31 seems pretty good！ @guoci @fcyu
