### ISSUE TITLE
Process 'PhilosopherDbAnnotate' finished, exit code: 2 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by tnguyenwi** [Nesvilab/FragPipe#629]
**Describe the bug**

Hello I have this issue.
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping
can you please help me how to solve this problem?
Thanks,
TN
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Hi Felipe @prvst ,

Can you take a look since the error was from Philosopher?

Thanks,

Fengchao

**Comment by prvst** [comment]
Please send the log file.

**Comment by tnguyenwi** [comment]
[](url
[tnguyen_log_2022-03-30_17-14-33.txt](https://github.com/Nesvilab/FragPipe/files/8384490/tnguyen_log_2022-03-30_17-14-33.txt)
)

**Comment by tnguyenwi** [comment]
Thanks

**Comment by tnguyenwi** [comment]
Thanks

> can you share the database as well?

[NCBI_Ixodata+Bovine_validated.zip](https://github.com/Nesvilab/FragPipe/files/8391405/NCBI_Ixodata%2BBovine_validated.zip)

**Comment by prvst** [comment]
The zip is empty

**Comment by prvst** [comment]
@tnguyenwi the format is not compatible. Plese see [here](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database) how to fix it

**Comment by prvst** [comment]
To give a little more context, this is wrong:
`>sp|B7PKZ2.1|CYTLG_IXOSC RecName: Full=Salivary cystatin-L; AltName: Full=Sialostatin L; Short=SialoL; Flags: Precursor`

You have to change to its original format like this:

`>sp|B7PKZ2|CYTLG_IXOSC Salivary cystatin-L OS=Ixodes scapularis OX=6945 GN=IscW_ISCW018603 PE=3 SV=1`

**Comment by tnguyenwi** [comment]
Thanks Felipe. It worked!
