### ISSUE TITLE
msbooster fails due to not finding dia-nn output

### ISSUE THREAD

**Issue by hguturu** [Nesvilab/FragPipe#630]
**Describe the bug**
Running the default LFQ-phospho workflow on DDA data with FragPipe v17.1. After finishing MSFragger search, it runs MSBooster. This is the output of MSbooster. This is on `Linux ip-10-82-192-45 5.13.0-1019-aws #21~20.04.1-Ubuntu SMP Wed Mar 16 11:54:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

----------------------
## If you're submitting a bug report, please attach log file
```
MSBooster [Work dir: /home/ubuntu/sbir/SBIR_LFQ-phospho]
java -Xmx438G -cp /home/ubuntu/fragpipe/tools/msbooster-1.0.jar:/home/ubuntu/fragpipe/tools/smile-core-2.6.0.jar:/home/ubuntu/fragpipe/tools/smile-math-2.6.0.jar:/home/ubuntu/fragpipe/tools/batmass-io-1.23.6.jar Features.MainClass --paramsList /home/ubuntu/LFQ-phospho/msbooster_params.txt
Using 127 threads
Generating input file for DIA-NN
23083526 unique peptides from 120607650 PSMs
Writing DIA-NN input file
Diann input file generation took 588925 milliseconds
Input file at  /home/ubuntu/LFQ-phospho/EXP1398/spectraRT.tsv
23083526 unique peptides from 120607650 PSMs
DiannFull input file generation took 474418 milliseconds
Input file at  /home/ubuntu/LFQ-phospho/EXP1398/spectraRT_full.tsv
Generating DIA-NN predictions
/home/ubuntu/fragpipe/tools/diann/1.8/linux/diann-1.8 --lib /home/ubuntu/LFQ-phospho/EXP1398/spectraRT.tsv --predict --threads 127 --strip-unknown-mods
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Wed Mar 30 09:43:58 2022
Logical CPU cores: 128
Predicted spectra will be saved in a binary format
Thread number set to 127
DIA-NN will use deep learning to predict spectra/RTs/IMs even for peptides carrying modifications which are not recognised by the deep learning predictor. In this scenario, if also generating a spectral library from the DIA data or using the MBR mode, it might or might not be better (depends on the data) to also use the --out-measured-rt option - it's recommended to test it with and without this option

0 files will be processed
[0:00] Loading spectral library /home/ubuntu/LFQ-phospho/EXP1398/spectraRT.tsv
[3:12] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)
[5:10] Spectral library loaded: 0 protein isoforms, 0 protein groups and 23083526 precursors in 19575142 elution groups.
[5:17] Encoding peptides for spectra and RTs prediction
[7:04] Predicting spectra and IMs
Cannot find DIA-NN's output. Please rerun MSBooster
Process 'MSBooster' finished, exit code: 255
Process returned non-zero exit code, stopping
```

**Comment by yangkl96** [comment]
Hello,

Could you retry running FragPipe from the MSBooster step (unchecking boxes from steps before including MSFragger)? This is a known error, but sometimes works just by rerunning it.

Thanks,
Kevin

**Comment by hguturu** [comment]
Unfortunately, it failed again. Will proceed without MSBooster.

**Comment by hguturu** [comment]
Should this issue really be closed if its not fixed?

**Comment by guoci** [comment]
@hguturu does it always fail? Are the errors on the log always the same each time you run it?

**Comment by hguturu** [comment]
I tried it twice and both times it failed on the same step (first file?) with the above error. Haven't tried it again since I have been running it without msbooster.

**Comment by guoci** [comment]
@hguturu can you then try to run the following in the output directory, then post the output?
```
/home/ubuntu/fragpipe/tools/diann/1.8/linux/diann-1.8 --lib /home/ubuntu/LFQ-phospho/EXP1398/spectraRT.tsv --predict --threads 127 --strip-unknown-mods
echo $?
```

**Comment by hguturu** [comment]
Just ran this on the command line (outside of Fragpipe) and it ran to completion and returned 0 and created a `spectraRT.predicted.bin`.

**Comment by yangkl96** [comment]
@hguturu Thanks for trying that out, could you share your spectraRT.tsv file here: https://www.dropbox.com/request/uHxwXw0LtAC02s1H8f0D

Sometimes this error is difficult to reproduce because it is system dependent, but I will try to reproduce and fix

**Comment by hguturu** [comment]
@yangkl96, I need to check to if I am allowed to upload results from this dataset to third parties. I see its not particularly identifiable since its just a peptide/charge list, but I want to confirm. Will upload if I am allowed.

**Comment by candidaorelmex** [comment]
I have exactly the same issue!

First I got an error saying:
![image](https://user-images.githubusercontent.com/90688191/168002749-d3123dfe-f9e4-46a2-8f7e-35f22d22f222.png)

I reran with just MSBooster:
![image](https://user-images.githubusercontent.com/90688191/168002538-ac30c0d8-f92e-40e1-9c36-6042b78016eb.png)

Anything I can do to avoid the error?

If it's relevant, Im processing DDA and DIA files together, so Im using both DIAUmpire and MSFragger. I had the same issue when I checked the box to use DiaNN and when I had it unchecked.

**Comment by candidaorelmex** [comment]
> This is a different issue from the one above, as in this case the peptide prediction step does not start, whereas the issue above happens in the middle of the prediction step. Could you include your log file please?

Here a run with only DIA files, same issue though (judged by the error). First ran it as normal, second time with only MSBooster as suggested by the console:

[log_2022-05-12_20-47-38.txt](https://github.com/Nesvilab/FragPipe/files/8681855/log_2022-05-12_20-47-38.txt)
[log_2022-05-12_20-52-22.txt](https://github.com/Nesvilab/FragPipe/files/8681854/log_2022-05-12_20-52-22.txt)

**Comment by yangkl96** [comment]
Could you run the following command from the command line?

`C:\FragPipe\fragpipe\tools\diann\1.8\win\DiaNN.exe --lib E:\Ilja\fragpipe_search_results\2205012_Petrova-collab\black6\spectraRT.tsv --predict --threads 10 --strip-unknown-mods`

**Comment by candidaorelmex** [comment]
I'm running fragpipe on a computer where I dont have admin rights and can't access the terminal. I'll see if I can arrange this command to be run.

**Comment by fcyu** [comment]
FragPipe 18.0 should be robust enough to prevent this issue. Reopen a new issue if the bug still persist.
