### ISSUE TITLE
Why does the fasta header of the database affect the results?

### ISSUE THREAD

**Issue by thaumP** [Nesvilab/FragPipe#632]
Why does the fasta header of the database affect the results?

I built the database from the metagenome, so the fasta header of the database does not follow the standard form of NCBI or uniprot.
However, I found that changing the header produced significant changes in the results.

I have tried 3 forms of header.
1. prodigal output form, such as ">k141_1227164_1 # 1 # 615 # -1 # ID=1_1;partial=10;start_type=ATG;rbs_motif=GGA/GAG/AGG;rbs_spacer=5-10bp;gc _cont=0.659"
2. prodigal form of output, but with the characters after the first space removed, e.g. ">k141_1227164_1"
3. the general form of renaming, e.g. "ECSMG1", "ECSMG21"
4. the general form of renaming with fixed length, e.g. "ECSMG00000001 ", "ECSMG00000021 "

Total razor peptide， 1: 35116 ;  2:  34077;  3:  27689;  4: 35251

Strangely enough, searching with these three databases gives different results, especially between 3 and 4, even though they have exactly the same sequence.

----------------------

database 2 contain contaminats

[log_1.txt](https://github.com/Nesvilab/FragPipe/files/8403721/log_1.txt)

[log_2.txt](https://github.com/Nesvilab/FragPipe/files/8403714/log_2.txt)

[log_3.txt](https://github.com/Nesvilab/FragPipe/files/8403723/log_3.txt)

[log_4.txt](https://github.com/Nesvilab/FragPipe/files/8403735/log_4.txt)

**Comment by fcyu** [comment]
Thanks for your report. To investigate, can you upload all files, including mzml and those generated by FragPipe, to https://www.dropbox.com/request/AKSxroOfjkFoaNjGJiWc

Thanks,

Fengchao

**Comment by thaumP** [comment]
> Thanks for your report. To investigate, can you upload all files, including mzml and those generated by FragPipe, to https://www.dropbox.com/request/AKSxroOfjkFoaNjGJiWc
> 
> Thanks,
> 
> Fengchao

I upload result, database, and a example ms data.

**Comment by fcyu** [comment]
Thank you for the files. Following are my explanations.

1. Your database is very large (331462 target proteins). With such a big database, there might be many random matches even after FDR filtering.
2. Given a scan, there might be peptides that cannot be distinguished by MSFragger. For example, `I` and `L` are indistinguishable; two peptides that have the same score are indistinguishable. But, when using MSBooster and Percolator, some of the scores of two indistinguishable peptides are different (e.g. predicted RT and spectrum, some scores that are calculated after database search.). Such cases are very rare, but with a large database/search space, they become not so rare.

If you are doing metaproteomics analysis, I suggest you disable protein inference (check do not use ProteinProphet). Or, maybe you can contact us privately regarding your purpose for using our tools.

Best,

Fengchao

**Comment by thaumP** [comment]
> 
Thank you Fengchao.  Your advice is very useful. I tried again based on your advice, but still had some problems.

I tried to use a smaller metatranscriptome database, about 90,000 sequences, with a shorter average length.

Two types of fasta header were used: short, eg "ECSMG21"; long, eg "ECSMG00000021".

If protein inference (PI) is disabled, the fasta header has a negligible effect on the peptides results.

If protein inference is turned on, fasta header has a significant effect on peptides results. This may be related to the size of the database you are talking about, as the difference is much larger in the metagenomic database. Surprisingly in both databases the longer fasta header always leads to more peptide identifications and I cannot understand what can cause this problem.

The peptide results also appear different after protein inference is turned on. In my understanding, protein inference should come after peptide validation and it seems that it should not affect the peptide results.

Can you tell me the drawbacks of using protein inference in metaproteome? But I need information about proteins . 

metatranscriptomic database:
![image](https://user-images.githubusercontent.com/100261099/161464410-c2065a82-a77d-48ab-9685-f8a1963c5f76.png)
![image](https://user-images.githubusercontent.com/100261099/161464700-28ff84ca-a639-46c2-bdf2-047ed22bd65b.png)
![image](https://user-images.githubusercontent.com/100261099/161465124-80006900-924f-42e7-86fa-24ff130d9f7d.png)

Metagenomic database :
![image](https://user-images.githubusercontent.com/100261099/161466276-1445e3dc-006a-4b23-b459-d52db952ad44.png)

**Comment by fcyu** [comment]
Thank you very much for your test. 

> If protein inference (PI) is disabled, the fasta header has a negligible effect on the peptides results.
> If protein inference is turned on, fasta header has a significant effect on peptides results. This may be related to the size of the database you are talking about, as the difference is much larger in the metagenomic database. Surprisingly in both databases the longer fasta header always leads to more peptide identifications and I cannot understand what can cause this problem.

I am not sure if there is a bug in the protein inference. Felipe @prvst and Alexey @anesvi , can you take a look?


> The peptide results also appear different after protein inference is turned on. In my understanding, protein inference should come after peptide validation and it seems that it should not affect the peptide results.

You are using sequential filtering, which means that the PSMs are filtered with PSM and protein FDR. As you can see in the following example, the PSMs and peptides are filtered again after protein inference and cut-off. If you just want protein inference but no protein cut-off, you can use `--prot 1` in the filter command.
```shell
INFO[10:54:56] Converged to 1.00 % FDR with 137046 PSMs      decoy=1383 threshold=0.834628 total=138429
INFO[10:54:57] Converged to 1.00 % FDR with 34197 Peptides   decoy=345 threshold=0.936451 total=34542
INFO[10:54:57] Converged to 1.00 % FDR with 42238 Ions       decoy=426 threshold=0.923067 total=42664
INFO[10:54:59] Protein inference results                     decoy=4842 target=16891
INFO[10:55:00] Converged to 1.03 % FDR with 6228 Proteins    decoy=64 threshold=0.9798 total=6292
INFO[10:55:03] Applying sequential FDR estimation            ions=43151 peptides=35331 psms=134662
INFO[10:55:04] Converged to 0.11 % FDR with 134508 PSMs      decoy=154 threshold=0.834628 total=134662
INFO[10:55:04] Converged to 0.18 % FDR with 35267 Peptides   decoy=64 threshold=0.834628 total=35331
INFO[10:55:05] Converged to 0.15 % FDR with 43085 Ions       decoy=66 threshold=0.834628 total=43151
```

Best,

Fengchao

**Comment by prvst** [comment]
@thaumP This is why we try to enforce a pattern or standard for the database headers. The workflows run multiple tools, and some are not even maintained by us. All these tools will try to read and parse the headers, and we try to keep things in line by asking people to follow the popular formats. When you come up with your own format, these programs might interpret them in different ways, so please stick to the standards that we suggest, to the best way to avoid problems.

I'm not familiar with your experiment, but it seems to me that you are having issues with the protein inference and a very large protein database. Please keep in mind that FragPipe is a DIA/DDA proteomics processing pipeline. If you are working with metaproteomics, then you need a metaproteomics pipeline. Some of them are compatible with Fragger, but the way how the data is processed and analyzed differs from the traditional DDA shotgun proteomics analysis. Some things might not make much sense, especially depending on the number of organisms you have in your sample.

**Comment by anesvi** [comment]
I suggest you first establish that without running ProteinProphet the results are the same. Just do not run it and filter without prot.xml

If so, then we can think what ProteinProphet does differently depending on the headers

Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thaumP** [comment]
@fcyu @prvst @anesvi 

Thank you for your reply！I re-ran the test, using the MG database. 5 header types, running with or without ProteinProphet

1. Letters with variable digits, such as: "ECS12345"
2. Letters with six digits, such as: "ECS012345"
3. Letters with eight digits, such as: "ECS00012345"
4. Variable digits, such as: "12345"
5. Six digits, such as: "012345"

2. letters plus six digits, e.g. "ECS012345"
3. Letters plus eight digits, e.g. "ECS00012345"
4. digits with variable digits, e.g. "12345"
5. six digits, e.g., "012345"

The number of peptides identified, respectively, is as follows.

![image](https://user-images.githubusercontent.com/100261099/161666303-47d98e96-7aaf-4475-8862-d7a01c9eae5c.png)

With header length fixed, the results are stable. If PP is not turned on, header still has an effect on the result, but it is slight. After PP is turned on, it has a significant effect.

Since some work may require merging databases from different sources, I think this issue may be of a little sense.

**Comment by anesvi** [comment]
I am still not sure if the issue is with philosopher or ProteinProphet. ProteinProphet should note care about the headers.   More likely philosopher. You can see if the number of protein groups with high probability is about the same in prot.xml files. It would require Felipe looking at philosopher. If he is not able, Perhaps you can just use the fixed length headers that give consistent results.
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thaumP** [comment]
I checked the prot.xml file in T4 and T5, and as the table shows, there is a slight difference in the possibility of protein groups. 
![image](https://user-images.githubusercontent.com/100261099/161697553-393998e3-81d8-4dd2-b950-a0a57d3f6aa5.png)

And I sent these results file to Fengchao's link.

**Comment by prvst** [comment]
This only adds weight to my previous comment, and current opinion about using custom headers. I don't understand either why ProteinProphet results are different when using different headers. I know how Philosopher parses the headers, but it needs to be in sync with what the Prophets do for the results to make sense, otherwise it will be cases where different proteins might be considered the same or maybe something else. Even if you pinpoint the reason we will be limited on what we can do because we are not the maintainers of ProteinProphet. Having said that, I second Alexey's opinion, so please keep to the official formats, and the fixed length headers.
