### ISSUE TITLE
Cannot execute program. fork/exec /tmp/[...]/InteractParser: exec format error

### ISSUE THREAD

**Issue by GKok** [Nesvilab/FragPipe#634]
Hi!

I've used FragPipe on a local Windows machine for optimization of our workflow, but want to run it on a high performance cluster with X11 forwarding for the actual analyses. 

Unfortunately, it crashes after a while, with the following set of errors repeated many times:
```
time="11:21:34" level=error msg="Cannot deploy asset. RefreshParser"
time="11:21:34" level=error msg="Cannot deploy asset. InteractParser"
time="11:21:34" level=error msg="Cannot deploy asset. PeptideProphetParser"
time="11:21:34" level=fatal msg="Cannot execute program. fork/exec /tmp/58f42d88-e192-4a0c-bc17-27c425b38e9a/InteractParser: exec format error
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
Processing interrupted, stopping PeptideProphet
```

Machine:
```
CentOS Linux 7
java version "1.7.0_261"
OpenJDK Runtime Environment (rhel-2.6.22.2.el7_8-x86_64 u261-b02)
OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)
```

With latests versions of FragPipe, MSFragger and Philosopher.

Any ideas on what's going wrong?

**Comment by prvst** [comment]
@guoci do you think it could be a problem with the CentOS binary deploy?

**Comment by GKok** [comment]
I've asked the HPC developers about their opinion, and they told me that `/tmp` only has 100 MB of space on the compute nodes. Instead, `$TMPDIR` should be used. Could that be the problem, and if so, is it possible to specify this anywhere?

**Comment by prvst** [comment]
That could be the reason. Unfortunately, I don't know if you can change the temporary folder location using FragPipe, you can do that in Philosopher when you run it manually though.

**Comment by GKok** [comment]
Thanks! I've found this issue, and will try their solution: https://github.com/Nesvilab/FragPipe/issues/306

```
> export JAVA_OPTS=-Djava.io.tmpdir=$TMPDIR
> ./fragpipe
```

**Comment by GKok** [comment]
That's unfortunate. Would it help to re-compile philosopher on the HPC? I guess this would needed to be done prior to every run, as the tmpdir changes every session.

**Comment by GKok** [comment]
@guoci Many thanks for your prompt update! This indeed passes the correct tmp directory to Philosopher, and fixes the errors above. However, it now crashes at the same step with a different error. 

```
time="10:59:24" level=info msg="Executing PeptideProphet  v4.1.1"
time="10:59:25" level=fatal msg="Cannot execute program. fork/exec /scratch/1938675/InteractParser: text file busy"
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping
```

**Comment by guoci** [comment]
@GKok does the file `/scratch/1938675/InteractParser` exists? Try executing it on the command line and show me the output.

**Comment by GKok** [comment]
@guoci Yes, it exists and works. 
_(the batch number is different, because I had to re-start it)_

```
[gkok@n0082 ~]$ cd /scratch/1966425/
[gkok@n0082 1966425]$ ./InteractParser 
./InteractParser (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64))
usage  : InteractParser <outputfile> <file1.pep.xml> <file2.pep.xml>... <options>
options: 
	-a<path_to_data_dir> : path to the data directory
	-D<path_to_database> : path to the database
	-T<database_type>    : database type
	-X<experiment_label> : assign experiment_label to each spectrum_query
	-L<min_peptide_len>  : minimum peptide length not rejected (default 7)
	-R<max_rank>         : maximum peptide rank in output (default 1)
	-A : allow (don't reject) X containing peptides
	-S : record retention_time_sec in pepXML
	-i : record ion_injection_time in pepXML
	-I : record precursor intensity in pepXML
	-B : record base peak intensity in pepXML
	-O : record total ion current in pepXML 
	-2 : record signal to noise pepXML 
	-G : record collision energy in pepXML
	-V : record compensation voltage in pepXML
	-P : correct protein names (applied automatically for OMSSA results)
	-C : correct charge states (applied automatically for OMSSA results)
	-M : correct Pyro-Glu and Ammonia Loss Modifications E[111], Q[111] (applied automatically for OMSSA results)
	-N : don't write the input file reference to the output pepXML file (Use only when one input file is given)
	-W : only warn, don't skip files containing PeptideProphet results
	-E<enzyme>: enzyme used in sample, one of:   (semi-cleavage specification: -Esemi<enyzme>)
	   trypsin : cut(KR) nocuts(P) sense(C)
	   stricttrypsin : cut(KR) sense(C)
	   argc : cut(R) nocuts(P) sense(C)
	   aspn : cut(D) sense(N)
	   chymotrypsin : cut(FLWY) nocuts(P) sense(C)
	   clostripain : cut(R) nocuts(-) sense(C)
	   cnbr : cut(M) sense(C)
	   elastase : cut(AGILV) nocuts(P) sense(C)
	   formicacid : cut(D) nocuts(P) sense(C)
	   gluc : cut(DE) nocuts(P) sense(C)
	   gluc_bicarb : cut(E) nocuts(P) sense(C)
	   iodosobenzoate : cut(W) nocuts(-) sense(C)
	   lysc : cut(K) nocuts(P) sense(C)
	   lysc-p : cut(K) sense(C)
	   lysn : cut(K) sense(N)
	   lysn_promisc : cut(KR) sense(N)
	   ralphtrypsin : cut(KRST) nocuts(P) sense(C)
	   nonspecific : cut() sense(C)
	   pepsina : cut(FL) nocuts(-) sense(C)
	   proline_endopeptidase : cut(P) nocuts(-) sense(C)
	   trypsin/chymotrypsin : cut(FYWLKR) nocuts(P) sense(C)
	   staph_protease : cut(E) nocuts(-) sense(C)
	   tca : cut(KR) nocuts(P) sense(C)
	       : cut(YWFM) nocuts(P) sense(C)
	       : cut(D) sense(N)
	   trypsin/cnbr : cut(KR) nocuts(P) sense(C)
	                : cut(M) nocuts(P) sense(C)
	   trypsin_gluc : cut(DEKR) nocuts(P) sense(C)
	   trypsin_k : cut(K) nocuts(P) sense(C)
	   trypsin_r : cut(R) nocuts(P) sense(C)
	   thermolysin : cut(ALIVFM) nocuts(DE) sense(N)

InteractParser will also correct some other common issues found in pepXML files written by various search engines.

[gkok@n0082 1966425]$ 
```

**Comment by guoci** [comment]
@GKok I don't know what is the cause then. Perphaps you can set the tmpdir to a normal location (outside of `/scratch`) and retry.

**Comment by GKok** [comment]
@guoci Thank you for the suggestion. I've tried that, in combination with updating to Philosopher 4.2.1, but unfortunately it throws the exact same error. Googling tells me the error is caused an attempt to modify an executable (InteractParser) while it's running. I'll check with our HPC administrators if they can think of something, and I'll keep trying :-)

Once again, thank you all for your assistance.

**Comment by guoci** [comment]
@GKok I think I might have fixed the issue, please try the following:
https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi?usp=sharing

**Comment by GKok** [comment]
@guoci Thanks for the update! This one crashes immediately after initializing the run.

```
CheckCentroid
java -Xmx297G -cp /home/xxx/gkok/fragpipe/lib/fragpipe-17.2-build36.jar:/home/xxx/gkok/fragpipe/tools/batmass-io-1.25.2.jar com.dmtavt.fragpipe.util.CheckCentroid /hpc/shared/xxx/gkok/MS/mzml/01CPTAC_LSCC_W_BI_20190615_KL/01CPTAC_LSCC_W_BI_20190615_KL_f05.mzML 47
Done in 1695 ms.
Process 'CheckCentroid' finished, exit code: 0
WorkspaceCleanInit [Work dir: /hpc/xxx/users/gkok/MS/FPOut/CPTAC01_02_WT_17.2b36/CPTAC02]
/home/xxx/gkok/fragpipe-17.2-build33/tools/philosopher_v4.2.1_linux_amd64/philosopher workspace --clean --nocheck
time="11:43:19" level=info msg="Executing Workspace  v4.2.1"
time="11:43:19" level=info msg="Removing workspace"
time="11:43:19" level=warning msg="Cannot read file. open .meta/meta.bin: no such file or directory"
time="11:43:19" level=info msg=Done
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: /hpc/xxx/users/gkok/MS/FPOut/CPTAC01_02_WT_17.2b36/CPTAC02]
/home/xxx/gkok/fragpipe-17.2-build33/tools/philosopher_v4.2.1_linux_amd64/philosopher workspace --init --nocheck --temp /scratch/2101170/0a47dc89-0cf9-405a-b7d9-1b5c2586f879
time="11:43:19" level=info msg="Executing Workspace  v4.2.1"
time="11:43:19" level=info msg="Creating workspace"
time="11:43:19" level=fatal msg="cannot find the custom temporary folder"
Process 'WorkspaceCleanInit' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 273 remaining tasks
```

I did, however, manage to workaround the error by using the FragPipe 17.2-build 33 you sent me, with Philosopher 4.1.1 (instead of 4.2.1) and deselecting 'generate peptide-level summary' and 'generate protein-level summary'. This way, I get through to the end and get the reports I need. 

Then, I noticed that the philosopher steps are quite time-consuming. While I'm running on a HPC with many cores available, FragPipe runs every philosopher step sequentially instead of in parallel, ignoring the 'parallelism' setting in the 'Workflow' tab. Do you know if there's another setting that I'm missing, to use the full CPU power available? It would save an enormous amount of time if FragPipe could run the philosoper steps (database/filter/etc.) in e.g., 128 parallel threads. 

Thanks again :-)

**Comment by guoci** [comment]
@GKok Please, try a new update again:
https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi?usp=sharing
Some parts of Philosopher (eg Proteinprophet) cannot be run in parallel, it is an external tool. The ProteinProphet step is especially slow in 4.1.1.
But in 4.2.1, the slow ProteinProphet step has been resolved and other parts of Philosopher should also run much faster.

**Comment by guoci** [comment]
Please try an updated `Philosopher` here:
https://drive.google.com/drive/folders/1g1Z_v_eWKhIuuC2wTqu0WahkIAgEBxzi?usp=sharing

**Comment by GKok** [comment]
@guoci This version, in combination with your latest FP build works! And indeed approx. 25% faster than the previous version. Many thanks! :)

**Comment by GKok** [comment]
Well... That's when using the first 50 files from 2 experiments. I now tried with 250 files from 10 experiments. That crashes again, now at `Rewrite pepxml`. Any ideas?

```
PeptideProphet: Delete temp
java -cp /home/xxx/gkok/fragpipe/lib/fragpipe-17.2-build36.jar com.github.chhh.utils.FileDelete /hpc/xxx/users/gkok/MS/FPOut/CPTAC01_10_WT/CPTAC10/fragpipe-10CPTAC_LSCC_W_BI_20190726_KL_f25.pepXML-temp
Process 'PeptideProphet: Delete temp' finished, exit code: 0
Rewrite pepxml [Work dir: /hpc/xxx/users/gkok/MS/FPOut/CPTAC01_10_WT/CPTAC07]
java -cp /home/xxx/gkok/fragpipe/lib/* com.dmtavt.fragpipe.util.RewritePepxml /hpc/xxx/users/gkok/MS/FPOut/CPTAC01_10_WT/CPTAC07/interact-07CPTAC_LSCC_W_BI_20190714_KL_f23.pep.xml /hpc/shared/xxx/gkok/MS/mzml/07CPTAC_LSCC_W_BI_20190714_KL/07CPTAC_LSCC_W_BI_20190714_KL_f23.mzML
Not all given paths exist: Optional[/hpc/xxx/users/gkok/MS/FPOut/CPTAC01_10_WT/CPTAC07/interact-07CPTAC_LSCC_W_BI_20190714_KL_f23.pep.xml]
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 315 remaining tasks
```
