### ISSUE TITLE
Philosopher filter not find the interact.pep.xml file 

### ISSUE THREAD

**Issue by tjlundgren** [Nesvilab/FragPipe#635]
Hi Fragpipe team,
This is a copy of [an issue](https://github.com/Nesvilab/philosopher/issues/332#issue-1186860259) I submitted to the Philosopher github -- I'm unsure which is more appropriate so please pardon the double submission...

Describe the bug

I am trying to output unfiltered results with PeptideProphet to .tsv to model the decoy distribution across all my samples (similar to the sample_model.png already output per sample) and to parse low scoring spectra. When I change settings in FragPipe to include all PSMs, I get an error at the filter step...
"FATA[17:40:58] Missing input file. you must provide a pepXML file or a folder with one or more files, Run 'philosopher filter --help' for more information "

When I look at the directory indicated in the filter command, I see a sample.pepxml.

To Reproduce

    Mass-offset search
    PeptideProphet with --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --minprob 0 --accmass
    ProteinProphet --maxppmdiff 2000000
    Philosopher Filter with --sequential --razor --mapmods --prot 1 --psm 1 --ion 1 -- pep 1 --pepProb 0 --protProb 0 --models, Print decoys option selected in FragPipe GUI

Expected behavior

Regular .tsv outputs (specifically looking for psm.tsv) with all decoys and low scoring targets.

Please complete the following information:

    OS: Windows
    FragPipe Version: 17.1
    Philosopher version: 4.1.0 (build 1635640020)

Additional context
This is following a MSFragger mass-offset search. I noticed an updated tooltip for the 'Report as variable mod' option in MSFragger suggested the PeptideProphet --accmass tag, which I had previously not been using. Adding this tag did not cause errors in the normally filtered results, but it is another setting I've changed recently before encountering this issue.
Thank you in advance for your help,
FragPipe log:
[log_2022-03-28_17-40-58.txt](https://github.com/Nesvilab/philosopher/files/8383244/log_2022-03-28_17-40-58.txt)
First sample.pepxml:
[2021-06-18-ECL_Slot1-41_1_1711.zip](https://github.com/Nesvilab/philosopher/files/8383254/2021-06-18-ECL_Slot1-41_1_1711.zip)
Filter.log file for first sample:
[filter.log](https://github.com/Nesvilab/philosopher/files/8383257/filter.log)

**Comment by fcyu** [comment]
Hi Felipe,

I don't think it is very likely in FragPipe, because users don't have the freedom to change the path of the pep.xml file and the path for the filter command. I can see that PeptideProphet finished successfully from the log. Maybe need to ask for all of the files in the result folder.

Best,

Fengchao

**Comment by tjlundgren** [comment]
I reran the search in a clean directory and fresh instance of FragPipe, same error. Should I upload the results folder? 
[log_2022-04-04_19-56-44.txt](https://github.com/Nesvilab/FragPipe/files/8418211/log_2022-04-04_19-56-44.txt)

**Comment by prvst** [comment]
Before that, could you try again but using the latest version of all tools?

**Comment by tjlundgren** [comment]
Updated MSFragger to 3.4 and Philosopher to version: 4.1.1 (build 1637179075), will update tomorrow with log/results.

**Comment by tjlundgren** [comment]
Same result.
[log_2022-04-05_17-27-34.txt](https://github.com/Nesvilab/FragPipe/files/8427092/log_2022-04-05_17-27-34.txt)

**Comment by prvst** [comment]
Can you share one interact.pep.xml file with me?

**Comment by tjlundgren** [comment]
Here is a recent one:
[2021-06-18-ECLandSALTY1_Slot1-42_1_1715.zip](https://github.com/Nesvilab/FragPipe/files/8427469/2021-06-18-ECLandSALTY1_Slot1-42_1_1715.zip)
Another is in the first post. Thanks again for your help!

**Comment by tjlundgren** [comment]
Apologies, is this the correct file?
[interact.pep.zip](https://github.com/Nesvilab/FragPipe/files/8427614/interact.pep.zip)

**Comment by prvst** [comment]
Your file seems fine, and by the looks of your log, everything else in the run seems OK too:
```INFO[10:16:01] Parsing interact.pep.xml                     
INFO[10:16:11] 1+ Charge profile                             decoy=183 target=227
INFO[10:16:11] 2+ Charge profile                             decoy=9479 target=43708
INFO[10:16:11] 3+ Charge profile                             decoy=6406 target=21934
INFO[10:16:11] 4+ Charge profile                             decoy=1286 target=2977
INFO[10:16:11] 5+ Charge profile                             decoy=104 target=184
INFO[10:16:11] 6+ Charge profile                             decoy=0 target=0
INFO[10:16:11] Database search results                       ions=58892 peptides=42909 psms=86488
INFO[10:16:11] Converged to 1.00 % FDR with 35190 PSMs       decoy=355 threshold=0.8757 total=35545
INFO[10:16:11] Converged to 1.00 % FDR with 9795 Peptides    decoy=98 threshold=0.9572 total=9893
INFO[10:16:11] Converged to 1.00 % FDR with 16407 Ions       decoy=165 threshold=0.9362 total=16572
```

There's not much I can do without looking directly at your computer and your files. My impression is that FragPipe might be set in a unusual way, or maybe some paths are not being interpreted correctly.

@guoci @fcyu Maybe worth checking the paths, directories, and settings again?

**Comment by tjlundgren** [comment]
Sorry, I was trying to replicate the issue via command line but this should be the unaltered file
[interact.pep.zip](https://github.com/Nesvilab/FragPipe/files/8427715/interact.pep.zip)

**Comment by prvst** [comment]
Looks good too:
```
INFO[10:29:10] Executing Filter  v4.2.1                     
INFO[10:29:10] Processing peptide identification files      
INFO[10:29:10] Parsing interact.pep.xml                     
INFO[10:29:16] 1+ Charge profile                             decoy=101 target=124
INFO[10:29:16] 2+ Charge profile                             decoy=2061 target=25781
INFO[10:29:16] 3+ Charge profile                             decoy=2122 target=13431
INFO[10:29:16] 4+ Charge profile                             decoy=543 target=1812
INFO[10:29:16] 5+ Charge profile                             decoy=51 target=136
INFO[10:29:16] 6+ Charge profile                             decoy=0 target=0
INFO[10:29:16] Database search results                       ions=27228 peptides=21249 psms=46162
INFO[10:29:16] Converged to 1.00 % FDR with 30031 PSMs       decoy=303 threshold=0.8665 total=30334
INFO[10:29:16] Converged to 1.00 % FDR with 10479 Peptides   decoy=105 threshold=0.9472 total=10584
INFO[10:29:16] Converged to 1.00 % FDR with 14407 Ions       decoy=145 threshold=0.9292 total=14552
INFO[10:29:17] Post processing identifications 
```

**Comment by tjlundgren** [comment]
That looks odd, as I was not trying not to filter to 1% (--sequential --razor --mapmods --prot 1 --psm 1 --ion 1 -- pep 1 --pepProb 0 --protProb 0 --models)

**Comment by fcyu** [comment]
Felipe @prvst, I reproduced the error (see the attached screenshot). It seems to be a bug in Philosopher.

![image](https://user-images.githubusercontent.com/6926299/162000045-99da6e05-1d77-4418-b947-98cb8573ab6c.png)

Best,

Fengchao

**Comment by prvst** [comment]
I see the error now. Somehow the folder is causing a problem. I think I pinpointed the issue of a modification from Guo Ci, I'll talk with him.

**Comment by prvst** [comment]
@tjlundgren Here's a pre-release for you to test:

[Philosopher v4.2.2-RC](https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0)

**Comment by tjlundgren** [comment]
Pre-release version worked very well! Thank you again for your time and excellent software.
