### ISSUE TITLE
DIA library creation with different LC runs

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/FragPipe#637]
Hi all,

We have some datasets that used different Evosep LC times (20minute per sample and 11 minutes).

I wonder if I can still put them together to form a DIA library?

I had a look at the Easypqp github where the following is stated:
Retention times are calibrated using an internal or external standard.

Still not really sure if it would work. Happy to hear what you all think?

Kind regards,
Patrick

**Comment by anesvi** [comment]
I think it should be OK. Unless 11 min and 20 min LC so different that peptide change elution order a lot. 

Just play with FragPipe/EasyPQP options. If it is unfractionated DDA data you are building library from, the first choice should always be 'use automated selection...". If all runs are fractionated DDA, use CIRT option. But when you have fractionated DDA data  it is better to process single-shot DIA and fractionated DDA together and still use automated run selection for RT alignment. 

Check the RT alignment figures generated by EasyPQP to see if the alignment between 20 min and 11 min is OK. 

Alexey

**Comment by PatrickvanZalm** [comment]
Thanks Alexey, we were thinking the same direction so glad to see the ideas align.

Ill have some testing to do.

**Comment by anesvi** [comment]
Let us know how the tests go. So we know in case someone else asks the same. Best, Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
