### ISSUE TITLE
MBR is slow when there are many donor runs.

### ISSUE THREAD

**Issue by anfoss** [Nesvilab/FragPipe#640]
I have 192 timstof DDA-PASEF files and I have been running the LFQ-MBR workflow. However, while all steps are pretty fast (i.e 1 day)  it has been hanging at the MBR step since 4 days. 

We are running FragPipe on a Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz  with 128 GB of installed RAM so there should be no issue in threading or parallelization. 
Is there any setting that can be tweaked to speed this up for the next time? It is taking longer to search the data then to acquire it.

**Comment by fcyu** [comment]
Can you send the log file?

Best,

Fengchao

**Comment by anfoss** [comment]
[log_2022-04-08_11-36-27.txt](https://github.com/Nesvilab/FragPipe/files/8454497/log_2022-04-08_11-36-27.txt)

MSfragger was done before but there was a out of memory error so in this run I just started from peptide prophet

**Comment by fcyu** [comment]
Thank you for the log file. 

I can see that IonQuant is transferring peptides from all runs to the acceptor run. By default, the top run number is 100000. In your case, you can set it to, say 10, which will only transfer top 10 most similar runs for each acceptor run.

Best,

Fengchao

**Comment by anfoss** [comment]
perfect thanks for the clarification!
