### ISSUE TITLE
Mass calibration 

### ISSUE THREAD

**Issue by LakminiSenavirathna** [Nesvilab/FragPipe#645]
Hi,

I am running my raw files using MSfragger and found from the log file, that mass calibration for some files is not performed and it indicates ' Not enough data to perform mass calibration. Using the uncalibrated data." Could you please let me know what is the issue with this?
Also, I was not able to generate the peptide list file. After this run, I was only able to get the interact file. I have attached the log file for your reference. Could you please advise me to resolve the issue?

Thanks,
Lakmini

[log_2022-04-09_04-03-27.txt](https://github.com/Nesvilab/FragPipe/files/8476090/log_2022-04-09_04-03-27.txt)

**Comment by fcyu** [comment]
It means that there are not enough high quality PSMs from the first search. You need to double check your settings. For example, does your data have chemical labeling or enriched modifications? Does your data from trypsin digestion?

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Thanks, I am trying to look for some glycation modifications. (samples did not have chemical labeling or enrichment). Yes. they are from trypsin digestion.

**Comment by fcyu** [comment]
Your log shows that there are no PSMs with probability > 0.05: `...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05`. Please double check your data and settings.

Best,

Fengchao
