### ISSUE TITLE
PhilosopherFilter fails with `Cannot decode packed binary. expected element type <msms_pipeline_analysis> but have <msms_run_summary>`

### ISSUE THREAD

**Issue by hguturu** [Nesvilab/FragPipe#649]
**Describe the bug**
I was running the `LFQ-phospho` workflow on a set of mzML files from Bruker data. After running the whole process during the `PhilosopherFilter` step one of the job fails with `FATA[19:58:57] Cannot decode packed binary. expected element type <msms_pipeline_analysis> but have <msms_run_summary>`

This is from the same run as https://github.com/Nesvilab/FragPipe/issues/630 and https://github.com/Nesvilab/FragPipe/issues/631#issuecomment-1086136771 where I had issues with `MSBooster` and `PTMProphet`. I actually got the above `PhilosopherFilter` error previously on Ubuntu after the previously suggested work around (turn off MSBooster, run PTMProphet commands manually to side step the FragPipe failures). I thought maybe me running things manually some how caused the files to not be formatted properly.

Since then I switched from Ubuntu to Windows and ran everything in FragPipe. I didn't have any issues with `MSBooster` or `PTMProphet` and it ran all the way through. And several `PhilosopherFilter` also ran, but then this crashed occurred.

This error is reproducible since if I run below in either Powershell or Git-Bash I get the same error and the exit codes ($LASTEXITCODE, $?) are 1 for both.
```
C:\FragPipe\fragpipe-jre-17.1\tools\philosopher\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml E:\LFQ-phospho_windows\EXP0252X21_A --protxml E:\LFQ-phospho_windows\combined.prot.xml --razorbin E:\LFQ-phospho_windows\EXP0252X21_A\.meta\razor.bin
```

----------------------
## If you're submitting a bug report, please attach log file

```
PhilosopherFilter [Work dir: E:\LFQ-phospho_windows\EXP0252X21_A]
C:\FragPipe\fragpipe-jre-17.1\tools\philosopher\philosopher.exe filter --sequential --prot 0.01 --tag rev_ --pepxml E:\LFQ-phospho_windows\EXP0252X21_A --protxml E:\LFQ-phospho_windows\combined.prot.xml --razorbin E:\LFQ-phospho_windows\EXP0252X21_A\.meta\razor.bin
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 3304 remaining tasks
INFO[19:58:56] Done                                         
INFO[19:58:56] Executing Filter  v4.2.1                     
INFO[19:58:57] Fetching razor assignment from: E:\LFQ-phospho_windows\EXP0252X21_A\.meta\razor.bin: 83203 razor groups imported. 
INFO[19:58:57] Processing peptide identification files      
INFO[19:58:57] Parsing interact-EXP0252X21_A.mod.pep.xml 
FATA[19:58:57] Cannot decode packed binary. expected element type <msms_pipeline_analysis> but have <msms_run_summary> 
```

**Comment by fcyu** [comment]
Can you send the whole log file?

Thanks,

Fengchao

**Comment by hguturu** [comment]
Here you go.
[log_2022-04-14_19-58-57.zip](https://github.com/Nesvilab/FragPipe/files/8497182/log_2022-04-14_19-58-57.zip)
B

**Comment by fcyu** [comment]
Hi Felipe @prvst ,

Can you take a look? Everything seems good until Philosophe filter command.

Best,

Fengchao

**Comment by fcyu** [comment]
I also noticed that some runs have `'chmod' is not recognized as an internal or external command, operable program or batch file.` error in PTM-Prophet, but some don't. It might be related to the error in the filter command. Felipe @prvst can you investigate is too?

Thanks,

Fengchao

**Comment by prvst** [comment]
It's a malformed pep.xml file. I see phospho in the folder name, so I guess PTMprophet was executed? If so, reduce the number of threads and try again.

**Comment by fcyu** [comment]
I think David has already fixed this bug in PTM-Prophet. Can you update Philosopher to include the new PTM-Prophet? We keep receiving error reports due to this bug.

Best,

Fengchao

**Comment by prvst** [comment]
@guoci we added the most recent PTProphet to the source, right?

**Comment by guoci** [comment]
I have never updated it.

**Comment by hguturu** [comment]
Hi, Yes I was running `LFQ-phospho` workflow. Is there a recommended number of max cores for stable performance? I was using 127 and noticed close to 100% CPU utilization on my 128 core machine. 

I assume this means the task is highly parallelized and getting a benefit from the many cores. Since I have many files, I want to run through the files as fast as possible since even with 127 cores this job took nearly a week. 

Is there a check I can do on the resulting pep xml so I can just re-run those bad files manually to avoid recomputing everything?

**Comment by prvst** [comment]
Unfortunately, no. This is a known problem on a third-party tool, and there's no "right" number. This happens with people running 10 or 100 threads because it seems to depend on their configuration.

**Comment by hguturu** [comment]
Looks like it might even be non-deterministic in the number of threads (i.e. I think I was able to re-run it using the same thread count and it succeeded).

Oddly `proteinprophet` uses this file as input, but it didn't complain. Does that mean the file is only partially malformed and proteinprophet results are valid? If not, it might be worthwhile having this check in `proteinprophet` to avoid running protein inference and then failing at the filter/report stage.

**Comment by prvst** [comment]
Yeah, multithreaded issues are hard to debug. The files are good regarding their content. It's just the header that is malformed, some XML tags are left open and philosopher needs them to consume the file. ProteinProphet will ignore everything in the file except for the lines it needs.

**Comment by prvst** [comment]
Can you send me your file?

**Comment by ProteomicsPSG** [comment]
See attached the params, the config and the log file plus a file list for PrtProphet. From the reduced sample set (50 runs).

[filelist_proteinprophet.txt](https://github.com/Nesvilab/FragPipe/files/8592472/filelist_proteinprophet.txt)
[fragpipe_2022-04-29_12-15-30.config.txt](https://github.com/Nesvilab/FragPipe/files/8592473/fragpipe_2022-04-29_12-15-30.config.txt)
[fragger.params.txt](https://github.com/Nesvilab/FragPipe/files/8592474/fragger.params.txt)
[log_2022-04-29_13-36-48.txt](https://github.com/Nesvilab/FragPipe/files/8592475/log_2022-04-29_13-36-48.txt)

**Comment by ProteomicsPSG** [comment]
Hi Felipe,
I have uploaded the log file and settings file to github on this issue thread.
Do you need more info, eg.  Some raw file?

Actually, I think I have done something wrong in the settings parameters. But don’t know where.
Could you check that?

Previous searches with MS fragger didn’t give this error.. but I chose some different settings.

Thanks a lot for your help.

Twan

**Comment by fcyu** [comment]
We have the pre-release versions of FragPipe and MSFragger than fixes the multi-threading issue in PTMProphet.

Please contact us for the pre-release versions if you want to have a try.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
Hey - are there any updates of this issue? I run Fragpipe on the CPTAC GBM phospho data and had the similar problem. Please see the log file attached. Thanks!
[log_2022-11-05_03-42-10.txt](https://github.com/Nesvilab/FragPipe/files/9946856/log_2022-11-05_03-42-10.txt)

**Comment by fcyu** [comment]
Yes, we have the pre-release that fixes this issue.

Please send an email to yufe AT umich.edu get the download link.

Best,

Fengchao

**Comment by fcyu** [comment]
We have released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
