### ISSUE TITLE
Another crash, while loading the data

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#652]
Error while loading a TIMS-TOF file on the software. looks like it crashes on a specific file. is it a file problem?

Thanks!
David.
[log_2022-04-18_13-14-42.txt](https://github.com/Nesvilab/FragPipe/files/8505040/log_2022-04-18_13-14-42.txt)

**Comment by fcyu** [comment]
Hi David,

Correct, your .d folder has been corrupted. Please double check your files.

Best,

Fengchao
