### ISSUE TITLE
New isobaric labels for FragPipe

### ISSUE THREAD

**Issue by CNChomiX** [Nesvilab/FragPipe#655]
There are only isobaric labels of TMT6, TMT10, TMT11, TMT16, iTRAQ4 and iTRAQ6 in FragPipe. If I use TMT2plex or TMT analogues, how can I add these custom labels by myself? Thanks.

**Comment by fcyu** [comment]
The TMT-2 (126, 127C) support has been implemented in https://github.com/Nesvilab/FragPipe/commit/21533c15646e3f5eef84f8abbd426b219c24644b. If you want to test the pre-released version, please send an email to yufe AT umich.edu. We will release a formal version soon.

Best,

Fengchao
