### ISSUE TITLE
MS Fragger V17.0_Peptide file missing

### ISSUE THREAD

**Issue by LakminiSenavirathna** [Nesvilab/FragPipe#656]
Hi,
I have used MS Fragger V14.0 for my analysis and the analysis was completed successfully, it generated a peptide (TSV ) file and an interact file.  I recently tried to work again on v14.0, however, my windows updates seemed not to support the v14.0 and, then I installed the newer version V17.0 of MSFragger. I wanted to follow the same type of analysis using v17.0, but the newer version does not create the peptide file and, the log file shows some tasks are canceled. I attached both log files Exp1 for the earlier version and Exp2 for the newer version. Could you please let me know what should be changed to get the peptide file in my results folder ? I want to perform the same analysis  that I have done using V14.0.
[log_Exp1.txt](https://github.com/Nesvilab/FragPipe/files/8525435/log_Exp1.txt)
[log_Exp2.txt](https://github.com/Nesvilab/FragPipe/files/8525436/log_Exp2.txt)

Thanks,
Lakmini

**Comment by fcyu** [comment]
Hi Lakmini,

Please upgrade the Philosopher and try again. If the error persist, please send the log file.

Best,

Fengchao

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

OK, I will update and try again. ! Thanks.

Lakmini

**Comment by LakminiSenavirathna** [comment]
Hi Fengchao,

I updated Philosopher and the problem was solved. Thank you very much for the advice.

Lakmini

**Comment by fcyu** [comment]
No problem. Please feel free to contact us if you have any questions in the future.

Best,

Fengchao
