### ISSUE TITLE
SQLITE_CORRUPT[11]: database disk image is malformed

### ISSUE THREAD

**Issue by anfoss** [Nesvilab/FragPipe#667]
**Describe the bug**

I am searching 30 DDA-PASEF file with LFQ-MBR but Fragpipe fails with the error : sumich.ms.fileio.exceptions.FileParsingException: umich.ms.fileio.filetypes.bruker.BrukerException: Error reading PASEF spectra with tims_read_pasef_msms_for_frame_v2(): SQLITE_CORRUPT[11]: database disk image is malformed

The file which cause the error can be searched as standalone file with the same pipeline without this error (either by using the MZbin or the .d).

I am attaching the log file 
[log_2022-05-01_18-46-50.txt](https://github.com/Nesvilab/FragPipe/files/8600441/log_2022-05-01_18-46-50.txt)

**Comment by fcyu** [comment]
The log says that the file is corrupted. Please check your computer's file system and files.

Best,

Fengchao

**Comment by fcyu** [comment]
The file system issue normally hard to reproduce. Can you try it again with and without many files?

**Comment by anfoss** [comment]
That is exactly what I am reporting that this MS file can be run individually without issues while with other file it loads and fails.

**Comment by fcyu** [comment]
As you can see from the log, MSFragger loads each file sequentially. There are many reasons causing MSFragger failed to load the file. Mostly due the the issue of your disk (the log also said that "database disk image is malformed"). If you think there is something that we should fix, can you send your files to us? 

Best,

Fengchao

**Comment by anfoss** [comment]
I understand that MSfragger loads each file sequentially but if it would be an issue from our end (like a thermo corrupted file) I will not be able to search it in any search engine/open it. 

I can convert this file, search it within Fragpipe and MaxQuant, convert it using MSconvert and open it using data analysis in Hystar, so the file is clearly fine, what would be the reason that when loaded with other file makes it corrupted?

**Comment by fcyu** [comment]
> There are many reasons causing MSFragger failed to load the file. Mostly due the the issue of your disk (the log also said that "database disk image is malformed").

It could be your file system's issue which causes MSFragger failed to load the file **at that moment**. Can you try to reproduce the error? If you can reproduce it, can you remove all other .d and try again without changing any other settings?

Again, if you think there is something that we should fix, can you send **all** of your files to us because we cannot reproduce it with our own files?

Best,

Fengchao

**Comment by fcyu** [comment]
Can you try again with all 30 files? 

Here (https://www.dropbox.com/sh/ze66kwto1iwuatg/AABfcfHqjilAwWFO3XFwKVsza?dl=0) is the link to upload the files.

Best,

Fengchao

**Comment by anfoss** [comment]
Figured it out, seems that if I assign names automatically with 'by filename' in the main msfragger tab it fails while if I do it sequentially or add them by hand it does not.

**Comment by fcyu** [comment]
Although I don't think assigning experimental names by filename would cause any issue, I am glad that you figured it out.

Best,

Fengchao
