### ISSUE TITLE
EasyPQP uses 100% of cpu resources

### ISSUE THREAD

**Issue by karlssoc** [Nesvilab/FragPipe#668]
**Describe the bug**
EasyPQP uses 100% of cpu resources. 

Fragpipe is an excellent software that I mostly run on a server also used by several others. For FragPipe workflows I limit the RAM and Parallelism under the FragPipe Workflows tab not to bog down resources for other users. However these limits seem not to apply for EasyPQP where I get 100% usage during convert steps. It would be great if the global workflow limits also would apply for EasyPQP.

Thanks,
Christofer

----------------------
![f](https://user-images.githubusercontent.com/36695929/166660193-2af73e92-3429-49b2-975f-620d7d43cbf9.jpg)

**Comment by fcyu** [comment]
Hi Christofer,

This is a know issue: https://github.com/Nesvilab/FragPipe/issues/567

Guo Ci @guoci , is there any update regarding this bug?

Best,

Fengchao

**Comment by guoci** [comment]
@karlssoc since you are on Linux, you can use `taskset` command to restrict the number of cores for a process. See:
https://serverfault.com/questions/250545/taskset-core-numbers-question

**Comment by fcyu** [comment]
Close duplicated issue.
