### ISSUE TITLE
Metaproteomics searches with Fragpipe

### ISSUE THREAD

**Issue by DianaSamodova** [Nesvilab/FragPipe#670]
Hello,
I was wondering whether it would be possible to perform filtration of results with Philosopher at 100% peptide FDR? If yes, could you, please, help me with the corresponding command? Thank you in advance. 
Regards,
Diana

**Comment by fcyu** [comment]
Hi Diana,

The flags for the filter command should be `--ion 1 --pep 1 --pepProb 0 --prot 1 --protProb 0 --psm 1 --razor`. You also need to add `--minprob 0` to ProteinProphet command, and set `min probability` to 0 for PeptideProphet or Percolator.

FYI, here (https://github.com/Nesvilab/philosopher/wiki/Filter) is the document of the filter command.

Best,

Fengcao

**Comment by DianaSamodova** [comment]
Thank you very much, Fengcao! I’ll give it a try.
Best,
Diana

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao

**Comment by DianaSamodova** [comment]
Hi Fengcao,
I have conducted a search at 100% FDR, however, I am not sure that MS1 intensity has been quantified with the current filtration settings. On the other hand, to perform LFQ, the data got filtered at 1% FDR. Do you know, whether it would be possible to also perform LFQ at a 100% FDR and if yes, what shall I change in the settings? Thank you.
Best regards,
Diana

**Comment by DianaSamodova** [comment]
Sounds reasonable, thank you. I’ll set MRB FDR to 100% as well.
Best,
Diana

**Comment by DianaSamodova** [comment]
Hi Fengcao,
I have managed to get protein intensities at a 100% FDR, however, I don’t see the peptide score in the output files, in order to perform manual adjustment for 1%FDR.
Is there any possibility to retrieve the score values? As far as I remember, there were multiple score versions (next score etc) available in the previous FragPipe versions.
Thanks in advance.
Best wishes,
Diana

From: Diana Samodova
Sent: 11. maj 2022 12:30
To: 'Nesvilab/FragPipe' ***@***.***>; Nesvilab/FragPipe ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Nesvilab/FragPipe] Metaproteomics searches with Fragpipe (Issue #670)

Hi Fengcao,
I have conducted a search at 100% FDR, however, I am not sure that MS1 intensity has been quantified with the current filtration settings. On the other hand, to perform LFQ, the data got filtered at 1% FDR. Do you know, whether it would be possible to also perform LFQ at a 100% FDR and if yes, what shall I change in the settings? Thank you.
Best regards,
Diana

**Comment by DianaSamodova** [comment]
Hi Fengchao,
Thanks for your reply! For now I have only gotten psm.tsv files for each raw file separately (not a combined_psm.tsv) output file, but I guess its something to do with the workflow selection? I guess I have to remove the “experiment” names, in order to obtain a combined psm.tsv file for all raw files? Thanks again.
Best,
Diana

**Comment by fcyu** [comment]
Yes, if you want to have all PSMs in a single psm.tsv, you need to remove "experiments" and "bioreplicate".

Best,

Fengchao

**Comment by DianaSamodova** [comment]
Great! Will do. Thanks a lot for your help.
Best,
Diana
