### ISSUE TITLE
PTMProphet failing to execute

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#671]
PTMProphet failing to execute.
Getting this error: Cannot execute program. chdir M:.: The system cannot find the path specified.
Can you explain to me how to fix this please?

I ran the program twice with a slight variation in the PTMProphet settings, so there are two logs attached.
----------------------

[log_2022-05-10_09-00-26.txt](https://github.com/Nesvilab/FragPipe/files/8656517/log_2022-05-10_09-00-26.txt)
[log_2022-05-09_19-38-25.txt](https://github.com/Nesvilab/FragPipe/files/8656518/log_2022-05-09_19-38-25.txt)

**Comment by ndtivendale** [comment]
OK. I've done that, and I got the same result.
[log_2022-05-11_12-48-51.txt](https://github.com/Nesvilab/FragPipe/files/8666883/log_2022-05-11_12-48-51.txt)

**Comment by prvst** [comment]
A few adjustments;

1. Please use the latest release (v4.2.1), not the experimental release candidate (philosopher-v4.2.2-PTMp.exe). The release candidates might contain temporary changes that might not be considered for the final version. In your case, we just want to pinpoint the problem, so let's start with the latest stable version.

2. Please, also update FragPipe with the latest version.

**Comment by ndtivendale** [comment]
@prvst OK, but you said previously on another thread: @ndtivendale You had an issue because the version you have does not know how to read a TAIR database header. You can grab a pre-release version which contains the function you need

https://www.dropbox.com/work/Public/Philosopher/Release%20Candidate

**Comment by ndtivendale** [comment]
Also, isn't 17.1 the latest version on Fragpipe?

**Comment by ndtivendale** [comment]
Tried again with v4.2.1 of Philosopher and PTMProphet still did not execute.
[log_2022-05-12_07-54-08.txt](https://github.com/Nesvilab/FragPipe/files/8674029/log_2022-05-12_07-54-08.txt)

**Comment by anesvi** [comment]
I see you are passing the following
mods

STY:79.966331,MP:15.9949,K:42.0106,EKR:14.0157,M:-21.9877, M:-4.9863, ]^:42.0106

First , you need to get rid of spaces

Second, you are doing some kind of crazy search. I am not sure any localization tool can handle it.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prvst** [comment]
@ndtivendale We are talking about two separate issues. I added the TAIR support to the latest release candidate; the PTMProphet is path issue is different so we need to test it with the current version. Usually path errors are problems related to the computer itself. Are you running the program on a cluster or a system with a limited tmp folder?

**Comment by ndtivendale** [comment]
@prvst Ah, I see. thank you.

I'm not sure what a cluster system is and I'm not sure about the size of the temp folder.

@anesvi I removed the spaces and that got ride of one error, but now I am getting a runtime error. Is this due to my 'crazy search'? If so, is it possible to get rid of? Error text below.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
FATA[10:18:14] Cannot execute program. there was an error with PTMProphet, please check your parameters and input files 
Process 'PtmProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by anesvi** [comment]
We never used PTM-prophet for more than 1-2 mods. Cannot help you here. Just uncheck PTM-prophet. Or do simpler searches with Less modifications.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ndtivendale** [comment]
Ah, I see. Thanks.
