### ISSUE TITLE
Will FragPipe integrate denovo peptide sequencing tools in the future?

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#672]
Just like the integration of PepNovo in OpenMS, the recent open source tools for denovo peptide sequencing based on deep learning, such as deepnovo or casanovo, are of great significance for the development of computational proteomics. I don’t know if the team has plans in this area in the future.

**Comment by fcyu** [comment]
I guess we will not.

Best,

Fengchao
