### ISSUE TITLE
Where is SPC output for running SAINT?

### ISSUE THREAD

**Issue by ttessie2** [Nesvilab/FragPipe#673]
Last time I was using MSfragger/fragpipe there were spectral count and intensity files for direct input to SAINT. I'm only getting the reprint.int file and not the SPC anymore. Has something changed or am I doing something wrong?

**Comment by fcyu** [comment]
This is weird. Both reprint.int and reprint.spc should be there. Can you send us the log file?

Thanks,

Fengchao

**Comment by ttessie2** [comment]
[log_2022-05-09_19-34-32.txt](https://github.com/Nesvilab/FragPipe/files/8665504/log_2022-05-09_19-34-32.txt)

**Comment by fcyu** [comment]
Thanks for the log file. For the current version, you need to check `generate protein-level summary` in the `FDR filter and report` panel. In the future version, that option it not necessary if you have IonQuant checked.

Best,

Fengchao

**Comment by ttessie2** [comment]
Thank you!
