### ISSUE TITLE
SILAC run

### ISSUE THREAD

**Issue by drstiltz** [Nesvilab/FragPipe#675]
[log_2022-05-11_12-33-06.txt](https://github.com/Nesvilab/FragPipe/files/8671824/log_2022-05-11_12-33-06.txt)

Hello,
I'm trying to identify the proteins in a SILAC run where there are only 2 heavy isotopic amino acids. For some reason the MS1 quantification through IonQuant fails. What would be the primary reason?

**Comment by fcyu** [comment]
You only run MSFragger and IonQuant, which is not enough. You need to run Percolator, ProteinProphet, FDR filter, and report.

Please load the SILAC related workflow, adjust the var mods and labels, and try again.

Best,

Fengchao
