### ISSUE TITLE
Moxidation and phenylalanine

### ISSUE THREAD

**Issue by apataskar** [Nesvilab/FragPipe#679]
Hi, I am trying to detect a mutant protein that has W->F or W->M substitution. Now, I want to detect both of them using Philosphoer and see which one is there in cancer proteomes (CPTAC). But, M-oxidation has the same mass as F. I wonder how does PEPQUERY handle this sameness in mass. When I detect W->F, I want to control that with W-> Moxi as well to be 100% sure it is W->F. Can Phislosopher be used for this purpose?

Looking forward to hear from you.

Thank you :)

Abhijeet Pataskar

**Comment by prvst** [comment]
I believe this question is related to the database search, but other tools might have some play, so I'm transferring here for everyone to see.

**Comment by fcyu** [comment]
If two things have the identical mass, I don't think you can separate them since by the nature of mass spectrometry, the only information you have is mass and intensity. Unless one of the modifications is labile and/or has diagnostic ion.

Best,

Fengchao

**Comment by dpolasky** [comment]
I think the masses of M+oxidation and F actually differ by 0.033 Da, which should be enough to separate them in high mass accuracy data. Using narrow mass tolerances in the MSFragger search (like 10 ppm) should be sufficient to prevent matching M-ox for an F and vice versa for most peptides

- Dan
