### ISSUE TITLE
SILAC results file

### ISSUE THREAD

**Issue by drstiltz** [Nesvilab/FragPipe#680]
Hello,

I'm having trouble understanding the results from a SILAC run.
In the main proteome file, I can see the labelled proteins and how many labels there were, but i
[log_2022-05-12_16-05-47.txt](https://github.com/Nesvilab/FragPipe/files/8695931/log_2022-05-12_16-05-47.txt)
n the `labelled` proteome file, the number of proteins is much lower and not all of them have high/low ratios. Some ratios are 0, so would that mean that there is no labelled peptide in that protein?

Would there be an easy way to compare the peak intensities for labelled and unlabelled proteins in SILAC?

**Comment by fcyu** [comment]
> In the main proteome file, I can see the labelled proteins and how many labels there were, but i
n the labelled proteome file, the number of proteins is much lower and not all of them have high/low ratios.

What is the "main proteome file"? Can you tell us the file name? That is the file name of the "labelled proteome file"?

> Would there be an easy way to compare the peak intensities for labelled and unlabelled proteins in SILAC?

I am not sure if I follow the question. If you were talking about comparing the intensities of light-labeled proteins and medium/heavy-labeled proteins, you can use the log-ratios in the protein_label_quant.tsv file.

Best,

Fengchao

**Comment by fcyu** [comment]
Also, it looks like your fasta file does not have any decoy proteins, which makes your result not meanful. Please read the tutorials from https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html (and probability also https://fragpipe.nesvilab.org/docs/tutorial_silac.html) before using FragPipe.

Best,

Fengchao

**Comment by drstiltz** [comment]
Hello there,

The tutorial says using decoy databases is optional. Considering, I'm doing an untargeted total proteome search in my sample, a regular UniProt FASTA file of human proteome would be sufficient. Am I wrong? However, In the labelled proteome file, for most of my proteins, I see 0 H/L ratio, which is not what I expect. Also, I have two different isotopic amino acids in my sample and is it possible to separate the protein hits by the ones that have only one heavy amino acid with the ones that have two of them? I'm trying to get the average labelling efficiency in my whole protein mix.

**Comment by danielgeiszler** [comment]
>The tutorial says using decoy databases is optional. Considering, I'm doing an untargeted total proteome search in my sample, a regular UniProt FASTA file of human proteome would be sufficient. Am I wrong?

Would you mind pointing out where it says this? You probably want a decoy database in order to validate your hits. This is a standard search.

**Comment by fcyu** [comment]
> The tutorial says using decoy databases is optional. 

It would surprise me if the tutorial literally says that. Could you paste the sentence here?

> Considering, I'm doing an untargeted total proteome search in my sample, a regular UniProt FASTA file of human proteome would be sufficient. Am I wrong?

I don't think we should give the advice regarding how to do your own research. But you need to add decoy proteins to your fasta file by clicking "add decoy" in the Database tab of FragPipe.

> However, In the labelled proteome file, for most of my proteins, I see 0 H/L ratio, which is not what I expect. Also, I have two different isotopic amino acids in my sample and is it possible to separate the protein hits by the ones that have only one heavy amino acid with the ones that have two of them? I'm trying to get the average labelling efficiency in my whole protein mix.

I am not sure if I follow it. But in bottom-up proteomics, it is difficult to assign the same peptide sequence with different labeling to different proteins. 

For the basic research questions, I suggest you read the literatures. We normally only answer questions regarding using our tools.

Best,

Fengchao

**Comment by drstiltz** [comment]
Apologies, I understand. I thought the decoy data was automatically created during the run, if a file was not added. I had never created one before.
