### ISSUE TITLE
Issue with spectral library build and DIA pipeline

### ISSUE THREAD

**Issue by cantrelllee** [Nesvilab/FragPipe#681]
Hi, I've been having issues with building a spectral library from DIA and DDA files for quite some time. Recently I was able to do this on one or two files from only DIA inputs, but was testing DDA and DIA combined inputs for spectral library build and subsequent quantitation. 

My CPU has 64 GB of RAM, run on auto RAM in setup. I was sitting at 59 GB of RAM for most of the main search of 51 DIA files. Previously, this is where MSFragger has crashed for me. Now it seems to be crashing in Easylib generation. The error code is nondescript to me, but maybe you have ideas? Log file attached alongside lines from log in Easy PQP convert. 

Thanks, 

Lee

-- done [took 0.00 s (CPU), 0.02 s (Wall)] -- 
EasyPQP convert error END
EasyPQP convert error BEGIN
Info: Converting F:\Scratch\20220514_DDADIA_Mods\interact-pEX1_lsc_6051_20220121_53_1_IN_rank2.pep.xml.
Info: Parsing run pEX1_lsc_6051_20220121_53_1_IN.
Info: Parsing pepXML.
EasyPQP convert error END
EasyPQP convert error BEGIN
Info: Converting F:\Scratch\20220514_DDADIA_Mods\interact-pEX1_lsc_6051_20220121_53_1_IN_rank4.pep.xml.
Info: Parsing run pEX1_lsc_6051_20220121_53_1_IN.
Info: Parsing pepXML.
Traceback (most recent call last):
  File "C:\Users\cantrls1\Downloads\FragPipe-17.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 965, in <module>
    main_easypqp()
  File "C:\Users\cantrls1\Downloads\FragPipe-17.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 786, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
EasyPQP convert error END
EasyPQP convert error BEGIN
Info: Converting F:\Scratch\20220514_DDADIA_Mods\interact-pEX1_lsc_6051_20220121_53_1_IN_rank5.pep.xml.
Info: Parsing run pEX1_lsc_6051_20220121_53_1_IN.
Info: Parsing pepXML.
EasyPQP convert error END
EasyPQP convert error BEGIN
Info: Converting F:\Scratch\20220514_DDADIA_Mods\interact-pEX1_lsc_6051_20220121_53_1_ON_rank1.pep.xml.
Info: Parsing run pEX1_lsc_6051_20220121_53_1_ON.
Info: Parsing pepXML.
EasyPQP convert error END
EasyPQP convert error BEGIN
EasyPQP convert error END
EasyPQP convert error BEGIN
EasyPQP convert error END
EasyPQP convert error BEGIN
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 4 remaining tasks


[log_2022-05-16_11-06-31.txt](https://github.com/Nesvilab/MSFragger/files/8701910/log_2022-05-16_11-06-31.txt)

**Comment by guoci** [comment]
@cantrelllee can you also post the folder `easypqp_logs`?

**Comment by cantrelllee** [comment]
[easypqp_logs.zip](https://github.com/Nesvilab/FragPipe/files/8702079/easypqp_logs.zip)

**Comment by cantrelllee** [comment]
Sure, thanks for the help @fcyu and @guoci . I'm also running a less lengthy sample set now with ~5% of the data attempted in the post above. Will see if it replicates the error. I was able to run the speclib pipeline from only DIA files earlier this week. The changes here are the addition of DDA and deamidation as a PTM.

**Comment by guoci** [comment]
some of the commands with non-zero exit status have incomplete output, but I do not know what is causing the error.
can you try rerunning the EasyPQP step to replicate it?

**Comment by cantrelllee** [comment]
How can I do this without restarting the pipeline?

**Comment by guoci** [comment]
you can uncheck all other steps, then click on run

**Comment by cantrelllee** [comment]
This appears to have worked. I have significantly more complete peptide IDs with this than with DIA-NN library free search. The DDA data for library only contributes about 2500 proteins to the matrix with DIA contributing about 1000 distinct protein groups. In total, 3500 proteins identified in the FragPipe/MSFragger pipeline. DIA-NN library free search found ~5000. 

I anticipate many of these proteins to degrade, and biologically it is suitable to suggest that ~1000 proteins are seen in all samples. Oddly, most of my samples have 2500 shared protein groups with ~3000 proteins measured in cells where we anticipate very few. I saw that the tolerance on DIA-NN exceeded 25 ppm for some samples with a calibrated mass accuracy below 3 ppm at MS1 and MS2 levels. 

I'm going to do some correlation/quantitative distribution analysis between the two search approaches, but before I get too deep in the weeds on this, is there some reason why this may have occurred?

**Comment by fcyu** [comment]
> I have significantly more complete peptide IDs with this than with DIA-NN library free search. The DDA data for library only contributes about 2500 proteins to the matrix with DIA contributing about 1000 distinct protein groups. In total, 3500 proteins identified in the FragPipe/MSFragger pipeline. DIA-NN library free search found ~5000.

Do you mean that DIA-NN library free search got more proteins? It is difficult for us to comment with such little information. Maybe you can share the log files with us as a start.

Best,

Fengchao
