### ISSUE TITLE
Error when searching .d files 

### ISSUE THREAD

**Issue by humility3239** [Nesvilab/FragPipe#682]
Hi, We searched 14 .d files(4-D proteomics files) by Fragpipi V17.0 with "IonQuant" and "Match between runs" picked. However, The session failed with the errors below.

![f8bcd6f017502fbb0f8917ad053b650](https://user-images.githubusercontent.com/65068128/168703852-ac3ae3bd-b1e8-4726-b387-ce3041b6c302.jpg)

<img width="687" alt="7b627e6fe506b7056a1e5809da7f85d" src="https://user-images.githubusercontent.com/65068128/168703875-eb4c2a13-9149-4392-bbb2-aac13a547ae0.png">

**Describe the bug**

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
For your first error, the files in the .d folder were corrupted.

For your second error, there is not enough free memory in your computer.

Best,

Fengchao

**Comment by humility3239** [comment]
Thanks, I will try to search again
