### ISSUE TITLE
IonQuant JRE failure

### ISSUE THREAD

**Issue by BrendonSeale** [Nesvilab/FragPipe#683]
Hello,

Whenever I attempt to run ionquant on a file I get a Java exception error. I have no clue where it's coming from. It's possible that it is isolated to this particular computer. It only happens with IonQuant and searches without it run fine.

I have attached both the FragPipe log and the Java pid error log it creates.

Wish I could tell you more but it doesn't seem to be associated to any of the options (fixed/variable modifications, quant options, different files, etc.) I have changed through various attempts.

Thanks!

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.
[hs_err_pid9392.log](https://github.com/Nesvilab/FragPipe/files/8710438/hs_err_pid9392.log)
[log_2022-05-17_13-08-43.txt](https://github.com/Nesvilab/FragPipe/files/8710439/log_2022-05-17_13-08-43.txt)

**Comment by fcyu** [comment]
They don't have much difference if you just run the java program.

Best,

Fengchao

**Comment by BrendonSeale** [comment]
Seems latest JDK (v 18) is ok, but latest JRE (v 8) was causing issues.
