### ISSUE TITLE
Philosofer error when processing phosphopeptide TIMS-ToF data

### ISSUE THREAD

**Issue by JesseIL** [Nesvilab/FragPipe#684]
I am processing 5 data files of TIMS-ToF Pro data in Fragpipe 17.1 for MS1 based quan of phosphopeptide data (I used the LFQ-phospho workflow). Am getting an error:
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

Attached is the log file.
Thanks,

Yishai
[log_2022-05-18_13-55-32.txt](https://github.com/Nesvilab/FragPipe/files/8715618/log_2022-05-18_13-55-32.txt)

**Comment by guoci** [comment]
That bug has been fixed (https://github.com/Nesvilab/FragPipe/issues/650#issuecomment-1102891564).
@prvst can you provide @JesseIL with the binaries?

**Comment by prvst** [comment]
Hi @guoci, feel free to share the URL too, it's the same from our Slack channel:

https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0
