### ISSUE TITLE
Downloading combined FASTA 

### ISSUE THREAD

**Issue by k-p4** [Nesvilab/FragPipe#688]
**Describe the bug**
When specifying multiple FASTA files to download in the databases section, the error message:

```
java.lang.IllegalStateException: Something happened during database download
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:175)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:281)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:172)
	... 1 more
```

repeatedly arises. This has been replicated on multiple machines and OSes.

**Comment by fcyu** [comment]
Can you copy and paste the whole text in the "Console" of the "Run" tab?

Thanks,

Fengchao

**Comment by k-p4** [comment]
Copy pasted the entire console:
```
13:59:03 INFO : Executing: D:\DataPC03_lab_files\fragpipe\tools\philosopher\philosopher.exe workspace --init --nocheck

13:59:03 INFO : Process output: 

13:59:03 INFO : Executing: D:\DataPC03_lab_files\fragpipe\tools\philosopher\philosopher.exe database --custom D:\DataPC03_lab_files\Raw_files\all_fastas\human_20220511.fasta\UP000005640_9606.fasta --contam --contamprefix

13:59:08 INFO : Process output: 

13:59:08 INFO : Executing: D:\DataPC03_lab_files\fragpipe\tools\philosopher\philosopher.exe workspace --clean --nocheck

13:59:08 INFO : Process output: 

13:59:08 INFO : Detected new or changed file: .meta

13:59:08 INFO : Detected new or changed file: .meta

13:59:08 INFO : Detected new or changed file: 2022-05-23-decoys-contam-UP000005640_9606.fasta.fas

13:59:10 INFO : No more file events when updating database

14:00:31 INFO : Database for download ID: UP000163834,UP000005640

14:00:44 INFO : Executing: D:\DataPC03_lab_files\fragpipe\tools\philosopher\philosopher.exe workspace --init --nocheck

14:00:44 INFO : Process output: 

14:00:44 INFO : Monitoring directory for file changes: D:\DataPC03_lab_files\Raw_files\all_fastas

14:00:44 INFO : Executing: D:\DataPC03_lab_files\fragpipe\tools\philosopher\philosopher.exe database --reviewed --contam --contamprefix --id UP000163834,UP000005640

14:00:45 INFO : Process output: 

14:00:45 INFO : No more file events when downloading database

14:00:45 ERROR: Something unexpected happened!

java.lang.IllegalStateException: Something happened during database download

	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:175)

	at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.IllegalStateException: Process returned non zero value

	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:281)

	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:172)

	... 1 common frames omitted


```

The error message appears as a separate "pop-up message as well"

I am specifying the fastas as: UP000163834,UP000005640. I also tried putting a space after the comma but the same error came up again.

**Comment by anesvi** [comment]
I just tried the same and confirm that I get an error too

**Comment by fcyu** [comment]
I reproduced it too. Philosopher throw errors when I ran the same command in command line:
![image](https://user-images.githubusercontent.com/6926299/169890447-2b3e1b80-23ec-42fb-9a87-7fae7c57587f.png)

Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by prvst** [comment]
There's no reviewed database for Rotavirus A, take the --reviewed out from the string. 

@anesvi  Should we download the unreviewed anyway in cases like this?

**Comment by anesvi** [comment]
Yes, I think so. And maybe print a warning that reviewed was not found, so unreviewed was downloaded instead

**Comment by prvst** [comment]
There's not a way to know if the reviewed exists or not, the query using the current parameters just won't return any data, we don't have a way to get the reason why from the API. I can default to fetch sequences from tremble, if the fetch from swissprot fails though.

**Comment by k-p4** [comment]
Thank you for the insights. In the interim would I be able to combine the two fastas as:


```
paste -d '' fasta_1 fasta_2 > fasta_3
```


and run fasta3 (subsequently adding decoys and contams)? 

Would this cause any issues in assigning proteins/unique peptides to organisms?

**Comment by fcyu** [comment]
Your solution should work. I cannot see any issues.

Best,

Fengchao

**Comment by fcyu** [comment]
Wait, `paste` command combines files "vertically". I think you should use `cat fasta_1 fasta_2 > fasta_3`.

Best,

Fengchao

**Comment by k-p4** [comment]
Yes, my mistake. ```cat``` should be used.
