### ISSUE TITLE
Error message when configuring FragPipe

### ISSUE THREAD

**Issue by Lutho5** [Nesvilab/FragPipe#689]
1. I downloaded FragPipe, MSfragger and Philosopher.
2. Unzipped all the folders
3. launched fragpipe from the bin folder
4.  It managed to locate philosopher ( had a dialog box saying, there are spaces in the path)
5.  It failed to locate MSfragger  (dialog box started with;  java.util.zip.ZipException: error in opening zip file... I have attached a screenshot)

**Comment by fcyu** [comment]
Please send the screenshot of the config tab.

Thanks,

Fengchao

**Comment by Lutho5** [comment]
Hi,

Please find attached

Regards

Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________

**Comment by fcyu** [comment]
Unfortunately, I cannot see the attachment. You need to login to GitHub, go to https://github.com/Nesvilab/FragPipe/issues/689, and add attachment there.

Best,

Fengchao

**Comment by Lutho5** [comment]
![msfragger error](https://user-images.githubusercontent.com/93644315/169889825-f4f0d3da-c3af-48b0-b460-f8aed58ced30.png)
![msfragger error](https://user-images.githubusercontent.com/93644315/169889889-209650b7-3845-41a0-b54b-483bac1deef9.png)

**Comment by Lutho5** [comment]
Hi,

I've attached it again


Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________

**Comment by fcyu** [comment]
Can you specify the correct MSFragger.jar path? Your path shows "N/A".

Best,

Fengchao

**Comment by Lutho5** [comment]
c:\Users\lutho\Downloads\MSFragger-3.4


Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________

**Comment by Lutho5** [comment]
![MSFragger file path](https://user-images.githubusercontent.com/93644315/169891732-1ac900ff-f7e4-4cc0-b76d-6f909bd958dc.png)
![MSFragger file path](https://user-images.githubusercontent.com/93644315/169891752-462340e3-5fd7-4995-b3be-2188fab1d096.png)

**Comment by fcyu** [comment]
Can you give `c:\Users\lutho\Downloads\MSFragger-3.4\MSFragger-3.4.jar` to the MSFragger config panel? You can also nevagate the select the MSFragger-3.4.jar by clicking "browse".

Best,

Fengchao

**Comment by Lutho5** [comment]
I used browse... I'll attach the screenshot


Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________

**Comment by Lutho5** [comment]
![SELECTED PATH USING BROWSE](https://user-images.githubusercontent.com/93644315/169893188-a63e7ba3-6a49-4d79-acd2-4f950e9ea434.png)
![SELECTED PATH USING BROWSE](https://user-images.githubusercontent.com/93644315/169893236-6fb2eeaa-8797-4f68-9ec8-917dd6824dba.png)

**Comment by fcyu** [comment]
The screenshot shows that it works. Are there any issues left?

Best,

Fengchao

**Comment by Lutho5** [comment]
No, nothing else. does this mean it will be able to pick up the path in the future? and do I need to save anything?


Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________

**Comment by fcyu** [comment]
Correct, FragPipe will save the paths to a cache file automatically. You don't need do anything.

Best,

Fengchao

**Comment by Lutho5** [comment]
Thanks a lot!

Kind Regards

Lutho Mbabala | BSc Hons (Molecular Biology) SU
PhD Candidate – MCB Group
Division of Molecular Biology and Human Genetics
Department of Biomedical Sciences
Faculty of Medicine and Health Sciences
Stellenbosch University

e: ***@***.***

a: BMRI, Francie van Zijl Drive, Tygerberg

________________________________
