### ISSUE TITLE
label-free quantification of multiple files

### ISSUE THREAD

**Issue by mwsaelee** [Nesvilab/FragPipe#690]
Hello,

I was wondering if there is a simple way to perform label-free quantification on multiple files. I found that when I run "philosopher freequant" in a folder/workspace with multiple result files, only the first result file in the folder would be processed instead of all the files being quantified. I was running MSFragger through command lines.

It seems that psm.bin which is required for  "philosopher freequant" is only created for the first result file in the folder. Short of running each result file in its own workspace, is there a simpler way to perform label-free quantification on multiple files?

Thanks

**Comment by fcyu** [comment]
Please use FragPipe and using the "LFQ-MBR" workflow. Here (https://fragpipe.nesvilab.org/docs/tutorial_lfq.html) is the basic workflow.

Best,

Fengchao
