### ISSUE TITLE
Percolator failing opening a file 

### ISSUE THREAD

**Issue by iolanda-vendrell** [Nesvilab/FragPipe#691]
Hi all, 
i have been experiencing problems when analysing DDA TIMS-TOF data from a set including 52 mass spec files. Percolator keeps crashing reporting it is unable to open a specific error "ERROR: Could not open the file xxx_psms.tsv for writing. Check if the folder exists and if you have permission to write." Initially this happens with one file, so I double checked that the file wasn't corrupted and ran it through Fragpipe alone and worked. Next, I removed that file and the FP crashed again with same error saying couldn't open another file. The error log is attached. 
I would appreciate if you could help. 

Many thanks in advance, 

best wishes, 

[FP_error_log_2022-05-25_14-47-19.txt](https://github.com/Nesvilab/FragPipe/files/8771942/FP_error_log_2022-05-25_14-47-19.txt)

**Comment by danielgeiszler** [comment]
There is no log attached here. Could you please try uploading it again?

**Comment by iolanda-vendrell** [comment]
Hi,
I have now uploaded. Also attached in this email,

Many thanks,

Best wishes,
Iolanda

**Comment by fcyu** [comment]
It looks like something was wrong with your file system. Can you restart everything and try again? For this type of error, it is difficult for us to troubleshot since we cannot reproduce it.

Best,

Fengchao

**Comment by iolanda-vendrell** [comment]
Hi Fengchao,
I have done the analysis few times, closing fragpipe and starting it again. What I haven’t done is to restart the PC, which I will do in half an hour or so…
Do you think that the file path is too long? I can try to change that.

Many thanks,

Iolanda

**Comment by iolanda-vendrell** [comment]
Good morning Fenchao,

I managed to get It working. The problem it was the folder path were I was saving the fragpipe output. It was too long
Thanks for you help. Much appreciated,

Best wishes,

Iolanda
