### ISSUE TITLE
How to output quantitative results of DDA and DIA in one task

### ISSUE THREAD

**Issue by thaumP** [Nesvilab/FragPipe#692]
Hi！

When I load both DDA and DIA .d data in Fragpipe, the Quant(MS1) screen is grayed out and this step is skipped when I run the whole workflow.

How can I output both MS1 and DIA-NN results based on the DDA and DIA loaded at the same time?

Thank you

**Comment by fcyu** [comment]
If you want to do DDA based MS1 quantification, you need to use ddaPASEF data only and load LFQ-MBR workflow.

If you want to do DIA based quantification, you can use both ddaPASEF and diaPASEF data. Then, the ddaPASEF data is used to build a spectral library, and the diaPASEF data is used to do quantification.

Best,

Fengchao
