### ISSUE TITLE
log4j vulnerability of FP-PDV

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#695]
Hi Fengchao

I was very pleased to see that the log4j vulnerability of DIA-Umpire (#580 ) has already been fixed in the latest release of FragPipe (v.18.0). Unfortunately, a re-run of our in-house log4j vulnerability scanner discovered log4j 1.2.13 to 1.2.15 in the newly implemented FP-PDV tool:

```
indicator for vulnerable component found in D:\...\fragpipe\tools\DIA_Umpire_SE-2.2.8.jar (org/apache/logging/log4j/core/lookup/JndiLookup.class): log4j 2.17.0
indicator for vulnerable component found in D:\...\fragpipe\tools\FP-PDV-1.0.1\lib\com.springsource.org.apache.log4j-1.2.15.jar (org/apache/log4j/net/SocketNode.class): **log4j 1.2.15**
indicator for vulnerable component found in D:\...\fragpipe\tools\FP-PDV-1.0.1\lib\com.springsource.org.apache.log4j-1.2.15.jar (org/apache/log4j/net/SMTPAppender.class): **log4j 1.2.15**
indicator for vulnerable component found in D:\...\fragpipe\tools\FP-PDV-1.0.1\lib\com.springsource.org.apache.log4j-1.2.15.jar (org/apache/log4j/net/JMSAppender.class): **log4j 1.2.15**
indicator for vulnerable component found in D:\...\fragpipe\tools\FP-PDV-1.0.1\lib\log4j-1.2.13.jar (org/apache/log4j/net/SocketNode.class): **log4j 1.2.13-1.2.14**
indicator for vulnerable component found in D:\...\fragpipe\tools\FP-PDV-1.0.1\lib\log4j-core-2.17.1.jar (org/apache/logging/log4j/core/lookup/JndiLookup.class): log4j 2.17.0
```

As I understand, is the security risk of log4j v.1.x less problematic than log4j < v.2.17, nevertheless I wanted to share these findings with you. Can you think of any problems I have to expect with the usage of FragPipe (apart from the loss of the viewer function), if I delete the tools/FP-PDV-1.0.1 folder as an intermediate security fix?

Best,
Christian

**Comment by danielgeiszler** [comment]
Hi @chscho ,

I ran a quick test deleting /tools/FragPipe-PDV-1.0.1/lib/log4j* and deleting the entire /tools/FragPipe-PDV folder and it didn't seem to cause any issues. I didn't test the headless version, so you're in uncharted water if you're running without the GUI. As a quick solution, it should work while we update the libraries.

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/FragPipe/commit/f19eb9de96bd79ef6ab62753058770dbc50e6a25.

Best,

Fengchao
