### ISSUE TITLE
0 pairs of modified / unmodified peptides ??

### ISSUE THREAD

**Issue by JM-Bader** [Nesvilab/FragPipe#702]
I ran a MSFragger search via FragPipe and wanted to characterize the PTMs in the output. 
I enabled oxidation (M) and N-term Ac as variable modifications and carbamylation (C) as fixed modification. 

These modifications do occur: 
![image](https://user-images.githubusercontent.com/98888664/171643859-fb05e9f4-5891-45a3-b528-f8a838353cd8.png)
![image](https://user-images.githubusercontent.com/98888664/171640761-56714f40-8307-4fac-80fa-6d503710ed1b.png)

However, very surprisingly there appear to be 0 pairs of modified / unmodified peptidoforms with identical stripped sequence: 

If there were such a single pair, then the number of unique stripped sequnces should be lower than the total number of stripped sequences. But this is not the case. 
![image](https://user-images.githubusercontent.com/98888664/171641051-1ce261b1-33f1-49ee-b45d-0be42efd54e6.png)

I then wondered whether the MSFragger output table structure could be different to what I expected (different entry rows for peptidoforms with identical stripped sequence). I realized this because different charge states (2,3) get aggregated into a single row and the entries are specified with a comma.  However, the comma annotation for modifications appears to indicate that both modifications are present on the same single peptidoform (instead of 2 independent peptidoforms occuring with either modification A or modification B or in an umodified state (== C)).
![image](https://user-images.githubusercontent.com/98888664/171643299-ff11fc5c-547a-4eae-ace9-ae7332bba9a5.png)
 
It appears quite unlikely to me that thousands of variably modified peptidoforms (in particular M oxidized) are detectable but not a single corresponding peptidoform without modification is detectable. 

Q1: Could this be a bug?? (As unmodified is indicated by NaN, maybe MSFragger tries to put both unmodified and modified into one entry (Assigned Modification = [NaN; ModificationXY]) and erroenously collapses this by removing the NaN >> only modified entry remains.
Q2: How would it look like  int the peptide output table if MSFragger detected both modified and unmodified peptidoforms of the same stripped sequence?

**Comment by JM-Bader** [comment]
Hi Fengchao, thank you for your swift reply!

I was using the peptides.tsv. 
I am not sure what you are mean with 'peptide is nonredundant'. Presumably you mean that different peptidoforms of the same stripped sequence don't get separate row entries in the peptides.tsv table. Correct? In that case, how is the existance of both modified and unmodified peptidoforms present in the peptides.tsv table? I would expect it then to be encoded in the "assigned Modifications" column but could not find it yet.  Unfortunately, this is not clear from the tutorial. 

I see that the modification status information should be clear from the combined_modified_peptides table. So I will look there now. Anyway it would be good to understand the logic behind the peptides.tsv table. Thanks!

**Comment by fcyu** [comment]
> I am not sure what you are mean with 'peptide is nonredundant'. Presumably you mean that different peptidoforms of the same stripped sequence don't get separate row entries in the peptides.tsv table. Correct?

Correct. The `peptide.tsv` file lists nonredundant **stripped** peptide **sequences**.

> In that case, how is the existance of both modified and unmodified peptidoforms present in the peptides.tsv table? I would expect it then to be encoded in the "assigned Modifications" column but could not find it yet.

The `assigned modification` column in `peptide.tsv` is the collection of all modifications from all modified peptides with the same peptide sequence. If you want to have different peptidoforms in separated rows, you need to look at the `ion.tsv` files. 

NOTE: you need to run IonQuant in the `Quant (MS1)` tab to have reasonable `ion.tsv` file. The `ion.tsv` file generated by Philosopher without IonQuant collapses peptidoforms with the same sequence, charge, and mass, which is not quite informative. 

> How do I get the combined_modified_peptide.tsv table?

You need to assign your runs to experiments/bioreplicates. BTW, why do your files have `C15Li02_` prefix? Did you add them after FragPipe finishing?

Best,

Fengchao

**Comment by JM-Bader** [comment]
> If you want to have different peptidoforms in separated rows, you need to look at the `ion.tsv` files.

I don't necessarily want them in separate rows, if the information is explicit in one row it's ok as well.
If in the peptide.tsv one row is the collection of all modification states, how is it clear whether i) only the modified version has been identified or ii) both the modified peptidoform (as specified in the "Assigned Modifications") AND the unmodified peptidoform were identified? Or is the information about the unmodified peptidoform omitted in the peptides.tsv table?


> You need to assign your runs to experiments/bioreplicates.

In my case, I quant a library for DIANN downstream. SO there are no bioreplicates/experiments. Does assigning them arbitrarily (just to get the combined_modified_peptide.tsv) modulate/change the results themselves in any way?



> BTW, why do your files have `C15Li02_` prefix? Did you add them after FragPipe finishing?

Well, I assign IDs to different libraries (or by extension search results) to keep an overview. Otherwise having multiple outputs can be messy. I added the ID prefix after getting the search results. BTW, having the option to specify an ID prefix within FragPipe would be nice, too.

**Comment by fcyu** [comment]
> I don't necessarily want them in separate rows, if the information is explicit in one row it's ok as well.
If in the peptide.tsv one row is the collection of all modification states, how is it clear whether i) only the modified version has been identified or ii) both the modified peptidoform (as specified in the "Assigned Modifications") AND the unmodified peptidoform were identified? Or is the information about the unmodified peptidoform omitted in the peptides.tsv table?

`peptide.tsv` file is not supposed to be used for peptidoform because they are collapsed. If you want the detailed info for each peptidoform, please use `ion.tsv`, `combined_ion.tsv`, or `combined_peptide.tsv`.

> In my case, I quant a library for DIANN downstream. SO there are no bioreplicates/experiments. Does assigning them arbitrarily (just to get the combined_modified_peptide.tsv) modulate/change the results themselves in any way?

You can assign all runs to a single experiment.

> BTW, having the option to specify an ID prefix within FragPipe would be nice, too.

Folder name serves as "prefix" here.

Best,

Fengchao

**Comment by fcyu** [comment]
Oh, also. Since your data is from DIA, please DO NOT enable `Quant (MS1)`. That option is for DDA only. I appoligize that I made an incorrect suggestion since I did not know that it is DIA data.

Then, if you want to have good information about peptidoform, you probability need to get it from psm.tsv file, or from DIA-NN's output after FragPipe running `Quant (DIA)`.

Best,

Fengchao

**Comment by JM-Bader** [comment]
> Oh, also. Since your data is from DIA, please DO NOT enable `Quant (MS1)`. That option is for DDA only. I appoligize that I made an incorrect suggestion since I did not know that it is DIA data.
> 
> Then, if you want to have good information about peptidoform, you probability need to get it from psm.tsv file, or from DIA-NN's output after FragPipe running `Quant (DIA)`.
> 
> Best,
> 
> Fengchao

Thanks for the addendum. In fact, the fraction raw files to create the library are DDA. So I guess I should still enable Quant (MS1). 
I only use the library for DIA searches with DIANN.

**Comment by anesvi** [comment]
The library will have the modifications on the peptide.  But not the localization info. Perhaps can contact us directly, as resolving peptidoforms in DIA data is not trivial, and hard to discuss via github I think.
We can also implement some specific suggestions you may have

Best
Alexey

**Comment by anesvi** [comment]
If you just want to build a library for DIA-NN to extract quant from DIA runs, you do not need enable MS1 quant in FragPipe
