### ISSUE TITLE
Discripency between Intensities (Log2Ratio) and Peptide prophet Scores for certain labels

### ISSUE THREAD

**Issue by MathewBerg9** [Nesvilab/FragPipe#710]
**Describe the bug**
Data output generated in ion_label_quant, peptide_label_quant have intensity values and Log2Ratio values in all labels (L,M,H), but peptide prophet values suggest that the peptide is detected in only 1 channel (H). 
How can there be an intensity ratio between two labels if the protein/peptides corresponding to that protein are only detected in 1 label not the other 2.?
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:
![Ion Label quant](https://user-images.githubusercontent.com/107181382/172820379-5fa27fcc-20d4-439c-abc1-d60dfd456d70.JPG)
![Peptide Label Quant](https://user-images.githubusercontent.com/107181382/172820392-f6d36da3-6617-4c6e-9b6c-1f43a3bf485d.JPG)
![Protein Label Quant](https://user-images.githubusercontent.com/107181382/172820589-5f48715d-6ee9-4528-998d-cf2c175ba214.JPG)
![MS Stats](https://user-images.githubusercontent.com/107181382/172820441-2c03b893-a8d6-462f-977d-fadcdb7ea953.JPG)
cdb.JPG)

- by clicking the `E
![MS Stats](https://user-images.githubusercontent.com/107181382/172820411-eff4b9a5-f799-4271-aa37-96d7931bf1dc.JPG)
xport Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
We use requantify to find the other peptide. For example, given a light one, we can find the heavy one if the heavy one is not identified.

Best,

Fengchao
