### ISSUE TITLE
FragPipe Open and DIA workflows error

### ISSUE THREAD

**Issue by AmeyShirolkar** [Nesvilab/FragPipe#711]
[log_2022-06-09_17-47-38.txt](https://github.com/Nesvilab/FragPipe/files/8870271/log_2022-06-09_17-47-38.txt)
[log_2022-06-09_15-45-30.txt](https://github.com/Nesvilab/FragPipe/files/8870282/log_2022-06-09_15-45-30.txt)
[log_2022-06-09_13-07-23.txt](https://github.com/Nesvilab/FragPipe/files/8870293/log_2022-06-09_13-07-23.txt)

[log_2022-06-09_00-46-10.txt](https://github.com/Nesvilab/FragPipe/files/8870299/log_2022-06-09_00-46-10.txt)

Hello Team, 

These are few error logs I am getting at FragPipie while using Open and DIA workflows.
Please help with this.
Regards.

**Comment by danielgeiszler** [comment]
These are all closed searches, but some of the open parameters have been turned on. 

"It is a closed search while localize_delta_mass = 1. Please change localize_delta_mass to 0."

You need to turn off the localize delta mass parameter in the MSFragger tab.

We recommend sticking with the default workflow parameters when possible.

**Comment by AmeyShirolkar** [comment]
hello Daniel,

Even after several attempts I am unable to trace the "localize delta mass parameter" in MS Fragger tab.
Exactly where it is located?

**Comment by fcyu** [comment]
Can you reload the workflow you want to use and try again? Most of the time, you don’t need to worry about most of the parameters.

Best,

Fengchao

**Comment by AmeyShirolkar** [comment]
hello Fengchao,

It is done for many times, reloading of workflows Turn on-Turn off FragPipe but not a single time I have reached till the endpoint.
Regards.

**Comment by fcyu** [comment]
The log shows that you loaded the workflow and then changed the precursor mass tolerance and unit, which you should not if you wanted to perform an open search.

Best,

Fengchao

**Comment by fcyu** [comment]
As to the last log from the DIA data analysis, there were not many IDs from your data, which crashed Philosopher. Also, you should not assign your data into experiments if you wanted to build a single spectral library. Here is the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_DIA.html

Best,

Fengchao

**Comment by AmeyShirolkar** [comment]
hello Team,

Open workflow errors,

[log_2022-06-10_17-33-09.txt](https://github.com/Nesvilab/FragPipe/files/8879934/log_2022-06-10_17-33-09.txt)
[log_2022-06-10_18-32-40.txt](https://github.com/Nesvilab/FragPipe/files/8879935/log_2022-06-10_18-32-40.txt)
Its still not working.

Even after submitting all files together (without assigning them into experiments) I was never able to make a DIA spectral library out of FragPipe, which format it would be, .tsv? Yes the given tutorial also didn't worked out.
Regards.

**Comment by fcyu** [comment]
For the open search, the error was from Crystal-C. You can disable it by unchecking it:
![image](https://user-images.githubusercontent.com/6926299/173095636-73349e55-7088-43bf-97d5-303c6a09ffdf.png)

For the DIA spectral building, I can see that you were using the settings from open search, changing the precursor unit to ppm but leave most of the other parameters the same, which is NOT RIGHT. Open search and DIA spectral building have a lot of differences. For example, your precursor mass tolerance was still from -50 to 500, and `lozalize_delta_mass` was still 1. 

Can you load the `DIA_SpecLib_Quant` workflow and try again? For most of the cases, you need to load the workflow each time, and try NOT change the parameters if you are not so sure.

Best,

Fengchao

**Comment by AmeyShirolkar** [comment]
hi Fengchao,
There is some confusion, we have mixed my 2 different issues.
I am unable to run open workflow, because I am detect this localize_delta_mass setting in MS Fragger.


For DIA I have used both the DIA workflows but either I am getting Java errors, or non zero exit codes 1 or 2, I am separately sending log files for that to you.
Regards.
