### ISSUE TITLE
MSFragger m/z and charge range settings for MS1 and MS2 ?

### ISSUE THREAD

**Issue by JM-Bader** [Nesvilab/FragPipe#716]
How do I set the following parameters in MSFRagger for a DDA search?

1) m/z range for precursors ?
2) m/z range for fragments ?
3) charge range for precursors ?

What is the default?
Or is it automatically detected from the raw file?

There are some settings that sound a bit similar but not quite what I am looking for or not really clear: 
![image](https://user-images.githubusercontent.com/98888664/173352083-06a6fd96-dbf8-4541-b4de-964c6c02ed64.png)

I could not find an explanation for "Min peaks" for instance on the github page: 
https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#Search-Parameters

Some of the settings in the github explanatory page appear to be what I am looking for but they don't appear on the MSFragger tab in FragPipe: 
![image](https://user-images.githubusercontent.com/98888664/173352882-e10c2fe9-35a1-4c97-8b2d-dbef1044aa2f.png)

**Comment by fcyu** [comment]
Thanks for your feedback, we have some explanations in the MSFragger repo. But we will add them to the FragPipe tutorial.

> m/z range for precursors ?

Default one (500 Da - 5000 Da) is good.

> m/z range for fragments 

I don't think we have this parameter. We use all peaks up to the precursor mass value in MS/MS.

> charge range for precursors ?

When there are charge info in your data, MSFragger uses it. If not, is uses 1-4 by default.

> There are some settings that sound a bit similar but not quite what I am looking for or not really clear:

Those are parameters for MSFragger. As you already found, they are explained in https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters

> I could not find an explanation for "Min peaks" for instance on the github page:

That one is called `minimum_peaks` in MSFragger parameters. Some of them have slightly different names between FragPipe and MSFragger `fragger.params`. But it should be straightforward to figure them out. Please let us know when you have questions.

> Some of the settings in the github explanatory page appear to be what I am looking for but they don't appear on the MSFragger tab in FragPipe:

The `precursor_charge` you listed is at the bottom of the MSFragger tab in FragPipe.

Best,

Fengchao

**Comment by JM-Bader** [comment]
> Default one (500 Da - 5000 Da) is good.

this is not an m/z range. It only concerns masses. 
Clearly, there is a link but charge states also play a role. 

For instance If I measure only from 300 - 1500 m/z (or any other range) - which is the actual parameter set at the MS, I want to set that range for precursors to that range. There is only a fuzzy overlap of boundaries between peptide mass (specifiable in MSFragger) and m/z ranges (actually set during acquisition).

**Comment by dpolasky** [comment]
There's no need to worry about matching a precursor outside the m/z range set during the instrument acquisition - if the instrument did not acquire any precursors larger than 1500 m/z (for example), MSFragger cannot match them because they are not present (so specifying it as a parameter would be redundant). There is not a way to restrict the m/z range specifically for the precursors within the window acquired by the instrument, but I'm not aware of an example where that would be needed (of course if you have one, please let us know!). 
Best,
Dan

**Comment by fcyu** [comment]
I agree with Dan. For the precursor mass range, if there is no signal, MSFragger won't use it to matching anything. MSFragger just need to constrain the peptide mass range so that it won't go crazy.

As to the MS/MS mz range, same logic here. All peaks with mz smaller than precursor mass will be used. Thus, there is also no need to set MS/MS mz range.

Best,

Fengchao

**Comment by fcyu** [comment]
> I record data on a Bruker timsTOF Pro. Can MSFragger extract the charge information from such raw files ?

Yes, it uses the charge info in the file.

> If not I presume it will use the default 1-4. In that case, there is a large search space (all potential +1 species) that inflate the decoy space (extra wrong 'targets' + complimentary decoys while real +1 precursors where excluded for MS/MS by the acquisition method). Due to FDR control, one would expect that the extra decoys reduce the achieved depth and also there will be additional wrong 'targets' (identified +1 peptides that are false). Not a show stopper, but it appears to me that this is not ideal.

If there is no charge info, which is quite rare, MSFragger will enumerate from 1 to 4. For high-res MS2, it won't harm the result too much.

Best,

Fengchao

**Comment by JM-Bader** [comment]
> There's no need to worry about matching a precursor outside the m/z range set during the instrument acquisition - if the instrument did not acquire any precursors larger than 1500 m/z (for example), MSFragger cannot match them because they are not present (so specifying it as a parameter would be redundant). 

Hi Dan, thanks for the swift reply. 
I agree that there is conceptional redundancy - at least roughly. 
However, first it can be both ways. The second filter in your case m/z can be more or less restrictive than the first - which also depends on how relaxed/restrictive the first one is. 

If I measure up to 1200 m/z and have a +4 charge precursor at around 1200 m/z it has a mass of 4,800 >> it is in the mass range 500 -5000. That's good. 

Conversely, however: Most/many peptides are +2. At 5000 Da this translates to 2500 m/z - this is much larger than my acquisition scheme will ever pick if I measure up to 1200. Clearly, 5000 Da is higher end of the spectrum and in normal digests not that many peptides are that large. However, the search spaces could include potential +2 peptides in the range from 1200 m/z to 2500 m/z (when specifying up to 5000 Da) that are never picked (when having an acquisition up to 1200 m/z at the instrument).  

I presume MSFragger limits the search space by subsetting the overall fasta search space (and including the corresponding decoy search space) to those peptides matching the picked precursor. Correct? 

If not, the search space would be inflated with peptides that can not be picked (which is expected to reduce depth via FDR control).

**Comment by dpolasky** [comment]
That's right, MSFragger only searches peptides (both target and decoy) that match the precursor mass. So in your example, +2 peptides with mass >2500 Da are in the theoretical search space, but will not be matched to any spectra (because there are no spectra with precursor charge = 2 and m/z > 1200) and so will not affect the FDR estimation or search results.
