### ISSUE TITLE
NullPointerException error on version 18.0

### ISSUE THREAD

**Issue by JLewisMicro** [Nesvilab/FragPipe#717]
[log_2022-06-10_12-19-35.txt](https://github.com/Nesvilab/FragPipe/files/8895127/log_2022-06-10_12-19-35.txt)

Hi Team,

After using FragPipe v18.0 to run some DDA data, the visualisation window was opened, but failed to load the data, running in an endless loop for over 24 hours. We forcibly shut the window, but since then, when we have tried running anything, we get the attached NullPointerException error. I've also tried running version 17.1 and that comes up with the same error. I've tried restarting the computer, and checked that java is up to date, but nothing has so far stopped the error. 

Do you know what causes the error and how to resolve it?

Thank you!
Jessica

**Comment by fcyu** [comment]
Hi Jessica,

Although I am not sure why the visualization windows messed up the cache files, but can you try 1) checking if all tools are configured in the "Config" tab; and 2) resetting it by clicking "clear cache and close":
![image](https://user-images.githubusercontent.com/6926299/173464892-c951d239-b550-4cb7-a75d-9ceb18427b27.png)

Best,

Fengchao

**Comment by JLewisMicro** [comment]
Hi Fengchao,

All tools were configured, but clearing the cache seems to have done the trick, it's running again now.

Thanks for your help,
Jessica
