### ISSUE TITLE
Cannot use Philosopher's freequant when Ionquant is not present

### ISSUE THREAD

**Issue by prvst** [Nesvilab/FragPipe#721]
The Freequant option should be possible to use in the absence of IonQuant

![image](https://user-images.githubusercontent.com/403705/173691045-afca906e-b77e-42f7-ab6b-d3172d434474.png)

**Comment by fcyu** [comment]
Can you send me the screenshot of the config and workflow tabs?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Oh, sorry, you said "in the absence of IonQuant". Yes, we require IonQuant to enable the Quant (MS1) tab. 

Best,

Fengchao

**Comment by prvst** [comment]
The freequant option should be available without ionquant , since they are not dependent on each other.

**Comment by fcyu** [comment]
Fixed in 18.1-build5
