### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#722]
**Describe the bug**
Trying to run a search but keep getting a Java heap space error. Help me please?
[log_2022-06-15_13-32-12.txt](https://github.com/Nesvilab/FragPipe/files/8914674/log_2022-06-15_13-32-12.txt)

**Comment by fcyu** [comment]
It looks like you were performing a search with very large search space:
```
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 1 # semi-specific searching
variable_mod_01 = 15.994900 MP 1
variable_mod_02 = 42.010600 [^ 1
variable_mod_03 = 79.966330 STY 1
variable_mod_06 = 42.010600 K 1
variable_mod_07 = 14.015700 EKR 1
variable_mod_10 = -21.987700 M 1
```

If those parameters cannot be changed, you can either 1) find a computer with bigger memory; or 2) increase the `split database` (in MSFragger tab) from 1 to, say, 4:

![image](https://user-images.githubusercontent.com/6926299/173969750-d547adeb-ccd5-479e-a02c-f5d66802ae96.png)

Best,

Fengchao

**Comment by ndtivendale** [comment]
Thanks. I'll try that. But the split database option is greyed out. Why would that be?

**Comment by fcyu** [comment]
You need to have Python configured. Here is a brief tutorial: https://fragpipe.nesvilab.org/docs/tutorial_setup_fragpipe.html

Best,

Fengchao

**Comment by danielgeiszler** [comment]
The split database function requires Python. Do you have that configured?

**Comment by ndtivendale** [comment]
Ah, yes, just needed to update to 3.9. There was no prompt that Python needed updating, so I hadn't bothered. Maybe include that as a feature in future FP releases?

**Comment by danielgeiszler** [comment]
Thanks for the suggestion! We'll take a look at.

**Comment by fcyu** [comment]
Hi @ndtivendale,

Thanks for your kind suggestion. But Python is not required when users don't need to use the split database or spectral library building. And we don't know if users want to use those two functions beforehand. Thus, showing a prompt might be annoying to most users.

After downloading a new FragPipe, it is a good practice to check the config tab to see if everything is good. If Python is not well configurated, "database splitting" and "spectral library generation" will display informative message. Then, those who want to use Python should configure it.

Best,

Fengchao

**Comment by ndtivendale** [comment]
That worked! I split it into 6. Thanks!
