### ISSUE TITLE
Are N-terminal acetylations on protein or peptide N-terminii?

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#725]
More of a question than a bug. When N-terminal acetylation is included as a variable modification, is the program looking for acetylation of peptide or protein N-terminii?

**Comment by danielgeiszler** [comment]
Protein n-termini are specified using [^, peptide n-termini are specific using n^.

**Comment by fcyu** [comment]
Hi @ndtivendale ,

FYI, please check the documentation about the variable modification setting from https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#Variable-Modifications

Best,

Fengchao
