### ISSUE TITLE
Where is unique intensity and total intensity in proteins_combined?

### ISSUE THREAD

**Issue by ttessie2** [Nesvilab/FragPipe#728]
I'm using the recent MSFragger update. Not sure if I've missed something because it has changed but the proteins_combined tsv file seems different than what it was in the previous version. Where are the columns for unique intensity and total intensity for example?

**Comment by fcyu** [comment]
We added an option in 'Quant (MS1)' to control the intensity uniqueness. You can change it as shown following
![image](https://user-images.githubusercontent.com/6926299/174932187-c79707a5-571d-45c6-8371-0c4fa595825e.png)

Best,

Fengchao
