### ISSUE TITLE
Fragpipe DIA-NN - Spectral library

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/FragPipe#730]
Dear Fragpipe team, 

I am using fragpipe together with DIA-NN, and I would like to use the library.tsv built from fragpipe together with another spectral library.
In DIA-NN tab, when I mouse over the field "Spectral library (optional)", it is written "Additional spectral library file. if blank, using library.tsv built from fragpipe." 
Does this mean that if I add a library here, this library will be used together with the one created by fragpipe, or that it will be used instead of the fragpipe's one?

If this is not used together with the one build by fragpipe, do you have any suggestion on how to run such analysis?

Thanks a lot for your help

**Comment by fcyu** [comment]
No, DIA-NN only uses the one in "spectral library (optional)" if it is not blank.

If you want to use multiple libraries, you can run DIA-NN standalone with multiple `--lib` flags.

Best,

Fengchao

**Comment by f-huber** [comment]
Hi Fengchao, 

That's what I thought, thanks a lot for your answer.

Best,

Florian
