### ISSUE TITLE
FragPipe open workflow errors

### ISSUE THREAD

**Issue by AmeyShirolkar** [Nesvilab/FragPipe#734]
hello Team FragPipe,

During analyzing a mouse data using a open workflow I am getting these various errors on FragPipe. Please provide your suggestions what rectifications I can do in this.
Regards.

[log_2022-06-24_00-33-49.txt](https://github.com/Nesvilab/FragPipe/files/8983791/log_2022-06-24_00-33-49.txt)
[log_2022-06-23_23-01-08.txt](https://github.com/Nesvilab/FragPipe/files/8983792/log_2022-06-23_23-01-08.txt)
[log_2022-06-23_20-38-04.txt](https://github.com/Nesvilab/FragPipe/files/8983793/log_2022-06-23_20-38-04.txt)
[log_2022-06-23_20-16-06.txt](https://github.com/Nesvilab/FragPipe/files/8983794/log_2022-06-23_20-16-06.txt)
[log_2022-06-23_15-07-37.txt](https://github.com/Nesvilab/FragPipe/files/8983795/log_2022-06-23_15-07-37.txt)
[log_2022-06-23_15-03-00.txt](https://github.com/Nesvilab/FragPipe/files/8983796/log_2022-06-23_15-03-00.txt)
[log_2022-06-23_12-54-39.txt](https://github.com/Nesvilab/FragPipe/files/8983797/log_2022-06-23_12-54-39.txt)

**Comment by danielgeiszler** [comment]
1. FragPipe cannot find the files it needs where they should be. This may be an issue with your local configuration. Please check with your coworkers if they are able to process the data as they could before, in which case we cannot help with this issue.
2. PeptideProphet cannot find the files it needs where they should be. This may be an issue with your local configuration. Please check with your coworkers if they are able to process the data as they could before, in which case we cannot help with this issue.
3. [We have already answered this question](https://github.com/Nesvilab/FragPipe/issues/711). You can disable Crystal-C to fix this.
4. [We have already answered this question](https://github.com/Nesvilab/FragPipe/issues/711). Do not change the precursor tolerance if you want to run an open search.
5. [We have already answered this question](https://github.com/Nesvilab/FragPipe/issues/711). Do not change the precursor tolerance if you want to run an open search.
6. You need more memory.
7. You need more memory.

**Comment by fcyu** [comment]
Hi @AmeyShirolkar ,

We have already answered your questions. For some of those questions, you need to find a local expert to troubleshoot them for you since they are related to your computer and system. Please do not submit the same questions.

I will close this issue. If you have new question, please submit a new one with the log file.

Best,

Fengchao

**Comment by AmeyShirolkar** [comment]
Sir,

For 1. yes my co-workers are able to process data in version 16.1 but I am
not in 18.1.
I have got a brief success only when I used mzML files instead of .raw but
data quality was compromised.
I will relook at PeptideProphet issue.
Regards.
