### ISSUE TITLE
custom added protein with '-' in the name is filtered out by Philosopher from the reports

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/FragPipe#735]
I found an issue (or rediscovered?)
I have a custom database with a sequence of high abundant, spike in protein. 
If I add the sequence as 
>alphaamylase
it is identified just fine

if I add as >alpha-amylase
Philosopher removes it from the report, it's gone

Is there a reason we cannot allow it? At least we should give a warning.

**Comment by prvst** [comment]
We don't have any rules prohibiting dashes in the names

**Comment by anesvi** [comment]
@prvst I think we fixed this?

**Comment by prvst** [comment]
yes, its fixed
