### ISSUE TITLE
TMT PhilosopherFilter error

### ISSUE THREAD

**Issue by Irkcy** [Nesvilab/FragPipe#736]
Dear developer:
 
     I ran Fragpipe 18.0 on Linux and encountered the following error：

time="19:29:34" level=info msg="Executing Filter  v4.2.2"
time="19:29:44" level=error msg="sync /mnt/workd/b32/.meta/razor.bin: input/output error"
panic: sync /mnt/workd/b32/.meta/razor.bin: input/output error

I have attached the log. By th way, does Philosopher 4.2.2 not support Thermo raw files?

Best,
Irkcy

[fraglog20220625.txt](https://github.com/Nesvilab/FragPipe/files/8986221/fraglog20220625.txt)

**Comment by fcyu** [comment]
Correct, Philosopher no long support Thermo raw files.

As to the error, everything looks find until Philosopher filter command:
```shell
PhilosopherFilter [Work dir: /mnt/workd/b32]
/usr/local/bin/philosopher filter --sequential --picked --prot 0.01 --tag rev_ --pepxml /mnt/workd/b32 --protxml /mnt/workd/combined.prot.xml --razorbin /mnt/workd/B1/.meta/razor.bin
time="19:29:34" level=info msg="Executing Filter  v4.2.2"
time="19:29:44" level=error msg="sync /mnt/workd/b32/.meta/razor.bin: input/output error"
panic: sync /mnt/workd/b32/.meta/razor.bin: input/output error

goroutine 1 [running]:
philosopher/lib/msg.callLogrus(0xc00017a200, 0x37, 0xc06177, 0x5)
	/workspace/philosopher/lib/msg/msg.go:319 +0x4c5
philosopher/lib/msg.Custom(0xd246e0, 0xc0001af860, 0xc06177, 0x5)
	/workspace/philosopher/lib/msg/msg.go:14 +0xa7
philosopher/lib/sys.CopyFile(0x7ffee37b0929, 0x1d, 0xc00012cb20, 0x1e)
	/workspace/philosopher/lib/sys/sys.go:114 +0x1cd
philosopher/lib/fil.Run(0xc000126450, 0x24, 0xc00012ad70, 0xe, 0xc000126480, 0x29, 0xc00012c4e0, 0x1d, 0xc00012c500, 0x14, ...)
	/workspace/philosopher/lib/fil/fil.go:37 +0x2585
philosopher/cmd.glob..func5(0x1d7f8a0, 0xc00018a180, 0x0, 0xc)
	/workspace/philosopher/cmd/filter.go:43 +0x469
github.com/spf13/cobra.(*Command).execute(0x1d7f8a0, 0xc00018a0c0, 0xc, 0xc, 0x1d7f8a0, 0xc00018a0c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1d81820, 0x460b00, 0xc0001c1f70, 0xc0001c1f68)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
	/workspace/philosopher/main.go:25 +0x7c
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping
```

Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by prvst** [comment]
The filter apparently worked fine for the first data set, where the razor was generated, then the following 28 datasets imported the data correctly with no issues. I do not know why suddenly the program gave you that error, and I'm afraid I can't do much from here because it seems to be related to your system. I did notice that you are pointing to files that are mounted from a external or temporary partition. Perhaps the connection dropped?

**Comment by Irkcy** [comment]
> Correct, Philosopher no long support Thermo raw files.
> 
> As to the error, everything looks find until Philosopher filter command:
> 
> ```shell
> PhilosopherFilter [Work dir: /mnt/workd/b32]
> /usr/local/bin/philosopher filter --sequential --picked --prot 0.01 --tag rev_ --pepxml /mnt/workd/b32 --protxml /mnt/workd/combined.prot.xml --razorbin /mnt/workd/B1/.meta/razor.bin
> time="19:29:34" level=info msg="Executing Filter  v4.2.2"
> time="19:29:44" level=error msg="sync /mnt/workd/b32/.meta/razor.bin: input/output error"
> panic: sync /mnt/workd/b32/.meta/razor.bin: input/output error
> 
> goroutine 1 [running]:
> philosopher/lib/msg.callLogrus(0xc00017a200, 0x37, 0xc06177, 0x5)
> 	/workspace/philosopher/lib/msg/msg.go:319 +0x4c5
> philosopher/lib/msg.Custom(0xd246e0, 0xc0001af860, 0xc06177, 0x5)
> 	/workspace/philosopher/lib/msg/msg.go:14 +0xa7
> philosopher/lib/sys.CopyFile(0x7ffee37b0929, 0x1d, 0xc00012cb20, 0x1e)
> 	/workspace/philosopher/lib/sys/sys.go:114 +0x1cd
> philosopher/lib/fil.Run(0xc000126450, 0x24, 0xc00012ad70, 0xe, 0xc000126480, 0x29, 0xc00012c4e0, 0x1d, 0xc00012c500, 0x14, ...)
> 	/workspace/philosopher/lib/fil/fil.go:37 +0x2585
> philosopher/cmd.glob..func5(0x1d7f8a0, 0xc00018a180, 0x0, 0xc)
> 	/workspace/philosopher/cmd/filter.go:43 +0x469
> github.com/spf13/cobra.(*Command).execute(0x1d7f8a0, 0xc00018a0c0, 0xc, 0xc, 0x1d7f8a0, 0xc00018a0c0)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1d81820, 0x460b00, 0xc0001c1f70, 0xc0001c1f68)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
> philosopher/cmd.Execute()
> 	/workspace/philosopher/cmd/root.go:35 +0x2d
> main.main()
> 	/workspace/philosopher/main.go:25 +0x7c
> Process 'PhilosopherFilter' finished, exit code: 2
> Process returned non-zero exit code, stopping
> ```
> 
> Felipe @prvst , can you take a look?
> 
> Thanks,
> 
> Fengchao



Thank you for your promt reply. It's still the same place reporting the error. But I ran successfully in GUI.

Best,
Irkcy

**Comment by anesvi** [comment]
Yes I think it is in the order entered.
But You should not use the same annotation file. There may be some issues.
Each sample should have a different name , and the bridge sample should be like poolb1, poolB32, ... all names differently


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
