### ISSUE TITLE
How to run IonQuant with FragPipe CLI

### ISSUE THREAD

**Issue by Munchic** [Nesvilab/FragPipe#737]
Hello! I noticed that the GUI version requires specifying IonQuant executable along with Philosopher and MSFragger. However, in the CLI version, there are only flags `--config-philosopher`, `--config-msfragger`. How do I get IonQuant to run as well? Thank you!

**Comment by fcyu** [comment]
Please find the solution from https://github.com/Nesvilab/FragPipe/issues/733#issuecomment-1165838214

Best,

Fengchao

**Comment by Munchic** [comment]
@fcyu thank you so much for your quick response!
