### ISSUE TITLE
No enzyme/endogenous peptides search

### ISSUE THREAD

**Issue by monicakruk** [Nesvilab/FragPipe#738]
Hello!

We would really appreciate any recommendations for a project. 

It seems I am maxing out the Java heap (log file attached) but trying again, so I wanted to ask what you recommend here:
We have 51 raw ms files we want to analyze. The samples were filtered to less than 3 kDa, basically all endogenous peptides or small proteins. We are searching against the a human database with contaminant files, about ~100k sequences x 2 for decoys. We want to quantify (no label used) the peptides/proteins and learn if there are any differences between the 51 samples. The number of files and type of search (no enzyme) seems to require a lot of processing power.

How would you recommend setting up this analysis on Fragpipe? Non-specific peptideome, LFQ-MBR, etc., amount of RAM (up to 64 GB), etc.? I've seen percolator find more peptides before in other samples, so we prefer that, but we might have to use PeptideProphet and split the database? 

Thank you for your time,
Monica
[log_2022-06-28_14-00-04.txt](https://github.com/Nesvilab/FragPipe/files/9004775/log_2022-06-28_14-00-04.txt)

**Comment by fcyu** [comment]
Hi Monica,

First of all, you'd better to upgrade FragPipe, MSFragger, IonQuant, and Philosopher to the latest version. Then, you need to use split database. `Nonspecific-peptidome` and `nonspecific-HLA` are different workflows with different peptide length ranges. You need to pick the one suitable for you. You also need to enable IonQuant to perform LFQ and MBR.

Best,

Fengchao

**Comment by dpolasky** [comment]
I would also add that if you're filtering the peptides in the sample to <3 kDa, you can set the peptide mass range in MSFragger to a max of 3000, which will filter out a lot of possible peptides and reduce the memory needed (may still need to use split database though). 

Best,
Dan
