### ISSUE TITLE
Issues with glyco workflow

### ISSUE THREAD

**Issue by Lerialapse** [Nesvilab/FragPipe#741]
Hi! I'm analyzing the glycopeptide data acquired on timsTOF SCP (analogous to timsTOF Pro) and get this error in course of analyisis.

```
Operating on slice 1 of 7: 
	Fragment index slice generated in 1.81 s
	001. CEAM_50ng_1_full_step_90k_Slot2-26_1_5940.mzBIN 0.7 s | deisotoping 0.4 s
There was an error in analyzing spectrum.
There was an error in analyzing spectrum.
Cannot read field "b" because the return value of "java.util.HashMap.get(Object)" is null
Cannot read field "b" because the return value of "java.util.HashMap.get(Object)" is null
There was an error in analyzing spectrum.
Cannot read field "b" because the return value of "java.util.HashMap.get(Object)" is null
There was an error in analyzing spectrum.
Cannot read field "b" because the return value of "java.util.HashMap.get(Object)" is null
There was an error in analyzing spectrum.
There was an error in analyzing spectrum.
Cannot read field "b" because the return value of "java.util.HashMap.get(Object)" is null
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

```
What is this field "b"? Is it instrument-related? Would be very grateful for ideas on how to solve it.

Kind regards,
Valeriia

**Comment by dpolasky** [comment]
Hi Valeriia, 
It looks like there was an issue reading the data file, but not sure why from the snippet - can you upload the complete log file? 

Best,
Dan

**Comment by Lerialapse** [comment]
[log_2022-06-30_10-51-01.txt](https://github.com/Nesvilab/FragPipe/files/9018079/log_2022-06-30_10-51-01.txt)

Thanks!

**Comment by Lerialapse** [comment]
One more question to piggyback on this one. What is the default list of N-glycan assignments? It's not very clear from the documentation. Moreover, the example file for the custom glycan DB is missing in the manual 
![image](https://user-images.githubusercontent.com/14138821/176636224-09124848-a7f4-422d-a1c2-931888aff873.png)
