### ISSUE TITLE
Dalton fragment accuracy issue in MSFragger

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#745]
**Describe the bug**
Hi,
I am analyzing DDA datasets from an LTQ-Orbitrap (high-low) in FragPipe v18. I set my fragment mass tolerance in the MSFragger tab to DA and 0.4 value.  The tolerances specified in the MSFragger params log and the new tolerance set after recalibration was not as I might expect.

First, the fragment_mass_units = 1 was still listed as PPM, and the fragment_mass_tolerance = 400.0.  Is this the expected result?  In my experience, the mass accuracies for ion trap-CID data are fairly uniform and I would prefer to specify a mass-independent fragment tolerance.

Second, after re-calibration, the new fragment mass tolerance set by MSFragger is 500 PPM.    This is unexpected given the pre and post-calibration median and MAD values for the data.  
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |   1.56   0.81 |   0.03   0.66 |  174.71  99.37 |  16.62  113.05  
-----|---------------|---------------|---------------|---------------

If this is not expected, perhaps it relates to my source files, which were mzxml, which I centroided and converted to mzml using Proteowizard's MSConvert.  I've attached the log file for analysis of one of these files, but I have many other files that produce the result described above.  let me know if it would be helpful to upload one of the data files.

Thanks,
Todd
----------------------
## If you're submitting a bug report, please attach log file

[log_2022-06-29_22-56-23.txt](https://github.com/Nesvilab/FragPipe/files/9016083/log_2022-06-29_22-56-23.txt)

**Comment by fcyu** [comment]
Hi Todd,

Following are my point-to-point answers.

> First, the fragment_mass_units = 1 was still listed as PPM, and the fragment_mass_tolerance = 400.0. Is this the expected result? In my experience, the mass accuracies for ion trap-CID data are fairly uniform and I would prefer to specify a mass-independent fragment tolerance. 

Yes, we converted Da to ppm in the mass calibration. If I remember it correctly, I do see the mass error changes with respect to the mz. Doing so also makes the code easy to maintain.


> Second, after re-calibration, the new fragment mass tolerance set by MSFragger is 500 PPM. This is unexpected given the pre and post-calibration median and MAD values for the data.

500 ppm is based on the parameter optimization procedure after mass calibration:
```
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |  150  |  200  |  250  |  300  |  350  |  400  |  450  |  500  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count | skip  | skip  |  11246|  11687|  12085|  12413|  12476|  12757
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------
 Peaks | 150_1 | 125_1 | 100_1 |  75_1 
-------|-------|-------|-------|-------
 Count |  12757|  12652| skip rest
-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |  12078
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |  12764
-------|-------
-------|-------
FragChg|    1  
-------|-------
 Count |  11949
-------|-------
```
As you can see, 500 ppm gives the most ID.

Best,

Fengchao

**Comment by enonimos** [comment]
Thanks Fengchao, this is very helpful!

**Comment by fcyu** [comment]
My pleasure.

Best,

Fengchao
