### ISSUE TITLE
Some N-terminal acetylations are not N-terminal

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#748]
Protein N-terminal acetylation was included in my search as a variable modification. For most of the psms, the N-terminal acetylation is mapped to the first or second residue of the protein, which makes sense since I checked the box to 'Clip N-term M.' However I am finding a small number of psms with 'N-terminal' aceylations that are not mapped to the first or second residue of the protein. If these peptides are not mapped to the N-terminal end of their proteins, how can they be N-terminally acetylated? Why is this happening and how can I stop it? You can see the problem in the attached example output file. 
Note, that I used '[^' to specify protein N-terminal acetylation in MSFragger.
----------------------
[psm_000_1.xlsx](https://github.com/Nesvilab/FragPipe/files/9024368/psm_000_1.xlsx)

**Comment by ndtivendale** [comment]
I am not sure why that text came out so big! Sorry.

**Comment by fcyu** [comment]
Seems to be the same one as https://github.com/Nesvilab/FragPipe/issues/718

Can you check if those peptides can be mapped to another protein, which makes it N-term Acetylation?

Best,

Fengchao
