### ISSUE TITLE
FragPipe doesn't run in Linux system 

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#749]
Hi al,
I recently start to work with FragPipe for analyzing proteomics DDA and DIA data. I usually work in windows system but I have a computer with higher performance with Linux. I install the FragPipe I follow the tutorial for the 'conda deactivate' but for some reason the same data with exactly the same settings and I always have an error that related with Java. The system has an Ubuntu system v.20.0.4 and the latest Java version 11.0 (FragPipe request more than v.9). 
Does anyone has the same issue and maybe an idea about what I can change?
Thank you in advance for your replies.
Best,
Tasos

**Comment by fcyu** [comment]
Hi Tasos,

Can you send us the log files or the screenshot?

Thanks,

Fengchao

**Comment by tasos2310** [comment]
Anastasios Samaras has shared a OneDrive for Business file with you. To view it, click the link below.
<https://ucdavis365-my.sharepoint.com/:i:/g/personal/asamaras_ucdavis_edu/EaBGwIDzMTpDuMWNyWbh1LABlk0qRIBu_evhIUKM_md4Ug>
[https://r1.res.office365.com/owa/prem/images/dc-jpg_20.png]<https://ucdavis365-my.sharepoint.com/:i:/g/personal/asamaras_ucdavis_edu/EaBGwIDzMTpDuMWNyWbh1LABlk0qRIBu_evhIUKM_md4Ug>
IMG_20220702_125819.jpg<https://ucdavis365-my.sharepoint.com/:i:/g/personal/asamaras_ucdavis_edu/EaBGwIDzMTpDuMWNyWbh1LABlk0qRIBu_evhIUKM_md4Ug>

Hi Fengchao,
The message that I took is this in the attached picture. I am sure that is not a data problem because I put them in a windows system. I tried to convert to mzml files but I have the error after the checking files that I have now.
I try to understand what I am doing wrong,

Best,
Tasos
________________________________

**Comment by fcyu** [comment]
Hi Tasos,

To make the raw file parser work, you need to install [Visual C++ Redistributable for Visual Studio 2017](https://aka.ms/vs/16/release/VC_redist.x64.exe) in Windows, and Mono in Linux.

Details can be found in the beginning of this tutorial: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#configure-fragpipe

Best,

Fengchao
