### ISSUE TITLE
Open Search Returning No PTM-Shepherd output CSV file

### ISSUE THREAD

**Issue by organicchemist99** [Nesvilab/FragPipe#751]
- Describe the issue or question:
I am trying to run an open search for peptide modifications on a mzML file using this workflow https://fragpipe.nesvilab.org/docs/tutorial_open.html
I am able to run the search and it says that the main search has been completed but I do not get a PTM-Shepherd output file in the output directory. I have tried this with the sample FFPE dataset (downloaded from the link in the tutorial) as well as my own .raw file which was converted to a mzML file using MSConvert. Is there something wrong with the search parameters or my settings? How do I get the desired output file to show up so I can open it in Excel?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2022-07-06_13-54-36.zip](https://github.com/Nesvilab/FragPipe/files/9057115/log_2022-07-06_13-54-36.zip)
)

**Comment by fcyu** [comment]
Can you double check the following two things?

1. Does your mzML file have MS1 scans?
2. The IDs from the search is quite low, can you confirm that the enzyme, species, or chemical labelling (if any) are correct?

Thanks

Fengchao

**Comment by organicchemist99** [comment]
Hi Fengchao,
Thanks for your quick response. I am very new to using MSfragger (as well as proteomics in general) and I am not too sure how to open a mzML file to check if there is any MS1 scans. Is there a good program to open this file? I know that the experiment was run on a Thermo Fusion Lumos.

The data is from a TMT experiment using trypsin digest, human, and TMT chemical labels. Do I have to put in a TMT modifications in the variable search parameters to fix this issue?

**Comment by fcyu** [comment]
We have a tutorial about data conversion here: https://fragpipe.nesvilab.org/docs/tutorial_convert.html . If you were not following the tutorial and using a different setting, you could re-convert it again.

If your data has TMT, I suggest you adding TMT as variable or fixed modification because most of the spectra have it. Please check our TMT-related workflows and borrow that to your open search.

Best,

Fengchao

**Comment by organicchemist99** [comment]
Hi Fengchao,
I followed the tutorial for the conversion of my raw file but I can try doing that again. 
I just added the TMT as a variable modification using n^ with a mass of 229.16293 (is this correct?). The search is running and seems to be taking much longer (maybe it has identified more peaks?). 
Thanks for your assistance thus far. I will reach back out once the search completes.

**Comment by organicchemist99** [comment]
Looks like it failed again...
[log_2022-07-06_14-51-25.zip](https://github.com/Nesvilab/FragPipe/files/9057337/log_2022-07-06_14-51-25.zip)

**Comment by anesvi** [comment]
Please email me directly and I will send you my Open-TMT workflow
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anesvi** [comment]
Yes, we do not recommend open search of low mass accuracy MS2 data

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by organicchemist99** [comment]
Hi Alexey and Fengchao,
Thank you for all of your great help thus far! I just sent an email to nesvi@umich.edu.
Only reason I am attempting an open search is because I performed TMT proteomics on an FFPE sample and I believe I may be losing out on sequencing some modified peptides due to chemical modifications. I was hoping to identify these modifications by open search to then rerun a TMT workflow in FragPipe with these set as variable modifications. Do you have any other recommendations for this type of sample? Thanks!

**Comment by danielgeiszler** [comment]
We discussed this in the PTM-Shepherd paper.

 https://www.sciencedirect.com/science/article/pii/S153594762035132X
