### ISSUE TITLE
Unclear how to input FASTA file into fragpipe in headless mode

### ISSUE THREAD

**Issue by hazeldilmore** [Nesvilab/FragPipe#752]
Hello, I'm trying to run the LFQ-MBR.workflow in headless mode on a linux server. I have the .workflow and .manifest files ready, but I keep getting the following error: 

> 2022-07-06 22:37:40,101 ERROR - FASTA file path is empty or the file is corrupted

I've tried adding the correct fasta file to the manifest file, as well as to the tools/fasta directory and the cache directory, but have gotten the same error. There doesn't appear to be any documentation for this issue. Do you have any suggestions? 

Thank you in advance!

**Comment by danielgeiszler** [comment]
Can you share your workflow file here?

**Comment by hazeldilmore** [comment]
I used the LFQ-MBR.workflow file that was included with the fragpipe download. It doesn't appear to have any fasta file input, but maybe I just missed it?

**Comment by fcyu** [comment]
@hazeldilmore Can you use FragPipe GUI to export the workflow you want for the first time of using the headless mode? You will be able to see how to set fasta file from the exported workflow file.

Best,

Fengchao

**Comment by hazeldilmore** [comment]
I downloaded workflow from GUI after adding the .fasta file. I apologize for redundancy but I do not see a field where this file is added or the where I could add the filepath. Could you please advise me on how to add this field so that it can be read by the software?

**Comment by fcyu** [comment]
Could you please read the tutorial here (https://fragpipe.nesvilab.org/docs/tutorial_headless.html) regarding how to export or saving the workflow to a custom folder when you done the setting in GUI?

Best,

Fengchao

**Comment by hazeldilmore** [comment]
Realized I was running fragpipe 17.0; updating to 18 fixed the issue - thanks! :)
