### ISSUE TITLE
Slight change in results due to splitting database

### ISSUE THREAD

**Issue by thaumP** [Nesvilab/FragPipe#753]
Hello, I found that the results of the identified peptides changed after I selected split database.

Changing the value of split database from 1 to 2 is the only variable and I found that all the output results are different, starting from the .pepXML file.

I would like to know why split database causes to change the results and what can be done to make the results identical?
[peptide_split2.xlsx](https://github.com/Nesvilab/FragPipe/files/9068849/peptide_split2.xlsx)
[split2_log_2022-07-08_11-43-28.txt](https://github.com/Nesvilab/FragPipe/files/9068854/split2_log_2022-07-08_11-43-28.txt)

[peptide_split1.xlsx](https://github.com/Nesvilab/FragPipe/files/9068851/peptide_split1.xlsx)
[split1_log_2022-07-08_11-35-37.txt](https://github.com/Nesvilab/FragPipe/files/9068852/split1_log_2022-07-08_11-35-37.txt)

**Comment by fcyu** [comment]
That is because there are duplicated peptides from different proteins in different split fasta file. When calculating e-values, those peptides are counted multiple times. While without split database, those peptides will be detected and only count once.

Best,

Fengchao
