### ISSUE TITLE
Is the psm.tsv files of each batch by Fragpipe18.0 normalized?

### ISSUE THREAD

**Issue by Irkcy** [Nesvilab/FragPipe#757]
Dear developer,

   I ran FragPipe18.0 with the TMT16 workflow. In the ‘Quant (Isobaric)’ tab, I select the "All" in the "Normalization" section. I wonder whether the result of psm.tsv files of each batch by Fragpipe18.0 normalized or not? And I uesd the ratio_protein_None.tsv(default log2-tansformed).

  Then I have reduced the values in the ratio_protein_None.tsv(default log2-tansformed). I have attached a file that is total values of all proteins of each sample by the ratio_protein_None.tsv(after reduced).  Thanks very much.

[Total_intensity.xlsx](https://github.com/Nesvilab/FragPipe/files/9091329/Total_intensity.xlsx)

Best,
Irkcy

**Comment by fcyu** [comment]
No, only the files in the `tmt-report` folder are normalized by TMT-Integrator.

Best,

Fengchao
