### ISSUE TITLE
contaminants filtered from TMT-Integrator

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#759]
I have noticed that FragPipe v.18 removes contaminant proteins from the outputs in the TMT-report folder, whereas they were kept in FragPIpe v.17.1. I am using a bovine casein spike-in, so I can fix this by removing "contam" from the .fasta file for these entries. Is there an option in FragPipe to keep contaminants through the reporter ion quantification, or can you make this an option in a future release? Thanks, Matt

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by mwfoster** [comment]
OK, thanks. That is the solution I came up with. Matt

**Comment by anesvi** [comment]
@mwfoster<https://github.com/mwfoster> – we have a few questions. What version of Philosopher did you use? Did you add contaminants using philosoper? Did you use TMT-Integrator?  I think we need a bit more detail

**Comment by anesvi** [comment]
@mwfoster did we fix this issue?

**Comment by mwfoster** [comment]
I did check again today and I don't see contaminants identified in the psm/peptide/protein.txt files passed through to the tmt-report folder. I'm fine with the suggested workaround which is to remove the "contam_" from the protein name if you want to have it appear in the tmt-report files.
