### ISSUE TITLE
Problem with the fragpipe 18. DIA-NN looks failling

### ISSUE THREAD

**Issue by hupak2022** [Nesvilab/FragPipe#763]
Hello,
I have upgraded fragpipe to fragpipe 18. Since, all my Hybrid-DIA runs fails. MSfragger works perfectly as I can see the results generated from it as well as the spectral library.  I had the impression that something is wrong with DIA-NN but I don't know how.
Please find below the log file. I hope this can help you to fixe this issue

Best

Hui Song
[log_2022-07-14_09-45-15.txt](https://github.com/Nesvilab/FragPipe/files/9109821/log_2022-07-14_09-45-15.txt)

**Comment by fcyu** [comment]
Hi Hui,

To make DIA-NN work with raw format. You need to install Thermo MS File Reader: https://github.com/vdemichev/DiaNN#raw-data-formats

Best,

Fengchao
