### ISSUE TITLE
Is it necessary to filter the results by 'Expectation< 0.01' ?

### ISSUE THREAD

**Issue by grimace9527** [Nesvilab/FragPipe#766]
Hi, I am using MSFragger to search for glycopeptides, and find that the 'psm.tsv' file contains a column named "Expectation". If I use the default settings in peptideprophet and proteinprophet, havethe results in the 'psm.tsv' file already been filtered by FDR < 0.01? If so, is it necessary to filter the results again by the 'Expectation' value?
Thanks for your reply.

**Comment by fcyu** [comment]
No, you should not filter the results again by the expectation value.

Best,

Fengchao
