### ISSUE TITLE
issue with open visualization window

### ISSUE THREAD

**Issue by glycomev** [Nesvilab/FragPipe#768]
Hello everyone,

I'm not familiar at all with code, I succed to run my analysis it's telling me "All jobs done" but when I try to visualized the result it's tell me "Failed to parsed results, check your file" and i don't know what to do 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Not sure why I cannot assign this issue to Kai. But if Kai see this, can you follow-up?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi,

Could you please share the `*.fp-manifest` and `log ` files with me? 

Kai

**Comment by glycomev** [comment]
[log_2022-07-21_16-21-21.zip](https://github.com/Nesvilab/FragPipe/files/9160321/log_2022-07-21_16-21-21.zip)

**Comment by glycomev** [comment]
I don't know how to obtain fp-manifest

**Comment by KaiLiCn** [comment]
The `*.fp-manifest` should be in the result folder, same with log file.

**Comment by glycomev** [comment]
[lcms-files_2022-07-21_16-21-21.zip](https://github.com/Nesvilab/FragPipe/files/9160353/lcms-files_2022-07-21_16-21-21.zip)

**Comment by KaiLiCn** [comment]
Appreciate it. I am working on it. I will let you know if I need more data from you.

**Comment by KaiLiCn** [comment]
Could you share this result folder with me, if it's not too big? `Z:\H2020_project\WP10_spike_protein\Spike_produce_in_tobacco\2021-09-08\MSfragger_t_gluc_4`

**Comment by fcyu** [comment]
@glycomev , were you running FragPipe in GUI mode or headless mode?

Best,

Fengchao

**Comment by glycomev** [comment]
@fcyu I think i'm in GUI mode, I let the defaut parameter in workflow, 
@KaiLiCn  Can I send you this by e-mail ? because it's confidencial data

**Comment by KaiLiCn** [comment]
Sure. This is my email. lkai@umich.edu

**Comment by KaiLiCn** [comment]
@glycomev . Based on the log file, you only ran MSFragger but no Philosopher etc. Could you use the build-in workflow to generate complete results?

Kai

**Comment by fcyu** [comment]
Hi @glycomev ,

Can you take a look at the tutorial (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html) and run again?

Best,

Fengchao

**Comment by glycomev** [comment]
Yes sure

Thanks

Le Jeudi, Juillet 21, 2022 16:41 CEST, Fengchao ***@***.***> a écrit:
 
 
Not sure why I cannot assign this issue to Kai. But if Kai see this, can you follow-up?
Thanks,
Fengchao
