### ISSUE TITLE
MSBooster does not recognize mzXML formats

### ISSUE THREAD

**Issue by klannieha** [Nesvilab/FragPipe#769]
Hi,

I am generating spectral libraries with the DIA-SpecLib_Quant workflow using converted mzXML files. MSBooster has been giving me an error where it cannot find the mzML/mgf files in the directories. It worked after switching to using the .raw files, but it would be nice if the mzXML formats can also be recognized.

`MSBooster v1.1.4
Using 8 threads
java.lang.IllegalArgumentException: No matching mzml/mgf file for UP000202_01.pin, please check that provided mzml/mgf directories contain proper mzml/mgf files.
at Features.PinMzmlMatcher.<init>(PinMzmlMatcher.java:80)
at Features.MainClass.main(MainClass.java:470)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping`

Thanks,
Annie

**Comment by fcyu** [comment]
Hi Annie,

We no longer support mzXML format because the information in that format is not as complete as mzML or raw. Furthermore, converting from raw to mzML is no more complicated than to mzXML.

Best,

Fengchao
