### ISSUE TITLE
Error when converting overlapping windows DIA files to mzML

### ISSUE THREAD

**Issue by roberthardt** [Nesvilab/FragPipe#770]
Hi there,

![MS_convert_error](https://user-images.githubusercontent.com/24385067/180398647-8a40fb8b-b692-44cc-9361-8705d14e987b.png)
I stumbled upon a problem when wanting to convert our overlapping window DIA files acquired on an Orbitrap Fusion Lumos with MSConvert as described on the Github help page. I think this has to do with the way the DIA method was set up years ago in an older version of Thermo Tune. This was before there was a dedicated DIA acqiusition method node and thus we basically used a tMSn node with the DIA window centers as mass list. Unfortunately, one or two of the overlaps differ slightly in size, thereby probably causing MSConvert to fail. Interestingly, this was never an issue with Spectronaut, which could analyze our data just fine.

![method03](https://user-images.githubusercontent.com/24385067/180397689-e3b0ab37-fd94-44fd-be56-32373c9b34ff.png)
![method02](https://user-images.githubusercontent.com/24385067/180397692-16bbb8a1-f928-4831-a71f-e248e9bbdf16.png)
![method01](https://user-images.githubusercontent.com/24385067/180397695-963d2f24-f9e6-45f7-a9d3-c43d03444409.png)

Best regards

Robert

**Comment by fcyu** [comment]
Hi Robert,

This it is an issue from msconverter, I suggest you submit the issue to https://github.com/ProteoWizard/pwiz/issues

Best,

Fengchao

**Comment by fcyu** [comment]
Solved in https://github.com/ProteoWizard/pwiz/issues/2166
