### ISSUE TITLE
Wrong peptide start and end positions

### ISSUE THREAD

**Issue by hollenstein** [Nesvilab/FragPipe#771]
Dear FragPipe Team,

First of all, thank you very much for providing these fantastic tools. I am working at a proteomics MS facility and we are planning to switch to FragPipe for the bulk of our data analysis in the near future. I am currently looking into using FragPipe for several typical sample types we get in the facility, and how to further process the outputs generated by FragPipe. So I will probably have several questions in the future and maybe also some feature requests.

**I’ve noticed a rare problem of the reported peptide Start and End positions:**
When looking up the positions of a peptide in the protein sequence from the FASTA file, in very few cases the Start and End positions reported by FragPipe don’t match the actual positions. It appears to be a problem caused by treating Isoleucine and Leucine as indistinguishable (at least in the cases I’ve observed).

For example, the reported peptide “GDSLDSVEALIK” matches exactly once to the protein sequence of “Q13813”, at position 1474 to 1485. However, FragPipe reports 496 to 507. When replacing all “L” with “I” in the peptide and the protein sequence, then the peptide matches to two positions within the protein: 496 to 507 (GDSLDSVEALLK), and 1474 to 1485 (GDSLDSVEALIK). I assume that when matching the peptide to the protein (treating “L” and “I” as indistinguishable), the first occurance of the peptide is reported by FragPipe. I think this behavior is fair enough, however, the actual sequence of the peptide in the ion.tsv and other tables is not updated and thus does not fit to the reported Start and End positions.

In the few cases I’ve seen, only the “original” peptide sequences that were reported are tryptic peptides, meaning the preceding amino acid were K/R, whereas the peptides from the reported start/end positions were only semi-tryptic peptides.

I’ve seen that you are planning to consider the cleavage rules when mapping peptides to proteins in an upcoming version (https://github.com/Nesvilab/FragPipe/issues/718), so this might already solve the problem in most if not all the cases. I still wanted to let you know, as this seems to be an unintentional behavior.

Best,
David

Here is the protein sequence for the mentioned example
>sp|Q13813|SPTN1_HUMAN Spectrin alpha chain, non-erythrocytic 1 OS=Homo sapiens OX=9606 GN=SPTAN1 PE=1 SV=3
MDPSGVKVLETAEDIQERRQQVLDRYHRFKELSTLRRQKLEDSYRFQFFQRDAEELEKWIQEKLQIASDENYKDPTNLQGKLQKHQAFEAEVQANSGAIVKLDETGNLMISEGHFASETIRTRLMELHRQWELLLEKMREKGIKLLQAQKLVQYLRECEDVMDWINDKEAIVTSEELGQDLEHVEVLQKKFEEFQTDMAAHEERVNEVNQFAAKLIQEQHPEEELIKTKQDEVNAAWQRLKGLALQRQGKLFGAAEVQRFNRDVDETISWIKEKEQLMASDDFGRDLASVQALLRKHEGLERDLAALEDKVKALCAEADRLQQSHPLSATQIQVKREELITNWEQIRTLAAERHARLNDSYRLQRFLADFRDLTSWVTEMKALINADELASDVAGAEALLDRHQEHKGEIDAHEDSFKSADESGQALLAAGHYASDEVREKLTVLSEERAALLELWELRRQQYEQCMDLQLFYRDTEQVDNWMSKQEAFLLNEDL**GDSLDSVEALLK**KHEDFEKSLSAQEEKITALDEFATKLIQNNHYAMEDVATRRDALLSRRNALHERAMRRRAQLADSFHLQQFFRDSDELKSWVNEKMKTATDEAYKDPSNLQGKVQKHQAFEAELSANQSRIDALEKAGQKLIDVNHYAKDEVAARMNEVISLWKKLLEATELKGIKLREANQQQQFNRNVEDIELWLYEVEGHLASDDYGKDLTNVQNLQKKHALLEADVAAHQDRIDGITIQARQFQDAGHFDAENIKKKQEALVARYEALKEPMVARKQKLADSLRLQQLFRDVEDEETWIREKEPIAASTNRGKDLIGVQNLLKKHQALQAEIAGHEPRIKAVTQKGNAMVEEGHFAAEDVKAKLHELNQKWEALKAKASQRRQDLEDSLQAQQYFADANEAESWMREKEPIVGSTDYGKDEDSAEALLKKHEALMSDLSAYGSSIQALREQAQSCRQQVAPTDDETGKELVLALYDYQEKSPREVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPAAYVKKLDPAQSASRENLLEEQGSIALRQEQIDNQTRITKEAGSVSLRMKQVEELYHSLLELGEKRKGMLEKSCKKFMLFREANELQQWINEKEAALTSEEVGADLEQVEVLQKKFDDFQKDLKANESRLKDINKVAEDLESEGLMAEEVQAVQQQEVYGMMPRDETDSKTASPWKSARLMVHTVATFNSIKELNERWRSLQQLAEERSQLLGSAHEVQRFHRDADETKEWIEEKNQALNTDNYGHDLASVQALQRKHEGFERDLAALGDKVNSLGETAERLIQSHPESAEDLQEKCTELNQAWSSLGKRADQRKAKLGDSHDLQRFLSDFRDLMSWINGIRGLVSSDELAKDVTGAEALLERHQEHRTEIDARAGTFQAFEQFGQQLLAHGHYASPEIKQKLDILDQERADLEKAWVQRRMMLDQCLELQLFHRDCEQAENWMAAREAFLNTEDK**GDSLDSVEALIK**KHEDFDKAINVQEEKIAALQAFADQLIAAGHYAKGDISSRRNEVLDRWRRLKAQMIEKRSKLGESQTLQQFSRDVDEIEAWISEKLQTASDESYKDPTNIQSKHQKHQAFEAELHANADRIRGVIDMGNSLIERGACAGSEDAVKARLAALADQWQFLVQKSAEKSQKLKEANKQQNFNTGIKDFDFWLSEVEALLASEDYGKDLASVNNLLKKHQLLEADISAHEDRLKDLNSQADSLMTSSAFDTSQVKDKRDTINGRFQKIKSMAASRRAKLNESHRLHQFFRDMDDEESWIKEKKLLVGSEDYGRDLTGVQNLRKKHKRLEAELAAHEPAIQGVLDTGKKLSDDNTIGKEEIQQRLAQFVEHWKELKQLAAARGQRLEESLEYQQFVANVEEEEAWINEKMTLVASEDYGDTLAAIQGLLKKHEAFETDFTVHKDRVNDVCTNGQDLIKKNNHHEENISSKMKGLNGKVSDLEKAAAQRKAKLDENSAFLQFNWKADVVESWIGEKENSLKTDDYGRDLSSVQTLLTKQETFDAGLQAFQQEGIANITALKDQLLAAKHVQSKAIEARHASLMKRWSQLLANSAARKKKLLEAQSHFRKVEDLFLTFAKKASAFNSWFENAEEDLTDPVRCNSLEEIKALREAHDAFRSSLSSAQADFNQLAELDRQIKSFRVASNPYTWFTMEALEETWRNLQKIIKERELELQKEQRRQEENDKLRQEFAQHANAFHQWIQETRTYLLDGSCMVEESGTLESQLEATKRKHQEIRAMRSQLKKIEDLGAAMEEALILDNKYTEHSTVGLAQQWDQLDQLGMRMQHNLEQQIQARNTTGVTEEALKEFSMMFKHFDKDKSGRLNHQEFKSCLRSLGYDLPMVEEGEPDPEFEAILDTVDPNRDGHVSLQEYMAFMISRETENVKSSEEIESAFRALSSEGKPYVTKEELYQNLTREQADYCVSHMKPYVDGKGRELPTAFDYVEFTRSLFVN

**Comment by fcyu** [comment]
Hi David,

Thanks for your feedback. I think it is also related to the issue https://github.com/Nesvilab/FragPipe/issues/500 . We will see what we can do.

Best,

Fengchao

**Comment by fcyu** [comment]
@prvst Is it fixed?

Best,

Fengchao

**Comment by prvst** [comment]
I updated some rules since this report. It would be good to try running it again with teh current release to see the results.

**Comment by hollenstein** [comment]
Hi,

Thanks for the update. I can run my samples with the latest release and let you know in the next days if the issue is gone.

Best,
David

**Comment by anesvi** [comment]
Hi David,

Thanks for the test

Felipe, could you please take another look and see if you can replace the peptide sequence reported with the correct I/L (that matches the protein to which the peptide is reassigned)?

Thanks
Alexey

**Comment by hollenstein** [comment]
Yes, the issue is already present in the PSM table.

**Comment by hollenstein** [comment]
Sure, I will send you a link

**Comment by prvst** [comment]
Thanks.

Quick question; have you noticed that you have completely identical sequences in your database under different IDs?

**Comment by prvst** [comment]
@hollenstein I released a new version that corrects the mapping of cases like you describe above. Please download it and give it a try.

**Comment by hollenstein** [comment]
Hi, sorry for the delay.

I've re-run FragPipe with the following versions:
FragPipe version 19.0
MSFragger version 3.6
IonQuant version 1.8.9
Philosopher version 4.7.0

Unfortunately, the issue seems not be resolved and there is an additional bug. For about 10% of all entries in the combined_ion.tsv file, the “Start” and “End” entries are now 0, so I couldn’t check if the reported positions are correct. In order to test the “I” and “L” issue, I’ve checked if the reported peptide sequence is present in the sequence of the reported protein. For ~100 entries this was not the case. However, when treating “I” and “L” as indistinguishable all peptides could be found within the protein sequence, and all those peptides appeared to be fully tryptic peptides.

**Comment by prvst** [comment]
@hollenstein thanks for the testing. We're currently working on a few changes and fixes on both MSFragger and Philosopher. We'll keep you posted.

**Comment by hollenstein** [comment]
Thanks for the update. Let me know if I can help with some testing again.

**Comment by prvst** [comment]
You can grab the latest Philosopher release candidate [here](https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0). But there's also a bug fix in MSFragger, so you'll need that from Fengchao too.

**Comment by fcyu** [comment]
Fixed in MSFragger 3.7 and Philosopher 4.8.0.

Best,

Fengchao
