### ISSUE TITLE
Error when trying to split database

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#772]
I'm getting the following error when I try to run FragPipe and I don't know what to do.

Traceback (most recent call last):
  File "C:\data\Nathan\FragPipe-jre-18.0\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\data\Nathan\FragPipe-jre-18.0\fragpipe\tools\msfragger_pep_split.py", line 613, in main
    sample_fasta(fasta_path, fasta_path_sample, min(num_parts, 1))
  File "C:\data\Nathan\FragPipe-jre-18.0\fragpipe\tools\msfragger_pep_split.py", line 599, in sample_fasta
    with fasta_path_sample.with_suffix('.sorted_fasta').open('wb') as f:
  File "C:\data\Nathan\Anaconda\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\data\Nathan\Anaconda\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'split_peptide_index_tempdir\\2022-06-21-decoys-contam-Araport11_pep_20220103.fasta.sorted_fasta'
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2022-07-25_14-50-01.txt](https://github.com/Nesvilab/FragPipe/files/9178727/log_2022-07-25_14-50-01.txt)
tach the zipped file by drag & drop here.)

**Comment by guoci** [comment]
@ndtivendale Can you show me the folder listing of `split_peptide_index_tempdir`?
It seems that some files are missing.

**Comment by ndtivendale** [comment]
@guoci I think I have solved the problem. My FASTA file had the extention .fasta.fas and that messed with the creation of the split database. It seems to be running now :)

**Comment by fcyu** [comment]
> My FASTA file had the extention .fasta.fas and that messed with the creation of the split database. 

I think it is quite common when users add decoys using FragPipe. @guoci , is there something we need to fix?

Thanks,

Fengchao

**Comment by guoci** [comment]
@fcyu I am not convinced that is the cause but I do not know what is causing the error
