### ISSUE TITLE
MaxLFQ Intensity Vs Intensity

### ISSUE THREAD

**Issue by smahajan-CLS** [Nesvilab/FragPipe#774]
Hi,
I analyzed over 300 raw files (all samples are in triplicates unless some files crashed while running and were removed in order to continue) using Fragpipe with ionquant. I recently updated the versions for Fragpipe and Philospher as it showed new update downloads. With the earlier version, there were Intensity, total and Unique Intensity and corresponding LFQ values. In the recent version there are only Intensity and MaxLFQ Intensity in the output.
I am uncertain which value should I use. the goal is to compare relative intensities of a few proteins in all these samples that were run on a single ORBITRAP instrument. I have noticed that some proteins (with family members/ isoforms) have a high MaxLFQ intensity values while the corresponding Intensity is zero and also vice versa in combined protein file. Looking at the corresponding combined peptides file, I noticed that there are unique peptides for all the family members/ isoforms.
I am not sure why the MaxLFQ values are higher if the Intensity is zero? Can you please explain.
Thank you,
Kind regards,
Shikha

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Shikha,

Here (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_proteintsv) has the explanation of all those intensities. The "Intensity" is from top-N algorithm (https://www.mcponline.org/article/S1535-9476(20)35104-5/fulltext), and the "MaxLFQ Intensity" is from MaxLFQ algorithm (https://www.mcponline.org/article/S1535-9476(21)00050-5/fulltext). Depends on your top-N settings, the "Intensity" could be zero but the "MaxLFQ Intensity" is not.

Best,

Fengchao

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

Thank you for your prompt reply. I did change the parameters and it looks like the issue is resolved.

Thank you,
Kind regards,
Shikha

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

I have another question. I recently started using MS Fragger for data processing and when I load data from Fragpipe into Scaffold I do not get the peptide fragmentation tab ( Protein Tab) active. I cannot see the individual b and y ions corresponding to each peptide. I could see it when I used Proteome Discoverer to analyze my data.

I had contacted Scaffold team and they suggested me since it's a spectrum issue, I'd pay extra attention to the bits about MGF files. I have already selected the write mgf file in the  Fragger tab.

Can you please suggest anything I may be missing in Scaffold or probably Fragpipe parameter selection.

Thank you,
Shikha

**Comment by fcyu** [comment]
I have no idea about the issue in Scaffold, but FragPipe has the visualization module now. You can have a try.

Best,

Fengchao

**Comment by smahajan-CLS** [comment]
Fengchao,

Thank you. Really appreciate it.
Our company recently bought the Fragpipe license, and I am trying to set up basic analysis pipeline for my team. I have been using MaxQuant and Saffold for more than 10 years but It’s amazing how Fragpipe works. I am trying to switch most of our data analysis to Fragpipe as it’s so efficient.


Kind regards,
Shikha

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anesvi** [comment]
Hi Shikha,

Thanks for using the tools.

We do not have direct interactions with the Scaffold developers, but if  you figure out what the issue is, let us know.

Best,
Alexey

**Comment by smahajan-CLS** [comment]
Hello Dr. Nesvizhskii ,

Sure. I will let you know.
The scaffold has two options to use MSFragger. One involves to run MSFragger through Scaffold that I have not explored so far.
The other one includes using MS Fragpipe output files to analyze and visualize data. I am using this option currently.

My previous work flow included Proteome Discoverer or Maxquant to analyze the raw files followed by Scaffold as a visualization tool and I am able to analyze the individual b and y ions and quality of the spectrum from the following tabs. This data is useful in selecting peptides for any targeted approach.

I have contacted Scaffold earlier last week and I may contact them again tomorrow as I am not able to do it so far and let you know of any updates.

Thank you,
Shikha


***@***.***





































Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

I have figured the issue out. I had contacted Scaffold and I had the MGF file saved in a folder with raw files and not with output files for some reason  and it wasn’t accessible for Scaffold.

Hope it helps.

On a separate note, is it a software update in version 18 vs 17. Earlier version has unique and total intensities included for intensity and LFQ intensity. The new version only gives intensity and MaxLFQ. Is one better than other?

Thank you,
Kind regards,
Shikha

**Comment by fcyu** [comment]
Hi Shikha,

Thanks for your information. So, what should we do to make is compatible with Scaffold?

As to the changes regarding the intensity, we stop listing razor, unique, and total intensities, which is a little bit overwhelming. We added a new dropdown menu called `peptide-protein uniqueness` in the `Quant (MS1)` tab to control what kind of intensity to report.

Best,

Fengchao

**Comment by anesvi** [comment]
We write MGF files where raw files are. So Shikha, please tell the Scaffold team to look in the right place. I guess this is not something we need to worry about in FragPipe, Fengchao.
Alexey

**Comment by smahajan-CLS** [comment]
Hi Alexey,

I have been able to combine the folder for raw files and output so its not an issue anymore. I really appreciate you and Fengchao’s prompt responses to resolve the issue quickly.

Kind regards,
Shikha
