### ISSUE TITLE
Relaxing run specific protein FDR does not change results

### ISSUE THREAD

**Issue by roberthardt** [Nesvilab/FragPipe#776]
- Describe the issue or question:
I ran a DIA-Speclib-Quant analysis trough Fragpipe and passed it to DIA-NN for quant. After completion I wanted to rerun the DIA-NN step only, this time  relaxing the "run specific protein FDR" a bit (0.05 instead of the default 0.01) interestingly though this resulted in an identical "diann-output.pg_matrix.tsv" file. I would have expected to get slightly higher IDs that way.

- Upload your log file
0.01 run:
[diann-output.log.txt](https://github.com/Nesvilab/FragPipe/files/9190994/diann-output.log.txt)

[diann-output.pg_matrix_0.01.tsv.zip](https://github.com/Nesvilab/FragPipe/files/9191019/diann-output.pg_matrix_0.01.tsv.zip)

0.05 run
[diann-output.log.txt](https://github.com/Nesvilab/FragPipe/files/9190998/diann-output.log.txt)
:
[diann-output.pg_matrix_0.05.tsv.zip](https://github.com/Nesvilab/FragPipe/files/9191022/diann-output.pg_matrix_0.05.tsv.zip)

Best

Robert

**Comment by fcyu** [comment]
Since you already have global protein FDR filtering, adding run-specific FDR might not change much depends on your data.

Best,

Fengchao
