### ISSUE TITLE
DIA-SpecLib_Quant pipeline with MBR

### ISSUE THREAD

**Issue by klannieha** [Nesvilab/FragPipe#777]
Hi,

It seems like DIA-NN on its own documentation has MBR on as their default settings. Is that the same case with the DIA-SpecLib_Quant workflow using DIA-NN for quant? 
So far I see each replicate from an experiment getting their own output folder and reports, just wondering if there would be MBR information in it? Or does the MBR option has to be specified with the `Cmd line opts` ? 
Thanks!
Annie

**Comment by fcyu** [comment]
If you run DIA-NN in FragPipe, there is no need to enable DIA-NN's MBR. That MBR is only for DIA-NN's in silico prediction approach. 

If you want to have a single report with all runs, you can remove the experimental groups.

Best,

Fengchao

**Comment by klannieha** [comment]
Thank you!
