### ISSUE TITLE
Visualization window does not open

### ISSUE THREAD

**Issue by SStoychev01** [Nesvilab/FragPipe#781]
Hi FragPipe team,

I'm running FragPipe v18. After completing a DDA search I try to use the "Open Visualization window" but window doesn't open?

Thanks for the assistance.

Stoyan

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Can you send us your log file?

Thanks,

Fengchao

**Comment by SStoychev01** [comment]
Sure, please find attached
[log_2022-07-30_11-27-01.txt](https://github.com/Nesvilab/FragPipe/files/9225896/log_2022-07-30_11-27-01.txt)

.
