### ISSUE TITLE
Which SVG image viewer to use for ubuntu

### ISSUE THREAD

**Issue by Professor333** [Nesvilab/FragPipe#783]
I can't seem to install an SVG viewer correctly that Fragpipe will recognize it. I'm using Ubuntu, so what do I need to fix the following error?

WARNING: No interface org.openide.util.spi.SVGLoader instance found in ProxyLookup(class=class org.openide.util.Lookup$DefLookup)->[MetaInfServicesLookup[jdk.internal.loader.ClassLoaders$AppClassLoader@46fbb2c1], SingletonLookup[jdk.internal.loader.ClassLoaders$AppClassLoader@46fbb2c1]]
Jul 29, 2022 10:09:13 AM org.openide.util.ImageUtilities getIcon
INFO: No SVG loader available for loading jar:file:/home/ryan/translation/FragPipe-18.0/fragpipe/lib/org-netbeans-swing-outline-RELEASE130.jar!/org/netbeans/swing/etable/columns.svg

**Comment by fcyu** [comment]
No need.
