### ISSUE TITLE
TmtIntegrator Error: More than one reference tag, TMT16

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#784]
Hi, we've encountered this error multiple times for our TMT data. Sometimes, we can resolve it by going over every "annotation.txt" file and rename the offending names. However, we're not able to find any duplicate in this case, to the "Reference Tag": psNTm.

Is there a documentation on what'd trigger this kind of error? Do you only consider the exact string match as the "duplicate" or by other criteria.

It'd also be very useful for you to perform the check for duplication at the beginning of the workflow, instead of waiting for a few days to be surprised! A detailed message on the source of the error and the entries where the duplicates are found would be tremendously helpful, especially for large project with many, many TMT plates.

Thanks again for your help as always!

Wen

[annotation.txt](https://github.com/Nesvilab/FragPipe/files/9247492/annotation.txt)
[log_2022-08-02_22-33-21.txt](https://github.com/Nesvilab/FragPipe/files/9247493/log_2022-08-02_22-33-21.txt)

**Comment by fcyu** [comment]
Can you send us the column names in the file `D:\AZ_CST\ALL\results-iso-semiT-boosted\P1\psm.tsv`?

Thanks,

Fengchao

**Comment by wyu** [comment]
Thanks for your reply!

Here are the headers from each of the TMT plates starting with the name of the plate. The colnames are consistent with what we've defined in the annotation.txt files. The closest entries is "2psNTm" in plate 22, for example.

Thanks!
Wen

P1 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, GC02, GC01, Duo03, Eso02, GC06, Stm03, Stm01, Duo02, GC04, Duo01, Pro01, Pro02, GC03, PC02, psTTm
P10 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Skn07, RCC06, Kid03, Kid01, Liv07, RCC05, RCC03, Hrt07, BM07, RCC01, RCC02, Kid02, Pan07, RCC04, psTTm
P11 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, RCC11, Kid05, RCC07, RCC12, Liv08, Skn08, BM08, RCC08, Kid06, Pan08, RCC09, Hrt08, RCC10, Kid04, psTTm
P12 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, RCC17, RCC13, Pan09, Kid08, RCC16, RCC19, Kid07, RCC15, Skn09, BM09, Hrt09, RCC14, Liv09, RCC18, psTTm
P13 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Hrt10, BM10, RCC22, 2psTTm, Skn10, Kid10, RCC21, Kid09, RCC25, RCC20, Pan10, RCC24, RCC23, Liv10, psTTm
P14 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Ile01, CRC02, Jej02, CRC06, Jej01, CRC03, CRC05, Ile03, CRC04, Ile02, CRC01, Col01, Col02, Col03, psTTm
P15 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, CRC12, Ile05, CRC10, Ile06, Jej04, CRC09, Jej03, Col04, Col06, CRC7, Col05, CRC11, Ile04, CRC08, psTTm
P16 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, CRC14, CRC17, Col08, CRC19, CRC15, Ile07, Jej05, CRC13, CRC18, Jej07, Jej06, Col07, CRC16, Ile08, psTTm
P17 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Col10, Col09, CRC23, Jej10, CRC20, Ile09, CRC24, CRC25, Jej09, 2psTTm, Ile10, CRC21, Jej08, CRC22, psTTm
P18 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Skn01, NSC05, NSC03, Lng01, Lng02, Pan01, NSC01, Hrt01, BM01, NSC06, NSC04, Liv01, Lng03, NSC02, psTTm
P19 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Hrt02, NSC10, Liv02, Skn02, NSC11, Lng06, BM02, NSC07, NSC08, Lng04, Lng05, NSC09, NSC12, Pan02, psTTm
P2 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Stm04, Eso04, GC11, GC07, Stm06, Eso03, PC03, PC04, Eso10, Stm07, GC10, GC12, Stm05, Eso05, psTTm
P20 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, NSC18, Hrt03, Liv03, NSC13, Lng08, NSC17, NSC15, BM03, NSC14, Skn03, NSC16, Pan03, Lng07, NSC19, psTTm
P21 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Hrt04, Lng09, NSC23, NSC21, BM04, NSC20, Liv04, NSC25, Lng10, NSC24, Skn04, 2psTTm, NSC22, Pan04, psTTm
P22 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Pro08, P15-CRC, 2psTTm, P18-NSC, P3-PC, P11-RCC, P5-GC, 2psNTm, P6-OV, Pro09, P8-OV, P20-NSC, P13-RCC, P14-CRC, psTTm
P23 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, P16-CRC, P12-RCC, P1-PC, P10-RCC, P21-NSC, 2psTTm, Pro10, P7-OV, P4-GC, 2psNTm, P2-GC, P9-OV, P17-CRC, P19-NSC, psTTm
P3 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Duo06, PC05, Duo07, Pro05, GC15, PC06, Duo08, GC16, Eso06, GC13, GC14, Stm08, GC19, Eso07, psTTm
P4 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, GC18, Pro06, GC17, PC08, Pro07, GC20, Stm10, Duo09, GC23, Stm09, Eso09, GC22, Duo10, GC21, psTTm
P5 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, psTTm, Eso08, GC25, GC24, Pro03, Pro04, GC08, GC09, Duo05, Duo04, Stm02, Eso01, PC01, GC05, psTTm
P6 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, OV06, Ova02, OV01, FT01, OV05, Ova01, FT03, Pan05, BM05, OV03, Ova03, FT02, OV04, OV02, psTTm
P7 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, OV11, Ova04, OV09, Pan06, Ova06, BM06, OV08, OV10, FT04, FT05, FT06, OV07, OV12, Ova05, psTTm
P8 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, FT08, OV14, Ova07, OV13, FT07, OV18, Hrt05, OV15, Ova08, OV19, OV17, Liv05, Skn05, OV16, psTTm
P9 --> Spectrum, Spectrum File, Peptide, Modified Peptide, Prev AA, Next AA, Peptide Length, Charge, Retention, Observed Mass, Calibrated Observed Mass, Observed M/Z, Calibrated Observed M/Z, Calculated Peptide Mass, Calculated M/Z, Delta Mass, SpectralSim, RTScore, Expectation, Hyperscore, Nextscore, PeptideProphet Probability, Number of Enzymatic Termini, Number of Missed Cleavages, Protein Start, Protein End, Intensity, Assigned Modifications, Observed Modifications, Purity, Is Unique, Protein, Protein ID, Entry Name, Gene, Protein Description, Mapped Genes, Mapped Proteins, Quan Usage, psNTm, Hrt06, OV21, Liv06, OV20, OV24, Ova09, psTTm, FT09, OV25, Ova10, OV23, OV22, FT10, Skn06, psTTm

**Comment by fcyu** [comment]
Hi Wen,

Hui-Yin, who developed TMT-Integrator, told me that TMT-Integrator matches the substring in finding the reference tag. Thus, `2psNTm` in your annotation file is treated as the reference tag. To remove the duplicated tags, you need to give totally different name.

Best,

Fengchao
