### ISSUE TITLE
PTMprophet error

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/FragPipe#787]
Hi,

I am processing a phosphoproteomic dataset produced on a timsTOF pro machine. PTMprophet finished running without any errors, but for a subset of the samples it produced only a pep.xml.tmp file (no mod.pep.xml) and these files are all apparently truncated (they end with a '</spectrum_query>' tag).

Can you please take a look at the log file.

Thank you,
Janos

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped
[log_2022-08-05_01-05-53.txt](https://github.com/Nesvilab/FragPipe/files/9270692/log_2022-08-05_01-05-53.txt)
 file by drag & drop here.)

**Comment by fcyu** [comment]
> for a subset of the samples it produced only a pep.xml.tmp file (no mod.pep.xml) and these files are all apparently truncated (they end with a '</spectrum_query>' tag).

It seems like a bug in PTM-Prophet. Please contact the PTM-Prophet team.

Best,

Fengchao

**Comment by jd690764** [comment]
Thank you, Fengchao!  Do you know what would be the best place to ask them?
Is it this one:

https://sourceforge.net/p/sashimi/discussion/235608/

Thanks,
Janos

**Comment by fcyu** [comment]
I think so. I see that you already created a ticked there.

Best,

Fengchao

**Comment by anesvi** [comment]
I don’t know how much they can help. Since we are running PTM-Prophet through Philosopher.
What is the error again?
Need to check with Felipe too

**Comment by fcyu** [comment]
In the log file, there is no error message from PTM-Prophet, but Philosopher complained
```
C:\msfragger2\FragPipe-jre-18.0\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe filter --sequential --picked --prot 0.01 --tag rev_ --pepxml E:\tmp\220803_unsync_rpe_imac\msf_220803\k50a_s_1 --protxml E:\tmp\220803_unsync_rpe_imac\msf_220803\combined.prot.xml --razor
INFO[01:05:52] Executing Filter  v4.4.0                     
INFO[01:05:52] Processing peptide identification files      
INFO[01:05:52] Parsing E:\tmp\220803_unsync_rpe_imac\msf_220803\k50a_s_1\interact-20220802_PepSep_10_15_0_RPETTBK2KO-LAPN-TTBK2K50A-S-I_Slot1-37_1_12536.pep.xml.tmp.a10656 
INFO[01:05:52] Parsing E:\tmp\220803_unsync_rpe_imac\msf_220803\k50a_s_1\interact-20220802_PepSep_10_15_0_RPETTBK2KO-LAPN-TTBK2K50A-S-I_Slot1-37_1_12536.pep.xml 
panic: Cannot decode packed binary. XML syntax error on line 52912: unexpected EOF

goroutine 99 [running]:
philosopher/lib/msg.callLogrus({0xc0018000a0, 0x4b}, {0x9412c0, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0xa90040?, 0xc0000040f0?}, {0x9412c0, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*PepXML).Parse(0xc0003b7a50, {0xc000028140, 0x94})
	/workspace/philosopher/lib/spc/spc.go:63 +0x1c6
philosopher/lib/id.(*PepXML).Read(0xc00016e2c0, {0xc000028140, 0x94})
	/workspace/philosopher/lib/id/pep.go:207 +0x105
philosopher/lib/id.ReadPepXMLInput.func1(0x1, {0xc000028140, 0x94})
	/workspace/philosopher/lib/id/pep.go:386 +0x105
philosopher/lib/id.ReadPepXMLInput.func2(0x0?, {0xc000028140, 0x94})
	/workspace/philosopher/lib/id/pep.go:422 +0xa2
created by philosopher/lib/id.ReadPepXMLInput
	/workspace/philosopher/lib/id/pep.go:419 +0x978
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping
ERRO[01:05:52] Cannot decode packed binary. XML syntax error on line 52912: unexpected EOF 
```

Janos said that "PTMprophet finished running without any errors, but for a subset of the samples it produced only a pep.xml.tmp file (no mod.pep.xml) and these files are all apparently truncated (they end with a '</spectrum_query>' tag)."

Best,

Fengchao

**Comment by anesvi** [comment]
Can you try again from PTM-Prophet step. Maybe just Parsing E:\tmp\220803_unsync_rpe_imac\msf_220803\k50a_s_1\interact-20220802_PepSep_10_15_0_RPETTBK2KO-LAPN-TTBK2K50A-S-I_Slot1-37_1_12536.pep.xml

See if it is crashes.

Occasionally PTM-Prophet has errorsdue to multithreading. But I think only on windows. Are you running on windows?

**Comment by anesvi** [comment]
Yes I see you are running a windows executable

So, how many cores did you specify? If you run again and get crashes, may need to reduce the number of cores

**Comment by jd690764** [comment]
Hi Alexey,

I am using 48 threads, and so far I had no issues like this. I repeated the
run before asking for your help and got the same error message. I can try
running it again with fewer threads, maybe?

Thanks,
Janos

**Comment by fcyu** [comment]
Hi Janos,

Can you delete all of the `*.pep.xml.tmp*` files and try again? Philosopher would read those files if they are present.

Best,

Fengchao

**Comment by jd690764** [comment]
Hi Fengchao,

I downgraded philosopher to v4.2.1, and re-ran the workflow using the same
parameters - no problem this time.

Thanks for your help.
Janos

**Comment by anesvi** [comment]
I don’t think we changed PTM-Prophet binary in Philosopher for a while. So I am not sure what is going on. Felipe, can you confirm?

**Comment by lumpthree** [comment]
I've Encountered this same error with Philosopher v4.4. Deleting the pep.xml temp files and then re-running with processes set to 1 worked for me.

**Comment by anesvi** [comment]
Yes thanks. For now, the solution seem to be deleting temp files, setting threads to 1, and rerunning from PTMProphet ( unchecking all steps before)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
