### ISSUE TITLE
Analysis of SILAC samples with MBR?

### ISSUE THREAD

**Issue by michaelsteidel86** [Nesvilab/FragPipe#789]
Is there a way to analyze SILAC samples including match-between runs with FragPipe?

Thanks in advance!
Michael

**Comment by haianhle** [comment]
@fcyu is analysis of SILAC samples possible for diaPASEF at the moment? Is the instruction available somewhere you could point me to? So far we've been doing this with DIANN. Thank you.

**Comment by fcyu** [comment]
No, it does not support diaPASEF.

Best,

Fengchao

**Comment by michaelsteidel86** [comment]
Hi Fengchao,

has situation changed in the meantime? 
Does current version (Fragpipe / Ionquant) support MBR for SILAC samples?

Thanks 
Michael

**Comment by fcyu** [comment]
Hi Michael,

It support MBR for SILAC now. We will release a new version soon. If you want to try the pre-release version, please send an email to yufe AT umich.edu

Best,

Fengchao
