### ISSUE TITLE
MBR for files with only MS1 scans into library containing MS1 and MS2 scans?

### ISSUE THREAD

**Issue by eliseneedham** [Nesvilab/FragPipe#791]
Thanks for creating and maintaining FragPipe!

I am looking to search some DDA files and match them into a DDA library. These files only had MS1 acquired with the plan to match in to get the identifications. Is this possible with Fragpipe? I tried a standard LFQ-MBR search with one sample file and library files, and it gave a warning:

_Failed in checking 
PATH_EDITED_FOR_QUESTION\sample_file.mzML. Will ignore it.
Cannot invoke "umich.ms.datatypes.scancollection.ScanIndex.getNum2scan()" because the return value of "java.util.TreeMap.get(Object)" is null
PATH_EDITED_FOR_QUESTION\sample_file.mzML: Scans = 0_

This was followed by an error code: 

_Not all given paths exist: Optional[PATH_EDITED_FOR_QUESTION\sample_file.pep.xml]
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping_

I see there is a check for MS2 scans. Would it be possible to skip this step and still search successfully? Not sure if this is relevant but in case this gives more flexibility, I will be building FragPipe from scratch on an HPC.

**Some more file info:** 
- The sample (MS1 only) files were acquired using the BoxCar method but I have converted them to a standard format with https://github.com/statisticalbiotechnology/quandenser-pipeline/blob/master/dependencies/boxcar_converter.py. 
- It seems like BoxCar/the conversion isn’t the issue because converted BoxCar files from PXD009348 searched without errors using the same settings in FragPipe. I can email one of the files with only MS1 if that would help too.
- The library is standard DDA with MS1 and MS2, and gives no errors in this log or when run alone. 

Thanks again!

Best wishes,
Elise

**Comment by fcyu** [comment]
Hi Elise,

No, MS1 only DDA won't work with our tools because we need MS/MS to have some IDs for retention time alignment.

Best,

Fengchao
