### ISSUE TITLE
Visualization fails to open.

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#795]
Running a typical MSFragger workflow with Percolator validation run finishes without errors.
Clicking Open visualization window results in: Failed to parse result, please check file.
What file is it looking for?

**Comment by fcyu** [comment]
Can you send us the log file?

Thanks,

Fengchao

**Comment by rudnickp** [comment]
[log_2022-08-12_13-14-51.txt](https://github.com/Nesvilab/FragPipe/files/9329640/log_2022-08-12_13-14-51.txt)

**Comment by fcyu** [comment]
Thanks for your file. My guess is that the visualization module expects the proteins with 1% FDR but you didn't run protein inference. Can you load the built-in workflow or enable 'Protein Inference" and try again?

Best,

Fengchao

**Comment by rudnickp** [comment]
Enabling Run ProteinProphet fixed the problem.
Thank you
Paul
