### ISSUE TITLE
Saving workflows

### ISSUE THREAD

**Issue by rudnickp** [Nesvilab/FragPipe#796]
- Describe the issue or question:
After saving a workflow in FragPipe, the selection drop-down defaults back to the first workflow on the list.  This is confusing and may cause unexpected overwriting.  This is a request keep the saved workflow as active.

**Comment by fcyu** [comment]
Sorry for the late response. I finally got a chance to fix this bug: https://github.com/Nesvilab/FragPipe/commit/4be7b750fb09902bc9a291f79ce2fc5ba1031690. The fix will be included in the next release.

Let me know if you have any further question.

Best,

Fengchao
