### ISSUE TITLE
Easypqp install SSL certificate problem

### ISSUE THREAD

**Issue by emhumphries** [Nesvilab/FragPipe#798]
Hello, I uninstalled easypqp 0.1.29 in Fragpipe v18.0 and now I can't reinstall it due to an SSL issue. Below are the error messages from both the GUI button and anaconda commandline. Do you have any suggestions on how to get around this?
![image](https://user-images.githubusercontent.com/74599273/184528349-dadde279-e618-4186-91f6-fedbe38efe9c.png) 
![image](https://user-images.githubusercontent.com/74599273/184528446-92652ad8-0c84-4d43-96a9-6751f8c9df4b.png)
Thanks,
Erin

**Comment by fcyu** [comment]
Hi Erin,

It is due to your system configuration. Not a problem in our tools. Please contact your IT department.

Best,

Fengchao

**Comment by guoci** [comment]
@emhumphries The article below might help resolve your problem.
https://jhooq.com/2-ways-to-fix-ssl-certificate-problem-self-signed-certificate-in-certificate-chain/#pip
