### ISSUE TITLE
Parameter groups similar to MaxQuant

### ISSUE THREAD

**Issue by Skourtis** [Nesvilab/FragPipe#802]
Hi, 

I'm looking to analyse a big collection of SILAC experiments which have different labelling strategies. Some are Heavy Light, some are Heavy Medium Light,  and some even have different digestion enzymes. When I've previously done this in MaxQuant, I can define parameter groups for each raw file, and each group has its own labelling strategy.

Is this possible in Fragpipe? If not, could I somehow run each 'parameter group' as a search, and then combine the output of the individual  ion_quant files?

Could this be related to https://github.com/Nesvilab/FragPipe/issues/258 ? 

Thank you,
Savvas

**Comment by fcyu** [comment]
Hi Savvas,

Yes, it is the same as https://github.com/Nesvilab/FragPipe/issues/258. You can run the searches separately and combine the result by yourself.

I will close this issue since it is a duplicate one.

Best,

Fengchao

**Comment by Skourtis** [comment]
Thank you Fengchao for the answer.

Last clarification. Are you suggesting to simply concatinate the different ion_quant tables from the different runs? This won't lead to changes in fdr/ normalisation problems?

Thank you,
Savvas

**Comment by fcyu** [comment]
Hi Savvas,

You probability need to redo the FDR filtering if you want all your data is filtered with global FDR. As to the normalization, You need to decide according to your data since it is from different experiments.

Best,

Fengchao
