### ISSUE TITLE
SILAC IonQuant Issues in FragPipe18

### ISSUE THREAD

**Issue by fshikwana** [Nesvilab/FragPipe#803]
Hi,

We've been using FragPipe to search our data for a while now and everything was going great; however, since the update to fragpipe 18, I have not been able to get a quant output from SILAC samples. When I run the same files on fragpipe 17.1, the search finishes with no issues. Am I doing something wrong? I'm using the same saved workflow I have always used for SILAC. 
I've uploaded a log file of one of my SILAC searches.

Thank you,
Flow

- Upload your log file
[log_2022-08-10_16-43-41.txt](https://github.com/Nesvilab/FragPipe/files/9398592/log_2022-08-10_16-43-41.txt)

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Flow,

Can you send one of your psm.tsv file to me? Or, if it is OK, can you send all of your files to me? I can give you a link to upload the files if you need one.

Thanks,

Fengchao

**Comment by fshikwana** [comment]
Yes, I can send you all of my files. I think I'll need an upload link.

Thanks,
Flow

**Comment by fcyu** [comment]
Thank you! Here is the link: https://www.dropbox.com/request/1D876h7DfJuxU39yN3LI

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Flow,

Thanks for your files. 

I just noticed that you are using IonQuant version 1.8.1 which is not a formal released version. It is a beta version that might have bugs. Can you download the version 1.8.0 and try again?

Best,

Fengchao

**Comment by fcyu** [comment]
BTW, if you want a fixed pre-released version, please send an email to yufe AT umich DOT edu. I can send you a new one.

Best,

Fengchao

**Comment by fshikwana** [comment]
I'll try it with the 1.8.0 version and let you know. The 1.8.1 version is the one the lab now uses due to a fixed issue with certain masses not working for quant. I'm pretty sure my labmate had reached out to you guys & the 1.8.1 version was the one you sent to us.

Thanks,
Flow

**Comment by fcyu** [comment]
Yes, you are correct. I fixed the masses issue for your lab but introduced the new one. I have a fixed version now. If you want to have a try, please send an email to me so that I can send you the link to download.

Best,

Fengchao

**Comment by fshikwana** [comment]
Ion quant 1.8.0 seems to work for SILAC searches. 

Thank you,
Flow
