### ISSUE TITLE
Error "ERRO[08:36:50] Cannot decode packed binary. XML syntax error on line 3631: unexpected EOF"

### ISSUE THREAD

**Issue by Maithy15** [Nesvilab/FragPipe#807]
Hi,

I got the following error "ERRO[08:36:50] Cannot decode packed binary. XML syntax error on line 3631: unexpected EOF", and fragpipe stopped. I have attached the whole log file for you. I checked the previous issues, and it seems this error means there is some special char. in the interact XML file.

Please let me know how to solve this problem. Is restarting the search enough?

log file
[log_2022-08-25_08-57-27.zip](https://github.com/Nesvilab/FragPipe/files/9422221/log_2022-08-25_08-57-27.zip)
)

**Comment by anesvi** [comment]
@Maithy15 can you confirm there were 'xml.tmp' files, and you were able to run the tools after cleaning the folder?

**Comment by Maithy15** [comment]
@anesvi Sorry for not updating! The XML.tmp files there. I restarted after cleaning the folder and it worked!

Thanks
Maithy

**Comment by anesvi** [comment]
@prvst can we print an informative error message when this error happens and there are 'tmp.xml' files in the directory. I am not sure though if we can figure out why they are present. We should discuss internally.

**Comment by prvst** [comment]
already done!

**Comment by fcyu** [comment]
We have the pre-release versions of FragPipe and MSFragger than fixes the multi-threading issue in PTMProphet.

Please contact us for the pre-release versions if you want to have a try.

Best,

Fengchao

**Comment by ougochu** [comment]
Note: I'm running FragPipe 18.0 / MS Fragger 3.5 / IonQuant 1.8.0 / Philosopher 4.4.0 / Python 3.9.12 on a Windows 8.1 machine.

@Maithy15 @prvst when you all refer to XML.tmp files existing in a directory, to which directory are you referring? The directory containing the .mzML files / .raw files? The output directory? I'm having very similar issues to @Maithy15 but was not able to find any .tmp files.

Attached you'll find 2 log files: the earliest one was automatically generated when the run stopped. The later one was user-generated, and includes the error code.

Thanks for any help,

OU
[221103_Run1_Logs.zip](https://github.com/Nesvilab/FragPipe/files/9938967/221103_Run1_Logs.zip)

**Comment by Maithy15** [comment]
If I remember correctly, they were in the output folder.

**Comment by fcyu** [comment]
Hi @ougochu ,

Your crash is different from @Maithy15 's. It is not because of the tmp file left from PTMProphet. You did not run PTMProphet. 

Hi Felipe @prvst , can you take a look? The error messages are

```shell
INFO[05:18:32] 1+ Charge profile                             decoy=0 target=0
INFO[05:18:32] 2+ Charge profile                             decoy=5410 target=182987
INFO[05:18:32] 3+ Charge profile                             decoy=4423 target=258715
INFO[05:18:32] 4+ Charge profile                             decoy=1319 target=44999
INFO[05:18:32] 5+ Charge profile                             decoy=353 target=4584
INFO[05:18:32] 6+ Charge profile                             decoy=98 target=551
INFO[05:18:35] Database search results                       ions=197240 peptides=143408 psms=503509
INFO[05:18:36] Converged to 1.00 % FDR with 475136 PSMs      decoy=4796 threshold=0.723073 total=479932
INFO[05:18:36] Converged to 1.00 % FDR with 123840 Peptides  decoy=1250 threshold=0.892011 total=125090
INFO[05:18:36] Converged to 1.00 % FDR with 176057 Ions      decoy=1777 threshold=0.854113 total=177834
panic: Cannot decode packed binary. XML syntax error on line 1153751: unexpected EOF

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc004f82820, 0x4d}, {0xb312c0, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0xc80040?, 0xc0035f6480?}, {0xb312c0, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*ProtXML).Parse(0xc02202f8e0, {0xc00001c200, 0x3a})
	/workspace/philosopher/lib/spc/spc.go:91 +0x20e
philosopher/lib/id.(*ProtXML).Read(0xc02202fb88, {0xc00001c200?, 0x20ca680?})
	/workspace/philosopher/lib/id/pro.go:121 +0x85
philosopher/lib/fil.ReadProtXMLInput({0xc00001c200?, 0xd?}, {0xc000018128, 0x4}, 0x3ff0000000000000)
	/workspace/philosopher/lib/fil/fil.go:507 +0x9f
philosopher/lib/fil.Run({{0xc0001acc60, 0x24}, {0xc0001acc90, 0x2f}, {0xc0001b2640, 0x49}, {0xc0001aa900, 0x3e}, {0xc0001aa940, 0x35}, ...})
	/workspace/philosopher/lib/fil/fil.go:80 +0x77a
philosopher/cmd.glob..func5(0x20d4040?, {0xb30ca0?, 0xb?, 0xb?})
	/workspace/philosopher/cmd/filter.go:43 +0x390
github.com/spf13/cobra.(*Command).execute(0x20d4040, {0xc0000e6790, 0xb, 0xb})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x20d2b40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[05:18:52] Cannot decode packed binary. XML syntax error on line 1153751: unexpected EOF 
```

Best,

Fengchao

**Comment by prvst** [comment]
@ougochu can you share your prot.xml file ?

**Comment by ougochu** [comment]
@fcyu thank you, understood.

@prvst my combined.prot.xml file for "Run 1" (for which the error logs are pasted) is attached -- thank you!
[221103_Run1_combined.prot.zip](https://github.com/Nesvilab/FragPipe/files/9940587/221103_Run1_combined.prot.zip)

**Comment by prvst** [comment]
@ougochu your file is corrupted, the writing stopped midway down, looks like a large chunk is just missing.

**Comment by ougochu** [comment]
@prvst agreed. I haven't been able to reproduce the error on subsequent runs with fewer batches/samples. I'll see if, and under what conditions, it happens again when running the same dataset.

**Comment by fcyu** [comment]
We have released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
