### ISSUE TITLE
Java or RAM issue?

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/FragPipe#809]
- Describe the issue or question:
Hello,

We are trying to run a sizeable data set (64 .raw files, 143GB), I am trying it on Amazon Cloud at 64Gb RAM. I attached the log file, at the end there seems to be java errors, although there are likely others as well. I also attached images of the java version and the system info. If it just needs more RAM I can run on more RAM through AWS, but was hoping 64Gb would be enough :)

Thank you so much for any advice you can provide

All the best,

Jason
[log_2022-08-26_20-25-36.txt](https://github.com/Nesvilab/FragPipe/files/9436345/log_2022-08-26_20-25-36.txt)
<img width="552" alt="system info" src="https://user-images.githubusercontent.com/72038445/186988402-5a2fe0a1-360b-40c4-8f82-e962a8ac831b.png">
<img width="299" alt="java version" src="https://user-images.githubusercontent.com/72038445/186988423-82592f07-88c3-48e5-bd53-135a50944aec.png">

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It is not about the memory. 

There are several errors due to different reasons. 

1. Some of your files are corrupted:
```
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-36.raw. Will ignore it.
UNAVAILABLE: OS Error
C:\Users\Administrator\Downloads\S22034-Nick-36.raw: Scans = 0
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-52.raw. Will ignore it.
UNKNOWN
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-60.raw. Will ignore it.
UNKNOWN
C:\Users\Administrator\Downloads\S22034-Nick-52.raw: Scans = 0
C:\Users\Administrator\Downloads\S22034-Nick-60.raw: Scans = 0
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-44.raw. Will ignore it.
UNAVAILABLE: io exception
C:\Users\Administrator\Downloads\S22034-Nick-44.raw: Scans = 0
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-28-2nd.raw. Will ignore it.
UNKNOWN
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-53.raw. Will ignore it.
UNKNOWN
Failed in checking C:\Users\Administrator\Downloads\S22034-Nick-11.raw. Will ignore it.
UNKNOWN
C:\Users\Administrator\Downloads\S22034-Nick-28-2nd.raw: Scans = 0
C:\Users\Administrator\Downloads\S22034-Nick-53.raw: Scans = 0
C:\Users\Administrator\Downloads\S22034-Nick-11.raw: Scans = 0
```

2. There are errors that I never saw. Please double check your files and system.
```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 63 out of bounds for length 58
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index 63 out of bounds for length 58
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Best,

Fengchao

**Comment by jmcalist** [comment]
Thanks so much, I tried with the jre version of Fragpipe with Java and it seems to have done better, but looks like it got stuck on sample 49 (logfile attached)

I checked the file for this sample and when I checked the TIC in SeeMS from ProteoWizard, the following error resulted:, do you happen to know what could cause this error?

Thanks so much!

[cid:f72d8a98-8cf9-4d5b-8626-d07dfa0b1d21]
________________________________

**Comment by fcyu** [comment]
I can't find the whole log or the screenshot. Can you put them in a zip file and reply them in the GitHub?

Thanks,

Fengchao

**Comment by jmcalist** [comment]
Thanks so much, here you are!
[log_2022-08-27_03-20-25.txt](https://github.com/Nesvilab/FragPipe/files/9439916/log_2022-08-27_03-20-25.txt)
![SeeMS error message](https://user-images.githubusercontent.com/72038445/187081113-f23cfdfd-08ec-4549-bad1-1d3a81a9c4aa.png)

**Comment by fcyu** [comment]
I have no idea about your errors. It also looks like the Thermo raw reader couldn't work well on your computer.

As a workaround, you can convert your raw files to mzml files, and then, using them in FragPipe. Here is the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by jmcalist** [comment]
Thanks so much! I have converted to mzml with past fragpipe runs and will try that again with this one

Thanks as always for all your assistance!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
