### ISSUE TITLE
Not all contaminants are specified as contaminants

### ISSUE THREAD

**Issue by JensSettelmeier** [Nesvilab/FragPipe#813]
Dear Fragpipe team,

FYI - in the dabase section, if you use a fasta file with the proteome of e.g. rabbit and use the function "add contaminants and decoys", some usual human contaminants are added, but not specified with "cont" at the beginning of the entry in the fasta file. 
In a resulting protein.tsv human proteins are then identified and not marked as cont, which is strange if you search against rabbit proteome. 

Cheers,
Jens

**Comment by prvst** [comment]
A fix was implemented and will be availabale in the next release
