### ISSUE TITLE
PEP and q-values in psm.tsv?

### ISSUE THREAD

**Issue by michaelsteidel86** [Nesvilab/FragPipe#816]
Which values within the psm.tsv table correspond to posterior error probabilities (PEP) & q-values? How are the measures "Expectation" and "PeptideProphet Probability" related to PEPs and q-values? 

In case there is no direct link - how could one include these measures?

**Comment by fcyu** [comment]
PeptideProphet Probability = 1 - PEP
The psm.tsv is filtered with 1% PSM and protein level FDR. q-value is the monotone version of FDR.

Best,

Fengchao

**Comment by anesvi** [comment]
I would add that is using Percolator, the columns PeptideprophetProbability is 1-PEP  (where PEP is from Percolator)

I would not worry about the PEP or probabilities at the PSM level though, as they are not that meaningful in the statistical sense. Really can think of them as scores.

Here is a review I can recommend:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2956504/

Best
Alexey
