### ISSUE TITLE
Advise on file labeling (IonQuant + MBR) before MSFragger LFQ Search using FragPipe

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/FragPipe#819]
Good day

I have the following experimental design, with the orange icons being analyzed with proteomics. I want to use fragpipe and MSstat, what would be the best way to annotate the files when uploading them to Fragpipe?
![Experimental Design](https://user-images.githubusercontent.com/109790066/188856700-b0988a8c-bb6e-4fd4-8b0d-bac12285ad76.PNG)

Would this be correct?
![image](https://user-images.githubusercontent.com/109790066/188858091-f77c10e6-2f9d-4014-99f3-ca87da4e2112.png)

It would be great to hear back from you.
Melissa

**Comment by fcyu** [comment]
Hi Melissa,

Thanks for your interest in our tools. 

If your "replicates" are not fractions, you need to give different "bioreplicates". In case you need more details, here (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#single-experiment-report) is the tutorial about assigning experimental groups. Here (https://github.com/Nesvilab/FragPipe/issues/183) has some discussion regarding the MSstats.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Hi, thank you for getting back to me. 

I am new to the field of proteomics, could you explain what a fraction is?

I've looked at those to sources, but unfortunately still struggling to translate it conceptually to my situation.

Regards
Melissa

**Comment by MelissaVorster** [comment]
Allright, will do.

Regarding IonQuant and MSstat, is there any other documentation to read except https://fragpipe.nesvilab.org/docs/tutorial_msstats.html ? Any resource that can work as a tutorial that explains the steps and output?

**Comment by fcyu** [comment]
I think you should start with https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html, and then https://fragpipe.nesvilab.org/docs/tutorial_lfq.html. 

As to the output files, https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html is the one you should read. 

Also https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_workflows.html for built-in workflows and https://fragpipe.nesvilab.org/docs/tutorial_convert.html for raw data conversion in case you need it.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Thank you for sharing this information. I have been trying to follow those steps as far as possible. Just still a bit unclear about the difference between MSstats, IonQuant and then something like Skyline?

**Comment by fcyu** [comment]
They are different tools to perform label-free quantification. You only need to use one of them. Since you are already using FragPipe, you can stick to IonQuant which is included in FragPipe. The LFQ (https://fragpipe.nesvilab.org/docs/tutorial_lfq.html) tutorial should cover most of the content that you need.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Thank you Fengchao, I've followed those steps.
I would like to identify and quantify the proteins. How does one use the output from that steps in the LFQ link to quantify the proteins? To see which proteins are upregulated and which are downregulated?

**Comment by fcyu** [comment]
You can use `combined_protein.tsv` and look at the `[experiment] Intensity` columns.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Great, and how is the intensity calculated?

**Comment by fcyu** [comment]
Please check the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_proteintsv

If you want to know what "MaxLFQ" and "Top-N" mean, please check the paper: https://www.sciencedirect.com/science/article/pii/S1535947621000505?via%3Dihub

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Yes, thank you I have looked at most of these tutorials, therefore asking these questions here. Thank you for the swift responses nonetheless, I will look at that paper :)
