### ISSUE TITLE
MSstat error: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :   Ran out of iterations and did not converge

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/FragPipe#820]
Hi 
When I tried to follow the MSstat code [https://fragpipe.nesvilab.org/docs/tutorial_msstats.html](url) so that I could generate a protein intensity table, I got the following error? 

![image](https://user-images.githubusercontent.com/109790066/188957692-3c355775-9ad2-4172-8525-0d2721e41620.png)

Resulting in an empty tsv file output. Could you perhaps help?

Regards
Melissa

**Comment by fcyu** [comment]
Can you send the log file and your command?

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Log file:
[log_2022-09-07_21-08-38.txt]

R commands:
[MSstat_Rcommands.txt](https://github.com/Nesvilab/FragPipe/files/9508978/MSstat_Rcommands.txt)

Let me know if these will do :)

**Comment by MelissaVorster** [comment]
Log file:
[log_2022-09-07_21-08-38.txt](https://github.com/Nesvilab/FragPipe/files/9508983/log_2022-09-07_21-08-38.txt)


R commands:
[MSstat_Rcommands.txt](https://github.com/Nesvilab/FragPipe/files/9508978/MSstat_Rcommands.txt)

Let me know if these will do :)

**Comment by fcyu** [comment]
Can you send the log/output messages from R?

**Comment by MelissaVorster** [comment]
if (!requireNamespace("BiocManager", quietly = TRUE))
+   install.packages("BiocManager")
> 
> BiocManager::install("MSstats")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.1 (2022-06-23 ucrt)
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.2.1/library
  packages:
    cluster, MASS, nlme, survival
Warning message:
package(s) not installed when version(s) same as current; use `force = TRUE` to re-install: 'MSstats' 
> 
> rm(list = ls())
> library(stringr)
> library(readr)
> library(MSstats)
> 
> rootDir <- "C:\\Users\\23308834\\Desktop\\TD_Fragpipe_LFQ_AllTogetherDiffExpDesign\\" # Specify the path of the directory containing MSstats.csv.
> print(str_c("Using IonQuant's result from ", rootDir))
[1] "Using IonQuant's result from C:\\Users\\23308834\\Desktop\\TD_Fragpipe_LFQ_AllTogetherDiffExpDesign\\"
> 
> # Read MSstats.csv file.
> raw <- read_csv(str_c(rootDir, "MSstats.csv"), na = c("", "NA", "0"))
Rows: 813008 Columns: 10                                                                                                                                                                            
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (5): ProteinName, PeptideSequence, IsotopeLabelType, Condition, Run
dbl (3): PrecursorCharge, BioReplicate, Intensity
lgl (2): FragmentIon, ProductCharge

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> raw$ProteinName <- factor(raw$ProteinName)
> raw$PeptideSequence <- factor(raw$PeptideSequence)
> 
> # Change root directory for MSstats
> print(str_c("Root DIR: ", rootDir))
[1] "Root DIR: C:\\Users\\23308834\\Desktop\\TD_Fragpipe_LFQ_AllTogetherDiffExpDesign\\"
> setwd(rootDir)
> 
> # Processing the data using MSstats
> processedData <- dataProcess(raw, logTrans = 10)
INFO  [2022-09-07 21:18:49] ** Features with one or two measurements across runs are removed.
INFO  [2022-09-07 21:18:49] ** Fractionation handled.
INFO  [2022-09-07 21:18:50] ** Updated quantification data to make balanced design. Missing values are marked by NA
INFO  [2022-09-07 21:18:53] ** Log2 intensities under cutoff = 5.127  were considered as censored missing values.
INFO  [2022-09-07 21:18:53] ** Log2 intensities = NA were considered as censored missing values.
INFO  [2022-09-07 21:18:53] ** Use all features that the dataset originally has.
INFO  [2022-09-07 21:18:59] 
 # proteins: 3517
 # peptides per protein: 1-262
 # features per peptide: 1-1
INFO  [2022-09-07 21:18:59] Some proteins have only one feature: 
 sp|A2A432-2|CUL4B_MOUSE,
 sp|A2A4P0|DHX8_MOUSE,
 sp|A2A5R2|BIG2_MOUSE,
 sp|A2A6Q5-2|CDC27_MOUSE,
 sp|A2A8Z1-2|OSBL9_MOUSE ...
INFO  [2022-09-07 21:19:00] 
                    Control Treatment
             # runs      14        14
    # bioreplicates       2         2
 # tech. replicates       7         7
INFO  [2022-09-07 21:19:00] Some features are completely missing in at least one condition:  
 KELFLSK_2_NA_NA,
 LFSADPFDLEAQAK_2_NA_NA,
 HQLEEEQK_2_NA_NA,
 EFLLSMANR_2_NA_NA,
 ADAVQEATFQVELPR_2_NA_NA ...
INFO  [2022-09-07 21:19:00]  == Start the summarization per subplot...
  |=======================================================================================================================================================| 100%
INFO  [2022-09-07 21:21:49]  == Summarization is done.
Warning messages:
1: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
2: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
3: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
4: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
5: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
6: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
7: In survreg.fit(X, Y, weights, offset, init = init, controlvals = control,  :
  Ran out of iterations and did not converge
> 
> print("Preparing a protein-intensity table.")
[1] "Preparing a protein-intensity table."
> x <- processedData$RunlevelData
> y <- data.frame(matrix(nrow=length(unique(x$Protein)), ncol=length(unique(x$SUBJECT_NESTED)) + 1))
> colnames(y) <- c("Protein", unique(as.character(x$SUBJECT_NESTED)))
> y$Protein <- unique(x$Protein)
> for (protein in y$Protein) {
+   for (subject in unique(x$SUBJECT_NESTED)) {
+     if (length(x[x$Protein == protein & x$SUBJECT_NESTED == subject,]$LogIntensities) > 0) {
+       y[y$Protein == protein, match(subject, colnames(y))] <- x[x$Protein == protein & x$SUBJECT_NESTED == subject,]$LogIntensities
+     }
+   }
+ }
> 
> write_csv(y, str_c(rootDir, "MSstats_protein.csv"), na = "")

**Comment by MelissaVorster** [comment]
[R_log.txt](https://github.com/Nesvilab/FragPipe/files/9509045/R_log.txt)

**Comment by fcyu** [comment]
The programs ran OK. Maybe something is wrong with your input data, which I can't check. Please see if there are non-zero intensities in "MSstats.csv", and if there are outputs from MSstats.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Input file:
[MSstats.zip](https://github.com/Nesvilab/FragPipe/files/9509086/MSstats.zip)


Output file: (empty)
[MSstats_protein.csv](https://github.com/Nesvilab/FragPipe/files/9509089/MSstats_protein.csv)

**Comment by fcyu** [comment]
Thanks for your files.

I figured out the reason. It looks like MSstats changed the output format, which breaks the "Preparing a protein-intensity table." part. You can delete everything starting from `print("Preparing a protein-intensity table.")` and write your own downstream analysis using MSstats' output: `processedData `.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
All right, thank you for looking at this with me. It seemed like when I ran just the first bit up to `print("Preparing a protein-intensity table.")` it still gave me that error...

Is there any MSstat manual I can follow for the downstream analysis?

**Comment by fcyu** [comment]
I ran it with your MSstats,csv, there is no error. The red message you pasted are not errors. Here (https://www.bioconductor.org/packages/release/bioc/html/MSstats.html) is the MSstats webpage.

Best,

Fengchao

**Comment by MelissaVorster** [comment]
Ok, thank you for the assistance.
