### ISSUE TITLE
`"` in the fasta file broke the program.

### ISSUE THREAD

**Issue by SarMich** [Nesvilab/FragPipe#821]
Hello, 

I am attempting to run a peptidome workflow, but the Fragger search fails with the error "_csv.Error: field larger than field limit (131072)" .  I have attached the log, and would appreciate your help in finding if my settings are incorrect or how I can fix the error.

Thank you,
Sarah

[log_2022-09-12_10-53-32.txt](https://github.com/Nesvilab/FragPipe/files/9550644/log_2022-09-12_10-53-32.txt)

**Comment by fcyu** [comment]
I think this is the bug in the split database. Guo Ci @guoci , can you take a look?

Thanks,

Fengchao

**Comment by guoci** [comment]
@SarMich Can you show me the all of the generated `pin` files? It looks like some might have very huge fields.

**Comment by SarMich** [comment]
@guoci Here they are, let me know if this is what you need.  Part 1:

[pin files_0-4.zip](https://github.com/Nesvilab/FragPipe/files/9560155/pin.files_0-4.zip)

**Comment by SarMich** [comment]
Part 2: 
[pin files_5-9.zip](https://github.com/Nesvilab/FragPipe/files/9560160/pin.files_5-9.zip)

**Comment by guoci** [comment]
At least one of the pin files is invalid, those are tab delimited files, but one field is very large.
![image](https://user-images.githubusercontent.com/1260178/189993832-38de010c-c8e3-42a9-af8c-3cfdd6107cbd.png)

**Comment by fcyu** [comment]
Hi @SarMich ,

Can you sand us your fasta file?

Thanks,

Fengchao

**Comment by guoci** [comment]
Can you also send the fasta?

**Comment by SarMich** [comment]
Yes, here it is - the original fasta was downloaded from uniprot, and decoys were added in fragpipe.   Thank you!

[fasta.zip](https://github.com/Nesvilab/FragPipe/files/9560368/fasta.zip)

**Comment by fcyu** [comment]
Those `"` broke the program. I am not sure where they are from. 
![image](https://user-images.githubusercontent.com/6926299/189999046-da108dd4-0288-49d1-8b1d-ce74be694fcd.png)

Can you download a new fasta file from scratch, and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment]
BTW, they are also in your original fasta file:
![image](https://user-images.githubusercontent.com/6926299/189999469-48de5974-5563-40ee-a5ad-badaad030f07.png)

Best,

Fengchao
