### ISSUE TITLE
checkcentroid returning 1 and fragpipe quits

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/FragPipe#822]
- Describe the issue or question:
I have tried running fragpipe on our network compute cluster and the code exits out with: 
"CheckCentroid
java -Xmx79G -cp /users/smburke/fragpipe/lib/fragpipe-18.0.jar:/users/smburke/fragpipe/toIols/batmass-io-1.25.5.jar com.dmtavt.fragpipe.util.CheckCentroid /users/smburke/FragWorkingDir/JS-CS-220613_GroopmanJ_JS_PAA_1_P19.mzXML 1
Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping"

I am unsure why this is happening. I have run the fragpipe using the same manifest, workflow and cache on the terminal of an ubuntu vm with the correctly referenced paths and it ran just fine on that machine. Any help would be appreciated

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid trun
[fragpipe_run.txt](https://github.com/Nesvilab/FragPipe/files/9552688/fragpipe_run.txt)
cation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
You are using **mzXML** format. Please re-convert your data from raw to **mzML**. Here is the tutorial in case you need it: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by jossmi** [comment]
Hi Fengchao, thanks for your quick reply. Sean and I are working together on the project, so I just wanted to clarify - our workflow is running DIA-Umpire on demultiplexed overlapping-window DIA data, to pass pseudo-DDA data to MSFragger for open searching. My understanding was that DIA-Umpire required mzXML input files and generates mzML output files for MSFragger to use. I'm running this workflow right now on these same mzXML files on my desktop, actually, and it works fine, so is the file format really the issue? Sean is trying to get this up and running on a computing cluster using the command line, so is there a command  that needs to be included to make sure FragPipe knows that it's dealing with DIA mzXML data for DIA-Umpire to use (like when the data type is specified on the "Workflow" tab in the FragPipe GUI)?

Thanks!

**Comment by fcyu** [comment]
>  My understanding was that DIA-Umpire required mzXML input files and generates mzML output files for MSFragger to use.

DIA-Umpire support mzML format now. I suggest you use mzML format since there are more information.

> I'm running this workflow right now on these same mzXML files on my desktop, actually, and it works fine, so is the file format really the issue?

Sorry for the confusion. I double checked the code, and it looks like the `CheckCentroid` should support mzXML format. Then the error should be due to something else.

> is there a command that needs to be included to make sure FragPipe knows that it's dealing with DIA mzXML data for DIA-Umpire to use (like when the data type is specified on the "Workflow" tab in the FragPipe GUI)?

You pass that information using manifest file and workflow file. There are data type column in the manifest file.

Best,

Fengchao

**Comment by mremachine1** [comment]
I set it up according to the workflow and manifest that my colleague josh gave me and opened the gui on the server to point to the locations for msfragger, philosopher and python. I am still getting the check centroid exit code one error.
I am using jdk 14.0.2, python 2.7, msfragger 3.5, philosopher 4.4, and diaumpire 2.2.8, and ptmshepherd 2.0. I am not sure where there run problem is coming from. I've included the log, workflow, manifest and both caches below as text files. any suggestions would be appreciated. 
Thanks, 
Sean
Process 'CheckCentroid' finished, exit code: 1
Process returned non-zero exit code, stopping
Error occurred during initialization of VM
Could not reserve enough space for 193986560KB object heap


[wkflow.txt](https://github.com/Nesvilab/FragPipe/files/9559637/wkflow.txt)
[ui-cache.txt](https://github.com/Nesvilab/FragPipe/files/9559646/ui-cache.txt)
[runtime-cache.txt](https://github.com/Nesvilab/FragPipe/files/9559681/runtime-cache.txt)
[log.txt](https://github.com/Nesvilab/FragPipe/files/9559683/log.txt)
[manifest.txt](https://github.com/Nesvilab/FragPipe/files/9559684/manifest.txt)

**Comment by fcyu** [comment]
Hi Sean,

It seems that Java couldn't allocate 348 GB in your server. I don't know the reason, but can you manually set a smaller RAM value using `--ram` flag?

Thanks,

Fengchao

**Comment by mremachine1** [comment]
does it take units like --ram 25G? what is the format and thanks

**Comment by fcyu** [comment]
It is a good question! It takes integer and the unit is GB. For example, `--ram 25` means 25 GB.

Best,

Fengchao
