### ISSUE TITLE
MSFragger error when DIA-Umpire SE Q3 set to off

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#823]
Hi all,

I have DIA data that I am converting to pseudo-DDA with DIA-Umpire, followed by open search with MSFragger. Typically, I don't get very good PSM hits in the Q3 tier of DIA-Umpire output, so I would like to leave that unchecked in the DIA-Umpire tab and not spend the time generating or searching it. However, I am getting an error from MSFragger, which appears to be expecting the Q3 files to be present. Am I misunderstanding the function/purpose of that Q3 checkbox or missing something else in the settings? This isn't halting my workflow, as I can get around this by just allowing DIA-Umpire to generate the Q3 files, but we would like to avoid dealing with the Q3 files if possible, since we are trying to get this workflow deployed on a computing cluster and we would like to avoid the extra processing time and data storage needs. 

I've attached my log and parameter files. 

Thanks,
Josh

[fragger_dda.params.txt](https://github.com/Nesvilab/FragPipe/files/9552936/fragger_dda.params.txt)
[lcms-files_2022-09-12_21-17-42.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/9552937/lcms-files_2022-09-12_21-17-42.fp-manifest.txt)
[log_2022-09-12_21-17-42.txt](https://github.com/Nesvilab/FragPipe/files/9552938/log_2022-09-12_21-17-42.txt)
[umpire-se.params.txt](https://github.com/Nesvilab/FragPipe/files/9552939/umpire-se.params.txt)
[diaumpire_se.log](https://github.com/Nesvilab/FragPipe/files/9552940/diaumpire_se.log)

**Comment by fcyu** [comment]
Hi Josh,

Thanks for your feedback. Another user also contacted us about this bug today. I have fixed it. If you want to try the pre-released version, please feel free to let me know.

Best,

Fengchao

**Comment by jossmi** [comment]
So MSFragger 3.5 does not have this fix, correct? How would I get the pre-released version? And would that be just this bug fix or additional experimental updates for the next version?

Josh

Joshua W. Smith, Ph.D.
Research Associate

Department of Environmental Health and Engineering
Johns Hopkins Bloomberg School of Public Health

Mass Spectrometry and Proteomics Facility
Department of Biological Chemistry
Johns Hopkins University School of Medicine

**Comment by fcyu** [comment]
If you want to test the pre-release version, please send an email to yufe AT umich.edu. The pre-release will have new functions, not just the bug fix.

Best,

Fengchao
