### ISSUE TITLE
LFQ-phospho workflow: cannot decode packed binary

### ISSUE THREAD

**Issue by without1102** [Nesvilab/FragPipe#825]
I tried to use LFQ-phopho workflow to quantify my phosphoproteomics data. I converted the raw files into mzML files, and run the workflow in FragPipe (v 18.0). However, it showed that  "panic: Cannot decode packed binary. XML syntax error on line 408092: unexpected EOF" in search log and stopped running FragPipe. I attached my search log as below. Please help me check the log. Thank you very much.

Best,

Chuan-Chih

[log_2022-09-13_16-57-14.txt](https://github.com/Nesvilab/FragPipe/files/9555299/log_2022-09-13_16-57-14.txt)

**Comment by danielgeiszler** [comment]
This normally means you have a temporary interact pepXML file from a previous PeptideProphet run that needs to be deleted. Please check to see if you have something that looks like a temporary xml file in your directory, delete it, and rerun the tools that have no finished.

Alternatively, restart your analysis in a clean directory.

**Comment by anesvi** [comment]
It may also happen if PTM-prophet did not complete an analysis of a fine. Can you rerun as Danny suggested, and send us the log file if still a problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by without1102** [comment]
Hello Danny and Alexey,

Thank you for your suggestion. I deleted the temporary xml files from my previous run and rerun it. But I still got the same error message and I attached the log file. Please help me take a look. Thank you for your time.

Chuan-Chih
[log_2022-09-14_11-52-42.txt](https://github.com/Nesvilab/FragPipe/files/9562563/log_2022-09-14_11-52-42.txt)

**Comment by anesvi** [comment]
It looks like fir a very small number of users PTM-Prophet has issues.
Unfortunately, we do not know how to resolve this. The only thing I can suggest to try is to reduce the number of threads (set to say 8 in the Workflow tab).
You can also contact us directly, if you are willing to help us debug the issue. We would need to ask you to run PTM-Prophet binary directly, not as part of Philosopher. So it is easier if you talk to us directly than via github

Best
Alexey

**Comment by without1102** [comment]
Dear Alexey,

I reduced the number of threads to 4, but I still got the same error. Yes, I am willing to work with you to debug this issue. Please tell me how to contact your group. Thanks.

Best,

Chuan-Chih

**Comment by anesvi** [comment]
Please contact me at nesvi at med.umich.edu
And we will communicate directly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anesvi** [comment]
Email me at nesvi at  med.umich.edu

**Comment by fcyu** [comment]
We have the pre-release versions of FragPipe and MSFragger than fixes the multi-threading issue in PTMProphet.

Please contact us for the pre-release versions if you want to have a try.

Best,

Fengchao

**Comment by fcyu** [comment]
We have released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
