### ISSUE TITLE
`"` in the fasta file broke the program.

### ISSUE THREAD

**Issue by DRock420** [Nesvilab/FragPipe#826]
Hi there

I am running a non-specific peptidome search and it runs fine when I set the variable mods to 0 (actually there are no identifications but I am working on that) , however, if I set the variable mods to 1 or more I get an XML syntax error: panic: Cannot decode packed binary. XML syntax error on line 11083: expected attribute name in element 
goroutine 51 [running]:
philosopher/lib/msg.callLogrus({0xc0000ffaa0, 0x5f}, {0x8612c0, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0x9b0040?, 0xc0002bb740?}, {0x8612c0, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*PepXML).Parse(0xc000167a50, {0xc0000b4200, 0x77})
	/workspace/philosopher/lib/spc/spc.go:63 +0x1c6
philosopher/lib/id.(*PepXML).Read(0xc0000ce2c0, {0xc0000b4200, 0x77})
	/workspace/philosopher/lib/id/pep.go:207 +0x105
philosopher/lib/id.ReadPepXMLInput.func1(0x1, {0xc0000b4200, 0x77})
	/workspace/philosopher/lib/id/pep.go:386 +0x105
philosopher/lib/id.ReadPepXMLInput.func2(0x0?, {0xc0000b4200, 0x77})
	/workspace/philosopher/lib/id/pep.go:422 +0xa2
created by philosopher/lib/id.ReadPepXMLInput
	/workspace/philosopher/lib/id/pep.go:419 +0x978
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping
ERRO[11:41:11] Cannot decode packed binary. XML syntax error on line 11083: expected attribute name in element 

If I open the temp xml file and go to line 11083 it looks like this:
peptide="ISPFVARPADDGAFGAKCMGSGNDVVLAAVDDDCM" massdiff="1.981689453125" calc_neutral_pep_mass="3513.5671" peptide_next_aa="V" " num_missed_cleavages="0" num_tol_term="0" protein_descr="40S ribosomal protein S3 OS=Manduca sexta OX=7130 GN=RpS3 PE=2 SV=1" num_tot_proteins="1" tot_num_ions="136" hit_rank="1" num_matched_ions="26" protein="rev_sp|P48153|RS3_MANSE" peptide_prev_aa="V" is_rejected="0" num_missed_cleavages="0">

The software has written an extra " after peptide_next_aa="V" causing a syntax error

Would you have any suggestions?

Running 18.0, 3.5, 4.4.0

Thanks in advance

Derek

**Comment by fcyu** [comment]
Can you send us the log file?

Thanks,

Fengchao

**Comment by DRock420** [comment]
HI Fengchao

Please see attached

Derek

**Comment by fcyu** [comment]
Thanks for the log file. 

There is no ID from your data:
```
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
```

There are also some issue in your fasta file:
```
  - Y:\data\Adamo\REC-2401\20220902_REC-2401_Adamo\Derek_Fragger\interact-20220902_REC-2401_Sample_01_IT.pep.xml
  - Building Commentz-Walter keyword tree...error2 TETSVTDLDYSTIEDTDYTVTDSSTSSDETTGTDDKSSTTT vs YVYYANYSNSLVYNNEEQRLSYFTEDIGLNSYYYYFHSHLPFWWNSERYGALKSRRGEIYYYFYQ
```

I don't know the reason since it is from PeptideProphet. Can you download a new fasta file using FragPipe and try again?

Best,

Fengchao

**Comment by DRock420** [comment]
HI Fengchao

I only know one way to download it through Fragpipe, however the Uniprot Proteome site for that species is blank (contains no protein entries) which just gives me a java error when I try to download the fasta file.

https://www.uniprot.org/proteomes/UP000791440

Do you have any suggestions for a work around?

Thanks

Derek

**Comment by fcyu** [comment]
Hi Derek,

You can download the fasta file from https://www.uniprot.org/uniprotkb?facets=reviewed%3Atrue&query=%28taxonomy_id%3A7130%29, and then, adding decoys by clicking `add decoy` button in FragPipe.

At the meantime, can you send us your fasta file? You need to zip your file and upload it in GitHub. Replying the email would make GitHub truncate it.

Thanks,

Fengchao

**Comment by DRock420** [comment]
HI Fengchao

That's how we created the original database. I have attached the .fas file with decoys and contaminants

Thanks

Derek


[2022-09-09-decoys-contam-ManducaSexta_taxonomy_id7130_uniprot2022.09.07.fasta.zip](https://github.com/Nesvilab/FragPipe/files/9560420/2022-09-09-decoys-contam-ManducaSexta_taxonomy_id7130_uniprot2022.09.07.fasta.zip)

**Comment by fcyu** [comment]
Hi Derek,

Your fasta file has exactly the same issue as https://github.com/Nesvilab/FragPipe/issues/821#issuecomment-1245901552:

![image](https://user-images.githubusercontent.com/6926299/190001494-894079d3-ca51-4d31-a75d-dba2ba0d26b4.png)

Best,

Fengchao

**Comment by DRock420** [comment]
Thanks Fenchao, the search finishes with the new FASTA file. I don't know how it got corrupted.

The search still resulted in 0 psm and so I will try against a more general all species database to see if that improves anything

**Comment by fcyu** [comment]
Thanks for your feedback. 

Please feel free to contact us if you have any further questions.

Best,

Fengchao

**Comment by DRock420** [comment]
Sorry, yes we are working together to fix the problem

Derek
