### ISSUE TITLE
FP processing fails on phospho tims-TOF data

### ISSUE THREAD

**Issue by MKatWIS** [Nesvilab/FragPipe#828]
Hello,

Am running tims-TOF Pro phospho data (with IM) in FragPipe, using the LFQ-phospho workflow. I uploaded the mzml files to FP and keep getting the following error:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ionquant.IonQuant.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-09-15 11:48:16 [ERROR] - Index 0 out of bounds for length 0
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

Would love some help, log is attached.

Thnx,
Meital
[log_2022-09-15_11-48-16.txt](https://github.com/Nesvilab/FragPipe/files/9573823/log_2022-09-15_11-48-16.txt)

**Comment by fcyu** [comment]
How did you convert the .d to mzML format? I suggest you using .d directly if it is possible.

Best,

Fengchao

**Comment by MKatWIS** [comment]
Hi Fengchao,

I tried using the .d files, but the software put on a msg saying that PTMProphet (which needs to be used for PTM localization) can only use .mzml files.
We use MSConvert to generate the mzml files

Thnx

**Comment by fcyu** [comment]
I see. Did you follow the tutorial here: https://fragpipe.nesvilab.org/docs/tutorial_convert.html 

If yes, can you send me one of your mzML files?

Thanks,

Fengchao
