### ISSUE TITLE
Fragpipe v18 vs previous version specific setting

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/FragPipe#829]
Good day

I am trying to follow this protocol explained in the paper attached, but can't seem to find the setting: “Multi-experiment report” and “Generate peptide level summary”. How could one change these settings in the 18th version of fragpipe?

Protocol paper:
[Qualitative and Quantitative Shotgun Proteomics Data Analysis.pdf](https://github.com/Nesvilab/FragPipe/files/9574349/Qualitative.and.Quantitative.Shotgun.Proteomics.Data.Analysis.pdf)

Specific section:
![image](https://user-images.githubusercontent.com/109790066/190381818-7eb78808-a27b-469f-94b8-1b25ebb5a3bc.png)

It would be great to hear back on this matter.
--Melissa

**Comment by fcyu** [comment]
Hi Melissa,

That paper was using FragPipe version 12.1. We have version 18.0 now, which has been changed a lot. 

If you need some tutorial and documents, here it is: https://github.com/Nesvilab/FragPipe

Best,

Fengchao
