### ISSUE TITLE
FragPipe with directory path with Chinese characters 

### ISSUE THREAD

**Issue by anesvi** [Nesvilab/FragPipe#83]
I was teaching at a workshop in Taiwan, and a few people had an issue with some tools in FragPipe - the 'file not found' sort of issues.  In all cases, it was because the folder names contained Chinese characters.  Things looked OK on the same laptops after data was moved to a folder in English.

I am not sure it is something we can fix, or should just be warning people that there may be an issue and they should just stick to English.

Thanks
Alexey

**Comment by chhh** [comment]
Unicode characters in paths are never a good idea. I'd also advise against spaces in paths. FragPipe itself should be ok with both, but even then I wouldn't use them.
There's no way to fix this. We can show a warning if there are spaces or non ascii symbols in any paths.

**Comment by chhh** [comment]
Warnings are now issued in 9.0
