### ISSUE TITLE
Difference in unique peptide numbers between PSM.tsv and peptide.tsv output files

### ISSUE THREAD

**Issue by ryanpe13002** [Nesvilab/FragPipe#830]
To whom it may concern,

I recently ran the FragPipe pipeline without MSBooster, and am trying to understand some of the output files.

My understanding is the PSM file reflects individual instances of peptides with a given modification matching a spectrum, filtered to 1% FDR. I also understand that the peptide.tsv file should be these identified peptides stripped of any modifications.

However, when I count the number of unique peptides in the psm.tsv file (using the column “Peptide”, which comes stripped of any mods), I get 2359 unique peptide sequences. When I do this same count using the peptide.tsv file, I get 2234 unique peptides. What accounts for the discrepancy between these two numbers? Based on what I understand about them, and what is on the FragPipe output tutorial guide, these numbers should be the same. Where does the additional filtering come in?

Thank you so much for any help or guidance you can provide, I deeply appreciate it!

Kindest regards,
Ryan Englander

**Comment by fcyu** [comment]
If I remember correctly, the peptides in peptide.tsv are filtered with 1% peptide and protein FDR, while the PSMs in psm.tsv are filtered with 1% PSM and protein FDR. Need Felipe @prvst  or Alexey @anesvi to confirm that.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, the peptide file is filtered differently; some PSM pass PSM -level FDR but their peptides do not pass the peptide-level FDR

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanpe13002** [comment]
Thank you so much everyone! I am using FragPipe for immunopeptidomics applications, and so the relevant information for downstream applications is the actual peptides that I am identifying; from that perspective, it seems like it makes more sense to go with the peptide file, as it is somewhat more stringent than the PSM file. Does this interpretation make sense?

**Comment by prvst** [comment]
I don't believe the peptide filtering is more stringent than the PSM filtering. You see less observations post-filter because we collapse the PSMs into the peptide sequences. For your application, probably both types of data would point you into the right direction, the PSM list is just more granular than thee peptide list.

**Comment by ryanpe13002** [comment]
When I collapse the number of unique peptide sequences in the PSM file and compare them to the unique sequences in the peptide file, there are ~100 more peptides in the PSM file that are not in the peptide file (2359 PSM vs. 2234 peptide for this dataset). So there must be some additional filtering going on, right? They're not exactly equivalent.

**Comment by prvst** [comment]
That's correct. Internally, the program creates a *peptide*, and an *ion* representation from the original PSM list. Each list is then individually filtered using the respective. FDR filters.

**Comment by ryanpe13002** [comment]
Ah, that makes sense! So the peptide.tsv file is saying that these are the peptides, stripped of mods, that are filtered to a level where ~1% of them are false identifications, while the PSM.tsv file is saying that these are the peptide/spectral matches that are filtered to a level where ~1% are false. And so it's not necessarily less strict, but _peptide.tsv is necessarily a subset of PSM.tsv_. Is that last conclusion correct? If so, I will feel comfortable using the peptide.tsv file going forward!

**Comment by anesvi** [comment]
Yes correct

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prvst** [comment]
Yes. that's right.

**Comment by anesvi** [comment]
Yes, please use peptide.tsv for immunopeptidomics

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
