### ISSUE TITLE
ERRO[19:13:18] Cannot decode packed binary. XML syntax error on line 2076829: unexpected EOF 

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/FragPipe#833]
Hello,

While trying to run LFQ-phospho the following error was encountered: 
ERRO[19:13:18] Cannot decode packed binary. XML syntax error on line 2076829: unexpected EOF 

I may have seen a similar error addressed here in the list of questions and it mentioned about deleting .tmp files. I searched for tmp files, only found a few (see screenshot), deleted the tmp files and tried again, but the same error occurred

It is a fairly large data set, when I tried to run it on a subset of just 16 of the samples, it seemed to run fine

Thank you as always for all of your assistance! 

All the best,

Jason 
[log_2022-09-08_21-34-31.txt](https://github.com/Nesvilab/FragPipe/files/9584694/log_2022-09-08_21-34-31.txt)
![tmp files](https://user-images.githubusercontent.com/72038445/190657539-8576e5a5-ee7d-4477-8e99-c64a8d203d65.png)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by jmcalist** [comment]
Hello,

If I can provide any additional information related to this topic please let me know

Thanks so much!

All the best,

Jason

**Comment by anesvi** [comment]
Please contact me directly by email. We may ask you to test some things for us, but easier to do directly
Alexey

**Comment by jmcalist** [comment]
Hi Alexey,

Thank you so much for continuing to follow up on this, we really appreciate it!

Based on your information regarding conversion of .tmp files to .mod, I noted the following in log files. In the example below, it appears that writing of the mod file for sample 9 files (highlighted in yellow below), but this error is not seen for the next sample 58. I searched two log files for mod.pep.xml" failed: Operation not permitted, and in one run this error occurred for all samples except 5 (n=63 total files), and for the other run the error occurred for all samples except 2. In both runs the error did not occur on sample 49. I am not sure if this is helpful, but just something I noticed. I would be happy to help try troubleshooting on my side, feel free to have a member of your team contact me. ​​


PtmProphet [Work dir: C:\Users\Administrator\Desktop\Danve_phopho_all\S22034-Nick-9]
C:\Users\Administrator\Downloads\FragPipe-jre-18.0\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe ptmprophet --keepold --static --em 1 --nions b --mods STY:79.966331,M:15.9949 --minprob 0.5 --maxthreads 7 interact-S22034-Nick-9.pep.xml
INFO[05:40:05] Executing PTMProphet  v4.4.0
INFO: Writing file interact-S22034-Nick-9.pep.xml.tmp.a00892 ...

Creating 7 threads
Wait for threads to finish ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Using statically set 15 PPM tolerance ...
​
INFO: processed 91000/91302 spectrum_queries          
INFO: done ...
INFO: Computing EM Models ...
Iterating PTM Model: ....5..done
INFO: done ...
INFO: done ...

Creating 7 threads
Wait for threads to finish ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
INFO: Reading file interact-S22034-Nick-9.pep.xml ...
​
INFO: written 91000/91302 spectrum_queries            
INFO: done ...
INFO: Writing file interact-S22034-Nick-9.mod.pep.xml ...
'chmod' is not recognized as an internal or external command,
operable program or batch file.
INFO: done ...

command "chmod 664 interact-S22034-Nick-9.mod.pep.xml" failed: Operation not permitted
INFO[05:41:37] Done
Process 'PtmProphet' finished, exit code: 0
PtmProphet [Work dir: C:\Users\Administrator\Desktop\Danve_phopho_all\S22034-Nick-58]
C:\Users\Administrator\Downloads\FragPipe-jre-18.0\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe ptmprophet --keepold --static --em 1 --nions b --mods STY:79.966331,M:15.9949 --minprob 0.5 --maxthreads 7 interact-S22034-Nick-58.pep.xml
INFO[05:41:37] Executing PTMProphet  v4.4.0
INFO: Writing file interact-S22034-Nick-58.pep.xml.tmp.a06372 ...

Creating 7 threads
Wait for threads to finish ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Using statically set 15 PPM tolerance ...
​
INFO: processed 88000/89609 spectrum_queries          
INFO: done ...
INFO: Computing EM Models ...
Iterating PTM Model: ....5..done
INFO: done ...
INFO: done ...

Creating 7 threads
Wait for threads to finish ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
INFO: Reading file interact-S22034-Nick-58.pep.xml ...
​
INFO: written 37000/89609 spectrum_queries             INFO[05:42:48] Done
Process 'PtmProphet' finished, exit code: 0
________________________________

**Comment by anesvi** [comment]
Dear Jason,

We were able to fix the problem in PTMProphet! Or so we hope.
Felipe, could you please send Jason a pre-release of philosopher (.exe) so he can test.

Thanks
Alexey


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prvst** [comment]
I'll get the link soon, I need to wrap it up some other changes first

**Comment by jmcalist** [comment]
Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prvst** [comment]
@jmcalist , please take the latest RC version from this [link](https://www.dropbox.com/scl/fo/rdk9igzzzzkybz7ro4edg/h?dl=0&rlkey=gzdy0y5zaiudjqdjbwqmkvo0c)

**Comment by prvst** [comment]
try this one https://www.dropbox.com/sh/0mr4zbprhaxk453/AADdLawYWnQ_-tekDkdnLscWa?dl=0

**Comment by jmcalist** [comment]
Perfect, I have RC19 running, thank you for all your support, I will let you know how it goes
________________________________

**Comment by jmcalist** [comment]
Hi Felipe,

Thank you again for the file, I have been running it and it seems to be taking longer than many of the other Fragpipe runs I have done, but I do know it is a lot of samples. Just wanted to send this log file while it is in process so you could have a look if it is helpful for you

Thanks again!

All the best,

Jason
________________________________

**Comment by anesvi** [comment]
Felipe can you do a few tests, to see how much slower it on our servers? We may have to ask David to see if he can speed it up

**Comment by anesvi** [comment]
Jason
What step is taking longer? Only PTM-Prophet should be affected. Can you tell how much longer PTM-Prophet is taking per file compared to before?
Alexey

**Comment by anesvi** [comment]
The log is truncated by the way, please send us by email directly

**Comment by prvst** [comment]
You can attach the file to the post here , instead of copying its content. Do you have an idea on how much longer? and in which step?

**Comment by jmcalist** [comment]
Thank you as always for your amazingly quick replies!

It looks like Match Between Runs has been going for over 12 hours (since the timestamp of 2022-10-13 03:41:03), but it is going through each sample, and there are a lot of samples (n=63). It is nearing the last sample for MBR, currently on 58, so things may pick up after that

Thank you again!

All the best,

Jason


________________________________

**Comment by fcyu** [comment]
Hi Jason,

Which analysis are you comparing against regarding the run time? Can you send us both logs files from your fast and slow jobs?

FYI, you need to zip and upload the files in GitHub. Attach the file when replying the email does not help. GitHub will truncate your email.

Best,

Fengchao

**Comment by anesvi** [comment]
I though you were testing PTM-Prophet crash. Is that ok now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmcalist** [comment]
Hi Fengchao,

Thanks so much, I will try to reply through github in the future, I had just sent the logfile to Felipe and Alexey via their umich accounts. I was only comparing to different runs in Fragpipe which are always very fast, I do not have two logfiles for this same job


[log_2022-10-13_16-37-27.txt](https://github.com/Nesvilab/FragPipe/files/9778920/log_2022-10-13_16-37-27.txt)

**Comment by jmcalist** [comment]
I loaded the Prophet file from Felipe in the config page and ran the run as I had been before with the previous Prophet file. My apologies if I should have done it another way

**Comment by anesvi** [comment]
It looks to me that the MBR step took most of the time. I suppose we can reduce the default value for the number of runs used as donor runs. Fengchao what do you think?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fcyu** [comment]
Yes, we should reduce the top runs. Current default value is too high.

Best,

Fengchao

**Comment by fcyu** [comment]
We released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
