### ISSUE TITLE
Combined protein ID list 

### ISSUE THREAD

**Issue by MelissaVorster** [Nesvilab/FragPipe#834]
Good day

I am trying to understand the output that I got when I ran Fragpipe with MSFragger. What is the method used to create the combined_protein.tsv file? What are the criteria for a protein to be part of this list?

This is a photo of the output files that I got:
![image](https://user-images.githubusercontent.com/109790066/191204838-3c9b4f39-abee-4b30-9520-79a3a2b2d0ae.png)

It would be great to hear back from you.

Regards
Melissa

**Comment by fcyu** [comment]
Hi Melissa,

Please find the tutorial about the output files from https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html

Best,

Fengchao
