### ISSUE TITLE
Re-Running Fragpipe

### ISSUE THREAD

**Issue by Maithy15** [Nesvilab/FragPipe#835]
Hi,

I ran a fragpipe search and made a mistake in naming the files in the experiment name column. Would it be possible to use the pepxml files created by fragpipe to start a new search? Would it reduce the search time? If I am right the pepxml files are already calibrated, and this should reduce the time, right?

Thanks
Maithy

**Comment by fcyu** [comment]
Hi Maithy,

Yes, you can rename the experiment, rearrange the folders, copy the pepxml files to the correct folder, uncheck MSFragger, and re-run rest of the tools.

It would save some time.

pepxml files are search results from MSFragger.

Best,

Fengchao
