### ISSUE TITLE
Process 'PhilosopherFilter' finished, exit code: 2.

### ISSUE THREAD

**Issue by ergtw45t** [Nesvilab/FragPipe#839]
When I start with ten mzml files,FragPipe can finish work.But when I start with total files(about fourty),it raise an error as follows.
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping
ERRO[18:06:16] Cannot decode packed binary. XML syntax error on line 6954277: unexpected EOF 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-09-22_19-15-21.txt](https://github.com/Nesvilab/FragPipe/files/9625840/log_2022-09-22_19-15-21.txt)

**Comment by fcyu** [comment]
Can you upload the log file?

Thanks,

Fengchao
