### ISSUE TITLE
Getting error while running XRNAX-massoffset

### ISSUE THREAD

**Issue by Arslan-Siraj** [Nesvilab/FragPipe#842]
Dear Awesome team,

I am getting this error, 
"D:\Data_202209\RNA_UV_Rep1_ECOLI\MF_Perc_RNA_UV_Rep1_ECOLI_S30\shepherd.config"
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -5000 out of bounds for length 0
	at edu.umich.andykong.ptmshepherd.peakpicker.Histogram.mergeHistogram(Histogram.java:79)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:487)
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2022-09-29_02-30-16.txt](https://github.com/Nesvilab/FragPipe/files/9669745/log_2022-09-29_02-30-16.txt)

I added the log file as well, I will like to get any suggestions.

Thanks,

**Comment by fcyu** [comment]
`mass_offsets = 612.051/611.067/630.061/629.077/636.062/652.057/635.078/651.073/653.088/669.083/306.025/324.036`

I think you should put `0` in your mass list.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
You have zero PSMs. Please check your parameters and protein database.
