### ISSUE TITLE
DBAnnotate index out of range error

### ISSUE THREAD

**Issue by ManojK000** [Nesvilab/FragPipe#847]
- Describe the issue or question:
Hi. I am new to fragpipe and trying to do an opensearch. The program exits at the DBAnnotate stage. Please see the attached long file. Hopefully, you will be able to help. Thanks. Manoj

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-10-03_15-31-00.txt](https://github.com/Nesvilab/FragPipe/files/9698481/log_2022-10-03_15-31-00.txt)

**Comment by fcyu** [comment]
```
D:\MUD\Software\ProteinAnalysis\FragPipe\fragpipe18\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe database --annotate D:\MUD\Software\ProteinAnalysis\FragPipe\Databases\2022-10-03-decoys-A_thaliana_201606-Araport11_v3.fasta.fas --prefix rev_
INFO[15:30:59] Executing Database  v4.4.0                   
INFO[15:30:59] Annotating the database                      
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
philosopher/lib/dat.ProcessTair({0xc003823cb1, 0x88}, {0xc0037dfef0, 0xa3}, {0xc000018110, 0x4})
	/workspace/philosopher/lib/dat/db.go:472 +0x39c
philosopher/lib/dat.(*Base).ProcessDB(0xc00020c000, {0xc000026150, 0x6d}, {0xc000018110, 0x4})
	/workspace/philosopher/lib/dat/dat.go:159 +0x82d
philosopher/lib/dat.Run({{0xc00001d2f0, 0x24}, {0xc00001e3a0, 0x20}, {0xc000020960, 0x49}, {0xc00001d320, 0x2f}, {0xc00001d350, 0x26}, ...})
	/workspace/philosopher/lib/dat/dat.go:66 +0x493
philosopher/cmd.glob..func4(0x2a93da0?, {0x14f0ca0?, 0x4?, 0x4?})
	/workspace/philosopher/cmd/database.go:23 +0x7e
github.com/spf13/cobra.(*Command).execute(0x2a93da0, {0xc0002b6040, 0x4, 0x4})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2a92b40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping
```

I never saw this error before. Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by prvst** [comment]
Please share the database file

**Comment by ManojK000** [comment]
There must be something odd about the file because i was able to resolve the issue by using a slightly different database file.
Here is the link to the problematic database:
https://www.dropbox.com/s/zg16f558dui2hqj/2022-10-03-decoys-A_thaliana_201606-Araport11_v3.fasta.fas?dl=0

Thanks for prompt help. Best wishes. Manoj

**Comment by prvst** [comment]
Well, good that you got it resolved. I would avoid setting up names like this:

`>AT4G11543.1 ; `

Avoid special characters like hashes or semicolons surrounded by space. These might make your report columns look weird, too. If you want to be sure if the file is OK, please check the [Wiki](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database).

**Comment by andrewyy677** [comment]
> Well, good that you got it resolved. I would avoid setting up names like this:
> 
> `>AT4G11543.1 ; `
> 
> Avoid special characters like hashes or semicolons surrounded by space. These might make your report columns look weird, too. If you want to be sure if the file is OK, please check the [Wiki](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database).

Hi, Felipe

I've got the error message of "panic: runtime error: index out of range [1] with length 0" at the DBAnnotate stage when running FragPipe using "LFQ-MBR.workflow". The error can be fixed by converting the fasta DB like ">xx" to ">xx|xx|xx" in windows, but cannot be fixed in linux in the same way. I do not know how this happened and how to solve the problem in linux run. Attached the original DB, converted DB, log in windows and log in linux. Thanks for your time!

best, 
Yingying

[FP_problem.zip](https://github.com/Nesvilab/FragPipe/files/9791150/FP_problem.zip)
