### ISSUE TITLE
PhilosopherFilter: No Ions, peptides or protein passing FDR

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/FragPipe#849]
Dear Fragpipe team, 

I wonder if I should post this in fragpipe or in philosopher, sorry if I chose the wrong place for this question.

Basically, I ran fragpipe in DIA non-specific HLA mode and I have an issue with philosopher filter (I think), leading to 0 ions, psms and peptides identification when fragpipe runs philosopher report.

What is surprising is that using the same raw files, but with a slightly different fasta file (the headers format is the same, but there are a few differences in the entries), does not lead to this issue. In addition, the number of target and decoy reported by philosopher filter is very similar between the 2 runs, but the FDR converges directly to 0 for the problematic run:

Run with **no** peptides reported (PhilosopherFilter log):
```
time="09:11:58" level=info msg="1+ Charge profile" decoy=47 target=715
time="09:11:58" level=info msg="2+ Charge profile" decoy=262 target=7452
time="09:11:58" level=info msg="3+ Charge profile" decoy=25 target=730
time="09:11:58" level=info msg="4+ Charge profile" decoy=0 target=0
time="09:11:58" level=info msg="5+ Charge profile" decoy=0 target=0
time="09:11:58" level=info msg="6+ Charge profile" decoy=0 target=0
time="09:11:58" level=info msg="Database search results" ions=4024 peptides=3832 psms=9231
time="09:11:58" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="09:11:58" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="09:11:58" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="09:11:59" level=info msg="Protein inference results" decoy=239 target=3173
time="09:11:59" level=info msg="Converged to 9.67 % FDR with 2440 Proteins" decoy=236 threshold=0.6997 total=2676
time="09:11:59" level=info msg="Applying sequential FDR estimation" ions=0 peptides=0 psms=0
time="09:11:59" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="09:11:59" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="09:11:59" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="09:12:00" level=info msg="Post processing identifications"
time="09:12:02" level=info msg="Assigning protein identifications to layers"
time="09:12:04" level=info msg="Processing protein inference"
time="09:13:12" level=info msg="Synchronizing PSMs and proteins"
time="09:13:13" level=info msg="Total report numbers after FDR filtering, and post-processing" ions=0 peptides=0 proteins=0 psms=0
time="09:13:13" level=info msg=Saving
time="09:13:13" level=info msg=Done
```

Run with peptides reported (PhilosopherFilter log):
```
time="16:05:20" level=info msg="1+ Charge profile" decoy=47 target=633
time="16:05:20" level=info msg="2+ Charge profile" decoy=296 target=7320
time="16:05:20" level=info msg="3+ Charge profile" decoy=26 target=717
time="16:05:20" level=info msg="4+ Charge profile" decoy=0 target=1
time="16:05:20" level=info msg="5+ Charge profile" decoy=0 target=0
time="16:05:20" level=info msg="6+ Charge profile" decoy=0 target=0
time="16:05:20" level=info msg="Database search results" ions=4030 peptides=3843 psms=9040
time="16:05:20" level=info msg="Converged to 1.00 % FDR with 5170 PSMs" decoy=51 threshold=0.932126 total=5221
time="16:05:20" level=info msg="Converged to 0.99 % FDR with 434 Peptides" decoy=3 threshold=0.984137 total=437
time="16:05:20" level=info msg="Converged to 1.00 % FDR with 295 Ions" decoy=2 threshold=0.984137 total=297
time="16:05:21" level=info msg="Protein inference results" decoy=272 target=3166
time="16:05:21" level=info msg="Converged to 11.03 % FDR with 2429 Proteins" decoy=268 threshold=0.6993 total=2697
time="16:05:21" level=info msg="Applying sequential FDR estimation" ions=2860 peptides=2765 psms=5221
time="16:05:22" level=info msg="Converged to 0.98 % FDR with 5170 PSMs" decoy=51 threshold=0.932126 total=5221
time="16:05:22" level=info msg="Converged to 1.00 % FDR with 2474 Peptides" decoy=24 threshold=0.959724 total=2498
time="16:05:22" level=info msg="Converged to 1.00 % FDR with 2587 Ions" decoy=25 threshold=0.957697 total=2612
time="16:05:22" level=info msg="Post processing identifications"
time="16:05:26" level=info msg="Assigning protein identifications to layers"
time="16:05:30" level=info msg="Processing protein inference"
time="16:06:13" level=info msg="Synchronizing PSMs and proteins"
time="16:06:13" level=info msg="Total report numbers after FDR filtering, and post-processing" ions=2587 peptides=2474 proteins=1920 psms=5170
time="16:06:13" level=info msg=Saving
time="16:06:13" level=info msg=Done
```

Since the only difference between the two runs is the fasta, I guess it might be related. 
Do you have any idea about what could cause this problem in PhilosopherFilter? 

Thank you very much by advance for your help.

With best regards,

Florian

Fragpipe logs are attached (for information, I run fragpipe in a container, hence the warnings at the beginning of the logs):
[Fragpipe_Fail.log](https://github.com/Nesvilab/FragPipe/files/9724265/Fragpipe_Fail.log)
[Fragpipe_Success.log](https://github.com/Nesvilab/FragPipe/files/9724266/Fragpipe_Success.log)

**Comment by fcyu** [comment]
Hi Florian,

Thanks for your report. I think it triggered some bug in Philosopher because everything looks good except for the filtering step.

BTW, I do remember that there are some unfixed bugs in the Philosopher filtering step, like https://github.com/Nesvilab/FragPipe/issues/545#issuecomment-997002678. Not sure if it is related.

Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by f-huber** [comment]
Hi @prvst,
I guess you refer to the fasta file right?
Basically, we create personalized proteomes from different sequencing data. 
For this particular case, we had 4 sequencing datasets (same original sample, different conditions) and therefore created 4 different fasta. It ran ok on 3/4 of them. 
I didn’t check what entries are different between them, but I expect that there is a very large overlap between the entries of all 4 fasta. 
Let me know if you need additional information, I’ll be happy to help you.

**Comment by f-huber** [comment]
Hi @prvst,
Thanks a lot for your answer. 
You’re correct, I indeed tried to mimic uniprot but adding some information. Originally, I tried using a generic format, but it was not working well either. 
We used this format for a while and it never crashed. 
I’ll try using only uniprot-like format and remove all “glued” attributes. 
I’ll come back to you in the coming days to let you know if this solved the issue. 
thanks again and best,
Florian

**Comment by f-huber** [comment]
Hi @prvst ,
So I tested without the glued attributes in the fasta, but I got the exact same error as with the other fasta.
Here is an example of the header format I tested:
`>db|1-REF|OR4F5-REF OR4F5 OS=human GN=ENSG00000186092.7 PE=1 SV=1
`
Could this header lead to philosopher errors?
Thanks, 
Florian

**Comment by tobiasko** [comment]
We had many issues with fasta headers that start with `>db` when `db` is not `sp` or `tr`! We meanwhile use a pseudo uniprot header even if the entries are not from swissprot or trembl to prevent this:

`>sp|Acc|Name someText`

See https://www.uniprot.org/help/fasta-headers

Hope this helps!

**Comment by prvst** [comment]
@f-huber Then you still have some FASTA entries with incompatible formats. The glued attributes was an example from the couple of sequences I can see in the log. Try @tobiasko suggestion.

**Comment by f-huber** [comment]
Thank you a lot @prvst and @tobiasko for the explanation about `>db`. I changed it to `>sp ` and it worked!
I just would like to mention that I also accidentally first reran it with `>db` and it worked - not sure why. 
Anyway, I’ll only use `>sp` header fully formatted as uniprot to avoid issues in the future. 
Best regards,
Florian
