### ISSUE TITLE
Philosopher error during PhilosopherFilter

### ISSUE THREAD

**Issue by PatriciaSosa** [Nesvilab/FragPipe#850]
I'm trying to run a phospho-LFQ workflow, and I'm having the following error: 
- panic: Cannot decode packed binary. XML syntax error on line 104220: unexpected EOF; and
- ERRO[23:25:48] Cannot decode packed binary. XML syntax error on line 104220: unexpected EOF.

I'm running with FP 18.0 and the last versions of MSFragger and Philosopher. My computer possess 32 GB of RAM, Processor Intel Xeon CPU E5-2697 v2 @ 2.70 GHz, 64-bit, and Windows server 2012. In my run, I'm splitting the DB in 20 using the peptideprophet. 

The log is attached.
[log_2022-10-05_23-25-48.txt](https://github.com/Nesvilab/FragPipe/files/9725593/log_2022-10-05_23-25-48.txt)

Thanks in advance.
Best,
Patricia Sosa.
[log_2022-10-05_23-25-48.txt](https://github.com/Nesvilab/FragPipe/files/9725585/log_2022-10-05_23-25-48.txt)

**Comment by fcyu** [comment]
Hi Patricia,

This is a known bug. We believe we have figured the way to solve it. Stay tuned.

Best,

Fengchao

**Comment by PatriciaSosa** [comment]
Hi Fengchao!
I don't know if this information is useful for you, but... I tried the same workflow, but I remove the phosphorylation modification from MSFragger and put N (2.988231) for deamidation with H2O18 and run again. Analysis was done without troubles. Then I change in PTMProphet STR to N for site localization and also the run was successful. 

I have one doubt related to output tables. I'm wondering if the "Filename_Localization" column in the "combined_modified_peptide.tsv" file has the site probability information? And also which output table (i.e., peptide information) do you prefer to do statistics analysis?
Thanks.
Best,
Patricia.

**Comment by PatriciaSosa** [comment]
> Hi Patricia,
> 
> This is a known bug. We believe we have figured out the way to solve it. Stay tuned.
> 
> Best,
> 
> Fengchao

>
Hi Fengchao!
I don't know if this information is useful for you, but... I tried the same workflow, but I remove the phosphorylation modification from MSFragger and put N (2.988231) for deamidation with H2O18 and run again. Analysis was done without troubles. Then I change in PTMProphet STR to N for site localization and also the run was successful.

I have one doubt related to output tables. I'm wondering if the "Filename_Localization" column in the "combined_modified_peptide.tsv" file has the site probability information? And also which output table (i.e., peptide information) do you prefer to do statistics analysis?
Thanks.
Best,
Patricia.

**Comment by fcyu** [comment]
We released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
