### ISSUE TITLE
philosopher labelquant Cannot read file

### ISSUE THREAD

**Issue by JasonYJWei** [Nesvilab/FragPipe#851]
Hi,

I'm trying to label the TMT channels to the mzML files with the command labelquant, and get the following errors for v3.3.12 and v4.4.0

~/Programs/philosopher_v3.3.12/philosopher labelquant --brand tmt --plex 11 --annot S054_HNSCC_Discovery_Proteome/20CPTAC_HNSCC_Proteome_JHU_20190809/annotation.txt --dir rawdata/CPTAC/S054_HNSCC_Discovery/Proteome/20CPTAC_HNSCC_Proteome_JHU_20190809/mzML/
INFO[21:22:23] Executing Isobaric-label quantification  v3.3.12
FATA[21:22:23] Cannot read file:open .meta/ev.param.bin: no such file or directory

~/Programs/philosopher_v4.4.0/philosopher labelquant --brand tmt --plex 11 --annot S054_HNSCC_Discovery_Proteome/20CPTAC_HNSCC_Proteome_JHU_20190809/annotation.txt --dir rawdata/CPTAC/S054_HNSCC_Discovery/Proteome/20CPTAC_HNSCC_Proteome_JHU_20190809/mzML/
INFO[21:33:56] Executing Isobaric-label quantification  v4.4.0
ERRO[21:33:56] Cannot read file. open .meta/psm.bin: no such file or directory
panic: Cannot read file. open .meta/psm.bin: no such file or directory

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc000034880, 0x3f}, {0xb29f26, 0x1?})
        /workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ReadFile({0xc75480?, 0xc0000ff800?}, {0xb29f26, 0x5})
        /workspace/philosopher/lib/msg/msg.go:75 +0x6e
philosopher/lib/sys.Restore({0xa994e0, 0xc00013e4d8}, {0xc000031500, 0xd}, 0x0)
        /workspace/philosopher/lib/sys/sys.go:263 +0x2cb
philosopher/lib/rep.RestorePSM(0x1?)
        /workspace/philosopher/lib/rep/io.go:70 +0x93
philosopher/lib/rep.(*Evidence).RestoreGranular(0xc00013e000)
        /workspace/philosopher/lib/rep/io.go:56 +0x2a
philosopher/lib/qua.RunIsobaricLabelQuantification({{0x0, 0x0}, {0x0, 0x0}, {0xb299d8, 0x4}, {0x7fffffffccad, 0x92}, {0x7fffffffcbec, 0x3}, ...}, ...)
        /workspace/philosopher/lib/qua/qua.go:66 +0x16c
philosopher/cmd.glob..func9(0x1cd9900?, {0xb29938?, 0x8?, 0x8?})
        /workspace/philosopher/cmd/labelquant.go:50 +0x2dd
github.com/spf13/cobra.(*Command).execute(0x1cd9900, {0xc0000c4580, 0x8, 0x8})
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1cd7c20)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x25
main.main()
        /workspace/philosopher/main.go:25 +0x90

I have initialed the workspace with "~/Programs/philosopher_v4.4.0/philosopher workspace --init", but really didn't see files ".meta/psm.bin" and ".meta/ev.param.bin"

Could you please help me out? Thank you very much.

Best,
Jason

**Comment by prvst** [comment]
Did you ran the filter?

**Comment by JasonYJWei** [comment]
> Did you run the filter?

No. I didn't run philosopher step-by-step. Actually, I have a custom PSM from other pipeline, which need to perform the quantification. So, I'm trying to run the command labelquant firstly. But not quite sure how to process correctly.

**Comment by prvst** [comment]
@JasonYJWei Philosopher commands need to be used in the correct order, and you need to generate the reports from within the program analysis. Outside reports won't work because they are generated in different ways, and might have different information inside. I suggest you take a look at the Philosopher [Wiki](https://github.com/Nesvilab/philosopher/wiki), and check for the tutorials..

**Comment by JasonYJWei** [comment]
OK. I see. Thank you so much. @prvst @fcyu
