### ISSUE TITLE
Percolator issue for ddaPASEF data (large database with splitting)

### ISSUE THREAD

**Issue by JoergDoellinger** [Nesvilab/FragPipe#852]
Dear FragPipe Team,

I am searching a ddaPASEF file against a large database (6.4M enries) using FragPipe (v18.0). The analysis is working fine using PeptideProphet but crashes when I use Percolator.
(Reading tab-delimited input from datafile Ecoli_100SPD_ddaPASEF_PaSER_S1-A1_100SPD_diaPASEF_10-7-2022_174.pin
ERROR: Cannot open data stream.
ERROR: Failed to read in file, check if the correct file-format was used.
Process 'Percolator' finished, exit code: 1).
Is percolator supporting database splitting for timsTOF data at the moment?
I have used this worklfow in the past with Orbitrap data without issues.

Best regards

Joerg

**Comment by fcyu** [comment]
Can you send us the log file?

Thanks,

Fengchao

**Comment by JoergDoellinger** [comment]
Hi Fengchao,

the file is missing. I have repeated the analysis and now it is working (slightly more IDs than PeptideProphet, just as expected). I tried this analysis 3 times before I wrote you. I don't know the reason?

Thank you very much

Best,

Joerg
