### ISSUE TITLE
Adding fraction column to "Input LC-MS Files" table and usage for MBR in Ionquant?

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/FragPipe#853]
Dear FragPipe / Ionquant team(s),

would it be possible to add a column with fraction number to the input table and use this information in Ionquant similar to the way MBR for fractions works in MaxQuant (matching fraction N only for fraction N and N+/-1 )? 
When working with fractionated samples I always found it quite reasonable to limit the MBR function to identical and/or neighboring fractions but to avoid matching between fractions where no overlap is expected from the experimental setup.
An other advantage would be that in large experiments the matching step would be less time consuming when the user can pre-select samples for this.

Best regards,
Juergen

**Comment by fcyu** [comment]
Thanks for your suggestion. But if you want to restrict the MBR in similar runs, you can adjust the "MBR min correlation" and "MBR top runs" parameters. To me, those two are more reasonable than the ad-hoc "matching N and N+- 1 fractions" rule. With those two parameters, the fractions used in MBR will be adjusted adaptively.

Best,

Fengchao
