### ISSUE TITLE
DIA and PTMProphet

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#855]
Hi FP team,

A quick question...is PTMProphet compatible with DIA workflows? Specifically, MSFragger-DIA using mzml files (converted from ThermoRAW).  I used the DIA_SpecLib_Quant workflow and enabled PTMProphet with specification of modifications to report. The analysis completed successfully with no errors, and mod.pep.xml were generated from PTMProphet, but PTM site specific reports were not output. Apologies if this is in your documentation and I missed it.

Todd

**Comment by fcyu** [comment]
I don't think so. The localization probability is not optimal since the MS2 spectrum is multiplexed. And the localization probability is also not propagated to the spectral library.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, but that option in DIA-NN is conservative. It will basically remove peptides where the reported configuration (as a whole) is not confident.  So even if there is one site (if doubly phosphorylated) can be confidently localized, it may be removed.
And if not localized, again it may be removed (instead of reporting along with low localization probability)

**Comment by enonimos** [comment]
Thanks for the qualifiers. Do you happen to know if the filtering you mention is applied only when generating the specific quant matrices, e.g. precursors, protein group, gene group, etc?  If the base "diann-output.tsv" file is relatively "filter-free", then manual thresholding could be an option.

**Comment by anesvi** [comment]
I forgot. Should ask Vadim. I cc him here

**Comment by vdemichev** [comment]
@enonimos the PTM q-value filtering is autoamtically applied in DIA-NN when generating (i) all the matrices and (ii) a spectral library - hence also during MBR. Localisation confidence filtering is not applied automatically and needs to be applied by the user, based on the main report of DIA-NN (not the matrices).

**Comment by enonimos** [comment]
@vdemichev thanks, I see what you mean when looking in the main report at the PTM.Q.Value column, nearly all are < 0.01.  But, as a quick comment, I noticed a small percent of entries (~1%) were retained despite having PTM.Q.Value = 1 and Global.Q.Value = 1. Is there another score that would cause these to be included in the main report and not filtered.

**Comment by vdemichev** [comment]
Main report without MBR is not subject to any PTM filtering, so will indeed contain entries with PTM.Q.Value = 1 or Global.Q.Value = 1.

**Comment by enonimos** [comment]
Ok, thank you for the explanation, greatly appreciated.
