### ISSUE TITLE
Process `IonQuant` finished, exit code: 1 java.lang.NullPointerException: Something was wrong in update protein.tsv

### ISSUE THREAD

**Issue by ArchaeaXu** [Nesvilab/FragPipe#857]
Hi everyone!

I'm currently processing my timsTOF Pro data with FragPipe 17.1, (88 .d DDA files into 2 groups) :

Version info:
FragPipe version 17.1
MSFragger version 3.4
Philosopher version 4.4.0 (build 1657042643)

I loaded the "LFQ-MBR" workflow, with the RAM set as 0, Parallelism set as 40. In the ‘Database’ tab, contaminants and decoys were added to my FASTA file. In MSFragger tab, I set tie Missed cleavages1 as 3. Run MS1 quant checked. Other parameters was followed as default. I get the following error message:

2022-10-12 16:35:39 [INFO] - Loading K:\FragPipe_Results\LC_9\MS2101870047_4ul_Slot2-47_1_874.pepXML...
2022-10-12 16:35:48 [INFO] - Use each MS2 scan's calculated MZ in peak tracing.
2022-10-12 16:35:48 [INFO] - Quantifying...
2022-10-12 16:36:16 [INFO] - Updating Philosopher's tables...
java.lang.NullPointerException: Something was wrong in update protein.tsv
	at s.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-10-12 16:36:58 [ERROR] - Something was wrong in update protein.tsv
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

All the Intensitys in "combined_protein.tsv" and "protein.tsv" are 0.

Best,
Hongkai

- Upload your log file

[log_2022-10-12_16-37-18.txt](https://github.com/Nesvilab/FragPipe/files/9782756/log_2022-10-12_16-37-18.txt)

**Comment by fcyu** [comment]
That is because you are using the old versions of FragPipe and MSFragger. Could you upgrade them and try again?

Thanks,

Fengchao

**Comment by ArchaeaXu** [comment]
> That is because you are using the old versions of FragPipe and MSFragger. Could you upgrade them and try again?
> 
> Thanks,
> 
> Fengchao

Appreciate for your reply, I will ask the Admin to see if the new version can be installed, and test it as early as I can.

Best,
Hongkai

**Comment by ArchaeaXu** [comment]
Thank you very march for your super useful reply. All jobs done without error with following version:
FragPipe version 18.0
MSFragger version 3.5
Philosopher version 4.4.0

Best,
Hongkai
