### ISSUE TITLE
DB annotation Error message: panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by andrewyy677** [Nesvilab/FragPipe#859]
- Describe the issue or question:
Hi, FragPipe Team

I've got the error message of "panic: runtime error: index out of range [1] with length 0" at the DBAnnotate stage when running FragPipe using "LFQ-MBR.workflow". The error can be fixed by converting the fasta DB like ">xx" to ">xx|xx|xx" in windows, but cannot be fixed in linux in the same way. I do not know how this happened and how to solve the problem in linux run. Attached the original DB, converted DB, log in windows and log in linux. Thanks for your time!

best,
Yingying

- Upload your log file
(If a log file hasn't b
[FP_problem.zip](https://github.com/Nesvilab/FragPipe/files/9791163/FP_problem.zip)
een generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Yingying @andrewyy677 ,

Felipe @prvst didn't response anything. I think I can give some suggestions although I didn't develop Philosopher. 

Could you 
1. Change the protein headers from `>xx|xx|xx` to `>sp|xx|xx` according to another thread here (https://github.com/Nesvilab/FragPipe/issues/849#issuecomment-1271424089)?
2. After changing the format, can you also append decoys by clicking "add decoys" in the "database" tab of FragPipe/

Best,

Fengchao

**Comment by prvst** [comment]
Sorry, I must have missed the notification.

@andrewyy677 why do you need to do this ?   `>137_peg.1022|137_peg.1022|137_peg.1022`

**Comment by andrewyy677** [comment]
> Hi Yingying @andrewyy677 ,
> 
> Felipe @prvst didn't respond anything. I think I can give some suggestions although I didn't develop Philosopher.
> 
> Could you
> 
> 1. Change the protein headers from `>xx|xx|xx` to `>sp|xx|xx` according to another thread here ([PhilosopherFilter: No Ions, peptides or protein passing FDR #849 (comment)](https://github.com/Nesvilab/FragPipe/issues/849#issuecomment-1271424089))?
> 2. After changing the format, can you also append decoys by clicking "add decoys" in the "database" tab of FragPipe/
> 
> Best,
> 
> Fengchao

Hi Fengchao

Thanks! I've change the protein headers to >sp|xx|xx and run the headless mode in linux. But I got a new error: "2022-12-13 03:02:53,963 ERROR - Cannot get error message". I also add decoys in the database before run the fragpipe. My command line, output and log files were attached.
[output3.zip](https://github.com/Nesvilab/FragPipe/files/10213917/output3.zip)

**Comment by andrewyy677** [comment]
> Sorry, I must have missed the notification.
> 
> @andrewyy677 why do you need to do this ? `>137_peg.1022|137_peg.1022|137_peg.1022`
Hi, 
I  saw your annother reply saying the error may be cased by the problematic database (https://github.com/Nesvilab/FragPipe/issues/847). And I check the [Wiki](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database) titled "How to prepare a protein database", and change the database header into the right format.

**Comment by andrewyy677** [comment]
> Sorry, I must have missed the notification.
> 
> @andrewyy677 why do you need to do this ? `>137_peg.1022|137_peg.1022|137_peg.1022`

Hi,
Thanks! I saw your annother reply saying the error may be cased by the problematic database (https://github.com/Nesvilab/FragPipe/issues/847). And I check the [Wiki](https://github.com/Nesvilab/philosopher/wiki/How-to-Prepare-a-Protein-Database) titled "How to prepare a protein database", and change the database header into the right format. I've change the protein headers to >sp|xx|xx and run the headless mode in linux. But I got a new error: "2022-12-13 03:02:53,963 ERROR - Cannot get error message". I also add decoys in the database before run the fragpipe. My command line, output and log files were attached.
[output3.zip](https://github.com/Nesvilab/FragPipe/files/10213988/output3.zip)

**Comment by fcyu** [comment]
Hi @andrewyy677 .

Your log file is not complete. 

I see that you use several perl scripts to modify the workflow file and manifest file, which I can't verify if there is no problem. Can you first run FragPipe in GUI mode to make sure that it finished successfully, then, migrate to headless mode? 

Best,

Fengchao

**Comment by andrewyy677** [comment]
> Hi @andrewyy677 .
> 
> Your log file is not complete.
> 
> I see that you use several perl scripts to modify the workflow file and manifest file, which I can't verify if there is no problem. Can you first run FragPipe in GUI mode to make sure that it finishes successfully, then, migrate to headless mode?
> 
> Best,
> 
> Fengchao

Thanks! I'll give it a try!

Best,
Yingying
