### ISSUE TITLE
Freequant: corrupted pepXML file. iTraq4 experiment

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#865]
Hi, we're encountering an error while searching an iTraq4 dataset from CPTAC. Looks like one of the pepXML is corrupted judging on the file sizes. How should we work around the problem in order to complete the analysis?

Thanks!
Wen 

 Directory of G:\contrib\A_36_GC_early_onset_PDC000214\results_isoform\N5381T5760

10/17/2022  09:38 PM       129,792,842 FN01_N5381T5760_180min_10ug_C1_053015.pepXML
10/17/2022  09:38 PM       130,252,487 FN02_N5381T5760_180min_10ug_C2_053015.pepXML
10/17/2022  09:39 PM       130,096,557 FN03_N5381T5760_180min_10ug_C1_053015.pepXML
10/17/2022  09:39 PM       131,206,680 FN04_N5381T5760_180min_10ug_C2_053015.pepXML
10/17/2022  09:40 PM       133,732,627 FN05_N5381T5760_180min_10ug_C1_053015.pepXML
**10/17/2022  09:41 PM        89,938,341 FN06_N5381T5760_180min_10ug_C2_053015.pepXML**
10/17/2022  09:41 PM       136,035,527 FN07_N5381T5760_180min_10ug_C1_053015.pepXML

[log_2022-10-20_09-49-13.txt](https://github.com/Nesvilab/FragPipe/files/9830692/log_2022-10-20_09-49-13.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by prvst** [comment]
the pepXML is the output from MSFragger right? If the file is corrupted, why dont you run Fragger again?

**Comment by wyu** [comment]
[FN06_N5381T5760_180min_10ug_C2_053015.zip](https://github.com/Nesvilab/FragPipe/files/9833328/FN06_N5381T5760_180min_10ug_C2_053015.zip)

Hi, I took a closer look at the offending pepXML file attached. Looks like it has the proper ending tag. The file is quite a bit smaller than the other ones in the folder. Not sure if re-run the search would help.

...
</search_hit>
</search_result>
</spectrum_query>
</msms_run_summary>
</msms_pipeline_analysis>

Thanks!
Wen

Process 'FreeQuant' finished, exit code: 0
FreeQuant [Work dir: G:\contrib\A_36_GC_early_onset_PDC000214\results_isoform\N5381T5760]
E:\Tools\FragPipe\FragPipe-jpe-18\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe freequant --ptw 0.4 --tol 10 --dir G:\contrib\A_36_GC_early_onset_PDC000214\mzML\N5381T5760
INFO[04:29:36] Executing Label-free quantification  v4.4.0  
INFO[04:30:06] Indexing PSM information                     
INFO[04:30:11] Reading spectra and tracing peaks            
INFO[04:30:11] Processing FN01_N5381T5760_180min_10ug_C1_053015 
INFO[04:30:47] Processing FN02_N5381T5760_180min_10ug_C2_053015 
INFO[04:31:25] Processing FN03_N5381T5760_180min_10ug_C1_053015 
INFO[04:32:01] Processing FN04_N5381T5760_180min_10ug_C2_053015 
INFO[04:32:39] Processing FN05_N5381T5760_180min_10ug_C1_053015 
INFO[04:33:18] Processing FN06_N5381T5760_180min_10ug_C2_053015 
panic: Cannot decode packed binary. XML syntax error on line 3802344: unexpected EOF

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc0c1c69e50, 0x4d}, {0xa912c0, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0xbe0040?, 0xc034ff8240?}, {0xa912c0, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/psi.(*IndexedMzML).Parse(0xc1235b3ed0, {0xc104648000, 0x63})
	/workspace/philosopher/lib/psi/psi.go:115 +0x17b
philosopher/lib/mzn.(*MsData).Read(0xc1235b45d0, {0xc104648000, 0x63})
	/workspace/philosopher/lib/mzn/mzn.go:194 +0x66
philosopher/lib/qua.peakIntensity({0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/workspace/philosopher/lib/qua/lfq.go:92 +0xd5d
philosopher/lib/qua.RunLabelFreeQuantification({{0x0, 0x0}, {0x0, 0x0}, {0xa90d40, 0x4}, {0xc00013a0c0, 0x38}, {0x0, 0x0}, ...})
	/workspace/philosopher/lib/qua/qua.go:46 +0xed
philosopher/cmd.glob..func6(0x20342e0?, {0xa90ca0?, 0x6?, 0x6?})
	/workspace/philosopher/cmd/freequant.go:50 +0x29a
github.com/spf13/cobra.(*Command).execute(0x20342e0, {0xc000166060, 0x6, 0x6})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2032b40)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
Process 'FreeQuant' finished, exit code: 2
Process returned non-zero exit code, stopping
ERRO[04:33:37] Cannot decode packed binary. XML syntax error on line 3802344: unexpected EOF 

~~~~~~~~~~~~~~~~~~~~
Cancelling 207 remaining tasks

**Comment by prvst** [comment]
Can you convert your mzML files again using the latest msconvert ?

**Comment by wyu** [comment]
Thanks for your suggestion! 

I repeated the mzML conversion with the latest "msconvert" from "ProteoWizard3.0.22293.189308e". Before launching the search on the complete dataset, I was able to successfully search one arbitrary iTraq4 plex (N13T236). However, the plex "N5381T5760" that gave me the error before still yielded the same error as shown in the log file. 

Do you think that something is silently wrong about the "FN06_N5381T5760_180min_10ug_C2_053015" run? If so, is there a way to bypass it, so we can complete the overall search? Missing one run from a 24-fractions experiment is probably OK.

Thanks!
Wen

[log_2022-10-26_12-35-23_failed_plex.txt](https://github.com/Nesvilab/FragPipe/files/9871962/log_2022-10-26_12-35-23_failed_plex.txt)
fully

**Comment by prvst** [comment]
Can you share the file ?

**Comment by wyu** [comment]
Hi, here is the pepXML file I was referring to. Let me know if you need the whole plex.

Wen

[FN06_N5381T5760_180min_10ug_C2_053015.zip](https://github.com/Nesvilab/FragPipe/files/9872080/FN06_N5381T5760_180min_10ug_C2_053015.zip)

**Comment by prvst** [comment]
Sorry I was referring to the raw and mzML files

**Comment by wyu** [comment]
Hi, can you see if you can access the Box folder via the link? The upload will take some time, but the folder should be there.

https://az.box.com/s/1ar441189nakjlvdoe5kcn7vgboigzsl

Wen

**Comment by wyu** [comment]
Hi, the Box folder containing the raw, mzML and MsFragger output is not ready. I also place the sample manifest in the folder for your reference.

https://az.box.com/s/1ar441189nakjlvdoe5kcn7vgboigzsl

Thanks!
Wen

**Comment by prvst** [comment]
you forgot to send the database

**Comment by prvst** [comment]
Actually, that's unnecessary. I took the faulty mzML and converted myself, and got the same problem; the file does not seem to convert all the way to the end. The most likely reason is that you might have a bad raw file. My suggestion is that you try copying from the source again, if possible. In case not, just put it aside.

**Comment by wyu** [comment]
Thanks for looking into the issue! I was able to complete the search once I removed the offending pepXML and innteract* files in this folder.

Wen
