### ISSUE TITLE
Error in mass calibration: Not enough data to perform mass calibration.

### ISSUE THREAD

**Issue by ymk555** [Nesvilab/FragPipe#866]
- Describe the issue or question:
Hello FragPipe team,

I'm running DDA search using Fragpipe 18.0, MSFragger 3.5, ionQuant 1.8.0 and Philosopher 4.4.0. I run into this message in the mass calibration step:
`Not enough data to perform mass calibration. Using the uncalibrated data.`
As a result, the result output has very low identification. I also ran library files (not DIA) together to do MS1 feature mapping, but there was no such error for the library files. 
Any help or solution this issue? 

I really appreciate your efforts for developing this tool.
Yumi

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-10-20_13-10-04.txt](https://github.com/Nesvilab/FragPipe/files/9833642/log_2022-10-20_13-10-04.txt)

**Comment by fcyu** [comment]
Hi Yumi,

I guess your test_sample_01 data is from low-input data, but your test_lib_* data is from bulk cells. I think, it is expected that your test_sample_01 data did not have enough data for mass calibration, but your test_lib_* data did not have this issue.

But, your test_sample_01 data has so few IDs that match-between-runs failed, which results in few IDs even after match-between-runs. I think you should check our test_sample_01.

Best,

Fengchao

**Comment by ymk555** [comment]
Thank you, Fengchao.

When I look into the test_sample_01 raw file, it has pretty enough scan events in both MS1 and MS2. Does this issue only happen when the spectrum files does not have enough spectrum?

**Comment by fcyu** [comment]
It happens when there are not enough **high-quality** spectra. But, failure of the mass calibration won't affect the number of identified IDs much. So, the fundamental problem is that there are not enough IDs in your data.

Best,

Fengchao

**Comment by ymk555** [comment]
Thank you Fengchao.
I'll have to look into my sample quality.

Regards,

Yumi

**Comment by ymk555** [comment]
Thank you Fengchao.
I'll have to look into my sample quality.

Regards,

Yumi
