### ISSUE TITLE
fragpipe runnung error

### ISSUE THREAD

**Issue by khksw0403** [Nesvilab/FragPipe#867]
![error](https://user-images.githubusercontent.com/74076044/197050716-f137930a-10c5-40d3-9adc-9714946a9433.png)

Hello, developer!

i ran fragpipe and got above error msg. do you have any idea?

-detail info-
ubuntu 22.04 LTS
MSFragger 3.5
IonQuant 1.8.0
Philosopher 4.4.0
python 3.9.12

**Comment by fcyu** [comment]
It looks like your raw file was corrupted.

Best,

Fengchao
