### ISSUE TITLE
Missing diann-output.pdf when running fragpipe in linux cmd

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#871]
Hello,
I am writing because I run Fragpipe using the command line in Linux and when comparing my results with another person from my group that uses the interface in Windows, we realized that I don't have the diann-output.pdf (but I do have diann-output.tsv). While checking the log file I saw that in his case he had an extra command that I didn't have:

C:\DATA\FragPipe-jre-18.0\fragpipe\tools\diann\1.8.1\win\dia-nn-plotter.exe diann-output.stats.tsv diann-output.tsv diann-output.pdf

So, is the file missing because dia-nn-plotter.exe cannot be run in Linux? Is there any way I can get the diann-output.pdf?

Thanks in advance for your help.

Best regards,

Emma

**Comment by fcyu** [comment]
Hi Emma,

You are correct. The command `C:\DATA\FragPipe-jre-18.0\fragpipe\tools\diann\1.8.1\win\dia-nn-plotter.exe diann-output.stats.tsv diann-output.tsv diann-output.pdf` is to generate the PDF file. Unfortunately, it is only available in Windows due to how it is implemented. 

Best,

Fengchao
