### ISSUE TITLE
DIANN.exe has stopped working

### ISSUE THREAD

**Issue by EayonYang** [Nesvilab/FragPipe#873]
When I run FragPipe provided DIA_SpecLib_Quant workflows, I get this error. And I also check  'Quantify with DIA_NN' on the ‘Quant (DIA)’ tab. How can I solve this problem?

![image](https://user-images.githubusercontent.com/95112283/199167641-1325ecae-0a0d-4450-ba84-e0de1280e08a.png)
 Thank you~

**Comment by fcyu** [comment]
Can you send us the log file?

Thanks,

Fengchao
