### ISSUE TITLE
How is intensity normalised?

### ISSUE THREAD

**Issue by ndtivendale** [Nesvilab/FragPipe#874]
In the combined protein output file, how is the intensity normalised?

**Comment by fcyu** [comment]
The normalization algorithm is described in https://doi.org/10.1074/mcp.TIR120.002048 section "IonQuant Algorithm"

IonQuant uses MaxLFQ algorithm to aggregate peptide intensities to protein intensities. It is described in https://doi.org/10.1016/j.mcpro.2021.100077 section "Calculating Protein Intensity Using MaxLFQ Algorithm"

Best,

Fengchao
