### ISSUE TITLE
easypqp exhausted all memory

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#875]
Hi,
I want to analyze DIA data using fragpipe's DIA_SpecLib_Quant process, then I have some problems. I found that during one of the steps, the easyPQP program was using some number of threads, which caused the server to run out of memory and further cause the computing power to be underutilized at all.
So I would like to ask if there is any way to limit the number of threads used by easyPQP (if this will reduce the memory pressure), but without affecting the speed of other programs such as MSFragger, Philosopher?
Thanks,
LeeLee

**Comment by fcyu** [comment]
I don't think you can specify a different thread number for EasyPQP. But we do have a known issue: https://github.com/Nesvilab/FragPipe/issues/567

Best,

Fengchao

**Comment by lbwfff** [comment]
I re-run the software with a quarter of the thread count and it ran smoothly. I found that the parallelism parameter of fragpipe controls the number of tasks of esaypqp, because easypqp still occupies all my CPU, but the reduction of the number of tasks does not cause memory problems. 
Considering that easypqp will use the full thread count, would it be more appropriate to let fragpipe's default easypqp task count be one?

**Comment by fcyu** [comment]
This is what the issue https://github.com/Nesvilab/FragPipe/issues/567 is about. I will close this one since it is a duplicated issue.

Best,

Fengchao
