### ISSUE TITLE
ProteinProphet Error while running FragPipe

### ISSUE THREAD

**Issue by ManasijP** [Nesvilab/FragPipe#876]
Apologies if this issue has already been sorted in any other threads, but I could not find it.

I have been trying to run a standard open search with 3 mzml files generated using MSConvert from .raw files generated from a ThermoScientific Orbitrap Elite. The FASTA file is swissprot, I have added a decoy using the add decoy functionality, and I am using the standard open workflow.

The program seems to run fine till the PeptideProphet stage, and then there is an error message saying panic: Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files. After this, it shows another error message as follows-

Process 'ProteinProphet' finished, exit code: 2
Process returned non-zero exit code, stopping

I am probably missing something really simple and doing something silly, but cannot seem to point the issue. 

[log_2022-11-03_16-15-52.zip](https://github.com/Nesvilab/FragPipe/files/9931211/log_2022-11-03_16-15-52.zip)

**Comment by fcyu** [comment]
The search found no IDs from your data. Please double check your settings such as enzyme, variable modifications, etc.

Best,

Fengchao

**Comment by hongweizhao1** [comment]
have solved this solution? sir I meet the same trouble
