### ISSUE TITLE
Additional column request - normalized vs non-normalized intensities

### ISSUE THREAD

**Issue by roberthardt** [Nesvilab/FragPipe#877]
Dear developers,

would it be feasible to report the normalized as well as the non-normalized intensities of proteins/peptides etc in the result tables? Currently there is only the intensity column which is, I assume, either normalized or non, depending on the IonQuant settings. While I usually work with normalized intensities, I usually also like to see who the original sample response was before normalization (boxplots etc.). At the moment I would have to run ion quant twice, once with normalization enabled and once without, to get this information.

Best

Robert

**Comment by fcyu** [comment]
Hi Robert,

Thanks for your suggestion. We will discuss it internally.

Best,

Fengchao
