### ISSUE TITLE
Dia-NN wiff file workflow

### ISSUE THREAD

**Issue by ttessie2** [Nesvilab/FragPipe#879]
Hello,
I'm new to DIA workflows and I'm wondering how to demultiplex wiff files for running DIA-NN in MSFragger. I see the documentation for thermo RAW files, but what about WIFF files?

**Comment by ttessie2** [comment]
I suppose all I was wondering was if there were additional parameters to consider when converting the wiff files to mzML. So what your saying is I can convert the DIA wiff files to mzML the same way I'd convert my DDA wiff files? The DIA acquisition windows overlap by 0.5 m/z so I wasn't sure if this was something that needs to be considered.

**Comment by fcyu** [comment]
What is your isolation window size? If it is much wider than 0.5 Th, then it is not staggered isolation windows. No additional settings are needed.

Best,

Fengchao

**Comment by ttessie2** [comment]
Windows go as follow and increase from 7.5 to 15.5 to 25.5 to 50.5 and only overlap by 0.5.
399.5	407
406.5	414
413.5	421
420.5	428
427.5	435
434.5	442
441.5	449
448.5	456
455.5	463
462.5	470
469.5	477
476.5	484
483.5	491
490.5	498
497.5	505
504.5	512
511.5	519
518.5	526
525.5	533
532.5	540
539.5	547
546.5	554
553.5	561
560.5	568
567.5	575
574.5	582
581.5	589
588.5	596
595.5	603
602.5	610
609.5	617
616.5	624
623.5	631
630.5	638
637.5	645
644.5	660
659.5	675
674.5	690
689.5	705
704.5	720
719.5	735
734.5	750
749.5	775
774.5	800
799.5	825
824.5	850
849.5	900
899.5	950
949.5	1000
999.5	1050
1049.5	1100
1099.5	1150
1149.5	1200
1199.5	1250

**Comment by fcyu** [comment]
Thanks for your information. I don't think additional settings are needed. You can follow the "Convert Thermo .raw files (DDA or DIA data with non-overlapping windows)" tutorial from https://fragpipe.nesvilab.org/docs/tutorial_convert.html.

Best,

Fengchao

**Comment by ttessie2** [comment]
Thank you, this worked!
