### ISSUE TITLE
EasyPQP convert error

### ISSUE THREAD

**Issue by SStoychev01** [Nesvilab/FragPipe#880]
Hello, I'm trying to build a spec library from DDA run but EasyPQP comes back with and error "not enough values to unpack (expected 1, got 0)". The various log files are uploaded here, Thanks for your assistance. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop her
[easypqp_convert_0.log](https://github.com/Nesvilab/FragPipe/files/9963168/easypqp_convert_0.log)
[cmds.txt](https://github.com/Nesvilab/FragPipe/files/9963184/cmds.txt)

[log_2022-11-08_18-03-40.txt](https://github.com/Nesvilab/FragPipe/files/9963163/log_2022-11-08_18-03-40.txt)

**Comment by fcyu** [comment]
Can you send some scan tag examples from Complex_Cent_DDA.mzML to us? If you don't know how to open the mzML file, you can also send us the whole file.

Best,

Fengchao

**Comment by SStoychev01** [comment]
here you go, can grab the mzml file from here https://drive.google.com/file/d/1GCQTats8vBHaT77ET0CRrrDO0p7BDZSa/view?usp=sharing

![image](https://user-images.githubusercontent.com/25788643/200639999-6fd5bc41-dac0-4920-9e7c-0d3a947831f8.png)

![image](https://user-images.githubusercontent.com/25788643/200640323-4d9dd288-e446-45df-a175-9b95e7c01205.png)

![image](https://user-images.githubusercontent.com/25788643/200640545-c4aa5442-4f3c-4ad2-ae33-12d4162ca741.png)

**Comment by fcyu** [comment]
Thank you very much for you file.

Your data is from TripleTOF 5600, which has a different scan ID format than Thermo. And there is no scan number encoded in the ID: `sample=1 period=1 cycle=1 experiment=1`. For this case, MSFragger rollbacks to use `index+1` as the scan number. We will discuss internally how to fix EasyPQP.

Best,

Fengchao

**Comment by SStoychev01** [comment]
Thank you

**Comment by ttessie2** [comment]
Great, so I can go ahead and insert/remove those lines of code in my existing convert.py file?

**Comment by fcyu** [comment]
You can install the fixed version using 
```shell
pip uninstall -y easypqp
pip install git+https://github.com/guoci/easypqp.git@master
```
You need to have git installed.

Best,

Fengchao
