### ISSUE TITLE
DDA/DIA labelling in manifest file

### ISSUE THREAD

**Issue by ericart89** [Nesvilab/FragPipe#881]
Hello,
I am running Fragpipe using the command line in Linux. We are implementing a HLA workflow for both, DIA and DDA data and we have thousands of injections. Exceptionally, we have seen that we have some injections wrongly labelled (DDA instead of DIA, or the opposite) and then we get the following message in MSFragger:

XXX.mzML seems from DIA but MSFragger is in DDA mode.

I know that in the interface version of Fragpipe (Windows), the adquisition mode of the injection is automatically detected when loading the sample, so I was wondering if there is something similar for the Linux version.... for instance, loading the manifest file without any labels could work? In case it doesn't exist, can you recommend any method/tool to automatize the DDA/DIA labelling before running fragpipe?

Thanks in advance for your help.

Best regards,

Emma

**Comment by fcyu** [comment]
Hi Emma,

I believe you can still use the FragPipe GUI in Linux as long as you have X-window or X-forwarding (https://fragpipe.nesvilab.org/docs/tutorial_setup_x_forwarding.html). 

If you want to use the headless mode, you can edit the manifest file using Excel, which is supposed to be easier to drag, copy, and paste. 

The "automatic" detection is not very smart. It just guesses the data type by the file name.

> for instance, loading the manifest file without any labels could work?

If there is no data types, FragPipe uses DDA by default.

Best,

Fengchao

**Comment by anesvi** [comment]
I agree, running with a file manifest created in advance is a better option when there are many files
Alexey

**Comment by ericart89** [comment]
Ahh, so if I understand correctly, your current implementation in the GUI is only based in the file name?

**Comment by fcyu** [comment]
No problem.
