### ISSUE TITLE
Out of memory error | semi-specific search + multiple variable modifications

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/FragPipe#884]
Dear FragPipe team,

I am trying to run a semi-specific search in a dataset from samples treated for C-terminal enrichment. We are currently searching the measured samples before C-terminal enrichment, so this is pretty much a shotgun analysis.

It contains several modifications that we are setting as variable in the search, which results in a very big search space. 

We always end up having an out-of-memory error. Have tried with 50/75/100/150/200 GB of RAM usage. We have tried in a server PC with several users simultanously and also in a dedicated PC, with less RAM (100GB) with same results.

For differential analysis of C-terminal processing, we need to do proper quantitation. I understand that open-search is not compatible with IonQuant, therefore we choose to go for closed search with variable modifications.

Do you haven an idea on how can we overcome this issue? I would have expected MSFragger to generate enough slices to be able to handle the big search space, but it seems to me that it is always generating only one slice, regardless of the RAM usage.

The chemical modifications are as follows:

- Amidation of C-term, but we also expect cross-reactivity with D and E.
- Light and heavy dymethyl at K and N-term.
- Acetylation of N-term and K.

The log file:
[log_2022-11-11_11-11-27.txt](https://github.com/Nesvilab/FragPipe/files/9989386/log_2022-11-11_11-11-27.txt)

**Comment by fcyu** [comment]
The database slice happens after MSFragger generates all modified peptides. Currently, your computer with 50GB free memory does not have enough memory to generate modified peptides.

Can you try to increase "split database" from 1 to, say, 4? It requires Python.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Hello Fengchao,

Many thanks for your suggestion.

Just as a quick update, I have tried 4 and 8 slices using 150 GB RAM and still failing. Now testing with 16 slices.

Best,
Miguel

**Comment by fcyu** [comment]
Have you disabled "mass calibration and optimization"? If no, you should disable it.

Best,

Fengchao

**Comment by MiguelCos** [comment]
Thanks for pointing that out. 

I was not disabling it. Now I did. Let's see how it goes.

Best,
Miguel

**Comment by PetrLapcik** [comment]
Hello,

I collaborate with MiguelCos on this project. I set up the search with  "split database" option to 30 and it finished successfuly. 

Thanks a lot for the help!

With regards
Petr
