### ISSUE TITLE
EasyPQP convert error END

### ISSUE THREAD

**Issue by ttessie2** [Nesvilab/FragPipe#886]
Not sure what went wrong here! Got right up until the end and got this error.

[log_2022-11-15_19-54-07.txt](https://github.com/Nesvilab/MSFragger/files/10017186/log_2022-11-15_19-54-07.txt)

**Comment by guoci** [comment]
@ttessie2 According to the log, it seems you have run out of memory, as indicated by the following line.
`MemoryError: bad allocation`

**Comment by ttessie2** [comment]
Any idea why this would be the case? Is 32GB RAM enough?

**Comment by anesvi** [comment]
I see you are using SWATH data. Is it Sciex instrument? Which one?
Are the files very big?
I am not sure. It has not been an issue for other users as far as I remember.
Alexey

**Comment by ttessie2** [comment]
Hi Alexey, 
Data was acquired on a TripleTOF 6600. I will try again, perhaps there was something running in the background that contributed to this?  Which files are you referring to as far size? the mzml files?

**Comment by anesvi** [comment]
mzML
Well, we do not know what happened at the moment

**Comment by ttessie2** [comment]
I don't have the file sizes on hand, it's all on my PC at home.
I'm looking at the log, is the memory error associated with pyopenms (line 21395)? The easypqp convert error end/begin occurs multiple times prior to line 21395. But only at line 21395 does the memory error show up. Is there are separate easypqp issue here?

**Comment by ttessie2** [comment]
They swath mzml files are around 7GB.

**Comment by fcyu** [comment]
Hi @ttessie2 ,

Your mzML files are quite large. Can you set the `Parallelism` in the `Workflow` tab to 1 and re-run from spectral library generation? You can skip finished steps by unchecking them.

Best,

Fengchao

**Comment by ttessie2** [comment]
It's running now. I also updated easypqp to 1.33 since I got the notification.

**Comment by ttessie2** [comment]
[log_2022-11-16_19-40-21.txt](https://github.com/Nesvilab/FragPipe/files/10026718/log_2022-11-16_19-40-21.txt)

Unsuccessful :(

**Comment by fcyu** [comment]
```
  File "C:\Users\Tanner\anaconda3\lib\site-packages\easypqp\convert.py", line 434, in read_mzml_or_mzxml_impl
    fh.load(path, input_map)
  File "pyopenms\pyopenms_5.pyx", line 11095, in pyopenms.pyopenms_5.MzMLFile.load
RuntimeError: - due to that error of type Parse Error in: D:\a\OpenMS\OpenMS\OpenMS\src\openms\source\FORMAT\HANDLERS\MzMLHandler.cpp@181-void __cdecl OpenMS::Internal::MzMLHandler::populateSpectraWithData_(void)
exit status: 1
```

I believe that something was wrong with your data. If you want, we can take a look at your mzML file. But I am not sure how much we can help.

Best,

Fengchao

**Comment by ttessie2** [comment]
Which file would you like?
For what it's worth. I've been able to process all of the DDA files in fragpipe without issue and I haven't had any issue processing the DIA files directly in DIA-NN.

**Comment by fcyu** [comment]
> For what it's worth. I've been able to process all of the DDA files in fragpipe without issue and I haven't had any issue processing the DIA files directly in DIA-NN.

Then, is sounds like an issue in OpenMS. You should submit a bug report to their repository.

Best,

Fengchao

**Comment by ttessie2** [comment]
I will do that.
Do you know if this error is with a particular file?

**Comment by fcyu** [comment]
`40045_miniT_32_1_NBCC164_Mymryk_Tanner_90min_quarter_SWATH.mzML`

**Comment by ttessie2** [comment]
I'm not sure how to send such a large file. Is there any way you can help me inspect it? Anything obvious I can look for?

**Comment by fcyu** [comment]
Since I never read OpenMS source code, I am afraid I can't help much. But I can take a look if you upload it to https://www.dropbox.com/request/srDd88TLWdgerkgPuJci

Best,

Fengchao

**Comment by ttessie2** [comment]
That's okay, I appreciate the offer! I don't want to take up your time if I've submitted the issue to OPENMS. I'll see what they say and then go from there.

**Comment by TTCooper-PhD** [comment]
> Hi @ttessie2 ,
> 
> Your mzML files are quite large. Can you set the `Parallelism` in the `Workflow` tab to 1 and re-run from spectral library generation? You can skip finished steps by unchecking them.
> 
> Best,
> 
> Fengchao

I have a similar issue right now. I am analyzing files from Thermo Eclipse, weird thing is these runs have worked before in FragPipe so I am unsure what has changed. I recently updated EasyPQP.

**Comment by TTCooper-PhD** [comment]
> > Hi @ttessie2 ,
> > Your mzML files are quite large. Can you set the `Parallelism` in the `Workflow` tab to 1 and re-run from spectral library generation? You can skip finished steps by unchecking them.
> > Best,
> > Fengchao
> 
> I have a similar issue right now. I am analyzing files from Thermo Eclipse, weird thing is these runs have worked before in FragPipe so I am unsure what has changed. I recently updated EasyPQP.

![image](https://user-images.githubusercontent.com/36017084/204190892-344234a0-0e71-470d-ab11-a0f1b21f626a.png)

**Comment by fcyu** [comment]
>  weird thing is these runs have worked before in FragPipe so I am unsure what has changed. 

It is weird since the same file worked before. Could you share your raw file with us? I can send you a link to upload if you need.

Best,

Fengchao

**Comment by TTCooper-PhD** [comment]
> https://www.dropbox.com/request/srDd88TLWdgerkgPuJci

dropbox link above? no problem.

**Comment by TTCooper-PhD** [comment]
I did reconvert from raw to mzml in mscovert, but should be with the same parameters.

**Comment by fcyu** [comment]
> dropbox link above? no problem.

Correct.

Best,

Fengchao

**Comment by TTCooper-PhD** [comment]
> > dropbox link above? no problem.
> 
> Correct.
> 
> Best,
> 
> Fengchao

sent you two files, one has worked previously (24hr) one is new (48hr).

**Comment by ttessie2** [comment]
Is there a reason why rebooting your computer solved this? I still have not been able to resolve the issue on my end.

**Comment by ttessie2** [comment]
I will upload the problematic file to the dropbox for you to take a look at if you don't mind.

**Comment by fcyu** [comment]
Yes, I can take a look.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @ttessie2 .

I have no issue running your file using FragPipe. Please see the attached log file.

Best,

Fengchao
[log_2022-11-29_11-54-07.txt](https://github.com/Nesvilab/FragPipe/files/10115398/log_2022-11-29_11-54-07.txt)
