### ISSUE TITLE
"DIA-NN did not print 'Finished'" error message

### ISSUE THREAD

**Issue by lolaakinlaja** [Nesvilab/FragPipe#887]
I have been repeatedly met with this error when running a frapipe search with msbooster selected. I am not really sure how to fix this (how to rerun frappe from msbooster step?) and I have looked for solutions. Any help will be appreciated. Here is the error message I am getting. 

DIA-NN did not print 'Finished', and therefore did not finish predictions successfully. Rerunning from the MSBooster stepmay resolve the issue. Exiting
Process 'MSBooster' finished, exit code: -1
Process returned non-zero exit code, stopping

Here is the log file
[log_2022-11-16_16-09-55.txt](https://github.com/Nesvilab/FragPipe/files/10026612/log_2022-11-16_16-09-55.txt)

**Comment by fcyu** [comment]
This is the DIA-NN issue that we have been straggled with for a long time. It happens random and hard to reproduce. I think there are no other ways except for trying more times.

Best,

Fengchao

**Comment by yangkl96** [comment]
Hello,

Sorry for the late response. Please try opening the command line (in the Windows search bar, type "cmd") and running `C:\Users\kdavid1.EAD\Downloads\FragPipe-18.0\fragpipe\tools\diann\1.8.1\win\DiaNN.exe --lib C:\Users\kdavid1.EAD\Desktop\lola_111022\hymenopteramine_fasta\bee_01_h\bee_hymenopteramine_01_msbooster\bee_hymenopteramine_01\spectraRT.tsv --predict --threads 7 --strip-unknown-mods` to see if DIA-NN can produce the library this way

**Comment by lolaakinlaja** [comment]
I actually was able to resolve this error by just ensuring that Visual C++ Redistributable for Visual Studio was installed on my computer and that seems to have fixed it. 
Here is the link to what I installed.
[https://aka.ms/vs/16/release/VC_redist.x64.exe](url)

**Comment by yangkl96** [comment]
Glad to hear that, I've added an error message for the next msbooster release to direct people to the redistributable download site
