### ISSUE TITLE
questions on pepxml of research results

### ISSUE THREAD

**Issue by ibphuangchen** [Nesvilab/FragPipe#888]
Hey, 

I have a naive question. I looked that the search results (pepxml files) by MSFragger in the fragpipe pipeline, and found that the cysteine modifications are all shown as 160.03065, instead of 57.02146. Why is that? I also seen that in the tab-delimited .pin file, it is shown as 57.02146. Could you give a brief explanation? Thanks!

**Comment by fcyu** [comment]
160.03065 = 57.02146 + 103.00919, where 103.00919 is the mass of cysteine. 

Best,

Fengchao

**Comment by ibphuangchen** [comment]
Got it. Thank you!
