### ISSUE TITLE
LFQ-MBR without MBR option 

### ISSUE THREAD

**Issue by Sierra0920** [Nesvilab/FragPipe#889]
Hi, 

I tried to run the LFQ-MBR workflow with and without the MBR option and it seems like they have  the exact same results 

I used the same MS datasets with 4 experiment groups and each of them had 24 raw files(fractions). I wanted to see the difference when i turned the MBR option ON and OFF in the IonQuant channel.

But it seems like the number of identified and quantified proteins and protein ids are exactly the same in both results.

Is there any other way i can run LFQ without MBR option?
I uploaded the log files from both runs.

Thanks

[log_2022-11-17_15-04-45_LFQ_OffMBR.txt](https://github.com/Nesvilab/FragPipe/files/10037204/log_2022-11-17_15-04-45_LFQ_OffMBR.txt)
[log_2022-11-18_04-58-28_LFQ_OnMBR.txt](https://github.com/Nesvilab/FragPipe/files/10037205/log_2022-11-18_04-58-28_LFQ_OnMBR.txt)

**Comment by fcyu** [comment]
MBR won't affect the total number of peptides and proteins identified from all experiments. It reduces the zero intensities (missing values). To see the effect, you should count the number of proteins/peptides with non-zero intensities.

Best,

Fengchao

**Comment by Sierra0920** [comment]
i already counted the missing values when i meant quantified proteins. But it's the same. Both have same number of proteins with non-zero intensities and same intensity values.

**Comment by Sierra0920** [comment]
Yes, i used `combined_protein.tsv` files. 

Could I send you the files via e-mail? 

Thanks

**Comment by Sierra0920** [comment]
Thank you

I sent the email with the files. 

Best, 

Sarang
