### ISSUE TITLE
Quantification result file processin in R!

### ISSUE THREAD

**Issue by seongminlab** [Nesvilab/FragPipe#890]
Dear FragPipe developers!

I want to directly process the "combined_protein.tsv" in R

i have 9786 lines in my combined_proteins file

Here is my R code for data uploaded to DataFrames

`
Prot <- read.table("combined_protein.tsv", sep='\t',header=T)

nrow(Prot)
`

but in "Prot" have only 3882 lines!

how can i loaded combined_protein.tsv to R ??

when i convert TSV to CSV,  that file is clearly working by read.csv()  ..... 

suggest any other options for read TSV in R 

Thank you,

Best
Seongmin

**Comment by fcyu** [comment]
Hi Seongmin,

Your question is about how to load a tsv file using R programming. 

Although we generally don't answer questions that are not very much directly related to our tools, I can paste my code in the following. Hope it will help.

```R
library(readr)
xx <- read_tsv("combined_protein.tsv", na=c("", "0"))
```

Best,

Fengchao

**Comment by seongminlab** [comment]
Thank you !
