### ISSUE TITLE
Visualization window does not work

### ISSUE THREAD

**Issue by Amon789** [Nesvilab/FragPipe#891]
Hi, 

It gives an error message when I try to open the visualization window after the DIA-DIA-Umpire-SpecLib-Quant runs.
Can you help what went wrong? What should I pay attention to in order to open the visualization window?

![image](https://user-images.githubusercontent.com/85936610/202713178-45e4eb9e-488e-4721-9848-bfa1f7acd3e1.png)

**Comment by fcyu** [comment]
Kai @KaiLiCn , can you take a look?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi @Amon789 , I will do a test and will let you know if I need anything from you.

Best,
Kai

**Comment by KaiLiCn** [comment]
Hi,

Could you share your log file and fp-manifest file with me? They should be in your result folder.

Kai

**Comment by Amon789** [comment]
Hi, 

Please find attached the files. I add .txt to the fp.manifest to be able to upload here. 
[log_2022-11-17_12-37-07.txt](https://github.com/Nesvilab/FragPipe/files/10073991/log_2022-11-17_12-37-07.txt)
[lcms-files_2022-11-17_12-37-07.fp-manifest.txt](https://github.com/Nesvilab/FragPipe/files/10074012/lcms-files_2022-11-17_12-37-07.fp-manifest.txt)

**Comment by kailaw138** [comment]
i have a similar problem, however, no error message or log was given by fragpipe. 

when only a few data are processed, it loaded perfectly and fast. However, when the data were larger (more than a 10 data), it took a v. long time to load and yet nothing was shown after a high cpu load and back to ideal. 

have no idea what was going on. terminate java and exit. multiple times already.

**Comment by KaiLiCn** [comment]
Sorry for the inconvenience. We will release a new version of FragPipe with updated visualization tool in coming days. Please try it and let me know if it still has the same problem.

**Comment by fcyu** [comment]
Hi @kailaw138 ,

We released a new version that fixes this issue. Please download it from https://github.com/Nesvilab/FragPipe/releases/tag/19.0

Best,

Fengchao
