### ISSUE TITLE
Tims Tof MS data analysis

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#892]
Hi all,
I am trying to use some .d files from a TIMS-TOF MS and analyze them with fragpipe.  Targets are non-labbeled. I wou;d like to ask you what of the workflow you propose to me, to optimize my results. In my first approach I convert the .d files to mzml and trying to run in the default workflow. As a result, you can see in the attached log file that the Mass callibration completed, as long as MS Booster, but then I had a lot of reasons that something went wrong. Then I tried to imput the .d files as they are, and run it with another workflow. But the really weird fact was that even when I tried with with a workflow for labelled targets (as negative control lets say), still give results. So I am confused if my analysis wotk in an appropriate way.
Thank you in advance 
Best
tasos
[log_2022-11-17_14-43-44.txt](https://github.com/Nesvilab/FragPipe/files/10045661/log_2022-11-17_14-43-44.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Tasos,

First of all, I need to have some basic knowledge about your sample before giving any suggestions.

1. What is the enzyme when you digest the sample?
2. What is the species?
3. You said that "argets are non-labbeled.". I just want to confirm that there is no chemical labeling, right?
4. Are there any PTM enrichment?
5. Is the data DDA or DIA?

Best,

Fengchao

**Comment by tasos2310** [comment]
Hi Fengchao,
Thank you for your quick response,
1. The enzyme that I use is trypsin. 
2. The target species is a fungi calles Cladosporium fulvum. The point and the complexity in our case is that the starting material is infected material tomato plant tissue. So the database that I use is always tomato and fungi proteome. My interest is fungal proteins but in order to see if everything works I used tomato too. 
3. yes exactly, no chemical labbeling. 
4. No PTM enrichment. The only extra treatment on those samples is the use of Pierce™ High pH Reversed-Phase Peptide Fractionation Kit, to improve protein identification in general.
5. Data are DDA. 
Best,
Tasos

**Comment by fcyu** [comment]
Hi Tasos,

Thanks for your information. From your log, the enzymes setting can be adjusted because 1) both enzymes were to trypsin; 2) the enzyme name was set to `nonspecific`. Could you do the following?

1. Do not use the mzML file for the timsTOF data. Using the raw .d folder normally gives better result.
2. Remove the spaces in your folders and files names. For example, the `MZML files` folder and the `2022-11-17-decoys-Alternative splicing proteome.fasta.fas`. Although they have not caused any issues, but they would in the rest of the steps after MSFragger searching.
3. Does cysteine has carbamidomethylation?
4. Load the `LFQ-MBR` workflow, specify the fasta file, and do not change anything else.

Could you rerun your data, and send me the log file if there are any issues?

Best,

Fengchao

**Comment by tasos2310** [comment]
Hi Fengchao,
Yes you are right the double digest set up remained accidently from a previous analysis. I fix the details that you told me and seems that works. Have a look on the log file. But the results is like this that I was theoretically expected.
Best,
tasos
[log_2022-11-18_17-33-30.txt](https://github.com/Nesvilab/FragPipe/files/10045762/log_2022-11-18_17-33-30.txt)

**Comment by fcyu** [comment]
Hi Tasos,

Glad to see that it works.

Best,

Fengchao

**Comment by tasos2310** [comment]
One more question to see if there is a way to improve sensitivity. When I put the database, i select from the database and I add in spike-in sequences my targets. IF I did not inlude the tomato you think that something could change??
Thank you in advance,
Best
Tasos

**Comment by fcyu** [comment]
It is a difficult question. I guess you know your sample better than me. You can try both ways to see what gives the better result.

Best,

Fengchao

**Comment by tasos2310** [comment]
I just start to do that. 
Thank you so much for your help,
Best regards,
Tasos
