### ISSUE TITLE
Running Technical replicates

### ISSUE THREAD

**Issue by AparnaChauhan** [Nesvilab/FragPipe#893]
I want to analyze LFQ files which have been run in technical triplicates (6 fractions for each sample). However, I'm unsure whether to consider each replicate as separate experiment and combine the intensities after FragPipe run or set experiment same for all replicates. Although I need one intensity column per sample in the end, would the algorithm used for combining intensities work for technical replicates?

![image](https://user-images.githubusercontent.com/49096431/203063669-695e2bbb-8d78-4f6b-bf43-1785390e512e.png)

**Comment by fcyu** [comment]
> Although I need one intensity column per sample in the end, would the algorithm used for combining intensities work for technical replicates?

Yes, I think so.

Best,

Fengchao
