### ISSUE TITLE
--config-IonQuant flag

### ISSUE THREAD

**Issue by avera1988** [Nesvilab/FragPipe#894]
Hi, 

I am trying to run fragpipe in a headless mode in our HPC. I was dealing to configure the location of IonQuant, I had to start a GUI session and there save the configuration of the paths pointing to philosopher, MS-Fragger and IonQuant. 
I noticed that users can specify the paths for both Philospher and ms-fragger using the flags ` --config-msfragger `  and ` --config-philosopher ` . However, I am wondering if there is a flag for also specifying the path to IonQuant without the necessity to run the GUI.  For some other clusters, GUI is not possible to run.

Thanks!

Arturo.

**Comment by fcyu** [comment]
Duplicated issue: https://github.com/Nesvilab/FragPipe/issues/733
