### ISSUE TITLE
Process 'DIA-NN' finished, exit code: -1

### ISSUE THREAD

**Issue by DianaSamodova** [Nesvilab/FragPipe#898]
- Describe the issue or question:
Process returned non-zero exit code, stopping DIA NN. Failed to write the output files. Please see the log file attached.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[diann-output.log.txt](https://github.com/Nesvilab/FragPipe/files/10084556/diann-output.log.txt)

**Comment by fcyu** [comment]
The log file says 
```shell
No MS2 spectra: aborting
ERROR: cannot load the file, skipping
```
Can you double check if your mzML files have MS2 scans?

Thanks,

Fengchao

**Comment by DianaSamodova** [comment]
Dear Fengchao,
This is strange, because I used the following conversion settings:
***@***.***
Moreover, I tried loading .d files directly into the FragPipe and got the following error message: ***@***.***  This is very strange, because I was able to analyse the same raw files with DIA NN.
Do you have any idea, why this might be the case? Thanks in advance.
Best,
Diana

**Comment by danielgeiszler** [comment]
Hi Diana,

Some of your message was obscured because it believed it was an email.

**Comment by DianaSamodova** [comment]
Hi Daniel,
This is strange. I just wrote that I used the recommended settings for timsTOF data conversion, as well as I got a following message "No LCMS files provided after excluding diaPASEF runs", when I tried searching .d files directly, withou preconversion to .mzML.
Best,
Diana

**Comment by fcyu** [comment]
Hi Diana,

If your data was from diaPASEF, we don't support it for now (as the error message you saw). Unfortunately, converting it to mzML won't change the fact that the data is from diaPASEF.

Best,

Fengchao

**Comment by DianaSamodova** [comment]
Hi Fengchao,
Thanks for letting me know.
Best,
Diana

**Comment by fcyu** [comment]
Hi Diana,

If your data was from diaPASEF, MSFragger-DIA has not fully support it yet (as the error message you just saw). If you converted it to mzML format, MSFragger-DIA would be able to search it but the result is not optimal. Then, when DIA-NN performs the quantification, it doesn't support diaPASEF in mzML format (it can only process .d for the diaPASEF data). I think that is why you see the error message from DIA-NN.

Best,

Fengchao

**Comment by DianaSamodova** [comment]
Hi Fengchao, 
I see...the thing is that I simply need to combine the raw files into one experiment and search them with DIA NN, that's why I was trying to do it within the FragPipe, because I don't know how to do it in DIA NN. 
Anyway, thanks for your help.
Best,
Diana

**Comment by fcyu** [comment]
Hi Diana,

Thanks for the additional information. 

You can still analyze diaPASEF data in FragPipe with the following steps:

1. Set the data type to `DIA-Quant` for all .d folders from diaPASEF. `DIA-Quant` means only performing quantification no MSFragger-DIA searching.
2. In the DIA-NN tab, specify the path of the library.tsv file if it is from an existing analysis.

Best,

Fengchao

**Comment by DianaSamodova** [comment]
Hi Fengchao,
Thanks for the suggestion! Unfortunately, I don't have a library for this particular samples and was planning to analyse them with the direct DIA..
Best,
Diana
