### ISSUE TITLE
 [unweightedSpectralEntropy, deltaRTLOESS]; Process 'MSBooster' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by ling-t** [Nesvilab/FragPipe#899]
Hello,

While trying to run TMT  the following error was encountered:
Generating edited pin with following features: [unweightedSpectralEntropy, deltaRTLOESS]
Loading predicted spectra
Processing b1_1.mzML
java.lang.NullPointerException
	at Features.mzMLReader.setPinEntries(mzMLReader.java:254)
	at Features.percolatorFormatter.editPin(percolatorFormatter.java:277)
	at Features.MainClass.main(MainClass.java:529)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 65 remaining tasks

Thank you as always for all of your assistance!

All the best,

Ling

[log_2022-11-26_21-57-51.txt](https://github.com/Nesvilab/FragPipe/files/10096419/log_2022-11-26_21-57-51.txt)

**Comment by yangkl96** [comment]
Hi Ling,

I tried this with some TMT mzml files I had available, but couldn't replicate it. Would it be possible to share CAA20221121yexf_wosp22052_TMT16plex_120min_b2_12.mzML here: https://www.dropbox.com/request/0PgTcPwAKjkUiVXt57M0

Thanks,
Kevin
