### ISSUE TITLE
Wrong FragPipe version breaks the latest IonQuant

### ISSUE THREAD

**Issue by pablomics-star** [Nesvilab/FragPipe#902]
Hi, I am calculating on Linux my analyzed samples in Timstof Pro ( .d raw files), using on Fragpipe v17, MSfragger v3.5. The problem is when I quantify with Ionquant v1.7.17, it starts the calculation but leaves it halfway, throwing the following error:

**java.lang.NullPointerException: Something was wrong in update protein.tsv**

However, every time it stops somewhere in IonQuant (see attached log file) do you have any suggestions for what to do about it?
[log_2022-11-30_12-53-35.txt](https://github.com/Nesvilab/FragPipe/files/10125591/log_2022-11-30_12-53-35.txt)

**Comment by fcyu** [comment]
The version of FragPipe does not match those of MSFragger and Philosopher. Can you upgrade the FragPipe to 18.0 and try again?

Best,

Fengchao

**Comment by pablomics-star** [comment]
> The version of FragPipe does not match those of MSFragger and Philosopher. Can you upgrade the FragPipe to 18.0 and try again?
> 
> Best,
> 
> Fengchao

I'll do that and tell you, thank you very much
