### ISSUE TITLE
Understanding rt_score

### ISSUE THREAD

**Issue by grahamdelafield** [Nesvilab/FragPipe#903]
I am interested in learning more about the rt_score reported in psm.tsv. I assume this is in the same vein as other metrics and indicates the agreement between the observed retention time and the predicted/expected retention time? Perhaps this is a function of peptide prophet?

This is not listed on the [documentation](https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html) page. Thanks!

**Comment by fcyu** [comment]
This score is from MSBooster. And you are right about its meaning. For details, please check the preprint here: https://www.biorxiv.org/content/10.1101/2022.10.19.512904v1

Best,

Fengchao

**Comment by grahamdelafield** [comment]
Thank you!
