### ISSUE TITLE
fragpipe with dia always crashing beacuse of memory

### ISSUE THREAD

**Issue by RicZenChioz** [Nesvilab/FragPipe#905]
Dear Fragpipe team 

thank you for the hard work. 
i just downloaded the new v19.0 and i am trying to do DIA using some DDA files as library. (i have 12 fractions and 4 DIA files)
it is continuosly crashing in the MAIN SEARCH of the DIA part while all other previous steps always work fine. if i do only the fractions in DDA mode it always works.

in one of the error i found this:
_Not enough memory allocated to MSFragger.
If mass calibration was enabled, please turn it off by setting calibrate_mass = 0 (when running MSFragger in command line) or changing 'calibration and optimization' to 'None' (when running MSFragger in FragPipe).
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35)._

i tried to limit the ram but is still crashing, i tried to limit from 7-50 to 7-35 and less mod but nothing.

i tried to use the split database but this error comes 
![image](https://user-images.githubusercontent.com/119876312/205697937-8117ad3a-4a4a-46df-bed5-b20a3b3ef6bf.png)
"split database is incompatible with DIA, GFP-DIA...."

i dont really how to solve this... also DIA-nn on its own works perfectly fine.

can you help me here?

**Comment by fcyu** [comment]
Ca you share us the log file? It's file name starts with `log_`.

Thanks,

Fengchao

**Comment by RicZenChioz** [comment]
yes i found 4 of those of different testing (more or less CPU/ram and different search space)
[log_2022-12-05_13-51-46.txt](https://github.com/Nesvilab/FragPipe/files/10156332/log_2022-12-05_13-51-46.txt)
[log_2022-12-05_13-20-21.txt](https://github.com/Nesvilab/FragPipe/files/10156333/log_2022-12-05_13-20-21.txt)
[log_2022-12-05_16-52-20.txt](https://github.com/Nesvilab/FragPipe/files/10156334/log_2022-12-05_16-52-20.txt)
[log_2022-12-05_12-57-04.txt](https://github.com/Nesvilab/FragPipe/files/10156335/log_2022-12-05_12-57-04.txt)

**Comment by fcyu** [comment]
Thanks for your log file. I took a look at the first one and there are several issues
1. Your computer only has 8 GB free memory
2. You set several variable modifications:
```
variable_mod_01 = 15.9949 M 3
variable_mod_02 = 42.0106 [^ 1
variable_mod_04 = -17.0265 nQnC 1
variable_mod_06 = 0.984 NQ 1
```
Some of them were not necessary. You can remove -17 neutral loss, and also 0.984 deamidation. I don't think deamidation can be well detected in DIA data since it is very closed to the isotopic error. -17 neutral loss can be removed if your computer's memory is not enough. It won't hurt the result much.

If you still had out-of-memory error, you can also change the max occurrences of oxidation from 3 to 2 or 1.

3. You should not assign any experimental groups to your data since you want to build a single spectral library with all your data. You can do that by clicking "clear groups" in the "workflow" tab.

Best,

Fengchao

**Comment by RicZenChioz** [comment]
@fcyu one stupid question, how much ram should i need for real mixed DIA-DDA search? 
i have an  i7-12700k with 16GB of ddr5 ram. would a 32 be enough? 64? 
do you have like a rule of thumb x numer of files -> y GB of RAM

**Comment by fcyu** [comment]
It is hard to tell. Normally, if the computer's memory is 16 GB, there should be ~10 GB free memory available, which is enough for most of the searches without any additional variable modifications or semi/non-specific digestion. If you want to search more modifications, timsTOF data, or semi/non-specific digested peptides, 32 GB is recommended and 64 GB would be enough for almost all kinds of analysis.

Best,

Fengchao

**Comment by RicZenChioz** [comment]
hi @fcyu unfortunately it crashed also with basi settings

here are the logs
[log_2022-12-05_18-18-14.txt](https://github.com/Nesvilab/FragPipe/files/10156797/log_2022-12-05_18-18-14.txt)
[log_2022-12-05_17-49-28.txt](https://github.com/Nesvilab/FragPipe/files/10156798/log_2022-12-05_17-49-28.txt)

**Comment by fcyu** [comment]
This time, your computer even have fewer free memory: 6 GB. I think you should find a better one with more memory.

Best,

Fengchao
