### ISSUE TITLE
search for a single HexNAc modification

### ISSUE THREAD

**Issue by Chunyan-Hou** [Nesvilab/FragPipe#906]
- Describe the issue or question:

I am new to FragPipe and was trying to identify S/T modified with a single HexNAc. I used O-glycan workflow and set the mass offsets of 0 and 203.0794 (HexNAc) on S and T. In the psm result, the localization probabilities for HexNAc were low. I was wondering if I'd better use the default workflow with an additional variable modification of HexNAc on S/T. Do you think it would increase the number of modified S/T with higher localization probability? The fragger params file was attached for reference. Thank you.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[fragger.txt](https://github.com/Nesvilab/FragPipe/files/10157680/fragger.txt)

**Comment by dpolasky** [comment]
There are a couple of possible ways to search for HexNAc on S/T, but which is best depends on what kind of MS2 data are you searching (HCD, ETD, if you have paired scans, etc.) - what kind of data do you have? Can you also upload the full log from FragPipe? 

Thanks,
Dan

**Comment by Chunyan-Hou** [comment]
Hi Dan,

Thanks for reaching out. The data were obtained in HCD-pd-EThcD mode. Please refer to the log.
[log_2022-12-02_22-13-00.txt](https://github.com/Nesvilab/FragPipe/files/10197322/log_2022-12-02_22-13-00.txt)

Thank,
Chunyan

**Comment by dpolasky** [comment]
Hi Chunyan,
Thanks! HCD-pd-EThcD is great - you can actually use the new O-Pair localization mode that was just released with FragPipe 19 a few days ago to get the best results. It uses MSFragger to search HCD spectra to identify the peptide and O-Pair to localize the glycan(s) from the paired EThcD spectra. You can find it as the "glyco-O-Pair" workflow in FragPipe 19 (and edit the parameters to have the right mass offsets/diagnostic ions as you did before). It allows searching for multiple glycosites on the same peptide if you include multiple mass offsets in MSFragger search (e.g., 203, 406, etc for 1 or 2 HexNAc sites). 

PTMProphet has recently added support for labile modifications, but I am not sure how well it performs or if it can handle something as labile as HexNAc on S/T. I think the EThcD scans might be okay to localize with it (maybe just using c/z ions), but it's very unlikely there are enough location-specific ions in the HCD scans. I would recommend the O-Pair workflow for this sort of data instead.

Best,
Dan

**Comment by Chunyan-Hou** [comment]
Hi Dan,

Good to know. Thank you! I will update FragPipe and try the O-Pair workflow.

Best,
Chunyan
