### ISSUE TITLE
Methylation

### ISSUE THREAD

**Issue by ohovey5** [Nesvilab/FragPipe#909]
Hello FragPipe Team,

Our lab recently received a Methylbinder for enriching methylation peptides from our collaborator. I compared FragPipe, MaxQuant, ProteomeDiscover, PEAKs. FragPipe has given the least number of mono, di, tri-methylation sites than the other softwares (25 compared to 253). Is there preticular setting I should use or is FragPipe not optimized for these workflows? 

Cheers,
Owen

**Comment by fcyu** [comment]
Hi Owen,

It is hard to tell based on the limited information. Is it possible for you to share some data with us? I can create a Dropbox share folder if you need.

Best,

Fengchao
