### ISSUE TITLE
What is crystal-C?

### ISSUE THREAD

**Issue by jgmeyerucsd** [Nesvilab/FragPipe#91]
I noticed a new tab was added to Frag Pipe for some additional refinement by a program called Crystal-C - what is this program? Where can I find more information? Should we use it for nonspecific searches?

Thank you,
Jesse

**Comment by huiyinc** [comment]
Hi Jesse,

Crystal-C is a tool for removing artifacts from open search results. You could skip it if you are working on close research. For more information, please see: https://github.com/Nesvilab/Crystal-C.
Please feel free to ask if you have more questions.
Thanks.

Huiyin

**Comment by jgmeyerucsd** [comment]
Thanks
