### ISSUE TITLE
Can't pull current master because of git-lfs error

### ISSUE THREAD

**Issue by chhh** [Nesvilab/FragPipe#910]
- Describe the issue or question:
Trying to pull current master branch (FP 19.0 release) I get:
```bash
$ git checkout --track upstream/master
Updating files: 100% (329/329), done.
Downloading MSFragger-GUI/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so (498 MB)
Error downloading object: MSFragger-GUI/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so (bef4b84): Smudge error: Error downloading MSFragger-GUI/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so (bef4b84c08da403b651eea3a94676c7f83275068778bfafa2f95070ad9b1d478): [bef4b84c08da403b651eea3a94676c7f83275068778bfafa2f95070ad9b1d478] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it     
```

@fcyu Could you please re-upload this file: https://github.com/Nesvilab/FragPipe/blob/master/MSFragger-GUI/tools/diann/1.8.2_beta_8/linux/libtorch_cpu.so
According to this SO answer: https://stackoverflow.com/a/54433489/88814
This command might help: `git lfs push --object-id origin bef4b84c08da403b651eea3a94676c7f83275068778bfafa2f95070ad9b1d478`

**Comment by chhh** [comment]
@fcyu Or maybe just `git lfs push --all`

**Comment by fcyu** [comment]
Thanks @chhh. This LFS caused some trouble before and I somehow managed to fixed it. Maybe something was wrong when I reset the `master` branch this time.

Executed `git lfs push --all origin master`. Can you see if it fixed the issue?

Best,

Fengchao
