### ISSUE TITLE
FragPipe 19 identified significantly less diglygly peptides than 18 when processing ubi ddaPASEF data.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#912]
- Describe the issue or question:
FragPipe18 identified about 20000 diGlyGly peptides while 19 just identified 400 diGlyGly peptides.
log files have been uploaded.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-12-02_18-28-45.txt](https://github.com/Nesvilab/FragPipe/files/10173142/log_2022-12-02_18-28-45.txt)
[log_2022-12-05_16-57-15.txt](https://github.com/Nesvilab/FragPipe/files/10173149/log_2022-12-05_16-57-15.txt)

**Comment by fcyu** [comment]
Hi @andyzim111 

Two log files have difference parameters:
1. The version 19 one had fixed modification 229 on lysine, but the vesion 18 one didn't. This difference made a big difference.
2.  The version 19 one had PTMProphet enabled but the version 18 one didn't
3. Some other minor differences.

Can you rerun them with the same parameters?

Best,

Fengchao

**Comment by andyzim111** [comment]
I have removed the fixed modification 229 on lysine and rerun the analysis.
Because PTMProphet in FragPipe 18 does not support d. files, I can not enable PTMProphet in FragPipe 18.

**Comment by fcyu** [comment]
Then, you should also disable PTMProphet on FragPipe 19 for a fair comparison. But I don't think it would affect the peptide number.

Best,

Fengchao

**Comment by andyzim111** [comment]
After removal of the fixed modification 229 on lysine, FragPipe 19 identifies 17050 diGlyGly peptides with PTMProphet enabled, while Fragpipe 18 identifies 19545 diGlyGly peptides. 
Is this difference caused by PTMProphet?
Log file for FragPipe 19 is attached.

[log_2022-12-08_04-59-42.txt](https://github.com/Nesvilab/FragPipe/files/10182472/log_2022-12-08_04-59-42.txt)

**Comment by anesvi** [comment]
Please compare without PTMProphet in FP19. Do you get the same?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyzim111** [comment]
FragPipe 19 without PTMProphet: 16840 di-GlyGly peptides
FragPipe 19 with PTMProphet:17050
FragPipe 18: 19545
[log_2022-12-08_19-34-47.txt](https://github.com/Nesvilab/FragPipe/files/10191468/log_2022-12-08_19-34-47.txt)

**Comment by fcyu** [comment]
For FragPipe 19, with and without PTMProphet give the identical number of PSMs, peptides, and etc:

![image](https://user-images.githubusercontent.com/6926299/206616038-770f02e7-16e5-46ca-9226-e846f4a6b4fe.png)

Unless there are something I am not aware of, the di-GlyGly peptides should also be the same. Could you double check peptide counts? If you are sure that there is no error in your counting, could you share the result files with us?

For the comparison of FragPipe 18 and 19 without PTMProphet, there are many parameters having different settings, the biggest one is the FDR filtering:

![image](https://user-images.githubusercontent.com/6926299/206616269-9767359c-04c6-4233-90a2-c72528b4212d.png)

Could you make sure that the parameter are the same and compare the result again?

Best,

Fengchao

**Comment by andyzim111** [comment]
What files do you need?
I will change "picked" into "razor" and rerun it.

**Comment by fcyu** [comment]
psm.tsv

**Comment by fcyu** [comment]
> I will change "picked" into "razor" and rerun it.

FDR filtering is just one of the differences. Could you make sure that **all** shared parameters are the same?

Best,

Fengchao

**Comment by andyzim111** [comment]
The zipped PTM.tsv files are 50 M, how can I send you?

**Comment by anesvi** [comment]
I suggest you benchmark v 19 vs 18 using just one .d file. No need to use all data. It would make things much simpler, including sharing data

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fcyu** [comment]
@andyzim111 , please upload your files to https://www.dropbox.com/request/W7NZ07N3KClQuMe8DCm3

Best,

Fengchao

**Comment by andyzim111** [comment]
@fcyu, I have processed one d file using FragPipe 19 and 18 with the same workflow.

[18_psm.zip](https://github.com/Nesvilab/FragPipe/files/10205198/18_psm.zip)
[log_2022-12-12_13-41-08.txt](https://github.com/Nesvilab/FragPipe/files/10205201/log_2022-12-12_13-41-08.txt)
[log_2022-12-12_14-13-05.txt](https://github.com/Nesvilab/FragPipe/files/10205202/log_2022-12-12_14-13-05.txt)
[19_psm.zip](https://github.com/Nesvilab/FragPipe/files/10205209/19_psm.zip)

**Comment by anesvi** [comment]
I looked at the log files and PSM.tsv and the results looked very similar to me. I do not see any issue.

**Comment by fcyu** [comment]
Hi @andyzim111 ,

Thanks for your file. I took a look at your psm.tsv files, version 19 actually got more IDs than version 18 in terms of total PSMs (28477 vs 28347) and diglygly PSMs (15450 vs 15368). Thus, same as Alexey's conclusion, I don't see any issues.

Best,

Fengchao
