### ISSUE TITLE
fragpipe --headless (Fragpipe v18) stopped working when computer connected to internet.

### ISSUE THREAD

**Issue by wolski** [Nesvilab/FragPipe#913]
I am running fragpipe headles calling:

"c:/FragPipe/fragpipe_v18//bin/fragpipe.bat --headless --workflow c:/dummdummer/TMT11TestData/FragPipe_workflow.workflow --manifest c:/dummdummer/TMT11TestData/manifest.fp-manifest --workdir c:/dummdummer/TMT11TestData --config-msfragger c:/FragPipe/fragpipe_v18//tools/MSFragger-3.5/MSFragger-3.5.jar --config-philosopher c:/FragPipe/fragpipe_v18//tools/philosopher_v4.4.0_windows_amd64/philosopher.exe --ram 10"

and getting the error:

C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\/bin/java.exe
2022-12-07 10:25:07,555 ERROR - Does not appear to be an executable file: "c:\FragPipe\fragpipe\tools\philosopher_v4.4.0_windows_amd64\philosopher.exe"

Why is fragpipe looking for philosopher in an "old" location although I am explicitly passing the correct location with the "--config-philosopher" parameter.

I tried to fix the problem by deleting the cache files in "c:/FragPipe/fragpipe_v18/cache", but this did not solve the problem.
Are there other "cache" files I need to delete?

Thank you.

**Comment by wolski** [comment]
Thank you for looking into it.
Not that I know of. I am attaching the workflow file. (I had to add the txt suffix to be able to upload it to github).
[FragPipe_workflow.workflow.txt](https://github.com/Nesvilab/FragPipe/files/10178394/FragPipe_workflow.workflow.txt)

Maybe related observation: If I start the fragpipe_v19 GUI, it can see the path's I specified for fragpipe_v18
![image](https://user-images.githubusercontent.com/1926513/206247194-8818dcc1-5ff1-4ff0-9df6-06d1938cb33f.png)

Therefore, I was wondering if there is a global cache file in my home directory I must delete.

**Comment by fcyu** [comment]
Yes, there is a system level cache directory `%LOCALAPPDATA%\Temp\fragpipe`. You can also open the directory by clicking "open cache location" in the config tab.

In case you don't know, there is also a local cache directory in the fragpipe folder.

Can you delete the files in those two directories and try again?

Thanks,

Fengchao

**Comment by wolski** [comment]
How do I run two different versions of fragpipe on the same machine?

I have a project (A) running over a more extended period, with several related experiments,  which I started analyzing with FP v18. I want to continue to analyze it with the same version of the fragpipe (v18).
But I also have project (B), which started just recently, and I would like to analyze it with the latest version of fragpipe (v19).

Therefore, I would like to have two isolated installations of fragpipe on the same machine. 

It seems that, at the moment, this isn't possible because both versions share a single %LOCALAPPDATA%\Temp\fragpipe. Therefore, If I adjust the paths to the jar files for v19, this affects fragpipe 18 and the other way around.

Is there a way to support this use case with the current version of fragpipe, without docker or a second windows box, etc?

**Comment by fcyu** [comment]
You can change the cache folder using the approach in https://github.com/Nesvilab/FragPipe/issues/306

> Is there a way to support this use case with the current version of fragpipe, without docker or a second windows box, etc?

If you use FragPipe GUI, which is the easiest way to use FragPipe on Windows, you can. Just set two different cache folders for two versions, or specify/double check the paths of MSFragger, IonQuant, and Philosopher every time you start FragPipe.

Best,

Fengchao

**Comment by wolski** [comment]
The fragpipe --headless (v18) stopped working after the release of FragPipe v19. It still works when the computer is unplugged from the network. 

I did the following tests:

- I tested the fragpipe v18 on two windows machines. On both fragpipe, v18 did not work.
- Then I did run the same command line on the same data with FragPipe v19, and it did work, confirming that there are no errors in the workflow file or the other files.
- Then, we tested if fragpipe --headless (v18) would work when we unplugged the computer from the network. Without a network connection, the fragpipe --headless v18 did work.
-  Then we tested if fragpipe --headless v18 does work on Linux machines. On Linux, the fragpipe v18 also stopped working when the computer was connected to the internet.


The error I reported in the first comment is some random error thrown by "fragpipe.bat --headless" (v18)
For instance, I also have seen the following error:

```
C:\b_testfolder\MSV000084263>c:\FragPipe\fragpipe_v18\bin\fragpipe.bat --headless --workflow FragPipe_workflow.workflow --manifest manifest.fp-manifest --workdir .
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\/bin/java.exe
2022-12-09 09:27:25,436 ERROR - Could not read fasta file: "c:\FragPipe\fragpipe_v18\bin"
java.nio.file.AccessDeniedException: c:\FragPipe\fragpipe_v18\bin
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
```

I am attaching the workflow file for completeness.

**Comment by cpanse** [comment]
@wolski just turn of you windows network

**Comment by fcyu** [comment]
FragPipe pulls the information from the server and finds that there are new versions of MSFragger, IonQuant, and Philosopher available. Then, it displays balloon notifications on GUI mode or error messages on headless  mode. The GUI mode one can be closed and won't affect anything, but the headless mode one will stop FragPipe.

> @wolski just turn off you windows network

Unfortunately, this is the best solution so far. I apologize for the trouble, but I will change the error messages to warning messages, and not stop FragPipe headless.

Best,

Fengchao

**Comment by wolski** [comment]
So there will be a patch for FragPipe v19.
However, will there also be a patch for **v18**?
Or can I drop the fragpipe file from the V19 installation into the bin folder of my fragpipe 18 installations to replicate the results obtained with fragpipe v18?

**Comment by wolski** [comment]
Thank you for the patch. I installed it, and  FragPipe v 18 is working when the network is on.

```
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\/bin/java.exe
2022-12-12 10:44:06,478 WARN  - FragPipe update available, new version 19.0
2022-12-12 10:44:07,791 WARN  - Philosopher update available.
2022-12-12 10:44:09,971 WARN  - There is a newer version of MSFragger available [3.6].
2022-12-12 10:44:10,331 WARN  - There is a newer version of MSFragger available [3.6].
2022-12-12 10:44:12,481 WARN  - Philosopher update available.
2022-12-12 10:44:14,417 WARN  - The output directory is not empty. Some files might be overwritten in: c:\b_testfolder\MSV000084263
System OS: Windows 11, Architecture: ARM64
Java Info: 17.0.5, OpenJDK 64-Bit Server VM, Microsoft
```

**Comment by fstein** [comment]
Hi Fengchao,

could you possibly also update the FragPipe headless in a way that it does not exit if python or any of the python modules (such as easypqp) are not installed. Sometimes, I have problems to install the right python modules (pip fails sometimes). FragPipe headless does not even start, even in the case it does not need python.

Thanks a lot.

Best,

Frank

**Comment by fcyu** [comment]
Hi Frank @fstein ,

Sure. I will change the code and keep you posted.

Best,

Fengchao

**Comment by fcyu** [comment]
For the FragPipe 19, fixed in https://github.com/Nesvilab/FragPipe/commit/55c682d7716811a9b96b9fff0053c960e86d50f9.

For the FragPipe 18, please download the patch from https://www.dropbox.com/sh/52x7mtyobsudge0/AADRLPMvus8CIGbO4v1nMZhZa?dl=0

Best,

Fengchao

**Comment by fstein** [comment]
Thanks Fengchao for the quick fix. Could you maybe also release a patch for FragPipe 19?

Best,

Frank

**Comment by fcyu** [comment]
Hi Frank @fstein ,

Sure. Here is the link to download: https://www.dropbox.com/sh/97yqexmftiwb2kc/AACehcuZ3JUyzdufhf5Ypv_ta?dl=0

Best,

Fengchao

**Comment by fstein** [comment]
Hi Fengchao,

the patch for FragPipe 19 does still gives an error (when used in headless) if I want to use an old philosoper version. Since there is this bug of the duplicated TMT intensity columns, I need to use the old philosopher version. Could you maybe adjust this in a way that also FragPipe 19 does not stop any more when using old components?

Thanks a lot.

Best,

Frank

**Comment by fcyu** [comment]
Hi Frank,

FragPipe 19 needs Philosopher 4.6.0+ because some of the tools require the new functionalities in Philosopher. Felipe is fixing those bugs, and hopefully, we will release a new Philosopher shortly. 

Best,

Fengchao
