### ISSUE TITLE
Re-open FP-PDV of a previous search

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#928]
Hey all,

I really like the FP-PDV, and I've started using the standalone PDV viewer as well. It seems the FP-PDV is a bit more feature-rich, so I would prefer to use that to look at my data. However, as far as I can tell, it seems I can only view the most recent search with FP-PDV from the Run tab, and once I close that, I cannot re-open it. Is that true, or is there a way to open FP-PDV alone and open prior search results?

Also, I saw a past post on looking at open search results with FP-PDV, and having the unassigned modifications (DeltaMass column) annotated in the spectra just like the variable or fixed modifications are. It was mentioned this was available in a pre-release version of FragPipe. Is that feature going to be added to a new release soon, or would I be able to get access to the pre-release version?

Thanks!

**Comment by fcyu** [comment]
Hi @jossmi ,

You can open FP-PDV with the old results. Just specify the "output dir" to the result folder you want to open.

> Also, I saw a past post on looking at open search results with FP-PDV, and having the unassigned modifications (DeltaMass column) annotated in the spectra just like the variable or fixed modifications are. It was mentioned this was available in a pre-release version of FragPipe. Is that feature going to be added to a new release soon, or would I be able to get access to the pre-release version?

For this question, need Kai's @KaiLiCn help.

Best,

Fengchao

**Comment by KaiLiCn** [comment]
Hi,

Unfortunately, in the current version, the users can only assign the "delta mass" by 'check peptide' function under "Tool" button. I am working on a new function to assign "delta mass" in an easier way. But it's not a localization tool, so you still need to manually localize it. I will release the new version of FP-PDV [here](https://github.com/Nesvilab/FP-PDV/releases). 

Best,
Kai
