### ISSUE TITLE
Inappropriate settings resulted in 0 hypserscore PSMs, which broke the split script.

### ISSUE THREAD

**Issue by kgousset** [Nesvilab/FragPipe#930]
Dear FragPipe team,

I am getting a ZeroDivisionError when running a semi-specific search with multiple variable modifications using split database (set to 19) on a modified LFQ-MBR workflow.  This same search works fine with an enzymatic search.

This is timsTOF SCP data running on an AMD Ryzen 7 with 64GB of RAM.  Ran the same search on my AMD Ryzen Threadripper 2990WX with 128GB of RAM and got the same results (sorry I didn't save the log file for that run, but it gave the same error).

Thank you for your help.

[log_2022-12-15_06-40-45.txt](https://github.com/Nesvilab/FragPipe/files/10239726/log_2022-12-15_06-40-45.txt)

**Comment by fcyu** [comment]
It looks like there are 0 hyperscore PSMs in your data. May I ask why did you change "min frage modeling" and "min matched frags" to 1? It will make the e-value modeling suboptimal.

If you don't have a good reason, please use the default values.

Best,

Fengchao

**Comment by kgousset** [comment]
Thank you for your response.  

Someone (not from your team) told me that it would be more inclusive, but I would be more than happy to change it back if it would allow it to run.  Do you think that is the problem?  I thought I ran it once before changing those settings, and it errored out the same way, but I could be wrong.  I guess I can give it a try.

**Comment by fcyu** [comment]
> Someone (not from your team) told me that it would be more inclusive

It depends on how you define "inclusive". Setting them to 1 will have more PSMs **before** the FDR filtering, but might have fewer PSMs **after** the FDR filtering because the e-value modeling is not good.

> Do you think that is the problem? I thought I ran it once before changing those settings, and it errored out the same way, but I could be wrong. I guess I can give it a try.

I think so. Can you load the built-in "LFQ-MBR" workflow, adjust the enzyme and variable modification settings, and try again?

Best,

Fengchao

**Comment by fcyu** [comment]
Forgot to mention, after loading the built-in workflow, you also need to adjust the "split database" option in the MSFragger tab since your search space it large.

Best,

Fengchao

**Comment by kgousset** [comment]
Thank you again. I have it running now.  I will let you know how it goes.  Keeping my fingeres crossed.

**Comment by kgousset** [comment]
Hi,

I just wanted to let you know that the run completed after I changed the two values you suggested.

Thank you so much for your help.

Best,
Karine
