### ISSUE TITLE
lost ability to generate MSstats file in V19

### ISSUE THREAD

**Issue by lyons89** [Nesvilab/FragPipe#934]
In the new V19 release I am not able to check the box "Generate MSstats file" that's located at the bottom of the Validation tab, it's grayed out. I don't have any issues checking it with V18. Does not appear to be dependent on which workflow i load. Could it be an error with my installation?

Best,
Scott

**Comment by lyons89** [comment]
You're a genius FengChao, that did the trick!
Great job with the new release btw.

**Comment by fcyu** [comment]
Thanks for the kind words. Feel free to contact us again if you have any further questions.

Best,

Fengchao
