### ISSUE TITLE
Output file analysis

### ISSUE THREAD

**Issue by SharmaGautam1** [Nesvilab/FragPipe#935]
- Describe the issue or question:

I used the proteome xchange files PXD020556 for practice of LFQ-MBR (only six files as given on the tutorial page (https://fragpipe.nesvilab.org/docs/tutorial_lfq.html). I have to clarify few things:
1. In the multiple output files, which file do we have to take forward for LFR data analysis? I am considering combined_proteins.tsv. Is it right?

2.  Which intensity do we have to take forward? LFQ intensity or MaxLFQ intensity for analysis?

3. The output also have different folders for individual groups, like 3 controls and 3 aspirin. In those files, is protein.tsv file of each individual groups represents the proteins present in that particular group?

Please clarify as there is no such information in details on the tutorial page.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
> In the multiple output files, which file do we have to take forward for LFR data analysis? I am considering combined_proteins.tsv. Is it right?

Correct.

> Which intensity do we have to take forward? LFQ intensity or MaxLFQ intensity for analysis?

MaxLFQ intensity in most cases.

> The output also have different folders for individual groups, like 3 controls and 3 aspirin. In those files, is protein.tsv file of each individual groups represents the proteins present in that particular group?

Correct.

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Thanks for the clarification.

---
Best Regards
Gautam Sharma

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao
