### ISSUE TITLE
crash FragPipe v19

### ISSUE THREAD

**Issue by Angrist75** [Nesvilab/FragPipe#937]
I think Fragpipe cannot handle DIAs with windows, which are too wide. I am trying to repeat on my EvosepOne-FAIMS-Exploris 480 system the work of Erwin M. Schoof: "Enhancing single-cell proteomics through tailored Data-Independent
Acquisition and micropillar array-based chromatography." Spectronaut 17, DIA-NN 1.8.2 beta 11 smoothly handle the files I generated with great agreement with the results of the paper mentioned earlier. In contrast, when I reprocess the files with FragPipe v19 using DIAspecLib_Quant the software closes unexpectedly without giving errors. If needed I can share the raws.
Andrea

**Comment by fcyu** [comment]
I believe the data is from low resolution MS2. FragPipe might have slightly low sensitivity but it should not crash. Can you tell me the file name you used? I think I have all files from that publication downloaded.

Best,

Fengchao

**Comment by Angrist75** [comment]
sorry I misunderstood, the data are my own. they are not low resolution if you give me an address I will share them, or if there is any useful logs from FragPipe I can attach them in the next comment

**Comment by fcyu** [comment]
No worries. Here is the link to upload the files: https://www.dropbox.com/request/9wb5fgjearDLkFDLzNrN

You can also upload the log files starting with "log_".

Thanks,

Fengchao

**Comment by fcyu** [comment]
H @Angrist75 ,

I tried your data and FragPipe finished without any error. Please see my log file from [log_2022-12-18_21-35-52.txt](https://github.com/Nesvilab/FragPipe/files/10255478/log_2022-12-18_21-35-52.txt)

BTW, one possible mistake is that the files are in raw format. To let DIA-NN read the file, you need to install Thermo MS File Reader as warned by FragPipe:

![image](https://user-images.githubusercontent.com/6926299/208337002-6bf985d2-75bc-4f89-a945-d5422e5d96d3.png)

Best,

Fengchao

**Comment by Angrist75** [comment]
I'm afraid I discovered the problem and realized it was because of the settings of my Institute's antivirus software...Thanks for everything
Andrea
![Malware Detection Fragpipe](https://user-images.githubusercontent.com/63410174/208451503-1a3dd371-5050-4e5e-b22b-6115618cc3d0.png)

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
