### ISSUE TITLE
Experiment/Group - Dash converted to underscore

### ISSUE THREAD

**Issue by f-huber** [Nesvilab/FragPipe#938]
Dear Fragpipe Team, 

Just to let you know that I noticed in Fragpipe V19 that the Experiment/Group names provided in the maniifest files are renamed by changing "-" to "_" (using the headless version of fragpipe).

For example "Test-1" would be changed to "Test_1" as output folder.

This is not a real issue on our side, but I wondered if this an expected behaviour?

With best regards,

Florian

**Comment by fcyu** [comment]
Hi Florian,

Yes, I did it no purpose because some downstream tools don't like "-".

Best,

Fengchao

**Comment by f-huber** [comment]
Hi Fengchao,

perfect, thanks for the information!

Best regards,

Florian
