### ISSUE TITLE
Fragpipe: ERROR - Cannot get error message

### ISSUE THREAD

**Issue by MarcIsak** [Nesvilab/FragPipe#939]
- Describe the issue or question:

Hi! I get an error when I try to run fragpipe version 18.0 in headless mode inside a docker container with the following command:

fragpipe --headless --workflow workflows/testing_speclib.workflow --manifest /data/speclib_wf.fp-manifest --workdir /data/output_speclib

The resulting error does not help me to troubleshoot the error since it only says: 

2022-12-19 15:13:25,245 ERROR - Cannot get error message

I have managed to run fragpipe through the GUI inside the container, but I would need to get the CLI to work as well
for my application. 

I would be very grateful if you could help me troubleshoot this problem. 

Best regards,

Marc

- Upload your log file

To my knowledge, no log file created when I run this command.

**Comment by fcyu** [comment]
Hi Marc,

Can you try if the path from https://github.com/Nesvilab/FragPipe/issues/921#issuecomment-1344740105 works for you?

Best,

Fengchao

**Comment by MarcIsak** [comment]
Hi @fcyu!

Replacing the fragpipe-18.jar file with your new patch solved my problem! 

I am closing this issue now!

Thanks a bunch! 

Marc
