### ISSUE TITLE
MSstatsPTM output file

### ISSUE THREAD

**Issue by lyons89** [Nesvilab/FragPipe#940]
Sorry to bother you again Fengchao. I really like using MSstats and really appreciate the msstats output file you have fragpipe generate. I've seen in the past people have asked about support for [MSstatsPTM](https://github.com/Nesvilab/FragPipe/issues/536) and I wanted to ask about it again. I think the current issue I'm having is that the msstats.csv output for a TMT experiment doesn't seem to fill out the modifications column. I'm reluctant to bother you about this, and instead can also message the MSstatsPTM team and ask if they can create a fragpipe/philosopher converter using either the mstats.csv or psm.tsv output. 

Best,
Scott

**Comment by fcyu** [comment]
Hi Scott,

I think I need to clarify some technical details first. When enabling IonQuant for the LFQ-related analysis, the MSstats.csv file is generated by IonQuant, and the format can be read by the `dataProcess` function in MSstats. When performing the TMT analysis which IonQuant is not enable, the MSstats file is generated by Philosopher. You need to use the `PhilosophertoMSstatsTMTFormat` function to convert the format to MSstatsTMT data frame, then performing the analysis using the functions, such as `proteinSummarization`.

From your message, I believe you were talking about the TMT analysis, right? Then, I think need to let Felipe @prvst to take a look.

Best,

Fengchao

**Comment by anesvi** [comment]
Scott is asking about MSstatsPTM (not TMT) I think
So if using LFQ workflow, it would be done by IonQuant. If TMT, by philosopher

**Comment by prvst** [comment]
@fcyu I think he is asking about PTM not TMT

@lyons89 I haven't tested our outputs with MSatstPTM

**Comment by lyons89** [comment]
My apologies for not being more precise. I'm asking about MSstatsPTM for TMT data.

Thank you Fengchao for clarifying that IonQuant is exporting the msstats.csv for unlabeled data while philosopher is exporting it for TMT data.

**Comment by fcyu** [comment]
Yes, MSstatsPTM can be used for both TMT and LFQ data. I think I can make IonQuant LFQ support it in the future. 

Best,

Fengchao

**Comment by lyons89** [comment]
Is it normal to have the philosopher msstats.csv output not have any values in the Modifications column, or did I forget to do something?

Thank you,
Scott

**Comment by prvst** [comment]
The modifications column for now is empty because I'm preparing that one for the MSstatsPTM. For other Msstats, you need to use the Modified.Peptide column, which corresponds to the same field from the pep.xml file. An empty field means no modification, a naked sequence means static modifications, and sequences with brackets correspond to variable modifications.

**Comment by clairemsimpson** [comment]
I just want to second that having FragPipe generate a msstats.csv file that's compatible with MSStatsPTM (LFQ as well) would be really useful, and I'm glad to hear it's being worked on! It seems possible to run a MSStatsPTM analysis with the output given currently by taking some information from the msstats.csv file and file with modification data, but there are a couple of ambiguous points (e.g. should each row in the final table be a unique site or unique peptide?) and it would be great to have it done automatically.

**Comment by anesvi** [comment]
Good timing for your email. We are in a rush to get it working well before the USHUPO short course we are teaching with Olga’s team in three weeks.
Would you be able to explain in more details what we need to change, and we can discuss
 "e.g. should each row in the final table be a unique site or unique peptide"
You can contact me via email directly at nesvi   At med.umich.edu
Thanks!
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anesvi** [comment]
Ok, I started reading the MSstats docs myself
https://www.bioconductor.org/packages/release/bioc/vignettes/MSstatsPTM/inst/doc/MSstatsPTM_LabelFree_Workflow.html

and finally checked what we are actually generating. Yes, we need to have some discussions with the Msstats team, as I am not sure what they expect to see the input MSstats file, could be localized sites and converted to single site format (as all their examples show only single sites like P34876_S170) but that not how the data looks like initially: there could be many PSMs with the same sequence but different PTM configurations. How that is supposed to be summarized to the single site level for PTMs stats I am not sure.

Best,
Alexey

**Comment by fcyu** [comment]
We have made FragPipe fully support MSstatsPTM for DDA LFQ and DIA LFQ. Contact us if you want to try the pre-released version.

Best,

Fengchao
