### ISSUE TITLE
MSFragger Precursor mass tolerance

### ISSUE THREAD

**Issue by SharmaGautam1** [Nesvilab/FragPipe#941]
- Describe the issue or question:
Hi,
In the v19 Fragpipe, precursor mass tolerance is set as 20 PPM by default but in the manuscript (Fast Quantitative Analysis of timsTOF PASEF Data with MSFragger and IonQuant). it is set as 50 PPM.
Which one to go for LFQ analysis?

---
Best Regards
Gautam Sharma

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Gautam,

50 ppm was the old default value. Please use the latest value.

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
20 PPM, right?

**Comment by fcyu** [comment]
Correct,

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Thanks Fengchao.

Best Regards
Gautam Sharma
