### ISSUE TITLE
"MemoryError: bad allocation" in EasyPQP - Frapipe 19

### ISSUE THREAD

**Issue by JWLackmann** [Nesvilab/FragPipe#942]
- Describe the issue or question:
Cheers,
we recently updated to Fragpipe 19 and I wanted to generate a library for DIA runs using HpH fractions measured on a timsTOF Pro2. We did that multiple times on Fragpipe 16, but since updating to V19, I run into a "MemoryError: bad allocation" problem with EasyPQP. I can process the exact data successfully on V16 (so seems the files themselves are fine), but not on V19. I have RAM running on auto allocation, system has 256 GB available, though I also tried restricting it to e.g. 150 GB, same issue. Run in attached logs is limited to 24 parallelism, though I also tested it with more and less, same error. 
Best & thank you!
Jan

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-12-20_09-38-42.zip](https://github.com/Nesvilab/FragPipe/files/10266747/log_2022-12-20_09-38-42.zip)

**Comment by fcyu** [comment]
Hi Jan,

Can you also send us the log file from V16 where the job was done without any issue? 

To resolve the EasyPQP memory issue, can you try the workaround here: https://github.com/Nesvilab/FragPipe/issues/886#issuecomment-1317790507 ?

Thanks,

Fengchao

**Comment by JWLackmann** [comment]
Hi Fengchao,
sure, see attachment!
[log_2022-12-17_14-23-41.zip](https://github.com/Nesvilab/FragPipe/files/10269408/log_2022-12-17_14-23-41.zip)

**Comment by fcyu** [comment]
Hi Jan,

Thank you very much for the log file. It looks like two jobs had different amount of free memory. The successful one had 448 GB, while the crashed one had 217 GB. I guess that it the reason.

Best,

Fengchao

**Comment by JWLackmann** [comment]
Hi Fengchao,
448 GB free memory sounds a bit weird, as none of our systems have more than 256 GB...? Might be tie for an upgrade, though!
Anyway, I tried the workaround you linked and had everything processing with parallelization on 1 and it went through smoothly, thanks!

**Comment by fcyu** [comment]
> 448 GB free memory sounds a bit weird, as none of our systems have more than 256 GB...? 

I got this information from your log file:
```
MSFragger [Work dir: W:\HELA-24Frac-lib\output]
D:\software\FragPipe-jre-16.0\fragpipe\jre\bin\java.exe -jar -Dfile.encoding=UTF-8 -Xmx448G D:\software\FragPipe-jre-17.0\fragpipe\tools\MSFragger-3.4\MSFragger-3.4.jar W:\HELA-24Frac-lib\output\fragger.params W:\HELA-24Frac-lib\Hela_Lib_S2-A10_11-5-2022_16-33-12_6249.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A11_11-5-2022_17-21-37_6250.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A12_11-5-2022_18-10-01_6251.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A1_11-6-2022_11-43-16_6267.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A2_11-5-2022_10-05-44_6241.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A3_11-5-2022_10-54-09_6242.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A4_11-5-2022_11-42-37_6243.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A5_11-5-2022_12-31-01_6244.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A6_11-5-2022_13-19-28_6245.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A7_11-5-2022_14-07-57_6246.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A8_11-5-2022_14-56-21_6247.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-A9_11-5-2022_15-44-46_6248.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B10_11-6-2022_02-14-19_6261.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B11_11-6-2022_03-02-45_6262.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B12_11-6-2022_03-51-11_6263.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B1_11-5-2022_18-58-27_6252.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B2_11-5-2022_19-46-52_6253.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B3_11-5-2022_20-35-20_6254.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B4_11-5-2022_21-23-45_6255.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B5_11-5-2022_22-12-12_6256.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B6_11-5-2022_23-00-38_6257.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B7_11-5-2022_23-49-03_6258.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B8_11-6-2022_00-37-28_6259.mzML W:\HELA-24Frac-lib\Hela_Lib_S2-B9_11-6-2022_01-25-53_6260.mzML
MSFragger version MSFragger-3.4
Batmass-IO version 1.23.6
timsdata library version timsdata-2-8-7-1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
JVM started with 448 GB memory
```

> Anyway, I tried the workaround you linked and had everything processing with parallelization on 1 and it went through smoothly,

Glad to hear that the workaround worked for you.

Best,

Fengchao
