### ISSUE TITLE
Using mzML as input to decrease storage space needed

### ISSUE THREAD

**Issue by Skourtis** [Nesvilab/FragPipe#944]
Hi! 

I´m trying to analyse a very large number of DDA files ( more than 20 TB) and struggling with storage space for the thermo .raw files. I will reanalyse them with different fragpipe FDR settings/fasta files so processing and deleting the initial files isn't an option. I tried converting them to mzML through thermoparser to save space, but some mzML seem to get corrupted in the process and MSfragger finds no scans inside these files (while it works great with the original .raw files).

I noticed that MSfragger produces its own intermediate mzML files (filename_uncalibrated.mzML) and thought I could convert all raw file to mzML using MSfragger and then use these files as mzML input and delete the original .raw thus saving space. 

I noticed that while MSfragger is perfectly reproducible (at the pepXML level) starting from the same .raw file, if I instead use the uncalibrated.mzml I get very similar but not identical results. 

Would you suggest against using the MSfragger-produced mzml files as original input to MSfragger, or would that be acceptable?

Thank you,
Savvas

**Comment by danielgeiszler** [comment]
Hi Savvas,

1. Have you look at our guide for converting to mzML files? Do you still
have this issue when following these steps? This would probably be the best
solution.
https://fragpipe.nesvilab.org/docs/tutorial_convert.html

2. The parameter optimization step might choose slightly different
parameters if you give it slightly different files, which is probably where
this discrepancy is occurring. You should be able to reproduce your search
by checking “write calibrated mzML” in the MSFragger tab, looking at your
log file to see which parameters MSFragger chose for the search, disabling
parameter optimization and calibration, and reprocessing the calibrated
mzML files with the new settings.

Obviously the second option is more work, so the first option would be
better.

**Comment by Skourtis** [comment]
Thanks Daniel! I'll have a look at the second option since I'm running this on linux and wine is giving me some trouble for proteowizard.

**Comment by fcyu** [comment]
Hi Savvas,

If you want to use msconvert in linux, they have a docker image for it: https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses

Best,

Fengchao
