### ISSUE TITLE
Adding decoys in headless

### ISSUE THREAD

**Issue by pstew** [Nesvilab/FragPipe#945]
- Describe the issue or question:

Hello Fengchao and team, hope you are doing well. Can you please clarify if we need to add decoys to a FASTA database prior to running in headless mode? Is there an option for adding decoys to an existing FASTA in the workflow parameters somewhere? Is it possible to run in headless mode just for adding decoys to a database and nothing else, or should we make our own script for this? Does FragPipe do any sort of check to see if an existing FASTA already has decoys added? Thank you!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
> Can you please clarify if we need to add decoys to a FASTA database prior to running in headless mode? Is there an option for adding decoys to an existing FASTA in the workflow parameters somewhere? Is it possible to run in headless mode just for adding decoys to a database and nothing else, or should we make our own script for this? 

Unfortunately, no, since adding decoy is a one-time job and can be done easily on any computer.

> Does FragPipe do any sort of check to see if an existing FASTA already has decoys added? 

Yes, there is. 

Best,

Fengchao

**Comment by pstew** [comment]
Got it thank you very much.
