### ISSUE TITLE
Re-run MBR in IonQuant without complete quantification

### ISSUE THREAD

**Issue by palbanese** [Nesvilab/FragPipe#947]
Hi, 
is it possible to re-run the MBR top runs (default 10) without recalculating all quantindexes? i am searching 140 TIM-TOF files (>1TB) so it is quite demanding. can I just recalculate MBR varying this parameter? or I have to re-run all IonQuant tasks from scratch?

Thks!

Pascal

**Comment by fcyu** [comment]
Hi Pascal,

For the current version, no. I am overhauling some modules and it might be supported in the future version.

Best,

Fengchao
