### ISSUE TITLE
FragPipe headless stops working when new version available

### ISSUE THREAD

**Issue by Munchic** [Nesvilab/FragPipe#952]
Hello!

We use FragPipe headless in Linux HPC and noticed that when a newer version is available (e.g., MSFragger), FragPipe stops working even though all the versions are kept the same (e.g., it has been working until something was updated). Is there a flag in headless mode to ignore new version?

When processing a large number of runs, it would be nice to be able to search them all with the same version. Thank you for your help!

```
2022/12/12 04:35:35 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptacdev/panoply_fragpipe@sha256:41edb2434be1551cfdce0480ce62d0cf38cc908b27d16e1fa656533132a14eb7 /cromwell_root/script
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.43ce7eef
2022-12-12 04:39:31,843 ERROR - There is a newer version of MSFragger available [3.6].
```

Sincerely,
Munchic

**Comment by fcyu** [comment]
Duplicated issue: https://github.com/Nesvilab/FragPipe/issues/921

Please use the patch mentioned in https://github.com/Nesvilab/FragPipe/issues/921#issuecomment-1344740105

Best,

Fengchao

**Comment by Munchic** [comment]
@fcyu thank you!
