### ISSUE TITLE
MSBooster finished exit code:1

### ISSUE THREAD

**Issue by iolanda-vendrell** [Nesvilab/FragPipe#953]
Hi all, 
Recently when analysing DDA data, either acquired with Orbitrap or TIMS-TOF data, using the LFQ-MBR with the booster on i do get the error "MSBooster finished, exidt code 1. This never happened before. If I untick the MS booster, the search runs. 

This started happening more and less after i updated at the same time MSFragger to vs3.6, Philosopher v 4.4.0, python 3.9.12 and EASy/PQP  v0.1.34

Please find enclosed the log txt file and msbooster for TTF (tims-tof data) and fusion lumos (FL). 
Any suggestion on how to sort this out will be great. 

Many thanks in advance, 

best wishes, 

iolanda

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-12-08_14-42-21_TTF.txt](https://github.com/Nesvilab/FragPipe/files/10354913/log_2022-12-08_14-42-21_TTF.txt)
[log_2022-12-15_17-06-42_TTF.txt](https://github.com/Nesvilab/FragPipe/files/10354914/log_2022-12-15_17-06-42_TTF.txt)
[msbooster_params_TTF.txt](https://github.com/Nesvilab/FragPipe/files/10354915/msbooster_params_TTF.txt)
[msbooster_params - FL.txt](https://github.com/Nesvilab/FragPipe/files/10354923/msbooster_params.-.FL.txt)
[log_2022-12-19_09-05-41 - FL.txt](https://github.com/Nesvilab/FragPipe/files/10354924/log_2022-12-19_09-05-41.-.FL.txt)

**Comment by fcyu** [comment]
Hi Iolanda,

The FragPipe and Philosopher versions that you are using aren't compatible with the latest MSFragger. Can you upgrade them to the latest versions, and try again?

Thanks,

Fengchao
