### ISSUE TITLE
Error: did not find any PeptideProphet results in input data!

### ISSUE THREAD

**Issue by PrHamm** [Nesvilab/FragPipe#955]
[log_2023-01-07_18-24-30.txt](https://github.com/Nesvilab/FragPipe/files/10366831/log_2023-01-07_18-24-30.txt)

Hello!
I am a student very new to using FragPipe. Apparently there is a problem with Peptide/ProteinProphet. I get the error on most runs, but only on certain raw files, not all. I suspect that the problem has to do with the parameters set, not with the paths or with the fasta file. I can't figure out what to change, everything I've tried so far doesn't work. I would be very grateful for any help!
Many thanks!

**Comment by fcyu** [comment]
```
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
```

Your data has few ID, and PeptideProphet failed in modeling. Please check your enzyme and variable modification settings.

Best,

Fengchao
