### ISSUE TITLE
Native memory allocation (mmap) failed

### ISSUE THREAD

**Issue by EayonYang** [Nesvilab/FragPipe#956]
hello,all,
     I got an error about memory when I run 'MSFragger' function, so I turned up relevant settings that memory is 60G and thread is 30G, I stiil got memory error. I dont't konw how to deal with it. The attachment is eh running log.  Looking forward to your response. 

Good luck.

[log_2023-01-09_17-03-17.txt](https://github.com/Nesvilab/FragPipe/files/10374579/log_2023-01-09_17-03-17.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
It seems that your computer does not have 60 GB free memory but you still let Java to allocate that amount of memory by setting it to 60. Can you confirm that your computer has at least 60 GB free memory? 

Best,

Fengchao

**Comment by EayonYang** [comment]
I confirm my computer has enough ARM , because I use external mechanical hard disk with 2T storage space to run processes.

发自我的 iPhone

在 2023年1月10日，00:22，Fengchao ***@***.***> 写道：

﻿

外部邮件/External Mail




It seems that your computer does not have 60 GB free memory but you still let Java to allocate that amount of memory by setting it to 60. Can you confirm that your computer has at least 60 GB free memory?

Best,

Fengchao

**Comment by fcyu** [comment]
You should check the RAM/memory, not the storage space. Please consult your IT department if you are not sure.

Best,

Fengchao
