### ISSUE TITLE
java.lang.IllegalStateException: Something happened during database update

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#957]
Greetings,

I am trying to add decoys and contaminants to my protein database, but I am experiencing the below error. Please do advise me on how to troubleshoot. Thank you.

**20:34:36 ERROR: Something unexpected happened!
java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	... 1 common frames omitted**

Regards,
Parthiban

**Comment by fcyu** [comment]
Hi Parthiban,

Something was wrong when adding decoys. Could you please send me the screenshot of the console in the run tab?

Thanks,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Please refer below for screenshot.

![image](https://user-images.githubusercontent.com/69944967/211586938-80ad0edc-9027-4e3f-ad6b-a4038449fe7c.png)

**Comment by fcyu** [comment]
Thank you for the screenshot. Could you please run the following commands in the command console, and send me the output message?
```shell
D:\FragPipe-19.0\fragpipe\tools\philosopher_v4.7.0_windows_amd64\philosopher.exe workspace --clean --nocheck
D:\FragPipe-19.0\fragpipe\tools\philosopher_v4.7.0_windows_amd64\philosopher.exe workspace --init --nocheck
D:\FragPipe-19.0\fragpipe\tools\philosopher_v4.7.0_windows_amd64\philosopher.exe database --custom D:\Proteome_Databases\OpenProt\All\OpenProt_Mouse_20200901.fasta --contam --contamprefix
```

Thanks,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Please refer below for screenshot.

![image](https://user-images.githubusercontent.com/69944967/211591483-e1dcc7b5-5148-431c-9ebb-0b2b8bb1d40c.png)

**Comment by BenSamy2020** [comment]
Sorry please ignore the above image. Please refer to the below one:

![image](https://user-images.githubusercontent.com/69944967/211592875-3282c940-b948-475b-9e99-cd942cd0c0b1.png)

**Comment by fcyu** [comment]
Thank for your screenshot. It looks like the fasta file is no available. Can you double check?

Thanks,

Fengchao

**Comment by BenSamy2020** [comment]
Sorry,

![image](https://user-images.githubusercontent.com/69944967/211596391-e17363ae-5ebb-461b-931f-6904137f0ef6.png)

**Comment by fcyu** [comment]
Thanks for the update. It looks like everything worked well. I guess the reason of the original issue was due to the incorrect fasta path.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

But it is not working on the GUI.

![image](https://user-images.githubusercontent.com/69944967/211598158-2c6a7f74-4171-4d16-a63f-7e0347d512b9.png)

**Comment by BenSamy2020** [comment]
It works on cmd

![image](https://user-images.githubusercontent.com/69944967/211598364-7abfc939-e100-4637-b47b-ce97555b577e.png)

**Comment by fcyu** [comment]
Does the folder have both `OpenProt\All\OpenProt_Mouse_20200901.fasta` and `OpenProt\All\OpenProt_Mouse_20200901.fasta.fasta` ? If yes, can you delete the second me and try again?

Thanks,

Fengchao

**Comment by BenSamy2020** [comment]
Delected the fasta.fasta and it is still failing on the GUI and works on cmd.

I tested a uniprot file of ~20,000 sequences it worked fine. I think the OpenProt data is too big for the tool to handle...

Regards,
Parthiban

**Comment by fcyu** [comment]
I am not sure of the reason now. Can you share the fasta file with me? You can send it to yufe AT umich.edu

Thanks,

Fengchao

**Comment by BenSamy2020** [comment]
You can the download the file from here: https://openprot.org/p/download
with these options..

![image](https://user-images.githubusercontent.com/69944967/211600385-dc2412fb-0703-426b-90f1-45e3052d4929.png)

**Comment by fcyu** [comment]
Thanks. But I could not reproduced your error:
![image](https://user-images.githubusercontent.com/6926299/211601977-6d37bf25-0dcc-4c4a-817b-48a1f897f44a.png)

Best,

Fengchao

**Comment by fcyu** [comment]
I could not reproduce your error:

![image](https://user-images.githubusercontent.com/6926299/211602947-912ee629-d64e-4e43-b6a6-3e2b111dc261.png)

Best,

Fengchao
