### ISSUE TITLE
Not able to run DIA_SpecLib_Quant with own library

### ISSUE THREAD

**Issue by MRamirezGarras** [Nesvilab/FragPipe#958]
I have tried to run DIA_SpecLib_Quant with three different settings for the spectral library:
- 1 DDA file with a whole HeLa extract
- 16 DDA files with a fractioned HeLa extract
- my own library, created from the same 16 DDA files from the previous point

The first two options worked without problems, but when I try to do the last one the run finishes as soon as I press RUN. There is nothing in the log (either console or log file) and nothing in the output folder. If I name the experiments, then I get one folder with then name of each experiment, but all of them are empty. 

I am working with Bruker raw files (.d). The spectral library was created with Fragpipe using the same MSFragger settings, and I am selecting the file library.tsv for my runs (I assume this is the right one). 

These are the versions I have used:
FragPipe version 19.0
MSFragger version 3.6
IonQuant version 1.8.9
Philosopher version 4.7.0
Python version 3.9.13
EasyPQP version 0.1.35

**Comment by fcyu** [comment]
I could not reproduce this issue. Could you please share the log file with me? You need to upload the file to this issue page rather than replying the email.

Best,

Fengchao

**Comment by fcyu** [comment]
I guess something was wrong with your settings, but since there is no log file, I couldn't troubleshoot. 

When you using your own library.tsv, did you disable MSFragger, all validation tools, and spec lib generation? Did you specify your LC-MS file as `DIA`?

Best,

Fengchao

**Comment by MRamirezGarras** [comment]
> When you using your own library.tsv, did you disable MSFragger, all validation tools, and spec lib generation? 

Ups, I did not disable MSFragger and validation, thanks for the help.
