### ISSUE TITLE
MSFragger 3.6 not generating .mgf files causes issues with interact-pep.xml data upload into Skyline

### ISSUE THREAD

**Issue by tobimaile** [Nesvilab/FragPipe#960]
Hello FragPipe team:

I have an issue that per current changelog, the .mgf files are not generated anymore by MSFragger 3.6. 
Why are .mgf files not created in 3.6 anymore?
I am running DDA- and PRM-PASEF data on timsTOF instruments and now I have the issue that I can not upload my data on Skyline since the .mgf files are required. Is there a workaround to generate .mgf files for cases like this one?

Best regards,
Tobi

**Comment by fcyu** [comment]
Hi Tobi,

Thanks for your feedback. We will add an option to write mgf in the next release. It should be ready in a few days.

Stay tuned.

Best,

Fengchao

**Comment by tobimaile** [comment]
Great, thanks Fengchao!

**Comment by fcyu** [comment]
FragPipe 19.1 coupled with MSFragger 3.7 has the `write_uncalibrated_mgf` option now.

Best,

Fengchao

**Comment by tobimaile** [comment]
Hi Fengchao,

Happy Friday! Thank you for the quick response! I updated to 19.1 and am
running it now.

Best,
Tobi

Am Do., 12. Jan. 2023 um 18:41 Uhr schrieb Fengchao <
***@***.***>:
