### ISSUE TITLE
Ionquant 1.8.9 fails on converted Agilent QTOF data

### ISSUE THREAD

**Issue by justmpm** [Nesvilab/FragPipe#961]
- Describe the issue or question:  The new version of Ionquant is failing on Agilent QTOF data converted to .mzML using msconvert (v.3.0.23010 and v.3.0.21091)  It seems specific to Agilent data as .mzML files generated from thermo .RAW data with msconvert work fine.  The Agilent .mzML files will work on the previous version of MSfragger (3.5) and Ionquant (1.8).  
I have attached the log file here and the data files can be downloaded from here:  https://icgeborg-my.sharepoint.com/:u:/g/personal/myers_icgeb_org/EVSGm3Pa0aBEvlBLtg1lpFoBkWIwyAx-qf1I8fPGwfNu_A?e=a4AP5G

Thanks!

[log_2023-01-12_09-32-06.txt](https://github.com/Nesvilab/FragPipe/files/10399921/log_2023-01-12_09-32-06.txt)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Thank you very much for the bug report.

I have found and fixed the bug. The new version will be released this week.

Best,

Fengchao

**Comment by justmpm** [comment]
Thanks so much for your rapid response!

**Comment by fcyu** [comment]
Fixed in IonQuant 1.8.10.

Best,

Fengchao
