### ISSUE TITLE
Percolator: not enough features

### ISSUE THREAD

**Issue by kwebber3** [Nesvilab/FragPipe#962]
- Describe the issue or question:

Blanks have too few features and crash percolator. I have to remove them to get through the workflow.

- Upload your log file [log_2023-01-12_08-16-06.txt](https://github.com/Nesvilab/FragPipe/files/10403057/log_2023-01-12_08-16-06.txt)

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

ERROR: Reading tab file, too few features present.
No-terminate flag set: ignoring error and using a pseudo-feature of zeroes.
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid.

Process 'Percolator' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 131 remaining tasks
[log_2023-01-12_08-16-06.txt](https://github.com/Nesvilab/FragPipe/files/10403060/log_2023-01-12_08-16-06.txt)

**Comment by fcyu** [comment]
Thanks for the report. 

I guess Percolator couldn't read the empty pin file. I am not sure if it is easy for them to fix this bug, but I think the current workaround is removing the files as you have already done.

Best,

Fengchao

**Comment by kwebber3** [comment]
I was able to get it to work using peptideprophet. Changing minimum score to 0 didn't help either
