### ISSUE TITLE
TMT isotope correction factors?

### ISSUE THREAD

**Issue by pieeye75** [Nesvilab/FragPipe#963]
Hi,

I am trying to work out if FragPipe will allow me to put in the TMT isotope correction factors for a TMT 16-plex. I've had a good look around and I can't find anything. Am I missing something? I appreciate that if I treat all my samples in the same way the relative changes are comparable, but I like the idea of applying the correction factors.

thanks,

Peter

**Comment by josephineabighanem** [comment]
Hi, 
the question is marked as closed, but i couldn't find the answer.
So is there a way to define the TMT isotope correction factors? 
Thanks for the help
Josephine

**Comment by fcyu** [comment]
No, we don't support the isotope correct factors because we found that it did not significantly improve the results but made the tool harder to use.

Best,

Fengchao
