### ISSUE TITLE
TMT16 crash Philosopher/FreeQuant?

### ISSUE THREAD

**Issue by emhumphries** [Nesvilab/FragPipe#964]
Hi, I'm running the standard TMT16 workflow using mzML files and am getting the following error in both Fragpipe v19.0 and v19.1:
```
panic: Cannot decode packed binary. XML syntax error on line 1336144: unexpected EOF

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc0000296d0, 0x4d}, {0x12c10f5, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0x14392c0?, 0xc02006b338?}, {0x12c10f5, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/psi.(*IndexedMzML).Parse(0xc0007edbe0, {0xc000028fa0, 0x47})
	/workspace/philosopher/lib/psi/psi.go:115 +0x17b
philosopher/lib/mzn.(*MsData).Read(0xc0007ee2e0, {0xc000028fa0, 0x47})
	/workspace/philosopher/lib/mzn/mzn.go:194 +0x66
philosopher/lib/qua.peakIntensity({0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/workspace/philosopher/lib/qua/lfq.go:92 +0xd5d
philosopher/lib/qua.RunLabelFreeQuantification({{0x0, 0x0}, {0x0, 0x0}, {0x12c09d9, 0x4}, {0xc000020240, 0x35}, {0x0, 0x0}, ...})
	/workspace/philosopher/lib/qua/qua.go:47 +0xea
philosopher/cmd.glob..func6(0x2ebcca0?, {0x12c0935?, 0x6?, 0x6?})
	/workspace/philosopher/cmd/freequant.go:50 +0x29a
github.com/spf13/cobra.(*Command).execute(0x2ebcca0, {0xc0000be120, 0x6, 0x6})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2ebb2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
ERRO[11:28:12] Cannot decode packed binary. XML syntax error on line 1336144: unexpected EOF 
Process 'FreeQuant' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 84 remaining tasks
```

GitHub won't let me upload the files, so here's a link: https://drive.google.com/drive/folders/1yCXgmkRFu8oB0yIUHf19BU8URUEipzQ_?usp=sharing

**Comment by prvst** [comment]
This is a sign that you have a malformed, corrupted or invalid mzML file.

@fcyu This is another one of those cases where MSFragger could have flagged that early in the database search with a warning. You can see in the MSFragger log that something is not right with file VC-Cells-f56.

**Comment by fcyu** [comment]
@prvst I see that `VC-Cells-f56` has fewer scans than other runs. But it passed MSFragger's spectral file checking. Mass calibration, which read both MS1 and MS2 scans, and identification also finished without any error. Before taking a look at the mzML file, I can't see any issue in MSFragger. Maybe MSFragger is robust enough to process the corrupted mzML file. As to Philosopher, I have no comment since I am not the developer.

Best,

Fengchao

**Comment by emhumphries** [comment]
Yes, the mzML file was corrupted. Reconverting the file fixed the issue. Thank you for your help and rapid response.
Regards,
Erin
