### ISSUE TITLE
DIA raw files-mzml conversion

### ISSUE THREAD

**Issue by smahajan-CLS** [Nesvilab/FragPipe#965]
- Describe the issue or question:
Hi, I am converting the Thermo raw files to mzml format using the instructions provided on Fragpipe website using MSConvert. when I upload the mzml files generated, these are not recognized as DIA files but DDA files. I have created these files earlier and those works fine and when I upload the previously generated files those are recognized as DIA files. I am using the peak picking as first filter and demultiplex as second filter as raw files have staggered windows. Can you please advise? 
Thank you,
Best regards,
Shikha

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Shikha,

FragPipe does **not** detect the data type by reading the mzML file. It just **guesses** based on the file and folder name. So, the automatically assigned data type are likely to be incorrect. You need to adjust by yourself.

Best,

Fengchao

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

I have run it by adjusting it to the DIA_quant format and there were errors while running. I had run it with the files that I created 3 weeks ago using exactly same format and it recognizes those file as  DIA_files by itself that I adjust to DIA_quant and it ran smoothly.

As per the tutorial, The data type of each file should be automatically detected by FragPipe, check that these assignments are correct.

***@***.***

One of the errors that I encountered this time was the MSBooster which I deselected and ran again. Then I an into errors while generating/ reading spectral library from DDA files. I have ran it few times now and there are few errors that I am not able to complete the run.

Please let me know if you have any suggestions. I have not saved all the logs so I may rerun again and save  and send you the error files if needed.

Thank you,
Best wishes,
Shikha

**Comment by fcyu** [comment]
Can you upload the whole log file to this GitHub issue page or send it to yufe AT umich.edu?

Best,

Fengchao

**Comment by smahajan-CLS** [comment]
Sure. I am going to rerun and save any error log files and upload late  today.
Thanks,
Shikha

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

Please see the attached log files.
The first file shows the error when I upload the DDA files and DIA files (manually set us DIA_quant) and get the error with MSBooster.
Second error file is if I unselect the MSBooster and continue the run.

Please let me know if any other information is required.

Thank you,
Kind regards,
Shikha

**Comment by fcyu** [comment]
Hi @smahajan-CLS ,

GitHub truncates the file if you directly reply the email. Can you upload the whole log file to this GitHub issue page or send it to yufe AT umich.edu?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Shikha,

Two of your log files have been well received. Let me put it here as a reference.

For the MSBooster error, could you upgrade FragPipe, Philosopher, IonQuant, and MSFragger to the latest version and try again?

For the SpecLibGen error, you need to upgrade the tools. Also, you should assign all your files, including DDA and DIA ones, into a single experiment group, or just not assign any experiment group.

[SM_MSBooster_error_log_2023-01-18_09-01-33.txt](https://github.com/Nesvilab/FragPipe/files/10449182/SM_MSBooster_error_log_2023-01-18_09-01-33.txt)
[SM_SpecLibGen_error_log_2023-01-18_09-47-39.txt](https://github.com/Nesvilab/FragPipe/files/10449183/SM_SpecLibGen_error_log_2023-01-18_09-47-39.txt)

Best,

Fengchao

**Comment by smahajan-CLS** [comment]
Hi Fengchao,

I have upgraded FragPipe, Philosopher, IonQuant, and MSFragger to the latest version last week. So I’m not sure if that is the issue. Last time I processed this data successfully was in November last week/ December first week and it had the earlier version. I am using these versions now
C:\Users\Public\FragPipe-jre-18.0\fragpipe\tools\MSFragger-3.7\MSFragger-3.7.jar
C:\Users\Public\FragPipe-jre-18.0\fragpipe\tools\IonQuant-1.8.10.jar
C:\Users\Public\philosopher_v4.8.0_windows_amd64\philosopher.exe
C:\Anaconda\python.exe


Regarding the workflow, I have the following set up (all DDA files  as DDA and all DIA files individual names as in column 2 to be quantified with DIA_NN). Would you rather suggest to name as column 3 where all DIA files are named as single experiment or leave all as blank? If I leave them blank would it quantify each file as single sample?

1
2
3
4
5
Path
Experiment assigned
Should assign
data type
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_01_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_02_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_03_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_04_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_05_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_06_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_07_DDA.raw
DDA
DDA
DDA
D:\GBM_pg84_DDAfiles\07Dec22_Sample_SM_08_DDA.raw
DDA
DDA
DDA
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_01_DIA.mzML
SM_01_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_02_DIA.mzML
SM_02_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_03_DIA.mzML
SM_03_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_04_DIA.mzML
SM_04_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_05_DIA.mzML
SM_05_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_06_DIA.mzML
SM_06_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_07_DIA.mzML
SM_07_DIA
DIA
DIA_quant
manually adjusted
D:\GBM_pg85_DIAfiles\mzmlfiles\07Dec22_Sample_SM_08_DIA.mzML
SM_08_DIA
DIA
DIA_quant
manually adjusted


Thank you,
Shikha

**Comment by fcyu** [comment]
You are using FragPipe 18. The latest version is 19.1

You can lease all experiment group and bioreplicate blank by clicking "clear groups" in the workflow tab.

Best,

Fengchao
