### ISSUE TITLE
KeyError in msfragger_pep_split.py

### ISSUE THREAD

**Issue by jamc1996** [Nesvilab/FragPipe#966]
Hello,

Thank you for your work on MSFragger, I've really enjoyed using it.

I'm running into a strange error that I couldn't find in any previous issue. I was running MSFragger via FragPipe with small database on 3 raw files and it ran through perfectly. I then used the same raw files with a larger reference database and had to increase the "Split database" option to avoid running out of Heap space (according to https://github.com/Nesvilab/MSFragger/issues/186).

Now whenever I run with MSFragger with the split database I hit an error after MAIN SEARCH DONE that seems to be in python code fragpipe/tools/msfragger_pep_split.py where it gives a key error for SpecID in my data.

Thanks for your help.

Best wishes,
John.

**Comment by fcyu** [comment]
No response.
