### ISSUE TITLE
In relation to using data from Bruker timsTOF Pro, thanks for the help before christmas. Is it okay to search pasef data using, LFQ Phospho, Mass Offset Common PTM`S, and open workflows. Best Kieran

### ISSUE THREAD

**Issue by kwynne71** [Nesvilab/FragPipe#968]
- Describe the issue or question:

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Yes, FragPipe works well with the DDA data from timsTOF Pro. You can load the .d folder without any data conversion.

Best,

Fengchao

**Comment by kwynne71** [comment]
As i thought.
Thanks Again Fengchao.

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao
