### ISSUE TITLE
How to specify files in headless mode?

### ISSUE THREAD

**Issue by TTCooper-PhD** [Nesvilab/FragPipe#970]
I might have a basic question as the tutorial isn't clear to me on how to point to files (.raw or .mzML) within a specified directory. I understand setting up the manifest first in the GUI, but do I also load the files in the GUI before I save the experiment/manifest? 

In my case, I would like to use a specific experimental layout (i.e enzyme, missed cleavages, DIA setting) across multiple folders representing multiple experiments. 

Thank you in advance!!

**Comment by fcyu** [comment]
File paths and experimental groups can be specified in the manifest file. It is just a text file. To get familiar with the format, you can export an example manifest file in the GUI mode. Later, you can just edit that file.

Other parameters can be specified in the workflow file. You can also export the workflow file in the GUI file, which is the easiest way to get the file you want.

Best,

Fengchao

**Comment by TTCooper-PhD** [comment]
> File paths and experimental groups can be specified in the manifest file. It is just a text file. To get familiar with the format, you can export an example manifest file in the GUI mode. Later, you can just edit that file.
> 
> Other parameters can be specified in the workflow file. You can also export the workflow file in the GUI file, which is the easiest way to get the file you want.
> 
> Best,
> 
> Fengchao

Perfect. Thank you!
