### ISSUE TITLE
Broken Dropbox link in tutorial

### ISSUE THREAD

**Issue by csdaw** [Nesvilab/FragPipe#975]
- Describe the issue or question:

Hi there, I'm trying to follow the tutorial [Using a custom offset workflow with FragPipe: RNA crosslinking analysis](https://fragpipe.nesvilab.org/docs/tutorial_custom_mass_offset.html) which states the necessary files are in a 
Dropbox folder. However, the link is broken (just sends me to a "That didn't work for some reason" page).

I was wondering if you could make the tutorial files available some other way?

Thank you!

**Comment by fcyu** [comment]
Thank you very much for your report.

I believe that link was from Sarah's Dropbox folder, but her account has been expired. We will fix this shortly.

Best,

Fengchao

**Comment by Jmonod** [comment]
Hi Fengchao, 

Any update on the broken Dropbox link toward the unimod_20191002_RNAadducts.txt file ? It's still broken... 

Thanks !

**Comment by danielgeiszler** [comment]
[unimod_20191002_RNAadducts.txt](https://github.com/Nesvilab/FragPipe/files/11220670/unimod_20191002_RNAadducts.txt)

I have a copy of this file in particular that I can give you. However, I also want to let you know that this modification list is for a somewhat older protocol for RNA crosslinking and this modification list may not be generalizable to newer experiments. We recently used an RNA crosslinking dataset with a different technique to demonstrate our labile mode (below).

https://www.sciencedirect.com/science/article/pii/S1535947623000488

**Comment by fcyu** [comment]
We have updated the tutorials by adding new/more data. I planed to put it to GitHub soon.

Best,

Fengchao

**Comment by Jmonod** [comment]
Thanks Daniel and Fengchao. 

This is very convenient as we have a nice XRNAX dataset waiting to be analyzed. I will definitely consider implementing your freshly published method.

**Comment by Jmonod** [comment]
@danielgeiszler Would you be able to provide your XRNAX FragPipe workflow? It would be much easier than copying from your publication. 

Joe

**Comment by fcyu** [comment]
Fixed
