### ISSUE TITLE
PDV closes when trying to match with predicted MS2 spectrum

### ISSUE THREAD

**Issue by Soumyaiit019** [Nesvilab/FragPipe#979]
- Describe the issue or question:
Whenever I click the match peptide button to view the MS2 spectrum comparison with the peptide from the library.
No error files were generated. 
Currently using the Fragpipe 19.1 and the search finished without any problems. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2023-01-19_15-34-13.zip](https://github.com/Nesvilab/FragPipe/files/10494687/log_2023-01-19_15-34-13.zip)

**Comment by KaiLiCn** [comment]
Hi,

Could you please share your whole result folder and raw files with me? I will take a test on your result. You could upload the files here: https://www.dropbox.com/request/eGdPuVo952JZsz2sdUpE

Thanks!
Kai

**Comment by KaiLiCn** [comment]
Hi,

I received your files and I will take a test next week.

Best,
Kai

**Comment by fcyu** [comment]
@KaiLiCn , any updates?

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
Hi.

Sorry for the late reply. One tmp file is missed when the user select "Delete temp files" in "Run" panel. We have fixed it in the next release. But in the current version, you can fix it by unclick the "Delete temp files" option. 

![image](https://user-images.githubusercontent.com/29800230/226630785-cd041a43-20e3-40c9-bd86-70c0ceb463e8.png)

Kai

**Comment by fcyu** [comment]
The change of no deleting `spectraRT_*.tsv` has been pushed to https://github.com/Nesvilab/FragPipe/commit/6a81180cea6419da79cea0ecddf781732a46667d and https://github.com/Nesvilab/FragPipe/commit/036cb9a085b9755353fd2608f63e3cf1c2a1661a.

Best,

Fengchao
