### ISSUE TITLE
Change the special character separator in IonQuant

### ISSUE THREAD

**Issue by prvst** [Nesvilab/FragPipe#982]
I got a feedback from someone trying to use our tools, and having issues because one of the FASTA records actually has a `@` in the name. 

```
>tr|Q1RMN8|Q1RMN8_BOVIN Immunoglobulin light chain, lambda gene cluster OS=Bos taurus OX=9913 GN=IGL@ PE=2 SV=1
MAWSPLLLTLVALCTGSWAQAVLTQPSSVSGSLGQRVSITCSGSSSNIGRDNVGWYQQVP
GSGLRTIIYSSSSRPSGVPDRFSGSKSGNTATLTISSLQAEDEADYFCVAYDSSSSTVFG
SGTTLTVLGQPKSPPSVTLFPPSTEELNGNKATLVCLISDFYPGSVTVVWKADGSTITRN
VETTRASKQSNSKYAASSYLSLTSSDWKSKGSYSCEVTHEGSTVTKTVKPSECS
```

Please consider changing the special character separator

**Comment by fcyu** [comment]
Thanks for the feedback. In the next version, I will fix this issue by removing the dependency on the special character.

Best,

Fengchao
