### ISSUE TITLE
Pierce iRT not detected in DIA data. 

### ISSUE THREAD

**Issue by TTCooper-PhD** [Nesvilab/FragPipe#983]
I have spiked in a standard amount of PRTC (I believe) into my samples, however, I cannot get a successful run if the Pierce_iRT calibration option is selected. However, these runs are successful if I selected the default "select a run for calibration". 

Am I simply not using enough? or am I missing something altogether?

[log_2023-01-28_09-34-37.txt](https://github.com/Nesvilab/FragPipe/files/10527501/log_2023-01-28_09-34-37.txt)
[log_2023-01-28_09-09-43.txt](https://github.com/Nesvilab/FragPipe/files/10527502/log_2023-01-28_09-09-43.txt)

**Comment by fcyu** [comment]
Could you help to check if there are Pierce iRT peptides in the psm.tsv files? If not, could you upload your fasta file here?

Thanks,

Fengchao

**Comment by TTCooper-PhD** [comment]
Peptides aren't there. I think I am using the wrong FASTA file.

**Comment by fcyu** [comment]
Could you check the FASTA file? If it is correct, could you upload your FASTA file here?

Thanks,

Fengchao

**Comment by TTCooper-PhD** [comment]
2023-01-28-decoys-reviewed-isoforms-contam-UP000005640
[2023-01-28-decoys-reviewed-isoforms-contam-UP000005640.zip](https://github.com/Nesvilab/FragPipe/files/10527669/2023-01-28-decoys-reviewed-isoforms-contam-UP000005640.zip)


I searched it again and received the same error. I am wondering if PRTC is simply not detected in one of the CVs?

**Comment by fcyu** [comment]
I tested using your fasta file and found iRT peptides in my data, so I think it was due to the issue in your data, not the program.

Best,

Fengchao
