### ISSUE TITLE
Low IDs from the mzML file converted by a very old msconvert 

### ISSUE THREAD

**Issue by maggie0128** [Nesvilab/FragPipe#984]
Hello,
I am testing TMT16-phospho workflow, having trouble to get decent phosphosite numbers-say similar as proteome discoverer (PD). 19k single sites were identified in PD, yet only <100 in Fragpipe, using the same set of data. I am not quite sure what i have missed. Could you please help with this? I followed the tutorial here: https://fragpipe.nesvilab.org/docs/tutorial_tmt.html#quantification-settings.

thank you very much,
Maggie

**Comment by fcyu** [comment]
Can you upload your workflow file?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Thanks for your log file. As a reference, I moved it here [log_2023-01-29_19-34-26.txt](https://github.com/Nesvilab/FragPipe/files/10531704/log_2023-01-29_19-34-26.txt)

Something does not look right in your log file. Can you confirm that your data was labeled with TMT-16 and digested with trypsin? If yes, I might need to test using your mzML file with your fasta file. If you are willing to share your data, I can give you a link to upload.

Also, the fasta file name is `2023-01-24-decoys-human20307_mouserefseq_pd_download_clean_other_sepecies.fasta.fas`. Could you tell me if and why there are human+mouse proteins in your file?

Thanks,

Fengchao

**Comment by maggie0128** [comment]
Fengchao,

  Thank you for your prompt response! yes, my data is TMT16 and trytic digested. I searched against both human and mouse data base, so i combined human and mouse fasta files. I tested this fasta in PD and it works well. Sorry that i am not allowed to share data. You believe there might be something wrong on my mzML file? This is how i converted raw to mzML: something wrong?
![image](https://user-images.githubusercontent.com/123913715/215378506-b9385d43-1f78-4918-9d35-d3660bcdd035.png)

**Comment by fcyu** [comment]
Your msconvert seems to be from a very old version, which might not be compatible with Philosopher. Could you upgrade your msconvert to the latest version, reconvert the raw to mzML, and try again?

Thanks,

Fengchao

**Comment by maggie0128** [comment]
oops! I sure can try that tomorrow morning. If things work out, i will let you know. Appreciate your help!

**Comment by fcyu** [comment]
Or maybe that msconvert version is not too old. Since we don't have the mzML file, it is hard to locate the source of the problem.

Best,

Fengchao

**Comment by maggie0128** [comment]
Hi Fengchao,

  I tried the newest version of msconvert, and it worked well! Decent number was reported with new mzML file. Thank you very much for your help! I have a very quick question on newer version msconvert. Here is the parameters i used. Do i need to change the settings of <min SNR> or <min peak spacing> for different data-such as TMT, global, PTM, label free, etc? Or should i adjust the settings based on different instrument type?
![image](https://user-images.githubusercontent.com/123913715/215556093-fb74adf4-fe50-4b57-86a7-8cb4eed11982.png)

thanks,
Maggie

**Comment by fcyu** [comment]
Hi Maggie,

I am glad to hear that reconverting the data using the latest msconvert solved the issue. 

> Do i need to change the settings of (min SNR) or (min peak spacing) for different data-such as TMT, global, PTM, label free, etc? Or should i adjust the settings based on different instrument type?

No, you don't need to change anything. Adding the vendor peakPicking filter is good enough.

Best,

Fengchao
