### ISSUE TITLE
Philosopher 4.8.1 error caused by special character in fasta header

### ISSUE THREAD

**Issue by hollenstein** [Nesvilab/FragPipe#985]
Dear FragPipe team,

I've updated Philosopher to the latest version (4.8.1) and ran an LFQ workflow with some test samples. I got an error message caused by a special character in one of the FASTA headers. This error does not occur when running exactly the same workflow with philosopher 4.8.0. I also checked the [uniprot entry ](https://www.uniprot.org/uniprotkb/Q1RMN8/entry) for the gene that causes the problem and it seems that special characters like @ can actually occur in uniprot fasta headers.

**Error message**
```
D:\programs\fragpipe_19-1\tools\philosopher_v4.8.1_windows_amd64\philosopher.exe database --annotate D:\databases\combined\2023-01-27-decoys-2022.01_UP000005640_9606_Homo_sapiens_1protein_per_gene__2022.01_UP000002311_559292_Saccaromyces_cerevisiae_1protein_per_gene__contaminants.fasta.fas --prefix rev_
INFO[13:48:02] Executing Database  v4.8.1                   
INFO[13:48:02] Annotating the database                      
panic: The proteion record [tr|contam_Q1RMN8|Q1RMN8_BOVIN Immunoglobulin light chain, lambda gene cluster OS=Bos taurus GN=IGL@ PE=2 SV=1] contains an unsupported character: @. Please remove it before running philosopher again

ERRO[13:48:03] The proteion record [tr|contam_Q1RMN8|Q1RMN8_BOVIN Immunoglobulin light chain, lambda gene cluster OS=Bos taurus GN=IGL@ PE=2 SV=1] contains an unsupported character: @. Please remove it before running philosopher again 
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping
```

Maybe related to this error, as it also occurs with philosopher 4.8.1 and not with 4.8.0, I also get an error message when adding decoy entries to a fasta file. However, the .fas file seems to be generated correctly and contains the right number of decoy entries.

```
java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	... 1 more
```

Best regards and thanks for your help,
David

**Comment by fcyu** [comment]
Hi David,

The current version of IonQuant use `@` as the separator in a function, so the `@` in the fasta header breaks the program. That is why Philosopher check the fasta file and print the error. We will fix this issue in the next release.

Best,

Fengchao

**Comment by prvst** [comment]
@fcyu Are you planning to use something else, or can I just remove the checking rule for IonQuant ?

**Comment by fcyu** [comment]
I will change the algorithm to stop using any character as the separator. I think you can just remove the checking.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Fixed in the latest release.
