### ISSUE TITLE
DiMetylation quantification (TIMS-Pro data)

### ISSUE THREAD

**Issue by okleifeld** [Nesvilab/FragPipe#986]
Dear Fragger team.

Thank you for the helpful tool. 

We are using FragPipe to search and quantify N-terminal peptides data that was acquired with TIMS-Pro.

In this case the peptides were labeled with heavy and light dimethylation. The searches were conducted with MSFragger v19.0 using the Bruker timsTOF .d files. Heavy and light dimthylation modifications were set as variable modifications and quantification was carried out as described in the FragPipe SILAC tutorial: (https://fragpipe.nesvilab.org/docs/tutorial_silac.html). 

The search and quantification finished without any errors but we noticed that we obtained an unusually large number of singleton peptides that were identified only with one type of labeling (e.g. just light or just heavy) that were not quantified. While the large number of singletons is expected, it seems that in such cases when a peptide is identified by MS/MS only in the heavy form (or vice-versa) IonQuant is not "looking" for the parther MS1 peak.  

I would like to use this opportunity to ask if and how IonQuant is dealing with the ion mobility information in such MS1-based qualifications.

Can you please advise?

Thank you very much.

Oded 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2022-12-31_01-17-45.txt](https://github.com/Nesvilab/FragPipe/files/10536369/log_2022-12-31_01-17-45.txt)

**Comment by fcyu** [comment]
Hi Oded,

Details of the algorithm about the MS1 based quantification can be found from https://doi.org/10.1074/mcp.TIR120.002048 . For label quantification, IonQuant also uses the "requantify" strategy to look for the partner MS1 peak.

I can't find any obvious error from your log. If you can share some data with me, I can take a look.

Best,

Fengchao

**Comment by okleifeld** [comment]
Dear Fengchao,
I am happy to share our data. Unfortunately, our institute is not allowing us to open our FTP servers so my only option is to use Dropbox.
I can send you one of the .d files via Dropbox, would that work for you?
Best,
Oded


Oded Kleifeld Ph.D
Assistant Professor
Room 433/4 Biology Building,
Technion City, Haifa, Israel
Tel: +972 778871453
***@***.******@***.***> | https://<http://www.biology.technion.ac.il>oklab.net.technion.ac.il<http://oklab.net.technion.ac.il/>
[https://biology.technion.ac.il/wp-content/uploads/sites/33/2021/06/לוגו-אנגלית-משולב-עם-טכניון.png]

[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/TECH.png]<https://www.technion.ac.il/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/FB.png]<https://www.facebook.com/biologyf.technion>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/IG.png]<https://www.instagram.com/biologytechnion/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/YT.png]<https://www.youtube.com/channel/UCunuhqt7m9VE73ovrRNM86g/featured>

On 30 Jan 2023 at 17:06 +0200, Fengchao ***@***.***>, wrote:

Hi Oded,

Details of the algorithm about the MS1 based quantification can be found from https://doi.org/10.1074/mcp.TIR120.002048<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1074%2Fmcp.TIR120.002048&data=05%7C01%7Cokleifeld%40technion.ac.il%7Ca4049b14cb0e486ffeb408db02d3970a%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106880025023872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2vCC%2FBFb5im%2FQ4QU0xfzO0Hvuv9QmuMOWV4sbbxR6rE%3D&reserved=0> . For label quantification, IonQuant also uses the "requantify" strategy to look for the partner MS1 peak.

I can't find any obvious error from your log. If you can share some data with me, I can take a look.

Best,

Fengchao

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FFragPipe%2Fissues%2F986%23issuecomment-1408792238&data=05%7C01%7Cokleifeld%40technion.ac.il%7Ca4049b14cb0e486ffeb408db02d3970a%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106880025023872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rUESWuLIxxp50YqREqB7hDGIJXnxfMlAXC1ZWMSmNFM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXNVEUOM2QZZDX3O5JAR4OTWU7KH5ANCNFSM6AAAAAAULF3UWA&data=05%7C01%7Cokleifeld%40technion.ac.il%7Ca4049b14cb0e486ffeb408db02d3970a%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106880025023872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kHw%2FQUdjEDsqJnIcUKWO3MkKeSy1PSVDIzRHn43IqnE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

External e-mail, be judicious when opening attachments or links

**Comment by fcyu** [comment]
Hi Oded,

Thanks. Here is the link to upload the files: https://www.dropbox.com/request/WgquuzZWVjvU8fFH1CF8

Best,

Fengchao

**Comment by okleifeld** [comment]
Hi again,
I think the upload is now completed.
Please note that we our (expected) light N-term and K modifications are +28.0313 and the heavy ones are +34.061173.
BTW In the log files I don’t see the specification of the N-terminal dimethylation despite using the settings as shown in the tutorial.
Thanks,
Oded


Oded Kleifeld Ph.D
Assistant Professor
Room 433/4 Biology Building,
Technion City, Haifa, Israel
Tel: +972 778871453
***@***.******@***.***> | https://<http://www.biology.technion.ac.il>oklab.net.technion.ac.il<http://oklab.net.technion.ac.il/>
[https://biology.technion.ac.il/wp-content/uploads/sites/33/2021/06/לוגו-אנגלית-משולב-עם-טכניון.png]

[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/TECH.png]<https://www.technion.ac.il/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/FB.png]<https://www.facebook.com/biologyf.technion>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/IG.png]<https://www.instagram.com/biologytechnion/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/YT.png]<https://www.youtube.com/channel/UCunuhqt7m9VE73ovrRNM86g/featured>

On 30 Jan 2023 at 20:03 +0200, Fengchao ***@***.***>, wrote:

Hi Oded,

Thanks. Here is the link to upload the files: https://www.dropbox.com/request/WgquuzZWVjvU8fFH1CF8<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Frequest%2FWgquuzZWVjvU8fFH1CF8&data=05%7C01%7Cokleifeld%40technion.ac.il%7C7ed0ea9ba2eb416c56b008db02ec5956%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106986356748616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DxDD2prBIKIimTfSISGjmWDm8GqGZl9mwYZ69lU3WU0%3D&reserved=0>

Best,

Fengchao

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FFragPipe%2Fissues%2F986%23issuecomment-1409078150&data=05%7C01%7Cokleifeld%40technion.ac.il%7C7ed0ea9ba2eb416c56b008db02ec5956%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106986356748616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FpF9U%2Fut01CbQw0DHPYnc0nfjMm8V9JQeyS6D4%2BIt4U%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXNVEUOCZBZHL5OK3ZZBEA3WU77ARANCNFSM6AAAAAAULF3UWA&data=05%7C01%7Cokleifeld%40technion.ac.il%7C7ed0ea9ba2eb416c56b008db02ec5956%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638106986356748616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wtw3v7nlOskeeIOdsfBJK0ycctifEwpLfxpTEsNSyFs%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

External e-mail, be judicious when opening attachments or links

**Comment by fcyu** [comment]
Hi Oded,

Thanks for the update. I will take a look and keep you updated.

> BTW In the log files I don’t see the specification of the N-terminal dimethylation despite using the settings as shown in the tutorial.

I see that you have 

variable_mod_01 = 15.9949 M 2
variable_mod_04 = 34.063118 K 4
variable_mod_05 = 28.0313 K 4
**variable_mod_06 = 34.063118 n^ 1
variable_mod_07 = 28.0313 n^ 1**

Best,

Fengchao

**Comment by okleifeld** [comment]
Hi again,
Sorry I was not clear enough - I meant that I don’t see IonQuant specification for the N-term and in the log (with Ionquant marking all I see are the following lines (and I don’t see the N-term among them):
ionquant.heavy=K34.063117
ionquant.imtol=0.05
ionquant.ionfdr=0.01
ionquant.light=K28.0313
ionquant.locprob=0.75
ionquant.maxlfq=1
ionquant.mbr=0
ionquant.mbrimtol=0.05
ionquant.mbrmincorr=0
ionquant.mbrrttol=1
ionquant.mbrtoprun=100000
ionquant.medium=
ionquant.minexps=1
ionquant.minfreq=0
ionquant.minions=2
ionquant.minisotopes=2
ionquant.minscans=3
ionquant.mztol=10
ionquant.normalization=1
ionquant.peptidefdr=1
ionquant.proteinfdr=1
ionquant.proteinquant=2
ionquant.requantify=1
ionquant.rttol=0.4
ionquant.run-ionquant=true
ionquant.tp=0
ionquant.uniqueness=0
ionquant.use-labeling=true
ionquant.use-lfq=false
ionquant.writeindex=0

Thanks


Oded Kleifeld Ph.D
Assistant Professor
Room 433/4 Biology Building,
Technion City, Haifa, Israel
Tel: +972 778871453
***@***.******@***.***> | https://<http://www.biology.technion.ac.il>oklab.net.technion.ac.il<http://oklab.net.technion.ac.il/>
[https://biology.technion.ac.il/wp-content/uploads/sites/33/2021/06/לוגו-אנגלית-משולב-עם-טכניון.png]

[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/TECH.png]<https://www.technion.ac.il/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/FB.png]<https://www.facebook.com/biologyf.technion>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/IG.png]<https://www.instagram.com/biologytechnion/>[https://gustavo.webgr.technion.ac.il/wp-content/uploads/sites/59/2021/02/YT.png]<https://www.youtube.com/channel/UCunuhqt7m9VE73ovrRNM86g/featured>

On 30 Jan 2023 at 21:37 +0200, Fengchao ***@***.***>, wrote:

Hi Oded,

Thanks for the update. I will take a look and keep you updated.

BTW In the log files I don’t see the specification of the N-terminal dimethylation despite using the settings as shown in the tutorial.

I see that you have

variable_mod_01 = 15.9949 M 2
variable_mod_04 = 34.063118 K 4
variable_mod_05 = 28.0313 K 4
variable_mod_06 = 34.063118 n^ 1
variable_mod_07 = 28.0313 n^ 1

Best,

Fengchao

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FFragPipe%2Fissues%2F986%23issuecomment-1409225427&data=05%7C01%7Cokleifeld%40technion.ac.il%7C5aee51c3a2f94bc7bf9e08db02f9656d%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638107042399865674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0qENbRZCYWi3Gl29lk1qA1sFve57OJXSaHPhs00UMZE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXNVEUITOJA5EG4Z2D4FGDLWVAJ6ZANCNFSM6AAAAAAULF3UWA&data=05%7C01%7Cokleifeld%40technion.ac.il%7C5aee51c3a2f94bc7bf9e08db02f9656d%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C638107042400021886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kU9TN8wKIAkDYDElEep0%2BFaEqhCPk%2BuTibul2tIie4o%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

External e-mail, be judicious when opening attachments or links

**Comment by fcyu** [comment]
Oh, that could be the reason of getting many singleton peaks. Should set the light label as `Kn28.0313` and the heavy label as `Kn34.063117`. Let me test it using your data.

Best,

Fengchao

**Comment by okleifeld** [comment]
Hi Fengchao,
I just wonder if you managed to have a look at the data and the specific issue that I described. While this was observed with TIMS-Pro data, we see similar behaviour, also with data obtained with Thermo instruments using similar searches and workflow. It seems that no ratio is calculated for all the peptides that were identified just as in the heavy or just in the light form (at least based on the information shown in "combined_modified_peptide_label_quant.tsv" file).
Thanks,
Oded

**Comment by fcyu** [comment]
Hi Oded,

Yes, I took a look at your data and found no issue. 

To find the log-ratios from the light/heavy-only MS/MS identification, you need to locate the rows with blank "**PeptideProphet Probability**". The blank "Light/Heavy Modified Peptide" indicates that the corresponding MS1 peak was not found. See my following screenshot from your data:

From modified_peptide_label_quant.tsv
![image](https://user-images.githubusercontent.com/6926299/218269786-ef155b36-6919-4be7-9a62-7097102a181a.png)

Best,

Fengchao
