### ISSUE TITLE
Cannot use Percolator with ProteinProphet?

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#987]
I ran an open search of DDA data and selected CrystalC for cleanup and Percolator for PSM validation, with ProteinProphet activated for protein inference. FragPipe got all the way through Percolator, but crashed when trying to run ProteinProphet. Error pasted below.
My understanding was that PeptideProphet and Percolator were alternative options for PSM validation, the results of either of which can be passed on to ProteinProphet for protein inference. Is this not the case, or did I do something wrong elesewhere? Did I need to have "keep intermediate files" selected? I kept the default options of "--only-psms --no-terminate --post-processing-tdc". I've attached my log. 

Thanks!
Josh

Process 'Percolator: Delete temp' finished, exit code: 0
ProteinProphet [Work dir: D:\Data\2022\MaoX\WangN\221130\Data\MSFraggerSearch\TestRun1]
C:\FragPipe\FragPipe_v19.1\fragpipe\tools\philosopher_v4.8.1_windows_amd64\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined D:\Data\2022\MaoX\WangN\221130\Data\MSFraggerSearch\TestRun1\filelist_proteinprophet.txt
INFO[16:46:49] Executing ProteinProphet  v4.8.1             
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105101442-exported (Windows_NT-x86_64))
 (no FPKM) (no groups) (using degen pep info)
Reading in D:\Data\2022\MaoX\WangN\221130\Data\MSFraggerSearch\TestRun1\interact-JS_LI_CS_221130_MaoX_NW_S1_c.pep.xml...
panic: Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc00002a380, 0x6c}, {0x860dbc, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.ExecutingBinary({0x9d9600?, 0xc0001c8290?}, {0x860dbc, 0x5})
	/workspace/philosopher/lib/msg/msg.go:209 +0x6e
philosopher/lib/ext/proteinprophet.ProteinProphet.Execute({{0xc00007c300, 0x5b}, {0xc00007c360, 0x5c}, {0xc00007c3c0, 0x5c}, {0xc00007c300, 0x5b}, {0xc00007c360, 0x5c}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:110 +0x7d2
philosopher/lib/ext/proteinprophet.Run({{0xc00001e7e0, 0x24}, {0xc000020480, 0x3c}, {0xc000024690, 0x49}, {0xc0000246e0, 0x4b}, {0xc000024730, 0x42}, ...}, ...)
	/workspace/philosopher/lib/ext/proteinprophet/proteinprophet.go:62 +0x3b3
philosopher/cmd.glob..func14(0x245b740?, {0xc00007a140, 0x1, 0x
[log_2023-01-30_16-46-50.txt](https://github.com/Nesvilab/FragPipe/files/10540384/log_2023-01-30_16-46-50.txt)
5})
	/workspace/philosopher/cmd/proproph.go:26 +0xb4
github.com/spf13/cobra.(*Command).execute(0x245b740, {0xc00007a0f0, 0x5, 0x5})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x245c2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
ERRO[16:46:50] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 6 remaining tasks

**Comment by jossmi** [comment]
Also, is it possible to just run the Validation tab alone within FragPipe without re-running MSFragger? I'd like to just re-do my analyses with PeptideProphet, using the output from MSFragger, but the Workflow tab doesn't accept those files?

**Comment by fcyu** [comment]
I think you triggered the Percolator bug that all PSMs' PEP are 1, which result all PSMs' probability are 0. You have to switch to PeptideProphet for now.

> Also, is it possible to just run the Validation tab alone within FragPipe without re-running MSFragger? I'd like to just re-do my analyses with PeptideProphet, using the output from MSFragger, but the Workflow tab doesn't accept those files?

Yes, you just need to uncheck "Run MSFragger" in the MSFragger tab.

Best,

Fengchao

**Comment by jossmi** [comment]
Thanks!

**Comment by fcyu** [comment]
No problem.

Please feel free to contact us if you have any further questions.

Best,

Fengchao
