### ISSUE TITLE
Protein coverage Question

### ISSUE THREAD

**Issue by charlypavan** [Nesvilab/FragPipe#990]
- Describe the issue or question:
Dear FragPipe Team
I have a question about the output table protein.tsv. In the Protein coverage column:
For the following protein in green (image) I have 6 peptides ( this is almost 20 % cov) but the value is only 3.4.
Even if I consider only unique peptides, it should be more than 3.4%.
Any comment about this?
![MSFRagger](https://user-images.githubusercontent.com/118544713/216437425-0e64ed80-d17f-4b73-8add-5fe633aee076.png)

Thanks in advance,
Carlos

y drag & drop here.)

**Comment by fcyu** [comment]
It is calculated by Philosopher. Need Felipe @prvst to take a look.

Best,

Fengchao

**Comment by anesvi** [comment]
There was a bug, need to use the latest philosopher

But if you ARE using the latest philosopher, then we need to take a look

**Comment by charlypavan** [comment]
Thanks, It is not the latest version of philosopher.
I will try it and see.
Thanks for your help,
Carlos
