### ISSUE TITLE
error msg="Cannot decode packed binary. strconv.ParseUint: parsing \"76198\": value out of range"

### ISSUE THREAD

**Issue by thaumP** [Nesvilab/FragPipe#992]
Hi,

I am trying to run with a huge database and increase the FDR value. This was successful for many of the samples, but some of the sample runs were terminated. 

The error report is below

time="03:27:34" level=error msg="Cannot decode packed binary. strconv.ParseUint: parsing \"76198\": value out of range"
panic: Cannot decode packed binary. strconv.ParseUint: parsing "76198": value out of range

goroutine 21 [running]:
philosopher/lib/msg.callLogrus({0xc000038660, 0x53}, {0xb29f26, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0xc75980?, 0xc04af9a000?}, {0xb29f26, 0x5})
	/workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*PepXML).Parse(0xc0002d5a50, {0xc00027e3c0, 0x92})
	/workspace/philosopher/lib/spc/spc.go:63 +0x1c6
philosopher/lib/id.(*PepXML).Read(0xc000404000, {0xc00027e3c0, 0x92})
	/workspace/philosopher/lib/id/pep.go:207 +0x105
philosopher/lib/id.ReadPepXMLInput.func1(0x0, {0xc00027e3c0, 0x92})
	/workspace/philosopher/lib/id/pep.go:386 +0x105
philosopher/lib/id.ReadPepXMLInput.func2(0x0?, {0xc00027e3c0, 0x92})
	/workspace/philosopher/lib/id/pep.go:422 +0xa2
created by philosopher/lib/id.ReadPepXMLInput
	/workspace/philosopher/lib/id/pep.go:419 +0x978
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

Cancelling 4 remaining tasks

Thank you

[log_2023-02-04_03-27-34.txt](https://github.com/Nesvilab/FragPipe/files/10606705/log_2023-02-04_03-27-34.txt)

**Comment by prvst** [comment]
Can you share this one ? interact-P20220804469-meer-61-2-1_Slot1-27_1_861.pep.xml

Also, I see almost 2 million proteins in the inference. Care to give some details ?
