### ISSUE TITLE
PTMProphet failed when using "Split database" option in MSFragger  (FragPipe --headless mode)

### ISSUE THREAD

**Issue by liuxiaoxian** [Nesvilab/FragPipe#994]
- Describe the issue or question:

I had a workflow with multiple modifications that required using split database option in the MSFragger setting. But the FragPipe (--headless mode) failed in the PTMProphet step. Below is the error message: 

[ERROR:] cannot read scan in data file /my_work_dir/split_peptide_index_tempdir/20220808_AJ-Human-AJ001_FAIMS_calibrated.mzML exiting ...
Process 'PTMProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

Cancelling 6 remaining tasks

It seems that the calibrated.mzML file in the split_peptide_index_tempdir/ directory could not be found, so that the 'PTMProphet' step failed. The split_peptide_index_tempdir/ directory is the temporary folder generated by MSFragger, and would be removed when all MSFragger search finished. So when 'PTMProphet' processes  /my_work_dir/split_peptide_index_tempdir/20230104_AJ_FaimsOFF_028_run1_calibrated.mzML, the “cannot read scan in data file” error occurs, since there is no split_peptide_index_tempdir/ at all. Could you fix it? I appreciate your help!

[1078016.log](https://github.com/Nesvilab/FragPipe/files/10664685/1078016.log)

**Comment by fcyu** [comment]
Thanks for your bug report. I have reproduced it.

It seems that the split script copies calibrated.mzML to the `split_peptide_index_tempdir` folder and runs MSFragger, which causes the issue. For now, changing MSFragger's "calibration and optimization" to "none" can avoid this error.

Best,

Fengchao

**Comment by fcyu** [comment]
I have fixed this bug in

**Comment by fcyu** [comment]
I have fixed this bug in https://github.com/Nesvilab/FragPipe/commit/c874446ca78d0c092842a9420f64db62e29d93a0. If you want to have a try, please download the pre-release version of FragPipe from https://www.dropbox.com/t/2WlZfIwGdPTyvG4v

Best,

Fengchao
