### ISSUE TITLE
Is there a way to install FragPipe with conda?

### ISSUE THREAD

**Issue by NoeRzPz** [Nesvilab/FragPipe#997]
- Describe the issue or question: @fcyu
Hi Fengchao, 
I was wondering if my question is possible, to keep more in control all the package versions used. Many thanks in advance.
Kind regards,
Noelia

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
No, but we will release a docker image in the future.

Best,

Fengchao
