### ISSUE TITLE
Spectral library generation and filtering

### ISSUE THREAD

**Issue by pchirania** [Nesvilab/FragPipe#999]
Hi,

I am new to Fragpipe and trying to generate a spectral library from DDA PASEF data. I am using the DIA_SpecLib_Quant workflow with a few changes in the MS fragger parameters. I have a few questions about the spectral library generated at the end:

1. Would I need to / is it recommended to filter the search results (beyond what is present in the workflow by default) before input into easypqp for spectral library creation?
2. 
3. Would I need to / is it recommended to filter the final spectral library (library.tsv) file generated by the fragpipe workflow before use by DIANN for quantification of diaPASEF data?
4. 
5. What checks should one make to check the quality of the spectral library?

Please let me know if you need any other details. Looking forward to hearing back.

Thank you very much,
Payal

)

**Comment by fcyu** [comment]
Hi Payal,

Thanks for your interest in our tools.

> Would I need to / is it recommended to filter the search results (beyond what is present in the workflow by default) before input into easypqp for spectral library creation?

No, if you did not change the FDR filtering settings in FragPipe.

> Would I need to / is it recommended to filter the final spectral library (library.tsv) file generated by the fragpipe workflow before use by DIANN for quantification of diaPASEF data?

No, if you did not change the FDR filtering settings in FragPipe.

> What checks should one make to check the quality of the spectral library?

I am not sure what the quality checking you were referring to. But the entries in the spectral library have been filtered with 1% peptide and protein FDR. 

Best,

Fengchao

**Comment by pchirania** [comment]
Hi Fengchao,

Thank you so much for the super quick response, really appreciate it!!

I have the filtering criteria set as --picked --prot 0.01 (default).
So, I can be using the generated library.tsv file directly as DIANN input for quantification?

I also had a few clarification questions on the type of Fasta file used for searching and its impact on the spectral library- 

1. I used the UniProt human database of reviewed sequences with contaminants and decoys, downloaded via FragPipe - is that alright?

2. Would the generated spectral library have contaminants and decoys? Sorry about the naive question, I just want to be sure.

3. Lastly, would you recommend using the fasta files with isoforms for searching? Or how would it impact the resulting spectral file?

Thank you again,
Payal

**Comment by fcyu** [comment]
Hi Payal,

> So, I can be using the generated library.tsv file directly as DIANN input for quantification?

Yes.

> I used the UniProt human database of reviewed sequences with contaminants and decoys, downloaded via FragPipe - is that alright?

That is correct.

> Would the generated spectral library have contaminants and decoys? Sorry about the naive question, I just want to be sure.

It is actually not a naïve question. If you have "remove contaminants" enabled and the contaminants have `contam_` prefix, there will be no contaminants in the spectral library. If you have "removed contaminants" disabled OR the contaminants does not have `contam_` prefix, the spectral library would have contaminants.

> Lastly, would you recommend using the fasta files with isoforms for searching? Or how would it impact the resulting spectral file?

I would not recommend including isoforms in the searching. It would make the protein grouping hard.

Best,

Fengchao

**Comment by pchirania** [comment]
Hi Fengchao,

Thank you again for quick replies, this is very helpful!

I have "remove contaminants" disabled. However, I want to mark and keep the identified contaminants in the spectral library for DIANN searching as it does not additionally add contaminants. Is my thought process right?

Also, do contaminants have the "contam_" prefix enabled by default?

Lastly, I understand the issue with protein grouping. How would you recommend using isoforms if I have interested in identifying/quantifying specific isoforms for certain proteins?

Thank you again,
Payal

**Comment by anesvi** [comment]
>How would you recommend using isoforms if I have interested in identifying/quantifying specific isoforms for certain proteins?

I do not know myself after 20 years in this business how to do it well. Let us know when you figure it out!
Alexey

**Comment by fcyu** [comment]
> I have "remove contaminants" disabled. However, I want to mark and keep the identified contaminants in the spectral library for DIANN searching as it does not additionally add contaminants. Is my thought process right?

Correct.

> Also, do contaminants have the "contam_" prefix enabled by default?

If the fasta file is downloaded by Philosopher, yes.

Best,

Fengchao

**Comment by pchirania** [comment]
Hi Alexey,

Thank you for your reply. I understand your point :) Perhaps, I will start with adding only the isoforms for specific proteins I am interested in and create a separate spectral library for specialized searches. But, let me know if this approach concerns you in any way?

Best,
Payal

**Comment by anesvi** [comment]
Yeah, I was half joking and being a bit sarcastic, but it is big challenge. I think you would just want to stay at the peptide level for downstream analysis
See some discussions here
https://pubs.acs.org/doi/10.1021/acs.jproteome.1c00894
Alexey

**Comment by pchirania** [comment]
Hi Alexey,

:) Thank you for the tip and the paper - it is very helpful! 

Best,
Payal

**Comment by pchirania** [comment]
Hi Fengchao,

Thank you for the replies, these answer all the queries I had for now!! Thank you for the wonderful tools for DIA analysis!

Best,
Payal
